### ISSUE TITLE
StaticImageMedium returns wrong HTML tag?

### ISSUE THREAD

**Issue by chslion** [getgrav/grav#1001]
Hey Guys,

i have a .gif image and Grav renders it in an `<image>` Tag.
Problem lies in the StaticImageMedium class in line 26:
`return [ 'name' => 'image', 'attributes' => $attributes ];`
Shouldn't name actually be 'img' ?

-chslion

**Comment by flaviocopes** [comment]
That's weird. Can you paste the relevant parts of the markdown/twig code you used to get that image?

**Comment by chslion** [comment]
I just tried it with a fresh install of the latest Grav Release (1.1.3) and Chrome (Version 51.0.2704.79 Ubuntu 15.10) shows the `<image>` Tag in the html source.

I used the shipped welcome page with the following markdown

`
![Gif Image](foo.gif)
`

![source](https://cloud.githubusercontent.com/assets/5700605/17936070/de8d49b2-6a1d-11e6-9f8f-88fa0c9e4d32.png)

The Element Inspector changes the image tag to a valid img tag.

![inspector](https://cloud.githubusercontent.com/assets/5700605/17936074/e39fe4a0-6a1d-11e6-981f-6e75be8a0247.png)

**Comment by rhukster** [comment]
I can confirm this is a bug.. Never noticed because it is rendered fine in Chrome. BTW, in the future, you can submit a PR as you already had the fix :)  Cheers.
