### ISSUE TITLE
[add-resource] New Plugin Passwordgen

### ISSUE THREAD

**Issue by robgnu** [getgrav/grav#1003]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **https://github.com/robgnu/grav-plugin-passwordgen**

**Comment by rhukster** [comment]
@robgnu please create a GitHub **Release** with all the required files: https://learn.getgrav.org/advanced/grav-development#themeplugin-release-process

It won't show up in GPM until you do.  Cheers!

**Comment by robgnu** [comment]
@rhukster oh sorry - I'm new. I've created a release. I hope, everything is ok now.

**Comment by flaviocopes** [comment]
Make sure you update the release in the blueprint too https://github.com/robgnu/grav-plugin-passwordgen/blob/master/blueprints.yaml#L2 (create a 0.1.2 release
)

**Comment by robgnu** [comment]
@flaviocopes Thank you. The blueprint is corrected and a new release has been created.
