### ISSUE TITLE
some issues with image actions

### ISSUE THREAD

**Issue by simonhaenisch** [getgrav/grav#1006]
I had some issues with the quality image action and now I checked them all and I have problems with the following actions:

* `quality()` doesn't work
* `cropZoom()` doesn't work
* `flip()` always flips vertical, no matter what parameters are used (but needs two)

I tried it on two different websites, one hosted with Nginx and the other with Apache.

Is it just me having these issues or can you reproduce it?

**Comment by rhukster** [comment]
* `quality` works fine for me.. just try this: `![](image.jpg?quality=1)`
* `cropzoom` works fine for me too: `![](image.jpg?cropZoom=100,100)
* `flip` does appear to be broken as you say, but it's at the Gregwar library level from what I can tell.  i'll debug this further.

Please provide your image, and your markdown syntax you are using...

**Comment by rhukster** [comment]
Ok, standalone Gregwar test works fine with `flip` so must be an issue.. will get it sorted...

**Comment by rhukster** [comment]
Ok, it's because the params are being interpreted as strings. so "true" and "false" are both seen as a string, and therefore `true`.  It works if you use: `flip:0,1`.

I will update the docs accordingly

**Comment by rhukster** [comment]
closing this issue now.

**Comment by simonhaenisch** [comment]
Thanks for looking into it. What I did was include an image in a twig template, like

```twig
<img src="{{ page.route }}/{{ header.image}}?quality=25" alt="image">
```

and that doesn't work. Same for `cropZoom`. Flip works with `1` / `0`, and all the other action do work like that, too.

`quality` and `cropZoom` only work if I do it in the markdown file like in your example (the image is served from cache).
