### ISSUE TITLE
Allowed memory size exhausted with many "retina" images

### ISSUE THREAD

**Issue by simonhaenisch** [getgrav/grav#1009]
I just uploaded about 45 images with `@3x.jpg` into a page directory, which made Grav exhaust the 128 mb php memory limit. Some of the images were pretty large.

I think what happened is that Grav started creating all the lower quality images and that was too much. I resized and compressed the images and uploaded them again, then it took like 10-15 seconds when accessing the site after that for the first time, but it worked.

Would it be possible to process the images in another way so they don't all have to be in memory? Or only process images that are being included in the page?

**Comment by rhukster** [comment]
Really it's not something we can fix easily.  The main problem is that the GD library for PHP is not very efficient.  When resizing large images, it actually has to convert them to bitmaps in memory, so your 4mb JPG could become 50+mb in memory.  Doing this for 45 images x 2 for @2x and @1x is a lot processing and a lot of memory.

An option would be to use Imagick library which is a native library and is more efficient.  Unfortunately, the image manipulation library we use (Gregwar Image) only works with GD.  It would require changing to another library to provide Imagick support.

There is already an issue regarding replacing Gregwar, but it's a major change and potentially not backwards compatible, so it's not something that can be done lightly:

https://github.com/getgrav/grav/issues/983

Please comment on issue above if you have further questions/thoughts/ideas.

Cheers!
