### ISSUE TITLE
Assets not loaded when cache is compiled

### ISSUE THREAD

**Issue by namaless** [getgrav/grav#101]
<code>
cache:
    enabled: true
</code>
in the plugin i used inline js and js file, always not loaded:
<code>$this->grav['assets']->addJs('//maps.googleapis.com/maps/api/js?sensor=false');</code>
<code>$this->grav['assets']->addInlineJs($this->grav['twig']->twig()->render($template_js_main, $template_vars));</code>

**Comment by mahagr** [comment]
Yes, that is what is expected, really. You need to add the assets in a function that gets executed always, not just when you're on fresh content.

I know.. What we really should be doing is to cache assets object as well to make sure that assets rendered inside twig are also included.

**Comment by namaless** [comment]
Then I can't use this method to load assets from php?

**Comment by mahagr** [comment]
Looks like in your case you cannot as you are using a twig function. You need to find a workaround until the issue is fixed..

**Comment by rhukster** [comment]
Rather than Twig function, you should load the assets from the plugin class.  That way you won't have to deal with the issue of whether or not the content is cached, and the twig function is used or not.

**Comment by namaless** [comment]
Yes but some js data coming with twig function, i can't change this, the only way is add the js into html template but it's a bad way, but for now it's the only way...
