### ISSUE TITLE
Trying to get User ACL to work

### ISSUE THREAD

**Issue by blizam** [getgrav/grav#1010]
https://learn.getgrav.org/admin-panel/faq#managing-acl

in my user yaml I see

access:
 admin:
   login: true
   super: true

I want this user to have admin.pages

so I deleted super: true (also tried super: false)

and replaced it with

pages: true

and added

maintenance: true (tried it without as well)

and I crashed the matrix (see attached vid)
--basically I cannot login, though the error handling on this, when configured as stated above, appears broken

amIdoingitwrong?

note:
I did get this error in terminal on the password step of creating a new user

exec() has been disabled for security reasons in /[webroot]/public_html/vendor/symfony/console/Helper/QuestionHelper.php on line 445

but... I still was able to enter a password and complete the rest of the user creation process successfully 

I've also changed the admin route if that matters... I have no issues logging in with my primary admin.super account or when I set this new user to super: true

Grav v1.1.3 - Admin v1.1.4 

PHP 5.6.23, Apache, CentOS

[2016-08-26_18-49-07.zip](https://github.com/getgrav/grav/files/440717/2016-08-26_18-49-07.zip)

**Comment by rhukster** [comment]
First, this is an admin plugin question/issue, the place for those issues is: https://github.com/getgrav/grav-plugin-admin/issues, please use that project in the future :)

Second, I 'think' this might already be fixed in develop, as we had a fix for Ajax that was requiring `admin.super` and it shouldn't of.  Can you test with the **develop branch**?

**Comment by blizam** [comment]
Thanks for the quick reply, and noted on the correct repo... I'll take a look at testing with the develop branch this evening

**Comment by blizam** [comment]
Yes, using the Develop branch of the Admin Plugin has resolved the issue :)
