### ISSUE TITLE
Css/Js file loading optimization

### ISSUE THREAD

**Issue by aqwsez** [getgrav/grav#1011]
Hi

I'm currently using grav for a multisite setup.
My css and js files are currently being loaded from these type of urls:
/user/sites/[DOMAIN-NAME]/themes/[THEME-NAME]/css/style.css
Would it be possible to simplify them and make them look like this:
/themes/[THEME-NAME]/css/style.css

Even better would be if we could also bundle all the css and all the js files, uglify and compress them.

Thanks

**Comment by rhukster** [comment]
The most efficient way would be to use a webserver rewrite rule.

**Comment by rhukster** [comment]
If you turn on the CSS peipline feature it will combine and compress them and store them in `/assets` folder.

**Comment by aqwsez** [comment]
Thank you for the solution. The css pipeline and js pipeline are working very well. Is it certain that there won't be any naming conflicts? I have a multisite setup and every site will store its bundled js and css files in the assets folder. All the bundled files should have a unique filename, how is this filename being generated?

**Comment by rhukster** [comment]
https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Assets.php#L687

Basically filename is based on the content of the combined file. So unless those files are exactly identical they will have unique names. If they are identical then it's the same file so conflict is irrelevant.

**Comment by aqwsez** [comment]
Great work, thank you very much
