### ISSUE TITLE
write to cache with 775/664 permission (not images)

### ISSUE THREAD

**Issue by simonhaenisch** [getgrav/grav#1013]
Is it possible to setup Grav so that the files created in the `cache` folder have `775`/`664` permissions instead of `755`/`644`? I know it's possible to set it for images, but I haven't found an option for normal file cache.

I use a setup where PHP runs as `www-data` user and my user (for ssh) is in the `www-data` group. All folders have `775` and files have `664`. That way I can use GPM from either the admin panel or command line.

But when Grav writes some files to cache with `755`/`644` permissions, I can't use `bin/gpm` via command line until I fix the permissions of the `cache` directory. (I can use it, but I get permission errors when trying to install something)

**Comment by rhukster** [comment]
Have you set the 'sticky bit' (`+s`) and umask as per? https://learn.getgrav.org/troubleshooting/permissions#different-accounts-fix-permissions-manually

**Comment by mahagr** [comment]
I think we could add configuration setting for umask? Generally I would do this in PHP configuration, though.

**Comment by simonhaenisch** [comment]
I think I did the `+s` but not the `umask`. I'll try it, thanks.

**Comment by simonhaenisch** [comment]
I just got into this again and I don't think that the *sticky bit* or *umask* will solve my issue here.

The sticky bit makes sure that only the owner (me) can delete/rename files in a folder. I don't really see a reason to use it in this case as I'm not in a multi-user environment and don't have to worry about anyone messing with my files.

`umask` is only valid for the current session. To make it permanent I would have to set it in my `.bashrc` (which I already have). Could be useful to mention that in the docs. Anyway that is only for the files that I create with my user, but not for the files created by Grav/PHP.

I can set `umask 002` in my PHP config like @mahagr suggested, that makes sense.

**Comment by pascalrobert** [comment]
We have a similar issue, but with the images folder. Even if I have set the umask to 002 at the file system level, and in Apache, new directories in images are created with 755 instead of 775.

**Comment by Perlkonig** [comment]
Ditto, @pascalrobert. I haven't figured out whether it's a problem with my hosting setup or with Grav itself. No matter how I set umask, the contents of my `images` folder are always 755.

**Comment by pascalrobert** [comment]
Even with ACLs, when the folders are recreated, the effective rights don't have write permissions.

**Comment by rhukster** [comment]
Can you try somethign for me:

Create a file called `setup.php` in the root of your Grav install (alongside `index.php`) and put this:

```
<?php
umask(0022);
```

if you already have a setup.php, just add it to the top.  This file should get picked up and used for every Grav call.

**Comment by rhukster** [comment]
BTW, i'm assuming you have already tried the optional system setting:

```
images:
  cache_perms: '0775' 
```

**Comment by pascalrobert** [comment]
cache_perms: '0775'  was already set. Tried the trick with setup.php, didn't work.

I do notice something strange:

> images/0# umask -S
> u=rwx,g=rwx,o=rx

So umask is right, but:

> images# ls -l
> drwxr-xr-x 3 www-data www-data 4096 nov  2 09:40 0

Permissions are not what umask says it should be. This is on Ubuntu 12.04, the site is running under a LXC container.

**Comment by Perlkonig** [comment]
Doh! How did I not know about `cache_perms`? That appears to have fixed it! The umask in `setup.php` didn't work. Thanks!

**Comment by axelf** [comment]
HI,

is there any solution with the cache files? I have the same issue like @simonhaenisch and all solutions from the docs do not work (except running apache under the same user like the ssh user, but thats not an option for me). Cache files created by grav have only 644 and 755 permissions

**Comment by rhukster** [comment]
Did you try the setup.php solution i posted above???

**Comment by axelf** [comment]
@rhukster thank you, now it is working. I thought the setup.php was for the images :-) I searched 2 days for a solution, but now problem solved. Thank you again for the hint.

Could this be added to the documentation? In my opinion simple and nice solution

**Comment by rhukster** [comment]
I have it i the list of topics to document: https://github.com/getgrav/grav-learn/issues/356

**Comment by flaviocopes** [comment]
Added https://learn.getgrav.org/troubleshooting/permissions#cache-folder-permissions
