### ISSUE TITLE
[add-resource] grav-plugin-bibliography

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1014]
I would like to add a plugin to the Grav Repository, here are the project details: [grav-plugin-bibliography](https://github.com/OleVik/grav-plugin-bibliography).

**Comment by rhukster** [comment]
Nice, will get this added shortly.

**Comment by rhukster** [comment]
Added to GPM

**Comment by rhukster** [comment]
@OleVik this needs a release:

```
OleVik/grav-plugin-bibliography         No Release Found
```

**Comment by OleVik** [comment]
Sorry, I forgot to make one in the process, done it now.
