### ISSUE TITLE
Retina images in combination with manual derivatives

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav#1016]
I want to generate srcset attributes for the images I'm using so that they both scale down on small displays and up on retina displays. Grav's methodology for this seems logical enough, in a first sweep I appended "@2x" to the filenames, to get it working on retina displays. That worked fine. Then I wanted them to scale down as well, so I manually called the `derivatives` method as well. This made the images scale down on mobile, **but** it also put a limit on the maximum width, so that the largest source only had half the width of the original image.

I'm not sure exactly where the flawed logic is here, but it seems to be in how the combination of `$alternatives` and `$derivatives` is treated in the `srcset` method of the `ImageMedium` class (see [here](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Medium/ImageMedium.php#L207-L221)).

The `$alternatives` array should probably either be emptied if we use the derivative method manually, or srcset shouldn't work exclusively with either the `$alternatives` array or the `$derivatives` array

**Comment by rhukster** [comment]
This is a bit gnarly and it's super hard to debug on my non-retina display.  I really need a new computer!

**Comment by fredrikekelund** [comment]
The problem should be reproducible anyway, even if the difference is hard to tell. Here's how I encountered the issue:
1. Add a wide picture, 2500px in my case
2. Append "@2x" to the filename
3. Call the derivatives method in the twig template like `derivatives(500, 2500, 500)`
4. Check the srcset attribute, the widest version of the image will be just 1250px, half of the original image

**Comment by rhukster** [comment]
I've added a Hacktoberfest tag to see if we can get some help with this as I'm a bit stretched with other things at the moment.

**Comment by fredrikekelund** [comment]
This one is hopefully addressed by my PR, so I think we just need to iron that issue out to be able to close this. Maybe this isn't that much of low hanging fruit either

**Comment by fredrikekelund** [comment]
Pregenerated alternatives and alternatives that are generated using ImageMedium#derivatives now use the same underlying method, which should make things more predictable.
