### ISSUE TITLE
Antimatter: The little menu icon is late appearing when shrinking the window size

### ISSUE THREAD

**Issue by Neshraghi** [getgrav/grav#1017]
I have quite a few menu headings that stretch across the top of the page.
When I reduce the page size, the normal menu doesn't reduce to the menu icon soon enough – the whole of the normal menu disappeared.
When reduced even further, the menu icon does appear and the normal menu disappears.
How can I make it that the normal menu disappears as soon as the left most item in the normal menu bumps into the logo/site title?

**Comment by rhukster** [comment]
Screenshot please :)  Also maybe this should be opened in Admin plugin? https://github.com/getgrav/grav-plugin-admin/issues

**Comment by w00fz** [comment]
Thanks for opening in https://github.com/getgrav/grav-theme-antimatter/issues/74
