### ISSUE TITLE
Error when bin/grav install is run from GitHub clone

### ISSUE THREAD

**Issue by bennettscience** [getgrav/grav#102]
I tried installing Grav straight to my web directory via SSH today and got the following error in the terminal when I tried to run `bin/grav install` to get the dependencies:
```
bin/grav install
Status: 500 Internal Server Error
Content-type: text/html

Preparing to install vendor dependencies...

Status: 404 Not Found
Content-type: text/html

No input file specified.
No input file specified.
```

I grabbed the ZIP file and got it running okay, but I figured I should file the issue anyways. Not sure what I did wrong (if anything).

**Comment by rhukster** [comment]
Where did you run `bin/grav` from? What OS are you on? Your code example looks like it's trying to load a webpage which is weird, because this is a CLI command that should be run from a terminal/console.

**Comment by rhukster** [comment]
let's take this to the forums :)

**Comment by brettdewoody** [comment]
The [docs](http://learn.getgrav.org/advanced/grav-cli) have been updated with a fix for this.

If you run `php -v` and see `cgi-fcgi` then you need to prefix all `bin/grav commands` with `php-cli`.
