### ISSUE TITLE
Modular Page Issue

### ISSUE THREAD

**Issue by oxideorcoal** [getgrav/grav#1021]
I created a base theme from the devtools plugin, and I'm trying to make a single, modular page. However, when I go to load the site in my browser I'm getting no content, aside from the default nav bar and footer. I'm 95% sure that my `page` directory structure is correct, because when I switch to a different theme (I've tried Antimatter and Bones) I see my page content as I'm supposed to.

The only things I've done so far after downloading the base theme are:

1. create `modular.html.twig` in the `template` directory with the following content:

```
{% extends 'partials/base.html.twig' %}

{% block content %}
    {{ page.content }}
{% endblock %}
```

2. Create a directory called `modular` in the `templates` directory with the 4 files that correspond to the Markdown files in the `pages` directory

Screenshot of my `theme` directory:

![image](https://cloud.githubusercontent.com/assets/19677540/18222852/559b2ef6-7172-11e6-94d9-920280b38944.png)

All of the files in the `modular` directory have the same content (as this is my first time making a modular page and wanted to test it):
`<h1> {{ page.content }} </h1>`

EDIT:
I just tried making a base theme again using devtools, and now this is happening:
![image](https://cloud.githubusercontent.com/assets/19677540/18222917/14d4c506-7174-11e6-9fab-f00a0982c963.png)

**Comment by flaviocopes** [comment]
What's the content of your `modular.html.twig` page? 

Also, what is your pages folder structure? is the home page a modular page?

**Comment by oxideorcoal** [comment]
The home page is indeed a modular page. The contents of my modular.html.twig page is in my OP, and my page folder structure is:

![image](https://cloud.githubusercontent.com/assets/19677540/18224894/28aa9bac-71b3-11e6-8ccb-a4ff173a228c.png)

**Comment by flaviocopes** [comment]
Ok the problem is modular.html.twig (missed it!) - copy it over from Antimatter. It must loop the child pages. Otherwise all it does is output the modular.md page markdown content.

**Comment by oxideorcoal** [comment]
@flaviocopes Fantastic! Thank you SO much.
