### ISSUE TITLE
[remove-resource] Delete Plugin

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav#1025]
In Issue #1022 I added a plugin called `geoplugin` that geolocated using a single service. I later realized I should expand it to incorporate any service. In Issue #1024 I submitted the updated plugin `iplocate`. Please delete (or whatever you do) the older plugin `geoplugin`. This new one includes it but also replaces it.

Sorry for the churn!!!

**Comment by rhukster** [comment]
removed...
