### ISSUE TITLE
Markdown Extra breaks Twig

### ISSUE THREAD

**Issue by hansvana** [getgrav/grav#1026]
On a Twig-enabled page I use the following code:
`<a href="{{ page.url }}">{{ page.title }}</a>`
Which outputs something like
`<a href="my-page">My page</a>`
Which works fine, until I enable Markdown Extra on my site through the Admin panel.
After that, the output changes to
`<a href="%7B%7B%20page.url%20%7D%7D">My page</a>`
So {{ page.title }} still works, but {{ page.url }} breaks, I'm guessing because of the quotes.

Full (redacted) page code: [http://pastebin.com/GUFehkgr](http://pastebin.com/GUFehkgr)

**Comment by w00fz** [comment]
Have you tried enabling `twig_first`?  [More details here](https://learn.getgrav.org/content/headers#process-twig-first)

**Comment by rhukster** [comment]
I can't replicate this.. Here's what I have

main page:

    ---
    title: Markdown Extra breaks Twig #1026
    process:
        twig: true
    markdown:
        extra: true
    content:
        items: @self.siblings
        order:
            by: date
            dir: desc
        limit: 10
        pagination: true    
    ---
    
    {% for p in page.collection %}
     <div><h3>{{ p.title }}</h3></div>
     {% for c in p.children %}
      <a href="{{ c.url }}">{{ c.title }}</a>
     {% endfor %}
    
    {% endfor %}

Then this folder structure:

![grav-demo-sampler 2016-09-06 08-31-27](https://cloud.githubusercontent.com/assets/1084697/18277627/580a373a-740c-11e6-86aa-509631bb8bc1.png)

The output looks fine:

![markdown extra breaks twig grav 2016-09-06 08-31-59](https://cloud.githubusercontent.com/assets/1084697/18277637/656f5bb2-740c-11e6-8612-d4961938e55b.png)

And source too:

![markdown-extra-breaks-twig-1026 2016-09-06 08-32-47](https://cloud.githubusercontent.com/assets/1084697/18277675/81afb9de-740c-11e6-89ea-4046ddf08f26.png)

My guess is you have another plugin interfering.  So which plugins do you have installed?

**Comment by hansvana** [comment]
Sorry for the late response. 'Process Twig First' fixes this problem.
