### ISSUE TITLE
Install missing vendor dependencies in plugins with bin/grav install

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav#1028]
Hello!

I exclude all `vendor` folders from my Grav repo with putting line `vendor/` in my `.gitignore` in root folder. It brings some issues with installing repo in other computer just because `composer install` or `bin/grav install` creates `vendor` only in root folder.

Now I'm using this command in console:

```
find . ./user/plugins/ -name composer.json -maxdepth 2 -execdir composer install \;
```

Works good in Linux/Mac, but need to install Cygwin or Git Bash on Windows.

I also saw https://github.com/composer/installers where Grav is present but didn't understand how to use it...
Maybe `.dependencies` file can help, but found nothing about it in Grav learn and have problems with using:
https://github.com/getgrav/grav/issues/1027

I think that's checking `user/plugins` folder and installing missing vendor deps is a good thing for `bin/grav install` command. Maybe it was `-vendor` key or something.

**Comment by atomicthumbs** [comment]
this would be nice. currently precompiling Grav with HHVM leads to it complaining about a bunch of plugins:
```
Unable to stat file /home/atomicthumbs/pinopsida.com/html/user/plugins/admin/vendor/zendframework/zendxml/vendor/autoload.php
Unable to stat file /home/atomicthumbs/pinopsida.com/html/user/plugins/email/vendor/swiftmailer/swiftmailer/lib/Swift.php
Unable to stat file /home/atomicthumbs/pinopsida.com/html/user/plugins/email/vendor/swiftmailer/swiftmailer/tests/acceptance/Swift/swift_required.php
Unable to stat file /home/atomicthumbs/pinopsida.com/html/user/plugins/email/vendor/swiftmailer/swiftmailer/tests/acceptance.conf.php
Unable to stat file /home/atomicthumbs/pinopsida.com/html/user/plugins/email/vendor/swiftmailer/swiftmailer/tests/smoke.conf.php
Unable to stat file /home/atomicthumbs/pinopsida.com/html/user/plugins/login/vendor/birke/rememberme/vendor/autoload.php
Unable to stat file /home/atomicthumbs/pinopsida.com/html/user/plugins/login/vendor/birke/rememberme/test/Storage/PHPUnit/Extensions/Database/TestCase.php
Unable to stat file /home/atomicthumbs/pinopsida.com/html/vendor/seld/cli-prompt/vendor/autoload.php
```

I _think_ this is the same issue, and I _think_ it may relate to the fact that HHVM seems to be segfaulting regularly when I use the admin panel, but I can't confirm this.

**Comment by flaviocopes** [comment]
I think your issue is having vendor/ excluded in your .gitignore and you're pushing to a server the repo, so the vendor folder in email/login/code is not committed.

Btw while most of Grav core is (automatically) tested on HHVM too, Admin or other plugins are not regularly tested on HHVM.

**Comment by atomicthumbs** [comment]
This is using the .zip package available on getgrav.org.

**Comment by flaviocopes** [comment]
Ok so that leaves out the .gitignore issue. Those files are actually existing on the server, right?

**Comment by Sogl** [comment]
@flaviocopes Issue closed. No plans to add this enhancement?
