### ISSUE TITLE
Error xmlParseEntityRef: no name when trying to access XML version

### ISSUE THREAD

**Issue by 01010000101001100** [getgrav/grav#1029]
I am getting `error on line 16 at column 74: xmlParseEntityRef: no name` when I try to access `xml` version of a post on my Grav site. Have a look yourself:
http://focusasia.xyz/fintech-in-asia-brief.xml

**Comment by rhukster** [comment]
What does the full page .md look like?  Also what does the .xml.twig template look like.  I basically need all the bits to reproduce the error locally.

**Comment by rhukster** [comment]
Does this still occur with latest Grav?
