### ISSUE TITLE
PHP5 GD not being recognised

### ISSUE THREAD

**Issue by gbell12** [getgrav/grav#103]
Grav doesn't like my PHP5 GD installation... fails the check in  user/plugins/problems/problems.php (both tests of the conditional)

I can see GD loaded via phpinfo()

I'm on Ubuntu 14.04, and the package is PHP5-GD version 5.5.9.

If I hack problems.php, then the Blog skeleton throws an `Undefined constant 'IMG_JPG'`  exception.

**Comment by rhukster** [comment]
I think its a problem with your PHP GD libraries:

https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=ubuntu%20undefined%20constant%20'img_jpg'

Seems to be a common problem (not Grav specific).  Is there a newer version available?

**Comment by gbell12** [comment]
I Googled it too, but lots seemed to be very old.  That version is the latest.

There's a thread on the forums: http://getgrav.org/forum#!/?Undefined%20constant  But his was a case of GD just not being installed.  In my case, it seems to be installed.

$ php5 -i | grep -i gd
/etc/php5/cli/conf.d/20-gd.ini,
gd
GD Support => enabled
GD Version => 2.1.1-dev
gd.jpeg_ignore_warning => 0 => 0
GDM_LANG => en_AU
GDMSESSION => awesome
_SERVER["GDM_LANG"] => en_AU
_SERVER["GDMSESSION"] => awesome

**Comment by rhukster** [comment]
Maybe try uninstalling and reinstalling it?

**Comment by rhukster** [comment]
Also what is the full dump of your GD section from `phpinfo();`

**Comment by gbell12** [comment]
It's working now.  Just like that.  And the two tests:
```
        if (defined('GD_VERSION')) {
        if (function_exists('gd_info')) {
```

...are returning true as well.  I have no explanation for this.  I haven't rebooted.  Apologies for the time waste; maybe this will just serve as a record for an intermittent problem, and be helpful for the next occurrence for someone.

**Comment by rhukster** [comment]
No worries. Glad it's working. :)

**Comment by retnikt** [comment]
For me, reloading Apache (doing a `sudo service apache2 reload`) worked, so maybe that would help you in future.
