### ISSUE TITLE
Twig in pages

### ISSUE THREAD

**Issue by Cl1608Ho** [getgrav/grav#1032]
I have globally enabled Twig parsing in pages, and no override set for the specific page (home)

I tried `{{ page.url }}` which works as expected, and is replaced by `/home`.

I wanted to use more sophisticated stuff, like `{% for site in pages.children.nonVisible %}` but this doesn't get executed, apparently just skipped.

Is there a way that i can use such thing in a page, or what should i do then?

**Comment by rhukster** [comment]
That sort of twig should work fine in pages if you have twig processing enabled.  More likely it's just not finding any suitable pages.  

I think in this case you want `page.children` ???

The best thing to do is to enable the debugger in Grav, and then Dump vars to make sure the Twig code is correct:

```
{{ dump(page.children.nonVisible) }}
```

**Comment by Cl1608Ho** [comment]
Well.

Through debugging i found my error. I don't want page.children.

I want to iterate over all nonvisible pages. at the moment, i'm doing this via `page.parent.children...` but is there a better way?

**Comment by rhukster** [comment]
I think you might want `page.siblings..`

**Comment by Cl1608Ho** [comment]
Well, yes, but also what I mean is how to get a Collection of *all* pages, not just siblings ;) 

Thanks for the effort

**Comment by rhukster** [comment]
probably you are looking for `descendants()` then:

https://learn.getgrav.org/content/collections
