### ISSUE TITLE
Adding subpages when "Hide home route in URLs" is enabled

### ISSUE THREAD

**Issue by JeffStarr** [getgrav/grav#1034]
In the admin area, when the setting "Hide home route in URLs" is enabled, there are issues when adding new subpages to the home page. 

Click on "Add Page" > Fill out the form > Click "Continue"

That works fine, but when you're there looking at the draft, maybe adding some content or whatever, and then click the "Save" button for the first time, the returned page is missing all frontmatter and page content. The frontmatter and content are displayed again only after revisiting the newly created page from the Pages menu.

Also, when this happens, the draft subpage say has a URL such as:

`http://example.com/admin/pages/home/post-1`

..but the returned/empty subpage URL attains an extra instance of `home/`:

`http://example.com/admin/pages/home/home/post-1`

Again, this behavior occurs only when the setting "Hide home route in URLs" is enabled. Given the duplication of `home/` (or whatever the home slug happens to be) in the URL, I suspect a correlation, most likely having something to do with the home-route redirect.

**Comment by rhukster** [comment]
Will look into this.. Thanks.

**Comment by ivan-dalmet** [comment]
Same problem here :/

**Comment by ivan-dalmet** [comment]
**Step 01**
![image](https://cloud.githubusercontent.com/assets/9749061/18466150/c5e68fcc-799a-11e6-90ba-0943f98cb089.png)

**Step 02 after click on "continue"**
![image](https://cloud.githubusercontent.com/assets/9749061/18466299/72e6ebb8-799b-11e6-967c-1601c5bb72ac.png)
![image](https://cloud.githubusercontent.com/assets/9749061/18466183/f785e2bc-799a-11e6-98b2-1ae356585067.png)

**Step 03 after click on "save"**
![image](https://cloud.githubusercontent.com/assets/9749061/18466273/541f6214-799b-11e6-88ad-e0099f3fb952.png)
![image](https://cloud.githubusercontent.com/assets/9749061/18466223/255d6db8-799b-11e6-82a4-c639e032c09d.png)

**Step 04 after click again on "save"**
![image](https://cloud.githubusercontent.com/assets/9749061/18466273/541f6214-799b-11e6-88ad-e0099f3fb952.png)
![image](https://cloud.githubusercontent.com/assets/9749061/18466289/6509cd62-799b-11e6-96df-4836bcb3da97.png)

Hope this help.

**Comment by flaviocopes** [comment]
Thanks, replicated

**Comment by flaviocopes** [comment]
Can you test the latest develop of the Admin plugin @ivan-dalmet @JeffStarr ?

**Comment by JeffStarr** [comment]
@flaviocopes I'm only 7 days into Grav at this point, so don't have a develop version set up yet.

**Comment by ivan-dalmet** [comment]
How can i install the latest develop of the Admin plugin easily ?

**Comment by ivan-dalmet** [comment]
@flaviocopes I replace my admin folder content by files of grav-plugin-admin develop branch.
Same problem but now url redirection is ok (no more /blog/blog)

**Comment by flaviocopes** [comment]
@ivan-dalmet I thought the problem was the url redirection. 

What's the other issue? Still got an error after the second save?

**Comment by ivan-dalmet** [comment]
@flaviocopes Yes exactly same errors

**Comment by rhukster** [comment]
I've added a Hacktoberfest tag to see if we can get some help with this as I'm a bit stretched with other things at the moment.

**Comment by rhukster** [comment]
Closing to due to inactivity
