### ISSUE TITLE
Error 500 on install

### ISSUE THREAD

**Issue by picaditto** [getgrav/grav#1036]
I can´t install the script because i get error HTTP ERROR 500.
Check the logs and get these: PHP Fatal error: Call to undefined function Grav\\Common\\Config\\json_encode() in /var/www/…/data/www/…/system/src/Grav/Common/Config/Compil edBlueprints.php on line 3

**Comment by rhukster** [comment]
As I said in the forum, pretty much the only way to get that error is if PHP doesn't have that function because it's too old.  Grav needs PHP 5.5+

**Comment by rhukster** [comment]
Also if you are on some versions of Linux (Ubuntu?) you might need to install the **php5-json** package: http://stackoverflow.com/questions/18239405/php-fatal-error-call-to-undefined-function-json-decode
