### ISSUE TITLE
Markdown links and tables processed wrong way

### ISSUE THREAD

**Issue by NorthernCode** [getgrav/grav#1037]
`[My Link](http://link.com)`

renders as:

`[My Link](http://link.com)` and the http-part contains the link.

**Comment by rhukster** [comment]
I can assure the links are working fine.. they are tested every build with our Test suite:

https://github.com/getgrav/grav/blob/develop/tests/unit/Grav/Common/Markdown/ParsedownTest.php

Did you turn off markdown processing or something???

**Comment by NorthernCode** [comment]
All other markdown like headers and lists work, but link (and also what i just noticed) tables do not render right way.

**Comment by NorthernCode** [comment]
Hmm seems it was the Text Formater option. If it was yes this happened.

**Comment by rhukster** [comment]
Text Formatter?

**Comment by NorthernCode** [comment]
On the options tab of the page

**Comment by NorthernCode** [comment]
Seems to be a Plug-In

**Comment by rhukster** [comment]
Yah not something i'm familiar with from the core.

**Comment by rhukster** [comment]
Seems like it's related to the 3rd party plugin. I suggest opening up an issue in that plugin's issue tracker.
