### ISSUE TITLE
Multiple forward slash in URL shows error

### ISSUE THREAD

**Issue by PhoenixPeca** [getgrav/grav#104]
Why does multiple forward slash shows an error? I mean It shows 500 server error, when error reporting is off.. And shows "Crickey! blah blah blah" when error reporting is on.. Can it just fail silently and redirects to homepage or shows the 404 error instead like the getgrav.org website..

**Comment by rhukster** [comment]
Are you running Nginx by any chance? Getgrav.org and my locals don't have these problems but they run Apache.

**Comment by PhoenixPeca** [comment]
Im running apache...

**Comment by PhoenixPeca** [comment]
For example I mistyped http://localhost/home into http://localhost///home. Then shows me errors, either 500 or that crickey stuff, depending if I turn on or off the error reporting. Is there another way to show 404 not found instead?

**Comment by namaless** [comment]
Why you need multiple slash in the url? O.o

**Comment by rhukster** [comment]
I can't replicate this on any of my local installs.  Can you double check you have the latest `.htaccess` in place:

https://github.com/getgrav/grav/blob/develop/.htaccess
