### ISSUE TITLE
Retina images not displaying/inserting full file name in admin

### ISSUE THREAD

**Issue by JeffStarr** [getgrav/grav#1040]
The "Page Media" panel does not display the entire file name when uploading `@3x`, `@2x`, etc. size images. Instead the file name is displayed without the `@3x` suffix. Further, when clicking on the  image's "Insert" button from the Page Media panel, the image likewise is inserted without the `@3x`.

For example, uploading an image named `sample-image@3x.jpg` results in `sample-image.jpg` displayed as the file name on the image thumbnail displayed on the Page Media Panel. Likewise, when clicking the Insert button, the inserted file name is `sample-image.jpg`:

`![](sample-image.jpg)`

As explained on Gitter, I do not know if this is a bug or the default/expected behavior.

**Comment by w00fz** [comment]
You are only supposed to upload the matching `@2x` and `@3x`, or have Grav generate them for you, you are not supposed to reference theme because Grav has built-in support for it.

See https://learn.getgrav.org/content/media#higher-density-displays

**Comment by JeffStarr** [comment]
So you're saying that what I've described is the intended behavior?

**Comment by w00fz** [comment]
What's the output on the frontend rendering?

**Comment by JeffStarr** [comment]
Here is an example:

`<img src="/images/8/4/b/0/0/84b003ac6da44eaa43a501bda63027ec526dad9e-sample-image3x.jpeg" srcset="/images/8/4/b/0/0/84b003ac6da44eaa43a501bda63027ec526dad9e-sample-image3x.jpeg 600w, /images/6/d/3/9/e/6d39e7a8e6106a157e970ff5104df8bcbe2bb5ba-sample-image3x.jpeg 1800w, /images/3/9/a/5/1/39a51424fc867304147df72e6e4b546d7e4586ae-sample-image3x.jpeg 1200w" sizes="100vw" />`

As shown here, the `srcset` values all specify "3x" in the file name, and the file name doesn't seem to change when the browser is resized, etc. I guess I was expecting to see the 3x image (i.e., the original image) used in the Page Media panel, and then the `@2x` and `@3x` (i.e., the resized images) used as the `srcset` values (because like you said, Grav auto-generates them). Instead it looks like only the 3x is used and the 2x and/or original is nowhere to be found in the source code. I get that the actual 3x images that are used in the `img` tag vary in size, but the nomenclature seems to indicate otherwise.

**Comment by rhukster** [comment]
As this has been commented on i'll leave this, but in the future, please open admin-related issues in the admin plugin: https://github.com/getgrav/grav-plugin-admin/issues

**Comment by w00fz** [comment]
This is not an issue and all expected behavior. If you upload your high def files Grav doesn't mess with it otherwise generates them for you. At least this is how it was last I checked.
We can't reference or list all high definition formats , it's really useless. Instead it only reference the original name with no postfix. You really don't have to worry about anything so unless I'm missing the question I think this is all working as expected?

**Comment by w00fz** [comment]
Also they are not the same files, look closer to the path, the srcset reference all different files. The @3x suffix is just a naming convention, the srcset is doing exactly the same by defining sizes for you.

**Comment by JeffStarr** [comment]
Yep that's what I figured, just the nomenclature seems imprecise. Thanks for explaining.
