### ISSUE TITLE
Admin resource loaded on frontend

### ISSUE THREAD

**Issue by JeffStarr** [getgrav/grav#1042]
When using the Asset Manager to include CSS, the login styles are included on all pages on the frontend:

`<link href="/user/plugins/login/css/login.css" type="text/css" rel="stylesheet" />`

This impacts performance by loading an unnecessary resource. Should be limited to the backend, unless there is a way to exclude the resource somehow via the Asset Manager..?

**Comment by w00fz** [comment]
This is actually a setting:

https://github.com/getgrav/grav-plugin-login/blob/develop/login.yaml#L2

**Comment by JeffStarr** [comment]
So if I set `built_in_css` to false, the `login.css` is the only resource that is affected, correct?

**Comment by JeffStarr** [comment]
Okay cool, but I want to know: if I set `built_in_css` to false, the `login.css` is the ONLY resource that is affected, correct? I.e., are there any other resources that may be impacted by changing this option.

**Comment by rhukster** [comment]
Nope, like i said it's a login config option.  

https://github.com/getgrav/grav-plugin-login/blob/develop/login.php#L515-L517

**Comment by JeffStarr** [comment]
Thanks that explains it.
