### ISSUE TITLE
Can't install Grav (issues found but not displayed?)

### ISSUE THREAD

**Issue by Anthodev** [getgrav/grav#1043]
Hello,

I try to install grav (1.1.5) on my Vagrant box but the installer say to find issues while no issues are listed (all the checkboxes are green)

![grav_install_error](https://cloud.githubusercontent.com/assets/1784889/18506321/caf294ee-7a6b-11e6-820b-e54f6ce887f2.jpg)
![grav_install_error2](https://cloud.githubusercontent.com/assets/1784889/18506323/caf5a2ec-7a6b-11e6-9b32-f9f044fe6b46.JPG)
![grav_install_error3](https://cloud.githubusercontent.com/assets/1784889/18506322/caf303c0-7a6b-11e6-8d00-ae1b223d2a79.JPG)

How can i fix this issue please?

Thanks!

**Comment by flaviocopes** [comment]
I think the problem is linked to https://github.com/getgrav/grav-plugin-problems/issues/9, so basically due to a bug in the Problems plugin, the PHP Zip extension line is not showing the correct status.

So, check if you have the PHP Zip extension enabled. 
Could this be the case?

**Comment by Anthodev** [comment]
It was, i installed and activated php-zip, it's all good now.

Thank you! :)

**Comment by Anthodev** [comment]
It was, i installed and activated php-zip, it's all good now.

Thank you! :)
