### ISSUE TITLE
What Code Highlighting is supported?

### ISSUE THREAD

**Issue by nitmws** [getgrav/grav#1045]
Page https://learn.getgrav.org/content/markdown, section Syntax highlighting, tells that after fencing with ``` the file extension of a specific code type can be added to launch a code specific hightlighting.

I've tried ```xml and is looks just only as pre-formatted, no xml-specific highlighting (e.g. element tags and attribute tags in a special color.)

1.  what types of code are supported at all?
2. are any settings in e.g. the configuration required?

**Comment by flaviocopes** [comment]
Install https://github.com/getgrav/grav-plugin-highlight and have a look at https://highlightjs.org/ for the available options
