### ISSUE TITLE
Bug : Installtion missing zip extension check (grav keeps redirect on issue found page with no issue)

### ISSUE THREAD

**Issue by nicolas-bastien** [getgrav/grav#1046]
After a fresh install version 1.1.5.

localhost redirects me on the issue found page but there is no issue to correct

![grav-issue found with no issue](https://cloud.githubusercontent.com/assets/1446466/18544309/586e7b08-7b34-11e6-9811-0f3b7ef64ff6.png)

I'm working with docker, with a custom dockerfile based on php:5.6-apache.

**Comment by nicolas-bastien** [comment]
If I run php local server everything is fine 

    php -S localhost:8080

(but I wont be able to use admin)

**Comment by flaviocopes** [comment]
Might be an issue I discovered yesterday in checking for the PHP Zip extension. Can you check it's enabled? (it will be marked as error internally, but not highlighted in red in that list you see)

**Comment by nicolas-bastien** [comment]
@flaviocopes you're right with zip extension it works.

So I guess it should check that requirements too

**Comment by flaviocopes** [comment]
I re-released the Problems plugin yesterday which should fix this issue. Did you download your Grav package today?
