### ISSUE TITLE
Consider adding additional admin limitations designed for Authors/Contributors

### ISSUE THREAD

**Issue by nlile** [getgrav/grav#1048]
From what I've read it seems like there is currently no way to add an author or blog contributor to Grav and give him/her posting abilities without also letting him/her be able to edit any and every post/page. This seems to be the only option to create a user who is an 'Author' or 'Contributor' 
```
access:
admin:
login: true
super: false
pages: true
site:
login: true
state: enabled
```
But I certainly don't want my guest post authors or once a week posters to be able to edit my home page.

**Comment by rhukster** [comment]
@nlile please open an issue in the admin repo and copy/paste this there: https://github.com/getgrav/grav-plugin-admin/issues

Closing here as it's the wrong repo.
