### ISSUE TITLE
Feature suggestion: full control over image sizes with ImageMedium#derivatives

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav#1051]
I would like to suggest that the `ImageMedium#derivatives` method be able to take an array instead of just max, min and step arguments. That array would allow for flexible control over what image widths to resize to.

This is useful because often times you're looking for an incremental increase in image widths - for mobile users you might want to really optimize for performance, but for desktop users, maybe all you need is one or two large versions that won't ever be too small.

I could easily submit a PR for this, but wanted to get a green light first.

**Comment by rhukster** [comment]
Sounds useful.. green light given :)

**Comment by fredrikekelund** [comment]
Cool! :) I'll see if I can submit a PR for this some time in the coming week
