### ISSUE TITLE
Bug: `Types::scanTemplates` throws error when "modular" directory folder is missing

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav#1059]
As in [themer, #4](https://github.com/Sommerregen/grav-plugin-themer/issues/4) [Types::scanTemplates](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Types.php#L84-L85) throws an error, if any any theme ships without a "templates/modular" directory.

The best is to check beforehand, if the folder exists and if yes do the registering then.

**Comment by rhukster** [comment]
Agreed.  How about a PR? :)

**Comment by Sommerregen** [comment]
@rhukster Not right now. At the moment I'm on another project. I'm just reporting issues when I find some. However when I have time and nobody other do it before me,  I'll fix it.
