### ISSUE TITLE
Error 500 page exposes site details to visitors

### ISSUE THREAD

**Issue by gitname** [getgrav/grav#1064]
Even with the **Display errors** option set to `No`... 

![image](https://cloud.githubusercontent.com/assets/7143133/18805339/a98c4fd8-81bf-11e6-9039-4c317466db6f.png)

..., the [Error 500 page](https://github.com/getgrav/grav/blob/master/system/src/Grav/Common/Errors/Resources/layout.html.php) (example shown below) still exposes more information than I would like it to while in Production.

Specifically, it does 2 things I want to change:

1. It has the **known appearance** of a Grav Error 500 page (providing a clue to the visitor that the site uses Grav and is vulnerable to any outstanding vulnerabilities in Grav)
2. It shows the **PHP error information** (providing a clue to the visitor of potential vulnerabilities in the site)

![image](https://cloud.githubusercontent.com/assets/7143133/18805359/66d0821c-81c0-11e6-9548-8285e27b06e2.png)

I would like to be able to customize the page, to disable it completely, or for there to be a Grav option I can use to indicate whether I want it to contain the PHP error information or not.

**Comment by Perlkonig** [comment]
I concur. When "display errors" is set to false, it should return a bare `500` and let the web server handle it. I'm looking through the source code but don't understand Whoops enough to know what the alternatives are. What would happen if you just returned `Handler::Quit` in [this function](https://github.com/getgrav/grav/blob/6c042b48043336203b138e2e76cf2b3a11dbda33/system/src/Grav/Common/Errors/SimplePageHandler.php#L29)? Why does Grav want to handle it in the first place? I'll do a little digging.

**Comment by Perlkonig** [comment]
A bare `Handler::Quit` seems to work. Something to consider, anyway.

**Comment by rhukster** [comment]
Done.
