### ISSUE TITLE
jquery update to 3.1.1

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav#1070]
Please forgive me if it's not a grav issue ☆
Jquery is actually 2.0.2 in `system/assets` but a 3.1.1 has been released [here](https://jquery.com/).
Thanks in advance

**Comment by rhukster** [comment]
I think it is probably better to keep jQuery 2.X as the default for the time being for compatibility reasons.  However, we could add jQuery 3.X to Grav and let you choose between them. 

I will look into this.

**Comment by flaviocopes** [comment]
`system/assets` includes jQuery 2.2.4, which is the latest 2.x release up to now.
I added jQuery 3.x, which you can add via the System settings. Simply change 2.x to 3.x.

**Comment by vanilla-thunder** [comment]
removing jquery from hardcoded assets would be better since including needed frameworks is done by templates.
