### ISSUE TITLE
Documentation: onMarkdownInitialized missing

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav#1076]
I see that the `onMarkdownInitialized` event is not listed on the life cycle page.

**Comment by rhukster** [comment]
Will get this added

**Comment by Perlkonig** [comment]
Oh, and a reminder about `onFallbackURL`, too.

**Comment by rhukster** [comment]
I have that one in my list already :)

**Comment by flaviocopes** [comment]
Done
