### ISSUE TITLE
Make use of Hacktoberfest!

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav#1078]
DigitalOcean and GitHub is running [Hacktoberfest](https://hacktoberfest.digitalocean.com), a contest where participants can win a t-shirt and other goodies by contributing to open source projects.

This might be a good chance to get help with some low hanging fruit, documentation or what not. You just need to tag issues with "Hacktoberfest" to make them findable. Don't know how many issues would be a good fit, but thought I'd let you know :)

**Comment by rhukster** [comment]
Did not know about this!  I'll give it a go!
