### ISSUE TITLE
Desire for a wiki?

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav#1079]
I recognize the appeal of reasonably lean documentation, but there are often recipes and such that are helpful if available to a wider audience. The forum is too transient to do this effectively. Is there a reason there is no official wiki? Projects like [DokuWiki](https://github.com/splitbrain/dokuwiki) are very similar in philosophy, being fully flat file. I could probably even find a place on one of my servers to host it, if that were necessary. I know GitHub offers a built-in wiki, but I don't have any experience with it.

I just know that there are a few things I've learned writing plugins these last couple months and monitoring the forums that I think might be valuable in some sort of more permanent place.

Thoughts?

**Comment by rhukster** [comment]
I'm really just afraid of having too many places for information.  Github issues, Gitter, Forum, Docs, and then a Wiki too? I would prefer to just add a section to the Docs that can be used for this.  As those are directly linked to GitHub, anyone can fork, and PR to add information.

**Comment by Perlkonig** [comment]
Fair enough. I'll gather some thoughts, consider a possible way to incorporate them into the main docs, and submit a pull request.

**Comment by flaviocopes** [comment]
Recipes on the docs Cookbook are user-contributed (https://learn.getgrav.org/cookbook).

That is the best place to submit tricks and other little gems you find. It's all Github based, so simple to even edit online (or you can clone the docs site locally)

**Comment by flaviocopes** [comment]
I now see you already moved on to that with https://github.com/getgrav/grav-learn/pull/326 👍 , closing this
