### ISSUE TITLE
Page caching doesn't take changed media into account

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav#1080]
I've had a lot of trouble with Grav finding media files that didn't exist in reality and therefore triggering an error. Or, so I thought, but in the end it looks like what was in fact going on was that Grav had cached the page objects, and those page objects weren't invalidated as I updated only the media files in that page. 

Is this intended behavior? Is there a way to get around this while still reaping some caching benefits? Whether I use the `file` or `folder` caching method doesn't seem make a difference either.

**Comment by rhukster** [comment]
This is intended behavior for performance reasons. 

If you have a filesystem that updates the root folder when any file changes, then the `folder` option will trigger on any file in that folder being updated.  However, the `file` option has to run through every folder recursively in `user/pages/` and check every relevant file to see if the date has changed.    This has to happen on every page load, no matter if the cache is on or off.  This is how the cache knows if it has to be invalidated or not.

The configuration now is to only check `.yaml` and `.md` files: https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Filesystem/Folder.php#L56

**Comment by fredrikekelund** [comment]
What will determine if the file system updates the root folder or not? And does the root folder equal `user/pages` or can it be any page folder? And I guess we're talking about mtime of the folder here?

I guess that if this is the way the cache works, then that's okay, but the docs ought to be clearer on this to avoid nasty surprises. Some more detail about how the page caching works in the "performance & caching" chapter as would be great, and also possibly a mention in the content deployment chapter. If people believe they'll be able to simply rsync content to the server with Grav, then that chapter could contain some kind of warning/gotcha to take the page cache into consideration. 

Also, would it be possible to invalidate and reinitialize a page in the cache if it encountered an error when initializing media?

**Comment by rhukster** [comment]
The folder time stamps work on most unix platforms when you modify a file within that folder.  For example if you `touch` a file, or if you `vi` a file.  Grav is able to just check these folder timestamps and see if any folder is newer that before.

However, there are many situations when the folder is not updated.  For example deleting a file doesn't update the folder timestamp.  Certain editors (i'm look at you `ST3`) don't update the folder timestamp when you edit a file. It's quite possible that `rsync` falls into this category too.

In these cases the best thing to do is to kick off a manual folder modification.  You can use the built in Grav `bin/grav clear` command which effectively simply **touches** the config folder to force a rebuild on the next page hit. Alternatively you can simple do a manual shell script to `touch` a page or config file and achieve the same result.

Regarding your media question, if an error is encoutered, as long as it's a particular error that a cache clear is known to recover, it would be a matter of simply calling `Grav::instance()['cache']->clear()`
