### ISSUE TITLE
access to web.config not restricted - why?

### ISSUE THREAD

**Issue by AddaxSoft** [getgrav/grav#1084]
anyone browsing the website can access hxxp://website-url.something/web.config which contains sensitive information.

other files include the README.md which expose other sensitive information. Is this addressed somewhere? How about putting these files in a protected folder accessed by authenticated users only?

**Comment by rhukster** [comment]
`web.config` is contained in the `webserver-configs/` in the root of Grav.  These are sample configurations for setting up various webservers.  None of these have server-specific information and are intended to be modified for your individual environments. `web.config` is actually a sample configuration for IIS webserver.

These are by default hidden via the `.htaccess` (or your appropriate webserver config).  And even if they weren't they would be in `hxxp://website-url.something/webserver-config/web.config`  If you have a `web.config` in the root of your site, it's probably been moved there, and it wouldn't even do anything anyway, as you have to configure IIS with that file, not simply drop it in your root.

I suggest deleting it.
