### ISSUE TITLE
Add setting to use same session for front end and admin

### ISSUE THREAD

**Issue by maxfrigge** [getgrav/grav#1085]
Currently the session is [split up](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Session.php#L80) in front end and admin. While this might be desired in some cases, there are also other cases where you want a shared session - e.g. when displaying an admin bar with links to edit or create a new page, currently logged in user name etc.

I propose that there should be a session setting to enable/disable sharing the session (disabled by default). 

I can create a PR if you agree on this.

**Comment by rhukster** [comment]
A PR would be considered as long as the default state was 'split' sessions.

**Comment by maxfrigge** [comment]
I have prepared a PR for this feature, but there are still few things to take care of.

Session related translations are stored in the admin plugin - I will create a PR for that once everything else is settled. I am also struggling with a proper naming and description. 

This is what I am currently using (the setting is `system.session.split_admin`)
![split_session](https://cloud.githubusercontent.com/assets/11060313/19150989/638870ec-8bca-11e6-8363-e0229bbe6c4d.png)

Then there is a small glitch when changing this setting. Upon saving, your current session will become invalid, which results in a logout (redirect to login) along with an error message "invalid security token". Is this ok or should there be a process to migrate from on session name to the other?

**Comment by w00fz** [comment]
I'm not sure if that's ok but if it is inevitable, I think we should at least have it explained in the description (tooltip). _"By changing this field, your session will become invalid and you will be required to login again."_ ... something along those lines

**Comment by maxfrigge** [comment]
I wouldn't say inevitable.. it shouldn't be too hard to migrate the session to another namespace. I haven't had a closer look at possible pitfalls yet though - is there anyone around who has more experience with the admin session?

**Comment by flaviocopes** [comment]
I think having a proper description with this side-effect explained is fine. I guess that when you enable this setting, admin will use the site session, so that's inevitable unless the opposite happens (site uses the admin session), which I don't know if it's doable / nicer.

**Comment by rhukster** [comment]
done.

**Comment by CherryDT** [comment]
Note that this value is not documented in the docs. (It is shown in the example, but not explained.)
