### ISSUE TITLE
Filter by Taxonomy by using the OR function

### ISSUE THREAD

**Issue by crusnac** [getgrav/grav#1087]
Current functionality only allow for "AND" functionality as a GET parameter when filtering based on taxonomy.  Add the ability to filter based on "OR".

Example: http://demo.getgrav.org/blog-skeleton/blog/tag:city,night  

City OR Night

**Comment by nineteeneightyeight** [comment]
I've ran into this as a requirement for a client. Do we know if this is on the roadmap at all?

**Comment by flaviocopes** [comment]
It's been marked as enhancement but it's not in the roadmap as an immediate addition to the codebase. You can work on this functionality and submit a PR if you want to speed up the process.

**Comment by nineteeneightyeight** [comment]
I had a look yesterday evening, I can see what's happening - the pages are being removed from the collection if their not in the array list. So if it's comma delimited then it has to have both of those taxonomy. Ideally I'd have said the ',' should have been used as the OR selector and something like '&' or '+' should have been used as the AND selector - so I'm not really sure how to proceed. I'd need a decision on the design pattern before being able to carry out the work required.

**Comment by nineteeneightyeight** [comment]
I would appreciate some advice with this, as it's an important piece of functionality for my client. I can't think of a selector that could be used for an 'OR' - as the only reserved separator is the comma. Another route could be to add a new entry in the config, but it appears to make this work with the admin area - I need to be able to translate the text in many languages (not exactly something I'm able to do). It seems a relatively simple change, but my lack of understanding of the under the hood of Grav makes it hard for me.

Thanks.

**Comment by rhukster** [comment]
This is something we are going to tackle in 2.0 with advanced object collection support.

**Comment by hughbris** [comment]
So this is 'on hold' essentially. Seems to me from the perspective of knowledge management (keeping ideas in the same thread and cross referenced to commits), that it would be better to tag 'on hold' or 'v2.0' and leave open.

_Just friendly advice on issue management from a guy who doesn't manage any group repos_ :) ...
