### ISSUE TITLE
Server Error 500 when Saving Docs

### ISSUE THREAD

**Issue by ghostinhershell** [getgrav/grav#1094]
Maybe you guys can help me figure this out. I get seemingly random 500 Internal Server errors in Grav. This issue only affects the content writing portion of Grav. I've done test cases and isolated some triggers:
1. Images. Removing images fixes the issue for some articles. Doesn't for others.
2. Character count. This affects new pages. Adding more than 500 characters (estimate) is a trigger.
3. Content. For some pages, I couldn't get around the 500 error without removing all content. Adding a single character and saving will trigger the 500 error.

I created a test case spreadsheet. Here's the link: https://docs.google.com/a/kmapsystems.com/spreadsheets/d/1DoDLRpripwSY-tElDf2ub1KKU6-yw3LN_l5wRaJCPbM/edit?usp=sharing

Whenever I run into an error, I log it in this spreadsheet. If you need any other info, please let me know.

Thanks!
Sarto

**Comment by fourroses666** [comment]
Hmm this sounds very recognizable.

**Comment by flaviocopes** [comment]
If you're on a server, can you try replicating this issue locally, to help identify if the problem is related to a server setting, or not?

**Comment by ghostinhershell** [comment]
It is on a server but replicating the issue locally isn't an option. The server is hosted. Do I have any other options?

**Comment by ghostinhershell** [comment]
We did also recently update the Grav base and admin UI.

**Comment by flaviocopes** [comment]
I've never seen this problem so my guess is it's specific to the server, but that's just my guess, and easiest thing would be you setting up Grav in a local MAMP or similar setup, and copy the user/ folder of the live site there, so the site is replicated local, and you can see yourself if the issue is reproducible.

**Comment by ghostinhershell** [comment]
Ok, here's an example of text that I cannot save in Grav's admin UI.

https://docs.google.com/a/kmapsystems.com/document/d/1twi_oLBskT16GV5FW5vyeKOOk8U-CgKuQkezdhFvqVs/edit?usp=sharing

The red highlighted text triggers errors in Grav. Maybe it's a specific word or phrase or even formatting that I'm not picking up? Can you take a look and possibly see if you can enter the text into a Grav article and save it without errors.

Thanks so much!
Sarto

**Comment by rhukster** [comment]
You mind just pasting the text here, or making the document publicly accessible?

**Comment by ghostinhershell** [comment]
[toc]
You can manage all active programs and drafts within the Programs tab of your Admin Console. Edit, Clone, Delete, Activate or Disable a program right from this page.
<div style="clear: right;"></div>

## Edit your Program
Once you have created a Program, you can always go back and update any pages or rewards. Follow these steps to editing your program:

![](Edit%20Pages.png?class=imgframe,imgfloatright&lightbox)
1.  In your Admin console, click on the **Programs** tab.
2.  Select the name of the program you want to edit. This should take you to the **Program** page.
3.  In the lower half of the page is the **Edit Pages** section. Select the **Edit** button next to the section you want to edit.
<div style="clear: right;"></div>

!!! If you are looking to make changes to your site setup, you can access those pages in Settings. 

---------------START OF ERROR----------------------------------
## Clone your Program
![](cloneprogram.png?class=imgframe,imgfloatright&lightbox)
To copy an existing program in its entirety, use the Cloning option by selecting the "Clone" button under the Actions column. This will create a new draft program that is a copy of the program you selected.
<div style="clear: right;"></div>

## Other Actions

![](programotheroptions.png)
Remove an active program or draft by selecting the orange "**Delete Button"** and confirm the deletion. You can also deactivate a program by selecting the **"Move to Draft**" button. This will disable all URLs and move the program to Draft Programs.
* **Activate Program** or **Make Program Inactive** - If you have not activated your program, this button will make it active and publicly accessible. If your program is already active, this button will "turn off" your program and make it no longer accessible.
* **View Details** - This takes you to the Program page. There you can view your member and referral count, edit your program pages, and view integration options.
* **Clone** - Clones your program and creates a copy. This copy will be in your drafts.
* **Default** - Only available for activated programs. Makes program your default program.
* **Delete** - This will delete your program from your account. It and all the data in it will no longer exist.

**Comment by ghostinhershell** [comment]
Here's a txt file:
[Managing Programs.txt](https://github.com/getgrav/grav/files/525112/Managing.Programs.txt)

**Comment by flaviocopes** [comment]
Nothing wrong, I don't see any issue here. 

Unless the problem is the image, which I don't have.

Same issue if you remove the images from the text?

**Comment by nepomuk13** [comment]
Could it be related to file permissions? I remember I had some random 500 errors on pages where new or updated content didn't had the correct permissions (iirc: permissions were root:root whereas I needed grav:root)

**Comment by ghostinhershell** [comment]
I think the issue did have something to do with permissions. I ended up contacting the server host about it and the issue was fixed. Thanks for your help and support guys, I really appreciate it! 

I made sure to vote for Grav for the 2016 CMS Critics Award. Good luck guys :)

**Comment by flaviocopes** [comment]
Good to hear that! Would be nice to know what was wrong about them, if someone else has a similar issue

**Comment by diegovogel** [comment]
@ghostinhershell Do you know what the server host had to change in order to fix this? I'm having very similar issues and have tried everything I can on my end. Thanks

**Comment by diegovogel** [comment]
I was able to get this sorted out with my hosting provider. They said it was a ModSecurity issue:

> Looks like you're tripping a ModSecurity rule when you add the content, which is blocking the request and resulting in the 500 error.
>
> The particular rule you're hitting is common among Wordpress sites, so I'll go ahead and whitelist it to prevent this from happening again.

Worked like a charm!
