### ISSUE TITLE
Admin login broken when proxying Grav on alternative port

### ISSUE THREAD

**Issue by eduwass** [getgrav/grav#1095]
I have a certain environment where I'm running Grav on port 8080, everything works fine but the admin login doesn't work because when logging in it redirects me to:

http://localhost/admin

When it should be:

http://localhost:8080/admin

**Comment by flaviocopes** [comment]
I run my main development site on port 8080, so it's not a scenario I can reproduce / it's not a known issue within Grav. Grav picks up the port it's running on.

I don't have an immediate answer at what could be the problem, which web server are you using?

**Comment by eduwass** [comment]
Sorry haven't answered before, actually I haven't explained this properly, I'm not really running on port 8080, I'm proxying port 80 to 8080 with HAproxy, I guess that is why this different to your scenario.

**Comment by flaviocopes** [comment]
Ok in this case you need to enable `reverse_proxy_setup` in `user/config/system.yaml`, did you try already?

**Comment by eduwass** [comment]
Thanks for the response @flaviocopes 

Today I've played around with the settings, I've tried `reverse_proxy_setup: true`  but it still makes no difference to me, I'm getting same results.

I've also tried specifying the port in the custom URL like this:
```
custom_base_url: http://localhost:8080
```

But then all links look liked:
`<link rel="icon" type="image/png" href=":8080/user/plugins/admin/themes/grav/images/favicon.png">`

Which was incorrect since it translates to a URL with the port repeated twice:
`
http://localhost:8080/:8080/user/plugins/admin/themes/grav/images/favicon.png
`

I attempted to work around that error by using
```
absolute_urls: true
```

Which would then print the absolute URL correctly, this is so far the closest to working I have, but there are still some other errors: I was seeing a red 'Invalid security token' error on the dashboard and login panel, and when I click on logout there seems to be a loop error in the URL, making the URL look like:

`http://localhost:8080/admin/task:logout/:8080/admin/logout/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/:8080/admin`

Any ideas?

Thanks!

**Comment by eduwass** [comment]
I've been browsing through the code a bit and I've found out that it picks the login URL from this line of code:

[/user/plugins/admin/themes/grav/templates/partials/login.html.twig:19](https://github.com/getgrav/grav-plugin-admin/blob/0a2b1d790f4cb4b189837c215eeda158a75e44dd/themes/grav/templates/partials/login.html.twig#L19)

The `{{uri.url}}` var will render an absolute URL, e.g:
```
<input type="hidden" name="redirect" value="http://localhost/admin">
```

I think my problem would be fixed if it rendered either:
```
<input type="hidden" name="redirect" value="/admin" />
```
or
```
<input type="hidden" name="redirect" value="http://localhost:8080/admin">
```

I'd do a pull request but I'm not entirely sure how to achieve this.

**Comment by flaviocopes** [comment]
I have setup a reverse proxy configuration locally, but I have no issues in using Grav Admin. I used this very simple nginx reverse proxy https://gist.github.com/natchiketa/987524a561e892924e81 and tried both with Apache running in a subdirectory (localhost:8009/grav/), or Caddy running in the domain root (localhost:8009/) and in both cases, no issues. 

I guess the problem is in the HAproxy config, but no idea what it might be. If you can try the above nginx setup to isolate the problem, would be 👍

**Comment by flaviocopes** [comment]
`custom_base_url` is meant to be used in other scenarios, mainly when you want Grav to respond on the root but be physically located in a subfolder, with htaccess redirects in place.

**Comment by rhukster** [comment]
Closing to due to inactivity
