### ISSUE TITLE
Problem with nested collections

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav#1097]
Hello!

I'm trying to implement Wordpress style archives in my Grav site.
For example,
Post: https://bestblog.wordpress.com/2007/06/13/elle-effect/ 
Day: https://bestblog.wordpress.com/2007/06/13/ 
Month: https://bestblog.wordpress.com/2007/06/ 
Year: https://bestblog.wordpress.com/2007/

I decided to use nested folders to work with it, but found some problems. First, I'm trying to work with adding year folders.

1_ Problem with pagination.

I use nested loop:

``` twig
{% set yearCollection = page.collection() %}

<!-- Year loop -->
{% for postYear in yearCollection %}

<!-- Post collection -->
{% set postCollection = postYear.collection() %}

<!-- Post loop -->
{% for post in postCollection %}

....my html output...

{% endfor %}

{% endfor %}

{{ dump(postCollection.params.pagination) }}

{% if config.plugins.pagination.enabled and postCollection.params.pagination %}
    {% include 'partials/pagination.html.twig' with {'base_url':page.url, 'pagination':postCollection.params.pagination} %}
{% endif %}
```

And my dump is always `null`, I can get `yearCollection` pagination parameter only, not `postCollection` that I need.

Can I get all nested items in one BIG collection and set pagination with it?

2_ Before year directories I used this construction to output events on main page:

``` markdown
process:
    twig: true
    markdown: false
events:
    items:
        '@page': '/events'
    order:
        by: date
        dir: desc
    dateRange:
        start: today
```

Now with this code I can get only years, but can't get posts directly with `'@page': '/events-year'`, also it doesn't work with `'@page': '/2016`. Why?

3_ Third problem is copy&pasting the same files for post in every year directory:
![image](https://cloud.githubusercontent.com/assets/7556290/19211927/97cb4080-8d93-11e6-9abf-528e32de2537.png)
Without them I get error 404. 

Is it possible to get rid all of these problems?

**Comment by Perlkonig** [comment]
There are plugins to generate these sorts of archives. Have you looked at how they implement this? I know this doesn't answer your questions directly. I'd  just hate for you to waste time if  there's a plugin that will get where you want to go.

**Comment by Sogl** [comment]
@Perlkonig This issue was opened long time ago in `grav-plugin-archives` repo:
https://github.com/getgrav/grav-plugin-archives/issues/16
I don't know any other type of plugin that can do this job for me...

**I did a more deep research and found a way how to solve my 2nd problem.**
In YAML:
```
'@page.descendants': '/events'
```

In md:
```
{% set events_collection = page.collection('events').ofType('post') %}
```
Desc do a recurse through folders and this good filter do a final job 👍 


**But it did't work for pagination (1st problem)** 😞 
I found an issue where this problem is discussed:
https://github.com/getgrav/grav-plugin-pagination/issues/18
Will be some movement on this issue?

**3rd problem is still open...**

**Comment by flaviocopes** [comment]
`postCollection` in your example is null because of the scope, as it's defined inside the `for` but you access it outside of it. Use http://twig.sensiolabs.org/doc/filters/merge.html to populate an array in the iteration.

**Comment by Sogl** [comment]
@flaviocopes 
> Use http://twig.sensiolabs.org/doc/filters/merge.html to populate an array in the iteration.

Can I use `merge` to put collections into each other?

And what about my other questions?

**Comment by flaviocopes** [comment]
If you define `postCollection` inside the for, it's not accessible outside it. 

If you access /2016 as a page, then it must have a markdown file in it, otherwise you'll get a 404.

**Comment by Sogl** [comment]
I solved problems with scope and need help with 1st and 3rd problems.

**Comment by Sogl** [comment]
@rhukster Why this issue was closed without any comment?

**Comment by rhukster** [comment]
oh sorry, i just read "I solved problems..." and thought you were all sorted.  reopening.

**Comment by Sogl** [comment]
@rhukster Don't worry :wink: 
I would be very happy if you can help me with 1st and 3rd questions. Please read my comments here:
https://github.com/getgrav/grav/issues/1097#issue-181821336
https://github.com/getgrav/grav/issues/1097#issuecomment-252425970

**Comment by Sogl** [comment]
Why I can't use only one `frontmatter.yaml` with `template` variable in it?

Documentation:
https://learn.getgrav.org/content/headers#template

How it looks:
![image](https://cloud.githubusercontent.com/assets/7556290/19421544/84889dca-944f-11e6-96d9-4390b3f693dd.png)

`frontmatter.yaml` content:
```
template: events
content:
    items: @self.children
    order:
        by: date
        dir: desc
```

Error 404.
Why?

**Comment by rhukster** [comment]
Closing to due to inactivity

**Comment by Sogl** [comment]
@rhukster Because no answers from developers
