### ISSUE TITLE
Dump variables change position in debugbar

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav#1098]
Hello!

Today I found strange bug(?) with ouput dump variables.
I have this code:

``` twig
{% extends 'partials/base.html.twig' %}

{% set month = page.title %}
{% set year = page.parent.title %}

{% block title %}{{ dump(month)}}{{ dump(year) }}{{ month }}-{{year}} &mdash; {% endblock %}

{% block content %}

{{ dump(month)}}
{{ dump(year) }}

...
<h1 class="brand-heading"> {{ month }}-{{ year }}</h1>
...

{% endblock %}
```

I also found an answer in SO how to use variables with different scopes:
http://craftcms.stackexchange.com/a/167

In title and on page I see `08-2016` (month-year). That's right.
But dump output I see `2016-08` (year-month):

```
2016
08
2016
08
```

Sometimes on page refresh dump positions change:

```
2016
08
08
2016
```

How it can be happen?

**Comment by flaviocopes** [comment]
I can't replicate this.

The Twig dump output is a combination of functionality provided by Twig and the PHP Debug Bar (https://github.com/maximebf/php-debugbar) and I'm not sure how Grav is involved in this, but I could not find any way to make them appear in the reverse order.

**Comment by Sogl** [comment]
@flaviocopes 

I tried to do the same but simpler in `base.html.twig`:
```twig
{% block head %}

{{ dump("one") }}
{{ dump("two") }}
{{ dump("three") }}
....

{% endblock %}
```

Output:
```
three
one
two
```

It's not normal I think.

**Comment by flaviocopes** [comment]
Can't replicate, no matter how many times I hit refresh. 

Can you replicate this on a clean Grav skeleton?

**Comment by Sogl** [comment]
I can replicate this after switching to `antimatter` theme... now need to check on fresh Grav install.

**Comment by flaviocopes** [comment]
Might be related to https://github.com/maximebf/php-debugbar/issues/222 ?

**Comment by rhukster** [comment]
Closing to due to inactivity
