### ISSUE TITLE
Problem when metadata item has double quotes

### ISSUE THREAD

**Issue by andrelima** [getgrav/grav#110]
I had a metadata item ("description") which had an expression (in the middle of it) in double quotes, and that didn't properly output to the HTML... Seems like a bug.

**Comment by rhukster** [comment]
Can you provide me your full YAML configuration where you have this double quote issue?

**Comment by rhukster** [comment]
Fixed in next release

**Comment by andrelima** [comment]
Oh, thank you! Sorry for not having provided that info you requested before... Time has been tight!

**Comment by andrelima** [comment]
Is there an ETA for the next release?

**Comment by rhukster** [comment]
Probably friday

**Comment by rhukster** [comment]
I was right, i have released 0.9.14 today with this fix.
