### ISSUE TITLE
403 forbidden when access non-routed and non-visible link

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav#1101]
Hello!

I'm using `images` directory of my Grav site just for uploading images, I don't need any `md` files in it. Also my site is multilanguage. How it looks in admin panel:
![image](https://cloud.githubusercontent.com/assets/7556290/19296293/39ecf094-9086-11e6-8bf4-10655911a00d.png)

When I type `http://sitename/images` I see this error:
![image](https://cloud.githubusercontent.com/assets/7556290/19296388/d64a0580-9086-11e6-9356-8668d93abc1e.png)

404 error with custom page when I type `http://sitename/en/images` or another lang, that's how it should be.

I also have the same non-visible non-routed folder with one pdf file in it, but without nested folders:
![image](https://cloud.githubusercontent.com/assets/7556290/19296505/d471ef74-9087-11e6-9792-0566e66fb882.png)

And when I type `http://sitename/downloads`, no 403 error after...  redirect to `http://sitename/en/downloads` and 404 as it should be.

Why it happening with `images` URL?

**Comment by flaviocopes** [comment]
The `images` folder is under `pages`?

**Comment by Sogl** [comment]
> The images folder is under pages?

`images` and `downloads` folders are in `pages`:

![image](https://cloud.githubusercontent.com/assets/7556290/19310320/339819a4-90d5-11e6-962c-0459ec4f31ca.png)

**Comment by rhukster** [comment]
I think you might have an actual `/images` folder inside your webroot that is getting picked up before Grav is able to route this internally to Grav's `user/images/` folder.

**Comment by Sogl** [comment]
But I want to view images from admin panel. Can't understand difference between `downloads` without 403 error and `images` with this error.

**Comment by rhukster** [comment]
what i'm saying is do you have an images in your webroot? outside of Grav. like `~/public/html/images`  ???

**Comment by Sogl** [comment]
>what i'm saying is do you have an images in your webroot? outside of Grav. like ~/public_html/images ???

Ah...yes, it's created by Grav automatically when I'm using `cropZoom`:
![image](https://cloud.githubusercontent.com/assets/7556290/19330977/6cee39ce-912d-11e6-8e9f-1310ed206963.png)

**Comment by flaviocopes** [comment]
Ok so, `images` points to the actual images/ folder in the Grav installation. It has priority.
The fact you have a 403 is due to `Options -Indexes` in the .htaccess file.

**Comment by Sogl** [comment]
Any way to correctly handle this request? I see the same when typing `http://sitename/user`

**Comment by flaviocopes** [comment]
The `images` folder needs to always be accessible as it's where the images cache puts its content, otherwise that is going to break. You can't access images using the `/images` route, but using a full pages directory path will work. (yoursite.com/user/images/...)

Same for `user` or any main folder which should be publicly accessible.

**Comment by flaviocopes** [comment]
Any actual folder is going to be a 403 with the default `.htaccess`

**Comment by Sogl** [comment]
If this is correct behavior I close this issue
