### ISSUE TITLE
Error after clearing cache

### ISSUE THREAD

**Issue by kodemi** [getgrav/grav#1103]
Grav v1.1.5
1. Clear cache in admin page.
2. Reload page.

`session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/vhosts/u0224630.plsk.regruhosting.ru/httpdocs/eventmonaco.ru/system/src/Grav/Common/Config/CompiledBase.php:182)`

![1476278911831screensave](https://cloud.githubusercontent.com/assets/213874/19312283/69d560f2-909a-11e6-9dda-30ca659af07a.png)

**Comment by rhukster** [comment]
Never seen this before, so have some more questions for you:

Is this 1.1.5 from GitHub Develop branch or 1.1.5 downloaded from getgrav.org?

Do you have any other plugins installed? Does this happen if you run the site locally?

**Comment by kodemi** [comment]
It's downloaded from getgrav.org.
Yes. I have some plugins:  
- Admin Panel  v1.2.2
- Assets  v1.2.1
- Email  v2.5.0
- Error  v1.5.1
-  Form  v2.0.5
-  Leaflet v1.0.1
-  LightSlider  v1.5.1
-  Login  v2.1.2
-  Markdown Notices  v1.0.0
-  Pagination  v1.3.2
-  Problems  v1.4.5
-  Shortcode Core  v2.3.1
-  SimpleSearch  v1.9.2

It doesn't happen if I run the site locally.

**Comment by rhukster** [comment]
it's probably an error on your hosting environment that is displaying some output before the session is started by Grav.  This would cause this error.  Perhaps you can check in your PHP / Apache error logs to see if anything is output there?

**Comment by Stepanov-Sergey** [comment]
after clearing cache folder "images" is empty.

**Comment by flaviocopes** [comment]
The `images` folder contains cached images generated by Grav, and it's cleared when you clear the global cache or the images cache. It's not meant to store your images. All content you add to the site should be put under the `user` folder, or in a custom folder.

**Comment by flaviocopes** [comment]
Closing this ticket for inactivity on the original post
