### ISSUE TITLE
[add-resource] New Plugin - image resizing at upload time

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav#1106]
I wrote a plugin that will listen for the `onAdminSave` event, and generate responsive image alternatives for the images that don't have any. It's available at [fredrikekelund/grav-plugin-resize-images](https://github.com/fredrikekelund/grav-plugin-resize-images).

Naturally, it would be cool to add this to GPM, but this is also a call for feedback!

Also, I'm wondering - how does GPM look for new releases of a plugin? Does it work with git tags, or does it simply use the latest commit from the main branch?

**Comment by flaviocopes** [comment]
Once added to the GPM, new releases are made by increasing the version in the plugin blueprint, adding an entry to the changelog and then creating a new release on GitHub. 

The GPM will check for new releases once every hour.

**Comment by fredrikekelund** [comment]
Easy enough, thanks! So I guess I'll have to tag an initial release now as well?

**Comment by flaviocopes** [comment]
Yes, create a release named as your current version. See https://learn.getgrav.org/advanced/grav-development#themeplugin-release-process

**Comment by rhukster** [comment]
Still waiting on the release so it can be added to GPM.

**Comment by fredrikekelund** [comment]
@rhukster I've created a new release on GitHub, hopefully it's ready to be picked up now!

**Comment by rhukster** [comment]
roger, will add it tomorrow.

**Comment by fredrikekelund** [comment]
@rhukster any updates on this one? :)

**Comment by rhukster** [comment]
added!

**Comment by fredrikekelund** [comment]
🤘
