### ISSUE TITLE
[add-resource] New Plugin "Recent Posts"

### ISSUE THREAD

**Issue by GittiHab** [getgrav/grav#1108]
I would like to add my new plugin to the Grav Repository.
Here are the project details: [Recent Posts Repository](https://github.com/GittiHab/grav-recent-posts)

**Comment by w00fz** [comment]
It looks like you tagged your release as `1.0.0` but your blueprints.yaml is saying `1.0`, this might cause issues.
You should update your blueprint and do a re-release for the 1.0.0.

**Comment by GittiHab** [comment]
Hey,
I just updated the `blueprints.yml` accordingly and re-released version `1.0.0`. I hope everything is fine now.

**Comment by rhukster** [comment]
Added to GPM
