### ISSUE TITLE
Saving system.yaml to see changes

### ISSUE THREAD

**Issue by PZ01** [getgrav/grav#1109]
Just started using Yaml. I added an alert('test') to one of the twig views and it does not load. When I save the system.yaml file and reload the page it then triggers. Whatever change I make, I need to save the system.yaml file. I'm using Nginx and the latest release. What could be causing this caching?

It's painful to work this way.

**Comment by flaviocopes** [comment]
Is the Twig cache disabled in the System settings? Disable the pages cache too when developing.

**Comment by PZ01** [comment]
Alright, looks like disabling both cache options in the Admin configuration section did the trick. I don't know if this is emphasized in the tutorial, but it might be worth putting it as a note. Thank you!
