### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by muuvmuuv** [getgrav/grav#1111]
I would like to add my new theme 'neonio' to the Grav Repository.
Here are the project details: https://github.com/muuvmuuv/grav-theme-neonio

**Comment by flaviocopes** [comment]
Create a release on the repository named 1.0.0 https://help.github.com/articles/creating-releases/

**Comment by muuvmuuv** [comment]
@flaviocopes done :).

**Comment by rhukster** [comment]
Added to GPM
