### ISSUE TITLE
Problematic order of duplicate assets

### ISSUE THREAD

**Issue by hundblue** [getgrav/grav#1112]
Suppose there are javascript asset collections declared as follows:

```
  'lib1' => 'plugin://xx/assets/lib1.js',
  'lib2' => ['lib1', 'plugin://xx/assets/lib2.js'],
  'lib3' => ['lib2', 'lib1'],
```

That is, lib2.js is dependent on lib1, and  the lib3 collection uses both lib1 and lib2. Since lib3 does not know/care that about interdependencies between lib1 and lib2 it happens that lib1 is listed after lib2. 
Currently (in version 1.1.5), the resolved order (as rendered via script tags) is :
plugin://xx/assets/lib2.js
plugin://xx/assets/lib1.js
In my opinion, the correct order should be reverse - the dependency of lib2 on lib1 should take precedence over the order given by the lib3 list.
More specifically, duplicately added assets should keep their original order. Thus, something like this should be added into the `addJs` method of the `Assets` class:

```
  if ( isset ($this->js[$key]) ) {  // duplicate entry, keep the original order
    $data['order'] = $this->js[$key]['order'];
  }
```

just before the final `$this->js[$key] = $data` assignment.

**Comment by rhukster** [comment]
This should be sorted in last couple of Grav updates as we now 'natsort' plugin loading.
