### ISSUE TITLE
possibility in asset manager to have async AND defer for JS

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav#1113]
actually, asset manager offers async OR defer.
As an enhancement, this issue is a request for async AND defer.
Thanks in advance.

**Comment by flaviocopes** [comment]
You can already. Simply use the syntax

```twig
{% do assets.addJs('theme://js/slidebars.min.js', {'priority':102, 'loading':'async defer'}) %}
```

**Comment by tidiview** [comment]
Thank you for answering: would it be possible to show this possibility in documentation: learn.get.grav?

**Comment by flaviocopes** [comment]
Thanks for the PR in Learn
