### ISSUE TITLE
Utils::truncateHTML removes whitespace when generating summaries

### ISSUE THREAD

**Issue by adamroe** [getgrav/grav#1114]
I have set my **Summary Size** high, so that only pages which have a **Summary Delimiter** have summaries generated on the list page. 

Unfortunately, in this instance when comparing `page.summary` and `page.content`, short articles which span multiple paragraphs which should otherwise have `page.summary == page.content` do not. This can be shown by dumping the variables:

```
{{ page.summary|var_dump }}
{{ page.content|var_dump }}
```

outputs 

```
string(53) "<p>This is a post.</p><p>It spans multiple lines.</p>"
string(54) "<p>This is a post.</p>
<p>It spans multiple lines.</p>"
```

I have developed a workaround by editing `/system/src/Grav/Common/Page/Page.php:summary()` to compare the string length of `$content` vs `$size`, so if content is shorter than the summary cut-off, just return the content as is:

```
		if (strlen($content) < $size) {
	         	         return html_entity_decode($content);
		} else {
	         	         $summary = Utils::truncateHTML($content, $size);
	         	         return html_entity_decode($summary);
		}
```

Is this a bug, or am I just missing something obvious? Is there a more graceful workaround?

**Comment by adamroe** [comment]
Incidentally, it effects images as well (summary vs. content)

```
string(68) "<p><img src="/user/pages/02.blog/no-splashing/no-splashing.jpg"></p>"
string(70) "<p><img src="/user/pages/02.blog/no-splashing/no-splashing.jpg" /></p>"
```

**Comment by rhukster** [comment]
The difference there is that the truncate uses DOM to understand the HTML so that its able to close any open HTML tags that happen to be left dangling at the truncation point.  However, when it does this it's going to make the HTML XHTML compliant (ie the `/>` on that image tag.  This can lead to differences in the content length.

The safest approach if you are having truncation issues is to use the manual summary delimiter (`---`) and use that in the place you want the summary to  stop.

**Comment by adamroe** [comment]
I have tried changing my `===` to `---` as the summary delimiter: rather than creating a summary it inserts a `<hr>`. I must be missing something obvious.

**Comment by adamroe** [comment]
Regardless, is there a better way of comparing `page.content` and `page.summary`? If there is a summary available I want to output a "read more" link, otherwise just have the content by itself. This behaviour causes a "read more" link to appear on every post.

The theme code in question:

```
{% if page.header.continue_link is sameas(false) %}
    {# ... #}
{% elseif truncate and page.summary != page.content %}
	{# summary available + link to full post #}
    {{ page.summary }}
    <p><a href="{{ page.url }}">Continue reading...</a></p>
{% elseif truncate %}
	{# post is short, no summary or link required #}
    {{ page.content }}
{% else %}
	{# single post page #}
{% endif %}
```

**Comment by flaviocopes** [comment]
This is what the snippet should do. Almost same as in the Antimatter theme:

```twig
    {% if page.header.continue_link is sameas(false) %}
        <div class="e-content">
            {{ page.content }}
        </div>
        {% if not truncate %}
        {% set show_prev_next = true %}
        {% endif %}
    {% elseif truncate and page.summary != page.content %}
        <div class="p-summary e-content">
            {{ page.summary }}
            <p><a href="{{ page.url }}">{{ 'BLOG.ITEM.CONTINUE_READING'|t }}</a></p>
        </div>
    {% elseif truncate %}
        <div class="p-summary e-content">
            {% if page.summary != page.content %}
                    {{ page.content|truncate(550) }}
                </div>
            {% else %}
                    {{ page.content }}

            {% endif %}
            <p><a href="{{ page.url }}">{{ 'BLOG.ITEM.CONTINUE_READING'|t }}</a></p>
        </div>
    {% else %}
        <div class="e-content">
            {{ page.content }}
        </div>

        {% if config.plugins.comments.enabled %}
            {% include 'partials/comments.html.twig' %}
        {% endif %}

        {% set show_prev_next = true %}
    {% endif %}
```

**Comment by adamroe** [comment]
That's what I based my snippet on... `page.summary` will always `!= page.content` if it splits multiple paragraphs, no matter the length. I have [created a test case](https://fortressofdoom.me/grav/) with the first two entries demonstrating the problem.

**Comment by flaviocopes** [comment]
Ok I see your point, we got "Continue reading" in Antimatter, even if there's no text after the intro.

"Continue reading" might not be what you want in your case, as you already removed it in your snippet.

I think what happens is page.summary is different because of the truncate editing the markup.

Try comparing them:

`{{ dump(page.content) }}{{dump(page.summary)}}`

**Comment by flaviocopes** [comment]
Re-reading the original topic, you already know that!

**Comment by flaviocopes** [comment]
I don't see an easy way to do this unless using a page header property

**Comment by adamroe** [comment]
Surely this isn't intended behaviour, right? 

The commit I referenced above fixes the issue—is that something that is likely to be merged or will I be amending `Page.php` after every update?

**Comment by flaviocopes** [comment]
Submit a PR with that change, we'll review it.
