### ISSUE TITLE
Caddyfile doesn't work

### ISSUE THREAD

**Issue by Fahrradflucht** [getgrav/grav#1115]
```
2016/10/18 21:30:44 webserver-configs/Caddyfile:9 - Parse error:
Wrong argument count or unexpected line ending after 'status'
```

```
➜  ~  caddy -version
Caddy 0.9.3
```

**Comment by flaviocopes** [comment]
Confirmed, worked with the Caddy version available when it was written (0.8.2), now it does not work any more.

**Comment by flaviocopes** [comment]
In particular, `status` is not working any more. A simpler Caddyfile like

```
localhost:8089 {
    gzip
    fastcgi / 127.0.0.1:9000 php
    rewrite {
        regexp .*
        ext    /
        to     /index.php?_url={uri}
    }
}
```

works fine. Looking into what changed.

**Comment by Fahrradflucht** [comment]
I found [this](https://github.com/mholt/caddy/issues/1012) yesterday but I'm not sure if it's related. I fixed it by rewriting to a path that I then put a status rule on. Like so:

```
rewrite {
    r /(.git|cache|bin|logs|backups|tests)/.*$
    to /denyaccess
}

rewrite {
    r /(system|vendor)/.*\.(txt|xml|md|html|yaml|php|pl|py|cgi|twig|sh|bat)$
    to /denyaccess
}

status 403 /denyaccess
```

but this seems kind of dirty doesn't it?

**Comment by flaviocopes** [comment]
With the Caddyfile format changes, I think it's the only way - pinged on the Caddy repo to check if there's another solution.

**Comment by flaviocopes** [comment]
Went on with the solution you proposed, which fixes the problem. Also kept a Caddyfile version for older releases, since this syntax does not work anymore for Caddy 0.8.x
