### ISSUE TITLE
Twig variables in front-matter not working?

### ISSUE THREAD

**Issue by rkrejcii** [getgrav/grav#1117]
I would like to use Twig variables in frontmatter, but actually I'm not able to get this working properly.

In `system.yaml` I have set:

```
frontmatter:
  process_twig: true  
```

And on page (in `default.md`) I've following frontmatter:

```
---
title: {{ site.title }}
---
```

When I open given page, I'm getting

```
Error: Invalid Frontmatter
...
Unexpected characters near "}" at line 1 (near "title: {{ site.title }}").
```

All this with fresh installation of Grav Core with Admin plugin.

Thanks for any hint.

**Comment by flaviocopes** [comment]
Wrap it in quotes: `title: "{{ site.title }}"`

But, it won't be processed. Twig is processed inside the page content, not in the page header.

**Comment by rhukster** [comment]
Just tested this and confirmed that @flaviocopes' example works.  BTW, it will process it in the page header as you have your `frontmatter.process_twig` config set to `true`

**Comment by rhukster** [comment]
Please let me know when you have tested/confirmed this fix.. and i'll close this.

**Comment by flaviocopes** [comment]
Missed that option! Works, just wrap in quotes @rkrejcii

**Comment by Sogl** [comment]
@flaviocopes I tried as you mentioned.

In `system\config\system.yaml`:
```
frontmatter:
    process_twig: true 
```

And in my `md` header:
```
download_button_url: "{{ grav.language.getLanguage }}/downloads/story.pdf"
```

Also tried:
```
download_button_url: "{{ site.title }}"
```

Doesn't work :disappointed:
Cache is disabled by also was  cleared in admin panel.

**Comment by Sogl** [comment]
Problem was in these lines in `frontmatter.yaml`:
```
process:
    twig: false
```

set to `true` solved it.
