### ISSUE TITLE
using new GRAV (behind a proxy): themes and plugins in admin plugin failed

### ISSUE THREAD

**Issue by oscon** [getgrav/grav#1118]
When I choose themes or plugins page in the admin plugin. GRAV crashed with the following error:
"An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable") in "partials/plugins-list.html.twig" at line 20."

GRAV ist installed on a XAMPP (Windows) 3.2.2 environment behind a proxy, which uses an authentification (user, pw).

**Comment by flaviocopes** [comment]
in the system settings, try turning off "Remote Verify Peer (SSL)", does it change something?

**Comment by oscon** [comment]
No unfortunately not: same error
the advanced configuration in den admin plugin looks like this
![grav-advanced](https://cloud.githubusercontent.com/assets/478932/19597172/328a990a-9793-11e6-9b1d-b64481f69455.jpg)
is there a possibility to configure user and password for the proxy?

**Comment by flaviocopes** [comment]
Sure, use the `user:password@host:post` format in the Proxy URL field

**Comment by oscon** [comment]
still the same problem...
let's wait the next version as rhukster described?

**Comment by flaviocopes** [comment]
The new release is already out, version 1.1.8

**Comment by oscon** [comment]
...and still the same error...

**Comment by oscon** [comment]
Maybe there should be a possibility, to disable the online connection to the GRAV repository, if the admin plugin is used?

**Comment by flaviocopes** [comment]
Try clearing the browser cache, to clear any cached Javascript file. Or open a new session in Incognito(private) mode.

**Comment by oscon** [comment]
clear all cache in Firefox
ctrl-shift-p in Firefox
localhost/striped/admin -> plugins or themes
=> same error
![grav-error](https://cloud.githubusercontent.com/assets/478932/19690060/a6367b28-9acf-11e6-95e3-e9744f4dc1d4.jpg)

**Comment by flaviocopes** [comment]
Are the requirements listed in https://learn.getgrav.org/troubleshooting/common-problems#cannot-connect-to-the-gpm satisfied ?

**Comment by oscon** [comment]
- OpenSSL / curl are enabled
- Proxy is enabled and set
- Remote Verify Peer (SSL) is set to false
- bin/gpm index
faioswal@WS01409279 e:\xampp\htdocs\striped
# e:/xampp/php/php bin/gpm index
PHP Warning:  Module 'openssl' already loaded in Unknown on line 0

Warning: Module 'openssl' already loaded in Unknown on line 0
PHP Notice:  Undefined index: host in E:\xampp\htdocs\striped\system\src\Grav\Co
mmon\GPM\Response.php on line 141

Notice: Undefined index: host in E:\xampp\htdocs\striped\system\src\Grav\Common\
GPM\Response.php on line 141
PHP Notice:  Undefined index: host in E:\xampp\htdocs\striped\system\src\Grav\Co
mmon\GPM\Response.php on line 145

Notice: Undefined index: host in E:\xampp\htdocs\striped\system\src\Grav\Common\
GPM\Response.php on line 145

GPM Releases Configuration: Stable

No data was found in the GPM repository stored locally.
Please try clearing cache and running the bin/gpm index -f command again
If this doesn't work try tweaking your GPM system settings.

For more help go to:
 -> https://learn.getgrav.org/troubleshooting/common-problems#cannot-connect-to-
the-gpm

faioswal@WS01409279 e:\xampp\htdocs\striped
#

**Comment by flaviocopes** [comment]
The notices look related to the proxy URL. What's the value you entered for it?

**Comment by oscon** [comment]
faioswal:<mypassword>@192.168.10.56:8088

**Comment by flaviocopes** [comment]
Prepend the protocol too, `http://myuser:mypassword@192.168.10.56:8088` otherwise `parse_url()` interprets it wrong:

```
26-Oct-2016 15:55:49 Europe/Rome] array(2) {
  ["scheme"]=>
  string(6) "myuser"
  ["path"]=>
  string(29) "mypassword@192.168.10.56:8088"
}
```

instead of

```
[26-Oct-2016 15:56:29 Europe/Rome] array(5) {
  ["scheme"]=>
  string(5) "http"
  ["host"]=>
  string(13) "192.168.10.56"
  ["port"]=>
  int(8088)
  ["user"]=>
  string(6) "myuser"
  ["pass"]=>
  string(10) "mypassword"
}
```

**Comment by oscon** [comment]
Thanks for the hint. Tried it out, but the result was the same error: any ideas?
"An exception has been thrown during the rendering of a template ("GPM not reachable. Please check your internet connection or check the Grav site is reachable") in "partials/plugins-list.html.twig" at line 20."
![grav-error1](https://cloud.githubusercontent.com/assets/478932/19730853/ccbe99ca-9b9b-11e6-9ac0-08cdaa203c25.jpg)

**Comment by oscon** [comment]
As a workaround, set the following line in E:\xampp\htdocs\striped\user\plugins\admin\themes\grav\templates\partials\plugins-list.html.twig and \themes-list.html.twig inactive (in TWIG-comments) and admin plugin works without any problems behind (our) proxy:

plugins (line 20):
 {#       {% set releaseDate = plugin.date ?: admin.gpm.findPackage(slug).date %} #}

themes (line 21):
{#        {% set releaseDate = theme.date ?: admin.gpm.findPackage(slug).date %} #}

**Comment by flaviocopes** [comment]
The problem is now "hidden", you can see the plugins and themes settings now but you still can't install/update packages

**Comment by oscon** [comment]
That's okay like that: So I can at least develop behind the firewall without the errors
for updating: themes and plugins will be copy manually into the directories, no problem!
