### ISSUE TITLE
Quick Save (CMD+S) No Longer Saves Pages

### ISSUE THREAD

**Issue by marcodeluca** [getgrav/grav#1119]
Just updated to Grav v1.1.6 - Admin v1.2.3

When editing a page using the admin plugin, using CMD+S on a mac to save the page, the page refreshes with the success message "Successfully saved" but the page content does not change. All changes are lost. This worked before (although I may have missed a few updates).

**Comment by flaviocopes** [comment]
I can replicate the problem

**Comment by flaviocopes** [comment]
Fixed by https://github.com/getgrav/grav-plugin-admin/pull/832
