### ISSUE TITLE
Missing translation for PLUGIN_ADMIN.REDIS_SOCKET in Admin plugin

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav#1123]
I have just tried Grav v1.1.6 with Admin v1.2.3 and I notice that there is a label which doesn't have English translation in Configuration

I attach the screenshot.
![screencapture-localhost-clean-blog-admin-config-system-1477031472606](https://cloud.githubusercontent.com/assets/503262/19588933/35e942cc-9793-11e6-991f-b698a887fa33.png)

**Comment by flaviocopes** [comment]
Thanks for reporting, fixed
