### ISSUE TITLE
Include multiple partials

### ISSUE THREAD

**Issue by AndiLeni** [getgrav/grav#1126]
Hello,
I want to ask whether there is a way to include multiple code snippets/partials in one theme. Couldn't figure out how to do this. Thanks

**Comment by Perlkonig** [comment]
Can you clarify? You can have as many `include` statements as you want in a template. Where exactly are you running into trouble?

**Comment by AndiLeni** [comment]
I have several partials with different contents. All of them contain some code for example a navbar. I need to include those partials into my default theme. But when I try to archive this I get the "Did you forget the {% block %} tags?" message

**Comment by Perlkonig** [comment]
We'd need to see some code. It sounds like you may be confusing the twig primitives [`embed`](http://twig.sensiolabs.org/doc/tags/embed.html), [`extends`](http://twig.sensiolabs.org/doc/tags/extends.html), and [`include`](http://twig.sensiolabs.org/doc/tags/include.html). You can also look at the [default "new theme" templates](https://github.com/getgrav/grav-plugin-devtools/tree/develop/components/theme/pure-blank/templates) and see how yours differ.

**Comment by flaviocopes** [comment]
Closing as not a Grav issue but an issue in your Twig template. @Perlkonig suggestion should already solve your doubt, comment if not.
