### ISSUE TITLE
resize images dynamically not working

### ISSUE THREAD

**Issue by leotop** [getgrav/grav#113]
Function
http://learn.getgrav.org/content/media
    Sample Image](sample-image.jpg?resize=50,50)

/user/pages/01.home/sample-image.jpg
/user/pages/01.home/images/sample-image.jpg
/user/pages/images/sample-image.jpg
/images/sample-image.jpg

not working. In url add /images/sample-image.jpg?resize=50,50 not resizing or give another path for picture.

**Comment by leotop** [comment]
if I use 
{{ dump(page.media['sample-image.jpg']) }}
resize with twig work, md not work

**Comment by rhukster** [comment]
I'm assuming you also posted in the forums? Please check my reply there first:

http://getgrav.org/forum#!/general:media-image-actions-dont
