### ISSUE TITLE
[add-resource] New Skeleton

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav#1130]
For your consideration: [Perlkonig/grav-skeleton-knowledge-base](https://github.com/Perlkonig/grav-skeleton-knowledge-base)

This is my first skeleton package. Let me know if I blew something up. I just copied and edited the `.dependencies` file. I don't actually understand how it works 😄

**Comment by rhukster** [comment]
I've added this, but it won't work with just a .dependency file. You need to actually build the whole ZIP package and upload it and add it to the release for the skeleton.

http://diblas.net/blog/how-to-build-a-grav-skeleton

**Comment by Perlkonig** [comment]
Ahh! Thanks for the link. Will do that ASAP.

**Comment by Perlkonig** [comment]
Like that? I couldn't run the script linked because I don't have access to composer CLI. I just walked through the script manually.

**Comment by rhukster** [comment]
I think you have some missing plugins (simplesearch for example).  The package should basically unzip and just 'work', as you can see below, the current one does not.

![2016-10-31 at 1 17 pm](https://cloud.githubusercontent.com/assets/1084697/19868139/60a5f6d2-9f6c-11e6-9c13-4151f71a9551.png)

**Comment by Perlkonig** [comment]
I see. So that `composer create-project` line is what runs the the `.dependencies` file? I don't have access to `composer` CLI on my host. I'll have to do it manually.

I'll try again tonight when I'm at my home setup and can properly test.

**Comment by rhukster** [comment]
`bin/grav install` should install stuff from .dependencies

**Comment by Perlkonig** [comment]
OK. So manually I need to do the following:

  * Download and extract the latest Grav.
  * Delete `user` folder and replace with sample content.
  * Run `bin/grav install` to install all plugins (and theme?).
  * Zip it up.
  * Extract somewhere accessible by your webserver and test.
  * If it's good, then upload zip file to GitHub.

When a later Grav version is released, do I just update the ZIP file of my current release? Or should I bump the version number and create a new release?

**Comment by rhukster** [comment]
If your skeleton is not actually changing, i would just rebuild with newer versions of things and re-upload to current release

**Comment by Perlkonig** [comment]
Now I'm getting parsing errors with my `.dependencies` file. Is it being parsed as YAML? Also, do I have to also list all the dependencies in the theme blueprint file *as well as* in the `.dependencies` file?

**Comment by Perlkonig** [comment]
I'm not motivated enough to make this work right now. Maybe it's just the incessant doorbell ringing (man do I hate Halloween), but my brain is not grokking things. Closing this for now. I'll try again another day, perhaps.

**Comment by rhukster** [comment]
I hear ya, we've had near 100 kids come by tonight!

**Comment by rhukster** [comment]
Btw I really don't want to add some support to this in the devtools plugin. We have a shell script we use in our builds, but a simple version than can be run from the cli would be handy right ?

**Comment by w00fz** [comment]
FYI we have `devtools` (not to be confused with the plugin) which is a very close version to what we use for building up our skeletons automatically.

I haven't kept an eye on it in a while but it should still work and you should be able to create a skeleton in a more conventional and easy way with it.

https://github.com/getgrav/devtools

**Comment by Perlkonig** [comment]
It would. Better would be some documentation. Again, it may just be me. I just don't understand how all the parts are fitting together. If the theme is set up properly (and I see I need to go back and add the dependencies to mine), and a git repository containing the user folder is up (as is mine), the rest should be eminently automatible (that's not even a word). Anyway, brain fried, and I don't plan on doing any front-end development in the near future, so I'll stick to the plugins for now. I'll come back to this later on. Thanks, though!

**Comment by rhukster** [comment]
Yah i have it on my list to document better.. but here's the gist of it anyway:

1) install fresh grav into 'some directory'
2) copy / clone your skeleton repo as 'user' folder in this site
3) this skeleton should have a `.dependencies` file at the root of it, ie `user/.dependencies` after copy/cloning.  Your skeleton should contain config, pages, etc, but nothing in `user/plugins` or `user/themes`.  Your `.dependencies` file should have references for this.

Example:

```
git:
    archives:
        url: https://github.com/getgrav/grav-plugin-archives
        path: user/plugins/archives
        branch: master
    breadcrumbs:
        url: https://github.com/getgrav/grav-plugin-breadcrumbs
        path: user/plugins/breadcrumbs
        branch: master
    error:
        url: https://github.com/getgrav/grav-plugin-error
        path: user/plugins/error
        branch: master
    feed:
        url: https://github.com/getgrav/grav-plugin-feed
        path: user/plugins/feed
        branch: master
    pagination:
        url: https://github.com/getgrav/grav-plugin-pagination
        path: user/plugins/pagination
        branch: master
    problems:
        url: https://github.com/getgrav/grav-plugin-problems
        path: user/plugins/problems
        branch: master
    random:
        url: https://github.com/getgrav/grav-plugin-random
        path: user/plugins/random
        branch: master
    relatedpages:
        url: https://github.com/getgrav/grav-plugin-relatedpages
        path: user/plugins/relatedpages
        branch: master
    simplesearch:
        url: https://github.com/getgrav/grav-plugin-simplesearch
        path: user/plugins/simplesearch
        branch: master
    sitemap:
        url: https://github.com/getgrav/grav-plugin-sitemap
        path: user/plugins/sitemap
        branch: master
    taxonomylist:
        url: https://github.com/getgrav/grav-plugin-taxonomylist
        path: user/plugins/taxonomylist
        branch: master
    antimatter:
        url: https://github.com/getgrav/grav-theme-antimatter
        path: user/themes/antimatter
        branch: master
links:
    archives:
        src: grav-plugin-archives
        path: user/plugins/archives
        scm: github
    breadcrumbs:
        src: grav-plugin-breadcrumbs
        path: user/plugins/breadcrumbs
        scm: github
    error:
        src: grav-plugin-error
        path: user/plugins/error
        scm: github
    feed:
        src: grav-plugin-feed
        path: user/plugins/feed
        scm: github
    pagination:
        src: grav-plugin-pagination
        path: user/plugins/pagination
        scm: github
    problems:
        src: grav-plugin-problems
        path: user/plugins/problems
        scm: github
    random:
        src: grav-plugin-random
        path: user/plugins/random
        scm: github
    relatedpages:
        src: grav-plugin-relatedpages
        path: user/plugins/relatedpages
        scm: github
    simplesearch:
        src: grav-plugin-simplesearch
        path: user/plugins/simplesearch
        scm: github
    sitemap:
        src: grav-plugin-sitemap
        path: user/plugins/sitemap
        scm: github
    taxonomylist:
        src: grav-plugin-taxonomylist
        path: user/plugins/taxonomylist
        scm: github
    antimatter:
        src: grav-theme-antimatter
        path: user/themes/antimatter
        scm: github
```

The `git:` bit above is what you'll need for the skeleton builder.. `links:` bit is used for `-s` sym link stuff.

4) Now from the root of your site, run:

```
$ bin/grav install
```

This will use the .dependencies file it finds in `user/` to install all that stuff you reference (plugins, theme).

5) At this point, your site should be fully functioning.  Just zip it up and attach that to your release.

**Comment by Perlkonig** [comment]
Well I have a working demo site, so theoretically I should just be able to zip that up, but nobody else will be able to rebuild it because the `.dependencies` file is not parsing properly (something with `count-views`; is it parsed as YAML?). I also need to add the dependencies to the theme's `blueprints.yaml`. Finally turning off the lights and going to bed. Maybe this will all be clear in the morning 😄

**Comment by Perlkonig** [comment]
Finally figured it out. I'm just blind. Fixed the `.dependencies` file and released. It seems to be working now. Let me know.

**Comment by Perlkonig** [comment]
You apparently added it already. Thanks.
