### ISSUE TITLE
PROBLEM with PARSING OF JAPANESE after UPGRADE to 1.1.6

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav#1134]
after UPGRADE to 1.1.6, I experienced a change into PARSING OF JAPANESE

a LINK like this in `item.ja.md`:
`https://www.amazon.co.jp/%E8%AB%B8%E5%AD%90%E7%99%BE%E5%AE%B6%E2%80%95%E2%80%95%E4%B8%AD%E5%9B%BD%E5%8F%A4%E4%BB%A3%E3%81%AE%E6%80%9D%E6%83%B3%E5%AE%B6%E3%81%9F%E3%81%A1-%E5%B2%A9%E6%B3%A2%E6%96%B0%E6%9B%B8-%E8%B2%9D%E5%A1%9A-%E8%8C%82%E6%A8%B9/dp/4004130476/378-6956610-7563751?ie=UTF8&*Version*=1&*entries*=0`

got OUTPUT _interpretated_:
`https://www.amazon.co.jp/諸�__百家――��_国�_�代�_���_想家�_��_�-岩波新書-��_塚-茂樹/dp/4004130476/378-6956610-7563751?ie=UTF8&%2AVersion%2A=1&%2Aentries%2A=0`

THIS MAKES LINK **_UNUSABLE_**

wonder if it is not related to `CHANGELOG`:
- `Added Utils::getExtensionByMime() and cleaned up Utils::getMimeByExtension + tests`
  or
- `Updated vendor libs including Twig 1.25.0`

What should I do? (sorry to write that on _sunday_!)

**Comment by rhukster** [comment]
Without being able to read japanase, can you provide me with an example of what the **markdown** looks like, what output is **expected** and what is **actually output**..

**Comment by tidiview** [comment]
please, don't be AFRAID by japanese but consider the problem from a informatical point of view: it's long but not complicated.

basically, I have some blog posts called `item.ja.md` with some reference links into them like:

**1)** in body of blog post (eg: after frontmatter), something like in the middle of some text, a markdown formatted link formed `[some text][2]`:

 ` some text in japanese ... 書いた「` (after is the link>) `[{r}諸子百家{/r:しょしひゃっか}][2]` (<before was the link) `」を読んで、...  some text in japanese`

1) in the text of blog post, [{r}諸子百家{/r:しょしひゃっか}][2] is a markdown formatted link marked `[2]` on part of text `{r}諸子百家{/r:しょしひゃっか}` (please note: this part of text is having a syntax with `{r]` and `{/r: ... }` because it's using plugin `markdown-rubytext` for styling to ruby)

**2)** 

`[2]: https://www.amazon.co.jp/%E8%AB%B8%E5%AD%90%E7%99%BE%E5%AE%B6%E2%80%95%E2%80%95%E4%B8%AD%E5%9B%BD%E5%8F%A4%E4%BB%A3%E3%81%AE%E6%80%9D%E6%83%B3%E5%AE%B6%E3%81%9F%E3%81%A1-%E5%B2%A9%E6%B3%A2%E6%96%B0%E6%9B%B8-%E8%B2%9D%E5%A1%9A-%E8%8C%82%E6%A8%B9/dp/4004130476/378-6956610-7563751?ie=UTF8&*Version*=1&*entries*=0 "https://www.amazon.co.jp/諸子百家――中国古代の思想家たち-岩波新書-貝塚-茂樹/dp/4004130476/378-6956610-7563751?ie=UTF8&*Version*=1&*entries*=0"`

2) after the 1) text, at bottom of  `item.ja.md`, the reference of markdown formatted link [2] referenced above has two parts, part a) and part b), like all markdown formatted link following structure `[2]: src "title"` :

`part a)` is part `src` of `<link>` HTML tag:

`https://www.amazon.co.jp/%E8%AB%B8%E5%AD%90%E7%99%BE%E5%AE%B6%E2%80%95%E2%80%95%E4%B8%AD%E5%9B%BD%E5%8F%A4%E4%BB%A3%E3%81%AE%E6%80%9D%E6%83%B3%E5%AE%B6%E3%81%9F%E3%81%A1-%E5%B2%A9%E6%B3%A2%E6%96%B0%E6%9B%B8-%E8%B2%9D%E5%A1%9A-%E8%8C%82%E6%A8%B9/dp/4004130476/378-6956610-7563751?ie=UTF8&*Version*=1&*entries*=0`
`part b)` is `title of `<link>` HTML tag`:

`"https://www.amazon.co.jp/諸子百家――中国古代の思想家たち-岩波新書-貝塚-茂樹/dp/4004130476/378-6956610-7563751?ie=UTF8&*Version*=1&*entries*=0"`

This is an example among many on other blog posts that have the same problem.


Problem is:
- BEFORE `update 1.1.6,`, HTML `link` tags would be PERFECT (not interpretated)
- AFTER `update 1.1.6,`, HTML `link` tags are interpretated and output like:
for part a)  `src` of `<link>` of HTML tag > PROBLEM:

`https://www.amazon.co.jp/諸�__百家――��_国�_�代�_���_想家�_��_�-岩波新書-��_塚-茂樹/dp/4004130476/378-6956610-7563751?ie=UTF8&%2AVersion%2A=1&%2Aentries%2A=0`
for part b)  `title` of `<link>` of HTML tag > NO PROBLEM:

`https://www.amazon.co.jp/諸子百家――中国古代の思想家たち-岩波新書-貝塚-茂樹/dp/4004130476/378-6956610-7563751?ie=UTF8&*Version*=1&*entries*=0"`


OUTPUT:
`<a src="PROBLEM" title="NO PROBLEM"></a>`


As in previous post, I wonder if it is not related to `CHANGELOG` of `update 1.1.6,`:
- `Added Utils::getExtensionByMime() and cleaned up Utils::getMimeByExtension + tests`
OR
- `Updated vendor libs including Twig 1.25.0`


If needed, I can provide folder `user` for replication.

Thanks ☆

(it's more than middle of night time in France; good night!)

**Comment by tidiview** [comment]
#

**Comment by flaviocopes** [comment]
I can't replicate the problem - please note that `<a src="..">` is not valid HTML for a link, but instead it should be `<a href="...">`.

In your long description you didn't tell how to exactly replicate the issue. I put 

```

<a href="https://www.amazon.co.jp/%E8%AB%B8%E5%AD%90%E7%99%BE%E5%AE%B6%E2%80%95%E2%80%95%E4%B8%AD%E5%9B%BD%E5%8F%A4%E4%BB%A3%E3%81%AE%E6%80%9D%E6%83%B3%E5%AE%B6%E3%81%9F%E3%81%A1-%E5%B2%A9%E6%B3%A2%E6%96%B0%E6%9B%B8-%E8%B2%9D%E5%A1%9A-%E8%8C%82%E6%A8%B9/dp/4004130476/378-6956610-7563751?ie=UTF8&*Version*=1&*entries*=0">test</a>

[link](https://www.amazon.co.jp/%E8%AB%B8%E5%AD%90%E7%99%BE%E5%AE%B6%E2%80%95%E2%80%95%E4%B8%AD%E5%9B%BD%E5%8F%A4%E4%BB%A3%E3%81%AE%E6%80%9D%E6%83%B3%E5%AE%B6%E3%81%9F%E3%81%A1-%E5%B2%A9%E6%B3%A2%E6%96%B0%E6%9B%B8-%E8%B2%9D%E5%A1%9A-%E8%8C%82%E6%A8%B9/dp/4004130476/378-6956610-7563751?ie=UTF8&*Version*=1&*entries*=0)
```

In a page, and both URLs were opened correctly to that Amazon item. Does this markdown above work for you?

**Comment by tidiview** [comment]
I don't really see how to replicate the issue so I suggest that I send to you the `user` folder so that you can replicate in the exact same conditions (I will give precise indications -what page to look at- at that moment, if you agree).

I apologize I made a mistake in my description; after your comment, I checked again, and it's `href` and not `src`; I don't really understand why I made such a mistake, but anyway, consider that when I wrote `src`, in code, it's in fact `href`.

To answer your question, link was opened correctly to that Amazon item before upgrade; after, not anymore.

**Comment by flaviocopes** [comment]
Did you try the snippet I posted above in one of your pages? Does it have the problem?

**Comment by tidiview** [comment]
I did try that before to post an issue, and the result convince me of write it.

In those pages, I am using shotcode-core plugin and other things that makes a particular context so that it is probably meaningful to test in the exactly same conditions.

**Comment by flaviocopes** [comment]
Send me the `user` folder via gitter.im/flaviocopes

**Comment by tidiview** [comment]
Done!

**Comment by flaviocopes** [comment]
We discussed on Gitter but never been able to recreate the problem on my end.
