### ISSUE TITLE
Collection#random generates warning when passing int larger than collection count

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav#1135]
If I do this:

```php
$taxonomy_map = $this->grav['taxonomy'];

$collection = $taxonomy_map->findTaxonomy([
    'type' => $term
]);

$collection->random(4);
```

And `$collection` contains fewer than 4 pages, I get an error:

> array_rand(): Second argument has to be between 1 and the number of elements in the array

Maybe throwing an error is the right thing to do here, if I ask for 4 pages, maybe I should be able to always expect 4 pages. But a manual check in `Collection#random` that `$num` is smaller than the collection count, and a more user friendly error message if that's not the case, might be helpful!

**Comment by Perlkonig** [comment]
The error message seems pretty user friendly. The only problem is the `random` function itself isn't mentioned. If you pass a number larger than the count, should [the function](https://github.com/getgrav/grav/blob/7710cba7ad6b5c24a5caab94b4d067db5d1abaf2/system/src/Grav/Common/Iterator.php#L183-L195) just silently change the number to `count(array)`?

```php
if ($num > count($this->items)) {
    $num = count($this->items);
}
```

**Comment by flaviocopes** [comment]
I think so, so if you ask for 4 but you only got 2, 2 are returned without any error.
