### ISSUE TITLE
Grav's Responsive Images functionality not working/working differently

### ISSUE THREAD

**Issue by nineteeneightyeight** [getgrav/grav#1136]
(https://learn.getgrav.org/content/media#responsive-images)

Since updating Grav (to 1.1.8) my client's site has been getting some errors relating to the responsive images support. In the admin plugin, when selecting an image from the dropdown it is now showing 'image@3x.jpg' - previously that would have been 'image.jpg' - because the responsive images functionality within Grav would have done it's magic and generated 3 images (i.g. image.jpg, image@2x.jpg and image@3x.jpg).

If the image is set to just 'image.jpg' within the markdown itself, then an error occurs:

```
Whoops\Exception\ErrorException thrown with message "imagecreatetruecolor(): product of memory allocation multiplication would exceed INT_MAX, failing operation gracefully
"

Stacktrace:
#0 Whoops\Exception\ErrorException in /home/grav/www/html/vendor/gregwar/image/Gregwar/Image/Adapter/GD.php:77
```

**Comment by flaviocopes** [comment]
From which dropdown you select an image? A `filepicker` field?

**Comment by flaviocopes** [comment]
I tried uploading a `image@3x.png` image in the Page Media and inserted it as `![](image.png)` in the markdown, was added correctly in the frontend as 

```
<img src="/grav-develop/images/2/3/6/7/7/2367706e56f8dce23de92170318e212d8a219a0f-image1x.png" srcset="/grav-develop/images/2/a/5/2/c/2a52cf157245687258079bb23c6223745d95e163-image3x.png 1200w, /grav-develop/images/e/9/f/1/3/e9f1303f0ca4f3f35d90bb08bd4c43cd11b8aefd-image2x.png 800w, /grav-develop/images/2/3/6/7/7/2367706e56f8dce23de92170318e212d8a219a0f-image1x.png 400w" sizes="100vw">
```

**Comment by nineteeneightyeight** [comment]
I select the file using a `pagemediaselect`.

Sorry, when I said markdown I meant within the Frontmatter.

The image is output in the template as follows:

```
{% set header_image = page.header.header_image|defined(true) %}
{% set header_image_width  = page.header.header_image_width|defined(540) %}
{% set header_image_height = page.header.header_image_height|defined(480) %}
{% set header_image_file = page.header.header_image_file %}

{% if header_image %}
    {% if header_image_file %}
        {% set header_image_media = page.media.images[header_image_file] %}
     {% else %}
         {% set header_image_media = page.media.images|first %}
     {% endif %}
        
     {{ header_image_media.cropZoom(header_image_width, header_image_height).html }}
{% endif %}
```

**Comment by flaviocopes** [comment]
`pagemediaselect` since the latest release is now an alias for `filepicker` and this might have caused your issue, as it uses raw files instead of page media.

I think this change https://github.com/getgrav/grav-plugin-admin/commit/a42fd33c4ff1c3ae9a81ce8d7d23e85813e5f6da is going to fix your issue. You can try it now by downloading the latest develop branch of Admin from https://github.com/getgrav/grav-plugin-admin/archive/develop.zip

**Comment by nineteeneightyeight** [comment]
As far as being able to select the image from the dropdown - that seems to be fixed by using the admin plugin fix you mentioned. However, the main issue is still there. I'm still getting an error message from Grav Core (I believe), when using these images.

I assume it's something to do with the automatic generation of these responsive images.

**Comment by flaviocopes** [comment]
I've not been able to recreate it yet, I wonder if it's a Grav issue or rather a GD library issue http://stackoverflow.com/questions/20614686/gd-warning-product-of-memory-allocation-multiplication-would-exceed-int-max

**Comment by rhukster** [comment]
How big is your image? Can you attach it here so I can test with it?

**Comment by thedistricts** [comment]
@rhukster [test-3ximage.zip](https://github.com/getgrav/grav/files/561539/test-3ximage.zip)

**Comment by flaviocopes** [comment]
Thanks, I tried but I can't replicate any error when using the images locally.

**Comment by thedistricts** [comment]
Is that replicating uploading the image on v1.0.10 and then upgrading Grav v1.1.8?

**Comment by fredrikekelund** [comment]
This was introduced due to my changes in #1107. Sorry about that! Submitted a PR that should fix the problem

**Comment by fredrikekelund** [comment]
Just a note on this one – this bug would basically affect any case where users try to use image alternatives (either as supplied from disk, or generated by `ImageMedium#derivatives`) in combination with image filters. So perhaps it would be good to do push a minor release to fix this

**Comment by fredrikekelund** [comment]
@flaviocopes @rhukster sorry about troubling you with this, but I think the change change might warrant a bugfix release – see my previous comment for details
