### ISSUE TITLE
Custom template for tag-archive

### ISSUE THREAD

**Issue by daku-souru** [getgrav/grav#1138]
I want to create a custom template for the tag archive of my blog. Sadly I cannot find any way to achieve this in the config. Grav is always loading the template of my homepage. Does anyone have an idea for a proper solution?

Thanks

**Comment by Perlkonig** [comment]
You're trying to create a single page that simply lists all tags? Create a new template file (something like `user/themes/mytheme/templates/tags.html.twig`) and then create a `tags.md` file wherever in your page hierarchy you want.

**Comment by daku-souru** [comment]
Hi. Not really. I list the tags of an article beneath the content. If the user clicks on it, GRAV will attach the tagname to the URL like this: www.xyz.com/tag:example. My goal is to load a separate template for those sites. If there is another way of handling the tag archive sites then I'm more than willing to try it as well.

**Comment by Perlkonig** [comment]
I'm not sure if there's a way to directly override that. I had the same question a while back and never found an answer. Maybe someone else will chime in. You can certainly create your own `/tag` route (or whatever) with your own template that takes and processes query parameters (e.g., [how I ended up doing it](https://github.com/Perlkonig/grav-theme-knowledge-base/blob/master/templates/taxonomy.html.twig). )

**Comment by daku-souru** [comment]
Thank you Perlkonig. I will try this out and hope it'll work for me.

**Comment by rhukster** [comment]
Closing to due to inactivity
