### ISSUE TITLE
Include page content of another page

### ISSUE THREAD

**Issue by philipisik** [getgrav/grav#1139]
Hi folks! Is it possible to include the content of a page into another page? I don't get any useful results, when I'm searching this question. 

I have a page with "about us" content, which should included as a modal in every page. So I need to include the `{{ page.content }}` from the "about us" page into the `base.html.twig`. Is this possible?

Regards Philip

**Comment by rhukster** [comment]
Very possible: https://github.com/getgrav/grav-plugin-page-inject is the easiest way.  Alternatively you can use twig:

```
{{ page.find('/some/other.page').content }}
```

If you want to include the same twig template with the same content on every page, you can put do that right in the twig:

```
{% set page = page.find('some/other/page') %}

<div id="about-us">
  {{ page.content }}
</div>
```

**Comment by philipisik** [comment]
Perfect! Thank you very much, works fine :-)

**Comment by parijke** [comment]
Is the same possible with modular content?

**Comment by paulhibbitts** [comment]
Hi @parijke , yes it is. If I remember correctly for the Page Inject plugin just added the underscore ('_') character to insert modular content. For example:

```
[plugin:content-inject](/ux-techniques-guide/_user-interface-design)
```
