### ISSUE TITLE
image

### ISSUE THREAD

**Issue by 789x** [getgrav/grav#1140]
```
![](bg_fb_cover.jpg)
```

dont show anything on my end. the image is already in the same folder (home). I am using default template, markdown and twig is on.

**Comment by rhukster** [comment]
No clue what you are asking, i just see a broken image in single ticks...

**Comment by rhukster** [comment]
No idea what your asking here. I only see a broken image in single ticks.

**Comment by 789x** [comment]
exclamation braces then  filename in parenthesis

im putting the code but markdown processes it as image which cannot be found here

**Comment by rhukster** [comment]
Please use back ticks around your code ( ```)

**Comment by 789x** [comment]
im trying the sample of the markdown as well but not processing on grav https://guides.github.com/features/mastering-markdown/

**Comment by 789x** [comment]
```
![](bg_fb_cover.jpg)
```

thanks for the time looking at this... been a headache... i tried putting it on images folder and calling the path but same thing happens

**Comment by rhukster** [comment]
if you have an image called `my-image.jpg` in your page's folder.. ie:

```
01.home
  - default.md
  - my-image.jpg
```

then in `default.md` you can just have:

```
# title

![](my-image.jpg)
```

This should just _work_

**Comment by 789x** [comment]
```
# All Workers Unity
![](bg_fb_cover.jpg)
# **** <p style="text-align: center;">All Workers Unity (AWU) is a national campaign network uniting all sectors for the implementation of a National Minimum Wage in the amount of P750 daily for the private sector & P16,000 monthly for the public sector and --the Banning of Contractualization in PH.</p>****

```
you can check out this at allworkersunity.com

files in the 'home' folder are default.md and bg_fb_cover.jpg

**Comment by rhukster** [comment]
try this:

```
# All Workers Unity

![](bg_fb_cover.jpg)

# **** <p style="text-align: center;">All Workers Unity (AWU) is a national campaign network uniting all sectors for the implementation of a National Minimum Wage in the amount of P750 daily for the private sector & P16,000 monthly for the public sector and --the Banning of Contractualization in PH.</p>****
```

BTW, you can't put HTML inside a Markdown element, so your `# **** <p style...` will not be displayed as you expect, just use `<h1>` tag if you plan to use other HTML mixed in there.  Also you can't put a `<p>` tag in an `<h1>` tag anyway, that's invalid HTML.

**Comment by 789x** [comment]
its working on the website http://allworkersunity.com 

seems strange that image dont work

**Comment by rhukster** [comment]
ok, guess that mixing Markdown does work there.. weird as it's not technically valid.

Anyway, regarding the image i see a possible problem.  It's generating retina images for this image, but it's not using the cached location:

```
<img src="/user/pages/home/bg_fb_cover.jpg" srcset="/user/pages/home/bg_fb_cover-320.jpg 320w, /user/pages/home/bg_fb_cover-480.jpg 480w, /user/pages/home/bg_fb_cover-640.jpg 640w, /user/pages/home/bg_fb_cover-960.jpg 960w, /user/pages/home/bg_fb_cover-1280.jpg 1280w, /user/pages/home/bg_fb_cover-1600.jpg 1600w, /user/pages/home/bg_fb_cover-1920.jpg 1920w, /user/pages/home/bg_fb_cover-2240.jpg 2240w" sizes="100vw">
```

I'm not sure how this happens, as it doesn't do this in my testing.  Are you sure you just using `![](bg_fb_cover.jpg)` and not using derivatives: https://learn.getgrav.org/content/media#sizes-with-media-queries ??

**Comment by rhukster** [comment]
BTW, it does appear that you have some 'retina' image script running outside the Grav retina capabilties.  This is adding support for various retina image sizes and images that don't exist, for example, my browser is trying to load `http://allworkersunity.com/user/pages/home/bg_fb_cover-960.jpg` which does not exist (hence the broken image), but the actual src image is there:

http://allworkersunity.com/user/pages/home/bg_fb_cover.jpg

**Comment by 789x** [comment]
yes no other derivatives just plane insert image.  i tried changing image using http its not showing. btw my image cache is off and the overall cache is off as well -devt stage.

**Comment by 789x** [comment]
i tried turning on the image cache and cleared the image cache... same thing

**Comment by 789x** [comment]
if its retina problem how do i turn it off since i dont have any derivatives?

**Comment by rhukster** [comment]
I have no idea how you are getting that derivative based output without manually setting `?derivatives` on the markdown image URL.

I can't replicate this locally. I just add an image locally, and i just get a regular IMG tag output. Maybe you can zip up your site and let me download and test with it to see what's going on?

**Comment by 789x** [comment]
![bg_fb_cover](https://cloud.githubusercontent.com/assets/9293604/19831688/f4375a38-9e42-11e6-9909-53fb6cd70209.jpg)

**Comment by 789x** [comment]
![bg_fb_cover](https://cloud.githubusercontent.com/assets/9293604/19831704/1da9a75e-9e43-11e6-8eee-8a0168975089.jpg)

**Comment by 789x** [comment]
i cant upload the .md file nor the zip files of user folder

**Comment by rhukster** [comment]
upload it to dropbox/googledrive/ whatever.  I can get the image, i need your site, as you seem to have something going on beyond the page and regular grav stuff.  I can't replicate your issue locally, so need as much of your site as possible to try to recreate it.

**Comment by 789x** [comment]
https://drive.google.com/file/d/0B5nNDrg-kh_2R0cxeXJBQ2tVTGM/view?usp=sharing

**Comment by 789x** [comment]
Thank you in advance

**Comment by flaviocopes** [comment]
The problem is caused by the `imgsrcset` plugin, removing it fixes the problem https://github.com/olevik/grav-plugin-imgsrcset/issues - tagging @OleVik as he knows better what could be the problem

**Comment by OleVik** [comment]
Thanks for notifying me @flaviocopes. The code @rhukster highlighted;

```
<img src="/user/pages/home/bg_fb_cover.jpg" srcset="
/user/pages/home/bg_fb_cover-320.jpg 320w, 
/user/pages/home/bg_fb_cover-480.jpg 480w, 
/user/pages/home/bg_fb_cover-640.jpg 640w, 
/user/pages/home/bg_fb_cover-960.jpg 960w, 
/user/pages/home/bg_fb_cover-1280.jpg 1280w, 
/user/pages/home/bg_fb_cover-1600.jpg 1600w, 
/user/pages/home/bg_fb_cover-1920.jpg 1920w, 
/user/pages/home/bg_fb_cover-2240.jpg 2240w" sizes="100vw">
```

points to the ImgSrcset-plugin being active, indeed. It should be noted that this does not actually generate the various image-sizes for you, only the `srcset`-attribute. Thus you would need to generate the images yourself (see [this gulpfile](https://gist.github.com/OleVik/f2c8b51a7153743b13607072c27cf8d2) for an example).

**Comment by rhukster** [comment]
Thanks for tracking that down guys. Makes sense.  That imgsrcset plugin creates the appropriate HTML output to support various imagest but as ole says, it's your responsibility to create those images.
