### ISSUE TITLE
Exclude page structure from URL path

### ISSUE THREAD

**Issue by daku-souru** [getgrav/grav#1141]
I was wondering if it is able to exclude the page structure from the URL of an article. 
Like for example an article that normally has the URL: www.xyz.com/media/movies/test will be available at www.xyz.com/test instead. 

Ideas are very welcome. Thanks in advance.

**Comment by Perlkonig** [comment]
See [the docs on routing](https://learn.getgrav.org/content/routing).

**Comment by rhukster** [comment]
Closing to due to inactivity
