### ISSUE TITLE
[add-resource] New Plugin: View Source

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav#1144]
For your consideration: [Perlkonig/grav-plugin-view-source](https://github.com/Perlkonig/grav-plugin-view-source)

Lets you view the raw front-matter and Markdown of a given page, if permitted.

**Comment by rhukster** [comment]
Ack, tomorrow i'll catch up on all the plugins and themes!

**Comment by rhukster** [comment]
Added!
