### ISSUE TITLE
"latest-stable" tag

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav#1146]
Is there a reason there's no `latest-stable` or other such tag? I'd like to script the process of generating a skeleton, and it would be helpful if it could just be ignorant of the actual version number and just grab the latest release. Thanks!

**Comment by rhukster** [comment]
latest-stable is actually `master` branch.  That is always the current release, `develop` is the development branch that is unstable

**Comment by Perlkonig** [comment]
Yes, but there's no accompanying release, like https://github.com/getgrav/grav/releases/download/master/grav-master.zip. In this case, I'll just clone the repo. Thanks!
