### ISSUE TITLE
Wrong timezone if there is a second or more twig variables in template

### ISSUE THREAD

**Issue by joville** [getgrav/grav#1148]
I have a template where I am putting the data from the admin interface (custom date fields) into a twig template via the following variables

`{{ teaser.header.countdown.start|date("O") }}` and
`{{ teaser.header.countdown.start|date("O") }}`

which should print the datestrings with a timezone setting for GMT +01:00 each. The first one (start) gets printed right, the second is printing +02:00 instead of +01:00 even if im using a third variable. I think, this is a bug so far. I am not sure wether this is from grav general system or from grav admin plugin.

As a temporary solution I was putting a twig set variable to get the right timezone:

{% set tz = config.system.timezone|date("O") %}
{{ teaser.header.countdown.start|date("D M d Y") }} GMT{{ tz }}
{{ teaser.header.countdown.end|date("D M d Y") }} GMT{{ tz }}

**Comment by flaviocopes** [comment]
Can't replicate at the moment, I pasted your same string in a page or in a twig template:

```
{{ teaser.header.countdown.start|date("O") }}
{{ teaser.header.countdown.start|date("O") }}
```

and I got 
```
+0100 
+0100
```

**Comment by joville** [comment]
@flaviocopes Sorry, I have duplicated the same (start). The following is correct:

{{ teaser.header.countdown.start|date("O") }}
{{ teaser.header.countdown.end|date("O") }}

**Comment by flaviocopes** [comment]
Same result for me, I don't see the second being increased. What dates did you enter in the header?

**Comment by joville** [comment]
---
title: Teaser
countdown:
    start: '30-10-2016 09:00'
    end: '20-05-2017 09:00'
---

**Comment by flaviocopes** [comment]
That's likely DST (daylight savings time) kicking in. Try with the same date in both.

**Comment by joville** [comment]
Thanks for your hint, you are right!
