### ISSUE TITLE
Permissions issue on FreeBSD 11 & php 5.6.26

### ISSUE THREAD

**Issue by llorban** [getgrav/grav#1149]
`Fatal error: Uncaught exception 'RuntimeException' with message 'Opening file for writing failed on error fopen(/usr/local/www/apache24/data/grav/user/config/security.yaml): failed to open stream: Permission denied' in /usr/local/www/apache24/data/grav/vendor/rockettheme/toolbox/File/src/File.php:202 Stack trace: #0 /usr/local/www/apache24/data/grav/vendor/rockettheme/toolbox/File/src/File.php(316): RocketTheme\Toolbox\File\File->lock() #1 /usr/local/www/apache24/data/grav/system/src/Grav/Common/Config/Setup.php(269): RocketTheme\Toolbox\File\File->save(Array) #2 /usr/local/www/apache24/data/grav/system/src/Grav/Common/Config/Setup.php(190): Grav\Common\Config\Setup->check(Object(RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator)) #3 /usr/local/www/apache24/data/grav/system/src/Grav/Common/Processors/SiteSetupProcessor.php(17): Grav\Common\Config\Setup->init() #4 /usr/local/www/apache24/data/grav/system/src/Grav/Common/Grav.php(121): Grav\Common\Processors\SiteSetupProcessor->process() #5 /usr/local/www/apache24/ in /usr/local/www/apache24/data/grav/vendor/rockettheme/toolbox/File/src/File.php on line 202`

Any help would be appreciated.

**Comment by w00fz** [comment]
Have you seen this? https://learn.getgrav.org/troubleshooting/permissions

**Comment by llorban** [comment]
I have but I could use some clarification on points 2 and 3. I set chmod 664 for directories and 775 for files, but I'm not entirely clear which situation (2 or 3) applies to my configuration.

**Comment by w00fz** [comment]
Often on *NIX the apache/php services user/group do not match the filesystem user.
So if your filesystem user is `www` and your apache runs as `www-data:www-data`, then you'll have to adjust these to properly match and allow to read/write files.

Is this your local machine or is this a provider?

**Comment by llorban** [comment]
Thank you @w00fz this is helpful. I can see that apache is running as www:www and the filesystem is use is a different account, so situation 3 would apply to me. Following the guidelines on the getgrav page works until the second step. The chown commands work but the chmod commands spit an operation not permitted command even if running as sudo.

**Comment by w00fz** [comment]
Sudo should work. Have you tried `sudo su -` and then run the commands again?

**Comment by llorban** [comment]
Using su - did not work. However, I ran sudo chmod -R 775 on a few folders in cache and system/config and grav started working now.

**Comment by w00fz** [comment]
Great!
A good test is also running `bin/grav clear-cache all` to make sure everything can be cleared out without permissions issues.

**Comment by rhukster** [comment]
Sounds like you have it sorted.  Closing.  Please reopen if need be.
