### ISSUE TITLE
Unable to filter page collections using taxonomy terms containing commas

### ISSUE THREAD

**Issue by gitname** [getgrav/grav#1151]
I have a Grav site in which I store information about songs.

Each song is represented by a distinct page (e.g. one page for `All Shook Up` by `Elvis Presley`, a separate page for `Thriller` by `Michael Jackson`, etc.).

On this site, I use the following taxonomies:

* Excerpt from `user/config/site.yaml`:

    ```yaml
    taxonomies:
      - artist
      - genre
    ```

    * You can ignore the `genre` taxonomy for the remainder of this post.

Each song has one or more artists. Example artists include:

1. `Beatles`
2. `Dave Dee Dozy Beaky Mick & Tich` (contains an **ampersand**)
3. `Earth, Wind & Fire` (contains an **ampersand** and a **comma**)

The artist is specified in the YAML front matter of that song's page. For example:

* Excerpt from `user/pages/02.songs/yesterday/song.md`:

	```yaml
	---
	title: Yesterday
	taxonomy:
	    artist:
	        - Beatles
	    genre:
	        - Oldies
	date: 10/02/2015 4:34:28
	---
	```

The site contains a *Listing* page that displays a list of all songs (i.e. pages) that have a given artist. When addressing that *Listing* page, the artist is specified in the URL. For example:

1. The page at URL `https://www.example.local/songs/artist:Beatles`
    * Shows all 9 songs that have `Beatles` as an artist
2. The page at URL `https://www.example.local/songs/artist:Dave%20Dee%20Dozy%20Beaky%20Mick%20%26%20Tich`
    * Shows all 2 songs that have `Dave Dee Dozy Beaky Mick & Tich` as an artist
3. The page at URL `https://www.example.local/songs/artist:Earth%2C%20Wind%20%26%20Fire`
    * **Shows 0 songs**, even thought there are 2 songs that have `Earth, Wind & Fire` as an artist!

**The page in example 3 does not behave the way I expect it to. I expect it to show 2 songs, but it shows 0 songs.**

Out of all these example artists, the one in example 3 is the only one that contains a comma.

**Comment by flaviocopes** [comment]
Can you post me your user/ folder zipped on https://gitter.im/flaviocopes, so I can quickly replicate the problem?

**Comment by gitname** [comment]
Hi @flaviocopes, I haven't setup my gitter.im account yet, although I do plan to soon.

In the meantime, I reproduced this issue on a clean Grav installation and documented the process by which I did that. I intentionally used mostly shell commands in order to avoid pointing and clicking.

Here is the process:

1. On your Ubuntu 14.04 web server running Apache, use the shell to navigate to your web root directory. This will be your working directory until step 7.

    ```sh
    $ cd /var/www/html/
    ```

2. Download the `Grav Core + Admin Plugin (version 1.1.8)` ZIP file from the internet (using the `-L` option to tell `curl` you want it to follow redirects).

    ```sh
    $ sudo curl -L -O https://github.com/getgrav/grav/releases/download/1.1.8/grav-admin-v1.1.8.zip
    ```

3. Extract the contents of the downloaded ZIP file. This will cause a folder named `./grav-admin` to be created in the current directory.

    ```sh
    $ sudo unzip ./grav-admin-v1.1.8.zip
    ```

4. Using your web browser, visit the fresh Grav site at: `http://<hostname>/grav-admin`. You will see the Grav admin account creation page. Create an admin account using any username, password, etc. that you want. You will automatically be logged into the site. Log out of the site.

5. Back at the web server's shell prompt, create a new page template. This page template will list all the items in a given collection.

    ```sh
    $ pwd
    /var/www/html
    $ sudo vi ./user/themes/antimatter/templates/list.html.twig
    ```

    * Populate that page template with the following Twig code:

        ```twig
        <ol>
        {% for item in page.collection() %}
            <li>{{ item.title }}</li>
        {% endfor %}
        </ol>
        ```

6. Create a new page that uses this template. This page will define the collection the page template will process by default.

    ```sh
    $ sudo mkdir ./user/pages/02.posts
    $ sudo vi ./user/pages/02.list/list.html.twig
    ```

    * Populate it with:

        ```yaml
        ---
        title: 'Posts'
        content:
            items: self@.children
        ---
        ```

7. Change your working directory.

    ```sh
    $ pwd
    /var/www/html
    $ cd ./user/pages/02.posts/
    $ pwd
    /var/www/html/grav-admin/user/pages/02.posts
    ```

8. Create 5 new directories. In the next step, you will create 1 page in each of these directories.

    ```sh
    $ sudo mkdir ./a ./b ./c ./d ./e
    ```

9. Create 1 page in each of those directories. Populate each page with specific YAML Front Matter, which you will use to to specify the tags you want to *give* to the page. **Some of those tags will contain commas**.

    ```sh
    $ echo -e "---\ntitle: a\ntaxonomy:\n  tag: ['t1', 't2']\n---" | sudo tee ./a/default.md
    $ echo -e "---\ntitle: b\ntaxonomy:\n  tag: ['t1', 't2']\n---" | sudo tee ./b/default.md
    $ echo -e "---\ntitle: c\ntaxonomy:\n  tag: ['t1', 't3a, t3b']\n---" | sudo tee ./c/default.md
    $ echo -e "---\ntitle: d\ntaxonomy:\n  tag: ['t1', 't3a, t3b']\n---" | sudo tee ./d/default.md
    $ echo -e "---\ntitle: e\ntaxonomy:\n  tag: ['t1']\n---" | sudo tee ./e/default.md
    ```

10. Using your web browser, visit the following URLs and see the following results. Steps (iv) and (v) demonstrate the issue.

    1. URL: `http://<hostname>/grav-admin/posts`
        * ✅ Result: the page lists the titles of pages `a`-`e`.

    2. URL: `http://<hostname>/grav-admin/posts/tag:t1`
        * ✅ Result: the page lists the titles of pages `a`-`e`.

    3. URL: `http://<hostname>/grav-admin/posts/tag:t2`
        * ✅ Result: the page lists the titles of pages `a`-`b`.

    4. URL: `http://<hostname>/grav-admin/posts/tag:t3a,%20t3b` (comma is decoded)
        * ❌ Result: the page **does not list any titles** (instead of the titles of pages `c`-`d`).

    5. URL: `http://<hostname>/grav-admin/posts/tag:t3a%2C%20t3b` (comma is encoded)
        * ❌  Result: the page **does not list any titles** (instead of the titles of pages `c`-`d`).

**Comment by gitname** [comment]
I corrected a few copy/paste errors in my comment above.

**Comment by gitname** [comment]
> Can you post me your `user/` folder zipped on https://gitter.im/flaviocopes, so I can quickly replicate the problem?

Done, sort of. I sent you a ZIP file containing the `user/` folder of the site I described in [my second comment](https://github.com/getgrav/grav/issues/1151#issuecomment-258575958) (i.e. the comment containing the 10-step guide to reproducing the issue).

**Comment by flaviocopes** [comment]
Thanks, I saw the problem. I posted this PR which is enough to solve the problem at this moment: https://github.com/getgrav/grav/pull/1164 but I did some testing of the problem and currently you need to URL encode the parameters 4 times. This means that to target a "t3a, t3b" taxonomy term you need to use the URL: /posts/tag:t3a%2525252C%25252520t3b. 

Not ideal, but works. Should not be this way, though.

**Comment by flaviocopes** [comment]
If you can, test the PR and check if it solves the problem for you

**Comment by gitname** [comment]
Using the code in the PR, and using the URL you provided, I do see the behavior you described (in other words, I do see the titles of pages `c`-`d`).

![screen shot 2016-11-18 at 11 27 33 pm](https://cloud.githubusercontent.com/assets/7143133/20453843/a568aed0-ade6-11e6-8ccb-46a5258c3dd1.png)

**Comment by flaviocopes** [comment]
Cool, PR merged
