### ISSUE TITLE
GPM Not Reachable Locally Only - macOS with MAMP Pro

### ISSUE THREAD

**Issue by erwstout** [getgrav/grav#1152]
I'm having an issue only locally where the error `GPM not reachable. Please check your internet connection or check the Grav site is reachable` is displayed when trying to run `bin/plugin devtools new-theme`. The initial prompt to name the theme is displayed but upon naming it I get the error. I've gone over all the steps in the troubleshooting guide and nothing seems to help.

Some system information:
+ macOS 10.12.1
+ MAMP Pro w/ PHP 7.0.8
+ PHP 5.6.25 (cli)

![screen shot 2016-11-04 at 1 50 36 pm](https://cloud.githubusercontent.com/assets/9441913/20022010/c1f7b80e-a295-11e6-8419-88ef34f82ce3.png)

![screen shot 2016-11-04 at 1 50 50 pm](https://cloud.githubusercontent.com/assets/9441913/20022012/c5848af6-a295-11e6-9457-24184978483a.png)

Running `bin/gpm index` returns fine with no errors

Looking at permissions everything seems fine (never had issues with permissions installing WordPress, etc):

![screen shot 2016-11-04 at 1 55 19 pm](https://cloud.githubusercontent.com/assets/9441913/20022128/5848da0e-a296-11e6-91cb-49eb9e662a29.png)

When I try installing directly onto one of our servers it works fine, and locally the site is running fine and I can install plugins via the admin panel or command line fine. Any thoughts to why this is happening? I hope I provided enough information. Thanks!

**Comment by w00fz** [comment]
That's interesting because the new theme and gpm index share the same GPM class so they should either both fail or succeed.

Can you try a `bin/gpm index -f` (to force a refetch)

**Comment by erwstout** [comment]
Running `bin/gpm index -f` gives me (even after clearing cache):

```sh
GPM Releases Configuration: Stable

No data was found in the GPM repository stored locally.
Please try clearing cache and running the bin/gpm index -f command again
If this doesn't work try tweaking your GPM system settings.
```

**Comment by erwstout** [comment]
Ah i found the issue (such as called out in the troubleshooting guide) it was Remote Verify Peer (SSL). I had tried disabling it earlier by editing the system files and it didn't work, but this time I disabled it via the admin interface and it worked and I am now able to connected successfully. Thank you for such a quick response.
