### ISSUE TITLE
Problem with using Grav site with subdomain

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav#1155]
Hello!

I use shared hosting and trying to use Grav in subdomain like `grav.domain.com`

My `.htaccess` content (example copied from hosting help page):
```
### default encoding
AddDefaultCharset UTF-8

### enable mod_rewrite
RewriteEngine On
RewriteBase /

### subdomain test
RewriteCond %{HTTP_HOST} ^grav\.domain\.com$
RewriteCond %{REQUEST_URI} !/grav/
RewriteRule ^(.*)$ /grav/$1 [L]
```

I have `grav` subdirectory with full site in it.

But when I go to my site, browser is waiting sooo long and show me error page. Firefox show `Wrong redirect on page. Firefox has detected that the server is redirecting the request for this address in a way that will never complete.`

Finally site works only with subdirectory: `http://grav.domain.com/grav/en`

What's wrong with my configuration?

**Comment by w00fz** [comment]
Why do you need to use an htaccess redirect, can't you just point the domain virtual host to the folder in question?

**Comment by Sogl** [comment]
No, I can't. Thing that you described worth the extra money as +1 site to the existing.

**Comment by rhukster** [comment]
Closing to due to inactivity
