### ISSUE TITLE
[add-resource] New Roman Plugin

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav#1156]
I would like to add a plugin to the Grav Repository.
Here are the project details: https://github.com/dimitrilongo/grav-plugin-roman

The Grav Roman Plugin for Grav CMS : adds the ability to convert an integer into a roman numeral and vice versa. Based on https://github.com/bransinanderson/Craft-Roman

**Comment by w00fz** [comment]
Very fun and interesting plugin. Added! Should be available soon.
