### ISSUE TITLE
Plugins, shortcodes, and priorities

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav#1159]
two times now I've run into a situation where plugins I'm developing simply don't run until I change the initial priority value, which makes no sense. Perhaps I'm not understanding how things work? Or maybe something happened in recent updates? I just now realized that these are both shortcode plugins that extend "Shortcode Core," so maybe that's part of it?

Here's the scenario:

All my plugins start with the following:

```php
    public static function getSubscribedEvents()
    {
        return [
            'onPluginsInitialized' => ['onPluginsInitialized', 0]
        ];
    }
```

Then, in the `onPluginsInitialized` handle, I enable whatever other events I want to listen to.

But over the weekend I spent hours trying to figure out why my plugin wasn't executing. On a total lark I changed that initial `onPluginsInitialized` priority to 100 and everything worked. And then just now I tested a plugin and it, too, would not execute until I changed the value to 10. After some testing, I've found that these plugins only execute if the priority is greater than 0. Negative or zero values don't work at all.

Any idea why this might be happening? Thanks!

**Comment by flaviocopes** [comment]
Can you upload one sample plugin with the problem? Privately if you need, on Gitter

**Comment by Perlkonig** [comment]
Grazie, flavio. The one that triggered this post was the [Google Charts plugin](https://github.com/Perlkonig/grav-plugin-google-charts). You'll see `onPluginsInitialized` is set to 10. Let me know what else you might need. I can send you the whole user folder of my dev server, but it's big :smile:

**Comment by flaviocopes** [comment]
I tried adding an exit() first thing in onPluginsInitialized() and it is called correctly also with `0` priority. I didn't test the plugin functionality yet. 

Can you check this simple thing?

**Comment by Perlkonig** [comment]
So here's the code. If `onPluginsInitialized` is set to 0, then the `dump("In init")` does indeed run but the shortcodes don't work. If I set it to anything greater than 0, then everything works as expected.

```php
<?php
namespace Grav\Plugin;

use Grav\Common\Plugin;
use RocketTheme\Toolbox\Event\Event;

/**
 * Class GoogleChartsPlugin
 * @package Grav\Plugin
 */
class GoogleChartsPlugin extends Plugin
{
    /**
     * @return array
     *
     * The getSubscribedEvents() gives the core a list of events
     *     that the plugin wants to listen to. The key of each
     *     array section is the event that the plugin listens to
     *     and the value (in the form of an array) contains the
     *     callable (or function) as well as the priority. The
     *     higher the number the higher the priority.
     */
    public static function getSubscribedEvents()
    {
        dump("In subscribed");
        return [
            'onPluginsInitialized' => ['onPluginsInitialized', 0]
        ];
    }

    /**
     * Initialize the plugin
     */
    public function onPluginsInitialized()
    {
        dump("In init");
        // Don't proceed if we are in the admin plugin
        if ($this->isAdmin()) {
            return;
        }

        // Enable the main event we are interested in
        $this->enable([
            'onShortcodeHandlers' => ['onShortcodeHandlers', 0]
        ]);
    }

    public function onShortcodeHandlers()
    {
        $this->grav['shortcode']->registerShortcode('GChartShortcode.php', __DIR__);
    }
}
```

My user folder minus the 143 MB `user/pages/01.blog` folder [can be downloaded from my site](https://perlkonig.com/user.zip).

**Comment by flaviocopes** [comment]
Not 100% familiar with the shortcode plugin event flow. Maybe adding it in onPluginsInitialized is too late? I see Shortcode UI listening on onShortcodeHandlers directly https://github.com/getgrav/grav-plugin-shortcode-ui/blob/develop/shortcode-ui.php#L15

**Comment by rhukster** [comment]
Plugins are now sorted with Natsort, should resolve this.
