### ISSUE TITLE
[Feature request] - Support other PHP-based template languages

### ISSUE THREAD

**Issue by matthew-dean** [getgrav/grav#1160]
Self-explanatory.

Well, maybe I should explain anyway. I want to introduce Grav to a development team. They already are familiar with Jade. So I'm wondering if it would be possible to add, in the future, support to hook in different template languages.

**Comment by rhukster** [comment]
This is is something we are definitely interested in for Grav 2.0, but in Grav 1.1, Twig is integrated quite tightly. That said, Twig is like most moustache-style templating languages, so it's pretty easy to pick up if you have used another similar one.

**Comment by rhukster** [comment]
We're considering this for 2.0, will revisit it then.

**Comment by matthewjumpsoffbuildings** [comment]
is there any news on this? id really like to use pug templates if possible
