### ISSUE TITLE
Page Select, certain type only

### ISSUE THREAD

**Issue by kevin-coyle** [getgrav/grav#1161]
Is there a way in grav to restrict the pages form item to only show pages of either a certain type or decedents of an item?

**Comment by kevin-coyle** [comment]
(this could be a duplicate of https://github.com/getgrav/grav/issues/1093)

**Comment by flaviocopes** [comment]
Not yet. Marking as enhancement

**Comment by flaviocopes** [comment]
Closing here as tracked in https://github.com/getgrav/grav-plugin-admin/issues/854
