### ISSUE TITLE
[add-resource] New Plugin: Google Charts

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav#1162]
For your consideration: [Perlkonig/grav-plugin-google-charts](https://github.com/Perlkonig/grav-plugin-google-charts)

Embeds Google charts into pages via shortcode

**Comment by flaviocopes** [comment]
I believe you must name the release `1.0.0`, instead of `Grav Plugin: Google Charts` in https://github.com/Perlkonig/grav-plugin-google-charts/releases/tag/v1.0.0` or the GPM won't pick it up, @w00fz am I right?

**Comment by Perlkonig** [comment]
Hasn't been a problem so far. They just want the tag. If you download the zip file, it's actually named `v1.0.0.zip`.

**Comment by Perlkonig** [comment]
https://github.com/Perlkonig/grav-plugin-google-charts/releases/tag/v1.0.0

**Comment by w00fz** [comment]
This is fine, the important thing is you keep consistency when you release, meaning that you always tag with `v` prefix and don't switch to version without the `v` prefix.

Going to add it

**Comment by w00fz** [comment]
Added! Should be available soon.

**Comment by flaviocopes** [comment]
Ok, was a doubt of mine :)
