### ISSUE TITLE
Life cycle confusion when processing twig in a page

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav#1163]
Can anyone confirm the order in which events are fired when twig is processed in a page? 

I'm trying to build [a demo page](https://perlkonig.com/demos/count-views) for my [Count Views plugin](https://github.com/Perlkonig/grav-plugin-count-views). I have a page with the following front matter:

```yaml
twig_first: true
process:
    twig: true
```

I then try to access the count data injected by my [Count Views plugin](https://github.com/Perlkonig/grav-plugin-count-views) during the `onPageInitialized` event. But it's not available. I know the plugin is working. And a `dump()` in the plugin itself does indeed return the data, but it doesn't appear to be available to twig in the page (but it is if requested in a template, as evidenced by my [Knowledge Base theme, sidebar template](https://github.com/Perlkonig/grav-theme-knowledge-base/blob/master/templates/partials/sidebar.html.twig#L15)). 

So what is the life cycle sequence in this case? Thanks!

**Comment by flaviocopes** [comment]
I tried using the `onTwigSiteVariables` event but it's executed after the page processes the Twig.

Adding a variable to Twig on `onPageInitialized` worked instead: 

```
    public function onPageInitialized(Event $e)
    {
        $this->grav['twig']->twig_vars['xxx'] = 'yyy';
    ... 
``` 

and then it was available in the page too.

You're setting a value on the config object at realtime so I'm not sure how that works. I'd rather make the variable available in Twig in the way I posted above.

**Comment by Perlkonig** [comment]
That makes sense for what I'm doing. I'll just do it that way. Grazie!

**Comment by Perlkonig** [comment]
Not working. So in `onPageInitialized` of the plugin, I have the following line:

`$this->grav['twig']->twig_vars['viewcounts'] = $data;`

If I do a `dump($data)`, everything is there, but in the body of the page it's still not working.

[HTML results](https://perlkonig.com/dev/demos/count-views)

[Source code](https://perlkonig.com/dev/demos/count-views?view-source=)

**Comment by flaviocopes** [comment]
I tried it before posting, not sure why it's not working for you!

**Comment by Perlkonig** [comment]
Now it's happening with another plugin, so it's not this specific one. So what could be causing this problem? Here's the plugin code:

```php
    public function onTwigSiteVariables() {
        ...
        $this->grav['twig']->twig_vars['backlinks'] = $data;
    }
```

I can `dump($data)` and `dump($this->grav['twig']->twig_vars)` and all my data shows. But the following markdown stub gives me `null`.

```
---
...
twig_first: true
process:
    twig: true
---

{{ backlinks|json_encode(JSON_PRETTY_PRINT) }}
```

**Comment by Perlkonig** [comment]
`onPageInitialized` didn't work, but `onPagesInitialized` did.

**Comment by flaviocopes** [comment]
Maybe twig cache is involved in the issue?

**Comment by flaviocopes** [comment]
Oh sorry I kept the tab open and didn't see your comment updated

**Comment by Perlkonig** [comment]
I tried disabling that and it didn't work. I'm so confused, but if onPagesInitialized works, I'll go with it ☺
