### ISSUE TITLE
Multi-language not working

### ISSUE THREAD

**Issue by matthew-dean** [getgrav/grav#1165]
I have a home page with `modular.en.md` and `modular.fr.md` (the two languages added in the admin). However, navigating to the home page under `domain/` (which redirects to `domain/en/`), it still displays only the French version. They definitely have the appropriate content. Any reasons why this might occur?

I'm using the latest stable build of Grav.

**Comment by matthew-dean** [comment]
Dang it.... I had this happening lots at the end of the day yesterday, but now I don't see it. Anything that could cause that? Some sort of caching issue? I kept trying to clear the cache yesterday, but no matter what it showed the French version. Blarg.

**Comment by flaviocopes** [comment]
Not having an idea of what could have happened, except page cache.

**Comment by matthew-dean** [comment]
I know, it's hardly a useful question when even I can't reproduce. I guess I can just say I'm quite certain that French content was showing with `/en`. One possibility....... I originally had `modular.fr.md` and `modular.md`, which I didn't realize would show French for both versions until I read the docs. Then I renamed `modular.md` to `modular.en.md`, cleared the cache, and still had the same problem. It's possible the bug is somewhere in there, where it couldn't "reset" to find the proper language page. (Until a new session?)
