### ISSUE TITLE
Error occurs after Grav admin upgrade to 1.1.8 (images)

### ISSUE THREAD

**Issue by littlenamgal** [getgrav/grav#1166]
Hi there, my page which contains media collection at the frontmatter. it works to v1.1.5. After upgrade, error appear just on this page “can't convert undefinded object”.

![untitled-1](https://cloud.githubusercontent.com/assets/22469780/20130545/6f6b7dd6-a692-11e6-9913-779f39856fe4.jpg)

Error message:-
Fetch Failed: can't convert undefinded to object Grav
Undefined index: alternative

i copied the same files in 1.1.5 version and 1.1.8 version. And i tried to remove the media from frontmatter with no content. the images and the .yaml file are placed in the same folder as page (.md)

blueprint:-
```
title: Fido Playing with his Bone
description: The other day, Fido got a new bone, and he became really captivated by it.
```
content of the page is blank, just frontmatter:-
```
title: 'Photo Gallery'
menu: 'Photo Gallery'
```
template for the page (gallery.html.twig)
```
{% extends 'partials/base.html.twig'  %}

{% block content %}
	 
	{{ page.header.title }}
	

	 <div class="image-gallery">
	 
	
    {% for image in page.media.images %}
	
    <div class="gallery-item">
        <div class="image-surround">
            {{ image.lightbox(1024,768).resize(200,200).html('Sample Image') }}
        </div>
        <div class="image-info">
            <p class="image-title">{{ image.meta.title }}</p>
            <p class="image-desc">{{ image.meta.description }}</p>
        </div>
    </div>
    {% endfor %}
    </div>
	
	
{% endblock %}
```
it works fine in version 1.1.5. In version 1.1.8 same error still appears.

**Comment by flaviocopes** [comment]
Does it only happen in IE/Edge? Can you check with Chrome/Firefox for example?

**Comment by littlenamgal** [comment]
um.. I m using firefox

**Comment by flaviocopes** [comment]
I think I need your user/ folder zipped to replicate.. send it to https://gitter.im/flaviocopes

**Comment by fredrikekelund** [comment]
Hi @littlenamgal, I did some work on the image pipeline that was released with v1.1.8, so maybe I can help debug this.

Is this an error that only appears in the admin panel? Does the template render correctly - ie. does the page on the actual site look right? Does it appear regardless of whether you have images in the folder or not? Could you post a list of the files in the folder?

**Comment by littlenamgal** [comment]
Hi @fredrikekelund, 
thank you for your help. the page could not be rendered correctly. the files are attached for your reference. thank you
![untitled-2](https://cloud.githubusercontent.com/assets/22469780/20513366/624c0278-b0c0-11e6-8a82-c865919ffef9.png)

[06.test-gallery.zip](https://github.com/getgrav/grav/files/605624/06.test-gallery.zip)

**Comment by fredrikekelund** [comment]
Hmm, are you using the Antimatter theme @littlenamgal?

**Comment by fredrikekelund** [comment]
It looks like this was the same issue as described #1179. Do you want to try with the latest source from GitHub and see if it fixes the problem, @littlenamgal?

**Comment by littlenamgal** [comment]
Oh~ Thank you so much.  it fixed after i replaced the Media.php ;)
https://github.com/getgrav/grav/blob/55bb4cf2fa1780d5017c1248a46f578c9a342aca/system/src/Grav/Common/Page/Media.php

**Comment by fredrikekelund** [comment]
Cool! 👍 Looks like this issue can be closed then
