### ISSUE TITLE
User blueprints

### ISSUE THREAD

**Issue by matthew-dean** [getgrav/grav#1167]
In the documentation, it says that custom pages (blueprints for custom fields) can be built by putting blueprints in the `/user/blueprints/pages` folder. https://learn.getgrav.org/forms/blueprints/example-page-blueprint

After having done this, how do you get that page type to show up when creating a new page? Is there a missing step here?

**Comment by flaviocopes** [comment]
Also create a corresponding twig template file, then it will show up.

**Comment by matthew-dean** [comment]
Okay, so even though you can create a user blueprint, you cannot create a user template aside from in the theme? I was hoping there was a way to maintain a third-party theme and create custom page forms.

The obvious use-case: being able to update the theme at at will, without overwriting custom blueprints / pages.

**Comment by wsanter** [comment]
You can use theme-inheritance to keep the third-party theme updated without directly impacting your customized theme.
[Theme Inheritance](https://learn.getgrav.org/themes/customization#theme-inheritance)

**Comment by matthew-dean** [comment]
Even when modifying the theme: I've placed a `project.yaml` file in the theme's `blueprints/` folder and a `project.html.twig` file in the theme's `templates/` folder. I do see a "Project" option when I go to add a new page, but it doesn't present the custom form defined in the `.yaml` file.

**Comment by matthew-dean** [comment]
Never mind, I see it now! Thanks!
