### ISSUE TITLE
PageInject Plugin or page.find: variables

### ISSUE THREAD

**Issue by Ironvasya** [getgrav/grav#1170]
Hi
Is there any way to use variables with [plugin:content-inject] ?

(with twig processing(first) enabled,) 
`[plugin:content-inject](/timetable/first)` – works

but

`{% set gymUrl = “/timetable/first” %} `
`[plugin:content-inject]( gymUrl )` – does not

Thanks

**Comment by flaviocopes** [comment]
`[plugin:content-inject]({{ gymUrl }})` works? (with Twig processing enabled)
