### ISSUE TITLE
Admin bug with android

### ISSUE THREAD

**Issue by rbouikila** [getgrav/grav#1171]
Hi team, 

I found a bug in the admin panel when I write a new page with my mobile android.
No text appears when I type on the keyboard.

Regards,

**Comment by flaviocopes** [comment]
I don't have an Android device at hand, perhaps someone can check and confirm this problem?

**Comment by rbouikila** [comment]
Hi guys,

I have tested with two other devices under android and I doesn't have the bug.
I think the bug comes from my device.

Sorry and thanks for your reactivity.

Regards,
