### ISSUE TITLE
[add-resource] New Plugin (Grav Instagram Feed Plugin)

### ISSUE THREAD

**Issue by dannystey** [getgrav/grav#1177]
I would like to add my new plugin to the Grav Repository.
Here are the project details: [**dannystey/grav-plugin-instagram-feed**](https://github.com/dannystey/grav-plugin-instagram-feed)

I saw that there is already an Instagram plugin form artifex404. But it seems that this repository is not well supported and does not work well. And you need an access token for a feed. What in my opinion is not necessary for your a public feed. 

However, I decided to create a plugin, which is lighter and easy to use. All you have to know is written in the readme.md. [README.md](https://github.com/dannystey/grav-plugin-instagram-feed/blob/1.0.0/README.md)

Hope I can be a active part of the Grav Community.

Best regards,
Danny

**Comment by rhukster** [comment]
Added to GPM. thanks.
