### ISSUE TITLE
Media Metafile issue on upgrade to 1.1.8

### ISSUE THREAD

**Issue by asirco** [getgrav/grav#1179]
After updating from 1.1.6 to 1.1.8, I received an error on just one of my pages as shown in the attached image.

After a little digging I found the route cause. It seems that if you have and additional yaml media metafile for an image that does not exist in the same folder, this "critical" error appears.

For example, I had a spurious dogs-vs-cats.jpg.meta.yaml file in a module page which simply stated a max-width field for an image. The image was deleted but the yaml file stayed in situ. Upon updating Grav to 1.1.8, it seems that Grav has become more stringent when checking these files. If there's no associated image file to a meta.yaml file, then this critical error is thrown.

Simply removing the meta.yaml file fixed the immediate issue, but it shouldn't be this way. Deleting an image should remove it's meta file and, in my opinion, Grav should be a little more forgiving in situations where there are extra meta files in a directory.
<img width="894" alt="screen shot 2016-11-19 at 20 53 43" src="https://cloud.githubusercontent.com/assets/1963539/20458361/29036e9c-ae9b-11e6-9fd6-c50155a8adbc.png">

**Comment by rhukster** [comment]
Does sound like a bug.. thanks for reporting.

**Comment by flaviocopes** [comment]
Replicated
