### ISSUE TITLE
Pagination with taxonomy

### ISSUE THREAD

**Issue by tboulogne** [getgrav/grav#1183]
Hello,

I could not get pagination working with taxonomy. I rewrote the the findTaxonomy [findTaxonomy](https://github.com/tboulogne/grav/blob/develop/system/src/Grav/Common/Taxonomy.php) and get pagination on the frist page with pagination on bottom of page with this template [taxonomy](https://gist.github.com/tboulogne/25cbb91c2f15a75baefd961934326520).

1. taxonomy selection
![1_taxonomy_selection](https://cloud.githubusercontent.com/assets/6205275/20547646/da684048-b11d-11e6-984f-ce5fd25a43db.png)

2. selection between values
![2_first_filter](https://cloud.githubusercontent.com/assets/6205275/20547648/da71df72-b11d-11e6-8a2f-59f9c0706d7c.png)

3. results
![3_results](https://cloud.githubusercontent.com/assets/6205275/20547647/da6fca52-b11d-11e6-9c3c-9c9b04e23a2c.png)

![3_results_pagination](https://cloud.githubusercontent.com/assets/6205275/20547645/da40aa10-b11d-11e6-88e8-6bea665b8082.png)
But when i click on a page number
```
http://blog.dev/taxonomy/publication:2016/page:2
````
i had nothing.

Thanks for help on this please.
(i tried to make it with a plugin, same result...)

Regards,

**Comment by flaviocopes** [comment]
Are $limit and $start getting the correct values, in your edits?

**Comment by tboulogne** [comment]
Hello,

It was something with the route. With the template, /page:2 give a 404. I wrote a little plugin to do the same.  Now if i add /page:2 i could access data but i don't have pagination on the bottom page.But i discover collection send to pagination module is the slice one and there is a parameter like collection > limit. I don't know how to solve this. I make a workaround in my template...

**Comment by tboulogne** [comment]
Hello @flaviocopes 

I check further and perhaps you could help.

I fire event into findTaxonomy function with a collection of 105 items with **params['pagination']=true** (do same in my plugin)
```php
$grav->fireEvent('onCollectionProcessed', new Event(['collection' => $collection]));
```

If i dump the collection Into pagination plugin onCollectionProcessed :
```php
public function onCollectionProcessed(Event $event)
    {
        /** @var Collection $collection */
        $collection = $event['collection'];
        $params = $collection->params();

        // Only add pagination if it has been enabled for the collection.
        if (empty($params['pagination'])) {
            return;
        }
        
        if (!empty($params['limit']) && $collection->count() > $params['limit']) {
            require_once __DIR__ . '/classes/paginationhelper.php';
            $this->pagination = new PaginationHelper($collection);
            $collection->setParams(['pagination' => $this->pagination]);
        }
    }
```
the count is *3* and pagination is missing into **params**!

Any tips to understand what failed please ?

Thanks

**Comment by flaviocopes** [comment]
Pagination works out of the box with taxonomies, check for example the "Blog site" skeleton.

Filtering by tag in that skeleton renders the pagination filtered by tag too.

**Comment by tboulogne** [comment]
@flaviocopes Perhaps it's my mistake but with another folder than blog, not working on my side :-(.
And i see a post into the forum with this problem too.

**Comment by flaviocopes** [comment]
Can you post a sample pages structure with this problem?

**Comment by tboulogne** [comment]
i make a workarround using a jquery script (bootpag).
I will try to reproduce and post the bug here.

**Comment by rhukster** [comment]
Closing to due to inactivity
