### ISSUE TITLE
Collection filter based on more than one taxonomy discards criteria where terms are not in the taxonomy

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav#1184]
This could be contentious, it's a case where surprising behaviour happened when creating a filtered collection by more than one taxonomy vocabulary.

This snippet demonstrates the collection I am trying to make in the page frontmatter:

``` YAML
content:
    items:
        '@taxonomy': {tag: staff, team: hygienists}
 ```
So I want pages tagged 'staff' ***and*** (the default) also ascribed the term 'hygienists' from the vocabulary 'team'. The example is taken from [examples provided in Grav documentation](https://learn.getgrav.org/content/collections#taxonomy-collections).

There are currently no pages where taxonomy:team=hygienists, but this is a placeholder for when there may be, and I expect the filter to return an empty collection until then. That's the part that may be controversial, but in my context it makes perfect sense.

What I see instead in the resulting collection is all pages tagged staff (i.e. the first \@taxonomy criterion).

_(I have tried the alternate YAML formats suggested. When setting similar page collections and the term does exist in the 'team' vocabulary, the filter works as expected.)_

I can see the [code that is responsible for this behaviour in Taxonomy.php](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Taxonomy.php#L94), and it is unchanged in Grav 1.1:

``` PHP
        foreach ((array)$taxonomies as $taxonomy => $items) {
            foreach ((array)$items as $item) {
                if (isset($this->taxonomy_map[$taxonomy][$item])) {
                    $matches[] = $this->taxonomy_map[$taxonomy][$item];
                }
            }
        }
```
Expected behaviour could be achieved by adding an ``else`` clause on line 96 after the ``if`` stanza, something like:
```PHP
else {
   $matches[] = []; /* actually I'm not exactly sure what type $matches should be, .. 
                       but we want a value here that will produce an empty set when ..
                       $operator is 'and' and make no difference when it's 'or'. */
}
```
Let me know if you want me to write that patch. :)

**Comment by flaviocopes** [comment]
I tested and I'm not getting the problem. Did you add team to the site taxonomies in the Site configuration (or `user/config/site.yaml`)?

**Comment by hughbris** [comment]
Thanks for checking. Yes, I forgot to mention that I have registered the vocab there. Also, that I am using Grav v.1.1.8! (sorry, was late and I have to move on to another project)

I'm surprised you can't reproduce because, if I traced the code back correctly, you can see in that predicate (``isset($this->taxonomy_map[$taxonomy][$item])``) where it will not add the criterion if the term does not exist in the vocabulary.

I'll try reproducing on a clean install, and also adding that patch in to Taxonomy.php. Don't have time right now though.

!remindme one week
(does that work on Github?)

**Comment by flaviocopes** [comment]
I tried with taxonomies already defined (tag and category)

**Comment by hughbris** [comment]
I _was_ able to reproduce this. Github won't allow me to attach a git patch file, so [I created a Gist](https://gist.github.com/hughbris/a1be0f7f98dbafed49ae935f4f6fb7c5), hope that works for you :) You need to apply it to the user directory of a clean Grav 1.1.8.

As mentioned, I also tested my suggested fix to [Taxonomy.php](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Taxonomy.php) where I add an `else` block. It produced the behaviour I wanted/expected, i.e. no results.

After you've confirmed a bug, would you like me to submit a pull request?

**Comment by flaviocopes** [comment]
Thanks! Fixed in `develop`. I was able to reproduce the problem with your patch. So basically if there are 2 taxonomies required but one has 0 items, it's going to simply pick the ones corresponding to the other taxonomy, thus generating a wrong result. Didn't get the problem in the first place. 👍

**Comment by hughbris** [comment]
I thought maybe you didn't grok, but that is because I gave a poor explanation :/ My bad. Thank you.
