### ISSUE TITLE
_url query parameter in nginx config

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav#1185]
On [line 15 of webserver-configs/nginx.conf](https://github.com/getgrav/grav/blob/develop/webserver-configs/nginx.conf#L15), all requests are rewritten to include a `_url` query parameter. It doesn't look like this is being used anyhwhere in the source code, and when I tried to remove it, Grav functioned normally.

I guess it could be removed from the default nginx config?

**Comment by flaviocopes** [comment]
This was a recent change https://github.com/getgrav/grav/commit/baacfa794a28e041cf6cbf22fa3528389fc8db8f#diff-3570e54530339c26430698f3639ecd8d I am not super familiar with the nginx configuration so I am not sure what it's used for, need to dig into it

**Comment by fredrikekelund** [comment]
Yeah sure, I thought at first that it wasn't used in any of the other webserver config files, but it looks like it's in the Caddyfile as well, but none of the others.

**Comment by fredrikekelund** [comment]
Judging from #1245, this query param is intentional and meant to live on? But it's only used by Gantry?

**Comment by flaviocopes** [comment]
The `$query_string` params were added back to the suggested nginx config because of a problem discovered in Gantry, but applies to anything really. Just, we don't use those parameters anywhere else in Grav and never noticed.

**Comment by rhukster** [comment]
Closing to due to inactivity
