### ISSUE TITLE
GPM not updating

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav#1186]
The plugins you added the other day still aren't showing on [the website](https://getgrav.org/downloads/plugins).

**Comment by w00fz** [comment]
Which ones specifically?

**Comment by Perlkonig** [comment]
* Issue #1182 (Scheduler)
* Issue #1177 (Instagram)
* Issue #1175 (Backlinks)
* Issue #1172 (Prism)

**Comment by rhukster** [comment]
Weird, they are missing in the repo.. i know i added them, but maybe i reset and lost them :(.. will add again.

**Comment by rhukster** [comment]
Ok found the problem.. i had 'stashed' the changes due to a conflict, and forgot to add them back.. Added now.. Should show up within the hour
