### ISSUE TITLE
404 Not Found Not Found

### ISSUE THREAD

**Issue by spencerthayer** [getgrav/grav#1187]
I'm getting the following error on a fresh install.
> # Fetch Failed: 
> **404 Not Found Not Found**
> The requested URL /admin/notifications.json/task:getNotifications was not found on this server. Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

Anyone have any ideas why this is the case?

**Comment by spencerthayer** [comment]
**Note:** I understand that `AllowOverride All` is an option in the `.htaccess` file but I would like to understand what is specifically causing this error so that I can fix it properly.

**Comment by Perlkonig** [comment]
[Obligatory link to the docs](https://learn.getgrav.org/troubleshooting/page-not-found)

If you look at `.htaccess`, it only does three things:

1. Most importantly, it does a bunch of rewriting.
2. It turns off indexes.
3. It sets the directory index.

Based on that and [the Apache AllowOverride docs](https://httpd.apache.org/docs/current/mod/core.html#allowoverride), your `AllowOverride` needs to include `FileInfo` and `Indexes`.

**Comment by spencerthayer** [comment]
@Perlkonig you think that the .htaccess is the cause of Grav not finding `/admin/notifications.json/task:getNotifications`?

**Comment by Perlkonig** [comment]
I don't know. You asked about htaccess, so I answered. You'll have to look at the troubleshooting docs linked above to start that part.

**Comment by GitHamburg** [comment]
https://github.com/getgrav/grav-plugin-admin/issues/203#issuecomment-453386316

> It's a nginx issue about "Nginx pseudo static", you can solve it by adding the rewrite content below to nginx conf.
> 
> ## Begin - Index
> ```
>     rewrite ^/your grav subfolder/admin/(\w+).json/(.*)+$ /apps/grav/index.php?$query_string;
>     ...
> ```
> ## End - Index
