### ISSUE TITLE
Can you add minify HTML?

### ISSUE THREAD

**Issue by Stepanov-Sergey** [getgrav/grav#1190]
Can you add the switch "HTMLminify" to  "Configuration-> System Assets"
 which will include the command in to base template {%spaceless%}  at the beginning and at the end {%endspaceless%} 
It will speed up page loading
for example
http://twig.sensiolabs.org/doc/tags/spaceless.html

Now every time I put and delete the record in the base template, but it is not convenient for debugging

**Comment by You85** [comment]
+1

**Comment by rhukster** [comment]
I'm confused why you can't just add this to your theme? Grav doesn't really mess with theme templates and i don't think it should start now.

**Comment by rhukster** [comment]
BTW, you can still make it a switch in your theme configuration.
