### ISSUE TITLE
Problem with caching and sending forms

### ISSUE THREAD

**Issue by muuvmuuv** [getgrav/grav#1192]
Hey all I have already a problem with caching (memcache currently installed).

I can not send a form after I cleared the cache and submit a form. The first form submit works (not cached yet) the second one not.

There is no error coming just a redirect back to the form.

GRAV: v1.1.8
Admin: v1.2.4
Form: v2.0.7
PHP: 5.6.24-0+deb8u1
System: Linux flora 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64
Server API: FPM/FastCGI
IPv6: yes

Memcache:
Version: 2.2.0
libmemcached version: 1.0.18
SASL support: yes
Session support: yes
igbinary support: no
json support: no
msgpack support: no

Settings here: 
![bildschirmfoto 2016-12-06 um 16 19 23](https://cloud.githubusercontent.com/assets/11534760/20930978/cbe53316-bbcf-11e6-90bb-d6f528b5dbc6.png)

**Comment by flaviocopes** [comment]
You mention memcache but you have memcached selected, they are 2 different systems, which one are you using?

**Comment by muuvmuuv** [comment]
@flaviocopes we are using memcache. Thank's for the hint, but that did not worked for us. It gave us an error now. Here the response:
```[2016-12-07 22:55:47] grav.CRITICAL: Class 'Memcache' not found - Trace: #0 /var/www/static/grav/influxe-gaming.de/vendor/filp/whoops/src/Whoops/Run.php(375): Whoops\Run->handleError(1, 'Class 'Memcache...', '/var/www/static...', 210) #1 [internal function]: Whoops\Run->handleShutdown() #2 {main} [] []```

**Comment by flaviocopes** [comment]
This new error is because Memcache is not installed in PHP. Is it loaded in your phpinfo()? (you can check that in the Admin config 'info' panel

**Comment by muuvmuuv** [comment]
@flaviocopes I pasted the info above. It is installed with version 2.2.0

**Comment by rhukster** [comment]
Grav now automatically sets `never_cache_twig` if a form is found in a page.
