### ISSUE TITLE
[add-resource] New Plugin  - GFFI(Gallery From a Folder of Images)

### ISSUE THREAD

**Issue by Stepanov-Sergey** [getgrav/grav#1193]
I would like to add my new Plugin to the Grav Repository.
Here are the project details: https://github.com/Stepanov-Sergey/GFFI

**Comment by flaviocopes** [comment]
@Stepanov-Sergey can you fill the description? As it's used in the plugins listing https://github.com/Stepanov-Sergey/GFFI/blob/master/blueprints.yaml#L3

**Comment by Stepanov-Sergey** [comment]
done

**Comment by w00fz** [comment]
Added
