### ISSUE TITLE
Grav installation - Blank page despite sufficient permissions

### ISSUE THREAD

**Issue by Voldacar21** [getgrav/grav#1195]
There's 775 permission for all folders and files. 
My PHP version is 5.6.21.

But I've blank page and I can't use shell script, because I've shared web hosting service without ssh access. 

What should I do? 

Thanks in advance.

**Comment by rhukster** [comment]
Are you sure it's a blank page because of permissions? It could be any PHP error.  Have you checked the php error logs?

**Comment by Voldacar21** [comment]
I have this error : ".htaccess : Invalid command 'Prevent', perhaps misspelled  or defined by a module not included in the server configuration.

What should I do ?

**Comment by flaviocopes** [comment]
The only time `Prevent` is mentioned in the stock .htaccess is in the comments: https://github.com/getgrav/grav/blob/develop/.htaccess#L72 did you modify that?

**Comment by rhukster** [comment]
Closing to due to inactivity
