### ISSUE TITLE
API for adding Twig extensions / filters?

### ISSUE THREAD

**Issue by matthew-dean** [getgrav/grav#1196]
I see the Twig class for Grav's Common core API, but I don't see a usable method that I can reference to a) add a Twig extension to my theme, b) register that on the page request from the theme's event hook file.

**Comment by matthew-dean** [comment]
Never mind: https://learn.getgrav.org/plugins/event-hooks#onTwigInitialized

**Comment by rhukster** [comment]
Also there are some good examples of Adding dynamic Grav functions/filters in other plugins.. 

For example a dedicated Twig extension see Admin plugin: https://github.com/getgrav/grav/issues/1197

For a more inline example of just adding a function, see Star Ratings plugin: https://github.com/getgrav/grav/issues/1197
