### ISSUE TITLE
admin: grav-tabs-state cookie causes "too many redirects" error. 

### ISSUE THREAD

**Issue by ardkevin84** [getgrav/grav#1197]
Application Versions: Grav v1.1.9-rc.1 - Admin v1.2.5-rc.2 

In the admin side, opening a page in the editor view and toggling a tab sets the below cookie. This cookie causes a "too many redirects" error in Chrome (linux, updated). Delete the cookie, and all is well. I commented-out the code in admin.js.min that sets it, and I've had no trouble since. 

Is this an isolated issue, or something that should be addressed. Let me know if you need more info.

Cookie name: `grav-tabs-state`
Content: 
```
{%22tab-content.options.advanced%22:%22data.options%22}
```

Problem cookie generated by: 
```
//-- in /user/plugins/admin/themes/grav/js/admin.min.js (formatted, approx. line 12744 
u[t.attr("name")] = t.val(), s.default.set("grav-tabs-state", JSON.stringify(u), {expires: 1 / 0}), c.Instance.editors.each(function (e, t) {
    var n = (0, a.default)(t).data("codemirror");
    n && 0 === n.display.lastWrapWidth && n.refresh()
})
```

**Comment by w00fz** [comment]
How can I recreate the issue?
The JS itself doesn't do much but store the active tab upon click (https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/app/utils/tabs-memory.js).

The restoring of active tab on load happens via Grav Admin itself via twig file, but even then it's strange because there really isn't any redirect that should happen, it's just about setting the tab to active via classname.

**Comment by ardkevin84** [comment]
It may well be a local problem (eg: theme related, possibly), but that would be the replication case. 

I got it pretty consistently down to: 
- open the page in editor. 
- change tab 
- check cookies for `grav-tabs-state` 
  - fail-case:
    - click save with the cookie present. receive browser error 
  - pass-case: 
    - delete that one cookie and save the page. page saves.

**Comment by flaviocopes** [comment]
So simply opening a page, switching tab and saving causes an error for you? If this is the case, I can't replicate it with my install

**Comment by ardkevin84** [comment]
After opening this ticket, I thought that it was because I'd junked something up in a custom blueprint - that site had tons of custom stuff in it. Today, though, I noticed the same issue in a dev site that isn't quite as heavy. Also, I noticed that I don't have to *save a page* to reproduce. I can: 
- open a page in the admin editor. 
- change tab. 
- click on the pages sidebar 
- (get the too many redirects error originally noted) 
This one, I basically curl-ed the company's live site, and jigsawed the html into twig.

**Comment by flaviocopes** [comment]
Still not able to replicate 😕

**Comment by flaviocopes** [comment]
Which page type was that? Also, which browser are you using?

**Comment by ardkevin84** [comment]
We've seen it in Chrome on linux and mac. 
Today, if you like, I can send a vagrant that has the fail case. Alternatively, the first site we notived it on has since been pushed live -  we happen to still host its dev domain, though. Would admin access to that dev site help?

**Comment by flaviocopes** [comment]
Zip me the whole site and send to https://gitter.im/flaviocopes the link, I will check if it can be replicated locally, or if it's a server config

**Comment by ardkevin84** [comment]
@flaviocopes I'm pretty convinced this is isolated, considering: 

- no one else seems to be reporting it
- i see a similar issue with octobercms, in similar circumstances. 

I use chrome on linux, and the other person in the office who reported it is chrome on mac. I'm more inclined to think the issue is chrome vs. jquery than grav.
