### ISSUE TITLE
Video Embed Issue

### ISSUE THREAD

**Issue by ghostinhershell** [getgrav/grav#1198]
Hey there! I embedded a video into our knowledge base. The video displays as it should but it completely throws off the formatting of everything that comes after it. 

Here's a link to give you a visual:
https://referralrock.com/knowledgebase/

Any help would be much appreciated.

PS, I've read Grav's KB article on [Media](https://learn.getgrav.org/content/media) but couldn't find a fix.
Also, I have tried just spacing out the text from the video but that didn't work.

**Comment by Perlkonig** [comment]
Can you post some code? How are you embedding the media? Some Markdown would help diagnose the problem.

**Comment by ghostinhershell** [comment]
Here's the embed code:

<script src="//fast.wistia.com/embed/medias/uoyme38m87.jsonp" async></script><script src="//fast.wistia.com/assets/external/E-v1.js" async></script><div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_uoyme38m87 videoFoam=true" style="height:100%;width:100%">&nbsp;</div></div></div>


And here's a sample of the text being affected:

### What is Referral Marketing?
Referral Marketing is when you promote your products or services to new customers by using the influence of your existing network (customers, partners, etc.). Referral marketing is founded on the idea of [**word of mouth marketing**](https://referralrock.com/blog/word-of-mouth/?target=_blank), but it is a more proactive and scalable way to generate new customers.

### Key Referral Rock Concepts
Our [**Referral Rock Concept Video**](https://referralrock.wistia.com/medias/yaw5m3uc15/?target=_blank) is a great place to start to understand our terms.  There are a ton of terms used in referral marketing and each company may use a slightly different variation of terms. While most terms are clear, it’s important to highlight the two that change the most between companies and platforms: Member and Referral.

**Comment by ghostinhershell** [comment]
The headers contain 3 hashtags and the links follow the [](url) format. Nothing fancy, no HTML, etc.

**Comment by ghostinhershell** [comment]
This is what it looks like published:

![2016-12-08_09-50-48](https://cloud.githubusercontent.com/assets/14021469/21014418/f24c8c7c-bd2b-11e6-8487-8956c1922b54.png)

The video embeds and is functional, but everything after it doesn't display properly.

**Comment by flaviocopes** [comment]
Not able to replicate

![screen shot 2016-12-09 at 17 37 05](https://cloud.githubusercontent.com/assets/11783388/21056502/254fe2d0-be36-11e6-97a9-14a866926a20.png)

I put the script tag in the twig template, while the content in the page, I imagine you did the same?

**Comment by ghostinhershell** [comment]
I didn't try that at all. Does that just mean encasing the script in curly brackets {{}}?

**Comment by flaviocopes** [comment]
No need to use curly braces. Just put the script snippet in the Twig, it's HTML.

It was stripped from my page markdown, that's why I moved it to the twig.

**Comment by rhukster** [comment]
Can we close?

**Comment by flaviocopes** [comment]
I think so. I just wanted to check, adding the embed code you used inside markdown directly is going to cut it at the first `<script>` tag.

To add it correctly, add new lines after each `<script>` tag:

```
<script src="//fast.wistia.com/embed/medias/uoyme38m87.jsonp" async></script>
<script src="//fast.wistia.com/assets/external/E-v1.js" async></script>
<div class="wistia_responsive_padding" style="padding:56.25% 0 0 0;position:relative;"><div class="wistia_responsive_wrapper" style="height:100%;left:0;position:absolute;top:0;width:100%;"><div class="wistia_embed wistia_async_uoyme38m87 videoFoam=true" style="height:100%;width:100%">&nbsp;</div></div></div>
```

**Comment by ghostinhershell** [comment]
Just wanted to say thanks. The issue was resolved :)
