### ISSUE TITLE
Install specific version of a plugin

### ISSUE THREAD

**Issue by c33s** [getgrav/grav#1200]
currently it is not possible to install a plugin of a specific version.
```
php bin\gpm install mobile-detect --version 1.0.0
Grav Package Manager version 1.1.8
```
this makes it impossible to use grav in an ci environment. if i develop a grav application locally (with vendors and plugins in `.gitignore`) and commit my changes to the my repo where the ci-server will takeover (gitlab-ci), which has the sourcecode from my repo and then calls the build & deploy commands:

`gitlab-ci.yaml`:
```
  - composer install --no-scripts
  - php bin/grav install
  - php bin/gpm install admin
  - php bin/gpm install devtools
  - php bin/gpm install landio
  - php bin/gpm install cachebuster
  - composer install --no-interaction --no-progress --optimize-autoloader  --ignore-platform-reqs
  - lftp -u username,password hostname -e "set ftp:ssl-allow true; set ssl:verify-certificate no; mirror --delete --reverse ./ targetdirectory"
```

in this case plugins can have a different version on production as on the local development server. depending on when the plugins where installed locally (can be a month ago), it can lead to a major gap between the plugin versions.

it should be possible to define the version i want to install from a plugin:

```
php bin/gpm install admin --version=1.2.4
```

**Comment by flaviocopes** [comment]
Not nice as `--version=`, but there's 

`bin/gpm direct-install` which also allows you to install a local package.

Install a plugin:

`bin/gpm directinstall https://github.com/getgrav/grav-plugin-admin/archive/1.2.5-rc.4.zip`

**Comment by c33s** [comment]
@flaviocopes thanks for your nice workaround, this of course helps very much.

for the future it would be awesome to manage this in the .dependencies file directly

related: #880

**Comment by akeif** [comment]
I'm very much interested in completing this feature request. Dev instance up and running. Let's see what I can do.

**Comment by akeif** [comment]
@rhukster @w00fz Can we discuss the following Slack conversation before I keep working on this issue? I need to know what you guys want to do with this issue. Right now, when the CLI install a package, it download the latest version for each dependencies. If I'm to add a feature to download older versions, I should download the specified versions from the package blueprints.yaml

```
akeif [8:14 PM] 
@rhuk @w00fz About issue #1200 `bin/gpm install` fetch packages dependencies
from `https://getgrav.org/downloads/plugins.json`.
Is there a way to request an older plugin version data? I'm pretty sure it's not possible.
If not, do you have any recommendation? My only idea so far is to get `blueprint.yaml`
from the plugin GitHub repo for the user specified version.

w00fz [8:36 PM] In the next admin update you will be able to use direct install
and specify a path
[8:36]  You can already via cli
[8:37]  In the future we might consider providing different versions but the idea of grav
is to try to move forward so we don't want to encourage too much using older version
but latest and greatest
[8:38]  I think the ability to still install older versions if really needed as we offer now
is a good compromise
```

**Comment by akeif** [comment]
@w00fz As you can see @rhukster tagged this issue as *enhancement*. Thus, I'm not sure how to react to your Slack answer.

**Comment by rhukster** [comment]
I'm still willing to look at your proposed PR solution.  In general the best solution is usually the latest, but there is of course some good reasons to be able to pull a known/specific version from GPM.  For example if a newer version is known to have bugs or cause conflicts.  It does need to fit in seamlessly with the current GPM system as well as the admin.

**Comment by akeif** [comment]
Ah well. I don't think I can do it.

Blueprints format changes over time, which is giving me problem rolling back to older versions.

Also, correctly injecting data from older blueprints in data returned from the Grav plugin.json repository is hard given the complexity of the [package installation process](https://github.com/akeif/grav/blob/issues/1200/gpm-install-version/system/src/Grav/Console/Gpm/InstallCommand.php#L218).

**Comment by akeif** [comment]
@rhukster Would you have any advice to help me get on track with this feature request? I'm not sure I can do this in a reasonable amount of time.

**Comment by rhukster** [comment]
Closing to due to inactivity
