### ISSUE TITLE
.dependencies file should be written on plugin install

### ISSUE THREAD

**Issue by c33s** [getgrav/grav#1201]
if i run `php bin\gpm install mobile-detect` the `.dependencies` file should be auto updated.

sidequestion maybe worth a own issue:
why plugins aren't handled as normal composer packages?
https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md

**Comment by flaviocopes** [comment]
Related: https://github.com/getgrav/grav/issues/880

**Comment by c33s** [comment]
related: #1200

**Comment by rhukster** [comment]
When we started writing the GPM, composer didn't have the capabilities it does now.  I think for Grav 2.0 we'll look into using composer under the covers. However, by having our own installer, it does give us more control, so it's definitely something we will look into.

Regarding `.dependencies`, that file was created to allow skeleton packages to list plugins/themes that they needed in order for us to build packages.  We probably could replace that with a variant of the blueprints as that also supports dependencies including version information.
