### ISSUE TITLE
No id attribute on generated header tag

### ISSUE THREAD

**Issue by jbouzekri** [getgrav/grav#1205]
I have a page where I put this markdown : 

```
## My title

[link to my title](#my-title)
```

However it has generated : 

```
<h2>My title</h2>

<a href="#my-title">link to my title</a>
```

I think it is missing an id attribute on the h2 in order to allow a link to an anchor in the page.

**Comment by flaviocopes** [comment]
It's not missing, it's normal.

The Anchors plugin https://github.com/getgrav/grav-plugin-anchors provides this anchor functionality by adding an id to the header tags you want.

**Comment by jbouzekri** [comment]
Ok I did not know this plugin. Sorry for the wrong issue and thank you.

**Comment by NicoHood** [comment]
I found this post via google and it seems that the linked plugin is outdated and not working properly (found some issues).

There is a new alternative (also official) I want to mention here:
https://github.com/trilbymedia/grav-plugin-page-toc
