### ISSUE TITLE
Access `user/images/logo` via stream in twig

### ISSUE THREAD

**Issue by c33s** [getgrav/grav#1206]
as asked in [gitter][1] i was looking for a way to access `user/images/logo` via stream in twig
haven't found anything like this, i made a little [plugin][2].

```
{{ medium('image://logo.png').resize(35, 35).html('', '', 'logo') }}
```
my question: is this plugin necessary? do i oversee something? should i release the plugin?

[1]: https://gitter.im/getgrav/grav?at=5840615b8d65e3830ec56f8f
[2]: https://github.com/c33s/grav-plugin-twig-medium

**Comment by Perlkonig** [comment]
You can already  use `user://images/XXX`.

**Comment by mahagr** [comment]
New version (which will be released in few days) will already support this via page media:

```twig
{{ media('image://logo.png').resize(35, 35).html('', '', 'logo') }}
```

**Comment by rhukster** [comment]
@mahagr I think you forgot to add the Twig function for this to work??

**Comment by mahagr** [comment]
Well, the object is definitely defined, but it looks like that twig doesn't recognise object that can be called as a function.

Even `{{ page.media('image://test.jpg').resize(35, 35).html('', '', 'logo')|raw }}` doesn't work even if it should.

I don't really like

**Comment by rhukster** [comment]
Actually the syntax is:

```
{{ media[image://logo.png'].resize(35, 35).html('', '', 'logo') }}
```
