### ISSUE TITLE
"Identifier "messages" is not defined." in "partials/messages.html.twig" at line 1

### ISSUE THREAD

**Issue by jappe66** [getgrav/grav#1207]
I just updated all my plugins as well as the admin plugin itself to the latest versions and now I'm getting this error when trying to access admin:

> 0 - An exception has been thrown during the rendering of a template ("Identifier "messages" is not defined.") in "partials/messages.html.twig" at line 1.

In the log:

> [2016-12-12 08:55:02] grav.CRITICAL: An exception has been thrown during the rendering of a template ("Identifier "messages" is not defined.") in "partials/messages.html.twig" at line 1. - Trace: #0 /var/www/clients/client9/web13/web/v2/vendor/twig/twig/lib/Twig/Template.php(350): Twig_Template->displayWithErrorHandling(Array, Array) #1 /var/www/clients/client9/web13/web/v2/cache/twig/7d/7dff403d142e9a2d756f252e188ee962252b1330d727c9b7ba3cbc1ae1c80556.php(304): Twig_Template->display(Array) #2 /var/www/clients/client9/web13/web/v2/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_713c981bf753081f6a40091b53505b6c1775baba49cb1d114c0a80c716bb1686->block_messages(Array, Array) #3 /var/www/clients/client9/web13/web/v2/cache/twig/7d/7dff403d142e9a2d756f252e188ee962252b1330d727c9b7ba3cbc1ae1c80556.php(191): Twig_Template->displayBlock('messages', Array, Array) #4 /var/www/clients/client9/web13/web/v2/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_713c981bf753081f6a40091b53505b6c1775baba49cb1d114c0a80c716bb1686->block_page(Array, Array) #5 /var/www/clients/client9/web13/web/v2/cache/twig/7d/7dff403d142e9a2d756f252e188ee962252b1330d727c9b7ba3cbc1ae1c80556.php(158): Twig_Template->displayBlock('page', Array, Array) #6 /var/www/clients/client9/web13/web/v2/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_713c981bf753081f6a40091b53505b6c1775baba49cb1d114c0a80c716bb1686->block_body(Array, Array) #7 /var/www/clients/client9/web13/web/v2/cache/twig/7d/7dff403d142e9a2d756f252e188ee962252b1330d727c9b7ba3cbc1ae1c80556.php(45): Twig_Template->displayBlock('body', Array, Array) #8 /var/www/clients/client9/web13/web/v2/vendor/twig/twig/lib/Twig/Template.php(382): __TwigTemplate_713c981bf753081f6a40091b53505b6c1775baba49cb1d114c0a80c716bb1686->doDisplay(Array, Array) #9 /var/www/clients/client9/web13/web/v2/vendor/twig/twig/lib/Twig/Template.php(350): Twig_Template->displayWithErrorHandling(Array, Array) #10 /var/www/clients/client9/web13/web/v2/cache/twig/e0/e00ff3035159c99bc3f95d87ab63fa299c9c7be42969983e1a35fb1a6cdfa694.php(32): Twig_Template->display(Array, Array) #11 /var/www/clients/client9/web13/web/v2/vendor/twig/twig/lib/Twig/Template.php(382): __TwigTemplate_6ca9ecdcbf92903e60e3bc1747ec0fbc4fd17f33be5a2bcb60a97c3e1358b7ef->doDisplay(Array, Array) #12 /var/www/clients/client9/web13/web/v2/vendor/twig/twig/lib/Twig/Template.php(350): Twig_Template->displayWithErrorHandling(Array, Array) #13 /var/www/clients/client9/web13/web/v2/vendor/twig/twig/lib/Twig/Template.php(361): Twig_Template->display(Array) #14 /var/www/clients/client9/web13/web/v2/vendor/twig/twig/lib/Twig/Environment.php(357): Twig_Template->render(Array) #15 /var/www/clients/client9/web13/web/v2/system/src/Grav/Common/Twig/Twig.php(340): Twig_Environment->render('dashboard.html....', Array) #16 /var/www/clients/client9/web13/web/v2/system/src/Grav/Common/Service/OutputServiceProvider.php(18): Grav\Common\Twig\Twig->processSite(NULL) #17 /var/www/clients/client9/web13/web/v2/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #18 /var/www/clients/client9/web13/web/v2/system/src/Grav/Common/Processors/RenderProcessor.php(17): Pimple\Container->offsetGet('output') #19 /var/www/clients/client9/web13/web/v2/system/src/Grav/Common/Grav.php(121): Grav\Common\Processors\RenderProcessor->process() #20 /var/www/clients/client9/web13/web/v2/system/src/Grav/Common/Grav.php(358): Grav\Common\Grav->Grav\Common\{closure}() #21 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure)) #22 /var/www/clients/client9/web13/web/v2/system/src/Grav/Common/Grav.php(334): call_user_func_array(Object(Closure), Array) #23 /var/www/clients/client9/web13/web/v2/system/src/Grav/Common/Grav.php(122): Grav\Common\Grav->__call('measureTime', Array) #24 /var/www/clients/client9/web13/web/v2/system/src/Grav/Common/Grav.php(122): Grav\Common\Grav->measureTime('render', 'Render', Object(Closure)) #25 /var/www/clients/client9/web13/web/v2/index.php(45): Grav\Common\Grav->process() #26 {main} [] []

I have done "bin/gpm update" and "bin/composer.phar install".

I updated all of the plugins at once so I'm not sure which one triggered this but there was at least Email and Form plugins that needed to update.

**Comment by flaviocopes** [comment]
Question, you're using the latest stable version, or are you using the `testing` channel? 

I know I got this problem when I updated to Login (RC) but failed to update Admin too.

**Comment by jappe66** [comment]
Using the RC version. Now I'm back to stable version with no problems anymore. I should maybe stick with them :) just wanted to post this.

**Comment by flaviocopes** [comment]
If using RCs, update all plugins by putting Grav on the testing channel (`system.gpm.releases: testing`) so all plugins are up to date too

**Comment by Renkineko** [comment]
Hi, where should i save the ` system.gpm.releases: testing` line ? Same problem than OP here, but don't know if i'm using testing or stable, i updated grav from the interface and i don't remember what i downloaded back in time :)

Thanks

**Comment by flaviocopes** [comment]
You probably don't have the latest version of login or admin. Use `bin/gpm update` from the command line.

**Comment by Renkineko** [comment]
I tried that command but it just updated the themes one... :/
