### ISSUE TITLE
Unable to work with GRAV offline via admin

### ISSUE THREAD

**Issue by dayre** [getgrav/grav#1210]
I live in an area with very spotty internet, i've started a GRAV site i'd like to continue working with offline locally on my laptop (adding pages, changing config settings etc..)

The admin app doesn't seem too happy with the lack of network access.

It would be great if GRAV admin could handle this situation more gracefully and still allow for adding pages, changing configuration settings etc. without long delays and/or errors showing.

I haven't tried working with the command line commands in this situation, so not sure if it is an issue there as well.

**Comment by rhukster** [comment]
The command line has no requirements on external network, so that is 100% fine.

The admin plugin does by default check for updates, notfiications, etc.  Even google fonts are used by default.  You can disable most (all?) of these in the admin plugin configuration to turn them off.

**Comment by rhukster** [comment]
Offline has already been much improved since this issue was created.
