### ISSUE TITLE
Save as pdf : Problem ewith long code

### ISSUE THREAD

**Issue by Quentinvarquet** [getgrav/grav#1212]
Hello,

I tried to save my page as a PDF (ctrl+p) but I saw there is a problem when the "code" is too long.

Here is an example in the PDF :  

![image](https://cloud.githubusercontent.com/assets/7962157/21184023/e07bb03e-c20a-11e6-9a97-fde23084845f.png)

We can see the full code in the same line. Do you know of to fix it ?

Thank you

**Comment by rhukster** [comment]
Sounds like a CSS issue with whatever theme you are using, not a core Grav issue.  You just need to create a print style sheet and ensure that pre tags wrap in that.

http://support.printfriendly.com/publisher/developer-questions/custom-css-styles/
