### ISSUE TITLE
Markdown Twig filter stopped working

### ISSUE THREAD

**Issue by matthew-dean** [getgrav/grav#1213]
```twig
{% for p in page.collection %}
      {{ p.header.extra_description|markdown }}
{% endfor %}
```
The `extra_description` is a markdown editor field. This seemed to be working at some point, but now, it just returns blank. Other Twig filters work fine.

**Comment by flaviocopes** [comment]
What is the content of that field, to replicate the problem?

**Comment by rhukster** [comment]
Well simple stuff works.  I just tested with this:

```
{{ 'This is **Strong** and this is __italic__'|markdown }}
```

And it worked just fine.

**Comment by mmyrte** [comment]
I just ran into a possibly related problem - but I cannot be sure, since @matthew-dean didn't post specifics ;) 

Both when filtering as markdown _and_ when trying to render markdown from a normal page, a url with a `?query` in it gets truncated and only returns what's before the question mark.

I have the notion that there might be a problem with `Grav\Common\Markdown\ParsedownGravTrait` and its compatibility with upstream - but I don't have the time to try and solve the issue. Either it's a regex-issue specific to links, or it's more fundamental...

**Comment by flaviocopes** [comment]
`id` and other parameters are interpreted as link attributes. Use `noprocess` at the end of a URL that contains them (not intuitive, I know): https://learn.getgrav.org/content/linking#pass-through-supported-attributes

**Comment by mmyrte** [comment]
Thank you very much for your help, that did it - I must admit that reading that section of the docs never occurred to me. Happy new year!

**Comment by matthew-dean** [comment]
Twig data:
```
extra_description: "* 6, three-level luxury units from 4,500sf including the high exposure prominent corner unit\r\n* Existing luxury tenants: redacted, redacted\r\n\r\nLeasing Manager: Redacted Redacted\r\nEmail: [redacted.redacted@example.com](mailto:redacted.redacted@example.com)\r\nPhone: 604.555.7209"
```
We never got this working from the regular markdown filter. What I did was write a custom Twig filter for the collection that iterated through and used Grav's internal markdown converter.

**Comment by flaviocopes** [comment]
I got no issues in parsing that line

![screen shot 2017-01-03 at 09 43 13](https://cloud.githubusercontent.com/assets/11783388/21602875/df446bd2-d198-11e6-976b-923a2841552c.png)

I tried both putting the twig in the page directly, or in the template file. Cannot replicate the problem.

**Comment by matthew-dean** [comment]
Well, I don't know what to tell you. It always remained invisible and missing from the HTML markup. It's possible the other values on the page caused some other Twig or Grav bug. Calling the markdown filter directly in PHP for each member of the collection fixed it, so we did find a workaround.

**Comment by SkyKao** [comment]
I just tried `{{ 'This is **Strong** and this is __italic__'|markdown }}`, and it returns blank for me.

**Comment by rhukster** [comment]
Where are you putting it?

**Comment by SkyKao** [comment]
I put it inside my template.twig.html
`{{'This is **Strong** and this is __italic__'}}` works, but as soon as I put that `|markdown` filter, it just returns blank

**Comment by rhukster** [comment]
![2017-01-11 at 4 54 pm](https://cloud.githubusercontent.com/assets/1084697/21871331/bb019e48-d81e-11e6-8c64-5dd16bf6b848.png)

like this???

**Comment by rhukster** [comment]
Is this a modular page and template?

**Comment by SkyKao** [comment]
![screen shot 2017-01-11 at 3 58 48 pm](https://cloud.githubusercontent.com/assets/5401398/21871465/2a49201c-d817-11e6-8a2c-1fd70d902832.png)

Notice the first one works, before the `<hr>`, but the one after that, with the `|markdown` doesn't work.

**Comment by rhukster** [comment]
I believe, you but i just can't replicate this!

![2017-01-11 at 5 09 pm](https://cloud.githubusercontent.com/assets/1084697/21871636/b5bf9c9e-d820-11e6-9c4a-349f11061217.png)

Anything else going on? what plugins do you have installed?

**Comment by rhukster** [comment]
Probably a long shot, but try wrapping the var in a () like this:

```
{{ (page.header.walkthrough)|markdown }}
```

Also what version of Grav are you running?  Perhaps you can zip up the site and shoot me a copy so i can try with your exact setup?

**Comment by SkyKao** [comment]
I just updated Grav to the newest version, and also disabled all the plugins except the core ones.

No luck..

**Comment by rhukster** [comment]
Either put a zip of your current site, or download a base grav install, configure it in such a way that it fails the same way as your seeing, and zip that up.  That way I can get a working copy that recreates the issue, because I've not been able to recreate this at all.

**Comment by SkyKao** [comment]
I have figured it out, thanks Andy.
I was extending my theme on TwigExtension.

my code was: 
`public function getFilters() {
    return [
        new \Twig_SimpleFilter('sortByLocal', [$this, 'sortByLocal']),
        new \Twig_SimpleFilter('sortByLocalFeatured', [$this, 'sortByLocalFeatured'])
    ];    
  }`

I updated it to this.

`public function getFilters() {
    $arr = parent::getFilters();
    return $arr + [
        new \Twig_SimpleFilter('sortByLocal', [$this, 'sortByLocal']),
        new \Twig_SimpleFilter('sortByLocalFeatured', [$this, 'sortByLocalFeatured'])
    ];    
  }`

And it works.

**Comment by rhukster** [comment]
ah!!! good to know.  There's a safer way to do that though, this is for a function, but same goes for filter:

```
    /**
     * Add simple `stars()` Twig function
     */
    public function onTwigInitialized()
    {
        $this->grav['twig']->twig()->addFunction(
            new \Twig_SimpleFunction('stars', [$this, 'generateStars'])
        );
    }
```

**Comment by flaviocopes** [comment]
So @SkyKao issue was he was removing all other Twig filters when adding his custom ones.

Remains @matthew-dean which is still not clear.

**Comment by SkyKao** [comment]
we're actually working on the same project..

**Comment by matthew-dean** [comment]
@rhukster Why does adding a Twig extension that adds filters make previous registered extensions / filters unavailable?

**Comment by rhukster** [comment]
It was the way it was being done.  It was actually clearing out all existing filters and replacing it with the custom one from the theme.  Their solution was to add the new filter to the existing ones.  However, my better solution is to simply 'addFunction' (or 'addFilter') in this case.  So there's never any chance of replacing all the existing filters.

**Comment by matthew-dean** [comment]
Ah ok. Thanks!

**Comment by matthew-dean** [comment]
@rhukster Can you explain a little more why it didn't work? The flow doesn't look any different than: https://github.com/kesslernetworks/grav-plugin-twigpcre.

That is, it's registering a Twig extension which returns filters. Why does it work with PCRE extension and didn't for us?

**Comment by SkyKao** [comment]
@rhukster I just realized my sortByLocal and sortByLocalFeatured doesn't work after that.
`public function getFilters() {
    $arr = parent::getFilters();
    return $arr + [
        new \Twig_SimpleFilter('sortByLocal', [$this, 'sortByLocal']),
        new \Twig_SimpleFilter('sortByLocalFeatured', [$this, 'sortByLocalFeatured'])
    ];    
  }`

**Comment by rhukster** [comment]
You really should use the techinque I pasted above.  That is the preferred approach: http://twig.sensiolabs.org/doc/1.x/advanced.html

**Comment by flaviocopes** [comment]
@SkyKao The `+` operator is not doing what you expect it to do. It's _not_ merging the 2 arrays. See http://stackoverflow.com/a/2140094

**Comment by flaviocopes** [comment]
Closing the issue as it's a plugin coding issue now and the original problem is solved.
