### ISSUE TITLE
Multisite Quirks

### ISSUE THREAD

**Issue by elproducto** [getgrav/grav#1215]
I noticed a few issue with Multisite setup following directions on the Learn Grav pages.  Not sure if the following items are by design or maybe a bug.

1. Unable to download plugin on sub site, got error, touch(): Unable to create file /license.yaml because Permission denied. The Main site can download and install plugin without any issue
2. Statistics counter is not per site but show statistics for all sites.  Tested by loading pages from main site and subsite and watched number go up on both sites.
3. Separate admin credential per site, not an issue I thought maybe it would be one login and you could maintain the various sites from that one login.  I see why multiple logins would be beneficial to maintain separation of sites, but would not mind one interface to manage them all.
4. Plugin & Theme are not shared. I guess I could symlink them across the various sites

![image](https://cloud.githubusercontent.com/assets/3057562/21235784/446c885a-c2c6-11e6-83b9-eceeb93b46e1.png)

**Comment by w00fz** [comment]
For this error in the screenshot, it seems you don't have the proper permissions set for the `user/data` folder. Try making that folder writable.

**Comment by elproducto** [comment]
I tried with 777 and now 775 and got the same results when trying to install a plugin.  I also logged in as root and ran chown -R myphpuser:myphpuser on my Public HTML folder and still the same result when attempting to install plugins.

**Comment by flaviocopes** [comment]
I hear you, these are multisite quirks we need to document and hopefully clear out over time. Another one I know for example is, triggering a backup backups all sites.

**Comment by tourtools** [comment]
the licence.yaml for the single site has to be in /user/sites/[sitename-folder]/data dir, usually it has a 644 mod, the non accessibility it depends on the webserver user's group, 
try to set it to 664,
for me it worked
