### ISSUE TITLE
Custom tabs slide under Normal / Expert buttons

### ISSUE THREAD

**Issue by matthew-dean** [getgrav/grav#1216]
Picture is self-explanatory. The CSS doesn't seem to account for tabs that span the width of the page editing box.

<img width="901" alt="screen shot 2016-12-15 at 3 32 47 pm" src="https://cloud.githubusercontent.com/assets/414752/21246163/d7660ffe-c2db-11e6-8f68-a02639c06e9e.png">

**Comment by rhukster** [comment]
Fixed
