### ISSUE TITLE
[add-resource] New Plugin loginldap

### ISSUE THREAD

**Issue by markleary** [getgrav/grav#1220]
I would like to add my new pluginto the Grav Repository.  Here are the project details: https://github.com/markleary/grav-plugin-loginldap

This provides the ability to login/authenticate against an LDAP directory (tested with Microsoft AD).  It is compatible with the page level access restrictions used by the login plugin.  Originally, I tried extending the login plugin similar to how login-oauth was written, but ultimately it made more sense to start fresh, reusing some of the base login code.

**Comment by rhukster** [comment]
Thanks! will get this added shortly.

**Comment by rhukster** [comment]
Added.. sorry for the delay

**Comment by w00fz** [comment]
Your plugin is not getting added to the repository because the Release version (v0.3.0) doesn't match the blueprint (0.3.0).

Can you try deleting the tag and recreating it with 0.3.0, no `v` prefix. Once you do that, GPM should start picking it up automatically

**Comment by markleary** [comment]
All set, thanks.

**Comment by markleary** [comment]
Does not look like this has been picked up by gpm yet, am I missing something else?

**Comment by w00fz** [comment]
It keeps failing at the 'getRelease', did you mean to keep your plugin in `testing` or did you plan this to be a stable release?

In your blueprint you have `testing: true` but when you created your release you didn't mark it as 'pre-release', this might be the cause of it failing.

If you edit your current release you can check the 'pre-release' option in GitHub.

![gantry5 2017-01-05 09-18-43](https://cloud.githubusercontent.com/assets/11734/21690183/ff71db5c-d327-11e6-96b3-70088d690b35.png)

**Comment by markleary** [comment]
Ahh, I set testing: false and updated release.  Thanks.

**Comment by w00fz** [comment]
There might still be something off, I'm investigating because other than that testing flag you fixed now, I don't see anything wrong.

**Comment by w00fz** [comment]
Ok it's sorted now, should appear soon. Sorry about that!
