### ISSUE TITLE
Debugbar error in 1.1.11

### ISSUE THREAD

**Issue by josbeir** [getgrav/grav#1227]
Am experiencing issues after upgrading to 1.1.11 with the debugbar extension in the admin plugin (see screenshot) after running an ajax request (in this case focussing a filepicker field).

Tried it with a fresh install and still have the issue. 

Disabling the debugger 'solves' the issue for now.

![screen shot 2016-12-25 at 18 55 36](https://cloud.githubusercontent.com/assets/26058/21472311/d07325c4-cad3-11e6-93aa-139aca74e459.png)

**Comment by rhukster** [comment]
what version of admin are you running? We have a fix for that in the latest version, but updating requires disabling the debugger.

**Comment by rhukster** [comment]
oh, is this specific to the filepicker field? that might be one we missed...

**Comment by josbeir** [comment]
Using admin panel 1.2.7
Am indeed experiencing this with the filepicker field. Also encountered it during the plugin upgrade process after updating grav (using the admin plugin) but after that i think it went away there. 

Still experiencing it with the filepicker however.

**Comment by rhukster** [comment]
Ok fixed this in Grav core.. will be released soon.

**Comment by josbeir** [comment]
thanks!
