### ISSUE TITLE
Theme related suggestions

### ISSUE THREAD

**Issue by DonD01** [getgrav/grav#1229]
Hi, I have some suggestions related to Base Template, theme tutorial and variables, from the theme developer's perspective.

----------

`{% set theme_config = attribute(config.themes, config.system.pages.theme) %}`
That's not great to be required to define a basic variable by default in a template. I found it's already available in grav as `config.theme` so maybe we can delete this from Base Template and docs.

`<html lang="{{ grav.language.getActive ?: theme_config.default_lang }}">` -> 
`<html lang="{{ page.language ?: site.language }}">`
There's already `page.language` available, just introduce default variable `site.language` and it gets a lot cleaner.  `theme_config.default_lang` is not the best because it should be default site language as set by the user and not theme language as set by theme developer. `default_lang` is also not even defined in the theme config of Base Template. 

`<title>{% if header.title %}{{ header.title|e('html') }} | {% endif %}{{ site.title|e('html') }}</title>` ->
`<title>{% if page.title %}{{ page.title|e }} | {% endif %}{{ site.title|e }}</title>`
`page.title` is more intuitive and doesn't introduce new top-level variable, 'html' is default for escape filter

`<link rel="canonical" href="{{ page.url(true, true) }}" />`
Maybe consider introducing some new variable like `page.permalink` but for canonical, e.g. `page.canonical`

`{{ page.header.body_classes }}` - > `{{ page.body_classes }}`

`{{ base_url == '' ? '/' : base_url }}`
Can't `base_url` just return '/' instead of ''? Also I had to check where it came from as it's a new top-level variable. Something like `site.url` would be more intuitive.

`{{ config.site.title }}` -> `{{ site.title }}`

----------

Generally speaking I'd make most of variables available as `x.y` and not `x.y.z`, while also limiting the number of top-level `x` variables available.

`config.system.variable` -> `system.variable`
`config.theme.variable` -> `theme.variable`
`config.site.variable` -> `site.variable`
`page.header.variable` -> `page.variable`
`header.variable` -> `page.variable`

I think these changes would make Base Template, documentation, and workflow with grav more clean and intuitive. Some of them are already supperted but not documented as default worflow.

**Comment by rhukster** [comment]
Some of these are good ideas and would definitely make things a little easier.  As i'm already actually working on a new default theme, i'll see what I can do about adding some of these improvements.

The one thing that is not relaly possible, is the `header.variable` -> `page.variable`.  There could be conflicts here as the header is a flexible YAML powered set of variables, where as the page itself, is an object that represents the page.  The `header.` is simply a shortcut for `page.header.`

**Comment by DonD01** [comment]
Grav looks good, I'm glad to provide some feedback.

About `header.variable` -> `page.variable`, I put `{{ page.title }}` in a template and it also alredy works as shortcut for `{{ page.header.title }}`! Is it discouraged to use `page.title`, and rather type `header.title` or `page.header.title`? It's easier to remember and more consistent to me to just use `page.language` and `page.title` instead of `page.language` but `headers.title` or `page.headers.title`. Also that way I can have mirrored default variables in `site.` and just type: `{{ page.title|e }} | {{ site.title|e }}` or `{{ page.language ?: site.language }}`.

**Comment by rhukster** [comment]
Quite a few improvements have been taken care of here: https://github.com/getgrav/grav/pull/1232

**Comment by rhukster** [comment]
This PR has been merged, just need to document it all!
