### ISSUE TITLE
[add-resource] New Plugin 'Add Page By Form'

### ISSUE THREAD

**Issue by bleutzinn** [getgrav/grav#1230]
I would like to suggest to add a new plugin to the Grav Repository. The project is available at:
[https://github.com/bleutzinn/grav-plugin-add-page-by-form](https://github.com/bleutzinn/grav-plugin-add-page-by-form)

The plugin allows front end users to create a page by filling in a form. It has been tested with Grav v1.1.12 - Admin v1.2.7 both on localhost and on a Debian server.

**Comment by bleutzinn** [comment]
The latest release (v1.3.0) features the SimpleMDE Markdown Editor. If properly configured (by given the textarea field the id: simplemde), users can write content in a WYSIWYG like editor and  content will be saved as markdown.

**Comment by rhukster** [comment]
Added to GPM.. Should show up shortly.
