### ISSUE TITLE
Installation aborted for dependency during plugin install

### ISSUE THREAD

**Issue by Rarst** [getgrav/grav#1233]
I installed Grav using `composer create-project` method, followed by `php bin/grav install` (Composer hook failed for me since Windows needs explicit `php` to execute the file).

It worked fine, but subsequent attempt to install Admin plugin is failing on Form package dependency:

```
>php bin/gpm install admin

GPM Releases Configuration: Stable

The following dependencies need to be installed...
  |- Package form
  |- Package email
  |- Package login

Install these packages? [Y|n]
Preparing to install Form [v2.0.8]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...  Installation aborted
```

Looking up the place in source and dumping respective Exception message:

```
rename(C:/server/www/grav/tmp/Grav-586d16512d971/getgrav-grav-plugin-form-22c1a94/,C:\server\www\grav/user/plugins/form): ╬Єърчрэю т фюёЄєях. (code: 5)
```

**Comment by flaviocopes** [comment]
Did you download from Github, or you used the stable release? What does ╬Єърчрэю т фюёЄєях mean?

**Comment by flaviocopes** [comment]
Rephrase: using Composer you installed the latest stable, or the current development version?

**Comment by Rarst** [comment]
> Rephrase: using Composer you installed the latest stable, or the current development version?

Latest stable.

```
>php bin/grav --version
Grav CLI Application version 1.1.12
```

> What does ╬Єърчрэю т фюёЄєях mean?

Nothing meaningful. Looks like something in cyrillic (probably error message from the system) got garbled somewhere in the process.

**Comment by Rarst** [comment]
Seems to be permissions issue on the source folder, I was able to make it work by throwing this into `Folder::move()`:

```php
$iterator = new \RecursiveIteratorIterator( new \RecursiveDirectoryIterator( dirname( $source ) ), \RecursiveIteratorIterator::SELF_FIRST );
foreach ( $iterator as $item ) {
    chmod( $item, 0777 );
}
```

Had you considered Symfony Filesystem for file operations? Makes stuff like this a little easier cross–platform.

**Comment by rhukster** [comment]
I looked at Symfony filesystem library when I started Grav.  It was just too slow for our purposes back then, not sure if anything has changed since.

**Comment by Rarst** [comment]
Not sure why it would introduce performance overhead, without knowing more context. I mostly value it for being a little more smart and fluent API. It seems to me it's pretty thin wrapper around filesystem functions most of the time.

**Comment by rhukster** [comment]
Definitely something we will revisit for Grav 2.0.

**Comment by mahagr** [comment]
Also symfony filesystem doesn't really work for Grav as its relaying more and more on streams.

What comes to chmodding everything to 0777, I wouldn't recommend it. You should set your Apache so that you'd not run into permission issues. Or just chown everything in your www folder into `www-data.` or whatever apache uses.

**Comment by Rarst** [comment]
This isn't issue with _existing_ files as much as with temp directory being created then attempted to be moved without sufficiently robust check that it _can_ be moved. For example of handling this WP in "direct" filesystem mode will try to fallback to `copy()` with subsequent delete, if straight `rename()` fails.

`0777` specifically is just a quick and dirty test here for what gets in the way.

**Comment by mahagr** [comment]
We've already changed our move logic to do that. Just test out CI build if it works in there.

**Comment by Rarst** [comment]
Great, thank you! :) Confirm as working in my system.

Fixed by https://github.com/getgrav/grav/commit/cc96d160a4b4d1c2d7b274a5dbe53fddded62a38
