### ISSUE TITLE
Always Blank Hover after i click active themes or plugins

### ISSUE THREAD

**Issue by blackmamb41** [getgrav/grav#1234]
Please help me what wrong with my grav, always blank hover if i click active themes or plugins
![image](https://cloud.githubusercontent.com/assets/11955657/21668102/360169f4-d331-11e6-9f60-f56f64098cb2.png)

**Comment by flaviocopes** [comment]
It should show a modal with a confirmation message:
 
![screen shot 2017-01-05 at 09 51 37](https://cloud.githubusercontent.com/assets/11783388/21674051/59c4a37e-d32c-11e6-854e-93a767012c56.png)

Try disabling Adblock (or a similar browser extension) on the page, does it work? In this case, which extension is it?

**Comment by rhukster** [comment]
Also what browser is that? IE? can you try something newer?

**Comment by rhukster** [comment]
Closing to due to inactivity
