### ISSUE TITLE
[add-resource] New Plugin: Vimeo

### ISSUE THREAD

**Issue by cworreschk** [getgrav/grav#1235]
I would like to add my new plugin to the Grav Repository.

Like your YouTube-Plugin my Vimeo plugin converts markdown video links to html embed code.

These are the main features:
- Embed Vimeo videos and configure the player
- Override the player parameters for each page
- Button to add Vimeo videos in the content editor
- Twig functions to embed Vimeo videos in other templates
- Multi-Language Support (Currently `de` and `en`)

Here are the project details: **[cworreschk/grav-plugin-vimeo](https://github.com/cworreschk/grav-plugin-vimeo)**

**Comment by rhukster** [comment]
Added to GPM, should show up soon.
