### ISSUE TITLE
Taxonomy Search not working properly

### ISSUE THREAD

**Issue by leveled** [getgrav/grav#1238]
I seem to be running into some errors with searching for items in Grav via taxonomy categories. As an example I have a blog page setup as such

~~~
user@host:# ls -R 01.Blog/an_entry/ 
item.md
sub-entry-1/
  item.md
sub-entry-2/
  item.md
~~~
In this case the parent 'an_entry' has tags and each 'sub-entry' has tags as well. If I'm on the front page of the blag and search for tags I am only returned results for 'an entry' . Is it possible to get the sub entries to show up in a taxonomic search as well?

**Comment by flaviocopes** [comment]
Is this a problem specific to the Simplesearch plugin?

I tried and I don't get issues with searching in the sub entries. They show up in the search.
