### ISSUE TITLE
Body-classes not being added to the page

### ISSUE THREAD

**Issue by arnoldstoba** [getgrav/grav#1240]
When i try to add custom body-classes to a page, nothing is added in the rendered document. The classes are added to the meta information inside the .md files, but are not displayed in the frontend. Anything i'm doing wrong? Cache cleared and tested on multiple sites.

**Comment by flaviocopes** [comment]
That feature must be implemented by the theme. All the core themes should do it by adding a line similar to

```html
<body class="{{ page.header.body_classes }}">
```

in their base twig.

Which theme is yours?

**Comment by rhukster** [comment]
also the page frontmatter should have a matching:

```
body_classes: my-class
```

**Comment by arnoldstoba** [comment]
@rhukster The frontmatter contains my body_classes, but they are not displayed in the frontend.
@flaviocopes I am using the [GRAV-saturn theme](https://github.com/getgrav/grav-theme-saturn).

**Comment by flaviocopes** [comment]
Fixed in the theme, issuing a release
