### ISSUE TITLE
Consider composer/ca-bundle for safer connectivity

### ISSUE THREAD

**Issue by Rarst** [getgrav/grav#1241]
As [docs on GPM troubleshooting](https://learn.getgrav.org/troubleshooting/common-problems#cannot-connect-to-the-gpm) note SSL verification is a typical issue. Especially in Windows context, where curl in PHP typically needs explicit certificates file set up for it to work.

Rather than recommending to disable verification I would urge to consider [composer/ca-bundle](https://github.com/composer/ca-bundle) package, which helps try find system’s certificate bundle and ships with Mozilla’s as fallback.

**Comment by rhukster** [comment]
Something we should look into!  Just have to find a system we can replicate this issue on to know if this will make a difference.  Cheers.

**Comment by rhukster** [comment]
I've investigated and now added this to develop branch.  Please test it when you get a chance. Thanks.
