### ISSUE TITLE
[add-resource] New Plugin: QR Code

### ISSUE THREAD

**Issue by cworreschk** [getgrav/grav#1242]
I would like to add my new plugin to the Grav Repository.

With this plugin you can create easily QR Codes and embed them in your site by using the shortcode `[qrcode]` in your content.

These are the plugin features:

* Simply create QR Codes with the shortcode [qrcode]
* Override the plugin parameters for each page
* Inline attributes for the QR Code shortcode element
* Button to add QR Codes in the content editor
* Twig functions to embed QR Codes in your templates
* Multi-Language Support (Currently `en` and `de`)

The project details are here: **[cworreschk/grav-plugin-qrcode](https://github.com/cworreschk/grav-plugin-qrcode/tree/master)**

**Comment by rhukster** [comment]
Added to GPM
