### ISSUE TITLE
"Invalid security token; please reload the page and try again" only when saving theme settings

### ISSUE THREAD

**Issue by patriclougheed** [getgrav/grav#1245]
Got Grav running great in my Linux, PHP7, Nginx space and can do everything fine except save theme settings. Just updated to latest build and all plugins as well with no change. Double checked file permissions as well. Using Grav v1.1.12  and Admin v1.2.7

Using Nginx conf supplied and no errors being logged. 

Turned debug on and attached results.

[grav_debug.txt](https://github.com/getgrav/grav/files/702898/grav_debug.txt)

**Comment by rhukster** [comment]
@mahagr looks like a gantry5 issue?

**Comment by patriclougheed** [comment]
My bad... I now see that the appearance menu is specific to gantry themes.

**Comment by mahagr** [comment]
Same as https://github.com/gantry/gantry5/issues/1748

I'm really not sure what could cause this to fail in Nginx as we just call

```php
$nonce = Utils::getNonce('gantry-admin');
```

and

```php
    protected function checkSecurityToken()
    {
        /** @var Request $request */
        $request = $this->container['request'];
        $nonce = $request->get->get('nonce');
        return isset($nonce) && Utils::verifyNonce($nonce, 'gantry-admin');
    }
```

**Comment by flaviocopes** [comment]
Same as https://github.com/getgrav/grav-plugin-admin/issues/893#issuecomment-271974482 using g5_hydrogren

**Comment by flaviocopes** [comment]
Replicated

**Comment by mahagr** [comment]
Please update nginx.conf: 

```
    location / {
        try_files $uri $uri/ /index.php?_url=$uri&$query_string;
    }
```

**Comment by patriclougheed** [comment]
Works like a charm now! Thanks

**Comment by regalstreak** [comment]
Not nginx.conf but well the configuration of the site in ```sites-available```
