### ISSUE TITLE
[add-resource] New Plugin: Admin Styles

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1246]
I would like to add a plugin to the Grav Repository, here are the project details: [grav-plugin-adminstyles](https://github.com/OleVik/grav-plugin-adminstyles).

Note: This is a [pre-release](https://github.com/OleVik/grav-plugin-adminstyles/releases/tag/v0.9.1) (v0.9.1), and somewhat of a work in progress. Please report any issues or inconsistencies through the [issue-tracker](https://github.com/olevik/grav-plugin-adminstyles/issues).

**Comment by rhukster** [comment]
Added to GPM. Thanks.

**Comment by rhukster** [comment]
Failed because it needs a release.

**Comment by OleVik** [comment]
Pre-releases don't count? I'll do a proper release of v1.0.0 after some visual regression tests in the next few days and update this issue.

**Comment by rhukster** [comment]
you still need to release, but need to set it to pre-release checkbox.  I strongly suggest still tagging your RC versions too.

**Comment by OleVik** [comment]
v0.9.1 is created as a pre-release and tagged, using GitHubs interface, thought that would work.

**Comment by rhukster** [comment]
I think the problem now is you have tagged 0.9.1, but the blueprints still points to 0.9.0

**Comment by OleVik** [comment]
Ahh, the blueprint gets me 50% of the time I push an update!

**Comment by OleVik** [comment]
Proper release is out, [v1.0.0](https://github.com/OleVik/grav-plugin-adminstyles/releases) in release-tag, blueprint, and changelog.

**Comment by rhukster** [comment]
Ok, showing fine now in GPM.
