### ISSUE TITLE
Problem when outputting images with twig. Incorrect url.

### ISSUE THREAD

**Issue by DavideTrendstudio** [getgrav/grav#1247]
Using this code

      {% for item in page.header.gallery %}
        {% set image = page.media[item.src].cropZoom(800, 600).quality(70) %}
        <a href="{{ image.url }}">
          <img src="{{ image.url }}" alt="{{ item.alt }}" title="{{ item.title }}" />
        </a>
      {% endfor %}

the output of {{ image.url }} is different for the link and the image. Also "cropZoom" and "quality" does not apply to the images.

The link href results in: /images/3/a/7/f/2/3a7f258ac043fa43b12530c5a519eb80aeeea6a1-image.jpeg
and the image src in: /images/4/e/d/4/9/4ed497e604c57259d515cd55bd6378adb3d6ef80-image.jpeg

The second print statement results always in an incorrect url.

Removing the link from the code, for example, solves the problem.

  {% for item in page.header.gallery %}
       {% set image = page.media[item.src].cropZoom(800, 600).quality(80) %}
        <img src="{{ image.url }}" alt="{{ item.alt }}" title="{{ item.title }}" />
    {% endfor %}

What is the issue here?

**Comment by rhukster** [comment]
can you provide your page header with the gallery info? i would like to try to recreate this as i'm not 100% sure what you are seeing.

**Comment by rhukster** [comment]
btw, it sounds like calling `url()` is resetting the media actions, hence the different URL and lack of actions visible.

A quick solution would be:

```
 {% for item in page.header.gallery %}
    {% set image = page.media[item.src].cropZoom(800, 600).quality(70) %}
    {% set image_url = image.url %}
    <a href="{{ image_url }}">
      <img src="{{ image_url }}" alt="{{ item.alt }}" title="{{ item.title }}" />
    </a>
  {% endfor %}
```

However, I think it's a bug that does need fixing.

**Comment by rhukster** [comment]
Oh there is a reset param on that already, but it's `true` by default, you can pass it in manually:

```
{% for item in page.header.gallery %}
    {% set image = page.media[item.src].cropZoom(800, 600).quality(70) %}
    <a href="{{ image.url(false) }}">
      <img src="{{ image.url }}" alt="{{ item.alt }}" title="{{ item.title }}" />
    </a>
  {% endfor %}
```

But this is not very obvious, frankly i think this should be modified to be `false` by default. I'll have to test thought to see if this has any implications with chained methods.

**Comment by DavideTrendstudio** [comment]
Here is my Blueprint:

              header.gallery:
                  type: list
                  label: ADD_IMAGES
                  style: vertical
                  fields:
                    .src:
                      type: filepicker
                      folder: 'self@'
                      label: SELECT_IMAGE
                      preview_images: true
                      style: vertical
                    .alt:
                      type: text
                      label: ALT_TEXT
                    .title:
                      type: text
                      label: TITLE_ATTRIBUTE


and the array in the header:

gallery:
    -
        src: ambiente.jpg
    -
        src: anreise.jpg
    -
        src: bar.jpg

**Comment by rhukster** [comment]
Can you try my recommendations above?

**Comment by DavideTrendstudio** [comment]
I have changed the code. Setting {{ image.url(false) }} for the href works fine. The href and src attributes are the same and the "cropZoom" and "quality" applies to the image.

**Comment by rhukster** [comment]
Yah, i looked at the code, and changing the default to `false` has too many dependencies.  Pretty much every function resets the previous actions.  If this was changed, it would result in strange results when chaining other functions together.  It's not something we can do without potentially breaking people's sites.  

Either:

1) assigning the value to a variable, and reusing that
2) explicitly disabling the reset (as you have done) in the method call

These are the two best solutions.

**Comment by DavideTrendstudio** [comment]
Ok. Thanks for the help!
