### ISSUE TITLE
Markdown parser does not escape * character inside of backticks

### ISSUE THREAD

**Issue by ekumlin** [getgrav/grav#1248]
If given the following input...

```
*(Test `a*b` test`.)*
```

... Grav's Markdown parser will actually parse it into something like...

```
<i>(Test `a</i>b<code> test</code>.)*
```

Whereas it should be parsed into...

```
<i>(Test <code>a*b</code> test`.)</i>
```

This is in line with how, for example, GitHub renders it: *(Test `a*b` test`.)*

Here's some shots directly from Grav using the input above.

Desired (written using HTML):
![](http://i.imgur.com/1wLNJAe.png)

Actual (written using Markdown):
![](http://i.imgur.com/aCrpdJC.png)

**Comment by flaviocopes** [comment]
Grav uses Parsedown. I tried the [online demo](http://parsedown.org/demo) and replicated the problem:

![screen shot 2017-01-14 at 15 59 34](https://cloud.githubusercontent.com/assets/11783388/21955777/1cf0b0ee-da72-11e6-9a1d-6ac77614f5db.png)

It's an upstream issue, that means an issue in a library Grav uses. 

Can you open the issue on their issue tracker? https://github.com/erusev/parsedown/issues 

Thanks!

**Comment by ekumlin** [comment]
Did so!

Tracking this in [parsedown/434](https://github.com/erusev/parsedown/issues/434) and [parsedown/461](https://github.com/erusev/parsedown/issues/461).

Should I leave this open, or would you prefer to close [external] bugs?

**Comment by flaviocopes** [comment]
Let's close this, since we have no control over it, but people stumbling on this problem will likely find the issue through Google and the issues search.
