### ISSUE TITLE
Explicit, required dependencies

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1251]
The [current system](https://learn.getgrav.org/forms/blueprints/example-plugin-blueprint) of dependencies is optional, in the form of:

```
dependencies:
  - afterburner2
  - github: https://github.com/getgrav/grav-plugin-github.git
  - { name: email, version: '~2.0' }
```

This allows for flexibility in what plugins and themes a different plugin/theme depend on for functionality, but may also break installations upon update. I propose that the `dependencies`-property be required, including what version of Grav's core the plugin/theme **depends on**, and additionally was **tested with**. This would look like:

```
dependencies:
  - { name: grav, version: '~1.1.12', tested: '1.1.12' }
```

Imagine a scenario where a plugin depends on Grav version `~1.1.9` and Admin-plugin `1.2.7`, which in turn depends on Form-plugin `~2.0`, Email-plugin `~2.0`, and Login-plugin `~2.0`. If the plugin overrides parts of any of these, with the functionality as it exists at these versions, then an upgrade to these implicit dependencies can break their functionality inadvertently through the plugin's overrides.

So rather than an implicit dependency, where upgrades can break them, the following as required would prevent upgrading implicit dependencies to a point where the installation breaks:

```
dependencies:
    - { name: grav, version: '~1.1.9', tested: '1.1.9' }
    - { name: admin, version: '~1.2.7', tested: '1.2.7' }
    - { name: form, version: '~2.0' }
    - { name: email, version: '~2.0' }
    - { name: login, version: '~2.0' }
```

Thus a full system upgrade allows upgrading to the newest versions in the range of Grav core `>=1.1.9 <1.2.0`, Admin-plugin `>=1.2.7 <1.3.0`, Form-plugin `>=2.0.0 <2.1.0`, Email-plugin `>=2.0.0 <2.1.0`, Login-plugin `>=2.0.0 <2.1.0`. Without being a required property, upgrades exceeding these versions could break installations, but could still be allowed by a `--force`-parameter in the upgrade-process for the adventurous.

**Comment by rhukster** [comment]
To be honest, i feel like this is a bit of overkill . We have dependencies with versions, but they are rarely used.  We use them when needed, and they have worked fine, and it's already far beyond the capability of most platforms.

**Comment by OleVik** [comment]
That is indeed the problem, they are too rarely used. Even with a less strict dependency-system than proposed above, any update to a plugin or theme can potentially break functionality if it is tested with major or minor updates (following SemVer).

Plugins especially can override functionality and structure, and so a minimal dependency-specification of `{ name: grav, version: '~1.1' }` would indicate that upgrading beyond that MAJOR.MINOR-version is untested, thus at least informing the user that this may break functionality unintentionally.

Given that requirement, core, plugins, and themes can be upgraded as far as possible within the given constraints, in this instance any patches to core are assumed safe to apply.

**Comment by rhukster** [comment]
Closing to due to inactivity
