### ISSUE TITLE
Broken symbolic links in directory cause SplFileInfo::getMTime to fail

### ISSUE THREAD

**Issue by indigoxela** [getgrav/grav#1254]
Hi,
just realized this problem: if a directory below user/pages/ contains a broken symbolic link, I get a fatal error:
`SplFileInfo::getMTime(): stat failed for /bla/bla/file...`

This is easy to reproduce. Create a symbolic link, remove the link target file.
Condition: the broken symlink must contain ".md" _somewhere_ in its name.

Examples:
.what-ever-name.mdfoo-bar.txt
.what-ever-name.mdfoo-bar.end

This problem even occurs with dot-files and with "ignore_hidden" set to true.
And ".md" can be anywhere in the filename, not only as an ending.

How can I solve that?

Possibly grav should be a bit stricter when parsing directories?

**Comment by indigoxela** [comment]
Another important condition for above error to occur:
```
cache:
  enabled: true 
  check:
    method: file
```
So this is actually a caching problem.

**Comment by flaviocopes** [comment]
Thanks for reporting
