### ISSUE TITLE
Schedule post/page by daily hours?

### ISSUE THREAD

**Issue by prinla** [getgrav/grav#1255]
Hello,
Any possibility to schedule a post or the publishing of a page on a daily base by hour?
Ex. Every day between 12:00 and 18:00 a post appears on the webpage.

Indeed I would love to make appear a "OPEN NOW" during working times... without needing to change it manually every day.

Any ideas?

**Comment by flaviocopes** [comment]
It cannot be done currently, the page can be scheduled to be published/unpublished just once. It could be a good job for a plugin.

**Comment by dimayakovlev** [comment]
@prinla This can be done with Twig in template. No plugin required. If current time is in range then do what you want. See twig `date` function http://twig.sensiolabs.org/doc/2.x/functions/date.html

**Comment by flaviocopes** [comment]
@dimayakovlev I didn't think about using Twig, good one 👍

**Comment by dimayakovlev** [comment]
@prinla Set start and end of working time in page header.

```yaml
working_time:
  start: '12:00'
  end: '18:00'
```

In Twig template you can implement what you want to do. Simplest example is:

```twig
{% set current_date = date() %}
{% if current_date >= date(page.header.working_time.start) and current_date < date(page.header.working_time.end) %}
We are working
{ % else %}
We are closed
{% endif %}
```
