### ISSUE TITLE
Cookie plugin

### ISSUE THREAD

**Issue by RUSampson** [getgrav/grav#1256]
Colleagues, just download new ver of cookies notify plugin.

How can i help you to fix this?

PS
grav newest, trying without any modules and with gantry5 - nothing changes

RuntimeException thrown with message "Failed to read languages.yaml: Malformed inline YAML string: 'Cerrar at line 60 (near "DIMISS: 'Cerrar")."

Stacktrace:
#31 RuntimeException in /system/src/Grav/Common/File/CompiledFile.php:82
#30 Symfony\Component\Yaml\Exception\ParseException in /vendor/symfony/yaml/Inline.php:286
#29 Symfony\Component\Yaml\Inline:parseQuotedScalar in /vendor/symfony/yaml/Inline.php:232
#28 Symfony\Component\Yaml\Inline:parseScalar in /vendor/symfony/yaml/Inline.php:71
#27 Symfony\Component\Yaml\Inline:parse in /vendor/symfony/yaml/Parser.php:537
#26 Symfony\Component\Yaml\Parser:parseValue in /vendor/symfony/yaml/Parser.php:231
#25 Symfony\Component\Yaml\Parser:parse in /vendor/symfony/yaml/Yaml.php:65
#24 Symfony\Component\Yaml\Yaml:parse in /vendor/rockettheme/toolbox/File/src/YamlFile.php:82
#23 RocketTheme\Toolbox\File\YamlFile:decode in /system/src/Grav/Common/File/CompiledFile.php:57
#22 Grav\Common\File\CompiledYamlFile:content in 

And more than 60 points more

**Comment by rhukster** [comment]
You probably should create this ticket on the repo of the cookie plugin itself, not here.  This is for core-grav issues.

**Comment by RUSampson** [comment]
My missunderstanding, of course. Sorry, you're right
