### ISSUE TITLE
[add-resource] New Plugin: Twig Feeds

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1257]
I would like to add a plugin to the Grav Repository. Here are the project details: [Twig Feeds](https://github.com/OleVik/grav-plugin-twigfeeds).

Simply put, it exposes RSS and Atom feeds to Grav making them available for use in Twig.

**Comment by rhukster** [comment]
I can see this being handy :)

**Comment by rhukster** [comment]
will add to downloads soon

**Comment by rhukster** [comment]
Should be there.
