### ISSUE TITLE
Add Collection method to merge with another page collection, and a Collection filter for both non-modular and modular children

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav#1258]
Both of these enhancements would solve my immediate problem, but each is also useful in its own right IMHO.

My problem is (was) that I [wanted to incorporate some modular items](https://gitter.im/getgrav/grav?at=587f4058cbcb28177084b363) (which I tagged 'visible' in frontmatter) into my navigation menu (as hash fragment links, what some people call jumplinks). So, since the collection filters treat modular and non-modular children mutually exclusively, I thought I'd just merge one into the other. (Twig's merge filter produces an array result.)

Firstly, if I'd been able to grab both types in a single filter, the problem would not have arisen.

Secondly, there doesn't seem to be a nifty way to combine two Grav page collections. Thanks to @mahagr I came up with a kludgy way:

``` twig
{% set menu_pages = page.children.visible %}
{% for frag in page.children.modular if frag.header.visible %}
    {% set menu_pages = menu_pages.addPage(frag) %}
{% endfor %}
{# there may also be a more concise way to do this using page.evaluate()
   but we couldn't figure that out #}
```

but I think it should be a standard method in PHP and exposed to Twig :)

**Comment by rhukster** [comment]
So i just added a simple merge method:

```
{% set collection1 = page.collection %}
{% set collection2 = page.collection('test_content') %}

<h3>Merged</h3>
<ul>
{% for p in collection1.merge(collection2) %}
<li>{{ p.title }}</li>
{% endfor %}
</ul>
```

**Comment by hughbris** [comment]
Thanks :)

I think it's still worth considering an "all children" filter down the track, but this solves my problem in that I can undo my messy workaround. Loving this kind of responsiveness to issues as I build sites, can usually get the solution through core updates within a few days :)
