### ISSUE TITLE
grav does not support .ico favicon image files in all folders.....

### ISSUE THREAD

**Issue by 4evermaat** [getgrav/grav#1259]
the individual pages folders do not seem to support .ico favicon image file formats.  Is there any way for users to be able to edit the formats that grav can process?  

The browser might handle them, even if grav has never heard of them.

**Comment by flaviocopes** [comment]
Yes, copy `system/config/media.yaml` to `user/config/media.yaml` and add your image format.

**Comment by 4evermaat** [comment]
Is there a help file link that helps explain the different [sub] parameters of the media.yaml file?

**Comment by flaviocopes** [comment]
It's not mandatory, it's just used as a fallback image for media. Do you need multiple mime types? .ico is (unofficially) supported everywhere with `image/x-icon`
