### ISSUE TITLE
get/post form to other page with Grav Form plugin

### ISSUE THREAD

**Issue by DavideTrendstudio** [getgrav/grav#1260]
On a project I am working on, I have a small form with two fields on every page except on the contact page. When a user fills the form out and submits it, must be redirected to the contact page and the  input should be displayed in a second form as present on this page.

I know how to redirect the user to the contact page after form submission and display the input on this page. What I can't figure out, is how to set the user's input as default value on the second form.

With PHP it would look like this:

```html
<form method="post" action="contact.php">
    <input type="text" name="userinput" />
   <input type="submit" value="Submit">
</form>
```

... and in contact.php:

```php
<?php 
if(!isset($_POST['userinput'])) {
   $input = '';
} else {
   $input = $_POST['userinput'];
}
?>
<form>
    <input type="text" name="user-input"  value="<?php echo $input; ?>"/>
   <input type="submit" value="Submit">
</form>
```

How can I achieve this with Twig and the Form plugin?

Thanks!

**Comment by rhukster** [comment]
Look like what? I think you forgot to post code samples?

**Comment by flaviocopes** [comment]
Code was hidden as not enclosed in backticks. I edited it and it shows up.

You should look at how the Form plugin implements the destination page by default: https://github.com/getgrav/grav-plugin-form/blob/develop/templates/forms/default/data.html.twig

and the form generation https://github.com/getgrav/grav-plugin-form/blob/develop/templates/forms/default/form.html.twig#L35-L41

I would create a new Twig template in your theme, and make that the template of your second form, with the adjustments to get the value from the form object.

**Comment by DavideTrendstudio** [comment]
Tanks for the help!

**Comment by rhukster** [comment]
Closing to due to inactivity
