### ISSUE TITLE
Custom header collection sorting doesn't support date format

### ISSUE THREAD

**Issue by ichik** [getgrav/grav#1261]
Hi,
I'm trying to establish custom sorting of collection of pages in a timetable like this:
```
order:
    by: header.eventdate
    dir: asc
```

Unfortunately it doesn't seem to support datetime format that is stored in this custom header (i.e. `eventdate: '03-02-2017 22:18'`).

As a result event from February 3rd comes before January 20th for example. I can resort to using just date for sorting, but date of creation an item is not an event date per se.

**Comment by rhukster** [comment]
I've looked at this and really we have no way to really know what or how to order custom header type sort fields. For this reason, I suggest you change the `header.eventdata` to use ISO format dates: `yyyy-mm-dd`.  This way the sort order will be correct with regular natural sort order that is assumed for all such fields.

You can then reformat this on display via the Twig Date filter: http://twig.sensiolabs.org/doc/2.x/filters/date.html

**Comment by ichik** [comment]
The thing is, though, that the format in the field is defined by this blueprint:
```
header.eventdate:
                      type: datetime
                      label: Event date
```
And the actual data is then set through Admin plugin, is there any way to change the format Admin plugin uses?

**Comment by w00fz** [comment]
This is now fixed. The fix involves a new option for the `datetime` field that allows you to specify manually the format. So in your case you could write in the blueprint:

```yaml
header.eventdate:
  type: datetime
  label: Event date
  format: 'Y-m-d'
```

which will force the format to `2017-01-20` for that particular field.
