### ISSUE TITLE
Sanitize attribute values provided in markdown

### ISSUE THREAD

**Issue by indigoxela** [getgrav/grav#1263]
Hi,
attribute values (e.g. image alt) inserted via markdown don't seem to get sanitized.
So people can insert any javascript code with a little trick:
`![the image alt" src="" /> <script type='text/javascript'>alert('Gotcha!');</script>](image.jpg)`
Note the **"** character that lets people break out of the attribute. The alert in above example works.
Important: pages.markdown.escape_markup setting has absolutely no influence on that.

Additional info about this topic:
https://www.owasp.org/index.php/XSS_%28Cross_Site_Scripting%29_Prevention_Cheat_Sheet#RULE_.232_-_Attribute_Escape_Before_Inserting_Untrusted_Data_into_HTML_Common_Attributes

In system.yaml there's a setting to either escape _all_ html markup (including script and style tags) or nothing.
**This is a feature request:** a finer grained setting to prevent _style_ and _script_ tags but allow others (div, span...).

**Comment by rhukster** [comment]
So here's the deal.  We can't really protect a site from the admins of that site.  There is a point where you have to say if an editor or author intentionally puts in XSS code into their own site, then they have the right to do so.

Even if we escaped the markdown (this is littered with potential issues with legitimate markdown), then you could simply put HTML and JavaScript in your content.  Or you could simply put this XSS code in your twig template.  As you have complete control, you could simply disable any encoding that the Twig is doing.

There are plenty of reasons why being able to add javascript to content is an important feature and capability that many people take advantage for legitimate uses.  

If you specifically don't trust your administrators or authors, then you can simply escape the content output in your theme's twig templates:

```
{{ page.content|e }}
```

Or use the `|striptags` filter to remove HTML tags including `<script>`. 

Really you have control to make Grav as flexible or as secure as you wish.

**Comment by indigoxela** [comment]
Hi  rhukster,
many thanks for your detailed explanation.

It's not the legitimate admin/editor I worry about. But whenever there's an account, it could get hacked.
So my concerns are about limiting the potential harm such an account could do.

> Really you have control to make Grav as flexible or as secure as you wish.

I'll have a closer look at the possibilities.
Still I think, Grav is the coolest flat file CMS I ever found.
