### ISSUE TITLE
page.collection() returns true even if there is no page collection defined in .md

### ISSUE THREAD

**Issue by lid3rs** [getgrav/grav#1265]
In my .md file page.collection('similarProjects') is not defined, but while using {% if page.collection('similarProjects') %} returns TRUE. This appeared after the (v1.1.14) update.

**Comment by flaviocopes** [comment]
In 1.1.14 we fixed a bug where an empty collection was returned as an empty array. It will now return an empty collection, so check for `page.collection('similarProjects')|length` instead

**Comment by flaviocopes** [comment]
(linked change: https://github.com/getgrav/grav/commit/e2ee02a71d4fb0b0100008a5ff49dbe01ccdbfd5) - cause of the problem: an empty array is evaluated by Twig as false, while an empty Collection object is not.

**Comment by rhukster** [comment]
actually i would use this:

```
{% if page.collection('similarProjects') is not empty %}
...
{% endif %}
```
