### ISSUE TITLE
URGENT!!! No update or install possible

### ISSUE THREAD

**Issue by prinla** [getgrav/grav#1267]
Hello,
I use grav for a longer time now without problems...
But since today on any of my website (using admin on the server or gpm locally) I can't install anything anymore!!!

F.ex. the update to GRAV 1.1.14 is announced in the topbar... I click on the update button...
The message prompts that it is installed... but after a refresh it tells me that the same update is avaible...
And nothing has been installed!!!

Same with the plugins... I want to add a new one... I push the install button... it tells me the plugin has been installed... but indeed the plugin details are shown still with the button "install plugin" 
And nothing has been installed!!!

I tried the GPM locally to update the Grav core ... but it tells me "Runtime Expeption. Error while trying to download 'https://getgrav.org/downloads/grav.json?v=1.1.12&stable=1".

Trying to install a plugin over GPM gives me also an error!!!

The same problems occur to all of my webpages!!!

PLEASE HELP ME URGENTLY!!!
Thanks
Oliver

**Comment by rhukster** [comment]
Can you try this suggestion I made on a similar issue: https://github.com/getgrav/grav-plugin-admin/issues/939#issuecomment-273940443

Basically I'm trying to find out which change caused this.  I can't replicate it, and it seems to be only affecting a few people. Please try replacing the `Folder.php` from the 1.1.12 version, and see if that helps.  If not then it must be something else.

Thanks!

**Comment by prinla** [comment]
No this can't be the same problem then in the 939 issue...
It happens on every website I have...whether it's running 1.1.12 or 1.1.14 or even on an older site 1.1.8
It is not a problem with the version... neither with the server I use (as I use different ones)
In the 939 issue it says GPM still works... but it doesn't in my cases!!!
It happens with the update of the core, the install of ANY plugin and the update of any plugin !!!
Only disinstall a plugin still works...
It seems to me it has nothing to do with the website as it happens on all of my websites (on different servers as I said) with different core versions, plugin versions and themes...
AND IT'S ONLY SINCE TODAY ...
... since the new core announcement appears on all the websites!!!

But I have 3 websites where I manually installed over ftp the new core 1.1.14 and on these websites it happens also.

Seems to be a major update/install bug

**Comment by rhukster** [comment]
Do you have a local installation setup? Can you try it there also.  I've just tried a free install on my local installation, and was able to install/update fine.  Both from CLI and admin plugin.  So I don't think it's a widespread issue with GPM, it's something related to certain configurations. 

Can you try disabling the `verify_peer` option in the system.yaml and then try GPM updates/installs again:

![2017-01-21 at 9 30 am](https://cloud.githubusercontent.com/assets/1084697/22175915/477bf61c-dfbc-11e6-9177-ad2a7d6b9848.png)

Also, it might be worth toggling the different `Remote Fetch` options.

**Comment by rhukster** [comment]
Also I want to point out that nothing has changed in the last few days, but about a week ago we did make a change to GPM asset URLs.  It doesn't seem like this would be the issue though because there would be an error that you couldn't even download the file if that was causing the issue (and we've seen no issues stating that).

The GPM system does cache the index of changes for 24 hours, so it's possible you've not checked for updates lately and the cache has only now just expired for your sites, showing the updates today, but that's normal behavior.

**Comment by prinla** [comment]
Yes I have a local installation and there it works fine as you said...
The same website on the server doesn't work!!!

I tried to switch of the verify-peer on different site -> NO CHANGE ... still not working

**Comment by rhukster** [comment]
what about curl/fopen???

**Comment by prinla** [comment]
Very strange after installing the new Core on the local installation, i cannot access anymore neither the admin/plugins nor the admin/themes !!!

**Comment by prinla** [comment]
Works!!!
After changing the remote fetch to fopen it worked on one website...
Checking the others...

**Comment by prinla** [comment]
Concerning the problem on local installation... 
I changed the remote fetch to fopen also ... and now it works again.

**Comment by rhukster** [comment]
Hmnm.. curl works fine for me if when I set it manually.  Can you tell me the versions of Curl that you have where curl is not working?

```
> curl --version
curl 7.51.0 (x86_64-apple-darwin16.0) libcurl/7.51.0 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```

Perhaps the version is the issue.. or it could be some setting that's now required due to our minor change last week.

**Comment by prinla** [comment]
As I said I have different version installed, I check them 1 by 1 (more to come)
One website where it doesn't work has curl 7.38.0

**Comment by prinla** [comment]
Another has 7.26.0

**Comment by prinla** [comment]
But I see that most of the websites (can't check them all so quickly) have curl version 7.38.0

**Comment by rhukster** [comment]
ok, we might have to write a little script that can output curl configuration and also all the details of the curl request that must be failing.  Probably will happen next week, but for now, just use fopen.

Thanks for helping debug this, definitely feel like we are closer to working out what's going on.

**Comment by prinla** [comment]
Thanks for YOUR help !!!
And by the way THANK YOU so much for the BEST CMS ever written !!!
I love GRAV and I love your support team...
It's a pleasure to work with you !!!

**Comment by rhukster** [comment]
BTW, if you got to the **Info** tab in configuration, and look a the **curl** section.  Other than version/age etc, is there anything else that is different from yours (broken curl site) compared to mine:

![2017-01-21 at 10 14 am](https://cloud.githubusercontent.com/assets/1084697/22176223/9ea640b8-dfc2-11e6-86f5-2ac2e0b98559.png)
![2017-01-21 at 10 14 am](https://cloud.githubusercontent.com/assets/1084697/22176226/a1f451b0-dfc2-11e6-8e1e-14c0c6799994.png)

**Comment by prinla** [comment]
The IDN is set to YES
The TLS-SRP set to YES
I don't have at all "HTTP2", "GSSAPI", "KERBEROSS", "UNIX-SOCKETS", "PSL"
In the protocols I have one more in the list -> "rtmp" (the rest is the same)
My Host is "x86_64-pc-linux-gnu"
My SSL Version is "OpenSSL/1.0.1t"
and I have under the ZLib also a point called "libSSH Version" set to "libssh2/1.4.3" 

The rest is the same

**Comment by rhukster** [comment]
ok thanks.

**Comment by rhukster** [comment]
hey @prinla I've tried on a couple of linux servers and can't replicate the curl issue their either.  What hosting company/companies do you use that have this issue? If you can replicate local, what setup are you using there? Basically how can we replicate this ourselves?  Also would it be possible to get access to one of your installations where this is happening so we can try to debug it a bit more?

Cheers!

**Comment by rhukster** [comment]
@prinla got something for you to try.  Please try switching the GPM method back to **auto** or **curl** and then in: `src/Grav/Common/GPM/Response.php` line 364 change the default redirects from 3 to 5:

```
$max_redirects = isset($options['curl'][CURLOPT_MAXREDIRS]) ? $options['curl'][CURLOPT_MAXREDIRS] : 5;
```

See if that works.

Thanks!

**Comment by rhukster** [comment]
Actually sorted it, it was not that. Seems when `open_basedir` is enabled combined with Curl and the fact we were throwing a `303` redirect to reach github, it then failed. 

Good news is it's just a server fix.  Although we've put a fix in Grav also so any other 303 redirects will be handled properly.  Pretty sure things will just work for you now if you set **GPM Method* back to **auto**

**Comment by ayozehd** [comment]
> what about curl/fopen???

Definately that saved my day. I was on 1.5.1 Grav version and had same problem upgrading to 1.6.x. Curl was installed on 7.65.1. Have no idea why suddenly responses were failing even after your server fix. Just posted for more info...
