### ISSUE TITLE
Creating a new theme does not work

### ISSUE THREAD

**Issue by mosesontheweb** [getgrav/grav#1268]
Hi,

just wanted to start to develop my own theme for my website. Therefore I created a new environment for development with a newly installed Grav and devtools as plugin. Running the plugin from CLI ends with this message:
```
X-Powered-By: PHP/5.5.30
Content-type: text/html

FATAL: Must be run from ROOT directory of Grav!
```
In fact I'm exeuting the script from within the Grav-root with the command `bin/plugin devtools new-theme`. Can't determine if it is coming from Grav or the devtools plugin.

Any hints?

Regards, Thomas

**Comment by rhukster** [comment]
I think he php bin in your path is the CGI version and not the CLI version. CGI is meant for the webserver only.  Type `php -v` to test

You might need to put the CLI php version in your path if it exists or install it manually if it do set.

**Comment by mosesontheweb** [comment]
Hi,

you were right. In case of Domainfactory you have to modify the header of bin/plugin to the following line:
`!/usr/bin/env php5-55LATEST-CLI`
This is a link to the currently latest PHP 5.5 CLI version (as of 24.01.2017 it's version 5.5.38)

Thanks for that hint. Problem solved!

Regards, Thomas

**Comment by rhukster** [comment]
You could also create an alias for that `php5-55LATEST-CLI` binary so something like: `phpcli`
 then you can just run `phpcli bin/plugin...`
