### ISSUE TITLE
Error with `bin/gpm selfupgrade`

### ISSUE THREAD

**Issue by sthag** [getgrav/grav#127]
Hi

I installed grav 0.9.14 yesterday. But today is grav 0.9.15 day :)
This is on a virtual ubuntu 14.04.1 machine.
So I tried `bin/gpm selfupgrade` within my grav directory.

I got:

```
[Whoops\Exception\ErrorException]
Use of undefined constant CURLOPT_REFERER - assumed 'CURLOPT_REFERER'
```

I expected the update to happen.

**Comment by namaless** [comment]
You need to enable php5-curl in you server.

**Comment by sthag** [comment]
Ok. I did. Now it is working.
But I could not find anything in the help about this.
Should I just know this if working with such things or is there some documentation missing?
I guess it would be good to have it as requirements.

Thanks for the help.

**Comment by rhukster** [comment]
Yes, I have some PHP settings on the list of things to add to system requirements in the documentation, and also into the *problems* plugin that should let you know if your system has a missing requirement. Thanks.
