### ISSUE TITLE
New plugin: Backup Manager

### ISSUE THREAD

**Issue by leotiger** [getgrav/grav#1270]
Hi @gravteam, hi @rhukster.

As announced: My plugin is ready and with the first fixes done I would like to see the plugin in the Grav plugin repository.

Link to the plugin: https://github.com/leotiger/grav-plugin-backup-manager

Thanks.
u

**Comment by w00fz** [comment]
Hi!
this is good stuff and we can certainly add it to GPM. There are a few things that are missing in order for us to add it though.

Have a look at the steps in https://learn.getgrav.org/cli-console/grav-cli-gpm#add-your-resource-to-the-repository and https://learn.getgrav.org/advanced/grav-development#themeplugin-release-process - I think you are just missing a release but I would double check all of them to make sure.

**Comment by leotiger** [comment]
Hi @w00fz 

I added a release to my GitHub repository.

u

**Comment by leotiger** [comment]
Hi @w00fz, @rhukster.

Version 0.1.3 is out. It fixes some issues and includes some minor improvements.

u

**Comment by rhukster** [comment]
Added to repo 👍
