### ISSUE TITLE
Email plugin thankyou/ redirect not working with form on home page

### ISSUE THREAD

**Issue by zacharyhudy** [getgrav/grav#1271]
Having a contact form on the home page when trying to route to the respective thankyou page, a 400 error is thrown because it is trying to find /thankyou which is wrong since the thankyou page is nested under the home folder. The correct routing would be /home/thankyou but since it is on the root folder, it is unable to find the page. 

![screen shot 2017-01-25 at 4 59 18 pm](https://cloud.githubusercontent.com/assets/6532700/22316204/7b9474ee-e320-11e6-818e-633e77cf23c6.png)

It took me sometime to find a work around. I created a non-visible thankyou page at the root level. Is this the intended method or ? 

Thanks!

**Comment by rhukster** [comment]
Please open this under the forms plugin repo: https://github.com/getgrav/grav-plugin-form/issues

**Comment by flaviocopes** [comment]
P.S. It should work fine. Is the form in a modular page?
