### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by tnware** [getgrav/grav#1277]
I would like to add my new theme to the Grav Repository
Here are the project details: 

**tnware/grav-theme-mdux**

https://github.com/tnware/grav-theme-mdux

https://github.com/tnware/grav-theme-mdux/releases/tag/0.9.8

I created a theme coined "material design user interface". I started this theme in Summer of 2016 and, after a period of hiatus, I have worked to bring it up to functionality on the current version of Grav. 

I would like for this to be available in the theme repository, especially considering there seem to be no themes reflecting Google/Android Material Design.

I plan to continue contributions to bring code structure up to date.

Thank you,
Tyler Woods

**Comment by rhukster** [comment]
Added to GPM.  Thanks.
