### ISSUE TITLE
JSON object of ALL blog items

### ISSUE THREAD

**Issue by julienchazal** [getgrav/grav#1279]
Hello

I know it's possible to output a blog item in JSON format, but is it possible to output a blog list in JSON in order to have a JSON object with every blog items informations inside ?

Thx !

**Comment by flaviocopes** [comment]
You can add a `blog.json.twig` in your theme, and have it print the blog posts in JSON format, start from

```
{% set collection = page.collection() %}
{% for child in collection %}
    {{child.content|json_encode}}
{% endfor %}
```
for example.

**Comment by julienchazal** [comment]
thx a lot @flaviocopes 
btw i needed to add `template_format: json` in `blog.md` to get it work
i don't think it's in the docs ?

**Comment by flaviocopes** [comment]
You can also access `/blog.json` (forgot to mention)
