### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by tnware** [getgrav/grav#1282]
I would like to add my new theme to the Grav Repository.
Here are the project details: 
**tnware/grav-theme-material-lite**

https://github.com/tnware/grav-theme-material-lite/releases/tag/0.1.1

This is a simple, lightweight Material Design standard site. 
It supports default page and error page.

It scales for mobile and has corresponding side-nav.

Thank you

**Comment by rhukster** [comment]
Added to GPM, should show up soon
