### ISSUE TITLE
[add-resource] New Plugin: Directory Listing

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1283]
I would like to add a plugin to the Grav Repository. Here are the project details: [Directory Listing](https://github.com/olevik/grav-plugin-directorylisting).

It exposes a Twig-variable, `{{ directorylisting }}`, which returns a hierarchy of files below the page, stylized as a collapsible tree-structure.

**Comment by rhukster** [comment]
Added to GPM should show up soon.
