### ISSUE TITLE
Theme/Plugin changelog

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1284]
Am I mistaken, or do the plugin/theme changelogs only accept American (`01/30/2017`) and not European (`30-01-2017`) date formats? [Shouldn't it accept both](https://learn.getgrav.org/content/headers#date), or better yet also [DateTime default](http://php.net/manual/en/datetime.format.php)'s Y-m-d?

Just noticed that even after switching to the European for a few of my plugins (from my previous, incorrect format), they don't show up with a changelog in the [Plugins-directory](https://getgrav.org/downloads/plugins).

**Comment by flaviocopes** [comment]
No, they work fine too, see 

https://github.com/flaviocopes/grav-plugin-shoppingcart/blob/develop/CHANGELOG.md

and 

https://getgrav.org/downloads/plugins#changelog:shoppingcart

**Comment by OleVik** [comment]
I must be doing something wrong, because [this](https://github.com/OleVik/grav-plugin-directorylisting/blob/master/CHANGELOG.md) leads to [nothing](https://getgrav.org/downloads/plugins#changelog:directorylisting).

![image](https://cloud.githubusercontent.com/assets/974717/22461366/408bb46a-e7a9-11e6-8c0f-22f293e0708c.png)

**Comment by flaviocopes** [comment]
The only difference I see is the spaces

```
# v1.0.2
## 31-01-2017
1. [](#improved)
    * Expanded README
```

try


```
# v1.0.2
## 31-01-2017

1. [](#improved)
    * Expanded README
```

**Comment by flaviocopes** [comment]
Let me know if this leads somewhere. Also just noticed those 4 copy-to-clipboard icons

**Comment by OleVik** [comment]
You were right, it was the spacing between the headers and the lists. It [works now](https://getgrav.org/downloads/plugins#changelog:directorylisting). Also just one copy-to-clipboard icons now.
