### ISSUE TITLE
[add-resource] New Skeleton - OER Content Space

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#1286]
I would like to add this new skeleton package to the Grav Repository. OER Content Space is designed to share and collaboratively update Markdown-based Open Educational Resources content using seamless GitHub/GitLab syncing. Includes the visual layout manager Gantry 5.

Here are the project details: https://github.com/hibbitts-design/grav-skeleton-oer-content-space

**Comment by rhukster** [comment]
Added to GPM. Thanks.

**Comment by paulhibbitts** [comment]
Thanks very much Andy!
