### ISSUE TITLE
how to have plugin repo updated in GPM

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav#1288]
I have updated plugin [markdown-rubytext](https://github.com/tidiview/grav-plugin-markdown-rubytext) repository yesterday.
I though that today, with sufficient delay like 12 hours, it would automatically get updated to the GRAV GPM, but it seems that it does not.
I have looked at the docs, to look at  information about that but could not find.
How should I proceed?
Thanks in advance

**Comment by flaviocopes** [comment]
Replied on the chat, needed a release
