### ISSUE TITLE
Debbuger doesn't work if the js is being loaded with async or defer

### ISSUE THREAD

**Issue by robertbak** [getgrav/grav#1289]
This is is how my first javascript block looked when I noticed this:
```twig
{% block javascripts %}
     [...]
{% endblock %}
{{ assets.js('head',{"async":"","defer":""}) }}
```

which results in a .js error (`Uncaught ReferenceError: PhpDebugBar is not defined`) on line 
```html
<script type="text/javascript">
var phpdebugbar = new PhpDebugBar.DebugBar();
```
because it's being run before the PhpDebugBar has been loaded.

**Comment by rhukster** [comment]
Yup, not much you can do about that, you can't defer the debugger JS because it needs to be loaded before the panel renders.

**Comment by robertbak** [comment]
Oh, ok, idea: couldn't you always load the PhpDebugBar.js files just above "var phpdebugbar = new PhpDebugBar.DebugBar();" without bundling them with the user js files?

**Comment by rhukster** [comment]
Let me have a look at it...

**Comment by rhukster** [comment]
Please try that Pull Request linked above.  Should sort this issue.  Thanks.

**Comment by robertbak** [comment]
This will be more complicated, since that in turn requires dependencies to be loaded (but I'm not sure if this wouldn't be an issue anyway, on a theme without jQuery?). The only downside of this not working is that it's not obvious why it isn't working.  

```
Uncaught ReferenceError: jQuery is not defined
    at VM184 debugbar.js:4
(anonymous) @ VM184 debugbar.js:4
widgets.js:83 Uncaught TypeError: Cannot read property 'makecsscls' of undefined
    at widgets.js:83
    at widgets.js:463
(anonymous) @ widgets.js:83
(anonymous) @ widgets.js:463
openhandler.js:13 Uncaught TypeError: Cannot read property 'extend' of undefined
    at openhandler.js:13
    at openhandler.js:202
(anonymous) @ openhandler.js:13
(anonymous) @ openhandler.js:202
(index):133 Uncaught TypeError: PhpDebugBar.DebugBar is not a constructor
    at (index):133
(anonymous) @ (index):133
```

**Comment by robertbak** [comment]
Hey, 
so I've looked at this a bit more, and while there's technical things to do, I think the bigger question is _Where should the debugger work?_

I've hit another case where it won't work (when there's no assets.js at all on the page), so I think the current state is that the debugger will show up on:
_Generated Html pages that have at least one assets.js() call and where the first one is loaded synchronously. _

So before going into more technical questions (like whether PhpDebugBar should have a version where the js code is wrapped in an window _load_ event listener, which it probably should) probably it would be needed to figure out what sort of pages the debugger should work on, any html (and what about ajax calls), just pages with js already in them, etc?

**Comment by flaviocopes** [comment]
Since this is not a much common problem (if you're in production and need to use async&defer to speed up page loading, you're not using the debugger), and as you noted debugger has its jQuery dependency, which would need to be loaded sync as well, which is probably the biggest JS file you load, removing much of the convenience of async&defer, why not simply solve this problem on the theme twig side:

```twig
{% if system.debugger.enabled %}
    {{ assets.js() }}
{% else %}
    {{ assets.js('head',{"async":"","defer":""}) }}
{% endif %}
```

**Comment by rhukster** [comment]
I agree, this is the first time it's come up and I don't really want to change something that has been running great for 99.9% of people when it can be done via the theme.

**Comment by heihachi88** [comment]
@flaviocopes, how can i browse contents of `system` object? I don't see its documented anywhere.
