### ISSUE TITLE
Pipeline/minification-mechanism handling encoded SVG Data-URIs

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1295]
From a discussion on Slack (on the 6th of February, around 9pm CET), data-URI in CSS set with the value of an encoded SVG breaks the pipeline/minification. The comparative replication occurred from [this line](https://github.com/nolimits4web/Swiper/blob/master/dist/css/swiper.css#L557) in the Swiper-library. The background-image url is not incorrect, but rather heavily optimized (see [this guide](https://codepen.io/tigt/post/optimizing-svgs-in-data-uris)).

Why and how this breaks pipelining or minification is uncertain, but it's worth looking into as encoded SVG's as data-URIs are only going to be used more with the adoption of SVG icons and handy Sass/Less/Stylus-functions.

Possibly a related recent issue with matthiasmullie/minify: [162](https://github.com/matthiasmullie/minify/issues/162).

**Comment by rhukster** [comment]
Definitely looks like the issue is upstream in `matthiasmullie/minify`.  We'll keep an eye on this.

**Comment by rhukster** [comment]
Good news, this is fixed in https://github.com/matthiasmullie/minify/commit/41dc7827da21b2d39870c358e6b3ee3934a0965a

This is not released yet though so next release should have it.

**Comment by sphkress** [comment]
I just found out, SVG is working when using it inside an IMG, but when using it as OBJECT, it's still trying to download the file instead of displaying it. Is this really intended? I don't know whether this might be related to #366

**Comment by flaviocopes** [comment]
I don't see this related to the issue. Please open a new issue with a little example to try replicating the problem.

**Comment by sphkress** [comment]
Oh got it... this is one of the trickiest parts of Grav, to be honest: URL rewriting. I was using {{page.url}}/image.svg which is working perfectly for IMG tags, but inside the OBJECT data, the 'real' path is required. So data="{{page.relativePagePath}}/image.svg" is finally working.

**Comment by OleVik** [comment]
This was fixed upstream in [1.3.44](https://github.com/matthiasmullie/minify/releases/tag/1.3.44) as far as I can tell.
