### ISSUE TITLE
GSoC call for ideas

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav#1297]
The Wiki page https://github.com/getgrav/grav/wiki/GSoC-2016---Ideas-List contains a list of [Google Summer of Code](https://summerofcode.withgoogle.com) (application underway) ideas.

![vertical gsoc logo](https://cloud.githubusercontent.com/assets/11783388/22692865/28fed88e-ed41-11e6-90c1-563726c025a8.jpg)

Comment here to discuss and add more to the list!

**Comment by flaviocopes** [comment]
Some ideas 

- Add a user profile page in the Login plugin with events to be expanded by plugins, or create a separate plugin since that could grow huge (think CB / JomSocial)
- Create a database plugin that would provide a layer to store any kind of data in a database (SQL [mysql, postgres,sqlite] and eventually noSQL as well?)
- Official Docker image
- AMP plugin
- Social posting tool (automatically post to Tw/Fb/G+ or just post to Buffer and manage things from there

**Comment by OptikWebCreative** [comment]
visual / drag and drop form creator (think Breezing Forms / RSForms)

**Comment by OleVik** [comment]
Could we add to this GraphQL? It was discussed quite a bit [on Slack yesterday](https://getgrav.slack.com/messages/general/convo/C3Z7KN6MC-1486418012.002649/), and have great potential both for [implementation](webonyx.github.io/graphql-php/) and as more efficient and flexible than a REST API-layer (a [decent comparison](https://philsturgeon.uk/api/2017/01/24/graphql-vs-rest-overview/)). Also, a well-executed GraphQL-layer would in itself be an efficient interface between any database as it's first and foremost a query-language (hence the QL) - you could store data the same way the API retrieves it without conflict.

Furthermore, a Gregwar-replacement is needed, but could perhaps better be achieved by the core team as it integrates very tightly into v1.1->v2 and beyond. Thus, as I understand it, a GSOC-project might achieve a good result but not necessarily anyone to maintain it further. So the GSOC-student would not only need to be involved in the specific replacement, but Grav more broadly. I'm not sure if that is a limitation in any way, but it's worth specifying as project goal and the larger involvement expected.

Lastly, importers are indeed useful, but from previous GSOC-projects on other CMS' they clearly need to be maintained long-term, not developed as once-offs - the pace of development between CMS' almost always lead to broken importers.

**Comment by OptikWebCreative** [comment]
the ability to set a particle to be visible on certain pages only - same as assignments for outlines

**Comment by rhukster** [comment]
@OptikWebCreative that sounds like a Gantry feature request, not a Grav one :)

**Comment by OptikWebCreative** [comment]
I would agree @rhukster but with J! (and WP I think) you can create a module / widget and set it to being a G5 particle, there is no way to do that in GRAV (yet) so maybe GRAV needs to get the functionality to enable G5 to take advantage of it as for every time I want to change a particle, but not the whole layout at the moment it means a new outline

**Comment by OptikWebCreative** [comment]
so if i create a G5 particle module in J! and set it to appear on HomePage, About, Contact only, G5 handles it? i would have thought J! would have handled the assignments

**Comment by w00fz** [comment]
Maybe these questions should be taken over to the https://github.com/gantry/gantry5 issues?

**Comment by rhukster** [comment]
I added a few of yours @flaviocopes.

Regarding the profile page, I actually have a local example of a profile page that could be easily added to the default login plugin.

**Comment by Sommerregen** [comment]
I have some ideas, too.

* Dropbox plugin
* TwoFactor authentication for Admin/Login plugin (maybe LDAP, too?)
* Versioning of files, i.e, using `GitSync` plugin

**Comment by Sogl** [comment]
> maybe LDAP, too?

+1 to LDAP

One idea from me to Admin Panel. I really missed user administration page where you can create new users from here, manage their permissions etc
Or maybe it's in the plans for Admin Panel Pro?

**Comment by w00fz** [comment]
yes, user management and files versioning (pages) are admin pro features.

**Comment by Sogl** [comment]
@w00fz 
>yes, user management and files versioning (pages) are admin pro features.

And ACL system too? I want to hide some pages like Configuration/Plugins/Themes etc from normal users.

**Comment by tidiview** [comment]
@flaviocopes
> Social posting tool (automatically post to Tw/Fb/G+ or just post to Buffer and manage things from there

+1
suggestion:
Consider integration of multilanguage from start with possibility of seperate account per languages

**Comment by flaviocopes** [comment]
@Sogl you can already do that https://learn.getgrav.org/admin-panel/faq#managing-acl (OT)

**Comment by david-bettondesign** [comment]
**WYSIWYG Editor**
I realise that this isn't a particularly glamorous suggestion but I feel it is important. Markdown is great and most of the people reading this wouldn't dream of using a WYSIWYG editor but from experience asking a non-web savvy user to learn something new (such as markdown) is an upward struggle to say the least. The **only** thing stopping me using Grav to develop client websites is the lack of a WYSIWYG editor.

**Comment by rhukster** [comment]
There is an LDAP plugin already: https://github.com/markleary/grav-plugin-loginldap - it's in GPM too.

**Comment by Sommerregen** [comment]
@rhukster Oh, I forgot to look at the plugin repo first. But I have another one, this time more fundamendal:

* a translation manager plugin (maybe client and server) to edit/add/modify local translations easily (depending on plugin, theme, grav core etc.) with upload and download capability 😉

**Comment by rhukster** [comment]
translation manager is a good one, i'll add that to the list

**Comment by leotiger** [comment]
StackEdit for GRAV! I have a working implementation of StackEdit in my GRAV implementations but a full-fledged StackEdit solution that allows offline-editing, local copies, etc. would be great for GRAV. StackEdit already includes Dropbox and other providers, why not GRAV intances?

**Comment by rymdluo** [comment]
@leotiger +1 for StackEdit. I currently have my /pages synced to NextCloud so that I can literally drop posts to upload and use their markdown editor via browser if I need to. A StackEdit solution would be dreamy.

My suggestion referencing #1099. @rhukster made a good point about Grav caching frontmatter for all pages. Provide a whitelist/blacklist to ignore/only look at choice pages, similar to advanced-pagecache plugin.

I would then provide the same whitelist/black to both Grav and plugin to work in sync with each other.

**Comment by paulhibbitts** [comment]
Hi @rymdluo I'd love to learn how you are syncing your Grav pages to NextCloud. Thanks!

**Comment by rymdluo** [comment]
Hey @paulhibbitts in this case it was a silly simple hack. You will need NextCloud and Grav on the same server though. Upload your entire /pages folder into NextCloud, delete /pages folder from your Grav system and create a symbolic link directing to the uploaded /pages folder that's in NextCloud.

The directory in NextCloud should be something like /nextcloud/data/'username'/'folders'/pages.

**Comment by paulhibbitts** [comment]
Thanks @rymdluo for sharing that technique - nice!

**Comment by artofthesmart** [comment]
AMP integration looks more like a template than a built-in feature.  You might be able to get 90% of the way there by building up a boilerplate Template slug that people can use to build their new theme on top of.

i.e. [Devtools](https://learn.getgrav.org/themes/theme-tutorial#step-2-create-base-theme) would have an option to generate an AMP slug in addition to the existing option?

**Comment by flaviocopes** [comment]
I'm closing the issue as the Grav application to GSoC was not accepted.
