### ISSUE TITLE
Autoprefixer?

### ISSUE THREAD

**Issue by vladzhigulsky** [getgrav/grav#1298]
Any chance you could add autoprefixer?
It would be useful to clean up some obsolete vendor prefixes. Also there won't be a need to use Sass mixins for that anymore.

**Comment by flaviocopes** [comment]
You mean this autoprefixer? https://github.com/postcss/autoprefixer

If this is the case, I think this is something you should add to your theme creation gulp/webpack/* workflow, to generate the final CSS. Not something that Grav should provide.

**Comment by vladzhigulsky** [comment]
Yes, I completely agree. Realised that later. Thanks and apologies.
