### ISSUE TITLE
Responsive column layouts

### ISSUE THREAD

**Issue by pobo3** [getgrav/grav#1300]
Is there a way to use the responsive column layouts (like bootstrap) for markdown or what solution you recommend to use for got it in Grav+Markdown?

Thanks

**Comment by Perlkonig** [comment]
Normally you put structural stuff in the templates, not the Markdown files themselves. That said, you can put raw HTML in your page files if you want. You can also use plugins like [Classifier](https://github.com/Perlkonig/grav-plugin-classifier) or one of the two Bootstrap plugins [in the repository](https://getgrav.org/downloads/plugins).

**Comment by pobo3** [comment]
Thanks
