### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by zh-wowtv** [getgrav/grav#1302]
Got the "Fetch Failed" error when I goto admin. And it hangs when I click "Check update".

<img width="277" alt="screen shot 2017-02-12 at 2 19 19 pm" src="https://cloud.githubusercontent.com/assets/18462946/22860150/8182f458-f12f-11e6-95c4-89fc002434f8.png">

My current version is 1.13. Any idea? Thanks

**Comment by w00fz** [comment]
Inspect the network activity of your browser when you get this error, that way you can see the response in its entirety. It will tell exactly what caused the fetch to fail.

**Comment by rhukster** [comment]
Closing to due to inactivity
