### ISSUE TITLE
Grav adds quotes

### ISSUE THREAD

**Issue by risoul** [getgrav/grav#1303]
My text in header of a modular is : 
title: 'L''été' (french). I have to add a quote if I want to show L'été
But each time I save, Grav add another quote.
After multiple save I have
title: 'L''''été' (french) and it show L'''été

**Comment by flaviocopes** [comment]
Mmm, I cannot replicate. 
Not by creating the page via Admin directly, or creating via file system and then editing via Admin.

Which browser are you using? Also, happens with the latest Admin release? (released yesterday)?

**Comment by rhukster** [comment]
Closing to due to inactivity
