### ISSUE TITLE
uploading locally created posts

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav#1305]
Strange things have happened, and I know I am pretty much bound to break some functionality all the time ...

1. create an article locally in Markdown.
2. Save article inside a folder named blabla-blabla-blabla
3. add photos to folder and to the article (preview is awesome locally)
4. upload folder with filezilla / cyberduck to live site in its proper folder (either blog or a different collection page)
5. view article - awesome, it shows on live site, it is indexed and appears in the archives
6. using Admin, open the article for various misspelled word checks.
7. save article inside Admin -error - as per picture attached

Is this due to my fiddling with the twig template and changing the code lines a bit to resize a photo ?
Is this due to something else ?
Not sure if this is an issue per say but something is cooking here
![captura de ecran din 2017 02 13 la 23 16 33](https://cloud.githubusercontent.com/assets/7076631/22907747/94f1fd54-f242-11e6-863a-5d6819061f80.png)
![captura de ecran din 2017 02 13 la 23 14 28](https://cloud.githubusercontent.com/assets/7076631/22907749/99cebdbc-f242-11e6-8d43-cbbcd7e3190e.png)

**Comment by flaviocopes** [comment]
The error comes from the https://github.com/fredrikekelund/grav-plugin-resize-images plugin - disabling that plugin removes the error?

**Comment by rhukster** [comment]
Also would be good to test with your page in question.  Could you provide a zip of page's folder that includes the `.md` and the associated `images` files?

**Comment by JohnMica** [comment]
guys it is the plugin resize-images  = I have disabled it and the error is gone, I could upload the page and the image for you guys to see more, but without the plugin I can now edit and in Admin posts previously updated.

**Comment by rhukster** [comment]
So case closed?

**Comment by flaviocopes** [comment]
@JohnMica please let the plugin author know about the problem.
