### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by michael-collins** [getgrav/grav#1306]
I would like to add my new plugin/theme to the Grav Repository._Here are the project details: **open-curriculum/grav-plugin-oerschema**

**Comment by rhukster** [comment]
Hi Michael,

per the requirements you are going to need a `screenshot.jpg` and `thumbnail.jpg` of the appropriate dimensions: https://learn.getgrav.org/advanced/grav-development#theme-requirements

Cheers!

**Comment by michael-collins** [comment]
Hi @rhukster this is for a plugin. Do I still need these images?

**Comment by rhukster** [comment]
My apologies, nope, you don't need those for a plugin.  Not sure how I got 'theme' out of that description. I'll add it to GPM shortly.

**Comment by michael-collins** [comment]
Great, thanks!

**Comment by rhukster** [comment]
Showing up.. Thanks.
