### ISSUE TITLE
Redirect results in double extensions

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav#1307]
I ran into an issue recently when trying to configure redirects for URL's that included file extensions. The file extensions was appended an additional time to the URL. This is an issue that seems to have been introduced in afc18236c2d43907b96577272dff517ddc037640. There's no link to an issue or anything in the changelog, so I'm not sure what scenarios that change covers, but there looks to have been a small regression.

To reproduce the problem, configure a redirect like this for instance:

```yml
^/files(/.*)$: http://example.com$1
```

Then visit the URL http://grav.dev/files/example.zip (switching out the hostname as appropriate of course). You'll be automatically redirected to http://example.com/example.zip.zip.

**Comment by rhukster** [comment]
I'll take a look at this.

**Comment by rhukster** [comment]
Sorted.

**Comment by fredrikekelund** [comment]
Thanks!
