### ISSUE TITLE
Translations Bug

### ISSUE THREAD

**Issue by simonhaenisch** [getgrav/grav#1309]
I have the following language configuration in `system.yaml`:

```yaml
languages:
  translations: false
````

Then the error page looks like this (translation doesn't work):

ERROR 404
PLUGIN_ERROR.ERROR_MESSAGE

I had this setup on a site because I enabled translations and later disabled them again, as it was work in progress. Also tried it on a fresh Grav installation, it's the same.

By either enabling translations or removing the language block from the config it works again. The block can't be removed via admin panel though...

**Comment by flaviocopes** [comment]
This is not a bug, but how things are expected to work :)

The error plugin uses the string `PLUGIN_ERROR.ERROR_MESSAGE` to allow multilanguage. 

Even if you don't want to use multilanguage, you need to keep translations enabled, or even the english  language won't be "translated".

You could have those disabled if you provide your own Twig that overrides the Error plugin with your own strings that do not need translation. And do the same for any other plugin/theme that might use translation strings.

**Comment by simonhaenisch** [comment]
Ah ok, thanks for the clarification. So `translations: true` is the default setting (if setting is not present)?

**Comment by flaviocopes** [comment]
Yes, it's the default configuration (https://github.com/getgrav/grav/blob/develop/system/config/system.yaml#L13)
