### ISSUE TITLE
Adding a blueprint to the top with `ordering@: 0` not working

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav#1310]
Looks like `ordering@: 0`  (https://learn.getgrav.org/forms/blueprints/advanced-features#changing-field-ordering) is not working. `1` and above work, but 0 is not, a new field is always at the bottom (edited)

`ordering@: -10000` works

@mahagr hint:

> yeah, there's likely (!$field['ordering@'])
> should likely be !isset()

**Comment by rhukster** [comment]
it's an issue with yaml, 0 is evaluating to false, try `!!int 0`
