### ISSUE TITLE
Extend or plug-into CLI commands

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1314]
Can CLI commands be extended or hooked into? I am extending a plug-in with CLI, and need to run a command that clears a custom folder in /cache alongside/after `clearcache` has ran.

**Comment by rhukster** [comment]
Your actually in luck.  The Cache object has a hook to an `onBeforeCacheClear` (https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Cache.php#L366) event that you can hook into via a custom plugin like so:

```
    public function onBeforeCacheClear(Event $event)
    {
        $remove = isset($event['remove']) ? $event['remove'] : 'standard';
        $paths = $event['paths'];

        if (in_array($remove, ['all', 'standard', 'cache-only']) && !in_array('cache://', $paths)) {
            $paths[] = 'cache://gantry5/';
            $event['paths'] = $paths;
        }
    }
```

This basically adds the `cache/gantry5` folder to the list of folders that a regular Grav cache clear (CLI or admin) will do.

**Comment by OleVik** [comment]
Is this method still valid? I see it's set to be deprecated [in Gantry](https://github.com/gantry/gantry5/blob/18c83d7b167cbb40867e5db70f171483e473f83a/platforms/grav/gantry5/gantry5.php#L63). Running with or without cache enabled, the following:

```
public static function getSubscribedEvents()
{
    return [
        'onBeforeCacheClear' => ['onBeforeCacheClear', 0]
    ];
}

public function onBeforeCacheClear(Event $event)
{
    $remove = isset($event['remove']) ? $event['remove'] : 'standard';
    $paths = $event['paths'];

    if (in_array($remove, ['all', 'standard', 'cache-only']) && !in_array('cache://', $paths)) {
        $paths[] = 'cache://twigfeeds/';
        $event['paths'] = $paths;
    }
}
```

Does not work when running `bin/grav clearcache`. Appending `--all`, of course does because by default it will bust `'cache://`. Seemingly, the path is not registered with the event and thus remains intact.

Also, is there functionality for running a task on update of all or specific plugins/themes?

**Comment by drzraf** [comment]
Note: This event could benefit from being passed the `&$output` too.

**Comment by rhukster** [comment]
The CLI commands have had some big changes in Grav 1.7.  We've broken out the initialization of the various parts of Grav to give more granular control.

Could you guy try putting this in the `CleanCacheCommand.php` for 1.7:

```php
    protected function serve()
    {
        $this->initializePlugins();
        $this->cleanPaths();
    }
```
