### ISSUE TITLE
Cached image is 3x the size of the original

### ISSUE THREAD

**Issue by rab497** [getgrav/grav#1315]
I have a 400 x 400 PNG image with transparent background added to a modular/text page. The orignal image is 56KB. When the page is served the cached image is 165KB. If I have the 'Cache All Images' option turned on in the Configuration this also happens to another PNG image I have in the same page. Why does one of the images get cached and the other not get cached? I guess the difference in the size is due to the image being run through GD for some manipulation and that spits outs the bigger file size. Is there a way to prevent the image being processed?

![cached-img](https://cloud.githubusercontent.com/assets/25840060/23058624/d55cf99a-f4ed-11e6-9962-91aa9da265dc.png)
![original-img](https://cloud.githubusercontent.com/assets/25840060/23058635/e3a0a344-f4ed-11e6-970e-876468135ba0.png)
![not cached](https://cloud.githubusercontent.com/assets/25840060/23058662/03152358-f4ee-11e6-9a5b-772e036ffa3f.png)

`GD Support
enabled
GD headers Version
2.2.3
GD library Version
2.2.3
FreeType Support
enabled
FreeType Linkage
with freetype
FreeType Version
2.6.1
GIF Read Support
enabled
GIF Create Support
enabled
JPEG Support
enabled
libJPEG Version
8
PNG Support
enabled
libPNG Version
1.2.54`

**Comment by flaviocopes** [comment]
The image is served from the cache folder if there is manipulation on them (`.resize`) or any other action, and/or if `system.images.cache_all` is enabled. How are you adding that image?

**Comment by rab497** [comment]
Ahh, new to Grav, just getting used to the inner workings.
I have just put it in the folder with the text.md file. I understand now, this is being added automatically by the TWIG file, which has a cropresize.

`
{% set image = page.media.images|first %}
{% if image %}
  {{ image.cropResize(400,400).html('','','align-'~page.header.image_align) }}
{% endif %}
`

The other image uses a modified showcase template which does not have any image manipulation.

The issue remains that if I want the images to be manipulated automatically I would suffer a 3x increase in the image size... but I guess that is not a problem with Grav.

**Comment by flaviocopes** [comment]
Yes that manipulation is going to be cached, to avoid executing it every time.
It's surely weird that it's 3x, I tested with a PNG image and it grew 10% bigger, I tried a JPG image and it got a 90% decrease in size, but this also depends on the original image size.

To avoid caching in the first place, you could edit that template, and specify an image already 400x400, or do that crop via CSS instead.
