### ISSUE TITLE
Grav broken after upgrade

### ISSUE THREAD

**Issue by hacklab01** [getgrav/grav#1318]
After today's upgrade to the latest version I get a server error 500 saying;

Server Error
Sorry, something went terribly wrong!

500 - Failed to read languages.yaml: Unexpected characters near "www". как внешние"" at line 183 (near "WWW_HELP: "Автоматически связывать любое имя хоста, которое начинается с "www". как внешние"").

For further details please review your logs/ folder, or enable displaying of errors in your system configuration.

/var/www/grav/system/src/Grav/Common/Config/CompiledLanguages.php(62): Grav\Common\File\CompiledYamlFile->content() #1 /var/www/grav/system/src/Grav/Common/Config/CompiledBase.php(160): Grav\Common\Config\CompiledLanguages->loadFile('plugins/externa...', '/var/www/grav...') #2 /var/www/grav/system/src/Grav/Common/Config/CompiledBase.php(99): Grav\Common\Config\CompiledBase->loadFiles() #3 /var/www/grav/system/src/Grav/Common/Service/ConfigServiceProvider.php(118): Grav\Common\Config\CompiledBase->load() #4 /var/www/grav/system/src/Grav/Common/Service/ConfigServiceProvider.php(38): Grav\Common\Service\ConfigServiceProvider::languages(Object(Grav\Common\Grav)) #5 /var/www/grav/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Service\ConfigServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #6 /var/www/grav/system/src/Grav/Common/Themes.php(285): Pimple\Container->offsetGet('languages') #7 /var/www/grav/system/src/Grav/Common/Themes.php(256): Grav\Common\Themes->loadLanguages(Object(Grav\Common\Config\Config)) #8 /var/www/grav/system/src/Grav/Common/Themes.php(47): Grav\Common\Themes->configure() #9 /var/www/grav/system/src/Grav/Common/Processors/ThemesProcessor.php(18): Grav\Common\Themes->init() #10 /var/www/grav/system/src/Grav/Common/Grav.php(126): Grav\Common\Processors\ThemesProcessor->process() #11 /var/www/grav/system/src/Grav/Common/Grav.php(368): Grav\Common\Grav->Grav\Common\{closure}() #12 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('themes', 'Themes', Object(Closure)) #13 /var/www/grav/system/src/Grav/Common/Grav.php(344): call_user_func_array(Object(Closure), Array) #14 /var/www/grav/system/src/Grav/Common/Grav.php(127): Grav\Common\Grav->__call('measureTime', Array) #15 /var/www/grav/system/src/Grav/Common/Grav.php(127): Grav\Common\Grav->measureTime('themes', 'Themes', Object(Closure)) #16 /var/www/grav/index.php(52): Grav\Common\Grav->process() #17 {main} [] []

Any help would be greatly appreciated! :)

**Comment by paulhibbitts** [comment]
@hacklab01 This error is caused by an issue in the External Links plugin, and an issue (and PR) has already been made at its repo https://github.com/Sommerregen/grav-plugin-external-links/

For the short-term, either removing the External Link plugin or replacing it with the previous version should get you going again.

**Comment by hacklab01** [comment]
Thanks @paulhibbitts  I just figured it out myself. :) Reading logs on black on white not green on black helped... :)

I just removed the Russian translation from languages.yaml in the external links plugin and now everythign works.
