### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by geschke** [getgrav/grav#1319]
I would like to add my new theme to the Grav Repository._Here are the project details: **geschke/grav-theme-tikva**

https://github.com/geschke/grav-theme-tikva

Tikva is a minimalistic Grav theme, based on Bootstrap 4 (currently alpha-6) framework. It comes with 25 preinstalled Bootstrap themes, some color options can be customized. It supports a footer with 1 - 6 columns by using pages in a "footer" folder. More options see README file or demo site. 

Thanks in advance & Kind regards,
   Ralf

**Comment by rhukster** [comment]
Added to GPM. Thanks.
