### ISSUE TITLE
classes on markdown links

### ISSUE THREAD

**Issue by bmrankin** [getgrav/grav#1324]
**Markdown**
```
[link](#about?classes=btn,btn-primary)
[link](http://google.com?classes=btn,btn-primary) 
```
**Rendered HTML**
```
<a href="#about?classes=btn,btn-primary">link</a>
<a href="http://google.com" class="btn btn-primary">link</a>
```
Links created on pages work if the anchor is going to another url, but if going to an id on the page they do not render.

Is there a setting I missed somewhere or do I need to escape the '#' somehow?

Thanks

**Comment by rhukster** [comment]
Actually it's a known issue that the `#` target links are not working with classes.  Glad you ticketed it as I had forgotten about it.  I'll look at this soon.

**Comment by bmrankin** [comment]
Thanks @rhukster

**Comment by rhukster** [comment]
Ok, I know what it is.. URL should look like this:

```
[link](?classes=btn,btn-primary#about)
[link](http://google.com?classes=btn,btn-primary)
```

Anchor fragment should come after the query. https://en.wikipedia.org/wiki/Fragment_identifier

Works with this syntx.
