### ISSUE TITLE
Feature request: Ability to use folders without md-files

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav#1328]
Sometimes I need to store images and other files outside the root page folder. See:
![image](https://cloud.githubusercontent.com/assets/7556290/23290776/9001d1d0-faa7-11e6-96c5-68175f230ea8.png)

I don't need any md in it just because sometimes needs to delete files via FTP and can accidentally delete it.

But without md Media Manager don't work: 
`NOTE: You cannot add media files until you save the page. Just click 'Save' on top`

Also I can't create nested folders without putting md in EVERY folder. See:
![image](https://cloud.githubusercontent.com/assets/7556290/19422774/2938c79a-9465-11e6-8b61-bb79aa46a1a0.png)
Grav don't have any option to specify template for nested folders.

Any ideas?

**Comment by flaviocopes** [comment]
Currently, Pages expect a `.md` file into them, otherwise Admin thinks it's not a saved page yet. You can still make this work using file system / FTP instead of Admin, but I think this can be solved with Admin Pro which will feature a more advanced media management functionality.

**Comment by rhukster** [comment]
Hmm.. this works for me, just create "add folder" rather than "add page":

![2017-02-24 at 6 11 pm](https://cloud.githubusercontent.com/assets/1084697/23326616/a7c8311e-fabc-11e6-87f1-69613e980905.jpg)

**Comment by rhukster** [comment]
This is actually an admin feature request.  Grav-core itself supports this fine, it's only the admin that doesn't.  Can you please re-open this issue here: https://github.com/getgrav/grav-plugin-admin/issues

**Comment by Sogl** [comment]
@rhukster It also affects Grav core if we want to extend frontmatter options for nested folders template.
Ok. Done in Admin panel:
https://github.com/getgrav/grav-plugin-admin/issues/1000
