### ISSUE TITLE
[add-resource] New Plugin: Hypothesis

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#1331]
I would like to add a plugin to the Grav Repository. Here are the project details https://github.com/hibbitts-design/grav-plugin-hypothesis

This plugin displays the Hypothesis (https://hypothes.is/) sidebar on your Grav site.

Thanks very much,
Paul
ps - where might I find the info to also get this to work with Gantry themes? For now, I've made a particle that does the same thing.

**Comment by rhukster** [comment]
Added to GPM

**Comment by paulhibbitts** [comment]
Thanks very much Andy!
