### ISSUE TITLE
Anomalous rendering of getgrav.org in a UC Browser on Android

### ISSUE THREAD

**Issue by macropas** [getgrav/grav#1332]
Anomalous rendering of [https://getgrav.org](https://getgrav.org) in a UC Browser (Android):

![screenshot_20170227-211011](https://cloud.githubusercontent.com/assets/7488502/23380665/5e2d3862-fd44-11e6-8f2d-88768696757c.png)

**Comment by rhukster** [comment]
What version of Android, and what browser + version?   Android fragmentation is such that there is a lot of old Android versions out there, running old browsers.

**Comment by macropas** [comment]
Android 6.01
Мost recent version of UC Browser:
![screenshot_20170228-005533](https://cloud.githubusercontent.com/assets/7488502/23383828/e33890b8-fd50-11e6-9548-ea5d3a80efe0.png)

**Comment by macropas** [comment]
@rhukster 
[UCBrowser](https://play.google.com/store/apps/details?id=com.UCMobile.intl&hl=en)

**Comment by rhukster** [comment]
Oh ok, this is not an official Android browser.  

I have no way to test it, and frankly we only really 'support' the popular browsers: Chrome, Firefox, Safari, IE10+.

**Comment by rhukster** [comment]
BTW, tested latest version on iOS and it works fine. i have a feeling it's using webkit to render though.

**Comment by macropas** [comment]
@rhukster 
[it's pity...](http://stats.areppim.com/stats/stats_mobibrowserxsnapshot.htm)

**Comment by flaviocopes** [comment]
Tested UC Browser on the iPhone too, looks good
