### ISSUE TITLE
[add-resource] New Plugin srcset Helper

### ISSUE THREAD

**Issue by simoncramer** [getgrav/grav#1335]
I would like to add my new plugin srcset Helper to the Grav Repository.

It makes images on pages responsive by injecting the 'derivatives' markdown argument. Grav's own media processing and caching is leveraged to generate the images.

Thanks a lot for reviewing my repository at [https://github.com/simoncramer/grav-plugin-srcset/](https://github.com/simoncramer/grav-plugin-srcset/)

**Comment by rhukster** [comment]
Is there a reason you are not using the built-in functionality? https://learn.getgrav.org/content/media#responsive-images

**Comment by simoncramer** [comment]
Yes, because the build in functionality does not allow me to control the image sizes created.
And the main point of this plugin is to make all images in a page responsive without doing it manually in the editor for every image.

**Comment by rhukster** [comment]
Got it thanks, will add.

**Comment by rhukster** [comment]
Added
