### ISSUE TITLE
[add-resource] New Plugin: Esperanto Helper

### ISSUE THREAD

**Issue by jacobm001** [getgrav/grav#1339]
I would like to add my new plugin/theme to the Grav Repository. Here are the project details: **jacobm001/grav-plugin-esperanto-helper**

---

Esperanto Helper is a simple plugin to make it easier to write characters that are commonly used in Esperanto, but aren't used in English (therefore not in a standard QWERTY layout). The plugin works by replacing all *x notation* characeters (such as `cx`) to their proper Unicode counterparts.

**Comment by rhukster** [comment]
Added.

**Comment by jacobm001** [comment]
I'm not seeing it as an available plugin in the Admin interface. I tried both the Stable and Testing selections.

**Comment by rhukster** [comment]
It's added, but GPM rebuild happens every hour at 15mins past the hour.. takes about 10mins to run.. so check in 20 mins or so.

**Comment by jacobm001** [comment]
Oh, my bad. I saw the label change 9 hours ago and assumed your comment had been 9 hours ago as well. Sorry, I'll be patient. :)
