### ISSUE TITLE
Grav Doesn't Treat SVGs as Images 

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav#134]
Can Grav be modified to recognize .svg files as images, but not attempt any pixel manipulation of them?

**Comment by bjornbjorn** [comment]
+1 to this .. would be nice to be able to link to .svg files using the standard lookup mehtod - ie. page.media['icon.svg'].url

**Comment by rhukster** [comment]
This support is being worked on already as part of the media system update. Should be available in a week or two.

**Comment by bjornbjorn** [comment]
Great stuff, Andy! :+1:

**Comment by rhukster** [comment]
This has been implemented in @Gertt's media update
