### ISSUE TITLE
multilingual site.yaml for ceevee theme

### ISSUE THREAD

**Issue by pacija** [getgrav/grav#1342]
Hi,

I am relatively new to Grav, and am trying to create multilingual homepage with ceevee theme. The problem I'm facing is the fact that this theme takes information from site.yaml (header/title and header/description) and displays it on homepage. But as far as I'm aware, site.yaml can't have multiple per-language values for header/title and header/description.

Is there some other way I could achieve this?

**Comment by rhukster** [comment]
You would have to modify the theme to take values from a Lang file or prefix value keys with the Lang code and modify the template to do the same when it retreives the value.
