### ISSUE TITLE
Need help for Caching

### ISSUE THREAD

**Issue by MrMacStripe** [getgrav/grav#1344]
Hey Grav community, first of all, this is not an issue but a question.

I want to use Grav for the first time and am ready to go live except for the caching part. I´m used to enable GZIP and HTTP Headers in the .htaccess file, write a robots.txt etc. 

What do I need to do in Grav to set it up for good and efficient caching? The docs aren´t helpful at all. The info I get there are visible as tooltips in the admin panel. 

If I run the site through google´s page speed insights I get warnings about undefined http headers for my images, the pipelined css and js and so on.

Please help to bring some light in this topic.

Edit: I should add some more info. 
The Caching, HTTP Header options etc are set to enabled in the admin panel. But I feel that this is not everything you can do to speed up the site.

**Comment by rhukster** [comment]
Not a definitive guide, but might help you:  https://getgrav.org/blog/turbo-charge-grav-with-a-cdn

**Comment by ganar** [comment]
Related to this question: I get almost all of my images with the correct timestamp, at least all of the images that come in the content. But the images I'm calling in the template do not get cached or get a time-stamp.

This is also giving me problems in  *Google´s page speed insights*

This is the code I'm using:

`<img src="{{ theme_url }}/assets/img/logo_moviles_diapo.png" alt="">`

I've yet to find instructions on the docs on how to reference images via `TWIG` or GravCMS in the templates and get them to be stored in cache, or at least, to have the propper time-stamp.

**Comment by flaviocopes** [comment]
@ganar only page content is cached, images directly written in Twig are not. 

Put that image into `user/pages/images/` and use

`{{ page.find('/images').media['logo_moviles_diapo.png'].html}}`

See https://learn.getgrav.org/content/media#where-to-put-your-media-files
