### ISSUE TITLE
onPageContentRaw event limitation (`$process_markdown`/`$process_twig` declared too early)

### ISSUE THREAD

**Issue by marcastel** [getgrav/grav#1345]
Trying to use different markdown engines that can be set in a page's front matter.

Managed to do this with `onPageContentProcessed` but this is not a clean hack.

Tried `onPageContentRaw` which appears to be the logical way of achieving our goal.

```{.php}
public function onPageContentRaw (Event $e) {
...
// Use our own markdown conversion tool, but keep Parsedown for Admin tool
if (!$this->isAdmin ()) $page->setRawContent ($this->processMarkdown());

// Tell Page class not to enact intrinsic Parsedown engine
$process = $page->process ();
$process ["markdown"] = false;
$page->process ($process);
...
}
```

I used `Page::process()` to toggle off markdown handling. However, this can't work because the `$process_markdown`  variable in `Page::content()` is set prior to triggering the events.

Rather than:
```
if ($process_markdown) $this->processMarkdown();
```

Could we have:
```
if ($this->shouldProcess('markdown')) $this->processMarkdown();
```

While we're at it, the same applies to `$process_twig`, so why not:
```
if ($this->shouldProcess('twig')) $this->processTwig();
```

Cheers

**Comment by rhukster** [comment]
Why not set:

```
process:
  markdown: false
```

In the page front matter?

**Comment by marcastel** [comment]
Obviously. KISS principle :-)

- This works on regular pages (however perhaps not as expected, see note 1 below).
- Seems not to work on modular page content portions.

Needs further investigation and tests. I will update this as soon as I have done sufficient testing.

FWIW: Still _quick and dirty_ here is my [test plugin](https://github.com/ISLEcode/grav-dragonfly-plugin).


_Notes/Todo_:

1. I haven't seen where the `header.process.markdown` setting is used. Apparently not in `Page.php`. From my current (limited) understanding, this setting will allow you to only disable the _internal_ markdown engine, it doesn't allow you to swap it with another. Or put differently, if you toggle the Markdown engine off, the custom plugin will have to reimplement the pre-/post logic for Twig processing as currently implemented in `Page.php`.

2. Swapping the Markdown engine should/could also impacts the Twig `markdown` filter (i.e. if you change the Markdown engine for pages, you should probably also change it for Twig templates). This I have not investigated yet. Gladly accepting kick off help :-)

3. Keep track of _mandatory Grav Markdown requirements_ and add test suite for this such that any plugin _fiddling around_ with the Markdown engine, doesn't break expectations of core Grav components and the administration module.

**Comment by rhukster** [comment]
1. It does work, just tested it.  It basically just disables any markdown processing of pages.  You could add your own in `onPageContentRaw` or `onPageContentProcessed` as really those are either side of the process markdown process in Page.

2. You would need to add your own Twig filter to use your new markdown engine.  

3. The default Parsedown engine is extended with some grav media/link logic.  If you wanted to implement your own markdown engine, you will probably want to provide support for this functionality (which is broken out already in `Grav\Common\Helpers\Excerpts`).

> FYI: The markdown engine was never really intended to be swapped out in Grav 1.x that's why this process is not super trivial, although it's possible.  This is something we are intending to remedy in Grav 2.x

**Comment by rhukster** [comment]
Closing to due to inactivity
