### ISSUE TITLE
Publish Date publishes Today's Date rather than Publish Date of Page

### ISSUE THREAD

**Issue by simmonsr** [getgrav/grav#1346]
Please see sshot:

![screen shot 2017-03-10 at 2 15 35 pm](https://cloud.githubusercontent.com/assets/5002814/23811941/c3f26846-059d-11e7-93f6-4d348ad87a03.jpg)

**Comment by rhukster** [comment]
It's failing because you should be using:

```
{{ page.publishDate()|date(display.date.format) }}
```

This will ensure you use the `publishDate()` method on the Page object.

This is the date that's already been processed and converted into a timestamp.  Your trying to access something directly in the header, and that would be `page.header.publish_date`.

**Comment by simmonsr** [comment]
Thank you
