### ISSUE TITLE
Defaut ordering of modular should be folder, not date

### ISSUE THREAD

**Issue by olivierdalang** [getgrav/grav#1347]
Hi !

Currently it seems default ordering for modular pages is by date. I think it doesn't make much sense to sort content by date for modulars, and it's also quite disorientating for new users, as page order will seem to change randomly upon saving files.

I'd suggest to change default ordering to folder name.

Thanks for the great work !

**Comment by rhukster** [comment]
ordering in the admin is based on if you have a `content.order.by` in your page header, it will try to order by that type.  However this doesn't work well for modular page with `custom` ordering.  The best solution I've found is to simply use folder prefix ordering, with no `order.by`:

```
01._showcase
02._text
...
```
