### ISSUE TITLE
How to get inheritance working in an existing theme

### ISSUE THREAD

**Issue by ganar** [getgrav/grav#1350]
I managed to [get inheritance to work with antimatter using this instructions](https://getgrav.org/blog/theme-development-with-inheritance), I'm trying to do the same [with bones](https://github.com/smartgravity/grav-theme-bones), but the new theme will not inherit the theme Bones properly —no CSS in the header— .

[The developer does not seem to know how to solve the issue](https://github.com/smartgravity/grav-theme-bones/issues/34), an open issue has been unanswered for 3 months. 

How could I solve this issue myself? what has to be added to a theme in order for it to work properly with inheritance when creating a theme based on it?

**Comment by rbukovansky** [comment]
@ganar Well, I can see I'm not alone with same issue... #1353

**Comment by ganar** [comment]
I'm glad you managed to make it work. I'm abandoning the idea of using inheritance in my new template, and instead will move forward with an skeleton template suggested by another user. Inheritance: it was good while it lasted.

**Comment by rhukster** [comment]
Should be sorted with this commit: https://github.com/getgrav/grav/commit/874160480faf5d968a8f32a3f254618e4dd0ad0d

**Comment by rbukovansky** [comment]
It really works. :+1:

**Comment by shiz0** [comment]
Sorry to dig this up, but is there something else to do to make it work?
I tried with a fresh install today (1.3.3) and pulled bones theme via gpm, but sadly, no inheritance. Just unformatted content. Firefox's web console said it could not load some foundation css stuff with a "-" in the filename, so I suspect I am still experiencing the original issue here maybe?

**Comment by rhukster** [comment]
It might be an issue with bones skeleton, it's definitely working for most themes.

**Comment by shiz0** [comment]
Probably then... 
it is not that big of an issue for me anyway, it's just that earlier this year i started a project for a client on a copy of bones and I thought I could maybe switch to properly using inheritance before handing the site over soon.
But now I will just finish it like this which is totally fine, too.
Thank you for your answer.
