### ISSUE TITLE
Markdown extra enabled --> Source Code Error

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#1352]
In a markdown file I embedded html5 audio:

![source1](https://cloud.githubusercontent.com/assets/12480617/23919462/2fceb36a-08f7-11e7-9f97-d39d01c4d56a.png)

Resulting Source code:

![audio](https://cloud.githubusercontent.com/assets/12480617/23919436/1a91ab7e-08f7-11e7-8159-0f1a9a7fd6b5.png)

After enabling markdown extra--> Resulting Source Code:

![source2](https://cloud.githubusercontent.com/assets/12480617/23919482/43ed9064-08f7-11e7-9d30-b5d5469e1502.png)

Grav issue? markdown extra issue?

**Comment by rhukster** [comment]
It's markdown extra i'm afraid (well ParsedownExtra).  

You can see the same thing by pasting your audio code here: http://parsedown.org/extra/

I have had quite a few weird issues with markdown extra.  I don't really recommend using it unless it can be avoided.  If you really need it, just use it on that specific page only, and don't enable it site-wide.

BTW, you could submit an issue upstream: https://github.com/erusev/parsedown-extra/issues
