### ISSUE TITLE
Korean language support

### ISSUE THREAD

**Issue by rkrejcii** [getgrav/grav#1355]
I would like to ask you if Grav supports Korean language. In `system/languages` I searched for `ko.yaml`, but didn't find any.

If the Korean is not supported, how can I add the support on the theme level please? Also need to make it work with Grav LangSwitcher plugin https://github.com/getgrav/grav-plugin-langswitcher.

Many thanks.

**Comment by OleVik** [comment]
You would add language for a theme in [languages.yaml](https://learn.getgrav.org/content/multi-language#plugin-and-theme-language-translations). Korean is not fully translated [in admin](https://crowdin.com/project/grav-admin/ko) or [in core](https://crowdin.com/project/grav-core), but you can contribute to it. Once translations are complete, they are pulling into Grav by the developers.

**Comment by rhukster** [comment]
Translation of languages for Grav core and Amin plugin are handled on Crowdin.com

If you want to provide Korean translations, please do so there and those language files will me merged back into GitHub.

https://crowdin.com/projects/getgrav

Cheers!
