### ISSUE TITLE
Grav in subfolder with root URL

### ISSUE THREAD

**Issue by GittiHab** [getgrav/grav#1358]
Hello,

I am just trying to deploy a new site we moved to grav. In order to keep the old site running while deploying we would like to keep grav in an own subdirectory (let's call it `grav`). Therefore the site would be reachable under `domain.com/grav` but I want it reachable under `domain.com` – sounds exactly like Scenario 1 described in the [Docs](https://learn.getgrav.org/advanced/change-site-url).
This is why I added `custom_base_url: 'https://domain.com` and the `.htaccess` modification. And tadaa... the front page works! But now all other pages and the admin page throws a 404 error. If I remove the `custom_base_url` setting it is the other way around – all pages work except for the front page.
With front page I mean the page being displayed if only `domain.com` is in the address bar.

What am I doing wrong?

Thanks for your help already 😃

**Comment by GittiHab** [comment]
OK, I have been trying around another few hours. As it turns out the main problem has been that I am using `https://` and my provider does some strange rewrites there.

So when using `http://` most things work fine with two exceptions which I find very weird:

1. If I now call the start page on the `https://`-version I get a error about too many redirects.
2. If I open subpages on the `https://`-version the javascript and css files aren't loaded because the assetmanager adds a `/` infront of the absolute pathes which Grav seems to add if another URL than the `custom_base_url` is called.

So there seems to be some problems in general when trying to use a site on both http and https version and a different base_url – I believe people would experience same issues when using different base_urls.

**Comment by GittiHab** [comment]
For the `https`-Problem I have just investigated a bit and figured that setting `absolute_urls = enabled` (to enabled) should fix this – it probably didn't work during my first tests because of some browser cache.

The problem is that in `Assets.php` on line 210 a `/` is prepended to the `base_url` if `absolute_urls` are turned off.

It would of course be cool if this is done more intelligently here as the `base_url` can obviously be absolute and relative.

**Comment by rhukster** [comment]
I am not able to reproduce this. I have setup many many Grav sites on both HTTP and HTTPS at the root of a site but also in subfolders.

I just tested again on my local with a grav installation in a sub-folder and have no problem reaching this via HTTP or HTTPS.

Are there specific settings you have enabled in system.yaml? Can you paste a copy of your system.yaml here?

**Comment by GittiHab** [comment]
Thanks for trying to help!

As it turns out, the problem with the 404 error is caused by a faulty configuration at my hoster, so this problem can be marked as solved.

The other issue which remains is that the frontpage cannot be loaded if the `base_url` is the other version. Did this work for you when reconstructing?

**Comment by rhukster** [comment]
The custom `base_url` is really for specific cases where there is reverse proxies or rewriting rules that cause Grav to be unable to determine it by itself.  It's very likely that adding arbitrary values in here will cause problems.
