### ISSUE TITLE
[add-resource] New Image Gallery Plugin

### ISSUE THREAD

**Issue by variar** [getgrav/grav#1360]
I would like to add my new image gallery to Grav Repository. Here are my project details: https://github.com/variar/grav-plugin-unitegallery

This plugin adds twig extension that provides new function for creating image galleries using [Unitegallery](http://unitegallery.net/) javascript library (https://github.com/vvvmax/unitegallery/).

Usage examples:
```
// with default plugin configuration
{{ unite_gallery(page.media.images) }}

// with custom options (passed directly to unitegallery js function)
{{ unite_gallery(page.media.images, '{"gallery_theme":"tiles", "tiles_type":"justified"}') }}
```

**Comment by rhukster** [comment]
Added to GPM, should show up in the next hour.

**Comment by variar** [comment]
I'm sorry, but for some reason gpm -f index still does not show this new plugin in the output. Should I create new release to make it visible? Or maybe there is something wrong with blueprints?

**Comment by rhukster** [comment]
I'm not sure what the issue is.  It seems to find the release just fine, but it just doesn't show up. I will dig into it more.

**Comment by rhukster** [comment]
Ok it was another plugin further down the list that had invalid syntax in the changelog that was tripping up the whole update script.  I've removed that plugin for now. Yours is showing up.
