### ISSUE TITLE
[Possible bug] Unexpected behavior on page.find(/home/_modularblock).content 

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav#1363]
Hi,

I noticed today that when calling a modular page from another page using {{page.find('/home/_our-team').content}} the whole modular block is inserted (template with its variable) into the page whereas I expected to only display the markdown content of this very page.

Is that on purpose? 

Let me know if you need more info to reproduce this.

**Comment by rhukster** [comment]
Modular 'content' is always pre-rendered with the associated Twig template.  This is what makes it different from regular pages.  This is expected behavior.
