### ISSUE TITLE
Vignetting filter for images

### ISSUE THREAD

**Issue by olivierdalang** [getgrav/grav#1364]
Hi !

A very simple, nice and useful image filter is [vignetting](https://en.wikipedia.org/wiki/Vignetting). Would it be possible to add it to grav ?
The implementation is very easy : http://php.net/manual/fr/function.imagefilter.php#109809

This would require to fork the gregwar library, but as far as I understand Grav doesn't rely on gregwar releases anyway.

I just tried the changes locally and it works great.

What do you think ?

**Comment by olivierdalang** [comment]
See https://github.com/Gregwar/Image/issues/137

**Comment by rhukster** [comment]
We do still use Gregwar from composer. We were stuck on a specific commit, but i've now modified that to be just dev-master.  If you can get your function added to Gregwar it will get picked up by Grav.

**Comment by olivierdalang** [comment]
For the record, I made a PR here : https://github.com/Gregwar/Image/pull/138
I hope it will get some attention as the repo doesn't seem very active...

I think if this gets merged, we'd still need to change `system/src/Grav/Common/Page/Medium/ImageMedium.php` to add `vignette` to `$magic_actions`
