### ISSUE TITLE
Cyrillic support in substr (page.summary)

### ISSUE THREAD

**Issue by sonik2k** [getgrav/grav#1365]
Truncator.php
line  107

`                $currentText[0]->nodeValue = substr($currentText[0]->nodeValue, 0, $currentText[1] + 1);`

to

`               $currentText[0]->nodeValue = mb_substr($currentText[0]->nodeValue, 0, $currentText[1] + 1);`

**Comment by rhukster** [comment]
Can you edit the file directly in GitHub and create a Pull Request? https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Helpers/Truncator.php

**Comment by sonik2k** [comment]
Oy, i can edit files in repo ;)

**Comment by flaviocopes** [comment]
@sonik2k did you ever create the PR, or you forgot about it? Was looking to test

**Comment by rhukster** [comment]
Closing to due to inactivity

**Comment by keosion** [comment]
Here is the PR : #2007
