### ISSUE TITLE
403 Forbidden error on MAC

### ISSUE THREAD

**Issue by ericfjl** [getgrav/grav#1366]
I use the grav's .htaccess,I get 403 error [You don't have permission to access /opensource/php/grav-admin/ on this server.],but when i change the .htaccess to my .htaccess,I get it successfully!
my .htaccess:[
```
<IfModule mod_rewrite.c>
  Options +FollowSymlinks -Multiviews
  RewriteEngine On

  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-f
# RewriteRule ^(.*)$ index.php/$1 [QSA,PT,L]
  RewriteRule ^(.*)$ index.php [L,E=PATH_INFO:$1]
</IfModule>
```
]

**is this something wrong with the grav's .htaccess?**

**Comment by rhukster** [comment]
Well i'm not sure where that `.htaccess` comes from, but ours looks like this:

https://github.com/getgrav/grav/blob/develop/.htaccess

I think you are working with an `.htaccess` from your hosting company?

**Comment by ericfjl** [comment]
I mean that : yours .htaccess(https://github.com/getgrav/grav/blob/develop/.htaccess) is not work in my mac ,the error is 403 


![image](https://cloud.githubusercontent.com/assets/4636005/24187986/719e85da-0f1a-11e7-9f4a-b5ef4efa3ae8.png)

**Comment by ericfjl** [comment]
And i use anoher .htaccess form [`http://git.oschina.net/rainfer/YFCMF/blob/master/.htaccess?dir=0&filepath=.htaccess&oid=23ba96fef1481b830b3f12ac052e1a1e92e8c27a&sha=d2d960ff59d3d76a575321712ffffbc7d0e10f11]`,the grav is work successfully.

so i guess that there are something wrong with the [`https://github.com/getgrav/grav/blob/develop/.htaccess`] in mac

**Comment by rhukster** [comment]
Well your the first one to report it.  We all use Macs here, either with MAMP, native Apache, and Brew Apache.  All work fine.  What kind of server setup do you have that's causing problems?

**Comment by ericfjl** [comment]
I use the native Apache

**Comment by ericfjl** [comment]
I run the `bin/grav install` on my mac,and it work!

**Comment by flaviocopes** [comment]
So the problem was you downloaded from GitHub and the vendor/ folder was not having the Composer dependencies?

**Comment by flaviocopes** [comment]
Closing as was solved
