### ISSUE TITLE
getgrav.org server error

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#1367]
![error](https://cloud.githubusercontent.com/assets/12480617/24138017/d1108bee-0e16-11e7-82ac-a3f9c8a57bfc.png)

**Comment by mahagr** [comment]
It looks like DNS issue. It may go away soon(ish)..?

**Comment by axel-rank** [comment]
![error2](https://cloud.githubusercontent.com/assets/12480617/24138431/775623d2-0e18-11e7-862b-48e1d9b2f76e.png)

**Comment by OleVik** [comment]
Should note that the subdomain learn.getgrav.org is not affected.

**Comment by axel-rank** [comment]
getgrav.org is back.

**Comment by axel-rank** [comment]
Server Error is back???

**Comment by mahagr** [comment]
I bet it is DNS issue in github side. Or some kind of attack against them. Should be fixed again.
