### ISSUE TITLE
Visible Yes / No Options

### ISSUE THREAD

**Issue by simmonsr** [getgrav/grav#1370]
I'm going to throw a request in here to just simply have Yes / No option for Visible when adding a New page (remove Auto):

![screen shot 2017-03-21 at 1 56 19 pm](https://cloud.githubusercontent.com/assets/5002814/24166973/227b7508-0e43-11e7-8c1d-73692983e0fe.jpg)

In the end the only options are Enabled / Disabled, so I think this would be best really.

**Comment by rhukster** [comment]
This was actually  added to to an issue where people wanted to be able to more easily add new pages and have the wizard modal (this window) know if the other pages added for this parent were predominantly visible or not.
