### ISSUE TITLE
403 forbidden error -- mod_sec workaround doesn't apply

### ISSUE THREAD

**Issue by amrikahill** [getgrav/grav#1371]
Hi there, 

I installed grav about a week ago and still can't get access to all the features. I get a 403 Forbidden error as seen in the image below. I've gotten my hosting company to disable the mod_sec issue that I read could be a cause for this error. However that didn't work. 

I cannot add pages or posts without the site breaking. 

Thanks for the help!
<img width="1440" alt="screen shot 2017-03-22 at 2 01 09 am" src="https://cloud.githubusercontent.com/assets/23082087/24184444/5677bedc-0ea4-11e7-8c3c-3e66c66f3f49.png">

**Comment by rhukster** [comment]
Use developer tools and the network tab.  Select the XHR filter and reload the page.  You should see the request details for the call that is failing.  Can you confirm with your hosting provider why that request is being denied?

From the message it's clear that the webserver is denying the request.  Litespeed should be able to use .htacess rules just fine, so you might also want to ask them about that.

**Comment by rhukster** [comment]
Closing to due to inactivity
