### ISSUE TITLE
[change-resource] Take over Plugin 

### ISSUE THREAD

**Issue by geschke** [getgrav/grav#1372]
I would like to take over an existing plugin grav-piwik-plugin. Here are the project details: **MichelePalmieri/grav-piwik-plugin**

https://github.com/MichelePalmieri/grav-piwik-plugin

My pull request (https://github.com/MichelePalmieri/grav-piwik-plugin/pull/5) is still not answered, and it seems that the author didn't answer on issues since more than a year. 
It is just a small plugin, and it does not need much work to update, but I think the new Piwik code should be embedded soon. For sure I will have a look at the open issues, too. 

Thanks in advance!
Kind regards,
    Ralf

**Comment by rhukster** [comment]
I've submitted a ticket and we'll see how/if the owner responds.

**Comment by MichelePalmieri** [comment]
done

**Comment by rhukster** [comment]
Seems the original author is good with you taking over the plugin.  Just submit a new issue with request for plugin release when it's ready for another release, and we'll update the reference to your version.  Cheers.
