### ISSUE TITLE
No longer possible make Theme functions calls from blueprints (data-*@).

### ISSUE THREAD

**Issue by parcand** [getgrav/grav#1373]
This feature does not seem to work anymore:
`data-options@: ['\Grav\Theme\ImaginaryClass::getMyOptions', 'default', false]`

Could it be related to the recent changes that have been made to the theme autoloader?
https://github.com/getgrav/grav/commit/874160480faf5d968a8f32a3f254618e4dd0ad0d

**Comment by rhukster** [comment]
Well, it's possible, if you had this method inside your theme's standard class but that would assume your theme was called `imaginary-class` with the theme's class being: `imaginary-class/imaginary-class.php`.

**Comment by parcand** [comment]
Thanks for pointing that out. It made me realize that I was wrongfully using camelCase for both my theme folder and primary class file name. I will make sure to rename my stuff using hyphens as words separators. That said, thank you for the quick fix, I'm sure it will help other people who might have made the same mistake.

**Comment by ash0080** [comment]
@rhukster 
data-default@ doesn't seem to work now, data-options@ works
only test in admin
as official tutorial:
data-default@: '\Grav\Plugin\Admin::route'

**Comment by rhukster** [comment]
This works for me.  However, if there is an error in your static method, it will appear that the data-@ option is not working.  I found this out the hard way this week :)

Try calling a known working function then maybe just call your static function from your plugin code directly to ensure things work as expected and the correct value is returned.
