### ISSUE TITLE
Is the theme update process ok?

### ISSUE THREAD

**Issue by geschke** [getgrav/grav#1375]
Hello!

Just a question - I released a new version of my theme yesterday (approximately before 11 hours), but until now it didn't appear on the theme overview page (https://getgrav.org/downloads/themes) with the new version 0.1.4. The same in my Grav installations, neither in web interface nor when I try with gpm on the cli (with or without -f option). 
So I would like to ask if the theme update process is ok? 

Thanks in advance & Kind regards,
   Ralf

**Comment by rhukster** [comment]
Ugg.. well it was a plugin that was causing the whole script to error out.  I've commented it out until we can find what the solution is. Should pick up your new release in 20 mins or so.
