### ISSUE TITLE
Inline PHP codes ?

### ISSUE THREAD

**Issue by hostingwalk** [getgrav/grav#1376]
I know JS HTML CSS shortcodes are possible, but is their anyway to use PHP inline code ?

**Comment by rhukster** [comment]
You can't put PHP inline in your content or even in your Twig.  This is for security reasons to help deter hacking.  

The preferred approach is to create a simple plugin with your PHP logic.  Depending on your needs this could be a shortcode plugin, markdown plugin, or just a custom Grav plugin that does something and assigns data to a Twig variable to be used in Twig templates. 

There are plenty of examples of these various types in the downloads section.
