### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by akeif** [getgrav/grav#1379]
I would like to add my new plugin to the Grav Repository. Here are the project details: **[akeif/grav-plugin-psysh](https://github.com/akeif/grav-plugin-psysh)**

Allow usage for the absolutely awesome gorgeous amazingly useful PsySH shell in Grav context.

This plugin provide a single command `bin/plugin psysh shell`. It's aimed at core and plugin developers but can help any dev who would benefit from interactive debugging.

**Comment by rhukster** [comment]
Will do soon! thanks.

**Comment by rhukster** [comment]
Should show up on next GPM rebuild
