### ISSUE TITLE
HHVM Fatal error, clean install

### ISSUE THREAD

**Issue by ArkQA** [getgrav/grav#138]
Apache 2.4 + hhvm latest + Ubuntu 14 LTS

Fresh install: git clone, gpm install. Dependencies installed ok.

`$ php index.php` or visiting in browser produces this:

```
Fatal error: Uncaught exception 'BadMethodCallException' with message 'Call to a member function get() on a non-object (NULL)' in /opt/wwwroot/system/src/Grav/Common/Assets.php:168
Stack trace:
#0 /opt/wwwroot/system/src/Grav/Common/Grav.php(206): Grav\Common\Assets->init()
#1 /opt/wwwroot/index.php(29): Grav\Common\Grav->process()
#2 {main}
BadMethodCallException: Call to a member function get() on a non-object (NULL) in file /opt/wwwroot/system/src/Grav/Common/Assets.php on line 168
Stack trace:
  1. BadMethodCallException->() /opt/wwwroot/system/src/Grav/Common/Assets.php:168
  2. Grav\Common\Assets->init() /opt/wwwroot/system/src/Grav/Common/Grav.php:206
  3. Grav\Common\Grav->process() /opt/wwwroot/index.php:29
```

The line on system/src/Grav/Common/Assets.php appears to be:
```
$asset_config = (array)$config->get('system.assets');
```

gpm install worked, but:

![image](https://cloud.githubusercontent.com/assets/10857464/6052675/60862e64-ac8a-11e4-9c00-ef9958ae9d03.png)

**Comment by rhukster** [comment]
HHVM is completely untested and I guess there are some compatibility issues that exist.  I'll keep this one around to track when we add HHVM support.

**Comment by ArkQA** [comment]
Thanks. I assume this has something to do with https://wiki.php.net/rfc/catchable-call-to-member-of-non-object (3rd reference at bottom)?

(btw - sorry, I forgot that hhvm isn't stock php; been using it for long enough that it slipped my mind)

**Comment by rhukster** [comment]
I don't think it's that PHP issue as Grav runs 100% fine on 5.4, 5.5 and 5.6. It's definitely some bug or limitation in HHVM that we would have to work around to provide support.

**Comment by rhukster** [comment]
Grav 0.9.17 has been fixed to support HHVM.  Enjoy :)
