### ISSUE TITLE
http error 500 in windows server2008 r2

### ISSUE THREAD

**Issue by ericfjl** [getgrav/grav#1380]
HTTP 错误 500.0 - Internal Server Error
无法在<fastCGI>应用程序配置中找到<handler> 

模块 FastCgiModule 
通知 ExecuteRequestHandler 
处理程序 phpStudy_FastCGI 
错误代码 0x80070585 
请求的 URL http://gw.xirmei.com:80/index.php 
物理路径 D:\xrm\deliver.xirmei.com\index.php 
登录方法 匿名 
登录用户 匿名 
 最可能的原因:
•IIS 收到了请求；但在处理请求过程中出现内部错误。此错误的根本原因取决于处理该请求的是哪一个模块以及出现此错误时工作进程中出现了何种情况。
•IIS 无法访问网站或应用程序的 web.config 文件。如果 NTFS 权限设置不正确，便会出现这种情况。
•IIS 无法处理网站或应用程序的配置。
•已经过身份验证的用户没有使用此 DLL 的权限。
•该请求将被映射到托管处理程序，但不会安装 .NET 可扩展功能。
 可尝试的操作:
•确保 web.config 文件的 NTFS 权限正确，并允许访问 Web 服务器的计算机帐户。
•检查事件日志中是否记录了任何附加信息。
•确认 DLL 的权限。
•如果请求被映射到托管处理程序，则安装 .NET 可扩展功能。
•创建跟踪规则以跟踪此 HTTP 状态代码的失败的请求。有关为失败的请求创建跟踪规则的详细信息，请单击此处。
 链接和更多信息此错误表明在处理请求时出现问题。Web 服务器收到了请求，但在处理过程中出现错误，导致 500 错误。 
查看更多信息 »

Microsoft 知识库文章:

•294807

**Comment by flaviocopes** [comment]
Which PHP version are you running? Grav requires 5.5.9 or later. PHP 5.5.9 was released in 2014, Windows Server 2008 a few years earlier, so I guess that is the problem?

**Comment by flaviocopes** [comment]
Just a hint - if your PHP is up to date, then it's something else.

**Comment by ericfjl** [comment]
C:\Users\Administrator>php --version
PHP 5.6.24 (cli) (built: Jul 20 2016 21:18:46)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by ericfjl** [comment]
I had changed my web service to sentos,and it work well!

**Comment by Mausy5043** [comment]
This week I stumbled on a similar problem with my hosting provider. They had changed me to PHP v7.0 and this caused the site to return an HTTP error 500 when visited.
After setting the PHP version to 5.6.31 the site worked again. 

Is there also an upper limit to the PHP version?

**Comment by flaviocopes** [comment]
No, any PHP version since 5.6 is tested and works fine. One possible issue is that the PHP 7.0 version they installed missed some required libraries. 

This is detected by the *Problems* plugin, but it's run only the first time you access Grav. It can be re-run by removing the `cache/problem-check-*` file.

**Comment by Mausy5043** [comment]
@flaviocopes Thanks. v7.1 works now, so, I'm sticking with that.
