### ISSUE TITLE
Download links for theme and grav-core.

### ISSUE THREAD

**Issue by tboulogne** [getgrav/grav#1381]
Hello,

I'm working on some scripting with grav and i faced problems. Solved them could help others, i think.

**Download link**
It could be interesting to have a "latestrelease.tgz" link in complement of the numbered link to facilitate some scripting task. (the script will always have the latest version)

**Command line interactive option**
In the same idea, bin/gpm and bin/grav could have an option to load a file (yaml format for example) exempting fulfillment  of all interactive parameters. (Did not see this, excuse-me if option exist :-( )

Hope it could help improving this fantastic tool !

Regards,

**Comment by w00fz** [comment]
Re #1, you can already via https://getgrav.org/download/plugins/admin/latest.

Re #2 GPM has a lot of options , you can use direct-install for specifying a link manually, you can also use --all-yes to skip prompts or you can specify the options to alter them.
