### ISSUE TITLE
Add Page in RC-3 Core always creates folder number with prefix 1001

### ISSUE THREAD

**Issue by bleutzinn** [getgrav/grav#1386]
Today I did a fresh install using composer and then updated core only from Admin.
Then when I create (Add) a page from Admin:
- with v1.1.17 and Admin v1.2.14 -> OK; folder prefix increments as normal
- using v1.2.0-rc.3 with Admin v1.2.14 -> not OK; every new page gets a prefix of 1001. There is no incrementing, so 1002 does not get created.

Both MacOS and Debian server show same behaviour. Everything works fine. Pages get served, can be edited, etc.

**Comment by rhukster** [comment]
Ya I can see this also. My testing involved reordering which fixes it. No reodering at all leaves this behavior.

**Comment by rhukster** [comment]
Should be sorted now. Please confirm with commit in admin plugin.

**Comment by bleutzinn** [comment]
Just downloaded Admin Plugin rc-4 from develop and can confirm the fix.
