### ISSUE TITLE
Please Review and Resolve before continuing...

### ISSUE THREAD

**Issue by ericfjl** [getgrav/grav#1387]
I got these error when i input this url:gw.xirmei.com
(IIS6.1+php5.6)

D:/xrm/deliver.xirmei.com/cache exists but is not writeable

D:/xrm/deliver.xirmei.com/logs exists but is not writeable

D:/xrm/deliver.xirmei.com/images exists but is not writeable

D:/xrm/deliver.xirmei.com/assets exists but is not writeable

D:/xrm/deliver.xirmei.com/user/data exists but is not writeable

D:/xrm/deliver.xirmei.com/backup exists but is not writeable

D:/xrm/deliver.xirmei.com/tmp exists but is not writeable

**Comment by BugHunter2k** [comment]
The user which runs ISS under has noch permissions to write to the mentioned directories. Have a look at:
https://learn.getgrav.org/basics/requirements#permissions
