### ISSUE TITLE
403 forbidden  error

### ISSUE THREAD

**Issue by magicnote** [getgrav/grav#1388]
i use grav-skeleton-blog-site ，it’s from `https://github.com/getgrav/grav-skeleton-blog-site`,I get 403 error['You don't have permission to access /tag:link on this server.'] from `/tag:link` .

but, i use `/blog/tag:link` or php web server(`php -S  ip:port system/router.php`), is work.

env:
Apache/2.4.18 (Win32) PHP/5.5.37  （WAMP）

sorry, i english is so bad.

**Comment by flaviocopes** [comment]
When using Apache on Windows, you need to change in `user/config/system.yaml` the `param_sep` value from `:` to `;`, see https://learn.getgrav.org/basics/grav-configuration#system-configuration. This should solve the issue.
