### ISSUE TITLE
Direct Install lacks options and cleanup

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1389]
Thought I'd tag @akeif for this, since he's been very involved in getting the `directinstall` command working. Whilst the command works well, with only minor infidelities I thus far have blamed on Windows and haven't tracked down fully in debug, two points are worthy of immediate consideration: The command does not register common options, and folders are not deleted on failure or success.

For the former, `force`, `all-yes`, and `destination` are not available. Just like the rest of GPM, having them available cuts down on development-time significantly. For the latter, I noticed that regardless of whether the installation halts or succeeds, the temporary folders in `/tmp/` are not deleted - at least none have been thus far.

**Comment by akeif** [comment]
Thanks @OleVik :smile:. I'm definitely interested in tackling this issue.

### My understanding

If I get you right, here what should be done before solving this issue.
1. files created in `/tmp/` while running `directinstall` should be removed
1. **folders** must be deleted whether the command succeed or fail
1. command `force` should be available and implemented properly
1. command `all-yes` should be available and implemented properly
1. command `destination` should be available and implemented properly

### Request for more information on point 2
I get you are saying that this might happens only on Windows.
Also, what do you mean by **folders**?

**Comment by OleVik** [comment]
Folders, as in directories. After running the command, whether it fails or not, it leaves behind a copy of the extracted extension in `/tmp/Grav-randomhash/` for each attempt, but they are not subsequently removed by the process.

What happens on Windows is not related to point 1-5, they are merely current deficiencies of the implementation. On Windows two things happen on occasion: `mkdir` fails, or Composer's Autoload fails with `the name is already in use in /tmp/Grav-randomhash/pluginname/pluginname.php`. I suspect this is more an issue with Windows, though, and shouldn't be tackled unless it can be consistently reproduced.

**Comment by akeif** [comment]
All right. So I'll stick to this:

1. files created in `/tmp/` should be removed whether the command succeed or fail
1. command `force` should be available and implemented properly
1. command `all-yes` should be available and implemented properly
1. command `destination` should be available and implemented properly

**Comment by akeif** [comment]
I'll take a look and make a plan before coding. I'd like create a merge request for each points but we'll see how this goes.

I'll try to do this tonight but will do Friday or Saturday at worst.

**Comment by akeif** [comment]
**todo** Add `bin/gpm direct-install` command to the [API doc](https://learn.getgrav.org/api/Grav/Console/Gpm.html).

**Comment by akeif** [comment]
**What the command does**

Install
* Grav
* plugin (package)
* theme (package)

from (.zip only?)
* path
* URL

**Comment by akeif** [comment]
**Test packages links**

[Grav latest](https://getgrav.org/download/core/grav/1.1.17)
[Grav core 1.1.17](https://github.com/getgrav/grav/releases/download/1.1.17/grav-v1.1.17.zip)
[Grav update 1.1.17](https://github.com/getgrav/grav/releases/download/1.1.17/grav-update-v1.1.17.zip)
[Antimatter latest](https://getgrav.org/download/themes/antimatter/2.1.1)
[Antimatter 2.1.0 zip](https://github.com/getgrav/grav-theme-antimatter/archive/2.1.0.zip)
[Antimatter 2.1.0 gz](https://github.com/getgrav/grav-theme-antimatter/archive/2.1.0.tar.gz)
[Admin 1.1.17](https://github.com/getgrav/grav/releases/download/1.1.17/grav-admin-v1.1.17.zip)
[Piwik 1.0.2](https://github.com/MichelePalmieri/grav-piwik-plugin/archive/V.1.0.2.tar.gz)

**Comment by akeif** [comment]
@OleVik In the `bin/gpm direct-install` context, what would be the difference between `--yes-all` and `--force`. To me, both would do exactly the same, so one would be an alias.

**Comment by OleVik** [comment]
The aliases of `force` and `yes-all` are `f` and `y`, respectively. `force` will "Force re-fetching the data from remote", whilst `yes-all` "Assumes yes (or best approach) instead of prompting".

Essentially, you can force retrying/refreshing data from the GPM **and/or** pass the generic `yes` to all asked questions, such as "Dependencies are not met, proceed? y|n?". See [InstallCommand.php](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Console/Gpm/InstallCommand.php#L61-L84).

**Comment by akeif** [comment]
Look likes theres two var I need to check out in `system/src/Grav/Console/Gpm/DirectInstallCommand.php`.
`$tmp_zip` and `$tmp_source`.

**Comment by akeif** [comment]
I don't think `direct-install` hit a cache. To what I see on `GPM::downloadPackage` and `GPM::copyPackage` in `DirectInstallCommand.php` it's copied and downloaded each time.
So the `--force` option will not be useful as of now.

Let's see what come out of this.

**Comment by akeif** [comment]
Installing an older Grav package delete the `tmp` folder and fails.

```
di https://github.com/getgrav/grav/releases/download/1.1.17/grav-v1.1.17.zip
#!/usr/bin/env php
Are you sure you want to direct-install https://github.com/getgrav/grav/releases/download/1.1.17/grav-v1.1.17.zip [y|N] y

Preparing to install https://github.com/getgrav/grav/releases/download/1.1.17/grav-v1.1.17.zip
  |- Downloading package...   100%
  |- Extracting package...    ok
  |- Checking destination...  ok
  |- Installing package...  
                                    
  [RuntimeException]                
  Cannot move non-existing folder.  
                                    

direct-install <package-file>
```

**Comment by akeif** [comment]
Following my tests with packages from [this comment](https://github.com/getgrav/grav/issues/1389#issuecomment-290155351) successful installation clean temporary files.
See `Folder::delete` [here](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Console/Gpm/DirectInstallCommand.php#L190) and [here](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Console/Gpm/DirectInstallCommand.php#L207).

**Comment by akeif** [comment]
I can't get my functional test to work. Instantiating a null output when I call the Grav command is giving me trouble.

This doesn't help me: http://stackoverflow.com/questions/18237519/symfony2-console-output-without-outputinterface

I get the error
```
[Symfony\Component\Console\Exception\InvalidArgumentException] The "package" argument does not exist.
```
