### ISSUE TITLE
Support for multi-tenancy.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1390]
Does grav support multi-tenancy out of the box? If not, how involved would it be to make it ready for multi-tenancy?

By multi-tenancy, I mean I have a site that has multiple tenants, and the admin of each tenant can create their own documents, and these documents are accessible only to the users within that tenant. 

Thanks!

**Comment by iandroogmans** [comment]
You might be looking for this: 
[](https://learn.getgrav.org/advanced/multisite-setup)

**Comment by hifall** [comment]
That seems to be what I am looking for. Thanks!
