### ISSUE TITLE
Learn2 menu doesn't automatically scroll when paging to next item that is off-screen

### ISSUE THREAD

**Issue by ViolaGoodacre** [getgrav/grav#1391]
Steps to reproduce in https://learn.getgrav.org:

1) Select the "Web Servers and Hosting" menu item. This is a good menu item to start on because it has a lot of sub-menu items
2) Click the right arrow. This causes the next menu item to be selected and the corresponding page to load.
3) Keep repeating step 2. Eventually, the bottom of the visible browser window is reached.
4) Repeat step 2 a few more times. The selected menu item is out of view.

If the selected menu item is off-screen, I think the menu should automatically scroll to bring it into view.

**Comment by flaviocopes** [comment]
Good idea, but can you open this issue on https://github.com/getgrav/grav-theme-learn2/issues ? I'm closing it here as it's not a Grav core issue

**Comment by ViolaGoodacre** [comment]
Thanks for the quick response. I've raised it as a Learn2 issue, as suggested.
