### ISSUE TITLE
Multisite 404.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1392]
I am trying grav's multisite feature and I am running into a 404 error, on Ubuntu 16.04/PHP 7.

I have set up grav on a machine, and it runs just fine (without multisite in the scene yet). The grav folder is placed under /var/www, so everything is in /var/www/grav/. Entering 12.34.56.78/grav/ in the browser shows the page without any issue.

Then I take the sub-directories approach for multisite. I've follow the instructions in the multisite section in the grav documentation, i.e., create the setup.php file, create a directory called ustc under user/sites, and create all the 4 required folders under user/sites/ustc/.

Then I enter 12.34.56.78/grav/ustc/, and I see the grav-style 404 page: "Error 404 Woops. Looks like this page doesn't exist."

If I enter 12.34.56.78/ustc/, I see Apache's 404: "Not Found The requested URL /ustc/ was not found on this server."

Can anyone tell me what's wrong here, and how I can fix it?

Thanks!

**Comment by flaviocopes** [comment]
You are probably getting a "normal" 404 issue. This https://learn.getgrav.org/troubleshooting/page-not-found will help.

I say "normal" because it could happen also when viewing subpages (e.g. /blog/something) in a normal Grav setup, without multisite.

**Comment by hifall** [comment]
@flaviocopes thanks for your suggestion.

To take a step back: even when grav's content is under /var/www/grav/, I still should access site ustc's content like 12.34.56.78/ustc/, is that correct?

**Comment by flaviocopes** [comment]
Yes, that is correct if you have setup a `ustc` subsite.

**Comment by hifall** [comment]
But here is where I am lost: accessing 12.34.56.78/ustc/ doesn't even trigger calling the setup.php script under /var/www/grav/, and since 12.34.56.78/ustc/ doesn't even refer to grav installation in any way (no global url rewrite), how does Apache know grav?

**Comment by hifall** [comment]
Can someone help please?

**Comment by hifall** [comment]
I have also tried to take the subdomain approach. After creating setup.php with subdomain content, and creating the subdomain folder under /var/www/grav/user/sites/, I enter: ustc.mydomain.com, I see:

<img width="360" alt="screen shot 2017-04-01 at 12 04 35 pm" src="https://cloud.githubusercontent.com/assets/5734293/24575264/6b615f42-16d3-11e7-8605-0046a613198c.png">

If I enter ustc.mydomain.com/grav, I see:

<img width="1218" alt="screen shot 2017-04-01 at 12 06 02 pm" src="https://cloud.githubusercontent.com/assets/5734293/24575270/a183a602-16d3-11e7-919f-208417fb7c58.png">

So, I am not able to make the multisite feature work with either directory or subdomain approach. Some help here would be appreciated!

**Comment by flaviocopes** [comment]
The subfolder approach is simpler, as does not involve multiple domains. 

First, make sure that works before trying the subdomain approach. 

Is the .htaccess file present in the Grav main folder? Did you try all the suggestions listed in https://learn.getgrav.org/troubleshooting/page-not-found ?

**Comment by hifall** [comment]
@flaviocopes,

The .htaccess file is in the Grav main folder, i.e., under /var/www/grav/. And it's been verified to be picked up by Apache.

Also, I have tried all the applicable suggestions listed in the link you gave, when taking the subfolder approach.

**Comment by mahagr** [comment]
Looks like the file is pointing to the root folder, so there's something wrong with the configuration or the code (what is count-views.yaml?)

**Comment by hifall** [comment]
@mahagr I have no idea what count-views.yaml is.

**Comment by flaviocopes** [comment]
Might be a plugin you installed. but not sure which one.

In your setup.php file, subfolder approach, try adding an exit() inside the 

```

if (!$name || !is_dir(ROOT_DIR . "user/{$folder}")) {
    return [];
}
```

part, and also try dumping the $name and $folder variables content. That should help determining what is the issue in finding the subsite folder.

**Comment by hifall** [comment]
I checked the grav install folder, and the count-views.yaml seems to come from a plugin called count-views.

@flaviocopes I am not able to test your suggestion, as setup.php is never called. I have posted a question before: 

"But here is where I am lost: accessing 12.34.56.78/ustc/ doesn't even trigger calling the setup.php script under /var/www/grav/. Since 12.34.56.78/ustc/ doesn't even refer to grav installation in any way (no global url rewrite), how does Apache know grav?"

**Comment by flaviocopes** [comment]
If the main Grav site responds on `12.34.56.78`, `setup.php` should be called. But looking at your screenshot, it seems it responds on `12.34.56.78/grav`, so you should open `12.34.56.78/grav/ustc`

**Comment by hifall** [comment]
Ok, accessing 12.34.56.78/grav/ustc dumps the values:

$name: grav
$folder: sites/grav

**Comment by flaviocopes** [comment]
I think the main problem here is that the subfolder approach works only if the site is on a root domain. 

So, Grav should respond directly on `12.34.56.78`, not on `12.34.56.78/grav`.

**Comment by hifall** [comment]
I don't quite get you, what do you mean by "respond" -- you mean I should place the grav content directly under /var/www/, rather than /var/www/grav/?

**Comment by hifall** [comment]
If possible, I'd like to know if it's a bug of grav, or something incorrect/missing/misleading in grav's documentation, or I am missing something?

Some of the instructions I was given above are somewhat contradictory or unclear.

**Comment by flaviocopes** [comment]
The example subfolder multisite approach expects the Grav site to respond on the root domain name. So, as you are using an IP address instead of a domain name, it should directly respond on 12.34.56.78, and in your specific case, being put in `/var/www/`.

**Comment by hifall** [comment]
First I want to make it clear since I did not in the original post: I failed to run the multisite feature with domain name too with the subdirectory approach, not just IP address. Also, I don't see how using an IP address makes any difference in that case.

Second, as instructed, I move grav's content under /var/www/, and use ustc as the site's name like /var/www/user/sites/ustc, then try to access mydomain.com/ustc/. It gives me:

![Uploading Screen Shot 2017-04-05 at 11.01.19 PM.png…]()

I have tried to use your code to dump the values, but I don't see the values. It gives the same error -- probably the code is not executed because of the exception.

**Comment by hifall** [comment]
As a side note -- this discussion is getting a bit long and taking more time than expected. I think it's relatively easy to repro it on your side, if possible. It'd probably take ~2 minutes. I believe the steps are well described in the original post. You can let me know if anything is unclear.

**Comment by flaviocopes** [comment]
I have tested the subfolder example `setup.php` and it works fine to me.

The count-views error you got is not generated by Grav itself, it's the "Count Views" plugin that tries to write to the `user/data` folder, and there is a permission issue as the web server has not the permissions to write that file (either remove that plugin, or see https://learn.getgrav.org/troubleshooting/permissions to solve the permission problem and make the page load).

**Comment by Okdesk** [comment]
I re-tested the subfolder example, and it did not work for me out of the box.

It turned out the $name variable was "grav" for a url like: http://mydomain.com/grav/ustc, rather than "ustc".

I then changed the following line:

    $name = Folder::shift($path);

to:

    $name = base($path);

Then $name became "ustc", and I was able to access http://mydomain.com/grav/ustc just fine.

So it seems to me that $name is not calculated correctly.

**Comment by Okdesk** [comment]
FYI: I also tried the sub-domain example, and it just worked out of the box.

**Comment by hifall** [comment]
I re-tested the subfolder example, and it did not work for me out of the box.

It turned out the $name variable was "grav" for a url like: http://mydomain.com/grav/ustc, rather than "ustc".

I then changed the following line:

$name = Folder::shift($path);
to:

$name = base($path);
Then $name became "ustc", and I was able to access http://mydomain.com/grav/ustc just fine.

So it seems to me that $name is not calculated correctly.

**Comment by hifall** [comment]
FYI: I also tried the sub-domain example, and it just worked out of the box.

**Comment by flaviocopes** [comment]
That's what I meant with

> The example subfolder multisite approach expects the Grav site to respond on the root domain name. So, as you are using an IP address instead of a domain name, it should directly respond on 12.34.56.78, and in your specific case, being put in /var/www/.

$name was miscalculated if using `http://mydomain.com/grav/ustc`

In this case, it works with Grav listening on  http://mydomain.com, so your subsite is  http://mydomain.com/ustc

**Comment by CarlosMCuadrado** [comment]
I am running a Grav installation on an apache server on MAC OS X High Sierra.
My configuration: Sites / grav / user / siteA

After lookin over and over multisite setup on grav documentation and official blog, what worked for me was unfold the grav installation.
My new config: Sites / user / siteA

I hope this could help anyone. :)
(sorry for my english).

Thanks!
