### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by amtur8** [getgrav/grav#1394]
Hi, 

I would like to present this plugin for review : https://github.com/savoirfairelinux/grav-plugin-content-management

Any comment is welcome.

**Comment by rhukster** [comment]
@amtur8 i think `content-management` is too generic a name for this plugin. In relation to Grav this should be something like:  `grav-plugin-savoirfaire`

**Comment by OleVik** [comment]
Does the plugin do much of the same as Git Sync?  I can't quite tell from the readme what it facilitates, and if its use is specifically restricted to users of Savoir Faire.

**Comment by akeif** [comment]
@amtur8 and I are colleagues at [Savoir-faire Linux](https://github.com/savoirfairelinux). I'll check the plugin with her and see what should be done for it to become useful to the Grav community.

**Comment by akeif** [comment]
@rhukster We're having management issue that will prevent this plugin to be contributed and maintained properly. I would advise closing the issue.

@amtur8 Please close this issue when you are able.
