### ISSUE TITLE
Using pure html in md files.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1395]
Does grav fully support pure html in md files under user/pages/? That is, can arbitrary standard html code be rendered correctly by grav correctly?

The motivation for this question is that we use a jQuery rich text editor plugin to allow user to enter html code for documentation, rather than markdown. The output of the editor is html code. We'd like to stick with pure html if possible.

Thanks!

**Comment by OleVik** [comment]
Yes, because Markdown (Parsedown in this case)  supports all HTML natively. In most cases you can mix them too.
