### ISSUE TITLE
LetEncrypt incompatibility

### ISSUE THREAD

**Issue by theme1256** [getgrav/grav#1398]
I have now had this problem twice, so I thought I would share it.
When using LetsEncrypt on a domain using grav, it is not capable of renewing the certificates because it needs access to the `.well-known` folder.
My solution, so far, has been to change the `.htaccess` line blocking access to files and folders starting with a dot.
The line just after the comment:
```
# Block all direct access to files and folders beginning with a dot
```
I change to:
```
RewriteRule (^|/)\.(?!well-known) - [F]
```
Just posting this here if others need it and hoping that it could be included in a future update.

**Comment by axel-rank** [comment]
I'm using Let's Encrypt on my domains with Grav too.
The automatic certificate renewing did work well until last time about 3 weeks ago.
Next week certificate should be automatic renewed again so I'll wait and see what's happening.
Using Plesk and I'm able to manual renew. This has worked so far without issues.

**Comment by theme1256** [comment]
Might want to add that I am using Certbot to generate and renew my certificates. Running on a Ubuntu 16.04 LTS server with Apache and PHP7.0.
It might just be an incompatibility with Certbot and not LetsEncrypt.

**Comment by flaviocopes** [comment]
Yes, LetsEncrypt needs access on that folder.

The default .htaccess is already providing access to it: https://github.com/getgrav/grav/blob/develop/.htaccess#L65 since 1 year already https://github.com/getgrav/grav/commit/5a1fa1025dd2b698b113952328f5bebaab2b78fd

You might have an older version of that file.

**Comment by flaviocopes** [comment]
Closing, but might be worth adding a line to the Learn site.
