### ISSUE TITLE
Problems with windows commandline

### ISSUE THREAD

**Issue by nickbe** [getgrav/grav#140]
There are currently some issues when using GRAV under a simple windows development environment. GRAV has been installed manually by unzipping the package into a subfolder.

bin\gpm and bin\grav are called with a simple batch like this:

gpm.bat
>@echo off
>SET PHP=C:\DEV\WEB\PHP56\php\php.exe
>%PHP% bin\gpm %1 %2 %3 %4 %5 %6 %7 %8 %9

I can use `gpm install <plugin>` to add a plugin or theme, but when I type `gpm index` all installed plugins and themes are displayed as `(not installed)`

Probably as a result the `gpm update` command also reports `Nothing to update` all the time.

Since I suspect that the upcoming admin plugin will be able to manage the plugins by itself I wouldn't give to much attention to it if this cannot be solved easily. But being able to use the commandline options under windows would also be nice.

**Comment by rhukster** [comment]
Should be resolved in the next release.

**Comment by nickbe** [comment]
Confirmed, I just tried the patch and now it works like a charm. Thanks!!!

**Comment by rhukster** [comment]
BTW I put the path to PHP in my windows environment variables for the PATH, and I am able to run `bin/grav` and `bin/gpm` without any reference to PHP, it just works fine.  Even the `/` is fine when i use git bash.

**Comment by nickbe** [comment]
Yep. It's working without problems here too. Right now (and of course beside many other features) the fact that I can develop with GRAV and just use PHP -S is just phaenomenal. GRAV is really well designed working is ... well fun. And that's the best feature so far.

**Comment by rhukster** [comment]
Thanks nick!
