### ISSUE TITLE
direct-install - notice of array to string conversion

### ISSUE THREAD

**Issue by iusvar** [getgrav/grav#1405]
Using `bin/gpm direct-install`
when the dependencies in a blueprint contain a github repository
(as in the first example shown in [learn.getgrav.org](https://learn.getgrav.org/forms/blueprints/example-plugin-blueprint) )
I get a notice of array to string conversion to the line [158](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Console/Gpm/DirectInstallCommand.php#L158) of file `DirectInstallCommand.php`

I tried on the develop branch

**Comment by rhukster** [comment]
Did you try to install a blueprint???

**Comment by iusvar** [comment]
I tried to install a plugin, exactly my snappygrav.
[This is the blueprints](https://github.com/iusvar/grav-plugin-snappygrav/blob/master/blueprints.yaml) that concerns him.

**Comment by flaviocopes** [comment]
Thanks for reporting!

**Comment by iusvar** [comment]
Thanks to you
