### ISSUE TITLE
Performance issues without server cache

### ISSUE THREAD

**Issue by floqqi** [getgrav/grav#1406]
Using the newest version of grav (with admin) I'm experiencing very bad performance when the server cache is not available. The first requests needs up to five seconds after clearing the server cache (or cold start after a few hours of no request). I've enabled almost any caching option available in the backend. My grav installation is hosted at a shared hoster where I've never encountered such issues until I used grav. Is there anything I can configure or trace where the bottleneck is?

Edit: I currently have a very very small blog with just five sites. So the issue is not the number of pages / size.

**Comment by rhukster** [comment]
It's hard to tell without looking. Could just be a plugin.  Try disabling them one by one to see if any one of them is significantly impacting.  Might be some twig logic you have. Or might just be a slow hosting setup.  Php 5.5 for example or no Ssd drives. 

If you like you can zip up your site and send me a link to download it and I can take a look also.

**Comment by floqqi** [comment]
I'm using PHP 7.1, this should not be the problem.

Thank you for the tip with disabling the plugins one by one. Seems like the official [pagination-plugin](https://github.com/getgrav/grav-plugin-pagination) was my issue. If I disable the plugin the response time for the index site is around 1.5 seconds without server cache. This is okay for me.
