### ISSUE TITLE
SVG images missing from `page.media.images`

### ISSUE THREAD

**Issue by tfeldmann** [getgrav/grav#1407]
Grav v1.2.0 - Admin v1.3.1

The SVG images added to page media are not accessible in the `page.media.images` array (twig), only in `page.media`.

**Comment by flaviocopes** [comment]
The default configuration considers a svg as a vector file: https://github.com/getgrav/grav/blob/develop/system/config/media.yaml#L33

If you copy that file to `user/config/media.yaml`, you can change the SVG type to `image` and it will be listed under `page.media.images`. Currently it's listed under `page.media.files`.

Worth discussing if it should belong to the image type by default.

**Comment by flaviocopes** [comment]
> Worth discussing if it should belong to the image type by default.

Actually SVG cannot have most of the image functions applied to them, so that would not make much sense

**Comment by rhukster** [comment]
I was going to say, it's no in images for a good reason.

**Comment by tfeldmann** [comment]
So I guess it would be cool if the image functions could handle svg ;-)

**Comment by ganar** [comment]
@tfeldmann you can get SVG from ` page.media.files`: it works like a charm
