### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by barryanders** [getgrav/grav#1409]
https://github.com/barryanders/grav-plugin-blackhole

I put this together a while back. I let it sit to allow the bugs to get worked out. I also improved at PHP over the time it sat and was able to come back and clean up some of it. It's useful for exporting pages to static HTML. Since it has been months, it's possible that my method for collecting the pages may be outdated. Either way, it works and the destination can be set either in the admin plugin or in the command line. Let me know if I need to do anything else.

Thanks

**Comment by rhukster** [comment]
Will add this soon.

**Comment by rhukster** [comment]
Added to GPM for next 'build'
