### ISSUE TITLE
Link is Wrong on Grav Site for 1.2.0

### ISSUE THREAD

**Issue by JREAM** [getgrav/grav#1410]
Under the Quick Installation the version is not 1.2.0 @ https://getgrav.org/downloads

**Comment by flaviocopes** [comment]
@rhukster is it the cache that needs a refresh?

**Comment by rhukster** [comment]
<img width="1099" alt="2017-04-07 at 2 12 pm" src="https://cloud.githubusercontent.com/assets/1084697/24818096/577cdd44-1b9c-11e7-8740-6831ddd5cfd4.png">

It is the 1.2.0 version for me.  Unless this is somewhere else??

**Comment by flaviocopes** [comment]
Looks fixed now! Was pointing to 1.1.17 when I checked, while the top links were correct, was a cached part of the page, most probably.
