### ISSUE TITLE
Unable to access fonts.googleapis.com in China.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1412]
Hi,

Not sure this is a concern of yours... but I notice that Grav needs to reference fonts.googleapis.com for  assets, and users in China will fail to have access to these, as google sites are blocked in China. This results in very slow page loads when Grav is accessed from China.

Thanks.

**Comment by mikecrittenden** [comment]
Are you talking about inside the admin UI? If so, go to /admin/plugins/admin and disable "Use Google Fonts". which will make it use Helvetica instead.

**Comment by hifall** [comment]
No, I am not using the admin UI. Just talking about the non-admin UI part of Grav, that is, the Grav pages.

**Comment by rhukster** [comment]
Well it's not Grav per say, it's the theme.  Antimatter is the default theme, and uses Google fonts.  Just change the theme to something else, or change the font.
