### ISSUE TITLE
RTFM skeleton + multisite runtime exception 400.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1413]
First of all, I am able to get default grav working fine with multisite and subdomain features. This issue is about making the RTFM skeleton (which uses learn2 theme) work with multisite and subdomain. I am currently seeing some error when trying to do so: Template "default.html.twig" is not defined.

Steps I take:
1 download the RTFM skeleton from: https://getgrav.org/downloads/skeletons;
2 install it on my web server;
3 check the skeleton and find it works fine (trying to access https://www.domain.com/grav/ displays the page in learn2 theme);
4 set up multisite for subdomain, following: https://learn.getgrav.org/advanced/multisite-setup; the folder structure is: /var/www/grav/user/sites/subdomain.domain.com/themes/learn2;
5 trying to access https://subdomain.domain.com/grav/ gives:
<img width="1216" alt="screen shot 2017-04-10 at 4 30 14 pm" src="https://cloud.githubusercontent.com/assets/5734293/24853112/8adc45d6-1e0c-11e7-9cbe-676f04c55542.png">

Note if I change system.yaml to use antimatter theme, it's able to display https://subdomain.domain.com/grav/ correctly. But not for learn2.

**Comment by hifall** [comment]
Okay, just found that RTFM/learn2 doesn't have default.html.twig, while there is a default.md in 01.home. The absence of default.html.twig causes this issue.

**Comment by rhukster** [comment]
Yes, Learn2 is a very specific theme intended for documentation only.  It doesn't provide a default.html.twig, so `default.md` files are not going to work without some customization.
