### ISSUE TITLE
Issue accessing Grav root without trailing /.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1415]
This happens in multisite + subdomain scenario.

After I successfully set up multisite with the subdomain approach, I now have a site folder under: /var/www/grav/user/sites/subdomain.domain.com.

Then when I try to access: http://subdomain.domain.com/grav/, everything works fine, and the page content comes out of the site folder. Let's call this case 1.

However, when I try to access: http://subdomain.domain.com/grav, it redirects to: http://www.domain.com/grav/, and the page content seems coming from /var/www/grav/user/pages. Let's call this case 2.

Note that the only difference between the way we access in case 1 and 2 is there is no trailing slash in case 2.

This seems to fail with the grav root only. Accessing a URL like http://subdomain.domain.com/grav/intro seems to work. That is, it fetches the content from the site folder correctly.

Now, how can I make a url like http://subdomain.domain.com/grav work correctly?

**Comment by rhukster** [comment]
This sounds like something related to your .htaccess / vhost config?

**Comment by hifall** [comment]
I thought so at first. Then I checked my .htaccess at /var/www, /etc/apache/apache2.conf, and /etc/apache/sites-enabled/*, but did not find anything suspicious. I also tried to completely remove /var/www/.htaccess, and the issue persists.

I am running on a full-fledged VPS, not vhost.

**Comment by flaviocopes** [comment]
Could this be a side effect of having `system.pages.redirect_trailing_slash` enabled?

**Comment by hifall** [comment]
@flaviocopes I just set redirect_trailing_slash: true in system.yaml, but the problem persists.

**Comment by flaviocopes** [comment]
In your `setup.php` file, check what are the values of the variables in the various scenarios, adding an 

```php
var_dump($environment);
var_dump($folder);
exit();
```

into it. That might add some light into why this happens

**Comment by hifall** [comment]
Ok, just dumped the values. And here is what I got.

Navigating to: https://subdomain.domain.com/grav/ gives:
$environment: subdomain.domain.com
$folder: sites/subdomain.domain.com

Navigating to: https://subdomain.domain.com/grav gives:
$environment: www.domain.com
$folder: sites/www.domain.com

**Comment by flaviocopes** [comment]
Looks something wrong in determining the value of `$environment`, inside that file.

**Comment by hifall** [comment]
Yes, that's what I think too.

**Comment by hifall** [comment]
So do you think this will be fixed soon? If not, is there a quick workaround? We'd like to deploy grav into a production environment soon, and hope to smooth away the edges before we do.

Thanks.

**Comment by flaviocopes** [comment]
I was thinking that `/grav` was a page, but you actually seem to have installed Grav in a subfolder, inside a subdomain. 

The default multisite configuration assumes your Grav site runs on

`https://subdomain.domain.com`

not 

`https://subdomain.domain.com/grav`

**Comment by hifall** [comment]
From Grav's documentation, it doesn't seem to dictate that Grav's content be installed directly under webroot, for multisite.

But anyways.

So you are suggesting placing Grav's content directly under webroot would provide more info for debugging?

**Comment by flaviocopes** [comment]
If you have Grav running on `yourdomain.com`, the [basic approach](https://learn.getgrav.org/advanced/multisite-setup#quickstart-for-beginners) is to have it run

- `site1.yourdomain.com`
- `site2.yourdomain.com`
- `site3.yourdomain.com`

that's what the example setup.php is thought for. 

So make sure you install it in the root domain, and if still gives issues, it's something related to the server configuration not returning the correct host name for some reason.

**Comment by rhukster** [comment]
Closing to due to inactivity
