### ISSUE TITLE
Setting a style tag in an image

### ISSUE THREAD

**Issue by ganar** [getgrav/grav#1417]
I need to be able to add to  

`{{ p.media.images|first.quality(60).cropZoom(600,450).html(page.title, page.title, 'nd-corner-image gnd-corner-image-center gnd-corner-image-top', ) }}`

this style within the `img` tag.

`style="border: 0;display: block;height: auto;width: 100%;max-width: 900px;"`

Is there a way to do this in GravCMS?

**Comment by flaviocopes** [comment]
There is no option to set the `style` attribute.

You could add those CSS statements to a class, and assign that class (using `!important` if for some reason you cannot use the CSS selector hierarchy precedence)

**Comment by ganar** [comment]
@flaviocopes I was hopping that since the `img` tag can be set with a whole number of additional information, I would be able to add this information to the tag.

I need this to be a style because it is for an HTML mail template, and some styles must be inlined.
