### ISSUE TITLE
Simplesearch returns no result with multisite.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1418]
This happens with multisite + subdomain + Simplesearch plugin (msS).

After grav is set up with msS, I enter a keyword Grav in the search box, like this:
<img width="1088" alt="screen shot 2017-04-11 at 12 29 33 pm" src="https://cloud.githubusercontent.com/assets/5734293/24892936/b4e26044-1eb2-11e7-9881-a48af981a3aa.png">

Then it returns nothing, although it should return at least the home page. See:
<img width="1108" alt="screen shot 2017-04-11 at 12 31 23 pm" src="https://cloud.githubusercontent.com/assets/5734293/24892952/cdee4102-1eb2-11e7-9c2f-6680ba43b14a.png">

**Comment by flaviocopes** [comment]
Question: did you test if on the same site, not in a multisite environment, search works? Might simply be a Simplesearch configuration issue, where it searches in a specific taxonomy (by default `category: blog`, but your pages do not adhere to that taxonomy?

**Comment by rhukster** [comment]
Closing to due to inactivity
