### ISSUE TITLE
Redirects & Routes broken in latest release

### ISSUE THREAD

**Issue by immersegfx** [getgrav/grav#1420]
It appears that version 1.2.1 introduced a bug in \Grav\Common\Pages\Pages https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Pages.php#L399

$route = $config->get("site.routes.{$route}"); overrides the $route with null which is passed to the $source_url variable that can't be matched.

**Comment by rhukster** [comment]
Argghhh.. Good catch. This slipped through when i reviewed the PR. Can you please test my fix (linked above)

**Comment by immersegfx** [comment]
Looks good to me, successfully tested on my site.  thanks for the quick patch.
