### ISSUE TITLE
Text limit

### ISSUE THREAD

**Issue by butchewing** [getgrav/grav#1423]
Is there a text or filesize limit? I’m getting this when I put “too much” text on a page:

```
/system/src/Grav/Common/Helpers/Truncator.php:157\nPHP message: PHP 233. Grav\\Common\\Helpers\\Truncator::removeProceedingNodes()
```

**Comment by rhukster** [comment]
Not really, usually that error is caused by invalid HTML that the Truncator class has trouble handling.  Can you provide a copy of your page?

**Comment by butchewing** [comment]
Here is it. Of course, I added .txt in order to upload it here.

[default.md.txt](https://github.com/getgrav/grav/files/917830/default.md.txt)

**Comment by rhukster** [comment]
Might just be that your `<br>` tags should actually be `<br />` for xhtml compatibility. Try that. 

This error is probably coming from a `summary()` call.  it's trying to find the right spot without breaking on a tag.  You can also try putting: `===` somewhere in your list to force a summary break at a point of your choosing.

**Comment by butchewing** [comment]
Yep, I added `===` to the top of the page and it worked.
