### ISSUE TITLE
Multi-site: How do I access stuff placed in a folder in the user/custom_folder/ namespace?

### ISSUE THREAD

**Issue by aligajani** [getgrav/grav#1424]
I have a multi site setup but its actually one site being accessed from different domains presenting the same looking site with slightly different content. I wanted to place common vars in the user/custom_folder namespace and access them.  Many thanks for your help in advance.

**Comment by rhukster** [comment]
Please provide details of how to replicate this EXACTLY.  Please provide a sample multisite setup which mimics your setup. Include everything that will enable us to test and replicate this.  Cheers.
