### ISSUE TITLE
Page parent automatically changes when edit plugin admin

### ISSUE THREAD

**Issue by STnetwork** [getgrav/grav#1425]
Hi,

I have the last version of Grav (1.2.2) and Grav Admin Plugin (1.3.3), and when I edit a page on the admin plugin, the parent change automatically on root.

Thanks for your help

**Comment by rhukster** [comment]
I am unable to replicate this. What is the parent before and what does it get changed to??

**Comment by STnetwork** [comment]
I talk about this parent in a page : 
<a href="http://www.bild.me/bild.php?file=7228091parentgrav.PNG" target="_blank"><img src="http://s1.bild.me/bilder/110417/thumb_7228091parentgrav.PNG" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

when I just want edit the page content, the parent change like this : 

<a href="http://www.bild.me/bild.php?file=7988864parentgrav2.PNG" target="_blank"><img src="http://s1.bild.me/bilder/110417/thumb_7988864parentgrav2.PNG" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

so the link of the page change automatically too, I have to change the parent every time I change the content page.

**Comment by rhukster** [comment]
Images are broken :(

**Comment by STnetwork** [comment]
It's ok now !

**Comment by rhukster** [comment]
So you are saying editing in the content tab causes the parent to reset?

**Comment by STnetwork** [comment]
yes !

**Comment by OleVik** [comment]
This should be fixed in develop: [Admin-plugin issue 1059](https://github.com/getgrav/grav-plugin-admin/issues/1059).

**Comment by rhukster** [comment]
This fix has already been release in Admin v1.3.3 released yesterday.  I'm unable to replicate this in current version.  Please make sure you are on latest.

**Comment by STnetwork** [comment]
Ok it's fixed for me too, I had to reinstall admin plugin !

Thanks
