### ISSUE TITLE
Using grav for both knowledge base and manual.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1426]
We have 2 types of documentation in our own system: one is knowledge base (KB) type, and the other one is manual type. The KB-typed documents serve as a more "casual" way to learn about our business, while the manual-typed documents are supposed to be a precise description of how our products work.

As such, we will use 2 themes: knowledge base and learn2. The knowledge base themes is used for KB, and learn2 is used for manual.

There are 2 separate  endpoints for the 2 types of documentation: mydomain.com/help_center/ is for KB, while mydomain.com/manual/ is for manual. When user navigates to mydomain.com/help_center/, he will see the KB, and will see manual for mydomain.com/manual/.

Now my question is: how do I use grav for both types? The obvious approach is to keep a copy of grav under /help_center/, and another copy under /manual/, so that different endpoints invoke different grav copies. Note that we've already taken the subdomain approach to serve documents for our tenants, so we can't simply switch to the subdirectory approach for this purpose.

Is there a better way to achieve this? Can I just use 1 copy of grav to serve both endpoints in different themes?

Thanks!

**Comment by flaviocopes** [comment]
This is what you need: https://github.com/sommerregen/grav-plugin-themer

Allows multiple themes on a single site
