### ISSUE TITLE
Broken tag link in blogitem templates?

### ISSUE THREAD

**Issue by Salvatos** [getgrav/grav#1430]
There seems to a problem that I'm not sure stems from specific themes or a configuration issue, but I can reproduce it under Antimatter and Afterburner2, and it's also visible on the latter's demo and not the former's.

**Issue:** The tag links as set in blog_item.html.twig point to the site root (e.g. https://demo.getgrav.org/tag:photography) instead of the proper location (e.g. https://demo.getgrav.org/afterburner2-skeleton/tag:photography). The sidebar links point to the correct location, which points to the issue coming from blog_item specifically.

Link in Afterburner2's blog_item:
`<a href="{{ blog.url }}/tag{{ config.system.param_sep }}{{ tag }}">{{ tag }}</a>`
Link in Antimatter's blog_item:
`<a href="{{ blog.url|rtrim('/') }}/tag{{ config.system.param_sep }}{{ tag }}" class="p-category">{{ tag }}</a>`
Link in taxonomylist plugin:
`<a class="{{ active }}" href="{{ base_url }}/{{ taxonomy }}{{ config.system.param_sep }}{{ tax }}">{{ tax }}</a>`

**Use case:** I am developing my site at localhost/grav. Using either variant of `{{ blog.url }}` makes the blog_item link point to localhost/tag:test (doesn't work) when viewed on the home page, or to localhost/grav/tag:test (works) when viewed from a blog post. Since the Antimatter demo doesn't seem to share this bug, I wonder if there is something wrong with how blog.url is generated or something about URL rewriting rather than with the themes.

**Workaround:** For now, using `{{ base_url }}` instead like the taxonomylist plugin produces a valid link in all locations for me.

**Comment by rhukster** [comment]
This sounds like a theme-specific question/issue? Not really a core Grav issue.  Antimatter probably just has more robust/updated Twig logic to handle all the cases as it's the default included there.  You can probably port the twig template in question to Afterburner2 as it was originally based on Antimatter in the first place.

**Comment by Salvatos** [comment]
Where would that twig logic reside? Just using Antimatter's link doesn't fix it.

**Comment by flaviocopes** [comment]
On which demo can you reproduce this? I cannot on the Blog Site (https://demo.getgrav.org/blog-skeleton/blog/sunshine-in-the-hills) which uses Antimatter, and I cannot replicate it locally.

**Comment by Salvatos** [comment]
Afterburner2's: https://demo.getgrav.org/afterburner2-skeleton/
