### ISSUE TITLE
resize of remote image doesn't seem to work

### ISSUE THREAD

**Issue by walkloud** [getgrav/grav#1431]
I am not sure if this is a bug, or missing feature.  I was trying to cropResize a remote image, e.g.
```
![](https://www.nasa.gov/sites/default/files/thumbnails/image/juice_artist-impression.jpg?cropResize=300,300)
```
but the cropResize had NO effect on the remote image size.  Conversely, the following manual entry in the same grav page DOES work
```
<img src="https://www.nasa.gov/sites/default/files/thumbnails/image/juice_artist-impression.jpg" width="300" />
```
I guess there is a smarter way to resize the image with the `<img />` call, but really, I was hoping there was a nice way to use the grav image linking `![]()` method to resize.  Is this possible?  If not, is it easy to add?  Seems like there is some well known PHP ways to do this, but I am inexperienced enough with PHP and GRAV to know where I would make those changes.

**Comment by rhukster** [comment]
Cropping only works for local 'page' media, not remote images.  Your `width="300"` example is not cropping its just setting the size of the IMG element to width of 300px. This is not a bug, it's a limitation/feature.
