### ISSUE TITLE
RTFM skeleton search broken?

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1432]
Searching from the left sidebar from the RTFM skeleton (downloaded from: https://getgrav.org/downloads/skeletons) doesn't work.

Repro:
1 perform a clean install of the skeleton on the server;
2 enter some text in the search box on the left sidebar, and  hit Enter;
3 the contents on the page never change (to show the expected search results).

**Comment by rhukster** [comment]
Please open this issue in RTFM Skeleton project.  Not core Grav.  Cheers.

**Comment by hifall** [comment]
Done. https://github.com/getgrav/grav-skeleton-rtfm-site/issues/8
