### ISSUE TITLE
A theme for API?

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1433]
Any plan for an API theme? I think it'd be essential for IT/Software companies.

Maybe something like: https://developer.gitbook.com/?q=#

Thanks!

**Comment by rhukster** [comment]
No plans for an API theme other than our existing learn-type documentation themes.  The current API site is generated by Sami, and is using the default Sami theme.

**Comment by rhukster** [comment]
BTW, the only thing in that theme you linked that is 'special' is the 2 col layout in the content. That could easily be added to learn2.

**Comment by hifall** [comment]
Well, actually the gitbook API theme seems to provide some API-specific mechanisms, including multi-programming language support. For example, one can view a code snippet in JS/Java/PHP at his own choice.

**Comment by rhukster** [comment]
We just use a tabs shortcode to produce similar on learn.getgrav.org

**Comment by hifall** [comment]
BTW, your current Sami-generated API site looks awesome too!

**Comment by rhukster** [comment]
thanks :)
