### ISSUE TITLE
Custom Redirect not forwarding query parameters

### ISSUE THREAD

**Issue by CoDanny** [getgrav/grav#1434]
I'm trying to create the following redirect:

```
http://www.astroprint.dev/design/uploaded?param=hello -> http://cloud.astroprint.dev/design/uploaded?param=hello
```

It ignores the query paramters and redirects to http://cloud.astroprint.dev/design/uploaded

```
redirects
  'design/uploaded?(.*)': 'https://cloud.astroprint.com/design/uploaded?$1'
```

Is this not supported ?

**Comment by flaviocopes** [comment]
Could this be related? https://github.com/getgrav/grav/issues/676

**Comment by CoDanny** [comment]
I saw that but I don't think so. The route /design doesn't exist on my Grav installation

**Comment by flaviocopes** [comment]
I checked and this is not going to work because Grav considers the route, not the query string part. You should add this to a webserver-level configuration instead.

**Comment by CoDanny** [comment]
I have done that but this greatly reduces the usefulness of custom redirects for porting an existing site to GRAV. I would ask that you add this as a feature in the roadmap

**Comment by newmedicine** [comment]
+1, wish this would worm
