### ISSUE TITLE
Custom Routes just redirect (not aliases)

### ISSUE THREAD

**Issue by CoDanny** [getgrav/grav#1435]
The following routes configured on my Grav server:
```
routes:
  /p/astrobox: /products/p/astrobox-gateway
  /p/cloud-slicer: /products/p/astroprint-cloud
  /3d-printer-manufacturers: /solutions/p/3d-printer-manufacturers
```
Just redirect one route the other. In the documentation, routes are explained as aliases, which means the browser won't be redirected but it will show the target page instead on the url provided

**Comment by rhukster** [comment]
This works for me when configured in `site.yaml`. It's not redirecting.  Are you sure you don't have a conflicting entry under redirects?  That would be tackled before the alias.

**Comment by CoDanny** [comment]
Here's my config. It doesn't look like it would...

```
redirects:
  /kickstarter: 'https://www.kickstarter.com/projects/306530051/astroprinttm-wireless-3d-printing-software'
  /account/: 'https://cloud.astroprint.com/account/'
  /js/min/lib/astroprint.import.js: 'https://cloud.astroprint.com/js/min/lib/astroprint.import.js'
  /p/team: 'https://cloud.astroprint.com/p/team'
  /stats: 'https://cloud.astroprint.com/stats'
routes:
  /p/astrobox: /products/p/astrobox-gateway
  /p/cloud-slicer: /products/p/astroprint-cloud
  /3d-printer-manufacturers: /solutions/p/3d-printer-manufacturers
```

My file is at `/user/config/site.yaml`. don't know if that makes a difference

**Comment by rhukster** [comment]
Even with your custom routes it just works for me :( . I can't reproduce this. Are you up to date running all the latest?  Do you have any redirects setup in your pages?

**Comment by CoDanny** [comment]
Ugh! I just noticed that does actually work on my production environment. 

However, it does not work on my development environment (localhost), which uses the file from here: `/user/www.astroprint.dev/config/site.yaml` (www.astroprint.dev is pointing to localhost)

the file has the same routes and redirects

**Comment by flaviocopes** [comment]
Cannot replicate it locally. Could be htaccess or other server-level redirects interfering?
