### ISSUE TITLE
Accented characters in URI does not work

### ISSUE THREAD

**Issue by molnarelodbalazs** [getgrav/grav#1437]
Hello there!

I have an URL: http://domain.com/search/query:függvény
The grav config gives me the variable with wrong encoding.  :-(
https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Uri.php#L448

What can I do?

**Comment by OleVik** [comment]
What is the specific error thrown by Uri.php?

**Comment by flaviocopes** [comment]
You should see this

![schermata 2017-04-20 alle 16 49 58](https://cloud.githubusercontent.com/assets/11783388/25236905/6d704530-25e9-11e7-8b49-e91aed66c1e7.png)

what do you see, instead?

**Comment by molnarelodbalazs** [comment]
I see: `f�ggv�ny` as in this variable: $config = Grav::instance()['config'];
> my header encoding is set to utf-8

**Comment by rhukster** [comment]
Seems to work for me also:

![2017-04-20 at 4 35 pm](https://cloud.githubusercontent.com/assets/1084697/25255370/777ccee2-25e7-11e7-89c6-404afa6a6c0a.jpg)

**Comment by flaviocopes** [comment]
What is the page encoding, sent to the browser? (type `document.characterSet` in the browser developer tools console)

**Comment by molnarelodbalazs** [comment]
Hello!

document.characterSet `"UTF-8"`

![image](https://cloud.githubusercontent.com/assets/26296798/25338143/7d477d76-28fe-11e7-88ec-1ea3aee09e71.png)

I can't find it out what is the problem. The reason why i wrote it here is I investigated my parameter 'till this line.

Thanks for your help!
Előd

**Comment by flaviocopes** [comment]
Strange then, the charset is correct. Is this happening with Chrome only, or also on other browsers as well?

**Comment by flaviocopes** [comment]
Can you also try on a separate device, a phone maybe?

**Comment by molnarelodbalazs** [comment]
It "works" like this in different browsers.
Here's what i get on browserstack
![image](https://cloud.githubusercontent.com/assets/26296798/25428086/04a5bb6c-2a75-11e7-9266-9f9f83c7c1ee.png)

**Comment by flaviocopes** [comment]
Can you PM me your user/ folder on Slack, so I can try replicating the problem with your same site setup?

**Comment by flaviocopes** [comment]
I can't replicate. 

![screen shot 2017-04-27 at 18 20 13](https://cloud.githubusercontent.com/assets/11783388/25493406/57f8a318-2b76-11e7-8725-22cf37309ffc.png)

If you make the subdomain public I can try replicating with my browser (it's not accessible at this moment)
