### ISSUE TITLE
[Suggestion] TinyPNG plugin

### ISSUE THREAD

**Issue by MrMacStripe** [getgrav/grav#1439]
I'm constantly trying to optimize my websites. Which method gets used for the image caching and the .derivatives function at the moment? Is there a way to hook this up with the awesome tinypng API?

**Comment by rhukster** [comment]
We already have a similar plugin: https://github.com/getgrav/grav-plugin-optimus

This uses the Optimus service, but you could use this plugin as a basis for a TinyPNG one.

**Comment by iainsgillis** [comment]
@MrMacStripe I haven't used the plugin myself, but @ladotech released a plugin to do this a couple of years ago. See https://github.com/ladotech/grav-plugin-tinypng 

@rhukster Is a community plugin on the Grav repository sufficient for closing an issue such as this one?

Cheers,
.ig

**Comment by rhukster** [comment]
Yah! Good solution.
