### ISSUE TITLE
Wrong results using page.evaluate

### ISSUE THREAD

**Issue by ganar** [getgrav/grav#1441]
I'm trying to get this piece of *twig* code to work in my blog template:

    {% set collection = "" %}
    {% set collection = page.evaluate([{ '@page.children':'/contenidos', '@taxonomy.tag':'apple' }]) %}
	{% set collection = collection.order('date','desc') %}

	{% for child in collection %}
	      {% include 'partials/blog_item.html.twig' with {'blog':page, 'page':child, 'truncate':true} %}
	{% endfor %}

The problem is that I can either get ` '@page.children':'/contenidos'` or `'@taxonomy.tag':'apple' ` to work individually but not both (since I want to filter by the tag `apple` on all the children pages below `/contenidos`. 

What am I missing here? I'm trying to reproduce the *twig* example at the end of [docs/page collections](https://learn.getgrav.org/content/collections)

**Comment by flaviocopes** [comment]
Try doing a `{{dump(collection|length)}}` at each step, and you can see how many items there are in the collection. The construct you're using is called a *Complex Collection* (https://learn.getgrav.org/content/collections#complex-collections) and will result in the _sum_ of the 2 items, not an *and* join.

**Comment by flaviocopes** [comment]
(p.s. I tested it locally and it works)

**Comment by ganar** [comment]
Thanks for your answer @flaviocopes: I understand from your answer that this means that the result is not a subgroup of all the pages within the children of `/contenidos` that have the tag `apple`.

how would you do that in a template? `find`, maybe?

**Comment by flaviocopes** [comment]
mm not aware of a way to do it, except iterate over a collection with just one filter, and then doing a check if the other condition is satisfied

**Comment by ganar** [comment]
@flaviocopes 

I found  a way of doing it, like so. but still need help adding the pages to the collection for pagination purposes:


	{% for child in page.find('/contenidos').children.order('date', 'desc').published() %}
		{% for label in child.taxonomy.tag %}
			{% if label == temporada_actual_tag %}
				{% include 'partials/blog_item.html.twig' with {'blog':page, 'page':child, 'truncate':true} %}
			{% endif %}
		{% endfor %}
	{% endfor %}

I need to do `collection.addPage(child)` inside the `if`: How do I do that?

**Comment by tboulogne** [comment]
Hello,

I think it's same than #1183 :-(. Today i get this case with :
```
$data = $this->grav['page']->evaluate(['@page.descendants' => $route ])->ofType('mycart_detail');
```

I got the collection without any pagination : 
```
dump($data->params) => null
```

And i did not find how to reinject parameters into a collection from evaluate... *setParams* does not work :-(.

Any tips ?

Thanks for help :-)

**Comment by ganar** [comment]
@tboulogne I have not been able to solve this. I'm keeping my results on this content short, and forfeiting pagination until I find a way of adding the results of the `find` to the collection.

**Comment by tboulogne** [comment]
@ganar I try to find a way to filter this before page processed.

**Comment by tboulogne** [comment]
@ganar i get something working 👍 

1/ in *onPageInitialized*
```
  $this->enable([
            'onTwigSiteVariables' => ['onTwigSiteVariables', 0],
            'onCollectionProcessed'=>['onCollectionProcessed', 0],
        ]);
```

2/ in *onPagesInitialized* i make first part of filter (you could put this part  in .md file directly an omit this part)
```
if($this->grav['page']->template() == 'mycart_category'){
             $page =  $this->grav['page'];
             $page->header()->content['items'] = ['0'=>'@self.descendants'];  
        }
```

3/ i create the * onCollectionProcessed* to make the second part of my filter.
```
public function onCollectionProcessed(Event $event)
    {
        /** @var Collection $collection */
        if($this->grav['page']->template() == 'mycart_category'){
          $collection = $event['collection'];
          $collection->setParams(['limit'=>$this->page_limit]); //pagination need this
          $collection->ofType('mycart_detail');
        }

    }
```
hope it could help.

**Comment by rhukster** [comment]
This is not documented, but you can actually call `page.collection()` manually and pass in an array that mimics the one in the header
for example:

```
{% set options = { items: {'@page.children': '/my/blog'}, 'limit': 5, 'order': {'by': 'date', 'dir': 'desc'}, 'pagination': true } %}
{% set collection = page.collection(options) %}

<ul>
{% for p in collection %}
<li>{{ p.title }}</li>
{% endfor %}
</ul>
```

This actually performs the exact same logic as the header-set collections when you call `page.collection()`

**Comment by tboulogne** [comment]
@rhukster thanks for the tip :-) !

**Comment by rhukster** [comment]
Just added this to the docs too, so now it IS documented :)

**Comment by ganar** [comment]
@rhukster How about adding pages to the collection during the `find `, in order to get the pagination to work properly? I'm sorry @tboulogne y could not understand your example

	{% for child in page.find('/contenidos').children.order('date', 'desc').published() %}
		{% for label in child.taxonomy.tag %}
			{% if label == temporada_actual_tag %}
				{% include 'partials/blog_item.html.twig' with {'blog':page, 'page':child, 'truncate':true} %}
			{% endif %}
		{% endfor %}
	{% endfor %}

I need to do `collection.addPage(child)` inside the `if`: How do I do that? I have not been able to make it work, had to stop using pagination

**Comment by tboulogne** [comment]
@ganar my example is in case you wrote a plugin. You could modify the collection in php. Did you see @rhukster example ?
```
{% set options = { items: {'@page.children': '/contenidos'}, 'limit': 5, 'order': {'by': 'date', 'dir': 'desc'}, 'pagination': true } %}
{% set collection = page.collection(options) %}
{% for child in collection %}
  {% if child.taxonomy.tag == temporada_actual_tag %}
    {% include 'partials/blog_item.html.twig' with {'blog':page, 'page':child, 'truncate':true} %}
  {% endif %}
{% endfor %}
```
Should work. Not tested
