### ISSUE TITLE
Markdown links don't pass HTTP query strings

### ISSUE THREAD

**Issue by dustinkerstein** [getgrav/grav#1444]
This markdown link:

`[Test](https://bugs.chromium.org/p/chromium/issues/detail?id=573565)`

Results in linking to https://bugs.chromium.org/p/chromium/issues/detail rather than https://bugs.chromium.org/p/chromium/issues/detail?id=57356

This should pass the query string, correct?

Thanks,
Dustin

**Comment by axel-rank** [comment]
Reminds me on:
https://github.com/getgrav/grav/issues/1399

**Comment by dustinkerstein** [comment]
Yeah, html links like this:

`<a href="https://bugs.chromium.org/p/chromium/issues/detail?id=573565" target="_blank">Test</a>`

In the same markdown file works correctly.

**Comment by OleVik** [comment]
See this [Docs-page](https://learn.getgrav.org/content/linking#pass-through-of-non-supported-attributes): Essentially, you want to include `&noprocess` in the parameters to make sure they are not processed by Grav.

**Comment by dustinkerstein** [comment]
Ah, got it. Thanks!
