### ISSUE TITLE
500 Error when trying to open non renamed page

### ISSUE THREAD

**Issue by CoDanny** [getgrav/grav#1446]
In our Grav installation (available upon request), we had a page /products/p/astrobox which was moved to /products/p/astrobox-gateway.

Google Webmaster tools detected an error 500 when trying to access the old route, instead of the expected 404. Looking in the logs in our dev environment the error is:

PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 67905 bytes) in /Users/arroyo/3dagogo-repos/astroprint/CMS/www/system/src/Grav/Common/Page/Pages.php on line 410" while reading response header from upstream, client: 127.0.0.1, server: ~www.astroprint.(dev|net|intranet)$, request: "GET /products/p/astrobox HTTP/1.1"

Using Grav 1.2.3

**Comment by rhukster** [comment]
I'm not able to replicate a simple moved page causing a 500 error.  The only think i can think of off hand is some redirect or rewrite rule (either in Grav or webserver) that is getting in the way.

is it possible to get a zipped copy of this site to see if I can replicate the issue?

**Comment by rhukster** [comment]
It's this route in your `site.yaml` conflicting:

```
routes:
  # /p/astrobox: /products/p/astrobox-gateway
```

Commenting it fixes the problem and you get a 404
