### ISSUE TITLE
Cannot move non-existing folder

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#1447]
After direct install of latest grav develop:

![message](https://cloud.githubusercontent.com/assets/12480617/25332527/204281d2-28e7-11e7-90f3-43ad47e247cd.png)

**Comment by rhukster** [comment]
So your trying to install latest grav develop over the top of your current grav install?

**Comment by rhukster** [comment]
Ok, this required a fix in Grav core and admin.  Basically i've forced ignoring of `tmp` and `user` folders when doing a Grav core direct-install.  Before it was expecting a nice clean 'update' package which didn't contain these folders.
