### ISSUE TITLE
Notify user if attempt to add a page matches an existing page

### ISSUE THREAD

**Issue by tamaracks** [getgrav/grav#1450]
Currently, if you add a new page with the folder name of an existing page in the Admin interface, Grav will proceed when you click Continue, but instead of a new page, it will pull up the existing page info. This could be a bit confusing when you thought you were creating a new page.

I'd prefer that it warn me the folder exists before even continuing to the page details, so that I could choose another folder name. But in any case, I think some kind of warning or notification that you've been brought to an existing page would be in order.

1. In the Admin interface, click on the Pages menu.
2. Click Add.
3. Fill in "Test" for the title.
4. "test" will be the folder name.
5. Click Continue.
6. A page will be created with that folder name. Add some text to the page. Save the page.
7. Click Add again.
8. Fill in "Test" for the title.
9. "test" will be the folder name.
10. Click Continue.

At that point, it will load the information from the page saved in step 6. It doesn't matter what you put as the title in step 8, it will load everything from the existing page.

**Comment by rhukster** [comment]
I think this is an issue for Admin plugin.  Please copy/paste this issue there: https://github.com/getgrav/grav-plugin-admin/issues

Thanks!
