### ISSUE TITLE
CSS/JS pipeline issues if URL contains query parameters

### ISSUE THREAD

**Issue by mahagr** [getgrav/grav#1451]
Fix looks something like this:

https://github.com/gantry/gantry5/commit/627c070ef6f97b9eff137be28f330e5a0250675c

**Comment by rhukster** [comment]
Which URL is this? The URL of the asset? so:

```
{% do assets.addCss('theme://css-compiled/nucleus.css?for=bar') %}
```

???

**Comment by mahagr** [comment]
Yeah, it removes `?foo=bar` from assets that are local files. Without this the file cannot be found and is not added into the pipeline, causing it to be silently removed.

Though my fix does not deal with CSS/JS files, which are generated by a script. We may also want to ignore assets which cannot be found from the filesystem instead of just removing them in the pipeline.
