### ISSUE TITLE
[Suggetion]Template html.twig is not defined

### ISSUE THREAD

**Issue by wooygcom** [getgrav/grav#1453]
I made myown.md file.
Of course it will make "myown.html.twig file is not defined" error.

So I suggest like this.

Load "default.html.twig" file If there is no twig file. :)

**Comment by rhukster** [comment]
I think this will lead to confusion.  Better to have an error here, or just rename the file to `default.md`.  At they very least you could create a simple `myown.html.twig` and simply extend `default.html.twig`.
