### ISSUE TITLE
auto_fix_orientation does not work

### ISSUE THREAD

**Issue by appinteractive** [getgrav/grav#1454]
Setting auto_fix_orientation: true does not triggering the images to rotate like expected. 

Not only that, when trying to use fixOrientation directly via twig, I always getting the invalid size parameters (unrotated), so I cant implement a gallery correctly while needing the correct dimensions of the original image (rotated).

```
    {% for image in page.media.images %}
        <div>
            <a href="{{ image.url() }}" itemprop="contentUrl" data-width data-size="{{ image.width }}x{{ image.height }}">
                {{ image.cropResize(200, 150).fixOrientation.html() }}
            </a>
            {% if image.meta.description %}
                {{ image.meta.description }}
            {% endif %}
       </div>
    {% endfor %}
```

While trying to set the orientation `{% set img = image.fixOrientation %}` Im getting a white page. So I was thinking that the auto_fix_orientation would fix that issue but as it is just applied as a filter, the dimensions are always wrong until the image is rendered. 

Is there any way to get this right? Or do I really have to write a plugin to fix that issue?

**Comment by flaviocopes** [comment]
Are you setting `auto_fix_orientation` in your `user/config/system.yaml`? I tested and it works.

About the second question, I don't get a white page (turn on error reporting, a white page is always an error page with errors silenced, to see if it shows a message. Or check the PHP error log.

Seems that the implementation for image processing (we use a library for that) do not allow those actions to "stick". For example, try `{% set img = image.resize(100, 100) %}`, and then `{{ img.html() }}`, you'll still get the original image. Same for width and height, they still refer to the original image, fixOrientation is just a visual thing, the original width and height is still the same. Plus, I tried `image.fixOrientation.width` but the value is still the original.

If you need to specify the w&h, and you already know all the images are landscape for example, you can compare the values and if h > w, reverse the values.
