### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by david-szabo97** [getgrav/grav#1455]
I would like to add my new plugin to the Grav Repository.
Here are the project details:  Admin Addon Media Rename is a dead simple plugin which adds media rename functionality to the admin panel. I wanted to avoid renaming the files on my machine before uploading so I had this pieces of code on my website for a while. I thought it would be great to refactor it into a plugin. Though it's more like a hack rather than a plugin :smile: As far as I know this kind of functionality will be added in the Admin Pro, so I don't mind if you reject this plugin.

**david-szabo97/grav-plugin-admin-addon-media-rename**

https://github.com/david-szabo97/grav-plugin-admin-addon-media-rename

**Comment by rhukster** [comment]
You'll need to do a Git release before it shows up in GPM.
