### ISSUE TITLE
gpm broken on certain webhosters [FIX]

### ISSUE THREAD

**Issue by bmuessig** [getgrav/grav#1456]
Hello!

While I still can't get grav with admin to work, I tried starting from grav-core and tried to install admin from there.
However, I was presented with multiple problems.

First, you just can't run gpm with the default syntax. I discovered though, that this one does work:
` php -C -f bin/gpm `

Second, `/bin/gpm install` was broken too.
I managed to fix this by patching `vendor/symfony/console/Helper/QuestionHelper.php`, line 121
to: `$inputStream = $this->inputStream ?: fopen('php://stdin', 'r');`

The worst problem is that I can't use the admin plugin, since I always get an "Invalid security token" error message.
I can log in and see the admin dashboard, but I can't do anything that persists. It will always fail with the above message.

**Comment by rhukster** [comment]
I think this is an edge case with your hosting provider because i've never heard of these issue in over 3 years.  A PR to add this kind of troubleshooting in the Grav docs would be appreciated though.
