### ISSUE TITLE
Remove  "|"

### ISSUE THREAD

**Issue by SamAleev** [getgrav/grav#1457]
How to remove a sign "|" in the title of the page?

**Comment by flaviocopes** [comment]
The theme adds it. For example, Antimatter does it in this line: https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/base.html.twig#L7

To edit it, you should create a child theme (https://learn.getgrav.org/themes/customization#theme-inheritance), and edit that line.
