### ISSUE TITLE
Question - Why is a - classified as an invalid slug character?

### ISSUE THREAD

**Issue by rhubarbselleven** [getgrav/grav#1459]
See: https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Page.php#L1500-L1502

I would have thought that a `-` would be a valid character to use in a slug.

**Comment by mahagr** [comment]
It is valid, but not as the first character.

**Comment by rhubarbselleven** [comment]
Ah, I see the issue. It's enforcing a lowercase slug. Should the slug not be lowercase then this notice is raised. 

Should this be the case? Is the direction of the team to only accept lower case slugs? Further, does this imply that only lowercase ascii is supported?

**Comment by mahagr** [comment]
Not sure. I think the decision to use lower case slugs was made because of Linux filesystem is case-sensitive and it would cause too many issues if we allowed people to use mixed-case in Windows and then deploy their sites in Linux server.

**Comment by rhubarbselleven** [comment]
Generated slugs, sure I can understand that. But where a slug is set explicitly, I wouldn't expect this.

**Comment by mahagr** [comment]
@rhukster What do you think?

**Comment by flaviocopes** [comment]
Actually this just adds an entry in the log, and things still work. I aligned that to the admin-side slug regex, also adding support for Cyrillic charset

**Comment by rhubarbselleven** [comment]
But when you have 2.3k pages that fail this on this check, that creates a huge amount of logs and so is not just an entry in a log but a larger capacity and scale issue

**Comment by rhukster** [comment]
We can remove the logging statement, it really doesn't serve much purpose.

**Comment by rhukster** [comment]
done.
