### ISSUE TITLE
Site and Admin Error latest Grav Develop: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#1462]
Just installed latest Grav Develop. 
Site broken:

![grav](https://cloud.githubusercontent.com/assets/12480617/25772257/6bee21de-3267-11e7-8f07-f2871728c18e.png)

In admin, after I click on username:

![admin](https://cloud.githubusercontent.com/assets/12480617/25772270/8e2bef6a-3267-11e7-9c6e-68c4a38cd94f.png)

Must have been one of the commits from 4/5 May (guess it's the Groups selection pre-filled in user form)

**Comment by flaviocopes** [comment]
Thanks for reporting!
