### ISSUE TITLE
Issues on IE11 and Edge.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1464]
I am not able to find browser support info about Grav. Is Grav supposed to support IE11 and/or Edge? If so, there some some UI issues I found running Grav on these browsers:
1 there is an extra close button in search bar when entering text in the search bar; this happens on both IE11 and Edge;
2 navigating to a Grav link causes flickering, because the right column (content column) appears first, then the left column appears later; this happens in IE11 only.

I used learn2 theme during the testing.

**Comment by rhukster** [comment]
It's not tested with IE11 at all.  It is tested with Edge however.  Also Chrome and Firefox.  If you wish to provide an IE11 CSS file that fixes issues, I would be interested in merging that in, but we have no plans on doing this ourselves.
