### ISSUE TITLE
cannot display images when using custom blueprint

### ISSUE THREAD

**Issue by stljeff1** [getgrav/grav#1465]
I am creating a custom modular that is essentially an image gallery. I used this  page as a reference when creating my blueprint for the gallery.

https://learn.getgrav.org/forms/blueprints/how-to-add-file-upload

Now in my twig template, after I add images to my module, I can dump my list of images and see each image and its properties, ie. name and path. However, when I try to reference those properties, I get null values.

How can I dump an array, ie. dump(image), and get: 
array:1 [
    "page@/logo.png" =&gt; array:4 [
      "name" =&gt; "logo.png"
      "type" =&gt; "image/png"
      "size" =&gt; 53440
      "path" =&gt; "page@/logo.png"
    ]

but then dump a property, ie. dump(image.path), and get null?

**Comment by stljeff1** [comment]
I've solved my own problem. I fault my lack of knowledge in accessing complex objects in Twig.

This post lead me to solve my problem: https://getgrav.org/forum#!/?image%20upload%20blueprints

Basically, when looping through my images, I needed to access each image by its key.

here is the loop in my View:

				{% for key, item in image.image %}
					
					<div class="{{ page.header.ui_id }}-image">
						<img src="{{ url(item.path)}}" alt="{{ image.title }}" class="img-responsive" />
					</div>
				{% endfor %}

**Comment by flaviocopes** [comment]
Good to see you solved, closing

**Comment by klihelp** [comment]
How `media_directory()` works? Gives me this error

```
 Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("Object of class Grav\Common\Page\Media could not be converted to string").
```

**Comment by klihelp** [comment]
Alright: issues/1545

**Comment by mahagr** [comment]
@klihelp It returns Media object, see how to use it in https://learn.getgrav.org/content/media
