### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by CollinDaugherty** [getgrav/grav#1467]
I would like to add my new plugin/theme to the Grav Repository._Here are the project details: **[CollinDaugherty/grav-theme-prime](https://github.com/CollinDaugherty/grav-theme-prime)**

**Comment by rhukster** [comment]
Added to GPM, should show up in next build.

**Comment by CollinDaugherty** [comment]
It doesn't appear to have been added.

**Comment by rhukster** [comment]
Ok I think the issue is that your 1.0.0 release actually has a `prime/` folder at the root. 

https://github.com/CollinDaugherty/grav-theme-prime/tree/1.0.0

This is not the same as the current 'master' branch which appears correctly. I think you just need to re-release.

**Comment by CollinDaugherty** [comment]
I'm a noob at using GitHub but I think I fixed it.

**Comment by rhukster** [comment]
Hm... i see you have a v1.0.0 tag, and a 1.0.0 tag.  This might confuse GPM.  I would probably delete both of those tags, and retag as 1.0.0 (don't put a v in front of it).

**Comment by CollinDaugherty** [comment]
Fixed.

**Comment by rhukster** [comment]
Ok, should get picked up ok now.. check in 30 mins.
