### ISSUE TITLE
Add babel support to js_pipeline ( Asset Manager )

### ISSUE THREAD

**Issue by robertovg** [getgrav/grav#1468]
Right now with `Asset Manager` we have the ability to minify and compress our javascript, which is very convenient, but would be nice to have a "build in" babel pipeline stage, to have the possibility of writing our javascript with ES6 and be compiled back with babel out of the box.

There is a way to configure something like that with Asset Manager?

Thanks in advance

**Comment by rhukster** [comment]
Babel is an NPM based builder tool right? Not sure how it would be possible to integrate this into the PHP-based Assets Manager.  Am I missing something?

**Comment by robertovg** [comment]
That's true, but maybe this could be a potential solution:

https://github.com/talyssonoc/php-babel-transpiler

No experienced with it yet, but if we could have something like that up and running, we could write native es6 javascript syntax in our custom themes and stop worrying about old browsers at all ( and then stop having to need babel  running locally or having to write old javascript on our files ). 

Actually this would make grav even better, the perfect web framework for developers 🙌 👨🏽‍💻

**Comment by rhukster** [comment]
Unfortunately that transpiler project seems to have died on the vine.
