### ISSUE TITLE
GPM does not work when updating on Windows

### ISSUE THREAD

**Issue by Vivalldi** [getgrav/grav#147]
Current error from windows command line when running `C\grav> php bin\gpm selfupgrade`
```
PHP Warning:  require_once(C:\path_to_grav\grav\bin/../vendor/autoload.php): failed to o
pen stream: No such file or directory in C:\path_to_grav\grav\bin\gpm on line 19
PHP Fatal error:  require_once(): Failed opening required 'C:\path_to_grav\grav\bin/../v
endor/autoload.php' (include_path='.;C:\php\pear') in C:\path_to_grav\grav\bin\gpm on li
ne 19
```

**Comment by rhukster** [comment]
What are you running in your windows terminal? Cygwin? BashGit? etc?

**Comment by Vivalldi** [comment]
None. Is that the problem?

**Comment by rhukster** [comment]
I think that's probably the root cause.  Windows just doesn't have the command line capabilities that GPM needs.  Could you try installing GitBash (seems the best option on windows), and trying it with that?

**Comment by Vivalldi** [comment]
Running the `bin\gpm selfupgrade` command in GitBash causes a runtime error due to a lack of administrative permissions. Then causing the above error if run again as bin\gpm deletes the system folder and replaces it later. If you run the `bin\gpm selfupgrade` command in GitBash after launching GitBash with administrative rights then you will not encounter a runtime error and gpm can upgrade successfully.
