### ISSUE TITLE
[add-resource] New Plugin - Admin Addon Revisions

### ISSUE THREAD

**Issue by david-szabo97** [getgrav/grav#1475]
I would like to add my new plugin to the Grav Repository.

Here are the project details: **david-szabo97/grav-plugin-admin-addon-revisions**

https://github.com/david-szabo97/grav-plugin-admin-addon-revisions

**Comment by rhukster** [comment]
As you probably know, we already have revisions support in Grav Admin Pro (unreleased though it is), and it even uses the same `.revisions` folder.  It would be best if you change the name of your default folder so things don't conflict when Admin Pro is released.  Other than that, I have no problem approving your plugin.

**Comment by david-szabo97** [comment]
@rhukster I changed the default directory to `.revs`.
Thank you!

**Comment by rhukster** [comment]
Added to GPM.  Cheers.
