### ISSUE TITLE
[add-resource] New Plugin: Responsive Images

### ISSUE THREAD

**Issue by OliverO2** [getgrav/grav#1476]
I would like to add my new plugin/theme to the Grav Repository. Here are the project details: **https://github.com/OliverO2/grav-plugin-responsive-images**

Some remarks:
* The plugin was successfully tested with Grav v1.2.4.
* Grav's latest development version (commit 82f2232) seems to break something, it looks like `onOutputGenerated()` does not get called.
* If at some point you would like to integrate the plugin's (simple) functionality into Grav, it would be most welcome, especially with regard to
    * automatically picking up images pre-rendered at different sizes and generating a `srcset` attribute for those,
    * a more readable way to specify a `sizes` attribute for responsive images,
    * working around the Microsoft Edge `srcset` bug.

**Comment by rhukster** [comment]
Added to GPM. Cheers.

**Comment by OliverO2** [comment]
Thanks!
