### ISSUE TITLE
[add-resource] New Plugin Rest Form

### ISSUE THREAD

**Issue by andreaschiona** [getgrav/grav#1479]
I would like to add my new plugin/theme to the Grav Repository._Here are the project details: **andreaschiona/grav-plugin-rest-form**

**Comment by flaviocopes** [comment]
Please create a release, see https://learn.getgrav.org/advanced/grav-development#themeplugin-release-process

**Comment by andreaschiona** [comment]
I have create a release.

Bye,
Andrea

**Comment by rhukster** [comment]
Added to GPM, cheers.

**Comment by andreaschiona** [comment]
Thanks
