### ISSUE TITLE
[Suggestion] Could GRAV expose an uniform Event Hook besides the onPagesInitialized for API routes

### ISSUE THREAD

**Issue by ash0080** [getgrav/grav#1487]
For now,
We need to wrote a url checker in 'onPagesInitialized' then use
$_GET / $_POST ...
to process the request
but the problem is the url checker is not managed centralized,
i's hard to avid namespace pollution if we wrote routes in individual plugins.
if we can make a API REGISTER, then an uniform route rule like,
your-domain/api/plugin-name/blah...blah
or  
your-domain/api?plugin=plugin-name&blah...blah
, maybe happier.

Seriously, an API register will make the GRAV more like a Framework than only a CMS, I think all needs have been done there in the Symfony, so... why not
if we can write an api easier, then we can use frontend MVC more flexible, Angular, React, Vue...
the writing of a plugin will be more modern.

For example, I wrote a vue example [here](https://github.com/ash0080/grav-plugin-vue-example)
Today, I added vuex localstorage and ajax to finished a shopping cart like feature in hours, maybe 1/5 lines of the code compare with the php version.

**Comment by mahagr** [comment]
You can use tasks for this. Just add GET/POST variable 'task' with your task name and then hook into `onTask.[name]` event.

**Comment by ash0080** [comment]
@mahagr 
Thank you for your reply, 
I looked into the LOGIN plugin, then understand.
Seems all TASKs exposed on the domain root url. using a task name to identity the request, though still need to avoid the namespace pollution manually, but it's better then processing on onPagesInitialized event hook

**Comment by mahagr** [comment]
You can use task in any page and then check out which page you're in when you're in the event. So all you need to do is to make sure your task name is unique and then write your logic to figure out the rest.

And yes, there's no namespaces on the tasks, so it's up to you to name it properly. And no, all handlers hooked to the event will be called, unless of course, the handler prevents that.

**Comment by ash0080** [comment]
A little bit confused now,
so what's the benefit of the onTask.name?
It seems more like a custom Event mechanism, seems do nothing except fired earlier than the onPagesInitialized. If a developer want to code an API, write it in onTask or onPagesInitialized seems almost same except you need pass a {task: taskname} to the php.
It can't make the things easier or more beautiful...

For example, compare between the $_POST and symfony Request, the Request do much more,
but these benefits haven't been inherited by GRAV now...

**Comment by flaviocopes** [comment]
Grav is most probably going to have a built-in API with plugin hooks in the next major version, and plugins namespacing rules will be considered in the process of defining conventions

Right now, your best option is to implement a plugin that responds to the API endpoints you need, and make it unique.

**Comment by ash0080** [comment]
@flaviocopes 
Wow ! that will be awesome!! Hope to see it soon!
