### ISSUE TITLE
post.media.images and page.media.images not displaying image url

### ISSUE THREAD

**Issue by kelseyurgorenci** [getgrav/grav#1489]
I am trying to call an image from a page. I am doing this for two separate needs: a page collection and a set of pages from a tag.

It is not working. I am new to GRAV and it isn't quite clear to me exactly how it should function.

Here is the last iteration I have tried:

<img width="741" alt="screen shot 2017-05-22 at 4 06 49 pm" src="https://cloud.githubusercontent.com/assets/24653532/26326359/d2cfd43a-3f08-11e7-8e5b-8764e14112dd.png">

One other issue, I have also noticed that for the tag taxonomy that you must use post.summary vs. with the page collection page.summary is used successfully. This isn't noted in the documentation.

Should I just be able to swap out post for page in all variables when pulling tag taxonomy?

**Comment by rhukster** [comment]
`page` is the current page variable, so the page based on the route you visited in your browser.
'post` is the temporary variable that represents each page returned by the taxonomy collection.  When you access `page.media.images` you are only accessing the images in the current page, not the multiple pages coming back as `post` in the for loop.

**Comment by kelseyurgorenci** [comment]
Ah I see. So is there any way to pull in an image from a post or page that you are not currently on?

**Comment by rhukster** [comment]
Of course, just replace `page.media.images` with `post.media.images` and it will output all the image in every post.

**Comment by flaviocopes** [comment]
@kelseyurgorenci the Taxonomy::findTaxonomy method returns a list of Page objects. So, a `post` variable in your loop is a Page object.

The `page` variable on the other hand is always a reference to the current Page.

There is no separation of pages/posts like in WP, if you're confused by that.

**Comment by kelseyurgorenci** [comment]
@flaviocopes That is totally what I was confused about. How did you know my background was in WP? :)
Thank you both!
@rhukster

**Comment by flaviocopes** [comment]
I guessed, from talking about posts/pages :) Glad the confusion is gone
