### ISSUE TITLE
Markdown Doesn't Handle [words](#)

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav#149]
You can see the problem on the Grav one page demo around this Markdown:

```
We believe the best recipe to make something great, is to bake with [quality ingredients](#) and add dollops of [cool stuff](#).
```
Everything after `[quality ingredients](#)` is cut off and the "quality ingredients" link doesn't work.

If (#) is replaced with (full url), then it renders and behaves correctly.

But I can't tell if it's Parsedown's problem or Grav's.

**Comment by bobrocke** [comment]
Oddly, changing to `[quality ingredients](/#)` fixes the rendering problem.

What could be up with that?

**Comment by Vivalldi** [comment]
The parser does not recognize # as an address.

**Comment by bobrocke** [comment]
OK, so it's not a Grav, Markdown or Parsedown problem, it's a problem with the `.md` file. I'll make a PR.

**Comment by rhukster** [comment]
Actually the parsedown parser does work with this: http://parsedown.org/demo

So must be a grav issue, reopening.

**Comment by Sommerregen** [comment]
I'm aware of this bug, too (I noticed it around two or three weeks ago). It happend just after the "big" commit change of `MarkdownTrait` to `ParsedownTrait` and all connected commits to it. I will try to have a look on it today and provide a PR, if you have not yet done so @rhukster.

**Comment by Sommerregen** [comment]
Ok, I tracked down the problem and it is indeed a bug in **Grav** (to be precise a regex problem in the `ParsedownGravTrait` class). I provide a PR now, see Pull Requests.

@bobrocke Thank's for filing up the issue again. I almost forgot it :smile:
