### ISSUE TITLE
Change Nav Menu Titles

### ISSUE THREAD

**Issue by Zaiyah** [getgrav/grav#1490]
Hello i have an Issue, i cant change the title names of the navbar.

I already changed the menu tag in the page setting, but nothing happens.

Anyone can help me?

Site is nhi.melanura.com

**Comment by flaviocopes** [comment]
Hi, the Agency theme, the one you're using, chooses to define the top menu in the "links" Site configuration property: https://github.com/getgrav/grav-skeleton-agency-site/blob/develop/config/site.yaml#L15-L25

You can change them in your `user/config/site.yaml` file.
