### ISSUE TITLE
width & height is added as url parameter in svg file in a loop

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav#1491]
when svg-file is used more than once in a loop it add url parameter to the file name
in my loop (i use the same svg for the loop)
```
{% set image_media_url = page.media[button.image].url %}
{% set mediatype = page.media[button.image].mime %}
```
i test if the file is `svg` so i remove `width` and `height` for my` img` tag
```
{% if ('svg' in mediatype) %}
  {% set image_width  = '' %}
  {% set image_height = '' %}
  {% set svg_classe = 'svg' %}
  {% set pagespeed_nodefer = 'pagespeed_no_defer' %}
{% endif %}
```

then in my template
```
 {% set media = '<img {{ pagespeed_nodefer }} class="' ~ image_class ~ svg_classe'" src="' ~ image_media_url '"' ~ image_width_attr ~ image_height_attr ~ image_alt ~ image_title '/>' %}
```
it render like that
```
<img  class="svg" src="/user/pages/politics/_programme/svg-test.svg" alt="Éducation #1" title="Éducation #1"/>

<img  class="svg" src="/user/pages/politics/_programme/svg-test.svg?width&height" alt="Éducation #2" title="Éducation #2"/>
```
id i add one more loop , the url parameter is
```
<img  class="svg" src="/user/pages/politics/_programme/svg-test.svg?width&height&width&height" alt="Éducation #3" title="Éducation #3"/>
```

Hope i'm clear
Thanks

**Comment by flaviocopes** [comment]
Can you post the whole loop? I don't see where you're setting `width` and `height`.

**Comment by dimitrilongo** [comment]
this the whole loop, i remove extra stuff, i test that loop same issue

```
{% for button in page.header.buttons %}

  {# MEDIA TYPE #}
  {% set mediatype = page.media[button.image].mime %}

  {# MEDIA URL #}
  {% set image_media_url = page.media[button.image].url %}

  {# MEDIA FILENAME #}
  {% set image_filename  = page.media[button.image].filename %}

  {# MEDIA WIDTH & HEIGHT #}
  {% set image_width  = page.media[button.image].width %}
  {% set image_height = page.media[button.image].height %}

  {% if ('svg' in mediatype) %}
    {% set image_width  = '' %}
    {% set image_height = '' %}
    {% set svg_classe = 'svg' %}
    {% set pagespeed_nodefer = 'pagespeed_no_defer' %}
  {% endif %}

  {% if image_width is not empty %} {% set image_width_attr  = ' width="' ~ image_width ~ '"' %}{% endif %}
  {% if image_height is not empty %} {% set image_height_attr  = ' height="' ~ image_height ~ '"' %}{% endif %}

  {% set image_alt = button.title|striptags %}
  {% set image_alt  = (image_alt) ? ' alt="' ~ image_alt ~ '"' : 'alt="' ~ image_filename ~'"' %}
  {% set image_title  = (image_title) ? ' title="' ~ button.title|striptags ~ '"' : ' title="' ~ image_filename ~'"' %}

  {% set media = '<img {{ pagespeed_nodefer }} class="' ~ image_class ~ svg_classe ~'" src="' ~ image_media_url ~ '"' ~ image_width_attr ~ image_height_attr ~ image_alt ~ image_title ~ '/>' %}

  {{media}}
  
{% endfor %}
```

**Comment by dimitrilongo** [comment]
> Are you sure mediatype 'svg' is correct? For svg should be image/svg+xml, in that case it will not reset your values.

same issue with `image/svg+xml`  `in` operator performs containment test, so i don't understand why i have that issue.
I will test on fresh install

**Comment by flaviocopes** [comment]
Try printing the values of `image_width_attr` in each iteration, I think it's a case of not resetting that

**Comment by dimitrilongo** [comment]
it returns null

**Comment by flaviocopes** [comment]
Send me in Slack your `user/pages` folder so I can try directly with your same page and header configuration

**Comment by dimitrilongo** [comment]
@flaviocopes send you page zip through slack

**Comment by flaviocopes** [comment]
Replicated the problem - calling `.width` or `.height` on a SVG medium. 

This happens because SVG is not an [ImageMedium](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Medium/ImageMedium.php), but it's a [StaticImageMedium](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Medium/StaticImageMedium.php), which in turn does not extend ImageMedium, but [Medium](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Medium/Medium.php) directly, which has no `width` or `height` methods, and the attribute is appended by the magic method [Medium::__call()](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Medium/Medium.php#L489-L501).

So, two solutions that I tested and fix this scenario are:

1. Add empty width() and height() methods to the StaticImageMedium class
2. Let StaticImageMedium extend ImageMedium

1. is simpler but might need to add more methods not implemented for svgs I didn't test the side effects of 2. 

Maybe it's best to state that SVGs do not support width() and height(), because they are not really considered images in Grav, and avoid calling those methods on them.

**Comment by dimitrilongo** [comment]
@flaviocopes thanks for your investigation. 
I will wait for a future update. More and more website use SVG (scalable, weight, modifiable, animation..)

**Comment by rhukster** [comment]
The main issue is that svg is not a typical image format. It's XML and not handled by GD librabry at all. Also it's not handled by the built in php functions to get width and height. In fact you don't need to specify a width and height on an svg at all as it's purely vector.

I don't think it make sense to try to support something the format doesn't even require.

**Comment by dimitrilongo** [comment]
even if you don't specify height & width the issue occurs

**Comment by mahagr** [comment]
http://tutorials.jenkov.com/svg/svg-viewport-view-box.html

SVG can define size in it, but it's kinda optional...

**Comment by rhukster** [comment]
FWIW, I use SVG a lot, it's my preferred image format whenever possible, I just size everything with CSS though.

**Comment by dimitrilongo** [comment]
@rhukster i totally agree it's very convenient for filling through css for instance. all my websites are are made with svg when it s possible 
that's why that issue inside a loop with same filename is very boring

my solution now is to copy the svg file and rename it, so i have 2 identicals svg with 2 differents name ;-(

**Comment by dimitrilongo** [comment]
@flaviocopes 
is it possible to add label "Bug" because it occurs only with same svg filename in a loop
