### ISSUE TITLE
Using Grav core as a library.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1492]
Our backend system needs to parse Grav pages, and return components like frontmatter and body, etc. We are experimenting embeding Grav\Common as a lib for this purpose. Specifically, use the Page class to parse page files. But we are running to various class not defined issues.

What's the proper way of using Grav classes in a larger project?

Thanks!

**Comment by flaviocopes** [comment]
Not sure if it's the proper way, but here's how I initialize Grav in the tests: https://github.com/getgrav/grav/blob/develop/tests/_bootstrap.php#L10-L29

**Comment by mahagr** [comment]
For undefined classes, you need to initialize the autoloader like with every other PHP project using composer. But yeah, I would use some existing file as a base, like `index.php` to make sure everything is properly initialized.

**Comment by hifall** [comment]
Thanks for the suggestions. Will try these out.
