### ISSUE TITLE
Tags added through Admin do not appear unless module md file is saved manually

### ISSUE THREAD

**Issue by kelseyurgorenci** [getgrav/grav#1493]
So I am in the development phase on my local machine and I am running into a couple issues that are only fixed by my manual saving of the associate markdown file:

- If I make a change to any *.hmtl.twig template, the changes are not shown unless I manually save the markdown file (e.g., for a modular page modularsection.md must be saved to see the reflected changes of modularsection.html.twig)
- I created a modular page that outputs a tag taxonomy and it works successfully only if the .md file is saved manually; meaning if a tag is added through the Admin GUI it is not appearing until the .md file of the modular page is saved manually

How can I fix this?

**Comment by rhukster** [comment]
During development you should disable cache in the system.yaml. This will cause the modular pages to not get cached as during development this is problematic. 

Alternatively you can set the `never_cache_twig: true` option in the modular subpage frontmatter.

**Comment by kelseyurgorenci** [comment]
Got it! Thanks @rhukster
