### ISSUE TITLE
Strange twig issue with markdown-extra

### ISSUE THREAD

**Issue by olivierdalang** [getgrav/grav#1495]
Hi !

I have a strange bug when I enable markdown extra in system.yaml with the following code in one of my pages content :

```
<div><img alt="A" src="{{page.media['img48.jpg'].url}}" style="width: 200px" class="center"></div>

<img alt="B" src="{{page.media['img48.jpg'].url}}" style="width: 200px" class="center">
```
gets rendered to 
```
<div><img alt="A" src="%7B%7Bpage.media%5B'img48.jpg'%5D.url%7D%7D" style="width: 200px" class="center"></div>
<img alt="B" src="/folder/user/pages/02.apropos/03.partenaires-et-bailleurs/03._les-bailleurs/img48.jpg" style="width: 200px" class="center">
```

Twig isn't rendered in the first one, while it is in the second one. The very odd this is that if I set twig blocks in other attributes, it works well (only src and href cause problems).
Everything works as expected as soon as I disable markdown-extra.

I don't know the internals of grav well enough to know where the problem could come from.

**Comment by rhukster** [comment]
it's an issue with markdown extra and twig. It's not a grav specific thing.  You can probably get around it by enabling `twig_first: true` in the page header. Although it might be better not to use markdown extra at all as it does seem to produce some weird issues that the regular markdown parser doesn't suffer from.
