### ISSUE TITLE
[add-resource] New Plugin cascade-filters

### ISSUE THREAD

**Issue by ash0080** [getgrav/grav#1498]
I'd like to add my new plugin to the Grav Repository.
The plugin provides a multiple layer filters collected throughout the site.

Here are the project details: [grav-plugin-cascade-filters](https://github.com/ash0080/grav-plugin-cascade-filters)

Thanks,
Elvis

**Comment by rhukster** [comment]
Sorry missed this one!  Added to GPM now.

**Comment by rhukster** [comment]
This won't show up until you create a GitHub release: https://help.github.com/articles/creating-releases/

**Comment by ash0080** [comment]
Done
