### ISSUE TITLE
Creating REST endpoint for search.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1499]
Not sure about the RESTFUL JSON API status, but I'd like to implement a REST endpoint, so that it returns related articles when called from remote and search keywords are passed in. I see some simplesearch_results.json.twig stuff in the simplesearch plugin, and I think it could be related, but I can't figure out how to implement the endpoint.

Could you shed some light on this?

Thanks!

**Comment by Perlkonig** [comment]
The webmention plugin does some endpoint processing.

**Comment by hifall** [comment]
Thanks @Perlkonig, I will look into the plugin shortly.

**Comment by flaviocopes** [comment]
Search offers a JSON endpoint by default, by going to `http://yoursite.com/search.json/query:your_query`
