### ISSUE TITLE
Implementing semantic search.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1500]
In addition to returning results based on traditional keyword search, we'd like to return semantically related pages as well. For example, if a page contains: "Item A's price is $1234.", a search for "cost of item A" would return that page. Here `price` and `cost` are semantically related.

Note that this is NOT fuzzy search. Traditional fuzzy search returns correct results for incorrectly typed queries. Returning semantically related pages requires Natural Language Processing (NLP) technologies which is outside the scope of Grav.

How would I implement such semantic search for Grav? I guess this would be done as a plugin, like SimpleSearch?

**Comment by Perlkonig** [comment]
When it comes to NLP, what first comes to mind is [Stanford's NLP project](https://nlp.stanford.edu/). There appears to be a [PHP interface](https://github.com/agentile/PHP-Stanford-NLP). I use the .NET interface a fair bit. The POS tagger is fast, but the core parser is relatively slow (from a user perspective). You'd have to do some sort of caching strategy. My approach would be to create a plugin that

1. gives a command line tool that processes pages, parses them, and caches the result in some way, and
2. provides a simplesearch-like widget that operates on the cached language data.
