### ISSUE TITLE
frontmatter.yaml does not respect pages.frontmatter.process_twig setting

### ISSUE THREAD

**Issue by the4thamigo-uk** [getgrav/grav#1504]
Hi,

I have tried to add twig into frontmatter.yaml values (i.e. https://github.com/getgrav/grav/issues/1494), but it looks like it is not processed.

Ive very tentatively made a fix to explore the issue. Can you let me know if it is worth a PR :

https://github.com/the4thamigo-uk/grav/commit/b7e2f2829072055b4bc82124f46876c3c6295843

**Comment by flaviocopes** [comment]
Go on with the PR, I'll check it 👍
