### ISSUE TITLE
Suggestion: merge frontmatter.yaml from ancestor folders

### ISSUE THREAD

**Issue by the4thamigo-uk** [getgrav/grav#1505]
Hi,

The frontmatter.yaml is a great Idea, but if you want to apply the same frontmatter to multiple pages you have to duplicate frontmatter.yaml. How about allowing frontmatter.yaml in all ancestors up to and including the pages subfolder.

Worth a PR?

**Comment by the4thamigo-uk** [comment]
Do you have any comment on this suggestion? It would be something immediately useful to us and avoids a lot of duplication of logic.

**Comment by bleutzinn** [comment]
It sure is an interesting suggestion. However with an eye on performance I don't think this should be default behavior but it could be a useful plugin.

**Comment by rhukster** [comment]
I also think performance wise, this would be an issue, also it would change exiting behavior.  Another issue is that from the text files it's not going to be clear at all what is getting set by what. I think this requires more thought but we do have support to automatically include a frontmatter.yaml file from the folder, perhaps this functionality could be expanded to look for this file in parent folders too.

**Comment by the4thamigo-uk** [comment]
another option is to generate the frontmatter.yaml in the folder once and cache it in the folder so that subsequent requests only load one 'rolled-up' frontmatter.yaml.

I was aware that my sketch code in https://github.com/the4thamigo-uk/grav/commit/d5b07a2e8fd5ddfb7cde8604f7301b8017ab9f3e is not particularly performant, but a cache approach would get around this... Unfortunately Im not familiar enough with the code yet to offer a PR.
