### ISSUE TITLE
Word truncated in summary.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1510]
Maybe this is too trivial. But here is the case: a summary can be cut off right in the middle of a word. See here, the last word "System" is truncated as "Sys...".

<img width="675" alt="screen shot 2017-06-02 at 9 02 02 pm" src="https://cloud.githubusercontent.com/assets/5734293/26726737/c843abfa-47d6-11e7-96d2-e638ae4c322a.png">

Maybe we can do it at word boundaries?

**Comment by flaviocopes** [comment]
`page.summary` by default is not word safe. This is probably what your theme uses.

Use the `|safe_truncate_html` filter: `{{ page.summary|safe_truncate_html }}` or `{{ page.content|safe_truncate_html }}` will do.
