### ISSUE TITLE
Question: static data in setup.php

### ISSUE THREAD

**Issue by the4thamigo-uk** [getgrav/grav#1512]
Hi,

We have a functioning multisite which can be accessed from a number of public hostnames. Each hostname is mapped to a backend grav folder using a customized setup.php. We retrieve the hostname -> folder mappings as a yaml file from Hashicorp Consul before launching the site, and we load the yaml using symfony at the top of setup.php.

Now, I believe that this may not be very efficient as we are essentially loading the same yaml file on every request. Id like to find a good way of avoiding this if possible. One way is to convert my yaml into php and 'include'ing it at the top of setup.php, so that the array is constructed on each request. This seems a bit of a hack though, but is probably fairly efficient.

I was wondering though, if there is a better more grav-like mechanism to do this. In paritcular can setup.php have access to the cached config in user/config/system.yaml. If so, then I could insert my yaml mappings directly into system.yaml and (presumably) setup.php would then take advantage of any yaml caching provided by grav? Is this possible?

What other options might I have to avoid having to reload the yaml mappings on every request?

Thanks,

Andy

**Comment by mahagr** [comment]
Take a look at `\Grav\Common\File\CompiledYamlFile` class, it is easy to use and compiles YAML into a PHP file using Grav cache folder. All updates to YAML file are detected, so it is safe to use.

**Comment by mahagr** [comment]
To answer your another question, no, `setup.php` cannot see configuration as it is not yet been loaded.

**Comment by the4thamigo-uk** [comment]
Great stuff, thanks Matias!

**Comment by mahagr** [comment]
I need to fix unit tests before it can be merged, will look into it tomorrow.
