### ISSUE TITLE
Translation Overrides doesn't work for a single key/value pair

### ISSUE THREAD

**Issue by core77** [getgrav/grav#1514]
I created a **/user/languages/de.yaml** file like the [docs say].(https://learn.getgrav.org/content/multi-language#translation-overrides)

I put the following overrides in it:

```
PLUGIN_SIMPLESEARCH:
     SEARCH_PLACEHOLDER: "Suche im Blog ..."
```

The override for the SEARCH_PLACEHOLDER string works. But the other strings for the simplesearch plugin are showing up in english.

I fixed this for me by pasting in all the german strings for the simplesearch plugin but expected it would work for only one key/value pair...

**Comment by paulmassen** [comment]
Interested in this too, but I think it's a problem with admin plugin actually.
I think you might have to add all the other translations, see also:  https://github.com/getgrav/grav-plugin-admin/issues/422

**Comment by paulmassen** [comment]
Also, as I suppose you want to use that as a placeholder, just use another prefix, such as:
````
MYCUSTOMSTRINGS:
SEARCH_PLACEHOLDER: "Suche im Blog ..."
```

And reference it in your form with
MYCUSTOMSTRINGS.SEARCH_PLACEHOLDER

**Comment by flaviocopes** [comment]
Yes, currently if you override a single string, you must also add all the other strings of the plugin, it's a known bug.

**Comment by rhukster** [comment]
This is fixed in the PR mentioned above, please test....

**Comment by rhukster** [comment]
Merged this manually...

**Comment by sarbanha** [comment]
I encountered the same problem, I noticed that Theme language variables precede the user/language variables, when I comment out a variable in theme language file, Grav tries to find it in user overrides.

I suppose user overrides must precede the theme language variables.

Grav 1.7.38
