### ISSUE TITLE
Dashboard: Class 'DOMDocument' not found

### ISSUE THREAD

**Issue by greinbold** [getgrav/grav#1515]
Hi,

When I load the Dashboard page, I can see this error: Class 'DOMDocument' not found

Same in News Feed on the same page...

![class_domdocument_not_found](https://cloud.githubusercontent.com/assets/20133970/26830716/09fc7cb6-4aca-11e7-8dad-731a4dfbf96c.jpg)

Any idea?

Grav: grav-admin-v1.2.4
OS: FreeBSD 11.0-RELEASE amd64
PHP: 5.6.30

Regards

**Comment by rhukster** [comment]
You need to have PHP xml installed. https://stackoverflow.com/questions/14395239/class-domdocument-not-found

**Comment by greinbold** [comment]
Thanks for your answer!

php56-xml installed and loaded in php confiugration using extension=xml.so

**Comment by flaviocopes** [comment]
Does it appear under yoursite.com/admin/config/info ?

**Comment by greinbold** [comment]
No, in https://mysite.com/admin

**Comment by greinbold** [comment]
Sure

![screenshot - 06062017 - 04 29 40 pm](https://cloud.githubusercontent.com/assets/20133970/26834348/607cba96-4ad5-11e7-9d76-194f345d0cf2.png)

**Comment by greinbold** [comment]
Another shot for libxml

![screenshot - 06062017 - 04 34 23 pm](https://cloud.githubusercontent.com/assets/20133970/26834621/200cd170-4ad6-11e7-83ed-4b33ab7f579d.png)

**Comment by flaviocopes** [comment]
It's not technically a Grav issue, but an environment configuration problem. 

Does DOM/XML appear in your phpinfo

![screen shot 2017-06-06 at 18 27 12](https://user-images.githubusercontent.com/11783388/26840246-cbabb7a8-4ae5-11e7-8ed3-2e57824c5b08.png)
?

**Comment by greinbold** [comment]
Ok.

1. dom does not appear in my phpinfo, so I installed php56-dom and now I see this error

![untitled](https://user-images.githubusercontent.com/20133970/26867787-0c8a9268-4b67-11e7-98b3-d78edd163b3e.jpg)

2. php-dom is not indicated on https://learn.getgrav.org/basics/requirements as a requirement for php

Regards

**Comment by greinbold** [comment]
So, issue fixed after installing php56-simplexml. Again, php-simplexml does not appear as a requirement of php in https://learn.getgrav.org/basics/requirements. Also for php-session...

**Comment by rhukster** [comment]
I'm glad you got it sorted.

To be honest this has never come up before for any other user.  Most installations already have XML built in.  Those that don't include everything you need with the php XML module. It seems for whatever reason your system breaks this down even further into many smaller sub-modules.  This is not common at all, and I think it would make it more confusing for most users to have them check for something that is almost always there.

I am curious as to what platform system you are using though, perhaps we can do something specific in the problems plugin, or a special note in the docs regarding the platform specifically.

**Comment by greinbold** [comment]
I install [FreeBSD](https://www.freebsd.org) on my servers and build packages (like php) with [Poudriere](https://github.com/freebsd/poudriere). You're right about the modules. Debian, Ubuntu and many other OS install some libraries (like php-xml, php-session, ...) by default and configure them when you install php. Sure is easy, but I think this is not a good practice.

**Comment by greinbold** [comment]
Is the same when you download the sources of a software. If the developer does not tell you what the libraries is needed to build from sources, you cannot configure and make it.

**Comment by flaviocopes** [comment]
Maybe we can add those checks inside the Admin plugin? The Problems plugin maybe should contain more general Grav requirements, but those are specific to Admin I think.
