### ISSUE TITLE
Is there a hook for logging in as admin or any other user?

### ISSUE THREAD

**Issue by notatamas** [getgrav/grav#1516]
I would like to log each login attempts and successful logins from the users. I guess it requires a custom plugin. Is there a hook I could use for this?

The plugin would run on each login or login attempt and write a new line in a specific log file.

**Comment by flaviocopes** [comment]
Any plugin can listen for the "onTask.login" event, and you can access the POST data. The event is not unique to Admin, it will fire for the frontend, too, so you need to detect if it's Admin or frontend login (if you have that feature enabled in your site)
