### ISSUE TITLE
Displaying results from external REST endpoint.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1517]
We need to display results returned by a separate service, in a Grav page. This would be helpful for personalizing documentation. For example: our own system keeps track of everything about our users, including name, email, API key, etc. When a user browses to a Grav page, and if he is logged in, we want Grav to call our system's REST endpoint to fetch the user info, then render the info on the Grav page, if necessary.

This would help personalize documents, and create a cohesive UX for users. For example, this would allow a Grav page to say: "Please use this API key: 123456-abcde for your application", without the user having to do anything else.

Currently, many documentation systems ask you to log into a separate dashboard to get pieces of info, then get back to the documentation again, like: "Please log into your dashboard, do A, do B, ..., find the API key, ...", which isn't the best, IMHO.

I guess in order to implement such a feature, I would need to:
1 install the Grav login plugin;
2 upon generating a Grav page, if the user is logged in, call the REST endpoint;
3 instantiate Twig variables with the result so that they are rendered.

Is this a feasible way to approach this?

Thanks!

**Comment by mahagr** [comment]
I'm using this one: https://github.com/Mashape/unirest-php , it should take care of calling to the external site. With some local caching (only fetch once per session), the site should remain fast enough.

Displaying the data depends on where you want to show it. The easiest approach would be to register your object/class into the Grav CI container and just call it from the template file.
