### ISSUE TITLE
JS Pipeline breaks on Gantry 5 JS

### ISSUE THREAD

**Issue by mahagr** [getgrav/grav#1518]
If you enable JS pipelining and set `js_minify: true`, Gantry 5 `main.js` breaks because of minifying JS breaks the code.

At least following code breaks:

```js
    for (var key in proto){
        if (key.match(verbs)) continue
        if (hasDescriptors){
            var descriptor = Object.getOwnPropertyDescriptor(proto, key)
            if (descriptor){
                Object.defineProperty(prototype, key, descriptor)
                continue
            }
        }
        prototype[key] = proto[key]
    }
```

in here:

```js
if (key.match(verbs)) continue if (hasDescriptors){
```
which is bad JS.

See also https://github.com/gantry/gantry5/issues/2001

**Comment by flaviocopes** [comment]
Shouldn't this problem must be solved on the Gantry side by simply adding a `;` after continue?
There are a few places in Gantry's JS where that semicolon-less statement is used.

**Comment by mahagr** [comment]
JS is automatically built, there's no way I can go and modify the file.

**Comment by flaviocopes** [comment]
Could as well be a problem in the minify lib we use https://github.com/matthiasmullie/minify/issues/178

**Comment by mahagr** [comment]
Yeah, looks like the same issue.

**Comment by rhukster** [comment]
Maybe @w00fz can help shed some light on where this issue lies?

**Comment by mahagr** [comment]
It looks like the bug was fixed in the library and has been released in the upstream. So we just need to update the library.
