### ISSUE TITLE
Possible Issue: GPM Testing and Stable

### ISSUE THREAD

**Issue by paulmassen** [getgrav/grav#1519]
Hi!

I'm not sure if it is actually an issue or if it is on purpose, but I noticed that if a Grav users has enabled Testing releases for the GPM, he does not get notified if a more recent stable releases exists.

So do plugin developer just need to keep their testing release ahead of the stable one or is it a bug?

Thanks!

**Comment by flaviocopes** [comment]
I think we should always have a notification for newer, non-testing releases. Marking as bug
