### ISSUE TITLE
Debug toolbar does not show up on child pages

### ISSUE THREAD

**Issue by akoebbe** [getgrav/grav#1520]
I was trying to do a little debugging with a child page (item page of a blog parent) and was unable to get the toolbar to show up when viewing the individual item page. The toolbar shows up on all other pages, just not that one. I'm extending the Antimatter them, and have only added new templates.

![grav-blog](https://user-images.githubusercontent.com/1044465/26886960-6a262130-4b6c-11e7-8b0e-954774f5b9af.png)

![grav-item](https://user-images.githubusercontent.com/1044465/26887000-7efaebe0-4b6c-11e7-97da-fdd0e1198790.png)

**Comment by flaviocopes** [comment]
In my testing Antimatter has no such issue. Can you test with Antimatter, and not your child theme?

Does it still happen? Is there ant JS issue in the page (check the Console in the Browser DevTools)

**Comment by akoebbe** [comment]
I've switched back to Antimatter and I'm still having the issue with the 'item' content. The debug toolbar javascript block injected to the bottom of the html content is not present on the item page, but is present the 'blog' page and others.

FWIW this is an install of the Grav + Admin zip package.

**Comment by akoebbe** [comment]
Also, I've verified that this is still the case in an incognito session, just in case browser plugins were getting in the way.

**Comment by mahagr** [comment]
Check if the output is there in the end of the page. Then check if the debugbar assets (js/css) are being loaded.

**Comment by akoebbe** [comment]
Nope no output after the HTML and no debug assets.

![view-source](https://user-images.githubusercontent.com/1044465/26991225-29cf4a08-4d1f-11e7-9bd0-d54f115a171f.png)

![view-source_localhost_8081_hypeblog_2017-06-01_the-show-begins](https://user-images.githubusercontent.com/1044465/26991262-4816d22e-4d1f-11e7-8471-feb7966520dd.png)

**Comment by flaviocopes** [comment]
The debugger if enabled will show up unless the page template type is not `html`.
This is to prevent it to fire on AJAX requests, I think.

Looking at the page URL, the issue is with your URL here. `.the-show-begins` causes Grav to think the template type is `the-show-begins` instead of `html`. 

Solutions: 
- change that URL
- add `template_format: html` to the page header
- set `append_url_extension: '.html'` in the system config

Maybe I miss where we can globally set a `template_format`, unless a valid one is found in `system.pages.types`, if we have such setting.

**Comment by akoebbe** [comment]
Hmm... Changing the url does solve the problem. Interesting the Grav knows to use the .html.twig template here, but the debug bar doesn't know that it's and HTML view. I might look in to this more, but if you feel this isn't a bug, then feel free to close this.

**Comment by mahagr** [comment]
I've added a change into 2.0 branch to allow debugbar to be used in any page types.
