### ISSUE TITLE
no more folder in Finder(mac) when folder's name is menu and numeric prefix

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav#1521]
really strange issue, first time i saw that, don't know if it's related with GRAV
when i copy folder from finder in MAC, and add numeric folder, can't access  the folder from the finder, ok from GRAV
After some investigation it happen only if the folder named is menu (see screenshot)
and file type is MenuExtra plugin in Finder
![capture d ecran 2017-06-07 a 19 31 27](https://user-images.githubusercontent.com/3842190/26892268-046e0ee2-4bb8-11e7-93c6-ee309dfbd8fd.png)

**Comment by flaviocopes** [comment]
This is an OS-specific feature, there's nothing Grav can do. Same with adding a `01.pages` with the Pages app installed. Finder will consider that an application-specific file. Not sure if there are OSX utilities or hacks to prevent this.

**Comment by dimitrilongo** [comment]
@flaviocopes thanks

**Comment by beamaria** [comment]
@dimitrilongo @flaviocopes: Thank you both!
It looks strange though that Gantry developers didn't find a solution to this problem...As far as I can see there is only one work around, that is uninstalling Pages...I searched Mac support to find a system to prevent this behaviour, but there is nothing :(
