### ISSUE TITLE
RESTful JSON API status?

### ISSUE THREAD

**Issue by delmicio** [getgrav/grav#1523]
Hello,
I've read in the blog that last year on january you've planned this, for 2016, an API REST endpoint for grav.

How is the status of this feature?

**Comment by mahagr** [comment]
It is going to be Grav 2.0 feature and there is some work being done towards it (mostly research and in a private project).

**Comment by delmicio** [comment]
Thank you @mahagr . Please let us know when the Grav 2.0 beta is published

**Comment by stephanedemotte** [comment]
A release date for Grave 2.0 ?

Thanks !

**Comment by flaviocopes** [comment]
There is no public release date planned yet.

**Comment by Moxxie** [comment]
Any update on this?

**Comment by creazy231** [comment]
Any updates about a rest api integration in 2k19?

**Comment by rhukster** [comment]
One of the main things we plan on focusing on actually.

**Comment by creazy231** [comment]
Awesome 👍 Is there any ETA like Q2, Q3, Q4 or any progress in percent?
Is the progress open source where people can help?

**Comment by rhukster** [comment]
Not really started on it yet, although we do have the initial API underpinnings in a pretty good state, just need to actually build out the API itself.

**Comment by creazy231** [comment]
Can't wait to see it live 😭 ❤️ Any updates?
