### ISSUE TITLE
Deleted page still cached.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1525]
Say we have 2 pages A and B, and both pages show up in browser. Now delete A's directory, and refresh the browser. Page A is still visible.

Caching is enabled. The checking method is `file`.

This happens in multi-site. And I haven't tested with no multi-site.

**Comment by rhukster** [comment]
It's quite common for file systems to not update the modified time stamp when a file or even a folder is deleted. Try the newer `hash` method. This will detect any change.

**Comment by hifall** [comment]
The `hash` method seems working fine. Thanks!
