### ISSUE TITLE
Output markdown is formatted wrong after multi-lang save 

### ISSUE THREAD

**Issue by jukefr** [getgrav/grav#1527]
Hello
I am trying out Grav because I need a good multilingual cms for a client, however I ran into an issue.
I have defined a page that lists content from a specific taxonomy like so :
```
---
title: Category title
content:
    items:
        '@taxonomy.category': category_title
---
```
when I edit this page and save it under another language it generates this content :
```
---
title: Category title
content:
    items: '''@taxonomy.category'': category_title'
---
```

I tried to switch between single and double quotes and it did nothing. Tried without quotes and it doesn't work.
I think this is a bug, correct me if I am wrong please.

**Comment by flaviocopes** [comment]
I cannot replicate the problem, by pasting your same snippet. 

Does that page use a custom blueprint?

**Comment by kjullien** [comment]
I am using version 1.3.0-rc.3 as well as the default Antimatter theme.
If it helps I tried with 4 languages enabled : french (default), english, spanish and chinese.

I will try to setup a new site from scratch and try the same see if I can replicate.

**Comment by kjullien** [comment]
Just tried again in a Linux environment here is the outcome :
- if I simply enable **fr** and **en** as languages everything works fine, when I save the page it formats the items nicely like so 
```
items:
    @taxonomy.category:
        urban
```
- however as soon as I added **es** and **zh** to the list then whenever I save a page it messes up the items and outputs them like so ```items: '''@taxonomy.category'': urban'```
- i then tried to disable **es** and **zh** but when I save then it still formats it wrong.

I will try to to another fresh install, but I was able to reproduce on Windows and Linux already so I am pretty sure something is up

**Comment by kjullien** [comment]
How to replicate : 
1. Fresh install from downloaded zip of rc from site, no language settings nothing, go straight to page creation.
2. Add a blog with (any syntax you please, I think I tried most of them...)
```
---
title: Blog
content:
    items:
        '@taxonomy.category': urban
---
```
3. Add an item with the right taxonomy
```
---
taxonomy:
    category:
        - urban
---

Hello World
```
4. Check if it works and it does.
5. Go in backend and go to the blog page.
6. Don't even need to change anything just hit save.
7. The outputted page is now :
```
---
title: Blog
content:
    items: '''@taxonomy.category'': urban'
```
And the listing doesn't work now for obvious syntax problems.

I have no idea how this happens, I thought it had to do with line endings at first, then languages but it is really inconsistent...

**Comment by flaviocopes** [comment]
Mmm, I followed the instructions but I'm still unable to replicate. I also tried downloading and installing a fresh RC. Might be an environment issue. You mention it just happens on Windows, what is the stack used? XAMPP or others?

**Comment by stephanfriedrich** [comment]
i get the same issue

**Comment by pjarts** [comment]
I experience the same problem, but only when I save in "normal mode". If I edit and save in "expert" mode everything works as expected.
