### ISSUE TITLE
Bootstrap not working (collapse feature)

### ISSUE THREAD

**Issue by kelseyurgorenci** [getgrav/grav#1528]
I can't seem to get Bootstrap collapse working. Jquery is already included in the theme and I have pulled in minified js and css for bootstrap in the base.html.twig doc (see screenshot) I have also added screenshot of the html.

What is going wrong here?
<img width="847" alt="screen shot 2017-06-16 at 9 03 07 am" src="https://user-images.githubusercontent.com/24653532/27227736-b0c09dca-5272-11e7-874b-a375e353a27f.png">
<img width="876" alt="screen shot 2017-06-16 at 9 00 16 am" src="https://user-images.githubusercontent.com/24653532/27227735-b0ba65a4-5272-11e7-9d39-0ed777144f34.png">

**Comment by flaviocopes** [comment]
Check if there are errors in the browser JavaScript console. Might be the order of the JS files loaded, or an incorrect bootstrap markup or initialization, but it's not really a Grav issue.

**Comment by kelseyurgorenci** [comment]
Got it. Thanks for the response anyhow.
