### ISSUE TITLE
[add-resource] Fullpage-plugin

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1529]
I would like to add a plugin to the Grav Repository. Here are the project details: [Fullpage](https://github.com/OleVik/grav-plugin-fullpage).

Currently in public beta-testing. Tested with a variety of cases, optimised and tweaked from feedback to simplify use and configuration. NB: The `styles`-setting in blueprints is not implemented, as it will use the new multilevel-field.

The plugin is a wrapper around the fullPage.js-library, and provides a simple way of creating fullscreen slideshows that can be navigated vertically and horizontally. Essentially, it transposes content and settings from Grav to the library. [Docs](https://olevik.me/plugins/fullpage/), [demo](https://olevik.me/plugins/fullpage/book/), and [demo-content](https://github.com/OleVik/grav-plugin-fullpage/tree/demo-content) is available.

**Comment by rhukster** [comment]
Added to GPM, cheers.
