### ISSUE TITLE
permissions problem after install

### ISSUE THREAD

**Issue by robertgarrigos** [getgrav/grav#1530]
I'm trying grav and having a lot of problems with the permissions. The main problem is that grav rely on the fact that the owner of the files is the user running the server. In my case, and I guess in many other, it's not. I run ubuntu 16.04 and, as usual, any file I unzip or download is owned by my user. I manage apache to be a member of the group owner, but that's not enough to run grav. Grav gives write permissions to the user owner only. Even if I change the files permissions to 775, every time I install a plugin or a theme throug terminal they get write permissions only for user owner. Turns grav unusable.

**Comment by robertgarrigos** [comment]
right. found the docs about permissions. So I'm in the third case....mmmm

**Comment by robertgarrigos** [comment]
Unfortunately this is not working yet. I can fix permissions with the shell script provided in the documentation, but just until cache refreshes. Then, I don't have permission to install a theme thru command line, for instance, as the php files under cache/compiled are been created as www-data:www-data with write permission for user owner only. Any ideas to fix this? Thanks

**Comment by paulmassen** [comment]
Did you try this section?
https://learn.getgrav.org/troubleshooting/permissions#cache-folder-permissions

**Comment by robertgarrigos** [comment]
thanks @paulmassen creating the setup.php file fixed it
