### ISSUE TITLE
Is Grav multi threaded?

### ISSUE THREAD

**Issue by msharron** [getgrav/grav#1531]
Just wondering if grav supports multithreading or if im better focusing on clock speed for a development server?

**Comment by rhukster** [comment]
Grav runs in php so really that's a PHP internals question. Generally speaking each request uses a php thread from a pool. So it's not multithreaded per request but can use multiple threads if you have concurrent threads. 

In regards to speed in a general sense, ssd performance is most important followed by clock speed, more cores help with load but don't make things run faster per request.

**Comment by msharron** [comment]
its load im interested in
