### ISSUE TITLE
Creating a custom field that is actually a group of fields

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav#1532]
Is there a way for a plugin to define a custom field that acts like a list field that encompasses other custom fields (e.g. custom list holds two custom child select fields)?  If it helps, I'm attempting to essentially create what's known in Drupal as a field collection for a plugin I'm writing.  Any help would be appreciated.

Thanks in advance.

**Comment by paulmassen** [comment]
What about the [Fieldset Field](https://learn.getgrav.org/forms/blueprints/fields-available#the-fieldset-field) ?

**Comment by flaviocopes** [comment]
Fieldset as suggested by Paul should do the job, if I understood correctly the question.
