### ISSUE TITLE
True single page Application with Grav?

### ISSUE THREAD

**Issue by MrMacStripe** [getgrav/grav#1533]
Hey guys,

I'd like to use Grav for a single page website. However, a blog will be included. I want to be able to link to every article, but it should load the single page and load the article in the div where it is supposed to be + autoscrolling to the section. 

However, my question is how to change the url when you load an article + how to load and display a given article if you direct link it via https://website.org/news/article_1

I know you can somehow do it with AJAX for the URL rewrite in combination with htaccess, but I have no idea how it is done.

**Comment by flaviocopes** [comment]
Hi, Grav acting as the backend is perfectly doable. You can retrieve any blog post as JSON by appending ".json" to it. You have automatic API for content built-in.

Changing the URL is a JavaScript Browser API topic, and you can find tons of tutorials explaining this on Google, it's not a Grav-specific thing.
