### ISSUE TITLE
No way to print asset URLs without protocol.

### ISSUE THREAD

**Issue by stljeff1** [getgrav/grav#1535]
There seems to be no way of printing an asset url such that it leaves off the protocol.

I want to print an image tag like so:

`<img src="//mydomain.com/Path/to/images/myimage.jpg"/>`

**Comment by rhukster** [comment]
There is no way to print a protocol-less URL automatically.  You can either display an absolute URL or a relative one.  If you want protocol-less you will need to build the URL yourself by appending the relative path to the domain.

**Comment by stljeff1** [comment]
Thank you for confirming this... can this be a feature?
