### ISSUE TITLE
Markup is inadvertently escaped

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1536]
With `markdown:  escape_markup: false` set both in system.yaml and default.md, markup is still escaped within elements. For example, `<div id="source">[grav]->[awesome]</div>` will render as `[grav]-&gt;[awesome]`, which seems counter intuitive. I assumed this was related to [ParsedownGravTrait L39](https://github.com/getgrav/grav/blob/cdc6b910cb2f264eb3edf3380668f83d32a52433/system/src/Grav/Common/Markdown/ParsedownGravTrait.php#L39), but even emptying that array has no effect.

Is this intended? Seemingly, escaping is done even when explicitly disabled.

A simple test case, in default.md:

```
<div id="source">[grav]->[awesome]</div>
<script>
    var source = document.getElementById('source');
    var source = source.innerHTML;
    console.log(source);
</script>
```

**Comment by flaviocopes** [comment]
Check `system.markdown.special_chars` - by default it has

```
  markdown:
    special_chars:
      '>': gt
      '<': lt
```

Removing them, the output is unescaped (tested your example)

**Comment by OleVik** [comment]
What is odd is that I can clearly see the effect of `special_chars` when `escape_markup` is `true`, but the effect is still applied with `escape_markup: false` in both system.yaml and default.md, at least for `>` and `<`.

I should note, this is Grav v1.2.4.

**Comment by Sommerregen** [comment]
@OleVik This is because there is no check in [ParsedownGravTrait.php#L48](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Markdown/ParsedownGravTrait.php#L48).
