### ISSUE TITLE
[add-resource] Nomnoml UML Diagrams Plugin

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1537]
I would like to add a plugin to the Grav Repository. Here are the project details: [Nomnoml UML Diagrams](https://github.com/OleVik/grav-plugin-nomnoml-uml-diagrams).

Adds a simple shortcode for rendering UML diagrams, and adds in assets to accommodate. Despite the odd name - apparently stemming from "delicious Unified Modelling Language" - it is a very handy tool for rendering UML-diagrams. One of extremely few such libraries that can display elegant, minimalist diagrams from a simple syntax, sorely missing from almost every other alternative I've evaluated.

**Comment by rhukster** [comment]
Added to GPM
