### ISSUE TITLE
[add-resource] New Plugin: Minify HTML

### ISSUE THREAD

**Issue by jmbelloteau** [getgrav/grav#1539]
I would like to add my new plugin to the Grav Repository. Here are the project details: **https://github.com/jmbelloteau/grav-plugin-minify-html**

**Comment by rhukster** [comment]
Added to GPM

**Comment by jmbelloteau** [comment]
@rhukster thank you !

**Comment by jmbelloteau** [comment]
Hi @rhukster!

I've just try to install the plugin from admin and apparently there is a little problem.

The root folder of the plugin is not properly named.

Actually it's `/user/plugins/minify-html` but should be `/user/plugins/minifyhtml`

Because of this the plugin is not showing/working.

**Comment by flaviocopes** [comment]
The folder is taken from the repo name, it's `grav-plugin-minify-html`, so Grav gets `minify-html`.

Change your main php file and yaml to `minify-html.php` and `minify-html.yaml` and create a new release. The class name is ok.

**Comment by rhukster** [comment]
Actually i can fix via GPM, by setting the 'slug' name.  It's always better to use the same name in your repo as in your local Grav plugin though or it gets confusing :)

**Comment by rhukster** [comment]
fixed for next GPM update

**Comment by jmbelloteau** [comment]
Don't worry @rhukster, I will stick to the default behaviour and make the @flaviocopes modification. This is easy to do 😄

**Comment by jmbelloteau** [comment]
Done!

**Comment by jmbelloteau** [comment]
@rhukster I think we both update and it's broke again ^^
Can you go back to `minify-html` for the next release.

Thank you man and sorry for the misunderstanding.

**Comment by rhukster** [comment]
switched it back for next update.

**Comment by jimblue** [comment]
@rhukster you will hate me lol !

I had to change my github username... sorry... here is the new link... it's the last time promess

https://github.com/jimblue/grav-plugin-minify-html

**Comment by rhukster** [comment]
done

**Comment by TomOne** [comment]
Apparently the `minify-html` plugin was deleted. Is there any alternative?
