### ISSUE TITLE
Extended Theme is Defaulting to Parent Theme on Git Pull

### ISSUE THREAD

**Issue by kelseyurgorenci** [getgrav/grav#1540]
I have not been able to find an answer to this in the documentation and am wondering if it is a bug.

I created an extended theme based on a custom theme I created. When I run a git pull on the live site server from my git repo the default theme is the "parent theme" rather than the selected extended theme.

I am wondering how to configure the extended (child) theme as the default so that I don't have a period of time each time I pull that the site is down until I login and configure to the correct theme?

**Comment by flaviocopes** [comment]
So the system.yaml setting of the default theme is overwritten when you pull?

**Comment by kelseyurgorenci** [comment]
@flaviocopes apologies, please close issue. My system.yaml file for my localhost user had the default theme modified, but not the user config system.yaml file.

My mistake! Thanks for your time.
