### ISSUE TITLE
[add-resource] New plugin: bibleref

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav#1543]
I would like to add my new plugin to the Grav Repository. 

Project details are found at https://github.com/jgonyea/grav-bibleref

Thanks in advance.

**Comment by flaviocopes** [comment]
Hi, can you create a release in the repo? https://learn.getgrav.org/advanced/grav-development#theme-plugin-release-process

**Comment by jgonyea** [comment]
Hi @flaviocopes,
My bad.  I've now added a release to the repo.

**Comment by flaviocopes** [comment]
Thanks!

**Comment by jgonyea** [comment]
This is my first attempt at contributing to something like this, so please let me know if I need to change anything.

Thanks.

**Comment by rhukster** [comment]
I'll get this added to GPM soon.
