### ISSUE TITLE
[add-resource] New Plugin - Admin Addon User Manager

### ISSUE THREAD

**Issue by david-szabo97** [getgrav/grav#1544]
I would like to add my new plugin to the Grav Repository. The plugin is under development but it can be used minimally in its current state. I will update in the following days to be full-featured. Thank you.

https://github.com/david-szabo97/grav-plugin-admin-addon-user-manager
**david-szabo97/grav-plugin-admin-addon-user-manager**

**Comment by rhukster** [comment]
Added to GPM

**Comment by flaviocopes** [comment]
Looks like it's not showing up, the release seems fine https://discourse.getgrav.org/t/where-is-new-plugin-admin-add-on-user-manager/3932

**Comment by rhukster** [comment]
was a copy-and-paste error.. missed the trailing `r`.  Fixed and updated now. Should show up in 'next' update 1 hour from now.
