### ISSUE TITLE
media objects disappear after a reload

### ISSUE THREAD

**Issue by apotropaic** [getgrav/grav#1545]
So, I recently learned about the global media object and tried to use it to pull images from my theme and found a bug in it. I'm not sure if I'm using it wrong or what the deal is. But here are repeatable steps you can do to reproduce it, I just tested this out on a clean develop branch.

1. clone develop branch
2. run bin/grav install 
3. on the antimatter theme add a media object to `templates/default.html.twig` like so: 

```
{% extends 'partials/base.html.twig' %}

{% block content %}
	{{ media['theme://images/logo.png'].html() }}
	{{ page.content }}
{% endblock %}
```

4. Load page of the fresh install - notice the logo on top.
5. Reload the page - logo is gone.
6. Clear cache in admin
7. Reload the page - logo is back.

**Comment by rhukster** [comment]
Ok, a point of confusion here that is probably to blame.  There's a `media` twig variable that is made available in the `processPage()` and `processSite()`. This is a conveincene variable that simply points to `$page->media()` which returns an array of the page's media.

So if you access `media['somefile.jpg]` you are using that.

However, there's also a a `media()` twig function that lets you use streams such as the example above.  This is not directly conflicting with the `media` variable, as the variable is an array and this is a function, but if you use `[]` you are using the variable, and if you use `()` you are using the function.  I think the solution to your issues is to use `()` like:

```
{{ media('theme://images/logo.png').html() }}
```

**Comment by apotropaic** [comment]
Ooh, ok this make sense. But I am unable to get the image to show up at all if I change it to a media function though.

And I did get my info and that snippet from the docs:

https://learn.getgrav.org/themes/theme-vars#media-object

So maybe its wrong there too?

**Comment by rhukster** [comment]
Well, i can reproduce the issue so i'm going to dig in!

**Comment by rhukster** [comment]
@mahagr any ideas on this one.. seems the Twig is just losing all reference to this once cached...

**Comment by mahagr** [comment]
This seems to be a hard one. The entry that causes this issue is the doctrine cached item for `Page\Media`.

**Comment by mahagr** [comment]
Found it out. Media object was serialized, but unserialization was incomplete.

**Comment by apotropaic** [comment]
Awesome that you guys were able to find the bug!

Getting back to my question about the docs, is it correct to use `media['theme://images/logo.png']` like the docs say, or is it supposed to be `media('theme://images/logo.png')` ? From the first reply by @rhukster it seems like the docs are wrong, but currently `media()` doesn't work for me at all

**Comment by rhukster** [comment]
The docs are correct.  I renamed the `media()` twig function which actually works on a directory to `media_directory()` to avoid confusion.

**Comment by klihelp** [comment]
How `media_directory()` works? Gives me this error

```
 Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("Object of class Grav\Common\Page\Media could not be converted to string").
```
