### ISSUE TITLE
contact form stops working after running a while.

### ISSUE THREAD

**Issue by merlinlegratteux** [getgrav/grav#1546]
Hello I have a problem with my contact form. 
The form validation leads to the error page after running a while normally.
Each time I make a correction or I clear the cache, It's working fine and after I while (question of minutes or an hour) It's stops working without any logic explanation. I don't even know where to look for with this strange behaviour!
Any help welcome!
Thanks

**Comment by flaviocopes** [comment]
The latest Form plugin RC (testing) releases should solve this issue. 

In the meantime, add `cache_enable: false` to the modular form (https://learn.getgrav.org/forms/forms/how-to-forms-in-modular-pages#using-forms-in-modular-pages)
