### ISSUE TITLE
Multi-Language copy of existing page

### ISSUE THREAD

**Issue by hellhond** [getgrav/grav#1549]
Hi, 

First of all, I love Grav, it's easy for the end-user, but powerful for us developers.

One usability issue I've encountered is that, in a multilingual site, in the admin, when I add a page in one language, it's not easy to copy that page to another language. E.g. as an easy starting point, incl. parent, template, etc.

As soon as I use the copy function, it's copied for the same language. And the language for the copied page cannot be changed within the admin.

Is this intentional, or just currently not an option ?

I understand that this can be easily copied / changed on the filesystem / user files, but most of our endusers only have access to the Grav admin, and don't have filesystem access.

**Comment by flaviocopes** [comment]
Near the "Save" button there's a drop down menu that lets you save the current page in another language. Is this what you're looking for?

![screen shot 2017-07-04 at 17 28 53](https://user-images.githubusercontent.com/11783388/27836107-5810697e-60de-11e7-8fd2-8c30a758af39.png)

**Comment by hellhond** [comment]
Thank you, did not notice that.
