### ISSUE TITLE
Incorrect link markdown transformation to html

### ISSUE THREAD

**Issue by sthag** [getgrav/grav#155]
![moment_2015-03-14_1426367359_chayd](https://cloud.githubusercontent.com/assets/1476724/6655733/64ab13c2-cb09-11e4-8f7d-2c87293d7272.png)

I use grav 0.9.19
I installed the materialize theme.
I copied the page content from the one-page site skeleton to have some dummy content.
I noticed that there was text missing on the html page.
I did a screenshot. The green lines show the differences.

I cannot reproduce this by using (#) as link.
But wanted to let you know.

**Comment by rhukster** [comment]
Already reported, patched, and merged :)

https://github.com/getgrav/grav/pull/150
