### ISSUE TITLE
[add-resource] New Widget Plugin 

### ISSUE THREAD

**Issue by sojimaxi** [getgrav/grav#1550]
I would like to add my new widget plugin to the Grav Repository.

Here are the project details: [**sojimaxi/grav-plugin-widget**](https://github.com/sojimaxi/grav-plugin-widget)

The plugin works by using modular templates and pages as reusable widgets to be displayed in various page templates.

It's a cool plugin I created to help me with my current project

Thanks
Soji

**Comment by flaviocopes** [comment]
Thanks, you need to make the version in the blueprint match the release tag: https://github.com/sojimaxi/grav-plugin-widget/blob/master/blueprints.yaml#L2 (re-release and make it `1.0.1`

**Comment by sojimaxi** [comment]
Thanks a lot @flaviocopes. The plugin has been updated to version 1.1.0 with a new feature

**Comment by rhukster** [comment]
Added for next GPM update.
