### ISSUE TITLE
[remove-resource] Editable Plugin

### ISSUE THREAD

**Issue by bleutzinn** [getgrav/grav#1551]
I would like to request for the plugin Editable [https://github.com/bleutzinn/grav-plugin-editable](https://github.com/bleutzinn/grav-plugin-editable) to be removed from the Grav Plugins Download page.

The idea of having a generic plugin which uses add-ons did not work out successfully. Also I have dropped the support for the ContentTools editor since it requires content to be in HTML only which causes a lot of confusion amongst.

**Comment by rhukster** [comment]
Removed for next GPM update
