### ISSUE TITLE
[add-resource] Editable with SimpleMDE Plugin

### ISSUE THREAD

**Issue by bleutzinn** [getgrav/grav#1552]
The [Editable with SimpleMDE Plugin](https://github.com/bleutzinn/grav-plugin-editable-simplemde) is the successor of the Editable Plugin.

This new plugin is optimised to use the SimpleMDE markdown editor as the (only) frontend editor. It features frontend uploading of page media and supports caching.

It is currently a pre-release and anyone is encouraged to test an report any [issues](https://github.com/bleutzinn/grav-plugin-editable-simplemde/issues).

**Comment by rhukster** [comment]
Added for next GPM update.
