### ISSUE TITLE
Find dead relative links

### ISSUE THREAD

**Issue by magnetik** [getgrav/grav#1553]
Hi,

We are using grav to build a documentation that has a great amount of relative link, but sometimes we renamed pages manually and so some links are not renamed.

A page to find all (relative) dead links from all content sounds like a nice addition to maintain this.

Is that something you would consider?

Thanks

**Comment by flaviocopes** [comment]
Would be a nice plugin, if someone wants to start tackling this.

Alternatively there are many tools that do this job from a command line command.

For example
- wget
- https://wummel.github.io/linkchecker/
- https://davidwalsh.name/broken-link-checker

**Comment by jgonyea** [comment]
@magnetik I'll see if I can take this on.

**Comment by jgonyea** [comment]
@magnetik Initial work started here
https://github.com/jgonyea/grav-plugin-broken-link-checker
Once I get a few more things off that to-do list, I'll submit it to official gpm.

**Comment by KrakenEXE** [comment]
What is the progress on this?

**Comment by jgonyea** [comment]
@KrakenEXE I haven't had time to finish this. I'll see if can get a working release this week.

**Comment by KrakenEXE** [comment]
@jgonyea Thank you very much. If you need any additional help please ask.

**Comment by stell** [comment]
Too bad this is not official. Is there some alternative within Grav?
