### ISSUE TITLE
Permissions for page listing/search.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#1555]
There is the `access` directive in the frontmatter to dictate if a page is only viewable by someone with certain permissions.

I wonder if it's possible to do the same thing for page listing and search -- that is, when specified, the page only appears in listing/search results if the user has certain permissions; if the user doesn't have these permissions, the page doesn't even appear at all.

Applicable scenarios include: when the user navigates to the home page listing all available pages, or when he tries to search for some keywords and Grav returns a list of results. In any of such scenarios, if the user doesn't have the permissions required in the page, the page simply doesn't show.

For example, if a page should be hidden from search results for users without `search` permission, we can specify in the page frontmatter like:

    search:
        site.login: true

This way, users who have not logged in won't be able to see the page in search results. Similarly, we can do:

    listing:
        site.login: true

**Comment by rhukster** [comment]
There's an `.md` page that is automatically provided by the search plugin, you could override this page with one of your own and put the access requirements in there.

More info on the search plugin repo: https://github.com/getgrav/grav-plugin-simplesearch
