### ISSUE TITLE
[add-resource] AutoSEO Plugin

### ISSUE THREAD

**Issue by laurent-steamlead** [getgrav/grav#1556]
I would like to add my new plugin/theme to the Grav Repository.

Here are the project details https://github.com/steamlead/grav-plugin-autoseo

AutoSEO is a plugin for Grav with which you can fill automatically the description and keyword metadata of a page using its content.

It's a plugin I created because I haven't time to specify the metadata of all the pages of my blog manually.
By default, all the pages have the same metadata (as specified in the site settings). 
And I don't want that (not very good for SEO).

**Comment by rhukster** [comment]
Added to GPM for next update.
