### ISSUE TITLE
After inserting contact-form modular page opens on form

### ISSUE THREAD

**Issue by DimitriSteyaert** [getgrav/grav#1557]
Hi, I have created a site based on the Agency theme and I've added a contact-form by editing the home page.
But when I browse to the site (https://steyaert.be/marleen/) it opens on the contact form part instead of the top of the page.
I have fooled around with the params but I can't seem to find a solution to this. 

This is the content of my homepage in the attached txt file.
[home.txt](https://github.com/getgrav/grav/files/1123059/home.txt)

**Comment by flaviocopes** [comment]
This is likely the issue: one of your form fields has `autofocus: on`, so the browser scrolls down.

**Comment by DimitriSteyaert** [comment]
Hero!
That was indeed the issue, thanks!
