### ISSUE TITLE
[add-resource] grav-plugin-advanced-admin-users-managment

### ISSUE THREAD

**Issue by Moonlight63** [getgrav/grav#1558]
I would like to add my new plugin/theme to the Grav Repository._Here are the project details: **Moonlight63/GravUsersPlugin**

**Comment by rhukster** [comment]
This is not a valid plugin.  It is a set of files that overrides other files in admin. For it to be able to be added to GPM, it needs to be a valid plugin sturcture.  Please see https://learn.getgrav.org/advanced/grav-development#theme-plugin-release-process

**Comment by Moonlight63** [comment]
I'm sorry, I didn't see anywhere on that page that said files couldn't be
overridden. In any case, I don't really know how else to accomplish some of
the functions I've added. There isn't very much documentation on extending
the admin plugin itself, and looking through the source code, I thought
being able to override files was kind of the point of that being possible
in the first place. I couldn't find many event hooks that would allow to
enable some of these features, like hiding pages to certain users. It
doesn't matter. I'll continue development for personal use. I would
appreciate any help from anyone who would know how to structure this
without overriding admin files. I'm just not sure how to do it.

**Comment by Sommerregen** [comment]
Hi @rhukster ,

Can you elaborate on your statement, that this is not a valid plugin? It is never stated to override something. I did a security review of his code. The `CHANGELOG.md` and the `blueprints.yaml` don't have the right format (docs, issue missing etc.), but everything else seems to me ok. It fulfils https://learn.getgrav.org/advanced/grav-development#theme-plugin-release-process and it is nowhere stated to **not** extend other plugins.

Well @Moonlight63 plugin does not comply to PSR standards, but it makes use of all the hooks provided by admin plugin. The only thing I may see critical are the `templates` folder that indeed overwrites something. But that is nothing one cannot fix and doesn't justify to exclude it from GPM (there are already other plugins, that overwrite templates from admin plugin).

**Comment by rhukster** [comment]
Hmm.. to be honest with i'm not sure what happened.

When i looked at this other day, i didn't see any files other than the admin page overrides (https://github.com/Moonlight63/GravUsersPlugin/tree/master/admin/pages)

I was on my phone, so maybe i clicked straight through to the pages folder of the GitHub code view.  I apologize for the hasty comment without investigating further.

No @Sommerregen this was not based on it overriding the admin plugin, it was purely because I didn't see the root of the plugin folder and all the required files were missing, and I only saw those 2 page override files.

Anyway, my mistake! It does appear to be valid, however, being called simply `users` is too generic and is going to cause confusion with the `user` plugin. I suggest that the plugin name (and therefore repo name) be changed to something more specific/unique.

**Comment by Sommerregen** [comment]
Hi @rhukster ,

I totally agree with your points now. Yes, the repository has to be renamed, @Moonlight63 . To comply with Grav standards I propose to name it

https://github.com/Moonlight63/grav-plugin-user-management

and the `users.php` and `users.yaml` to be `user-management.php` and `user-management.yaml` respectively.

**Comment by Moonlight63** [comment]
Perfect, I can do that. When I initially started the project, I never
really intended on releasing it, so there were certain things that I didn't
really "care about." (like the name, lol)
You said the change log and blueprints file are not correct. Could you
please explain that further? I read the learn.getgrav page on releasing,
and I thought I did it correctly. Then again, it was about 3am.... You also
said that the templates folder overriding could be changed..YES PLEASE! How
could I make it so that I don't need to override anything, but just extend?
I kind of just learned by looking at the other plugins that add
functionality to existing admin pages, and they all seem to just override
these files, as you already said. Sorry, I'm trying my best here!

I'll change the name ASAP.

**Comment by Moonlight63** [comment]
Name changed, plus a few smaller updates. New link here: 
https://github.com/Moonlight63/GravAdvancedAdminUsersManagment/releases

I'm still not sure why my changelog and blueprints file are incorrect, but I am going to look at the learn page again and see if I can figure it out.

**Comment by Sommerregen** [comment]
@Moonlight63 ,

They are correct now 👍 . I will probably do a PR (maybe in August, because holidays are coming closer) according to some coding standards. @rhukster Do you might want to have a look now?

**Comment by rhukster** [comment]
Added to GPM for next update.

**Comment by rhukster** [comment]
This has been added, but the name of the plugin in the blueprint is still "Users" which needs to be updated.
