### ISSUE TITLE
Sticky blog posts

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#156]
The option of making one or more blog (child) pages sticky, and always being displayed at the top of a list page could be quite useful. For example, a course site that uses blog pages for weekly class content, and having announcements and/or preparations as sticky posts which are always listed before regular posts. I think that this option would bring a lot of new possibilities to Grav list pages.

In addition, it would be very useful to be able to assign a custom twig template for these sticky posts.

**Comment by rhukster** [comment]
I did something similar to this in the mediator theme by having a **featured** taxonomy type.  These 'featured' posts are displayed at the top of the collection (no matter what page you are on).  See it in action here:

https://github.com/getgrav/grav-theme-mediator/blob/develop/templates/default.html.twig#L37

**Comment by Sommerregen** [comment]
Amazing and simple! Just for completeness. What would be better for the end user: use powerful TWIG extensions or provide an option in the core like what you have already done in the mediator theme?

**Comment by rhukster** [comment]
I really don't see the need to put something so specific in the core when this can be achieved already with taxonomy or another collection query and Twig.
