### ISSUE TITLE
[add-resource] ClickSend Form Notifier

### ISSUE THREAD

**Issue by omarusman** [getgrav/grav#1562]
I would like to add my new plugin to the Grav Repository. Here are the project details:  [ClickSend Form Notifier](https://github.com/ClickSend/grav-form-notifier)

**Comment by rhukster** [comment]
I've added this to GPM for next update

**Comment by omarusman** [comment]
Do we need to do something if we update our plugin? Or it's just automatically fetched by GPM? Thanks.
