### ISSUE TITLE
clearcache destroys whole system

### ISSUE THREAD

**Issue by bwhb** [getgrav/grav#1565]
We are running grav in `/var/chroot/grav.`
Running `/var/chroot/grav/bin` clearcache with `root` privileges in `/var/www` reproducably has the same consequence  like `rm - rf /*`
Very funny...

**Comment by rhukster** [comment]
Well that sounds disturbing. Can you provide some more details or exact steps to reproduce?

**Comment by bwhb** [comment]
what details may i provide? 
running grav 1.1.17 +Apache on Linux test 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux.

**Comment by flaviocopes** [comment]
(Preamble: you should not use that command as `root`)

Question: is that happening also if you run `bin/clearcache` without the full path? Did you customize any stream in the `setup.php` file or is this a clean Grav installation?

**Comment by rhukster** [comment]
I've tested just a `sudo bin/grav clear` without issue, so it's something related to the chroot setup you have there.  Also you should be running this from the root of grav install, so running  it with the absolute path might be the issue.

**Comment by rhukster** [comment]
We have a check in place to ensure that you are running from the root of Grav, is that check just failing or are you doing something to get around it?
