### ISSUE TITLE
case sensitive page\blog url, can it be configured?

### ISSUE THREAD

**Issue by elico** [getgrav/grav#1569]
I have started using grav for a project which uses case sensitive ID's.
Per ID I am creating a blog page ie at user/pages/03.EfGttter/blog.md
and what I was expecting is that I would be able to access the page only using:
`http://hostname/grav/EfGttter`
but from what I see the links created by grav are using only lower case ie:
`http://hostname/grav/efgttter`

I have been searching a in the github issues and didn't found something helpful about this matter and I am not up to dig into the code.
Is it configurable?(can I configure that the name would be case sensitive?)

**Comment by bleutzinn** [comment]
Have you looked at the documentation about [routing](https://learn.getgrav.org/content/routing) and especially about using Route Aliases? You could use unique (UUID?) names for the folder names and distinguish the pages by using an alias.

**Comment by elico** [comment]
@bleutzinn I have looked at the documentation but couldn't grasp it all to understand what would be the right way to resolve the issue.
I will try to look at it today again and update in the next couple days.

**Comment by elico** [comment]
@bleutzinn OK so I found the right way to make it work as I want.
The issue is that by default the route is case insensitive.
What I am using Grav is for an open-source (BSD) product named "YouTube Store".
The admin have the option to add YouTube ID's into a queue that will be downloaded later and will be added to the Grav system as a blog post.
And since it uses the YouTube videos ID as the post name(with a number prefix), by default Grav will use a lower case route such as for:  02.lRSKu21CtCk/blog.md
The path that will be used would be : http://webserver/grav/irsku21ctck
To resolve this issue I use the default route name for the post in the md file.
Example:
```
---
title: Best Of Amazing Chilling Out Music Session - Best Chill Mix 2017 / Tracklist - YouTube
visible: false
routes:
  default: '/ytid/lRSKu21CtCk'
---
```
And then I can access the blog post with the existing uuid which is case sensitive.

Thanks for redirecting me to the docs, it helps a lot to just know the right place to look for a specific tree in a forest.
