### ISSUE TITLE
Debugger Interferes with jQuery?

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav#157]
I have this code in the bottom block of my page Twig Template:
```
<script>
	$(window).load(function () {
		$('img.caption').captionate();
	});
</script>

<!-- Start the mobile menu focus handler -->
<script>
	$(function () {
		$('.category-block li:has(ul)').doubleTapToGo();
	});
</script>
```
Both calls generate `Uncaught TypeError: undefined is not a function` errors. But if the Debugger is turned off, there errors go away and the JavaScript executes as expected.

Is this a problem with the Grav debugger, or the way or location I'm calling my jQuery functions?

**Comment by rhukster** [comment]
When the debugger is enabled, jquery is automatically added. So what your seeing is the situation where your theme is not loading jquery, hence your errors.  The debugger loads jquery, and things work.

**Comment by bobrocke** [comment]
Backwards. Things work with the debugger off!

My block to set up JavaScript loading via `assets.js` looks like this:
```
{% block the_javascripts %}
	{% do assets.add('theme://js/jquery.js', 110) %}
	{% do assets.add('theme://js/captionate.js', 108) %}
	{% do assets.add('theme://js/doubletaptogo.js', 106) %}

	{% if page.header.validate %}
		{% do assets.add('theme://js/parsley.js', 103) %}
	{% endif %}
{% endblock %}
```
With the debugger off, that seems to work just fine; no errors are thrown and the JavaScripts work.

When I turn the debugger on, I get `Uncaught TypeError: undefined is not a function` errors for the two JavaScripts trying to load (`captionate.js` and `doubletaptogo.js`) and no functionality from them.

If I don't load `jquery.js` (yes, I should be using the jQuery distributed in Grav core and I'll switch to that soon), and with the debugger off, I get `Uncaught ReferenceError: jQuery is not defined` errors because no jQuery was loaded. That makes sense; nothing loaded jQuery.

But if I turn the debugger on and let it load jQuery, I still get the `Uncaught ReferenceError: jQuery is not defined` errors!

Can anyone make any sense of that?

**Comment by rhukster** [comment]
Your problem is exactly that your loading your own theme-provided jquery.  Debugger has no way to know what your theme is going to load, so it loads its own. So you get two version of jquery, and then you get errors. You should use the named asset as provided by grav, then the debugger and the theme will not conflict.

The way we had it before, was the debugger assumed the theme added jquery as it didn't do so on it own. Problem here is the debugger woudln't work with a theme that didn't load jquery. 

just update your theme to use the named asset (like all the other themes) and your problem goes away :)

**Comment by bobrocke** [comment]
But this:
```
{% block the_javascripts %}
	{% do assets.add('jquery', 110) %}
	{% do assets.add('theme://js/captionate.js', 108) %}
	{% do assets.add('theme://js/doubletaptogo.js', 106) %}

	{% if page.header.validate %}
		{% do assets.add('theme://js/parsley.js', 103) %}
	{% endif %}
{% endblock %}
```
still throws `Uncaught ReferenceError: jQuery is not defined` and `Uncaught TypeError: undefined is not a function` errors.

`/system/config/system.yaml` says:
```
assets:
  collections:
    jquery: system://assets/jquery/jquery-2.1.3.min.js
```
And that file exists there.

Where else do I need to be looking?

**Comment by rhukster** [comment]
I'm not sure, that should definitely work if your Grav is up to date and has the support for the named jquery asset.

**Comment by bobrocke** [comment]
I does work - if the debugger is off. jQuery loads, the JavaScripts load and execute, and there are no errors thrown. Turn on the debugger and JavaScript breaks. :(

**Comment by rhukster** [comment]
Only thing I can suggest is to look at the source and see if there is any weirdness with how the javascripts are loaded.  Also might be one of the other javascripts breaking the debugging JS. JS is not very good at dealing with an error.  One typo can trickle down and effect other JS files.

**Comment by bobrocke** [comment]
This loads the JS in reverse order of the priorities (captionate.js loads first):
```
{% do assets.add('jquery', 110) %}
{% do assets.add('theme://js/captionate.js', 108) %}
{% do assets.add('theme://js/doubletaptogo.js', 106) %}
```

And this loads them in order of their priorities (jquery first) and fixed the problem!
```
{% do assets.add('jquery', 110) %}
{% do assets.add('theme://js/captionate.js', 100) %}
{% do assets.add('theme://js/doubletaptogo.js', 90) %}
```
Is that expected?

**Comment by rhukster** [comment]
No, both should be in the correct order. Can you create a ticket with that example this information and i'll look at it when i get back next week?  Cheers!
