### ISSUE TITLE
New Release of Grav Creating Errors

### ISSUE THREAD

**Issue by msharron** [getgrav/grav#1570]
Looks like yesterdays release is causing me some issues.  It appears you are using a ' to termiante the meta info in MD files now, which means I get the resulting error.

RuntimeException (500)
Failed to read /home/coventry/public_html/user/pages/01.home/01._why-you-should-choose-us/whychooseus.md: Unexpected characters near " experience in drainage issues.'" at line 14 (near "text: 'The Drainage Coventry team has many years' experience in drainage issues.'").

RuntimeException (500)
Failed to read /home/liverpool/public_html/user/pages/22.sewer-desilting/02.hunts-cross/services-list.md: Unexpected characters near "s Cross'" at line 1 (near "title: 'Sewer Desilting Hunt's Cross'").

**Comment by flaviocopes** [comment]
Hi, this is not a change in 1.3.0 but looks like an issue in your frontmatter, not sure why you didn't get this problem before.

```
text: 'The Drainage Coventry team has many years' experience in drainage issues.'
```

You see, the string is terminated with `'` in the middle. You need to either escape it `\'` or use 


```
text: "The Drainage Coventry team has many years' experience in drainage issues."
```

or remove the containing quote entirely:


```
text: The Drainage Coventry team has many years' experience in drainage issues.
```

**Comment by msharron** [comment]
Yep....somehow it worked a charm till now :)
