### ISSUE TITLE
Update from admin panel failed and minor subsequent issue as a result

### ISSUE THREAD

**Issue by stephenvoisey** [getgrav/grav#1572]
Congrats on 1.3 release folks, keep up the great work. Grav is excellent.

I went to plugins and saw that there was an update to grav available. Hit the button there and got an AJAX error pop up in a red box (Pretty sure that is what it said, sorry, didn't stare at it for too long). The download for the file proceeded, but nothing seemed to happen, so went to CLI and ran self-upgrade. Update installed fine from CLI.

Went back to admin panel and refreshed. A red error popped up saying unable to rmdir /... /assets

The folder had a .gitkeep file in it, but otherwise empty. Ran update for plugins and everything looks fine, so not sure what the AJAX issue was.

Browser was Safari on Mac OS 10.12.5, box is vagrant / vmware hosted local dev in this instance running ubuntu 14.04 / nginx/apache setup via server pilot.

**Comment by stephenvoisey** [comment]
Okay, ran this process again on my other dev vagrant box with a different grav install. Going from 1.2.4 again. Invalid AJAX response pops up after download completed. Nothing happens, download just sits at 100%.

Refreshed admin panel page after gpm self upgrade. Error is: 

rmdir(/srv/users/serverpilot/apps/compassdev/public/assets): Directory not empty

All the best.

**Comment by stephenvoisey** [comment]
Tried to update the plugins on this second box via the control panel instead of the CLI. I had used cli for the self-upgrade of Grav. Going via the admin panel seems to have broken the admin panel install. Going to /admin gives me a 404 error now.

**Comment by rhukster** [comment]
The update package does contain an empty `assets` folder, and this is undoubtedly causing your update issues.  However this is not new and it's no different in this release than in any prior one. Is this the first update you've attempted on these sites?

**Comment by stephenvoisey** [comment]
Hi Andy, no I did an update about a month prior after a long gap to 1.2.4 I think it was. No problems at the time. Honestly can't recall if i did it via command line though, probably did, which doesn't show any errors during upgrading. I reinstalled the admin panel to fix the last 404 issue. All working fine now.

**Comment by damienwebdev** [comment]
After discussing this on Slack, I've been reliably able to repeat this on a Windows 10 system. To me at least, it looks like on Windows rmdir doesn't remove dot-folders.

With a base grav instance, add a dependency for https://github.com/getgrav/grav-plugin-assets

Do the following:

```
php bin/grav install
php bin/gpm update -o
```

See the following error:

```
  [RuntimeException]
  rmdir(/user/plugins/assets):
  Directory not empty
```

**Comment by sojimaxi** [comment]
@damienwebdev @rhukster  I think a Windows fix for this should be made for `rmdir()`
I experienced this as well today when upgrading a plugin from admin that was installed via `bin/grav install` from `.dependencies` . I had to manually delete the `.git` folder within the plugin before I could upgrade the plugin. 
`bin/grav`  clone repos while `bin/gpm` download releases.

**Comment by mahagr** [comment]
Is anyone able to get a backtrace on the issue? I've looked through google and it looks like that the hidden folders should already have been taken into account when deleting the folders.

Unfortunately, I don't have Windows computer to play with, which makes it a bit hard to debug this issue.

**Comment by OleVik** [comment]
From previous issues, taken from memory, this would be because any file is locked by a process in Windows. Thus not explicitly a permissions-issue, but rather indirectly. If PHP's rmdir() is told by Windows that the file is busy, it will throw the error. Busy in this context simply means that some process is "locking" the file "obstructively", which quite a lot of software tends to do. Elevated or reassigned permissions will not solve this from any terminal until the process is terminated.

Don't have time to try a replication before next week, but I suspect the deletion of files prior to attempting to deleting the folder is unsuccessful silently, or that a process is still accessing some file - could even be PHP itself.

**Comment by mahagr** [comment]
Yeah, that is what other sources propose as well. In Linux/OSX removing the file just removes its "name", which basically allows processes to keep the file open even after it was deleted. Or in other words, you can delete opened files without getting any errors or bad behavior. Windows doesn't have this behavior, so it cannot delete opened files.

But what comes to `.git` file, I don't think that Grav uses that file for anything and thus, it shouldn't be open. Unless of course there's git running somewhere.

This also doesn't explain why some people got similar error in OSX or in Linux.

**Comment by dirtroof** [comment]
I'm running a dev version on OS X and a live version on Linux. Both are hooked up to .git using the GitSync plugin. Both give me the `AJAX error` when I click upgrade GRAV. How to fix?
