### ISSUE TITLE
Markdown list parse error after update

### ISSUE THREAD

**Issue by ay-b** [getgrav/grav#1580]
Hi.
I've updated recently to the latest Grav and markdown list parsing got broken.

![](https://3.downloader.disk.yandex.ru/disk/82547112f9ef3f095f6a848997ca93000c0ee14e7e4e86d1317e707f9e4de384/5972158e/t6Cj5Br-ugki2THLWxvdkzv2tcQxkECyFoRytRLJKLqt31dMsQ_j8uyUFOKBNVnmNeiuNP7C-_fGiZVBx4UrBA%3D%3D?uid=0&filename=2017-07-21_13-51-52.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=148672&hid=137a30f1f69952e803bca6e4cff33dcc&media_type=image&tknv=v2&etag=aa81023dcd22bb117ff8f18d584df9f3)

List of installed plugins:
 AdSense v1.1.1
 Error  v1.6.0
 Feed  v1.6.2
 Google Analytics v1.4.0
 Google Maps v1.0.7
 Yandex Metrika v1.0.0
 Pagination  v1.3.2
 Problems  v1.4.7
 Resize Images v0.2.2
 Shortcode Core  v2.6.0
 SimpleSearch  v1.12.0
 Taxonomy List  v1.2.7

Active theme: Striped (Skeleton).

If I click "preview" button in the edit form — everything is fine. But saved topic is missing a correct parsing.

I've downloaded the fresh version of the parsedown.php and replaced the local one, but it didn't help.

Any suggestions?

**Comment by flaviocopes** [comment]
Hi, the image seems broken to me, I can't see the content - can you re-post it?
