### ISSUE TITLE
How can I delete the default error page - but it does not exist in the backend

### ISSUE THREAD

**Issue by AlexL777** [getgrav/grav#1581]
Hello Developers,

I have decided again for the GRAV CMS and see that in the frontend at https://cmsblogger.de a default error page is linked in the navigation.

This page does not exist. In which template I have to remove it because it does not look nice and I do not need this page.

Thanks in advance.

**Comment by flaviocopes** [comment]
Hi, the error page is provided by the Error plugin: https://github.com/getgrav/grav-plugin-error

You can override it with an empty template in your theme: https://github.com/getgrav/grav-plugin-error#template
