### ISSUE TITLE
[add-resource] New Plugin: grav-plugin-social-feed

### ISSUE THREAD

**Issue by moduleon** [getgrav/grav#1583]
I would like to add my new plugin to the Grav Repository:

https://github.com/moduleon/grav-plugin-social-feed

This plugin gives the ability to fetch posts from Facebook, Twitter, and Instagram (for now), and save them locally (it also download media). For that you need to use a cli tool, that you can call in a crontab for example. 

All configuration, for social networks apis, or accounts to follow are directly administrable from the dashboard in the plugin configuration form.

It also gives twig function to get those posts from a twig template (for server templating), and an api entrypoint (for dynamic browser templating), both handling pagination, filter and order directives on posts.

**Comment by flaviocopes** [comment]
Thanks! When creating a new release, also change the version in the blueprint: https://github.com/moduleon/grav-plugin-social-feed/blob/master/blueprints.yaml#L2 (make a new release to fix this)

**Comment by moduleon** [comment]
My bad, this has been fixed. 

https://github.com/moduleon/grav-plugin-social-feed/commits/v0.1.1

**Comment by rhukster** [comment]
This has been added to GPM for next update
