### ISSUE TITLE
Line 37 in nginx.conf (webserver-configs) causes error

### ISSUE THREAD

**Issue by vseow** [getgrav/grav#1585]
Output of `nginx -t`:

nginx: [emerg] "fastcgi_index" directive is duplicate in /etc/nginx/sites-enabled/example.com:70
nginx: configuration file /etc/nginx/nginx.conf test failed

Ran on PHP 7.0.18 on nginx 1.10.3

**Comment by w00fz** [comment]
It probably is duplicate if you have `fastcgi_index` in the global config as well.
However I don't see it being duplicate in the nginx.conf we provide.

/ [referenced conf file](https://github.com/getgrav/grav/blob/develop/webserver-configs/nginx.conf)

**Comment by Pyton** [comment]
You may have `fastcgi_index` in `/etc/nginx/fastcgi_params` file.

**Comment by vseow** [comment]
Thanks for the replies everyone but it looks like this line `fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;` was causing the issue for me

**Comment by D3m0nKingx** [comment]
Posting for future reference it is also referenced in : ```/etc/nginx/snippets/fastcgi-php.conf```
If you have your configuration setup with:
```
include snippets/fastcgi-php.conf;
fastcgi_index index.php;
```
You will encounter this error because  `fastcgi_index index.php;` is already in fastcgi-php.conf
