### ISSUE TITLE
Cant move pages in grav-admin

### ISSUE THREAD

**Issue by rnks** [getgrav/grav#1586]
When trying move some doc page to another parent folder/chapter grav says: "Successfully saved" but page doesn't move

**Comment by flaviocopes** [comment]
Is this a default page type, or a page with a custom blueprint?

**Comment by pahdom1** [comment]
We have installed rtfm skeleton and pages type is "doc"

**Comment by pahdom1** [comment]
Was installed a clean rtfm sceleton (https://github.com/getgrav/grav-skeleton-rtfm-site) with the following plugins:
Admin Panel  v1.5.1
Anchors  v1.5.1
Breadcrumbs  v1.5.0
Email  v2.6.0
Error  v1.6.0
Form  v2.8.0
Highlight  v1.3.1
Login  v2.3.2
Problems  v1.4.7
SimpleSearch  v1.1
 
We have that tree (see attachment (tree.png))
For example:
When we try to transfer "backulainstall" into "HOWTOS" - > "Windows" we got an message about success but nothing more.
![tree](https://user-images.githubusercontent.com/25930605/28582738-295b1984-716f-11e7-8cf4-bddbc96d9397.PNG)

**Comment by rhukster** [comment]
This really should be in the Admin issues btw: https://github.com/getgrav/grav-plugin-admin/issues

**Comment by rhukster** [comment]
Closing here as you have opened in the correct repo.
