### ISSUE TITLE
RTL doesnt work in grav

### ISSUE THREAD

**Issue by Aki-vito** [getgrav/grav#1587]
I cant find a way to activate rtl in the admin plugin.

**Comment by flaviocopes** [comment]
I'm afraid Admin is not RTL ready, yet. Linked issue: https://github.com/getgrav/grav-plugin-admin/issues/359

**Comment by rhukster** [comment]
You could test this PR: https://github.com/getgrav/grav-plugin-admin/pull/1054

I've asked for this to be updated to latest Admin version, but it still merges.
