### ISSUE TITLE
.size() action won't do anything

### ISSUE THREAD

**Issue by Kangouroops** [getgrav/grav#1588]
Hello, 

Latest grav version.

Following this doc:
https://learn.getgrav.org/content/media#sizes-with-media-queries
I was trying to use the `.size()` action to render `srcset` attribute, but it doesn't seem to output any specific html.

Here is the img call:
`{{ page.media[slide.image|first.name].cropZoom(1440, 900).html('', slide.text) }}`

I tryed to add (code copy/pasted from the doc)
- `.sizes('80vw')`
- `.sizes('(max-width:26em) 100vw, 50vw')`
But nothing is outputted in the html.

I tryed to remove `.cropZoom(1440, 900)`, but still, the `srcset` are not ouputted either.

Is it a bug or is it just me not understanding the `.size()` action ?

**Comment by flaviocopes** [comment]
I tried and I could no get it to work as well. 

I found you need to associate it with higher-quality image alternatives, or derivatives https://learn.getgrav.org/content/media#sizes-with-media-queries-using-derivatives

**Comment by Kangouroops** [comment]
> I found you need to associate it with higher-quality image alternatives, or derivatives 

Perfect ! Thank you for your help.
