### ISSUE TITLE
[add-resource] Updated grav-theme-medium

### ISSUE THREAD

**Issue by mblode** [getgrav/grav#1590]
I would like to add my updated Medium theme to the Grav Repository but the newest release isn't showing up. It could have something to do my deletion of v2.0.3 because I had made an error._Here are the project details: **mblode/grav-theme-medium**

**Comment by w00fz** [comment]
2.0.5 seems to be showing up fine on the website https://getgrav.org/downloads/themes
Is this resolved?

**Comment by mblode** [comment]
Awesome! How often does Grav themes/plugins look for updates? Or could it have been cached when I viewed the page?

**Comment by w00fz** [comment]
GPM right now updates once a hour only and it's not immediate. It starts updating the first half hour of each hour, 24/7.
