### ISSUE TITLE
set headers by page

### ISSUE THREAD

**Issue by jrivero** [getgrav/grav#1591]
Hi, I need set the cache-control header by page, and I think it would be interesting to have an option on page frontmatter to set any other headers, similar than meta settings

**Comment by flaviocopes** [comment]
You can set the `expires` property in the page frontmatter, and it will be used by Grav:

```

        // Calculate Expires Headers if set to > 0
        $expires = $page->expires();

        if ($expires > 0) {
            $expires_date = gmdate('D, d M Y H:i:s', time() + $expires) . ' GMT';
            header('Cache-Control: max-age=' . $expires);
            header('Expires: ' . $expires_date);
        }
```

**Comment by rhukster** [comment]
Oh that's embarrassing! It's my code too!  We definitely need to document that as I had forgotten about it :)

**Comment by jrivero** [comment]
It's fantastic news to be able to define an expiration time, I have to try it!

However I think it is also important to be able to define if the page is cachable (public, private, etc). @rhukster could make us a little patch :)

**Comment by rhukster** [comment]
done!
