### ISSUE TITLE
Insufficient password popup does not work on Safari

### ISSUE THREAD

**Issue by cragun47** [getgrav/grav#1592]
**Brief description**
When entering an insufficient password, the pop-up error message does not display when using the Safari browser.  Thus, on a new installation of grav-admin (grav with admin plug-in) the first step of creating an admin user through the admin panel seems to the user to fail.  The user does not know the password is insufficient, keeps trying to successfully create a user, but the user is never created.

**Environment:**
Host:  x10 hosting.  Apache-based shared service.
Host Apache: 2.4.18
Host PHP: 5.5.36
Host architecture:  linux on x86

**Client Computer**
OSX: Sierra 10.12.3
Safari: Version 10.0.3

Steps:
1. Upload grav-admin-v1.3.0.zip file; unzip on server.
In this case the directory is not the root directory of the site, but rather a sub directory of the site.
2. In Safari browser, point at to the base directory of grav installation.
Directory: www.mysite.com/Documents/grav2/grav-admin

3. When accessing the base directory of grav for the first time, user correctly is routed to the admin screen to create the first user.  www.mysite.com/Documents/grav2/grav-admin/admin

4.  The admin dialog appears

5. Type in an insufficient password  and tab to the next field, No error message is displayed (Image below).
<img width="964" alt="screen shot 2017-07-24 at 10 52 59 pm" src="https://user-images.githubusercontent.com/4914849/28574213-859ccd74-710a-11e7-8f14-bc6f6ce1c275.png">

An error message should appear if the password is not acceptable the minute that field loses focus. 

6. Type is the same insufficient password in the second password field.  A message is not displayed on leaving the second field. (Image below)
<img width="870" alt="screen shot 2017-07-24 at 10 53 31 pm" src="https://user-images.githubusercontent.com/4914849/28574291-bbda40f6-710a-11e7-9aac-9940029c4ed1.png">

7.  Fill in the rest of the information and Press Create User. There is a little bit of a flash (like the page gets reloaded) and the save password prompt appears at the top of the browser (image 3). The form is totally refreshed and the user must fill in the form again. A .yaml file has not been created.

<img width="940" alt="screen shot 2017-07-24 at 10 53 48 pm" src="https://user-images.githubusercontent.com/4914849/28574371-040eb2d0-710b-11e7-92da-2913e67d1f98.png">

See also [background discussion in discourse forums](https://discourse.getgrav.org/t/grav-in-a-shared-host-environment-admin-directory-htaccess-not-found/4167/8)

**Comment by rhukster** [comment]
Pretty sure this is fixed in latest develop branch of Grav Admin - https://github.com/getgrav/grav-plugin-admin/commit/05a6abd794de7891a2b8bdc0270800a68b72e033

BTW, this was brought up in admin plugin issues - https://github.com/getgrav/grav-plugin-admin/issues/1129
