### ISSUE TITLE
what are the page directory and file name limitations? where can I find documentation on this?

### ISSUE THREAD

**Issue by elico** [getgrav/grav#1593]
I encountered an issue with the page directory names.
I have an automated script that creates page id's and it automatically generates the pages posts.
I have a scenario which I am using an external ID and it happens to have "_xyz" as the id.
Now the result is that the page directory name would be:
grav/user/page/04._xyz/blog.md

and grav doesn't "know" about the page and I cannot see or access this page.
ie http://servername/grav/_xyz/
would result with 404 page.
But if I am changing the directory name to:
grav/user/page/04.z_xyz/blog.md

It will work fine with:
http://servername/grav/z_xyz/

Is it a bug? is there any documentation on these limitations? if yes or no, where can I see these?

**Comment by rhukster** [comment]
Folders with underscore is considered a 'module' page in Grav: https://learn.getgrav.org/content/modular#example-folder-structure

This means they are treated as sub-pages to be used in a parent page. That's why you cannot access it.

**Comment by elico** [comment]
Thanks!
