### ISSUE TITLE
[add-resource] New Plugin : grav-plugin-amazon-products

### ISSUE THREAD

**Issue by kinformation** [getgrav/grav#1596]
I would like to add my new plugin/theme to the Grav Repository._Here are the project details: **https://github.com/kinformation/grav-plugin-amazon**

This plugin displays Amazon products by ASIN/ISBN-10 on your pages.

**Comment by w00fz** [comment]
This looks good, I just wonder if the plugin should be called more specifically as 'amazon-products', instead of the the very generic 'amazon'.

Without looking at the readme i thought this was about aws, hence my confusion.

**Comment by BarryMode** [comment]
Cool, thanks for sharing this @kinformation!

**Comment by kinformation** [comment]
@w00fz
Thanks for the suggestion! I will change it.
Indeed it seems better to have **amazon-products** rather than **amazon**.

**Comment by kinformation** [comment]
I changed the plugin name and repository name.

https://github.com/kinformation/grav-plugin-amazon-products

**Comment by rhukster** [comment]
Thanks, i'll get this added soon.

**Comment by rhukster** [comment]
Added.
