### ISSUE TITLE
[change-resource] : grav-plugin-users-page-ownership

### ISSUE THREAD

**Issue by Moonlight63** [getgrav/grav#1599]
I would like to add my new plugin/theme to the Grav Repository._Here are the project details: Moonlight63/grav-plugin-users-page-ownership

This is an update/change to my previous plugin. I have removed the users management functionality since david-szabo97 has been doing a great job with his plugin, including getting group management to work. I have instead decided to simply expand on the idea of users 'owning' pages and admins being able to manage who can see and edit pages. 

I renamed my old repo before I thought about it, because I wanted to change the name of the plugin. That's why this is under 'change-resource.' The original repo was under grav-plugin-advanced-admin-users-managment, which is now gone. I apologize if that was a mistake.

**Comment by rhukster** [comment]
This has been done.
