### ISSUE TITLE
is page.siblings valid grav collection call?

### ISSUE THREAD

**Issue by drnasin** [getgrav/grav#1601]
when I try to access page.siblings in twig I get "null" but If I use this workaround it works.

` {% set options = { items: '@self.siblings'} %}

  {% set siblings = page.collection(options) %}`

Shouldn't page.siblings also return the same thing or did I misunderstood something in the docs?

**Comment by rhukster** [comment]
There isn't actually a `Page::siblings()` method at all.  You can however get all the siblings with `page.parent.children`, this does include the current page however, so you would have to check or remove that manually.

The alternative approach you have is also valid as the sibling calculation and removal of current page is handled in the `Page::collections()` method, you can make it a one liner too:

```
{% set siblings = page.collection({ items: '@self.siblings'}) %}
```

Which is much more palatable, and frankly very readable.

**Comment by drnasin** [comment]
excellent! makes sense now 🙂thank you for clarification!
