### ISSUE TITLE
Does Grav support Cyrillic slugs?

### ISSUE THREAD

**Issue by MaksymJ** [getgrav/grav#1602]
Hi,

Does Grav support Cyrillic slugs?
when i try to use Russian language (for example: `контакт`) in slug, i get 404 error page ...
for example `www.mydomain.com/контакт` throws 404 error ... 

Best Regards,
Maksym

**Comment by rhukster** [comment]
It does not support Cyrillic slugs. As there are no official rules, we went with what most software requires:

* Only latin alphanumeric characters and `-` for spaces.
