### ISSUE TITLE
How to increase the page media size

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav#1603]
some error is appearing while uploading files in page media section.

Can you suggest a solution for this issue?
![media](https://user-images.githubusercontent.com/25584016/29072150-32940da8-7c64-11e7-91e9-45abd84b75d2.png)

**Comment by dansku** [comment]
You need to increase the post_max_size on your php.ini configuration. It is a server configuration and not really a grav one. 

Look up on how to change the php.ini depending on your hosting/server.

**Comment by geogeorgejoseph** [comment]
ok
