### ISSUE TITLE
Support Twig custom paths and namespacing

### ISSUE THREAD

**Issue by mikecrittenden** [getgrav/grav#1604]
Namespaces are a very useful concept in Twig. You can see the Symfony implementation here: https://symfony.com/doc/current/templating/namespaced_paths.html#registering-your-own-namespaces

Any chance of adding support for them in Grav? Something like a `twig_paths:` property in the theme YAML that defines paths and the namespaces for them, perhaps? 

(I'd also appreciate any pointers in setting this up manually via a plugin, because messing with `Twig_Loader_Filesystem::addPath()` has proven to be difficult.)

**Comment by rhukster** [comment]
I have added preliminary support for this with a new event `onTwigLoader()` and two new methods in Twig class: `Twig::addPath($path, $namespace)` and `Twig::prependPath($path, $namespace)`.

For backwards compatibility, the loader is initiated as normal with the `$twig_paths` array that has been manipulated and added to by other plugins.  The loader event happens after this loader is initiated, and has these paths already added.  

This means you can add your own paths with namespaces and use them directly such as:

```
    public function onTwigLoader()
    {
        $this->grav['twig']->addPath(__DIR__ . '/blah/templates', 'blah');
    }
```

Then:

```
{% include '@blah/bar.html.twig' %}
```

However, nothing has changed in the core of Grav, and all the standard page templates, and 3rd party plugin templates are still using the default `main` namespace.

**Comment by mikecrittenden** [comment]
This rocks, thanks Andy!

**Comment by EvanLovely** [comment]
@mikecrittenden Nice work 👊

**Comment by mikecrittenden** [comment]
@EvanLovely 😢

**Comment by EvanLovely** [comment]
@mikecrittenden :pray:
