### ISSUE TITLE
Set headers on page frontmatter

### ISSUE THREAD

**Issue by jrivero** [getgrav/grav#1609]
Hi!

I have some issues with google analytics on amp pages and I have found a tested solution, but it is necessary to set some headers. I thought about programming a plugin, but I think it would be interesting to incorporate a option for set headers from page frontmatter (https://github.com/getgrav/grav/issues/1591) in the core because amp is something increasingly important.

Google Analytics Client ID In AMP Pages:
https://www.simoahava.com/analytics/google-analytics-client-id-amp-pages/#wp

**Comment by rhukster** [comment]
All rendered output is left to the theme.  If you wanted to automatically output some headers, then it should be done in a plugin, not in Grav core.
