### ISSUE TITLE
[add-resource] New Skeleton - Open Publishing Space

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#1610]
I would like to add this new skeleton package to the Grav Repository. Open Publishing Space is designed to publish, share and collaboratively edit Markdown-based content. Includes Admin Panel and Git Sync plugins.

https://github.com/hibbitts-design/grav-skeleton-open-publishing-space

Thanks very much,
Paul

**Comment by rhukster** [comment]
Added to GPM

**Comment by paulhibbitts** [comment]
Excellent, thanks Andy!
