### ISSUE TITLE
Error: No space left on device? --> Site/Admin broken

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#1616]
Grav 1.3.2 / Admin 1.5.2
Run into an error a few days ago:

![error](https://user-images.githubusercontent.com/12480617/29577290-29670728-876b-11e7-97d8-d8ae84511b7a.png)

Site broken couldn't login into admin. 
After ssh login and clearing cache (which was really huge) everything was working again.

So why did this happen? Never had that kind of issue before. Grav cache is disabled in my system.yaml ???
Shouldn't grav/twig cache be cleared automatically after a certain time???

BTW: My Webhosting Space is 75 GB!

**Comment by rhukster** [comment]
when a cache expires and recaches, or something changes, the old files are not removed, just new files are created with a new hash (as deleting files is slow).  You should periodically clear out your cache folder either manually or with a cron job that does it every few weeks or so. 

A Gav **clear all** should delete the directories so you can start fresh.

**Comment by axel-rank** [comment]
yes, but why is there a cache generated if I disabled it in system.yaml?
Not quite sure yet, but the issue might have something to do with grav-plugin-admin-addon-revisions.
Since install of this plugin my grav install size grew to over 100 MB. Normally it was about 48MB.
As I said I never had that issue before. I'll check. I uninstalled all 'non-grav' plugins.
