### ISSUE TITLE
<p> containing <h2>

### ISSUE THREAD

**Issue by the4thamigo-uk** [getgrav/grav#1617]
This simple markdown file : 

```
---
title: Some page
---
## A heading
```

Is rendered as : 

```
<h1>Some page</h1>
<p>
	<h2>A heading</h2>
</p>
```

As I understand it `<p>` elements should not contain `<hN>` elements and this fails in the W3C HTML Validator with : 

```
Error: No p element in scope but a p end tag seen.
```

**Comment by mahagr** [comment]
Seems to be issue with the used theme, which theme were you using?

**Comment by the4thamigo-uk** [comment]
It is a modified learn2.

**Comment by the4thamigo-uk** [comment]
Ok I think I see it in chapter.html.twig

```
{% extends 'docs.html.twig' %}

{% block content %}
	<div id="chapter">
    	<div id="body-inner">
			<p>
				{{ page.content }}
			</p>
		</div>
    </div>
{% endblock %}
```

**Comment by mahagr** [comment]
Create a new issue to the proper project :)

https://github.com/getgrav/grav-theme-learn2

**Comment by the4thamigo-uk** [comment]
Ok thanks

**Comment by the4thamigo-uk** [comment]
https://github.com/getgrav/grav-theme-learn2/issues/63
