### ISSUE TITLE
Starting a local PHP server deletes system/router.php

### ISSUE THREAD

**Issue by 95jonpet** [getgrav/grav#1627]
When downloading v1.3.2 of Grav and starting the php webserver (on Windows) with `php -S localhost:8000 system/router.php` The server appears to start, but on the first request to `localhost:8000`, the server dies without any errors and proceeds to delete the `system/router.php` file.

At this point, it is impossible to restart the server again, and a complete reinstall does nothing to fix the issue. Updating packages also does not appear to help.

I am on PHP 7.0.8 if that has anything to do with it, although I doubt it.

**Comment by rhukster** [comment]
This is not a problem with Grav or the router as it definitely does work with PHP 5.6.31, 7.0.22, 7.1.8 as i've just tested it.  More likely you have something else running on port 8000.  Try another port, like 8888.

**Comment by 95jonpet** [comment]
The problem is not that it refuses to start, the problem is that the actual executable is destroyed in the process. There are no errors from PHP, and it listens for requests until it removes router.php upon the first response.

**Comment by rhukster** [comment]
It really has to be something on your end.  There's nothing in Grav that could remove the router.php file.  Perhaps it's some security script that thinks the router.php is malicious, or some virus scanner. I'm not sure. If you try it on another non-windows machine it will work.  

BTW, it does work fine also on my windows 10 computer, but i don't have anything fancy installed.  Long story short, it's not Grav its something on your machine that is doing this.

**Comment by 95jonpet** [comment]
I can confirm that this is due to Avast flagging the router.php file as a virus.
