### ISSUE TITLE
Grav Slack badge in GitHub ReadMe's not displaying anymore

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#1628]
I've noticed that the Grav Slack badge in GitHub ReadMe's not displaying anymore - for example:

![2017-08-29_13-09-44](https://user-images.githubusercontent.com/1812771/29841738-705ef6fe-8cbb-11e7-99bf-d84650c8e07b.png)

I've got some installed in my own Grav skeletons where I first noticed the issue.

Thanks very much,
Paul

**Comment by rhukster** [comment]
I noticed this but hoped it was a temporary glitch, looks like its a bigger issue.  I'll see if there's an alternative, else i'll remove the slack button.

**Comment by paulhibbitts** [comment]
Thanks Andy, I did some initial investigation myself but did not come up with anything. If I do I will also let you know.

**Comment by rhukster** [comment]
I know what this is, it's actually being generated by a little node app that seems to have stopped running.  I've asked @w00fz to look at it as he set it up.

**Comment by paulhibbitts** [comment]
Thanks very much for looking into it!

**Comment by rhukster** [comment]
Sorted!

**Comment by paulhibbitts** [comment]
Awesome, thanks very much! It's a really nice touch🙂
