### ISSUE TITLE
Custom README.md file

### ISSUE THREAD

**Issue by NAYZO** [getgrav/grav#1636]
Hello,
How can I have my own README.md file for my project (each time I do an update of grav cms, all my edits in this file are lost and overwriting by the grav readme source file) ?

Thank you for advance.
Best regards.

**Comment by paulhibbitts** [comment]
If you locate it within the `user` folder (like with a Skeleton) it should not be over-written, at least that is how I've been doing it:

https://github.com/hibbitts-design/grav-skeleton-open-publishing-space

**Comment by NAYZO** [comment]
Thank you for your response, but in that case it wouldn't be automatically shown in the homepage of the versioning host repository like github, gitlab, ...

**Comment by rhukster** [comment]
It will if you only push the `user/` folder into your repo. It is not really a best-practice to push your entire grav site into github as you are storing lots of files that are purely Grav core, and not your custom pages/plugins/themes.

The Grav `README.md` file is part of the Grav distribution. There might be a way to change this via GitHub, but i don't think so.
