### ISSUE TITLE
navigation links include webroot full absolute path...

### ISSUE THREAD

**Issue by masavini** [getgrav/grav#1637]
hi,
i extracted the latest grav+admin zip on a shared hosting, inside `/home/cadgx10h/public_html/` folder.

the site only has 2 pages (/home, and /cadg) and they work fine, but navigation links are in the form 'http://cadg.x10host.com/home/cadgx10h/public_html/cadg'.

those links work as well, but i'm afraid i missed something in the system configuration...

**Comment by rhukster** [comment]
Check the `absolute_urls:` option in your `user/config/system.yaml` - if it's `true` it will show the full URL.

**Comment by masavini** [comment]
it's set to `false`...

**Comment by rhukster** [comment]
That's really the only way it could be doing that.  Do you have a local config perhaps in `user/localhost/config/system.yaml` ? that is overriding it?

**Comment by masavini** [comment]
i don't have `user/localhost` folder: i have `system/config/system.yaml`, but `absolute_urls` is `false` as well...

**Comment by rhukster** [comment]
The only other thing i can think of is that the theme you are using is at fault.  Normally the `partials/navigation.html.twig` (or whatever is outputting the nav in your theme) uses a `.url()` method to output the URL of the page, perhaps your theme has `.url(true)` which would output the absolute path.

**Comment by masavini** [comment]
i'll take a look, but i'm using the default theme and i did not change anything... thanks anyway...

**Comment by masavini** [comment]
no way... i tried with a fresh install, added one page and the issue is still there.
tried the same on c9.io and issue is NOT present...

i also noticed that the x10host.com installation gives a 'invalid security token' problem, while c9.io does not...

could the issues be related?

**Comment by rhukster** [comment]
Definitely sounds like a hosting thing.  I've never seen this particular issue and I can't recreate it on my local or on my couple of test remote sites.  Perhaps its worth contacting the hosting provider to see what they say?
