### ISSUE TITLE
install fails when root contains blank

### ISSUE THREAD

**Issue by cord** [getgrav/grav#164]
am running on MacOS

my local "webroot" is called "MAMP ROOT" with a blank

when running the installer I get following issue and the page does not load with "Theme 'antimatter' does not exist, unable to display page."

$ bin/grav install
....

sh: line 0: cd: /MAMP: No such file or directory
SUCCESS cloned https://github.com/getgrav/grav-plugin-problems -> /MAMP ROOT/grav/grav//user/plugins/problems

**Comment by rhukster** [comment]
if you rename to `MAMP_ROOT` all works correct? it's specifically this space in your folder name?
