### ISSUE TITLE
Strange behavior on ordering collection

### ISSUE THREAD

**Issue by tboulogne** [getgrav/grav#1640]
Hello,

I get an annoying problem. I set a field (price with float type [1.16]) in header.
``
price: 1.16
``

In php code i make :
``
$collection->order(‘header.price’,“asc”);
``

All prices are not sort in “asc” direction. I got 2.44 before 1.497 :frowning:
(it’s seems to work well with desc…)

PHP command **gettype** give double for **header.price** type. Good for sorting, but does not work.

Any idea to workaround this strange behavior ?

Thanks for help,

Regards.

**Comment by tboulogne** [comment]
Rah :)

I think i got it 👍 
``
$collection->order('header.price','asc',null,SORT_NUMERIC);
``

Changing the PHP flag it works :-).

**Comment by rhukster** [comment]
Marked for documentation.
