### ISSUE TITLE
What's new in grav 2

### ISSUE THREAD

**Issue by niahoo** [getgrav/grav#1643]
So I can see that you are wworking on a version 2.0. Is there any place that I could see a roadmap or a list of intended features ?

I'm starting to build a project right now and I want to get exciting news :)

Cheers.

**Comment by rhukster** [comment]
I was just discussing this with @mahagr last week.  We were discussing scope and a plan of attack for 2.0.  We're still working on these discussions, so as soon as we have a solid outline of what 2.0 will entail, and our plan for continuing to improve on 2.0, we'll document it in the form of a blog post at least, and perhaps in the docs too.

**Comment by niahoo** [comment]
Great :)

**Comment by drnasin** [comment]
Guys, do you need any more hands on 2.0? Willing to help if needed...

**Comment by mahagr** [comment]
More hands are always welcome if you have ideas for improvements.

So far most of the 2.0 branch does is to add some new base classes which can be used in Grav and plugins -- the classes are used in some private projects, but I still need to find time to implement them in Grav itself.

**Comment by drnasin** [comment]
can you tell me what was the idea behind 2.0?Some new major workflow improvements? New features?

**Comment by mahagr** [comment]
There's really no idea in the branch, it's just a bunch of classes which aren't used or not ready to be included in the current version of Grav.

**Comment by rhukster** [comment]
This is something we need to get a better handle on.  We've been so busy lately that we've not had much chance to really nail down what we want for 2.0.  Or at least it's been a bit fluid, and we still need to nail it down.  We'll discuss this as a team and post something.

**Comment by drnasin** [comment]
I understand @rhukster. What I would do (but that's just me) is to allow advanced users and "average joe" (but longtime) users to chip in with their ideas for improvements.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav/issues/1767

**Comment by niahoo** [comment]
Great, thank you :)
