### ISSUE TITLE
existing posts with page.summary went wrong after update to 1.3.3

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav#1644]
After updated to `1.3.3`, exisiting posts with `page.summary` function went wrong for me: it has been now cutting before `===` page summary delimiter: please find details below.

This is due to version 1.3.3 `CHANGELOG` [here](https://github.com/getgrav/grav/blob/develop/CHANGELOG.md)

New `page.summary` now cut at `===` delimiter BUT with count HTML tags so that it's now too short for me.

Removing the following part of `1.3.3` code by previous version `1.3.2` solved the issue:
line 522 of `\system\src\Grav\Common\Page\Page.php`
```
if (mb_strwidth($content, 'utf8') > $summary_size) {
                return mb_strimwidth($content, 0, $summary_size);
            } else {
                return $content;}           
```
by
```
return mb_substr($content, 0, $summary_size);
```

Sorry, I don't have sufficient technical `php` skills: please, help.

Here the structure of my `.md` file for more information:
```
some header with parameters:
summary:
    enabled: true
    format: short
    size: 0
---

! わたしたちが今日ふつう「女大学」と呼んでいるのは、
! この書の本文を受けついで編まれた教順書類である。<---This is page summary in japanese  

===  <--- This is page summary delimiter

##概要 <--- This is rest of page content in japanese
```

**Comment by rhukster** [comment]
I will look into this tomorrow.

**Comment by tidiview** [comment]
Thanks. I'll have a look tomorrow then

**Comment by rhukster** [comment]
Please try the fix above.
