### ISSUE TITLE
[add-resource] New Plugin/Theme (Owl-Carousel2)

### ISSUE THREAD

**Issue by tomntech** [getgrav/grav#1645]
I would like to add my new plugin/theme to the Grav Repository._Here are the project details: https://github.com/tomntech/grav-plugin-owl-carousel2/releases/tag/v1.0.0

The **Owl-Carousel2** for [Grav](http://github.com/getgrav/grav), when enabled, adds the required dependencies to the pipeline for [Owl-Carousel2](https://github.com/OwlCarousel2/OwlCarousel2) to work. The plugin exposes the common settings, along with default values, as per Owl-Carousel2.

**Comment by rhukster** [comment]
Does this simply add the CSS/JS to the pipeline?  There's already a shortcode plugin that does this but does more because it also adds a shortcode that make it easier to use.

**Comment by tomntech** [comment]
It does indeed, I wasn't aware of the existing plugin - during my search I missed it in the list (my fault). As my plugin doesn't add anything beyond the functionality of the one that already exists I will delete it.
