### ISSUE TITLE
Yaml Multiline text in frontmatter

### ISSUE THREAD

**Issue by njxqlus** [getgrav/grav#1646]
```
---
test: |
multi 
line
text
---
```
When use {{ page.header.text }} error appear:
```
Failed to read .../user/pages/01.home/_test/test.md: Unable to parse at line 2 (near "multi ").
```
I use last version of Grav from git clone install.

`>` symbol didn't work too

**Comment by iusvar** [comment]
Using `|` or `>` you should indent in the lines of your text, for example:
```
---
test: |
    multi 
    line
    text
---
```
as demonstrated in the first response in  https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiplelines

**Comment by njxqlus** [comment]
@iusvar Thank you, my friend.
I was confused about this, because when I copy-paste my text it's already have some spaces before it.
Now I try shift+tab in my editor and make indent again and it's work fine right now.
Spend some hours for this, thank you again!
