### ISSUE TITLE
Grav 0.9.21 - Image Path Issue

### ISSUE THREAD

**Issue by HOFB2015** [getgrav/grav#165]
Hi

So I updated Grav from 0.9.20 to 0.9.21 since doing this update no images on the site are appearing.

Debug has C:/MAMP/htdocs/user/pages/02.wallpapers/2-dark-wallpapers/_image\2_Dark_Wallpaper_01.jpg

Just before the image a \ is appearing instead of /

If I dis-regard the changes (via git) and go back to Grav 0.9.20 everything works fine and the debug shows the path as C:/MAMP/htdocs/user/pages/02.wallpapers/2-dark-wallpapers/_image/2_Dark_Wallpaper_01.jpg for the same image which is displayed fine.

**Comment by rhukster** [comment]
Should be sorted in Grav 0.9.22+
