### ISSUE TITLE
how to include certain partials based on page header ?

### ISSUE THREAD

**Issue by bluis4** [getgrav/grav#1653]
Hi,

i have 2 modular pages lets say 01.home and 02.other, with both pages have subpage _header. in the header.md file, i have title header "home" and "other". In the modular template header.html.twig, i want to include partials button.html.twig and card.html.twig. the button.html.twig should only show at home page and the card.html.twig should only show at other page.

i tried using
{% if page.header.title == home %}
{% include 'partials/button.html.twig' %}
{% else % %}
{% include 'partials/card.html.twig' %}
{% endif %}

but only partials card.html.twig that showed on both home and other page. is something wrong with the code ? Read both grav and twig documentation but still can't make it work.
Is it possible to do this ?

**Comment by paulhibbitts** [comment]
Hi @bluis4,

I've done something pretty similar, but used page.slug for simplifying the name check, e.g.:
`{% if page.header.slug == home %}`

**Comment by bluis4** [comment]
Hi,

thanks for fast answer. Both solution works like a charm. Thank you :)
