### ISSUE TITLE
[remove-resource] Delete OER Content Space Skeleton

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#1654]
With the release of my new Open Publishing Space skeleton and revised documentation, I'd like to have my (very similar) Gantry-based skeleton OER Content Space removed from the getgrav.org site:

https://github.com/hibbitts-design/grav-skeleton-oer-content-space

I will continue to offer direct downloads of this skeleton for a period of time, and as well all the Gantry Particles I created for it.

Thanks very much,
Paul

**Comment by rhukster** [comment]
will remove this soon.

**Comment by KrakenEXE** [comment]
Update please?

**Comment by rhukster** [comment]
its done.

**Comment by paulhibbitts** [comment]
Thanks Andy!

**Comment by paulhibbitts** [comment]
Hi @rhuk , the OER Content Space Site skeleton seems to still be listed on https://getgrav.org/downloads/skeletons, is that intentional? I'd like to remove it from the getgrav.org site altogether. Thanks!

**Comment by rhukster** [comment]
Uggg.. i committed it but didn't push.. Done so now.

**Comment by mitchellkrogza** [comment]
There's some problems going on with Travis and they responded to me with this message "During the week of September 25th-29th, we’re at a company-wide offsite, working on new features and improving Travis CI. While we’ll be checking email daily, our response times may be delayed." my particular problem is builds running for 6+ hours and never ending as per their 50 minute build timeout
