### ISSUE TITLE
GRAV and ANSIBLE: Must be run from ROOT directory of Grav

### ISSUE THREAD

**Issue by stephanfriedrich** [getgrav/grav#1655]
Hi thx for Grav i realy like it.
im trying to install grav via ansible an i got these issue after running a test.

`php -C -f /www/grav/bin/gpm`

dont know how to fix it

**Comment by stephanfriedrich** [comment]
actually i fixed it by run following command:

`cd /www/grav && bin/gpm`

**Comment by rhukster** [comment]
Yup was about to reply with the same. :)

**Comment by stephanfriedrich** [comment]
thx for your fast response
