### ISSUE TITLE
JS Pipeline do not work for {% block javascript_footer %}

### ISSUE THREAD

**Issue by MaksymJ** [getgrav/grav#1659]
Hi,

i'm using Gantry 5, and in particles, the scripts are written in `{% block javascript_footer %}...{% endblock %}`. **JavaScript pipeline** doesn't work for footer scripts.
It works only for scripts which are in header, written in `{% block javascript %}...{% endblock %}`
how to make it work for footer scripts? i can't find anything about it in docs.

Best Regards,
Maksym

**Comment by mahagr** [comment]
All the latest versions of Gantry do call `{{ assets.js('bottom')|raw }}`, which should automatically deal with the pipelining. The only scripts that do not get pipelined are those which you add in `Page Settings` > `Before </body>` as it accepts any tags, not just scripts.

Gantry also always sets the pipeline parameter to true in `Assets::AddJs()` function.

@rhukster Any idea on this one?

**Comment by rhukster** [comment]
Just make sure the theme doesn't infact have a bottom javascript similar to this:

```
{% block bottom %}
    {{ assets.js('bottom') }}
{% endblock %}
```

**Comment by mahagr** [comment]
The first Grav versions of Gantry didn't have this line, but it was added a long time ago. But I tested it out and it doesn't seem to use pipelining even if it should (files are added individually).

**Comment by rhukster** [comment]
I'll double check with pipeline on a non-g5 theme today and get back to you.

**Comment by rhukster** [comment]
I can confirm that with regular Grav (no Gantry5 enabled) JS pipeline will properly pipeline the bottom JS (if you use that example format I put above at least).

I think you need to test this with G5 specifically @mahagr
