### ISSUE TITLE
Add a pull request to https://staticsitegenerators.net

### ISSUE THREAD

**Issue by balupton** [getgrav/grav#166]

**Comment by rhukster** [comment]
Grav is not a static generator. It's a dynamic flat-file CMS, so we probably wouldn't make this list.  Thanks for the thought though!

**Comment by balupton** [comment]
@rhukster no worries, listing does support flat-file CMSs: https://github.com/jaspervdj/static-site-generator-comparison#requirements-for-additions - Grav would be accompanied by others like [yellow](http://datenstrom.se/yellow/) in that list. Perhaps we'll add a tag to indicate what types they are.

**Comment by rhukster** [comment]
I did not know that! Going to reopen this then!

**Comment by rhukster** [comment]
b843b8c7acd72574d9966ddbec177c2d0fc3d60d
