### ISSUE TITLE
Changing the defaulted CDN for Pure to something more up to date in the new theme generated file

### ISSUE THREAD

**Issue by KrakenEXE** [getgrav/grav#1661]
Currently the defaulted cdn for pure in a new theme page ::
http://yui.yahooapis.com/pure/0.6.0/pure-min.css

However we could use this instead since they recommend it::
https://unpkg.com/purecss@1.0.0/build/pure-min.css

**Comment by rhukster** [comment]
Where are you changing this? Are you talking about the devtools plugin? If so, this issue should be raised there, or better yet, edit the file and submit a PR.

**Comment by KrakenEXE** [comment]
Understood. I'll submit a pull request there! Thank you.
