### ISSUE TITLE
Block code "fences" not working properly

### ISSUE THREAD

**Issue by imcrypticcoder** [getgrav/grav#1663]
While adding cpp code using block code fences rendered page HTML broken. Please try adding this line of cpp code:

```cpp
#include <list>
```

**Comment by rhukster** [comment]
Aside from the lack of syntax highlighting (as the included highlight plugin doesn't provide CPP support) it looks fine:

![2017-09-28 at 6 11 am](https://user-images.githubusercontent.com/1084697/30965832-067366c4-a414-11e7-885c-7f7ac8b1acce.png)

It would help if you were more descriptive of the issue you are seeing.

**Comment by imcrypticcoder** [comment]
grav-plugin-hightlight uses highlight.js which supports C++ according to their live demo.
https://highlightjs.org/static/demo/

Anyway that HTML broken problem solved. Now having another problem. Code/Text missing while showing rendered code by highlight plugin. This happens when only part of code is showing. Supoose your blog page showing few posts partly with "Continue Reading... " button below. Here is my screenshot:

<img width="1130" alt="screen shot 2017-09-28 at 9 38 56 pm" src="https://user-images.githubusercontent.com/1979225/30976681-38f954ae-a497-11e7-8d92-1bb31c6a0396.png">

**Comment by rhukster** [comment]
The highlight plugin doesn't have the FULL highlight.js, it has a custom package with most of the standard languages, but CPP is not one of those. You can build your own and simply replace the JS file: https://highlightjs.org/download/

Your issue with the 'summary' view is that by default this will count a certain number of characters, and then close any HTML tags if still in some nested HTML.  To get around this you can either manually set the summary size on this page:  https://learn.getgrav.org/content/headers#summary

or

You can use the manual summary break indicator:

```
your **summary** up here.

===

This will only be shown when viewing **content**
```

**Comment by imcrypticcoder** [comment]
I will try to replace by original highlight.js.
I have tried by adding manually break indicator. Didn't work. Will it work inside of code ?

**Comment by imcrypticcoder** [comment]
1. I replaced by latest highlight.js (9.12.0) file in Highlight plugin folder with same name "highlight.pack.js". Nothing improved.
2. I have tried manually summary break indicator inside code and it didn't work. :(

I have check this issue with 2 theme and their skeleton project and got same results. These are the themes:
a. Deliver
b. Gravstrap Theme 

Reproduction Steps:
1. Download theme skeleton and install admin
2. In any blog item add code with the cpp code mentioned above.
3. Go to Blog page and notice some type distortion in the page.
4. In case of Deliver right sidebar expand to whole page and others problem after that segment of code.
5. In case of Gravstrap Theme same distortion occurred.

**Comment by rhukster** [comment]
Please always test with Antimatter theme. It's the default theme and it's what we use as the testing baseline.

**Comment by rhukster** [comment]
Ok first things first, syntax highlighting... 

Your example above is with GitHub's code highlight (not the same as highlight.js) I looked at the highlight.js demo page for C++ and the include was not highlighted, but the rest was... I didn't even update the `highlight.pack.js` at all, just left it with the default JS that comes with the current release and used the same code as the demo:

![2017-09-28 at 1 14 pm](https://user-images.githubusercontent.com/1084697/30985968-372c8cec-a44f-11e7-8937-9ae518752651.png)

As you can see it's highlighting perfectly fine.

**Comment by rhukster** [comment]
Second, the summary stuff:

This is my page, notice the manual summary separator:

```
---
title: 'Atom vs. Coda3?'
slug: atom-vs-coda
publish_date: '07/18/2015 02:54 pm'
taxonomy:
    category:
        - blog
    tag:
        - coda

---

One of my complaints about Coda was the lack of an [EditorConfig](http://editorconfig.org) plug-in allowing preferences to be set for indentation style and size (Tabs: 3, for example) by file type. I had offered the idea as a feature request to Coda’s development team and tweeted about the need for it, but it hadn’t reached the top of their priority list yet.

```cpp
#include <iostream>

int main(int argc, char *argv[]) {

  /* An annoying "Hello World" example */
  for (auto i = 0; i < 0xFFFF; i++)
    cout << "Hello, World!" << endl;

  char c = '\n';
  unordered_map <string, vector<string> > m;
  m["key"] = "\\\\"; // this is an error

  return -2e3 + 12l;
}
```

===

One of my complaints about Coda was the lack of an [EditorConfig](http://editorconfig.org) plug-in allowing preferences to be set for indentation style and size (Tabs: 3, for example) by file type. I had offered the idea as a feature request to Coda’s development team and tweeted about the need for it, but it hadn’t reached the top of their priority list yet.
```

Then in my blog view it looks like this:

![2017-09-28 at 1 23 pm](https://user-images.githubusercontent.com/1084697/30986355-5c520f8c-a450-11e7-9c69-ea3bcebb1c6f.png)

Then in my actual post page it looks like this:

![2017-09-28 at 1 24 pm](https://user-images.githubusercontent.com/1084697/30986381-729bcac6-a450-11e7-9302-f7e367ea1ba6.png)

This seems to be a non-issue to me.

**Comment by imcrypticcoder** [comment]
Hi rhukster, Thanks for detail explanation. I have done some other test according to your exposition.
1. When summary seperator used outside code and full code shown as summary, issue doesn't  happen.
2. Summary seperator don't work inside code. So when long code needed to be summarized, issue happen. Would you please try by using your existing small code twice with seperate code tag or below code in the provided link.

This is actual code I am trying to show in my page with auto summary. [My Actual Code](https://github.com/imcrypticcoder/CompetitiveProgramming/blob/master/Solved%20Problems/UVA/10000%20Longest%20Paths.cpp)

**Comment by rhukster** [comment]
You can't put a summary separator inside a code block. Everything in side that code block is considered code, and is not processed.  The regex that looks for it won't care though and it will break the HTML, so don't do it! :) . 

I think we're done here, you just need to tweak your content, or your separator length, or both. But there is no fundamental issue.
