### ISSUE TITLE
[add-resource] New Plugin - TinyMCE Editor Integration

### ISSUE THREAD

**Issue by newbthenewbd** [getgrav/grav#1666]
I would like to add my new plugin to the Grav Repository. Here are the project details: **[newbthenewbd/grav-plugin-tinymce-editor](https://github.com/newbthenewbd/grav-plugin-tinymce-editor)**

**Comment by rhukster** [comment]
Nice! Will add this soon.

**Comment by rhukster** [comment]
Added to GPM. should show up soon

**Comment by newbthenewbd** [comment]
Thanks!
