### ISSUE TITLE
[add-resource] New Plugin/Theme: FetchWP

### ISSUE THREAD

**Issue by cpannwitz** [getgrav/grav#1668]
Hey friends.

I would like to add my new plugin/theme to the Grav Repository. Here is the project repo: [https://github.com/cpannwitz/grav-plugin-fetchwp](https://github.com/cpannwitz/grav-plugin-fetchwp)

Main functionality is to fetch and display posts from the Wordpress REST Api. 
It includes several settings to featured media and more. Also a standard template for displaying them via Twig function.

If there are any issues, I'll try to solve them.

**Comment by rhukster** [comment]
Added to GPM. should show up soon

**Comment by rhukster** [comment]
I think there's a problem with you labeling the tag/release as `v0.6.0`, the blueprints is correct with `0.6.0`, but you should tag the release without the "**v**". It's in GPM, but it's not showing up because of this.

**Comment by cpannwitz** [comment]
Oh, sorry. Updated it. 
First time releasing something :S

Thanks for putting it on GPM :)
