### ISSUE TITLE
Tried installing grav in sub-folder called blog  Redirect to admin = not found

### ISSUE THREAD

**Issue by limenleap** [getgrav/grav#1669]
My installation of grav is in a sub-folder from the root. I installed grav-admin and did everything as instructed

when i go to http://../blog it redirects to 

http://../blog/admin 

But it says not found!
I am using a Caddy server on Ubuntu 16.04 with PHP 7.0

**Comment by rhukster** [comment]
You need to get your redirects sorted.

First check our docs: https://learn.getgrav.org/troubleshooting/page-not-found

However, Caddy requires a config file.. you can see the one provided by Grav for reference: https://github.com/getgrav/grav/tree/develop/webserver-configs

Also hop on our slack channel, there are peeps on there that use Caddy and can help you: https://chat.getgrav.org/
