### ISSUE TITLE
gpm selfupgrade error in there's no update available

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav#167]
I upgraded to Grav v0.21.0 using `bin/gpm selfupgrade` with no problem. To be sure it had "stuck" through a Git branch head change, I ran `bin/gpm selfupgrade` again and got this error:

```
 [Whoops\Exception\ErrorException]     
 Trying to get property of non-object 
```
I assume that was because there was nothing to upgrade? If so the `Nothing to update.` response that `bin/gpm update` generates was expected.

**Comment by rhukster** [comment]
Fixed for 0.9.22
