### ISSUE TITLE
Showing 404 error page after upgrade to latest version

### ISSUE THREAD

**Issue by andrekutianski** [getgrav/grav#1671]
After upgrade grav to v1.6.2 I receive a 404 error page after try update a page. Grav save the update on the page, but display a 404 error page

![page not found documentation eunarede](https://user-images.githubusercontent.com/5316107/31049151-54fb5dba-a603-11e7-876a-9b47041e5e02.jpg)

**Comment by rhukster** [comment]
Are you all up to date with plugins + Grav itself?  What webserver are you running with?  I can't replicate this so I don't think it's a widespread issue.

**Comment by rhukster** [comment]
Also is there anything special about your pages? what plugins are you running? can you try disabling the non-grav-team ones?

**Comment by andrekutianski** [comment]
I have restored the last backup and updated again, all up and running! Perhaps the package downloaded was corrupted?

**Comment by rhukster** [comment]
I've tested the update process myself and no one else has had issues, but maybe your download was not complete or something.  Have you tried updating again?

**Comment by andrekutianski** [comment]
Yes, I update again and the 404-page error does not show anymore

**Comment by rhukster** [comment]
sweet, closing.
