### ISSUE TITLE
Markdown syntax for superscript and subscript

### ISSUE THREAD

**Issue by imcrypticcoder** [getgrav/grav#1672]
Does **Grav** possess any markdown syntax for **superscript** and **subscript**? I didn't find anything in Grav markdown syntax doc. 
In case it's not available till now, is there any plan to add this support ?

**Comment by rhukster** [comment]
We're using parsedown which provides the GFM variety of markdown, which does not currently support this... However it's easy to just mix in some HTML:

```
This is some <sup>superscript</sup> text.

This is some <sub>subscript</sub> text.
```

This is some <sup>superscript</sup> text.

This is some <sub>subscript</sub> text.

**Comment by imcrypticcoder** [comment]
How about **Grav** adopts markdown syntax like **Beegit** markdown syntax.
https://beegit.com/markdown-cheat-sheet
