### ISSUE TITLE
No formdata template in Antimatter theme

### ISSUE THREAD

**Issue by Xarkam** [getgrav/grav#1675]
I read the doc and in the form creation page, it says that you must have a file called formdata (templates / formdata.html.twig)
This file does not appear in the theme.
I quote from the documentation:

> The formdata page template is provided in Antimatter and other themes. If your theme does not provide it, you'll see an error. You can just copy it from Antimatter and things should work fine.

![image](https://user-images.githubusercontent.com/331816/31114758-e58740d8-a81f-11e7-9290-0dfd5dca159d.png)
![image](https://user-images.githubusercontent.com/331816/31114795-08398280-a820-11e7-869a-f330ca18cbeb.png)
Could you update the documentation if this file is no longer in use?

Thanks.

**Comment by paulmassen** [comment]
Hi, 

This template is actually from the form plugin, you can find it in user/plugins/form/templates.
https://github.com/getgrav/grav-plugin-form/blob/develop/templates/formdata.html.twig

**Comment by Xarkam** [comment]
Thank for your response :)

**Comment by KrakenEXE** [comment]
Close.

**Comment by KaiLuettmann** [comment]
The documentation seems not to be updated. See "https://learn.getgrav.org/forms/forms/how-to-forms-in-modular-pages"
