### ISSUE TITLE
Backup the system before updating grav system

### ISSUE THREAD

**Issue by mattlickess** [getgrav/grav#1676]
Hello,
would it be possible to make that before updating the grav system to the latest version, there would be a backup file of all the system ? On the macs there is a thing such as folder overrides folder, and doesnt keep any files inside the folder which you created by your own. Could it be at least an option when you pressing update where it would ask, would you like to back it up first? or something like that. That option could be enabled and disabled somewhere in the settings.

Thanks for any answer, and have a nice day!

**Comment by axel-rank** [comment]
Install the [grav plugin backup manager](https://github.com/leotiger/grav-plugin-backup-manager)

**Comment by KrakenEXE** [comment]
Close or update.
