### ISSUE TITLE
[remove-resource] Delete ePortfolio Blog skeleton

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#1677]
With the continued uptake of new Open Publishing Space skeleton and revised documentation, I'd like to have my (again very similar) Gantry-based skeleton ePortfolio Blog removed from the getgrav.org site:

https://github.com/hibbitts-design/grav-skeleton-eportfolio-blog

Thanks very much,
Paul

**Comment by rhukster** [comment]
@paulhibbitts did I do this? :)

**Comment by paulhibbitts** [comment]
Hi @rhukster , a few weeks ago you removed the old OER Content Space skeleton, but this is a request to remove the **ePortfolio Blog** skeleton. I've done enough work now on my new Open Publishing Space skeleton to replace both of those older projects🙂

Thank you!

**Comment by rhukster** [comment]
Removed for next GPM update.

**Comment by paulhibbitts** [comment]
Excellent, thank you Andy!
