### ISSUE TITLE
Translate page title via admin panel

### ISSUE THREAD

**Issue by openscript** [getgrav/grav#1678]
Is it possible to make the page title or any other field translatable for admin panel users?

For example I want that my users, which use the admin panel, can translate the page title into different languages. Or another example, a static text in the footer? Is there something like a multi-language form element type?

How would you tackle this?

Thank you in advance!

**Comment by openscript** [comment]
My solution is to capture all text blocks on a special page with a special blueprint and access the data later with `{% set textblocks = page.find('/textblocks').header %}` in the templates.

**Comment by rhukster** [comment]
It's actually very possible without changing anything.. Just create a `user/languages/en.yaml` (or whatever) then override the lang string like:

```
PLUGIN_ADMIN:
  DASHBOARD: Dartsboard!
```

**Comment by openscript** [comment]
Sorry I didn't formulate my question correctly. I want that the user, which cannot change yaml files, can change the translation. e.g. some static text in the footer. I think the separate page is the most pragmatic solution, right?

**Comment by emukaevo** [comment]
> It's actually very possible without changing anything.. Just create a `user/languages/en.yaml` (or whatever) then override the lang string like:
> 
> ```
> PLUGIN_ADMIN:
>   DASHBOARD: Dartsboard!
> ```

Hi there, 
Please I need help for the same issue. I have the same problem. I did all that  is explained here but in my header doesn't appear any change and translation for english language. Appears just the default language wich is Italian language. Title and description of header are in site.yaml file. But I have no idea how to make possible to translate everything that appears in site.yaml file. How to deal with that? Any idea Please?
