### ISSUE TITLE
How to show collection of taxonomy other than "category" or "tag"

### ISSUE THREAD

**Issue by chrisbeckstrom** [getgrav/grav#1679]
I'm not sure if this is a theme question (I'm using twentyfifteen) or a grav question.

Bottom line: I want a URL like
'mygrav.com/series:cool'
to show all the pages with a taxonomy of series set to "cool"

this works out of the box for categories, like 
'mygrav.com/category:things'
but i can't figure out how to do it for taxonomies i've added myself. looking at the documentation and trying to examine the code too, i can't quite understand how grav knows what to do with 'category:something'

do i need to make a new template?

sorry if this is a real basic thing or if i missed a similar issue somewhere else!

grav is awesome, thanks for your hard work!

**Comment by rhukster** [comment]
You need to add the `series` taxonomy type to the `site.yaml` configuration file: https://learn.getgrav.org/content/taxonomy#taxonomy-example

Then you have to understand that filtering by a taxonomy is just that, a filter, it needs to filter out a larger collection into a smaller one.  So you need to make sure that whatever collection you have have defined for your main page, it includes the `series` you are going to filter. 

For example in the blog-skeleton, the collection filters all the pages of `category: blog` but the taxonomy list filters this list further using `tag`.

Make sense?

**Comment by chrisbeckstrom** [comment]
ahhh yes that totallly makes sense! thanks so much @rhukster. i had everything correct except the folder that contained the pages i wanted included in my custom taxonomy was not a child of my main page/folder. moved it there and it immediately worked.

great stuff, thanks so much for your help! grav is the best thing since beer growlers :-)

**Comment by rhukster** [comment]
👍
