### ISSUE TITLE
404 when processing [grav.txt](grav.txt)

### ISSUE THREAD

**Issue by nirokato** [getgrav/grav#168]
I have a file called **grav.txt** sitting in `/var/www/grav/user/pages/01.blog/raspberrypi-powered-by-grav/` and I want to link to it using Markdown.

File permissions are as follows for the text file:
`File permissions: -rw-rw-r-- 1 niro www-data 1343 Apr 8 18:14 grav.txt`

nginx is running as www-data and is already displaying the page item.md file correctly.

In the item.md of my website [http://nirokato.com/blog/raspberry-pi-powered-by-grav](http://nirokato.com/blog/raspberry-pi-powered-by-grav) I link to the text file using `[grav.txt](grav.txt)` which can be seen toward the bottom of the page. 

This creates the HTML link `http://nirokato.com/blog/raspberry-pi-powered-by-grav/grav.txt` 
When clicked it gives a 404.

> **Note:** This may also affect .html extensions as well.

access log
```
65.x.x.40 - - [08/Apr/2015:20:42:21 -0700] "GET /blog/raspberry-pi-powered-by-grav/grav.txt HTTP/1.1" 404 1147 "http://nirokato.com/blog/raspberry-pi-powered-by-grav/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
65.x.x.40 - - [08/Apr/2015:20:42:22 -0700] "GET /user/themes/antimatter/css-compiled/nucleus.css.map HTTP/1.1" 304 0 "http://nirokato.com/blog/raspberry-pi-powered-by-grav/grav.txt" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
65.x.x.40 - - [08/Apr/2015:20:42:22 -0700] "GET /user/themes/antimatter/css-compiled/template.css.map HTTP/1.1" 304 0 "http://nirokato.com/blog/raspberry-pi-powered-by-grav/grav.txt" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36"
```

**Comment by rhukster** [comment]
This is now fixed in the develop branch. Will be in the next release.
