### ISSUE TITLE
Menu items in site.yaml cannot open in a new tab

### ISSUE THREAD

**Issue by jpgklassen** [getgrav/grav#1680]
It doesn't seem possible to configure menu items in site.yaml to open in a new tab. Can we make this possible? Perhaps by adding `?target=_blank` to the end of the URL?

**Comment by rhukster** [comment]
really this is just a matter of editing the theme to do it as the links are output by the theme.  For example, with Antimatter theme, it's in the `templates/partials/navigation.html.twig` file:

https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/navigation.html.twig#L42
