### ISSUE TITLE
Consider forking Parsedown Extra

### ISSUE THREAD

**Issue by tadeas** [getgrav/grav#1684]
The upstream repository was last updated two years ago: https://github.com/erusev/parsedown-extra  and there are 45 open issues and 14 pull requests right now.

For example, I've just fixed an issue I discovered when using Grav. I'd love the fix to land in Grav, but since the Parsedown Extra upstream does not respond, I'm not sure what's the right way to proceed.

**Comment by rhukster** [comment]
Yes, I know it's not been updated in some time, and there are lots of bugs with it.  I really have no interested in forking it myself as I already have 100+ repos i have to maintain.  Have you considered forking it yourself and fixing other bugs? If you do i would consider pointing grav's "parsedown extra" repo to yours.

Just FYI, i would actually love to just drop parsedown extra, but we keep it for backwards compatibility reasons.  With Grav 2.0 we might even switch to another library if a better one is available.
