### ISSUE TITLE
multilingual sitemap alternate links

### ISSUE THREAD

**Issue by rauwebieten** [getgrav/grav#1685]
I am aware of the current limitations of the translated urls  (#522)

Even more, the user guide on using language specific domains with /htaccess redirects adds on more redirect to the chain.
(https://learn.getgrav.org/content/multi-language#setup-with-language-specific-domains)

This can be problematic: some crawlers do not allow redirects inside sitemaps.
http://www.johnfdoherty.com/google-sitemaps-ask-for-clean-urls/ 
http://www.redirect-checker.org/how-many-redirects.php

**Comment by rhukster** [comment]
This is not something that can really be changed easily at the Grav level. It's really something that should be solved at the sitemap plugin level I think.

**Comment by rauwebieten** [comment]
The same issue raises in the langswitcher plugin: the alternate links link to the raw-route of the page, not the URL with the custom translated slug.

for example, I have this URL structure:
example.com/en/domain-names
example.com/fr/noms-de-domaines
example.com/nl/domeinnamen

When I open the source code of the english page, the alternate links meta tags point to these URL's:
example.com/en/domains
example.com/fr/domains
example.com/nl/domains
which are the raw-route (domains is my folder name of this page) URL's of the translated pages. When you visit this page, Grav sends a 302 redirection to the URL with the correct slug.

In the generated sitemap, I see the same: All alternate links point to the raw-route versions.

This might be a problem, as I read several articles about bots not following URL's in sitemaps which have redirects.

More problems might occur, when you use the language specific domains. Grav is not aware of these different domains. The suggested setup in the docs is to use rewrite rules with htaccess:
example.com/en/* -> en.example.com/*
example.com/fr/* -> fr.example.com/*
example.com/nl/* -> nl.example.com/*

So, for example the URL `example.com/fr/domains` tested by a searchbot:
1. apache .htaccess redirects first to fr.example.com/domains  (.htaccess domain setup)
2. Grav then redirects to fr.example.com/noms-de-domaines
which is the correct URL

So it adds one more 302 redirection when switching languages. According to webmastertools, 2 redirects should work, but it is advised to use redirects at all in sitemaps.

It is not a sitemap-plugin issue, or a langswitcher-plugin issue. 
This has already been discussed in several issues (for example #522), which are closed, and I understand why.
It would be a very nice fix to implement in the future.

http://www.johnfdoherty.com/google-sitemaps-ask-for-clean-urls/
http://www.redirect-checker.org/how-many-redirects.php
