### ISSUE TITLE
Back-tick sections not handled correctly in blog summary

### ISSUE THREAD

**Issue by stevej2608** [getgrav/grav#1686]
On a blog page I have a back-tick section that contains some html. This is handled correctly by Grav when the page is displayed on it's own. 

On the blog summary page the back-ticked html is terminated when the 300 character limit is reached. This results in the back-ticked section being rendered as "live html" with all the blog summaries that follow being corrupted.

**Comment by rhukster** [comment]
Yah this is tricky because the summary breaking mid-way through a code block has to close the block properly. This is further confused by html in the code block.   I suggest using a manual page break to break either after or before the code block.
