### ISSUE TITLE
Routing paths with spaces and non-latin letters

### ISSUE THREAD

**Issue by masetto** [getgrav/grav#1688]
Before last upgrade spaces were allowed in folder name. But not now.
If folder name for example is `/this is folder name` and no slug has specified, when I navigate in the page `www.mysite.com/this is folder name` I have `Page not found`.

**Comment by mahagr** [comment]
In the latest version path gets `rawurlescape()`'d to prevent attacks within the path. I just added the test with current results for this.

**Comment by mahagr** [comment]
Need to talk with @rhukster about this issue.

**Comment by shalberd** [comment]
Wow, international Web pages! 

You really ought to repair this. I ran into this issue when I updated to 1.6.
International urls in my project did not work anymore. Specifically, those with German Umlauts.
ö ü ä

or French é

Before I read this here, I thought my page collections handling was wrong, all the time not seeing that e.g.

On my book page subpages

http://mypage.com/buecher was fine

while

http://mypage.com/bücher was not fine.

I reverted to 1.3.4 from 1.3.6 by copying the files of that version in the 
/system/
/bin/

over and restarted nginx.

All fine now with e.g. http://mypage.com/bücher/ostern

**Comment by mahagr** [comment]
@masetto @shalberd Both issues should be fixed now, please test!

There may be other side effects as well from the hardened `Uri` class aside of these.

**Comment by shalberd** [comment]
I reviewed the code, seems cool from a PHP and international URL standpoint.

**Comment by masetto** [comment]
I tested it, for me all right! Thank you

**Comment by rhukster** [comment]
Looks good to me too @mahagr

**Comment by shalberd** [comment]
should be in new release as soon as possible because people who relied on the update mechanism in admin panel were caught off-guard.

**Comment by rhukster** [comment]
This is released now, it should be picked up and show up via GPM in about 30 mins.

**Comment by shalberd** [comment]
Cool. Thank you all and especially @mahagr 
One final thing: changelog has issue links to grav-plugin-admin instead of the grav.

https://github.com/getgrav/grav/commit/0cb8e0664e62dc50a265242c093ede12c602c747#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by shalberd** [comment]
Updated via Admin panel from 1.3.4 to 1.3.7. Aside from a "please wait, downloading ..." message that got stuck in Firefox, all worked well. Files are updated on server and after a page refresh in admin panel, current version 1.3.7 is shown.

Url issue fixed, all good.

**Comment by shalberd** [comment]
There could be an issue of page.active or page.activechild in collections, leading to <li class="active"> ... entries not being currently generated when there are non-Latin letters.  In Grav Antimatter, I am not getting correct active classes and style shades on subsections of e.g. mydomain/über/dübel1 and mydomain/über/dübel2

**Comment by mahagr** [comment]
@shalberd Please open a new issue about it.
