### ISSUE TITLE
Grav 1.3.5 - "Invalid AJAX Response"

### ISSUE THREAD

**Issue by peracchi** [getgrav/grav#1689]
Hi!
Just installed Grav 1.3.5.
After setup admin account and enters Admin plugin, I got a "Invalid AJAX Response".
When try logout, "Invalid Security Token" is displayed and browser hangs.
Happens in Chrome and Firefox on my MacOS.

**Comment by rhukster** [comment]
Event though this is a probably a core-grav issue, it's most visible on the admin, as such we are discussing this here: https://github.com/getgrav/grav-plugin-admin/issues/1244

Please read that issue, and see if you are having the same problems.
