### ISSUE TITLE
Translated slug not always used in the page address

### ISSUE THREAD

**Issue by parijke** [getgrav/grav#1695]
I have a multilingual site with 2 languages. I have the following setup

/en/services
/nl/diensten

the foldername is services so the translated slug for nl is diensten

The problem occurs when I am on /en/services and switch to NL. Than the url in the address bar says /nl/services instead of /nl/diensten

Also, that url is a valid url (which in my opinion shouldn't because it has the url /nl/diensten

Is this a bug?

**Comment by parijke** [comment]
Redirect default route seems to fix this, but I do not exactly understand it. Can someone elaborate?

**Comment by rhukster** [comment]
It's really due to the way multilang is designed. Only one language is loaded at a time for performance reason.  The trade-off is that when in one language you really can't see the custom slugs of other languages. Check this thread for more details:

https://github.com/getgrav/grav/issues/1226
