### ISSUE TITLE
$_SERVER['HTTPS'] is not defined in some servers

### ISSUE THREAD

**Issue by mahagr** [getgrav/grav#1698]
See: https://github.com/getgrav/grav/commit/a9c82710a6f33b636a84cc42e4d0b1964d7c1483

**Comment by mahagr** [comment]
@paulmassen Created an issue for this. Please test out the fix.

**Comment by paulmassen** [comment]
Thanks @mahagr . Can confirm it works 👍 

This is probably an edge case, but cloud9 runs with https and on port 80, so port is still here on my cloud9 env, but I don't think it is worth fixing this just for people running it on cloud9.

**Comment by mahagr** [comment]
it has to have port because of you're using non-standard one for https. :)
