### ISSUE TITLE
Theme var root() not working

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav#1700]
Hi there,

I'm trying to use the theme var `root()`
https://learn.getgrav.org/themes/theme-vars#root

As the Grav doc say it suppose to returns true or false based on whether or not this page is the root page of the tree hierarchy.

I tested it with `{{ page.root() }}` on the home page and all first parent page of my website but it always return me false.

Am I doing something wrong or it is a bug?

Thank you for your help, cheers!

**Comment by rhukster** [comment]
You mean `page.route()`??? it's not `page.root()`.

**Comment by rhukster** [comment]
Sorry you linked to route in the URL and thought you had a typo.  `root()` is a valid method and should work fine:

```
    public function root()
    {
        if (!$this->parent && !$this->name && !$this->visible) {
            return true;
        } else {
            return false;
        }
    }
```

**Comment by jimblue** [comment]
Sorry @rhukster, I understand it was confusing... I've just corrected it!

**Comment by jimblue** [comment]
Little update from Slack: apparently I'm not the only one to have this problem.

**Comment by rhukster** [comment]
Well, this is being used successfully in several places in Grav.  It's actually for testing the true root of the pages folder, not necessarily the top-level pages. See `Page::activeChild()` for example

**Comment by jimblue** [comment]
Hi @rhukster!

I found that this solution was working for me to get top-level pages:

`page.parent.root()`
