### ISSUE TITLE
Deleting Pages with "\" as first character does not work.

### ISSUE THREAD

**Issue by derdobs** [getgrav/grav#1701]
On Grav v1.3.6 - Admin v1.6.4, deleting pages that start with a "\\" does not work (on Ubuntu/Nginx).

**Comment by rhukster** [comment]
can you give me some example? Are you talking about a folder name or a title? If a folder, you shouldn't have that in your folder name to start with.  We recently fixed a 'bug' that was allowing stray slashes and that might be what your seeing now.

**Comment by derdobs** [comment]
The user mistakenly created a folder with a backslash (i assumed that the backend allowed it), then mailed me as he could not remove the folder with the backslash anymore.

Sorry for the timewaste.
