### ISSUE TITLE
Images not showing in local env

### ISSUE THREAD

**Issue by nicholasnbg** [getgrav/grav#1703]
Hi all,

I'm new to grav, and kinda new to webdev.

I've got grav setup so that I push changes from local > github repo, then use a webhook to automatically push to my live site.

I'm testing creating a new page 
![image](https://user-images.githubusercontent.com/17841511/31746629-1358b780-b4b4-11e7-9326-65d02bd3db8b.png)

Using the default template, which contains this:
![image](https://user-images.githubusercontent.com/17841511/31746668-41ff40d6-b4b4-11e7-9f04-456497cbb9e8.png)

The weird part is, on my local host no image shows, but on the live site it does.
![image](https://user-images.githubusercontent.com/17841511/31746696-715fa6e0-b4b4-11e7-8576-549476db7d96.png)

Can anyone explain what is going on here?

**Comment by rhukster** [comment]
What platform are you running on locally? Also can you check your php config to ensure GD is installed?

**Comment by nicholasnbg** [comment]
I'm running on Wampserver on Windows10, in the PHP extensions menu it has a tick next to "php_gd2"

**Comment by rhukster** [comment]
Hmm do you have an option for libjpeg or something? Is it possible to try another web server like MAMP for Windows?

**Comment by nicholasnbg** [comment]
No libjpeg as far as I can see. I've got mamp setup on my laptop, will have a go later on today and let you know.

**Comment by nicholasnbg** [comment]
Hi @rhukster , I actually found an old thread where you helped someone with something similar (https://muut.com/i/getgrav/general:some-images-missing-from-im), and deleted the contents of my cache folder locally, and now it is working! So thanks :)
