### ISSUE TITLE
Shouldn't this be...

### ISSUE THREAD

**Issue by benface** [getgrav/grav#1707]
```
count($language) < 3
```
instead of
```
count($language < 3)
```
?

https://github.com/getgrav/grav/blob/dd166ce25cf36972a23d4261b09fed3ccdb8e0b7/system/src/Grav/Common/Grav.php#L151

**Comment by rhukster** [comment]
Yah i think so, you can edit the file directly in github and it will let you create a pull request with that change.

**Comment by benface** [comment]
Done: #1709
