### ISSUE TITLE
GPM update issue

### ISSUE THREAD

**Issue by renards** [getgrav/grav#1711]
An example : 
You are working on a plugin like simplesearch with an update pending and you want to update your staging/live server by script the following command will update the simplesearch plugin anyway :

`bin/gpm update -n admin email error form login markdown-notices problems`

I think only the plugins on the list should be updated.
I tested this with the current develop branch.

**Comment by rhukster** [comment]
I shall investigate!

**Comment by rhukster** [comment]
I can't replicate this. I had multiple things pending, i then tried to install just one, but it did what it was told.  Also tried with 2, and that also worked.  

The important part is this:

```
Limiting updates for only admin-addon-user-manager
```

What does yours say?

Full output:

```
/Users/rhuk/www/grav [rhuk@compy] [21:57]
> bin/gpm update

GPM Releases Configuration: Testing

Found 97 packages installed of which 4 need updating

01. Admin Addon User Manager [v1.8.0 -> v1.8.1]
02. Astrobin        [v1.0.2 -> v1.0.3]
03. Gantry 5 Framework [v5.4.14 -> v5.4.19]
04. Helium          [v5.4.14 -> v5.4.19]

Continue with the update process? [Y|n] n
Update aborted. Exiting...

/Users/rhuk/www/grav [rhuk@compy] [21:58]
> bin/gpm -n update admin-addon-user-manager

GPM Releases Configuration: Testing

Found 97 packages installed of which 4 need updating, only 1 will be updated
Limiting updates for only admin-addon-user-manager

01. Admin Addon User Manager [v1.8.0 -> v1.8.1]


GPM Releases Configuration: Testing



Preparing to install Admin Addon User Manager [v1.8.1]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!


Clearing cache

Cleared:  /Users/rhuk/www/grav/cache/compiled/*

Touched: /Users/rhuk/www/grav/user/config/system.yaml


/Users/rhuk/www/grav [rhuk@compy] [21:58]
```

**Comment by renards** [comment]
Hi @rhukster ,

what happens if you call this command one more time after you updated the admin-addon-user-manager plugin:

`bin/gpm -n update admin-addon-user-manager`

I think in this case nothing has to be done.

**Comment by rhukster** [comment]
confirmed!

**Comment by renards** [comment]
Thank you :+1:
