### ISSUE TITLE
Grav doesn't error when URL is a file

### ISSUE THREAD

**Issue by jacobm001** [getgrav/grav#1713]
I came across [this question](https://stackoverflow.com/questions/46892540/got-200-on-an-url-that-should-gives-a-404) on StackOverflow and was able to replicate it on my own Grav install. It appears that Grav will not throw a 404 and the error page as it should when the url contains a file. For example:

    https://website.com/doesnotexist     -> goes to the error page
    https://website.com/doesnotexist.zip -> goes to the homepage.

I'm using apache, and it appears the person who asked the original question is as well.

**Comment by nned** [comment]
@jacobm001 I confirm this.  For sure, it is a nasty bug.

**Comment by rhukster** [comment]
Going to look at this...

**Comment by rhukster** [comment]
Easy fix!  Ready for next release.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav/commit/d3695b2faa914748f5ffaec84d252f314203f03c

**Comment by jacobm001** [comment]
Thanks!

**Comment by Chouchen** [comment]
Thanks for making an issue out of my question on Stackoverflow :)

I thought it was a bad config on my part!
