### ISSUE TITLE
instance of Exception, instance of Error given --> Php7 & form plugin

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav#1714]
First time i have issue with a brand new install `centos7` with `virtualmin` panel
when installing form plugin,  i have error `…/­vendor/­filp/­whoops/­src/­Whoops/­Run.php233` my php version is `7.0.10`

**Comment by rhukster** [comment]
As i mentioned in Slack, pretty sure that your webserver is not actually running PHP 7.  Try creating a simple PHP page with:

```
<? phpinfo();
```

and pointing your browser to that.

**Comment by dimitrilongo** [comment]
I continue on [Slack Discussion](https://getgrav.slack.com/archives/C3Z7KN6MC/p1508792144000277)
