### ISSUE TITLE
getgrav.org: missing plugin: danny-stey/grav-plugin-instagram-feed

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav#1719]
This plugin no longer exist but is still in the plugin list: danny-stey/grav-plugin-instagram-feed

**Comment by rhukster** [comment]
Still there: https://github.com/dannystey/grav-plugin-instagram-feed

**Comment by jimblue** [comment]
Sorry at the time I was writing this issue it wasn't.

**Comment by rhukster** [comment]
You have a `-` in the name, but that is not how it's listed in GPM

**Comment by jimblue** [comment]
How ok my bad 😄  thanks for the explanation !
