### ISSUE TITLE
Problem with bin/gpm on Windows

### ISSUE THREAD

**Issue by Frucht** [getgrav/grav#172]
When I try to uninstall antimatter from grav, I get this error on windows when running php bin\gpm uninstall antimatter

    [RuntimeException]
    rmdir(E:/EasyPHP-DevServer-14.1VC11/data/localweb/landingpage/user/themes): Directory not empty

I'm running git bash with admin rights, but it still does not work : /

**Comment by rhukster** [comment]
Thanks, i'll take a look at this next week.

**Comment by drzraf** [comment]
while at it, please note that if php-curl is absent, gpm fails without any useful hint.
(other than a couple of CURL_OPTREFERER undefined, here and there)

**Comment by MatthiasKauer** [comment]
that php-curl hint was a life saver just now!

**Comment by rhukster** [comment]
both of these issues should be sorted in next release (or current develop branch)
