### ISSUE TITLE
Installation guide has incorrect URL

### ISSUE THREAD

**Issue by jdabs** [getgrav/grav#1721]
The green box that tells you the URL to complete the installation is incorrect on this page:
https://getgrav.org/downloads

It says that if you're using the admin version, you should go to yoursite.com/admin. However, when I extracted the admin zip on that page and extracted it on my webroot, it created a /grav-admin/ directory. Thus going to mysite.com/admin gave me a 404. But going to mysite.com/grav-admin works as it should. I believe this URL in the tip needs to be updated to show the default behavior of the extracted zip.

Thanks for your work!

**Comment by rhukster** [comment]
The `/admin` path is actually referring to the location of the admin plugin after installation, not so much the subdirectory. That all depends on if you extract it out and keep the folder or extract into your web root.
