### ISSUE TITLE
[add-resource] New Plugin: Webcomponents - Polymer

### ISSUE THREAD

**Issue by btopro** [getgrav/grav#1722]
I would like to add my new plugin to the Grav Repository.
Here are the project details: https://github.com/elmsln/grav-plugin-webcomponents

This adds lazy load support for webcomponents (generally structured based on polymer elements though it'll work with any custom element) so long as it's added into the `user/webcomponents` directory within at least 3 levels of depth.

**Comment by rhukster** [comment]
Added to GPM for next release.
