### ISSUE TITLE
[add-resource] new Plugin: cookieconsent 0.2.0

### ISSUE THREAD

**Issue by naucon** [getgrav/grav#1723]
I would like to add my updated plugin/theme to the Grav Repository. Here are the project details: https://github.com/naucon/grav-plugin-cookieconsent

Changelog:
* Add translations for english, french, spanish, german and italian.
* Translations will be used if no `content_message`, `content_dismiss`, `content_link` or `content_href` are defined in `cookieconsent.yaml`.

**Comment by w00fz** [comment]
Hello naucon, I see you already have the plugin added in the repository.
Once the plugin is in gpm, updates to the plugin are automatically detected, once a hour. There is no need on your end to open an issue about new releases. The plugin seems to be already on 0.2.0 on gpm so everything should be good.

Thank you!
