### ISSUE TITLE
How to get the active tag on a collection page

### ISSUE THREAD

**Issue by indigoxela** [getgrav/grav#1724]
I'm struggling to get the "current tag" on a filtered collection page in a template.
It is possible to get the uri.params though (url_taxonomy_filters is true), but that's not quite what I need.

Is there an easy way to get the single taxonomy tag the current collection is filtered by as a page variable?
My use case: I'd like to set the page heading dynamically by current tag.

**Comment by indigoxela** [comment]
While not ideal, I found a workaround. Playing with twig filters on uri.params seems to be a solution - at least for me.
```
{% if uri.params %}   
  {% set params = uri.params|ltrim('/')|split(':') %}   
  {% if params[0] == 'tag' %}
    {% set term = params[1]|regex_replace('/%20/', ' ') %}
    <h2>Content with tag <em>{{ term }}</em></h2>       
  {% endif %}
{% endif %}  
```

**Comment by tintincastro** [comment]
Coming a long time after, but might be useful to someone who finds your post…

Use `uri.param('tag')` to directly get the value of the parameter:

```twig
<h2>Content with tag <em>{{ uri.param('tag')|humanize }}</em></h2>
```

(Note that since it's a uri parameter, you probably should'nt display it directly like that and first check that it belongs to a valid tag list before)

**Comment by Penworks** [comment]
Another long time after comment, for those looking to achieve current tag being displayed in page, I can confirm these still work in current version of Grav 1.7.38 (2023). Thanks guys, for writing this down, Ive been trying to figure out how to call this for 3 days (Twig newbie).
