### ISSUE TITLE
support non js/css assets being added

### ISSUE THREAD

**Issue by btopro** [getgrav/grav#1726]
The current `.add()` command is too opinionated to do anything beyond css / js. It would be useful to allow for a 3rd fallback option if it doesn't match which is to allow deveopers to manually construct the tag they want to add.

## Example applications:
- HTML Import is currently not possible - `<link rel="import" src="somefile.html">`
- Creating a plugin that generates icon derivatives for different mobile devices / other important meta tags:
```
<meta name="msapplication-config" content="/xapi/sites/all/themes/elmsln_contrib/foundation_access/icons/elmsicons/browserconfig.xml">
        <link rel="apple-touch-icon" sizes="144x144" href="/xapi/sites/all/themes/elmsln_contrib/foundation_access/icons/elmsicons/elmsln-144.png">
        <link rel="icon" type="image/png" sizes="192x192" href="/xapi/sites/all/themes/elmsln_contrib/foundation_access/icons/elmsicons/elmsln-192.png">
<link rel="canonical" href="/xapi/node/68" />
```

## Rationale:
It would be great to be able to add these in via a plugin instead of depending on the theme to do SEO optimizations (as 1 example). Supporting `canonical` for example allows for better SEO and a plugin could provide this in a more modular, theme agnostic way then is currently possible.

## Recommendation:
Have a fallback that if it's not css / js, to read off the options and support a structure like this:
`.add('whatever.html', array('tag' => 'link', 'rel' => 'import'));`
`.add('meta', array('tag' => 'meta', 'name' => 'msapplication-config', 'sizes' => '144x144'));`
`.add('browserconfig.xml', array('tag' => 'link', 'rel' => 'apple-touch-icon', 'content' => '/xapi/user/plugins/seo/icons/elmsicons/browserconfig.xml'));`

**Comment by rhukster** [comment]
meta, html and xml are not Assets in the sense that Grav understands.  We actually have some plans in Grav 2.0 to have functions to add arbitrary HTML, metatags and some other things but it's using twig tags directly and not building on top of the Asset manager.  So this kind of functionality is coming...
