### ISSUE TITLE
Automatic Environment Configuration Theme config

### ISSUE THREAD

**Issue by jwillp** [getgrav/grav#1728]
I tried to apply the same logic to my theme's configuration file as well but it does not seem to work.
I created the following directory `localhost/themes/mytheme/mytheme.yaml`.

I know the [documentation](https://learn.getgrav.org/advanced/environment-config) only mentions `system.yaml` `site.yaml` and `plugin configurations`, but I was wondering if it was in the plans to also support this feature for themes ?

My use case being that I have a config variable called `env` where possible values are `development|production` that defines how twig should render templates depending on the value of said config variable. On localhost I would have `development` on localhost and `production` on the server. As a workaround I defined the variable in site instead of the theme's config file.

**Comment by rhukster** [comment]
This already exists, and you were close, it just needed to be:

```
localhost/themes/mytheme.yaml
```

<img width="292" alt="grav-demo-sampler 2017-10-31 15-36-03" src="https://user-images.githubusercontent.com/1084697/32250212-36cf6280-be51-11e7-80d7-38afdd7dfa14.png">

**Comment by jwillp** [comment]
Oh I see! Is it mentionned somewhere in the docs ?

**Comment by rhukster** [comment]
General Configuration: https://learn.getgrav.org/basics/grav-configuration#config-variable-namespacing

Environment Configuration: https://learn.getgrav.org/advanced/environment-config#theme-overrides

To be honest it wasn't clear, so i beefed it up a bit with some examples :)

**Comment by jwillp** [comment]
Great! Thank you!

**Comment by Bibi40k** [comment]
Hi, this is kinda old topic but i have this important question:
What about if in my working environments (dev, staging and production) the hostname doesn't change. I have a Chrome plugin that changes /etc/hosts file and points to local IP, staging IP and nothing for live IP?
In this case how can i setup different config files ?

**Comment by ricardo118** [comment]
i dont think it will work, perhaps you can try with ip as the folder name
