### ISSUE TITLE
[1.3.8] Taxonomies seem to work with lowercase entries only

### ISSUE THREAD

**Issue by campino2k** [getgrav/grav#1729]
I had 1.3.7 or 1.3.6  with a taxonomy named "produktwelt" and things like "Produktwelt1". The taxonomylist plugin worked great with that. Upgraded to 1.3.8 and filtering by the taxonomy works only when the taxonomy entry is completely lowercase.

**Comment by rhukster** [comment]
I see you have already provided PRs for taxonomylist plugin.  That's where this needs to be fixed as the change in 1.3.8+ of Grav was to tackle XSS attacks.

**Comment by campino2k** [comment]
That alone does only fix the active indicator. Besides that: Filtering for terms with Uppercase letters returns nothing
