### ISSUE TITLE
Sort Plugins by Popularity, or show Github stars?

### ISSUE THREAD

**Issue by gitressa** [getgrav/grav#1730]
Being new to Grav, it would be great with some more tools to help choosing which plugins to use ... perhaps adding "Sort by Popularity" at https://getgrav.org/downloads/plugins and `/admin/plugins` could help in the evaluation, or including the number of Github stars? I really like what I have seen so far, and can't wait to build my first grav web site.

**Comment by rhukster** [comment]
We're actually hard at work refactoring the whole downloads section to include many more advanced features and better ways to browse, sort, filter, etc.  So it's coming!!!! :)

**Comment by gitressa** [comment]
Sounds great, I am looking forward to seeing it!

**Comment by fridde** [comment]
I'd like to reopen this issue.
It would still be nice to sort plugins or themes by popularity/downloads, just to give an idea to someone new as to what could potentially be well maintained and useful resources.

I don't see how sorting by author or title ever could become relevant. If I'd vaguely remember a name of a plugin or theme, I'd google "grav plugin xyz" and not scroll through an alphabetical list.

I understand that sorting by popularity is harder than any other method though. Is there any download registry?
