### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by enovision** [getgrav/grav#1731]
I would like to add my new plugin/theme to the Grav Repository._Here are the project details: **enovision/grav-frontend-edit-button**

This plugin adds an 'edit this page' button on the frontend pages when logged in with a user account with admin rights. After clicking the button it will open the Admin Dashboard in another tab in your browser where you can start editing the page. Clicking back to the page with the article will automatically refresh the page showing the content you have just saved.

This plugin does not show an editor on the frontend !!! It is using the dasboard edit functionality of Grav CMS.

**Comment by rhukster** [comment]
Added to GPM.
