### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by gdvallance** [getgrav/grav#1732]
Hello,

I am somewhat stumped in trying to install `grav` locally on an Ubuntu 16.04 VM with php7 and apache.

I keep getting this error in http://localhost/grav no matter how I install it. (.zip and composer)

```php
bin/grav install"); } if (PHP_SAPI == 'cli-server') { if (!isset($_SERVER['PHP_CLI_ROUTER'])) { die("PHP webserver requires a router to run Grav, please use:

php -S {$_SERVER["SERVER_NAME"]}:{$_SERVER["SERVER_PORT"]} system/router.php

"); } } use Grav\Common\Grav; use RocketTheme\Toolbox\Event\Event; if (version_compare($ver = PHP_VERSION, $req = GRAV_PHP_MIN, '<')) { die(sprintf('You are running PHP %s, but Grav needs at least PHP %s to run.', $ver, $req)); } // Register the auto-loader. $loader = require_once $autoload; // Set timezone to default, falls back to system if php.ini not set date_default_timezone_set(@date_default_timezone_get()); // Set internal encoding if mbstring loaded if (!extension_loaded('mbstring')) { die("'mbstring' extension is not loaded. This is required for Grav to run correctly"); } mb_internal_encoding('UTF-8'); // Get the Grav instance $grav = Grav::instance( array( 'loader' => $loader ) ); // Process the page try { $grav->process(); } catch (\Exception $e) { $grav->fireEvent('onFatalException', new Event(array('exception' => $e))); throw $e; }
```

I don't know `php` but what it appears to be saying is that I don't have the correct minimum php version which is not true.`php -v` returns 

```bash
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```
It also appears to be saying that mbstring is not insalled either. Yet php -m returns

```bash
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
openssl
pcntl
pcre
PDO
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

So that is not true either.

Any pointers? I am sure it is something simple ...

Thank you!

Sincerely,

gdvallance

**Comment by rhukster** [comment]
Basically you don't have PHP installed correctly.  You are trying to run PHP with the CLI (Command Line Interface) version which is not compatible with the webserver.  You should be running with CGI or FPM version. 

I suggest you follow a guide such as this one: https://www.vultr.com/docs/how-to-install-and-configure-php-70-or-php-71-on-ubuntu-16-04 or this one https://www.howtoforge.com/tutorial/install-apache-with-php-and-mysql-on-ubuntu-16-04-lamp/

if you want to to use Nginx webserver, you can use the guide i've written up for various VPS providers (one you get past the setup of the VPS itself, the guide is the same): 

https://learn.getgrav.org/webservers-hosting/vps/digitalocean

**Comment by gdvallance** [comment]
@rhukster Thank you so much for your helpful reply! I knew something was wrong about my PHP installation, but not what exactly. I have learned something about PHP. I owe you a beer. If you are ever in Oxford, UK ...

**Comment by rhukster** [comment]
glad to help!
