### ISSUE TITLE
[1.3.8] Error message when creating page

### ISSUE THREAD

**Issue by tomzmtl** [getgrav/grav#1734]
Grav version : `1.3.8`

Just updated Grav to latest version `1.3.8`.
I just created a new folder, and upon creation I get the following error as a popup notification:

```
Fetch Failed: 
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
at Function.keys ()
at http://gololocalhost-showcase.com/user/plugins/admin/themes/grav/js/admin.min.js?096aa5a1ea:5:24264
at http://gololocalhost-showcase.com/user/plugins/admin/themes/grav/js/admin.min.js?096aa5a1ea:4:27913
at
```

* This shows up every time the page is reopened/refreshed, as well as every other page under it.
* The pages that were created before the update seem to be working fine.
* All changes made to the page seem to work fine so far (content, options etc).

![screen shot 2017-11-01 at 11 10 09 am](https://user-images.githubusercontent.com/1015603/32281428-2a8a72b8-bef5-11e7-8239-0408be85445e.png)

**Comment by tomzmtl** [comment]
After some tinkering, I observed that the error stops showing once I select a template other than "Default". I am not sure this is expected behaviour.

**Comment by rhukster** [comment]
Definitely not expected behavior and can't replicate myself.  What webserver are you running?

**Comment by co0kie** [comment]
Also had the same issue when upgrading to 1.3.8, I'm on v1.3.6 now.

**Comment by rhukster** [comment]
I'll repeat again, what webserver @co0kie ??

**Comment by co0kie** [comment]
@rhukster nginx

**Comment by tomzmtl** [comment]
@rhukster I'm running Apache. (macOS 10.12.6, MAMP, PHP 7.1.1)

**Comment by rhukster** [comment]
can you zip yup your site and send it to me (rhuk at getgrav dot org)
