### ISSUE TITLE
[1.3.8] "Invalid Ajax response" when toggling preview

### ISSUE THREAD

**Issue by tomzmtl** [getgrav/grav#1735]
The following error pop-up shows up when toggling the preview tab for a page I just created:

![screen shot 2017-11-01 at 12 43 07 pm](https://user-images.githubusercontent.com/1015603/32285955-54086930-bf02-11e7-8bb5-f81e05f3a6df.png)

* Same behaviour in full screen mode.

**Comment by rhukster** [comment]
Let's keep this on one ticket: https://github.com/getgrav/grav/issues/1734 

it's the same issue, invalid ajax.
