### ISSUE TITLE
Redirect loop on /

### ISSUE THREAD

**Issue by jpass** [getgrav/grav#1736]
If we set custom_base_url to relative url, homepage returns infinite loop.

Simple fix is to add check in  `system/src/Grav/Common/Uri.php` on line 308:

```php
$redirect = str_replace($this->root, '', rtrim($uri, '/'));
// If configured to, redirect trailing slash URI's with a 302 redirect
if ($uri !== '/' && $redirect !== $this->base()  && $config->get('system.pages.redirect_trailing_slash', false) && Utils::endsWith($uri, '/')) {
    $grav->redirect($redirect, 302);
}
```

I will try to post more information soon.

**Comment by rhukster** [comment]
I implemented your fix, but then discovered several other issues related to `custom_base_url` when using both absolute and relative custom paths.  Hopefully my commit will address all of these, please test :)

**Comment by jpass** [comment]
Your fix is perfect :)
