### ISSUE TITLE
Typo in system/blueprints/pages/modular.yaml

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav#1738]
https://github.com/getgrav/grav/blob/acea401a3d3ef02dd4c4f408ac037e354dbd12d7/system/blueprints/pages/modular.yaml#L45

shoud be `header.media_order`

**Comment by rhukster** [comment]
Already fixed: https://github.com/getgrav/grav/blob/develop/system/blueprints/pages/modular.yaml#L45
