### ISSUE TITLE
[update-resource] Plugin/SocialFeed

### ISSUE THREAD

**Issue by moduleon** [getgrav/grav#1739]
Hi,
I drafted a new release of the social-feed plugin (v0.1.2). This new version include vendors, and an autoload to be usable "out of the box".
Please add this new version in gpm.
Thank you

**Comment by rhukster** [comment]
If you created a new release it should automatically be picked up by GPM.  let me know if that doesn't happen and we can look into it for you.

**Comment by moduleon** [comment]
Hi, 
GPM only fetches the previous version (v0.1.1), I could use a hand on this.
Thank you rhukster.

**Comment by rhukster** [comment]
It's showing up just fine, you just need to flush your gpm to pick it up immediately:

```
bin/gpm index -f
```

Best way to check is to look at the site: https://getgrav.org/downloads/plugins
