### ISSUE TITLE
parsedown markdown glitch: blockquotes

### ISSUE THREAD

**Issue by drzraf** [getgrav/grav#174]
see this [SO thread](http://stackoverflow.com/questions/7167519/should-markdown-preserve-newlines-in-blockquotes)

I'm pretty sure that:
> quote; line1
> quote; line2

should be rendered in a ```<blockquote>``` as **2 distinct lines**
(as in github and muut)

**Comment by drzraf** [comment]
This discussion: https://github.com/erusev/parsedown/issues/226
suggested that setting _breaksEnabled_ should do the trick.
This is done by ```Parsedown->setBreaksEnabled()```
And indeed ParsedownGravTrait.php calls this function passing the _auto_line_breaks_ parameter.
**but** it passes ```$defaults['auto_line_breaks']```
I not sure, but dumping the value it seems that my
> markdown:
>    auto_line_breaks: True
in the header ofd my page was not taken into account (could be another bug).
(still I have to see if changing the auto_line_breaks value in the settings makes Parsedown processes quotes correctly... without side-effects)

**Comment by drzraf** [comment]
3rd bug, I added:
```
   markdown:                                                                        
        auto_line_breaks: true
```

To the _pages_ YAML section of the default ```user/config/system.yaml```
I'd expect to override the "false" value from ```system/config/system.yaml```
It does but.... other values of the same section, like _auto_url_links_ become "undefined":
> 9. Whoops\Exception\ErrorException, …/­system/­src/­Grav/­Common/­Markdown/ParsedownGravTrait.php41

**Comment by drzraf** [comment]
ok, I can confirm that setting auto_line_breaks does the trick (hopefully without side-effect).
The issue is now "how to set auto_line_breaks?"
1. Overriding 1 value of the markdown section in user/config/system.yaml undefines all others
2. Overriding from the page's header does not seem to work
I hope a maintainer could close this one about Parsedown while tracking the 2 others about overriding markdown values.

**Comment by rhukster** [comment]
It should work from the page header by using the syntax:

https://github.com/getgrav/grav/issues

```
===
title: Your Page
markdown: true
  extra: false
  auto_line_breaks: false
  auto_url_links: false
  escape_markup: false
  special_chars:
    '>': 'gt'
    '<': 'lt'
===

Your content
```

Can you confirm that is not working for you?

**Comment by drzraf** [comment]
it's not working (ie: the values aren't taken into account)
Note: header is delimited by ```---``` rather than ```===```

**Comment by rhukster** [comment]
I'll take a look

**Comment by drzraf** [comment]
fix confirmed
thx!
