### ISSUE TITLE
GPM always connects to getgrav server, even when only want to get Local Packages

### ISSUE THREAD

**Issue by aguvillalba** [getgrav/grav#1742]
I have disabled the option enable_auto_updates_check:
enable_auto_updates_check: false

The partial template user/plugins/admin/themes/grav/templates/partials/nav.html.twig tries to get the number of installed plugins:
<span class="badge count">{{ admin.plugins|length }}</span> (line 61)

This calls to: 
Grav\\Plugin\\Admin\\Admin::plugins(true) --->
Grav\\Plugin\\Admin\\Admin::gpm() --->
Grav\\Common\\GPM::__construct()

And in that construct you have this code:
```
$this->installed = new Local\Packages();
try {
        $this->repository = new Remote\Packages($refresh, $callback);
        $this->grav = new Remote\GravCore($refresh, $callback);
} catch (\Exception $e) {
}
```
So, independently of whether I want to the local plugins (Admin::plugins(true)) or not, the constructor of GPM will always try to connect to getgrav.org server to get the plugins repository.
IMHO this does not makes sense, since I want the local plugins, there is no need to connect to the external server.
The connection to external server to get the remote packages should be removed from the constructor and place it in a explicit function that is called whenever is needed to grab the remote repository.

I will try to make a pull request to fix this.

Thank you!

**Comment by rhukster** [comment]
Cool, i'll look forward to your PR.

**Comment by mahagr** [comment]
I would use DI to lazy load remote packages only if they are needed.

**Comment by aguvillalba** [comment]
Me too @mahagr, that's my idea as well. There is not dependency injection manager/framework in this project yet. Changing to DI is not straight forward now since it could break other things where the GPM is used (plugins for instance).
I have already asked in the slack channel about using DI manager/framework (I would not use a service locator), but no answer yet.
In the meantime, I am changing the code to do a "pseudo lazy-loading", so the Remote package is only created when it is actually needed.

**Comment by mahagr** [comment]
Grav uses DI, but inits all the classes early, eg. it doesn't lazy load most things.

**Comment by aguvillalba** [comment]
Well, Pimple is a service locator, not a proper dependency injection manager that's why I said that Grav is not using DI manager, and yes, it does not lazy load dependencies, which is also bad.

**Comment by aguvillalba** [comment]
PR added to solve this issue

**Comment by mahagr** [comment]
@aguvillalba You may want to take a look into the issue as your change was reverted because of it broke plugin/theme installation.
