### ISSUE TITLE
Check if session is started

### ISSUE THREAD

**Issue by jpass** [getgrav/grav#1744]
We integrate Grav as part of our platform. This means we need to use session when Grav is not use or use it before we initialize Grav.

In our index.php file we have
``` php
if(!$grav['session']->started())
{
    $grav['session']->init();
}
```
If same thing would be added to `system/src/Grav/Common/Processors/InitializeProcessor.php` we could control session.

Problem actually comes from `vendor/rockettheme/toolbox/Session/src/Session.php`:
``` php
// Destroy any existing sessions started with session.auto_start
if ($this->isSessionStarted())
{
    session_unset();
    session_destroy();
}
```
This removes any session started before Grav.

This solution could also check for `wrapped_site` in system config, because this is exactly what is happening, Grav is wrapped with our code.

**Comment by mahagr** [comment]
I would override $grav['session'] with your own (which extends Grav's Session class) in a plugin as early as possible. Though, I'm not 100% sure if it's possible right now.

**Comment by jpass** [comment]
I need to start session before Grav is fully initialized.

This is simplified version of my code:
``` php
<?php

$autoload = __DIR__ . '/vendor/autoload.php';
$loader = require_once $autoload;

use Grav\Common\Grav;

$grav =  Grav::instance(
    array(
        'loader' => $loader
    )
);

if(!$grav['session']->started())
{
    $grav['session']->init();
}
// ...
// do stuff with session
// switch to check if we use Grav or online shop code based on $_SERVER['REQUEST_URI'] 
// if Grav is used here we include 'index.php' from Grav subdirectory
```

We share session with shop platform.

**Comment by mahagr** [comment]
@jpass I've added option to upcoming Grav 1.4 to disable session initialisation inside Grav core. It allows you to create a plugin which overrides session handling allowing you to replace default session handler with something else. Just remember that you need all the functions we have in your session class, maybe extend ours and just replace the code so that it works with your sessions.

**Comment by mahagr** [comment]
Closing as it is already possible to do this.
