### ISSUE TITLE
route and taxonomy filter

### ISSUE THREAD

**Issue by manuel-84** [getgrav/grav#1748]
Hello, I would like to create a custom route to show filtered results and in the site config I've added:
`/prodotti/settore/(.*) >> /prodotti/settore:$1
`
that should do this
`/prodotti/settore/recinzioni >> /prodotti/settore:Recinzioni
`
but the result is always error 404

If I add the same rule but for a redirect (not route) it works but I don't want to change the url

**Comment by rhukster** [comment]
Can you provide the EXACT yaml configuration you have used?  Also did you do this in `user/config/site.yaml` ?

**Comment by manuel-84** [comment]
I did this with admin plugin ([screenshot](https://www.awesomescreenshot.com/image/2969280/4400924f51e5c5de2310c344ac672ef2)), so yes it's written in `user/config/site.yaml`

```
routes:
  '/prodotti-e-servizi/settore/(.*)': '/prodotti-e-servizi/settore:$1'
```

When I call a url like `website/prodotti-e-servizi/settore/Recinzioni` the result is an error 404 page instead of the page corresponding to `website/prodotti-e-servizi/settore:Recinzioni`

**Comment by atzorvas** [comment]
I have the same problem, and truth is I can't really understand why this is happening :confused:
