### ISSUE TITLE
Problem with URL encoding in Cyrillic

### ISSUE THREAD

**Issue by miketsts** [getgrav/grav#1749]
I embed the following link in the markdown:
`[George Orwell](https://ru.wikipedia.org/wiki/%D0%94%D0%B6%D0%BE%D1%80%D0%B4%D0%B6_%D0%9E%D1%80%D1%83%D1%8D%D0%BB%D0%BB)`

As a result, I get the following link in the browser:
`https://ru.wikipedia.org/wiki/%D0%94%D0%B6%D0%BE%D1%80%D0%B4%D0%B6_%D0%9E%D1%80%D1%83%EF%BF%BD_%D0%BB%D0%BB`

Apparently, the UTF8 replacement symbol "%EF%BF%BD_" is inserted instead of "%D1%8D". 
Another example with some other problematic characters:
`[Aldous Huxley](https://ru.wikipedia.org/wiki/%D0%A5%D0%B0%D0%BA%D1%81%D0%BB%D0%B8,_%D0%9E%D0%BB%D0%B4%D0%BE%D1%81)`

is converted to:
`https://ru.wikipedia.org/wiki/%D0%A5%D0%B0%D0%BA%EF%BF%BD_%D0%BB%D0%B8,_%D0%9E%D0%BB%D0%B4%D0%BE%EF%BF%BD_`

**Comment by rhukster** [comment]
I found the issue, I just need to understand the implications of fixing it. :)

**Comment by rhukster** [comment]
Ok this should work, and be 'safe' for other non-multibyte URLs

**Comment by miketsts** [comment]
Works for me.
Thanks a lot!
