### ISSUE TITLE
don't attempt to process files starting by .# or symlinks to non-existent files

### ISSUE THREAD

**Issue by drzraf** [getgrav/grav#175]
Using emacs client to edits files, unsaved file imply that a temporary file is created.
In my case this file:
- is named _.#default.md_ 
- is in the same directory than _default.md_
- is a symlink
- point to a "socket address" [= non-existent regular file, but it's for emacs consumption:(user@localhost.local.7621:1429404450)]

Grav fails "Crikey!" in such case:
```
5. RuntimeException
…/­system/­src/­Grav/­Common/­Filesystem/­Folder.php56 
```
(more exactly the ```file_modified = $file->getMTime();```)

**Comment by rhukster** [comment]
Should be resolved with this new filtering mechanism:

https://github.com/getgrav/grav/commit/bb49098a055b87d23ce2af0426c8c96f486da393
