### ISSUE TITLE
Problem with URL encoding in Greek

### ISSUE THREAD

**Issue by embranceii** [getgrav/grav#1751]
I can neither edit from the ACP or see any page thay has greek characters in the URL.
For example:http://embrancesblog.com/articles/crossfit-forging-elite-fitness works fine.
But http://embrancesblog.com/articles/%CE%AC%CF%81%CF%83%CE%B5%CE%B9%CF%82-%CE%B8%CE%B1%CE%BD%CE%AC%CF%84%CE%BF%CF%85-5-%CE%BC%CF%8D%CE%B8%CE%BF%CE%B9-%CF%80%CF%81%CE%B1%CE%B3%CE%BC%CE%B1%CF%84%CE%B9%CE%BA%CF%8C%CF%84%CE%B7%CF%84
doesnt.Now that URL has Greek chars in it.
I take that in current version Grav doesnt support utf-8 urls?

**Comment by rhukster** [comment]
Same issue as this: https://github.com/getgrav/grav/issues/1749 ?

**Comment by rhukster** [comment]
Specifically this: https://github.com/getgrav/grav/commit/83fdecbdd165aae2786f2e57d3876cc345218a7f#diff-dc4183ef1717fec67992f44218eaaa01L118

**Comment by embranceii** [comment]
Pretty much same issue,but I am not sure if its caused bu wrong conversion.

**Comment by rhukster** [comment]
Please test by removing replacing the existing line 118 with:

```
$url = $excerpt['element']['attributes']['href'];
```

This is without the extra htmlspecialchars and urldecode stuff.

**Comment by embranceii** [comment]
Just did.Still not accessabale in either the site or the ACP.

**Comment by rhukster** [comment]
If you can provide some details, that would help.. Ie, what is the URL you are actually trying to reach, the one that is correct?

**Comment by embranceii** [comment]
the site is embrancesblog.com/
everything that seems like mumbojumbo is reek charsacters.
The urls arent acesble through ACP or direct url.

I fyou still want to see what could be wrong I can give you access to both site and FTP>

![2017-11-16 19_32_19-pages _ grav](https://user-images.githubusercontent.com/33728749/32906237-f5445eae-cb04-11e7-8a4c-15939f5ad627.png)
![2017-11-16 19_32_42-pages _ grav](https://user-images.githubusercontent.com/33728749/32906238-f5f51b86-cb04-11e7-949f-ec2d31239f06.png)

**Comment by embranceii** [comment]
Also even if I try to add a page,and write the folder name in Greek chars,its auto converted in english.
![2017-11-16 19_36_01-pages _ grav](https://user-images.githubusercontent.com/33728749/32906378-698fc9a6-cb05-11e7-9f51-1bbaf2eb8bfd.png)

**Comment by mahagr** [comment]
@rhukster See my comment in linked diff.

**Comment by embranceii** [comment]
Hi there. Is this issue being worked on?
Cant wait to get rid of wordpress :/

**Comment by rhukster** [comment]
i'm out of town until tomorrow, will look at it then.

**Comment by rhukster** [comment]
Turns out my 'quick' fix actually broke some things with link attributes.  Looking for a better fix.

**Comment by rhukster** [comment]
This is a bigger problem than I originally thought. I went make quit a few versions and this never worked.  However I do have a possible solution:

1) Use a non-special-char folder name 
2) Override the `slug` in the `Advanced` -> `Overrides` section on the page.  This does set the slug properly, and also it's routable.

I will have to dig in deeper to this problem at a later date, as I have other pressing obligations.

**Comment by rhukster** [comment]
Actually after debugging, it turned out to be a really simple fix!

https://github.com/getgrav/grav/commit/362ee4c9eb4002cfe6cc0750fba2de244f90117a

Should be all sorted with this little edit.

**Comment by embranceii** [comment]
I downloaded you latest full repo, and the fix with the slug works,but without it,it doesnt.Can someone confirm I am no the only one with this problem?

**Comment by rhukster** [comment]
Send me a couple of you pages (folder + markdown files) and i'll test, but works for me right now with develop.

**Comment by embranceii** [comment]
Just did.Please chekc you email.
I even tried making a new folder/new post but still no luck.On creation of a page still doesnt allow ,only English is allowed for folder names etc.
Plus I can change the slug ONLY in already english titled pages as greek pages arent accesable in the admin.

**Comment by embranceii** [comment]
If you still need more info I will send credentials of my site so you can see it yourself.
