### ISSUE TITLE
Get all collection results ignoring a tag

### ISSUE THREAD

**Issue by tutchmedia** [getgrav/grav#1754]
Hi, 

Is it possible we can use findTaxonomy to get results ignoring any child pages with a given tag?

Basically something like show all results ignoring those with the the tag featured?

I did a search and couldn't find any answers so hoping i'm just being dumb.

Craig

**Comment by rhukster** [comment]
No this is a bit beyond current capabilities.  However, it shouldn't be too hard to use `findTaxonomy` then iterate over the collection and simply remove the child pages you want to ignore.
