### ISSUE TITLE
Caddy Web Server

### ISSUE THREAD

**Issue by justinglock40** [getgrav/grav#1755]
I can not get Caddy to serve up the Grav webpage. Any help you can provide? I tried using the pre-made caddy file but it didn't work for me

**Comment by DanielSokil** [comment]
I believe caddy supports only static files unless you set it up with FastCGI.
https://caddyserver.com/docs/fastcgi
OR use
https://github.com/dsamojlenko/php-caddy

**Comment by rhukster** [comment]
I've not used Caddy myself in a couple of years, but we have some Grav users who use Caddy daily with Grav.  You might want to hop on the slack channel and talk to them about it?

**Comment by justinglock40** [comment]
I figured out the hosting on caddy part. Now I just need to figure out how to actually code the page and stuff.
