### ISSUE TITLE
Be able to change system paths/URL

### ISSUE THREAD

**Issue by embranceii** [getgrav/grav#1757]
A very basic step to aoid hacking attempts,is to allow for site wide system url changes through variables.
e107 cms allowed that through the config file where you would specify where themes are stored,plugins etc.

Is this a viable feature asset for GRAV?
My WP sites lately have been hacked over and over,since its easy to detect what cms a site is using UNLESS it uses something differently.

**Comment by rhukster** [comment]
This can be done by creating a `setup.php` and modifying the streams locations. https://learn.getgrav.org/advanced/multisite-setup

However, be aware that 'security through obscurity' is pretty much the weakest kind of security there is.

**Comment by mahagr** [comment]
Most of the settings can be changed from yaml file as well as only few are needed for initialization. Setup.php is mostly needed only if you want to set multisite-setup.
