### ISSUE TITLE
Unsetting uploads stopped working

### ISSUE THREAD

**Issue by drnasin** [getgrav/grav#1758]
hi guys,

this stopped working:
```
uploads:
  unset@: true
```
while
```
content:
  unset@: true
```
still works...

any reason?

**Comment by rhukster** [comment]
I think you have to unset `media-order` as well as this is tied closely to uploads.

**Comment by drnasin** [comment]
urgh..thanks...will add it,,,but now I have to go thru all my grav installations and blueprints and add this...there was no easier solution than breaking BC?

**Comment by rhukster** [comment]
Well, unsetting uploads is not something that the average users does, and is not something we even test regularly.  The problem with Grav is that its so flexibly that there's really an unlimited number of combinations of things, and we can't always test or foresee every issue.  This one has come up a couple of times, and the solution is simple enough. Ensuring 100% backwards compatibility on every scenario is not always possible, but we do try our best!

**Comment by drnasin** [comment]
alright, fair enough, thanks for clarification @rhukster. btw I don't know if you saw my question in 2.0 thread but if you need any help with coding do let me know. I'm willing to help as much as I can. Just not sure where to start...
