### ISSUE TITLE
Mistake in nl.yaml (MONTHS_OF_THE_YEAR and DAYS_OF_THE_WEEK)

### ISSUE THREAD

**Issue by kpranke** [getgrav/grav#1759]
Months and days of the week in Dutch should not be capitalised. Atm some are and some are not.

Currently:
MONTHS_OF_THE_YEAR:
  - Januari
  - Februari
  - Maart
  - april
  - Mei
  - Juni
  - Juli
  - Augustus
  - september
  - Oktober
  - november
  - december
DAYS_OF_THE_WEEK:
  - Maandag
  - Dinsdag
  - Woensdag
  - Donderdag
  - Vrijdag
  - Zaterdag
  - Zondag

**Comment by rhukster** [comment]
You can fix this by proposing the change via crowdin: https://crowdin.com/project/grav-core
