### ISSUE TITLE
Modular page header not work

### ISSUE THREAD

**Issue by Ideneal** [getgrav/grav#176]
Creating a modular page it will break if after the header of the main md file there is not at least one space.

If the page has an header and has an empty content, the final header symbol '---' must be followed at least one space to work successfully.

**Comment by rhukster** [comment]
I'll look into this one!

**Comment by rhukster** [comment]
Fixed in toolbox: https://github.com/rockettheme/toolbox/commit/c8573ccc8bdf425b6c7a34af936048ec8bbede63

Actually turns out it affected all pages, not just modular.

**Comment by Ideneal** [comment]
Perfect! Thanks! :)
