### ISSUE TITLE
grav with H2O webserver error

### ISSUE THREAD

**Issue by DanielSokil** [getgrav/grav#1760]
My Error Log File
starting new worker 32649
[INFO] raised RLIMIT_NOFILE to 1048576
h2o server (pid:32649) is ready to serve requests
[lib/handler/fastcgi.c] in request:/index.php/:PHP Fatal error:  Uncaught RuntimeException: Opening file for writing failed on error fopen(/var/www/html/cache//compiled/files/b296ac48b18c22fb9ad19958ded5d09f.yaml.php): failed to open stream: Permission denied in /var/www/html/vendor/rockettheme/toolbox/File/src/File.php:202
Stack trace:
#0 /var/www/html/vendor/rockettheme/toolbox/File/src/File.php(320): RocketTheme\Toolbox\File\File->lock()
#1 /var/www/html/vendor/rockettheme/toolbox/File/src/PhpFile.php(31): RocketTheme\Toolbox\File\File->save(Array)
#2 /var/www/html/system/src/Grav/Common/File/CompiledFile.php(67): RocketTheme\Toolbox\File\PhpFile->save(Array)
#3 /var/www/html/system/src/Grav/Common/Config/Setup.php(178): Grav\Common\File\CompiledYamlFile->content()
#4 /var/www/html/system/src/Grav/Common/Processors/SiteSetupProcessor.php(18): Grav\Common\Config\Setup->init()
#5 /var/www/html/system/src/Grav/Common/Grav.php(132): Grav\Common\Processors\SiteSetupProcessor->process()
#6 /var/www/html/system/src/Grav/Common/Grav.php(379): Grav\Common\Grav->Grav\Common\{clos in /var/www/html/system/src/Grav/Common/File/CompiledFile.php on line 83

My h20 conf File
hosts:
  "localhost:80":
    listen:
      port: 80
      host: 0.0.0.0
    paths:
      "/":
        file.dir: /var/www/html
        redirect:
          url: /index.php/
          internal: YES
          status: 307

file.custom-handler:
  extension: .php
  fastcgi.spawn: "PHP_FCGI_CHILDREN=10 exec /usr/bin/php-cgi"

access-log: /var/log/h2o/access.log
error-log: /var/log/h2o/error.log
pid-file: /var/run/h2o/h2o.pid
#http2-reprioritize-blocking-assets: ON

**Comment by rhukster** [comment]
Never heard of it! Anyone else use this webserver that might have an idea?

**Comment by DanielSokil** [comment]
Problem Solved.
https://github.com/h2o/h2o/issues/1507

**Comment by rhukster** [comment]
Maybe you could provide a sample config for H2O server for the webserver-configs directory?

**Comment by DanielSokil** [comment]
Here is my h2o.conf file working perfectly.
`
file.etag: on
compress-minimum-size: 0
expires: off
compress: on
file.dirlisting: off
file.send-compressed: on
access-log: /var/log/h2o/access.log
error-log: /var/log/h2o/error.log
pid-file: /var/run/h2o/h2o.pid
http2-reprioritize-blocking-assets: on
user: www-data
hosts:
  "localhost:80":
    listen:
      port: 80
      host: 0.0.0.0
      "/grav":
        file.dir: /var/www/html/grav/
        redirect:
          url: /grav/index.php
          internal: YES
          status: 307
file.custom-handler:
  extension: .php
  fastcgi.connect:
    port: /run/php/php7.1-fpm.sock
    type: unix
`
