### ISSUE TITLE
[Suggestion] Embed PDF

### ISSUE THREAD

**Issue by iachopolo** [getgrav/grav#1761]
I'm not sure if this is the place to say this. But as the title says I think it would be very cool and usefull (I would use it) to have a way to embed a PDF file in the page.
Love all the work you've done!
Cheers!

**Comment by rhukster** [comment]
There's a plugin: https://github.com/iusvar/grav-plugin-snappygrav

**Comment by iachopolo** [comment]
I think I wasn't clear. What I mean is to display the PDF file within the page. Not to export the page or parts of it in PDF format.

**Comment by rhukster** [comment]
Ah ok, that is going to require something like: https://github.com/mozilla/pdf.js

**Comment by iachopolo** [comment]
Yes, you are right. My suggestion was to make a plugin with that behaviour
