### ISSUE TITLE
Could not save list with more than 60 items

### ISSUE THREAD

**Issue by tboulogne** [getgrav/grav#1762]
Hello,

I get a strange behaviour if i have a list field with more than 60 items.

i get `Invalid Security Token` error.
If i switch to expert mode, no error and data saved.
if i keep the list only with 60 items, data saved.

Any tips to surround this please ?
(example file attached)

Thanks for help.

Regards,
[default.txt](https://github.com/getgrav/grav/files/1497321/default.txt)

**Comment by rhukster** [comment]
It could be an out of memory issue and if so you might need to up that memory value in `php.ini`.

**Comment by tboulogne** [comment]
thanks @rhukster for your answer.
 
I try with memory_limit [256, 512, 1024]. Same error :-(.
Only one way to get it work is to keep list under 60 items.

**Comment by tboulogne** [comment]
hello @rhukster ,

Increasing max_input_vars from 1000 to 2000 seems to work.

I do further testing and confirm.

Regards

**Comment by rhukster** [comment]
That makes total sense. With 60 items and ach item having a few fields, you could easily have over 1000 form fields in that submission.

**Comment by mahagr** [comment]
Could be cool to add some JS to check if the form is too long and json encode it if it is. (hint hint hint)

**Comment by tboulogne** [comment]
@rhukster : yes. I confirm, it works.

@mahagr : the js check will not modify the php variable. Perhaps suggest into grav requirements a greater max_input_vars ?
