### ISSUE TITLE
Blog entries are ordered by date locally but if deployed are in a random (?) order.

### ISSUE THREAD

**Issue by inktrap** [getgrav/grav#1764]
Hi everyone!

This is so weird. I am developing locally and I am sorting articles by a custom header field which works fine. If I deploy grav to my [hoster](https://uberspace.de) the posts seem to appear in a random ordering.

Grav has not many requirements (apache, php, mod_rewrite, optional: mod_ssl) and the only thing I can think of [is their virtualhost config](https://wiki.uberspace.de/webserver:htaccess#hintergrunddie_virtualhost_konfiguration).

Here is the application: <https://bambule.uber.space/>
Here is an event: <https://bambule.uber.space/event/rechtsextremismus-erkennen-und-handeln?view-source>

The key by which I sort is: ``time: start``
Here is my ``event.md``:

~~~
---
title: Events
blog_url: event
body_classes: header-image fullwidth
onpage_menu: true
visible: false

sitemap:
    changefreq: daily
    priority: 1.03

content:
    items: @self.children
    order:
        by: header.time.start
        dir: asc
    pagination: true
    limit: 0
    dateRange:
        start: today
        field: header.time.start

feed:
    description: Blah
    limit: 0

---

# Blah
~~~

I think that this is independent of the file creation or modification time or the name of the directory. Edit: the grav error log is empty.

Any ideas?

**Comment by inktrap** [comment]
Another thing is … I guess grav processes the date format in header.time.start as a string, since I don't know how to give grav an indicator that it is acutally a date. However, the date format I set explicitly in my user config is: ``'Y-m-dTH:i:sO'`` and since all dates are converted (by me) to the same timezone beforehand, this should work.

**Comment by inktrap** [comment]
If someone e.g. @rhukster needs access details to a webspace I would be happy to provide a fresh grav install on a fresh webspace to explore this and would provide the credentials privately and/or add your ssh key.

**Comment by rhukster** [comment]
We recently had a similar situation: https://github.com/getgrav/grav/issues/1740

I created a fix in develop: https://github.com/getgrav/grav/commit/70284e1517a3bdbc3d04027de4ffc8ba72f184fa

This really should fix it if you set the order to 'folder' rather than the default (filesystem).  Can you test it?

**Comment by inktrap** [comment]
My folder IDs should not influence ordering, since my folder IDs are numbers, like ``1580056825390124`` and I don't want to sort by those. I am ordering by a custom field ``header.start.time``.

**Comment by inktrap** [comment]
So, I should change

~~~
pages:
  theme: antimatter
  order:
    by: header.time.start
    dir: asc
~~~

to

~~~
pages:
  theme: antimatter
  order:
    by: folder
    dir: asc
~~~

RIght? Or are you talking about a different value?

**Comment by rhukster** [comment]
if you have a custom header variable for sorting, then it should order the same on any system.

**Comment by inktrap** [comment]
Okay, if I create a minimal example, it doesnt event work locally. #1641 #1199 might be related. I want to sort by a custom header value that contains a date: time.start in this case.

I made a manual to reproduce this/share my config: https://github.com/inktrap/grav-1764

**Comment by rhukster** [comment]
Thanks, this is super handy... the header sorting just assumes a string, so dates are not really going to be handled effectively for sorting.  let me see what i can do tho.

**Comment by rhukster** [comment]
First thing i found from your sample:

You are referencing `header.time.start`, however your YAML is not indented correctly:

```
---
title: "Date 2018-06-15"
slug: ""
taxonomy:
tag: [example]
category: blog
template: item
time:
start: 2018-06-15T18:00:00+0100

---

``time.start: 2017-06-15T18:00:00+0100``

===

Content.
```

You would need:

```
...
time:
    start: 2018-06-15T18:00:00+010
```

Alternatively, you can simply change your ordering to use: 

```
content:
    items: @self.children
    order:
        by: header.start
        dir: asc
    pagination: true
    limit: 0
```

Now this actually works! However, there's not special date handling, its simply sorting by string. I'm going to look to see if I can detect if the field is a date/timestamp.

**Comment by inktrap** [comment]
Ooops, the yaml indentation mistake happened because I did not check the output of create.sh carefully. :/

However, this  _not_ the problem … I fixed the issue, recreated the files, pushed to github and deployed to <https://getgrav.uber.space/> and they are still unordered.

I installed the view-source plugin, so you can verify this easily without logging in (append ``?view-source``).

**Comment by inktrap** [comment]
- the first file: <https://getgrav.uber.space/blog/10040?view-source> ``time.start: 2017-05-08T18:00:00+0100``
 - the second file: <https://getgrav.uber.space/blog/10703?view-source> ``time.start: 2017-05-23T18:00:00+0100``
 - the fourth file: <https://getgrav.uber.space/blog/10140?view-source> ``time.start: 2017-04-27T18:00:00+0100``

**Comment by rhukster** [comment]
I think that the problem is probably the nested nature of the `header.time.start` as it does work fine with just `header.start`

**Comment by inktrap** [comment]
But that would be something to look into anyway, right? Docs mention: ``header.taxonomy.year`` [explicitly](https://learn.getgrav.org/content/collections#ordering-options)

**Comment by rhukster** [comment]
Yah, looks like it also works with `header.time.start`, so not sure what the deal is for you.  I have it ordering correctly now.

**Comment by inktrap** [comment]
Mmmh here: https://getgrav.uber.space/ it does not work with either of them. I switched it to ``header.start``

**Comment by inktrap** [comment]
@rhukster I [forked](https://github.com/inktrap/grav) grav and added debug statements. I copy pasted the output of dump() for grav on my localhost and on uberspace, with 5, 27 and 30 files. Currently grav is deployed with 5 files and dump statements [here](https://getgrav.uber.space/)

(27 and 30 are  included because at one point it seemed to be related to the number of files, ordering <28 pages correctly, but that was not repoducible).

**Comment by inktrap** [comment]
@rhukster and @flaviocopes 

I found the issue: On the server, the ``intl`` module is loaded. If I install ``intl`` locally, the behaviour occurs locally too. See my modified [Pages.php](https://github.com/inktrap/grav/blob/develop/system/src/Grav/Common/Page/Pages.php#L1309).

There are only three different options for [``Collator::asort``](https://secure.php.net/manual/de/collator.asort.php) and on my system ``$sort_flags`` defaults to ``14`` (I have not found a description of these constants, @flaviocopes mentions, that the constant ``SORT_NUMERIC`` translates to ``1``). These are available:

~~~
$col->asort($list, Collator::SORT_REGULAR);
$col->asort($list, Collator::SORT_STRING);
$col->asort($list, Collator::SORT_NUMERIC);
~~~

I tried ``_REGULAR`` and ``_NUMERIC`` and only ``SORT_STRING`` gave the expected results. It is what I would have assumed as a default and I guess I am not alone with this:

> Thanks, this is super handy... the header sorting just assumes a string, so dates are not really going to be handled effectively for sorting. let me see what i can do tho.

On the other hand, I would expect from ``SORT_REGULAR`` that it interprets strings as strings (and then it would behave the same as ``SORT_STRING`` which it does not.

So here are some ideas:

 - one could set the type of a header field in yaml by convention. Personally I like haskell's way of explicitly forcing a type with ``:`` which would result in something like this: ``time.start::date``. We should think about possible types. Since [PHPs default types](https://secure.php.net/manual/en/language.types.intro.php), the simple types are already available in [YAML](http://www.yaml.org/refcard.html).

 - this would have to be parsed and would influence the behaviour of sorting. One underlying question is: how should ``intl``'s ``Collator::asort`` sort e.g. a date? No option seems to fit.

 - I honestly don't see the advantage of ``SORT_NATURAL``.  Could someone explain, please? 
[Btw.: the limit enforced by the preg_replace_callback is not documented](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Pages.php#L1263) (original file).

And my last question is: how much of these settings should be configurable by the user?

These problems with unwanted/unexpected results of ``collator->asort()`` occured before and #1199 should never have been closed without solving the underlying issue.

# TODO

 - decide if explicit types for config values are useful and choose a syntax
 - think about ``intl``'s ``Collator::asort`` (which defaults/options fit here?)
 - perhaps include additional configuration options?
 - at least mention in the requirements that grav is ``intl`` aware
 - write a unittest to assure that sorting with ``intl`` works as expected :)

**Comment by inktrap** [comment]
# Explicit $sort_flags

We could change

~~~
content:
    order:
        by: date
        dir: desc
~~~

to

~~~
content:
    order:
        by: date
        dir: desc
        flag: SORT_STRING
~~~

where flag has a value specified by either ``Collator::arsort`` or by regular ``arsort()``. Alternatively one could name it ``sort_flag: SORT_STRING`` as it is known from PHP and the grav source; however this would be redundant to the whole ``order.`` block.


# Explicit types

 - if my custom header variable is start, we could either write:

~~~
 start : '2018-06-15T18:00:00+0100::date'
~~~

or could create a fixed structure, like

~~~
 start.value : '2018-06-15T18:00:00+0100'
 start.type : 'date'
~~~

I believe that both changes should be implemented in [buildSort](https://github.com/getgrav/grav/blob/70284e1517a3bdbc3d04027de4ffc8ba72f184fa/system/src/Grav/Common/Page/Pages.php#L1180) and that explicit sort_flags should overwrite explicit types.

**Comment by rhukster** [comment]
Ok, that's definitely something I can investigate.  I know that flavio added some `intl` support a while back, but as i don't have much use for it myself, I don't often test with it.

**Comment by rhukster** [comment]
I think the main issue is the `SORT_NATURAL` is not supported by the the `intl` collate logic, so some funky workarounds are required. That's where that regex comes in.. it's testing for folder order, and simplifying the search so it's numeric only.

I've added a little logic to set the sort_flags based on if the search is numeric or not, and it seems to work for your date example, and should work pretty well for other types too.

**Comment by rhukster** [comment]
I might also add the ability to manually override and disable the `intl` support but it would have to be on by default to maintain backward compatibility.  But at least it would let you disable the intl logic if the plugin is installed by you really don't need it.

**Comment by inktrap** [comment]
While this works for my case, it does not work for a numeric value.

> I can confirm that {% set events = eventsRaw.order('header.startdate', 'desc', null, 1) %} with Grav 1.1.9 with my current tests.

Where 1 means ``SORT_NUMERIC``. see #1199 .

Why not pass sort flags explicitly (they are already passed forward from ``order()``) and set sorting to ``SORT_STRING`` as a default? See proposal ``$sort_flag``

**Comment by rhukster** [comment]
SORT_NATURAL is supremely useful in that it sorts things as most people expect when mixing strings and numbers.  See the examples here: 

http://php.net/manual/en/function.natsort.php

**Comment by rhukster** [comment]
also SORT_NUMERIC only works on purely numeric values.  It was working fine in my testing.  This solution is not ideal, but the fundamental problem is that collator does not suppor the natural sorting that works so well for regular asort.  

I have added the ability to just skip the `intl` logic by setting `intl_enabled: false` in the system.yaml. This will ensure that your logic will run the same on a server that has intl installed or not. 

Having the ability to set the sort flags for a specific sort is possible, but without proper natural support it's not going to fix everything.

**Comment by inktrap** [comment]
Alright, this fixes the issue for me!

Thank you for your input and time and the natsort examples!

**Comment by Sogl** [comment]
@inktrap So what the fix for now?
