### ISSUE TITLE
Add rel="noopener noreferrer" to links with target="_blank"

### ISSUE THREAD

**Issue by courtneywright** [getgrav/grav#1765]
Hi, is it possible to add support for `rel="noopener noreferrer"` to links containing `target="_blank"` so that the Grav syntax can be used instead of something like: `<a href="link" target="_blank" rel="noreferrer noopener">Link</a>`?

This is a security issue. The new page has access to your window object and can navigate your page to a different URL. More info here if needed: https://mathiasbynens.github.io/rel-noopener/

**Comment by rhukster** [comment]
Just do this:

```
[your link](/your/link?target=_blank&rel=norefferer,noopener)
```
