### ISSUE TITLE
Taxonomy Default Values

### ISSUE THREAD

**Issue by tutchmedia** [getgrav/grav#1766]
Hi,

I currently have a custom taxonomy for Departments. I can display a list of all the selected departments for jobs available. 

However, i would like to put in departments and display them for departments which do not have any available careers.

I've tried doing merge to push in a pre-existing array of the Departments but this overwrites the total of jobs available..

Is there a way of doing this?

Thanks

**Comment by rhukster** [comment]
First you would need to create a new blueprint for your page type that extends the default blueprint. 
 Then you would have to 'unset' the current taxonomy field, and then replace it with a custom field that provides a list of departments to choose from.

So yes it's doable.
