### ISSUE TITLE
Environment configuration is ignored when using other port then 80

### ISSUE THREAD

**Issue by jscontrust** [getgrav/grav#1768]
I try to create a specific configuration for a server running on a specific port on localhost, so I created a specific configuration in `user/localhost/config/system.yaml`

When I now access my site with `https://localhost` it reads the configuration. But when I access it with `https://localhost:3000` it loads the default config from `user/config/system.yaml`

I read about environment configuration here:
https://learn.getgrav.org/advanced/environment-config1

I`m using a clean Grav 1.3.8.

**Comment by mahagr** [comment]
Use setup.php file in the root folder of Grav to send initial configuration depending on the port. The file is meant to customize multisite setups for any use case you may think of.

**Comment by rhukster** [comment]
I'm not able to reproduce this.. For me using the built-in PHP webserver on port 8000, the environment is correctly returned as 'localhost' and the correct environment base configuration is used.

**Comment by jscontrust** [comment]
Ok, found the problem: I ran localhost:3000 which accessed browsersync. But Browsersync proxied grav by domain grav.dev. So it did not use the configuration.
