### ISSUE TITLE
antimatter: javascript and subpages visibility

### ISSUE THREAD

**Issue by drzraf** [getgrav/grav#177]
The default antimatter theme needs javascript for the very basic of page switching (click to open the navigation menu).
I suggest that to be discussed. At least the navigation could start visible when javascript is disabled.
I found that when I discovered that subpages would not show up in the navigation menu  without the dropdown option being enabled.
Following the same principle of "content [and usability] first and eye-candiness and features second", I think it'd make sense that default settings do not hide subpages (eg: dropdown: true,)

**Comment by rhukster** [comment]
If you want to provide a Pull Request, I will take a look.  This is just a sample theme, and no-javascript support is not a top priority in our resource allocation.
