### ISSUE TITLE
modular page error

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav#1771]
I got an interesting one here, that i can reproduce on local dev with plain grav and admin / antimatter theme - all the latest.

- create a modular page
- create / or not empty children of the modular page
- try to view the page in the browser and get an error as per the image
![captura de ecran din 2017 12 03 la 13 41 11](https://user-images.githubusercontent.com/7076631/33525893-ac821d86-d82f-11e7-81b8-d1181973c1ac.png)

Not sure if this is due to no information present on the page itself but as soon as I add some text, the error is gone.

Also, once the Modular page is created, the only way to add text is to use the advanced mode (not sure if this is the intended behaviour), as per the image
![captura de ecran din 2017 12 03 la 13 45 28](https://user-images.githubusercontent.com/7076631/33525921-4511e392-d830-11e7-840b-ed18a412663e.png)

just thought you might want to know about this

**Comment by rhukster** [comment]
Well your error is clearing coming from `image-captions` plugin, so probably it's trying to do work on empty content, hence throwing the error.

Can you try editing the `image-captions.php` with this check:

```
    protected function processFigures($content)
    {

        if (trim($content) === '') {
            return;
        }
...
```

**Comment by JohnMica** [comment]
Thanks Andy. I’ll update that and see what happens. I might disable the plugin all together for now.

**Comment by JohnMica** [comment]
update - it seems the disabling /removing of the image-captions plugin did the trick.
