### ISSUE TITLE
Feature request: Default language per single page

### ISSUE THREAD

**Issue by phideas** [getgrav/grav#1772]
It would be nice to have an additional 'default language' selector for every page. 
e.g. page1 would open /en/page1 as default and page2 would open /es/page2 as default.
This feature would help multi language site with mixed content and mixed translations.

**Comment by rhukster** [comment]
Are you talking about admin specifically? if so, please add this issue to the admin issues list, not core Grav? https://github.com/getgrav/grav-plugin-admin/issues

**Comment by phideas** [comment]
Correct. Sorry sometimes I forget admin is a plugin it is so essential. Reposted https://github.com/getgrav/grav-plugin-admin/issues/1282
