### ISSUE TITLE
how to set assest name to be more readable after pipelining ?

### ISSUE THREAD

**Issue by bluis4** [getgrav/grav#1774]
Hi,
is it possible to set the css and js file name in ```root/assests/``` folder to be more readable without manually rename it ? something like ```my_css.css & my_js.js``` not ```c23b81a32b69396a1b11f3cf816f1a17.css```. If possible, how can i do this ?

Thanks

**Comment by rhukster** [comment]
This actually generated based on some attributes:

```
        // Compute uid based on assets and timestamp
        $uid = md5(json_encode($this->css) . $this->css_minify . $this->css_rewrite . $group);
        $file =  $uid . '.css';
```

If you were able to set a fixed name, Grav wouldn't know to regenerate the file when needed.
