### ISSUE TITLE
Hiding images folder from admin panel

### ISSUE THREAD

**Issue by superDuperCyberTechno** [getgrav/grav#1775]
I created a general images folder to host local images according to the [docs](https://learn.getgrav.org/content/media).

But: This is a site that is supposed to be administrated by a third party and as such, having the images folder show up in the Pages menu is somewhat confusing as the folder itself doesn't function as a page at all.

So; is it possible to hide the folder from the Pages overview?

**Comment by rhukster** [comment]
This is currently not possible as all pages are visible to those that have access to view the pages section.  This is something we would like to add, however, as part of a level of ACL control over all pages.  So you could restrict the access to some pages for certain users.
