### ISSUE TITLE
After Upgrade to v1.3.9

### ISSUE THREAD

**Issue by dadannurman** [getgrav/grav#1776]
Plugins

![grav po](https://user-images.githubusercontent.com/28327817/33650676-9442992c-da95-11e7-8a1f-162694324ec3.PNG)

No one

![grav po2](https://user-images.githubusercontent.com/28327817/33650699-a8dec4b4-da95-11e7-9763-92a51d97edf6.PNG)

??

**Comment by pr0ma** [comment]
+1

**Comment by bayrepo** [comment]
+1

**Comment by prinla** [comment]
+1
And the "Check for updates" don't seem to work neither for plugins nor templates

**Comment by rhukster** [comment]
Ugg.  Will look into this ASAP.

**Comment by rhukster** [comment]
1.3.10 released with the fix (basically reverted that GPM PR).  Should show up in GPM in 30 mins, please let me know if you can update to it, or if it has to be done via CLI, backup could be to use the Tools -> Direct Install

**Comment by pr0ma** [comment]
> Install a zip package from a remote location
Give me a link

**Comment by rhukster** [comment]
First you have to turn OFF official `Official GPM` updates in Configuration -> System

Then under tools, select "Install a zip package from a remote location", and paste:

```
https://github.com/getgrav/grav/releases/download/1.3.10/grav-update-v1.3.10.zip
```

That should fix it. 

WHen GPM is updated i'll do some more testing and see if Grav will update via GPM directly or not.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav/issues/1776#issuecomment-349649871 [https://github.com/getgrav/grav/issues/1776#issuecomment-349649871]

Instructions here.

- Andy Miller
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.8.79&pv=10.13.1&source=email_footer_2]
On Wed, Dec 6, 2017 at 6:54 AM, pr0ma <notifications@github.com> wrote:
Install a zip package from a remote location
Give me a link

**Comment by pr0ma** [comment]
working / thx

**Comment by pr0ma** [comment]
Small hack for Form plugin

`	 $stream_opts = stream_context_create([
                'ssl' => [
                    'verify_peer'      => false,
                    'verify_peer_name' => false
                ]
            ]);
                 $url = 'https://www.google.com/recaptcha/api/siteverify?' . $query;
                $response = json_decode(file_get_contents($url,false, $stream_opts), true );`
Another not SSL site not work with google captcha

**Comment by rhukster** [comment]
Blog post related to this: https://getgrav.org/blog/gpm-issue-in-grav-1.3.9

**Comment by dadannurman** [comment]
to v1.3.10 fix

![grav po3](https://user-images.githubusercontent.com/28327817/33701751-cd2b4d7a-db52-11e7-9bcb-13fd40e0f800.PNG)

than

![disk2](https://user-images.githubusercontent.com/28327817/33701732-b7ecb9ee-db52-11e7-9999-b8036d7c85b0.PNG)
