### ISSUE TITLE
Plugin Admin Addon User Manager

### ISSUE THREAD

**Issue by pr0ma** [getgrav/grav#1778]
After update Admin Panel plugin Admin Addon User Manager not work normal.
Try change avatar - result error "Data type 'user-manager/test' doesn't exist!"
![2017-12-08 10 57 48](https://user-images.githubusercontent.com/34234320/33758546-5933015a-dc07-11e7-958b-aa207e42fa4e.png)

**Comment by rhukster** [comment]
Please create an issue on the User Manager plugin: https://github.com/david-szabo97/grav-plugin-admin-addon-user-manager
