### ISSUE TITLE
*Feature Enhancement* Custom Routing

### ISSUE THREAD

**Issue by t35h** [getgrav/grav#178]
In some situations unique slugs may not be desirable for a permalink structure for whatever reasons - e.g: post titles may change and/or the same post title may be used often. 

So a sequential number as the unique identifier for the blog post followed by a url friendly title (just for aesthetics) can be used instead. This is kinda similar to how Stackoverflow handles it's permalinks to questions. When question titles are edited the old permalinks still work.

/blog/1/default.md
/blog/2/default.md
etc.

If routing supported more than 1 wildcard this could be as simple as

```
routes:
   /blog/<wildcard1>/<wildcard2>: /blog/<wildcard1>
```

`/blog/1/just-for-looks` would route to `/blog/1`

**Comment by mahagr** [comment]
Just some background info:

Right now Grav only does simple array lookup to figure out if path exists or not. So our routing mechanism doesn't support wildcards at all. The reason why we didn't originally add support for more advanced routers was the speed -- all advanced routers took too much time to initialize.

Adding wildcard support may seem to be easy, but in reality it's the most complicated part of most routers and also slow down routing considerably.

**Comment by t35h** [comment]
Well I definitely do not like the idea of there being a performance hit for it.

Could there be a simpler solution to my example though? Such as having an option to ignore the last part of a path if the path meets a certain condition (e.g being prefixed with /blog)

**Comment by rhukster** [comment]
any solution is going to require wildcards and regex, that's just how routing has to work.  It's still something I think could be an optional feature though.  Not something that is going to impact Grav by default, and the small trade off in performance will be worth it for some people that really want that control over the routing.

**Comment by mahagr** [comment]
There is also alternative way over regexps, if we just have /blog/* kind of wildcards. Its not nearly as flexible as regexps, but by splitting the urls into a tree and going it through node by node until you get to the action is one possibility.

Its also true that static pages could be handled in a different way to dynamic ones, and many regexp routers already do that. The downside of all of which I tested was that compiling all the routes is pretty slow task.

**Comment by rhukster** [comment]
I've implemented a simple regex solution in this commit: https://github.com/getgrav/grav/commit/6d2a7c53dc9358fe057ea380967e882075acc6ad

Basically it lets you setup both redirects and routes (aliases) with preg_replace type syntax.  So for example these are valid entries in `site.yaml`:

```
redirects:
    /changelog: /blog/the-urban-jungle
    /redirect/(.*): /blog/$1
    /complex/(.*)/(.*): /blog/$1/folder/$2
routes:
    /something/else: /blog/focus-and-blur
    /another/(.*): /blog/$1
    /one-ring/(.*): /blog/sunshine-in-the-hills
```

I think the results are pretty obvious and quite powerful.
