### ISSUE TITLE
[change-resource] Rename 'Image Captions' to 'Img Captions'

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1780]
To avoid conflict with [Image Captions](https://github.com/trilbymedia/grav-plugin-image-captions), please rename the [original](https://github.com/OleVik/grav-plugin-imgcaptions) to 'Img Captions' in GPM.

**Comment by rhukster** [comment]
I can't change the 'slug' unless you change the repo.  Your updated name should display fine though as that is pulled from the blueprint. 

Everything looking ok to you though?

**Comment by OleVik** [comment]
The slug should be fine, 'imgcaptions' matches the new nomenclature. Name is up to date in blueprint, and v2.0.0 is released.
