### ISSUE TITLE
Configuration by environment does not use the hostname but the url (docs are unclear here)

### ISSUE THREAD

**Issue by inktrap** [getgrav/grav#1781]
[Configuration by environment](https://learn.getgrav.org/advanced/environment-config) says that a configuration by environment:

> can be easily accomplished by providing an override of that setting in the file:
> user/localhost/config/system.yaml
> where localhost is the hostname of the environment (this is what the host you enter in your browser, e.g. http://localhost/your-site) 

however this is problematic.

Example: I am using apache with virtualhosts and my server ``test.box.int`` on the host ``box``. Thus, ``gethostname()`` returns ``box``, but if I create an environment config in ``user/box/config/`` it is not picked up by grav. So at least the term hostname is wrong here.

~~Secondly, I would argue in favor of **really** using the hostname as it is returned by ``gethostname()``, not the URL/domain~~ (see *Edit 2*) :
 
 - the domain is (in most cases, e.g. shared hosting) not the hostname.
 - there might be multiple domains defined for one grav instance ``box.org`` and ``box.com``.
 - the name of the virtual server ``test.box.int`` might not be the hostname ``box`` nor what i type in the address bar (``mynewsupergravsite`` without a TLD but defined in ``/etc/hosts``).

Edit: however, this would require different servers/hostnames for staging, production, preprod aso. which might not be flexible enough.

Edit 2: so, the best idea is to use whichever is available from these:
 - ``subdomain.example.tld``
 - ``example.tld``
 - ``example``
and perhaps edit the documentation to reflect this.

And if some of these environments share a config, I would symlink them, which is an important detail that one *should not forget*, because it might lead to (security) issues. E.g. if my production grav config is under ``example.com`` and my hoster provides a URL ``example.uber.space``, then the config should apply to both environments (and it might be the case that the default configuration is not the production configuration, right?!). (Sorry for the lengthy text).

**Comment by rhukster** [comment]
Yes, it is the URL, and this is not something we can change because it's been that way since the beginning.  If we were to change the behavior at this point, it would totally break configuration and options that have been set based on this premise.

**Comment by inktrap** [comment]
I am going to move this issue to grav-learn then and close it here as wontfix.
