### ISSUE TITLE
Duplicate entry in GPM CLI for upgrade and direct install

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav#1783]
It's not really clear what commands are available or not because of duplicate entries:

<img width="794" alt="34051130-b417ed9a-e1bd-11e7-805b-6d50a47fdc57" src="https://user-images.githubusercontent.com/10623367/34051197-ef20693a-e1bd-11e7-8c68-b9a061a77144.png">

**Comment by rhukster** [comment]
Those are just aliases, so you can type with `-` or not.

**Comment by jimblue** [comment]
Oh ok I tough it was a mistake. 😄
