### ISSUE TITLE
Plugins and Themes - Unable to Access/Update After Beta Install

### ISSUE THREAD

**Issue by brokentechnology** [getgrav/grav#1784]
I updated Grav to the latest Beta build. I have found the following issue when trying to access/update Plugins and Themes within Grav:

Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("Not Implemented").

I tested using GPM and have a similar error:

[root@tools public_html]# bin/gpm update

GPM Releases Configuration: Testing

  [BadMethodCallException]
  Not Implemented

When I use the index to list what I have, it also fails on the plugin part:

[root@tools public_html]# bin/gpm index

GPM Releases Configuration: Testing

PLUGINS [ 226 ]

  [BadMethodCallException]
  Not Implemented

**Comment by rhukster** [comment]
I can replicate this, will get fixed ASAP.  Cheers.

**Comment by rhukster** [comment]
Fixed, will get a new Beta out soonish.  Thanks.

**Comment by M4rtine** [comment]
Thanks, i have the same issue for me too ^^

**Comment by rhukster** [comment]
Fixed in 1.4b2 (now the version doesn't show!), but fixed in 1.4 latest branch.
