### ISSUE TITLE
[remove-resource] Delete Course Hub Bones theme

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#1785]
With my plans for the Course Hub project in 2018 I think it is best to now retire the Course Hub Bones theme, and focus on Bootstrap (4?) or other responsive frameworks themes that might be released moving forward.

Please remove the Course Hub Bones theme at:
https://github.com/hibbitts-design/grav-theme-course-hub-bones

Thanks very much,
Paul

**Comment by rhukster** [comment]
will remove shortly..

**Comment by rhukster** [comment]
removed for next udpate

**Comment by paulhibbitts** [comment]
Thanks very much @rhukster
