### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by SimonMueller** [getgrav/grav#1789]
I would like to add my new theme to the Grav Repository.
Here are the project details: [SimonMueller/grav-theme-pluspunkt](https://github.com/SimonMueller/grav-theme-pluspunkt)

 A simple, responsive and modern Grav theme built with Kube.

**Comment by rhukster** [comment]
nice, will get this added soon.

**Comment by rhukster** [comment]
Added for next update
