### ISSUE TITLE
2 Factor Authentication - It's constantly change

### ISSUE THREAD

**Issue by gravataLonga** [getgrav/grav#1790]
Hello everbody, 

2 Factor Authentication - It's constantly change or i miss something. Sorry i'm not english native but will do my best to explain what i'm doing.

When i enable 2FA on admin panel and can see 2FA secret but if i refresh notice the secret has been change. 

I have 1Password for my personal password wallets, and i have scan qrcode. But the QrCode it's constantly change.  

I'm developer, may be can submit a bugfix, but i don't know how. 

Best Regards,
Jonathan Fontes
jonathan.pt

**Comment by rhukster** [comment]
Are you hitting refresh? because the code is actually stored in the user yaml and doesn't change unless you manually 'refresh' it.

**Comment by gravataLonga** [comment]
Hi, nop i don't hit the refresh button. May it's better do a video or a gif, wait a moment.

**Comment by gravataLonga** [comment]
@rhukster Here you got a video, where you can see i never press the refresh button, only refresh the browser, and the secret code constantly change. 

https://www.youtube.com/watch?v=q5NQvuZWbik&feature=youtu.be

**Comment by rhukster** [comment]
Your video is clipped, however, I have a feeling that it's related to permissions on your user account yaml files (`user/accounts/admin.yaml`) etc.  If you look at this file, you should see the 2FA key stored.  I think that Grav is unable to write to your file, and therefore cannot store the key, so it's generating one every time.  You probably can't update your password or change your email address either, as this action also requires Grav to be able to modify your files.

**Comment by gravataLonga** [comment]
@rhukster yep i know my video was clipped, sorry about that. I will try give proper permission and post back the result. 

Thanks for your time!

**Comment by gravataLonga** [comment]
@rhukster Hello again, but you suggestion not work. As you can see here, the file is writer well because the date is constantly change.  

https://www.dropbox.com/s/zk44dtdc8559fyu/Screen%20Shot%202017-12-27%20at%2010.37.52%20PM.png

https://www.dropbox.com/s/jfgj6tqret5p9cm/Screen%20Shot%202017-12-27%20at%2010.38.03%20PM.png?dl=0

**Comment by gravataLonga** [comment]
Ah, by the way, the yml content is change also :  

one time
`twofa_secret: HLWZ3NBAM232IA7KO4RFV5CSQX3REU3V
twofa_enabled: true`

`twofa_secret: 3ZJPVI77PH5POFGMV26HXACPXNVZU3QR
twofa_enabled: true`

**Comment by rhukster** [comment]
This is just on reloading the page??

**Comment by gravataLonga** [comment]
Yep, i'm only reloading the page, i will do another video with filezilla source code and browser.

**Comment by gravataLonga** [comment]
@rhukster Video ready: https://youtu.be/puvMQBomW5k may be i'm doing something wrong.

**Comment by m4rkinh0** [comment]
Hi,
Just to let you know that this bug should be solved.

Similar case than [#1338](https://github.com/getgrav/grav-plugin-admin/issues/1338), right ?

**Comment by rhukster** [comment]
Yup i am pretty sure this is now resolved.

**Comment by gravataLonga** [comment]
Nice work, not using anymore Grav. :)
