### ISSUE TITLE
Page cache missed

### ISSUE THREAD

**Issue by maximelebreton** [getgrav/grav#1792]
Hello everybody,
I have a problem.

On a website, based on `Grav v1.1.5 - Admin v1.2.2`, a planethoster mutualized server, and a **file** cache system,
if i'm a new visitor (or open the site in a private window), the response time is about 10 seconds...
And if i'm a reccurent visitor, it's about 1 second.

The debugger show this message: Page cache missed
![image](https://user-images.githubusercontent.com/1072425/34264006-b18132e0-e671-11e7-9089-2709b4a13449.png)

I dont understand what's going on...
Any ideas?

Thank you!

**Comment by rhukster** [comment]
Any time you change a page or a configuration file, the whole cache is rebuilt and you will see this 'page cache missed' message.  It should make no difference if you are a new visitor or not, the caching is related to the state of the files on the server, not the user.

Your site could be slow for several reasons:

1. slow hosting (use a modern hosting provider with SSD drives - see our learn docs for some good options)
2. Using PHP 5.5 or 5.6 and not using PHP 7 or 7.1.  PHP 7+ is a 100% faster than 5.
3. You have lots of pages.  I"m talking about 1000+.  This of course is compounded if you have other problems in this list
4. Your site is not optimized for performance.  By this i mean you have lots of logic in Twig files and things that are not cached.  Better to put as much things into the page logic that IS cached, and doesn't have to be reprocessed constantly.  Or you could have lots of complex twig interactions.  This is not usually an issue, but if it gets out of hand it can have a big impact.
5. You have something loading on the page that is slow. This is often large images, or lots of image manipulations, but could also be related to javascript, etc.

The best way to look at your problems and work out what's going on is to:

1. Use your browsers development tools, and look in the network tab to see what's slowing things down.  Is it the initial document, or something else.
2. If it's the document, then that means Grav, so then look in your timeline of the debugger to see which part of grav is slow.  If it's in the render, then it's likely its something like #5 above. 
3. If you can try another hosting provider, shared hosting is usually 10x slower than a cheap VPS solution often costing more than the VPS would of cost you.
