### ISSUE TITLE
Chinese Admin Panel Translation Unavailable?

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [getgrav/grav#1794]
I have seracherd everywhere but cannot find a routine to swipe the panel language to Simplified Chinese. Besides, plugins do not have proper translations too. Is there any Chinese language pack available?

**Comment by rhukster** [comment]
Languages are translated using crowdin as stated here: https://learn.getgrav.org/content/multi-language#translation-support

Grav Admin is here: https://crowdin.com/project/grav-admin

The admin already has the translations in it, simply click your user profile and change your language.  If you want to help with fixing/improving translations, please join crowdin and then the project i linked above.

**Comment by March-happy** [comment]
@rhukster 
However I believe that there is no Chinese translation file in system/languages, as I see nothing related to Chinese like **zh_CN**, **chi**, **zho**. Besides, having **only** admin panel translated is not enough. Plugins, skletons and so on need translations too. In that case grav can be fully featured like WordPress.

The following is what I saw at my server:

`$ ls`
`ar.yaml  da.yaml  en.yaml  fr.yaml  it.yaml  nb.yaml  pl.yaml  ru.yaml  th.yaml  vi.yaml
ca.yaml  de.yaml  es.yaml  hr.yaml  ja.yaml  nl.yaml  pt.yaml  sk.yaml  tr.yaml
cs.yaml  el.yaml  fi.yaml  hu.yaml  lt.yaml  no.yaml  ro.yaml  sv.yaml  uk.yaml
`

**Comment by tranduyhung** [comment]
There is no language files for Chinese because there is no translations for Chinese yet, if you look at https://crowdin.com/project/grav-admin, Chinese translation progress is 0%. You can start contributing by translating.

The themes, the plugins are maintained in separated repositories by Grav developers or by other contributors, you can submit your pull requests for Chinese translations to those repositories.

**Comment by yezongyang** [comment]
uh, Chinese Simplified progress is 100%, but not in project

**Comment by rhukster** [comment]
I need to merge the latest fixes from crowdin into develop/1.9 branches.
