### ISSUE TITLE
How to implement efficient custom page ordering.

### ISSUE THREAD

**Issue by shoorlyne** [getgrav/grav#1795]
We have a web dashboard which displays a list of pages, and the user is allowed to re-order the pages via drag-and-drop, and the dashboard will send the ordered list to the server to save.

I wonder, what's the most efficient way to keep track of the order on the server? I can think of 2 ways:
1 use the custom order option in page header, but it seems to me that even a single order change requires updating multiple pages, which is an operation of O(n) time complexity;
2 prepend a number to each page's directory, and have Grav's default order sort it out; but again, this requires renaming multiple page directories.

Thanks for any thoughts.

**Comment by rhukster** [comment]
The order is maintained by numerical prefix on the page folder.  When you re-order via the admin, these folder names are renamed with new numeric prefix.  This is mainly due to the flat-file nature of Grav, and the ability to 100% maintain a site via folders and file structure alone.
