### ISSUE TITLE
collection is always filtered by uri.param

### ISSUE THREAD

**Issue by hi-ko** [getgrav/grav#1798]
I set up a multisite grav having a common shared blog site sharing blogs by taxonomy.
This is working perfectyl as long I use the taxonomy api but I'm somehow stucked when using the page api in case there is no taxonomy filter required for the sidebar twik filtering blogs by taxonomy because the page api is always filtering the collection by uri.params:

following the example from Taxonomy List Plugin or the default theme I create the links with uri.param:
`        <a class="{{ active }}" href="{{ base_url }}/{{ taxonomyname }}{{ config.system.param_sep }}{{ tax }}">{{ tax }}</a>`

but if a page is accessed with uri.param taxonomy you can't get all subpages of /blog by 
`page.collection({ items: {'@page': '/blog'} }).ofType('post')`
since it is filtered by uri.param taxonomy which results in an incomplete list of pages, tags etc.

The page api should provide something like a 'force' flag to ignore filters from current page.
I think this an requirement for any sidebar. Isn't there a way to get this done without implementing custom php classes like done with Taxonomy List Plugin?

**Comment by hi-ko** [comment]
In case someone is also looking for an approach filtering a shared blog site by site specific taxonomy. I added a taxonomy 'site' in all sites and a site param 'name' which acts as a filter on the shared blog site added to all other sites as a symlink. This works perfect except for blog site itself where the taxonomy api can not be used if no filter should be applied. Using the page api is resulting to the filtered effect described in the post above.

    {% if config.site.name is defined %}
        {% set pagelist = taxonomy.findTaxonomy({'site': config.site.name}).ofType('post') %}
    {% else %}
        {% set pagelist = page.collection({ items: {'@page': '/blog'} }).ofType('post') %}
        {{ dump(page.collection({ items: {'@page': '/blog'} }).ofType('post')) }}
    {% endif %}

    {% set taxlist = {} %}

    {% for post in pagelist %} 
       {% if post.taxonomy[taxonomyname] is defined %}
          {% set taxlist = taxlist|merge(post.taxonomy[taxonomyname]) %}
        {% endif %}
    {% endfor %}

    {% if taxlist %}
    {% set taxlist = array_unique(taxlist) %}

    <span class="tags">
        {% for tax in taxlist %}
            {% set active = uri.param(taxonomyname) == tax? 'active' : '' %}
            <a class="{{ active }}" href="{{ base_url }}/{{ taxonomyname }}{{ config.system.param_sep }}{{ tax }}">{{ tax }}</a>
        {% endfor %}
    </span>
    {% endif %}

**Comment by rhukster** [comment]
You should be able to set:

```
url_taxonomy_filters: false
```

On the collection definition to disable processing of the URI::param-based taxonomy filters.

**Comment by hi-ko** [comment]
Thanks for pointing me to the url_taxonomy_filters parameter. Adding the parameter to the page.collection did the trick. I already changed my code snippet above.
Could you please add this hint to the page collection documentation?

btw: setting url_taxonomy_filters on a page doesn't seem to have an effect unless set explicitly in a template.

**Comment by th0rgall** [comment]
I'm very glad I found this issue! I was writing my own URL taxonomy parser that would present a custom, complex page collection when receiving `category:tech` in the URL.

Unaware of the internal pre-filtering done by `url_taxonomy_filters`, the unexpected behavior was driving me nuts. Now it all works perfectly.

I'll put it up as an issue in the documentation to see whether and where this could be mentioned.
