### ISSUE TITLE
Memory leak when using non-ascii character (?) to create group

### ISSUE THREAD

**Issue by Marcool04** [getgrav/grav#1799]
Hi there, and first off, thanks for the great work on grav with which I'm very impressed.
First a bit of context:
````
[root@alarmpi ~]$ uname -a
Linux alarmpi 4.9.65-1-ARCH #1 SMP Fri Nov 24 17:54:03 UTC 2017 armv7l GNU/Linux
[root@alarmpi ~]$ pacman -Qi apache | grep Version
Version         : 2.4.29-1
[root@alarmpi ~]$ php --version
PHP 7.1.12 (cli) (built: Nov 22 2017 17:42:00) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12, Copyright (c) 1999-2017, by Zend Technologies
````
I was trying to create a new group in a fresh Grav installation today, using the name "Utilisateur enregistré". First the page just went blank, and I noticed the following error in my server log:

````
Got error 'PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) in /usr/share/webapps/grav/vendor/rockettheme/toolbox/File/src/File.php on line 254\nPHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes) in /usr/share/webapps/grav/vendor/filp/whoops/src/Whoops/Util/Misc.php on line 50\n', referer: https://abbasp.archmacbook.tk/grav/admin/group-manager/Utilisateurs%20enregistr%C3%A9s
````
I then increased the memory limit to 512M (from default 128M) just to see if that was the issue, but monitoring the memory usage showed a perfect ramp all the way up to full usage (this is not a high-ram context, 1Gb), see [screenshot](https://framapic.org/gallery#iOYhJvJAnXei/x2aC1K92vi9p.png). In the end the php timeout was reached:
````
Got error 'PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /usr/share/webapps/grav/vendor/rockettheme/toolbox/File/src/File.php on line 254\n', referer: https://abbasp.archmacbook.tk/grav/admin/group-manager
````
Having changed the group name to "Users" it worked perfectly, so my intuition is this could be an issue with the character encoding.
Let me know if more info is needed, I'm happy to help track this down.

**Comment by rhukster** [comment]
This is fixed in the Grav 1.4 branch, but you can manually apply the fix linked above directly to your install if you wish.

**Comment by Marcool04** [comment]
Hum... having applied that fix I tried to create the same group again, and I believe my server has actually run out of memory and crashed :)
The page hung without any kind of feedback and now I can't get any response from the machine (no ping nothing). Will have to wait and see if something kicks in to knock the php process out at some point, or if I can get an ssh 'killalll php-fpm' in from here… but I'll probably have to wait until I'm back at it physically before I can give you any information regarding what exactly happened. Perhaps we should not consider the fix to be perfectly pristine for the moment? :/

**Comment by Marcool04** [comment]
No, indeed, after a few hours the kernel OOM must have killed php-fpm for me, and I got access again. The situation now seems to be identical to what it was before I applied the fix I'm afraid :/

**Comment by rhukster** [comment]
Well, I definitely found a problem related to UTF8 chars in the root path.  This would cause a recursive redirect loop, that I guess on certain systems would suck up memory. Usually, PHP has limits that abort this kind of behavior though.  My fix in 1.4 branch fixed this.  However, I discovered another issue with sessions and not being able to log into admin. The problem was similar (encoded vs non-encoded paths), and after fixing this again in 1.4 branch I can now login and use the admin properly.

**Comment by rhukster** [comment]
If you continue to have problems, I suggest not using a UTF8 based folder name, and simply use standard chars.  There should definitely not be an issue there.

**Comment by Marcool04** [comment]
Hum… Right. Not sure what's going on exactly, I don't have php set on a very verbose log level, could try and ramp it up and get you a better error message maybe. But it's definitely running out of memory. I can vary the memory_limit parameter in php.ini and watch it gently increase its memory usage until it hits the limit, then the page goes blank and nothing more is done (so the thread get's killed I guess).
Seems a bit of a shame to not have UTF-8 support (although group names aren't exactly a key feature I guess), but it definitely works fine when standard chars are used, that I can confirm. Thanks for keeping at it anyhow! I'll post back here if I have some more time to poke at php and see where it's failing exactly.
Regards, Mark.

**Comment by rhukster** [comment]
having fixed my issues with UTF8 chars in root folders, i'm not having any issues per say with UTF8 group names.  I created the group manually in `user/config/groups.yaml`:

```
enregistré:
  access:
    site:
      login: true
```


Then set my group in my profile:

![user admin grav 2017-12-28 15-36-24](https://user-images.githubusercontent.com/1084697/34424952-e53173a2-ebe4-11e7-99a8-ac78245dd9fd.png)

Saved, then logged out then back in.. no issues.. just works.

**Comment by Marcool04** [comment]
Aah, now I understand. This is not an issue with grav core, but with the admin plugin "Admin Addon User Manager", which was included in the skeleton I included (I think?) and therefor didn't tick me off to the fact it wasn't core. Your discussion of adding the group in user/config/groups.yaml made me realize the admin panel way of doing so was not the generic one, and your screenshot of the panel doesn't include the "Users" and "Groups" menu items mine does.
So sorry for insisting. I'll post to the issue tracker on https://github.com/david-szabo97/grav-plugin-admin-addon-user-manager/.
All the best.
Mark.

**Comment by rhukster** [comment]
Ok, good to know.  BTW, this is a 3rd party plugin and not included in any 'official' skeleton package.
