### ISSUE TITLE
Grav URL System Enhancement

### ISSUE THREAD

**Issue by Vivalldi** [getgrav/grav#180]
Servers are slowed down if they do not have a trailing slash in urls as it is read as a redirect by browsers (except for files).

Example
URL without trailing slash: blog.com/blogitem
URL with trailing slash: blog.com/blogitem/

There is no need for the grav engine to support this but rather it should be a practice that should be used when making templates. (If needed I can put this in the learn section somewhere).

**Comment by mahagr** [comment]
There is no benefit of trailing flash as we have rewrite rule which checks both file and directory before calling index.php. So it will make both checks regardless of what we do, though some servers may be able to optimize the second check not to have filesystem lookup.

Anyway, even if both file and directory gets checked, we are doing hundreds of similar checks inside PHP. So basically your optimization is something that makes no difference at all.
