### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by alka-dev** [getgrav/grav#1800]
I would like to add my new pluginto the Grav Repository.
Here are the project details:[ **Admin Addon Media Sort Plugin**](https://github.com/alka-dev/grav-plugin-admin-addon-media-sort)

**Comment by rhukster** [comment]
What does this plugin do over the current page media ordering?

**Comment by alka-dev** [comment]
Nothing, the rest is done by admin plugin, the admin plugin add the media sort to the head of frontmatter file. This allows to sort media for frontend easily.

**Comment by rhukster** [comment]
Sill seems like the current drag-n-drop reordering accomplishes this already, but ive added it
