### ISSUE TITLE
Image linking markdown broken

### ISSUE THREAD

**Issue by enderlen** [getgrav/grav#1804]
"`[![](cff420ba-a871-4603-852d-f6b15f41d34f.jpg)](http://www.dynatmos.com) `"
markdown was working fine with 1.3.8
but in 1.3.10 i get broken display with shown result being image decorated by code and no link on image:
```
[
image
</figure>](http://www.dynatmos.com)
```

**Comment by rhukster** [comment]
I can't replicate this.. maybe its related to a plugin you installed?  The fact that there is a `<figure>` tag makes me think this is the case because by default this would simply output an image wrapped in a link.

**Comment by enderlen** [comment]
I have desactivate one by one plugins related to pictures. So I isolate the plugin involved in this issue. It appears to be the imgcaptions plugin (https://github.com/olevik/grav-plugin-imgcaptions/blob/master/README.md) that is now incompatible with newest version of grav...

Is there any way to revert to previous grav version (1.3.8) from admin panel?

**Comment by rhukster** [comment]
Well you could first try this plugin rather than that one: https://github.com/trilbymedia/grav-plugin-image-captions

It utilizes a more flexible dom manipulation library rather than regex, so it should be more reliable.

**Comment by enderlen** [comment]
thks for the advice, I will try the other plugin ;)

**Comment by OleVik** [comment]
As per [issue on plugin-repo](https://github.com/OleVik/grav-plugin-imgcaptions/issues/14#issuecomment-354366403), this is due to a change in API. Will be resolved once I update regex-patterns to accommodate, but temporarily resolved by using HTML-mode which implements the v1-API.
