### ISSUE TITLE
2Factor Auth - no available QR code

### ISSUE THREAD

**Issue by variablenix** [getgrav/grav#1806]
Grav `v1.3.10` - Admin `v1.6.7`

Using the reported versions of Grav and the Admin plugin displays no QR code when 2FA is enabled. I can reproduce the same thing across different Grav instances with the same versions. What I have done to try and circumvent the issue:

1. Emptied primary web browser's cache and restarted browser to no avail
2. Tested different web browsers to no avail
3. Emptied Grav's cache from within the admin UI to no avail
4. Uninstalled the Admin plugin and reinstalled to no avail.

![grav - no 2fa](https://user-images.githubusercontent.com/472631/34396871-84be50ae-eb25-11e7-9539-74a34de511e4.png)

I also verified `admin.yaml` has 2FA enabled:

```
enabled: true
route: /somepath
cache_enabled: false
theme: grav
content_padding: true
twofa_enabled: true
```
At this point I'm not entirely sure why this is happening or how to rectify it.

**Comment by rhukster** [comment]
2FA QR code is only viewable in the user profile. So click the avatar in the top left corner.

**Comment by variablenix** [comment]
Doh. Sorry for the noise. Thanks a lot @rhukster!
