### ISSUE TITLE
Reusing content in multiple pages (not requiring Twig)

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#181]
One of the strongest aspects of Grav is modular content, and to further support that aspect to a wider audience a non-Twig method to reuse content chunks across multiple pages would be very valuable.

For example, let's say there is a standard modular page displaying modular content chunks. On any other page within the site it would then be possible to re-use (insert or link?) the same content. The desired result is that an edit to the source of the modular content is then presented in multiple areas of the site.

**Comment by Sommerregen** [comment]
Hi @paulhibbitts,

sorry for aksing stupid questions, but I try to get your idea to think about an implementation in Grav (after releasing my pending plugins). Can you present a minimial working example here, what you are doing so far using TWIG? Are you only want to link (and embed) modular pages from an arbitrary page or do you have something different in mind?

**Comment by paulhibbitts** [comment]
Hi @Sommerregen ,

Thanks for your interest in this issue (no stupid questions to help clarify things, sorry I was not clearer to begin with :-)).

Here is an actual example: I am creating a Grav Skeleton for myself and hopefully other instructors to use for their course websites. Very often I need to duplicate resources which are on a global resources page to a specific class or other type of page. 

Here is a such a page of global resources:
http://hibbittsdesign.com/courses/canvas-prototype/ux-techniques-guide

Under the section "Benefit from and apply a user-centered design process?" I've got various modular chunks inserted. Now, for the first week of class I want to re-use the modular chunks about "usability" and "user-centered design" on this page:
http://hibbittsdesign.com/courses/canvas-prototype/home/01-week

To do this, I've enabled Twig on the page markdown file, and used this command:
{% include 'topic.html.twig' with {'page': page.find('/ux-techniques-guide/_user-centered-design')} %}

While I can automate most things instructors need to do with the template, I don't want instructors to have to use Twig commands in their markdown files to re-use content - I am hoping that something easier could be provided either via the upcoming Admin Panel, plug-in, etc.

I think a lot of other people using Grav and modular content could benefit from an easy-to-use method of re-using modular content on any page within their site without needing to use Twig, thus I started a conversation on Gitter about this yesterday (search the transcript for "I think reusable modular content").

Please let me know the above helps clarify what I was suggesting, and any other thoughts you may have.

Thanks!
Paul

**Comment by mahagr** [comment]
Sounds like something we are doing in Gantry5, but taking a bit different approach. I have an idea how to easily do it in Gantry5 at least. :)

Actually what you can do in Grav, is to put the page into frontmatter:

    sidebar: 
      template: topic.html.twig
      page: /ux-techniques-guide/_user-centered-design

and then do this inside the template:

    {% include page.header.sidebar.template with {'page': page.find(page.header.sidebar.page)} %}

**Comment by Sommerregen** [comment]
@mahagr Sounds good and fairly simple. I'm also thinking about, whether one can support such a feature using Markdown syntax only. Then one is more flexible in the content, where the modular page should be inserted. Unfortunately,

```
[](/ux-techniques-guide/_user-centered-design)
```

is already being used by Grav, but maybe one can switch to 

```
{{ modular:/ux-techniques-guide/_user-centered-design }}
```

**Comment by paulhibbitts** [comment]
Thanks for sharing how to do this with YAML and Twig @mahagr , that is useful to know.

@Sommerregen , yes this is more along the lines I am hoping to see in Grav - something that is simpler for others to use than Twig which can be included in a markdown file. That is, aimed at content authors vs. site developers.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-page-inject

This plugin should handle this request :)

**Comment by paulhibbitts** [comment]
Awesome to see this, thanks to everyone involved!
