### ISSUE TITLE
[add-resource] New Plugin: HAX

### ISSUE THREAD

**Issue by btopro** [getgrav/grav#1811]
I would like to add my new plugin to the Grav Repository.
Here are the project details: https://github.com/elmsln/grav-plugin-hax

This plugin builds on the webcomponents module to provide support for using the http://haxtheweb.org style authoring system in Grav as a replacement for it's edit form. Users will need to install webcomponents and hax and bower install (which snags https://github.com/LRNWebComponents/gravcms-hax) in order to use the project.

**Comment by rhukster** [comment]
NOt sure how this got lost, but i've added it again.
