### ISSUE TITLE
Grav/install removes pacakges

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav#1814]
## Setup:
Centos 6.x, PHP 7.1.x

## To reproduce
1. Install grav via `composer create-project getgrav/grav .` in the docroot, and composer installs its packages.
2. `bin/grav install` is run automatically to complete the installation of antimatter, problems, etc, but it also is marking the following packages for removal:
```
Package operations: 0 installs, 0 updates, 35 removals
  - Removing victorjonsson/markdowndocs (dev-master)
  - Removing fzaninotto/faker (v1.7.1)
  - Removing codeception/codeception (2.3.5)
  - Removing behat/gherkin (v4.4.5)
  - Removing facebook/webdriver (1.4.1)
  - Removing symfony/process (v3.3.9)
  - Removing guzzlehttp/guzzle (6.3.0)
  - Removing guzzlehttp/promises (v1.3.1)
  - Removing guzzlehttp/psr7 (1.4.2)
  - Removing psr/http-message (1.0.1)
  - Removing phpunit/phpunit (4.8.36)
  - Removing phpspec/prophecy (v1.7.2)
  - Removing phpdocumentor/reflection-docblock (3.2.2)
  - Removing phpdocumentor/type-resolver (0.3.0)
  - Removing phpdocumentor/reflection-common (1.0.1)
  - Removing webmozart/assert (1.2.0)
  - Removing phpunit/php-code-coverage (2.2.4)
  - Removing phpunit/php-token-stream (1.4.11)
  - Removing phpunit/php-file-iterator (1.4.2)
  - Removing phpunit/php-timer (1.0.9)
  - Removing sebastian/environment (1.3.8)
  - Removing sebastian/global-state (1.1.1)
  - Removing sebastian/version (1.0.6)
  - Removing phpunit/phpunit-mock-objects (2.3.8)
  - Removing doctrine/instantiator (1.0.5)
  - Removing phpunit/php-text-template (1.2.1)
  - Removing sebastian/comparator (1.2.4)
  - Removing sebastian/exporter (1.2.2)
  - Removing sebastian/recursion-context (1.0.5)
  - Removing sebastian/diff (1.4.3)
  - Removing stecman/symfony-console-completion (0.7.0)
  - Removing symfony/browser-kit (v3.3.9)
  - Removing symfony/css-selector (v3.3.9)
  - Removing symfony/dom-crawler (v3.3.9)
  - Removing symfony/finder (v3.3.9)
3. Run `composer test` 
```

## Expected behavior:
Tests run.

## Actual behavior
Tests fail due to missing packages, namely the ones marked earlier for removal relating to phpunit.  I'm required to run `composer install` to re-install the missing dependencies for testing.

## Notes
Unless I'm misunderstanding something about the installation process, it doesn't seem to make sense to download and install packages only to turn around and remove them.

**Comment by rhukster** [comment]
when you run `bin/grav create-project` it in turn runs `bin/grav install` which actually runs `composer install --no-dev` so it installs everything required but without the development packages, including those for testing.

You obviously had a setup with all the packages, so those development one were removed.  You need to do this to to run tests:

```
composer install
composer test
```
