### ISSUE TITLE
Remove copy to clipboard..

### ISSUE THREAD

**Issue by matroidde** [getgrav/grav#1817]
Hello.

If I use Markdown, i get only this:
![1](https://user-images.githubusercontent.com/31346301/34544503-efefb68a-f0e6-11e7-8f01-2e382bed07db.PNG)

but I wan't to have this sometimes:
![2](https://user-images.githubusercontent.com/31346301/34544516-00ca96a0-f0e7-11e7-851b-62545ddda29f.PNG)

What I have to type in there to get this without the copy to clipboard?
Thanks.

**Comment by rhukster** [comment]
This is just a feature of the 'learn2' theme.  A bit of javascript and CSS.

Simply remove this line: https://github.com/getgrav/grav-theme-learn2/blob/develop/templates/partials/base.html.twig#L35

**Comment by matroidde** [comment]
But for example on https://learn.getgrav.org pages, there are (as you can see in the 2 pictures) there are both of the opinions. One with and one without...

**Comment by quasipickle** [comment]
The button is only added to blocks longer than 5 characters: https://github.com/getgrav/grav-theme-learn2/blob/develop/js/learn.js#L177

**Comment by xemjeff** [comment]
A bit late, but if you do edit `learn.js` Line 177 file, remember to hard-reload the page in your browser to reload learn.js as well. Otherwise you'll keep using the old `learn.js` and not see the changes.  I set my lower limit to 15 chars.

**Comment by s22-tech** [comment]
> I set my lower limit to 15 chars.

That's an excellent idea!  Which made me think that it would be nice to only have the clipboard icon show when using code blocks surrounded by 3 backticks.  That way, inline code wouldn't have one no matter how long it was.

Unfortuantely, JavaScript is not my strong suit.  Anyone have any ideas?
