### ISSUE TITLE
Grav Haml Plugin

### ISSUE THREAD

**Issue by numito** [getgrav/grav#1819]
New plugin released to write template files in HAML with Twig integration.
https://github.com/numito/grav-haml
Credits to MTHAML from Arnaud Le Blanc

**Comment by rhukster** [comment]
Does this plugin require these codechanges to work: https://github.com/getgrav/grav/issues/1818 ?

**Comment by numito** [comment]
No need to do code changes.

**Comment by rhukster** [comment]
This has been added.. sorry for the delay!
