### ISSUE TITLE
CSS and JS Pipeline Error

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav#182]
If I have `css_pipeline: true` I get this error:

![error](https://cloud.githubusercontent.com/assets/2962426/7335263/2b7ce89a-eb80-11e4-9a6e-94fd30645457.jpeg)

If I change that to `css_pipeline: false` the error is cleared.

The same happens with js_pipeline.

Grav 0.9.26

**Comment by rhukster** [comment]
Try running a `composer update` to ensure you have the latest vendor libraries.

**Comment by bobrocke** [comment]
You were right, of course. This fixed it right up:
```
$ rm -Rf vendor
$ bin/composer.phar update --no-dev
```
