### ISSUE TITLE
markdown inside of html

### ISSUE THREAD

**Issue by aligator** [getgrav/grav#1820]
I need a centered link:
<center> [link](url) </center>
But the markdown inside of the center is not processed.

It would be great to have something like this:
https://stackoverflow.com/questions/1058933/can-i-define-a-class-name-on-paragraph-using-markdown
<center markdown='1'> [link](url) </center>

Is this possible or is there another way (besides using a native html-link) for this?

**Comment by paulhibbitts** [comment]
Hi @aligator you can apply a class to a Markdown link, like this:

```
[Required Reading Quiz](https://canvas.sfu.ca/courses/35900/quizzes/62496?classes=btn,btn-primary)
```
Does that give you what you are looking for?

**Comment by rhukster** [comment]
btw @aligator, paul's example is adding a class which you can then use to center.  Depending on your theme, you might already have one, or you can add one easily enough.

```markdown
[your link text](/your/url?classes=center)
```

where `center` is the class that could have:

```css
.center {
  text-align: center;
}
```

**Comment by aligator** [comment]
Thank you.

But i found another way:
Enabling Markdown extra in the configuration. 

This enables it just like it is described in the link.
