### ISSUE TITLE
[add-resource] New theme: editorial

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav#1821]
https://github.com/jgonyea/grav-theme-editorial
Editorial is a GravCMS port of the Editorial theme from HTML5Up.net.

**Comment by rhukster** [comment]
I think you need to update the thumbnail and screenshot images or they will display with the dummy ones in the GPM.

**Comment by jgonyea** [comment]
Oops, first theme. I'll get on those

**Comment by jgonyea** [comment]
The theme (finally) has its own thumbnail and screenshot images.  Please let me know if there's anything else I've missed.

**Comment by rhukster** [comment]
Added for next GPM update.  Thanks.
