### ISSUE TITLE
Executing PHP script inside Grav

### ISSUE THREAD

**Issue by yckelvin** [getgrav/grav#1822]
Dear Sir/Madam,

As Grav is written by PHP script, is it possible to execute PHP script inside the Grav page? 

I try `<?php .....?>` but not work.

Best regards,

Kelvin.

**Comment by rhukster** [comment]
No you cannot. This is primarily for security reasons.  If you need PHP logic you should create a plugin: https://learn.getgrav.org/plugins/plugin-tutorial

it's really quite simple with the `devtools` plugin to create the plugin skeleton code.
