### ISSUE TITLE
Subheadings below a heading with no paragraph content are aligned incorrectly.

### ISSUE THREAD

**Issue by Flamenco** [getgrav/grav#1826]
Using the 'Open Publishing Space' starter
```
# Foo
## Bar 1
abc
## Bar 2
abc
```
When it do this, the Bar 1 heading is centered instead of left aligned.

Workaround
```
# Foo
<nbsp />
## Bar 1
abc
## Bar 2
abc
```

<img width="378" alt="before" src="https://user-images.githubusercontent.com/819940/34797592-ebc30892-f626-11e7-85c2-fea0335160cd.png">

<img width="373" alt="after" src="https://user-images.githubusercontent.com/819940/34797671-26a5d3d6-f627-11e7-8ecf-c1e738a83bcc.png">

**Comment by paulhibbitts** [comment]
Thanks for the issue, but please create a copy of it on the repo for the "Open Publishing Space" theme and I will take a look (I am the author of the inherited theme): https://github.com/hibbitts-design/grav-theme-antimatter-open-publishing

**Comment by Flamenco** [comment]
The issue is that the h2 is centered if it has no paragraph below it, but is left justified if there is content.  That does not seem correct.

**Comment by Flamenco** [comment]
And it's not just alignment...  I looks like a parsing issue to me.  In the first screen shot, "bar 1" and "bar 2" are both h2 and should be the same style.

**Comment by Flamenco** [comment]
So the problem is **the second h2.**

I changed the CSS in typography.css from:
```
h1 + h2 {}
```
to
```
h1 ~ h2 {}
```
That solved it for me, but I don't know what that might break...

**Comment by paulhibbitts** [comment]
Thanks @Flamenco , I will try this in my Open Publishing Space theme too.

**Comment by paulhibbitts** [comment]
@Flamenco To confirm, what theme are you using? I do not see a typography.css file in Antimatter (or my Open Publishing Space theme).

**Comment by Flamenco** [comment]
This happens on the plain ol' antimatter theme.

**Comment by Flamenco** [comment]
<img width="720" alt="screen shot 2018-01-19 at 3 00 12 pm" src="https://user-images.githubusercontent.com/819940/35169164-7ba0bf5a-fd29-11e7-82ac-a530ef9524ce.png">

**Comment by Flamenco** [comment]
antimatter/template.css

**Comment by Flamenco** [comment]
I changed all the adjacent sibling selectors (+) to general siblings (~)

**Comment by paulhibbitts** [comment]
Thanks @Flamenco , perhaps it might be best to open this as an issue on the Antimatter repo (https://github.com/getgrav/grav-theme-antimatter)?

In the meantime I will also see if I can address it in my inherited theme (my CSS skills are quite limited, thanks for sharing how you are trying to address the issue).

**Comment by Flamenco** [comment]
https://github.com/getgrav/grav-theme-antimatter/issues/127
