### ISSUE TITLE
Adding a redirect creates a redirect loop

### ISSUE THREAD

**Issue by sstruemph** [getgrav/grav#1832]
I've been playing with redirects (globally in site.yaml, not at the page level) and I've run into a scenario that creates a redirect loop.

To reproduce:
1. Changed an existing page's slug and disable routing in the page's settings. 
2. Then put in a redirect (in site.yaml) to the new slug. 
3. Visit the original slug and a loop occurs where the last word in the new slug, after the last dash `-` is repeated infinite until the browser stops with a redirect loop error.

Example:
Old slug `test-page`
New slug `test-page-new`

Result: loading `example.com/test-page` is redirected to:
`example.com/test-page-new-new-new-new-new-new-new-new-new-new-new-new-new-new-new-new`

Am I doing something wrong?

**Comment by rhukster** [comment]
This is a combination of things:

1. Even if you change a slug in a page you can always reach a page via it's **RawRoute** which is the route based on the file's path. This would results in a page being accessible via the original route as well as via the slug you defined.

2. Setting `routable: false` means that this particular page is not going to be routable at all, neither by rawroute or the slug-based route.

The best way to accomplish what you are trying to do is to:

* Rename the original page's folder from `test-page` to `test-page-new`, and then add your site-based redirect: 
```
'/test-page': '/test-page-new'
```

as you already have....

**Comment by sstruemph** [comment]
@rhukster Will try this. Thank you for taking the time to answer my questions :)
