### ISSUE TITLE
Folder::move throws RuntimeException when crossing drive boundary

### ISSUE THREAD

**Issue by Silic0nS0ldier** [getgrav/grav#1833]
I stumbled onto this when getting UserFrosting's learn site running in docker. For the sake of issue replication, the commands are:

```bash
git clone https://github.com/userfrosting/learn.git userfrosting-learn
cd userfrosting-learn
docker pull ahumaro/grav-php-nginx
docker run -d -i -p 80:80 -p 2222:22 -v "$(pwd):/usr/share/nginx/html/user/" --name ufLearn ahumaro/grav-php-nginx
docker exec -it ufLearn bash
chmod +x bin/gpm # This is only needed if permissions are acting up
bin/gpm install -y error problems breadcrumbs anchors highlight simplesearch learn2
```

With how this sets things up, the `user` folder is mapped to `userfrosting-learn`. Works well for quickly testing out the docs as I work on them. Except that the mapping interferes with plugin installation. Specifically, the code responsible for moving plugin data into `user/plugins` is using `rename` which while fast, doesn't work when crossing a drive boundary (emulated or otherwise).

To get around the issue at the time I replaced `rename` with calls to `self::copy` and `self::delete` (going off memory there). It would be awesome if those 2 commands could be used as a fallback. I'm happy take a crack at getting it done, if someone can tell me how I should handle it when both fail (since its 2 exceptions to report then).

**Comment by rhukster** [comment]
Perhaps you could provide a pull request with your fixes so I could take a closer look?  Thanks!

**Comment by Silic0nS0ldier** [comment]
Huh. So my proposed fix is already implemented. What version of Grav had that Docker container pulled then... Ah. I see whats happened. I thought the image I was using automatically pulled the latest version (like another image I had tried), but clearly I was wrong.

I'll close this since its a non-issue.
