### ISSUE TITLE
2-Factor Authentication wont let me to log in

### ISSUE THREAD

**Issue by WhiteWolfSix** [getgrav/grav#1838]
Hi guys,

I am trying to log in into my site using 2-Factor Authentication which wont let me in for about last two days. I could not figure out what could be a problem. I tried to re-sync Google authenticator with no results. Any idea?

**Comment by rhukster** [comment]
Sounds like the authenticator value changed.  You can edit your `users/accounts/admin.yaml` directly and disable the 2FA option, then login normally, regenerate and re-setup your authenticator app.

**Comment by WhiteWolfSix** [comment]
Thanks for hint.

**Comment by WhiteWolfSix** [comment]
Well, this didn't solve my problem. I deleted both twofa_secret and twofa_enabled, uploaded yaml on server and re-setup my google authenticator app with no results. I also changed authenticator app to VIP Access (Symantec app) with the same problem so this isn't an issue of authenticator app.
