### ISSUE TITLE
summary size override in header?

### ISSUE THREAD

**Issue by egnirot** [getgrav/grav#184]
The summary size option is set in the top most site config at `system/config/site.yaml`, but I'm trying to override this setting for a single page, and I´ve defined it in the page header as follows:
```yaml
---
summary:
  size: 70
---
```
But it has no effect. The twig template uses the `page.summary()` function. When I override the size option by adding it to the user specific site config `user/config/site.yaml`, it works just fine, but then it's a global setting. Have I misunderstood the usage of the page headers? Btw, I'm using the latest Grav 0.9.26.

**Comment by rhukster** [comment]
OK, the page level merging of the summary options was missing, so it was not taking those into account.  I've fixed this and it will be available in the next release.  Sorry for the confusion!
