### ISSUE TITLE
Modular Ordering Bug

### ISSUE THREAD

**Issue by logknees** [getgrav/grav#1841]
title: Products
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _dredges-heading
            - _dredges-cards
            - _pumps-heading
            - _pump-cards
            - _floating-heading
            - _floating-cards
            - _other-products-heading
            - _other-products-cards

I've tried everything. Sometimes ordering them differently one level down in, say, dredges heading's options does something, but something completely unpredictable. The ordering in the configuration tab doesn't do anything, I'm not sure if there's some twig hierarchy that I'm not seeing. I've tried adding some rules in the base.html.twig and the modular.html.twig. Unsure what is going wrong here. It's a custom theme made by a developer that we can't find a way to contact. Is there any like default modular.html.twig or base.html.twig I can pull from or something? 

I'm also unable to switch the order by to manual, if that matters. I think that's just for collections but I'm not sure, I've only started encountering grav today.

**Comment by logknees** [comment]
sorry figured it out heheehehehe

**Comment by logknees** [comment]
@jimblue this issue was a while ago but I think what happened was I disabled the "custom ordering" and then renamed the files - _1dredges-heading, - _2dredges-cards or something close to that. It was for a client so I don't actually have the exact names of the files anymore, but I'm guessing it was some conflictions with the "custom ordering" and other rules grav has when it comes to ordering.

**Comment by jimblue** [comment]
Hey @logknees ! Thank you for your fast answer. Indeed it's because of the underscore. I think your solution is the good one but it should be integrated in `Grav core` directly so we don't have to rename each folder manually. I've open a new issue that detail the problem here: #1887
