### ISSUE TITLE
Page.find() and redirect rules cause broken  redirect

### ISSUE THREAD

**Issue by FrivalszkyP** [getgrav/grav#1843]
For starters, I'm aware of issue #1832 but I think mine is different.

## Issue:

page.find() will cause an erroneous redirect when pointing to a Custom redirect rule.

## Steps to reproduce: 

- Set the "Hide home route in URLs" to Yes in the Configuration / System admin page.
- Create a new page at `/home/recommended-page` with the default pagetype.
- Create a page type blueprint called `example.yaml`.
- Declare a custom field in the blueprint with the type `pages` and name it `recommended`.
- Create a new page at `/home/example` with this newly created `example` pagetype. 
- Set the custom field to a different page, to `/home/recommended-route`.
- Just so it's clear, now there should be a line in `/home/example/example.md` that points to `/home/recommended-page`
- In your theme folder, create an `example.twig` and in it, access the `header.recommended` value and print a link tag that points to the page that the URL stored in the `header.recommended` points to. So something like this: 

```
{% set recommendedPage = page.find(header.recommended) %}
<a href="{{ recommendedPage.url }}">{{ recommendedPage.title }}</a>
```

- Open the /example URL in the browser to verify that the link appears and works.
- Now go to the admin page of `/home/recommended-page` and change value of the `Folder` field, thus changing the URL of the page, to something else, e.g. `redirected-page`
- Now go to Configuration and choose the Site tab and add a Custom redirect with the old url pointing to the new one, so in this case: `/recommended-page` to `/redirected-page`. 
- Now open the /example URL once again in your browser and see that it is stuck in a bad redirect. The /home/recommended-page URL that is stored in its frontmatter is obsolete. The page.find() method should either return with false/null OR respect the Custom redirect rule and follow it to find /home/redirected-page, but instead, what I believe happens is it sends a `Location:` header to the browser.

## Expected outcome

The page.find() method should either return with false/null OR respect the Custom redirect rule and follow it to find /home/redirected-page, but instead, what I believe happens is that it finds the Custom redirect rule and sends a `Location:` header to the browser. Even though the requested page is NOT the /recommended-page` it's just something we're trying to access from the Twig template.

I tested page.find('/home/recommended-page', true) and it prevents the broken redirect issue, BUT does not find the /home/redirected-page, so it's only a partial solution.

**Comment by FrivalszkyP** [comment]
Okay I found the issue here: 

https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Pages.php#L487

This line does not respect the `$redirect` variable. While line 459 does take it into consideration, the line here does not, even though it more than makes sense since both cases deal with HTTP 30x redirects. 

I'm not able to create a pull request with a solution because I'm not sure how to handle the `$extension` variable. In my case, the `$found` variable contains a `.html` extension that was never part of the URL, and thus the `dispatch` method does not find the `redirected-page`. Changing this line to this snippet: 

```
                                    if ($redirect) {
                                        $this->grav->redirectLangSafe($found);
                                    } else {
                                        $page = $this->dispatch(str_replace('.' . $extension, '', $found), $all);
                                    }
```

But we all know that that's not a great solution. I'm just posting this as a jumping off point for you guys. Hope you can come up with a nice solution!

**Comment by rhukster** [comment]
The page extension does default to `.html` if none is provided in the URL.

**Comment by FrivalszkyP** [comment]
Yeah, I'm aware, but I just don't know a good, clean way to handle that. Please let me know if you're working on this issue or should I come up with a workaround in the meantime, because I have a couple hundred pages that I need to redirect in a live production environment.

**Comment by mahagr** [comment]
This one has been fixed; `find()` no more redirects, but `dispatch()` does. Find returns the page, so you need to deal with the potential redirect (or custom link) yourself.
