### ISSUE TITLE
Ability to choose a different default /logs directory location.

### ISSUE THREAD

**Issue by poomv2** [getgrav/grav#1851]
Due to some hosting companies, ie. 1&1. They don't allow use of the ./logs directory, so changing CHMOD permissions is a no go. - Having the ability to change the directory location would be great. This issue is stopping me from launching a clients site at the moment. Would be great to get this one resolved soon. Many thanks. Steve

**Comment by rhukster** [comment]
I think we sorted this on Slack chat? was just a message from problem plugin, but was actually working fine?

**Comment by poomv2** [comment]
Hey, yes, that's correct. It was just the Problems plugin that stopped the site loading.
