### ISSUE TITLE
Plugin site should check CHANGELOG dates

### ISSUE THREAD

**Issue by Flamenco** [getgrav/grav#1860]
Future changelog dates should not be allowed.

<img width="681" alt="screen shot 2018-02-06 at 7 33 00 am" src="https://user-images.githubusercontent.com/819940/35860491-3cfb7bea-0b12-11e8-9374-df7c1d8962e0.png">

**Comment by rhukster** [comment]
This is not something we control, this is what you put in your changelog file.  We just display that changelog with some CSS styling.

**Comment by paulmassen** [comment]
I think we have date in the future because some of us have tve habit to use the european date format dd/mm/yyyy

**Comment by Flamenco** [comment]
The relative date is generated, so there is some processing going on.

At the very least, if the date is not parseable or invalid (future or way in the past), it should not be displayed, displayed verbatim, and/or marked as erroneous.
