### ISSUE TITLE
[BUG] modular asset not rendered on reload if cache enabled

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav#1861]
I have a `modular.html.twig` page that contains `portfolio_modular.html.twig`

In `portfolio_modular.html.twig` I add an inline JS like so:

```
{# PORTFOLIO CONFIG #}

{% set portfolio_config %}
  var portfolioConfig = {{ page.header.shuffle ? 'true' : 'false' }};
{% endset %}

{% do assets.addInlineJs((portfolio_config), {'group':'bottom'}) %}
```

This inline asset is properly rendered on first page load but it's not on the next.
I've notice this happen only if Grav cache is enabled.

I've try to move the code above into the parent `modular.html.twig` to be sure the problem come from my code. And apparently not as when `assets.addInlineJs` is in the parent it's working.

All of that made me think there is BUG with Grav cache when adding assets from a modular.

Let me know if you need more information.

Cheers

**Comment by rhukster** [comment]
As explained in Slack chat this is not a bug, this is somewhat of a limitation for twig templates in modular pages.  A modular page is processed along with its modular twig and the result is stored as content, usually cached.  If you have 'non-visible' things going on these will probably get lost as they are not stored in the HTML rendered content.  Thre are several ways to approach this.  The easiest is to force Grav to not cache the twig portion of the content and reprocess the Twig for this particular modular page each time:

```
never_cache_twig: true
```

Another approach is to put the CSS/JS assets code in the parent (non-modular) page.

And lastly, you can use a plugin such as the Assets plugin which actually stores and caches any assets used separately from the content.

**Comment by jimblue** [comment]
Hi @rhukster thank's again it helped me to solve my pb!
