### ISSUE TITLE
Theme installation dependency bug?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#1862]
Not sure when this started to occur exactly, but when I release an update to my Course Hub Bootstrap theme it always displays that the bootstrap dependency is missing (even though it was installed):
![2018-02-07_12-48-12](https://user-images.githubusercontent.com/1812771/35946919-793a550a-0c1a-11e8-91fe-86d25d96a7d6.png)

Here is the theme blueprint file for reference:
https://github.com/hibbitts-design/grav-theme-course-hub-bootstrap/blob/master/blueprints.yaml

Did something change re: how a theme dependency is handled or am I needing to change something? Plugin dependencies are working fine of course.

Thanks very much,
Paul

**Comment by rhukster** [comment]
Weird, nothing has changed regarding this. Although you should use the version syntax:

```
dependencies:
    - { name: grav, version: '>=1.3.9' }
    - { name: form, version: '>=2.11.0' }
    - { name: login, version: '>=2.5.0' }
    - { name: email, version: '~2.0' }
```

**Comment by paulhibbitts** [comment]
Thanks @rhuk I will add the version syntax to the dependency and report back (next release) if that addresses the issue.
