### ISSUE TITLE
E_PARSE - syntax error, unexpected end of file, expecting ']' while trying to open admin page

### ISSUE THREAD

**Issue by setu4993** [getgrav/grav#1863]
Hi,

I accidentally deleted the landing blog page of my installation, and since then the admin page is inaccessible. I have retrieved the deleted pages into their correct folder structure and the website loads fine now, but I am still not sure why the admin page doesn't open.

Trying to open the admin page says:
``
Server Error
Sorry, something went terribly wrong!
E_PARSE - syntax error, unexpected end of file, expecting ']'
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
``
And the log says:
``
[2018-02-08 02:08:31] grav.CRITICAL: syntax error, unexpected end of file, expecting ']' - Trace: #0 /micro/vendor/filp/whoops/src/Whoops/Run.php(383): Whoops\Run->handleError(4, 'syntax error, u...', 3785) #1 /micro/system/src/Grav/Common/Errors/SystemFacade.php(36): Whoops\Run->handleShutdown() #2 [internal function]: Grav\Common\Errors\SystemFacade->handleShutdown() #3 {main} [] []
``
(I have retracted the folder structure from the log since it is running on an open website.)

Any help is appreciated. Thanks.

**Comment by setu4993** [comment]
So, I looked at the error_log created by the server, and turns out one of the *.yaml.php files under /cache/config was incomplete. I renamed that file, and tried opening the admin page again, and it worked.

However, I still am not sure what caused the file to be created in such a way. Keeping the issue open so that the error can be fixed.

**Comment by rhukster** [comment]
Strange one, i've never seen that error.  If you can give me some exact steps to reproduce, I can see about addressing it.

**Comment by setu4993** [comment]
1. Open the landing 'blog' page of the installation to edit it.
2. Delete it with the 'x' sign on top.

That is when the website and the admin pages stopped loading with the above error.

**Comment by rhukster** [comment]
I was able to delete the page ok.. 

![screen shot on 2018-02-19 at 12 06 10](https://user-images.githubusercontent.com/1084697/36393625-937fa382-156d-11e8-94fa-8f5034fab24f.png)

Even though it warned me about the hazards of deleting the current 'home' page, i confirmed and it deleted it. Admin didn't break, but simply showed me no pages:

![screen shot on 2018-02-19 at 12 07 52](https://user-images.githubusercontent.com/1084697/36393618-8ccd4242-156d-11e8-9739-18e9021a567c.png)

Front end didn't break either, just showed me a 404 as expected:

**Comment by setu4993** [comment]
I see. That's different from what happened to me.

I had an 'About' page that was 01, and the 'Blog' page that was '00' with items under the 'Blog' page. I am running Lingonberry, if that helps.
