### ISSUE TITLE
Twig-variables do not cache

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#1865]
The event hook `onPageContentProcessed` combined with cache enabled seems to break Twig-variables passed from a plugin, in which the variable renders once on when cache is rebuilt but is not cached. Thus on subsequent reloads of the browser, the output of the variable(s) render as empty.

This seems to be from some change between Grav v1.3.4 and v1.4.0-rc.1, but I cannot identify the specific change. See the attached file for a limited test case, in which the Fullpage-plugin passes `fullpage_init` into it's fullpage.html.twig-template.

[testcase_grav-v1.4.0-rc.1.zip](https://github.com/getgrav/grav/files/1714487/testcase_grav-v1.4.0-rc.1.zip)

Has there been any change in how Twig-variables are handled?

**Comment by rhukster** [comment]
There has really been no change in how twig variables are handled that I can think of.  Can you give me a little more detail about what i'm looking for.  The zip contains an entire site.  Cheers.

**Comment by OleVik** [comment]
Oh, I do apologize, I just threw the entire test-case into a folder. Specifically, see line 112 of `user/plugins/fullpage/fullpage.php`, which passes `fullpage_init` into a Twig-variable. This is called on line 58 of `user/plugins/fullpage/templates/fullpage.html.twig`. Uncached, the content of the variable renders, but when cached it does not.

I wonder if this is because of this happening in the `onPageContentProcessed` event. Though I am now testing with moving asset-logic into the template, the same event has been used previously to pass Twig-variables into the template - in earlier versions of the plugin using Grav v1.3.*.

**Comment by Perlkonig** [comment]
Well [the docs say](https://learn.getgrav.org/advanced/performance-and-caching#caching-and-events) that `onPageContentProcessed` doesn't get triggered on a cache hit, which makes sense. But I am hoping to find a way to inject dynamic data from a plugin into an otherwise cached page. Did you find a workaround @OleVik?

**Comment by OleVik** [comment]
I currently [disable it temporarily](https://github.com/OleVik/grav-plugin-fullpage/blob/master/fullpage.php#L73) when the plugin executes, and [restore it](https://github.com/OleVik/grav-plugin-fullpage/blob/master/fullpage.php#L169-L172) afterwards. This allows the plugin to operate as expected, without actually changing or overriding the user's settings outside of the scope of the plugin.
