### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by Diyzzuf** [getgrav/grav#1866]
I would like to add my new plugin  to the Grav Repository.
Here are the project details: **Diyzzuf/grav-plugin-private-site**

[Diyzzuf/grav-plugin-private-site](https://github.com/Diyzzuf/grav-plugin-private-site/)

Private is a Grav Plugin. It provide an authentification form to keep private your Grav site or part of it.
Update of Private Plugin, with integration of Admin/Login/Form Grav plugins & User Register / ACL

![27860e8a-e92b-11e4-94fb-4138a9af4ffe](https://user-images.githubusercontent.com/11059073/36076115-6a0d73fa-0f58-11e8-8eb8-361a2749b9a0.jpg)

**Comment by rhukster** [comment]
Added to GPM for next update
