### ISSUE TITLE
Properties from Expert mode visible in Normal Advanced mode

### ISSUE THREAD

**Issue by B-iggy** [getgrav/grav#1867]
Hey dear grav team,

once again thanks for such a great project you created here!

I would like to request a feature (?) about the Expert and Normal mode. Mostly because of convenience reasons but maybe for people useful nevertheless.

Would it be possible to translate every possible Expert property into the Normal mode view under Advanced?

**Example**:
You want to have icons in your navigation. For that you have `{% if page.header.icon %}`. But to implement that property you have to go in Expert mode > Frontmatter and add in the Content field for example
`icon: home`

Now what about a dedicated input field for the property Icon in the Normal view > Advanced?
Like I fake added here:

![image](https://user-images.githubusercontent.com/7815434/36077803-71ee4394-0f6f-11e8-9ba1-b2b8e39a8d99.png)

It does the same like the one in expert mode but just, you know, clicky picky for "normal" users ;)

Just an idea and thanks for reading.

Greetings

**Comment by rhukster** [comment]
You can add this functionality by providing custom blueprints: https://learn.getgrav.org/forms/blueprints

You can see these in action in themes such as Antimatter in the `blueprints/` folder.

**Comment by mahagr** [comment]
Oops, wrong commit message, should have been admin ^
