### ISSUE TITLE
Missing a cookbook entry for custom plugin route

### ISSUE THREAD

**Issue by niahoo** [getgrav/grav#1870]
Hello, 

I can't find this simple use case in the documentation : I want my plugin handle http request on a certain URL, e.g. GET /my-plugin/custom/route .

Is that possible ?

Thank you

**Comment by rhukster** [comment]
Yes, this probably could do with some documentation, but for now you can see something similar in `sitemap` plugin where it fires off some logic and outputs a sitemap when you go to a URL that's configured in the plugin's options:

https://github.com/getgrav/grav-plugin-sitemap/blob/develop/sitemap.php#L40-L51

**Comment by niahoo** [comment]
Thank you very much, I will look into this.
