### ISSUE TITLE
Custom renderer doesnt work

### ISSUE THREAD

**Issue by niahoo** [getgrav/grav#1871]
Hi, I added a new file type in media.yaml : `jpjson` and added a `item.jpjson.twig` but the URL `/blog/my-test-post.jpjson` yields a 404 error.

But it works if I have the same config with just json. Is it hardcoded somewhere ? It should work as stated in the docs.

Can you help me ?

Thank you

**Comment by rhukster** [comment]
Actually its' not `media.yaml` you need to edit but rather your `user/config/system.yaml` and edit the `page: types:` array:

https://github.com/getgrav/grav/blob/develop/system/config/system.yaml#L55

**Comment by niahoo** [comment]
Ok, thank you. So. his is for a plugin, would it be possible to dynamcally add the new type before the routing process where `$valid_page_types`is defined ? It seems that all hooks happen after this step.

**Comment by rhukster** [comment]
You can edit the system configuration dynamically at runtime:

```
$config = $this->grav['config'];
$current_pages_types = $config->get('system.pages.types');
$config->set('system.pages.types', array_push($current_pages_types, 'jpjson'));
```

**Comment by niahoo** [comment]
Yes I figured out, but unfortunately it seems that [the configuration is read](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Uri.php#L346) before I can do anything in a plugin hook.

Thank you.
