### ISSUE TITLE
Trailing Slash

### ISSUE THREAD

**Issue by DanielSokil** [getgrav/grav#1873]
I can't seem to find a setting to enable trailing slash.

Current `https://www.example.com/` Redirects to `https://www.example.com` for all pages.

Thanks Ahead.

**Comment by DanielSokil** [comment]
`Redirect trailing slash` does not work. Also mentioned in https://discourse.getgrav.org/t/trailing-slash-at-end-of-urls/5459

**Comment by rhukster** [comment]
Answered there: https://discourse.getgrav.org/t/trailing-slash-at-end-of-urls/5459/4
