### ISSUE TITLE
How to install grav with admin plugin in a sub-folder?

### ISSUE THREAD

**Issue by fabrizioquercia** [getgrav/grav#1874]
Hy everybody.

First of all sorry for my terrible english, hope you can understand me.

When I try to install grav with admin plugin in a sub-folder I receive a 404 error.

Example:
www.mysite.com/grav (without plugin: ok, view the front end correctly)
www.mysite.com/grav (with plugin: the plugin redirect me to grav/admin with 404 error)

if i use grav without admin plugin i can see the front page correctly, but if try to install the admin plugin, everytime i receive a 404 with ad immediare redirect like the sample above.

In my local pc i've not this problem, admin plugin works correctly anytime.

Please, someone can help me to solve this?

Hy
Fabrizio

**Comment by hugoaf** [comment]
There is information about 404 in the docs: https://learn.getgrav.org/troubleshooting/page-not-found

**Comment by fabrizioquercia** [comment]
Thanx a lot. I've already solved it by myself just now.

**Comment by MakePixelsWork** [comment]
Too bad this issue has not been resolved or answered. I'm asking the same thing, also on Discord, but have yet to been provided with a satisfactory answer. Anyone?

**Comment by rhukster** [comment]
FYI this is more an exception rather than a rule.  Mostly it just works in Apache with default settings.  Obviously your web server is configured in such a way that it requires rewrite base, but for most people it is not required.
