### ISSUE TITLE
Override absolute (base) URL for canonical URLs, or disable canonical URLs entirely

### ISSUE THREAD

**Issue by alexweissman** [getgrav/grav#1875]
There are cases where the desired base URL (e.g., `http://example.com/`) for the `link "rel=canonical"` DOM tag could be completely different from the base URL that Grav pulls in by default (e.g., `https://sub.example2.com/`).

At the moment, using the `routes.canonical` page header setting will _append_ a given value to Grav's default base URL.  However, there is no way to specify the complete, absolute URL here if the canonical value should point to a different domain or subpath.

If I do this:

```
routes:
    canonical: http://example.com/
```

I'll get `link "rel=canonical" href="https://sub.example2.com/http://example.com/`.

Using `custom_base_url` to change the actual base URL would seem like one possibility, but it comes with unintended side-effects and may not always be a practical solution.

It would also be helpful if we could disable canonical URLs entirely by setting `routes.canonical` to `false`.

**Comment by rhukster** [comment]
I can't replicate this: If I add this in the frontmatter:

```
routes:
    canonical: http://canoncical.com/home
```

The results with this:

```
{{ page.routeCanonical() }}
```

Is the full `http://canoncical.com/home` as expected.

**Comment by alexweissman** [comment]
Ah, it's possible that this is simply an issue with the Antimatter theme's implementation of the link tag: https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/base.html.twig#L11
