### ISSUE TITLE
Page changes not saving - Grav v1.4.0-rc.2 - Admin v1.7.0-rc.3

### ISSUE THREAD

**Issue by brokentechnology** [getgrav/grav#1878]
Hello,

I updated to the following versions:

Grav v1.4.0-rc.2 - Admin v1.7.0-rc.3

I can create a page just fine and fill out it's content. It will save the first time. However, if I go to edit that page and make changes, then save, it clears my changes even though it says saved.

There is no errors in the logs to indicate the cause. I am using the expert editor as well. 

I changed over to the "normal" editor and it is working fine. Appears to be an issue with the expert editor.

**Comment by rhukster** [comment]
I can't replicate this..i did this:

* I created a new page
* switched to expert mode
* added a custom frontmatter variable
* added some content in the content area
* saved
* exited to pages, and went back to the new page
* modified frontmatter variable
* modified content again, saved again
* exited to pages, and went back to the new page
* All changes showed as expected

**Comment by brokentechnology** [comment]
Very odd - I can no longer replicate either. I am not sure what went haywire. Maybe a cache issue. 

Everything working as intended - closing this out for you.
