### ISSUE TITLE
Upgrade broke

### ISSUE THREAD

**Issue by mabushey** [getgrav/grav#1882]
Hello,

I did a git pull on the grav directory: `Updating 7a3f1362..f9f8cb8b`

I ran `bin/composer.phar update` from this grav directory, then in the site directory ran `bin/grav composer`, `bin/grav clean`, and `bin/grav clearcache`.

```
╰─➤  bin/gpm            
PHP Fatal error:  Uncaught Error: Class 'League\CLImate\CLImate' not found in /var/www/grav/grav/bin/gpm:41
Stack trace:
#0 {main}
  thrown in /var/www/grav/grav/bin/gpm on line 41
```

How do I install CLImate?

Thanks for the help. :)

**Comment by mabushey** [comment]
I reinstalled my site from a backup and it's working with the upgraded central grav repo now. I wish grav/composer wasn't so delicate. I love grav but almost every upgrade takes the site down until I can figure out what composer/grtav/gpm commands to run in whatever sequence. Other than this grav makes me very, very happy.

**Comment by rhukster** [comment]
I really never have any issues like this :)

If you are working with the github version, this does not include the vendor dependencies (as the regular grav builds do), so to ensure you stay working every time you pull from github you should do a:

```
composer install --no-dev
```

This will install all the latest vendor libraries except the stuff used for development and testing. Don't use `composer update` as this will update the vendor libraries to latest versions that might not be tested, always use `install` which will install known working versions from the `composer.lock` file.

After this, simply clear the cache:

```
bin/grav clear --all
```

> BTW, don't run `bin/grav clean` as this is used to clean out tests and extra files that are used during the Grav build process only.

the `--all` will ensure you clear everything including any Twig compiled files.  If you do this, you should never have any other issues.

**Comment by mabushey** [comment]
Thank you for this reply Andy. This makes sense and you've alleviated my concerns regarding upgrading grav. If this works reliably for you I'm positive it do the same here.
