### ISSUE TITLE
Installed clean Grav, not able to work in Admin Panel

### ISSUE THREAD

**Issue by kirillsavine** [getgrav/grav#1886]
Running on shared hosting with SSH access.
Ran the following comands to install Grav into the public folder:
```
git clone -b master https://github.com/getgrav/grav.git
composer install --no-dev -o
php bin/grav install
```

After this I was able to successfully browse the Welcome page "Grav is Running!"

Now installing admin panel:
```
php bin/gpm install admin
````

This went without an issue. I was able to browse the admin section of the website, created the `admin` user, but once logged in into the admin panel using the browser, I constantly get "Fetch Failed" messages, and not able to install any themes or plugins using the Admin Panel UI. The "installing..." window just keeps hanging there forever. Screenshot below
![installing_theme](https://user-images.githubusercontent.com/12634922/36606281-3c537684-1891-11e8-8b8a-5352d7132f94.png)

Can it be related to not having SSL? (I do not have SSL on the website that I am trying to run). 

I would appreciate any advise how to overcome this issue of not being able to install a theme or plugin using Admin Panel UI.

**Comment by rhukster** [comment]
I'ts quite likely that it's SSL related as all the calls to check for GPM status etc require SSL to function.

**Comment by NikolaySitnikov** [comment]
Thank you Andy for your reply. Is it possible to run grav and admin plugin without having SSL? Or enabling SSL is the only option to solve the issue that I am facing? 
I appreciate your help

**Comment by kirillsavine** [comment]
Thank you Andy for your reply. Is it possible to run Grav and the Admin plugin without having SSL? Or enabling SSL is the only option to solve the issue that I am facing?
I appreciate your help
