### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by funkjedi** [getgrav/grav#1889]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: [funkjedi/grav-plugin-markdown-tasklists](https://github.com/funkjedi/grav-plugin-markdown-tasklists/)

To create a task list, preface list items with `[ ]`. To mark a task as complete, use `[x]`.

```
- [x] Finish my changes
- [ ] Push my commits to GitHub
- [ ] Open a pull request
```

![](https://help.github.com/assets/images/help/writing/task-list-rendered.png)

**Comment by rhukster** [comment]
I will get this added soon. thanks.

**Comment by rhukster** [comment]
Added for next GPM update.
