### ISSUE TITLE
error on line 63 at column 15: xmlParseEntityRef: no name

### ISSUE THREAD

**Issue by kaanavsar** [getgrav/grav#1890]
hi guys and gals,
I get  that error when I try to browse rss index.php which is created with php / xml
I tried several configurations stil cant solve it, its ok on other browsers but chrome has issues.

here is the full codes:
`<?php

		ob_start();
		header("Content-Type: text/xml");

		
		//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
		//~~~~~~~~~~~~~ Settings ~~~~~~~~~~~~~~~~~~~~~//
		//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
	
		include("../config.php");
		include("../class/mysql.class.php");
		include("../includes/db.php");
		include("../includes/functions.php");
		include("../includes/settings.php");
		
		
		//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
		//~~~~~~~~~~~~~ RSS infos ~~~~~~~~~~~~~~~~~~~~//
		//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
		
		echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n";
		echo "<rss version=\"2.0\">\n\n";
		echo "<channel>\n";
		echo "<title>".$settings['site_title']."</title>\n";
		echo "<link>".$settings['site_url']."</link>\n";
		echo "<description>".$settings['site_title']." | ".$settings['site_slogan']."</description>\n";
		echo "<language>en-EN</language>\n\n";
		
		
		$query = $db->read_query("SELECT id, title, spot, date
		 FROM news  WHERE active = 'Y' ORDER BY id DESC LIMIT 10") or die($db->sql->error());
									
		while($row = $db->sql_fetcharray($query)){
		
			echo "<item>\n";
			echo "<title>".stripslashes(strip_tags($row[title]))."</title>\n";
			echo "<link>".$settings['site_url']."/news_detail.php?id=".$row[id]."</link>\n";
			echo "<date>".time_to_now($row[date])."</date>\n";
			echo "<description>".stripslashes(strip_tags($row[spot]))."</description>\n";
			echo "</item>\n\n";
		
		}
		
		$db->sql_freeresult($query);
		$db->sql_close();
		
		echo "</channel>\n";
		echo "</rss>";
?>`

**Comment by rhukster** [comment]
I'm a bit confused by this question.  Where is this file and what does it have to do with Grav?  I'm pretty sure we are not using it as it requires a Database and Grav doesn't at all.

**Comment by kaanavsar** [comment]
sorry wrong place :(
