### ISSUE TITLE
Incorrect routing with setup.php based base

### ISSUE THREAD

**Issue by hundblue** [getgrav/grav#1892]
There is an incorrect use of `str_replace` in `Grav\Common\Uri::init()`:
[https://github.com/getgrav/grav/blob/eca23a918a71b0a49f5abad59e6c824f9e146351/system/src/Grav/Common/Uri.php#L321](`$uri = str_replace($setup_base, '', $uri);`).
The problem is that instead of removing just the prefix, **each** occurence of `$setup_base` is removed. For example, if the input `$uri` is equal to `'/foo/bar/foo/baz'` and `$setup_base` is equal to `'/foo'`, then the output `$uri` is now equal to `'/bar/baz'`.  The correct result should be  `'/bar/foo/baz'`.

**Comment by rhukster** [comment]
assigned to @mahagr to look at.

**Comment by mahagr** [comment]
I just checked this and the behaviour is correct. It should do just that as the base path gets added to the urls by `base_url` variable in twig or by using `url()`.

`Uri` is always relative to the site itself and is used in routing. If you want to point files outside of the site, you need to use absolute (or external) URLs.

**Comment by hundblue** [comment]
The behaviour which I have observed is that if the name of the subsite coincides with the name (the slug) of some page, then that page (or any of its subpages) is routed incorrectly.
For example, suppose `'foo'` is the name of the subsite (`'/foo'` is then passed as `$prefix` to `$container['pages']->base($prefix)`). Furthermore, suppose that some page of the subsite is also named `'foo'`. E.g., there is a page `'05.bar'` (under the `'pages'` folder) whose slug equals `'bar'` and a page `'05.bar/02.foo'` whose slug equals `'foo'`. Let `$url` be  `$hostname . '/foo/bar/foo'`. Then this url is resolved to the `'bar'` page instead of to the `'foo'` page.

**Comment by hundblue** [comment]
Just pressed the wrong button, no intention to close the issue.

**Comment by mahagr** [comment]
Ok, I think I got it now.

You're saying that `/foo/bar/foo` will become `/bar/` instead of `/bar/foo`...?

**Comment by hundblue** [comment]
Yes, exactly. Similarly, in my first example which I gave when I opened the issue, I was saying that `/foo/bar/foo/baz` will become `/bar/baz` instead of `/bar/foo/baz`.

**Comment by mahagr** [comment]
Should be fixed for Grav 1.4.6
