### ISSUE TITLE
Changing mime type of xlsx file not working

### ISSUE THREAD

**Issue by sanoopvas** [getgrav/grav#1894]
Changed the mime type of xlsx file from **mime: application/vnd.ms-excel** to  **mime: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet** using the admin configuration  but response  header still shows the mime type of xlsx files as **mime: application/vnd.ms-excel**. This causes the xlsx file not opening correctly in firefox.

In the file user/config/media.yaml the mimetype is correctly displayed as **mime: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet**

**Comment by rhukster** [comment]
Can you provide me a copy of your edited media.yaml ???

**Comment by geogeorgejoseph** [comment]
[media.yaml.zip](https://github.com/getgrav/grav/files/1773950/media.yaml.zip)
