### ISSUE TITLE
Frontmatter lacks documentation

### ISSUE THREAD

**Issue by frankhaugen** [getgrav/grav#1895]
I'm about to give up on Grav, because I'm trying to edit my pages in expert mode, but when wanting to edit the "frontmatter" there is no information about the "tags" i need to use.

I want to change the "logo" in the Antimatter theme, can't do it. I want to add a big background image, can't do it.

You need to create documentation, or some way to display the what kind of tags to use so I't intuitive to work with

**Comment by andrewd72** [comment]
It should be changeable by editing config.site.title which should show in Admin under config, site tab.   
Changing appearance will depend on theme, for antimatter look at lines 45-47
https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/base.html.twig

**Comment by frankhaugen** [comment]
I can change the site's name under that config location.

The lines of code indicate that i could use "header_image", or more likely "header_image_file", however, they do nothing.

Would be just super if the admin-panel just presented all the possible options for the given theme's page template

**Comment by rhukster** [comment]
It's up to the theme provider to document what can be set, and that really means that they need to provide an appropriate blueprint.yaml to define those fields.
