### ISSUE TITLE
Some warning messages when downloading xlsx files from the grav site

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav#1896]
Some warning messages when downloading xlsx files from the grav site using firefox .(issue only exist when open with ms-excel)

How to set MIME-TYPE for XLSX in grav?

Added xlsx mime-type as "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" in config - > Media . But it is not working.

![download 1](https://user-images.githubusercontent.com/25584016/36787222-5f54ee70-1caf-11e8-9312-651faaafbb93.jpg)

**Comment by rhukster** [comment]
Duplicate issue: https://github.com/getgrav/grav/issues/1894
