### ISSUE TITLE
Multisite with page inheritance

### ISSUE THREAD

**Issue by jrivero** [getgrav/grav#1901]
Hi,

I am trying to configure a multisite that inherits the pages that do not exist from a common directory. The problem is that using the Streams on pages does not seem to work and I do not locate the grav code that deals with it to analyze it and solve it.

I have:
user / pages
user / sites / site1 / pages
user / sites / site2 / pages

When I request a page in site1 and it is not in site1/pages I want to look for it in user/pages.

I'm trying many methods, but my idea revolves around the following code:
```
'page' => [
    'type' => 'ReadOnlyStream',
    'prefixes' => [
        '' => ['user/pages', "user/{$folderEnvironment}/pages"]
    ]
]
```

I found it similar past issue:
https://github.com/getgrav/grav/issues/714

**Comment by rhukster** [comment]
Passing this to the multisite expert @mahagr  :)

**Comment by jrivero** [comment]
toc toc toc :)

**Comment by mahagr** [comment]
I don't think that streams are properly supported by pages yet. I remember it being the last few places where the logic just picks the last existing folder in the stream uses that.

**Comment by jrivero** [comment]
ok!

Is it planned to do so in the future?

**Comment by mahagr** [comment]
It is planned, but Pages classes are rather complicated so I didn't dare to change the behaviour when we moved Grav to use streams.

**Comment by izzyu91** [comment]
I would like to add my +1 to this feature / change as well.

I just tried to build such a site and found this ticket while searching for the problem. It would immensly simplify my work at this point.

**Comment by mahagr** [comment]
Closing in favor of #714
