### ISSUE TITLE
victorjonsson/markdowndocs referenced as branch rather than tag

### ISSUE THREAD

**Issue by timcosgrove** [getgrav/grav#1902]
The victorjonsson/markdowndocs package that is referenced in composer.json points to a git branch rather than a tag:
```
    "require-dev": {
        "codeception/codeception": "^2.1",
        "phpunit/php-code-coverage": "~2.0",
        "fzaninotto/faker": "^1.5",
        "victorjonsson/markdowndocs": "dev-master"
    },
```
Is there a reason for this? The difference between master and the most recent tag is not very large: https://github.com/victorjonsson/PHP-Markdown-Documentation-Generator/compare/1.3.8...master Though that difference may be critical.

I ask because referencing the package like this means we cannot commit the package to git. Obviously committing `vendor` to git is not always best practice but there are times it's necessary.

**Comment by rhukster** [comment]
The reason is that I actually needed a fix that i did a PR (that was merged) - https://github.com/victorjonsson/PHP-Markdown-Documentation-Generator/commit/c9fa153b28a79f5da89ec32aa501be92db212aed

**Comment by rhukster** [comment]
I hope he does a new release soon, as that was some time ago.

**Comment by timcosgrove** [comment]
This is quite old and question was answered. Thanks!
