### ISSUE TITLE
Customizing what Markdown syntax is converted into...

### ISSUE THREAD

**Issue by superDuperCyberTechno** [getgrav/grav#1903]
As an example, would it be possible to edit what a header converts to?

`# Header`
Converts to:

`<h1>Header</h1>`

But since I'm currently using the Bulma CSS framework, I need it to convert to the following:

`<h1 class="title is-1">Header</h1>`

Possible?

**Comment by tidiview** [comment]
What about `# header {.title is-1}`?

**Comment by rhukster** [comment]
That requires markdown extra, and frankly that's a bit flakey.

**Comment by superDuperCyberTechno** [comment]
Hmmm. Not optimal but I appreciate your answers.
