### ISSUE TITLE
In-editor internal link completion

### ISSUE THREAD

**Issue by SirPL** [getgrav/grav#1904]
Hi,

I would like to propose new enhancement/plugin idea for grav editor: adding an auto-completion for links.

In the WordPress you may add a new link to a page on your website by typing its name. Then link is created automatically.
![obraz](https://user-images.githubusercontent.com/11311649/37118292-13775e0c-2254-11e8-9c79-3287f347c743.png)

![obraz](https://user-images.githubusercontent.com/11311649/37118460-9e536ed0-2254-11e8-910a-df9572f101fc.png)

![obraz](https://user-images.githubusercontent.com/11311649/37118431-7dd0f6f0-2254-11e8-9aa7-2481d97cd850.png)

**Comment by rhukster** [comment]
That would be amazing!  Look forward to someone helping create this :)

**Comment by SirPL** [comment]
@rhukster - Shall I create another request in admin plugin repo or you have it in your internal backlog? I don't know your way of work.
