### ISSUE TITLE
Fatal error after update and git pull

### ISSUE THREAD

**Issue by jtphelan** [getgrav/grav#1906]
I updated to Grav v1.4.0 and Admin v1.7.0 through the UI in my dev environment which worked fine. I committed the change and pushed and pulled to prod but now I'm getting this error.

```
[10-Mar-2018 00:19:41 UTC] PHP Warning:  include(): Failed opening '/home/myuser/public_html/vendor/composer/../../system/src/Grav/Common/Service/MessagesServiceProvider.php' for inclusion (include_path='.:/opt/cpanel/ea-php56/root/usr/share/pear') in /home/myuser/public_html/vendor/composer/ClassLoader.php on line 444
[10-Mar-2018 00:19:41 UTC] PHP Fatal error:  Class 'Grav\Common\Service\MessagesServiceProvider' not found in /home/myuser/public_html/system/src/Grav/Common/Grav.php on line 418
```

I've tried deleting the vendor dir and running composer install. I've run bin/grav clean and bin/grav clearcache

**Comment by rhukster** [comment]
Classloader is out of whack. It's trying to load a class that no longer exists

Deleting the vendor folder and doing a `composer install --no-dev` should work if you are not syncing your vendor folder. This should reinstall all vendor libraries and rebuild the composer classloader too.

Are you sure you are fully up to date on your Grav install too?

**Comment by jtphelan** [comment]
I am committing my vendor folder. I tried it anyway and I'm still getting the same error.

$ bin/grav -V 
Grav CLI Application version 1.4.0

![screen shot 2018-03-09 at 7 52 21 pm](https://user-images.githubusercontent.com/1500776/37237011-6c97ed00-23d3-11e8-9914-8728c4c8da93.png)

**Comment by jtphelan** [comment]
I followed this article when I setup the .gitignore
https://getgrav.org/blog/developing-with-github-part-2

**Comment by jtphelan** [comment]
Ok, I just recloned the site from scratch and it works. Is there any trick I'm supposed to do when updating locally and pushing those updates live?

**Comment by mahagr** [comment]
If you don't use `git`, use `rsync` to mirror your files, it will make sure that all the directories and files are identical to your local.
