### ISSUE TITLE
On running Grav instance behind a reverse proxy and custom port.

### ISSUE THREAD

**Issue by moijafcor** [getgrav/grav#1907]
I am running my instance behind two reverse proxies (the SSL termination and the caching). The backend runs on port 8080 and is not exposed to the public Internet.

I've noticed URIs take the PHP provided server parameter, http://www.example.com:8080; but in my use case, it has to be https://www.example.com/.

Is there a safe method to override this behaviour in such a way the Grav instance remains upgrade safe? (No hacking core files or theme tricks).

Thanks!

```
<meta name="generator" content="GravCMS" />
--
  | <meta name="description" content="" />
  | <meta name="keywords" content="" />
  | <meta name="og:sitename" property="og:sitename" content="" />
  | <meta name="og:title" property="og:title" content="" />
  | <meta name="og:type" property="og:type" content="article" />
  | <meta name="og:url" property="og:url" content="http://www.example.com:8080/myurl" />
  | <meta name="og:image" property="og:image" content="http://www.example.com:8080/path/to/image.jpg" />
```

**Comment by rhukster** [comment]
Thanks for moving this here.  So what Grav version? Have you tried 1.4?

**Comment by moijafcor** [comment]
Grav v1.4.0

**Comment by rhukster** [comment]
Have you enabled the `reverse proxy setup` option in system.yaml? if so try toggling that off as it's adding a port option.

**Comment by moijafcor** [comment]
Enabling `reverse proxy setup` option in `system.yaml`, cleaning up the cache in Grav and in the caching proxy solve the issue.

Thank you!
