### ISSUE TITLE
Inline twig function stops working after upgrade to 1.4

### ISSUE THREAD

**Issue by Magalex2x14** [getgrav/grav#1909]
Hello! 
Perhaps I'm missing something in the 1.4 changelog, but with 1.3 the following construction is worked:
`Feel free to **[contact us](mailto:{{"inbox@example.com"|safe_email}})**`

This construction throws Grav 1.4 to 500 error with text "Unexpected character "&"".
Sorry for bad English.

P.S. it is a modular page

**Comment by rhukster** [comment]
think this relates to an update in Parsedown to address XSS vulnerabilities: https://github.com/erusev/parsedown/releases/tag/1.7.0

This escapes `&` in markdown causing an error.  `twig_first: true` doesn't help either as that will output the `&` which markdown then proceeds to escape again.

**Comment by rhukster** [comment]
I think the only way around this new markdown security fix, is to explicity use the twig with HTML:

```
<strong><a href="mailto:{{"inbox@example.com"|safe_email}}">contact us</a></strong>
```

**Comment by rhukster** [comment]
Interestingly if you render the variable first it doesn't render the mardkown at all:

```
{% set safemail = "inbox@example.com"|safe_email %}

**[contact us](mailto:{{ safemail }})**

<strong><a href="mailto:{{ safemail }}">contact us</a></strong>
```

https://trilby.d.pr/TKeLSc

**Comment by Sogl** [comment]
@rhukster After updating from 1.3.10 to 1.4.7 I get another error:
```
Unknown "safe_email" filter in "__string_template__
35c8104ef025a6fba0efdb87648d33021c0690da522173a2de55b1bee351a5b7" at line 1.
```

Screen:
![image](https://user-images.githubusercontent.com/7556290/43151119-34c19658-8f74-11e8-8057-c961ca4e5f58.png)

I use this filter with `process: twig: true` in lines:
```yaml
text: '{{''mail@company.ru''|safe_email}}'
icon: envelope-o
link: '{{''mailto:mail@company.ru''|safe_email}}'
```

**Comment by rhukster** [comment]
try this:

```
text: '{{"mail@company.ru"|safe_email}}'
```

don't use double single quotes, use double quotes...

**Comment by ikogan** [comment]
Does this imply that it is now impossible to use twig with markdown?

**Comment by mahagr** [comment]
Nope, they work just fine, you just need to use the correct syntax.

**Comment by ikogan** [comment]
Apologies, I discovered that my problem is a result of an interaction with the smartypants plugin.

**Comment by mahagr** [comment]
If it's still an issue, please file a bug report here: https://github.com/getgrav/grav-plugin-smartypants/issues
