### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by Avelornes** [getgrav/grav#1912]
Hello, I've just installed a core+admin version of grav, but I've an error 500.

I've try this : https://learn.getgrav.org/troubleshooting/internal-server-error

That's my error.log : 

`PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Creating directory '/var/www/html/grav-admin/cache/compiled/files' failed on error mkdir(): Permission denied' in /var/www/htmlgrav-admin/vendor/rockettheme/toolbox/File/src/File.php:424\nStack trace:\n#0 /var/www/html/grav-admin/vendor/rockettheme/toolbox/File/src/File.php(195): RocketTheme\\Toolbox\\File\\File->mkdir('/var/www/html/...')\n#1 /var/www/html/grav-admin/vendor/rockettheme/toolbox/File/src/File.php(320): RocketTheme\\Toolbox\\File\\File->lock()\n#2 /var/www/html/grav-admin/vendor/rockettheme/toolbox/File/src/PhpFile.php(31): RocketTheme\\Toolbox\\File\\File->save(Array)\n#3 /var/www/html/grav-admin/system/src/Grav/Common/File/CompiledFile.php(67): RocketTheme\\Toolbox\\File\\PhpFile->save(Array)\n#4 /var/www/html/grav-admin/system/src/Grav/Common/Config/Setup.php(180): Grav\\Common\\File\\CompiledYamlFile->content()\n#5 /var/www/html/grav-admin/system/src/Grav/Common/Processors/SiteSet in /var/www/html/grav-admin/system/src/Grav/Common/File/CompiledFile.php on line 83`

Any idea ?

**Comment by rhukster** [comment]
You have permission problems: https://learn.getgrav.org/troubleshooting/permissions

**Comment by Avelornes** [comment]
I did it, all that has changed is the error. We go from a 500 error to a 404 error :/

**Comment by DanielSokil** [comment]
@Avelornes The `permissions-fixing` shell script could help you, https://learn.getgrav.org/troubleshooting/permissions

**Comment by ketanpatil3** [comment]
The problem was due to some service creating a file named "files" and hence grav was not able to create a folder with the same name. delete the file and the error will go away for sometime and again it will get stuck with the same file.
