### ISSUE TITLE
search function on the admin page problem

### ISSUE THREAD

**Issue by kristoferus75** [getgrav/grav#1914]
Hi !

I have a problem  with the search function on the admin page.
When ever I search I get the below:

TypeError: Cannot read property ‘forEach’ of undefined at e.value (http://192.168.100.66/user/plugins/admin/themes/grav/js/admin.min.js?1b7a11d60e:5:98431)

The next message it prompts is:
iconv(): Wrong charset, conversion from utf-8' toascii//translit’ is not allowed

newest grav and all plugins updated 

Grav v1.4.1 - Admin v1.7.1

kind regards

kristoferus75

**Comment by rhukster** [comment]
Please open this here: https://github.com/getgrav/grav-plugin-admin/issues
