### ISSUE TITLE
Rendering HTML broken after latest release

### ISSUE THREAD

**Issue by tutchmedia** [getgrav/grav#1915]
Hi, 

We're currently using imgcaptions to display ALT text when you hover over an image. The text being added is HTML and was working fine before the latest version but now appears as a string as it's not parsing the tags. When viewing the source it seems to be converting them to encoded tags.

Not sure if this is related to Parsedown? Any help would be greatly appreciated.

Thanks

**Comment by rhukster** [comment]
There was a security release for Parsedown to address XSS attacks.  This might be breaking imgcaptions plugin.  You should probably create this issue on the `imgcaptions` plugin's issue tracker.
