### ISSUE TITLE
Truncate to closest sentence-end

### ISSUE THREAD

**Issue by diegovogel** [getgrav/grav#1918]
Not sure if this is a bug or just a mistake in documentation, but [according to the docs](https://learn.getgrav.org/themes/twig-filters-functions#truncate-a-string) this should truncate a string to the nearest sentence-end after 5 characters: **truncate(5, true)**. 

However, when I use that it simply truncates to the nearest word-end after 5 characters (like **safe_truncate**). 

Is this a bug or what?

**Comment by rhukster** [comment]
I think it's some outdated documentation. I'm not sure the second variable does anything anymore as we had to rewrite that function several times to better support HTML.

**Comment by diegovogel** [comment]
Thanks for the tip, sadly that didn't work for me. The output I get with that exact code is **Hey this**
Which makes sense if 4 is the number of characters, not words. Was it counting words for you?

**Comment by diegovogel** [comment]
Unrelated side note: I noticed the Grav backend now says "made by Trilby", and the Trilby site has been updated to focus on Grav. This makes he happy because I love Grav and I'm glad it's growing enough for Trilby to focus on supporting it.

**Comment by rhukster** [comment]
I was just looking at the Truncator code, but now I'm seeing that's that `|truncate` uses the older `Utils::truncate()` method, but `Utils::safeTruncate()` is using the new `Truncator` class with a word-safe option, try this:

```
{{ 'Hey this is a sentence. And this is another sentence.'|safe_truncate(12) }}
```

And yes, Trilby Media is comprised of the same folks from RocketTheme, but as Trilby is focused on professional services for Grav specifically, it makes more sense for Grav to come under it's auspices.

**Comment by w00fz** [comment]
You could try adding the `$break option in the mix`, it will never be accurate but if you assume all your sentences end with a `.` (period), you could set that.

Discalimer, I haven't actually tested this :)

`truncate(12, true, '. ')` <- I have a space after `.` but you could play with that so it's just `.`

**Comment by diegovogel** [comment]
Cool, thanks. I'll give this a shot.

**Comment by diegovogel** [comment]
@w00fz that seems to work perfectly. I did it without the space after the period: `truncate(10, true, '.')`

Thanks for the suggestion!
