### ISSUE TITLE
textarea and editor acts funky in list element

### ISSUE THREAD

**Issue by superDuperCyberTechno** [getgrav/grav#1919]
![grav_bug](https://user-images.githubusercontent.com/6486383/37397894-13313d7c-277d-11e8-89c5-29d15e008397.png)

The expand/collapse buttons doesn't seem to do anything.

Disabling the fixed 70px height height rule in the browser dev tools expands the boxes just fine.

Tested in Chrome and Firefox.

**Comment by rhukster** [comment]
Can you please reopen this issue in the Admin issue tracker? https://github.com/getgrav/grav-plugin-admin/issues

**Comment by superDuperCyberTechno** [comment]
Sure, no problem, https://github.com/getgrav/grav-plugin-admin/issues/1386
