### ISSUE TITLE
HTML Video not visible.

### ISSUE THREAD

**Issue by JohanG2012** [getgrav/grav#1924]
When adding a video in markdown: `![](video.mp4)`

The video does not show. The reason seems to be that the `<source>`-tag is outputted within quotes (copied from dev tools):

 `<video controls="1" alt="">&lt;source src="/user/pages/01.home/_02_video/video.mp4"&gt;Your browser does not support the video tag.</video>`

**Comment by rhukster** [comment]
I think this is related to the Parsedown security updates that came as part of Parsedown 1.7.0.  I shall investigate

**Comment by rhukster** [comment]
I've created a fix that can be used by other plugins that are adding markdown elements with HTML.
