### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by githubcodi** [getgrav/grav#1927]
Hi, i couldn't install getgrav with admin plugin, i have fresh digitalocean droplet with vestacp, nginx and php-fpm.. it always show 404 error page, i tried www.mydomain.com/admin , but nothing works.

Can someone help with this please.

Thanks

**Comment by rhukster** [comment]
First, please check all the advice here:  https://learn.getgrav.org/troubleshooting/page-not-found

**Comment by githubcodi** [comment]
I checked this earlier, and tried everything, nothing worked. what could be the problem?

**Comment by githubcodi** [comment]
Any inputs, please
