### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav#1928]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **https://github.com/JohnMica/grav-theme-bulma-portfolio/**

**Comment by rhukster** [comment]
Added to GPM, thanks.

**Comment by rhukster** [comment]
Problem, we have a conflict with this theme:  https://github.coms6joui/grav-theme-portfolio

Please rename your plugin.

**Comment by JohnMica** [comment]
Will do thank Andy

**Comment by JohnMica** [comment]
updated the name, github link and a new release 

https://github.com/JohnMica/grav-theme-bulma-portfolio/releases/tag/0.1.1

hope this solve the little issue

**Comment by rhukster** [comment]
done.. thanks.
