### ISSUE TITLE
What should I modify of the source code when I set the nginx root in a parent directory？

### ISSUE THREAD

**Issue by rzhang228** [getgrav/grav#1929]
For example, my grav project is path in /a/b/c/grav.
And I need to start the server in / because of I have another pages which is not belong to grav to show.
My nginx config is already like this:
[https://github.com/getgrav/grav/blob/master/webserver-configs/nginx.conf](https://github.com/getgrav/grav/blob/master/webserver-configs/nginx.conf)

Now,I can visit the home page,but the linked page such as /a/b/c/grav/d is return a 404 with 'No input file specified'
I am sorry for my poor php knowledge...
If I have to modify the source code,where should I modify?
Thanks!!!

**Comment by rhukster** [comment]
Not really a grav issue, pure 100% nginx + php setup: look here - 

https://stackoverflow.com/questions/21377321/nginx-no-input-file-specified-php-fast-cgi
https://stackoverflow.com/questions/46028755/nginx-no-input-file-specified
https://stackoverflow.com/questions/35050957/nginx-fastcgi-php-windows-no-input-file-specified
https://stackoverflow.com/questions/19739433/nginx-the-infamous-input-file-not-specified-solution-included-and-possible-e

etc, Google is your friend :)
