### ISSUE TITLE
Image file size increasing after going through Grav caching- no image actions

### ISSUE THREAD

**Issue by CSixtyFour** [getgrav/grav#1935]
I've been doing some image optimisation and noticed that some images are outputting larger than the original file even though I'm just using Grav for the cache - no image actions. For example stopwatch.png is 55kb in the page folder and 210kb on screen after its passed through Grav which is unexpected!

I'm loading the image: ` {{ page.media.images[ pt.img ].html( '' , '' 'img-responsive') }}`
Output on the page is: `<img title="" alt="" class="img-responsive" src="/images/6/6/5/5/a/6655a468d9e88dc0c30cf56cd65448212f2ab30a-stopwatch.png" />`

other than enabling the cache my system setup is default:

```
images:
  default_image_quality: 85
  cache_all: true
  cache_perms: '0755'
  debug: false
  auto_fix_orientation: false
media:
  enable_media_timestamp: false
  auto_metadata_exif: false
  upload_limit: 67108864
```
The HxW stay the same (as expected) 
I've done an image compare in Beyond Compare and the only difference I see is the file going from 8bits to 32bits. 

I'm attaching both copies of the file for testing. I don't have many images but I have seen this with a few of the other images too (jpg as well as png). Possibly the transparent background is an issue?
Thanks
Original:
![stopwatch](https://user-images.githubusercontent.com/5107817/37726019-3ffce64e-2d2c-11e8-96fa-6cc049dd4d8e.png)
Output:
![6655a468d9e88dc0c30cf56cd65448212f2ab30a-stopwatch](https://user-images.githubusercontent.com/5107817/37726020-401db932-2d2c-11e8-99af-fb617da399ce.png)

**Comment by rhukster** [comment]
I would say the original image was optimized with some kind of PNG compression.  PHP's GD library doesn't have this kind of capability so when it resizes the images, they are going to be resized but 'unoptimized'.

There's not a whole lot we can do about this.  If you are working with optimized images, sometimes its best just to just use them as-is without doing any kind of media operations on them.

**Comment by CSixtyFour** [comment]
The initial reason for me putting the files through Grav was for the caching (which also seems to help cloudflare cache them too whereas CF doesn't cache directly linked images) and not because the images necessarily need to media operations. 

Is there a better method for linking the images than `page.media.images` and direct linking via `page.url`?
Or maybe it would be useful to have an option to allow caching but disable manipulation?
