### ISSUE TITLE
finish ul with nl2br in markdown

### ISSUE THREAD

**Issue by Memurame** [getgrav/grav#1937]
Sorry for mi bad english.

When i press enter after a defined ul in the markdown editor, the output will not make a new "p" tag.

![text_in_editor](https://user-images.githubusercontent.com/15847494/37872883-d9bd6e98-3010-11e8-888a-7ca98da4fc6f.PNG)
![text_in_raw](https://user-images.githubusercontent.com/15847494/37872885-dcf46cec-3010-11e8-8b70-0dcf44489314.PNG)
![page_twig](https://user-images.githubusercontent.com/15847494/37872886-e148d85a-3010-11e8-9fee-0dcaee853135.PNG)
![not_correct_in_browser](https://user-images.githubusercontent.com/15847494/37872887-e326ca42-3010-11e8-9e63-46495d128abc.PNG)

**Comment by rhukster** [comment]
I'm not sure if this is a question or a statement :)

Markdown generally requires an empty line between paragraphs.  

So something like this:

```
intro pargraph...

1. my list item
2. another list item

another paragraph
```

which will output:

```
<p>intro pargraph...</p>
<ol>
<li>my list item</li>
<li>another list item</li>
</ol>
<p>another paragraph</p>
```

You can test markdown parsing here: http://parsedown.org/demo

As we use the Parsedown library to do all our markdown parsing.

**Comment by n30nl1ght** [comment]
Thx for your answer.

But when i use the nl2br with the markdown filter then i have this problem. 
How i can use nl2br with markdown?

I will make a new line for every "enter" in the editor.
