### ISSUE TITLE
Update to 1.4.2 failed

### ISSUE THREAD

**Issue by benninkcorien** [getgrav/grav#1939]
Windows 10. Bug?
Via Admin panel, updated a plugin - went fine.
Clicked the button to update to the latest version of Grav 1.4.2 (from 1.4.1).

    Fetch failed. Fatal error.

Refreshed the page.

    Please run: bin/grav install

Except when I run that from the command prompt, (also tried running cmd as admin)

    myprojectfolder>php bin/gpm selfupgrade
    PHP Warning:  require_once(myprojectfolder\bin/../vendor/autoload.php): failed to open stream: No such file or directory in myprojectfolder\bin\gpm on line 23

    Warning: require_once(myprojectfolder\bin/../vendor/autoload.php): failed to open stream: No such file or directory in myprojectfolder\bin\gpm on line 23
    PHP Fatal error:  require_once(): Failed opening required 'myprojectfolder\bin/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in myprojectfolder\bin\gpm on line 23

    Fatal error: require_once(): Failed opening required 'myprojectfolder\bin/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in myprojectfolder\bin\gpm on line 23

**Comment by rhukster** [comment]
I need some windows users to test.

**Comment by jgonyea** [comment]
Win10x64, Xampp (portable) , php 7.1.8
Installed Grav+admin v1.4.1 from zip file (success)
Updated form plugin (success)
Clicked Plugins admin menu to refresh page (success)
Clicked button to upgrade Grav to 1.4.2 (success)
Cicked on Plugins admin menu to refresh page. (success)
Clicked "Update all plugins" to upgrade admin and login plugins (success)
bin/gpm is working (success)


Sorry, I couldn't reproduce the issue you're seeing, @benninkcorien

**Comment by OleVik** [comment]
This is not specific to Grav. Rather, PHP cannot find, access or otherwise execute the needed files to perform the upgrade. @benninkcorien, we'd need to know the full paths (full PHP error) to identify common Windows issues, as well as Xampp-environment to identify common issues with the installation of PHP.

In general, especially for Grav, I would advise against Xampp, Wamp, or any other pre-made environment. They add little and obscure problems. For Grav, you basically just need PHP and optionally a webserver installed.

**Comment by benninkcorien** [comment]
I thought maybe it was a path / slash error because it showed myprojectfolder\bin/../vendor/autoload.php in the error message ( where it maybe should be myprojectfolder / with a forward slash on Windows?)..

But I just successfully update another grav 1.4.1 project to 1.4.2 via the Admin panel (clean install via composer, with everything on default and no plugins installed), and that updated perfectly fine. So that's probably not it then.

I'm not sure if I can downgrade the project that failed, to try and replicate the issue, and I'm not sure if that would be helpful because it looks like I'm the only one who had this issue? And if it's a "my system" problem, it's not a bug.

What PHP installation/option do you recommend for use on localhost? I already had XAMPP installed so figured I could use the PHP that came with that, but am happy to install whatever works better.

**Comment by benninkcorien** [comment]
I saw the vendor library message, but am  not sure if it's because of how everything is configured on  my PC, or if it's a bug in Grav. Hence the questionmarks :)

I'm running php 7.1.10 (via XAMPP still). 

Thanks for the recommendations! Do you know if there will be any conflicts if I install both XAMPP and pure PHP/Caddy?

**Comment by OleVik** [comment]
Nope, they will run separately. It could well be how Xampp is ran, whether it spawns PHP's processes as administrator or not. Though generally not necessary, a fair few locations within Windows or locations created by software, prevent non-administrators or non-inherent users from creating files there. This is not necessarily related to your account, but to how permissions propagate.

The error stems from the installation procedure, where PHP does not have permissions to write files. The problem with pre-made environments like Xampp etc is how they handle propagating permissions, which often is a benefit for security, but for basic PHP and Grav there is little to no risk anyway. Less so than with such larger environments.

Using a location like C:/Projects will work well, in which you have Caddy dropped right into the folder or in C:/Projects/Grav and PHP in C:/Projects/PHP.

**Comment by benninkcorien** [comment]
Thank you. I'm going to read the Caddy documentation later.
( I tried  manually updating Grav with command prompt  in Admin mode but that didn't work either, ended up just unzipping the new file and overwriting everything except the User folder. that worked well).

**Comment by benninkcorien** [comment]
Update - It's definitely a windows thing, I added a second harddisk into my PC with Ubuntu - grav update works perfectly fine there.
