### ISSUE TITLE
Grav and URL queries

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#194]
Is it possible to make Grav correctly work with URL queries?
Actually, somehow Grav partially works with URL queries, but not always.
If the URL would be, for example, like `site.com/page?download=1&format=2` it will work, but if you will add extension `site.com/page.html?download=1&format=2` it won't work.
Another example is simplesearch plugin:
`site.com/search?query=somesearchtext` — will work
`site.com/search.html?query=somesearchtext` — won't work
`site.com/search.json?query=somesearchtext` — won't work

**Comment by rhukster** [comment]
I have tested and confirm there is an issue when using a query string and a file extension as you have shown above.  However, it is working fine with querystring and no extension, and also it works fine with parameter syntax with/without the file extension.

For example:

```
site.com/search/query:somesearchtext
site.com/search.html/query:somesearchtext
site.com/search.json/query:somesearchtext
site.com/search?query=somesearchtext
```

All work, but the following doesn't:

```
site.com/search.html?query=somesearchtext
site.com/search.json?query=somesearchtext
```

I have looked at the code, and see the issue, just need to find a suitable fix :)

**Comment by rhukster** [comment]
@maxlysenko Can you try that #3f16619 commit and see if that resolves your issues?

**Comment by maxlysenko** [comment]
I've tried commit #3f16619 and at least I can confirm that in general for now pages with URL queries are loaded fine (without error 404) either with or without extension.
As for simplesearch plugin I guess something has to be changed in the plugin for this fix, because after the fix even parameter syntax with extension (wich was working before) has stopped working.

So after the fix:
```
site.com/page?download=1&format=2
site.com/page.html?download=1&format=2

site.com/search?query=somesearchtext
site.com/search/query:somesearchtext
```
All work, and now the following doesn't:
```
site.com/search.html?query=somesearchtext
site.com/search.json?query=somesearchtext
site.com/search.html/query:somesearchtext
site.com/search.json/query:somesearchtext
```

**Comment by rhukster** [comment]
hmm.. not sure why search would be any different.  I did give search a quick test using the simple search form and that worked fine.  I guess I'll try testing ajax type searching with it later today.

**Comment by Gertt** [comment]
Simplesearch works on my install also. Can you double-check your site with search plugin is also running the latest Grav commit @rhukster mentioned? What is going wrong on your end, getting 404's?

**Comment by maxlysenko** [comment]
If it matters I am testing on Windows. At the moment I've found out that in `simplesearch.php` `$uri->path()` returns value `\/search` with leading backslash. If I trim leading backslash the search works just fine both with query string and with parameter syntax both with and without extension.

**Comment by rhukster** [comment]
Yup, it's all fine on Mac/Linux but does appear to be some issues under Windows.  Unfortunately i'm traveling at the moment and don't have access to a windows machine.  I'm hoping @Gertt can help out and run some tests on the Uri object for windows and try to get this issues resolved.

**Comment by Vivalldi** [comment]
@maxlysenko I have personally worked in windows. Do you mind syncing your entire grav install to a repository and I can debug on my windows install.

**Comment by maxlysenko** [comment]
@Vivalldi you can download the [Grav Blog Site Skeleton](https://github.com/getgrav/grav-skeleton-blog-site/releases/download/1.0.1/grav-skeleton-blog-site-v1.0.1.zip), download the latest [SimpleSearch Plugin](https://github.com/getgrav/grav-plugin-simplesearch/zipball/1.2.5), download mentioned commit [#3f1661965b](https://github.com/getgrav/grav/archive/3f1661965bf4004230f49ea0a1bc8c4f897c6a88.zip), put it all together and try.

For me with such setup the following variants work:
```
domain.local/grav-blog/search/query:hills
domain.local/grav-blog/search?query=hills
```
And all of the following variants do not work:
```
domain.local/grav-blog/search.html/query:hills
domain.local/grav-blog/search.json/query:hills
domain.local/grav-blog/search.html?query=hills
domain.local/grav-blog/search.json?query=hills
```

**Comment by Gertt** [comment]
Hey guys, let us know if this latest fix still doesn't resolve all issues!
