### ISSUE TITLE
Typo in truncate function

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav#1943]
Hello,

Seems there is a typo here: https://github.com/getgrav/grav/blob/df7e9b9c1f544ad5fc3cf4b4227df9d1361f8f2b/system/src/Grav/Common/Utils.php#L265

Should be `$string = mb_substr($string, 0, $breakpoint) . $pad;`

Because of this truncate string finish with a space and not `...`

**Comment by rhukster** [comment]
Fixed in 1.5 branch

**Comment by jimblue** [comment]
Nice, thanks @rhukster.
Is 1.5 a major release?
