### ISSUE TITLE
Invalid AJAX Response / 302 error code on updates / install (localhost / www.example.dev)

### ISSUE THREAD

**Issue by iocron** [getgrav/grav#1946]
I've tried to update my old Grav 1.3.8 to the new one (1.4.2), but I always get the error "Invalid AJAX response" / Error Code 302. So I tried a fresh version (1.4.2) to see if it's an error on 1.3.8 or not. The freshly installed version 1.4.2 has the same issues and gives me a 302 error code. I've no clue what's going on, I've never had those issues last year (haven't worked for the project for a while now, but I want to use Grav for some more projects now, except I can't get it working, e.g. can't install any plugins or do any updates :((( that's so frustrating).

**Comment by w00fz** [comment]
Try to inspect the Network section of your Browser developer tools and filter by XHR.
When you get the 302 in the table, inspect it and look at the response.
The error means something is messing up the expect JSON response or that you have some redirect happening that is making it fail.

**Comment by rhukster** [comment]
Can you try disabling the "Remote Verify Peer" option in System Configuration? It might be that your SSL library and certs are too old.
