### ISSUE TITLE
Site is working , in desktop borwsers , but shows garbled text in iphone on chrome and iphone safari

### ISSUE THREAD

**Issue by chansdad** [getgrav/grav#1947]
I am using the Mache skeleton and did not make much changes except the content itself .

Site pages are being rendered fine on desktop borwsers and also in android brosers , but iphone safari and iphone chrome shows garbled text . 

Any suggestions on what i should do ? I have already tried 
ensuring content type is set right in the metatag.
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"> 

Thanks in advance.

**Comment by w00fz** [comment]
Mache is not an skeleton/theme maintained by Grav, so you'll have to redirect the issue to the author
https://github.com/tranduyhung/grav-skeleton-mache
