### ISSUE TITLE
Text highlighting contrast in Firefox

### ISSUE THREAD

**Issue by B-iggy** [getgrav/grav#1949]
Hey guys,
with the recent facelift of Grav Backend there is a visual problem in Firefox if you select the text in the editor. (::-moz-selection

I think this is the right place for that?
https://github.com/getgrav/grav-plugin-admin/blob/0a2b1d790f4cb4b189837c215eeda158a75e44dd/themes/grav/css/uikit.css#L331

Weird though why the CSS color "#fff" does not apply for me.
Please check the screenshot for reference.

### Firefox
![grafik](https://user-images.githubusercontent.com/7815434/38087659-3447a388-3359-11e8-8d17-6a796d19d367.png)

### Chrome
![grafik](https://user-images.githubusercontent.com/7815434/38087676-4787a56a-3359-11e8-9c8e-af4390cab896.png)

Or is it only on my end?

Thanks

**Comment by rhukster** [comment]
I have run into this myself, and even have a note in my task list to fix it.  However, I have no clue how!

I've tried the `::moz-selection` psuedo, and it ignores it completely.  It must be coming from somewhere else, but it's really hard to track it down as you can't inspect it.

BTW uikit.css is not used anymore, it will be removed for next release.
