### ISSUE TITLE
Ability for SimpleSearch plugin to accept parameters from POST requests.

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#195]
It would be useful if SimpleSearch will be able to accept parameters from POST requests.
Maybe something like:
``` php
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $query = $_POST['query'];
} else
    $query = $uri->param('query') ?: $uri->query('query');
}
```

**Comment by rhukster** [comment]
Why not submit this as a pull request?

**Comment by rhukster** [comment]
I meant as a PR In the simplesearch repo.  Closing here as it's not Grav specific.
