### ISSUE TITLE
Debug panel is unreadable

### ISSUE THREAD

**Issue by heihachi88** [getgrav/grav#1953]
![image](https://user-images.githubusercontent.com/5739191/38140327-1b3669ea-3455-11e8-830d-501663d54fff.png)

Take a look at image, when i try to inspect my collections it's going to be very hard (very long scroll), maybe you can stylize it better somehow?

**Comment by rhukster** [comment]
This is just how the debug bar works: http://phpdebugbar.com/

Perhaps create an issue there?

**Comment by hughbris** [comment]
@heihachi88 I agree but it's an external tool so yes, politely request an improvement at phpdebugbar :)
