### ISSUE TITLE
Complex collections depending on Frontmatter headers and it’s value?

### ISSUE THREAD

**Issue by webcoderkz** [getgrav/grav#1954]
Include partial view with a complex collection:

`{% include 'partials/article-main.html.twig' with {'page': #here goes condition} %}`

How can i choose all pages, that has a field named main_article in the headers/Frontmatter set to true?

Or even without that “with” part directly in a TWIG file:

```
{% set options = { items: {'@root': #someCondition here} } %}
{% set main_collection = page.collection(options) %}
```

**Comment by rhukster** [comment]
Frankly its simpler to just get all the pages and then filter during the loop over those items.  Something like this with a conditional `for` (https://twig.symfony.com/doc/2.x/tags/for.html#adding-a-condition):

```
{% set main_collection = page.collection() %}
{% for page in main_collection if page.header.main_article == true %}
  {% include 'partials/article-main.html.twig'  %}
{% endif %}
```

**Comment by heihachi88** [comment]
I've ended it this way:

```
{% set options = { items: '@root.descendants', 'order': {'by': 'date', 'dir': 'desc'}, 'pagination': false } %}
{% set main_collection = page.collection(options) %}

{# selecting pages with main_article true #}
{% for p in main_collection|slice(0, 1) if p.header.main_article %}
	{% set image = p.media[p.header.image].cropZoom(540, 310) %}
	{# {{ dump(image) }} #}

	<article class="main-news">
	    <a href="{{ p.url }}" class="d-block mb-3">
	        <img src="{{ image.url }}" alt="{{ p.title }}" class="img-responsive w-100 rounded">
	    </a>

	    <a href="{{ p.url }}">
	        <h4>{{ p.title }}</h4>
	    </a>
	</article>
{% endfor %}
```

Won't be there a more elegant solution in the future?

**Comment by heihachi88** [comment]
There's actually an issue with this approach. with `slice(0, 1)` i wanted to limit number of articles to 1, but it won't work correctly, because in collection would be all the pages with/without `main_article` set to true, therefore - it doesn't work.

What you can advice?

**Comment by jgonyea** [comment]
I did something similar to what you're looking for in my Editorial theme.

https://github.com/jgonyea/grav-theme-editorial/blob/619fac3aaa1252c05c469d51fe4ec17b41782f68
/templates/partials/featured.html.twig#L1
