### ISSUE TITLE
Error messages are displayed very short

### ISSUE THREAD

**Issue by AndreasFurster** [getgrav/grav#1956]
I'm getting an error when updating Grav and installing plugins. It looks like it has something to do with permissions, so nothing I shouldn't be able to solve. 

The problem is that the error messages are displayed very short. See [screen capture](https://gyazo.com/502bcfa452636ce4583b9701f97d2efa). I'm currently using Grav 1.4.1

Is there another location to view all occurred error messages? Or is there a specific reason why this happens?

**Comment by rhukster** [comment]
Perhaps you could take a non-gif video so that we can pause on the frame with the error and actually see it?

**Comment by OleVik** [comment]
Using Chrome's native .gif controls, I can (barely, low resolution) read that it says: "touch(): Unable to create /licenses.yaml because Permission Denied". In essence, @AndreasFurster, you have a [Permissions issue](https://learn.getgrav.org/troubleshooting/permissions).
