### ISSUE TITLE
Unable to call config.plugins.plugin-name.enabled in a template because of hyphen (-) character

### ISSUE THREAD

**Issue by diazwatson** [getgrav/grav#1957]
I am trying to get the value of `config.plugins.disqus-comments` in a twig template but I always get `null` although if I dump the content of `config.plugins` I can see `disqus-comments` is there.

I also noticed that if I rename my plugin files and remove the `hyphen (-)` in the name, it works just fine.

Is this a bug?
Is there a way to scape this character in a twig template?

I would not like to have to change my plugin name just because of that :(

Thanks

**Comment by diazwatson** [comment]
I think I found a way around.
I am making available the configuration in twig templates declaring a variable and assigning to it.
```
    public function onTwigSiteVariables()
    {
        $this->grav['twig']->disqus_comments_plugin = $this->config->get('plugins.disqus-comments');
    }
```

**Comment by diazwatson** [comment]
Hi Andy, thanks for your reply.
Is there an example on how to access plugin configuration using the attribute() function I can look at?

**Comment by rhukster** [comment]
```
{% set some_var = attribute(config.plugins, 'disqus-comments').some_var %}
```

**Comment by NicoHood** [comment]
A big ouuf to all plugins with dashed in their name. Accessing variables via `page.header` becomes very ugly now. Can't we at least have a syntax like `page.header['dash-plugin`].property? I remember there was a similar syntax for accessing configuration settings, but not for the page header.

**Comment by rhukster** [comment]
If you are talking about Twig, it's a limitation in Twig itself.  You should use the `attribute()` function: https://twig.symfony.com/doc/2.x/functions/attribute.html

**Comment by NicoHood** [comment]
Sure, but it seems you have fixed that for the config (original question by @diazwatson for this issue).

My request was to add this functionality to the `page.header` as well. Using the `Data` class this should be simple. I've tested this and it works, however you should know best if there are other side effects that we need to take care of, or if that fix is pretty straight forward. If it is easy, we should add it.

**Comment by rhukster** [comment]
I don't see this change during the 1.x release. It would have too much compatibility impact.  If you want to work with the hyphen easier, you can easily just convert the header array to a data object and work with it.  The impact of that is minimal. I often do this in plugins when I need more flexibility that Data provides, and is a pain to work with arrays.

For Grav 2.x we'll definitely do things differently.
