### ISSUE TITLE
Assets with `+` in the name get truncated

### ISSUE THREAD

**Issue by w00fz** [getgrav/grav#196]
It appears that assets with a `+` in the name get truncated and fail to load. I tried with both `markdown.extra` on and off and it's the same behavior.

### Test
```
![My Filename](my+file.jpg)
```

### Expected
```
<img src="/my/route/path/my+file.jpg?<cache_hash>" alt="My Filename" />
```

### Instead
```
<img src="file.jpg" alt="My Filename" />
```

**Comment by rhukster** [comment]
should be sorted, please confirm and reopen if issue persists.

**Comment by w00fz** [comment]
All good now :+1:
