### ISSUE TITLE
FontAwesome pro

### ISSUE THREAD

**Issue by AndreasJacobsen** [getgrav/grav#1962]
Hello! Terribly sorry if this seems like a silly question, but I could not figure out how to use FontAwesome Pro with grav.

I'm coming from pure HTML/CSS/JS (so this is my first CMS).

I see that Grav supports the free FontAwesome icons but I've bought the pro version and want to use some of the icons there. I've installed the shortcode core plugin but I'm unsure as to how to move on. I am also using Gantry 5 in my project. I wouldn't mind writing HTML to get the icons to display on the page if necessary. But as of now I'm unsure about where to even put the icons and how to call them.

**Comment by andrewd72** [comment]
As far as I know there is no remote cdn version to use with the pro version because you need a license. 
In the pro download look in the "web-fonts-with-css" folder and load the css files in your grav theme (partials/base.html.twig template most likely):
{% do assets.addCss('theme://css/fontawesome-all.min.css') %}
Copying the css files to your /user/themes/YOURTHEMENAME/css
Making sure the fonts are as referred to in the css file which is 
/user/themes/YOURTHEMENAME/webfonts

**Comment by AndreasJacobsen** [comment]
Would this be the base.html.twig in /user/plugins/gantry5/admin/templates/partials or in /user/plugins/admin/themes/grav/templates/partials ?And how do I call them after, can I write "pure" HTML and just call the class names?

**Comment by andrewd72** [comment]
Never tried a gantry based theme but there is a Global Page Settings, Assets section where you should be able to point it to the right file?
You should be able to call them in either twig or markdown in <i> tags.

**Comment by AndreasJacobsen** [comment]
It seems that the .css loads just fine, I can see it in chrome. But the webfonts return 404 

My setup if that helps 
```
➜  g5_helium git:(master) ✗ cd css; ls
fontawesome-all.min.css
➜  css git:(master) ✗ echo "examplepath from css file" 
examplepath from css file
➜  css git:(master) ✗ tail -n 1 ../webfonts/fa-solid-900.ttf 
window-alt
          window-closewindow-maximizewindow-minimizewindow-restorewindowon-signwrenchx-rayen-sign% 

```

So the file path should be good, yet chrome returns 404 on the path 
![image](https://user-images.githubusercontent.com/8527173/38205253-32dabb66-36a6-11e8-8dc5-7cf7aa1a3cc2.png)

**Comment by AndreasJacobsen** [comment]
I had to add the fonts to "/user/plugins/gantry5/assets". This is probably only relevant if you are using the Gantry 5 framework. Thank you for all the help!
