### ISSUE TITLE
Twig function `url` is incorrect for image thumbnail files

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav#1965]
Pretty sure this is a bug. I have a thumbnail file using the pattern `[image-name].[extension].thumb.[ext]` described in [Thumbnail Location item 1](https://learn.getgrav.org/content/media#thumbnail-location).

When I dump `[image].thumbnail('page').display('thumbnail').html` I get an `img` tag with the correct path to thumbnail file as `src` attribute.

However, when I ask for `[image].thumbnail('page').display('thumbnail').url`, I get the path to the image itself, not its thumbnail file.

Both of these expressions return expected results when a thumbnail file _is not_ provided.

Am I using the correct expression? If not, I think there's a bug.

**Comment by rhukster** [comment]
That does sound like a bug. I'll need to investigate when i get a chance.

**Comment by rhukster** [comment]
Hmm.. i can't replicate this:

```
Thumbnail Exists: {{ media['progress.jpg'].thumbnailExists() ? "yes" : "no" }}

Image: {{ media['progress.jpg'].display('thumbnail').html() }}

URL: {{ media['progress.jpg'].thumbnail('page').display('thumbnail').url() }}
```

Screenshot: https://trilby.d.pr/CCOx61

**Comment by arkhi** [comment]
I had a similar problem and clearing the cache solved it.

I have manually added (not via the admin plugin) the thumbnail for a video after loading the page; the thumbnail would only be recognized after the cache was cleared.
