### ISSUE TITLE
Suggestion: create a Laravel Valet driver

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav#1968]
Valet is pretty nice development tool but for now there is no driver compatible with Grav.

https://github.com/laravel/valet/issues/384

It could be nice to create one 😄 !!!

**Comment by rhukster** [comment]
If someone creates one and submits a valid PR, i would be open to merging it.

**Comment by martisj** [comment]
@jimblue what issue are you facing? It seems to work out of the box for me.

**Comment by jimblue** [comment]
Hey @rhukster @martisj !

Sorry it was my fault, I had a conflict with httpd process.

Grav is working out of the box with Valet !! ✨ ✨ ✨

**Comment by rhukster** [comment]
Maybe a write-up for the Getgrav.org blog???? Never used it myself :)

**Comment by jimblue** [comment]
Yep I could when having a bit more time !
