### ISSUE TITLE
Suggestion : The Phantom theme by HTML5 UP

### ISSUE THREAD

**Issue by PierreClementCazon** [getgrav/grav#1969]
Hi,

Congratulations for this light and powerful CMS.
I particularly appreciate this theme : https://html5up.net/phantom
It's perfect for a blog on Grav, would anyone be able to convert it to a Grav theme ?

Thanks in advance for your help !

**Comment by rhukster** [comment]
Theme looks nice, I'm sure someone could port that! I have too many repos I manage already (200+!)

**Comment by PierreClementCazon** [comment]
I hope so ! Do you know any themes available on Grav in the same style ?
Thank you for your responsiveness and for everything you do.

**Comment by michielStaes** [comment]
@PierreClementCazon you could check out themes at  https://getgrav.org/downloads/themes

**Comment by PierreClementCazon** [comment]
Thank you very much @michielStaes !

**Comment by michielStaes** [comment]
PR made @ **https://github.com/getgrav/grav/issues/1973**
Feedback welcome.

**Comment by rhukster** [comment]
it's been added to gpm, should show up soon.
