### ISSUE TITLE
Problem with 'config.system.twig.autoescape'

### ISSUE THREAD

**Issue by jyri78** [getgrav/grav#197]
When _config.system.twig.autoescape_ is set to **true** and JS/CSS pipeline(s) enabled, then Twig will escape real tags (link and script), so webpage will not work.

Output will then be like that:
```html
<!-- ... -->

  <link rel="icon" type="image/png" href="/user/themes/antimatter/images/favicon.png" />

  &lt;link href=&quot;/assets/bc2a54ebaffaa41c7543dc8fc5fd96ef.css?3eb35881&quot; type=&quot;text/css&quot; rel=&quot;stylesheet&quot; /&gt;

  &lt;script src=&quot;/assets/081b5986802a60c40305378d98e086c3.js?99a90959&quot; type=&quot;text/javascript&quot; &gt;&lt;/script&gt;

</head>

<!-- etc. -->
```

**Comment by rhukster** [comment]
There are many other cases where this happens. This is more an experimental/debug feature than anything else.  Grav currently does not support turning this off.
