### ISSUE TITLE
Make slug and menu location independant in GRAV cms

### ISSUE THREAD

**Issue by simohammedhttp** [getgrav/grav#1980]
Hi, 

Please bear with me, I don't know if I can post an issue here.

Is it possible to have a simple URL like http://example.com/page_slug and add the page to whatever position I want in the menu especially a child position?

The problem is that whenever I attach a page to a parent menu, I got many levels in the slug like: http://example.com/parent/page_slug.

**Comment by rhukster** [comment]
The best solution is to place it in the file structure where appropriate for the menu hierarchy, then change the route: https://learn.getgrav.org/content/headers#routes
