### ISSUE TITLE
[suggestion] add subresource integrity to webpack assets engine

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav#1984]
Hi there!

For better security when using CDN, it could be nice to add **[subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)** to webpack Grav assets engine.

Simplest way that would not break actual the assets engine:

Add two parameters to Grav assets method:

- integrity
- crossorigin

To be able to render out:

`<script src="https://example.com/example-framework.js"  integrity="sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC" crossorigin="anonymous"></script>`

Users could easily fill those new params from twig.

What's your input on this?

**Comment by jimblue** [comment]
I agree `the ability to arbitrarily pass attributes to addJs() function would be a better solution` as assets could have a different integrity hash.

I agree about revamp Assets class for this kind of features like this issue too #1893 .

Maybe a Milestone, or maybe a Project could be a good place to keep things organised about Grav2.0?

I would be happy to help organise issue on it it's usefull for Grav dev.

Good luck @ work and tks again for your amazing job on Grav. (1386 issues closed, that's crazy 💯 !!!!!)

**Comment by AkkuFresh** [comment]
This function would be very useful.

**Comment by rhukster** [comment]
This refactor was done as part of 1.6. It’s available on the current RC release.
