### ISSUE TITLE
Clearing custom image field 1 also clears custom image field 2

### ISSUE THREAD

**Issue by joshhartmann** [getgrav/grav#1989]
Hi all, 
When I edit my page and remove an image from a custom field then click save it seems to be clearing both custom fields. 
Is there and option I am missing? Any help would be greatly appreciated. 

Blueprint snippet
`            #
            # Cover image
            #
            header.custom.cover:
              type: file
              label: Main splash banner 1000x450px
              destination: 'self@/splash'
              multiple: false
              accept:
                - image/*
            #
            # about image
            #
            header.custom.ange:
              type: file
              label: Image for About section 300x350px
              destination: 'self@/about'
              multiple: false
              accept:
                - image/*
`
(formatting may be gross so I attached a file version)
[blueprint.txt](https://github.com/getgrav/grav/files/1936211/blueprint.txt)

**Comment by mahagr** [comment]
This has likely been fixed in Grav 1.6.
