### ISSUE TITLE
Twig_Error_Runtime when enable assets pipeline on subfolder installation

### ISSUE THREAD

**Issue by Seebz** [getgrav/grav#199]
Enabling pipeline of assets on a subfolder installation produces a `Twig_Error_Runtime` exception.

> An exception has been thrown during the rendering of a template ("preg_replace(): Unknown modifier 'X'") in "partials/base.html.twig" at line 36. 

The error came from the method `Assets::gatherLinks`, especially the code `preg_replace($this->base_url, '/', $link, 1)` where `$this->base_url` isn't quoted and become an invalid regular expression.

**Comment by rhukster** [comment]
Your PR has been merged.  Thanks!

**Comment by Seebz** [comment]
Thanks to you and your team for your great work.
