### ISSUE TITLE
the folder 03.pages is seen as  "Pages" file in Mac

### ISSUE THREAD

**Issue by beamaria** [getgrav/grav#1994]
I don't know if someone else has this problem, I tried an installation grav+gantry 5 in localhost (helium theme) the folder 03.pages is seen as  a file of "Pages"in Mac, therefore the icon is changed to that of this program and it's not possible to open the folder...
Any solution? Thanks!

**Comment by dimitrilongo** [comment]
not related to Grav, see https://github.com/getgrav/grav/issues/1521, i'v never find a solution to that specific Macos "issue"

**Comment by rhukster** [comment]
Yah, it's an OS level thing, can't fix it on our end.  Just don't use `XX.pages` as a folder.  You can use something else and specifically set `slug: pages` in the page itself.
