### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by jcdepth** [getgrav/grav#2003]
`0 - RecursiveDirectoryIterator::__construct(): Unable to find the wrapper "theme" - did you forget to enable it when you configured PHP?`

I started getting this error after installing a couple plugins, Admin Media Tools, Admin Media Replace, Admin Media Move, Admin Addon Media Sort. After removing the plugins, I'm still getting this error.

Restarting the PHP FPM service doesn't resolve the issue either.

I've attached a formatted version of the error log.

[Grav Cleaned Log.txt](https://github.com/getgrav/grav/files/1965903/Grav.Cleaned.Log.txt)

Any help would be greatly appreciated

**Comment by rhukster** [comment]
I 'think' this might be related to those admin tools you added as I've never seen this error before.  

Those are 3rd party plugins, and are untested by us.  you probably need to open a ticket on those particular plugins.
