### ISSUE TITLE
Plugins CSS and JS excluded from robots.txt

### ISSUE THREAD

**Issue by gmpreussner** [getgrav/grav#2006]
Some search engine crawlers, such as Google throw low severity warnings, because plug-in .css and .js files are excluded from _robots.txt_. I added the following to resolve the warnings:

```
Allow: /user/plugins/*.css$
Allow: /user/plugins/*.js$
```

**Comment by w00fz** [comment]
This would probably belong best in the learn documentation. I don't think it should be Grav Core providing this very specific and opinionated behavior.
It really is a theme developer choice very much driven by the context of the site.

**Comment by gmpreussner** [comment]
I don't have any strong opinions about this, and I haven't used Grav long enough to comment on the philosophical choices. That being said, I only use official Team Grav plug-ins at the moment, some of which ship with Grav out of the box. As a user, I would expect there not to be any issues. I think it should just work out of the box (like it does for pretty much everything else). I could see this being a user configurable option in the Admin panel for those who want to hide CSS and JS from web crawlers for whatever reason.

**Comment by w00fz** [comment]
What are the warnings you are seeing? Also how are you checking these?

**Comment by gmpreussner** [comment]
In my particular case, search engines fail to fetch the following files:

```
/user/plugins/form/assets/form-styles.css
/user/plugins/highlight/css/github.css
/user/plugins/login/css/login.css
/user/plugins/highlight/js/highlight.pack.js
```

Regardless of whether or not they should be trying to fetch these in the first place, it seems to me a bit of an inconsistency in Grav, since CSS and JS files in Themes are not excluded by default.

**Comment by w00fz** [comment]
That's fair @gmpreussner , I personally wasn't even aware of these warnings for assets.

**Comment by mahagr** [comment]
Just to add, there are also compiled css files in `user/data/gantry5` which cause similar issues with Google:

https://github.com/gantry/gantry5/issues/2020

**Comment by rhukster** [comment]
Fixed by https://github.com/getgrav/grav/commit/bc22c8d2b1efad6f28608aa937e9dd0485eac6d7
