### ISSUE TITLE
Ampersand operator not working in Twig

### ISSUE THREAD

**Issue by aminur** [getgrav/grav#2012]
The `and` operator works in Twig for comparison but the `&&` operator causes an error for Grav.

If this is by design, please explain. Otherwise, it poses an unnecessary risk of breakage for someone porting functional Twig templates to Grav.

![ampersand operator broken](https://user-images.githubusercontent.com/3481366/39946980-2aa8544a-5568-11e8-9001-271a1a207aa1.png)

Many thanks!

**Comment by rhukster** [comment]
Twig doesn't use the same operators as PHP, you need to use `and` and `or`

https://twig.symfony.com/doc/2.x/tags/if.html

**Comment by aminur** [comment]
Apologies for the mistake.

I think this highlights why one should not simply trust the highest ranking search result. Just based on thi URL I assumed their version of Twig was authentic. I didn't see a mention of it being a custom syntax.

[Branch Twig](https://www.branchcms.com/learn/docs/developer/twig/operators)

I will stick to Symfony documentation.

Thanks very much!
