### ISSUE TITLE
Session Cookie only for admin login?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#2013]
Seems at the moment it's not possible to set the grav session cookie only for my custon admin login page?
So what's the use of grav setting a session cookie if I don't go to admin login?
And what's the use of system.session split setting in system.yaml?

So right now if I don't want grav cookie I can't use admin plugin.

**Comment by mahagr** [comment]
@axel-rank There will be a new setting in the admin to disable sessions in the site while keeping them in admin plugin.
