### ISSUE TITLE
Dashboard issue after updating Grav and plugins

### ISSUE THREAD

**Issue by Ikkache27** [getgrav/grav#2015]
Hi,
Since I've updated grav & plugins in latest versions, i can't use the dashbord, it seems like this :

![grav dashboard issue](https://user-images.githubusercontent.com/29124164/39967978-db800d86-56c5-11e8-8592-c14e77afd307.PNG)

**Comment by w00fz** [comment]
Can you open the browser inspector and see if you get any JS error?

**Comment by Ikkache27** [comment]
Hi w00fz, thank's for your reply ...
There is no error 
![inspector](https://user-images.githubusercontent.com/29124164/39970775-c0890592-56f1-11e8-8ba0-34e7b97f55db.PNG)

**Comment by Ikkache27** [comment]
Please can anyone help me about this issue, 
Thank's in advance

**Comment by Ikkache27** [comment]
@w00fz ,  there is an error : 

![eror json](https://user-images.githubusercontent.com/29124164/40001971-a42f240a-578f-11e8-85d3-9b52af393d29.PNG)

**Comment by w00fz** [comment]
@Ikkache27 check the network response and see if there's any error in there.

That in your screenshot is not a javascript error.

**Comment by Ikkache27** [comment]
@w00fz , @hellboy1975 ;
the same thing for me

**Comment by w00fz** [comment]
If you guys could DM me (in Slack)  access to admin so I can look at it, that would help. I’m not able to reproduce this issue.

**Comment by Blazeflack** [comment]
This can also be caused by adblockers and the browser plugin Privacy Badger from eff.org

**Comment by hellboy1975** [comment]
Still stuck with this :(
Tried recreating users with no success.  @w00fz are you still keen to take a look at this?

**Comment by w00fz** [comment]
I am, but nobody pinged me on slack. :)

I do need the access in order to inspect the issue. I simply can’t reproduce this on my environment.

https://getgrav.org/slack

**Comment by tremel** [comment]
Same issue on an instance of mine.
Had set jquery in `system.yaml` to 3.x. Errors told after update to 1.4.6, that jquery was not found.

Changed line from `jquery: 'system://assets/jquery/jquery-3.3.1.min.js'` to `jquery: 'system://assets/jquery/jquery-3.x.min.js'` and it is working.

**Comment by hellboy1975** [comment]
@tremel that didn't do much for me unfortunately.  Mine was actually `jquery: 'system://assets/jquery/jquery-2.x.min.js'`.  I tried `jquery: 'system://assets/jquery/jquery-3.x.min.js'` but it made no difference.  Was there any other steps you took?

**Comment by tremel** [comment]
@hellboy1975 No other steps.

**Comment by hellboy1975** [comment]
Finally sorted this out by just manually updating the admin plugins.
