### ISSUE TITLE
Twig support in frontmatter broken

### ISSUE THREAD

**Issue by ricardo118** [getgrav/grav#2016]
As per our previous conversation @rhukster, Twig support in frontmatter must have been broken by a previous update.

Currently the following code:

```
---
area_name: 'South London'
new_var: '{{ site.title }}'
---
{{ site.title }}
```

The `page.content` reports the correct `site.title` however, `page.header.new_var` does not process the twig.

**Comment by rhukster** [comment]
just tested with:

```
---
area_name: 'South London'
new_var: '{{ site.title }}'
process:
    twig: true
---

{{ site.title }}

{{ page.header.new_var }}
```
both output the title just fine.

Check to make sure you have `page.frontmatter.process_twig: true` in your system settings. Best way is to turn on debugger and look there:

<img width="618" alt="screen shot on 2018-05-20 at 11_55_45" src="https://user-images.githubusercontent.com/1084697/40281958-d69894c8-5c24-11e8-8b66-ac86867c7b35.png">
