### ISSUE TITLE
Server Error Unexpected character

### ISSUE THREAD

**Issue by motherfacker** [getgrav/grav#2017]
I have a problem: [screenshot](http://joxi.ru/zAN9RGQFlQkvM2)
log:
`[2018-05-14 16:32:14] grav.CRITICAL: Unexpected character "'". - Trace: #0 /home/httpd/vhosts/oftbook.cf/httpdocs/vendor/twig/twig/lib/Twig/Lexer.php(216): Twig_Lexer->lexExpression() #1 /home/httpd/vhosts/oftbook.cf/httpdocs/vendor/twig/twig/lib/Twig/Lexer.php(122): Twig_Lexer->lexBlock() #2 /home/httpd/vhosts/oftbook.cf/httpdocs/vendor/twig/twig/lib/Twig/Environment.php(677): Twig_Lexer->tokenize(Object(Twig_Source)) #3 /home/httpd/vhosts/oftbook.cf/httpdocs/vendor/twig/twig/lib/Twig/Environment.php(774): Twig_Environment->tokenize(Object(Twig_Source)) #4 /home/httpd/vhosts/oftbook.cf/httpdocs/vendor/twig/twig/lib/Twig/Environment.php(452): Twig_Environment->compileSource(Object(Twig_Source)) #5 /home/httpd/vhosts/oftbook.cf/httpdocs/vendor/twig/twig/lib/Twig/Template.php(366): Twig_Environment->loadTemplate('partials/base.h...', NULL) #6 /home/httpd/vhosts/oftbook.cf/httpdocs/cache/twig/08/08afbb43c0405539c4b0cfa0024c165641a751a655fdb27a06a44bafae571c8a.php(11): Twig_Template->loadTemplate('partials/base.h...', 'docs.html.twig', 1) #7 /home/httpd/vhosts/oftbook.cf/httpdocs/vendor/twig/twig/lib/Twig/Environment.php(487): __TwigTemplate_c76c10a4b34e7799dd2be04c8741ada39e91cf53cf53364831185f37d9779f71->__construct(Object(Grav\Common\Twig\TwigEnvironment)) #8 /home/httpd/vhosts/oftbook.cf/httpdocs/vendor/twig/twig/lib/Twig/Environment.php(363): Twig_Environment->loadTemplate('docs.html.twig') #9 /home/httpd/vhosts/oftbook.cf/httpdocs/system/src/Grav/Common/Twig/Twig.php(349): Twig_Environment->render('docs.html.twig', Array) #10 /home/httpd/vhosts/oftbook.cf/httpdocs/system/src/Grav/Common/Service/OutputServiceProvider.php(27): Grav\Common\Twig\Twig->processSite('html') #11 /home/httpd/vhosts/oftbook.cf/httpdocs/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #12 /home/httpd/vhosts/oftbook.cf/httpdocs/system/src/Grav/Common/Processors/RenderProcessor.php(19): Pimple\Container->offsetGet('output') #13 /home/httpd/vhosts/oftbook.cf/httpdocs/system/src/Grav/Common/Grav.php(132): Grav\Common\Processors\RenderProcessor->process() #14 /home/httpd/vhosts/oftbook.cf/httpdocs/system/src/Grav/Common/Grav.php(374): Grav\Common\Grav->Grav\Common\{closure}() #15 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure)) #16 /home/httpd/vhosts/oftbook.cf/httpdocs/system/src/Grav/Common/Grav.php(350): call_user_func_array(Object(Closure), Array) #17 /home/httpd/vhosts/oftbook.cf/httpdocs/system/src/Grav/Common/Grav.php(133): Grav\Common\Grav->__call('measureTime', Array) #18 /home/httpd/vhosts/oftbook.cf/httpdocs/system/src/Grav/Common/Grav.php(133): Grav\Common\Grav->measureTime('render', 'Render', Object(Closure)) #19 /home/httpd/vhosts/oftbook.cf/httpdocs/index.php(52): Grav\Common\Grav->process() #20 {main} [] [] `
how do fix it?
help me pls.
Thanks
p.s: it's happen after using plugin [Reeding time](https://github.com/getgrav/grav-plugin-readingtime)
i'm add {{ page.content|readingtime }} to themes/learn2/templates/partials/page.html and base.html in the sam time and after that it's happens.

**Comment by rhukster** [comment]
Seems you have an unexpected extra `'` (single quote) in a Twig template.  Unfortunately Twig is not very good at providing the location of the template that caused it :(
