### ISSUE TITLE
gpm uninstall error

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#202]
I tried to uninstall different plugins with gpm and get the message: ‘can’t delete non-existing folder'.
All plugins were installed with gpm in user/plugins folder.

OS is Free BSD 10.0
Error message is:
Preparing to uninstall Breadcrumbs [v1.3.0]
|- Checking destination… ok
|- Uninstalling package…
[RuntimeException]
Cannot delete non-existing folder.

**Comment by Frucht** [comment]
I have the same problem and I get an error that eval could not be found on windows 8.

**Comment by aradianoff** [comment]
Me too. Ubuntu14.04. All packages installed through gpm.
``` 
Preparing to uninstall MathJax [v1.2.0]
  |- Checking destination...  ok
  |- Uninstalling package...  
                                  
  [RuntimeException]                  
  Cannot delete non-existing folder.  
                                     
uninstall [-y|--all-yes] package1 ... [packageN]

```
