### ISSUE TITLE
How to add custom fields for all page template without creating individual blueprints?

### ISSUE THREAD

**Issue by 5minutesturkish** [getgrav/grav#2023]
I have several types of pages with unique blueprints but i need to create custom fields which will work on all types of pages. How can I do that?

**Comment by rhukster** [comment]
You can create a new base blueprint that extends default, then extend that new base blueprint in your custom pages.

Or you can create a blueprint 'snippet' and `include@` it into other blueprints.  See `Quark` them for an example of this later approach.
