### ISSUE TITLE
MD Target and Class Params Mixed Together

### ISSUE THREAD

**Issue by peteger** [getgrav/grav#2024]
Hi there,

just found a small issue with generated links from MD.

Using following MD syntax:
`[Link](http://test.com?classes=button?target=_blank)`

Renders following HTML:
`<a href="http://test.com" class="button?target=_blank">Link</a>`

Similar thing happens when you swap both parameters:

MD:
`[Link](http://test.com?target=_blank?classes=button)`
HTML:
`<a href="http://test.com" target="_blank?classes=button">Link</a>`

Thanks!
Petr

**Comment by andrewd72** [comment]
class not classes? And you can't use the "?" twice afaik.
Try:
[Link](http://test.com?class=button&target=_blank)

**Comment by peteger** [comment]
Thanks Andy, that works!

Cheers,
Petr
