### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by hexplor** [getgrav/grav#2028]
Hello :)
I would like to add simple plugin for displaying latest twitter feeds on grav pages. Currently very simple but planning to add some more features :) 
https://github.com/hexplor/grav-plugin-latest-tweets

**Comment by rhukster** [comment]
WTG @hexplor :) 👍

**Comment by w00fz** [comment]
nice!

**Comment by hexplor** [comment]
Will you add it to repo @rhukster ?

**Comment by rhukster** [comment]
Added now, should get picked up in 1 hr.
