### ISSUE TITLE
@Login Screen: buttons overlapping

### ISSUE THREAD

**Issue by ponderboy** [getgrav/grav#2029]
This is just a little CSS thing I guess. But it doesn't look right when the buttons overlap:

![screenshot_2018-05-24 grav admin login klangumfang buro fur medien und kultur](https://user-images.githubusercontent.com/5340556/40490533-0d598c02-5f6c-11e8-9fbc-909fe5f2c597.png)

**Comment by rhukster** [comment]
little but fixed for next release

**Comment by ponderboy** [comment]
Sorry, I know this one is closed, but the buttons are still very tight together. Basically just on top of each other. And the main problem I see is a usability one, because intuitively I always tend to click on the top button. Which is the forgot password button. Is this only me?
