### ISSUE TITLE
Supporting other date formats

### ISSUE THREAD

**Issue by bdillahu** [getgrav/grav#203]
Right now dates are parsed based on delimiter ("/" for American and "-" for European) which has month/day swapped around.

There have been needs for at least the "ISO" format of YYYY-MM-DD HH:MM:SS http://getgrav.org/forum#!/theme-development:international-yaml-date-fie

Some ability to make a site-wide (with document level override?) config for what the expected input date is would be handy.

I think the php library already supports some of this, reading here:

http://php.net/manual/en/datetime.formats.date.php

**Comment by bdillahu** [comment]
Playing some more, I'm not sure this is needed... I find that it parses correctly if the date field is enclosed by double-quotes (") - I had some entries with and some without, which was throwing me.

**Comment by rhukster** [comment]
good to know. closing this then.

**Comment by robsonsobral** [comment]
Hi! Good morning! I'm still studying Grav and when I read about the date, I thought that I should warn you.

I'm sorry for bring more issues here, but I think this can cause issues. Here, in Brazil, the used date format is `dd/mm/yyyy`!

I think it's better/safer to use [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) by default.

Thanks.

**Comment by flaviocopes** [comment]
@robsonsobral when adding dates manually (not using the Admin plugin) the format described here http://learn.getgrav.org/content/headers#date allows Grav to understand how it should interpret the date.

Displaying the date on the site is another topic, and it's set in the System configuration.

If you believe there is a problem I don't see, please open a new issue.
