### ISSUE TITLE
Weird routing with custom_base_url, relative urls and nested pages

### ISSUE THREAD

**Issue by Blazeflack** [getgrav/grav#2030]
Let me start by describing my setup.

I have grav installed as follows: `http://domain.xyz/grav-folder/`
I use a custom_base_url: `http://domain.xyz/grav-folder/`
I use relative urls for base_url

The issue I have started noticing after the latest round of updates:
When I am on a nested page such as `http://domain.xyz/grav-folder/some-folder/some-page/` then a relative link to another nested page will result in an incorrect routing.

Say I wanted to link to `http://domain.xyz/grav-folder/some-other-folder/some-other-page/` from the first nested page.

Doing that with a relative url of `some-other-folder/some-other-page` would result in the following routing:
`http://domain.xyz/grav-folder/some-folder/some-other-folder/some-other-page`.

Expected routing: `http://domain.xyz/grav-folder/some-other-folder/some-other-page`
Actual routing: `http://domain.xyz/grav-folder/some-folder/some-other-folder/some-other-page`

I hope I gave enough information for you to track this down. If not then please let me know.

Thank you.

**Comment by rhukster** [comment]
I'm confused, your custom_base is the same as your regular URL? Why are you using a custom base?

**Comment by Blazeflack** [comment]
I started using it because relative links in grav would use the root folder as a starting point, so a relative link of "some-folder/some-page" would result in the following URL: `http://domain.xyz/some-folder/some-page`

This leaves out the "grav-folder" which is the real root folder for Grab.

Up until recently it all worked as expected for me, but at some point in the last 4 or 5 updates something changed.

I'm not sure exactly when it changed, as a lot of updates happened in a short period of time.

**Comment by rhukster** [comment]
relative links will work fine if you use markdown style links as Grav automatically converts these.  In Twig you can use the `url()` function so:

```
{{ url('/some/relative/link') }}
```

will automatically take into account the current base path, and provide the correct link.

**Comment by Blazeflack** [comment]
I apologize, you are completely correct. It turns out it is an issue with Gantry apparently.

Please see my following test site: http://krakengroup.org/debug/folder-1/one

**Setup:**
Grav install folder: /debug/
Absolute URLs: no
Custom base URL: no

The links in the main content area is created through the Grav pages.
The links in the footer are created through Gantry.

The text of the links shows their href value (having a / at the beginning or not).

**Results:**
Links in Grav pages which start with a slash (/) will correctly use the Grav install folder as base URL.
Links in Gantry elements which start with a slash (/) will **not** use the Grav install folder as base URL, but rather the root domain (krakengroup.org in this case).

In order for links to work in Gantry you need to omit the beginning slash of a relative URL. I'm not sure if this is intended behaviour or a bug. But it seems weird that it doesn't behave the same way as Grav.

In any case I should probably post this in the Gantry repository just to make sure.

**Comment by rhukster** [comment]
@Matias can you take a look at this?

**Comment by mahagr** [comment]
@Blazeflack I need some example twig code for this, as I'm not sure how you are creating the links.

**Comment by Blazeflack** [comment]
@mahagr I created the links in the footer through the Admin plugin, using Gantry 5.

I used a custom HTML particle and regular a tags:

```
<a href="/folder-1/one"></a>
<a href="folder-1/one"></a>
```
etc.

The links in the middle of the page was also done through the admin panel, by modifying the content of the specific pages in the Pages menu.

If you still need some twig then I will try to come up with something.

**Comment by mahagr** [comment]
@Blazeflack I'm seeing particle to output like this when Grav is running from /:

```
<a href="/folder-1/one">/folder-1/one</a>
<a href="http://grav.local/folder-1/one">folder-1/one</a>
<a href="/folder-2/two">/folder-2/two</a>
<a href="http://grav.local/folder-2/two">folder-2/two</a>
```

... and the same when Grav is running from /sub:

```
<a href="/folder-1/one">/folder-1/one</a>
<a href="http://grav.local/sub/folder-1/one">folder-1/one</a>
<a href="/folder-2/two">/folder-2/two</a>
<a href="http://grav.local/sub/folder-2/two">folder-2/two</a>
```

Both look good to me..?

**Comment by Blazeflack** [comment]
@mahagr Please try it out in my debug installation here: http://krakengroup.org/debug/admin

User: mahagr
Pass: Mahagr12

When you look at http://krakengroup.org/debug/folder-1/one you can clearly see that there is a difference between using a starting forward-slash and not using it.

**Comment by mahagr** [comment]
In Grav the following markdown was used:

```md
[/folder-2/two](/folder-2/two)
[folder-2/two](folder-2/two)
```

They are rendered like this:

```html
<p><a href="/debug/folder-2/two">/folder-2/two</a></p>
<p><a href="/debug/folder-1/one/folder-2/two">folder-2/two</a></p>
```

I cannot see any issues on this either. Markdown is supposed to display links inside the page where Gantry is a theme and operates in another level.

I cannot see any issues

**Comment by Blazeflack** [comment]
@mahagr Did you visit my test installation from my previous post? There you can clearly see that using a beginning slash on Grav pages is required if you are in a subfolder and want to link to another page in another subfolder.

When you generate links through a Gantry particle then the opposite is true, and you need to avoid using a beginning slash.

**Comment by mahagr** [comment]
Yup, this is because of you're using markdown inside Grav page -- page knows in where it is located. In theme everything is shared (and cached) and there's no way to know the current page you're in -- and you're also writing plain HTML, not asking Grav/Gantry to route your path.

I cannot see any issues in this -- the scope is different (page vs decoration) and the language is different (markdown vs plain html).

**Comment by Blazeflack** [comment]
Alright, that actually makes sense. Thanks for the explanation.

I guess there isn't a way to setup Gantry particles on a nested installation (with working links) and then be able to launch the site later on in the root of a domain.

Since the beginning slash is required, the links in Gantry particles will start from the root domain instead of the nested folder where it is installed.

**Comment by mahagr** [comment]
There is, but you need to do some twig calls to get the proper routes from Grav. For that you need to use `{{ url('/path/from/root') }}` for media files and Grav router for routing the pages.

**Comment by Blazeflack** [comment]
While that works in the Custom HTML particle, I'm not sure that other particles accept twig code in a dedicated "l

**Comment by mahagr** [comment]
Other particles usually accept streams, like `image://myimage.jpg` as their input.

**Comment by Blazeflack** [comment]
Is there a stream for pages? :D

**Comment by Blazeflack** [comment]
I don't know if grav.page can be used in particle link fields but I'll give it a shot.

Thanks again.
