### ISSUE TITLE
Request to takeover / rename plugin "piwik"

### ISSUE THREAD

**Issue by geschke** [getgrav/grav#2032]
Hello!

Last year I had asked to takeover the piwik plugin - I'm sorry for the delay, the original author had agreed to the takeover request, but gave me access to its Github repository, so a complete takeover was not necessary. See the history in #1372 . 

But before some months, the Piwik project was renamed to "Matomo". So my question is - what is the best way to rename this plugin?
I would like to add some missing features, too. There are some feature requests, but at first I would change its name to "Matomo" or "Matomo (formerly known as Piwik)" or similar. 

How can I do this? Or should I fork the plugin repository and you could simply replace the old piwik plugin with the renamed project?

Thanks in advance & Kind regards,
   Ralf

**Comment by rhukster** [comment]
Hmm.. not run into this situation before.

If you are taking over the project, you should definitely have repo under your full control.  So fork it or get the original author to transfer it to your github account.

Regarding the rename. It's not trivial if you want to continue to support prior piwiki users.  I can easily add another entry in GPM for your new `matomo` name, but people with piwiki will not see any updates... Maybe you can update piwiki and place a banner in the admin or something to say to now use matomo? SOmething like that?

**Comment by OleVik** [comment]
Would it not conform better to community-reliance to simple give the Piwik plugin a last update, and then close the repo with a big note saying: "Piwik is now Matomo, see this repository for the continuation of this plugin. The Piwik-plugin will not be further updated."? That way, users of the Piwik-plugin are not prevented from using it, nor are they forced into Matomo (I still use Piwik, the upgrade hasn't been necessary yet). People upgrading to Matomo can be directed to that repository, and there is no need for transitory-fallback between them.

A banner in Admin feels intrusive to me, especially when someone has not upgraded to Matomo. In the new repository, you should definitely include a note saying "Matomo (formerly known as Piwik)", and link back to the Piwik-plugin to avoid confusion (that of which Matomo/Piwik themselves have made plenty of).

**Comment by mayailkour** [comment]
Any updates on this issue?
