### ISSUE TITLE
getgrav.org website discobot issue

### ISSUE THREAD

**Issue by Eggeriley** [getgrav/grav#2037]
I am finding that when I try to do the dialogue with discobot to sign up for the forum that copying the code does not work. When copying the code and links, it pastes in to the area fine, everything looks good on the left and the right, but I cannot enter the message because an error message pops up.

"post can't be empty"

I am attaching a screenshot below. 
<img width="1440" alt="screen shot 2018-05-29 at 9 57 09 am" src="https://user-images.githubusercontent.com/19999634/40673474-be74a31a-6326-11e8-9e2f-de71582cc945.png">

Because of this issue I don't believe that my posts are seen yet on the forum. What can I do to move forward?

**Comment by rhukster** [comment]
I think you can't have 'just' a quote, probalby a setting somewhere buried deep in the bowles of Discourse.  Just add some text before or after your quote.
