### ISSUE TITLE
Question: Rename default template folders 'modular' & 'partials'

### ISSUE THREAD

**Issue by dannystarkDE** [getgrav/grav#2039]
Is it possible to rename the default folders 'partials' and 'modular'?

**Comment by rhukster** [comment]
Simple answer to that is yes and no :)

`partials` is really just a recommend standard for compatibility with other plugins and themes.  Not required anywhere. So can change this.

`modular` is a specific folder that Grav looks to for modular page twig templates.. so can't change this.

**Comment by dannystarkDE** [comment]
Ah okay thanks :)
