### ISSUE TITLE
page.find() + filter by tags?

### ISSUE THREAD

**Issue by shibekin69** [getgrav/grav#204]
Hi!

Sorry for the bother but... noob question ahead. 

Is there a way to further filter a page.find() by tags? I'm using this code snippet found in the Content -> Pages section of the learn.getgrav.org site:

    {% for p in page.find('/projects').children if p != page %}
    <li><a href="{{p.url}}">{{ p.title }}</a></li>
    {% endfor %}
    </ul>

So I'd like to be able to filter only certain pages in /project containing particular tags. Is there something like the following?

    page.find('/projects').children.findTags({'tag':['ace']}); 

I'm also trying to see how this taxonomy.findTaxonomy() function works, but hasn't been working for me so far:

    {% for post in taxonomy.findTaxonomy({'tag':['ace']}) %}

Do I have to make sure that the page header contains the following?

    taxonomy:
      tag: ['ace']

And that the 'tag' is in the site.yaml's taxonomy declaration part? Anything else I'm missing?

Thanks!

**Comment by rhukster** [comment]
Your definitely on the right track.  I would just use the `findTaxonomy()` approach and ensure the pages you want to search for have the appropriate tags.  So something like:

```
{% for page in taxonomy.findTaxonomy({'tag':'foo','category':'project'}) %}
```

Then in your page use the following taxonomy:

```
taxonomy:
  category: project
  tag: [foo, bar]
```

And yes, you will need to add both `category` and `tag` to your site.yaml's `taxonomies`

**Comment by shibekin69** [comment]
Hi!
Hm. It doesn't return anything for me (blank result). Any idea how I can go about debugging this?

**Comment by rhukster** [comment]
Ensure you have the debugger turned on then you can start by dumping some values and seeing what you get back:

```
{{ dump(taxonomy.findTaxonomy({'tag':'foo'}) }}
```

Then look in the messages tab of the debugger to see the collection found.

Don't forget that the default operator for findTaxonomy is *and* so the example above would find pages where tag=foo AND category=project.

**Comment by shibekin69** [comment]
hmm. Does it matter where the pages are located? I'm trying to show pages that structured this way: 

    /user/pages/blog/blog-story-01/blog-item.md

**Comment by shibekin69** [comment]
Hi,

Ok I figured it out. It was the publish: false header setting I had in there. When I used page.find('/dir'), it seemed to ignore that setting and showed me the item anyway. But when I used taxonomy.findTaxonomy({'key':'value'}), it took that into consideration and didn't show me anything.

**Comment by rhukster** [comment]
cool.
