### ISSUE TITLE
Odd redirecting issue when not logged in

### ISSUE THREAD

**Issue by enovision** [getgrav/grav#2047]
For my plugin "frontend-edit-button" I connect a button on the page with a link that has an URL like this: 
```
https://notes.enovision.net/dashboard/pages/assorti/upgrade-vscode-in-linux
```
note: I have changed `admin` to `dashboard`, but that is not the problem here.

This is opened in a new tab. When you are **not** logged in, it will show the login dialog from GRAV automatically with the URL correctly shown in the locator of the browser with the login dialog. But when I log in now, the URL changes to:
```
https://notes.enovision.net/dashboard/assorti/upgrade-vscode-in-linux
```
so, without the `pages` in between.

* When I paste the correct URL in the URL locator of my browser it works correctly.
* When I go to the other tab and press the button of my plugin in the browser again (now I am logged in the other tab), I works also correct.

### expected ###
That the URL was not changed during the login procedure and removed the `pages` part from the URL.

This used to work in earlier versions of GRAV.

**Comment by rhukster** [comment]
Just fixed this with this ssue: https://github.com/getgrav/grav-plugin-admin/issues/1456
