### ISSUE TITLE
Why keeping JQuery v2 by default ?

### ISSUE THREAD

**Issue by jodumont** [getgrav/grav#2049]
Hi;

I saw under `system/assets/jquery/`
`jquery v2` and `jquery v3` are both available

I wonder why v3 is not by default here : [system/config/system.yaml](https://github.com/getgrav/grav/blob/develop/system/config/system.yaml#L109)

Because this change will keep all grav user out of these [vulnerabilities](https://snyk.io/vuln/npm:jquery?lh@2.2.4)

**Comment by rhukster** [comment]
JQuery2 is kept as default for compatibility reasons.  Changing to v3 as a default could impact people's sites when updating.  

FYI We'll probably drop jquery from the core completely in Grav v2.0
