### ISSUE TITLE
Trying to use Lazy Load Plugin but can't initialize?

### ISSUE THREAD

**Issue by shibekin69** [getgrav/grav#205]
Hi,

I'm trying to include this plugin in my site:

http://cdnjs.com/libraries/unveil

So I have a custom.js file that I'm loading after this, looking like the following inside my home.html.twig file:

    {% do assets.add('https://cdnjs.cloudflare.com/ajax/libs/unveil/1.3.0/jquery.unveil.min.js', 102) %}
    {% do assets.add('theme://js/custom.js', 101) %}

Custom.js looks like this:

$(document).ready(function() {
	$('img').unveil();
});

So I'm simply trying to initialize the loaded unveil js file, but I get an error that the unveil() function doesn't exist. How do I go about using js libraries with Grav (hopefully without having to resort to using Grav Plugins)?

**Comment by rhukster** [comment]
You can do this, but you need to do it in the JS block, so it gets processed properly.  Also it does require the theme has provided these javascript block.  For example in Antimatter, if you look in the `partials/base.html.twig` you will see there is a `{% block javascripts %}` defined, then in your template, as long as your extending this `partials/base.html.twig` you can do something like:

```
{% block javascripts %}
    {% do assets.add('https://cdnjs.cloudflare.com/ajax/libs/unveil/1.3.0/jquery.unveil.min.js', 102) %}
    {% do assets.add('theme://js/custom.js', 101) %}
    {{ parent() }}
{% endblock %}
```

Creating a custom plugin to do this is also a valid option and not very hard.
