### ISSUE TITLE
[add-resource] New Theme Bootstrap Blog

### ISSUE THREAD

**Issue by ayozehd** [getgrav/grav#2050]
Hi team!

I've uploaded just now my new theme. I use Boostrap 4 and FontAwesome 5, and it's ready to extend too with SCSS. I tried to accomplish all requirements in your guide, so tell me if anything is wrong to fix it.

There is no demo content in theme to avoid increase weight with images, but I got a demo under my website: [bootstrap-blog.ayozehd.com](http://bootstrap-blog.ayozehd.com/).

I think there are some interesting features for you like some fields in showcase to customize image actions, or a layout system in portfolio (all it's very simple indeed).

Checkout theme repo: [ayozehd/grav-theme-bootstrap-blog](https://github.com/ayozehd/grav-theme-bootstrap-blog)

**Comment by ayozehd** [comment]
@rhukster flag as theme please... Any update?

**Comment by rhukster** [comment]
Sorry been on holiday, and am still without good internet.  Will get to this soon, promise.

**Comment by rhukster** [comment]
actually managed to add this now.. should show up in 30 mins or so.

**Comment by ayozehd** [comment]
Thank you so much! Hope you had great holidays ;)
