### ISSUE TITLE
image src links

### ISSUE THREAD

**Issue by imonly** [getgrav/grav#2051]
- media['preview.jpg'].url = /images/1/8/e/1/d/blabla-preview.jpeg
How to get the real image path == /user/pages/home/preview.jpg ?

- Can I get a reduced image of a particular page, knowing only its URL? Yes, this is not a good idea - but there is a task to make bookmarks visual, knowing only page URLs

For page route **/home/**
/api/image?src=/home/preview.jpg&cropResize=300,300
Help please realize this, m?

**Comment by rhukster** [comment]
I'm not fully understanding the question.  

If you don't peform a media operation, you should see the full path (in the `user/pages/...` folder) for the image with simply `.url` or `.html`.  If you do something like `.cropResize(300,300)`, it will resize the image and cache that in `images/...` folder.
