### ISSUE TITLE
Grav crashes on IIS (Windows) with open_basedir in effect

### ISSUE THREAD

**Issue by lordrhodos** [getgrav/grav#2053]
On a recent project I came across the following issue with a provider using IIS on Windows and an active `open_basedir` setting related to the usage of [`GlobIterator`](https://secure.php.net/manual/en/class.globiterator.php).

> UnexpectedValueException
GlobIterator::__construct(): open_basedir restriction in effect. File(D:/inetpub/vhosts/ingenieurbau-bohn.de/httpdocs/user/pages/*.md) is not within the allowed path(s): (D:/inetpub/vhosts/ingenieurbau-bohn.de/httpdocs;D:/inetpub/vhosts/ingenieurbau-bohn.de/httpdocs;D:/inetpub/vhosts/ingenieurbau-bohn.de/httpdocs/ssl/cache;C:\Windows\Temp;)

I think this is caused by [this PHP issues](https://bugs.php.net/bug.php?id=65069) which never got resolved. 

We have tested the issue with PHP 5.6.x, 7.1.x and 7.2.x all with the same result.

You can easily reproduce the issue if you can get hands on an IIS with the `open_basedir` set. I have attached two files to recreate the issue which you should place inside the path of the `open_basdir` setting:

**globiterator.php**
```
<?php

try {
    /** @var SplFileInfo $fileInfo */
    foreach (new GlobIterator(__DIR__ . DIRECTORY_SEPARATOR . '*') as $fileInfo) {
        echo $fileInfo->getPathname()  . PHP_EOL;
    }
} catch (UnexpectedValueException $exception) {
    echo $exception->getMessage();
}
```

**globl**
```
<?php

foreach (glob(__DIR__ . DIRECTORY_SEPARATOR . '*') as $file) {
    echo $file . PHP_EOL;
}
```

The GlobIterator is used in [Common/Page/Pages.php:1011](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Pages.php#L1011) and in the [Grav Problems Plugin](https://github.com/getgrav/grav-plugin-problems/blob/develop/problems.php#L55) with the latter actually being the first Exception to be thrown (which can be skipped with disabling the problems plugin).

I have used `glob()` to patch the code for my project for now, but as hosting on IIS in conjunction with `open_basedir` setting mare be a rare case I just wanted to get some feedback before providing a PR.

[globiterator.zip](https://github.com/getgrav/grav/files/2090040/globiterator.zip)

**Comment by rhukster** [comment]
Hmm.. it's my understanding that the SPL iterators are far superior to the older glob() functions.  In regards to performance especially. If you could create a PR with some specific detection and fallback to use the glob function for this IIS scenario, I would be interested in merging that.

**Comment by mahagr** [comment]
To me this almost looks like misconfiguration of PHP. The weird thing is that...

```
D:/inetpub/vhosts/ingenieurbau-bohn.de/httpdocs/user/pages/*.md
D:/inetpub/vhosts/ingenieurbau-bohn.de/httpdocs
D:/inetpub/vhosts/ingenieurbau-bohn.de/httpdocs
```

... by looking into those three paths, the first path is inside of the allowed paths. But why is the same path two times in the configuration?

**Comment by lordrhodos** [comment]
@rhukster totally agree. I am happy to come up with a PR for this special case.

@mahagr you are right, configuration includes unnecessary paths. But I guess this should not have any impact on the issue? I will contact the provider to fix this and update the error message once I got feedback.

**Comment by mahagr** [comment]
Maybe just replace `GlobIterator` with FilesystemIterator with a proper filtering... As it seems to be buggy in Windows.

**Comment by mahagr** [comment]
I ended up rewriting the logic on fetching markdown files and folders in `Pages::recurse()` method. It was looping through the files multiple times with two different iterators.

@rhukster If you have some multilanguage site available, please test if the right pages get picked up. On my tests, the logic seems to work just fine, but it doesn't hurt to have some extra testing.

I also removed extra filtering for .md files, so as long as the main page file is in the extension fallback list, it will get picked up.

**Comment by rhukster** [comment]
Multilang test site seems to work fine.
