### ISSUE TITLE
Numbered list new line issue in demo

### ISSUE THREAD

**Issue by flavio20002** [getgrav/grav#2056]
Hi,
if i visit the demo page that comes with the core of the project (this demo is available also at this host https://www.softaculous.com/demos/GRAV), i see a new line after the second numbered list element. 

![image](https://user-images.githubusercontent.com/10809301/41334813-21b461a6-6ee7-11e8-924d-68ea4064bd50.png)

This is really strange, and depends from the block code that comes after it. If I remove the code block, the new line character disappear.

![image](https://user-images.githubusercontent.com/10809301/41334885-4c92a856-6ee7-11e8-9206-587f0299e25e.png)

Any idea?
Thanks

**Comment by rhukster** [comment]
Pretty minor issue, but it's caused by the default `ol` styling of Spectre.css:

```
ol {
    list-style: decimal inside;
}
```

When this is removed, the styling is as expected.  I'm not sure why Spectre.css has this behavior for lists by default, but Quark tries to keep things as Spectre-ish as possible.

**Comment by rhukster** [comment]
I've updated this in REPO for Quark.
