### ISSUE TITLE
Permissions incorrectly set after uploading image to admin

### ISSUE THREAD

**Issue by dmeagor** [getgrav/grav#2057]
When an image is uploaded using the admin -> content->page media options the file is added to the folder without inheriting the permissions from the folder.

One possibility is that the image is moved from another folder rather than copied so it takes the permissions from some tmp folder.

The result it that the image doesn't appear on the site preview due to a permissions error (but the thumb does appear in the admin)

This was on windows 10 iis.

**Comment by rhukster** [comment]
what permissions did the file end up with? Not seen this before and not sure how to replicate on my mac.

**Comment by mahagr** [comment]
PHP has settings on which permissions files have by default and which settings they can have (for example you cannot make the file executable, even if you try). Please start by fixing the permissions in `php.ini`. There is no inheritance for permissions.

**Comment by robotrick** [comment]
I have exactly the same problem. Images stored under user/pages/{page} can't be opened anymore because the rights are set incorrectly. However, the rights of images under {root}/images/{*} are set correctly.

**Comment by robotrick** [comment]
@dmeagor : https://stackoverflow.com/a/23857310
