### ISSUE TITLE
[add-resource] Project Space Theme

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#2060]
I would like to add the [Project Space](https://github.com/OleVik/grav-theme-project-space) theme to the GPM, descriptions and details in README.

**Comment by OleVik** [comment]
Also, a [Project Space](https://github.com/OleVik/grav-skeleton-project-space) skeleton.

**Comment by rhukster** [comment]
Added both to GPM

**Comment by rhukster** [comment]
FYI, skeleton failed....

**Comment by OleVik** [comment]
Oh, cause of the name - "grav-skeleton-project-space"? It has a release, and versions match.

**Comment by w00fz** [comment]
It’s because your tag is `v1.0.0`, it should be `1.0.0`

**Comment by OleVik** [comment]
Is this a reversion from previous logic? A while ago I needed to prefix the `v` to releases to get GPM to pick it up, and that has worked consistently for a [good while](https://github.com/OleVik/grav-plugin-twigfeeds/tree/v3.3.2).

**Comment by w00fz** [comment]
I'm sorry, you are actually good with tags/names, that is not the issue.
I didn't realize you had bot theme and skeleton in here.

The issue is the skeleton, you do need to have packages in the assets, otherwise it will fail.

You can see how they are done here:

https://github.com/getgrav/grav-skeleton-rtfm-site/releases
https://github.com/hibbitts-design/grav-skeleton-course-hub/releases

**Comment by OleVik** [comment]
I see, it does not target the source package but rather what is perceived as a compiled release that includes all of Core. I had set [.dependencies](https://github.com/OleVik/grav-skeleton-project-space/blob/master/.dependencies) to target correct versions thinking that was how the skeleton was compiled.

[v1.0.1](https://github.com/OleVik/grav-skeleton-project-space/releases/tag/v1.0.1) of the skeleton should solve this.

**Comment by OleVik** [comment]
Are there any issues with the [current release](https://github.com/OleVik/grav-theme-project-space/releases/tag/v1.1.1) of the theme? Blueprint-version is 1.1.1, release is `v1.1.1`, and changelog format is standard, but it has not propagated to GPM.

**Comment by w00fz** [comment]
This is sorted now @OleVik, there was a typo in our repository.

Sorry!
