### ISSUE TITLE
Filepicker - Cannot output images in Admin

### ISSUE THREAD

**Issue by peke314** [getgrav/grav#2062]
Hi, 

I am not able to output images for my client to pick from in the admin. 
I am in a blog item and I can only select images that are in the same folder even though I am changing the folder property. 

Here is my blueprint
`

      extends@: default

      form:
      fields:
      tabs:

      fields:
        blog:
          type: tab
          title: Informazione Evento

          fields:

            post_info:
              type: section
              title: Informazione del evento/corso
              underline: true

            picked_image:
              type: filepicker
              folder: '/user/themes/quark/img/icons'
              label: Select a file
              preview_images: true
              accept:
                - .png
                - .jpg
`

I'm working on Chrome (Version 67.0.3396.79)
Grav v1.4.5 - Admin v1.8.4

Thank you for any help I can get!

**Comment by mahagr** [comment]
Please try if `folder: 'user://themes/quark/img/icons'` or `folder: 'theme://img/icons'` works.

**Comment by peke314** [comment]
No luck, 
I've also tried to put the folder in the "pages" folder 
folder: 'user://pages/images/icons' but did not work either

**Comment by peke314** [comment]
@rhukster 
Don't know if this was fixed in new update, but with `folder: 'theme@:/img/icons'` it worked
Thanks!
