### ISSUE TITLE
Release Trouble?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#2065]
Grav 1.5.0 beta 1 + admin download package includes admin plugin 1.8.5, form plugin 2.15.1 and login plugin 2.7.3.
But where are the official plugin updates? ([should be released on 06/19/2018](https://github.com/getgrav)).  
Yesterday all updates (including Grav 1.4.6) showed up on grav downloads, but suddenly they disappeared?
If I set gpm release setting to test, it only shows Grav Beta available, but not admin/form/login updates.

**Comment by w00fz** [comment]
We had an issue with the 1.4.6 release and admin/login/form plugins so we quickly pulled them from GPM until further investigation.

If you manage to upgrade to any of the updates you are mentioning, you should revert back to the current stable releases.

The 1.5.0-beta.1 is unrelated to the 1.4.6 and should be something you install on a testing environment, it is not advised to use beta releases in production.
