### ISSUE TITLE
Grav 1.4.6/1.5.0-beta.1 causes preview error in admin editor

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#2066]
After Grav update to 1.4.6:
Go to pages in admin plugin, try to edit and click on preview tab:
Error message:

![error](https://user-images.githubusercontent.com/12480617/41682315-b2f7e674-74d7-11e8-987e-f326631f906f.png)

Preview looking for ...**json**.twig  and not for ...**html**.twig template!

This is definitely a grav error and not an admin issue.
I did all updates first (grav, admin, form, login). --> preview error 
Then installed backup and did only the grav update...--> preview error 

Seems related to:
https://github.com/getgrav/grav/pull/2044

**Comment by rhukster** [comment]
Could be this? https://github.com/getgrav/grav/pull/2044

**Comment by rhukster** [comment]
Oh you said that already. :)

**Comment by rhukster** [comment]
Ok, fixed... one liner.. see above...

**Comment by rhukster** [comment]
While that fixed the preview, it reverted the original issue.. better fix is:

Grav: https://github.com/getgrav/grav/commit/dfed333e1b1c36afa6e74b7a62c332057bbdb7ac

and

Admin: https://github.com/getgrav/grav-plugin-admin/commit/dc9b6daaa34bb0bca5e7883c8873d21aba850e3c
