### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by sebastienhouzet** [getgrav/grav#2067]
Hello

I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: https://github.com/sebastienhouzet/grav-plugin-oauth2

Thx :)

**Comment by rhukster** [comment]
There is already an oauth2 plugin that builds on top of the league oauth2 package. 

What does the stone do that our own one doesn’t? If it has some unique features it should be more uniquely named.

**Comment by rhukster** [comment]
If you want to build for a specific oauth provider the recommended approach is to extend existing oauth2 plugin. 

https://github.com/trilbymedia/grav-plugin-login-oauth2

Which slack extends:

https://github.com/trilbymedia/grav-plugin-login-oauth2-slack

**Comment by mahagr** [comment]
So you're talking about OAuth2 server, not a client like the login integration?

I agree that the name should be more specific, to give an idea what it is doing.

**Comment by sebastienhouzet** [comment]
It is a client, not server.

grav-plugin-login-oauth2 and mine not have same rules.

**Comment by rhukster** [comment]
Not familiar with bloc access.  Can you provide a link to find out more?

 Also can you rename the whole plugin to mention bloc access or something so it is more clear and does not conflict?

**Comment by sebastienhouzet** [comment]
Sorry, when i say Bloc, i want to say Denied access.

**Comment by w00fz** [comment]
I’m sorry but I don’t think we can include this plugin to gpm for different reasons.

1. Your plugin seems written very specifically for your personal use. I don’t think forcing users to the login form and register them as admins all the time upon login, is something many people would want. The permissions you set to the user are all hardcoded and there is no possibility of changing that.
2. The name you picked is incompatible with the login-oauth2 plugins family. 
3. Even tho you say they are different, in your plugin you are partially doing what the login-oauth2 plugin does, logging in into a generic provider. This is something you can do already, properly, through  the login-oauth2. I’d suggest you create a plugin that extends login-oauth2 (like the slack one) for generic access, login-oauth2-generic, which we would gladly approve for GPM as I can see it being very useful. Then you should be creating your own plugin for your own Ise where you add all the logic for blocking/denying access like you are doing.
This mix you have right now, however, is confusing all under the same login roof and definitely not compatible with the already existing oauth plugins.
