### ISSUE TITLE
Array to string conversion \Grav\Common\Page\Page::url

### ISSUE THREAD

**Issue by kolodkinvalentin** [getgrav/grav#2069]
I have custom canonical route:
`$this->grav['page']->routeCanonical('categories/my-canonical-url');`

In the base template:
`<link rel="canonical" href="{{ page.url(false, true) }}" />`

An error occured
Whoops \ Exception \ ErrorException (E_NOTICE) Array to string conversion
system/src/Grav/Common/Page/Page.php:1667
`if ($canonical) {
     $route = $pre_route . $this->routeCanonical();
 }`

\Grav\Common\Page\Page::routeCanonical
`if ($var !== null) {
            $this->routes['canonical'] = (array)$var;
        }`

**Comment by rhukster** [comment]
It's a bug!  not sure why the function was trying to convert this to an array... fixed in repo.
