### ISSUE TITLE
Menu id not sent in <a />

### ISSUE THREAD

**Issue by paolavness** [getgrav/grav#2070]
Hi there,
I'm needing to set custom id's for each menu's <a /> . I've tried adding an `id` to in the expert editor, but this has no effect. Have also searched the grav docs but nothing has come up around setting id's for menu <a />.

Is this currently not possible and if not, I'd like to make a feature request for it.

Thank you!

**Comment by rhukster** [comment]
Not following you.  There's no menu editor in Grav.  Are you talking about Gantry5?
