### ISSUE TITLE
[DarkSky Weather] New Plugin

### ISSUE THREAD

**Issue by PeterL83** [getgrav/grav#2071]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **PeterL83/darkskyweather**

**Comment by PeterL83** [comment]
I am sorry, but I can't find the plugin in the Grav Repository. Is it really added?

**Comment by rhukster** [comment]
It is in GPM, but seems there's an error with it:

```
PeterL83/darkskyweather                 Blueprints: Not Found
```

But i see you have a blueprint file.. investigating it a bit.

**Comment by rhukster** [comment]
OK, seems your release only has a README in it. 

https://github.com/PeterL83/darkskyweather/commit/9936f8345f8760d219590724e54569858d5acee5

 You just need to do a new release, and it will get picked up with next GPM update

**Comment by PeterL83** [comment]
Thanks for adding the plugin to the Grav Repository. I would like to make a small change. I have new repository called "PeterL83/grav-plugin-darkskyweather" and I want replace it. Thank you.
