### ISSUE TITLE
Broke on upgade

### ISSUE THREAD

**Issue by mabushey** [getgrav/grav#2073]
I get a git pull on both admin and base grav.

Then ran `bin/composer.phar install --no-dev` and `bin/grav clear --all`

I'm getting the following error:

 Whoops \ Exception \ ErrorException (E_ERROR)
Class Grav\Common\Twig\TwigExtension contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Twig_ExtensionInterface::getName)

**Comment by rhukster** [comment]
Hmmm.. Do you have the Twig PHP extension installed? What version of PHP are you running?

**Comment by mabushey** [comment]
Got it working, just had to delete the composer.lock before I ran `bin/composer.phar install --no-dev`. This was probably screwed up from way back. Thanks for the help!
