### ISSUE TITLE
Parent list in page editor - advanced tab - don't show full page list

### ISSUE THREAD

**Issue by mugol80** [getgrav/grav#2074]
Welcome
I have some small problem.
I have little over 1000 pages in this moment.

When i try change parent for some pages (not all, only last on list) 
i can't do this, because i don't see all parent pages on the list.

I see full list in view-source in select (options list), but after "selectize" (after create dropdown list) in developer tools i see only part list not all.

Have any suggestions what may be the reason and how i can fix it?

**Comment by mugol80** [comment]
Selectize have limit 1000 items (maxOptions) in default options.
i can find page when i write name, but when i have more then 1 page the same name i dont know what i should choose. Maby show route to the page too in select list?

**Comment by mahagr** [comment]
Fixed in Admin 1.10.
