### ISSUE TITLE
Folder either shows empty page or 404

### ISSUE THREAD

**Issue by AquaL1te** [getgrav/grav#2075]
When I create a folder it shows up as a menu, as it should. But when a user clicks on it, it opens a blank page. When I disable routing it becomes a 404. How can I just create a menu item which doesn’t link to anything? What I want to setup is that when someone clicks on it, it only expands the menu, nothing more.

At the moment I created page redirects to one of the folder items in order to hide this problem. But it’s not pretty. Also the TNT Search has some problems with this, when I type in a keyword which is a redirected folder, the page deforms. But that's another issue of course.

**Comment by rhukster** [comment]
You're really doing the simplest solution.  

Another solution would be to add a custom page header like:

```
placeholder: true
```

Then in your Twig template that renders the menu, check this with:

```
{% if page.header.placeholder %}
... output a <span> for placeholder...
{% else %}
... output a <a> for link ...
{% endif %}
```

Something like that. 

Of course you will need to have CSS support for menu items that are span and others that are the traditional links.
