### ISSUE TITLE
unexpected $autoload in index.php

### ISSUE THREAD

**Issue by Sajo811** [getgrav/grav#2078]
I enabled error logging as I was getting a white page when I starting the local development server. I get this error-
```
 Parse error: syntax error, unexpected '$autoload' (T_VARIABLE) in C:\webroot\grav\index.php on line 17
```
How do I fix this? I have php 7+ and grav 1.4.6
Thanks!

**Comment by rhukster** [comment]
What version of PHP are you running? Seems like a PHP error.  Remember Grav currently supports Grav 5.5+, but will soon be 5.6+ only.

**Comment by Sajo811** [comment]
I have PHP 7.2.6, as I specified in the original post @rhukster

**Comment by rhukster** [comment]
I'm not sure how you get this error then.

When I google this error, all the results basically relate to the PHP version running is old.  That's really the only way you can have this error because it means that PHP can't parse the PHP properly.  But we test it on every version from 5.5 to 7.2 and it works fine.

**Comment by rhukster** [comment]
I suggest you test with `phpinfo()` in a test php file to confirm the version.

**Comment by Sajo811** [comment]
I get this-
```php
phpinfo()
PHP Version => 7.2.6
```
and then a bunch of other info

**Comment by rhukster** [comment]
Last thing to try is to see if your index.php is corrupted or invalid.  Just reinstall Grav and try again.

**Comment by Sajo811** [comment]
I used a skeleton, should I just re-extract the whole thing again?

**Comment by rhukster** [comment]
Yes, but which skeleton was it? Perhaps the skeleton is corrupt somehow.

**Comment by Sajo811** [comment]
https://github.com/tranduyhung/grav-skeleton-x-corporation

**Comment by Sajo811** [comment]
when I run the debug server on a vanilla extract of the skeleton, I get this error :/ apache is running as admin https://i.imgur.com/lw8Ef3H.png

**Comment by rhukster** [comment]
Ok, a few things:

1) this is not a Grav or Trilby developed skeleton, so i can't speak to how it's been built or the package has been created.
2) the repo itself is not a full skeleton, it's merely the user folder, and won't run unless you have Grav installed and replace the user folder with this.
3) the 'releases' do appear to have full packages built, e.g. the `grav-skeleton-x-corporation-v1.2.3.zip` here: https://github.com/tranduyhung/grav-skeleton-x-corporation/releases/tag/v1.2.3
4) I noticed that while Grav was latest, Form plugin and X-Corporation theme is out of date in this skeleton, they can be updated with `bin/gpm update`

The v1.2.3 package seems to work fine for me in PHP 7.2

**Comment by rhukster** [comment]
Just remove grav completely and create a simple hello world php file.  I think you are just having webserver/php issues. It’s not even getting to grav in that last error.

**Comment by Sajo811** [comment]
Well an install of grav through the official homepage then the installation of the theme separately then adding content by working my way backwords by mimicking a vanilla skeleton clone of the theme in a different location seems to work, thanks
