### ISSUE TITLE
1.5.0-beta.1: bin/gpm install devtools PHP Fatal error

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#2079]
Installed a fresh copy of 1.5.0-beta.1 core + admin

Running `bin/gpm install devtools` fails with error:

```
 |- Downloading package...   100%
 |- Checking destination...  ok
 |- Installing package...  PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in .../grav-wp/system/src/Grav/Common/GPM/Installer.php:174
```

Same error as in  #2076

**Comment by OleVik** [comment]
Does your PHP have the Zip-extension enabled?

**Comment by pamtbaau** [comment]
1. php -m contains zlib in the list
1. I can install plugins via the Admin plugin which executes the exact same code line `.../grav-wp/system/src/Grav/Common/GPM/Installer.php:174`

I guess that's a yes...

**Comment by OleVik** [comment]
I don't think `zip` and `zlip` are equivalent, but we might need to know more about the environment. If it works from Admin, it should work from CLI, but they are typically not ran by the same user - one is virtually `www-host` and the other is whatever you logged in as on the command line.

**Comment by pamtbaau** [comment]
I ran the following: `sudo apt-get install php7.2-zip` and installing via `bin/gpm install devtools` works fine now...

That doesn't explain to me why Admin plugin did run ok... 

Issue #2076  is solved too and can be closed.

**Comment by OleVik** [comment]
Only the original poster or maintainers can close issues, so it would save the maintainers some time if you closed both of them yourself.
