### ISSUE TITLE
[add-resource] New Plugin Redirects2

### ISSUE THREAD

**Issue by dfrankland** [getgrav/grav#208]
I would like to add my new plugin to the Grav Repository.
Here are the project details: [dfrankland/grav-plugin-redirects2](https://github.com/dfrankland/grav-plugin-redirects2)

Redirects2 is a plugin that adds redirection on a per page basis. It also allows setting the http status code to one outlined by PHP header( "Location:" ) redirect.

**Comment by rhukster** [comment]
Hey Dylan I will get this added, but just wanted to make you aware that we did have some redirect changes in github since the last update.  Have you tested this with the latest develop branch?

Thanks!

**Comment by rhukster** [comment]
Specifically this commit is the bit that changed:

https://github.com/getgrav/grav/commit/6d2a7c53dc9358fe057ea380967e882075acc6ad

Might not make a difference as your plugin does its own redirecting :)

**Comment by dfrankland** [comment]
Since the plugin does it's own redirecting I wasn't worried about that change, but I just cloned and tested the develop branch without any issues. :+1:

**Comment by rhukster** [comment]
Ok, ive added it to the list. Should be available on the site and via GPM in about 15 mins.  Thanks!
