### ISSUE TITLE
grav.user not working

### ISSUE THREAD

**Issue by eaconner** [getgrav/grav#2088]
Has anyone else noticed that ```grav.user``` is no longer working? I've tried using ```{{dump(grav.user)}}``` and looking at the debugger but even though I'm logged in it shows:
```
Grav\Common\User\User {#105
  #gettersVariable: "items"
  #items: array:5 [
    "username" => ""
    "state" => "enabled"
    "authenticated" => false
    "authorized" => false
    "language" => "en"
  ]
```

**Comment by rhukster** [comment]
I can't replicate this..  Works fine for me...

Have you updated Grav + Login plugin to latest?

**Comment by mahagr** [comment]
Above user instance is available when login plugin has been installed, but the user hasn't logged in.

**Comment by rhukster** [comment]
Yes, i get that same output when i'm loggged out, but when i'm logged in I get user data.

**Comment by eaconner** [comment]
I'm running Grav 1.4.6, Admin 1.8.5, and login 2.7.3. Fresh download from getgrav.org. I get the same log if I'm logged in or out. I've checked everything that I can think of/

**Comment by rhukster** [comment]
Are you dumping this in the page content? If so, then it's cached.  You can turn off caching for the page, or you can still cache, but just run twig every time:

```
never_cache_twig: true
```

https://learn.getgrav.org/content/headers#never-cache-twig

**Comment by trojkat** [comment]
Same here on fresh install from yesterday (master branch). No matter if I'm logged in or not I get same `grav.user` object as @eaconner. Changing `never_cache_twig` to `true` doesn't help either. PHP version: `PHP 7.2.10-0ubuntu0.18.04.1`.

**Comment by Daryadi-S** [comment]
Yeah I found the problem: The {{ grav.user }} does not recognize you as user if you are only login as the super admin through "/admin".

But you also need to create account from "/user_register" and logged in through "/user_profile" there...
