### ISSUE TITLE
[add-resource] New Plugin: Static Social Embeds

### ISSUE THREAD

**Issue by AmauryCarrade** [getgrav/grav#2089]
I would like to add my new plugin to the Grav Repository.
Here are the project details: [**Nebulius/grav-plugin-static-social-embeds**](https://github.com/Nebulius/grav-plugin-static-social-embeds).

The goal is to allow authors to embed contents from Twitter, Instagram and Mastodon (as for now), without using the iframes provided by the services, to ensure independence and privacy. As a side effect, it's also way faster: we store all data in a cache, and there is no subsequent JS + iframe loading time. And it's not blocked by Firefox's privacy shield or privacy/ad blocker add-ons.

Shortcodes are used to include embeds into pages.

Twitter integration requires credentials from an app that the author must create. Others work without authentication.

Translated in English and French. I don't have a live demo currently, but you can check out screenshots on the README.

Thanks, and have a beautiful day :) .

**Comment by rhukster** [comment]
Added to GPM for next update

**Comment by AmauryCarrade** [comment]
Hi! Sorry to bother you but it seems that you saved this plugin under `social-embeds` instead of `static-social-embeds` in GPM's database. As a result, the folder name is wrong and the files never loaded (admin page without form and plugin's code never executed). And of course, it works if the folder is renamed (but it breaks updates).

```
$ php bin/gpm info static-social-embeds

GPM Releases Configuration: Stable

The package 'static-social-embeds' was not found in the Grav repository.

You can list all the available packages by typing:
    bin/gpm index



$ php bin/gpm info social-embeds

GPM Releases Configuration: Stable

Found package 'social-embeds' under the 'Plugins' section

Static Social Embeds [social-embeds]
------------------------------------
Embeds social status (like tweets, instagram posts, toots, etc.) in articles without using their embed iframe,
but rather statically without any dependency to the service.

Author      : Amaury Carrade <amaury@carrade.eu> 
Version     : 1.1.0
Keywords    : grav, plugin, embed, static, twitter, instagram, mastodon, tweet, toot, integration, post
Last Update : Tue, 16 Sep 2014, 02:07:16, +02:00 
Homepage    : https://github.com/Nebulius/grav-plugin-static-social-embeds
Docs        : https://github.com/Nebulius/grav-plugin-static-social-embeds/blob/master/README.md
Repository  : https://github.com/Nebulius/grav-plugin-static-social-embeds
Bugs        : https://github.com/Nebulius/grav-plugin-static-social-embeds/issues
Download    : https://getgrav.org/download/plugins/social-embeds/1.1.0
License     : MIT
Would you like to read the changelog? [y|N] n

You can install this package by typing:
    bin/gpm install social-embeds
```

Is there a way to fix this issue? Thanks!

**Comment by rhukster** [comment]
Sorry about that.  We’ll get this fixed.

**Comment by AmauryCarrade** [comment]
It had no consequences at all so no worries, and thanks :) .

**Comment by w00fz** [comment]
I updated the name from `social-embeds` to `static-social-embeds`.
The change should be picked up by GPM in about 30mins.
