### ISSUE TITLE
Status of admin interface

### ISSUE THREAD

**Issue by herrbischoff** [getgrav/grav#209]
I just wondered what the status of the admin GUI is. I really would like to use Grav on client projects but without it, that's unfortunately a no go.

I'm asking because I cannot seem to find a dev version of it. Also, I'd be more than willing to help out with front end work.

**Comment by rhukster** [comment]
This information will be decimated via the blog/twitter/gitter when we have that information.  Thanks!

**Comment by herrbischoff** [comment]
Thanks for your reply. So, you're not at all interested in developers joining in? I'll be sure to keep that in mind.

**Comment by rhukster** [comment]
Well I am definitely interested in developers helping out with it, if this is something that interests you please jump on our Gitter.im channel (linked in top-right of our getgrav.org site) and we can chat further.

Thanks!
