### ISSUE TITLE
How to implement Modals?

### ISSUE THREAD

**Issue by Cordoha** [getgrav/grav#2092]
Is there an easy way to make a modal with UIKit or any other way? I'm trying to implement one for GDRP, I have UIKit installed but I'm having trouble implementing them. I've followed example code, but nothing pops up. 

https://getuikit.com/docs/modal
https://www.inspiretheme.com/blog/freebies/48-uikit-for-gantry5-atom-and-updated-particles-freebies

I'm using the latest Grav install, and Gantry5.

**Comment by Cordoha** [comment]
I've pretty much figured it out. Took all evening, but found a way to do it with a notification and modal. Though, the way I am doing it doesn't accept a cookie, or have a time constrant to stop nagging. It also pops up every page. Best I can do for now, I guess.

**Comment by adavie1** [comment]
@Cordoha would you be willing to post your code? I want to do the same thing. Thanks in advance.

**Comment by hermetic-design** [comment]
@Cordoha I'd really like to hear how you managed to do that!
