### ISSUE TITLE
Custom routes with wildcards that route to custom templates

### ISSUE THREAD

**Issue by TheImpressionist** [getgrav/grav#2098]
Hey,

I'm trying to figure out whether the following would be possible:

- Define custom route with wildcards: `/page/:name/:id`
- Have that route to one template constantly

I understand that it is possible to define custom routes with wildcards using regexp. However, the issue is that the route needs to serve a custom template regardless of the `:id` or `:name` at the end. Meaning, I wouldn't have to create a new page for each ID or specific name.

If the answer that that is not currently possible, then I presume I can extend the routing functionality myself?

What I'd be looking at in such case:

```yaml
routes:
  - route: /page/(.*)/(.*)
    template: my_template.html.twig
```

**Comment by rhukster** [comment]
Currently, this is not possible in Grav.

**Comment by mahagr** [comment]
@TheImpressionist Grav does support paths like that, though with params:

```
/page/name:foo/id:1
```

Which are then available inside your page.

**Comment by TheImpressionist** [comment]
Ah okay, thanks. My current solution is to have the server route it to whatever template I need instead of grav.

I'll make a fork and play around with this concept.
