### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by brettdewoody** [getgrav/grav#210]
I would like to add my new theme to the Grav Repository. My theme uses Zurb's Foundation front-end framework and my plan is to add a high-performance build script to create an optimized cached version of the site. With the end goal being able to create super fast site that rank well using Google's PageSpeed tool. 

I'd like to get the theme into the GPM so I can more easily test the install. 

Here are the project details: [https://github.com/brettdewoody/grav-theme-foundation](https://github.com/brettdewoody/grav-theme-foundation)

**Comment by rhukster** [comment]
Thanks Brett, I'll get it tested and added shortly! Cheers.

**Comment by rhukster** [comment]
BTW i noticed first thing that the screenshot via the README.md on github is broken.  Also is there a demo?

**Comment by brettdewoody** [comment]
Haven't been able to put up a demo just yet, though I probably can in the
next day or two.

Can we add the theme to GPM so I can test a full install. Also, if needed
we could leave the theme off the Themes page on GetGrav.org while I clean
things up.

**Comment by rhukster** [comment]
Hi Brett, I tried to add the theme to GPM but it failed because of the missing screenshot.  Can you please double check you have all the times here covered:

http://learn.getgrav.org/advanced/grav-development#themeplugin-release-process

**Comment by brettdewoody** [comment]
I've added a screenshot. Let me know if that does the trick.

**Comment by rhukster** [comment]
Just need to re-release now so that the screenshot is in the latest released version too.  Then it should automatically show up next time the repo is generated (hourly).

**Comment by brettdewoody** [comment]
Doesn't look like the screenshot did the trick. Am I missing something else?

**Comment by w00fz** [comment]
You need to either have a screenshot.jpg at the root of the project or add a screenshot entry pointing to the location of it. Right know you have it under assets and named screenshot1.png so the repository doesn't find it. 

Have a look here http://learn.getgrav.org/advanced/blueprints

// Djamil Legato // From iPhone //

**Comment by rhukster** [comment]
Looks like you have this sorted! I see foundation is now showing up on the Themes page: http://getgrav.org/downloads/themes
