### ISSUE TITLE
adding '@2x' to images prevents removal from page media

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav#2100]
I haven't noticed this issue before, perhaps it is a new bug in 1.5.0 (beta2) and associated admin plugin?

Essentially I can successfully add and re-order images in page-media for a given project, (https://gresfordarchitects.co.uk/projects/chieveley) but when using the admin panel I am unable to delete a file, there is a red error note that comes up saying 

> unlink() not supported for read-only stream wrappers

**Comment by rhukster** [comment]
will look into this matt.  cheers.

**Comment by rhukster** [comment]
confirmed.. we're looking into it...

**Comment by MattAppleton** [comment]
Amazing!    thanks as ever...
