### ISSUE TITLE
Page with Folder Numeric Prefix Disabled Not Showing in Menu

### ISSUE THREAD

**Issue by simmonsr** [getgrav/grav#2102]
When Folder Numeric Prefix is disabled for a page, it does not display in the Menu (even though it is set to be Visible):

![screen shot 2018-07-16 at 2 22 31 pm](https://user-images.githubusercontent.com/5002814/42780111-05d48872-8908-11e8-9483-25ac940a6800.jpg)

Specifically testing with Gantry 5 templates and Grav.

**Comment by rhukster** [comment]
In non-Gantry5 setup i can't replicate this.  The visible override does indeed make it visible in the menu, however, as there's no numeric prefix, there's no order, so it's the last element in the menu.

**Comment by simmonsr** [comment]
Thank you verifying that. Is there anyway that **Folder Numeric Prefix** can be **enabled** by default globally? When a Child page is created with no siblings, it is **disabled** by default.

**Comment by simmonsr** [comment]
I would also note that if **Folder Numeric Prefix** is **disabled** and Visible is set to **auto**, it will not appear (whether G5 theme or Quark)

**Comment by rhukster** [comment]
The first 'new page' window is just to set some defaults, if you wish to set visibility explicitly you have to enable it via the advanced -> options:

![screen-shot-2018-07-18-10-29-07](https://user-images.githubusercontent.com/1084697/42894982-9fa8cb48-8a75-11e8-906b-7682b939f515.png)

Of course, this is via the admin plugin.  It's simpler to do it in files, just put `visible: true` in your page frontmatter.

**Comment by simmonsr** [comment]
And I understand that. I could just see it being confusing for user(s) if Visible shows enabled in Advanced tab yet not checked off:

![screen shot 2018-07-18 at 11 37 27 am](https://user-images.githubusercontent.com/5002814/42895280-fae62f92-8a7e-11e8-97ff-7276cee61d9e.jpg)

Since I'm more versed in Gantry, I only think of this (the above image) as the Master / Base setting (with Visible being Enabled globally). But it's really not that way...

**Comment by rhukster** [comment]
No, Grav is a simpler beast... there's not higher level trickle down inheritance like in Gantry.  You will get a better understanding of what's going on if you flip back and forth between normal/expert mode.  Also, I strongly advise, you 'develop' with the files directly in an editor like ST3/Atom/VSC, things will make more sense to you as you build out your site.

**Comment by simmonsr** [comment]
Ok, understood.
