### ISSUE TITLE
page add panel in html injection vulnerability

### ISSUE THREAD

**Issue by ismailtasdelen** [getgrav/grav#2105]
Hello Development Team,

When I was a security researcher and student, I wanted to discover and report "HTML Injection" vulnerability.

Version : Grav v1.4.7 - Admin v1.8.6

Vuln url adress : /GRAV/admin/pages -- page add

Screenshot :

![screenshot from 2018-07-18 13-49-16](https://user-images.githubusercontent.com/15425071/42877218-9d6abe2e-8a91-11e8-80a2-6a53994d0aa0.png)

Payload : html basic h1 tag 

Thanks

**Comment by rhukster** [comment]
Again this requires admin access.  Privileged access is required, and therefore is not a vulnerability.

**Comment by ismailtasdelen** [comment]
Thanks for the came back :+1:
