### ISSUE TITLE
[add-resource] Personalizer Add-On for the GRAV Shoppingcart plugin

### ISSUE THREAD

**Issue by leotiger** [getgrav/grav#2107]
I've published a few minutes ago a first version of the Shoppingcart-Personalizer add-on.

[Shoppingcart Personalizer](https://github.com/leotiger/grav-plugin-shoppingcart-personalizer) has two purposes, to show people how to write add-ons for the core plugin and to enhance the core plugin. Please refer to the readme on github to get an idea.

**Comment by leotiger** [comment]
Lot of additional stuff is now available, e.g. 

* better theme integration, the plugin allows to specify which base template to extend, defaults obviously to default
* complex, grouped product variations and configurations with pricing, user input, etc.

**Comment by rhukster** [comment]
added to GPM for next update
