### ISSUE TITLE
Set user specific access on page creation

### ISSUE THREAD

**Issue by cabajian** [getgrav/grav#2108]
Using this [post](https://learn.getgrav.org/cookbook/admin-recipes#add-a-custom-page-creation-modal) I added a new method for creating a specific page.

When this page is created, is it possible to set user-specific access to the page header, ie:

```
access:
    site:
        user1: true
```

so only `user1` has access to the page?

I know you can add custom fields, such as `access.site.login`, but how about dynamic fields, as exampled?

**Comment by rhukster** [comment]
Nope, this is not possible, but you can use a group, and just put that one person in that group.
