### ISSUE TITLE
[add-resource] Content-edit (front end md page editing)

### ISSUE THREAD

**Issue by finanalyst** [getgrav/grav#2111]
Greetings!   
(updated)

Please consider adding my new plugin to the Grav Repository.
Here are the project details: https://github.com/finanalyst/grav-plugin-content-edit

There is already a plugin for frontend editing called `editable-simplemde` and an admin side plugin that puts an edit button on the page for users with admin permissions called `front-end-edit-button`.

This new plugin extends the ideas in those plugins (particularly `editable-simplemde`), but offers the following advantages:
- it leverages Login so that pages can only be edited by authorised users or users in groups, and those users do not need to have admin permissions.
    - this cannot be done using the approach of `front-end-edit-button`
- All edits to pages and file uploads are separately logged with a datestamp, the edits being save in a diff format
    - neither of the other plugins separately log edits so that each edit can be quickly identified.
    - the user/editor making the edit is also logged.
- it leverages page collections so that different sets of pages can be edited by different groups/users
    - neither of the other plugins offers this sort of easily configured granularity. 
- it leverages DataManager so that the logged edits can be viewed easily and individual edits highlighted. 
- it allows for the *md* content of sub-pages in a modular page to be edited.
   - This cannot be done with `editable-simplemde`, which was why this plugin was developed.
- Frontend visualisation of the edits is now provided using another template (similar to the one for DataManager). Access to the edit and review pages can be separated, allowing for managerial oversight.

**Comment by rhukster** [comment]
Added to GPM for next update
