### ISSUE TITLE
Checkbox as required field is not working

### ISSUE THREAD

**Issue by Pixelpaule** [getgrav/grav#2116]
Hey guys,
my contact form with a checkbox as "required" field is not working. If I select the checkbox and submit the form, I always get the error: "Validation failed: "

That's my Fields:
privacy_policy_info:
  type: display
  label: Datenschutzerklärung
  outerclasses: form-hints
  display_label: true
  content: 'Bitte informieren Sie sich vor dem Absenden über die <a href="/datenschutz" target="_blank">Datenschutzerklärung</a> auf der Seite Datenschutz (Link neuer Tab).'

agree_to_terms:
  type: checkbox
  label: "Agree to the terms and conditions"
  name: 'Datenschutz'
  validate:
      required: true
      message: 'Bitte bestätigen Sie die Datenschutzbestimmungen'`

I have considered everything from the documentation.

Have a nice day!
Andre

**Comment by Pixelpaule** [comment]
Hey guys,

if the checkboxes has the Attribute value="1", then the contact form submitted. I resolved the problem temporarily with a small JavaScript.

```JavaScript
(function () {
    var elem = document.querySelectorAll('input[type=checkbox]');
    for (i=0; i<elem.length; i++) {
        elem[i].addEventListener('change', function () {
        if (this.checked == true) {
            this.setAttribute("value", "1");
        } else if (this.checked == false) {
            this.removeAttribute("value");
            }
        });
    };
}());
```

I hope the problem would be fixed by the developers soon. 

Have a nice day!
Andre

**Comment by rhukster** [comment]
This works for me with this example:

```
        accept_rules:
          label: Accept rules
          type: checkbox
          validate:
            required: true
            message: Please accept the rules to send  
```

I did find a bug in Quark theme while testing this as it has it's own override.  The `client_side_validation: false` form option was not working with checkbox or radio. but it was prompting me via HTML5 client side validation that this option was required.
