### ISSUE TITLE
Theme Config Multi Language Support

### ISSUE THREAD

**Issue by AndrewNB** [getgrav/grav#2118]
Hi,

I am using multiple languages on a site and it's working great for pages and system translations.  

I am stuck on the following issue:
I want to translate content that is stored in the user/config/themename.yaml file.  is this currently possible?

**Comment by dameert** [comment]
I found a bug with theme translations, opened ticket #2372 with a description to reproduce and propose 2 different fixes in pull requests #2373 #2374
