### ISSUE TITLE
Bug in Medium.php? config -> media.enable_media_timestamp

### ISSUE THREAD

**Issue by spacecowboy23** [getgrav/grav#212]
Hello, i possibly found a bug in /grav/system/src/Grav/Common/Page/Medium.php, Line 63:

if (self::getGrav()['config']->get('media.enable_media_timestamp', true)) {

For my installation of Grav v0.9.29, i always get a media timestamp in any HTML output, regardless of the settings in /grav/user/config/system.yaml or /grav/system/config/system.yaml

After changing  Line 63 in Medium.php to:

if (self::getGrav()['config']->get('system.media.enable_media_timestamp', true)) {

the enable_media_timestamp config works as expected, i can turn timestamps for media on and off via system.yaml. Can anyone confirm this bug, or is it only me affecting this bug?

**Comment by rhukster** [comment]
Yup, you are correct sir! Thanks!
