### ISSUE TITLE
Multilingual setup / hreflang

### ISSUE THREAD

**Issue by fabbow** [getgrav/grav#2120]
Hi there, 

there are quite a few issues about this in plugin repositories, but as it's something with Grav itself I would like to post it here. 

It seems like there is currently no way to directly link an hreflang tag from a page to its counterpart(s) in other languages when there is a translated slug. Grav only loads one language at the time and thus uses the raw route for langswitching or building hreflang tags by plugin. 

Google on the other hand wants us to have the hreflangs between the final URLs, not redirects and I believe this could be a dealbreaker for quite a few people that would love to use Grav but can't for this reason - at our agency it is. 

http://www.thesempost.com/google-dont-link-hreflang-redirecting-urls/

I'm not deep enough into Gravs Core Architecture but it would be great to have some people discuss this

**Comment by CSixtyFour** [comment]
I've just noticed this now too. In the sitemap plugin only the main language slug shows for the other language's page(s) which is not expected behaviour.

**Comment by rhukster** [comment]
This is a duplicate based on the fact that this is how Grav's multilang is able to be flexible and still performant: https://github.com/getgrav/grav/issues/1695#issuecomment-337585687
