### ISSUE TITLE
Best process to rename several Grav project GitHub repos?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#2125]
I want to rename several of my Grav projects to better align them (theme and skeleton), and was wondering if there are any best practices to do so? If I recall correctly, when a project GitHub repo is renamed it can temporarily cause issues with the GPM. Thanks very much!

**Comment by rhukster** [comment]
just create a ticket and give me the breakdown of the old and new names.  I can coordinate with you on slack to ensure we get the timing right.

This is one of those scenarios that will totally be handled by our new GPM logic that we're working on.

**Comment by paulhibbitts** [comment]
Will do, thanks very much Andy... and 👍👍👍 on that new GPM logic you are working on!
