### ISSUE TITLE
grav.CRITICAL: Class 'Grav\Event' not found - Trace: #0 {main} [] []

### ISSUE THREAD

**Issue by mintan** [getgrav/grav#2126]
I traced problem by many methods but could not solve its. Could any body help explain what had occur when have these messages:
---------------------
Error … index.php:54
Class 'Grav\Event' not found
--
// Process the page
51.try {
52.    $grav->process();
53.} catch (\Exception $e) {
54.    $grav->fireEvent('onFatalException', new Event(array('exception' => $e)));
55.    throw $e;
56.}
--
Arguments 
1."Class 'Grav\Event' not found"
-----------
Thank you

**Comment by mahagr** [comment]
Which version of PHP are you running on? Because of it looks like your PHP doesn't know how to parse the file.

**Comment by rhukster** [comment]
Definitely looks like your PHP version might not be up to minimum requirements.  Either that or your Grav installation is not all there.
