### ISSUE TITLE
[change-resource] Take over Shoppingcart

### ISSUE THREAD

**Issue by leotiger** [getgrav/grav#2127]
@rhukster I've been in communication with @flaviocopes talking about the Shoppingcart plugin. As I've been working a lot on the [Personalizer add-on](https://github.com/leotiger/grav-plugin-shoppingcart-personalizer) that provides a lot of expected out-of-the-box features, my proposal was to merge the two plugins into one. Flavio stated that he's not able to assume this at the moment and he agreed that I may take over the Shoppingcart plugin. He confirmed this in the corresponding [issue 89](https://github.com/flaviocopes/grav-plugin-shoppingcart/issues/89).

Plugin name: Shoppingcart
Repository: https://github.com/flaviocopes/grav-plugin-shoppingcart

My current PR: https://github.com/flaviocopes/grav-plugin-shoppingcart/pull/87

**Comment by rhukster** [comment]
I will update GPM to reflect it.

**Comment by leotiger** [comment]
There's also a site related with the Shoppingcart plugin. Probably it's the best to ask him for these plugins. Let me merge the two plugins first and if we see that there's some real demand for this we are on time to transfer the other plugins as well.

**Comment by rhukster** [comment]
New issues for those I think...
