### ISSUE TITLE
E_WARNING from file_exists() in Grav/Common/Themes.php

### ISSUE THREAD

**Issue by matteoredz** [getgrav/grav#2129]
I'm experiencing this issue randomly and my app keep crashing

<img width="1280" alt="schermata 2018-07-29 alle 11 39 45" src="https://user-images.githubusercontent.com/4482159/43592820-aab3e39e-9676-11e8-90cf-11ee41ade77d.png">

I need to restart Apache to make it work again.

My VPS runs php 5.6 and the apache user/group is www-data.. File / directory permission looks right to me, and also system requirements are matched.

I've read about NULL byte causing this issue, how is happening?

**Comment by rhukster** [comment]
From searching Google, it does seem to be a weird thing with null bytes on folder names in your filesystem. 

This would undoubtedly fix your issue:

```
$languages_folder = strval(str_replace("\0", "", $languages_folder));
```

After the `findResource()` line. Howerver, the bigger questions is, why do you 'randomly' have null bytes in your paths, and not other times (when it works).  I think perhaps there is either a problem with your server, or your server has been compromised somehow.  

I think you should contact your hosting provider and talk to them about this.
