### ISSUE TITLE
Fresh Gantry/Grav Install Crashing

### ISSUE THREAD

**Issue by artofthesmart** [getgrav/grav#2130]
Not sure if this is a Gantry bug or a Grav bug, but it looks like there's some discord here.

Steps to reproduce, I've done this a couple times to be sure.  Maybe I've done something wrong here because it's still working on my main installation.

1. Create a new grav installation from git.  run install.
2. From the CLI, install the admin plugin.
3. Log in.
4. From the interface, install the Gantry plugin.
5. From the interface, install the Helium theme.
6. From the interface, Activate the Helium theme.
7. From the interface, click "Gantry Framework".

ERROR: /home/webhost/peft/user/plugins/admin/admin.php => Page Not Found.

Gotta get to a meeting, but wanted to post it here in case anyone else is seeing this.

**Comment by mahagr** [comment]
You cannot access admin from the plugin php file -- it can be accessed just like any other page in Grav.

**Comment by artofthesmart** [comment]
Sorry, I'm in and out of meetings.  What I mean to say is that when the "Gantry 5" link appears in the left pane of the Admin plugin of Grav and you click on it, it yields an error in new installations.  On old installations it takes you to the Gantry configuration for your theme.

**Comment by rhukster** [comment]
I don't see a link to "Gantry Framework" but when i click on "Gantry 5" in the sidebar, it works just fine and goes to '`admin/gantry/configurations/default/styles`

**Comment by artofthesmart** [comment]
Must just be on my installation then; I'll keep searching for the issue.
