### ISSUE TITLE
Devtools RuntimeException: due to wrong foldername /devtools/components/theme/inheritence

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#2131]
When using `bin/plugin devtools newtheme` and selecting inheritance, devtools tries to copy folder
`/components/theme/inheritance`, but folder is actually named `/components/theme/inheritence`

Exception is thrown at Folder.php line 288:
```
if (!is_dir($source)) {
    throw new \RuntimeException('Cannot copy non-existing folder.');
}
```

**Comment by rhukster** [comment]
Fixed in devtools
