### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by lvennard** [getgrav/grav#2132]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **lvennard/grav-plugin-injectphp**

https://github.com/lvennard/grav-plugin-injectphp

**Comment by lvennard** [comment]
Its poorly written.. i know.. and i apologize up-front.  but works well if you need it in a pinch.  Im new to grav and this was the only part holding me back from going Full-GRAV, nothing is gonna stop me now.  :)  Hope this will help others past the conversion state, or just a simple dynamic output.

**Comment by zebooka** [comment]
This should be never used. Unless you want your website to be hacked

**Comment by lvennard** [comment]
you lost me, if you control the file that is called, how can you get hacked?  Do i need to add a warning for folks that will just randomly add unknown authors files ?

**Comment by zebooka** [comment]
Anyone with access to page edit will have ability to execute own code and escalate permissions to full access. Not to mention installation of third party software

**Comment by lvennard** [comment]
true.    If you do not control the files on your server, you could get hacked.. about a hundred different ways.

**Comment by rhukster** [comment]
i personally would never use this plugin. I would always do my logic in Twig if appropriate, else create a custom plugin that wraps the logic.  However, I can see this being useful, especially for development situations when you want to get something 'running' and then create a plugin in parallel.

**Comment by rhukster** [comment]
Added to GPM

**Comment by rhukster** [comment]
You need to create a release to ensure it gets picked up. https://learn.getgrav.org/advanced/grav-development#theme-plugin-release-process

**Comment by lvennard** [comment]
Release added.

**Comment by rhukster** [comment]
Shows now
