### ISSUE TITLE
Files with upper case filename extension are not found

### ISSUE THREAD

**Issue by Tamriel** [getgrav/grav#2133]
When uploading a file with an upper case filename extension, that file can be found at e.g. `/user/pages/02.page-name/hello.JPG`, but somehow not at `page-name/hello.JPG`. 
Files with a lowercase extension are found at `page-name/hi.jpg`. 

It would be nice to have consistent behaviour, since at least one Grav plugin builds on this and its author did not knew about this unexpected / inconsistent behaviour.

**Comment by rhukster** [comment]
Fixed in 1.5 branch..
