### ISSUE TITLE
PHP class inheritance issue with inherited theme names contains hyphens

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#2134]
Thanks to @OleVik I was able to track down an issue related to PHP class inheritance when an inherited theme name (not class) has hyphens included in it.

For example, with my current `bootstrap4-open-matter` theme, an inherited user theme (`mytheme`) on this theme does not pass through the PHP class functions of `bootstrap4-open-matter` as expected (note: class name does not contain hyphens, as I understand this is a known issue). 

To quote Ole:
_https://github.com/getgrav/grav/commit/874160480faf5d968a8f32a3f254618e4dd0ad0d does not solve all cases, if `MyTheme` extends `Bootstrap4OpenMatter` which extends `Bootstrap4`, and Bootstrap4OpenMatter uses hyphens in folder- and filenames, MyTheme and Boostrap4OpenMatter will not peacefully coexist in the namespace. Thus MyTheme fails to find the class for Bootstrap4OpenMatter. Removing hyphens in the folder `bootstrap4openmatter` as theme-folder, `bootstrap4openmatter.php`, and `bootstrap4openmatter.yaml` solves it._

Here is a complete skeleton to demonstrate this issue: https://ln.sync.com/dl/11c7ab0e0/48xt8tty-crv9dye6-e3ic28xs-3sigdm3u

**Comment by rhukster** [comment]
Ok, it was not the dashes per say, but more the digit before a capital (4 before O of open) that was throwing the inflector.  Fixed in 1.5 branch (which is going stable/live/production soon).

**Comment by paulhibbitts** [comment]
Awesome @rhukster,  thanks for fixing the issue! I will also test with that new release to confirm.
