### ISSUE TITLE
Frontmatter cache_enable: false not enabling onPageContentRaw event

### ISSUE THREAD

**Issue by heavydetail** [getgrav/grav#2135]
As the title says, if you set the Frontmatter cache_enable: false directive, it won't enable firing the onPageContentRaw event. Globally disabling the cache will behave as expected though.

I figured this out while forking the [anza/grav-plugin-filesource](https://github.com/anza/grav-plugin-filesource) plugin, because I thought there is a problem with it (the markdown/plugin:filesource code wasn't being processed, which happens in said event). See this [issue](https://github.com/anza/grav-plugin-filesource/issues/2) describing the problem also.

When I turn off global cache in the settings or clear the cache, the plugin starts working, with the frontmatter switch, it doesn't. So I guess the frontmatter switch is not being handled correctly by Grav?

cheers
Oh: debian 9, Grav v1.5.0-rc.1, php5-fpm, nginx-ee 1.10.3
Learn 2 Theme

**Comment by rhukster** [comment]
I can't replicate this. 

I tested it by enabling cache in the `system.yaml` file, then setting one page to `cache_enable: false`.  Then i put a breakpoint on line 649 (develop branch) where the `onPageContentRaw()` event is fired.  And it tripped on the breakpoint every page load for that page. So worked as expected for me.

![image](https://user-images.githubusercontent.com/1084697/43743089-b516f484-9991-11e8-9a57-9ddfb0544bc9.png)

**Comment by heavydetail** [comment]
Can you take a look at this short plugin code in question and tell me if the Event is handled correctly or did something change in Grav that rendered it non-functional? 

[Github/anza/grav-plugin-filesource/filesource.php](https://github.com/anza/grav-plugin-filesource/blob/master/filesource.php)

If it is actually the way it handles the event nothing needs to be done here, if it isn't: could you try replicating it by trying to use the filesource plugin, enable, let it load a test file and reload the same page. It should not be processed. It might also be some config issue on my side...
Which cache driver is being used when set to auto ?
