### ISSUE TITLE
[add resource] Grav Plugin Babel

### ISSUE THREAD

**Issue by leotiger** [getgrav/grav#2137]
I've made available a first version of the Babel plugin that allows to handle and maintain language definitions provided in plugins, themes, etc. in the Admin interface.

If the plugin suites I may add additional features and probably work with the GRAV team to allow integration into a shared language repository.

[Grav Babel plugin](https://github.com/leotiger/grav-plugin-babel)

**Comment by leotiger** [comment]
Fixed some bugs and added some improvements. Version 1.0.2 available.

**Comment by leotiger** [comment]
Version 1.0.3 available to make exports available as domain based language pack downloads.

**Comment by leotiger** [comment]
Version 1.1.1, released right now, fixes an issue with lists that did not respect their order on display and storage, e.g.

* January
* February
* November
* December
* March
* etc.

is now correctly managed as

* January
* February
* March
* ...
* November
* December

**Comment by leotiger** [comment]
Apart from this fix THEME variable are now tracked and language theme packages can be exported.

**Comment by rhukster** [comment]
Added to GPM
