### ISSUE TITLE
Tracking installed plugins/themes

### ISSUE THREAD

**Issue by tomzx** [getgrav/grav#214]
I haven't had the chance yet to look into the source for it, but it appears that installing plugins/themes through `gpm` does not store that information anywhere.

Here's my use case: I install a plugin, say "smileys". I want to be able to store that information in my git repository so that when I go about updating my website, it fetches the latest version of the plugin, or possibly a specific one.

I have two options here:
* Install the plugin through `gpm`, remove the `.gitignore` rules so that I can store all of the plugins file within my repository
* Write a shell script to run `gpm install smileys`, hopefully installing the package at a version that is compatible with the one I used so far (not really nice).

Thus, what seems to make the most sense, since `gpm` is `grav package manager`, would be that it stores the version it installed so that it may later on be reinstalled if needed.

**Comment by rhukster** [comment]
Grav already has support for a simple `.dependencies` file. We use this to help us build our packages or install gpm/symlinked plugins and themes.   Take a look at the blog skeleton file:

https://github.com/getgrav/grav-skeleton-blog-site/blob/develop/.dependencies

With this file in the root of Grav or in the `user/` you can run `bin/grav install` to install the packages. 

You can keep the updates by using GPM.

**Comment by tomzx** [comment]
@rhukster Is there any documentation about the .dependencies file?

**Comment by rhukster** [comment]
Not really. It's an internal development thing. If you want to use gpm the file is all you need and the blog skeleton is a good example.

**Comment by walutisme** [comment]
You can use `.dependencies` to build you own skeleton. Just read that example on blog skeleton, I think it easy to understand that file. Best use of this is if we can SSH to our server
