### ISSUE TITLE
HTML video with twig code is missing

### ISSUE THREAD

**Issue by JuneAhnFSP** [getgrav/grav#2141]
To whom it may concern

I'm trying to add a video on a page by using twig code below:

![](video.mp4)

it works on my localhost test but there are 404 error on server side testing.
on HTML, the video element's source is:
<source src="/user/pages/mypage/video.mp4">
in addition, the video is missing with url, 'myurl.com/user/pages/mypage/video.mp4' meanwhile, it works with 'myurl.com/mypage/video.mp4'.

I'm using the latest version GRAV and Microsoft Azure for hosting.
Am I missing some configuration detail?

**Comment by rhukster** [comment]
Cannot see the twig code.. please use code blocks.

**Comment by JuneAhnFSP** [comment]
oh sorry the twig code was
`![](video.mp4)`

**Comment by rhukster** [comment]
and what is the HTML output on each of your instances, local and remote?

**Comment by JuneAhnFSP** [comment]
Here is the HTML output
`<p><video controls="1" alt=""><source src="/user/pages/09.test/fsp-small.mp4">Your browser does not support the video tag.</video></p>`
