### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by jtbray** [getgrav/grav#2142]
Please add my new theme "Brilliant Resume" to the Grav Repository.

Project is here: https://github.com/jtbray/brilliant-resume

Thanks!
JTB

**Comment by rhukster** [comment]
Added to GPM

**Comment by rhukster** [comment]
You need to create a release to ensure it gets picked up.  https://learn.getgrav.org/advanced/grav-development#theme-plugin-release-process

**Comment by jtbray** [comment]
Here it is: https://github.com/jtbray/brilliant-resume/releases/tag/1.0.0

Just let me know if anything else is required... Thank you!

**Comment by jtbray** [comment]
updated the license and changelog and published the release...

can it get picked up now?

**Comment by rhukster** [comment]
Seems there's still a problem: 

```
jtbray/brilliant-resume                 Invalid or incomplete Blueprints:
                                         'icon' was expected but not found
```

**Comment by jtbray** [comment]
Icon was added to the blueprints & re-released.

Let me know if anything else please!

Thanks!

**Comment by jtbray** [comment]
Are there any other issues being logged?

**Comment by rhukster** [comment]
You should be good now.. there was a slight bug in our repo generating code that became apparent with a recent update to a vendor library that was causing everything to break.  This has been resolved.

**Comment by jtbray** [comment]
Great!

Thanks for all your assistance @rhukster!
