### ISSUE TITLE
/admin is a 404

### ISSUE THREAD

**Issue by gsalvatella** [getgrav/grav#2147]
When using lighttpd the admin page is not reachable (404 error). I'm using a naïve lighttp.conf with fastcgi in an arch linux distro. With apache there are no problems. According to [#915](https://github.com/getgrav/grav/issues/915) this could be due to rewriting issues, since lighttp doesn't use AllowOverride.

I do not fully understand how the "admin" page is generated, since there is no such page in the grav directory. Does the problem lie in the way this page is generated?

**Comment by rhukster** [comment]
Basically most URLs in side of Grav are based on URL rewriting.  This is standard for CMS platforms, and it works the same as WordPress for example.  In fact, you can use the same URL rewriting code that works for WordPress with Grav.

You've picked 2 things that are going to require research and more work.. arch linux + lighttpd.  If your new to this, i suggest using Apache as it 'just works' with the provided `.htaccess` file.

**Comment by gsalvatella** [comment]
Thanks for the insight. I nailed down what makes it work in apache. These three lines in .htaccess
```
# if requested file is not /index.php and doesn't match a physical file, rewrite to index.php
RewriteCond %{REQUEST_URI} !^/index\.php
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule .* index.php [L]
```
Without them apache throws a 404 again. The corresponding lighttp directives should be
```
url.rewrite-if-not-file = ( "^/grav_path/.*$" => "/grav_path/index.php" )
```
but it doesn't seem to work. I have seen that in `/user/plugins/admin/admin.yaml` there is a `route: '/admin'` directive, which I assume is what causes the redirection. My question is, which file is read when accessing admin? Is it admin.php? If so, accessing it directly in the browser throws an error (Grav/Common/Plugin not found) which is also reproducible in apache... I'm really confused on how I should debug this...

**Comment by ulfben** [comment]
I feel like lighttpd is common enough that this ought to be explained in the [troubleshooting section of the docs](https://learn.getgrav.org/16/troubleshooting/page-not-found). 

@gsalvatella here's what I did: enable mod_rewrite, add your rewrite-if-not-file rule, reload lighttpd and voila! It all worked. Keep an eye on the error log in case something else pops up (file permissions, or missing php modules for example). I use lnav for quickly browsing logs (hit E to jump to errors). 

```
# sudo nano /etc/lighttpd/lighttpd.conf

server.modules += ("mod_rewrite")
url.rewrite-if-not-file = ( "^/grav_path/.*$" => "/grav_path/index.php" )
```

`sudo /etc/init.d/lighttpd restart`

**Comment by ulfben** [comment]
Turns out [there is indeed a default config for lighttpd](https://github.com/getgrav/grav/tree/master/webserver-configs)! Again: that should probably be mentioned in the troubleshooting docs as well.
