### ISSUE TITLE
Date already parsed in Page::header

### ISSUE THREAD

**Issue by tomzx** [getgrav/grav#215]
In `\Grav\Common\Page\Page::header`, `$this->header->date` is already a unix timestamp. `strtotime` does not recognize unix timestamp and will return false. Later on, it will replace `$this->date` by `$this->modified`, which is incorrect.

```
if (isset($this->header->date)) {
    $this->date = strtotime($this->header->date);
}
```
Here is an example of a header with a date that is parsed to a unix timestamp:

```
---
date: 2013-01-05T08:12:11-05:00
---
```

**Comment by rhukster** [comment]
the page header date is not intended to be formatted like that, it's intended to be like this:

```
---
date: 17:34 07/04/2014
---
```

I've just tested it and it all works as expected

**Comment by tomzx** [comment]
@rhukster Why not provide support for it? After all, it is a standard date format ([ISO 8601](https://en.wikipedia.org/?title=ISO_8601)).

What is the purpose of limiting the parsing of date to a specific format when you use `strtotime` which supports a range of parsable date string? Is it to have a single supported format?

In the doc, you say

> Valid values are any string date values that strtotime() supports.

for both publish date and unpublish date.

http://learn.getgrav.org/content/headers#publish-date
http://learn.getgrav.org/content/headers#unpublish-date

However that is not true as they display the same issue (a unix timestamp passed to strtotime).

My suggestion would be to make it support any date format as well as the current one supported when you're parsing the header in `\Grav\Common\Page\Page::header`.
