### ISSUE TITLE
SMTP TLS problem with Email  v2.7.1

### ISSUE THREAD

**Issue by withindale** [getgrav/grav#2150]
Email plug-in works with SSL and no security but fails with TLS on port 587 at TMD Hosting - see below.

Ian Russell

Whoops\Exception\ErrorException thrown with message "stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number"

Stacktrace:
#23 Whoops\Exception\ErrorException in /home/codewayb/public_html/grav-site-1/user/plugins/email/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:94
#22 stream_socket_enable_crypto in /home/codewayb/public_html/grav-site-1/user/plugins/email/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:94
#21 Swift_Transport_StreamBuffer:startTLS in /home/codewayb/public_html/grav-site-1/user/plugins/email/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php:313
#20 Swift_Transport_EsmtpTransport:_doHeloCommand in /home/codewayb/public_html/grav-site-1/user/plugins/email/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:118
#19 Swift_Transport_AbstractSmtpTransport:start in /home/codewayb/public_html/grav-site-1/user/plugins/email/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php:79
#18 Swift_Mailer:send in /home/codewayb/public_html/grav-site-1/user/plugins/email/classes/Email.php:104
#17 Grav\Plugin\Email\Email:send in /home/codewayb/public_html/grav-site-1/user/plugins/email/email.php:99
#16 Grav\Plugin\EmailPlugin:onFormProcessed in /home/codewayb/public_html/grav-site-1/vendor/symfony/event-dispatcher/EventDispatcher.php:212
#15 Symfony\Component\EventDispatcher\EventDispatcher:doDispatch in /home/codewayb/public_html/grav-site-1/vendor/symfony/event-dispatcher/EventDispatcher.php:44
#14 Symfony\Component\EventDispatcher\EventDispatcher:dispatch in /home/codewayb/public_html/grav-site-1/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php:23
#13 RocketTheme\Toolbox\Event\EventDispatcher:dispatch in /home/codewayb/public_html/grav-site-1/system/src/Grav/Common/Grav.php:279
#12 Grav\Common\Grav:fireEvent in /home/codewayb/public_html/grav-site-1/user/plugins/form/classes/Form.php:729
#11 Grav\Plugin\Form\Form:post in /home/codewayb/public_html/grav-site-1/user/plugins/form/form.php:195
#10 Grav\Plugin\FormPlugin:onPageInitialized in /home/codewayb/public_html/grav-site-1/vendor/symfony/event-dispatcher/EventDispatcher.php:212
#9 Symfony\Component\EventDispatcher\EventDispatcher:doDispatch in /home/codewayb/public_html/grav-site-1/vendor/symfony/event-dispatcher/EventDispatcher.php:44
#8 Symfony\Component\EventDispatcher\EventDispatcher:dispatch in /home/codewayb/public_html/grav-site-1/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php:23
#7 RocketTheme\Toolbox\Event\EventDispatcher:dispatch in /home/codewayb/public_html/grav-site-1/system/src/Grav/Common/Grav.php:279
#6 Grav\Common\Grav:fireEvent in /home/codewayb/public_html/grav-site-1/system/src/Grav/Common/Processors/PagesProcessor.php:26
#5 Grav\Common\Processors\PagesProcessor:process in /home/codewayb/public_html/grav-site-1/system/src/Grav/Common/Grav.php:131
#4 Grav\Common\Grav:Grav\Common\{closure} in /home/codewayb/public_html/grav-site-1/system/src/Grav/Common/Grav.php:370
#3 Grav\Common\Grav:Grav\Common\{closure} in /home/codewayb/public_html/grav-site-1/system/src/Grav/Common/Grav.php:346
#2 call_user_func_array in /home/codewayb/public_html/grav-site-1/system/src/Grav/Common/Grav.php:346
#1 Grav\Common\Grav:__call in /home/codewayb/public_html/grav-site-1/system/src/Grav/Common/Grav.php:132
#0 Grav\Common\Grav:process in /home/codewayb/public_html/grav-site-1/index.php:52

/home/codewayb/public_html/grav-site-1/user/plugins/email/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php
        if (isset($this->_stream)) {
            switch ($param) {
                case 'timeout':
                    if ($this->_stream) {
                        stream_set_timeout($this->_stream, $value);
                    }
                    break;
 
                case 'blocking':
                    if ($this->_stream) {
                        stream_set_blocking($this->_stream, 1);
                    }
            }
        }
        $this->_params[$param] = $value;
    }
 
    public function startTLS()
    {
        return stream_socket_enable_crypto($this->_stream, true, STREAM_CRYPTO_METHOD_TLS_CLIENT);
    }
 
    /**
     * Perform any shutdown logic needed.
     */
    public function terminate()
    {
        if (isset($this->_stream)) {
            switch ($this->_params['type']) {
                case self::TYPE_PROCESS:
                    fclose($this->_in);
                    fclose($this->_out);
                    proc_close($this->_stream);
                    break;
                case self::TYPE_SOCKET:
                default:
                    fclose($this->_stream);
                    break;
            }
        }
Arguments
"""
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:\n
error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
"""

**Comment by rhukster** [comment]
Looks like a problem with your SSL lib version on your hosting provider.

**Comment by withindale** [comment]
Thank you, Andy.

Message from TMD below, FYI. I am passing your note back to them. SSL works
so we are using that.

However, upon testing this with the TLS method, it seems it responds with
the same error message you have provided, which seems to be caused by your
Grav-based website and how the PHP Hooks that establish a TLS Connection
work.

Unfortunately, we will not be able to assist you with resolving the issue
with the TLS Encryption, and you should contact an experienced web
developer for further assistance on the matter, but if you wish to have
your messages sent via an encrypted connection, you can always use the SSL
Method (465 Port).



Ian Russell

**Comment by rhukster** [comment]
Well, we're just using Swift email library, and the error comes from there.  Swift is the most widely used, and most robust email library available, so if it doesn't work with TMD, i'm going to bet the problem lies on their end, and not on Swift. :)

Glad you are able to use SSL though.

**Comment by withindale** [comment]
To avoid prolonging this agony I have just sent this suggestion to TMD:

As we have a solution (SSL instead of TLS) I suggest avoiding detailed
technical investigation by waiting until your version moves up from OpenSSL
1.0.2k (26 January 2017) to 1.0.2p (14 August 2018).

Ian
