### ISSUE TITLE
Truncator: encoding problems

### ISSUE THREAD

**Issue by dl4pj** [getgrav/grav#2154]
Hi,

Truncator::truncateWords has problems truncating texts with german letters.
In short summaries '?' signs are shown instead of "äöü".
Long texts are displayed correctly. 

I played around with the Truncator Source to find the source of the Problem.
htmlToDomDocument does not work correctly:
When I set $html = "äöü"; , the output in the Chrome-Browser are ?-signs.

The Problem exists in grave Versions 1.4.x and 1.5.

Thank you!

**Comment by dl4pj** [comment]
Hi,

is there any Information missing, I can help you with?
Are there any things, I can try?

Thank you,

Peter

**Comment by eisenherzz** [comment]
Seems that problem still exists.

**Comment by eisenherzz** [comment]
Seems to be environment dependant. Works on share hoster A and not on B. Did not find the difference yet. But basically I could narrow down the issue to `$html = mb_convert_encoding($html, 'HTML-ENTITIES', 'UTF-8');` For some reason umlauts get destroyed (sometimes)

**Comment by mahagr** [comment]
PHP version? Maybe some library?

**Comment by eisenherzz** [comment]
Many small differences starting with the OS (SunOS where it does not work vs. Linux).
Found a solution which at least worked for me. As I am not a developer somebody should review the change. Will commit it in a few second ;)

**Comment by mahagr** [comment]
You likely mean Solaris as SunOS hasn't been updated for 25 years now. BTW, you can also fix this with php.ini setting, but yeah, we should pass the encoding to the method.
