### ISSUE TITLE
NginX subdomain, /admin is 404

### ISSUE THREAD

**Issue by SeaSalvageUnit** [getgrav/grav#2157]
MY Nginx Setting
```
server {
        listen [::]:80;
        listen 80;
        server_name blog.mydomain.me;
        return 302 https://mydomain.me$request_uri;
}

server {
        listen [::]:443 ssl http2;
        listen 443 ssl http2;

        root /home/MYFOLDER/html/blog;

        index index.html index.php;

        location / {
                root /home/MYFOLDER/html/blog;
                try_files $uri $uri/ /index.php?$query_string;
        }

        location ~* /(\.git|cache|bin|logs|backup|tests)/.*$ { return 403; }
        location ~* /(system|vendor)/.*\.(txt|xml|md|html|yaml|yml|php|pl|py|cgi|twig|sh|bat)$ { return 403; }
        location ~* /user/.*\.(txt|md|yaml|yml|php|pl|py|cgi|twig|sh|bat)$ { return 403; }
        location ~ /(LICENSE\.txt|composer\.lock|composer\.json|nginx\.conf|web\.config|htaccess\.txt|\.htaccess) { return 403; }

        location ~ [^/]\.php(/|$) {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                if (!-f $document_root$fastcgi_script_name) {
                        return 404;
                }
                fastcgi_pass unix:/run/php/php7.1-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
                fastcgi_param SCRIPT_NAME $fastcgi_script_name;
                fastcgi_read_timeout 30;
        }

        include ssl.conf;
}
```

I read nginx document, grav-nginx conf file.
but i can't solve /admin 404 Not found error

i solved.

root@mydomain:/home/MYFOLDER/grav# bin/gpm install admin
The package admin is already installed, overwrite? [y|N] y

i can see admin page. wow!

**Comment by codlage** [comment]
I have a similar issue, at least I guess.

Did you try getting on others pages than the home ? I get a 404 error when I'm trying to access anything other than the homepage. Tried everything from the .conf file but can't make it works ...

**Comment by FrankGiesecke** [comment]
I have a similar issue.

But getting others pages than the `home` works fine. It seems to be a problem with the `admin` route.

**Comment by rhukster** [comment]
Not sure why you have two `server` blocks, but for things to work with subdirectories, the important thing is to ensure your `root` and `try_files` are correct.

In my test setup, i have a webroot on my raspberry pi of `/home/pi/www` (hence the root location below)

```
    ## Begin - Server Info
    root /home/pi/www/;
    server_name localhost;
    ## End - Server Info

    ## Begin - Index
    # for subfolders, simply adjust:
    # `location /subfolder {`
    # and the rewrite to use `/subfolder/index.php`
    location /learn {
        try_files $uri $uri/ /learn/index.php?$query_string;
    }
    ## End - Index
```

Inside this `www` folder I downloaded the `learn` skeleton and extracted it into `/home/pi/www/learn` and it works just fine with: `http://mysite.com/learn`

To test this I also installed the admin and it works just fine.

**Comment by devcomcool** [comment]
@codlage @FrankGiesecke @rhukster 
i solved.

root@mydomain:/home/MYFOLDER/grav# bin/gpm install admin
The package admin is already installed, overwrite? [y|N] y

i can see admin page. wow!

**Comment by christopher-bonitz** [comment]
Migrated a site today (tar compressed, moved, then extracted).
The site actually works, but the admin page is gone.

Tried to reinstall and update without luck.
So the 404 issue still exist.

Here are my nginx site config.
<pre>
server {
    listen         80 default_server;
    listen         [::]:80 default_server;
    server_name    mysite.net www.mysite.net;
    root           /var/www/mysite;
    index          index.html index.php;

    location ~* \.php$ {
    if ($uri !~ "^/uploads/")
    {
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }
        include         fastcgi_params;
        fastcgi_param   SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
    }

    listen 443 ssl; # managed by Certbot
    *more cert stuff*
    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    } # managed by Certbot

}
</pre>

**Comment by wallehxz** [comment]
I have some issue like you，use nginx with Server，

but rewrit server conf nginx in folder grav/webserver-configs/nginx.conf example，

this issue is run ok
