### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by ParitoshBh** [getgrav/grav#2158]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: https://github.com/ParitoshBh/grav-coder

_P.S - I have named the theme as `Grav Coder`, if in any way this violates any naming scheme please let me know!_

**Comment by ParitoshBh** [comment]
Is there something holding this up? If there's one please do share :)

**Comment by rhukster** [comment]
I've added this to GPM now... thanks.
