### ISSUE TITLE
Page::translatedLanguages(): contains slugs or routes

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#2163]
The documentation for Page::translatedLanguages() states:
> Return an array with the routes of other translated languages

However, the function returns an array with a **route** when the page has a default route defined, else it returns the **slug**. Which are quite different imho...

For example, let's assume we have the following folder structure:
```
.../pages/
     01.my/
        01.example/
           01.page/
```
- When the page has a default route defined, it returns the route.
With the following definition in frontmatter...
  ```
  routes:
    default: '/my/example/other-page'
  ```
  ...it returns the array: 
  ```
  [ "en" => "/my/example/other-page"]
- When no default route has been defined, it returns the slug for the page:
  ```
  [ "en" => "page"]
  ```

**Consequence**:
When looping through the results of $page->translatedPages() the different "route" types lead to unexpected results.
```
$translatedLanguages = $page->translatedLanguages();
foreach ($translatedLanguages as $language => $route) {
    // process $route ;
}
```

**Comment by rhukster** [comment]
Simple fix.

**Comment by pamtbaau** [comment]
@rhukster I'm not sure whether this issue should be closed, but maybe the below behaviour is by design...

When looking at the code for `Page::translatedLanguages()`, `$aPage->route()` will always be null, because a page created with ...
```
$aPage = new Page();
$aPage->init(new \SplFileInfo($path), $language . '.md');
```
... does not have a parent, and when there is no parent, `$aPage->rawRoute()` will always be null and `$aPage->route()` will always be null.

Considering:
- The slug always has a value, either derived from the folder, or from frontmatter.
- And, I presume, when a default route is added to frontmatter, it will be in the correct language of the page.

I would therefor, prefer the old behaviour of returning the slug or the default route set in frontmatter. Then the return value will be populated with routes/slugs in the proper language.
