### ISSUE TITLE
Throwing arbitrary error codes

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav#2164]
From within the Grav core code, I want to be able to emit an arbitrary HTTP status code. I'm told I *should* be able to do something like `throw new \RuntimeException("Should be a 406", 406);`, but that doesn't actually work.

I want to make changes to `Grav\Common\Twig\Twig.php`, specifically the `processSite` function. So I try the following:

```php
public function processSite($format = null, array $vars = [])
{
    throw new \RuntimeException("Should be a 406", 406);
    ...
}
```

What I get is an error page with a `status` header of `500`. I've tried tracing back where the status code gets set, but I can't find it. I would appreciate any assistance in understanding the lifecycle here. The earliest I can find is [the end of `index.php`](https://github.com/getgrav/grav/blob/756ddaa97db9daaa0c9bb697c2268cede6c3cc0d/index.php#L52-L58). But I can't find any code that triggers `onFatalException`.

**Comment by mahagr** [comment]
FYI: This is something that is limited by Whoops -- it will always use 500 errors in its responses. Overriding error handlers (especially for JSON) may be helpful, but requires some core changes.

**Comment by Perlkonig** [comment]
Well this gives me a place to look, at least. [`Whoops\Run` has a `sendHttpCode` function](https://github.com/filp/whoops/blob/45dad4e41eff66217626029f4172b04dc4025442/src/Whoops/Run.php#L203). I guess I'll start from there.

So does this mean that existing calls like [this](https://github.com/getgrav/grav/blob/1808fd3d6ed883a9ba5ee8c7d47f6b9350e54540/system/src/Grav/Common/Twig/Twig.php#L262) and [this](https://github.com/getgrav/grav/blob/a09c6b1088c13c85511eb415fb86eba815ad2856/system/src/Grav/Common/Processors/PagesProcessor.php#L39) in Grav core aren't actually working either?

**Comment by Perlkonig** [comment]
PR submitted.
