### ISSUE TITLE
Last-modified and Etag headers are expected to be more recent after changing the page templates but this does not happen

### ISSUE THREAD

**Issue by kirillaristov** [getgrav/grav#2168]
When page templates are updated, more recent headers Last-Modified and ETag are expected, but this does not happen.

Steps to reproduce:
1. load target page
1. record `etag` and `last-modified` for this target page
1. change any template *.html.twig for this target page
1. open target page in a new private window (for ensure that page are not cached)
1. compare `etag` and `last-modified` of past loaded target page and last loaded — they are identical. `Last-modified` is a date of last changed of the *.md file for target page.

**Grav calculating ETag and Last-modified, not webserver, and uses only content of the page:**
\system\src\Grav\Common\Grav.php (lines 248-257)
```php
// Set the last modified time
if ($page->lastModified()) {
	$last_modified_date = gmdate('D, d M Y H:i:s', $page->modified()) . ' GMT';
	header('Last-Modified: ' . $last_modified_date);
}

// Calculate a Hash based on the raw file
if ($page->eTag()) {
	header('ETag: "' . md5($page->raw() . $page->modified()).'"');
}
```

Thank you!

**Comment by rhukster** [comment]
It's not a simple task to know when the twig template is modified.  I'm sure this will require a custom twig extension or something.  Anyone know more about this?

**Comment by NicoHood** [comment]
I guess this is related to https://github.com/getgrav/grav-plugin-login/issues/264

I currently look through the etag code (it is not much it seems). To me it looks like that the mentioned lines above are not even executed by grav, when the browser (firefox > 80) loads the page (verified via missing logging entry). I sadly have not (yet) enough knowledge how etags are handled and why they are completely ignored for some reason.

**Comment by NicoHood** [comment]
@kirillaristov is this still an issue? For me the page always reloads on a template change. This is my cache setting:

```yaml
  expires: 3600
  cache_control: 'private, max-age=0, must-revalidate'
  etag: true
```

**Comment by mahagr** [comment]
Shouldn't be an issue as we fixed it.
