### ISSUE TITLE
Problem with file routes after upgrading to 0.9.30.

### ISSUE THREAD

**Issue by aradianoff** [getgrav/grav#217]
I used to be able to access .json files located in a page folder within a page  by opening `/route-to-page/name-of-file.json`. But now, I get, not an error page per se, but the source code of the 404 not found grav error page when I try to access those files. If I change the extension of the file to for example `.txt`, `.cvs`, or `.js`, then I can access the files. But with `.json` extension I can't, and I have no idea why...

**Comment by rhukster** [comment]
Try replacing the `fallbackUrl()` method in the Grav.php file with this:

```
protected function fallbackUrl($page, $path)
    {
        /** @var Uri $uri */
        $uri = $this['uri'];

        $path_parts = pathinfo($path);
        $page = $this['pages']->dispatch($path_parts['dirname'], true);
        if ($page) {
            $media = $page->media()->all();

            $parsed_url = parse_url(urldecode($uri->basename()));

            $media_file = $parsed_url['path'];

            // if this is a media object, try actions first
            if (isset($media[$media_file])) {
                $medium = $media[$media_file];
                foreach ($uri->query(null, true) as $action => $params) {
                    if (in_array($action, ImageMedium::$magic_actions)) {
                        call_user_func_array(array(&$medium, $action), explode(',', $params));
                    }
                }
                Utils::download($medium->path(), false);
            }

            // has an extension, try to download it...
            if ($uri->extension()) {
                $download = true;
                // little work-around to ensure .css and .js files are always sent inline not downloaded
                if (in_array($uri->extension(), ['.css', '.js'])) {
                    $download = false;
                }
                Utils::download($page->path() . DIRECTORY_SEPARATOR . $uri->basename(), $download);
            }
        }
    }
```

let me know if that works.  I know you will be able to reach the json with this, but the question is, does it work with the json being downloaded rather than being displayed inline?

**Comment by aradianoff** [comment]
It works! :+1: 
Thank you so much!

**Comment by rhukster** [comment]
I actually have a better option that i'm commiting now.  But will work in conjunction with that.  Basically adding some more 'types' as valid media files. 

Basically this:

https://github.com/getgrav/grav/commit/3af85ed14fa8fb9757b4f8562c95b39dbefb78ad
