### ISSUE TITLE
Error "This site can't be reached" due to twig_vars[] assignment

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#2174]
Was experience unexpected and irregular "This site can't be reached" errors lately when accessing Grav on my localhost. These errors lead to inaccessibility of any website using an IP4 address, no matter which browser being used.

After many reboots and tests, I narrowed it down to an assignment to the twig_vars array. Behaviour depends on size of array being assigned. At each request, an extra Apache process is started. After many repeats, the browser throws the error and not a single website using an IP4 address can be accessed. Only sites using IP6 (e.g. google.com) remain reachable.

Environment:
- Windows 10 (latest update)
- Windows Subsystem for Linux (Ubuntu 18.04)
- Apache/2.4.34 + PHP 7.2
- Websites are located outside Windows Subsystem for Linux

How to reproduce:
- Create new plugin using `$ bin/plugin devtools newplugin`
- Add method:
  ```
  public function onTwigSiteVariables()
  {
      // Language flag images count: 245, size: 126 KB total
      $flags = (new Media('user/plugins/language-switcher/images/'))->images();
      // $flags = array_slice($flags, 0, 2);
  
      $this->grav['twig']->twig_vars['languageswitcher'] = [
          'flags' => $flags,
      ];
  }
  ```
  Note: The twig variables are not used in any twig template.
- Use bash script to repeatedly run `wget`
  ```
  #!/bin/bash

  url='localhost/site-dev'

  for i in {1..100}
  do
     echo $i
     wget -qO- $url &> /dev/null
  done
  ```
When all flags (245, 126 KB) are assigned to twig_vars, a new Apache process is started on each request. When only a subset of the flags are assigned, no extra Apache process is started.

**Comment by rhukster** [comment]
What version of Grav are you running?  How did you install Apache + PHP?

**Comment by pamtbaau** [comment]
- Grav: v1.5.1
- Installed Apache + PHP using [this blog](https://medium.freecodecamp.org/setup-a-php-development-environment-on-windows-subsystem-for-linux-wsl-9193ff28ae83) ( w/o MariaDb and phpMyAdmin)

I will try and see if same issue arises when using XAMPP on Windows 10 outside Windows Subsystem for Linux.

**Comment by pamtbaau** [comment]
Issue does not arise using XAMPP. 

Performance difference is almost 3x better using XAMPP... Maybe that's because of the 5x more memory allocated to Apache. I will have a look at that.

In the mean time, I think I should switch back to XAMPP and use WSL only for the bash tools.

For now, I will close the issue since the root does not seem to be Grav at the moment.

**Comment by rhukster** [comment]
Ahh.. Good to know.. Would be nice to get a write up of the whole process for our docs. I think its a better idea to use WSL rather than XAMPP and other WAMP stacks.

**Comment by rhukster** [comment]
Need help documenting a Grav-centric WSL install on windows.

**Comment by pamtbaau** [comment]
I will be more then happy to create a doc on setting up WSL using Ubuntu 18.04, Apache, PHP 7.2 and XDebug to run Grav. I can also add some specifics required by Microsoft VS Code to debug Grav. 

What would be the easiest way for you to proceed?

**Comment by rhukster** [comment]
Best way is to fork the getgrav/grav-learn repo add th page under hosting guides and submit a pull request. https://github.com/getgrav/grav-learn

**Comment by pamtbaau** [comment]
Done: [PR 646](https://github.com/getgrav/grav-learn/pull/646)
