### ISSUE TITLE
SSL connect error (bin/gpm install devtools) - Too many redirects?!

### ISSUE THREAD

**Issue by iocron** [getgrav/grav#2177]
There are 302 redirections inbetween the source file, so the download/installation of the devtools (as described in the official documentation on https://learn.getgrav.org/themes/theme-tutorial) doesn't work. Error: 

Preparing to install DevTools [v1.2.1]
  |- Downloading package...    error                             
  |  '- Error while trying to download (code: 302): https://getgrav.org/download/plugins/devtools/1.2.1 
  |  '- Message: SSL connect error
  |  '- error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
  '- Installation failed or aborted.

The URL Redirections seem to cause those problems: 
https://getgrav.org/download/plugins/devtools/1.2.1 (Status 302) =>
https://github.com/getgrav/grav-plugin-devtools/zipball/1.2.1 (Status 302) =>
https://codeload.github.com/getgrav/grav-plugin-devtools/legacy.zip/1.2.1 (Status 200)

**Comment by w00fz** [comment]
Have you tried disabling the `verify_peer`setting or change the `method` between curl and fopen?

https://learn.getgrav.org/basics/grav-configuration#gpm
