### ISSUE TITLE
Call to a member function root() on null

### ISSUE THREAD

**Issue by tomzx** [getgrav/grav#218]
To reproduce:
* have a content file directly in the user/data/pages directory
* load the main page of your site
* see the exception

```
Whoops\Exception\ErrorException thrown with message "Call to a member function root() on null"

Stacktrace:
#0  in grav\system\src\Grav\Common\Page\Page.php:1632
```

**Comment by rhukster** [comment]
Yah, this is not supported, but I can fail quietly or in a more friendly way.

**Comment by tomzx** [comment]
:+1:
