### ISSUE TITLE
Forcing JSON withouth *.json

### ISSUE THREAD

**Issue by mgollmer** [getgrav/grav#2180]
Hello there, 

even if I run the risk that it has been asked in the past, but how do i force JSON as content type without adding ".json" to the url?

I'm trying to develop a plugin, where I need to set up an API. Is it possible to use some method/value in the Page object?

Regards, 
Michael

**Comment by Perlkonig** [comment]
[I had a PR related to this that ultimately died.](https://github.com/getgrav/grav/pull/1088) I'm now [working on fixing the arbitrary error code issue](https://github.com/getgrav/grav/issues/2164) and then I'm going to try issuing my PR again. I agree that Grav should be fully capable of understanding and responding to the `Accept` header, but currently I can't get the core to issue the appropriate `406 Not Acceptable` code.

**Comment by mgollmer** [comment]
Hi @Perlkonig, 

uuhhhh seems like I asked for a complex topic.  Is there a way to force the content type inside the coding? 

I mean yeah it would be nice if Grav would react on the `Accept` attribute of the header, but isn't there any other way?

**Comment by Perlkonig** [comment]
I had forgotten about that. We need to add that to the [Headers / Frontmatter page](https://learn.getgrav.org/content/headers), methinks.

**Comment by rhukster** [comment]
Definitely should add it... if someone wants to add it as a PR on learn, that would help! :)

**Comment by Perlkonig** [comment]
I will do my best.

**Comment by Perlkonig** [comment]
Sorry. [It's already there.](https://learn.getgrav.org/content/headers#template-format) Somehow I missed it.

So, @mgollmer, if indeed you want your page to *always* return JSON, just add `template_format: json` in your frontmatter and Grav will automatically apply the appropriate `*.json.twig` template.

**Comment by mgollmer** [comment]
UHHHH!!! Cool!

Thanks @rhukster! I must have scrolled over it. Just saw template, but not templateFormate. Thank you very much!
