### ISSUE TITLE
[add-resource] new Plugin

### ISSUE THREAD

**Issue by finanalyst** [getgrav/grav#2183]
Please consider my new plugin `map-leaflet`
It is an alternative to map-google using OpenStreetMap data and the leaflet js library
Project at https://github.com/finanalyst/grav-plugin-map-leaflet

**Comment by hughbris** [comment]
Besides being currently maintained, how does this differ from the [existing Leaflet plugin](https://github.com/magikcypress/grav-plugin-leaflet)?

**Comment by Perlkonig** [comment]
https://learn.getgrav.org/advanced/grav-development#abandoned-resource-protocol

**Comment by finanalyst** [comment]
My bad! I missed leaflet because I was looking for 'map'.
Extra value of my plugin:
a) Provision for other providers: MapBox and Thunderforest
b) Provision for Awesome-markers.
May be rename? to map-awesome-leaflet?

**Comment by hughbris** [comment]
> My bad! I missed leaflet because I was looking for 'map'.

Fair enough and pretty slack how the plugin didn't include the word "map" in descriptive fields. (Kids - this is why metadata matters!)

> Extra value of my plugin:
> a) Provision for other providers: MapBox and Thunderforest

Mapbox tiles or the full API? Definite positive either way.

> b) Provision for Awesome-markers. Current leaflet plugin cannot show markers although leaflet itself allows for one marker type to be added.
> 

hmm, pretty sure I've made multi-marker maps in the past using Leaflet only.

> May be rename? to map-awesome-leaflet?

Not sure given you've built something afresh.

**Comment by finanalyst** [comment]
> Mapbox tiles or the full API? Definite positive either way.
Mapbox provides styled tiles for the leaflet plugin. I have included in the config for the plugin five or so of the styles. I couldn't get all of the styles documented by MapBox to work with Leaflet, but maybe I was missing something.

MapBox has its own js library, with a different interface. So I used the leaflet interface and MapBox tiles. 

I prefer Thunderforest's map styling, for instance OpenCycle. But I developed this for a hiking website, so I use Outdoors.

> hmm, pretty sure I've made multi-marker maps in the past using Leaflet only.
Like I said before, Leaflet itself allows for markers. But what you do is create a map object that is associated with a div, then you create markers that you `addTo` the map. For this to work in a GRAV plugin, there has to be a way of generating the markers from the longitude/latitude (at the minimum) data. I do not see this in the current GRAV `leaflet` code.

So yes, you can use markers with Leaflet, but the GRAV leaflet plugin does not provide a way to do this.

My [a-markers] shortcode can contain a json array of hash which provide the data for each marker, and awesome-markers allows for each marker to have its own icon, title & color.

**Comment by jeremycherfas** [comment]
Wow. Thanks. This will help me a lot.

**Comment by finanalyst** [comment]
In my case I generate the JSON from the grav sqlite plugin, which can output in the required format for markers, namely a JSON array of hash, eg. `[ {"lng": 33, "lat": 33, "title":"cafe", "icon":"coffee }, {...}, {...}]`
You do this by creating the SELECT so that it names the columns, eg. `SELECT longitude as lng, ...`

My questions would be:
1. where would you have the geoJSON file? In a file on the server? 
1. geoJSON looks quite complicated whereas the markers need 'coordinates' (which can be taken from a geoJson file), a title, which is what you get when you hover on a PC or long press on a mobile (not sure which part of the geoJSON to use for this), icon or number to put on the marker (optional), but where can this be found? 
If there is a fairly general useage, I can modify the marker short code to handle this.

**Comment by finanalyst** [comment]
Given the name conflict and the difference between this plugin and the existing leaflet plugin, I am going to rename this plugin `map-marker-leaflet` and resubmit.
