### ISSUE TITLE
Incorrect routing on duplicate slashes

### ISSUE THREAD

**Issue by hundblue** [getgrav/grav#2184]
URL pathnames prefixed by duplicate slashes ('//', '///', ...) are incorrectly interpreted as absolute URLs. At present, the URL https://learn.getgrav.org//__FAKE_HOSTNAME__/content/routing
is resolved to
https://learn.getgrav.org/content/routing
This is caused by the `$bits = parse_url($uri);` asignment in [Uri.php](https://github.com/getgrav/grav/blob/bbc4fd6c79e734e54114b3524832f39798f89b7f/system/src/Grav/Common/Uri.php#L167).

**Comment by Perlkonig** [comment]
The word "incorrectly" implies that there's a "correct" way to interpret those slashes. But if you look at the [relevant](https://tools.ietf.org/html/rfc3986) [RFCs](https://tools.ietf.org/html/rfc7320), I can find no prescribed normalization of such slashes. Did I miss something?

So URI paths containing such are simply invalid, and the result of running such a URL through various tools is undefined. `parse_url` is a built-in PHP function. Grav can't do anything about it, short of rolling its own.

**Comment by mahagr** [comment]
URL starting with `//` is shorthand for the current protocol which is either `http://` or `https://`.

That said the behaviour you observed in the learn site is wrong, it should end up to 404 page.

**Comment by mahagr** [comment]
Confirmed this to be a bug in `Grav\Common\Uri` class. The issue isn't present on other libraries.
