### ISSUE TITLE
Bootstrap vulnerability in package-lock.json

### ISSUE THREAD

**Issue by goldjg** [getgrav/grav#2189]
GitHub flagged this when I setup my repo and commited Grav 1.5.1 to it:

Known moderate severity security vulnerability detected in bootstrap < 4.1.2 defined in package-lock.json.
package-lock.json update suggested: bootstrap ~> 4.1.2.

**Comment by rhukster** [comment]
Bootstrap is not in Grav itself, so this is probably something in a theme or plugin?  Please open the issue on the appropriate repo.  Cheers.

**Comment by goldjg** [comment]
Good shout - I didn't notice that but think it's the bootgrav theme - will check and raise there.
