### ISSUE TITLE
Honor the Accept-Language:nl from the client request

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav#219]
Browsers sometimes inform the client's preferred language choice. Grav could prefer the clients header request instead of the default from system.languages.supported (if that translation is existing). If the translation is not available, maybe fall back on the default in system.languages.supported.

But in case the client sets selects, through the LangSwitcher, another language than what's in the browser's request header, that session wide preference should get precedence if feasable.

**Comment by rhukster** [comment]
I like the idea of adding this when the language has not been specified.
