### ISSUE TITLE
Add custom script type?

### ISSUE THREAD

**Issue by devnewton** [getgrav/grav#2192]
Is there a way to add custom script type with addJS method?

Use cases: webgl shaders, PEG.js parser...

**Comment by Perlkonig** [comment]
You can of course add them directly to your theme. If you want to do it on a page-by-page basis, through a plugin for example, then here are a few good places to start:

* https://learn.getgrav.org/cookbook/plugin-recipes#how-do-i-inject-assets-like-javascript-and-css-files

* https://learn.getgrav.org/plugins/plugin-basics

* https://learn.getgrav.org/api#class-gravcommonassets

**Comment by devnewton** [comment]
Thank you.

The addJs method of \Grav\Common\Assets does not allow to set the type attribute of script ie I cannot do add the following in my [plugin](https://github.com/devnewton/grav-plugin-tribune) using Assets url resolution:

` <script id="peg" type="text/peg" src="..."></script>`

**Comment by Perlkonig** [comment]
I apologize for the misunderstanding. In looking over [the source code](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Assets.php), I don't see a way to do this [using `AddJs`](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Assets.php#L364), but I'm no expert. It's not necessarily surprising, though. The function is explicitly for JS assets and not generic. Clearly the key is [the `attributes` function](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Assets.php#L1173). But I don't see a way to override that array through `AddJs`.

There's a [`js` function](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Assets.php#L600) that accepts an `$attributes` array, but it's not called anywhere in that class, or anywhere at all, as far as I can see.

**Comment by rhukster** [comment]
So you need a custom `type` ? is the `id` required?

**Comment by devnewton** [comment]
Yes adding an id parameter would be useful.

**Comment by paulmassen** [comment]
Indeed, you can't really add a custom script type afaik.
I too had to do that for my SEO plugin and found a hack: https://github.com/paulmassen/grav-plugin-seo/blob/master/seo.php#L719

i.e: I'm closing the script tag, and manually add my own.

Hope it helps

**Comment by mahagr** [comment]
Generally all custom attributes should be handled, I've seen scripts using both id and type="application/json" for example.

**Comment by rhukster** [comment]
This is now possible in Grav 1.6:

```
{% do assets.addJs('yourscript.js',{'loading':'async defer', type:'text/peg'}) %}
```

**Comment by devnewton** [comment]
I dont see the type parameter on https://learn.getgrav.org/16/api :(

**Comment by mahagr** [comment]
The array can contain any HTML attributes, maybe it is needed to be said in the docs, @rhukster?

**Comment by rhukster** [comment]
Does need to be added to the docs..."Assets" section needs updating for 1.6
