### ISSUE TITLE
[add-resource] New Plugin and Skeleton

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#2193]
I'd like to add a [Timeline-plugin](https://github.com/OleVik/grav-plugin-timeline) and [Timeline-Skeleton](https://github.com/OleVik/grav-skeleton-timeline) to the GPM.

In short, it is a facilitated way of using pages as events in a timeline - created with PHP and Twig to allow for large hierarchies, relations, and customization. **Note: Dependency is set to Grav v1.6 to ensure PHP v7.1 is used. It will run on lower-version installations of Grav, but uses several dependencies which will not fall back gracefully to v5.6.**

**Comment by rhukster** [comment]
For skeleton you also need to create a pre-built package that includes latest Grav + Skeleton + Theme + Plugins + Config, etc.

https://learn.getgrav.org/advanced/grav-development#skeleton-requirements

**Comment by OleVik** [comment]
Added in [v1.0.2](https://github.com/OleVik/grav-skeleton-timeline/releases/tag/v1.0.2), it's the part of Skeletons I most often forget.

**Comment by rhukster** [comment]
Both added to GPM.
