### ISSUE TITLE
[add-resource] New Plugin: Smooch Chat

### ISSUE THREAD

**Issue by marshmn** [getgrav/grav#2195]
I would like to add my new plugin to the Grav Repository. It provides an integration with the smooch.io "Web Messenger" in order to provide a live chat facility for Grav sites.

Here are the project details: **marshmn/grav-plugin-smoochchat**
https://github.com/marshmn/grav-plugin-smoochchat/tree/master

**Comment by rhukster** [comment]
Added to GPM.
