### ISSUE TITLE
Recover files?

### ISSUE THREAD

**Issue by azraelkuan** [getgrav/grav#2199]
Hello, i have a question, how can i recover a page because i delete it by mistake on the admin page.
I have try to recover it using `extundelete` which can recover files by cmd `rm`, but i got nothing but only `images` and `caches`

**Comment by rhukster** [comment]
Currently no, it's your responsibility to maintain a backup of your files.  We are looking at integrating `revisions` though that will allow you to track and revert changes.

**Comment by azraelkuan** [comment]
thanks，I have done a backup.
