### ISSUE TITLE
gpm not seeing v0.9.31 for self-upgrade

### ISSUE THREAD

**Issue by ritchiedalto** [getgrav/grav#220]
running 0.9.30, executing bin/gpm selfupgrade yields:
You are already running the latest version of Grav (v0.9.30) released on Wed Jul  8 19:43:55 2015

any reason it's not seeing 0.9.31 ?

**Comment by rhukster** [comment]
Grav caches GPM responses for one day.  You can clear the GPM cache, and re-run it:

Try this:

```
$ bin/grav clear --all
$ bin/gpm selfupgrade
```

**Comment by w00fz** [comment]
FYI You can also run any GPM command with the `-f` or `--force` argument which basically forces a refetch of the repository overriding the cached one.

```
$ bin/gpm index -f

**Comment by ritchiedalto** [comment]
Thank you :)
