### ISSUE TITLE
[bug] Inconsistent assets.addJs execution on pages 

### ISSUE THREAD

**Issue by ganar** [getgrav/grav#2200]
Both `assets.addJs`and `assets.addCSS` fail intermittently when used in pages with TWIG activated.
Sometimes the code will work, sometimes it doesn't. Weird.

``````
 {% do assets.addJs('theme://js/form_ux.js', {group:'bottom'}) %}

``````

**Comment by rhukster** [comment]
More than likely this is a caching issue.. When the page content is cached, it's not processing the twig.. So just make sure you have `never_cache_twig: true` set in your page frontmatter.

https://learn.getgrav.org/content/headers#never-cache-twig

BTW, i'm knee deep in a refactor of Assets manager for Grav 1.6 which should improve flexibility.

**Comment by ganar** [comment]
I'll try that, @rhukster, thanks a lot for the tip. It's difficult to keep up with this kind of behavior sometimes.
