### ISSUE TITLE
Different domain for /login

### ISSUE THREAD

**Issue by katsil** [getgrav/grav#2203]
Hey!
Is there any way to use something like **auth.domain.com** instead of **domain.com/admin** or /login page? Thanks for reply.

**Comment by rhukster** [comment]
Never tried that!  I guess it could be done with webserver rewrites, but that's really outside the control of Grav itself.

**Comment by katsil** [comment]
so you mean that i can do it by apache rewrites, but you don’t recommend me do that because of security reasons?
