### ISSUE TITLE
[bug] Bug in TinyMCE Editor Integration v1.2.0 with Grav 1.5.1 + Gantry v5.4.26

### ISSUE THREAD

**Issue by Legolasindar** [getgrav/grav#2204]
**GRAV:** 1.5.1
**GANTRY:** 5.4.26
**TinyMCE Editor Integration:** 1.2.0

My site works well, not problem. Today, i updated TinyMCE Editor Integration to 1.2.0 version, and after this, the Recompile CSS option of Gantry not works, say this:

```
500 Internal Server Error
Oops, UniformResourceLocator: Absolute stream path with relative lookup not allowed ().
```

I tried disabling the TinyMCE plugin, and works again. I tried in another site in another hosting, and the same situation. Before uptade, works well, after update, nots works.

**Comment by rhukster** [comment]
This seems to be more a Gantry issue than Grav.  Please open on the issue on the Gantry repo.
