### ISSUE TITLE
[add-resource] New Plugin: Quando

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav#2206]
I would like to add a new plugin to the Grav Repository.

It's for publishing business opening and service hours, often one of the main things I want to find out from a front-facing business's website. Here are the project details with full documentation: https://github.com/hughbris/grav-plugin-quando

Thanks!

**Comment by hughbris** [comment]
Oh fudge, the version in the blueprints file is out of sync :/ Clearly I need a process.

**Comment by rhukster** [comment]
Added to GPM
