### ISSUE TITLE
Install of 0.9.31 issue - .dependencies file

### ISSUE THREAD

**Issue by ritchiedalto** [getgrav/grav#221]
Downloaded the [0.9.31 full version .zip](https://github.com/getgrav/grav/releases/download/0.9.31/grav-v0.9.31.zip) (not the update file) from the [releases page](https://github.com/getgrav/grav/releases) and unzipped in a clean dir. Set all file and dir permissions appropriately. Executing `bin/grav install` yields:

```
ERROR Missing .dependencies file in user/ folder
ERROR invalid YAML in .dependencies
```

Although I can't find it in the changelog, I thought I remember seeing a note somewhere that `.dependencies` was moved from `/user/` to the grav root. So I downloaded the [.dependencies](https://raw.githubusercontent.com/getgrav/grav/develop/.dependencies) file from the grav repo itself and put it in my grav root. Executing the install was then successful. 

So to me it looks like:
1. The .dependencies file is missing from the release .zip file
2. The error message for the missing file is incorrect

**Comment by rhukster** [comment]
Does sound like the `.dependencies` file is getting stripped out.  That's odd because it never did before.  I will investigate. In the meantime, you can download the pre-packaged version from the github downloads, or from getgrav.org: http://getgrav.org/downloads

Cheers.

**Comment by rhukster** [comment]
The full version from the grav downloads page, or from GitHub releases is already **pre-packaged** with all required plugins and antimatter theme, and you don't need to run `bin/grav install`.  That is for building from the GitHub sources only.

**Comment by ritchiedalto** [comment]
Oh, had no idea. Well if nothing else, maybe an update to the docs would be helpful :)

**Comment by rhukster** [comment]
These are the current docs for installation: http://learn.getgrav.org/basics/installation

If you have suggestions on how I could improve the wording to make things more obvious, I would definitely be interested in doing that.

**Comment by ritchiedalto** [comment]
Ah yeah, looks good, obviously I was doing the second method for so long that I made an assumption on the install procedure without re-checking the docs. Sorry dude.
