### ISSUE TITLE
fix for webm files not recognized - - implement in next GRAV update?

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav#2219]
This is an old bug discovered and highlighted last year on the forums by 'mos0711'
https://discourse.getgrav.org/t/issue-with-webm-video-files-due-to-incorrect-default-configuration/4889/5

to quote mos0711

> After some investigation, I’ve found out that there seems to be a typo in the default configuration of media types which ships with GRAV.
> 
>   webm:
>     type: file
>     thumb: media/thumb-webm.png
>     mime: video/webm
> Should rather be:
> 
>   webm:
>     type: video
>     thumb: media/thumb-webm.png
>     mime: video/webm
> At least - if I change the type from text to video, everything seems to work properly. 

Suggest the default media.yaml needs that typo ironing out?!

//

Next thing to check is a way to get my preferred html5 video solution working, ie .webm for all browsers except Safari, with fallback .mp4 for Safari!

**Comment by rhukster** [comment]
You know you can edit the file directly in GitHub here, and it will create a Pull Request :)

**Comment by MattAppleton** [comment]
Sorry, will do!

**Comment by MattAppleton** [comment]
pull request submitted! Slowly getting the hang of Git!

**Comment by rhukster** [comment]
This is merged..
