### ISSUE TITLE
Update behaviour

### ISSUE THREAD

**Issue by roelfrenkema** [getgrav/grav#2225]
I love GRAV, best thing I ever seen exept  for the sites I programed myself of course. What really bugs me is that during theme updates the pages directory is destroyed (read renamed), instead of having the themes new demo pages in the theme directory where they IMHO belong as documentation.   

An other thing that bugs the s%&*t out of me is the picture cache being destroyed. Having a few galeries means that I have to call those pages to repopulate the cache or my users will think the site is malfunctioning because that takes some time to build.  Please leave the image cache and the pages directory alone. **PLEASE**

**Comment by rhukster** [comment]
That behavior you are seeing with the pages directory when updating themes is definitely not normal. 

The theme should simply install over the existing theme in the `user/themes/` directory.  Nothing should touch the pages directory, nor have I ever heard of anyone seeing this behavior.  So that's truly odd.  It could be the 'demo' pages, which again is not commonly used, so maybe it's a bug specifically with that.  What theme are you using and how are you updating (cli/admin)???

Regarding the image cache being cleared, there is a system setting to ensure the default cache clearing does not clear out processed images:

```
cache:
  clear_images_by_default: false
```

**Comment by roelfrenkema** [comment]
I will I keep an eye out on the next update. Anyway to lug whats going on when it updates the theme???

**Comment by paulhibbitts** [comment]
Hi @rhukster , I have now been able to duplicate this issue of the `Pages` folder being unexpectedly re-written during a theme update via the CLI.

Step to reproduce:

1) Install a theme with a `_demo` folder (but do not install the demo content)
2) Lower the Blueprints ver. # to force an update for a theme update
3) Once complete, you should notice a new `Pages` folder, and an archived `Pages` folder called something like `pages.12-21-2018-17-26-33`

Please let me know if you need any more info or need more details etc.

Thanks very much,
Paul

**Comment by quartelmestre** [comment]
Hi, @paulhibbitts . After your comments in the getgrav forum, I did my daily update routine on my servers. There was indeed a theme update. In one of the servers, I updated the theme through the Admin panel, and no pages were changed.

In another server, I used the command line interface 

        ```bin/gpm update``` 

Here, the update process moved the pages directory to a time-stamped new directory (pages.05-06-2019-09-00-36) and created a new pages directory with only the theme demo content.

Screenshots follow. I hope this may be useful.
![DeepinScreenshot_select-area_20190506060023](https://user-images.githubusercontent.com/20466765/57216493-5ca47400-6fc6-11e9-8c4c-9d4dbc148bf7.png)
![DeepinScreenshot_konsole_20190506060129](https://user-images.githubusercontent.com/20466765/57216510-64641880-6fc6-11e9-97f0-3a012c9fcaf8.png)

**Comment by paulhibbitts** [comment]
Thanks very much for the screen caps @quartelmestre  - @rhukster I hope this helps track down this issue of the pages folder being replaced during a CLI theme update.

**Comment by rhukster** [comment]
I think this is not the same as the original issue? Sounds like the issue might be demo content installing over existing content during an update? Please create a new issue for this.  Cheers!

**Comment by paulhibbitts** [comment]
Thanks Andy, as requested I've created a new issue for this #2493
