### ISSUE TITLE
Upgrade to latest beta + Call to undefined method Grav\Common\Utils::checkFilename()

### ISSUE THREAD

**Issue by chossimbaone** [getgrav/grav#2226]
Hi.
I have a 1.6.3 beta1 site running, and am currently trying to edit media on a page. I do however get this error
 Call to undefined method Grav\Common\Utils::checkFilename()
my 
system/src/Grav/Common/Utils.php does not have this function.
I cannot upgrade to latest beta via the admin webpage. Is there a safe way to upgrade manually?

**Comment by rhukster** [comment]
Several ways. Easiest is to set the release level to testing in system config and check for updates.  

That should have b3 show up.  Alternatively you can download the grav update package from the releases section of github and use direct install to update.

**Comment by chossimbaone** [comment]
Super. Thankyuo for the quick reply. Maybe release level should be set to testing in the beta.zip on the download page.
I am up and running.
Thank you.
