### ISSUE TITLE
Oddities in sorting pages

### ISSUE THREAD

**Issue by DebuggeR94** [getgrav/grav#2228]
If we have a collection of pages sorted by folder names, like:
```
parent page:
   01.child_page_1
   02.child_page_2
   03.child_page_3
```
For example, a category and articles in it. And we edit any page, for example the second, this page starts to be displayed last in the list of pages. Until we again change it a position in Ordering-> Sortable Pages.

Code in parent page:
``` Twig
<!-- some code... -->
{% for child in collection %}
   {% include 'partials/page_category.html.twig' with {page: child} %}
{% endfor %}
<!-- some code... -->
```

The strangeness is that after editing the page, the folder name remains at the position, but for some reason it starts to appear last.

---
Grav v1.6.0-beta.3
Admin v1.9.0-beta.3

**Comment by rhukster** [comment]
What is the sort order of your collection as defined by the page's frontmatter?

**Comment by DebuggeR94** [comment]
I tried to repeat the problem step by step and found out what the problem was, in the parent page there was an ordering by date. I was misled by this. When in the parent page, sorting by date, "Folder Numeric Prefix" in the child pages works. I think it is better to disable this option for pages whose parent order not by folder.
