### ISSUE TITLE
More templates?

### ISSUE THREAD

**Issue by GalacticSun** [getgrav/grav#2229]
I love Grav, and forgive me if this is the wrong place to post this, but is there any way to get more free Templates / Themes for Grav?  Maybe you guys could hold a contest or something?  One of the biggest attractions for new users seems to be variety of templates for newbies and people checking it out - at least I know I ran across this challenge when setting mine up: I couldn't find a healthy selection of both free and paid templates / themes for Grav.  Thanks and keep up the great work.

**Comment by dimitrilongo** [comment]
did you see https://getgrav.org/downloads/themes you can find 103 themes and [here](https://getgrav.org/downloads/skeletons) 43 skeletons, about themes I can the 12 themes released in the last 4 weeks !!!! [Here : A curated list of awesome stuff to do with Grav](https://github.com/getgrav/awesome-grav)

**Comment by GalacticSun** [comment]
Well, sorry, I guess I was expecting more, coming from the world of Wordpress.  Maybe I can create some.
