### ISSUE TITLE
[add-resource] New Theme/Skeleton: Hola

### ISSUE THREAD

**Issue by Dzi0nek** [getgrav/grav#2238]
Hello,
I would like to add a new theme and skeleton to Grav Repository.

https://github.com/devlom/grav-skeleton-hola
https://github.com/devlom/grav-theme-hola

Hola is a modern and stylish vCard website template. Designed to be a resume, vCard, portfolio template, it’s the perfect template for creative designers, developers, freelancers, photographer or any creative profession.

**Comment by rhukster** [comment]
Added to GPM

**Comment by davidmuc** [comment]
Hello @rhukster, the hola theme shows up in the themes section of the GPM, but unfortunately not yet in the skeleton section (https://getgrav.org/downloads/skeletons). Both the skeleton and theme are being provided by @Dzi0nek. 
As the skeletons are extremely helpful for less experienced users: any chance to also include the hola skeleton to GPM?

**Comment by rhukster** [comment]
I get an error from GPM:

```
devlom/grav-skeleton-hola               Blueprints: Not Found
```

**Comment by davidmuc** [comment]
@rhukster, should be fixed by now, thanks to @Dzi0nek.

**Comment by hexplor** [comment]
Fixed. Closing.
