### ISSUE TITLE
Wrong character before manual break

### ISSUE THREAD

**Issue by giansi** [getgrav/grav#224]
Hi,
there's an issue with blog listing when adding a manual break. Look at the image:

![grav](https://cloud.githubusercontent.com/assets/13077519/8678409/bb0c80b6-2a54-11e5-96f3-b2f4f9c8c88e.jpg)

Here's my page definition:

    ---
    title: Come è strutturata una pagina web di Grav CMS
    taxonomy:
        category: blog
        tag: [grav, cms, pagina web]
    metadata:
        description: Viene spiegato in dettaglio come è strutturata una pagina web per essere usata con Grav CMS
    date: 07/04/2015
        
    highlight:
        theme: railscasts
    --- 
    
    Ogni sito web è costituito da una serie di pagine collegate tra loro. Ogni pagina contiene diverse informazioni che il gestore del sito riempie di contenuti. Vediamo come Grav gestisce questo tipo di entità.
    
    ===
    
    Le pagine in Grav

**Comment by rhukster** [comment]
I'm not seeing this on my test.  What do you have for your summary configuration details in your `site.yaml`

**Comment by giansi** [comment]
I've not configured that option in my config, so it's the inherited default one

**Comment by rhukster** [comment]
Can you paste your full page in a code block.  I wonder if its something to do with utf-8 character counts.

**Comment by giansi** [comment]
Sorry I don't understand what do you mean with "in a code block": do you want I paste it here?

**Comment by rhukster** [comment]
actually can you just zip up your entire `user/` folder and give me a link to that so I can get a copy of your site on my local?

**Comment by giansi** [comment]
https://dl.dropboxusercontent.com/u/65902327/user.tar.gz

**Comment by rhukster** [comment]
Thanks! Strangely enough I only see this with PHP 5.6.  with php 5.4 and 5.5 it seems fine. Digging in!

**Comment by rhukster** [comment]
Ok try this fix... should be fine.

**Comment by giansi** [comment]
Yes, it works! Thank you.
