### ISSUE TITLE
Option to add additional attribute types to media files with .html() 

### ISSUE THREAD

**Issue by apokaliptis** [getgrav/grav#2240]
Hi, I'm currently using the following code to display an image of product on a site I am working on,
```
{{ page.media.images|first.html(page.header.title,'product-image')|raw }}
```
And I would like to add the [microdata](https://schema.org/) attribute `itemprop="image"`. The  problem is that the media function `.html()` doesn't provide a way to do this according to the documentation. Rather than having to rewrite my code to manually create the desired HTML tag, it would be convenient to able to to do something like:
```
some-image.html('title of image', 'alt-text', 'class', 'custom-attribute="custom-value")
```

**Comment by rhukster** [comment]
I think at this point you are better off just building the HTML and using the media `.url()` method to get the actual URL of the image.

**Comment by apokaliptis** [comment]
Fair enough. I was able to achieve the desired html by writing the following, which ended up being more concise anyways.:
```
<img class="class" itemprop="image" src="{{ page.media.images|first.url }}" alt="{{ page.header.title }}." />
```
