### ISSUE TITLE
Redirect code gets rendered when original URL contains parameters

### ISSUE THREAD

**Issue by jlehtinen** [getgrav/grav#2247]
Redirects with redirect code (for example /someurl: '/otherurl[301]') fail when the url contains additional parameters.

To replicate:

- Create redirect `/someurl: '/otherurl[301]'` in `/user/config/site.yaml`
- Navigate to `/someurl?utm_source=adroll`
- Resulting URL will be `/otherurl[301]?utm_source=adroll`

**Comment by rhukster** [comment]
I have a feeling this is just a matter of setting up the redirect to take params into account.  Pretty sure this came up before, but the redirect settings are simply regex match/replace...  I will test and find an example of how to resolve.

**Comment by rhukster** [comment]
Actually just realized you were talking about the `[301]` code specifically.  This does not work in **site** redirects because that redirect code is a regex.  That ability to pass a code is for **page** redirects only. https://learn.getgrav.org/content/headers#redirect

**Comment by jlehtinen** [comment]
Ah, well that would explain it. On the other hand, I see no reason to just set the default redirect to 301, so will do that. Thank you and apologies, as the common saying goes in Finland!
