### ISSUE TITLE
config: Auto metadata from Exif:  throwing error when switched on

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav#2248]
This error has been tested on a completely vanilla / untouched install of Grav v1.5.3 - Admin v1.8.12

If we add an image WITH a metadata description / creator / keyword using the admin in 'normal' mode it throws an error like this, and the image doesn't appear to view...

`Opening file for writing failed on error fopen(user://...@2x.jpg.meta.yaml): failed to open stream: "\RocketTheme\Toolbox\StreamWrapper\ReadOnlyStream::stream_open" call failed`

adding a keyword-less file is fine and doesn’t prompt errors if added to a page…!  Seems like a bug or  am I being daft?!

if we click out of the page and back in in 'expert' mode (not 'normal' mode) the page does seem to behave OK though...

![screen shot 2018-11-01 at 20 05 59](https://user-images.githubusercontent.com/6295710/47877339-94621180-de13-11e8-8378-caa33ae8c899.png)

**Comment by rhukster** [comment]
I will look into this.

**Comment by rhukster** [comment]
Can you please upload an image (or email me one) that is causing the issue. I just tested a sample image and it worked. 

NOTE: You have to 'save' the page first before the metadata file is created.

<img width="834" alt="image 2018-11-03 at 2 47 44 pm" src="https://user-images.githubusercontent.com/1084697/47957225-8af1ba00-df77-11e8-8686-19c8590ebb07.png">

original: 

![canon_digital_ixus_400](https://user-images.githubusercontent.com/1084697/47957227-904f0480-df77-11e8-9133-f043a766e1ea.jpg)

**Comment by rhukster** [comment]
Also works for me if i append `@2x` for a retina image.

**Comment by MattAppleton** [comment]
Will do, just firing up my testbed so I can check exactly what was throwing the error.

**Comment by MattAppleton** [comment]
![johnspinks_ble0427g_05 2x](https://user-images.githubusercontent.com/6295710/47957788-ad55f880-dfb4-11e8-94f3-a00aa2bc34e7.jpg)

**Comment by MattAppleton** [comment]
this image has 'landscape' in the keyword IPTC core metadata

**Comment by MattAppleton** [comment]
If I add it via the admin to GRAV I get various error screens like this...

![screen shot 2018-11-03 at 22 05 57](https://user-images.githubusercontent.com/6295710/47957817-0160dd00-dfb5-11e8-81c6-be2cafcac692.png)

**Comment by MattAppleton** [comment]
There problem occurs when I hit 'save', then the red error screen persists. I am able to see that the file has been ingested looking at the .md feel, but the 'normal' admin and page media field shows no image content at all. And no metadata.yaml feel is added to the relevant folder.

**Comment by MattAppleton** [comment]
Andy  

 - -selection of photos all of which throw errors when uploading, but ONLY if the exif feature is toggled ‘ON’… each one has a keyword plus usual basic metatdata.

**Comment by MattAppleton** [comment]
OK, so trying to unpick this further...

On a Linode  / Serverpilot box running 
Grav v1.6.0-beta.4 - Admin v1.9.0-beta.4 (fresh install this evening)
PHP Version 7.2.11
EXIF Version | 7.2.11

I get the aforementioned errors when operating via the Admin plugin interface (ie adding images via admin interface) - - this is ONE exampel of the error message panels thrown, the other wont let me copy/paste
"Opening file for writing failed on error fopen(user://...@2x.jpg.meta.yaml): failed to open stream: "\RocketTheme\Toolbox\StreamWrapper\ReadOnlyStream::stream_open" call failed


on an older install
on SAME Linode Serverpilot box running 
 Grav v1.4.0-rc.1 - Admin v1.7.0-rc.2
PHP Version 7.2.11
EXIF Version 7.2.11
I DONT get these errors... ?!


install 1 (exif problems, seem to bit intermittent after a break though, ie if I come back later I can 'see' the image in the admin): 
https://private.modernactivity.com/GRAV/

install #2 (no problems
https://sandbox.modernactivity.com/grav-admin_Feb_base/

**Comment by MattAppleton** [comment]
Had a moment to check in on thi again. If I revisit the site admin on install #1 (https://private.modernactivity.com/GRAV/) on a different machine ./ new session, I do NOT get an error in admin view, I can see the image in the relevant post/.page.

BUT if I try adding a new image to a new page I get the same issue, red error opens and an 'invisible' image that has beed added to the site, but not been recognized by the admin, with no meta.yaml generated...

![screen shot 2018-11-06 at 20 55 27](https://user-images.githubusercontent.com/6295710/48093235-bccc8000-e206-11e8-8f2b-d84457b6ee37.png)
![screen shot 2018-11-06 at 20 55 10](https://user-images.githubusercontent.com/6295710/48093238-bfc77080-e206-11e8-9f23-49659b0592a7.png)

**Comment by MattAppleton** [comment]
If I then clear cache / refresh and revisit the page in admin, it does work. Interestingly, it is only at that point that the meta.yaml is generated, so soem time AFTER the image is added...

![screen shot 2018-11-06 at 21 01 29](https://user-images.githubusercontent.com/6295710/48093417-28165200-e207-11e8-8f67-6a455976d464.png)

**Comment by MattAppleton** [comment]
thanks for looking at this...

just ran latest Quark update on install #1, issue still live tho'

**Comment by MattAppleton** [comment]
Hi there — perhaps this is something being looked at with GRAV 2, but just wanted to say that the latest stable GRAV / Admin plugin / Quark still gives us the issue (red panel, disappearing images in admin) when eddying images with IPTC metadata.


And trying the same procedure with 

Grav v1.6.0-beta.6 - Admin v1.9.0-beta.6 - latest beta Quark - - same issue when adding images with embedded metadata...

**Comment by MattAppleton** [comment]
Hullo

I am still getting the same 'red panel on upload' errors when trying to add an image with keyword metadata: https://private.modernactivity.com/GRAV/test-pic_tues_02

As before, clearing cache and refreshing seems to help. But the issue is driving clients mad, as they want to keep using caption functions that express caption info held on the image file itself!

untouched plain install of **Grav v1.6.0-rc.3 - Admin v1.9.0-rc.3**

**Comment by MattAppleton** [comment]
the 'stable' install does NOT encounter the issue still
Grav v1.4.0-rc.1 - Admin v1.7.0-rc.2

BUT when going to 
**Grav v1.5.8 - Admin v1.8.19**

Image error panel appears when uploading keyword-tagged image.

**Comment by rhukster** [comment]
I'm not seeing your error, but see something else.  Which I've fixed locally with a one liner.  

In `system/src/Grav/Common/Page/Media.php` around line 159 you whould have something that sets the `$meta_path` variable.  before add that, add this code to get full file path:

```
            // Get full file path
            $file_path = Grav::instance()['locator']->findResource($file_path);

            // metadata file
            $meta_path = $file_path . '.meta.yaml';
```

**Comment by rhukster** [comment]
Ok, try this, around line 174 in `system/src/Grav/Common/Page/Media.php`, replace the existing if statement with this

```
                    if ($meta_trimmed) {
                        $full_meta_path = Grav::instance()['locator']->findResource($meta_path, true, true);
                        $file = File::instance($full_meta_path);
                        $file->save(Yaml::dump($meta_trimmed));
                        $types['meta']['file'] = $meta_path;
                    }
```

**Comment by MattAppleton** [comment]
@rhukster — Amazing work Andy, thus far it has solved exif-related media upload issues on my testbed install, will try it on a few other instances...

**Comment by MattAppleton** [comment]
just to say - -my recent testing checks out well, I think this issue solved, great work with current v1.6!

**Comment by rhukster** [comment]
Phew, saw this come in and thought it was a new issue!

**Comment by bricebou** [comment]
Hi,

It finally works both on localhost and on a shared hosting... But I don't know it it's the change of the if statement mentioned below or anything else... 
And there are several unknown causes :
- definitely an issue with cache : I have to clear the cache for the exif metadata to be accessible ;
- it seems I can't make exif auto metadata alongside with the Admin Addon Media Rename.

I'm using the latest stable Grav + Admin plugin package, on a local Debian Buster ; all requirements are "green" in the Tools > Reports page.

By the way, it seems that the conversion from coordinates in degrees to decimal values are quite buggy...
