### ISSUE TITLE
[remove-resource] Course Hub Grav Bootstrap theme

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#2249]
Now that the new Bootstrap4 Open Matter theme has been available for the past several months, I think it's time to retire and remove the old Bootstrap3 theme:

https://github.com/hibbitts-design/grav-theme-course-hub-bootstrap

Thanks very much,
Paul

**Comment by rhukster** [comment]
Will get to this over the weekend (hopefully)

**Comment by rhukster** [comment]
done.

**Comment by paulhibbitts** [comment]
Thanks very much Andy!
