### ISSUE TITLE
bin/grav backup does not create image folder

### ISSUE THREAD

**Issue by MatthiasKauer** [getgrav/grav#225]
Hi,
title (almost) says it all.
I'm running a grav installation I downloaded yesterday. 0.9.32, I believe.
```
matthias@rp3deb:~/www/grav$ bin/grav --version
Grav CLI Application version 0.1.0
matthias@rp3deb:~/www/grav$ bin/grav backup
Creating new Backup "/home/matthias/www/grav/backup/Woo-20150716002131.zip"
mv backup/Woo-20150716002131.zip ~/tmp
cd ~/tmp
unzip Woo-20150716002131.zip -d grav
cd grav
php -S localhost:8000
```

![screenshot_2015-07-16_08-23-58](https://cloud.githubusercontent.com/assets/2436121/8712929/d163740c-2b51-11e5-9933-1aaa21046cff.png)

After
```
mkdir images
```
everything works as expected (as far as I can tell for now).

Kind regards,
Matthias

**Comment by rhukster** [comment]
Yah actually i think the zip is not storing the empty folder.  I'll look into it.

**Comment by axel-rank** [comment]
in my latest backup (gra 0.9.32) logs folder is missing too.

**Comment by rhukster** [comment]
Fixed in latest develop branch
