### ISSUE TITLE
Feature Request: Show all pages with current tag

### ISSUE THREAD

**Issue by DebuggeR94** [getgrav/grav#2254]
At the moment, the tags serve only to filter pages, this is useful when we have one page with many child pages with different tags. But when our pages are structured by catalogs, the tags become almost useless.
Here it would be useful to display all pages (from the entire site or section) with the current tag. 
For example, the user has found an interesting article and wants to read more materials on this topic. 
The user clicks on the tag and gets a list of all materials on the site that have the same tag.
Almost all CMS that have tags have similar functions. And yes I know that with the help of crutches, this can be done in the template, but isn't it better to add this functionality to the grav itself?

**Comment by Perlkonig** [comment]
Grav is designed to support many different use cases. The core is, by design, minimalist. All the default blog-style skeletons I've come across include the functionality you describe. And adding it to a fresh theme [is straightforward](https://learn.getgrav.org/content/taxonomy). How would you prefer that this work?

**Comment by DebuggeR94** [comment]
On my site, all materials are categorized:
```
articles:
  catecory-1:
    child-catecory-1:
      material-1,
      material-2,
      material-3
    child-catecory-2:
      material-1,
      material-2
  catecory-2:
    material-1,
    material-2,
    material-3
```
And I have, really a lot of materials, arranged in their categories. How can I display all materials with the selected tag on one page?

The only option that came to my mind is to create a page that will show all the materials that are on the site, and already filter it by tag. But in my opinion, this method has two drawbacks:
1. I do not understand how to organize a crawl of all child categories, if I do not know in advance the depth of nesting.
2. I'm not sure about the performance of this method...

**Comment by DebuggeR94** [comment]
I found how to make it the most practical.
