### ISSUE TITLE
Cannot update plugin: "Use of undefined constant CURLOPT_CAINFO"

### ISSUE THREAD

**Issue by ywiyogo** [getgrav/grav#2255]
I got an issue with CURLOPT_CAINFO after did several change.
If I install the `problems` plugin, the plugin reports that PHP Curl is required but not installed.
I'Ve installed the php7.2-curl. The outputs of `php --info | grep -i curl` are:

    /etc/php/7.2/cli/conf.d/20-curl.ini,
    curl
    cURL support => enabled
    cURL Information => 7.58.0

I found a workaround to update the plugin using `bin/gdm update admin`. 
How can I fix this curl issue? I have to uninstall the `problems` plugin to activate my website.

**Comment by rhukster** [comment]
Curl is required for some features of the admin: https://learn.getgrav.org/basics/requirements#php-requirements

I would guess you have a broken install as i've never seen this issue before.

**Comment by ywiyogo** [comment]
@rhukster, I solved the issue. It was probably due to a conflict between PHP7.0 and PHP7.2. PHP7.2 is installed after I update my Ubuntu to 18.04. Redirecting the php-fpm socket to 7.2 in my Nginx config file and removing PHP7.0 solves this issue in my server. See also https://github.com/getgrav/grav-plugin-problems/issues/21#issuecomment-441441613
