### ISSUE TITLE
/public_html/index.php

### ISSUE THREAD

**Issue by kryukov54** [getgrav/grav#2257]
Dear *,
Could you plese help me?
          Thank you in advance,           Alex
I installed skeleton in ~/public_html.
Setup necessary rights for files and directories. 
Input URL: https://somehost.com/~xxxx
The server redirect me to https://somehost.com/~xxxx/admin
and return message:
404 Not found: The requested URL /home/xxxx/public_html/index.php was not found on this server.
There were two modification in .htaccess:
- RewriteBase /home/xxxx/public_html/
- Options -Indexes +FollowSymLinks

**Comment by rhukster** [comment]
Try here first: https://learn.getgrav.org/troubleshooting/page-not-found

If that doesn't help, hop on our slack channel and ask for some help there.. basically, your rewrite rules are not running.

**Comment by kryukov54** [comment]
Let us describe problem in more details.
Case A. Standard installation grav-v1.5.5.zip into ~username/public_html without any modification
   1. URL: http://server/~username  --> "Forbidden. You don't have permission to access /~username/ on this server. "
  2. Modification in .htaccess: Options -Indexes ==> Options -Indexes +SymLinksIfOwnerMatch
     URL: http://server/~username  --> "Say Hello to Grav! installation successful..."
Case B.  Standard installation grav-admin-v1.5.5.zip into ~username/public_html without any modification
  1. URL: http://server/~username  --> "Forbidden. You don't have permission to access /~username/ on this server. "
  2. Modification in .htaccess: Options -Indexes ==> Options -Indexes +SymLinksIfOwnerMatch
     URL: http://server/~username  --> (1) redirected to https://server/~username/admin
(2) "Not Found. The requested URL /home/username/public_html/index.php was not found on this server."

**Comment by kryukov54** [comment]
If I have case A and after that I install admin plugin (bin/gpm install admin) then I get the same diagnostic as for case B.
