### ISSUE TITLE
https urls generated with port 80

### ISSUE THREAD

**Issue by drnasin** [getgrav/grav#2259]
Seems that since one of the last updates my url's are generated wrong...

`<link rel="canonical" href="https://drnasin.com:80" />`

from what I can see SEO plugin has the same "Problem":
`<meta property="og:image" content="https://drnasin.com:80/user/pages/seoimages/043-browser-4.png" />`

**Comment by rhukster** [comment]
How are you generating the canonical link? It's probably in your `partials/base.html.twig` template, what does it look like?

**Comment by drnasin** [comment]
@rhukster I'm using one of the RT Gantry themes (photon) so the code is:

`<link rel="canonical" href="{{ page.url(true, true) }}" />`

**Comment by rhukster** [comment]
I have the same code in my test theme, but I can't seem to replicate this issue.  Are you running a reverse proxy or something?

**Comment by drnasin** [comment]
hm, could be as I am using their force ssl feature but why is it https and port 80.doesn’t make sense...

**Comment by rhukster** [comment]
Which force SSL option? Grav's?

Even with Grav's `force_ssl: true` i still get:

```
 <link rel="canonical" href="https://localhost/grav-demo-sampler/home" />
```

**Comment by rhukster** [comment]
OH, btw could be an issue/pr that has already been merged into Grav 1.6: https://github.com/getgrav/grav/commit/82d3d5eddaaa6a9faf4d739025168927e9d22b48

Please try that code change...

**Comment by drnasin** [comment]
@rhukster was talking about the option on my hosting provider side...
I tried the solution and it works. url's are generated ok now...even the SEO plugin...thank you!

**Comment by drnasin** [comment]
@rhukster apparently reverse_proxy setting also does the trick. Have no idea how I didn't seen it already, after so much time working with grav...weird...

**Comment by jeremycherfas** [comment]
Depends how quickly 1.6 will be released. :)

For the first time in 3 or 4 updates, I actually managed to remember to do the fix before going live again.

**Comment by mahagr** [comment]
We're about to release RC.1, so if everything goes well and we have enough people testing it out, it should be out pretty soon.
