### ISSUE TITLE
[add-resource] New Plugin 'World Maps'

### ISSUE THREAD

**Issue by Widebob** [getgrav/grav#2260]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **https://github.com/Widebob/grav-plugin-world-maps**

**Comment by rhukster** [comment]
Added.. Thanks.

**Comment by Widebob** [comment]
Hi Grav team !

The World Maps plugin have been updated to v1.0.1, is it possible to update the version from 1.0.0 to 1.0.1 in your plugin references ? The old one is not working.

https://github.com/Widebob/grav-plugin-world-maps
https://github.com/Widebob/grav-plugin-world-maps/releases/tag/1.0.1

Changelog and Readme can be updated too.

Thanks for all
Best regards

**Comment by rhukster** [comment]
It will update automatically if you do the release properly.  It looks like you forgot to update your blueprint.yaml in the 1.0.1 release: https://github.com/Widebob/grav-plugin-world-maps/blob/1.0.1/blueprints.yaml

Still says 1.0.0

**Comment by Widebob** [comment]
Ouh yes my bad !

Now at the 1.0.2 (readme improved). Thank you for it :)
