### ISSUE TITLE
default..html.twig is not defined

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav#2263]
seems that the latest beta (both Grav and Admin) is causing an error where

``` 
default..html.twig is not defined

```

could this be a typo somewhere in the code?

**Comment by rhukster** [comment]
Where do you see this?

**Comment by JohnMica** [comment]
When going into the admin plugin to see / edit options

Images attached



Regards,

John Mica

**Comment by rhukster** [comment]
It's weird that it has `default..html.twig` were you running the previous beta before this one? Can you try another browser? Perhaps its related to the content type negotiation that was added in last release.

**Comment by JohnMica** [comment]
Both safari and chrome have the same issue Normal and incognito

It was the previous beta for both of them (Grav and Admin) that I updated

Regards,

John Mica

**Comment by rhukster** [comment]
is this a custom theme or something? One that doesn't have `default.html.twig`?

**Comment by rhukster** [comment]
Also can you turn on full errors in the system.yaml i could really do with a stack trace to see where the error is coming from

**Comment by JohnMica** [comment]
It is a custom theme and I do have the default.html.twig

It was working just fine before this update (as in no errors occurred)

I might just try a fresh install and see if that solves it? Just a strange

Regards,

John Mica

**Comment by rhukster** [comment]
It's strange, i've tested upgrades, and fresh installs, both on my local apache webserver and also the bult-in PHP webserver.  Maybe the update failed mid-upgrade or something weird.

**Comment by JohnMica** [comment]
What I did notice is the debugger no longer appears to be showing (neither in the UI nor on the website) but the setting is true
Regards,

John Mica

**Comment by rhukster** [comment]
let me know if the fresh install sorts things out for you.

**Comment by JohnMica** [comment]
Will do Andy,

Once my laptop finished its update i’ll spin up a new Docker and see where that takes me

Regards,

John Mica

**Comment by rhukster** [comment]
Looking over all those 404, it seems a bunch of stuff is missing.. so i am leaning towards a bad/failed upgrade somehow.  never experienced one of these myself so hard to say how that happened.

**Comment by JohnMica** [comment]
seems that something did go wrong during the update.

after a computer restart, even if the childpages and the admin pages are accessible, the homepage of the website has a strange error as well
```
An exception has been thrown during the rendering of a template ("Template "modular/text..html.twig" is not defined.").
Previous exceptions
Template "modular/text..html.twig" is not defined. (404)
Template "modular/text..html.twig" is not defined. (0)

```

again the name..html.twig appears somehow - strange indeed

**Comment by JohnMica** [comment]
seems a fresh install takes away the issues completely.

**Comment by JohnMica** [comment]
sorry to reopen

the moment I select the add extensions option and place `.html` the issue reappears, so I guess it is not just the update or a fresh install after all.

**Comment by rhukster** [comment]
Ok, confirmed, its' related to the `append_url_extension:` option in `system.yaml`.  Do you mind creating a fresh issue for this?

**Comment by JohnMica** [comment]
Not a problem at all -shall I just reference this one then ?
Regards,

John Mica
