### ISSUE TITLE
append_url_extension results in errors with latest beta

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav#2264]
#2263
as described in the issue above, the moment you append a url in the UI / system.yaml file the errors keeps coming up 

```
missing defatult..html.twig
missing modular..html.twig
```
notice the double periods `..` 

using Grav v1.6.0-beta.6 - Admin v1.9.0-beta.6

**Comment by rhukster** [comment]
Tracked it down to this commit: https://github.com/getgrav/grav/commit/9b43f201590ad1719c1524cf791325036a733464#diff-d17e21f858763d0ffcdd6c827cc0eddc

Basically, if you comment out that code in the `Page.php` it works again.  Now just looking to see how to get this to work without it breaking everything!

**Comment by rhukster** [comment]
Ok fixed it properly and optimized the `templateFormat()` method while i was at it.
