### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by douglasgough** [getgrav/grav#2265]
I would like to add my new theme to the Grav Repository.
Here are the project details: **https://gitlab.com/dougwgough/foundational/tags/v1.0**

**Comment by rhukster** [comment]
Unfortunately, our GPM system is currently only compatible with GitHub.

**Comment by douglasgough** [comment]
Thats fine. I'll move it over to Github tomorrow.
Thanks

Doug Gough

**Comment by rhukster** [comment]
Was this ever moved to github???

**Comment by douglasgough** [comment]
Sorry, I've been super busy with home renovations and another project. I'll
try to move it over this week.

Thanks

Doug Gough

**Comment by rhukster** [comment]
Please reopen if you ever move to github
