### ISSUE TITLE
external link in new tab

### ISSUE THREAD

**Issue by proewer** [getgrav/grav#2266]
hello

i have a protfolio with external sub pages, how i can open the external link in a new tab?

best regards
paul

title: github
banner_color: '#9ba1ab'
external_url: 'https://github.com/proewer'

**Comment by rhukster** [comment]
Information is a bit sparse, but i'm guessing you are using theme that has the ability to set a banner (with `banner_color`) and provide a link.  You really need to edit the theme to just add `target="_blank"` to the link tag, or you could add an extra attribute to the blueprint/frontmatter to set if it should open in a new tab or not.  Either way this is a theme specific issue, not a core Grav one.

**Comment by HunterDG** [comment]
https://github.com/getgrav/grav-plugin-admin/issues/957
