### ISSUE TITLE
Fake XSS issue warning

### ISSUE THREAD

**Issue by Lufog-git** [getgrav/grav#2272]
I do not know on what principle XSS vulnerabilities work. But if you add the word ```OpenFeed:``` to the page content, you will receive a warning.
```NOTICE: Grav found potential XSS issues in content: 'invalid_protocols'```
Initially, in order to understand why this warning arises, I deleted the text from the article, paragraph by paragraph. And it was actually funny when there was only one word left from the article and the warning remained.

**Comment by rhukster** [comment]
It's the `feed:` part which can be used as an XSS vector.  In Grav 1.6 this is configurable so you can remove a false-positive like this.

For now you can disable feed XSS checks vai config -> security or not worry about it if you are a super admin, as super admins can still save even when there are warnings.
