### ISSUE TITLE
Make asset manager tag html5 compatible

### ISSUE THREAD

**Issue by kirillaristov** [getgrav/grav#2275]
Asset manager generates line like this:
`<link href="/assets/***.css" type="text/css" rel="stylesheet" media="all" />`
this line contains closed tag which is not required in HTML5.

I think, we can to make the code more clearly and make asset line like this:
`<link href="/assets/***.css" type="text/css" rel="stylesheet" media="all">`

https://www.w3schools.com/tags/tag_link.asp
https://stackoverflow.com/questions/19506028/do-you-need-to-close-meta-and-link-tags-in-html

**Comment by rhukster** [comment]
This is already fixed in Grav 1.6 as part of the AssetManager refactor
