### ISSUE TITLE
Move page problem

### ISSUE THREAD

**Issue by mugol80** [getgrav/grav#2276]
Alo

I finded some problem with move page in grav.

When we have pages (example):
->name (/name)
->namesomething (/namesomething)

and want move page /name to /namesomething we have error:
Failed: Cannot set page parent to a child of current page

It's will be working when we try move /testsomething to /test.

Reason is in function move() in file /system/src/grav/common/page/page.php (line: 967)

This function in line 979 use function 'startsWith' to test rawrute:
```
if (Utils::startsWith($parent->rawRoute(), $this->rawRoute())) {
            throw new Exception('Failed: Cannot set page parent to a child of current page');
}

```
but function 'startsWith' [/system/src/grav/common/utils.php (line: 80)]
```
public static function startsWith($haystack, $needle)
    {
        $status = false;

        foreach ((array)$needle as $each_needle) {
            $status = $each_needle === '' || strpos($haystack, $each_needle) === 0;
            if ($status) {
                break;
            }
        }

        return $status;
    }

```
Function check only if string start like second string not compare full string.

**Comment by rhukster** [comment]
Looks like the comparison simply needs a trailing / and it would work.
