### ISSUE TITLE
Unexpected behaviour with titleize removing hyphens

### ISSUE THREAD

**Issue by glasswork** [getgrav/grav#2278]
Titleize
Says it Converts a string to "Title Case" format
So that 'welcome page'|titleize  Welcome Page.

However, it also removes hyphens so that 'mother-in-law,'|titleize  becomes 'Mother In Law,'.

Is it converting the hyphen to an underscore and then humanizing the underscore to a space?
When capitalization changes (like Title Case) are requested, one does not expect other non-capitalization changes to happen.

**Comment by rhukster** [comment]
I'm not sure there's a better "automated" way of doing this.  Titleize is primarily intended to take slugs and make them into titles.  If you remove the handling of the `-` it would break this primary functionality.  So converting `mother-in-law` to `Mother in Law` is actually the intended output.
