### ISSUE TITLE
Add configuration option to not add the language prefix to the URL for Default language.

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#228]
When you start browsing without explicitly specifying a language in the URL and if Active language equals Default language, it would be nice to have an option to not add the language prefix to the URL.
For now even if you start with URL without specifying a language, all links on the page returned by `page.url()` will point to URLs with language.

**Comment by ichik** [comment]
I second this, using rawRoute() for now, but that hardly is the true solution for production.

**Comment by rhukster** [comment]
This is something that I want to add, but other things have priority right now.

**Comment by rhukster** [comment]
Should be done! Maybe you guys could test?

**Comment by ichik** [comment]
Surely, I'll give it a test some this week.

**Comment by flaviocopes** [comment]
Works for me! Should Grav redirect e.g. (assuming `it` is the default lang) `site.com/it/page` to `site.com/page` if that setting is enabled?

**Comment by rhukster** [comment]
Yes, I think it should for consistency sake.  I will look at adding that next.

**Comment by rhukster** [comment]
Ok refactored this now, also have remove the `home_redirect` settings because they were really conflicting with this new setting (causing crazy redirect loops) and really the logic is simpler and better handled with the one `include_default_lang` option.

**Comment by ichik** [comment]
Yep, tested it, it works wonderfully.
