### ISSUE TITLE
[1.6-beta.6] environments include ports

### ISSUE THREAD

**Issue by campino2k** [getgrav/grav#2284]
First image shows calculated environment in Grav 1.5.5 which ignores the port completely

Second image shows Grav public beta which includes the server port in the environment, so that the folder needs to be renamed "localhost:8000". While this is not a problem for Mac and Linux users, Windows users can't do that, since colons are forbidden in folder and filenames.

![auswahl_004](https://user-images.githubusercontent.com/209926/49663108-f5ea5100-fa4d-11e8-93aa-ab2f0ac690a3.png)

![auswahl_005](https://user-images.githubusercontent.com/209926/49662768-04843880-fa4d-11e8-9f9d-a9cc43073875.png)

**Comment by rhukster** [comment]
Fixed...
