### ISSUE TITLE
jQuery XSS vulnerability for v2.2.4

### ISSUE THREAD

**Issue by rhubarbselleven** [getgrav/grav#2286]
As per:

https://snyk.io/vuln/npm:jquery:20150627 

The remediation is to upgrade jQuery to version 3.0.0 or higher.

**Comment by rhukster** [comment]
JQuery 3.3 is already provided in Grav, just need to switch to it via the config.  JQuery 2.2.4 is default because of compatibility with 3rd party plugins. 

The plan is for Grav 2.0.0 will not rely on JQuery at all, but will have it available for 3rd party plugins.

**Comment by rhubarbselleven** [comment]
Is this the configuration point - [Named Assets](https://learn.getgrav.org/themes/asset-manager#named-assets)?

**Comment by rhukster** [comment]
TYes, you just change the jquery in your system config to the 3.x verison: https://learn.getgrav.org/basics/grav-configuration#assets
