### ISSUE TITLE
Call to a member function check() on null

### ISSUE THREAD

**Issue by ignism** [getgrav/grav#2287]
After a fresh install of Grav, it directed me to the error page, removing the problems plugin gave me a similar error page. 

    'problems_url' => $baseUrlRelative . '/user/plugins/problems',
        ];
 
        echo $twig->render('problems.html.twig', $data);
        http_response_code(500);
        exit();
    }
 
    private function problemsFound()
    {
        $status = $this->checker->check(__DIR__ . '/classes/Problems');
        $this->problems = $this->checker->getProblems();
        
        return $status;
    }
 
    private function getTwig()
    {
        $loader = new \Twig_Loader_Filesystem(__DIR__ . '/templates');
        $twig = new \Twig_Environment($loader, ['debug' => true]);
        $twig->addExtension(New \Twig_Extension_Debug());
 
        return $twig;
    }
}
 
Arguments
`"Call to a member function check() on null"`

**Comment by ossd** [comment]
I have the same error with php7.3. Php7.2 is working.

**Comment by ignism** [comment]
@ossd Thanks! Stepping back to 7.2 worked for me as well.

**Comment by rhukster** [comment]
Yup tweeted that there’s some pho 7.3 issues in grav.  However it’s hard to properly debug it yet due to xdebug not being available for 7.3 yet. Early days but we are aware.

**Comment by mahagr** [comment]
It looks like turning off opcache fixes many of the issues, though.

**Comment by edi0th** [comment]
Hi everyone ! I'm having the same issue but I've got php7.2 and opcache is already commented : /
What could I try to pass through this problem ? Or what other informations could I give you in order to help finding this issue ?  I'm using Debian !
Thanks in advance !
