### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by aradianoff** [getgrav/grav#229]
I would like to add my new plugin/theme to the Grav Repository if it is considered of interest.
Here are the project details: **https://github.com/aradianoff/recatpchacontact**

It is a plugin to add a contact form based on the one of Simple_Contact plugin but with Google reCAPTCHA validation and multilang support.

**Comment by rhukster** [comment]
Thanks i'll add this to the GPM shortly

**Comment by rhukster** [comment]
I'm having trouble adding your plugin to GPM, i'm getting an undefined offset error during the process.  Can you please double check your blueprints?

**Comment by aradianoff** [comment]
I think it was the keywords in the blueprints. I had embeded them in "". Could you check if it works now?

**Comment by rhukster** [comment]
ok looks like your changelog format is invalid.  I suggest copying one from antimatter or grav itself or something.

**Comment by aradianoff** [comment]
I am sorry I didn't realize. I fixed it now.

**Comment by rhukster** [comment]
added!

**Comment by aradianoff** [comment]
Thanks! :smile:

**Comment by aradianoff** [comment]
Sorry to bother you again... but I realized that I had a typo in the repository name. It said `recatpchacontact` instead of `recaptchacontact` (and it disabled the plugin...). I renamed the repository so it is named correctly now, but I suppose you have to change it in the gpm... 

https://github.com/aradianoff/recaptchacontact

**Comment by rhukster** [comment]
Typo fixed, should be reflected in 10-15 mins.
