### ISSUE TITLE
Grav does not run in PHP 7.3.0 (contains workaround)

### ISSUE THREAD

**Issue by mahagr** [getgrav/grav#2292]
if you're running PHP 7.3.0 and you have opcode cache enabled, you need to add the following line to your `php.ini`:

```ini
opcache.optimization_level=0x7FFFBBFF
```

There is an opcache bug in PHP 7.3.0 which will be fixed on the next PHP version:
https://bugs.php.net/bug.php?id=77275

**Comment by axel-rank** [comment]
Running PHP 7.3.0 and everythings working in Grav 1.5.6 and admin 1.8.15
Only error with admin 1.9.0-beta.7
https://github.com/getgrav/grav-plugin-admin/issues/1567

**Comment by mahagr** [comment]
Nope, the same issue happens for all versions of Grav due to a bug in PHP 7.3. In fact, this bug was found by using Grav 1.5 and Admin 1.8.

**Comment by axel-rank** [comment]
Very strange kind of a bug...
But on my side still working in PHP 7.3.0 with Grav 1.5 and Admin 1.8.
So I leave it until error comes up. Should be fixed next PHP release...

**Comment by rhukster** [comment]
You probably don’t have opcache installed so you are not seeing the bug.

**Comment by mahagr** [comment]
There's no need to wonder; PHP people have already confirmed to me that this bug has been fixed for 7.3.1 and it can be worked around by changing a single setting.

**Comment by axel-rank** [comment]
Well, if you're allowed to change php.ini
My provider doesn't allow that.
Anyway, still no problems with php 7.3.0 and opcache.

**Comment by mahagr** [comment]
PHP 7.3.1 is released and it looks like the issue was indeed fixed. Closing the issue.
