### ISSUE TITLE
fileupload remove file problem

### ISSUE THREAD

**Issue by hbkuipers** [getgrav/grav#2294]
When a uploaded file gives an error, lets say file too big, it is impossible to remove the file from the form without refreshing the page in the browser because the tooltip hinders the 'x' button under the image. Also the reset button doesn't clear the upload field while it does clears all other fields.

**Comment by w00fz** [comment]
You don’t really need to worry about removing it. If it failed it won’t be stored. Remains there only for “your records” until you leave or come back to the page

**Comment by hbkuipers** [comment]
I know a file won't upload when in error state but visitors may try to remove the file but they can't. It's just sloppy not be able to press the 'x' or use the reset button.
