### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by cadjou** [getgrav/grav#2301]
Hello Grav Team,

I would like to add my new plugin **cadphp** to the Grav Repository.
It's to include PHP simply inside Grav CMS with a security filter.

I put all the details in the Repositories Page
https://github.com/cadjou/grav-plugin-cadphp

Thank you

**Comment by rhukster** [comment]
Added to GPM..

**Comment by rhukster** [comment]
This won't show up until you RELEASE

**Comment by cadjou** [comment]
Hello and Happy New Year ;)
I made my release. 
Thank you
