### ISSUE TITLE
Difficulties with a delimiter

### ISSUE THREAD

**Issue by lufog** [getgrav/grav#2303]
The delimiter don't work when the Markdown process disabled in content settings. What makes it impossible to use the delimiter in html editors, like TinyMCE. 
Can there be any possibility to process this from html?

**Comment by rhukster** [comment]
I'll need to investigate this.  the intention of disabling markdown was to let the page render _as-is_ with HTML, so it may well be that the delimiter processing is reserved for markdown only.  Been a while since i looked at this code...

**Comment by rhukster** [comment]
OK, the issues is that because markdown wraps the delimiter in a paragraph tag, so our check looks for that: 

```
            // Handle summary divider
            $delimiter = $config->get('site.summary.delimiter', '===');
            $divider_pos = mb_strpos($this->content, "<p>{$delimiter}</p>");
            if ($divider_pos !== false) {
                $this->summary_size = $divider_pos;
                $this->content = str_replace("<p>{$delimiter}</p>", '', $this->content);
            }
```

So the slightly ugly solution is to simply put `<p>===</p>` as your delimiter, but it would be interesting to see what the editor is outputting?

**Comment by Lufog-git** [comment]
Yes, the problem was that the editor, adds the class “card-text” to each paragraph. With a paragraph without additional attributes everything works fine.

**Comment by Lufog-git** [comment]
Paragraph tags are hardcoded? As I understand it, I cannot set a separator like:
<p class="card-text">===</p>
or
<p class="card-text"></p>
In any case, it does not work for me. I will think how to set up the editor so that it does not add a class to the delimiter paragraph.
