### ISSUE TITLE
Paid Membership for registration

### ISSUE THREAD

**Issue by prinla** [getgrav/grav#2305]
Hello,
I would like to know if there is any possibility to make a registration as user on a grav website payable? Meaning the person has to pay a membership before he can register. Do you see any solution (with plugins) or coding?

**Comment by rhukster** [comment]
Anything is possible with a plugin, there's a couple of cart type plugins, but not sure if there is an existing 'membership' plugin.  If there's not it could definitely be developed.  Maybe hop on the discord chat and ask there?
