### ISSUE TITLE
Identifier "now" is not defined

### ISSUE THREAD

**Issue by ddiguru** [getgrav/grav#2306]
I recently upgraded brew installed modules and I am now getting the following error: Identifier "now" is not defined. 

`[2018-12-28 17:39:53] grav.CRITICAL: Identifier "now" is not defined. - Trace: #0 /Users/ppiper/workspace/grav-kb/system/src/Grav/Common/Cache.php(117): Pimple\Container->offsetGet('now') #1 /Users/ppiper/workspace/grav-kb/system/src/Grav/Common/Cache.php(104): Grav\Common\Cache->init(Object(Grav\Common\Grav)) #2 /Users/ppiper/workspace/grav-kb/system/src/Grav/Common/Grav.php(423): Grav\Common\Cache->__construct(Object(Grav\Common\Grav)) #3 /Users/ppiper/workspace/grav-kb/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Grav->Grav\Common\{closure}(Object(Grav\Common\Grav)) #4 /Users/ppiper/workspace/grav-kb/user/plugins/problems/problems.php(46): Pimple\Container->offsetGet('cache') #5 /Users/ppiper/workspace/grav-kb/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\ProblemsPlugin->onPluginsInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPluginsInitia...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #6 /Users/ppiper/workspace/grav-kb/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPluginsInitia...', Object(RocketTheme\Toolbox\Event\Event)) #7 /Users/ppiper/workspace/grav-kb/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPluginsInitia...', Object(RocketTheme\Toolbox\Event\Event)) #8 /Users/ppiper/workspace/grav-kb/system/src/Grav/Common/Grav.php(279): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPluginsInitia...', Object(RocketTheme\Toolbox\Event\Event)) #9 /Users/ppiper/workspace/grav-kb/system/src/Grav/Common/Processors/PluginsProcessor.php(19): Grav\Common\Grav->fireEvent('onPluginsInitia...') #10 /Users/ppiper/workspace/grav-kb/system/src/Grav/Common/Grav.php(131): Grav\Common\Processors\PluginsProcessor->process() #11 /Users/ppiper/workspace/grav-kb/system/src/Grav/Common/Grav.php(370): Grav\Common\Grav->Grav\Common\{closure}() #12 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('plugins', 'Plugins', Object(Closure)) #13 /Users/ppiper/workspace/grav-kb/system/src/Grav/Common/Grav.php(346): call_user_func_array(Object(Closure), Array) #14 /Users/ppiper/workspace/grav-kb/system/src/Grav/Common/Grav.php(132): Grav\Common\Grav->__call('measureTime', Array) #15 /Users/ppiper/workspace/grav-kb/index.php(54): Grav\Common\Grav->process() #16 {main} [] []`

Details:

- grav 1.5.6
- Mac os x mohave 10.14.2
- brew installed nginx 1.15.8
- brew installed PHP 7.3 

I've worked on comparing my 7.2/php.ini file with 7.3/php.ini file. I've also tried re-installing grav 1.5.6 from scratch, as well as, trying grav 1.6 beta. To no avail. Not sure what this issue is and can't seem to resolve it.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav/issues/2292

**Comment by ddiguru** [comment]
I meant to also state that i enabled the opcache.optimization from #2292 

`opcache.optimization_level=0x7FFFBBFF`

And this did not solve my issue. :-(

**Comment by rhukster** [comment]
Ah OK, sorry about that... I've not even tested 7.3.0 any further at this point as it's literally riddled with bugs. I suggest using 7.2 until 7.3 has a couple more 'dot' releases

**Comment by ddiguru** [comment]
Yep... agree. Closing this.
