### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by NastuzziSamy** [getgrav/grav#2308]
Hey guys, thanks for this framework ! <3 

I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: https://github.com/NastuzziSamy/grav-theme-acute

It is a fork from Mediator, as it is discountinued, I really want to push this theme as great as possible. It will not be the same as Mediator, of course.

It will be totaly inspired from Medium.

**Comment by rhukster** [comment]
Added to GPM

**Comment by NastuzziSamy** [comment]
Thanks !
