### ISSUE TITLE
[add-resource] New plugin

### ISSUE THREAD

**Issue by NastuzziSamy** [getgrav/grav#2309]
Hey guys, thanks for this framework ! <3

I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: NastuzziSamy/grav-plugin-url-shortener

The goal is simple: create shorten urls ^^

**Comment by rhukster** [comment]
This won't show up until you RELEASE...

**Comment by NastuzziSamy** [comment]
Ok thanks ! 
Was testing in production
