### ISSUE TITLE
JS pipelining error

### ISSUE THREAD

**Issue by kroegerama** [getgrav/grav#231]
The js minimizer seems to have a problem with the mdl-js from google.
I get the following error:

    JSMin: Unterminated RegExp at byte 187080: /

My template imports the following js:
[Material Design Lite](http://storage.googleapis.com/code.getmdl.io/1.0.1/material.min.js)

**Comment by rhukster** [comment]
This is an upstream JSMin issue:

https://github.com/mrclay/minify/issues/81

**Comment by rhukster** [comment]
btw, looks like all you need to do is ensure your file is named `-min.js` or `.min.js` and it will be skipped during the JSMn'ifying process.
