### ISSUE TITLE
[add-resource] Presentation-plugin

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#2320]
I would like to add the [Presentation-plugin](https://github.com/OleVik/grav-plugin-presentation) to the Grav Repository. A testing-release, [v1.0.0-beta.2](https://github.com/OleVik/grav-plugin-presentation/releases/tag/v1.0.0-beta.2) is released on GitHub - including a ready-to-deploy binary.

The plugin provides a simple way of creating fullscreen slideshows that can be navigated two-dimensionally, using the Reveal.js-library. At its core the plugin facilitates efficient handling of content for use with the library. You can utilize Reveal.js however you want through custom initialization, and still leverage the plugin's content-handling.

**Comment by rhukster** [comment]
I have a few extensions to add... will get to these tomorrow (hopefully!)

**Comment by rhukster** [comment]
Added to GPM
