### ISSUE TITLE
[Bug] Taxonomy URL Filters

### ISSUE THREAD

**Issue by Sauerbrei** [getgrav/grav#2321]
Hi,

we have setup a tag called "E3/DC" in a few blogitems. We're printing all available tags at our blog frontpage so a user is able to filter via click for those tags. That leaded us to a bug, where we wanted to urlencode this tag and we got redirected to the 404-Site. This may be caused by the slash which is automatically decoded by grav itsself --> https://github.com/getgrav/grav/blob/develop/system/src/Grav/Framework/Route/Route.php#L289
https://github.com/getgrav/grav/blob/develop/system/src/Grav/Framework/Route/Route.php#L292

Is there any way to get a tag-Link for the tag "E3/DC" to work?

Thanks!

**Comment by rhukster** [comment]
Short answer is no.  Taxonomy is intended to be used to filter content, and as such should be something that can be queried via the URL.  any `/` will be confused as a path separator in the url:

```
http://localhost/grav-blog/tag:E3/DC
```

is actually equivalent to:

```
http://localhost/grav-blog/DC
```

with the taxonomy `tag` equal to `E3`.  Even escaping this does not work, as we handle escaped characters as part of the URL also, there's no way to know it's only part of the taxonomy.
