### ISSUE TITLE
[add-resource] Presentation Deckset Plugin

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#2322]
I would like to add the [Presentation Deckset Plugin](https://github.com/OleVik/grav-plugin-presentation-deckset) to the Grav Repository. A testing-release, [v1.0.0-beta.1](https://github.com/OleVik/grav-plugin-presentation-deckset/releases/tag/v1.0.0-beta.1) is released on GitHub.

The plugin extends the Presentation Plugin with a [Deckset Syntax](https://docs.deckset.com/English.lproj/Customization/02-custom-theming.html) for Customization Commands, which can be used as the Parser for the main plugin.

**Comment by rhukster** [comment]
Added
