### ISSUE TITLE
Grav CMS Swag

### ISSUE THREAD

**Issue by LieselGorlov** [getgrav/grav#2323]
Do you have a swag shop (like [https://store.gatsbyjs.org/](https://store.gatsbyjs.org/) e.g.)?

**Comment by rhukster** [comment]
We were recently playing around with a "design by humans" store, but only have 1 shirt on there for now.

https://www.designbyhumans.com/shop/t-shirt/men/have-spacesuit/1032144/

What kinds of swag were you looking for?

**Comment by LieselGorlov** [comment]
I would be fine with shirts and stickers.
Other stuff (e.g. socks and hoodies) is nice too but it is not a must for me.

**Comment by LieselGorlov** [comment]
Can you please add a design without text (only logo)? I will order one shirt then and tell you about my experience with "design by humans".

Companies I can recommend:
[HELLOTUX](https://www.hellotux.com/) - extremely amazing quality, the design is not printed but embroidered
[Teezily](https://www.teezily.com/) - inks last many washings and quality is great
[Qwertee](https://www.qwertee.com/) - they do not offer custom prints yet but may plan to do so, regardings print quality they are by far the best
[Kotis](https://kotisdesign.com/) - overall very good
[Corporate Couture](https://corp-couture.com/) - overall very good
[Printfection](https://www.printfection.com/) - they are OK
[Zigpac](https://www.zigpac.com/) - awesome stickers
[Stickermule](https://www.stickermule.com/unlock?ref_id=2743880701) - awesome stickers, subscribe to the newsletter if you are interested in great deals
[Sock Club](https://custom.sockclub.com/) - very nice socks

Companies I cannot recommend:
[Threadless](https://www.threadless.com/) - prints are mostly gone after 1-3 washings
[Spreadshirt](https://www.spreadshirt.com/) - prints are mostly gone after 5 - 10 washings
[Teespring](https://teespring.com/) - prints are mostly gone after 5 - 10 washings
