### ISSUE TITLE
Different render in admin preview and site

### ISSUE THREAD

**Issue by berliozz** [getgrav/grav#2326]
Can somebody explain me, why preview in admin is different then in production site?
Below You find screenshot.

`Table example`
`| 1-st | 2-nd | 3-rd |`
`| :--- | : --- : | ---: |`
`| First | Second | Third|`

![Production view](https://user-images.githubusercontent.com/3850403/50881224-09dcf600-13f2-11e9-8dfb-a4dffc9fe749.png)

![Preview in admin panel](https://user-images.githubusercontent.com/3850403/50881261-211be380-13f2-11e9-8d23-5f40c3832265.png)

In admin pane I have full width table with separators per row.
In production — width equal content and hasn't any dividers.

I use default quark theme, without any customizations.

**Comment by rhukster** [comment]
The frontend will render a page based on whatever theme is being used.  The admin 'preview' is  independent of the frontend theme, and is intended to show the markdown/twig/shortcode rendering, but not necessarily exactly how it would be rendered on the frontend.  The preview button in the toolbar at the top can be used to open the current page you are editing and see it rendered in the frontend.

<img width="1169" alt="image 2019-01-09 at 10 18 01 am" src="https://user-images.githubusercontent.com/1084697/50916256-def5a080-13f7-11e9-8a96-bbab42af41f0.png">
