### ISSUE TITLE
[question] How to get all tags from child pages?

### ISSUE THREAD

**Issue by Lufog-git** [getgrav/grav#2329]
How to get only those tags that are contained in the child pages?

We have the following structure:
```
category 1
   page 1 (tags: ct1pg1)
   page 2 (tags: ct1pg2)
   page 3 (tags: ct1pg3)

category 2
   page 1 (tags: ct2pg1)
   page 2 (tags: ct2pg2)
   page 3 (tags: ct2pg3)

category 3
   page 1 (tags: ct3pg1)
   page 2 (tags: ct3pg2)
   page 3 (tags: ct3pg3)
```

How to make so that we only see those tags that belong to a particular category, for example:
```
category 1 (tags: ct1pg1, ct1pg2, ct1pg3)
category 2 (tags: ct2pg1, ct2pg2, ct2pg3)
category 3 (tags: ct3pg1, ct3pg2, ct3pg3)
```

**Comment by Lufog-git** [comment]
The idea was to filter materials in categories by tags. That will allow you to have only a few root categories, instead of a deep tree structure. And when in a category, tags are displayed, from materials from other categories, it looks very strange.

**Comment by rhukster** [comment]
This kind of thing we hope to solve with Grav 2.x which is going to have much more powerful collection capabilities.
