### ISSUE TITLE
Strange issue regarding execution

### ISSUE THREAD

**Issue by simogeo** [getgrav/grav#233]
I just started working with grav today.

I got the last release from github install in apache folder root. I also installed [deliver skeleton](https://github.com/getgrav/grav-skeleton-deliver-site/releases/download/1.0.2/grav-skeleton-deliver-site-v1.0.2.zip) and started working on that copy.

My structure folder is : 

```
-- Apache Root folder /
      |__ gravFolder/
      |__ deliverSkeletonGravFolder/

```

I'm able to access `http://localhost/deliverSkeletonGravFolder/`  but if I remove `gravFolder/` I get the following error when accedding the Deliver version : 

```
Fatal error: Uncaught exception 'RuntimeException' with message 'Please run: <i>bin/grav install</i>' in /home/xxx/www/deliverSkeletonGravFolder/index.php:11 Stack trace: #0 {main} thrown in /home/xxx/www/deliverSkeletonGravFolder/index.php on line 11
```

Except that I'm stucked, **I'm very surprised because I don't understand the link between two isolated folders**

And running `sudo ./bin/grav install` just give me an error (as mentioned in #20) : 

```
ERROR Missing .dependencies file in user/ folder
ERROR invalid YAML in .dependencies
```

ANy help would be welcome. Thanks in advance

**Comment by rhukster** [comment]
there really should be no connection between the 2 versions.  if you installed the github version into `/gravFolder/` and then you go in there and run `bin/grav install` it should install the vendor dependencies, plugins, and antimatter theme.  After that try reaching this install directly.  It should just work. Also you could just extract the prebuilt version: https://github.com/getgrav/grav/releases/download/0.9.33/grav-v0.9.33.zip

Also regarding the deliverSkeleton, you should download and install this from the release package:  https://github.com/getgrav/grav-skeleton-deliver-site/releases/download/1.0.2/grav-skeleton-deliver-site-v1.0.2.zip

This contains the latest Grav, plugins, theme, demo content etc.  Just extract it and your done: https://github.com/getgrav/grav-skeleton-deliver-site/releases/download/1.0.2/grav-skeleton-deliver-site-v1.0.2.zip

**Comment by aptly-io** [comment]
1. The skeleton archive already contains a grav-core and some initial user/ sub-directory. There's no need for a seperate grav-core (your gravFolder).
2. If you get gravFolder with git clone it does not contain any dependencies. Like the error message says: run bin/grav to download all these external PHP dependencies.
For questions like these it's easier to use the forum or gitter than submit questions as bugs ...

**Comment by simogeo** [comment]
@rhukster  @aptly-io :shutting of the computer, sleeping and starting to work again fixed the bug ...

Don't understand how that happened, but it seems to be ok right now. Many thanks for your quick replies and keep doing the great work.

**Comment by simogeo** [comment]
Actually, I had a problem with my initial `deliverSkeletonGravFolder/` folder - something was missing for sure. So I re-installed a fresh https://github.com/getgrav/grav-skeleton-deliver-site/releases/download/1.0.2/grav-skeleton-deliver-site-v1.0.2.zip version and replace my User/ folder.

**Comment by aptly-io** [comment]
Glad to know all works fine. Good luck and fun discovering grav !
Kind regards Francis

Simon Georget <notifications@github.com> schreef op 31 juli 2015 09:09:42 CEST:
>Actually, I had a problem with my initial `deliverSkeletonGravFolder/`
>folder - something was missing for sure. So I re-installed a fresh
>https://github.com/getgrav/grav-skeleton-deliver-site/releases/download/1.0.2/grav-skeleton-deliver-site-v1.0.2.zip
>version and replace my User/ folder.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/getgrav/grav/issues/233#issuecomment-126589145

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by simogeo** [comment]
@aptly-io : but if I rename my folder and try to reach it with my browser I get this error : 

```
 Fatal error: Uncaught exception 'RuntimeException' with message 'Please run: <i>bin/grav install</i>' in /home/simon/www/scop-grav/index.php:11 Stack trace: #0 {main} thrown in /home/simon/www/scop-grav/index.php on line 11
```

Did I missed something ?

**Comment by flaviocopes** [comment]
Can you retry from scratch? Remove those folders you already have. Download the grav-skeleton-deliver-site and unzip it so it's reachable as `http://localhost/grav-skeleton-deliver-site/`. If you rename that folder does it work?

**Comment by simogeo** [comment]
Same issue ....

**Comment by flaviocopes** [comment]
So leaving the folder named `grav-skeleton-deliver-site` works, but once renamed it does not work any more?

**Comment by simogeo** [comment]
That's it !

**Comment by simogeo** [comment]
I tried running  `clean` / `clear-cache` commands with no success

**Comment by rhukster** [comment]
I really don't know what your doing to see these results. Here's what I did:

1. Download Deliver skeleton: https://github.com/getgrav/grav-skeleton-deliver-site/releases/download/1.0.2/grav-skeleton-deliver-site-v1.0.2.zip

2. Extract this zip

3. rename this folder to `deliver`

4. point browser to `http://mysite.com/deliver` 

done, just works:

http://polydeon.com/monosnap/Home__Deliver_2015-07-31_07-33-26.png

**Comment by simogeo** [comment]
1. I did extract first, 

2. reach http://localhost/grav-skeleton-deliver-site/ with success

3. renamed my folder to /grav-skeleton/

4. Try again to reach http://localhost/grav-skeleton/ with the given error : 

```
 Fatal error: Uncaught exception 'RuntimeException' with message 'Please run: <i>bin/grav install</i>' in /home/simon/www/scop-grav/index.php:11 Stack trace: #0 {main} thrown in /home/simon/www/scop-grav/index.php on line 11
```

I'll be in holidays next 2 weeks. I'll try the way you propose on my way back.
Anyway, renaming a current project should not be a problem.

Thanks again for replying

**Comment by rhukster** [comment]
What platform are you on? What LAMP stack are you using? How exactly did you rename the folder?

**Comment by simogeo** [comment]
Ubuntu 14.04 / PHP Version 5.5.9 / Apache/2.4.7 (Ubuntu)

**Comment by rhukster** [comment]
Closing for now.  Please reopen if it continues to be an issue for you.

**Comment by simogeo** [comment]
Seems to work. Thanks !

**Comment by simogeo** [comment]
No. Does not work. (can't reopen ticket myself)

**Comment by rhukster** [comment]
Can you take a video/screencast of the steps, specifcally the part where it's working, then you rename, and then it's not working.

**Comment by simogeo** [comment]
I observed that if I restart my Apache server (`apachectl restart`) after renaming, everything is getting ok. I will consider the problem as solved.

I use [X-cache](http://xcache.lighttpd.net/) and I suspect this can be the cause of the trouble.
I don't know if you, grav developers could do something on the application part.

One more time, thank you for taking time regarding this issue.
