### ISSUE TITLE
Can I change how the compiled files in cache/compiled/files are named?

### ISSUE THREAD

**Issue by khartahk** [getgrav/grav#2330]
A hosting provider we are using has a very secure instalment and doesn't allow creating php just like that. Is it possible to change how the files are named in there?

**Comment by b1he** [comment]
If you want your website on another server without needing php, you could try a static site generator like Blackhole https://github.com/BarryMode/grav-plugin-blackhole

**Comment by khartahk** [comment]
This could be an option perhaps. I'm generally not looking for a static site just wan't to know if this caching that is generating php files can be simply disabled or changed how it names cached files.

**Comment by rhukster** [comment]
Change the names to what exactly? Is it the fact they are `.php` extensions?

**Comment by khartahk** [comment]
Yes, I should have said the extension was what I wanted to change.

**Comment by rhukster** [comment]
short answer is nope, those are cached PHP files so are `.php` extension.
