### ISSUE TITLE
Representing each article using just a `file.md` instead of `folder/file.md`

### ISSUE THREAD

**Issue by anasram** [getgrav/grav#2331]
Hi all, and happy new year.

Why each article in Grav should be represented using `folder/file.md` rather than simply just a `file.md`?

Anyway, is there a way (a configuration option or so) for article to be represented using just a `file.md`?

**Comment by b1he** [comment]
The file represents the template chosen for that page. So default.md means that page is using the default template.

Folders helps organise your website better, useful for things such as sub-pages and blog posts.

You can read more about it here: https://learn.getgrav.org/content/content-pages

I don't think you can have just pagename.md without folders.

**Comment by rhukster** [comment]
Folders are a key feature as they allow a page to have it's own media, also it allows the ability to have multilanguage versions of the page md file in one location.  Having a bunch of pages in a single folder would severely limit the functionality.

**Comment by anasram** [comment]
> they allow a page to have it's own media,

Typically, media should be considered as common resources, since they could be reused in several articles.

> also it allows the ability to have multilanguage versions of the page md file in one location. 

I already use multilanguage versions of all pages and articles in my blog without using a sub folder for each.

> Having a bunch of pages in a single folder would severely limit the functionality.

Do you mean performance?

In fact, this is the only reason I thought about when I realized that each article in Grav is represented by `folder/file.md` .
