### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by artofthesmart** [getgrav/grav#2339]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: 

**User**: artofthesmart
**Theme**: Hypertext
**URL**: https://github.com/artofthesmart/hypertext
**Demo**: http://hypertext.artofthesmart.com
**Summary**: Hypertext is a Grav theme that focuses on speed and simplicity by using little-to-no JS or CSS. Hypertext is meant to be used with the latest version of the Grav CMS.

**Comment by rhukster** [comment]
Added to GPM
