### ISSUE TITLE
Call to a member function check() on null

### ISSUE THREAD

**Issue by edi0th** [getgrav/grav#2340]
HI everyone !
I tried to install Grav on my computer, and it seems ok, but a the moment I putted the custom template a friend of mine made (and it woks on his computer), it gaves me a "Call to a member function check() on null" error on this function: 
```
private function problemsFound()
    {
        $status = $this->checker->check(__DIR__ . '/classes/Problems');
        $this->problems = $this->checker->getProblems();
        
        return $status;
    }
```
It seems to be the same error as in this post #2287 but the solution here was to step back to php7.2 (but i'm already in php7.2). 

Is anyone knows how i could deal with this ? : /

**Comment by rhukster** [comment]
Update problems plugin, you seem to be running an old version.
