### ISSUE TITLE
Markdown link processing should default to success-as-entered

### ISSUE THREAD

**Issue by notklaatu** [getgrav/grav#2349]
Feature request: 
If a user enters a valid URL, then Grav and Markdown should parse the URL as entered. Users should not be required to add a ``&noprocess`` flag to valid URLs in order for the URLs to display and link correctly.

If a user wants the URLs to be processed and munged in order to add special CSS properties to them, then that should require a special flag, such as ``&gravprocess``, so that processing beyond expected Markdown behaviour is performed.

This is the same bug as issues/989, but I'm re-opening because it requires users to refer to Github issues in order to fix. Even the relevant docs (https://learn.getgrav.org/content/linking#link-attributes) don't directly address the problem, since there's no reason to look in a section called link-attributes when trying to debug an apparent parsing error.

**Comment by rhukster** [comment]
You make some good points, however, the vast majority of links for users are simple links, where class an id attributes can be appended without issue. Existing links with either 'id' or 'classes' are much rare generally speaking (even if they are not for you personally).

Also changing the behavior of this would completely break thousands of existing installs.

**Comment by notklaatu** [comment]
Sorry, I think I forgot to provide an example.

I'm not using links with id or classes. Any link with a question mark (``?``) fails to parse correctly.

For instance:

    [This link will break](https://hackerpublicradio.org/eps.php?id=2446)

I think by default, such a link should get parsed correctly. A valid HTML link shouldn't require a special flag to *not* be munged.

**Comment by notklaatu** [comment]
OK, I think I understand now: any content in the leading brackets gets transformed into a CSS ``id``, and that breaks the ability to have a ``?`` in the link string. 

I feel like this abuses Markdown, but as you say, changing it now would break all other installs.

I'll have my bloggers use HTML links instead, as a workaround.
