### ISSUE TITLE
Highlight Specific lines in Code

### ISSUE THREAD

**Issue by noisytoken** [getgrav/grav#2360]
Hi

I am thinking about moving a WordPress blog to grav.

However, I unable to find a plugin to highlights the specific lines in my code snippet.

**Comment by rhukster** [comment]
Prism supports highlighting specific lines of code if you add those plugins.  

https://prismjs.com/

You could just add the relevant JS/CSS to your theme, then use standard `<pre><code>` HTML blocks and it should just-work.  

The problem with using Markdown code-blocks is there's no standard way to get line numbers rendered appropriately for the JS you decide to use.
