### ISSUE TITLE
XDebug and Grav Debugger interference?

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav#2361]
If the Grav debugger is enabled and my site is run with XDebug on, an exception (`InvalidArgumentException: Invalid resource file://`) is thrown from `vendor/rockettheme/toolbox/ResourceLocator/src/UniformResourceLocator.php` at line 435 repeatably.

Disabling the Grav Debugger clears the error.

Do others see this behavior?

**Comment by mahagr** [comment]
Something is running `$locator->findResource('file://...')` which is throwing an error.

**Comment by rhukster** [comment]
does sound like an issue with a plugin.. i can't replicate this on my test sites.

**Comment by bobrocke** [comment]
I can duplicate the error in a fresh install of the Blog Site Skeleton. On my system, if it's a plug-in problem, it comes from one of the stock plug-ins. But which one?

**Comment by rhukster** [comment]
![image 2019-02-05 at 5 48 06 am](https://user-images.githubusercontent.com/1084697/52274385-be8f0800-2909-11e9-88ab-4f0f64ba6aad.png)

Just tested blog skeleton and it works fine for me.. what version of PHP are you running? 7.2 is recommended at this point.

**Comment by bobrocke** [comment]
Just to be clear, I have a breakpoint set and VSCode listening for XDebug. Without listening, I get the Grav Debugger as you show. When listening, I get the exception caught in XDebug.

PHP is v7.2.10.

**Comment by rhukster** [comment]
Well, probably something related to VSCode and XDebug (or your specific breakpoint setup or breakpoint?) as I use PHPStorm and XDebug works fine with Grav debugger enabled too.

**Comment by bobrocke** [comment]
I'm using a Mac, too. But you are on to something. If I debug with Atom/XDebug, I'd don't get the XDebug exception.

So I need to figure out what's not right with VSCode/XDebug.
