### ISSUE TITLE
twig variables in form fields 'label'

### ISSUE THREAD

**Issue by Genenenenaam** [getgrav/grav#2363]
To comply with GDPR rules, my contact form has a checkbox that indicates that a user complies with the privacy regulations.

The label has an anchor link to the 'privacy' page. The href i want to set with twig.
`{{ page.find('/privacy').url(true) }}`

The fields for this form are defined in frontmatter:
- name: gdpr
        type: checkbox
        markdown: true
        helper: "I accept the <a href=\"{{ page.find('/privacy').url(true) }}\">privacy</a> regulations."
        validate:
          required: true

![schermafbeelding 2019-02-05 om 10 18 18](https://user-images.githubusercontent.com/20650976/52263451-7e428080-292f-11e9-9cc2-270039ccb261.png)

The issue is that twig in frontmatter is not being processed.
This are my setting in 'system.yaml'

frontmatter:
  process_twig: true
  ignore_fields:
    - form
    - forms

![schermafbeelding 2019-02-05 om 10 24 12](https://user-images.githubusercontent.com/20650976/52263738-3b34dd00-2930-11e9-9dd6-b8394c0713bb.png)

**Comment by rhukster** [comment]
I think you are making this more complex than it needs to be... you really don't need markdown there, just use a regular html link:

```
helper: i accept the <a href="/privacy">privacy regulations</a>
```

or if you want the full URL just use it:

```
helper: i accept the <a href="https://mysite.com/privacy">privacy regulations</a>
```

**Comment by Genenenenaam** [comment]
@rhukster A twig variable would be of better use to me since:
- "https://mysite.com/" changes to: https://dev.mysite.com/, https://stag.mysite.com/
- "/privacy" won't work in sub pages, then you get https://mysite.com/grandparent/parent/child/privacy

**Comment by rhukster** [comment]
actually `/privacy` should work in your case as it will be based from the root because it starts with `/`

**Comment by rhukster** [comment]
Another option is to create a new custom field that extends checkbox, and simply process the markdown of the `helper:` text with the twig `|markdown` filter.

**Comment by Genenenenaam** [comment]
I did, like this:

`{% if field.helper %}
<span class="field__label--checkbox">{% if field.markdown %}{{ field.helper|t|markdown(false) }}{% else %}{{ field.helper }}{% endif %}</span>
{% endif %}`
