### ISSUE TITLE
Working with data are not documented enough

### ISSUE THREAD

**Issue by Lufog-git** [getgrav/grav#2367]
There is not enough information about the mechanisms for working with data. 

The Grav documentation describes how to save the data obtained from the form in data (user/data). But there is no information on how to access this data (read/edit/delete), from php or twig. Are there any mechanisms for working with them in Grav? And if they are, where can I read more about it?

**Comment by Lufog-git** [comment]
After a bit of analysis of plugin repositories that work with data. I found information that working with data out of the box is now only being implemented. And this is somehow related to FlexObjects. I'm not mistaken?

**Comment by mahagr** [comment]
Right now `data/` is usually used with forms, for example, if you want to store the posted data before sending email etc. Some plugins also use it to keep track of their state, like if you enable likes/page hits plugins. And yes, Flex also defaults to `data/`, but isn't restricted to it.

There are no standards on how the data gets stored or retrieved, it's really application specific.

**Comment by Lufog-git** [comment]
@mahagr I thought there are some mechanisms for working with data. I wanted to save the data from the form with "process: save" and then process it in my plugin. But now I think it will be easier to immediately send the data from the form to the plugin using "onFormProcessed", and then save the data by the plugin itself.

**Comment by mahagr** [comment]
You can do that and it'll work just fine (especially with Form 3.0). There is data manager plugin, but a better way to load the data is to do that from your plugin -- for now.
