### ISSUE TITLE
Grav inlineJS BREAKS Content-Security-Policy

### ISSUE THREAD

**Issue by goldjg** [getgrav/grav#2370]
I’m trying to implement a content-security-policy on my blog (based on the blog site skeleton) and finding that Grav’s extensive use of inline resources means I have to add 'unsafe-inline' to both my script-src and style-src directives which defeats the purpose of a CSP somewhat.

I need to add it on style-src because the hero-image in Quark uses style="background-image: url({{ hero_image.url }} and CSP automatically blocks that because it’s an in-line style element.

I also find that the ganalytics plugin is problematic because it uses addInlineJs - though I could probably just create my own js file for it and do away with the plugin.

jscomments I could tweak the twig template to insert a nonce - my problem there is that while I’ve created my own quark theme (using streams per the official advice) and it creates a nonce variable which can be set in the CSP at render time, I can’t access it in jscomments plugin template as it seems to be generated after the page content has been rendered.

I found this, which seems a reasonable starting place - https://gist.github.com/ndavison/29708215fd5b4af2f2e2379dd2c24c96 - could the behaviour in this gist be made optional in changing a grav setting? So no change in behaviour unless you explicitly choose it?

**Comment by rhukster** [comment]
I think this is specific to Quark theme and it's use of `Assets::addInlineJS()`.  This function really just outputs `<script></script>` tags and puts the variable between them.  This is done out of simplicity and ease of use as a base theme.  You can easily modify Quark, or better yet, create a new theme with your own JS code self-contained in external files.  

This is not a fundamental problem with Grav, it's just a design decision for the default (but not required) Quark theme.

I appreciate your thoughts on the subject though 👍
