### ISSUE TITLE
Theme language.yaml unable to override

### ISSUE THREAD

**Issue by dameert** [getgrav/grav#2372]
Using the twentyfifteen skeleton I found that I am unable to override the themes languages.yaml content. I limit the site to 'en' only, so I put my overridden key in /user/languages/en.yaml (as per the docs). But my overridden key is not shown, unless I remove the original languages.yaml file (which is not the goal).

I found that this is because of the mergeRecursive function. The function is working correctly for plugin translation overrides, which are loaded early using the ConfigServiceProvider class. 
However, the Theme translations are only loaded later via the ThemesProcessor class. At that point the overriding file /user/languages/en.yaml is already loaded, and then the ThemesProcessor adds it's default translations (putting the original translations for the theme as the end translation to use).

I can think of two solutions to solve this problem quickly (I will provide pull requests):

1. Store the theme override translations in user://languages/theme.yaml and load them after the initial theme://languages.yaml file
2. Add unexisting keys from theme://languages.yaml to the language cache by adding an "inverse" parameter to the mergeRecursive function.

I am not sure which one is the best, the first one adds a new approach to overloading of translation keys for themes. The second one might have a performance impact when loading translation data from the theme

**Comment by rhukster** [comment]
I will evaluate these when I get a spare moment.  Thanks.

**Comment by rhukster** [comment]
Sorry it’s taken me so long to look at these.  I was thinking about this the other day and it occurred that it might make more sense to merge all the user/languages after the the theme.  This way all, user Lang files are process naturally after everything else. 

The intention of the user Lang files is to provide a way to override anything that comes before it. 

I will look into implications if this.  If it’s not feasible for a reason I can’t think of right now I’ll go with one of your PRs. Thanks

**Comment by dameert** [comment]
Indeed, I understand your reasoning. PR #2373 comes closest to this intention if it won't work out for all language files.

**Comment by dameert** [comment]
Feel free to close #2374

**Comment by dameert** [comment]
Closing due to age of the issue (2year - cleanup in my Issues to follow up.
