### ISSUE TITLE
Unable to install v1.5.8

### ISSUE THREAD

**Issue by RedVortex** [getgrav/grav#2375]
We saw that version 1.5.8 was released so we decided to upgrade to it. However, we're getting an error while installing v1.5.8.

This used to work with 1.5.6 and 1.5.7 but isn't working with 1.5.8, preventing us from upgrading to the latest grav version.

```
bash-4.4# composer create-project getgrav/grav ~/webroot/grav 1.5.8
  [InvalidArgumentException]
  Could not find package getgrav/grav with version 1.5.8.
```

**Comment by rhukster** [comment]
This has been sorted.  Seems Packagist required updating to the new webhook method to keep working in 2019.  All done.
