### ISSUE TITLE
Inflector properties not initialized properly

### ISSUE THREAD

**Issue by tomzx** [getgrav/grav#238]
Hi,

I'm using the simplesearch plugin which contains `{{ 'result'|pluralize(search_results.count) }}` in `templates/simplesearch_results.html.twig`. When that part of code gets executed, it throws an exception as it is trying to loop over a string when `Inflector::pluralize()` is called. That is because the calls to `$language->translate()` in the `Inflector` constructor fail to return an `array` and thus return the provided `string`.

Is there anything that is supposed to be done at the configuration level for the `Inflector` to work properly or is this simply a bug?

**Comment by flaviocopes** [comment]
You're right, I recreated the problem. Should be fixed with my PR, you can check it out while waiting for the merge: https://github.com/getgrav/grav/pull/239

**Comment by rhukster** [comment]
This should be sorted with latest develop branch.
