### ISSUE TITLE
[add-resource] New Plugin: Editable with ContentTools

### ISSUE THREAD

**Issue by bleutzinn** [getgrav/grav#2380]
While still in Beta, I would like to see my new plugin being added to the Grav Repository.
Here are the project details: https://github.com/bleutzinn/grav-plugin-editable-contenttools

Thanks,
Ron Wardenier

**Comment by rhukster** [comment]
Interesting Ron!

**Comment by rhukster** [comment]
Should show in GPM soon.

**Comment by bleutzinn** [comment]
Thanks!
After discovering and fixing one minor 'thing' I decided to remove the " testing" label and release version 1.4.7.

The `blueprints.yaml` has changed accordingly. Is the change in `blueprints.yaml` sufficient for the GPM to move the plugin from the testing to the stable channel ?
Again thanks!

**Comment by w00fz** [comment]
Yes that’s enough, make sure when you do the github release you don’t flag as pre-release

**Comment by bleutzinn** [comment]
Thanks for the tip. Just released version 1.4.7.
