### ISSUE TITLE
Blog list only displays 5 posts.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#2381]
I am on Grav 1.5.8, I use admin dashboard to manage posts and change settings, etc.

I just found when I have 6 posts, only the last 5 are displayed on the list, and the first one is missing.

Tried to change page count to 100, no luck.

How can I display all posts, with pagination?

**Comment by hifall** [comment]
Oops, missed the page content limit. Sorry about that.

**Comment by thagxt** [comment]
I'm having the same problem as you. Can you please explain how you fixed it?! Thanks
