### ISSUE TITLE
Avoid refreshing admin dashboard after saving.

### ISSUE THREAD

**Issue by hifall** [getgrav/grav#2382]
I use the admin dashboard to create posts. Each time I hit Save, the whole dashboard refreshes, which is not great UX. IMHO, it should update what's necessary instead of the whole dashboard.

Refreshing the whole dashboard cause the user to lose the focus, scroll position, etc. It seems like a small issue, but when you have many small saves, these add up.

**Comment by rhukster** [comment]
This is something we plan on addressing with a major rewrite of the admin in a future revision. Moving more to a client-based solution rather than relying so heavily on the server to do ALL the work.
