### ISSUE TITLE
[remove-resource] Delete Antimatter Open Publishing theme

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#2389]
I think the time has come to retire the Antimatter Open Publishing theme, as my Quark Open Publishing theme is where I want to focus on esp. for Grav 2 etc.

Please remove the Antimatter Open Publishing theme at:
https://github.com/hibbitts-design/grav-theme-antimatter-open-publishing

Thanks very much,
Paul

**Comment by rhukster** [comment]
Sorry missed this paul, will get this done soon

**Comment by rhukster** [comment]
Removed.

**Comment by paulhibbitts** [comment]
Thanks very much Andy!
