### ISSUE TITLE
Non-config user specific yaml files not found

### ISSUE THREAD

**Issue by gkurucz** [getgrav/grav#2390]
Hi!

I love Grav so far. I have a question though and couldn't find any answers to this...

I've built a very simple plugin for Swagger UI to display OpenAPI specifications written in `json` and `yaml`. It works fine for the `json` files but the `yaml` files are not found. This is how the thing works: I have a `swagger-ui.html.twig` template and have these two files, `user/pages/01.swagger-ui/swagger-ui.md` and `user/pages/swagger-ui/petstore.json` and the display is handled via the plugin and some custom theme implementations. Even if there wasn't anything happening in the background I can reach `petstore.json` but if I rename it to `yaml` then it's not found anymore, cache clears don't help either. I assume since `yaml` is used for configuration everywhere there's just a general filter for this extension.

Would the same happen if there was a [dedicated folder](https://learn.getgrav.org/forms/blueprints/how-to-add-file-upload) for uploading these files? Can you elaborate what is happening or how to make exceptions for certain yaml files?

**Comment by rhukster** [comment]
By default grav only serves files with these extensions:

```
pages:
  types: [html,htm,json,xml,txt,rss,atom]
```

To override this, you need to edit "Page Types" in the system.yaml configuration (either in admin or via a `user/system/config.yaml` override)
