### ISSUE TITLE
"Framework" routing in when building upon grav

### ISSUE THREAD

**Issue by andrewfenn** [getgrav/grav#2391]
I'm investigating grav as a good base for me to build more complicated websites out of and would like to know what is the best practice for adding custom routes on top of grav to load our own PHP code in the typical framework manner that is available in other PHP products.

What I am looking for is how to add a custom GET or POST route that can be routed to my own class? This would be ideal for me to flow into my own code. Any pointers on best practices on how that's done in Grav?

**Comment by rhukster** [comment]
In the new Grav 1.6 version (currently in RC state), we have implemented new classes under `src\Grav\Framework`. Two new helpful things to check are the new `Route` and `RequestHandler` set of classes.  We plan to move Grav core to use these, but right now we are making use of them in 3rd party plugins.

These are not really documented, but you can inspect the code and see what they are doing.  Hopefully we can have some examples and some 'core' plugins using them soon.

**Comment by andrewfenn** [comment]
Thank you for the helpful response. Sorry to bother, but could you also provide an example of the 3rd party plugins using the new classes?

**Comment by mahagr** [comment]
Actually, Grav 1.6 already uses PSR-7 and PSR-15 and allow you to inject your own routing into Grav as long as you use/wrap it to use PSR-15.

You can hook into a few events, including `onRequestHandlerInit` where you can access both `$event['request']` and `$event['handler']`, which allows you to add your own handlers -- or you can just return `Psr\Http\Message\ResponseInterface` in `$event['response']` and stop propagation.
