### ISSUE TITLE
file is too big?

### ISSUE THREAD

**Issue by ash0080** [getgrav/grav#2394]
![2019-03-02 15 17 32](https://user-images.githubusercontent.com/2803210/53679545-b360a980-3d08-11e9-9736-9f5ff7bff038.png)
![2019-03-02 16 01 05](https://user-images.githubusercontent.com/2803210/53679555-da1ee000-3d08-11e9-80a1-e3c0035cd6b6.png)
![2019-03-02 16 04 15](https://user-images.githubusercontent.com/2803210/53679565-fae73580-3d08-11e9-83a0-dfcfd95a9076.png)
![2019-03-02 16 34 21](https://user-images.githubusercontent.com/2803210/53679580-16ead700-3d09-11e9-95bb-94f27136f7e0.png)

is this a bug or my mistake?

**Comment by axel-rank** [comment]
Where do you upload? In admin? In frontend form?
Check form plugin setting: max filesize.

**Comment by ash0080** [comment]
in admin

**Comment by ash0080** [comment]
any tips？

**Comment by rhukster** [comment]
There's a grav config in system: `grav.config.system.media.upload_limit`

**Comment by axel-rank** [comment]
I cannot set this in admin plugin? Why?
In my usr/config/system.yaml the value for media upload_limit is: 2097152. ???
Is this the standard setting?

**Comment by ash0080** [comment]
![屏幕快照 2019-03-12 10 49 03](https://user-images.githubusercontent.com/2803210/54171194-818fd580-44b4-11e9-8b3c-2310066558db.png)
seems the config is 1G, but the limit still 256Mb, a bug?

**Comment by rhukster** [comment]
Actually the system `media.upload_limit` option has been removed, even though there's still some places in the code that uses it if set.  There is still a reference in forms for via `files.filesize`, this defaults to `0` unlimited, but it's possible you have this set?

**Comment by axel-rank** [comment]
Still documented as if I could set this in admin panel:

![admin](https://user-images.githubusercontent.com/12480617/54183968-c2ccb900-44a5-11e9-9513-69d906010b6c.png)

**Comment by rhukster** [comment]
Ok, I've dug into this quite a bit and it gets complicated....

First we had a setting `system.media.upload_limit`, then we had various options in form config like `form.files.filesize` as well as some admin plugin limits I can't recall.  Not to mention the default PHP values for `post_max_size` and `upload_max_filesize`.  These were all used in various places, but ultimately the PHP values are the hard-stop-limits.

Back in October of 2017 (Grav 1.3.7), this was simplified by removing the actual option for `system.media.upload_limit`, creating a method in Utils to get the system PHP values, and overriding any existing configuration settings for `system.media.upload_limit` with the smallest value provided by PHP settings. It was done this way to minimize the impact of changing the functionality mid-release cycle, so the old value could still be used, by plugins (admin, form, etc) but would use PHP provided values.

In the Grav 1.6 branch, I've now cleaned this up and completely removed all references to `system.media.upload_limit` and explicitly used the `Utils::getUploadLimit()` function to make this clearer going forward.  Admin and Forms plugins have also been updated in their respective RC branches in the same way.  

I'm testing all this with Grav 1.6, so there well may have been other fixes between this and Grav 1.5, but as I'm trying to get 1.6 out ASAP, I'm putting my focus there and not in 1.5 at the mo.

The basic rules are:

1) In Admin plugin, the filesize limit in File and PageMedia fields is limited by the PHP settings alone.
2) In Form plugin, the filesize limit in File field is limited by the field setting of `filesize:` if set, then the `form.file.filesize` if set and not 0, then the PHP settings.

I'm sure this will all be sorted when Grav 1.6 is released.

**Comment by lorddoumer** [comment]
after updating to 1.6 today file upload in the admin panel doesn't work anymore:  despite the maximum filesize is set to 2048M in the php.ini, which also the info-tab recognices, when trying to upload a file I get a NEGATIVE maximum file size; 
![screenshot](https://user-images.githubusercontent.com/7159996/56078128-c032eb80-5de4-11e9-9806-06b9692cfbae.png) 
how to fix this? never had any problem with 1.5

**Comment by rhukster** [comment]
Strange one, might need to get a copy of you `php.ini` and your Grav `system.yaml`

**Comment by rhukster** [comment]
Also is this with a Page media upload or some custom form you have?

**Comment by lorddoumer** [comment]
Ah, page media sorry not to mention it - form would be easy because there is an option for the upload size (page media worked with 1.5 also without problems when there was the option for it). The file is just a jpg (1920x1440px, 490kb), server is apache with php 7.2 fpm - please find attached the ini and yaml, please let me know if you need anything else.  

[php.ini.txt](https://github.com/getgrav/grav/files/3077245/php.ini.txt)
[system.yaml.txt](https://github.com/getgrav/grav/files/3077246/system.yaml.txt)

**Comment by rhukster** [comment]
@lorddoumer if you inspect you can fire up your browser developer tools, and inspect the **Page Media** element, you should see this `<div id="grav-dropzone"></div>` element.  In there is a `data-dropzone-options` that contain some settings.  One of those is the `maxFilesize` in megabytes.  What does yours look like?

![Image 2019-04-14 at 8 58 53 PM](https://user-images.githubusercontent.com/1084697/56105217-61f72d00-5ef8-11e9-97f7-a0e01b0e519a.png)

**Comment by lorddoumer** [comment]
Yes, there it is - and it has the same strange value: 
![screenshot](https://user-images.githubusercontent.com/7159996/56113352-ea5be900-5f5d-11e9-8dec-63686f2b368e.png)

Where does this coem from?

**Comment by rhukster** [comment]
I think it has something to do with the rounding logic.  can you try replacing the `Utils::parseSize()` function with this:

```
    public static function parseSize($size)
    {
        $unit = preg_replace('/[^bkmgtpezy]/i', '', $size); 
        $size = preg_replace('/[^0-9\.]/', '', $size);
        if ($unit) {
            return round($size * pow(1024, stripos('bkmgtpezy', $unit[0])));
        } else {
            return round($size);
        }
    }
```

**Comment by lorddoumer** [comment]
@rhukster that's it, upload working fine again, thanks! :)

**Comment by rhukster** [comment]
Sweet, should be in the next release later today.

**Comment by prismplex** [comment]
Still having the same issues with Grav 1.6.8 and PHP 7.3
Tried also with a newly installed Grav, so I think the problem is maybe somewhere at my end. Should I take care about a special php setting beside `upload_max_filesize` or `post_max_size`?
Thank you in advance!

![upload](https://user-images.githubusercontent.com/39129550/57022587-e30c2f00-6c2f-11e9-8582-abd8f2949f25.png)
![grav-dropzone](https://user-images.githubusercontent.com/39129550/57022627-033bee00-6c30-11e9-99c7-aec42d582749.png)

**Comment by rhukster** [comment]
What values do you have set for those in php.ini?

**Comment by prismplex** [comment]
`upload_max_filesize` 16G
`post_max_size` 0

**Comment by rhukster** [comment]
I just can't replicate what you are seeing with those values.  I get `"maxFilesize":0`

Can you try changing your values to sane ones?  like:

```
upload_max_filesize = 256M
post_max_size = 512M
```

Does that fix things? or do you still get weird negative numbers?

**Comment by rhukster** [comment]
Another thing to try.  In `user/plugins/form/classes/Form.php`, replace the `getMaxFilesize()` method with this:

```
    public static function getMaxFilesize($mbytes = false)
    {
        $config = Grav::instance()['config'];

        $system_filesize = 0;
        $form_filesize = $config->get('plugins.form.files.filesize', 0);
        
        $upload_limit = Utils::getUploadLimit();
        if ($upload_limit > 0) {
            $system_filesize = intval($upload_limit / static::BYTES_TO_MB);
        }

        if ($form_filesize > $system_filesize || $form_filesize === 0) {
            $form_filesize = $system_filesize;
        }

        if ($mbytes) {
            return $form_filesize * static::BYTES_TO_MB;
        }

        return $form_filesize;
    }
```

See if that helps?

**Comment by prismplex** [comment]
Thank you!
The modded function did not work, but I changed the value of `post_max_size` from 0 to 512M. Now it is working perfectly!

**Comment by kentchan4** [comment]
Hi, I am havng this issue as well, trying to upload a video 52M but saying file is too big.

Checked post_max_size and upload_max_size were 2048M and 102400M (for my Nextcloud use) but Grav configuration only read it 8M. I tried restart php8.3-fpm and apache2 but still no use. I can upload very large file into Nextcloud without problem.

I found out it was base on the PHP's default value like memory_limit showing 128M but my php.ini is 512M... but Grav show the load configuration path is /etc/php/8.3/fpm/php.ini 

I won't modify any yaml file and can guide me how to trace the problem and fix ?

**Comment by kentchan4** [comment]
Yes, the value like this:

upload_max_filesize = 102400M
post_max_size = 20480M 

however Grav show post_max_size = 8M, upload_max_filesize = 2M (which I think it is PHP's default value)

**Comment by rhukster** [comment]
Yes it does seem like the php.ini file you are editing is not getting picked up for some reason. And you are sure you are using PHP 8.3 via FPM?  Maybe you have an override of these settings in an .htaccess. 

Maybe try some of these suggestions: https://stackoverflow.com/questions/34773652/changes-to-php-ini-not-reflected-in-phps-phpinfo

**Comment by kentchan4** [comment]
Thank you !!! Finally I found out the php.ini having invalid character, no idea why Nextcloud can read it successfully.

Anyway, after I remove the character, Grav successfully read php.ini!

thanks again for your kind help!
