### ISSUE TITLE
Preload css

### ISSUE THREAD

**Issue by AstroHaze** [getgrav/grav#2399]
Hi dev Grav, i have a question, is possible add rel="preload" in css?
It would be great to be able to use this tag to optimize performance

**Comment by w00fz** [comment]
Not in the 1.5. In 1.6rc you should definitely be able to pass any attribute to the asset, including `rel`. Assets manager had been rewritten quite a bit.

I have to test it, though, I know `rel=“stylesheet”` was forced in 1.5 but I’m pretty sure that’s not the case in 1.6 anymore.

**Comment by rhukster** [comment]
I do plan on documenting this for 1.6
