### ISSUE TITLE
"Call to undefined method Symfony\Polyfill\Mbstring\Mbstring::mb_ord()"

### ISSUE THREAD

**Issue by unmick** [getgrav/grav#2402]
Hello,

Since the last update of Grav (1.5.8) , i have this message "Call to undefined method Symfony\Polyfill\Mbstring\Mbstring::mb_ord()" from /vendor/symfony/polyfill-mbstring/bootstrap.php : 

 `if (!function_exists('mb_chr')) {
    function mb_ord($s, $enc = null) { return p\Mbstring::mb_ord($s, $enc); }
    function mb_chr($code, $enc = null) { return p\Mbstring::mb_chr($code, $enc); }
    function mb_scrub($s, $enc = null) { $enc = null === $enc ? mb_internal_encoding() : $enc; return mb_convert_encoding($s, $enc, $enc); }`

I have seen that it's come from the plugin : "Shopping Cart Manual Checkout Addon" and that @codiflow  have got the same issue with the grav-plugin-seo : https://github.com/paulmassen/grav-plugin-seo/issues/75

mbstring seems correctly setup : 
![image](https://user-images.githubusercontent.com/35163557/54091149-ba2c9380-437c-11e9-9899-086130d6c73b.png)

Thanks for your help.

Mick

**Comment by rhukster** [comment]
My guess would be that you have that specific method disabled for some reason.  Are you running on a hosted environment? Can you contact the support staff for your server?  What version of PHP are you running? Maybe you had an error when building/compiling mbstring library? Can you try reinstalling?

**Comment by mahagr** [comment]
My take on this is that plugin already has composer and includes a different version of polyfill.

**Comment by unmick** [comment]
Hello,
It's an hosted environment provided by OVH. Not a real chance to manage this with the technical support :-).
PHP Version 7.1.25
According to @mahagr,  I have replaced the folder /user/plugins/shoppingcart-manual-checkout/vendor/symfony/polyfill-mbstring by /vendor/symfony/polyfill-mbstring and it's well working.

FYI @codiflow

Thanks to both of you !
