### ISSUE TITLE
Invalid AJAX Response error and general unresponsiveness

### ISSUE THREAD

**Issue by MelleNi** [getgrav/grav#2411]
Hey there :)

A while ago I made a website with grav and everything was working fine. A few days ago I started getting problems out of nowhere.

When I try to update grav to a newer version I get an error: `Invalid AJAX Response`, when I navigate to a different page, I see: `Error while trying to download (code: 0): https://getgrav.org/download/core/grav-update/1.5.8 Message: URL using bad/illegal format or missing URL`.

Is this easy to fix?

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/issues/1626#issuecomment-474789895

Seems this is a duplicate issue.  Closing this one, and keeping admin one.
