### ISSUE TITLE
Add the page to onMarkdownInitialized event

### ISSUE THREAD

**Issue by Goutte** [getgrav/grav#2412]
A change suggestion to allow plugins hooking `onMarkdownInitialized` to `mergeConfig` to allow per-page configuration overrides.

```diff
system/src/Grav/Common/Markdown/ParsedownGravTrait.php
@@ -47,7 +47,10 @@ trait ParsedownGravTrait
         $this->setMarkupEscaped($defaults['escape_markup']);
         $this->setSpecialChars($defaults['special_chars']);
 
-        $grav->fireEvent('onMarkdownInitialized', new Event(['markdown' => $this]));
+        $grav->fireEvent('onMarkdownInitialized', new Event([
+            'markdown' => $this,
+            'page' => $page,
+        ]));
 
     }
 ```

Perhaps there's a better way? `$event['markdown']->page` is protected.

---

If I do make a PR about this, should it be a one-liner or like above?

**Comment by rhukster** [comment]
Yes PR please...

**Comment by mahagr** [comment]
@Goutte You can access it by `$event['page']`, DO NOT USE `$event->page`, it is different.
