### ISSUE TITLE
Can't load image

### ISSUE THREAD

**Issue by ninjaring** [getgrav/grav#2414]
Hi,
I'm using grav site on shared hosting. It's all normal before. But when I installed new site (v1.5.8) on new subdomain, it can't load all images from all pages. Markdown are fine, the generated html codes are correct, but the images are failed.

Please help.

**Comment by rhukster** [comment]
It's most likely an issue with PHP GD library.  or it could be specific to libpng or libjpg.  Do you have a URL i can look at?

**Comment by ninjaring** [comment]
Thank you. Please take a look at
https://pw.fkite.space/artikel

**Comment by rhukster** [comment]
Are you sure the files exist?

https://pw.fkite.space/images/b/0/0/7/0/b0070af9f851aaaa308a40e41d07939be9706bf4-main.jpeg

for example shows a 404 (not a creation error like I expected)

what about permissions? are they readable?

**Comment by rhukster** [comment]
Also you might want to try a full cache clear:

```
bin/grav clear --all
```

This will force images to be regenerated

**Comment by ninjaring** [comment]
I did these options and still got problem:
- Full cache clear
- Change images permission from 644 to 775 and then full cache clear
- Change back to 644 and then full cache clear
- Change /images folder permission to 777 and then 775 (plus full cache clear everytime I changed permission)
- Disable SSL and then did full cache clear

Should I repeat site installation in manual way?

Also, I got another problem when I try to update grav or install plugin from Admin control panel (Invalid response). So I just upload plugin zip directly to server

**Comment by rhukster** [comment]
It could be something related to a server rewrite issue. Ie, you have some configuration in your web server that is rewriting the location for the `/images` folder.  If the files physically exist in the filesystem, but your webserver is saying 404, that they don't exist, then you could check your web server error log to see where it's actually looking for them.

Also you could simply check your `.htaccess` (assuming apache), to see if you have a rewrite entry for images/ folder.

**Comment by ninjaring** [comment]
Ah thank you! It's all about `.htacess` in the root of main domain (not subdomain). 
Something happened to lines like this `RewriteCond %{HTTP_REFERER} !^ .....`, that make subdomain is not configured properly.

Thank you very much!

**Comment by rhukster** [comment]
cool, closing...
