### ISSUE TITLE
gpm selfupdate and selfupgrade contradiction

### ISSUE THREAD

**Issue by Romarain** [getgrav/grav#2415]
Hi,

I've installed the 1.6 branch for one of my projects.

Today, I tried to update plugins with `bin/gpm update` and it said : 

> WARNING: A new version of Grav is available. You should update Grav before updating >plugins and themes. If you continue withou                             t updating Grav, some plugins or >themes may stop working.
>
>Continue with the update process? [Y|n] Y
>
>GPM Releases Configuration: Stable
>
>Nothing to update.

Then I tried `bin/gpm selfupgrade` and it said : 
> GPM Releases Configuration: Stable
>
>You are already running the latest version of Grav (v1.6.0-rc.3) released on Fri Feb  8 00:05:27 2019

But I can see in the [branches' page](https://github.com/getgrav/grav/branches) that there's a new version of 1.6 recently added. So it seems that my _GPM releases configuration_ isn't correclty set, and try to apply stable versions instead of recent ones.

I don't know what to do to force him to apply the latest releases.

**Comment by w00fz** [comment]
It looks like you are on the wrong channel (`stable`). You should be on `testing` channel instead.

It’s a system configuration.

**Comment by Romarain** [comment]
Ah ok. I remember that someone's told me about that. 
It's in system.yaml :
```
gpm:
  releases: testing
```
I changed that and retried, but now it says : 

```
Found 16 packages installed of which 5 need updating

01.                 [v -> v]
02.                 [v -> v]
03.                 [v -> v]
04.                 [v -> v]
05.                 [v -> v]

Continue with the update process? [Y|n] Y

GPM Releases Configuration: Testing

Preparing to install Admin Panel [v1.9.0-rc.3]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...
In Folder.php line 321:

  Unknown error
```

**Comment by w00fz** [comment]
I actually fixed the no versions showing up recently. I don’t think we have a new rc out with the fix.

It is safe to update all even if it doesn’t display versions.

**Comment by Romarain** [comment]
Yeah but it fails. PHP error.
I retried again, and now it's on the Email plugin that the rror is thrown : 
```
The package Email will be updated to a new major version 3.0.0-rc.3, from 2.7.2
Preparing to install Email [v3.0.0-rc.3]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...
In Folder.php line 321:

  Unknown error
```
What's going on ?

**Comment by rhukster** [comment]
Not seen that error before... That i think might be a legit issue (in Folder.php line 321)

**Comment by w00fz** [comment]
This turns out to be a legit issue. We are fixing it.

You can manually copy the email package to be up to date for now.

Cheers.
