### ISSUE TITLE
Error Grav Update 1.5.9

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#2416]
Trying to update Grav to 1.5.9

![Bildschirmfoto_2019-03-20_20-15-33](https://user-images.githubusercontent.com/12480617/54712669-2ceff880-4b4d-11e9-82b0-266a9845af95.png)

In admin-plugin it's showing an Invalid Ajax Response Error.

**Comment by w00fz** [comment]
1.5.9 was released and immediately removed. It is not available.

Please ignore it for now, it will be properly available later today.
