### ISSUE TITLE
vundefined on theme and plugin updatedialog

### ISSUE THREAD

**Issue by tsopanid** [getgrav/grav#2421]
yesterday i upgraded grav from 1.6.0-rc.3 to 1.6.0-rc.4

today i updated my Quark to v2.0.0-rc.2 and all test release plugins (Admin Panel, Email, Form and Login) 

The Update dialog showerd:
upgrading Quark from vundefined to vundefined,
upgrading AdminPanel from vundefined to vundefined,
...

no isues after the upgrade, just the dialog/info seems broken

**Comment by rhukster** [comment]
This was actually fixed in rc.4 admin, so it should work fine going to the next update. Purely visual but disconcerting I know.
