### ISSUE TITLE
Grav 1.5.10 can't require autoload php

### ISSUE THREAD

**Issue by JDomleo** [getgrav/grav#2423]
Hi, I am honestly stuck, cannot find any related issue, I updated to Grav 1.5.10 then this shows on any webpage:

`Warning: require(C:\Users\User\Documents\Projects\tmdip.co.uk\vendor\composer/../../system/defines.php): failed to open stream: No such file or directory in C:\Users\User\Documents\Projects\tmdip.co.uk\vendor\composer\autoload_real.php on line 66

Fatal error: require(): Failed opening required 'C:\Users\User\Documents\Projects\tmdip.co.uk\vendor\composer/../../system/defines.php' (include_path='C:\xampp\php\PEAR') in C:\Users\User\Documents\Projects\tmdip.co.uk\vendor\composer\autoload_real.php on line 66`

Any clue what I should do?

Thanks in advance!

**Comment by JDomleo** [comment]
Found something similar, [https://github.com/getgrav/grav/issues/944](https://github.com/getgrav/grav/issues/944), but this person solved it by going back a commit but I haven't committed anything yet as I have not had chance to do a git repo as I am in early stages.

**Comment by JDomleo** [comment]
FIXED - Had to download Grav Core 1.5.10 and copy over user folder.

Will leave open because would like to know why it happened, if it was anything I did wrong?

**Comment by rhukster** [comment]
What version of Grav were you on before upgrading?

**Comment by JDomleo** [comment]
I was on 1.5.9. It was on my localhost. When I say it's fixed, localhost/admin won't work...

**Comment by rhukster** [comment]
what 3rd party plugins are you running (i mean other than Admin/Form/Email/Login) ? As i've had no issues with anything recent, but had a few errors upgrading from Grav v1.1.17, but it did upgrade, just gave a JS error from admin, was fine via `bin/gpm selfupgrade`

**Comment by rhukster** [comment]
btw, did you install Grav via composer or github?

**Comment by JDomleo** [comment]
I am using:

- admin-addon-user-manager
- archives
- bootstrapper
- cookieconsent
- error
- minify-html
- pagination
- relatedpages
- seo
- simplesearch
- taxonomylist
- tinymce-editor

I installed via [https://getgrav.org/download/core/grav-admin/1.5.10](https://getgrav.org/download/core/grav-admin/1.5.10)

**Comment by rhukster** [comment]
I think it might be an issue with `admin-addon-user-manager`.  This is a 3rd party plugin and it does work with some low level things, I've seen a couple of other comments on Discord chat about issues with it.

**Comment by JDomleo** [comment]
I have removed this plugin but am getting the first message,

`Warning: require(C:\Users\User\Documents\Projects\tmdip.co.uk\vendor\composer/../../system/defines.php): failed to open stream: No such file or directory in C:\Users\User\Documents\Projects\tmdip.co.uk\vendor\composer\autoload_real.php on line 66

Fatal error: require(): Failed opening required 'C:\Users\User\Documents\Projects\tmdip.co.uk\vendor\composer/../../system/defines.php' (include_path='C:\xampp\php\PEAR') in C:\Users\User\Documents\Projects\tmdip.co.uk\vendor\composer\autoload_real.php on line 66`

**Comment by rhukster** [comment]
do this:

```
bin/composer.phar install --no-dev
```

**Comment by rhukster** [comment]
actually, you might be missing the `system/defines.php` file.. can you check if it's there? and installing Grav 1.5.10 again didn't work? It appears you have some key files missing

**Comment by JDomleo** [comment]
system/defines.php is present.

Installing Grav 1.5.10 and copying my user folder didn't work, ensuring I deleted the admin-addon-user-manager plugin.

bin/composer.phar install --no-dev  opened the composer.phar file but I don't know what to do with it...

**Comment by JDomleo** [comment]
Actually, I've got localhost working again, however localhost/admin does not appear to exist again.

**Comment by rhukster** [comment]
that might be a missing `.htaccess` file at the root. Or maybe `user/plugins/admin` is now missing?

**Comment by JDomleo** [comment]
Both files are there, would it be best starting again? I've made a few templates and blueprints.

It's weird because every time there was an update for Grav or a plugin or the Boostrap4 theme, the red error box would pop up, but this is the first time I've noticed something not work.

Could it be the fact it's localhost (although thinking about it, that shouldn't make a difference)?

**Comment by rhukster** [comment]
Something is broken for you, not sure how.. I would do this:

1. Backup/Save your current site
2. Install new Grav 1.5.10 + Admin package
3. Copy your old site's `user/` folder back on top of new install.

**Comment by rhukster** [comment]
Localhost makes no difference btw.

**Comment by JDomleo** [comment]
I've just following those steps for the Grav 1.5.10 + Admin package and separately for the Boostrap4 skeleton package and localhost/admin still doesn't seem to exist for either...

**Comment by JDomleo** [comment]
Ok so new update, had to redownload admin package seperately, so localhost/admin now works, however after signing in, I get this message:

`Server Error
Sorry, something went terribly wrong!

E_NOTICE - Uninitialized string offset: 0
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.`

**Comment by rhukster** [comment]
try clearing cache?

**Comment by JDomleo** [comment]
Still same error...

What I'll do is I'll start from scratch using the Boostrap4 theme and only copy over my templates I have created, then on the next Grav update, I will try to record the update and if the error happens again, I will make a new issue.

**Comment by rhukster** [comment]
sounds good.. i'm off for tonight anyway.. best of luck!

**Comment by JDomleo** [comment]
Cheers for your help!
