### ISSUE TITLE
Login fails after changing any user account parameter

### ISSUE THREAD

**Issue by Romarain** [getgrav/grav#2424]
Here's the way to reproduce the bug : 

1. Install a fresh version of GRAV 1.6 (testing channel).
2. Right after installation, install the admin plugin.
3. Create a dummy user _with site + admin access_.
4. Backup the user's YAML for further comparison (copy + rename).
5. Login in the admin panel with the user.
6. Go in the user's **profile**, and change something (ex : the language used).
7. Save and logout.
8. Retry to login **(it will fail)**.
9. Compare the backupd YAML with the actual one : observe how the **hashed password changed**.

Workaround to temporarily fix the bug :
- Reset the password with `$bin/plugin login changepass`.

This confirm that the problem comes from the password unexpected modification.

Notes : 
I've encountered this bug about _two days_ ago.

**Comment by rhukster** [comment]
hmm.. i can't replicate this.. Can you replicate with a fresh install of 1.6.0-rc.4 with admin package?

**Comment by w00fz** [comment]
Is it possible the autocomplete from your  browser is replacing the password and as you changed the language and saved, the password got saved as well?

**Comment by Romarain** [comment]
My bash actually says : 
``` You are already running the latest version of Grav (v1.6.0-rc.4) released on Wed Mar 20 21:13:56 2019```

My admin version is : ```Admin Panel [v1.9.0-rc.4]```

**Comment by rhukster** [comment]
I think @w00fz has the rigtht of it.  I've seen that in the past where autocomplete is filling your password without you actually typing it there.

**Comment by Romarain** [comment]
> Is it possible the autocomplete from your browser is replacing the password and as you changed the language and saved, the password got saved as well?

I think it's very unlikely : I disabled the browser auto-filling, and my LastPass extension only react on the URL of the /admin root. I'll take a look at it ver closely, and I come here to confirm that.

**Comment by Romarain** [comment]
Ok so I've just tested, and you're right guys :
- First test with my LastPass extension activated : the password field of the admin user's profile is filled.
- Second test with LastPass disabled : the field isn't filled. It's blank.

So, my apologies for the disturbing.

**Comment by rhukster** [comment]
no problem, glad it's sorted.

**Comment by w00fz** [comment]
👍
