### ISSUE TITLE
mb_strpos() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by MelleNi** [getgrav/grav#2427]
Hey there,

Just updated to the latest version. Suddenly all pages have stopped working. (They seem to be working _once_, until I navigate to the page again. Clearing the cache through the grav dashboard let's me visit the page again without error.)

The error I get is `mb_strpos() expects parameter 1 to be string, object given` in file `/system/src/Grav/Common/Page/Page.php` on line `684`.

Anyone know what's up?

**Comment by rhukster** [comment]
Which version? Stable or RC?

**Comment by MelleNi** [comment]
> Which version? Stable or RC?

v1.5.10 Stable

**Comment by mahagr** [comment]
I have no idea why page content would be an object:

```php
$divider_pos = mb_strpos($this->content, "<p>{$delimiter}</p>");
```

Maybe the issue in a plugin you're using?

**Comment by MelleNi** [comment]
> 
> 
> I have no idea why page content would be an object:
> 
> ```
> $divider_pos = mb_strpos($this->content, "<p>{$delimiter}</p>");
> ```
> 
> Maybe the issue in a plugin you're using?

It seems like you're right.
