### ISSUE TITLE
Avatars not displayed with flex users

### ISSUE THREAD

**Issue by lufog** [getgrav/grav#2431]
Uploaded avatars not work when set:
```yaml
accounts:
  type: flex
  storage: file
```
Only gravatar works.

**Comment by rhukster** [comment]
Does it work if you re-upload the avatar?

**Comment by lufog** [comment]
No, reloading does not fix this.

**Comment by mahagr** [comment]
I believe I've seen this myself. Will find time to take a look.

**Comment by mahagr** [comment]
Ok, there is a slight difference in how Flex user saves the filename compared to older user.

**Comment by mahagr** [comment]
I could not fix this in Grav 1.6, but it's now fixed in 1.7.
