### ISSUE TITLE
unpredicable behviour with truncate_html filter

### ISSUE THREAD

**Issue by olivierdalang** [getgrav/grav#2432]
Hi,

The `truncate_html` filter is nice but is not predicable .

`{{ 'abcdefghijkpqrstuvwxyz'|truncate_html(10) }}` renders `<p>abcdefghij...</p>`
while
`{{ 'abcdefghijkpqrstuvwxyz'|truncate_html(100) }}` renders `abcdefghijkpqrstuvwxyz`

This is problematic as it will break html/layout depending on the string.

Cheers,

Olivier

**Comment by rhukster** [comment]
Confirmed
