### ISSUE TITLE
[add-resource] New Plugin: Antispam

### ISSUE THREAD

**Issue by skinofthesoul** [getgrav/grav#2434]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **skinofthesoul/grav-plugin-antispam**

**Comment by rhukster** [comment]
I've added this but you will need a release and all the required bits before it shows up in GPM.

https://learn.getgrav.org/16/advanced/grav-development#theme-plugin-release-process

**Comment by skinofthesoul** [comment]
Thank you for helping me out there! I hadn't really noticed the bit about GitHub releases, and that they're different from commits. I have created one and hope I've got everything right now. Please let me know if anything is still missing, and I shall take due note of the whole release process so I can do it on my own next time.
