### ISSUE TITLE
grav.user.authorize for logged in user

### ISSUE THREAD

**Issue by tihro** [getgrav/grav#2436]
I use this to show part of the page to users with ‘some.rule’ access:
```
{% if grav.user.authorize('some.rule') %}
My content
{% endif %}
```
If admin grants access while the user is already logged in, it doesn’t work. In other words, user has to logout and login to see the hidden content.

**Comment by mahagr** [comment]
I have some plans to improve the current way by adding an event to reconstruct the user object for every request. I already use this method in a custom plugin.

**Comment by mahagr** [comment]
@tihro Just a quick update. It looks like if you're using groups, changing group access will not require a logout.

**Comment by mahagr** [comment]
There's now setting in login plugin which reloads the user object on every page load, thus fixes this issue. It is by default turned off.
