### ISSUE TITLE
Errant versions shown when updating plugins

### ISSUE THREAD

**Issue by Flamenco** [getgrav/grav#2439]
See screen shot of version confirm dialog when updating using latest RC.

<img width="768" alt="Screen Shot 2019-04-10 at 9 57 28 AM" src="https://user-images.githubusercontent.com/819940/55885138-5eba1500-5b77-11e9-93ce-f8b41c730c07.png">

**Comment by rhukster** [comment]
https://github.com/getgrav/grav/issues/2421
