### ISSUE TITLE
Grav 1.6 update removes Google fonts from pipelined css

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav#2440]
Hello!  Since updating to the new 1.6 Grav... I think this might be a reoccurrence of #1763 

Previously I have been adding Google fonts to my css like this

`@import url('https://fonts.googleapis.com/css?family=EB+Garamond:400,400i,500,500i,600,600i,700,700i,800,800i');`

This @import is now omitted from the pipelined css since the update.
If I put a direct link into my base.html.twig like so

`<link href="https://fonts.googleapis.com/css?family=EB+Garamond:400,400i" rel="stylesheet">
`

my fonts reappear...

**Comment by rhukster** [comment]
Hmm.. seems this fix got missed in the Assets rewrite. I will take a look.

**Comment by MattAppleton** [comment]
thanks... hadn't tested whether using local font files and @font-face { ...} works still, but either way it seems to be a bug.

**Comment by rhukster** [comment]
local fonts definitely work as i'm using them extensively.

looking over the code, and the last 'fixes' maitas did to address this before are still there, so not sure why it's not working.  I'l create a quick test setup

**Comment by rhukster** [comment]
Ok was something else.. anyway fixed.
