### ISSUE TITLE
Video preload doesn't work correctly on Safari (Mac)

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav#2441]
I have a portfolio site that is running into a preload problems.
The example page here contains 186Mb of videos and images: https://paulcohen.info/project/esso

page uses this twig element for media items

```
{{ media.preload().html() }}
```

On a Mac running Chrome and Firefox I see the expected / correct beghaviour — ie the page loads the image / hold frames for the videos (and starts to load just the beginnings of the video files unless they are clicked on)

BUT

On Safari  /  mac (tested on 3 different machines) the pages attempts to load ALL of the videos before showing anything...

**Comment by rhukster** [comment]
Can you please provide the HTML output by the Twig for the `<video>` tags?  I'm pretty sure we're just following the HTML5 spec here, but maybe there's something specific for safari required.

**Comment by MattAppleton** [comment]
Of course, sorry...

`<video controls="1" alt=""><source src="/user/pages/01.project/02.esso/EssoTheReindeerPrincess_1080.mp4">Your browser does not support the video tag.</video>`

**Comment by MattAppleton** [comment]
same video tags in Chrome

**Comment by rhukster** [comment]
This outputs the correct preload attribute in the tags:

```
{{ page.media['sample-trailer.mov'].preload('auto').html }}
```

**Comment by MattAppleton** [comment]
thanks... changing

`{{ media.preload().html() }}`

in my template to

`{{ media.preload('auto').html() }}`

but still seems Safari is misbehaving. If it helps the full page loop is here:

```
 {% for filename, media in page.media.all %}
                    {% if uri.param('slide') and md5(filename) == uri.param('slide')%}
                        {% set initial_slide = loop.index0 %}
                    {% endif %}
                    <div class="PCmystery">
                        {{ media.preload('auto').html() }}

                        <div class="title"> {{ page.title }} <span class="trans">({{ loop.index ~ ' of ' ~ loop.length }})</span></div>
                    </div>
                {% endfor %}
```

**Comment by rhukster** [comment]
If the output complies with the HTML5 video tag, then we are doing what we can, and the problem lies at Safari's feet: https://stackoverflow.com/questions/49799456/html5-video-tag-not-playing-video-in-safari-untill-it-is-fully-downloaded

**Comment by jleaders** [comment]
On another project I'm on, i noticed safari does not play all webm codecs. Also safari does not record video the way firefox and chrome can. Apple seems about a year behind
