### ISSUE TITLE
Left Trim function issue

### ISSUE THREAD

**Issue by petira** [getgrav/grav#2443]
When I using the Left Trim function on a string containing `com`, this is also deleted. Specifically for `'/sometext/computer/cpu'|ltrim('/sometext/')` is not a result `computer/cpu`, but only `puter/cpu`.

**Comment by rhukster** [comment]
This is how `ltrim` works in PHP.  The string is not a word, it's a list of characters: https://www.php.net/manual/en/function.ltrim.php, so all those individual characters are going to be stripped out.

**Comment by petira** [comment]
Okay, but I still do not understand why the part that is not selected is removed from the string. In my case, the list of characters `com`.  When I use `'/sometext/hardware/cpu'|ltrim('/sometext/')` the output is correct `hardware/cpu`.

**Comment by mahagr** [comment]
I think that @rhukster misread your example. I have no idea what could cause this, maybe you have a plugin that strips the output afterwards. Can you try to `{{ dump('/sometext/computer/cpu'|ltrim('/sometext/')) }}` to see if debugbar shows the right string?

**Comment by petira** [comment]
```
Grav v1.6.2
Environment Name: example
Cache: [true] Setting: [auto] Driver: [file]
Page cache missed, rebuilding pages..
Routed to page /computer (type: default)
puter/cpu
```

**Comment by mahagr** [comment]
Looks like the issue is in `ltrim()` then... Not sure why it would ever do that, though!

**Comment by petira** [comment]
@rhukster, can you reopen this issue? I will try to see if this issue also occurs in `rtrim` too. I think there is a reason to find the problem.

**Comment by mahagr** [comment]
```twig
{{ dump('/sometext/computer/cpu'|ltrim('/sometext/')) }}
```
outputs:
```
computer/cpu
```

Works for me.

**Comment by rhukster** [comment]
The `ltrim` and `rtrim` filters are literally wrappers for PHP's functions:

```
    public function rtrimFilter($value, $chars = null)
    {
        return rtrim($value, $chars);
    }

    /**
     * @param string $value
     * @param null $chars
     *
     * @return string
     */
    public function ltrimFilter($value, $chars = null)
    {
        return ltrim($value, $chars);
    }
```

**Comment by petira** [comment]
Thank you. The error is obviously on my server side. I will test and let you know.

**Comment by petira** [comment]
So, `ltrim` works differently than I thought. As @rhukster said, it is not a replacement string, but a character mask. What I needed is filter the `slice` together with the `length` filter.

@mahagr: `{{ dump('/sometext/computer/cpu'|ltrim('/sometext/')) }}` works for me too. But when I replace `/sometext/` some other string, it behaves differently.

**Comment by mahagr** [comment]
Right, `ltrim` is meant to replace individual characters, not beginning of a string. :)

You're using wrong function.
