### ISSUE TITLE
Remote assets disappear once page is cached

### ISSUE THREAD

**Issue by Tugzrida** [getgrav/grav#2445]
Potentially related to previous issues #101 and #770, and branching from #2216, remote assets are(in some cases) only output upon the first page load after a cache clear, completely absent from any subsequent refreshes.

On a clean install of 1.6.3 (plus admin & gantry, also verified before installing gantry), I tested adding FA5 CSS via twig to a single page (`{% do assets.addCss('https://use.fontawesome.com/releases/v5.8.1/css/all.css') %}`) and via Gantry > Page Settings > Assets to the whole site with different pipelining options selected, the results of which are summarised here:

| Pipelining... | Twig | Gantry 5 |
| ------------ | ---- | --- |
| off | `<link>` present in first load only | `<link>` always present |
| on, include externals off | `<link>` present in first load only | `<link>` present in first load only |
| on, include externals on | resource present in pipeline for first load only |  resource always present in pipeline |

**Comment by rhukster** [comment]
i'm aware of this particular issue, and will look at it shortly.

**Comment by rhukster** [comment]
Ok, please test the fix.

**Comment by Tugzrida** [comment]
Works perfectly now when adding via Gantry, however nothing seems to have changed from my table above when doing it via twig. Just to check what I'm doing there: in the Admin panel, I've been enabling twig processing for the target page, then adding the above twig to the top of the page.

**Comment by rhukster** [comment]
I'm not sure you tested with all the changes, because i've tested this (outside of Gantry) and it works perfect in all combinations.  here's: 

```
cache:
  enabled: true
  check:
    method: file
assets:
  css_pipeline: true
  css_pipeline_include_externals: false
  css_pipeline_before_excludes: false
  css_minify: true
```

After several reloads with cache on...

![Image 2019-04-13 at 9 56 05 PM](https://user-images.githubusercontent.com/1084697/56088112-2ba5a900-5e37-11e9-925f-aa858ac2ce5b.png)

**Comment by rhukster** [comment]
btw my Twig:

```
{% block stylesheets %}
    {% do assets.addCss('https://use.fontawesome.com/releases/v5.8.1/css/all.css') %}
    {% do assets.addCss('theme://css-compiled/spectre'~compress) %}
    {% if theme_var('spectre.exp') %}{% do assets.addCss('theme://css-compiled/spectre-exp'~compress)  %}{% endif %}
    {% if theme_var('spectre.icons') %}{%  do assets.addCss('theme://css-compiled/spectre-icons'~compress) %}{% endif %}
    {% do assets.addCss('theme://css-compiled/theme'~compress) %}
    {% do assets.addCss('theme://css/custom.css') %}
    {% do assets.addCss('theme://css/line-awesome.min.css') %}
{% endblock %}
```

**Comment by Tugzrida** [comment]
I'm still seeing it, here's exactly what I'm doing in an empty folder on my server:
`git clone https://github.com/getgrav/grav.git .`
`bin/grav install`
`bin/gpm install admin`

Then in admin, turn on debugger and edit default home page so it is as follows:
```
---
title: Home
body_classes: 'title-center title-h1h2'
process:
    markdown: true
    twig: true
---

{% do assets.addCss('https://use.fontawesome.com/releases/v5.8.1/css/all.css') %}

<i class="fab fa-keybase"></i>

# Say Hello to Grav!
...
```

Then the initial load:
![Screen_Shot_2019-04-14_at_14_17_11](https://user-images.githubusercontent.com/11975357/56088295-06f61380-5ec1-11e9-9cbb-c54a46c864d6.png)

And subsequently:
![Screen_Shot_2019-04-14_at_14_17_39](https://user-images.githubusercontent.com/11975357/56088296-18d7b680-5ec1-11e9-9023-87dbbca5d2ee.png)

Sorry if I'm doing something wrong, I'd normally just do it through gantry, but thought a theme-non-dependent test would be useful.

**Comment by rhukster** [comment]
Ok, well there's your problem.  You are adding the asset in your content, and the content get's cached and the Twig will get lost.  If you want to do it that way you need to set:

```
never_cache_twig: true
```

In your frontmatter.

**Comment by Tugzrida** [comment]
Ah, thanks, I don't often use twig so I forgot!
