### ISSUE TITLE
Taxonomy filter stopped working for integer values

### ISSUE THREAD

**Issue by brickcamp** [getgrav/grav#2446]
Hi there,

I just noticed that taxonomy terms formatted as integers stopped working with URL taxonomy filters. I reproduced this behaviour with Grav 1.6.3 and the vanilla develop branch.

Here's an example of what I mean: Consider a page with a YAML header [containing a string and an integer term](https://gitlab.com/brick.camp/brick.camp/blob/529544ead1977c6bb0a303112958a6d6553ffb6c/pages/21.tech/headlight-square/tech.md#L23):

```
taxonomy:
  count: ["1", 2]
```
What happens is that [a URL filter on the first](https://brick.camp/techs/with/stud_tilt_angle:90) works properly but [a URL filter on the second](https://brick.camp/techs/with/stud_tilt_angle:180) fails to deliver a result. Before the latest release, both worked. (I linked my real-world example for reference).

Changing every integer term to string isn't an option for me as I have a huge amount of them. I already [tried to strval every term automagically](https://gitlab.com/brick.camp/brick.camp/blob/529544ead1977c6bb0a303112958a6d6553ffb6c/plugins/brick-camp/classes/Techs.php#L111) via plugin hook. It works locally, but not on production. I'll keep on tinkering around, but maybe there are more people out there having this issue.

Edit: Fixed typo

**Comment by rhukster** [comment]
This is 'probably' related to the stricter YAML parsing in Symfony 4.2 (https://learn.getgrav.org/16/advanced/grav-development/grav-16-upgrade-guide#yaml-parsing)

I will investigate because it probably needs to have the data normalized to strings.

**Comment by brickcamp** [comment]
I fixed it by doing this at "onPageProcessed" ([here in context](https://gitlab.com/brick.camp/brick.camp/blob/3c342acadad5c5111fa93cad694a9bf215caf49d/plugins/brick-camp/brick-camp.php#L87)). Works for me now, but maybe has side effects for others who depend on integers elsewhere 🤔 

```
        $page = $event['page'];
        $taxonomy = $page->taxonomy();
        foreach ($taxonomy as $tax => $terms) {
            foreach ($terms as $key => $term) {
                $taxonomy[$tax][$key] = strval($term);
            }
        }
        $page->taxonomy($taxonomy);
```

**Comment by rhukster** [comment]
Please try the fix I just commited above.  Thanks!

**Comment by brickcamp** [comment]
This fix raises some issues with handling post taxonomies/terms as arrays. In my custom coding (which I can adapt - it's a mess honestly) as well as in the related-pages plugin, seen here:

![Bildschirmfoto-20190413224555-1276x544](https://user-images.githubusercontent.com/49322756/56085085-f2bd0280-5e3d-11e9-9ec6-2dfe6072d99d.png)
[Zip of full error page](https://github.com/getgrav/grav/files/3076720/Array_intersect.html.zip)

Maybe also elsewhere but this is what comes up on my page 🤔

**Comment by rhukster** [comment]
I can't seem to replicate this error... I'm using the blog skeleton: https://getgrav.org/download/skeletons/blog-site/2.0.0

It has taxonomy plugin, as well as taxonomy with only one entry (such as `category: blog`)

```
taxonomy:
    category: blog
    tag: ['1', 2, journal, link]
```

**Comment by rhukster** [comment]
I guess the problem might be is your taxonomy has arrays further in where it shouldn't have.  Can you give me a sample of the pages taxonomy that are causing the problems???

**Comment by brickcamp** [comment]
No further arrays that I'm aware of. To reproduce, pull vanilla Grav develop branch, [replace the user folder by this user.zip](https://github.com/getgrav/grav/files/3077303/user.zip) and run bin/grav install for the dependencies. The error occurs on `/tech/technic-brick-octagon`. :thinking: 

I honestly don't know why there is no issue with the skeleton, I tried it myself but didn't dive in deeper to force it there.

**Comment by rhukster** [comment]
it's probably that partcount not only being a single item, but not being an array: 

```
taxonomy:
  part: ["3894", "32000", "2780"]
  partcount: 80
```

I will look into it today, even though this is not formatted correctly, it should still be backwards compatible with stuff that worked in 1.5.

**Comment by brickcamp** [comment]
Thanks a lot! 👍 I'll look for ways to bulk update the formatting on my website.

**Comment by rhukster** [comment]
OK this should fix it once and for all! 

https://github.com/getgrav/grav/commit/9a5fa7e6998fb07e2555dac4822fbd8eff63d75c

**Comment by brickcamp** [comment]
Thank you so much! I'll test it in the evening after work :+1:

**Comment by brickcamp** [comment]
Tested it, works perfectly - thanks once again for your patience with this issue. I finally close it now.
