### ISSUE TITLE
Update issue after Grav core 1.5.x to 1.6.x when Configuration -> System -> Languages is not empty

### ISSUE THREAD

**Issue by jgate** [getgrav/grav#2447]
When the Configuration -> System -> Languages is set to multi language, e.g.  **de**  **en** it is not possible to update the plugins after Grav core update to version 1.6.x.
[Update to 1.6.pdf](https://github.com/getgrav/grav/files/3077070/Update.to.1.6.pdf)

**Comment by rhukster** [comment]
Weird that language would make any difference.. i'll investigate...

**Comment by rhukster** [comment]
I've tried to recreate this to no avail.  I really don't think it's got anything to do with the multilang settings.  More likely it's related to some JS error from something else.  Can you please open up your developer console in your browser and look for JS errors in the console tab?

Also, what are ALL the plugins and versions of those you have installed?  Maybe try disabling that "Admin Addons Media Rename" one and test? Those ones that inject things into the admin are most likely to be causing the errors.

**Comment by jgate** [comment]
You're right, it's the Admin Addon Media Rename plugin which is causing the problem.
Sorry for the issue report.
