### ISSUE TITLE
Agency Theme/Skeleton Demo Error Since Grav 1.6

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#2448]
![Bildschirmfoto_2019-04-14_10-29-58](https://user-images.githubusercontent.com/12480617/56090288-bd95cc00-5ea0-11e9-8c2b-8c2f15b5fa7e.png)

**Comment by rhukster** [comment]
I think this will resolve it: https://github.com/getgrav/grav/commit/d502ff08c1ca1881dedb4b6f43480e4329c1afe8

If not, then i need to see the full "whoops" error output.

**Comment by axel-rank** [comment]
Yes, your commit resolves the issue.

**Comment by rhukster** [comment]
Cool, i want to take a look at a couple more issues today, and i'll get the release out.
