### ISSUE TITLE
[add-resource] New Plugin - Deferred Instagram

### ISSUE THREAD

**Issue by Wunsz** [getgrav/grav#2449]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **thewunsz/grav-plugin-deferred-instagram**

In short I extended the functionality of the existing plugin:
**artifex404/grav-plugin-instagram**

This allows to fetch the Instagram feed after the page is loaded since the first call can take some time.

**Comment by rhukster** [comment]
I added this repo: `Wunsz/grav-plugin-deferred-instagram` as the other one didn't exist.  Should get picked up in next regen of GPM.
