### ISSUE TITLE
metadata settings in site.yaml - no effect

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#245]
After upgrade to GRAV 0.9.34 (bin/gpm selfupgrade) my metadata settings in usr/config site.yaml file have no effect anymore.
description, author, generator settings—> no effect
cleared all cache (grav, browser), still no effect

**Comment by rhukster** [comment]
I will investigate this.  What theme are you using btw?

**Comment by rhukster** [comment]
Should be fixed in develop
