### ISSUE TITLE
Overwrite users in environment configuration

### ISSUE THREAD

**Issue by hniemann** [getgrav/grav#2450]
I need to change admin password in staging and prod. 
Can I overwrite users in the environment configuration?
I have tried to put the users in user/localhost/accounts but it doesn't work.

**Comment by mahagr** [comment]
You will need to override `accounts://` stream in the stream configuration for that site.

**Comment by hniemann** [comment]
Can you give me an example for that?

**Comment by mahagr** [comment]
Here is documentation from the old way: https://learn.getgrav.org/16/advanced/multisite-setup

The new way is basically the same, but you can use `streams.yaml` where you have something like:

```yaml
accounts:
  paths:
    - user/site/accounts
```

**Comment by hniemann** [comment]
Do I have to use the Multisite Setup? Current I use only the Automatic Environment Configuration https://learn.getgrav.org/16/advanced/environment-config

**Comment by mahagr** [comment]
You can just throw the `streams.yaml` file into your site config. But the ideas in the docs apply.

**Comment by hniemann** [comment]
I put the ./user/localhost/config/streams.yaml with

```
schemes:
  accounts:
    paths:
      - user/localhost/accounts
```
and I put the user.yaml to user/localhost/accounts but it didn't work

**Comment by izzyu91** [comment]
Any news here. I believe I encountered the same problem here:

I am currently reworking my multisite. During that I wanted to move some files to sub directories as cleanup. 

A brief structure
user/
- accounts/
- sites/
- - site1/
- - site2/

Both sites are mostly independent, but the users are the same. As the user stream is the site1/site2 directly, I wanted to overwrite the account stream. But as soon as I did that, Grav did not find any user and I got the redirected to create the first admin user.

My current workaround is to set "user" as additional path in the user stream.

I tried both ways. Setting it via config/streams.yaml and the "old way" as you called it in the setup.php. The Grav version is the current 1.7.RC20. But as I recall it also happened on 1.6.

Dumping the locator shows the seemingly correct path in the schemes.

**Comment by mahagr** [comment]
To me this works:

```yaml
schemes:
  account:
    type: 'Stream'
    force: true
    prefixes:
      '': 'user/accounts'
```

**Comment by izzyu91** [comment]
Oh, thank you. Didn't think about this way. Works fine for me too!

**Comment by izzyu91** [comment]
I have to correct myself. I didn't test one function... Reading the user accounts works fine and logging is working too, but creating new users will create them in an accounts folder of the subpage even if the directory didn't exist before.

**Comment by izzyu91** [comment]
I think I got it working now. The solution seems to be moving to the "new" method of setting the streams using the streams.yaml and the environment variables. Using the old method (returning an array in setup.php) seems not to be working correctly. As far as I debugged it, the method `initializeLocator` is called four times. On the first call the values are right, but as soon the second call is made the array from setup.php seems to be ignored for some values and they will be reset to default.

Hopefully this will help you.

**Comment by mahagr** [comment]
It "works" also from `setup.php`, but there's a caveat: it only serves as an initial configuration and as the variables are overridden in `system/config/streams.php`, it won't work. I removed the system file so that the examples should work again. I also updated documentation to prefer `schemes.yaml`.
