### ISSUE TITLE
Split function

### ISSUE THREAD

**Issue by petira** [getgrav/grav#2451]
It is not a really issue, but I miss the function to split the string in Twig functions. For example:

```
{% set xString = ('text1','text2',...,'textN') %}
{% set xArray = Split(xString, ',') %}
```

`==> xArray ( [0] => 'text1' [1] => 'text2' ... [N-1] => 'textN' )`

**Comment by rhukster** [comment]
No need to miss it, it exists:

https://twig.symfony.com/doc/2.x/filters/split.html

**Comment by petira** [comment]
Thank you. Works great. You can close.
