### ISSUE TITLE
Disable tags in codemirror editor.

### ISSUE THREAD

**Issue by Memurame** [getgrav/grav#2453]
I only want to allow my client in the editor to do the text Bold. I want to hide all other tags.
![Unbenannt](https://user-images.githubusercontent.com/15847494/56200167-8eb55c80-603e-11e9-891b-dbc65d7fcf44.PNG)

Is this possible?
How can i do this?

**Comment by n30nl1ght** [comment]
Anyone a idea?

**Comment by ricardo118** [comment]
with some custom css in admin you could hide them via the css like
```
.grav-editor-button-italic {
display: none;
}
```
There's plugins that let you add custom css to admin

**Comment by Memurame** [comment]
> with some custom css in admin you could hide them via the css like
> 
> ```
> .grav-editor-button-italic {
> display: none;
> }
> ```
> 
> There's plugins that let you add custom css to admin

Thx a lot. I will test it.
