### ISSUE TITLE
Error during Plugin update with Grav 1.6.5 and PHP 7.2 on Docker

### ISSUE THREAD

**Issue by ikarstein** [getgrav/grav#2454]
Hi All, 

I have GRAV running on Docker on Debian.

Recently I installed PHP7.2 on a new Docker image and all other packages to upgrade GRAV from 1.5.x to 1.6.5.

Setup is OK. The website  is running. During plugin update I got an error. So I tried to upgrade all plugins from within the container with bin/gpm update -f -o

Then I got this error:
![image](https://user-images.githubusercontent.com/5047251/56240263-52f8b200-6093-11e9-9c48-2a886edcdaf9.png)

Any ideas?

Regards
Ingo

**Comment by rhukster** [comment]
Line 321 of Folder.php is an exception based on a failure during the installation of the file copy.  Most likely it's a permission issue where the installer can't copy over a file.  Could also be locked or something along those lines.

**Comment by rhukster** [comment]
Some info that might be helpful: https://learn.getgrav.org/16/troubleshooting/permissions
