### ISSUE TITLE
After update to 1.6 - error A non-numeric value encountered

### ISSUE THREAD

**Issue by HarDX** [getgrav/grav#2457]
I update theme as wrote https://getgrav.org/blog/important-theme-updates

but have problem
Twig \ Error \ RuntimeError
An exception has been thrown during the rendering of a template ("A non-numeric value encountered").
Previous exceptions
A non-numeric value encountered (2)

In logs
CRITICAL | An exception has been thrown during the rendering of a template ("A non-numeric value encountered").

```
        {% block javascripts %}
            {% do assets.addJs('jquery', 101) %}
            {% do assets.addJs('theme://js/jquery.bxslider.js') %}
            {% do assets.addJs('theme://js/script.js') %}
            {% do assets.addJs('theme://js/fixed-responsive-nav.js') %}
            {% do assets.addJs('theme://js/waypoints.min.js') %}
            {% do assets.addJs('theme://js/jquery.event.move.js') %}
            {% do assets.addJs('theme://js/jquery.twentytwenty.js') %}
            {{ assets.js()|raw }}
        {% endblock %}
        {% block bottom %}
        {{ assets.js('bottom')|raw }}
        {% endblock %}
        <div id="toTop">↑</div>
    </body>
</html>
```
Error at {{ assets.js()|raw }}

**Comment by HarDX** [comment]
Sorry, i have php 7.1.26 after upgrade to 7.3.2 - all is ok

**Comment by rhukster** [comment]
7.1.26 should have been fine.  It is not clear what was causing this though as there's nothing in your JS assets block that I can see that would cause an issue.
