### ISSUE TITLE
Ater update to 1.6.5 - "Unsupported operand types"

### ISSUE THREAD

**Issue by drnasin** [getgrav/grav#2458]
After updating one of my pages from 1.5.10 to 1.6.5 the page is not working and "Unsupported operand types" error is thrown in system\src\Grav\Common\Assets.php (L:302)

**Comment by rhukster** [comment]
Is it possible to see the source of the page in question or the specific trig line that is causing it?  I can’t fix an issue I don’t know how to recreate.

**Comment by rhukster** [comment]
I'm guessing you have something set wrong in your `priority` for an asset.  It should be an integer.  You would get that `unsupported operand types` error, if you had a string there.

**Comment by rhukster** [comment]
Should be fixed with the commit for #2461
