### ISSUE TITLE
After update to 1.6.5 I get 404 for ALL translated pages

### ISSUE THREAD

**Issue by drnasin** [getgrav/grav#2459]
Only default language pages are shown. After clicking on the flag to get translated version 404 is shown. Redirect default route is set to false…

seems like redirects are without the lang code in 1.6.5. hence 404....

**Comment by rhukster** [comment]
Ugg I know exactly what this is.  Fixed one issue and caused this. I’ll get you a temp fix shortly...

**Comment by rhukster** [comment]
Line 81 of `system/src/Grav/Common/Service/PagesServicesProvider.php` change that if statement to:

```
                // Default route test and redirect
                if ($config->get('system.pages.redirect_default_route') && $page->route() !== $path) {
                    $c->redirect($url);
                }
```

This was the old functionality.  I'm just going to roll back my fix as the other issue was pretty obscure, and this one is much more common.

**Comment by rhukster** [comment]
fixed in develop also
