### ISSUE TITLE
My PHP minisites in subfolders now in “error 404” upgrading from 1.5 to 1.6

### ISSUE THREAD

**Issue by enderlen** [getgrav/grav#2463]
Hi,

I host some PHP mini websites (not related to grav) at root of grav installation (e.g: [sample webpage of minisite for which Grav 1.6 throws an error 404](http://dynatmos.com/aen-custom/hybrid/hybrid_registres.php).

Prior to upgrade to 1.6, all my independant PHP mini-websites in “aen-custom” folder where working perfectly. But now Grav seems to intercept them and throws 404 errors.

I tried some advanced setting to exclude the mini website folder (the “System > Content > Ignore folder” setting from Admin Panel), but it had no impact.

Any help welcome as I would like to get back my site up and running…

br,

**Comment by rhukster** [comment]
Did you try the latest 1.6.6 release?

**Comment by enderlen** [comment]
I just updated from 1.6.5 to 1.6.6, but same issue

**Comment by rhukster** [comment]
Going to need some more information, or a test site zipped up to know how you have your end setup.  I can't recreate the issue it from the description provided.

**Comment by enderlen** [comment]
Hi, 
I've pushed a [zip to help test and reproduce](http://www.dynatmos.com/php_minisite_in_subfolder.zip)
This sample PHP minisite should be unzipped at root so in www.mydomain.com\aen-custom\prenoms\registre_prenoms.php

To help to see behavior, I suggest to comment "Options -Indexes" in .htaccess coming at root of domain, so \aen-custom\prenoms\ will be reachable and display folder content including the php page. Then from folder listing you click the registre_prenoms.php listed page and issue on my Grav 1.6.6 installation is that this leads to the Grav error 404 page (not the expected registre_prenoms.php page).

**Comment by rhukster** [comment]
Ok, Now I understand what you are trying to do.  You are trying to access a custom PHP script that is inside a Grav site.

This functionality is not controllable by Grav itself and is 100% controlled by the webserver.  When your browser requests a URL, the first thing the webserver does is try to locate that path in the filesystem.  If it is found, it is served and rendered.  If it is not found, the configuration of the webserver kicks in and things like looking for an index file (`index.html`, `index.php`, etc) if no file has been specified (e.g. `/aen-custom/prenoms/`). If that is not found, things like URL rewriting configuration will take effect, this is where Grav's `.htaccess` comes into play, as this has configuration to pass any path that has not been found, to Grav's `index.php` file that in turn tries to find the requested URL as a page route.

I tested your zip file by dropping it into a Grav 1.6 installation, and when I went to the URL the PHP loaded (albeit with warning errors on PHP 7.3).  As you seem to be using Apache, my first thought is that you have some configuration that is restricting access to your `aen-custom/prenoms/registre_prenoms.php` file path a that should be found by the webserver and served before ever reaching Grav.  This is clearly not happening, and things are falling back to Grav which is correctly saying that no page exists with that route.

**Comment by enderlen** [comment]
Does it mean that behavior with Grav 1.5 (and previous versions) was Grav recognized PHP custom pages as unsupported and just opened them as is, But now with Grav 1.6 such URLs are blocked by Grav as unsupported?

What can I do to keep Grav 1.5 (and previous versions) behavior regarding custom PHP pages?

**Comment by rhukster** [comment]
What I'm saying is it's most likely not related to Grav as the webserver should be handling that PHP script being found **before** Grav even gets a look in. Please re-read my explanation above, your problem lies in your web server configuration.

An unlikely, but still possible cause could be related to the `.htaccess` at the root of Grav as that does provide some overrides for Apache config.  If you had some custom modifications in this file they could have been lost, but Grav upgrade packages don't include this file, so there's no reason it would get overridden when doing a standard upgrade. If you did a manual upgrade and somehow overwrote a custom `.htaccess` you'll have to re-customize it or restore it from a backup.

However, that said, the default `.htaccess` works just fine and doesn't stop direct access to PHP files inside the Grav folder.

**Comment by enderlen** [comment]
It's the default .htaccess, I never made any customization in that file.
And it works fine with Grav 1.5. What change should be made to get it work with Grav 1.6?

**Comment by rhukster** [comment]
none, it's not changed.

**Comment by enderlen** [comment]
I took decision to move all my custom PHP content in a distinct subdomain so it is now completely separated from Grav and no URL is resolved anymore going through Grav system. Subdomain has exact Apache config. Now all my php content load without Grav error 404, like before.
So you can close the issue.
