### ISSUE TITLE
 getgrav.org Skeleton/Theme Demo Error 

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#2464]
Sora, Receptar, Gateway, Agency Theme/Skeleton Demo on https://getgrav.org/downloads/skeletons:

![Bildschirmfoto_2019-04-18_14-28-47](https://user-images.githubusercontent.com/12480617/56361074-b8a98300-61e6-11e9-973f-1753c6303944.png)

**Comment by rhukster** [comment]
Grav was out of date.  Should be fine now

**Comment by axel-rank** [comment]
All right now ;-)
