### ISSUE TITLE
error 500 on internet explorer 11 only

### ISSUE THREAD

**Issue by 3engel** [getgrav/grav#2467]
I recently updated grav to v1.6.6. I have a stange behaviour with modular twig templates.
When I open the page with internet explorer 11 grav throws a 500 server error with the following message.

> 0 - An exception has been thrown during the rendering of a template ("Template "modular/slides.txt.twig" is not defined.").

For sure, there is no template modular/slides.txt.twig, but there is a templete modular/slides.html.twig which should be loaded. There is no issue when using Chrome or Edge.
After further investigation, my temporary fix was to edit the _processPage_ function in _system\src\Grav\Common\Twig\Twig.php_ like that:
```
 if ($item->modularTwig()) {
  $twig_vars['content'] = $content;
  $extension = $item->templateFormat();
  **if ($extension == 'txt'){
    $extension = 'html';
  }**
  $extension = $extension ? ".{$extension}.twig" : TEMPLATE_EXT;
  $template = $item->template() . $extension;
  $output = $content = $local_twig->render($template, $twig_vars);
}
```
I have no idea where grav gets the txt extension from and why this is only occuring in IE11.
I'm using php 7.3.3 on nginx 1.10.3

Any ideas?

**Comment by rhukster** [comment]
Sounds like a duplicate of this issue: https://github.com/getgrav/grav/issues/2337#issuecomment-461841962

The default was fixed as far as I could tell, but you might have already saved the order of the page types previously.  Simply adjust the order and save and you should be fine.

**Comment by 3engel** [comment]
@rhukster 
I'm so sorry. I just was to stupid to use the search.
That fixed the issue.
