### ISSUE TITLE
[add-resource] New Plugin: Back to Top

### ISSUE THREAD

**Issue by marcosegato** [getgrav/grav#2469]
I would like to add my new plugin to the Grav Repository.
This grav plugin displays a "Back to Top" link at the end of every section, so the reader can jump back up to the table of contents.
Here are the project details: **marcosegato/grav-plugin-backtotop**

**Comment by rhukster** [comment]
You need a GitHub release for this to show up: https://learn.getgrav.org/16/advanced/grav-development#theme-plugin-release-process

**Comment by marcosegato** [comment]
Now it's done, sorry for the mistake
