### ISSUE TITLE
Chapter about Nginx at learn.getgrav.org

### ISSUE THREAD

**Issue by kris4de** [getgrav/grav#247]
I had some trouble with the preconfigured nginx.conf on my DigitalOcean Ubuntu VM and I think one chapter about configuration of Nginx would be helpful.

Some lines didn't work for my virtual host (or server block) configuration and others are not needed, I think.

```
worker_processes  1;

events {
    worker_connections  1024;
}
```

According to [this full example](http://wiki.nginx.org/FullExample), these lines are already default and not needed.

```
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
```

This surrounding `http` block throws errors and doesn't work with virtual host configuration – Nginx can't restart.

```
location / {
            root   html;
                index  index.php;
        if (!-e $request_filename){ rewrite ^(.*)$ /index.php last; }
    }
```

In default configuration, the first two lines inside `location /` are already present. But outside of `location /`. And I am not sure whether they belong in there, because it's not working properly – 404 errors (not Grav, Nginx) are the result.

As a conclusion, at least one chapter about Nginx configuration would be really appreciated.

**Comment by austinbutler** [comment]
I'd agree on having a little more NGINX in the manual. At the very least linking to the NGINX conf file included with the package itself: https://github.com/getgrav/grav/blob/develop/nginx.conf

Once I realized it was there, I had it working in seconds.

**Comment by rhukster** [comment]
Would be awesome if someone who knows Nginx better than me could draft up a version of this documentation that we can add to the learn docs??

**Comment by DarrylDias** [comment]
If you are trying to configure Grav with NGINX running on Ubuntu VPS on Digital Ocean. I would recommended editing the `/etc/nginx/sites-enabled/default` file instead of directly editing the `/etc/nginx/nginx.conf`. I have created a [gist](https://gist.github.com/DarrylDias/2a04dba9688e131eaced). That contains my current NGINX configuration that is running my current Grav [website](http://darryldias.me).

**Comment by greasan** [comment]
@DarrylDias I wrote about virtual host config. The `nginx.conf` is untouched. But thanks for your current configuration. I will have a look at it.

**Comment by simonhaenisch** [comment]
@rhukster I could help with that, where would you place it in the docs? Mabybe in Basics > Installation or Cookbook or Troubleshooting?

**Comment by flaviocopes** [comment]
We want to spin up a  "Web Servers" section with a page for each webserver with info on how to setup, tweak performance, basic security.. so you can create one for Nginx first then we add the other ones

**Comment by mabushey** [comment]
What's the status on this? I could help out and I'm pretty familiar with Nginx.

**Comment by flaviocopes** [comment]
I don't think there's any progress being done on this, so - you're encouraged to step up.

**Comment by moos3** [comment]
There should be a blurb about client_max_body_size in nginx for uploading files.

**Comment by simonhaenisch** [comment]
I have to configure a new nginx installation in the next days and will document it, so I can then create the page. @flaviocopes is it alright that I create a `/pages/14.web-servers/01.nginx/docs.md` page in the grav-learn repository then?

**Comment by rhukster** [comment]
That's fine, we can add others in there as we go.  Thanks!

**Comment by mabushey** [comment]
Here's what I'm using. I'm sure lots could be done to optimize it.

```
server {
  listen 80;
  server_name example.com www.example.com;
  include /etc/nginx/letsencrypt-acme-challenge.conf;
  add_header X-Forwarded-MYProto $http_x_forwarded_proto;

  if ($http_x_forwarded_proto !~* 'https') {
    rewrite ^ https://www.example.com$request_uri? permanent;
  }
}


server {
  listen 443;
  server_name www.example.com;
  root /var/www/html/www.example.com;
  access_log /var/log/nginx/www.example.com-access.log;
  error_log /var/log/nginx/www.example.com-error.log;
  index index.html index.php;

  ssl_certificate /etc/letsencrypt/live/www.example.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/www.example.com/privkey.pem;

  location / {
    try_files $uri $uri/ /index.html;
    if (!-e $request_filename){ rewrite ^(.*)$ /index.php last; }
  }

  location ~ \.php$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass   127.0.0.1:9001;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
  }

}

```

**Comment by rhukster** [comment]
We have a pretty simple nginx.conf here: https://github.com/getgrav/grav/blob/develop/webserver-configs/nginx.conf

Best if we use this for the documentation to keep things consistent.  If it can be improved, then fine, but would prefer to keep it as minimal and simple as possible so that it works with least amount of modification.

**Comment by simonhaenisch** [comment]
I'll write a little about how to setup a general nginx config then and that config will use the `include` directive to include a grav-specific site config (the one you mentioned). I will also explain what the site config does.
There is one thing I'd like your opinion on, @rhukster: When using ssl, the server block listening on port `80` should just (permanently) redirect to the https domain on port `443`. Thus all the directives that currently are in the `server` directive must be in a second `server` directive, like in @mabushey's config. My suggested solution would be to use an `include` to avoid duplicate code, i.e.:

```nginx
server {
    listen 80;
    server_name www.grav-site.com grav-site.com;

    # either
    # include grav-site.conf; # if you don't need ssl
    # or redirect to https
    return 301 https://grav-site.com$request_uri; # or with "www" sub-domain
}

# if you don't use ssl, remove or comment out the following server block
server {
    listen 443 ssl;
    server_name grav-site.com; # or www.grav-site.com, depending on where you redirect to

    # add ssl cert & options

    include grav-site.conf;
}
```

But that way the directives in the current config won't be inside the server block and that means that if someone mistakenly sym-links/copies that config directly into `/etc/nginx/sites-enabled/`, they will mess up their nginx config. I still have to test if nginx would use such a mis-configuration or return an error.

Other solutions would be to either provide a second `nginx-ssl.conf` and the user can copy/sym-link the one he wants (means duplicate code in both configs), or to just provide a non-ssl config and then explain how to make a ssl config out of it (benefit: no duplicate code, just one file).

**Comment by mabushey** [comment]
My opinion is having an extra include just complicates things. If the user is being redirected, the block contains a redirect and a load balancer https->http check in the event the load balancer is doing SSL termination. If the load-balancer is doing the SSL then the site config code will still be in the "listen 80;" block. Also Lets Encrypt only uses port 80 so that include will only be there.

**Comment by simonhaenisch** [comment]
@mabushey I see, in that case the load balance server would `proxy_pass` to one of the backends, so the "grav" server block would be on a different server than the load balancer block (which is quite an advanced setup)?

Still the question is what to do about a config for a non-ssl website without load-balancing (e.g. someone might not want it for a simple api documentation). Maybe the best way is to provide a simple non-ssl config like @rhukster said, and then write the chapter with three sections like:

1. explain nginx basics and how to use the config
2. explain how to modify for ssl
3. explain load balancing with ssl termination

(2.) could be split into two sections:

* 2.1 using an existing cert
* 2.2 using *Lets Encrypt* certs with ACME challange support

I don't know so much about (3) and (2.2), so I will just draft as much as I can.

**Comment by mabushey** [comment]
I have experience with Cisco load balancers, and the services provided by Rackspace and Linode. They do SSL termination and then pass on the data to a web server on port 80. The only way you know it's a port 443 SSL request is via the $http_x_forwarded_proto variable. 

Here is my `/etc/nginx/letsencrypt-acme-challenge.conf`:
```
#############################################################################
# Configuration file for Let's Encrypt ACME Challenge location
# This file is already included in listen_xxx.conf files.
# Do NOT include it separately!
#############################################################################
#
# This config enables to access /.well-known/acme-challenge/xxxxxxxxxxx
# on all our sites (HTTP), including all subdomains.
# This is required by ACME Challenge (webroot authentication).
# You can check that this location is working by placing ping.txt here:
# /var/www/letsencrypt/.well-known/acme-challenge/ping.txt
# And pointing your browser to:
# http://xxx.domain.tld/.well-known/acme-challenge/ping.txt
#
# Sources:
# https://community.letsencrypt.org/t/howto-easy-cert-generation-and-renewal-with-nginx/3491
#
#############################################################################

# Rule for legitimate ACME Challenge requests (like /.well-known/acme-challenge/xxxxxxxxx)
# We use ^~ here, so that we don't check other regexes (for speed-up). We actually MUST cancel
# other regex checks, because in our other config files have regex rule that denies access to files with dotted names.
location ^~ /.well-known/acme-challenge/ {

    # Set correct content type. According to this:
    # https://community.letsencrypt.org/t/using-the-webroot-domain-verification-method/1445/29
    # Current specification requires "text/plain" or no content header at all.
    # It seems that "text/plain" is a safe option.
    default_type "text/plain";

    # This directory must be the same as in /etc/letsencrypt/cli.ini
    # as "webroot-path" parameter. Also don't forget to set "authenticator" parameter
    # there to "webroot".
    # Do NOT use alias, use root! Target directory is located here:
    # /var/www/common/letsencrypt/.well-known/acme-challenge/
    root         /var/www/letsencrypt;
}

# Hide /acme-challenge subdirectory and return 404 on all requests.
# It is somewhat more secure than letting Nginx return 403.
# Ending slash is important!
location = /.well-known/acme-challenge/ {
    return 404;
}
```

**Comment by mabushey** [comment]
Actually with the load balancer it's a little more complex, you have to add this in the http block in nginx.conf:

```
     set_real_ip_from 10.0.0.0/8; # all addresses get a real IP.
     real_ip_header X-Forwarded-For; # the ip is forwarded from the load balancer/proxy
```

What this does is replace the IP from the load balancer with the actual IP. Otherwise all the logs will show the traffic was requested by the load balancer. The IP config is obviously dependent on the provider, for instance Linode would be `set_real_ip_from 192.168.0.0/16; # Linode config`

This is kind of irrelevant for Grav, but might help in understand things better for writing the documentation.

**Comment by simonhaenisch** [comment]
Just a status update: I am more or less done with writing the chapter, but I still have to test the whole configuration. I hope to do that today or tomorrow and then I'll create two pull requests, one for the new chapter at grav-learn and one here for an updated `webserver-configs/nginx.conf`.

Btw I will rename `nginx.conf` to just `nginx`, because the former implies that the file is a replacement for `/etc/nginx/nginx.conf` which it is not.
