### ISSUE TITLE
can't control position of external links relative to the pipeline

### ISSUE THREAD

**Issue by mjmaax** [getgrav/grav#2470]
It is not possible to set the position of external links before the pipeline CSS file. I use Grav 1.6.6.

assets:
  css_pipeline: true
  css_pipeline_include_externals: false

{% do assets.addCss('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', { position: before }) %}
{% do assets.addCss('theme://css/style1.css') %}
{% do assets.addCss('theme://css/style2.css') %}

=> the external link (bootstrap.min.css) will appear after the pipeline.

**Comment by rhukster** [comment]
Fixed with above commit combined with a slight change in your syntax:

```twig
{% do assets.addCss('https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css', { position: 'before' }) %}
```

Notice the quotes around the string `before`

**Comment by mjmaax** [comment]
Thank you for the fix!

I think this would be easier to read and also slightly more efficient:

    protected function filterAssets($assets, $key, $value, $sort = false)
    {
        $results = array_filter($assets, function($asset) use ($key, $value) {
            if ($asset[$key] !== $value) return false;
            if ($key === 'position' && $value === 'pipeline' && $asset->getRemote()) {
                $type = $asset->getType();
                if ($this->{$type . '_pipeline_include_externals'} === false) {
                    if ($this->{$type . '_pipeline_before_excludes'}) {
                        $asset->setPosition('after');
                    } else {
                        $asset->setPosition('before');
                    }
                    return false;
                }
            }
            return true;
        });
        if ($sort && !empty($results)) {
            $results = $this->sortAssets($results);
        }
        return $results;
    }

**Comment by rhukster** [comment]
you can override the position of an external if you provide a position in the `addAsset` call.  This takes precedence over the system level configurations.  The system level configuration is mostly for backward compatibility as prior to 1.6 you couldn't control the position per-item.  The go-forward approach is to specify `before`, `pipeline` or `after` when adding the asset.  The default is already `pipeline`, so specifying `before` or `after` effectively takes them out of the pipeline.

**Comment by mjmaax** [comment]
Sorry, what I meant is that it is not possible to specify that by default all externals are out of the pipeline and override one external asset to force it being in the pipeline (by providing position: 'pipeline' in the `addAsset `call). I have no grav installation to test it at the moment, that is just my guess looking at the code.

By first testing if ($asset[$key] !== $value) we can often avoid several conditions that deal with the specific case of externals, that's why I added it first in the suggested code of my previous message.
Additionally this also save us from testing again that $asset['position'] === 'pipeline' since we know that that this condition is always true.
I also put $asset->getRemote() at its correct place for clarity/efficiency.
The code is equivalent, but I believe slightly more efficient.
