### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by wernerjoss** [getgrav/grav#2471]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: 
https://github.com/wernerjoss/grav-plugin-icalendar
- this is my first try, I hope I have met all the requirements from [the documentation](https://learn.getgrav.org/16/advanced/grav-development#theme-plugin-release-process).
One point I'm not sure about, is how to incorporate a third party library, in this case [om\icalparser](https://github.com/OzzyCzech/icalparser) which I now have as a (patched!) copy in my sources.
please comment/advice.
Thanks
Werner Joss

**Comment by rhukster** [comment]
Added to GPM for next update
