### ISSUE TITLE
<p></p> is added to top of my page

### ISSUE THREAD

**Issue by payrequestio** [getgrav/grav#2472]
Theme:  Quark  v2.0.0   Grav v1.6.7

On top of my pages <p> </p> is added and i can`t find out why this is happend or how i can solve this.

I use HTML (like <div>) can that gives a problem ?
I only have the problem on 1 page

**Comment by rhukster** [comment]
probably some blank lines in your markdown.

**Comment by hostingwalk** [comment]
> probably some blank lines in your markdown.

Do you need to look at the .MD file or is there a way to check it ?
