### ISSUE TITLE
Grav version 1.6.7 issue

### ISSUE THREAD

**Issue by prbt2016** [getgrav/grav#2473]
Hi,

I downloaded and manually  installed Grav version 1.6.7  i.e Grav core+admin plugin zip from official website :
https://getgrav.org/download/core/grav-admin/1.6.7 on Centos 6.4, Apache 2.2, PHP 7.1.26.

However, found that 'security.yaml' file is pre-included in '/user/config/' in the zip package and the file contains salt. Also cache files are pre-included in the package
(i.e /cache/compiled/files/b0794593314e39a9a2896884d73c4714.yaml.php). Also checked that salt doesn't change post installation, even when '/user/config/' folder has permissions.

Could you please check and fix this?. As in the earlier version i.e 1.6.6 and earlier versions, 'security.yaml' was created post installation. Is this a packaging issue or is 'security.yaml' purposefully included in the package?.

Awaiting your reply.

**Comment by rhukster** [comment]
This is fixed in 1.6.8 which is being released now.
