### ISSUE TITLE
Can I display pdfs from an AWS S3 bucket on a Grav page?

### ISSUE THREAD

**Issue by nubotix** [getgrav/grav#2482]
I am new to Grav.  I would like to display pdfs from an AWS S3 bucket on a Grav page. (Limited space for pdfs on host).  Being (very) slow is unlikely to be an issue. 

How would I accomplish this?

Thanks

**Comment by hughbris** [comment]
Hi, welcome! Please use the [Grav forum](https://discourse.getgrav.org/) for this kind of question :)

**Comment by nubotix** [comment]
Done. Thanks hughbris.
