### ISSUE TITLE
Error while routing to http://grav.test.com/admin/user

### ISSUE THREAD

**Issue by nirajmaharjan09** [getgrav/grav#2483]
while routing to page that doesn't exist, should't user be redirect to error page??
![image](https://user-images.githubusercontent.com/7368147/56887654-de117900-6a91-11e9-86e4-cb0d896e5b4d.png)
![image](https://user-images.githubusercontent.com/7368147/56888013-bf5fb200-6a92-11e9-8054-7bcd2c7aa845.png)

**Comment by rhukster** [comment]
Well, that `admin/user` prefix is a special case.  We are working on some user management but it's not all there yet.

**Comment by joenovell** [comment]
Trying.. https.conf - apache2 IS: User admin SB: User _admin
Re-Compiling ,,,a-very-patch-ie,,, permission challenge and NOT a twig at all?

John Holmgren
joenovell@gmail.com

**Comment by joenovell** [comment]
It appears to be a solution without a routing solution..
The http.conf is using the underscore “_” , and my settings worked as mentioned with this SB: (Should Be) syntax;
SB: User _www
       Group _www
       User _admin
        Group _staff

_me thinks its is shorthand for NOT (boolean) logic!!! And I could get the ‘compose’ from ‘brew’ to install (I did have Remove Directories for a clean install… ignore my timestamps.. this is a labor of love and I am not a time clock.

Success is measured on a clean Grav install !!

Many TNX from your oldest admin...

John Holmgren
joenovell@gmail.com
