### ISSUE TITLE
Page | Site.tld: how to change the delimiter it the TITLE from admin side?

### ISSUE THREAD

**Issue by jooru** [getgrav/grav#2490]
Page | Site.tld: how to change the "|" delimiter it the TITLE of the page headers from admin side?
Now it's just hardcoded.

Thank you!

**Comment by rhukster** [comment]
This is actually not a Grav limitation, it's a feature of the Theme you are using.  If you are using Quark theme for example, the output of the `<title></title` tag is determined by the `partials/base.html.twig` file: https://github.com/getgrav/grav-theme-quark/blob/develop/templates/partials/base.html.twig#L9

So this is a theme-level edit on your site, depending on your theme, it could be different though.

**Comment by jooru** [comment]
Can you imagine, but in my 47 years it's my first post to GitHub, while being a professional developer. )
With my great respect to the Devs. Thank you! 

I'm gonna go drink that fact off. )
