### ISSUE TITLE
CLI Update command places existing Pages folder when a Theme '_demo' folder is updated

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#2493]
As requested, this is a new issue based on a reported CLI theme update issue.

Based on several user reports, if a theme contains a "_demo" folder this content replaces the existing Pages folder (the original is copied and renamed) when a CLI **update** is done if the "_demo" folder has been changed. Preferably, when a theme update via CLI is done the contents of the "_demo" folder would not be copied over.

I hope the above makes things clearer, please let me know if more info would be of help.

Below is also a series of screen caps to help illustrate the issue.

Thank you very much,
Paul

Hi, @paulhibbitts . After your comments in the getgrav forum, I did my daily update routine on my servers. There was indeed a theme update. In one of the servers, I updated the theme through the Admin panel, and no pages were changed.

In another server, I used the command line interface 

```
        bin/gpm update
```

Here, the update process moved the pages directory to a time-stamped new directory (pages.05-06-2019-09-00-36) and created a new pages directory with only the theme demo content.

Screenshots follow. I hope this may be useful.
![DeepinScreenshot_select-area_20190506060023](https://user-images.githubusercontent.com/20466765/57216493-5ca47400-6fc6-11e9-8c4c-9d4dbc148bf7.png)
![DeepinScreenshot_konsole_20190506060129](https://user-images.githubusercontent.com/20466765/57216510-64641880-6fc6-11e9-97f0-3a012c9fcaf8.png)

_Originally posted by @quartelmestre in https://github.com/getgrav/grav/issues/2225#issuecomment-489557511_

**Comment by paulhibbitts** [comment]
Thank you very much @rhukster !

**Comment by quartelmestre** [comment]
Thanks, @rhukster !
