### ISSUE TITLE
Parse error when bin/grav install

### ISSUE THREAD

**Issue by coreych** [getgrav/grav#25]
git clone grav.git
bin/grav install

Parse error: parse error in /Users/corey/Programs/webroot/grav/system/src/Grav/Console/CleanCommand.php on line 15

**Comment by erata** [comment]
hi, i use xampp v3.22 with PHP Version 5.6.11 and when i want to install a module or do something i take an error: "You are running PHP 5.3.19, but Grav needs at least PHP 5.4.0 to run".
could you help me...

**Comment by flaviocopes** [comment]
Your version of xampp looks outdated, it's using PHP 5.3 in the command line. Upgrade xampp and it should be fine.

**Comment by erata** [comment]
i install new version of xampp and its php version is 5.6.11 when i look at phpinfo

**Comment by flaviocopes** [comment]
Where are you getting that error, in the command line (running gpm) or in the browser?

**Comment by erata** [comment]
Command line

**Comment by flaviocopes** [comment]
The version used in the web server is different than the command line PHP version. I'm not sure how to upgrade that in xampp. You might want to check that in the xampp docs / ask in their forums.

**Comment by flaviocopes** [comment]
(you can still install a plugin by downloading the latest version in the zip package and put it in /user/plugins, but of course using the command line is more convenient)

**Comment by erata** [comment]
my used programs: MINGW32 (Git Bash), XAMPP the last version (PHP 5.6.11) and grav last version, but i could not run any module with comman line...

**Comment by giansi** [comment]
@erata Grav does not require a database, so why are you using XAMPP? Why don't you try with the PHP internal server, so you can run PHP both from web browser and cli with a single configuration? Here's a guide that could help you. http://diblas.net/blog/how-to-install-php-to-run-grav-cms-under-windows. Anyway, if you want to use XAMPP, try to find out how to configure the cli with XAMPP. Good luck

**Comment by erata** [comment]
hi, i install php and apache but again the message about php version low...
is there a different program for windows except MINGW32 (Git Bash) to run grav on command line?

**Comment by flaviocopes** [comment]
I think you just need to add the path to the correct PHP version to use. I'm not using Windows so I don't know the exact procedure, but I found these tutorials you can follow to change the PHP version it uses https://stackoverflow.com/questions/17727436/how-to-properly-set-php-environment-variable-to-run-commands-in-git-bash http://codeutopia.net/blog/2008/07/28/setting-up-command-line-php-on-windows/ https://stackoverflow.com/questions/15517718/php-version-on-windows-command-line

**Comment by erata** [comment]
hi, i found the problem. it arise from iis express php installation which i intall with web installer platform. so git bash see this program's php version. after i remove iis php the problem resolved.

thanks,

**Comment by flaviocopes** [comment]
Glad you sorted it out!

**Comment by johncarter-oz** [comment]
Hi, I know this is an old thread but I am also getting the parse error and I can explain the problem yet I do not know the way around.
So, my *nix is runnning PHP 5.4.16 (yes, I know it needs to be 5.5.9 or above) but my virtual server is running the very latest.
So Apache has no problem but to create an admin user, I SSH in but cannot execute the script to generate admin user due to the underlying "system" version of php.
We are using BlueOnyx. You can see here: http://www.blueonyx.it/index.php?page=multi-php about running multiple php versions but only for serving up web pages...
Any ideas?
Thank you in advance. BTW, if I should make a new thread for this, please tell me.

**Comment by flaviocopes** [comment]
Your hosting should provide a way to update the CLI version of PHP. 
Contact their support, as every host handles this kind of thing differently.
