### ISSUE TITLE
PHP Fatal Error When Setting Up Cron

### ISSUE THREAD

**Issue by WilliamMiceli** [getgrav/grav#2500]
#### Environment
Using Docker 18.09.6 on my hosts.
Have Grav in my own custom Docker image that I'm trying to put together.
Main repository: [https://git.williammiceli.systems/WilliamMiceli/docker-grav](https://git.williammiceli.systems/WilliamMiceli/docker-grav)
Using Grav v1.6.8 (upgraded to v1.6.9 once started)

#### Issue
Site is running normally until I start the cron daemon to run the provided crontab from the site itself, which at very least exits with status 0... but then the site goes blank...

#### Logs
5/11/2019 9:21:59 PM2019/05/12 01:21:59 [error] 15#15: *84 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Failed to save file /var/www/cache/compiled/blueprints/master-10.0.10.100.php in /var/www/vendor/rockettheme/toolbox/File/src/File.php:351
5/11/2019 9:21:59 PMStack trace:
5/11/2019 9:21:59 PM#0 /var/www/vendor/rockettheme/toolbox/File/src/PhpFile.php(31): RocketTheme\Toolbox\File\File->save(Array)
5/11/2019 9:21:59 PM#1 /var/www/system/src/Grav/Common/Config/CompiledBase.php(252): RocketTheme\Toolbox\File\PhpFile->save(Array)
5/11/2019 9:21:59 PM#2 /var/www/system/src/Grav/Common/Config/CompiledBase.php(117): Grav\Common\Config\CompiledBase->saveCompiledFile('/var/www/cache/...')
5/11/2019 9:21:59 PM#3 /var/www/system/src/Grav/Common/Service/ConfigServiceProvider.php(77): Grav\Common\Config\CompiledBase->load()
5/11/2019 9:21:59 PM#4 /var/www/system/src/Grav/Common/Service/ConfigServiceProvider.php(36): Grav\Common\Service\ConfigServiceProvider::blueprints(Object(Grav\Common\Grav))
5/11/2019 9:21:59 PM#5 /var/www/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\ConfigServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav))
5/11/2019 9:21:59 PM#6 /var/www/system/src/" while reading response header from upstream, client: 10.42.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "10.0.10.100"
5/11/2019 9:21:59 PM10.42.0.1 - - [12/May/2019:01:21:59 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0" "-"

#### Console
![image](https://user-images.githubusercontent.com/9000802/57576687-3bafa900-7434-11e9-8b20-0104244e6e5b.png)
![image](https://user-images.githubusercontent.com/9000802/57576693-626ddf80-7434-11e9-916e-f43879e56a2b.png)

Thank you for any help!

**Comment by WilliamMiceli** [comment]
Just to have a "moment in time" snapshot of everything in case it's useful in the future, this is the repository at the current commit I'm having this issue on:
[https://git.williammiceli.systems/WilliamMiceli/docker-grav/tree/be62c4005cf2694a91fdb499791c269ff693e8cf](https://git.williammiceli.systems/WilliamMiceli/docker-grav/tree/be62c4005cf2694a91fdb499791c269ff693e8cf)

**Comment by rhukster** [comment]
It looks like you have a permission issue with the `/var/www/cache/compiled/blueprints` directory.  Whatever user you are using for cron is not able to create files in it.

**Comment by WilliamMiceli** [comment]
I believe I have fixed it by adding the cron command in my nginx user's crontab (I have the site chown'd by nginx to not have to create the www-data user, since I'm on Alpine). Things seem to be working fine now, except that I have a warning in the Admin tools section saying "Cron Not Available". Does that check against a specific user, or maybe a specific cron package on an Ubuntu distribution? It seems like cron is working fine at the moment.

**Comment by rhukster** [comment]
Basicaly Grav running with the web server's user account runs a `crontab -l` command and looks for `bin/grav schedule`

```
    public function isCrontabSetup()
    {
        $process = new Process('crontab -l');
        $process->run();

        if ($process->isSuccessful()) {
            $output = $process->getOutput();

            return preg_match('$bin\/grav schedule$', $output) ? 1 : 0;
        }

        $error = $process->getErrorOutput();

        return Utils::startsWith($error, 'crontab: no crontab') ? 0 : 2;
    }
```

**Comment by WilliamMiceli** [comment]
Thank you @rhukster ! It might take me a while to figure out what's happening with things.
