### ISSUE TITLE
Cache-Control: max-age=0.....?

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav#2504]
i set in admin max-age=31536000
but in browser  see Cache-Control: max-age=0
what is wrong

**Comment by rhukster** [comment]
I just tested this and it works fine.  Basically, any page-level settings of cache control will override the default system setting.

If i add:

```
cache_control: max-age=204800
```

To my page frontmatter, my headers show that value.  However, if i remove that then it picks up my settings in `user/config/system.yaml`:

```
pages:
    ...
    cache_control: max-age=31536000
    ...
```

**Comment by abooks23** [comment]
sorry, my hosting permits change this option in Control Panel. issue can be closed. thx
