### ISSUE TITLE
Scheduler makes subfolders in cache folder owned by root

### ISSUE THREAD

**Issue by achwell** [getgrav/grav#2506]
Grav v1.6.9 - Admin v1.9.4

The new scheduler function makes some subfolders under <GRAV_ROOT>/cache to be owned by user root, which makes the site unavailable.

**Comment by mahagr** [comment]
Sounds like a configuration issue for me.

**Comment by achwell** [comment]
How do I configure which user the grav processes should use for running?

**Comment by rhukster** [comment]
It depends on the user running cron, as that user will be running the CLI command that runs Grav.  It should be the same user as the one that the webserver uses.  For these reasons I usually find it easier to create a new user and run webserver, and login, and use cron as a dedicated user.
