### ISSUE TITLE
InvalidArgumentException Invalid IP: UNKNOWN

### ISSUE THREAD

**Issue by lufog** [getgrav/grav#2507]
When i try to login on site, i get:
```
InvalidArgumentException
Invalid IP: UNKNOWN
```
The site is still in development and launched on the embedded PHP server. Before this problem was not, it appeared suddenly, I think after the update. Authorization in admin plugin works fine.

**Comment by rhukster** [comment]
Can you set the errors display to `1` and report back with the full stack trace?

**Comment by lufog** [comment]
[grav.log](https://github.com/getgrav/grav/files/3191673/grav.log)

**Comment by rhukster** [comment]
Thanks that helps a lot.  I’ll look into it.

**Comment by lufog** [comment]
<details>
  <summary>Stack frames (37)</summary>
  <pre><code>36 InvalidArgumentException
…\system\src\Grav\Common\Utils.php:1494</code></pre>
  <pre><code>35 Grav\Common\Utils getSubnet<br>
…\user\plugins\login\classes\Controller.php:134</code></pre>
  <pre><code>34 Grav\Plugin\Login\Controller taskLogin
…\user\plugins\login\classes\Controller.php:105</code></pre>
  <pre><code>33 Grav\Plugin\Login\Controller execute
…\user\plugins\login\login.php:506</code></pre>
  <pre><code>32 Grav\Plugin\LoginPlugin loginController
…\vendor\symfony\event-dispatcher\EventDispatcher.php:212</code></pre>
  <pre><code>31 Symfony\Component\EventDispatcher\EventDispatcher doDispatch
…\vendor\symfony\event-dispatcher\EventDispatcher.php:44</code></pre>
  <pre><code>30 Symfony\Component\EventDispatcher\EventDispatcher dispatch
…\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php:23</code></pre>
  <pre><code>29 RocketTheme\Toolbox\Event\EventDispatcher dispatch
…\system\src\Grav\Common\Grav.php:365</code></pre>
  <pre><code>28 Grav\Common\Grav fireEvent
…\system\src\Grav\Common\Processors\TasksProcessor.php:52</code></pre>
  <pre><code>27 Grav\Common\Processors\TasksProcessor process
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:45</code></pre>
  <pre><code>26 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:57</code></pre>
  <pre><code>25 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Common\Processors\RequestProcessor.php:52</code></pre>
  <pre><code>24 Grav\Common\Processors\RequestProcessor process
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:45</code></pre>
  <pre><code>23 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:57</code></pre>
  <pre><code>22 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Common\Processors\ThemesProcessor.php:27</code></pre>
  <pre><code>21 Grav\Common\Processors\ThemesProcessor process
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:45</code></pre>
  <pre><code>20 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:57</code></pre>
  <pre><code>19 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Common\Processors\PluginsProcessor.php:30</code></pre>
  <pre><code>18 Grav\Common\Processors\PluginsProcessor process
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:45</code></pre>
  <pre><code>17 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:57</code></pre>
  <pre><code>16 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Common\Processors\InitializeProcessor.php:78</code></pre>
  <pre><code>15 Grav\Common\Processors\InitializeProcessor process
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:45</code></pre>
  <pre><code>14 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:57</code></pre>
  <pre><code>13 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Common\Processors\DebuggerProcessor.php:27</code></pre>
  <pre><code>12 Grav\Common\Processors\DebuggerProcessor process
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:45</code></pre>
  <pre><code>11 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:57</code></pre>
  <pre><code>10 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Common\Processors\ErrorsProcessor.php:27</code></pre>
  <pre><code>9 Grav\Common\Processors\ErrorsProcessor process
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:45</code></pre>
  <pre><code>8 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:57</code></pre>
  <pre><code>7 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Common\Processors\LoggerProcessor.php:48</code></pre>
  <pre><code>6 Grav\Common\Processors\LoggerProcessor process
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:45</code></pre>
  <pre><code>5 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:57</code></pre>
  <pre><code>4 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Common\Processors\ConfigurationProcessor.php:28</code></pre>
  <pre><code>3 Grav\Common\Processors\ConfigurationProcessor process
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:45</code></pre>
  <pre><code>2 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Framework\RequestHandler\Traits\RequestHandlerTrait.php:57</code></pre>
  <pre><code>1 Grav\Framework\RequestHandler\RequestHandler handle
…\system\src\Grav\Common\Grav.php:249</code></pre>
  <pre><code>0 Grav\Common\Grav process
…\index.php:53</code></pre>
</details>

<details>
  <summary>Environment & details</summary>
  <div class="data-table-container" id="data-tables">
    <div>
      <label>GET Data</label>
      <span>empty</span>
    </div>
    <div>
      <label>POST Data</label>
      <table>
        <thead>
        <tr>
          <td>Key</td>
          <td>Value</td>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>username</td>
          <td>"lufog"</td>
        </tr>
        <tr>
          <td>rememberme</td>
          <td>"1"</td>
        </tr>
        <tr>
          <td>task</td>
          <td>"login.login"</td>
        </tr>
        <tr>
          <td>login-form-nonce</td>
          <td>"acf97cb2e52800a288a9f3628cbd60c6"</td>
        </tr>
        </tbody>
      </table>
    </div>
    <div>
      <label>Files</label>
      <span>empty</span>
    </div>
    <div>
      <label>Cookies</label>
      <table>
        <thead>
        <tr>
          <td>Key</td>
          <td>Value</td>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>noname-site-46d248d</td>
          <td>"31h4u007qqmhddot3k73mgepip"</td>
        </tr>
        <tr>
          <td>noname-site-46d248d-admin</td>
          <td>"1o2peime86lb16tkiul77qnij3"</td>
        </tr>
        <tr>
          <td>grav-tabs-state</td>
          <td>
            "{"tab-content.languages.http_headers.markdown.caching.twig.assets.errors.debugger.media.session.advanced":"data.errors"}"
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <div>
      <label>Session</label>
      <table>
        <thead>
        <tr>
          <td>Key</td>
          <td>Value</td>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>user</td>
          <td><abbr title="Grav\Common\User\User">User</abbr> {#146}</td>
        </tr>
        <tr>
          <td>redirect_after_login</td>
          <td>"/"</td>
        </tr>
        <tr>
          <td>messages</td>
          <td><abbr title="RocketTheme\Toolbox\Session\Message">Message</abbr> {#146}</td>
        </tr>
        </tbody>
      </table>
    </div>
    <div>
      <label>Server/Request Data</label>
      <table>
        <thead>
        <tr>
          <td>Key</td>
          <td>Value</td>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>DOCUMENT_ROOT</td>
          <td>"E:\Development\Web\org.noname\noname-grav"</td>
        </tr>
        <tr>
          <td>REMOTE_ADDR</td>
          <td>"127.0.0.1"</td>
        </tr>
        <tr>
          <td>REMOTE_PORT</td>
          <td>"50941"</td>
        </tr>
        <tr>
          <td>SERVER_SOFTWARE</td>
          <td>"PHP 7.3.5 Development Server"</td>
        </tr>
        <tr>
          <td>SERVER_PROTOCOL</td>
          <td>"HTTP/1.1"</td>
        </tr>
        <tr>
          <td>SERVER_NAME</td>
          <td>"0.0.0.0"</td>
        </tr>
        <tr>
          <td>SERVER_PORT</td>
          <td>"80"</td>
        </tr>
        <tr>
          <td>REQUEST_URI</td>
          <td>"/ru"</td>
        </tr>
        <tr>
          <td>REQUEST_METHOD</td>
          <td>"POST"</td>
        </tr>
        <tr>
          <td>SCRIPT_NAME</td>
          <td>"/index.php"</td>
        </tr>
        <tr>
          <td>SCRIPT_FILENAME</td>
          <td>"E:\Development\Web\org.noname\noname-grav\index.php"</td>
        </tr>
        <tr>
          <td>PATH_INFO</td>
          <td>"/ru"</td>
        </tr>
        <tr>
          <td>PHP_SELF</td>
          <td>"/index.php/ru"</td>
        </tr>
        <tr>
          <td>HTTP_HOST</td>
          <td>"localhost"</td>
        </tr>
        <tr>
          <td>HTTP_CONNECTION</td>
          <td>"keep-alive</span>"</td>
        </tr>
        <tr>
          <td>CONTENT_LENGTH</td>
          <td>"114"</td>
        </tr>
        <tr>
          <td>HTTP_CONTENT_LENGTH</td>
          <td>"114"</td>
        </tr>
        <tr>
          <td>HTTP_CACHE_CONTROL</td>
          <td>"max-age=0"</td>
        </tr>
        <tr>
          <td>HTTP_ORIGIN</td>
          <td>"http://localhost"</td>
        </tr>
        <tr>
          <td>HTTP_UPGRADE_INSECURE_REQUESTS</td>
          <td>"1"</td>
        </tr>
        <tr>
          <td>CONTENT_TYPE</td>
          <td>"application/x-www-form-urlencoded"</td>
        </tr>
        <tr>
          <td>HTTP_CONTENT_TYPE</td>
          <td>"application/x-www-form-urlencoded"</td>
        </tr>
        <tr>
          <td>HTTP_USER_AGENT</td>
          <td>"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98
            Safari/537.36 OPR/58.0.3135.132"
          </td>
        </tr>
        <tr>
          <td>HTTP_ACCEPT</td>
          <td>"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"</td>
        </tr>
        <tr>
          <td>HTTP_REFERER</td>
          <td>"http://localhost/ru"</td>
        </tr>
        <tr>
          <td>HTTP_ACCEPT_ENCODING</td>
          <td>"gzip, deflate, br"</td>
        </tr>
        <tr>
          <td>HTTP_ACCEPT_LANGUAGE</td>
          <td>"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6"</td>
        </tr>
        <tr>
          <td>HTTP_COOKIE</td>
          <td>"noname-site-46d248d=31h4u007qqmhddot3k73mgepip; noname-site-46d248d-admin=1o2peime86lb16tkiul77qnij3;
            grav-tabs-state={%22tab-content.languages.http_headers.markdown.caching.twig.assets.errors.debugger.media.session.advanced%22:%22data.errors%22}"
          </td>
        </tr>
        <tr>
          <td>REQUEST_TIME_FLOAT</td>
          <td>1558100710.8152</td>
        </tr>
        <tr>
          <td>REQUEST_TIME</td>
          <td>1558100710</td>
        </tr>
        <tr>
          <td>PHP_CLI_ROUTER</td>
          <td>true</td>
        </tr>
        </tbody>
      </table>
    </div>
    <div>
      <label>Environment Variables</label>
      <span>empty</span>
    </div>
  </div>
</details>

**Comment by rhukster** [comment]
Should be fixed with this: https://github.com/getgrav/grav/commit/be558ccac9223dcc24ec4c04612e5a479714d686
