### ISSUE TITLE
how to can add class to img with number image

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav#2508]
i  do cycle with images 
```
 {% for image in page.media.images %}
......
{{ image.html }}
......
    {% endfor %}
```
how i can add class to img with number images(w1,w2,w3,w4,w5........) 
for example with `{{ loop.index }}`
sorry my engl is bad))

**Comment by dimitrilongo** [comment]
take a look 
https://learn.getgrav.org/16 ->  answers to your question
or https://discourse.getgrav.org/ many answers to your question also
or Discord Channel https://getgrav.org/discord

**Comment by abooks23** [comment]
{{ image.url }}  - give url e.g. /user/pages/.......     ?
