### ISSUE TITLE
Presence of language prefix in URL incorrectly assigns admin session

### ISSUE THREAD

**Issue by CherryDT** [getgrav/grav#2511]
I discovered the following strange behavior on a multi-language page with admin plugin:

* After logging into the admin, my username would appear in the navbar on the page, but only sometimes. Further investigation showed that it would be hidden on the homepage with language prefix without trailing slash (e.g. `/en`) but visible with the trailing slash (e.g. `/en/`) or on sub-pages (e.g. `/en/blog`). This particular symptom is actually because of #2510 in combination with this bug.
* The "save language in session" feature would not work for me (after I "fixed" the previous issue using a htaccess redirect from `/en` to `/en/` - I hadn't fully understood the problem yet). Further investigation showed that on `/` a different session would be used than on `/en/`/`/de/`, and hence the new language would be written to session A but `/` would read from session B and redirect to the wrong language.

Turns out that this is due to a bug in `SessionServiceProvider.php`: It sets `$is_admin = true` if the route starts with `/admin` _or with a language prefix_. It should instead check if it starts with `/<prefix>/admin` in that case!

**Comment by CherryDT** [comment]
I fixed the issue in #2512

**Comment by CherryDT** [comment]
Thanks for the commit, however I'm not sure I understand how this work. Won't `Utils::pathPrefixedByLangCode` simply return `true`, which - if you stuff it into string concatenation - will become `1`, and hence you are now checking for `/1admin`?

**Comment by rhukster** [comment]
There's a second commit with a change in the Utils function.

**Comment by CherryDT** [comment]
Ooh, right, I'm sorry, I didn't realize. Never mind then, thanks for the fix!!
