### ISSUE TITLE
Login strange behavior

### ISSUE THREAD

**Issue by lufog** [getgrav/grav#2514]
I found very strange behavior in Grav. If you add a slash at the end of the address, then authorization from the admin plugin works on the site.

![ju06Ih8c9s](https://user-images.githubusercontent.com/10379487/58197927-f9a92180-7cd5-11e9-9653-5b286d1cc38d.gif)

The experiment was conducted on a clean Grav installation.

**Comment by rhukster** [comment]
Traveling this week, will look as soon as possible.

**Comment by rhukster** [comment]
Maybe a duplicate of this issue?

**Comment by lufog** [comment]
Yep it's duplicate of #2511 pull request #2512 fix that.

**Comment by rhukster** [comment]
Great thanks, i'll get that tested and merged in soon.
