### ISSUE TITLE
Bitwise Operator in TwigExtension.php Causing error with exifFunc

### ISSUE THREAD

**Issue by bperry11** [getgrav/grav#2518]
exifFunc throws "non-numeric value" error. Seems to be caused by accidental '&' instead of '&&' in this if statement:

```php
if ($image & file_exists($image) && $this->config->get('system.media.auto_metadata_exif') && $exif_reader)
```

Changing the first '&' to '&&' stopped the error and the function worked properly.

https://github.com/getgrav/grav/blob/92e8dbf4ea2ece2c3c792819cb4bdc92babfbd17/system/src/Grav/Common/Twig/TwigExtension.php#L1157

**Comment by rhukster** [comment]
It looks like that might of been a typo.  Fixing
