### ISSUE TITLE
SSL error on plugin updates from cert not matching the hostname

### ISSUE THREAD

**Issue by AshleyDumaine** [getgrav/grav#2520]
Grav version: `v1.6.9`

I noticed just yesterday when trying to update my several out-of-date plugins through either `bin/gpm update` or through the admin plugin (forced to cURL), I get the following:
```
Error while trying to download (code: 302): https://getgrav.org/download/plugins/<plugin_name>/3.0.3 Message: SSL peer certificate or SSH remote key was not OK SSL: no alternative certificate subject name matches target host name 'codeload.github.com'
``` 
Oddly, this is happening even with `Remote Verify Peer (SSL)` set to false.

**Comment by w00fz** [comment]
That is odd indeed because the `Remote Verify Peer (SSL)` setting was introduced exactly to bypass SSL errors.

Could you try clearing cache and ensuring the remote verify peer is disabled globally?
Also perhaps try fopen instead of cURL, the verify peer applies to both types.

**Comment by AshleyDumaine** [comment]
Same error happens with `system/config/system.yaml`'s `verify_peer` set to `false` even after clearing the cache. With fopen I still get an error but a less descriptive one regarding the 302:
```
Error while trying to download (code: 302): https://getgrav.org/download/plugins/<plugin>/3.0.3
```

**Comment by w00fz** [comment]
Is your network running behind some proxy?

Also can you try this hardcoded change to see if that helps?

1. Edit `system/src/Grav/Common/GPM/Response.php` (line: 138)
2. Replace
```
'curl' => [
    CURLOPT_SSL_VERIFYPEER => $settings['verify_peer']
],
```
with:
```
'curl' => [
    CURLOPT_SSL_VERIFYPEER => $settings['verify_peer'],
    CURLOPT_SSL_VERIFYHOST => false
],
```
3. Try again making sure you have switched back to cURL as method.

**Comment by AshleyDumaine** [comment]
I'm using nginx as a reverse proxy. The hard coded change fixed the 302 but now I'm getting `Page not found` on all of the plugin updates (both in the admin panel and with bin/gpm)

**Comment by AshleyDumaine** [comment]
Example with `bin/gpm` in verbose mode which is showing 500 errors:
```
$ bin/gpm update admin -v

GPM Releases Configuration: Stable

Found 29 packages installed of which 11 need updating, only 1 will be updated
Limiting updates for only admin

01. Admin Panel     [v1.9.3 -> v1.9.4]

Continue with the update process? [Y|n] 

GPM Releases Configuration: Stable



The following dependencies need to be updated...
  |- Package form

Preparing to install Form [v3.0.3]
  |- Downloading package...    error                             
  |  '- Error while trying to download (code: 500): https://getgrav.org/download/plugins/form/3.0.3 
  |  '- Message: HTTP response code said error
  |  '- The requested URL returned error: 500 Internal Server Error
  '- Installation failed or aborted.


The following dependencies can be updated as there is a newer version, but it's not mandatory...
  |- Package login
  |- Package email

Preparing to install Login [v3.0.2]
  |- Downloading package...    error                             
  |  '- Error while trying to download (code: 500): https://getgrav.org/download/plugins/login/3.0.2 
  |  '- Message: HTTP response code said error
  |  '- The requested URL returned error: 500 Internal Server Error
  '- Installation failed or aborted.

Preparing to install Email [v3.0.2]
  |- Downloading package...    error                             
  |  '- Error while trying to download (code: 500): https://getgrav.org/download/plugins/email/3.0.2 
  |  '- Message: HTTP response code said error
  |  '- The requested URL returned error: 500 Internal Server Error
  '- Installation failed or aborted.


Dependencies are OK

Preparing to install Admin Panel [v1.9.4]
  |- Downloading package...    error                             
  |  '- Error while trying to download (code: 500): https://getgrav.org/download/plugins/admin/1.9.4 
  |  '- Message: HTTP response code said error
  |  '- The requested URL returned error: 500 Internal Server Error
  '- Installation failed or aborted.


Clearing cache

ERROR: 
Cleared:  /var/www/grav/cache/doctrine/*
Cleared:  /var/www/grav/cache/compiled/*

Touched: /var/www/grav/user/config/system.yaml
```

**Comment by AshleyDumaine** [comment]
Aside from the last minor issue, I believe this is likely an error on the machine I'm running the site on as I'm able to run the curl (with and without ssl) on a different machine. Feel free to close, sorry about that.

**Comment by AshleyDumaine** [comment]
This ended up being an obscure failure with the endpoint `codeload.github.com` getting flagged by my network's pi-hole. Thus `codeload.github.com` was resolving to `0.0.0.0` which was presenting the SSL certs on the machine the site is running on, instead of the ones for `codeload.github.com`, resulting in the failure from the initial description. Fix ended up being to have the pi-hole whitelist `codeload.github.com`. Should be good to close.

**Comment by w00fz** [comment]
Glad you managed to sort that out.
If works with the verify peer I would suggest to keep that enabled.
