### ISSUE TITLE
[add-resource] New Theme: Rana

### ISSUE THREAD

**Issue by danzinger** [getgrav/grav#2522]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: https://github.com/danzinger/grav-theme-rana

**Comment by danzinger** [comment]
@rhukster, is there any problem with this contribution?

**Comment by rhukster** [comment]
No i'm just on vacation for a couple of weeks. Sorry will get to this when i'm back.

**Comment by rhukster** [comment]
Added to GPM
