### ISSUE TITLE
 How can I save form by user id when use login to site

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav#2523]
1. user log into site, and had id
2. user  fills form
3. user press submit and form data save with user id

how i can do this?

i know about save data form in txt...

thanks

**Comment by rhukster** [comment]
In your process action:

```
save:
            filename: 'csvdata-{{ grav.user.username ?: ''guest'' }}.txt'
```

This will cause the data to be saved with the username in the filename

**Comment by abooks23** [comment]
thanks

**Comment by abooks23** [comment]
not working i recive file 20190526-154738-436633.txt
i think 'date-time-????.txt' , thrid part of name file (????)  random every press submit

**Comment by rhukster** [comment]
what do you have defined for the `filename:` in the YAML?

**Comment by abooks23** [comment]
no... where?

**Comment by rhukster** [comment]
In you form under the `process:` section, see the code example i pasted originally.

**Comment by rhukster** [comment]
BTW, i tested and it works fine, so any issues is user error :)

**Comment by abooks23** [comment]
work to))  thanks
