### ISSUE TITLE
Index Mis-spelling for reCAPTCHA Contact Plugin

### ISSUE THREAD

**Issue by bassplayer7** [getgrav/grav#253]
I just tried to install `recaptchacontact` per the [documentation](https://github.com/aradianoff/recaptchacontact#gpm-installation-preferred), but received the message:

> Nothing to install.

When I listed the plugins that could be installed, I discovered that there was a misspelling and the index was actually: `recatpchacontact` instead of `recaptchacontact` (notice the `pt` is reversed) as it should. The plugin installed correctly with the misspelling. 

I looked around the [plugin](https://github.com/aradianoff/recaptchacontact), and found the mispelling in [one spot](https://github.com/aradianoff/recaptchacontact/search?utf8=%E2%9C%93&q=recatpchacontact), but am not sure if that is the place that impacts the official grav repo plugin index.

**Comment by rhukster** [comment]
Yes the author asked me to correct a typo, and I've not gotten to that yet.  Will do so now.

**Comment by rhukster** [comment]
Fixed, closing...
