### ISSUE TITLE
Huge Google Index Problem

### ISSUE THREAD

**Issue by prinla** [getgrav/grav#2531]
I was desperately trying to find out why on every index request of google a lot of my websites gave an error (5xx) ?!?

Indeed the pages were shown correctly in any browser but nonetheless google could not read them correctly (indeed some web-sniffer neather)

By chance I found that the bot requested **.txt.twig** instead of **.html.twig** (still don't know why). And the chance was even bigger when I found that issue on git (https://github.com/getgrav/grav/issues/2337) where the solution seemed to be to **adjust the files-array** in the **system-config**.

Now I suppose this is not only happening to me (people check your webpages on google webmaster even if they are almost indexed - mine were but by chance I rechecked and was confronted to the problem)!!!

**And maybe the Grav-Team could find us a real fix instead of having to change all the system configs of all my websites!!!**

@rhukster if you need more details about the problem, just tell me, I will provide them.

![inear](https://user-images.githubusercontent.com/16805582/58833938-703d0c00-8652-11e9-82c2-0755c14fb56e.JPG)

![accesslog](https://user-images.githubusercontent.com/16805582/58833967-7d59fb00-8652-11e9-95a6-87fdb168f8a1.JPG)

**Comment by glasswork** [comment]
Have you tried turning gzip compression on? I experienced similar oddities with LinkedIn, the Wayback machine, and the W3C Validator refusing to index pages --- turning gzip on fixed the issue for me. Maybe this is a related issue.

**Comment by mahagr** [comment]
Unfortunately, there is really no way to automatically change your site configuration once you have saved it from admin.

@rhukster Maybe we should force html to be the first in the list; after all, it is a web site.

**Comment by rhukster** [comment]
I've decided to use a new function that will always ensure the list is ordered with html/htm first. I only found 2 occurences of this value being used, both within Grav core, so should be fine for future updates.  Please test.
