### ISSUE TITLE
Grav is using filemdate instead of item.md date

### ISSUE THREAD

**Issue by mabushey** [getgrav/grav#2534]
Using the git-sync module to push up and then recreate site from git causes the file modification date to become current.  Using the Antimatter theme it is showing the pages as today's date (`04/JUN`) even though I have the Publishing date set for these documents.

```
# cat pages/02.notes/21.grbl/item.md 
---
title: GRBL
published: true
date: '2015-12-28 00:00'
```

From the page html:
```
<time class="dt-published" datetime="2019-06-04T12:38:10-07:00">
                <span>04</span>
                <em>Jun</em>
```

Running Grav v1.6.9 and Antimatter v2.2.0.
![2019-06-04_grav_date_error](https://user-images.githubusercontent.com/7863135/58910251-e892e400-86c9-11e9-9904-a5e42f892fd7.png)

**Comment by rhukster** [comment]
Can you try with the time first?

```
date: '00:00 2015-12-28'
```

**Comment by mabushey** [comment]
From user/config/system.yaml:
```
  dateformat:
    default: 'Y-m-d H:i'
    short: 'F jS \a\t g:ia'
    long: 'F jS \a\t g:ia'
```

The dates were all "entered" via the date picker in the admin plugin.

**Comment by mabushey** [comment]
This was me being stupid with two articles named similar (GRBL, Install GRBL). One didn't have a date. Sorry for wasting your time, and thanks again for such an awesome CMS.
