### ISSUE TITLE
a child theme does not inherit the parent configuration

### ISSUE THREAD

**Issue by aoloe** [getgrav/grav#2537]
as mentioned in discord, when i create a child theme based on quark i get slightly different behavior.

ricardo pointed me to the fact that the child theme is missing the configuration that is in the parent theme.

indeed, copying over the content of `quark.yaml`, get's me a perfect "copy".

if nothing speaks against it, i would expect my new theme to behave exactly the same as the parent one. this could be achieved by avoiding any config in the "defafult" themes or by letting the child theme read the parent config by default. (being able to turn this off might be a good feature...)

**Comment by aoloe** [comment]
... the theme has been created with the dev plugin...

**Comment by rhukster** [comment]
This is a limitation of child themes.  You need to 'copy' the configuration.  

I would only use a child theme if you were making very minor changes to a theme.  For most situations (99% of the time) it just is easier to copy the theme you want to base things from (with devtools) to a new theme.

**Comment by aoloe** [comment]
if child themes are supposed to be used for small changes, it's IMO even more important that the child works in the same way as the parent one...

<https://getgrav.org/blog/theme-development-with-inheritance> -- the first result in my google -- does not mention the need for copying the settings...

<https://learn.getgrav.org/16/themes/customization#theme-inheritance> shows a "manual" copy that includes copying the yaml file, but not the usage of the dev plugin (refers to the blog entry above for more).

personally, i'm not a front end designer and appreciate it, if i can build on the shoulders of giants... and inheriting from a base theme is the easiest way for me to track what i have changed (and potentially messed up).

summary:

- please improve the documentation, or
- get the dev tool to copy the content of the parent settings, or
- get the inheritance to also work for the setting.

**Comment by Perlkonig** [comment]
Related to [PR 2143] (https://github.com/getgrav/grav/issues/2537)

**Comment by mahagr** [comment]
Actually, it is not a limitation of child theme -- it was done like that by design. It has been a long time so I cannot really remember why it was done like that, but I'm sure there was a good reason to do it like that (years ago).
