### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav#254]
Sometimes errors are a bit obscure to users.

Like:

- mbstring support enabled ("Call to undefined function Grav\Common\Page\mb_strpos()")
- missing plugin required by another plugin (e.g. Login plugin required by Admin)
- missing proper user/accounts/ files (this is specific to login plugin for now, so maybe better to be managed by that directly on the login screen)
- php version check
- ...

I'd be useful to have some system in place to intercept those errors before they actually happen, with pointers to solve them, leading to less head scratching, thoughts on this topic?

**Comment by rhukster** [comment]
I think we just need to throw more informative exceptions where they occur.

**Comment by rhukster** [comment]
Did one already:

![crikey there was an error 2015-08-26 11-13-18](https://cloud.githubusercontent.com/assets/1084697/9500578/859c71ec-4be3-11e5-961a-50caac175396.png)

and with `error: display: false`:

![whoops there was an error 2015-08-26 11-14-05](https://cloud.githubusercontent.com/assets/1084697/9500604/9fe35476-4be3-11e5-8e0b-a12fc1cdc3c9.png)
