### ISSUE TITLE
search string

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav#2543]
Hi
need to compare the search string , for example: link` /search/query:abcd`, string `abcd`
 with given value, for example:` {% if abcd == ' qwerty' %}`
how I can get value ` 'abcd'` in twig for copmpare?

**Comment by N-Parsons** [comment]
I'm not sure about the colon syntax, but if you use `?` for your query parameters (eg. `/search?query=abcd`), you can access the query as a string using `grav.request.uri.query`. If you have multiple parameters, you can split on `&`, and then split the elements on `=` to get the parameter names and values; if it's just the one parameter, you only need the latter split, but there's no real issue in doing both.

If you enable the debugger and add `{{ dump(grav.request.uri) }}` in your twig template (or page if you enable twig processing there), it'll print the to messages. You can adjust the dump command (or use multiple) to explore what other useful keys exist.

**Comment by abooks23** [comment]
thanks
