### ISSUE TITLE
How to Set grav.user variable or reload user object

### ISSUE THREAD

**Issue by TheBitmonkey** [getgrav/grav#2546]
Hi,

This is not a bug just looking for a way to accomplish something.

I am setting some custom Variables in the accounts users yaml file. Unfortunatly these are not updated for the user until the next time they login:

Possible Solutions:

In a php file (not plugin) set the grav.user.myVariable   - I don't know how to.
Reload the user variables to reflect the latest variables - Can I do this in a twig file or external php file.

Those anybody have any idea how to do this. I am in a bad way with a live project. 

Thank you in advance.

**Comment by mahagr** [comment]
This has already been implemented. In Login plugin set `Sync User in Session` to `Enabled`. 

Note: This means that you need to update user fields from an event on every page load if they were not saved to the file.
