### ISSUE TITLE
[add-resource] New Plugin: Admin Frontmatter Yaml

### ISSUE THREAD

**Issue by igk1972** [getgrav/grav#2557]
Add a new Plugin to the Grav Repository, the project details: [grav-plugin-admin-frontmatter-yaml](https://github.com/igk1972/grav-plugin-admin-frontmatter-yaml).

In short, it lets adds a functional to contain non-localized header blocks in the frontmatter.yaml file. This is allows you to avoid duplication of common values, which are saved out in a single file. 

The most frequent use - for sites with content in many languages.

**Comment by rhukster** [comment]
I've added this to GPM, but you need to create a release before it will show up.  Check the learn docs for details.  

https://learn.getgrav.org/16/advanced/grav-development#theme-plugin-release-process

Cheers

**Comment by igk1972** [comment]
Thanks.

I created tag and release ([grav-plugin-admin-frontmatter-yaml/releases](https://github.com/igk1972/grav-plugin-admin-frontmatter-yaml/releases))

**Comment by rhukster** [comment]
It's showing in GPM now.. thanks.
