### ISSUE TITLE
Clockwork extension debugger not being recogized

### ISSUE THREAD

**Issue by chase-cromwell** [getgrav/grav#2558]
I have the Clockwork extension installed, and I have the Clockwork debugger enabled in the configuration, but I still get the "You need to install the Clockwork extension" Is there any documentation for the Clockwork debugging? I can't seem to find any recent info.
![image](https://user-images.githubusercontent.com/24304167/59793862-d3ef4800-9294-11e9-9fb1-77a1e9e40060.png)
![image](https://user-images.githubusercontent.com/24304167/59794051-4e1fcc80-9295-11e9-8afd-34814d3b0e8d.png)
Extension I've installed: https://chrome.google.com/webstore/detail/clockwork/dmggabnehkmmfmdffgajcflpdjlnoemp
Is there some other way to activate the Clockwork debug panel?

**Comment by paulhibbitts** [comment]
Hi @chase-cromwell , in Chrome (or Firefox) you need to View the Developer Tools and then tap on the Clockwork tab - here is what it looks like in Google Chrome:
![2019-06-19_13-24-11](https://user-images.githubusercontent.com/1812771/59797894-ba023500-9295-11e9-9441-38924bbaaa52.png)

**Comment by chase-cromwell** [comment]
Ah! I use my developer tools in the right hand panel, not bottom so the "Clockwork" button was hidden in a collapsed dropdown (just wasn't looking close enough)
Many thanks @paulhibbitts

**Comment by mahagr** [comment]
@rhukster Should we change the message a bit and add a link to a Grav learn page?

`Grav Clockwork Debugger Enabled. Please refer the documentation on how to use or disable it.`

**Comment by paulhibbitts** [comment]
Perhaps something like this might help @rhukster @mahagr ?

```
Grav Clockwork debugger enabled. Install Clockwork Browser extension (Chrome or Firefox), open your Developer tools and then select the Clockwork tab. Visit https://underground.works/clockwork for more information.
```

I'd also suggest not to display this text in red, as it is not an error condition but rather an informational in nature.
