### ISSUE TITLE
find some pages

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav#2564]
Hi
any page had id, how use page.find() with id()  (if page name unknown) to find necessary page, in php

iterate all page for (eg  if  page.id() == $ id) find current id or something else?

**Comment by rhukster** [comment]
I see you asked this question on the Discord chat.  That IS the correct place for asking basic questions about Grav usage. Also, try searching on learn.getgrav.org.

The Github issues list is intended for bug reporting and complex questions about Grav internals and things that are not suited to other formats.

Cheers,

**Comment by abooks23** [comment]
I not find this on learn.getgrav.org, 
about this no answer, only page find by route, path and other...
