### ISSUE TITLE
Page Permissions per role(group)

### ISSUE THREAD

**Issue by localnetwork** [getgrav/grav#2566]
Not quiet sure if there's a way in grav to restrict roles in edit, create, delete. I've seen this plugin: https://github.com/Moonlight63/grav-plugin-users-page-ownership but it seem's like i was not able to make this work to meet my requirements.

See attached screenshot.

Thank you.
![grav-page-permission](https://user-images.githubusercontent.com/15809239/60153027-8420fb80-9815-11e9-831b-7a32f4f48f7b.jpg)

**Comment by rhukster** [comment]
There is currently no built-in way.  We want to add this functionality in the future, but it's just not there yet.

**Comment by localnetwork** [comment]
Thanks for your reply @rhukster 

This will be a great addition in the future :)

**Comment by mahagr** [comment]
I'd like to add this one to flex pages someday. :)
