### ISSUE TITLE
Grav Scheduler error emails after deleting site

### ISSUE THREAD

**Issue by diegovogel** [getgrav/grav#2567]
Not sure if this is a bug or just something I don't know how to deal with, but here's the situation. I recently turned on the Grav Scheduler on a site that was running on my local machine. A few days later I deleted the site. Now when I open the terminal it keeps telling me I have new mail. I looked into it and within the past few hours I've gotten almost 200 emails with errors related to the Grav Scheduler. And these emails are all local, as in they're sent, received, and stored locally instead of online. Here's the message text:
```
Message 185:
From diegovogel@diegos-mbp.lan  Thu Jun 27 12:21:00 2019
X-Original-To: diegovogel
Delivered-To: diegovogel@diegos-mbp.lan
From: diegovogel@diegos-mbp.lan (Cron Daemon)
To: diegovogel@diegos-mbp.lan
Subject: Cron <diegovogel@diegos-mbp> cd /Users/diegovogel/LocalSites/onredemption.dev.cc;/usr/bin/php bin/grav scheduler 1>> /dev/null 2>&1
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=diegovogel>
X-Cron-Env: <USER=diegovogel>
X-Cron-Env: <HOME=/Users/diegovogel>
Date: Thu, 27 Jun 2019 12:21:00 -0400 (EDT)

/bin/sh: line 0: cd: /Users/diegovogel/LocalSites/onredemption.dev.cc: No such file or directory
```

I don't know much about cron jobs but from what I can tell it looks like a Grav Scheduler cron job is trying to run and failing because I deleted the site. My questions are:

1. How do I go about stopping this so I don't get hundreds of emails a day about this?
2. Could this be automatically taken care of by Grav as a future enhancement?

**Comment by rhukster** [comment]
The issue is that scheduler requires a cron entry.  That cron process is completely external to Grav. So if you delete the site, the cron entry is still there and will still try to run the scheduler.  So you need to remove that yourself also.

**Comment by diegovogel** [comment]
Thanks for the explanation @rhukster, I was able to find the offending cron entry and remove it. Would it be possible to have Grav do this automatically in the future?

**Comment by diegovogel** [comment]
Thanks for the explanation @rhukster, I was able to find the cron entry and remove it. That fixed it.
