### ISSUE TITLE
Bug: 127.0.0.1 overrides $_SERVER['REMOTE_ADDR']

### ISSUE THREAD

**Issue by cord** [getgrav/grav#257]
having multiple virtual hostnames on 127.0.0.1 does not work for environment configuration files as $_SERVER['REMOTE_ADDR'] is ignored

grav/system/src/Grav/Common/Uri.php:60

**Comment by rhukster** [comment]
`$_SERVER['HTTP_HOST']` is now taken into account making it more vhost friendly.
