### ISSUE TITLE
XML Output?

### ISSUE THREAD

**Issue by thejame** [getgrav/grav#2574]
I need an RSS feed for iTunes submission and have created a template (**podcast.xml.twig**) and page (**podcast.md**) that output XML. 

The problem is when I want to edit anything in the Markdown page in the Admin Plugin. Because I am using **podcast.xml.twig** (and not **podcast.html.twig**), the template does not show up in the Page Template dropdown of the Advanced tab of the page. This field defaults to the first template in the list, which then gets changed when the page is saved. This means my page loses its template and is useless. 

If I set the template to **podcast.html.twig** instead, I can force XML with `template_format: xml` but the page is still rendered in HTML. The Page Template value populates correctly, but this can't be submitted to iTunes because it's not a valid RSS feed.

I need XML- how can I get valid XML without risking my template type getting overwritten each time someone edits the page?

**Comment by rhukster** [comment]
you should be able to just have a dummy `podcast.html.twig` template to ensure it shows up in the dropdown, but still keep your `podcoast.xml.twig` file for rendering it.  Then when you request `http://yoursite.com/your-podcast.xml` it will automatically use the XML twig.  You could even set the redirect on the page to redirect `your-podast[.html]` to `your-podcast.xml`.  Would that work?

**Comment by thejame** [comment]
Are you talking about putting a redirect for the page in site.yaml? 
A blank html.twig template could do it - as long as the template override for template_format doesn't change.

**Comment by thejame** [comment]
This is working so far - I'm going to close the issue for now.
