### ISSUE TITLE
When i change routes.default the old slug still work

### ISSUE THREAD

**Issue by reo4** [getgrav/grav#2575]
when i add

routes: 
    default: '/map'

to override typography page route  , the '/typography' still redirect to the same page i excepect /map

**Comment by rhukster** [comment]
The old route will always be there to stop breakage, but it should redirect to the default. I will investigate.

**Comment by mahagr** [comment]
FYI: Currently Grav always adds the folder path to the alternative routes for the page.

**Comment by mahagr** [comment]
There is now a setting that fixes this behavior: `system.pages.redirect_default_route`.
