### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by Memurame** [getgrav/grav#2579]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: /Memurame/grav-toolbox

**Comment by rhukster** [comment]
Please use the repo naming format.  “grav-plugin-yourpluginname” or “grav-theme-youthemename”

Also toolbox name is already used by an internal plugin so please choose another name.

**Comment by Memurame** [comment]
Ok i changed the name. The new repo:
https://github.com/Memurame/grav-plugin-toolbox

**Comment by rhukster** [comment]
I also mentioned that **toolbox** is the name of an existing internal plugin, and you need to pick another name.

**Comment by Memurame** [comment]
Oh, my mistake.
Now i have renamed.
https://github.com/Memurame/grav-plugin-smartthings

**Comment by rhukster** [comment]
Added to GPM

**Comment by Memurame** [comment]
I can't find the plugin in the GPM and Plugin list.
Or is this only integrated with the next Grav Update?


> Added to GPM

**Comment by rhukster** [comment]
There's still no release in Github: Please ensure you have followed all the steps here: https://learn.getgrav.org/16/advanced/grav-development#theme-plugin-release-process
