### ISSUE TITLE
add dd() like in laravel

### ISSUE THREAD

**Issue by cord** [getgrav/grav#258]
handy for quick debugging

http://laravel.com/docs/4.2/helpers

dd

Dump the given variable and end execution of the script.

dd($value);

**Comment by dfrankland** [comment]
I think the Symfony equivilant is this: http://symfony.com/doc/current/components/var_dumper/introduction.html

**Comment by rhukster** [comment]
actually the symfony 'dump()` method is pretty darn nice.  Going to add it in the next release.

![dashboard grav2 2015-08-21 13-10-29](https://cloud.githubusercontent.com/assets/1084697/9416989/0782c31e-4806-11e5-9c0b-8212009aa8e3.png)

**Comment by rhukster** [comment]
Fixed via cf867d29a0ce44cd3570fcce2c8dad39f6637597
