### ISSUE TITLE
Installation checker should verify temp folder is accessible

### ISSUE THREAD

**Issue by MarcinOrlowski** [getgrav/grav#2582]
I had misconfigured setup and installation checker said all is fine. But later I figure out that I am unable to upload anything and it took me a moment to figure out why. I think it would not be too check if grav is able to use php configured temp folder for write

**Comment by rhukster** [comment]
It's kind of redundant.  The whole point of temp is for any application or service to write temporary files.  If temp is not writable, it's basically broken for everything, not just PHP.

**Comment by MarcinOrlowski** [comment]
You can easily set wrong path just for the installation i.e. with vhosts's `php_admin_value upload_tmp_dir SOME-WRONG-PATH` and this got nothing to do with system wide temp folder.
