### ISSUE TITLE
Constant RuntimeException Folder.php line 393 while updating plugins

### ISSUE THREAD

**Issue by Romarain** [getgrav/grav#2584]
_**Edit :** workaround here : https://github.com/getgrav/grav/issues/2584#issuecomment-511026016_

After an upgrade from 1.6.0-rc.4 to the latest Grav version (releases: testing), I tried to update plugins : 

```
01. Admin Panel     [v1.9.7 -> v1.10.0-beta.4]
02. Form            [v3.0.0-rc.4 -> v3.0.7]
03. Login           [v3.0.0-rc.4 -> v3.0.3]
04. Pagination      [v1.4.1 -> v1.4.2]
05. Problems        [v2.0.2 -> v2.0.3]
06. Widget          [v1.3.0 -> v1.3.2]
```
but if failed at one moment : 
```
Preparing to install Admin Panel [v1.10.0-beta.4]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!

Preparing to install Form [v3.0.7]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!

Preparing to install Login [v3.0.3]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...
In Folder.php line 393:

  [RuntimeException]
```
Then, when I retried, it said : 
```
01. Pagination      [v1.4.1 -> v1.4.2]
02. Problems        [v2.0.2 -> v2.0.3]
03. Widget          [v1.3.0 -> v1.3.2]
```
and it failed again : 
```
Preparing to install Pagination [v1.4.2]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!

Preparing to install Problems [v2.0.3]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...
In Folder.php line 393:

  [RuntimeException]
```

### Maybe one important information

When I first tried to `update` the plugins, I previously reset the global _system.yaml_ gpm release field to "_stable_", because I saw that it was on "_testing_" (wich was used for the self-upgrade), and I would like to set it to "_stable_" for production environment (while I did let it to "_testing_" on local).

So, the local CLI `self-upgrade` of my Grav project was made under "_testing_", but then, the first attempt of plugins update was made under "_stable_". Then, when it failed, I reset back the global _system.yaml_ channel to "_testing_", **and the above code excerpts are coming from that second and third attempt**. ;)

**Comment by Romarain** [comment]
After investigation, it may be due to files permissions. But I never changed anything under Windows 7, neither on my Xampp config (not mentioning that some of the plugins succeed in updating).

I re-tested to install one missing plugin (the `problems` plugin) with the CLI :
```
Preparing to install Login [v3.0.3]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...
In Folder.php line 393:

  [RuntimeException]
```
So I tried to install it directly from the admin panel. It said it succeed, but in fact the plugin isn't installed, and an alert is showing an error message : 
![2019-07-12_14h52m57s_chrome](https://user-images.githubusercontent.com/22033256/61131294-1fbe9700-a4b9-11e9-87c1-b894ebabbbe5.jpg)

So, I check the `user/plugins/problems` folder's permissions.

Here's the owner (me) : 
```
dir /Q plugins\problems
 Répertoire de D:\Travail\Programmation\Web\Projets_pro\Resonnances\www\user\plugins\problems
12/07/2019  14:32    <REP>          DEV\Romarain           .
12/07/2019  14:32    <REP>          DEV\Romarain           ..
               0 fichier(s)                0 octets
               2 Rép(s)  67 727 667 200 octets libres
```
Here's my account permissions : 
```
Belong to local groups          *Administrateurs
                                *HomeUsers
Belong to global groups         *None
```
Here's the `problems` folder's permissions : 
```
icacls plugins\problems
                             BUILTIN\Administrateurs:(I)(F)
                             BUILTIN\Administrateurs:(I)(OI)(CI)(IO)(F)
                             AUTORITE NT\Système:(I)(F)
                             AUTORITE NT\Système:(I)(OI)(CI)(IO)(F)
                             AUTORITE NT\Utilisateurs authentifiés:(I)(M)
                             AUTORITE NT\Utilisateurs authentifiés:(I)(OI)(CI)(IO)(M)
                             BUILTIN\Utilisateurs:(I)(RX)
                             BUILTIN\Utilisateurs:(I)(OI)(CI)(IO)(GR,GE)
```
(F) means "total control".
(M) means "modification" (R+W+X).
(RX) means "read and write" (R+W).

So as you can see, the SYSTEM (Système) and ADMINISTRATORS (Administrateurs) are in (F).

**Comment by rhukster** [comment]
It does look like some wonky permissions.  Not sure how it got to that point.  But it might just be simpler to reinstall and copy your user folder back over.

**Comment by Romarain** [comment]
If I really can't solve the problem, I'm going to do that.
But before, I'm trying to investigate on a possible issue with PHP and the folder deletion process under the management of the GPM and/or plugin installation internals.
Here what I found on the rmdir page of PHP : https://www.php.net/manual/en/function.rmdir.php
```
In case you're trying to rmdir() and you keep getting 'Permission denied' errors, make sure you don't have the directory still open after using opendir(). Especially when writing recursive functions for deleting directories, make sure you have closedir() BEFORE rmdir().
```
Also : 
```
Say, you're working on Windows and continue to get a permission's error without a reason. Then it may be that a different Windows program is working on the folder (see earlier notes also). In the case that you can't find that program, the line

<?php closedir(opendir($dirname)); ?>

may solve the problem!
Make sure to write this before rmdir($dirname);.
```
I'm going to watch the `error` plugin files (it's one of the plugin that fails installing on my machine) to find some `opendir()` uses that wouldn't have been closed correctly.

**Comment by Romarain** [comment]
I found nothing in the PHP files. So I decided to use the technic of the **manual deletion**.

### Workaround for fixing the RuntimeException

1. Try to manually delete the remaining folder of the plugin that is failing during installation or update or reinstallation (go in the plugins/ folder, and directly delete the desired folder). _Note : the folder should be empty if a previous installation failed (the folder had been emptied, but its own deletion failed)._
2. If a permission elevation prevent you to delete, change the security rights in order to give "total control" on the Authentified Users (Windows), or create an entry for your specific user (add an entity).
3. Retry the plugin installation. It should succeed.

Thanks for the message anyway, @rhukster ! ;)
This topic can be closed _(if an explanation comes later about those random permission problems, I will surely edit my message to share it)_.
