### ISSUE TITLE
problem with JS

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav#2585]
this script good work in Joomla
```
    var controller6 = new ScrollMagic();
var d6 = new TimelineMax();
d6
.to(line2pr3, 0.1,  {opacity:1})
.fromTo(line2pr3, 1, {drawSVG:"0 0%"}, {drawSVG:"100% 0%", ease:Power1.easeInOut})
.to(circle2pr3, 0.6, {attr:{r:116, transformOrigin:"50% 50%"}, opacity:1,  ease:Power1.easeInOut});

var scene6 = new ScrollScene({triggerElement: "#pre001", triggerHook: 'onEnter', offset:'500',duration:'400'})
    .addTo(controller6)
        .setPin("#pre001", {pushFollowers: true})
    .setTween(d6.play());
```
when insert this to Grav - not working
.setPin work good, and work in there position, but tween stat immediately after page load...
what nuances in Grav?

Help with this please

**Comment by rhukster** [comment]
How are you inserting into Grav?  What is it supposed to do? Do you have the actual ScrollMagic script installed and running? 

Just pasting the JS by itself in isolation does not help. JS is run by the browser, not the webserver.  If the JS has been output to the browser in a script tag, Grav has done it's job.  99% chance it's user/setup/configuration error.

**Comment by abooks23** [comment]
wrong order js files...  ScrollMagic need load after Tweenmax
