### ISSUE TITLE
[add-resource] New Theme - Klb4

### ISSUE THREAD

**Issue by lauroguedes** [getgrav/grav#2586]
I would like to add my new theme to the Grav Repository.
Here are the project details: **https://github.com/lauroguedes/grav-theme-klb4**

**Comment by rhukster** [comment]
Probably need to update your readme:) says your theme is the new default theme for grav

**Comment by lauroguedes** [comment]
I don't understand 🤔

**Comment by rhukster** [comment]
Looks like you sorted it now: https://github.com/lauroguedes/grav-theme-klb4/commit/39cb7e671184429fa4b8f738bb18c55d050638d1

**Comment by lauroguedes** [comment]
all right now rsrs?

**Comment by rhukster** [comment]
Added to GPM.
