### ISSUE TITLE
Multiple classes issue in Markdown Extra

### ISSUE THREAD

**Issue by onetrev** [getgrav/grav#2590]
I've found a weird potential glitch when working with Markdown Extra -- Inline HTML. So if I use this code block below, the two classes are generated as expected for the image _outside_ of the `<div>`. However, for the same image and same code inside the `<div>` block it doesn't parse the comma and just puts the entire class in as one like so: `class="content-intro-img,u-center"`

```
![Life buoy](life-buoy.svg?resize=250,250&classes=content-intro-img,u-center)

<div class="c-image-content-block" markdown="1">
  
  ![Life buoy](life-buoy.svg?resize=250,250&classes=content-intro-img,u-center)
  
  We want to help your business. Lorem ipsum delor florat.
  
</div>
```

If however I refactor the markdown to use the { .myclass } notation like below, then it generates the classes correctly both inside and outside of the div:

`![Life buoy](life-buoy.svg?resize=250,250) {.content-intro-img .u-center}`

Hopefully that makes sense. Ideally the first way would work as I think it's easier to work with. To be honest I'm not sure which way is recommended. The [Image Link](https://learn.getgrav.org/16/content/image-linking) page in the docs shows the first way, the [Media](https://learn.getgrav.org/16/content/media) page shows the latter.

NOTE: Grav v1.7.0-beta.4 - Admin v1.10.0-beta.4

**Comment by rhukster** [comment]
The `![Life buoy](life-buoy.svg?resize=250,250&classes=content-intro-img,u-center)` syntax is preferred as this is handled in a our custom parsedown functionality.  "Parsedown Extra" which provides MarkdownExtra functionality is very buggy, and this seems to be another case of that.  I recommend NOT using Markdown Extra at all

Instead, can install the `shortcode-core` plugin to get your surrounding div:

```
[div class=c-image-content-block"]
  
  ![Life buoy](life-buoy.svg?resize=250,250&classes=content-intro-img,u-center)
  
  We want to help your business. Lorem ipsum delor florat.
  
[/div]
```

**Comment by onetrev** [comment]
Gotcha, good to know. I've found that the shortcode works even with nested [div] shortcodes, so that's awesome. However, once you get more complex HTML I suppose the best bet then is just to go with custom `.twig` templates right? Or is there another suggested route? The only issue with the twig being then if you just want to make a quick tweak you have to jump into your code editor... Hopefully one day there can be template editing with the admin. :)

PS, not sure I should close this issue, as technically it's still a bug I guess, but I'm cool either way.

**Comment by rhukster** [comment]
It's really an issue with Parsedown Extra, so might as well close it.
