### ISSUE TITLE
Preview eye icon 

### ISSUE THREAD

**Issue by Sceko** [getgrav/grav#2591]
Click on eye icon http://prntscr.com/ofect4
go to Error 404
Is open http://127.0.0.1/grav/fi/admin/preview
Fix this on Beta version

**Comment by rhukster** [comment]
Which version are you having this issue on?

**Comment by Sceko** [comment]
beta

**Comment by rhukster** [comment]
I think this is fixed in the 1.10 admin branch already, can you test that?
