### ISSUE TITLE
ReferenceError: GravForm is not defined

### ISSUE THREAD

**Issue by localnetwork** [getgrav/grav#2592]
When the JS pipeline is activated, the following error shows up in the console which breaks the dropzone.

https://github.com/getgrav/grav-plugin-email/issues/58

**Comment by rhukster** [comment]
Do you have a `bottom` JS block in your theme?

**Comment by localnetwork** [comment]
Yes, it only occurs when JS pipeline is enabled.

**Comment by rhukster** [comment]
Fixed in Form plugin: https://github.com/getgrav/grav-plugin-form/commit/96eeff2634a6eb0d52dfc0afc30f5dd7e7b98255
