### ISSUE TITLE
[add-resource] New Plugins

### ISSUE THREAD

**Issue by ayozehd** [getgrav/grav#2595]
Hey Grav team!

I would like to add these new plugins to the Grav Repository.
Here are the project details: 
* [ayozehd/grav-plugin-lastfm](https://github.com/ayozehd/grav-plugin-lastfm/)
* [ayozehd/grav-plugin-sharer](https://github.com/ayozehd/grav-plugin-sharer/)

**Comment by rhukster** [comment]
Added both to GPM.
