### ISSUE TITLE
Interpreter strips Strings in code snippets

### ISSUE THREAD

**Issue by emign** [getgrav/grav#2598]
Hi,
the code snippet
`<pre>
    fun main(args: Array<String>) {
    val text = "SomeText"
    val len = text?.let {
        println("get length of $it")
        it.length
    } ?: 0
    println("Length of $text is $len")
}
</pre>`

gets printed as 

>   fun main(args: Array) {
>     val text = "SomeText"
>     val len = text?.let {
>         println("get length of $it")
>         it.length
>     } ?: 0
>     println("Length of $text is $len")
> }

 ` <String>
`
 is missing)

**Comment by rhukster** [comment]
Can you paste the sample code as a code-block so the indent/newlines are preserved?

**Comment by emign** [comment]
It's only an example code.
```
<pre> 
	fun main(args: Array<String>) { 
		val text = "SomeText" 
		val len = text?
					.let { println("get length of $it") it.length } ?: 0 println("Length of $text is $len") }
 </pre>
```
The problem is caused by the lesser than sign. Changing the code to manually entered html entities

```
<pre> 
	fun main(args: Array&lt;String&gt;) { 
		val text = "SomeText" 
		val len = text?
					.let { println("get length of $it") it.length } ?: 0 println("Length of $text is $len") }
 </pre>
```
works but is very inconvenient

**Comment by mahagr** [comment]
This is basic HTML, nothing we can do here. Use <code> tag to change the behavior.
