### ISSUE TITLE
[add-resource] New Plugin (shortcode-citation)

### ISSUE THREAD

**Issue by N-Parsons** [getgrav/grav#2599]
I would like to add a plugin to the Grav Repository.

Here are the project details: https://github.com/n-parsons/grav-plugin-shortcode-citation

The Shortcode Citation plugin for Grav provides the ability to add citations to web pages via the `[cite=id /]` shortcode, and then print an ordered list of references.

**Comment by rhukster** [comment]
Added to GPM
