### ISSUE TITLE
Where can I download the theme of this site? https://learn.getgrav.org/16

### ISSUE THREAD

**Issue by cnguu** [getgrav/grav#2604]

**Comment by lufog** [comment]
Really?..
https://getgrav.org/downloads/themes

**Comment by cnguu** [comment]
@lufog 

I found the theme of this [website](https://learn.getgrav.org/16) is [learn4](https://github.com/getgrav/grav-learn/blob/develop/themes/learn4), but I didn't find it [here](https://getgrav.org/downloads/themes).

**Comment by rhukster** [comment]
Learn4 is not a 'released' theme yet, because i've not had time to clean it up and make it ready.  You can mess with it by downloading directly: https://github.com/getgrav/grav-theme-learn4
