### ISSUE TITLE
How inrate SVG?

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav#2606]
Hi, somebody ask how iterate svg in twig? I post question in discord and no answer
I try this 
{% for image in page.media.images %} with {{ image.html }}
this
{% for image in page.media.files%}
no work...

**Comment by localnetwork** [comment]
{% for image in page.media.images %}
 {{ image.url }}
{% endfor %}

try if that works for you. you can also ask questions here: https://discourse.getgrav.org/

**Comment by rhukster** [comment]
if I remember correctly, you have to iterate over `.files` not `.images`.  You might have to look for files with `svg` extension though.
