### ISSUE TITLE
Hiding a page on grav

### ISSUE THREAD

**Issue by zagwalker** [getgrav/grav#2607]
Hi,

Wondering if there is any option of hiding a page rather than deleting it. If I could set something like:
```
access:
    status:hidden
```
It would be awesome!

Any idea how I can hide a page rather than deleting it?

Regards,
Lev

**Comment by paulhibbitts** [comment]
Hi @zagwalker , you could set the page to be unpublished: https://learn.getgrav.org/16/content/headers#published

You can also hide a page from menu navigation but still have the URL accessible using the visible option: https://learn.getgrav.org/16/content/headers#visible

BTW, for these type of questions about using Grav the Grav Forum (https://discourse.getgrav.org/) Discord chat room (https://getgrav.org/discord) would likely be your best avenues to do so.

**Comment by zagwalker** [comment]
Thanks a lot Paul!
