### ISSUE TITLE
[add-resource] New Plugin: Google Analytics (gtag.js)

### ISSUE THREAD

**Issue by cworreschk** [getgrav/grav#2609]
I would like to add my new plugin to the Grav Repository.

While the GA plugin of @escopecz and me uses the old Universal Analytics (analytics.js) library,  this plugin uses the global site tag (gtag.js) framework and API for sending data to Google Analytics.

Additionaly it supports Grav 1.6 and the following features:

- Disable Google Analytics for different IP addresses
- [Rename the global gtag() object](https://developers.google.com/analytics/devguides/collection/gtagjs/renaming-the-gtag-object)
- [Disable Analytics for opted-out users](https://developers.google.com/analytics/devguides/collection/gtagjs/user-opt-out)
- [Disable advertising features](https://developers.google.com/analytics/devguides/collection/gtagjs/display-features)
- [IP anonymization](https://developers.google.com/analytics/devguides/collection/gtagjs/ip-anonymization)
- [Configure cookie settings](https://developers.google.com/analytics/devguides/collection/gtagjs/cookies-user-id)
- [Do Not Track (DNT) support](https://allaboutdnt.com) 
- Supported Languages: `EN`,`DE`

---

The project details are here: **[cworreschk/grav-plugin-google-analytics](https://github.com/cworreschk/grav-plugin-google-analytics/tree/master)**

**Comment by rhukster** [comment]
Added to GPM

**Comment by escopecz** [comment]
@cworreschk if this is a replacement of https://github.com/escopecz/grav-ganalytics and both plugins have feature parity, do you want to add a note to the readme of the legacy plugin that there is a newer option that should be preferred?

@rhukster is there a process for sunsetting a plugin gracefully?

**Comment by cworreschk** [comment]
@escopecz I don't think it's a full replacement of our old plugin. There are many people who still use the `analytics.js` library. 

But we can add a note like I mentioned  https://github.com/escopecz/grav-ganalytics in this plugin.
