### ISSUE TITLE
Updating grav core deletes backups

### ISSUE THREAD

**Issue by wepawetmose** [getgrav/grav#261]
If grav/backup contains some backup.zip files, then by updating grav core this folder gets cleared.

**Comment by flaviocopes** [comment]
Replicated. Upgrading Grav probably shouldn't touch the backups folder

**Comment by w00fz** [comment]
This is now fixed. Was an issue with our builder not excluding the `backup` folder, ever since we forced the [folder presence in the repository via `.gitkeep`](https://github.com/getgrav/grav/tree/develop/backup).

I also updated the `update` package for v0.9.37 without the `backup` folder in it.
