### ISSUE TITLE
[add-resource] New Skeleton - Open Presentation Hub 📺

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#2611]
I would like to add this new skeleton package to the Grav Repository, which uses the Bootstrap4 Open Matter theme and Ole Vik's Presentation plugin.

Here are the project details: https://github.com/hibbitts-design/grav-skeleton-open-matter-presentation-hub

Thanks very much,
Paul

**Comment by rhukster** [comment]
Added to GPM

**Comment by paulhibbitts** [comment]
Thanks very much Andy!
