### ISSUE TITLE
[change-resource] Take over getgrav/grav-learn

### ISSUE THREAD

**Issue by newbthenewbd** [getgrav/grav#2612]
I would like to take over an existing resource, as I had not received a response to my pull request within the timeframe of 30 days.
Here are the project details: **[getgrav/grav-learn](https://github.com/getgrav/grav-learn)**
Here is the relevant pull request: **getgrav/grav-learn#720**

<sub>Yes, the above is sarcasm. But isn't it an actual irony that the present methods of Grav documentation management manage to keep the maintainers overworked and the documentation leaving a lot to be desired, at the same time?</sub>

**Comment by rhukster** [comment]
I'm on vacation and will attempt to catch up next week when I'm back.  If you would like to offer some solutions I'm all ears.  Really we need some committed volunteers to bolster things like documentation and support, but most people prefer to just take without realizing how much work is involved and don't really like to give their own time to help... c'est la vie.

**Comment by newbthenewbd** [comment]
Of course, to make my critique more constructive, I'd like to propose the implementation of a solution to the problem that I believe the aforementioned pull request to expose.

Instead of having people submit pull requests which are then subject to review by the documentation maintainers, I believe that contributors to the documentation could be recruited by the maintainers among the users of the official Grav Discord Chat, and given write rights to the repository, akin to a wiki. Because of the nature of Git, I believe that it is possible to do this in a way that does not risk the loss of data through vandalism, and the Grav Discord Chat itself could be used to maintain some sort of communication with the contributors.

Sincere apologies for intruding on Your vacation time, I really haven't meant to make it that way; rather, I hoped that the issue could perhaps become a medium for those concerned about the documentation to discuss possible improvements to the way it is managed, certainly not to overwork the great Grav Team even more than it currently is.

Thank You!

**Comment by rhukster** [comment]
There needs to be some oversight and review for these things to ensure quality, and that means that people who have this review and approval permission need to be qualified enough to know if a contribution is accurate and improves things.  And to do that approval, you still need to have some kind of submission/review/approval process.  This is something that PR's are designed to do.  So the mechanism is probably already as good as we can get, we just need to increase the team, and also perhaps put some more structure in place to ensure timely reviews and communication. 

I'm thinking that we need multiple 'teams', kind of how other projects do things. Each team would have a team lead, and team members. So a documentation team would be needed to be put together.

**Comment by newbthenewbd** [comment]
The problem that I see with sparse teams of experts in relation to documentation is that an amount of certain quality improvements involves very minor changes, not dissimilar to the one in my pull request. Through multiple psychological effects, requiring people who find such issues to create pull requests and stay responsible for them while waiting an indefinite amount of time for them to get merged not only slows down the progress that might have otherwise been made to other, unrelated areas of the documentation, it also makes it significantly less likely that such issues get reported at all. People who mostly focus on these kinds of improvements, including myself, wouldn't also be willing to join a regular team, as they might very well not find anything worthwhile to fix for a large amount of time, making for the belief that they are perceived as unproductive.

In contrast, when everything that the previously recruited, "irregular" contributors have to do boils down to pressing _Edit_, fixing a typo/discrepancy/bad formatting they have found, writing a short description of the changes and finally pressing _Save_, such psychological effects tend to not arise, and if the changes are actually incorrect, it is very likely that the same contributors who have made the changes notice the problem shortly thereafter, and, propelled by the guilt, quickly revert them. Admittedly, the wiki-alike solution would thus contribute to the commit bloat, however I think that the quality of the resulting content might actually end up higher. As for the quality of form, rather than the content, that problem could be mitigated by the recruiters - it should not be very hard to rate the written language proficiency of an individual applying for write access.

Another method to mitigate the aforementioned slowdowns might be to create a dedicated channel on the Grav Discord Chat, where people would solely point out minor quirks in the documentation, in a write-and-forget fashion, for the documentation maintainers to review. This idea, while I think that it could work, I am much less confident about, as it could ultimately increase the pressure put on the documentation maintainers, not only further removing some of the peace from their lives, but also affecting the quality of new, significant content to be put into the documentation.

But for now, please have some enjoyable time on the vacation, managing people is a complex thing, too complex for a well-deserved time of rest, really. :slightly_smiling_face: Thank You again!

**Comment by jeremycherfas** [comment]
@newbthenewbd Perhaps this is impractical, but would it be possible to fork the documentation, operate that as you suggest and then have the official documentation maintainers review a bunch of changes at once for incorporation?

**Comment by newbthenewbd** [comment]
Certainly an interesting idea. With some clever javascripts, it should be possible to make a website for such a fork that mimics Grav Learn, but recruits contributors at a different pace. With the use of something like https://github.com/wei/pull, the fork could also most of the time be automatically synchronized with the upstream.

The only possible problem that I currently see with such a concept is that the upstream maintainers may not be keen to merge pull requests featuring many diverse changes, even if each of the changes was briefly described (using data taken from the commit messages, with some minimal moderation to get rid of reverts, perhaps).

Some of that problem could be mitigated by creating a pull request to the upstream as the very first diverse commit is submitted to the fork, favorably with the use of another GitHub bot that would append the commit messages the pull request's description, while still allowing a human to modify that description, in order to occasionally clean it of reverts. A pull request like that could then be squashed and merged at a time chosen by the official documentation team, with the requests for changes fulfilled by the fork's contributors. After the pull request gets merged, the cycle would repeat.

I will further look into setting up the initial infrastructure for that, and if it indeed doesn't present currently unseen challenges, it would be nice to get the input of the Grav Team on this matter.

Thank You for the inspiration!

**Comment by rhukster** [comment]
Some interesting ideas, but I would mention that many smaller PRs are much simpler to merge than less large ones.  As @newbthenewbd points out, a single invalid or poorly worded sentence would mean the PR could not be merged until addressed.  This means more back and forth and more delay.  Also, it means more to review and therefore, we would probably put those off longer because they require more thought and therefore more time on our part.

If I see a quick 'fix', I often just approve it quickly.  It's just lately I've been swamped with client work, then I went on vacation, so I've not looked at anything small or large.  I'm slowly catching up on my backlog though.
