### ISSUE TITLE
Removing all metadata results in default values being added again

### ISSUE THREAD

**Issue by ulab** [getgrav/grav#2616]
I have tried to empty / remove all Admin / Site metadata fields resulting in the default `description: My Grav Site` being added  again.

**Comment by rhukster** [comment]
That's because it's in the default `system/config/site.yaml`, so it's picking that up. You need to put something in this field or that default will get used.

**Comment by ulab** [comment]
Other have suggested to write a `0` in there to remove the description meta tag in generated pages. Which seems to be a workaround unless you don't want to change system/config/site.yaml

**Comment by mahagr** [comment]
There was a bug with empty values being removed on save, this has now been fixed for upcoming versions.
