### ISSUE TITLE
Information on the page having issues in the Error Tracker

### ISSUE THREAD

**Issue by MrRhub** [getgrav/grav#262]
Add the name (path?) of the page having an issue in the Error Tracker.

For example, having 600 pages, I can't get which page is having issues when looking at this Error Report:

http://i.imgur.com/xpxH69C.png
http://i.imgur.com/qASafsRh.jpg

Thank you very much for you great work!

**Comment by rhukster** [comment]
Sounds like a great addition.  Definitely going to look at adding this soon.  Thanks!

**Comment by MrRhub** [comment]
On another similar note, somehow, would it be possible to don't crash the whole website when only one (not essential) variable is messed in one header. When I mean not essential, I mean all the variables that are set by the user and no the system itself to work (the one you put).

For example, if two-points ( : ) are not put after a variable. I know that as you're parsing the header it might be difficult to avoid those kind of "skipping issues alternatives" but it's quite annoying when a whole website is down because of a small mistake in one of the pages (not even the one we are trying to reach).

**Comment by rhukster** [comment]
I understand what your saying, but if we 'skipped' this page because there was an error with it, how would you really know that there was a problem with it?  We could of course log the error, but if you didn't check your logs you wouldn't see that.  

The main problem is that if the header is effectively corrupted, we cannot parse it.  If we cannot parse it, we can't load anything related to the page because the header sets the page up.  If we can't load the page at all, we can't display a message about it even in the admin.  

Really the only option is to skip the page, and log the error.  Your site would continue to work, but you could be left with wandering why your page is not displaying.

**Comment by MrRhub** [comment]
What about this solution:

If someone tries to actually reach this famous page (with the problem), he is redirected to a specific error page. If the person wants to see the home page but it's the contact page which has a problem in the header, he doesn't really care that he has no error message to say it - because he doesn't want this page anyway :)

**Comment by rhukster** [comment]
Hmm.. I can't do that, but it does give me an idea.  When there is an error with the header data, it might be possible to set some standard 'error' type header values for the page.. so the page will exist, and have  some very basic info (like title: slug) and content containing error message about the failed parsing of the header.

The page will probably look very broken, but at least it wont break the whole site, and you would get valuable information as to what happened when you visit the site. 

Sound like a solution?

**Comment by MrRhub** [comment]
Sounds like a good idea. I see that a bit like an error page in fact, as you've got an error message when you try to reach this particular page :)

It works for me then!

**Comment by rhukster** [comment]
![02 visible-page grav2 2015-08-14 16-18-21](https://cloud.githubusercontent.com/assets/1084697/9285161/272c9b74-42a0-11e5-8ab3-497c3f65d570.png)

This is with invalid YAML that would of thrown the whole site into fits..

**Comment by rhukster** [comment]
I've improved it!

![visible-page grav2 2015-08-14 22-52-28](https://cloud.githubusercontent.com/assets/1084697/9287542/3bfb8c72-42d7-11e5-9dc0-5e49480560b3.png)

**Comment by MrRhub** [comment]
Rhukster. You're awesome!
