### ISSUE TITLE
Add support for symbolic link in backup

### ISSUE THREAD

**Issue by X-Ryl669** [getgrav/grav#2623]
When Grav is doing a backup, it names the backup archive with some *random* timestamp that makes it hard to locate. I would be very useful if it created a symbolic link `lastestBackup.zip` pointing to the latest backup.

That way, I can have a cronjob running on some other server and only fetching this "file" (via scp for example) without needing some logic to figure out what's the lastest backup in the directory.

Thanks, grav is a wonderful software.

**Comment by rhukster** [comment]
Actually it's very easy to find the last one with `ls -latr` (or equiv) to sort the files based on timestamp.

**Comment by X-Ryl669** [comment]
With `scp` from my home server ?
I'd like to automate the copying of the last backup home. I don't want to get all backups home, just the last one. I don't want the public server to have account on my home server, but the opposite (safer), so running a local command is complex, because it would mean ssh + result parsing. 

It's much easier with a symbolic link on the server side, so no script are required anywhere just a simple `scp account@server:/var/www/grav/backup/latest.zip mySiteBackup/`

**Comment by rhukster** [comment]
It caan be done with SCP directly: https://unix.stackexchange.com/questions/82459/how-to-download-the-latest-file-in-a-folder-using-a-scp

**Comment by X-Ryl669** [comment]
No, it can't. The command you've linked need to set up a SSH account with bash access on the server and run a SSH command on it. IMHO, it's much easier to have the backup code adding a link to avoid running a script.

**Comment by rhukster** [comment]
Something this specific is just not going to be added to the core.  Different platforms handle symbolic links differently, and if we add support for other filesystems, symlinks might not be supported at all.

I suggest creating (or hiring a dev to create) a simple plugin that uses the `onBackupFinished` event to do add this kind of functionality as part of the backup process.  That way it's only going to be done for those that need it. I think it would only take a max of 2 hours to develop.

**Comment by X-Ryl669** [comment]
Sure, it's like adding in grav/system/src/Grav/Common/Backup/Backups.php (201):

```
+ $linkName = $destination = static::$backup_dir . DS . "LATEST.zip";
+ symlink($destination, $linkName);
Grav::instance()->fireEvent('onBackupFinished', new Event(['backup' => $destination]));
```

About making a plugin, I'll probably do this, yet that the backup finished event does not contain all path information (`$backup_dir` nor `DS`) but the complete destination name. It's ok as long as the format of the filename does not change (say, one wants to store backup in `year/month/day.zip`, and it'll break).

**Comment by X-Ryl669** [comment]
Ok, I've written the plugin, it's here: https://github.com/X-Ryl669/grav-plugin-consistent-backup-name/
Can you add it to the GPM repository ? (And close the issue when done ?)

Thanks!

**Comment by rhukster** [comment]
Added to GPM
