### ISSUE TITLE
Grav Will Not Update to 1.6

### ISSUE THREAD

**Issue by Nick-Henkey** [getgrav/grav#2625]
Grav will not update and continues to give me the following error:
![Screenshot at 2019-08-13 22-42-23](https://user-images.githubusercontent.com/54094314/62997382-e8773900-be1c-11e9-89a0-5b2d720f3e78.png)

This continues to show up, no matter which version of PHP (7.1 and 7.2 attempted) is installed on the server
![Screenshot at 2019-08-13 22-52-53](https://user-images.githubusercontent.com/54094314/62997543-8d921180-be1d-11e9-9126-fdf59983a099.png)

I found the file `index.php` that says `$ver = PHP_VERSION` that appears to have a related call to the one that is throwing an error. How do I get this call to pull the correct PHP information so I can complete the upgrade?

**Comment by mahagr** [comment]
Looks like your server is still using the old version of PHP; you need to change your server configuration to use PHP 7.2.

**Comment by rhukster** [comment]
Just because the terminal shows php 7.2 doesn’t mean the web server is using that version.  Check the config -> info tab or turn on debugger to see what version you are running in the server.

**Comment by Nick-Henkey** [comment]
Thank you @mahagr for pointing me in the right direction & @rhukster to show me where Grav tracks the information. Finally got PHP fully upgraded!
