### ISSUE TITLE
update to 1.6.12 breaks admin

### ISSUE THREAD

**Issue by mfilkov** [getgrav/grav#2627]
On WSL (Windows 10-1903 / Ubuntu 18.04.3 LTS) after update to GRAV 1.6.12 & Admin 1.9.8 I get "Fetch Failed:" on all Admin pages and in the console:

`PHP Warning:  require(/index.php): failed to open stream: No such file or directory in /path-to-grav/system/router.php on line 38`
`PHP Fatal error:  require(): Failed opening required '/index.php' (include_path='.:/usr/share/php') in /path-to-grav/system/router.php on line 38`

All works fine when I revert the changes to system/router.php, so it should be related to the new GRAV_BASEDIR system variable.

**Comment by rhukster** [comment]
Hmm.. what if you change line 23 in `system/router.php` to this:

```
$grav_basedir = getenv('GRAV_BASEDIR');
```

**Comment by rhukster** [comment]
Are you setting  `GRAV_BASEDIR` ?

**Comment by rhukster** [comment]
Actually think i found the bug, please try this for `router.php`:

```php
<?php

/**
 * @package    Grav\Core
 *
 * @copyright  Copyright (C) 2015 - 2019 Trilby Media, LLC. All rights reserved.
 * @license    MIT License; see LICENSE file for details.
 */

if (PHP_SAPI !== 'cli-server') {
    die('This script cannot be run from browser. Run it from a CLI.');
}

$_SERVER['PHP_CLI_ROUTER'] = true;

if (is_file($_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . $_SERVER['SCRIPT_NAME'])) {
    return false;
}

$grav_index = 'index.php';

/* Check the GRAV_BASEDIR environment variable and use if set */
if ($grav_basedir = getenv('GRAV_BASEDIR') ?: '') {
    $grav_index = ltrim($grav_basedir, '/') . DIRECTORY_SEPARATOR . $grav_index;
    $grav_basedir = DIRECTORY_SEPARATOR . trim($grav_basedir, DIRECTORY_SEPARATOR);
    define('GRAV_ROOT', str_replace(DIRECTORY_SEPARATOR, '/', getcwd()) . $grav_basedir);
}

$_SERVER = array_merge($_SERVER, $_ENV);
$_SERVER['SCRIPT_FILENAME'] = $_SERVER['DOCUMENT_ROOT'] . $grav_basedir .DIRECTORY_SEPARATOR . 'index.php';
$_SERVER['SCRIPT_NAME'] = $grav_basedir . DIRECTORY_SEPARATOR . 'index.php';
$_SERVER['PHP_SELF'] = $grav_basedir . DIRECTORY_SEPARATOR . 'index.php';

error_log(sprintf('%s:%d [%d]: %s', $_SERVER['REMOTE_ADDR'], $_SERVER['REMOTE_PORT'], http_response_code(), $_SERVER['REQUEST_URI']), 4);

require $grav_index;
```

**Comment by mfilkov** [comment]
Yep, that does it, not even a warning in sight :) Thank you!

**Comment by MichaelJDavies** [comment]
@rhukster I still seem to be getting this issue after trying your fix. Any advice?

**Comment by mahagr** [comment]
@MichaelJDavies Please upgrade Grav to 1.6.13. :)
