### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by pikim** [getgrav/grav#2628]
I would like to add an updated plugin to the Grav Repository.
Here are the project details: **https://github.com/pikim/grav-plugin-events**

**Comment by rhukster** [comment]
There is already a plugin called "Events" (which you forked), so please rename your plugin to something more unique.  Thanks!

**Comment by pikim** [comment]
I thought you'd replace the existing one with the new one. The original author was inactive for almost 3 years and has archived his repository, so I don't think he will contribute any more.

**Comment by rhukster** [comment]
In that case, please follow this guide: https://learn.getgrav.org/16/advanced/grav-development#abandoned-resource-protocol

We just want to make sure that we go through the process... 

cheers!

**Comment by pikim** [comment]
I had a look at the protocol, but unfortunately I can neither create a pull request nor a new issue as the repository is archived.

Therefore I wrote an email to the original author on August 22nd and there was no response, yet. Unfortunately I cannot provide a link to this correspondence then, but I could forward my email to you if desired. Is this also valid if we wait until 30 days have passed?

**Comment by rhukster** [comment]
Fair enough, if you are taking it over and fixing stuff, i'm cool with that.

**Comment by rhukster** [comment]
Added to GPM for next update

**Comment by pikim** [comment]
There was absolutely no response from the original author since August 22nd. I think he has moved on and uses another CMS now. His latest commits point in that direction.
