### ISSUE TITLE
collection by taxonomy not working

### ISSUE THREAD

**Issue by janmichaelr** [getgrav/grav#263]
hi, i can't seem to make a list of blog entries using collection by taxonomy. 
i have already done:
- blog.md file has values: content:   items: '@taxonomy.category: blog'
- site.yaml is set to taxonomies: [category]
- blog item.md has taxonomy:   category: blog

I get empty result on the page.

Can someone please help me on this?
Thanks.

**Comment by flaviocopes** [comment]
Make sure you use the correct indentation, like explained here: http://learn.getgrav.org/content/headers#collection-by-taxonomy

GitHub issues are for Grav issues - next time please post help requests on the forum http://getgrav.org/forum, thanks
