### ISSUE TITLE
Grav v1.7.0-beta.5 - Admin v1.10.0-beta.5 — taxonomies stop working

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav#2633]
As an example — if I install the latest Blog skeleton [https://getgrav.org/download/skeletons/blog-site/2.0.0](url) and attempt to run it with testing versions of GRAV (ie v1.7.0-beta.5) , clicking on a tag such as 'travel' in the sidebar or foot of a post item brings up a dead page — ie zero content, no error messages but no content either...

**Comment by MattAppleton** [comment]
reverting to a stable release solves the issue.

**Comment by rhukster** [comment]
Seems @mahagr accidentally removed this url taxonomy logic in 1.7 when he was refactoring.  He's going to look at it...

**Comment by MattAppleton** [comment]
thanks!
