### ISSUE TITLE
Markdown function wrongly expects at least 2 parameters. Easy fix!

### ISSUE THREAD

**Issue by eulores** [getgrav/grav#2635]
I believe the parameters in the function header have to be switched around.

**Wrong**:
```php
public function markdownFunction($context = false, $string, $block = true)
```
**Better**:
```php
public function markdownFunction($string, $block = true, $context = false)
```
### Simple testcase
This twig code fragment throws an error:
```twig
{% markdown *}
**bold?**
{% endmarkdown %}
```
https://github.com/getgrav/grav/blob/ed87faad92829b4218f91a3c81990f1fad23a7f5/system/src/Grav/Common/Twig/TwigExtension.php#L619

**Comment by mahagr** [comment]
That is not markdown function but a twig tag issue.

**Comment by mahagr** [comment]
Issue was introduced 10.8.2019 in revision 618a59921a1c4b54fdcf22ccffbc11aace912701.

**Comment by rhukster** [comment]
Fixed in latest release
