### ISSUE TITLE
Markdown extra fail to parse markdown inside html

### ISSUE THREAD

**Issue by VincentFericelli** [getgrav/grav#2636]
In grav 1.6.12 with markdown extra enabled (other features work), the content of a html div is not rendered as markdown but as plain text.

**Comment by rhukster** [comment]
Did you use the proper syntax per: https://michelf.ca/projects/php-markdown/extra/#markdown-attr

```html
<div markdown="1">
This is *true* markdown text.
</div>
```

**Comment by VincentFericelli** [comment]
Sorry I missed the markdown="1"
