### ISSUE TITLE
Suggestion - Change readme.md link to Requirements

### ISSUE THREAD

**Issue by MrSchism** [getgrav/grav#264]
My friend and I had an issue when installing (I even opened a ticket).  I realized that the reason why I missed the PHP requirements was that the link in the MD skips straight to installation.

By following a user's path, it would make more sense to direct the link to Requirements, not Installation.  It might also be worth linking the "PHP 5.4 or higher requirement to the PHP section to make them easier to find.  Alternatively, it might be worth adding a link to a comment next to the PHP notice saying "(required plugins)".

**Comment by rhukster** [comment]
Valid points! I will endeavor to improve these documentation items.  Cheers.
