### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by jasonccox** [getgrav/grav#2649]
I would like to add my new theme to the Grav Repository.
Here are the project details: https://gitlab.com/jasonccox/grav-theme-webfolio

**Comment by rhukster** [comment]
Unfortunately grav gpm only supports github.

**Comment by jasonccox** [comment]
Okay, here you are then: https://github.com/jasonccox/grav-theme-webfolio

**Comment by rhukster** [comment]
Added to GPM, should show up in 30 mins or so
