### ISSUE TITLE
Bug in "X" (Delete Page)

### ISSUE THREAD

**Issue by umbergerba** [getgrav/grav#265]
Currently, when I visit the list of pages and expand the sub-pages under blog, if I click the "X" to delete a page it will refresh to a new blank page with "Create 'Taskdelete" as the page header.

However, if I visit the page and click the "Delete" button at the top it work fine.

**Comment by dawidxt** [comment]
This issue was already reported, and it is fixed by now. The fix will be released with the new version of admin plugin *38.

**Comment by umbergerba** [comment]
Perfect!

**Comment by umbergerba** [comment]
Broken again with latest Grav Update RC5.
