### ISSUE TITLE
Fetch failed while updating plugin or theme

### ISSUE THREAD

**Issue by UnkwnUsr** [getgrav/grav#2651]
Hello,

everytime i try to update a plugin or theme through the grav.admin webinterface i get an error. It says something like "{"status":"success","dependencies":[]}".

![image](https://user-images.githubusercontent.com/54507384/63652947-f30fc780-c766-11e9-8a43-dfd87b73e838.png)

is there a fix for this issue?

**Comment by UnkwnUsr** [comment]
![image](https://user-images.githubusercontent.com/54507384/63653071-50584880-c768-11e9-99c9-57764cc688d9.png)

**Comment by rhukster** [comment]
Are you able to update from the terminal and not admin?
