### ISSUE TITLE
duplicate items in sidebar

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav#2656]
Looks like the Admin Panel 1.10.0 beta 7 doesn't crash anymore, but one of the other side effects still remains. 
The left sidebar in the Dashboard still repeats items: 

![grav-admin-panel_1-10-0-beta-7_repeat-items](https://user-images.githubusercontent.com/11002590/64049643-55cbdf00-cb2a-11e9-99f7-14a2997356b0.png)

You'll notice the first 3 items are repeated, and then Plugins and the 2 following items are also repeated.

_Originally posted by @SteveBaumann in https://github.com/getgrav/grav/issues/2653#issuecomment-526739572_

**Comment by mahagr** [comment]
Is there a template override as the menu file was updated with all the fixed menu items removed?

**Comment by mahagr** [comment]
File looks good:
https://github.com/getgrav/grav-plugin-admin/blob/1.10/themes/grav/templates/partials/nav.html.twig

**Comment by rhukster** [comment]
I'm not able to reproduce this.  Is it related to a plugin you are using?

**Comment by SteveBaumann** [comment]
I suppose it could be. But everything on the left sidebar was fine until that wonky update was installed. 
I'll trying backing up, then doing a fresh install of 1.7 beta 7, and then put things back in 1 at a time, to see what I get. Thanks.

**Comment by SteveBaumann** [comment]
I've now got it narrowed down to Admin Power Tools or one of its dependencies. 
Aside from the base plugins that come with the Grav + Admin install, it was the first plugin I copied back in, and then did the update, and right after that I had the duplicate items in the left sidebar again.

**Comment by SteveBaumann** [comment]
That's confirmed. 
One both Admin Power Tools and Core Service Manger were gone, and the sidebar was back to normal, I went back to plugins and installed Core Service Manager v1.0.18, and immediately the duplicate items were back in the left sidebar.

**Comment by rhukster** [comment]
Admin Power Tools has had some issues since Grav 1.6.  It kinda takes over and replaces functionality in the Admin to get it's 'power tools' name.  Unfortunately, that means when we update Admin, it often breaks.  I suggest creating an issue here: https://github.com/Flamenco/admin-power-tools
