### ISSUE TITLE
XSS: Stored XSS due to Javascript execution in SVG files

### ISSUE THREAD

**Issue by ebelties** [getgrav/grav#2657]
Hello,

I found that when uploading a new avatar, you can upload a **SVG**-file, which can contain Javascript (which gets executed upon visit).

I've attached a **SVG**-file which can be used to reproduce the issue.

If more information is needed, I can provide that.

Kind regards,
@ebelties

[grav-symbol.zip](https://github.com/getgrav/grav/files/3562445/grav-symbol.zip)

**Comment by rhukster** [comment]
I'm assuming you mean avatar in admin panel? This is a known issue with SVGs, and it generally comes down to options:

1. Just don't allow SVGs.  I think this is a harsh solution as SVGs are simply the best way to display vectors in browsers.

2. Sanitize the SVGs to remove any harmful HTML.  This is probably the best solution.  I've wanted to look at doing this for a while, but this a pretty low-impact XSS issue (being that it's in admin panel, and being that it's your own avatar and currently not displayed to anyone else).  However, it does need looking at when I have some time.

**Comment by rhukster** [comment]
For future reference here is a sample SVG cleaning library: https://github.com/anseki/htmlclean

**Comment by rhukster** [comment]
OK, for Grav 1.7.0-beta.8, Admin 1.10.0-beta.8, and Form 4.0.0-rc.5 I've added an SVG sanitize method for uploads in Admin + Form file fields.  This is on by default, but can be disabled in security config.
