### ISSUE TITLE
[add-resource] New Translator Plugin

### ISSUE THREAD

**Issue by ricardo118** [getgrav/grav#2658]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **[https://github.com/ricardo118/grav-plugin-translator](https://github.com/ricardo118/grav-plugin-translator)**

![screnshot](https://raw.githubusercontent.com/ricardo118/grav-plugin-translator/develop/screenshot.png)

**Comment by rhukster** [comment]
Added to GPM for next update (sorry was so long!)
