### ISSUE TITLE
Cannot Delete "Features"

### ISSUE THREAD

**Issue by umbergerba** [getgrav/grav#266]
Currently, under the "Features" modular sub-pages, the features cannot be removed; they can be edited and saved, but if any are deleted, they return after save.

**Comment by rhukster** [comment]
I'm guessing this was intended for the admin plugin repo? https://github.com/getgrav/grav-plugin-admin/issues

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-admin/issues/79
