### ISSUE TITLE
Migrate from Wordpress with both in parallel

### ISSUE THREAD

**Issue by h1ps** [getgrav/grav#2661]
Hi everybody,

I'd like to migrate from wordpress to grav.

In the beginning it will be a parallel installation. 
Only the start page and two subpages should be created in Grav. All other Wordpress pages will be created in Grav later, but should still be available. 

What is the best solution to achieve this dual usage?

Many thanks in advance,
h1ps

**Comment by rhukster** [comment]
You will probably have better luck asking this question in our discord chat: https://getgrav.org/discord

The GitHub issues are primarily for bugs or features.
