### ISSUE TITLE
Grav v1.7.0-beta.7 - Admin v1.10.0-beta.7 - Outline Assignments: Pages no longer listed, only Page Types 

### ISSUE THREAD

**Issue by withindale** [getgrav/grav#2662]
The Gantry layout Assignments tab no longer lists Pages above Page Types.  While possible to edit the assignments.yaml files, the red/green toggles on the Page list confirms status. This is very useful with hundreds of pages. Is this code or setting?

**Comment by marcodeluca** [comment]
Is there an update or maybe a suggestion to patch/fix this? Not being able to assign outlines to specific pages makes gantry unusable for people who rely on the admin to manage a grav website with gantry templates.

**Comment by mahagr** [comment]
It's actually fixed in CI build of Gantry already. There have been couple of issues about this, I must have missed this one.
