### ISSUE TITLE
FormTrait setting error "Badly encoded JSON data (for avatar) was sent to the form`

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav#2663]
When uploading an avatar in a registration form, I was receiving an extra error message (even though avatar is uploaded fine):

<img width="609" alt="monosnap-2019-09-06-15-01-21 image" src="https://user-images.githubusercontent.com/1084697/64460283-3ea36900-d0b7-11e9-825a-cf247d346cbb.png">

**Comment by rhukster** [comment]
Seems it happens in 1.6 also

**Comment by mahagr** [comment]
This is why it fails:

`data[_json][avatar]: +`

That is a badly encoded JSON string.
