### ISSUE TITLE
CBRcurrency (plugin)

### ISSUE THREAD

**Issue by reqweb** [getgrav/grav#2669]
I would like to add my new plugin to the Grav Repository.
Here are the project details: [CBRcurrency](https://github.com/reqweb/CBRcurrency)

**Comment by rhukster** [comment]
I've added this to GPM, but it won't show up until you do a proper release.  Please follow the guidlines here: https://learn.getgrav.org/16/advanced/grav-development#theme-plugin-release-process

**Comment by reqweb** [comment]
The problem is in the file README.md ?Am I right?03.10.2019, 23:49, "Andy Miller" <notifications@github.com>:Closed #2669.

**Comment by reqweb** [comment]
The problem in the readme file.md? Do I understand correctly?

**Comment by rhukster** [comment]
You need all those steps completed.  

* License
* README.md
* CHANGELOG.md
* blueprints.yaml

THen you ned to perform a GitHub release: https://help.github.com/articles/creating-releases

**Comment by reqweb** [comment]
done
