### ISSUE TITLE
Using grav as a member site

### ISSUE THREAD

**Issue by love-decay** [getgrav/grav#267]
I am thinking of using grav as a member site. Can anyone tell me how I can go about this. Members will not be able to post only comment or like stuff and if possible have a history of pages they have read and commented or liked.

thanks for your input

**Comment by rhukster** [comment]
Anything is possible, and although it can be done technically, it's a fair bit of custom work that would need to be done in a plugin.  If you are a competent php developer, then this is doable.  If you are not you will probably need to hire someone who is.  You might be able to find such a person on our 300+ strong gitter.im chat room: https://gitter.im/getgrav/grav
