### ISSUE TITLE
Footnotes and toc

### ISSUE THREAD

**Issue by carstenwm** [getgrav/grav#2675]
Any chance of Footnotes and table of content [toc] to be implenented?

**Comment by jeremycherfas** [comment]
I get footnotes through Markdown Extra.

**Comment by OleVik** [comment]
There's at least two plugins for generating table of contents: [Page Toc](https://github.com/trilbymedia/grav-plugin-page-toc) and [Toc](https://github.com/Sommerregen/grav-plugin-toc).

**Comment by carstenwm** [comment]
Thank you, I'll take a look
