### ISSUE TITLE
[change-resource] Take over plugin grav-prism-highlight

### ISSUE THREAD

**Issue by clemdesign** [getgrav/grav#2677]
I would like to take over the existing plugin grav-prism-highlight.
Here are the project details: 

Original Repository: https://github.com/alvr/grav-prism-highlight
Pull request with no response since 2017: https://github.com/alvr/grav-prism-highlight/pull/3
Proposed repository: https://github.com/clemdesign/grav-prism-highlight

**Comment by paulhibbitts** [comment]
Hi @clemdesign , there is an actively developed version of this Plugin now at: https://github.com/trilbymedia/grav-plugin-prism-highlight

**Comment by rhukster** [comment]
Correct @paulhibbitts, Trilby already took over this and completely rebuild the plugin with shortcode capabilities too.

**Comment by clemdesign** [comment]
Ok great!

I don't know why but the version of @alvr was used after an upgrade. But now update works.

Good job and thanks !
