### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by dawidxt** [getgrav/grav#268]
Hi, it would be nice if the Grav had an maintenance mode with on/off switch inside admin plugin with custom text.

**Comment by dfrankland** [comment]
This would be great as a plugin

**Comment by rhukster** [comment]
Yes quite doable as a plugin I think.  I think it would work hand in hand with the login plugin as you probably would want to be able to browse/visit the site if you had a certain level of access.

**Comment by dawidxt** [comment]
Yeah, for me it would be nice to have just a simple maintenace mode, but of course it would be nice if You after login in to dashboard had the ability to view the site and make changes while others can't see  this.

**Comment by rhukster** [comment]
FYI i whipped up a plugin and have it mostly working.. will release it next week.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-maintenance

**Comment by dawidxt** [comment]
Nice - Thank You  :)
