### ISSUE TITLE
Error upgrading to Grav 1.7.0-beta.10

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#2681]
![error](https://user-images.githubusercontent.com/12480617/66186397-708df800-e682-11e9-955c-893d7b5d230c.png)

**Comment by nscomputing** [comment]
Just upgraded without any problem from v1.7.0-beta.9 to v1.7.0-beta.10 using Grav admin. Running on Linux and Apache. After that upgraded Admin plugin as well to v1.10.0-beta.10.

**Comment by rhukster** [comment]
Confirmed, this is a bug in all the 1.7.0 beta versions from .4 at least all the way up to .9.

**Comment by w00fz** [comment]
Fixed with #b4fa7e3

**Comment by rhukster** [comment]
1.7.0 has now been released but this will not be fixed until you have 1.7.0-rc.1 or newer **installed**.  It will need to be updated manually until that point.

After that things should work again.

**Comment by Flamenco** [comment]
@rhukster  Does **updated manually** mean apply the commited fix manually and then upgrade, or **eject everything into a new install**?

**Comment by rhukster** [comment]
Follow these steps to manually update: https://github.com/getgrav/grav/issues/2722#issuecomment-551147063
