### ISSUE TITLE
Upgrading to v1.6.16 from v1.6.15 broke installation

### ISSUE THREAD

**Issue by amirasyraf** [getgrav/grav#2683]
Hi,

I upgraded from v1.6.15 through the admin plugin, but there was a problem. I don't remember it exactly, but I think it was something like `Failed to create system/, directory not empty` or something. 

Now after refresh, I'm getting HTTP 500.

Here's my nginx error.log: 

```
2019/10/07 02:37:57 [error] 29806#29806: *973 FastCGI sent in stderr: "PHP message: PHP Warning:  require(/var/www/mywebsite.com/blog/vendor/composer/../../system/defines.php): failed to open stream: No such file or directory in /var/www/mywebsite.com/blog/vendor/composer/autoload_real.php on line 67
PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/mywebsite.com/blog/vendor/composer/../../system/defines.php' (include_path='.:/usr/share/php') in /var/www/mywebsite.com/blog/vendor/composer/autoload_real.php on line 67" while reading response header from upstream, client: xxx.xxx.xx.xx, server: blog.mywebsite.com, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "blog.mywebsite.com"
```

What can I do beside doing a full reinstall?

**Comment by rhukster** [comment]
Sounds like you had an issue due to permissions.  The quick fix is to extract the update locally and copy over the Grav installation. It doesn't include the `user/` folder but will just replace all the system files:

https://github.com/getgrav/grav/releases/download/1.6.16/grav-update-v1.6.16.zip

**Comment by amirasyraf** [comment]
That fixed it.

However, permission issue is strange, since previous updates were fine, and I haven't changed any permission to the directory. Also, it managed to delete the files when updating, which means that there was read/write access, right?

Anyway, thank you for the help.
