### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by thomasschwarz96** [getgrav/grav#2684]
I would like to add my new plugin to the Grav Repository.
Here are the project details: [thomasschwarz96/grav-plugin-simple-cookie](https://github.com/thomasschwarz96/grav-plugin-simple-cookie)

**Comment by rhukster** [comment]
Added to GPM

**Comment by rhukster** [comment]
I had to comment out simple-cookie in the GPM until you can fix your YAML:

https://raw.githubusercontent.com/thomasschwarz96/grav-plugin-simple-cookie/master/blueprints.yaml

The `description:` has to be a single line, or use the YAML multiline format:

https://yaml-multiline.info/

**Comment by thomasschwarz96** [comment]
Thanks for your reply.
I fixed it.
