### ISSUE TITLE
Add ability to ignore files in a Page folder

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#269]
It would be very helpful to be able to flag certain files within Page folders to be ignored.

For example, within the folder "02.schedule" to be able add a "README.md" file for display within GitHub but have that file ignored by Grav and just have the usual Page.md file be rendered.

Thanks for considering this feature.

**Comment by miljan-aleksic** [comment]
+1 Not jus individual files, but entire folders as well.

**Comment by flaviocopes** [comment]
It's an Admin plugin thing, but I'll reply here: I'd implement this by adding a `ignore` property to admin.yaml. 

You can exclude entire folders, and it would work for root folders (e.g. adding ignore: ['ignore-this'] will ignore all the folder `user/pages/ignore-this` and subfolders).

The original ticket request is actually solved by renaming the README.md to another markdown-recognised extension (.markdown for example), so I'd limit ignoring to folders.

**Comment by rhukster** [comment]
I have added a system-wide ability to ignore certain files.. Useful for hidden files or other files that you don't want to track. Folders also, and more useful as those could be hidden subfolders for IDEs or source control systems.

**Comment by flaviocopes** [comment]
:+1:

**Comment by paulhibbitts** [comment]
Excellent, thank you!

**Comment by aoloe** [comment]
since the link to the commit by @rhukster is missing here:

- <https://learn.getgrav.org/16/basics/grav-configuration#pages>
- `ignore_files: [README.md]`
