### ISSUE TITLE
Taxonomy filters in URL affect all page.collection() queries

### ISSUE THREAD

**Issue by parkersweb** [getgrav/grav#2696]
On pages where I'm displaying a blog archive the URL has a taxonomy filter like `/category:anxiety` - but that currently makes my main menu disappear!

The main menu uses a page.collection() query and is built from `items: @root.children`

I've tried numerous variants of that query https://discourse.getgrav.org/t/ignore-taxonomy-url-filters/10349 - but they all seem to be affected by the URL taxonomy filter.

Feels like either `@root.` queries shouldn't regard taxonomy filters or there should be a `page.collection()` flag to ignore them?

**Comment by mahagr** [comment]
There is an option to disable this behaviour: `url_taxonomy_filters: false` in the collection configuration (same level as `items: ...`.

**Comment by hughbris** [comment]
Ah OK thanks. Genuinely curious: what are the practical applications of this option, and is `true` the best default?

**Comment by mahagr** [comment]
The setting is controlled by system configuration, so there's really no fixed default.

This said, I don't like the approach at all, this should really be controlled by the template file.

**Comment by Genenenenaam** [comment]
@mahagr you can also disable this globaly. See Admin panel: `Configuration -> System -> Content -> URL Taxonomy Filters`

**Comment by mahagr** [comment]
It can be disabled globally, but I think that may cause some plugins to not to work anymore.

**Comment by parkersweb** [comment]
Sorry for the delay in replying - thanks guys - solved my issue perfectly. Agree with with @hughbris that when `items` is @root.children feels like an odd default - but can see how it would be confusing to have different defaults based on collection.

For now I can submit an edit to the documentation for page.collection as it doesn't seem to be covered at all there.

Thanks again!
