### ISSUE TITLE
[Contact Form]] Can’t get field label inside fieldset in email

### ISSUE THREAD

**Issue by localnetwork** [getgrav/grav#2697]
MD File -----

`title: Careers
media_order: ‘career banner.jpg’
visible: true
content:
items: ‘@self.children’
order:
by: date
dir: desc
limit: 5
pagination: true
from: asdasd
to: asdasd
pagination: true
forms:
careers-form:
classes: careers-form
fields:
test:
type: text
label: Test
name: test
main:
type: fieldset
classes: ‘col-6 left-content p0’
fields:
first:
type: fieldset
classes: inner-left-content
fields:
personal:
type: spacer
text: ‘Personal Details’
desired_position:
name: ‘Desired Position’
type: text
classes: desired-position
label: ‘Desired Position’
outerclasses: d-none
readonly: true
disabled: true
first_name:
type: text
name: ‘First Name’
placeholder: ‘First Name*’
label: false
validate:
required: true
last_name:
type: text
name: ‘Last Name’
label: false
placeholder: ‘Surname*’
validate:
required: true
email:
type: email
name: ‘Email Address’
label: false
placeholder: ‘Email Address*’
validate:
required: true
contacts:
type: spacer
text: ‘Contact Details’
address:
type: text
name: address
label: false
placeholder: ‘Address*’
city:
type: text
name: city
label: false
outerclasses: ‘col-7 pull-left city’
placeholder: ‘City*’
postal:
type: text
name: postal
label: false
outerclasses: ‘col-5 pull-right postal’
placeholder: ‘Postal Code*’
phone:
type: text
name: phone
label: false
outerclasses: ‘col-6 pull-left phone’
placeholder: Phone
mobile:
type: text
name: mobile
label: false
outerclasses: ‘col-6 pull-right mobile’
placeholder: Mobile
second:
type: fieldset
classes: ‘col-6 right-content p0’
fields:
qualifications:
type: spacer
text: Qualifications
degree:
type: text
name: degree
label: false
placeholder: ‘Do you have a degree?’
school:
type: text
name: school
label: false
placeholder: ‘Where did you complete your degree?’
title:
type: text
name: school
label: false
placeholder: ‘Title of degree?’
range:
type: text
name: range
label: false
placeholder: ‘Salary range you are looking for*’
cv.upload:
type: file
outerclasses: cv
label: ‘Upload your CV*’
destination: user/themes/sub/cvs
filesize: 10
accept:
- .pdf
- .doc
- .docx
buttons:
submit:
type: submit
value: Submit
process:
save:
fileprefix: contact-
dateformat: Ymd-His-u
extension: txt
body: ‘{% include ‘‘forms/data.txt.twig’’ %}’
email:
subject: ‘[Site Contact Form] {{ form.value.name|e }}’
body: ‘{% include ‘‘forms/data.html.twig’’ %}’
message: ‘Thank you for getting in touch!’`

Screenshot -- 

![email-label](https://user-images.githubusercontent.com/15809239/66911750-b912c180-f043-11e9-8095-b3cd28eb95d2.jpg)

**Comment by rhukster** [comment]
Ugg need me formatted correctly in code lock please :)

**Comment by localnetwork** [comment]
Hi sorry, this is fixed. I just mised something.
