### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by francodacosta** [getgrav/grav#2698]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **francodacosta/grav-plugin-rich-preview**

This was a requested plugin on discord, basically it allows you to set a thumbnail and description meta tags automatically so that shared links can be properly visualized is apps like WhatsApp

Can you please check if everything is ok ?

thanks
Nuno

**Comment by rhukster** [comment]
Added to GPM
