### ISSUE TITLE
New theme

### ISSUE THREAD

**Issue by reqweb** [getgrav/grav#2702]
I would like to add my new theme to the Grav Repository.
Here are the project details: [**reqweb/Whoami**](https://github.com/reqweb/Whoami)

**Comment by rhukster** [comment]
Added to GPM

**Comment by reqweb** [comment]
Hi! I made a new version of the theme, I updated [CHANGELOG.md](https://github.com/reqweb/Whoami/blob/master/CHANGELOG.md), but in gmp the theme is not updated. What's wrong?
