### ISSUE TITLE
onTask and onAction not fired

### ISSUE THREAD

**Issue by SeriousKen** [getgrav/grav#2706]
According to the Grav lifecycle documentation for the task processor:

    If task:
        Fire onTask event
        Fire onTask.[TASK] event
    If action:
        Fire onAction event
        Fire onAction.[ACTION] event

But in the task processor only the onTask.[TASK] and onAction.[ACTION] events are fired.

https://github.com/getgrav/grav/blob/8678f22f6bf94e0a5c862f864e5a3d06cc31dd07/system/src/Grav/Common/Processors/TasksProcessor.php#L51-L55

**Comment by rhukster** [comment]
Actually I think this is an error in the documentation.  We changed this some time ago, but never updated the docs.

**Comment by SeriousKen** [comment]
Thanks for clearing that up.
