### ISSUE TITLE
Returning HTTP status code and page in plugins

### ISSUE THREAD

**Issue by dfrankland** [getgrav/grav#271]
Is there a proper way to throw an HTTP status code page? Not just return the status code, but the page too?

If one does not output anything in their plugin Grav shows the 404 page and returns a 404 status code, but how does one return status code 403 or others with the accompanying page?

I tried using `http_response_code();` in a plugin but that still returns a 404 status code and 404 page if I don't output anything. If I `exit;` after `http_response_code();` then no page is shown, but the proper status code is returned.

**Comment by rhukster** [comment]
this 'might' be a bug.  I'm going to look into it.

**Comment by dfrankland** [comment]
I figured it out. It needs to be set using `$this->grav['page']->header()->http_response_code = 403;`. It currently can't be set using `http_response_code();` unless you `exit;` before the end of your plugin's execution.

It would probably be a good idea to document this somewhere.
