### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by bjoernbohr** [getgrav/grav#2710]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: https://github.com/bit-it/grav-facebook-feed/releases/tag/v.0.1.0

Simple Plugin to add Your Facebook Feed onto your Website

**Comment by rhukster** [comment]
This is not going to work until you put the plugin at the root of the repo: https://github.com/bit-it/grav-facebook-feed

It's currently in a subdirectory, and that won't be picked up properly.

**Comment by bjoernbohr** [comment]
alright thanks for the info. I restructured the Project.

**Comment by rhukster** [comment]
Added to GPM.  thanks.

**Comment by rhukster** [comment]
OK failed because of missing blueprints: 

```
facebook-feed (bit-it/grav-facebook-feed)...failed [getBlueprints:missing]
```

Please double check you have a valid `blueprints.yaml` in the released version

**Comment by bjoernbohr** [comment]
Would it be possible to elaborate this further? I tried it locally and online and both times the Plugin worked like a charm. No errors on saving the Blueprint or in the Frontend whatsoever.

**Comment by bjoernbohr** [comment]
Okay i renamed the Release maybe that was the Problem. here is the new Lnik 
https://github.com/bit-it/facebook-feed/releases/tag/v.0.1.0
