### ISSUE TITLE
[change-resource] Take over Plugin (External Links)?

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#2711]
With Flex Pages front-end enabled the current release of the External Links Plugin will bring down a site. I've posted an issue, and then a PR about this but no response so far:

https://github.com/Sommerregen/grav-plugin-external-links/issues/30
https://github.com/Sommerregen/grav-plugin-external-links/pull/31

I've made a new fork of this Plugin, and at least in the short-term I could update the needed PHP (tested changes locally) to make this Plugin compatible with Grav 1.7:

https://github.com/hibbitts-design/grav-plugin-external-links

Please let me know how you think it is best to proceed.

Thanks,
Paul

**Comment by rhukster** [comment]
Sounds good to me @paulhibbitts

**Comment by paulhibbitts** [comment]
Ok, then let's proceed with the change resource request @rhukster. Do I need to do anything else on my end?

Thanks very much,
Paul

**Comment by rhukster** [comment]
Updated in GPM
