### ISSUE TITLE
[add-resource] New Plugin - Photo Images Effect

### ISSUE THREAD

**Issue by jleaders** [getgrav/grav#2712]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details:  [jleaders/grav-plugin-photoimages](https://github.com/jleaders/grav-plugin-photoimages)

![photoimage](https://user-images.githubusercontent.com/2430917/67797181-ace62580-fa81-11e9-807b-02bc1504f4ec.png)

**Comment by rhukster** [comment]
Added to GPM
