### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav#2713]
**I would like to add my new theme to the Grav Repository.**
Here are the project details: **[grav-theme-hotdoy](https://github.com/hotdoy/grav-theme-hotdoy/releases/tag/v1.2.4)**

A skeleton will be released after the theme release.

I'm **hotdoy** on discord if you need to reach me quickly.

EDIT: link is updated to latest release.

**Comment by hotdoy** [comment]
Some issues with current demo domain
Check [here](https://hotdoy.org/hotdoy/) for the temp one.

**Comment by rhukster** [comment]
Added to GPM for next release
