### ISSUE TITLE
Add the ability to order tabs (and fields?) to mix custom and system tabs/fields

### ISSUE THREAD

**Issue by akoebbe** [getgrav/grav#272]
I'd like to be able to be able to take a custom tab of fields I've created and make it the second tab (after "Content") in the content edit page. Currently the tab order is controlled by the order in the yaml files. And there's no way to re-order when tabs are in different yaml files. 

![pages___admin](https://cloud.githubusercontent.com/assets/1044465/9388405/b3dbcb10-472a-11e5-82b4-f9a8e33ed5cd.png)

While not in my use case I can see others wanting the same for custom fields. That might just be gold plating though.

**Comment by fourroses666** [comment]
+1 for this.

**Comment by rhukster** [comment]
This is actually an admin plugin/forms plugin enhancement.  Closing here.

**Comment by marcelgwerder** [comment]
Did this ever happen in any of the mentioned plugins? I'm looking for the same kind of functionality.

**Comment by rhukster** [comment]
Actually it's happening.. Turns out it **is** a core Grav feature, and we have a blueprints update branch in active development that we hope to merge this week.  This should have support for ordering.  It's really the last thing we are working on.

**Comment by rhukster** [comment]
I've reopened so that it's tracked.

**Comment by mahagr** [comment]
Yeah, its handled by ordering@: content
