### ISSUE TITLE
Ability to forcefully run a cron job now

### ISSUE THREAD

**Issue by drzraf** [getgrav/grav#2720]
Traditional cron is an overlay on top of individually executable scripts.
`onSchedulerInitialized` attaches a `PHP function` to a job entry, but we have no way to simply run the PHP function independantly.

Until we get a bootstrap system (`./bin/grav exec/eval/eval-script`), it'd be handy to have a way to trigger the job manually.
In my case I've a custom json cache system and I wanted to refresh manually when doing a specific update to my code (and test/debug it).
Currently I can only wait for the cron to run it again by itself.

**Comment by rhukster** [comment]
Not a bad idea, let me see what I can do.

**Comment by rhukster** [comment]
```
$ bin/grav scheduler -r test-ls
```

where `test-ls` is a Job ID

**Comment by drzraf** [comment]
1.6 backport?

**Comment by rhukster** [comment]
1.7 release is on the near horizon...
