### ISSUE TITLE
Can't Update Grav (v1.7.0-beta.10) to v1.7.0-rc.1 Via Admin

### ISSUE THREAD

**Issue by OrthoCube** [getgrav/grav#2722]
I get the notification "Grav v1.7.0-rc.1 is now available" and upon trying to update, it says "Grav was successfully updated to v1.7.0-rc.1" but when I reload the page, the bottom part of the admin still says "v1.7.0-beta.10" and installing the plugin updates such as the Admin Panel results in "One of the packages require Grav >= 1.7.0-rc.1" so it might not be updated indeed.

I have "GPM Relases" set to "Testing", tried playing with the "Remote Fetch", "Official GPM only", "Remote Verify Peer" settings but unfortunately, to no avail.

My server does not allow access to GPM, so I can't upgrade from there.

I can download Grav from my server, update it via GPM locally, then update the files, but is there any other easier way to update?

Thanks!

**Comment by rhukster** [comment]
I'm seeing an issue but a different error:

```
Fatal error: Cannot declare class Grav\Installer\Install, because the name is already in use in /xxxx/xxxx/xxxx/grav-admin-170b10/tmp/Grav-5dc438fb75fef/zip/grav-update/system/src/Grav/Installer/install.php on line 23
```

**Comment by rhukster** [comment]
I think your issue is this: https://github.com/getgrav/grav/issues/2681

This is fixed in RC.1 but to get it you need to manually upgrade to RC.1

**Comment by rhukster** [comment]
BTW, admin again, trying with direct install, same with `Fatal error: Cannot declare class Grav\Installer\Install` error issue when using this URL: `https://getgrav.org/download/core/grav-update/1.7.0-rc.1?testing`

**Comment by rhukster** [comment]
## Steps for a manual update:

1. make sure you are at the root of your Grav installation
2. `wget -O grav170rc1.zip https://getgrav.org/download/core/grav-update/1.7.0-rc.1\?testing`
3. `bsdtar --strip-components=1 -xvf grav170rc1.zip`

We are using `bsdtar` to remove the top level folder and allow installation directly into the root.  If you don't have this command, you can easily install it (e.g. `sudo apt-get install bsdtar`), alternatively you can unzip the `grav170rc1.zip` file somewhere else and `cp` all the files and folders back into your Grav installation so they get updated.

**Comment by Flamenco** [comment]
Thanks @rhukster.  Worked like a charm.  I did not have `bsdtar` installed.  

Here were my steps.
```bash

cd your-grav-root-dir
sudo wget -O grav170rc1.zip https://getgrav.org/download/core/grav-update/1.7.0-rc.1\?testing
sudo apt install libarchive-tools
sudo bsdtar --strip-components=1 -xvf grav170rc1.zip
sudo chown -R www-data:www-data ./*
sudo rm grav170rc1.zip
```

**Comment by paulhibbitts** [comment]
I am getting the `Fatal error: Cannot declare class Grav\Installer\Install, because the name is already in use in /xxxx/xxxx/xxxx/grav-admin-170b10/tmp/Grav-5dc438fb75fef/zip/grav-update/system/src/Grav/Installer/install.php on line 23` error using MAMP on my Mac - is the new RC on GPM yet or should I wait to test again @rhukster ?

**Comment by rhukster** [comment]
See my responses above @paulhibbitts

**Comment by paulhibbitts** [comment]
Thanks @rhukster , I did but maybe I am missing something? I was assuming for Admin Update with a standard PHP config (like MAMP) I could update Grav 1.6 -> 1.7RC without going to command line to install `bsdtar`?

**Comment by rhukster** [comment]
That issue is new, and we need to resolve it...

it seems to be related to ANY update to 1.7.0-rc.1 via Admin.

**Comment by paulhibbitts** [comment]
Thanks for the clarification, please contact me on Discord etc. if I can be of any help re: testing @rhukster
