### ISSUE TITLE
Grav 1.7-rc1, can't view Pages in Admin once set to use Flex Front-end

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#2724]
I've been building test skeletons with the 1.7 Betas, and just tried to do the same with the RC1. However, while the site works I cannot seem to view the Pages page, please see below:
![2019-11-07_14-55-21 (1)](https://user-images.githubusercontent.com/1812771/68435069-607ca300-016f-11ea-8bc6-3e5645055956.gif)

I am using Mac Catalina with MAMP for my testing (as done earlier too).

Here is a ZIP of the skeleton if you would like to test locally too:
https://ln2.sync.com/dl/bf9134850/fnucj8fe-3vfxm56e-v9pbub4p-v2rgqh45

Please let me know if any more info would help etc.

Thanks very much,
Paul

**Comment by paulhibbitts** [comment]
Hi @rhukster @mahagr , just to let you know this issue looks to still be present in RC 2:

![2019-12-04_16-29-47 (1)](https://user-images.githubusercontent.com/1812771/70193366-cba88f00-16b3-11ea-90f6-867e724fffad.gif)

Here is my MAMP configuration:
<img width="1160" alt="2019-12-04_16-31-11" src="https://user-images.githubusercontent.com/1812771/70193378-d8c57e00-16b3-11ea-9002-9484934cbfb8.png">

Please let me know if I cam be of more help etc.

Thanks,
Paul

**Comment by rhukster** [comment]
That’s for front end flex only.  You have to turn the admin on in the flex plug-in.

**Comment by mahagr** [comment]
It works without enabling it in the plugin. Not sure what is going on, can you check the AJAX response?

**Comment by paulhibbitts** [comment]
Hi @mahagr , I've done some more troubleshooting. The Flex Pages Admin UI works in Firefox, but not in Chrome or Safari on my Mac.

Here is a snapshot of the Console in Safari:
<img width="994" alt="2019-12-05_08-48-05" src="https://user-images.githubusercontent.com/1812771/70255628-fa6a4800-173b-11ea-9f98-11cf290bc9d6.png">

A snapshot of the Chrome Console:
<img width="1434" alt="2019-12-05_08-45-02" src="https://user-images.githubusercontent.com/1812771/70255690-0b1abe00-173c-11ea-9827-889809f0fe49.png">

And Firefox (working):
<img width="1195" alt="2019-12-05_08-45-21" src="https://user-images.githubusercontent.com/1812771/70255732-1837ad00-173c-11ea-8a8d-9442bea74400.png">

Please let me know if any more info etc is helpful.

Thanks,
Paul

**Comment by mahagr** [comment]
@w00fz Can you check out the errors ^

**Comment by SeriousKen** [comment]
I get the same error as @paulhibbitts, but it doesn't work in any browser, including Firefox (71.0 64 bit Windows)

**Comment by w00fz** [comment]
Ooops! I could never see this issue because caused by a first initial setup for the cookies and filters. Because I already had them in place it was working fine for all of us developing it!

Now I cleared the cookies I could replicate it and quickly sort it out.

Please note this is a Flex Object issue and not Grav, see trilbymedia/grav-plugin-flex-objects#39

**Comment by paulhibbitts** [comment]
Ah, thanks so much @w00fz ! Was not quite sure where to post the issue🙂
