### ISSUE TITLE
[change-resource] Take over Plugin/Theme (form-database)

### ISSUE THREAD

**Issue by gamahachaa** [getgrav/grav#2728]
I would like to take over an existing plugin/theme.
Here are the project details: 
**form-database**
https://github.com/scan5415/grav-plugin-form-database
**Unanswered Pull request**
https://github.com/scan5415/grav-plugin-form-database/pull/5

**Comment by rhukster** [comment]
Let's give the original author a chance to respond.

**Comment by rhukster** [comment]
Where's your version of the plugin???

**Comment by gamahachaa** [comment]
> Where's your version of the plugin???
There : 
https://github.com/gamahachaa/grav-plugin-form-database

**Comment by gamahachaa** [comment]
Ok I added the mention of the old repo and corrcted the Blueprints ...

**Comment by gamahachaa** [comment]
Hi Andy,
 All good ?

**Comment by rhukster** [comment]
yah i'll get this updated shortly

**Comment by rhukster** [comment]
Sorry for the delay.. Database plugin version 1.0.1 released, and also changed form-database plugin to your repo.

**Comment by gamahachaa** [comment]
No worries. Thanks you for this peace of mind framework!

Le jeu. 5 déc. 2019 à 01:03, Andy Miller <notifications@github.com> a
écrit :
