### ISSUE TITLE
Add resolution public/unpublic variables/methods for twig dump function

### ISSUE THREAD

**Issue by fosil** [getgrav/grav#2729]
If I use the twig function {{ dump(page) }}, the properties/methods will be displayed without distinction the option to display them. E.g. page.raw_route will appear in the dump, but if it is called directly ({{ dump (page.raw_route) }} or {{ page.raw_route }}) it will not return anything. Of course, because it is defined as private. This particular feature can be accessed through {{ page.rawRoute }}, but it's not clear from the dump. Would it be possible to mark "accessible" properties? - Like dump() called directly from PHP code does?

**Comment by mahagr** [comment]
Nope, none of the variables should be accessible directly as the variables may or may not be initialized. You should look into the public interface instead, available in:
https://learn.getgrav.org/16/api#class-gravcommonpagepage

**Comment by fosil** [comment]
There, of course I will find it. But for development work, it would be much more convenient to see it "at first" in the output of the dump. Like PHP dump, it marks public / protected / private

**Comment by mahagr** [comment]
For development, I would just use a good IDE like phpstorm, which gives you easy access to the class properties. The dump() is really for debugging purposes only, allowing you to see the internal state of the object.

If you install 1.7 and Flex-Objects plugin, you can enable Flex Pages, which has a more logical dump() compared to the old class. It is still an experimental feature, but should work fairly well at least in admin -- and we would appreciate any testing on it.

**Comment by fosil** [comment]
I wrote that dump is perfect from PHP. The problem is in the dump in the twig template and its display in the debug bar. PHPStorm suggests in the twig template which object properties are inaccessible? Respectively shows only the accessible ones? It does not seem too technically possible. But I don't know him in detail.

I glanced at the flex object and it looks really interesting. Maybe it will be a solution. I will definitely try it when some less "bloody" job appears :-)

When one of the TOP contributors answered: I still wanted to ask if there was a solution to my older forum question: https://discourse.getgrav.org/t/how-render-page-to-string-other-than-currently- displayed/10457
I'm sorry for OT!

**Comment by mahagr** [comment]
I think that debugbar uses symfony vardumper to get the content of the object. If you don't like the output from it, you can also use `var_dump()` from twig. And yeah, method hints do not work inside twig (or outside php).

Regarding to rendering a page to a string, I cannot really respond as it really depends on what you'd want to do and from where. That said, I've done it in couple of different ways in some projects.

**Comment by fosil** [comment]
It would also be interesting to consider the possibility of integrating a debug library from NetteFramework - https://tracy.nette.org/en/

**Comment by rhukster** [comment]
Interestingly Tracy is what we used in the original version of Grav.  We have since moved to Whoops, Symfony debugger and other tools

**Comment by fosil** [comment]
I moved the question to render into a variable into a new issue
