### ISSUE TITLE
SVG files not in page.media

### ISSUE THREAD

**Issue by rjspencer** [getgrav/grav#273]
In a page module folder I have a regular SVG. Its the only image file in the folder. The theme runs {% set image = page.media.images|first %} and then {{ image.html }} but nothing is output. If I add a JPEG to that folder with the SVG, the JPEG loads.
It seems that page.media.images does not include SVG files. 

One of the SVG files I tried.
![](http://kompozer.net/images/svg/Mozilla_Firefox.svg)

I am building a child theme of Antimatter. The module template is
```
{% if page.header.grayscale %}
    {% set image = page.media.images|first.grayscale() %}
{% else %}
    {% set image = page.media.images|first %}
{% endif %}

<div class="modular-row features sideimage pure-g {{ page.header.class }}">
    
    {% if page.header.image_left %}
    <div class="pure-u-1-2">
        <div class="{{ page.header.image_type }}" style="background-image: url('{{ image.url }}'); background-size: cover;"></div>
    </div>
    {% endif %}
    
    <div class="pure-u-1-2">
        {{ content }}
        
        {% for button in page.header.buttons %}
            <a class="button{% if button.primary %} primary{% endif %}" href="{{ button.url }}">
                {{ button.text }}
            </a>
        {% endfor %}
    </div>
    
    {% if page.header.image_right %}
    <div class="pure-u-1-2">
        <div class="{{ page.header.image_type }}" style="background-image: url('{{ image.url }}'); background-size: cover;"></div>
    </div>
    {% endif %}
    
</div>
```
Using the SVG as a background should not be the issue as I have also tried `{{ image.html }}` and get the same results.

**Comment by rhukster** [comment]
Because  SVG is actually a special kind of image and can't be manipulated with filters, it actually is listed in `page.media.files`.

Specifically it would be:

```
{{ page.media.files['firefox.svg'].html }}
```

or in markdown syntax simply:

```
![](firefox.svg)
```
