### ISSUE TITLE
Can't add items to list in Grav admin after updating to Grav v1.6.17, Admin v1.9.11, and Form v4.0.0

### ISSUE THREAD

**Issue by glasswork** [getgrav/grav#2730]
After update of grav and plugins I can no longer add to a list in the Administrative backend.

I _can_ manually add directly to the .md file and save it but not through admin interface.

It worked for a brief while after the update until a cache flush - then it stopped.

That was when noticed a change in the associated .md file. 

Previously it separated items by a '-', now it is using numbers followed by colons, like this '120:'

This is what the admin side looks like:
![Screen Shot 2019-11-13 at 12 10 50 PM](https://user-images.githubusercontent.com/4681577/68795685-ab366900-060e-11ea-9fd9-c8b3d6687777.png)

This is what the new .md file looks like:
![Screen Shot 2019-11-13 at 12 11 28 PM](https://user-images.githubusercontent.com/4681577/68795767-d9b44400-060e-11ea-8b0f-ae9b25cdfe19.png)

This is what the old .md file looked like:
![Screen Shot 2019-11-13 at 12 13 42 PM](https://user-images.githubusercontent.com/4681577/68795959-2f88ec00-060f-11ea-9e40-55f4f9d85978.png)

Any help appreciated.

**Comment by mahagr** [comment]
@glasswork Check the resulting yaml for any missing/out of order keys or keys with strings in it. Have you reordered the entries?

**Comment by glasswork** [comment]
Thanks for looking into this.

The yaml looks clean to me.
The only thing that seemed to change was the .md file.

No, I have not touched the yaml file since I started using it. It is as it was for all the previous 100+ entries.

Here is the yaml

`# Resources
    resources_section:
      type: section
      title: Add a Resource Item
      underline: true

    header.resource_item:
      type: list
      collapsed: true
      collapsible: true
      fields:
        .name:
          type: text
          label: Item Name
          description: '<br>Like: 5 Things You Should Know About The Yazzie Ruling.<br><br>'
        .format:
          type: select
          label: Item Format
          options:
            pdf: 'PDF'
            video: 'Video'
        .type:
          type: select
          label: Resource Type
          options:
            info: 'Informational Material'
            summary: 'Executive Summary'
            legal: 'Legal Document'
            brochure: 'Brochure'
            report: 'Report'
            video: 'Video'
        .area:
          type: select
          label: 'Resource Area(s)'
          help: 'You may select multiple areas - but try and keep it simple.'
          multiple: true
          validate:
            type: array
          options:
            education: 'Education'
            healthcare: 'Healthcare'
            public-benefits: 'Public Benefits'
            workers-rights: 'Worker''s Rights'
            equity: 'Economic Equity'
            legal-services: 'Civil Legal Services'
            nabapi: 'Native American Budget & Policy Institute'
        .language:
          type: text
          label: Item Language
          description: 'Like: `English`, `Spanish`, `Diné`, `Tewa`, `Vietnamese`.'
          default: 'English'
        .date:
          type: text
          label: Item Publication Date
          description: 'Like: YYYY/MM so 2019/10 for October 2019'
        .file:
          type: file
          label: Upload Item (if file)
          help: 'At the moment this accepts only PDFs.'
          destination: 'user/themes/nmclp/assets/resources'
          multiple: false
          avoid_overwriting: true
          accept:
            - .pdf
        .link:
          type: text
          label: Link to Item (if YouTube Video)
          description: 'Like: https://www.youtube.com/watch?v=V5vi9qWO0Oc'`

**Comment by glasswork** [comment]
Oh ... yes, I had reordered some entries. 
I had been doing that for some time though.

**Comment by glasswork** [comment]
Yep, stopped being able to add items through the Admin interface at the same number of items.
The upload for the item worked, but no additional fields came with it, like so:

```
-
        file:
            user/themes/nmclp/assets/resources/Factsheet-Domestic-Home-Care-Workers-2019-06.pdf:
                name: Factsheet-Domestic-Home-Care-Workers-2019-06.pdf
                type: application/pdf
                size: 181071
                path: user/themes/nmclp/assets/resources/Factsheet-Domestic-Home-Care-Workers-2019-06.pdf
```

The conclusion would seem to be that there is a limit somehow.

Oh, I varied what I added to bring it back to the limit using very different field values each time to make sure it wasn't one particular field entry that was gumming up the works.

**Comment by mahagr** [comment]
It is a limit in PHP settings:

Edit your php.ini:
```ini
max_input_vars = 2000
```

**Comment by glasswork** [comment]
Seriously??? Sorry I missed that.
I will change it and report back.

**Comment by glasswork** [comment]
Well, if phpinfo is right about the path of the php.ini file being used, that was not it. 
I also changed every php.ini file on my system just in case it wasn't accurate.
And I bumped them waaaay up.
I am going to fiddle some more...

**Comment by glasswork** [comment]
Ok - hard restart of system got the new php.ini setting to load ... simply restarting Apache did not do it for some reason.
Closing. Thanks again.
