### ISSUE TITLE
How render page to string (other than currently displayed)

### ISSUE THREAD

**Issue by fosil** [getgrav/grav#2732]
Hello,
I need to render the complete page (eg http://mydomain/page-need-render.ics into a string when the page being viewed is different (eg http://mydomain/page-actual-display). Ideally somehow less stupid than using “curl (http: //mydomain/page-need-render.ics)” :-) Anyone please have an idea?

Thx

**Comment by mahagr** [comment]
Try something like: `{{ grav.twig.processSite(page.templateFormat) }}`

**Comment by mahagr** [comment]
```php
$page = $grav['pages']->find('/path/to/page');
if ($page) {
    $content = $page->content();
}
```
