### ISSUE TITLE
Install Grav without Quark theme

### ISSUE THREAD

**Issue by alljamin** [getgrav/grav#2734]
I have a custom Grav theme and I manage my project via version control. Every time I clone a project to the new environment I need to run `bin/grav install` which installs all Composer dependencies along with the Quark theme. 

Is there an additional parameter to pass together with `bin/grav install` in order to ignore Quark installation?

**Comment by rhukster** [comment]
The Install command uses the .dependencies file to install plugins and themes. That’s where it gets quark from.  Just edit this file.

**Comment by alljamin** [comment]
Thank you for your prompt response! This is very helpful.
