### ISSUE TITLE
Can't save page when using Flex Pages in admin

### ISSUE THREAD

**Issue by SeriousKen** [getgrav/grav#2736]
With a default install of Grav 1.7.0-rc1 and Flex Pages enabled in experimental config. When I try to save a new page I get the following error:

Save Failed: Page /test-page cannot be moved to non-existing path \

**Comment by mahagr** [comment]
Looks like you're using Windows?

**Comment by SeriousKen** [comment]
Sorry, yes, I forgot to say this is on Windows 10.

**Comment by SeriousKen** [comment]
I've created a pull request should fix this https://github.com/getgrav/grav/pull/2770

**Comment by mahagr** [comment]
I'm going to check the fix soon (as well as looking if there are other similar cases), though the Christmas time will likely cause some delays. It'll be fixed before the next RC for sure.
