### ISSUE TITLE
Proposal : markdown span and div

### ISSUE THREAD

**Issue by VincentFericelli** [getgrav/grav#2739]
Allowing markdown div and span would be very usefull to render particular blocks of contents.
Pandoc synthax seems nice : https://pandoc.org/MANUAL.html#extension-fenced_divs.

**Comment by rhukster** [comment]
Not a bad idea, but we already support custom DIV and SPAN via shortcode-core syntax which is simple enough: https://github.com/getgrav/grav-plugin-shortcode-core#div

**Comment by VincentFericelli** [comment]
I didn't know this feature, interesting. But in the case of div and span it doesn't seem so "short" you just replace <> with [] : 

```
[div class="text-center"]
This text is **centered** aligned
[/div]
```
is quite the same as : 
```
<div class="text-center">
This text is **centered** aligned
</div>
```
while this is shorter : 
```
::: {.text-centered}
This text is **centered** aligned
:::
```
and even better for spans
```
[This text is **centered** aligned]{.text-centered}
```

The colon maybe not so readable, I don't know if using [[[ and ]]] would mess up the parser. If this feature is selected for implementation, it could also be argued that having a different syntax from another big actor of markdown is not a good idea.

**Comment by rhukster** [comment]
The difference is you can use markdown between shortcodes and you can’t between html.

**Comment by VincentFericelli** [comment]
Why it is not allowed ? It is in pandoc and I use it every day.
