### ISSUE TITLE
include docs in git

### ISSUE THREAD

**Issue by axd1967** [getgrav/grav#2743]
I'm trying to start an old version of Grav, so I need the documentation from that period.

As far as I can see, user documentation lives in a separate place, in learn.getgrav... Please consider making the user documentation part of the grav sourcecode repo so that this will no longer be a problem in the future. this way, documentation will evolve in a natural way together with code, and this will also allow to discover documentation changes through trivial diffs on the docs. 

thank you.

**Comment by mahagr** [comment]
All the history for the docs is there, too: https://github.com/getgrav/grav-learn

You can install the learn site locally and just pick revision from the history to match your version better.

**Comment by axd1967** [comment]
hello,
would it be possible to tag the grav-learn repo with the same tags as the grav releases? this way one can discover changes more easliy.
