### ISSUE TITLE
Cookies are set twice in the HTTP header

### ISSUE THREAD

**Issue by RichardPautz** [getgrav/grav#2745]
The set-cookie parameter is always set twice in the HTTP header. 
This happens on all grav based sites I looked at, whether I curl -I "https://getgrav.org" or one of the sites in the "Build with Grav" section, like https://trilby.media/ or https://www.oblique.space or even my own localhost.

**Comment by mahagr** [comment]
I think this might be side effect from a fix with no cookie being sent in older versions of PHP.
