### ISSUE TITLE
[add-resource] New Skeleton

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav#2748]
I would like to add my new [skeleton ](https://github.com/hotdoy/grav-skeleton-hotdoy)to the GPM.
EDIT:  Package is in!

**Comment by hotdoy** [comment]
To be honest I'm not sure I am doing everything alright here so if something is off. Don't be shy.

**Comment by rhukster** [comment]
A skeleton needs to have a pre-built package in the release with the latest Grav + user folder with everything ready to just unzip and run.  Eg: https://github.com/getgrav/grav-skeleton-blog-site/releases

**Comment by hotdoy** [comment]
OK so I basically just dump a full install with the themes, plugins and everything BUT the users?
Ill check everything properly tonight. Thanks!

**Comment by rhukster** [comment]
yah, basically get it running and up to date. Then run `bin/grav clean` to remove the extra unneeded stuff (cache, logs, accounts, data, etc), then zip it.

**Comment by hotdoy** [comment]
Wonderful! i wasn't aware of the clean cmd. Ill update this issue once I get it done.

**Comment by hotdoy** [comment]
@rhukster - All setup here. I've updated the v1.0.0 release with a package and tested it. 
Thanks for your help.

**Comment by rhukster** [comment]
Added to GPM
