### ISSUE TITLE
HTTPS throwing error 404 "The requested URL was not found on this server"

### ISSUE THREAD

**Issue by CDKML** [getgrav/grav#2749]
If i access my Grav page as HTTP everything works smoothly. 
But as soon as I access it from https://myweb.com it throws me a 404 error "The requested URL was not found on this server" and even if i write explicitly http://myweb.com it redirects me to the https page and i can't access any of my grav pages until i delete domain security policies.

I tried restarting my IIS (Apache), forcing SSL from grav in case it could do something else appart from just forcing, maybe adding a protocol or smthn, I tried rerouting .htaccess file from  HTTPS to HTTP but none of this worked.

Don't know what else to try

**Comment by rhukster** [comment]
Sounds like you have not configured the location of your HTTPS vhost to point to the same folder as your HTTP vhost.

**Comment by CDKML** [comment]
Should I try changing my httpd-vhosts.conf file and grant all permissions via virtual hosts for grav?

**Comment by rhukster** [comment]
Just need to make sure that HTTP (non-SSL) and HTTPS (SSL) vhosts point to the same directory. That's all you really should need.

**Comment by CDKML** [comment]
Finally we found an AllowOverride directive which was in the HTTP directory but not in the HTTPS. Once we put it in the HTTPS file the issue was solved. Thanks!
