### ISSUE TITLE
Uploading a svg logo file truncated

### ISSUE THREAD

**Issue by AndrassGray** [getgrav/grav#2755]
Trying to upload a new logo file in Grav 1.7.0-rc2 with the Quark theme.

The original file is 8kb in size, after upload is it 265 bytes.
![image](https://user-images.githubusercontent.com/30862808/70391963-e98b3200-19da-11ea-8849-90c307622923.png)

Shows 8.6kb in the admin, but is empty.
![image](https://user-images.githubusercontent.com/30862808/70391977-235c3880-19db-11ea-9beb-4958fe591820.png)

The original file has been created with PS and shows fine in Firefox.

Let me know if someone wishes to have the file for testing, I prefer not to upload it for general consumption.

**Comment by AndrassGray** [comment]
Also : Tried uploading the grav-logo.svg, and that works perfectly fine and as expected.

**Comment by rhukster** [comment]
Under the Configuration -> Security section there is an option for "Sanitize SVG".  Can you try disabling that? It seems that this might be an issue with your SVG that the sanitize logic is stripping out.

Looking at the composer.lock file it seems we are running an out of date version, so i will update that for the next 1.7. RC version.

**Comment by rhukster** [comment]
You can try this change and do a `composer update`

https://github.com/getgrav/grav/commit/4cc3f44caa16ea221ed6b98434cd23ceaff78edb

**Comment by AndrassGray** [comment]
Disabling the Sanitize SVG does the trick. New or old version have the same effect.

I tried the online version of the sanitizer and it breaks there, too. So this is definitely not a Grav problem, closing the issue here.

Will open another one with darylldoyle/svg-sanitizer to see if there is something that could be done.

Thanks for looking into this.

**Comment by AndrassGray** [comment]
https://github.com/darylldoyle/svg-sanitizer/issues/37

If Darryl can't fix this for some reason, maybe Grav could check the output-size after sanitizing and warn about an incompatible file-type. My guess is that the embedded binary in my SVG is what get's dropped. So yes, it's a SVG, but ...

**Comment by AndrassGray** [comment]
Daryll fixed it (my guess was wrong, fortunately), so this should be good soon here as well.
