### ISSUE TITLE
Add a link to the changelog

### ISSUE THREAD

**Issue by AnaelMobilia** [getgrav/grav#2757]
Hello,
On the admin home page, a notification appears when a new version of grav is available (and provide an upgrade button).
As it's a BP to read changelog before upgrading, it should be great to add a link to read the changelog.

A quick-win could be a link to the github CHANGELOG.md file with an anchor to the current version.
eg : https://github.com/getgrav/grav/blob/develop/CHANGELOG.md#v1619

Regards,
Anael

**Comment by rhukster** [comment]
This as already been addd to the grav 1.7 and admin 1.10 branches.  Should be available in next rc release.
