### ISSUE TITLE
Version using less files?

### ISSUE THREAD

**Issue by TheTechRobo** [getgrav/grav#2758]
I am using grav on a **very tight webhost**, byethost. It only gives you ~3000 inodes! Could you create a version using less files? I tried deleting all the cache but now grav doesn't load.

**Comment by rhukster** [comment]
This made me chuckle :)

No, we're not going to do that, sorry.

**Comment by mahagr** [comment]
I agree. Those servers are really not meant to be used with any CMS, sorry.

**Comment by TheTechRobo** [comment]
I thought so..
But you can't blame me for trying :smile:

Sent from my Outlook

On Dec 12, 2019, at 3:31 a, Andy Miller wrote:


This made me chuckle :)

No, we're not going to do that, sorry.
