### ISSUE TITLE
Modular page and Multiligual - loading both content

### ISSUE THREAD

**Issue by navjinder** [getgrav/grav#2759]
Hi Team Grav

I have created a website and have english and french content. I am using modular pages but for some reason it is loading both the content on the english pages. is there any other setting which I am missing

![image](https://user-images.githubusercontent.com/3472650/70651883-a8d02a80-1c1f-11ea-8749-4ea8444f372a.png)

![image](https://user-images.githubusercontent.com/3472650/70651901-af5ea200-1c1f-11ea-9549-167935dfc885.png)

**Comment by mahagr** [comment]
I cannot reproduce the issue in Grav 1.6 or 1.7. Make sure that your site has multilanguage turned on and configured correctly.

**Comment by navjinder** [comment]
@mahagr  This is solved. The Modular's were not setup properly 
fyi in your modules you have to use as I was creating `middle.en.html.twig` & `middle.fr.html.twig`
Grav was not loading the french files but would always load the english file. Therefore, I have added the twig if statement to show french and english content.
```
{% if html_lang == "fr" %}
--french content goes here--
{% else %}
--english content goes here--
{% endif %}
```

**Comment by mahagr** [comment]
Grav should be automatically picking up both of the files, I tried it in my local. In my case, I had the whole modular skeleton set up with English and Finnish and all files with `.en` and `.fi` in them.

Both languages were fully translated and working.

**Comment by navjinder** [comment]
hmm...That is strange it was not working for me I will try to replicate it.
