### ISSUE TITLE
Usage variables into twig function

### ISSUE THREAD

**Issue by pquerner** [getgrav/grav#2760]
Hey,
how is the following possible in a normal post?

```
<a href="mailto:{{config.site.author.email|safe_email}}">By mail</a>
```

Only `config.site.author.email` is replaced, but not transfered to the `safe_email` function.

**Comment by rhukster** [comment]
are you sure? it won't be visible in developer tools, try "view source"

**Comment by pquerner** [comment]
Yes, actual output is

```
<a href="mailto:example@example.org" class="mailto">By mail</a>
```

Grav 1.6.19 is in usage with PHP 7.3

**Comment by rhukster** [comment]
I can't replicate this:

![Image 2019-12-12 at 1 53 40 PM](https://user-images.githubusercontent.com/1084697/70748225-d3d18180-1ce6-11ea-8298-f7605ee5a8cf.png)

Works as expected for me...

**Comment by mahagr** [comment]
You need to view the source code of the page, not inspect etc inside the browser.

**Comment by pquerner** [comment]
![image](https://user-images.githubusercontent.com/4364044/70785271-8ad30900-1d8a-11ea-821c-416642ba3470.png)
![image](https://user-images.githubusercontent.com/4364044/70785463-e69d9200-1d8a-11ea-8b38-9b6e444897ae.png)

**Comment by rhukster** [comment]
If you are trying to do Twig in a page, you need to turn on twig processing for that page. Frankly it's better to use Shortcodes in content, and not Twig, as it's more readable for users.  Shortcode-core plugin has a nice "safe email" shortcode: https://github.com/getgrav/grav-plugin-shortcode-core#safe-email

**Comment by pquerner** [comment]
Twig is enable, else it wouldnt output anything, no?
I'll try the shortcode addon, thanks. I also tried the Antispam addon, which works quite nicely aswell.
