### ISSUE TITLE
Upgraded to 1.7.0-rc.2, Admin page started to crash

### ISSUE THREAD

**Issue by OrthoCube** [getgrav/grav#2762]
The error says "array_key_exists() expects parameter 2 to be array, null given".

This comes from `system/src/Grav/Common/Page/Pages.php`, line 722

```
public function get($path)
    {
        $path = (string)$path;
 
        // Check for local instances first.
        if (array_key_exists($path, $this->instances)) {
            return $this->instances[$path];
        }
 
        $instance = $this->index[$path] ?? null;
        if (\is_string($instance)) {
            $instance = $this->directory ? $this->directory->getObject($instance, 'flex_key') : null;
            if ($instance && $this->fire_events && method_exists($instance, 'initialize')) {
                $instance->initialize();
            }
        }
 
        $this->instances[$path] = $instance;
 
        return $instance;
    }
```

You can visit my website to view the full log, I don't mind. http://orthocube.xyz/admin

Is there any way to fix this? Thanks in advance :)

**Comment by mahagr** [comment]
It's already fixed. For a quick fix, go to the start of the file and find `protected static $instances;` and change it to `protected static $instances = [];`.

**Comment by OrthoCube** [comment]
I'm sorry I didn't notice the duplicate issue.
That fixed it :) Thanks!
