### ISSUE TITLE
[update-resource] Updated Plugin/Theme

### ISSUE THREAD

**Issue by DanielFlaum** [getgrav/grav#2768]
I would like to update my plugin in the Grav Repository.
Here are the project details: **DanielFlaum/grav-plugin-mermaid-diagrams**

The version of this plugin currently in the Grav Repository is v1.0.0. This requests seeks to update the Grav Repository with v1.1.0 of this plugin.

Let me know if I can help with anything. Thanks!

**Comment by rhukster** [comment]
GPM should automatically pick up any new releases.  If it didn't pick up a new release then it's probably something you did wrong during the release.  Check these things:

1. Make sure you actually created a release.
2. You updated the blueprints.yaml to have the correct version number (this must be done prior to releasing so it gets taggged)
3. Check to make sure you kept the same numbering scheme.  For example, if your first release was `v1.0.0`, make sure your next release is `v1.1.0`.  not `1.1.0` or `V1.1.0`, these will not get picked up.  It should match down to case and spaces, etc.

**Comment by DanielFlaum** [comment]
Yep, it picked it up. I thought it was a manual process that required an issue. Sorry for cluttering things up!
