### ISSUE TITLE
Gantry: #2662 reappears in v1.7.0-rc.2

### ISSUE THREAD

**Issue by psd-uk** [getgrav/grav#2769]
The issue with assigning specific pages (issue #2662) in gantry admin layouts seems to have come back in v1.7 RC2. I thought it was fixed in RC1.

Also list boxes don't format correctly in Safari, been a problem for a while, see screenshot.

<img width="1562" alt="Screenshot 2019-12-20 at 11 25 08" src="https://user-images.githubusercontent.com/59086878/71251935-82934480-231b-11ea-96ea-16e6b5e3d5b5.png">

**Comment by mahagr** [comment]
@psd-uk Can you re-test this issue with latest Gantry 5.4.32 release?

**Comment by psd-uk** [comment]
Sorry, I will be away from the desktop for a few days

**Comment by psd-uk** [comment]
I have now tested on v1.7.0-rc.3 & Gantry 5.4.32 and it does now show a Pages assignment box.

In Chrome it has the two containers inline vertically and controls function correctly.

In Safari you get both boxes as shown in the following screenshot:
<img width="932" alt="Screenshot 2020-01-09 at 16 13 42" src="https://user-images.githubusercontent.com/59086878/72084340-34aaa480-32fb-11ea-9366-505c984a7c67.png">

removing from the card :

#g5-container .card {
    vertical-align: top;
}

improves the formatting of the control elements but the card height does not expand. I have tried but cannot get this to expand in safari.

**Comment by mahagr** [comment]
Oh, you're talking about Safari. This issue isn't related to the issue you mentioned in the first message -- this is a bug in Safari with no known workaround.

Make sure you're on the latest version of Safari. Older versions of Safari have very buggy flexbox support which causes layout issues like this. FF and Chrome should work just fine.

**Comment by psd-uk** [comment]
Thanks Mahagr.

Yes it was a secondary bit to my first message. I will use Chrome until Safari is sorted.

**Comment by mahagr** [comment]
I'm closing this as it is not related to Grav but Gantry.
