### ISSUE TITLE
Flex user cannot log in on Windows

### ISSUE THREAD

**Issue by lufog** [getgrav/grav#2772]
I create two users, with same password and permissions: 
- **regular-user** (with disabled flex-users)
- **flex-user** (with enabled flex-users)

Then i try to login:
**regular-user** 
![regular-user](https://user-images.githubusercontent.com/10379487/71315312-c5176700-246a-11ea-8f7a-b7ca3e2648bf.gif)
Authorization passes without problems.

**flex-user** 
![flex-user](https://user-images.githubusercontent.com/10379487/71315311-c5176700-246a-11ea-8f1b-6715e14def21.gif)
Authorization does not pass.

Info: 
---
Windows 10 x64
PHP v7.4.0 (on built in server)
Grav v1.7.0-rc.2
Admin v1.10.0-rc.2

All tests were performed on a clean installation.

**Comment by mahagr** [comment]
I believe this is related to #2773

**Comment by lufog** [comment]
Unfortunately, in Grav v1.7.0-rc.3 this problem is not fixed.

**Comment by mahagr** [comment]
I don't think it's a Windows-specific issue as we had it tested in Windows.

Make sure you didn't change the storage type to folders as it would require different structure of files.

**Comment by lufog** [comment]
**Configuration -> Experimental:**

![изображение](https://user-images.githubusercontent.com/10379487/71710689-95734200-2e0e-11ea-9c16-baacafdaed94.png)

**User Accounts -> flex-user:**

![изображение](https://user-images.githubusercontent.com/10379487/71710750-dc613780-2e0e-11ea-8cb0-862d7b2b5293.png)

**User Groups -> super:**

![изображение](https://user-images.githubusercontent.com/10379487/71710773-eaaf5380-2e0e-11ea-8f99-003ec16e1d71.png)

**Comment by mahagr** [comment]
Settings look good. Not sure why the login fails, though...

**Comment by lufog** [comment]
This bug is the same as #2785, and my old https://github.com/getgrav/grav/issues/2444#issuecomment-527158445 and this commit https://github.com/getgrav/grav/commit/a8ff0e389241d99b6d81d7c3e4d5d62b988287d3 fix it.
