### ISSUE TITLE
[add-resource] Scholar Theme and Skeleton

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#2774]
I would like to add my new theme and skeleton to the Grav Repository:

1. [Scholar Theme](https://github.com/OleVik/grav-theme-scholar): An academic-focused theme, for publishing papers, articles, books, documentation, your resumé or other content with Grav.
2. [Scholar Skeleton](https://github.com/OleVik/grav-skeleton-scholar): Assembled Grav-installation with required and suggested plugins, as well as sample content, for testing the theme.

**Comment by rhukster** [comment]
Added both to GPM
