### ISSUE TITLE
Saving and previewing flex-pages does not work on Windows

### ISSUE THREAD

**Issue by lufog** [getgrav/grav#2776]
When flex-pages are enabled, saving and previewing pages does not work.
![T1Mhqu0C4O](https://user-images.githubusercontent.com/10379487/71452186-73851a00-2793-11ea-9277-a0f29ef6db1d.gif)

Info
---
Windows 10 x64
PHP v7.4.0 (on built in server)
Grav v1.7.0-rc.2
Admin v1.10.0-rc.2

All tests were performed on a clean installation.

**Comment by SeriousKen** [comment]
This is a duplicate of issue https://github.com/getgrav/grav/issues/2736

**Comment by mahagr** [comment]
I believe this is also related to #2773

**Comment by lufog** [comment]
Yep, in Grav v1.7.0-rc.3 this problem is fixed.
