### ISSUE TITLE
Invalid handle of markdown code inside a code block

### ISSUE THREAD

**Issue by AnaelMobilia** [getgrav/grav#2778]
Hello,

Grav badly interpret markdown code inside a code block.

Example : 
![image](https://user-images.githubusercontent.com/6187125/71547236-b87c9c80-299d-11ea-81bb-9cbf8958004a.png)
Render :
![image](https://user-images.githubusercontent.com/6187125/71547243-c8947c00-299d-11ea-985d-03434289707f.png)
Expected : 
  - The tiret line should'nt be transform as it's inside a code block
  - subitem2 shouldn't be a code block (and inverse for sdfsdf line)

So I had new line before and after the code block :
![image](https://user-images.githubusercontent.com/6187125/71547258-fe396500-299d-11ea-86e5-142af6645a7a.png)
Render : 
![image](https://user-images.githubusercontent.com/6187125/71547260-072a3680-299e-11ea-9915-1b107130a128.png)
Expected :
  - First code block is perfect !
  - subitem2 become a code block

Grav v1.6.19 - Admin v1.9.12 - No specific modules
Regards,
Anael

**Comment by rhukster** [comment]
To make this more reliable to test, please provide me your sample code in codeblocks (not screenshots) so i can try to recreate the issue exactly.

**Comment by AnaelMobilia** [comment]
@rhukster 
Example 1 : https://pastebin.com/acvjCxuj
Example 2 : https://pastebin.com/yJVwNc48

Regards,
Anael

**Comment by rhukster** [comment]
Seems this is an issue with Parsedown. Test here:

https://parsedown.org/demo

My results for first example:

![Image+2020-01-06+at+5 53 48+PM](https://user-images.githubusercontent.com/1084697/71859816-8d84fd80-30ad-11ea-90aa-faabcb788387.png)
