### ISSUE TITLE
Invalid input in Description

### ISSUE THREAD

**Issue by umbergerba** [getgrav/grav#278]
I get the following error when adding to the meta description ...

Validation failed: Invalid input in Description

Not sure what's happening, but it looks like there might be some kind of limit on the number of characters in the Meta Descriptions? If I cut back some on the text, it will save ok.

**Comment by rhukster** [comment]
I think you intended this to be in the admin plugin issue tracker?  This is not a grav issue per say.  

There is a limit on meta descriptions that recommend the size between 150 and 160 characters: https://moz.com/learn/seo/meta-description

Currently Grav limits the meta size to 155 characters

**Comment by umbergerba** [comment]
Yes, I posted this in the wrong place.

I figured their was a limit. The issue I have is that when I hit save it generates this error and wipes-out everything I entered in all the fields under the Options tab. A character count-down would be really nice to have here. THX!
