### ISSUE TITLE
Flex-user can't login

### ISSUE THREAD

**Issue by SjoerdSmeets** [getgrav/grav#2785]
When i created a new user using Flex-users a cryptic-username.yaml is created in /accounts.
This user can't login unless you rename to correct-username.yaml 

Tested with 1.7rc3 on Linux with php7.3

**Comment by SjoerdSmeets** [comment]
Hello, i found a way to correct this bug.

In \system\blueprints\flex\accounts.yaml change line 80 from 
key = storage_key to key = username

**Comment by mahagr** [comment]
@SjoerdSmeets Thanks, I had the key issigned wrong way between the folder and file variations.
