### ISSUE TITLE
After upgrade to v0.9.38 `page.active` returns `false` for home page.

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#279]
After upgrade to v0.9.38 `page.active` returns `false` for home page.

**Comment by flaviocopes** [comment]
@maxlysenko can you tell me how to replicate this?

**Comment by maxlysenko** [comment]
Take a look at site with theme where active state in navigation is setted using `if page.active`.
For example look at [Grav](http://getgrav.org) site. On the home page there is no upper line (which represents active state) for "Home" menu item and corresponding `<li>` element doesn't have `active` class.
Or simply write `{{ dump(page.active) }}` in the base template and look at the value for home page.

**Comment by flaviocopes** [comment]
Replicated, thanks!

**Comment by flaviocopes** [comment]
Fixed in the repo, will get in the next Grav update!
