### ISSUE TITLE
Two "Media" tabs in Configuration - Media

### ISSUE THREAD

**Issue by maofree** [getgrav/grav#2794]
Hi
I've found a little bug in "Configuration - Media" there are two tabs with the same name "Media" that point to the same configuration page

![1](https://user-images.githubusercontent.com/653230/72666454-bba20000-3a12-11ea-9779-27957a0cc941.png)

Grav v1.7.0-rc.3 - Admin v1.10.0-rc.3

bye

**Comment by mahagr** [comment]
I am not able to see this. Have you tried this with a clean installation? It would be great to find out when this happens.

**Comment by maofree** [comment]
hi
yes it is a clean installation downloaded the zip

**Comment by rhukster** [comment]
confirmed. looking into this...

**Comment by rhukster** [comment]
FYI discovered that Toolbox 1.4.6 didn't have this problem, so definitely something in later Toolbox version.
