### ISSUE TITLE
Jquery file is loaded in the head tag

### ISSUE THREAD

**Issue by maofree** [getgrav/grav#2795]
Hi
with the new 1.7 is loaded in the head tag.
is it possible to load the jquery file at the bottom like in the grav's versione 1.6.19 ?

![1](https://user-images.githubusercontent.com/653230/72666518-5995ca80-3a13-11ea-9070-717a2b5612aa.png)

thanks

Grav v1.7.0-rc.3 - Admin v1.10.0-rc.3

**Comment by mahagr** [comment]
This is likely caused by clockwork, can you try with debugging turned off?

**Comment by maofree** [comment]
hi
without debug I get the same issue

![1](https://user-images.githubusercontent.com/653230/72716620-d4292c00-3b72-11ea-9da8-6a73e67a7c3a.png)

**Comment by rhukster** [comment]
Where the JS loads (including JQuery) is dependent on the theme itself, the `partials/base.html.twig` structure and if you are using the built-in JQuery collection.  

Grav 1.6 and 1.7 are exactly the same in how they load JS, so you probably have a different theme, or different plugins that are either needing JQuery or not, it's not Grav 1.7, Asset management, and Quark have not changed in this regard.

**Comment by maofree** [comment]
hi
the theme is the default one, I'm using Graq RC Core + Admin plugin without extra plugin at this moment

**Comment by maofree** [comment]
try to look here
http://maofree.changeip.net/santacaterina/new/
maofree
maofree
set maofree two times at the firs login
I leave here for 30 minutes this info

**Comment by rhukster** [comment]
You are using Quark, it always puts JQuery in the header:
https://github.com/getgrav/grav-theme-quark/blob/develop/templates/partials/base.html.twig#L30

has done so all the way back to it's intial release: https://github.com/getgrav/grav-theme-quark/blob/1.0.0/templates/partials/base.html.twig#L27

Like I said it depends on your theme. It's not Grav 1.7 specific

**Comment by maofree** [comment]
ok thanks
