### ISSUE TITLE
Stream generation & localhost

### ISSUE THREAD

**Issue by victormoukhortov** [getgrav/grav#280]
`{{url('theme://images/someImage.svg', true)}}` in twig resolves to `http://localhost/path/to/image.svg` even when the site is being accessed by ip address. It should resolve to the same host name that the site is being accessed with.

Discovered while testing with a virtual machine on a local network.

**Comment by mahagr** [comment]
@rhukster Issue is in ```$this->grav['uri']->rootUrl(true)``` returning localhost.

**Comment by rhukster** [comment]
![2015-09-07-15-k6b1o](https://cloud.githubusercontent.com/assets/1084697/9723204/5e130a74-5579-11e5-8efa-25ba10b8819e.png)

Not able to reproduce this.  Are you sure it's not a host entry or something on your end?
