### ISSUE TITLE
security admin.super field doesn't work well

### ISSUE THREAD

**Issue by Mohamed-Programmer** [getgrav/grav#2800]
Hi every one,

I copied the default blueprint to themes/mytheme/blueprint.
I added security admin field under options field. It doesn't works very well. What happens is that the settings of "Options" comes under "Advanced" tab as you can see on the picture, it's switching
![123](https://user-images.githubusercontent.com/56513986/72988478-9df6e100-3dec-11ea-8870-e7a51e55d362.png)

This is how the blueprints looks.
![Capture](https://user-images.githubusercontent.com/56513986/72988636-ea422100-3dec-11ea-9c3a-3017daef4d18.PNG)

What am I doing wrong?

**Comment by mahagr** [comment]
This feature is not working well outside of Flex Objects or Form Plugin (frontend). Also it needs @ in the end.

PS: It should work with `security@: admin.super`, BUT if you save the form without being super user, field values under options will be lost.

**Comment by Mohamed-Programmer** [comment]
I already have Grav 1.7 RC.3 as you can see on the first picture. And I have the [Form Plugin
](https://github.com/getgrav/grav-plugin-form) with the Flex Object, but the Flex Object is not enabled because it will do weird stuff. Must I enable it? And did `security@: admin.super`, but still same result.

**Comment by mahagr** [comment]
What I was saying is that it will not work at all in this case.

**Comment by Mohamed-Programmer** [comment]
Oo sorry, I didn't understand you correctly. Is there other way to hide some tabs from non super admin?

I know another way for example `unset@: true` but I must place that another each blueprint because I want only the advanced tab from the default blueprint.

**Comment by mahagr** [comment]
No, right now there's no working way to do it from the plugins, themes or from the configuration.

**Comment by Mohamed-Programmer** [comment]
Oke, thank you for your time.
