### ISSUE TITLE
Allow setting more than one validation pattern for data

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav#2802]
I am actually looking for this capability from a form. That plugin seems to use the `Grav\Common\Data` `validate()` method.

So what I want to do is set more than one validation pattern, such that they all need to pass. Sure, this can almost certainly be done using a complex regular expression, but Grav is supposed to make the developer's life easy and this would help.

I envisage blueprint/form YAML something like:

```yaml
  validate:
    pattern: ['^((?!https?:\/\/)(?:\R|.))*$', '\w\s+\w']
```

and then `Grav\Common\Data\Validation->validatePattern()` could be modified to include a test for `$value` being an array, and loop through that if needed.

Happy to code, test, and submit this as a PR if you think it's a good idea. Wanted to float the idea first.

**Comment by hughbris** [comment]
Have realised this and much more complex cross-field combined criteria, each with their own validation messages, could probably be achieved through a plugin. This might be a better way to cater for developers with complex validation requirements.

**Comment by mahagr** [comment]
The main issue with this is frontend validation, which also needs to work to prevent users from sending the complex inputs. So somehow we would need to be able to build regexp validating those fields.

**Comment by hughbris** [comment]
Thanks for the answer, I don't know much about Grav's FE validation yet. It's probably best implemented as a plugin at this stage, in that case. If my need becomes greater, I could build one.

I am genuinely curious to know more about the nature of the FE validation issues you are talking about. This would be useful to know for building this plugin.
