### ISSUE TITLE
Avatar image deletion don't update avatar field in yaml file.

### ISSUE THREAD

**Issue by mhlsf** [getgrav/grav#2805]
### Environment : 
 - Linux Fedora
 - PHP 7.3.12
 - Grav 1.6.19
 - Admin Panel  1.9.12

Also tested on window Wamp

### Step to reproduce the bug : 

1. Upload an image using the filepicker on the admin profile page (admin/user/youraccount)
2. Save the profile with the save button to the top right
3. Delete the image using the bin icon on the image
4. Save again

### What should happen : 
There should be no image on the filepicker zone

### What happen : 
There is a blank image with the same information as the previously upload image

### What the issue : 
When we delete a profile image, Admin plugin call **taskRemoveFileFromBlueprint()** method in adminbasecontroller.php that correctly delete the image from the **user/accounts/avatar** folder but don't update the **avatar field** in the yaml file.

I would like to provide a fix but I don't know if the yaml file should be updated in **taskRemoveFileFromBlueprint()** or should be done trough **taskSaveUser()**

I suspect it should be done in the **taskSaveUser()** but the data filter seem to remove the avatar field when it is empty (see **Grav/Common/Data/Validation.php**)

**Comment by mahagr** [comment]
Cherry picked the fix to Grav 1.6 as well.

**Comment by mhlsf** [comment]
This fix does work, thank you !
