### ISSUE TITLE
[GPM] Protocol for removal/unlisting

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#2807]
Several plugins, presumably all by [Giansi](https://github.com/giansi), point to diblas.net for demonstration and for the author. This domain has fallen out of his control seemingly, which leads the visitor through a series of ad-sites that prompt the visitor to install extensions etc, as [recently reported](https://discourse.getgrav.org/t/docs-for-diblas-core-plugins-require-browser-plugins/11258).

I'm pretty sure we've seen this happen before. Could the GPM have a blacklist of domains, or a protocol like the [Abandoned resource protocol](https://learn.getgrav.org/16/advanced/grav-development#abandoned-resource-protocol) to unlist plugins until the issue is resolved?

**Comment by rhukster** [comment]
I've temporarily removed these plugins until the matter is addressed. Ideally, the author should be changing the blueprints and pointing to a new demo, then re-releasing. I don't want to be constantly policing this stuff manually.
