### ISSUE TITLE
Summary Separator Breaks Markdown Lists

### ISSUE THREAD

**Issue by victormoukhortov** [getgrav/grav#281]
```md
--
header: someHeader
---

## Title
- list item 1
- list item 2
===
- list item 3
- list item 4
```

There seems to be no way to make this work without breaking either the summary or the full content. I think it's because the summary separator `===` isn't removed until after markdown is parsed.

**Comment by rhukster** [comment]
Correct, however if the `===` is specifically causing your issues because with invalid markdown because it is considered an h1 header notifier, you can change the characters that summary is triggering on in the `system.yaml`.

**Comment by victormoukhortov** [comment]
It seems that no matter what separator I use, the problem persists.

This renders a blank line in the list in content view:
```md
- list item 1

===

- list item 2
```

And this just doesn't work:

```md
- list item 1
===
- list item 2
```

No other permutation produces expected results, regardless of the separator used. How do I put a summary separator inside a list?

**Comment by rhukster** [comment]
I really have no clue :(

**Comment by victormoukhortov** [comment]
So then this is a bug isn't it? It would be fixed if the summary was parsed out before the markdown stage wouldn't it?

**Comment by rhukster** [comment]
It's such a specific need that has never come up before.  Breaking a list into two parts is only going to lead to problems.  If this were in HTML:

```
<ul>
  <li>list item 1</li>
  ===
  <li>list item 2</li>
</ul>
```

You would definitely get broken tags because your list would be sliced into parts with missing `</ul>` tag in the summary.  You wouldn't say this was a bug, you would say, hey I can't break my content in the middle of a list, i'll do something else.

For this reason I really think you need to try another approach rather than saying its a bug in Grav.

**Comment by victormoukhortov** [comment]
Well, yeah, but that would be fixed by removing the summary from the page before applying markdown as well. It's the only logically correct approach isn't it?

**Comment by rhukster** [comment]
I really don't see a clear way around this.  However, if you find a solution and provide a PR I would gladly take into consideration to merge it.

**Comment by victormoukhortov** [comment]
Well, as I see it, the [`summary`](https://github.com/getgrav/grav/blob/c7c81e53801a5f3d317f639bf0571dd0ccefc7c8/system/src/Grav/Common/Page/Page.php#L383) function `Page.php` would have to be rewritten to instead of grabbing `content` and truncating it, first check if there is a separator in the body of `raw_content` and if there is, then pass that though a markdown filter and set it as summary.

Does that make any sense?
