### ISSUE TITLE
Root page Delete button is visible in List view

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#2810]
As discussed on Discord:

<img width="347" alt="2020-02-03_11-23-22" src="https://user-images.githubusercontent.com/1812771/73683882-f1ccba00-4677-11ea-9c06-b5e5f9d8bb2a.png">

Thanks very much,
Paul

**Comment by mahagr** [comment]
@w00fz It looks like we never finished implementing those buttons. What should we do with them?

**Comment by paulhibbitts** [comment]
Thanks @mahagr , could we also please keep this issue open re: larger fix to support deleting of this `root` page if functionality not needed. In the short-term, I've also started testing with Git Sync and it seems that the `root` page is *not* synced over to the repo, which is EXCELLENT!

**Comment by mahagr** [comment]
See also #2972

**Comment by mahagr** [comment]
Already fixed and released.
