### ISSUE TITLE
problem with modular page

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav#2813]
hi,
I have 8 modules in modular page? when I resize browser window (e.g. set galaxy and other in development version firefox ) and press reload browser will be display only 7 modules. In full size of browser display 8,9, 10 + , all modules - ok
whats wrong

**Comment by mahagr** [comment]
Check the source code of HTML first. I bet the module is there, just hidden by some CSS.

**Comment by mahagr** [comment]
Closed due to inactivity.
