### ISSUE TITLE
[add-resource] New Theme: Tail

### ISSUE THREAD

**Issue by MarcelKr** [getgrav/grav#2815]
I've made a theme using tailwind.css. It's a minimalistic blog for now. To be extended :) [This is the repo](https://github.com/MarcelKr/grav-theme-tail)

It would be nice to add it to the official GPM repo.

**Comment by rhukster** [comment]
I'll add this, but just FYI, I'm already working on a base tailwind theme that we'll be using for lots of stuff, most likely the next 'default' theme for Grave too.

**Comment by MarcelKr** [comment]
Oh OK, nice. If it's sufficiently distinct from this theme, I guess it's alright, isn't it?

For my theme I'm planning to implement some additions. A kind of book review template will be the next thing implemented.

**Comment by rhukster** [comment]
Added to GPM
