### ISSUE TITLE
Grav 1.7 RC.5: FlexObject::triggerEvent() does not emit events

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#2816]
```
// FlexObject

public function triggerEvent($name)
{
    return $this;
}
```

**Comment by mahagr** [comment]
Yup, I'm just using it in child classes. I had an idea to implement it in the base class but looks like I forgot.

**Comment by mahagr** [comment]
Note that I added a new set of classes which should be used instead of the Framework ones (unless you make your own).

**Comment by pamtbaau** [comment]
Thanks for fixing it!
