### ISSUE TITLE
Empty tags

### ISSUE THREAD

**Issue by TommiTikall** [getgrav/grav#282]
I am using the default theme antimatter, and I am experiencing that tags in **blog_item.html.twig**, is rendering the anchor tag even if there are no tags. 
This is my first experience with twig, but maybe it should check the length of the page.taxonomy.tag, or the backend method could return false if length === 0.

![grav-tags](https://cloud.githubusercontent.com/assets/2525981/9487461/14075576-4bd2-11e5-86b6-3d7eaf9a553a.jpeg)

**Comment by flaviocopes** [comment]
Can you check the blog item page does not contain the `taxonomy: tag:` header? If it's present and set as [''] then it shows the tags container.

Saving from the admin (latest version at least) should always remove the empty tag header.

**Comment by TommiTikall** [comment]
Hey @flaviocopes 

I'm not sure where you wanted me to look for the `taxonomy: tag:`, but it's not in the **blog_item.html.twig** template. And I re-opened the blog item with the empty tag, saved it, and it's gone :) 
This was done via the admin plugin.

Thanks for the info.

**Comment by flaviocopes** [comment]
Yes sorry I meant in the page md file (e.g. pages/blog/blog2/item.md file). Glad you sorted it out!
