### ISSUE TITLE
GRAV 1.7 RC6 - Flex Pages - Page template problem

### ISSUE THREAD

**Issue by kiranetph** [getgrav/grav#2828]
When changing the "Page Template" to a different template, it will create an additional file at the page.
Example: Page "Typography"
change from "default" to "error", then to "blog" will result in 
![image](https://user-images.githubusercontent.com/15226809/74830881-0c2cb600-534f-11ea-809d-f56e9d0c9265.png)

After disabling "Flex Pages (Admin)" everything works as expected.

**Comment by mahagr** [comment]
Fixed in https://github.com/getgrav/grav/commit/993bc5170b2153227863f8bf7c578aa6ad11810c
