### ISSUE TITLE
GRAV 1.7 RC6 - Flex Pages - Parent setting problem

### ISSUE THREAD

**Issue by kiranetph** [getgrav/grav#2829]
To recreate the problem:
Change "Parent" setting of "Typography" page to "Home" and save it. Now change it back to "Root" and it will create an error message:
![image](https://user-images.githubusercontent.com/15226809/74831715-c113a280-5350-11ea-85ee-53a7b7424b64.png)
Actually the page was saved with correct parent, it just shows the annoying and misleading error message.

It only applies to "Flex Pages". After disabling Flex pages (Admin), it works as expected.

**Comment by mahagr** [comment]
Looks like redirect issue to me, can you check the url of the page after saving?

**Comment by kiranetph** [comment]
it is /admin/pages/home/typography#
while it should be 
/admin/pages/typography#

**Comment by mahagr** [comment]
Fixed in Flex plugin: https://github.com/trilbymedia/grav-plugin-flex-objects/commit/98244ac6fedc4c3c77069d7fb11714275f2bea8e
