### ISSUE TITLE
inline images in RTFM theme not inline

### ISSUE THREAD

**Issue by notklaatu** [getgrav/grav#283]
I have not tested this outside of the RTFM theme yet, so I'm not sure whose bug it is, but inline images are not being rendered as inline elements. 

Or I could be getting the markdown wrong. Currently I'm doing:

    ![foo](../path/to/dir/image.png) Blah blah blah...

Which according to everything I find online should work as an inline image. However, it renders itself on a separate line.

I've done a cursory check through the source code but I'm not finding where the actual conversion from md to html is happening. I imagine it would just be a matter of checking for a newline and using either inline-block or block depending on the result.

**Comment by rhukster** [comment]
This is really how markdown and html works. If you want an image to be inline, you need to add a class to it and then set that class to have `display: inline`. Alternatively you can just use an HTML tag.

**Comment by notklaatu** [comment]
Oh, cheers for that. I didn't realise. Daring Fireball tutorial on markdown suggests otherwise, but I'm happy to just use html tag directly. Thanks.
