### ISSUE TITLE
[add-resource] New Plugin - login-oauth2-auth0

### ISSUE THREAD

**Issue by saitanay** [getgrav/grav#2830]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: 

https://github.com/saitanay/grav-plugin-login-oauth2-auth0

Refer: https://github.com/trilbymedia/grav-plugin-login-oauth2/issues/27 and 
https://github.com/trilbymedia/grav-plugin-login-oauth2/pull/29 for history

Requesting review  - @w00fz

**Comment by rhukster** [comment]
Added to GPM.  Thanks.

**Comment by saitanay** [comment]
Thank you @rhukster for adding this to GPM.

The listing @ https://getgrav.org/downloads/plugins doesnt seem to list the plugin though. Any further action required to add the plugin to the listing on getgrav.org?

**Comment by rhukster** [comment]
No it will show up as long as everything is correct in the blueprints etc, and when the automated update runs (about an hour)

**Comment by rhukster** [comment]
Also subsequent updates and releases will show up automatically too..

**Comment by saitanay** [comment]
Thanks for confirming.

**Comment by saitanay** [comment]
@rhukster  - The plugin isn't listed yet on https://getgrav.org/downloads/plugins

The other plugins that you quoted as examples - login-oauth2-slack, login-oauth2-discord etc also don't seem to show up on the plugins listing on getgrav.org. 

Any ideas?

**Comment by saitanay** [comment]
Installation via gpm doesn't seem to work either - 

`MacBookAir-TanaySai:grav tanay.sai$ bin/gpm install login-oauth2-slack

GPM Releases Configuration: Stable


Nothing to install.

MacBookAir-TanaySai:grav tanay.sai$ bin/gpm install login-oauth2-auth0

GPM Releases Configuration: Stable


Nothing to install.`

**Comment by rhukster** [comment]
Another plugin broke GPM with some invalid YAML, removed it now, and rebuilding GPM.

**Comment by rhukster** [comment]
![image](https://user-images.githubusercontent.com/1084697/74902872-992e3a00-5364-11ea-806c-ed79000bf486.png)

**Comment by saitanay** [comment]
Thank you 👍

**Comment by saitanay** [comment]
But @rhukster  - 

The GPM installation still doesn't seem to work. 

![image](https://user-images.githubusercontent.com/3456349/74923724-4b164680-53f7-11ea-913b-af4edce4bce1.png)

Also, I noticed the GPM listing reflect an old release version number - 1.0.0
![image](https://user-images.githubusercontent.com/3456349/74923787-65e8bb00-53f7-11ea-8b95-c746e7436fdc.png)
This should be at least 1.0.2 at the time when you rebuilt GPM
Could this be related to why GPM install is not fetching the module?

**Comment by rhukster** [comment]
1.0.3 is your latest release.  However you still say it 1.0.0 in the blueprint. https://github.com/saitanay/grav-plugin-login-oauth2-auth0/blob/1.0.3/blueprints.yaml

When you release a new version you need to update blueprint and changelog.

**Comment by saitanay** [comment]
Thank you Andy.

Created a new release with updated blueprint. Hope the next gpm cron run picks it up.

**Comment by saitanay** [comment]
it has been an hour+. But the new tag 1.0.5 doesnt seem to showup.

**Comment by rhukster** [comment]
Usually not this much trouble! Perhaps it’s all the higher Tags that are confusing it. Can you delete any tag above 1.0.5?

**Comment by w00fz** [comment]
I believe this has to do with the mismatch of the version with the tag name. Your version is `1.0.5` but your tag is `1.0.5b`. Not sure if the b was a typo there

**Comment by rhukster** [comment]
Also you have two 1.0.5 releases.

**Comment by saitanay** [comment]
> Also you have two 1.0.5 releases.

There was only 1.0.5 release, but two tags. 

Anyways, cleaned them up. 

Tags:
![image](https://user-images.githubusercontent.com/3456349/74953004-17ebab80-5427-11ea-95e3-8cb0af9c53be.png)

Releases:
![image](https://user-images.githubusercontent.com/3456349/74953092-36ea3d80-5427-11ea-807c-ff19b781a3c7.png)

Manifest file lists the latest version
https://github.com/saitanay/grav-plugin-login-oauth2-auth0/blob/master/blueprints.yaml#L2

Hope that would get the gpm pick the right release version in the next cron run @rhukster

**Comment by w00fz** [comment]
That should do it!
We are working on a better system but it’s not quite ready yet.

**Comment by w00fz** [comment]
Your 1.0.5 release has been picked up now 👍
