### ISSUE TITLE
Plugin dependency not working in GPM

### ISSUE THREAD

**Issue by saitanay** [getgrav/grav#2833]
Plugin https://github.com/saitanay/grav-plugin-login-oauth2-auth0 defines plugin https://github.com/trilbymedia/grav-plugin-login-oauth2 as a dependency. 

In the blueprint file of grav-plugin-login-oauth2-auth0 , i have defined the dependency as 
```
dependencies:
  - { name: login-oauth2 }
```
Also tried defining dependency to a specific version like
```
dependencies:
  - { name: login-oauth2, version: '~2.0.2' }
```

I have already installed the dependency module via gpm, which works fine
```
$ bin/gpm install login-oauth2
GPM Releases Configuration: Stable
Preparing to install Login OAuth2 [v2.0.2]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!
Clearing cache
Cleared:  /Applications/MAMP/htdocs/grav/cache/doctrine/*
Cleared:  /Applications/MAMP/htdocs/grav/cache/compiled/*
Touched: /Applications/MAMP/htdocs/grav/user/config/system.yaml
```

Installing plugin grav-plugin-login-oauth2-auth0 via gpm gives a dependency error even if the dependency is already installed. 
```
$ bin/gpm install login-oauth2-auth0
GPM Releases Configuration: Stable
Dependency login-oauth2 is required in an older version than the one installed. This package must be updated. Please get in touch with its developer.
```

**Comment by w00fz** [comment]
Semver is not fully supported for version of dependencies, we are already aware and looking at improving that. Try `version: '>=2.0.2'`

**Comment by saitanay** [comment]
Created a new release that gives dependency version in blueprint as 
```
dependencies:
  - { name: login-oauth2, version: '>=2.0.2' }
```

Let us see if that works after gpm picks the latest release. Will report here.

**Comment by saitanay** [comment]
That sort of worked. GPM based installation seems to work now. Will be closing this ticket after confirmation from one another user who is trying the same on a fresh installation of grav.

**Comment by saitanay** [comment]
```
dependencies:
  - { name: login-oauth2, version: '>=2.0.2' }
```

That worked for a while. 

On a new installation of grav, either because this is a newer version of grav1.7.0-rc.6 than earlier (1.6.21), or because i am using a newer version of login-oauth2 (v2.0.3) than earlier (v2.0.2), grav still shows the dependency warning, although the module works fine after installation.
