### ISSUE TITLE
Flex objects breaks during update

### ISSUE THREAD

**Issue by SjoerdSmeets** [getgrav/grav#2834]
On my local install of the beta 1.7 just updated to the latest rc6.
After that upgraded the plugins. While updating to the latest Flex Objects plugin i get a Crikey message. 

Flex: Blueprint file for flex-pages is missing.

Howto fix this?

**Comment by mahagr** [comment]
Edit file `user/config/plugins/flex-objects.yaml` and remove the line from it.

**Comment by mahagr** [comment]
(Note to myself: we need to somehow deal with missing blueprints)

**Comment by mahagr** [comment]
Fixed in Flex Objects plugin: https://github.com/trilbymedia/grav-plugin-flex-objects/commit/ebf6120fd2673266d50cd56ac5a50ce0819a6d47

**Comment by SjoerdSmeets** [comment]
Tried several things to make it work, even deleting the plugin. After deleting, the admin required Flex Objects, after installing the latest version this crashes as well.

Is the commit you did already in the latest version?

**Comment by mahagr** [comment]
Looks like this has not been released yet (would also be closed if it was).
