### ISSUE TITLE
Error while trying to download update

### ISSUE THREAD

**Issue by thagxt** [getgrav/grav#2835]
I'm trying to update from v1.6.19 to v1.6.21, thru the Admin and this is what I get:

`Error while trying to download (code: 0): https://getgrav.org/download/core/grav-update/1.6.21 Message: URL using bad/illegal format or missing URL malformed`

Plus it says "`You're offline`", but I'm clearly not.

I'm able to update Plugins!

**Comment by mahagr** [comment]
@rhukster @w00fz Have you seen this error before?

**Comment by thagxt** [comment]
Update: I was able to update the core via FTP, and now everything works. 
`"You're offline"` still appears in admin.

**Comment by rhukster** [comment]
Are you behind a proxy server or something?

**Comment by w00fz** [comment]
This is how I calculate if you are online/offline: https://developer.mozilla.org/en-US/docs/Web/API/Window/offline_event

> The offline event of the Window interface is fired when the browser has lost access to the network and the value of Navigator.onLine switches to false.

**Comment by rhukster** [comment]
Or do you run some kind of firewall software that could be limiting external access?

**Comment by thagxt** [comment]
Yes, it was a firewall problem.
