### ISSUE TITLE
Installation on Windows with Composer fails

### ISSUE THREAD

**Issue by davidjimenez75** [getgrav/grav#2838]
Windows 10 64bits using cmd as console:

    composer create-project getgrav/grav ./grav-test
    ...
    Package facebook/webdriver is abandoned, you should avoid using it. Use php-webdriver/webdriver instead.
    Generating autoload files
    ocramius/package-versions:  Generating version class...
    ocramius/package-versions: ...done generating version class
    > bin/grav install
    'bin' is not recognized as an internal or external command,
    operable program or batch file.
    Script bin/grav install handling the post-create-project-cmd event returned with error code 1

HOW I SOLVED: You must enter to the Grav project folder created by Composer and do the install manually:

    cd ./grav-test
    php ./bin/grav install

Tested on Windows 10 with Laragon and composers:

    composer --version
    Composer version 1.9.1 2019-11-01 17:20:17

And 

    composer --version
    Composer version 1.9.3 2020-02-04 12:58:49

**Comment by rhukster** [comment]
yes you have to be in the Grav folder, as that is where composer.json/composer.lock files reside.

**Comment by davidjimenez75** [comment]
Please dont close the Issue, the fail is real. the script is not executed in windows.

    > bin/grav install
    'bin' is not recognized as an internal or external command,
    operable program or batch file.
    Script bin/grav install handling the post-create-project-cmd event returned with error code 1

**Comment by rhukster** [comment]
Unless you are running in WSL, you generally need to prefix PHP commands with the php executable.  An you will need to provide the path if you have not setup the php executable directory in your system path setting.

https://learn.getgrav.org/16/cli-console/command-line-intro#windows

**Comment by davidjimenez75** [comment]
I just create the issue to know if this install error could be solved detecting if the installation is on  Windows or linux.

Maybe is a minority problem and we must just close this definitely, thanks for your time.

**Comment by mahagr** [comment]
Not really as the command is in the `composer.json` file.

**Comment by ThomasJanUta** [comment]
Related issue: <https://github.com/getgrav/grav/issues/402>

```
composer create-project getgrav/grav ~/webroot/grav
```

> 'bin' is not recognized as an internal or external command,
> operable program or batch file.
> Script bin/grav install handling the post-create-project-cmd event returned with error code 1

Make sure PHP script and the path to `/bin/grav` is correct
```
cd C:\Users\User\path-to\grav
C:\path-to\php74\php.exe .\bin\grav install
```
