### ISSUE TITLE
Toggleable fields get set to false after save. (1.6)

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav#2840]
For example, setting Visible to false works fine.
But the next time you save the page, Toggleable will be set to false so it goes back to default value (true) making the page visible again.

Set some settings to false
![2](https://user-images.githubusercontent.com/11572524/75443916-6b329200-5930-11ea-99c8-4fd764dff009.jpg)

After save
![3](https://user-images.githubusercontent.com/11572524/75443918-6b329200-5930-11ea-8cee-b4336e0c2e95.jpg)

After a second save without touching anything.
![4](https://user-images.githubusercontent.com/11572524/75443919-6b329200-5930-11ea-85f5-7018c5b00e57.jpg)

This was tested with a fresh install of 1.6.21 Grav core + Admin from getgrav.org
**This seems to be fixed in 1.7**

**Comment by mahagr** [comment]
Fixed in form and admin 1.9/1.10.
