### ISSUE TITLE
[Question] Custom twig filter/function doesn't work in evaluate/evaluate_twig

### ISSUE THREAD

**Issue by jp2masa** [getgrav/grav#2842]
## Repro

```php
    public function onTwigInitialized()
    {
        $this->grav['twig']->twig()->addFilter(new \Twig_SimpleFilter('myfilter', [$this, 'myfilter']));
    }

    public function myfilter($a)
    {
        return 10;
    }
```

Then in a twig template:

```twig
{{ evaluate("5|myfilter") }}
```

It will fail with a "Unknown "myfilter" filter in ..." error.

This works:

```twig
{{ 5|myfilter }}
```

It also fails for functions and `evaluate_twig`.

Is this supposed to work?

**Comment by rhukster** [comment]
That should work as long as you also listen registered `onTwigInitialized` event.
I do this all the time.

For example:

https://github.com/getgrav/grav-plugin-shortcode-core/blob/eeeee6e725ff870cae968f59602c9a7d20ab2766/shortcode-core.php#L61

https://github.com/getgrav/grav-plugin-shortcode-core/blob/eeeee6e725ff870cae968f59602c9a7d20ab2766/shortcode-core.php#L225

**Comment by jp2masa** [comment]
I have this, although I did not refer it in the issue:

```php
    public static function getSubscribedEvents()
    {
        return
        [
            'onTwigInitialized' => ['onTwigInitialized', 0]
        ];
    }
```

Also, as I stated before:

> This works:
> ```
> {{ 5|myfilter }}
> ```

It only doesn't work when evaluated using `evaluate`/`evaluate_twig` functions.

Am I listening `onTwigInitialized` the wrong way?

**Comment by hughbris** [comment]
@mahagr when you close old issues especially, would you mind adding a few words why? It can be frustrating when searching for issue solutions to see something similar and not be clear about a resolution, if any. Just "could not reproduce", "can't understand" would be adequate :)

**Comment by mahagr** [comment]
Evaluate creates a new twig environment, which only loads the default Grav extension.

To be honest, I wouldn't even fix that as I think the feature is already unsafe to use and should be sandboxed.
