### ISSUE TITLE
striptags not taking markdown off the page summary or contents

### ISSUE THREAD

**Issue by thejame** [getgrav/grav#2844]
Trying to use summary|striptags to take markdown out of the page.summary or page.contents when listing posts in a page collection. Page renders the h1-->h6 tags and bullet points if they are in the page contents or summary.

`
{% set featured_posts = page.collection %}
{% for featured in featured_posts %}    
            {{ featured.summary|striptags }}
{% endfor %}
`

I can try `|raw|striptags|e` or `|striptags` and still get the same html in the output.

![featured](https://user-images.githubusercontent.com/6295224/75730314-6740a000-5ca1-11ea-89fc-c6c18f791479.PNG)

**Comment by mahagr** [comment]
https://twig.symfony.com/doc/1.x/filters/striptags.html

It should work. What happens if you pass empty string as the parameter?

**Comment by thejame** [comment]
I'm not sure what happened but I can't replicate the issue now. Maybe a cache clear did it. I also re-formatted my Markdown document so maybe cleaning it up and adding the correct spacing around the "===" break helped. Thanks.
