### ISSUE TITLE
Error while trying to download (code: 0) 

### ISSUE THREAD

**Issue by jockel127** [getgrav/grav#2848]
I got the same issue like in this issue-report: https://github.com/getgrav/grav/issues/2835
I deactivated the firewall and my DNS-blocker temporarily but it still doesn't work. :(
In my case, there was no report `you are offline`
Can you please help me? I haven't any clues anymore :(

**Comment by rhukster** [comment]
Have you checked the standard stuff in the docs? https://learn.getgrav.org/16/troubleshooting/common-problems#cannot-connect-to-the-gpm

**Comment by Memurame** [comment]
I had the same mistake.
[This page helped me.](https://learn.getgrav.org/16/troubleshooting/proxy)

It was up to me to fopen.
