### ISSUE TITLE
Load .yml files as well as .yaml

### ISSUE THREAD

**Issue by Rainbowlemon** [getgrav/grav#2849]
I've just spent half a day trying to figure out why my blueprints weren't working before realising that Grav specifically only works with `.yaml` files, not `.yml`. It would be great if this is documented somewhere, and even better if Grav checked for both file extensions!

**Comment by rhukster** [comment]
According to the [YAML.org FAQ](https://yaml.org/about.html):

> FAQ
>
> **Is there an official extension for YAML files?**
>
>  Please use ".yaml" when possible.

**Comment by Rainbowlemon** [comment]
'Where possible' doesn't mean ".yml files won't load" though. Perhaps worth changing this to 'Grav will only load yaml files with the `.yml` extension'?
