### ISSUE TITLE
php72 on centos8 problems

### ISSUE THREAD

**Issue by ghost** [getgrav/grav#2854]
i am trying to install gravecms 1.6.22 on a centos 8.1.1911 (Core) with the default php (version 7.2) in his repository.
unfortunatly the installation crashed every time. 
if i install all requirements of php and navigate to the site in a browser, its occured the notification: 

"Please run: bin/grav install"

when i start bin/grav install, then i receive this notification:

Preparing to install vendor dependencies...

Fatal error: Uncaught Error: Call to undefined function Composer\Json\json_decode() in phar:///var/www/gravecmstest.net/bin/composer.phar/src/Composer/Json/JsonFile.php:153
Stack trace:
#0 phar:///var/www/gravecmstest.net/bin/composer.phar/src/Composer/Factory.php(290): Composer\Json\JsonFile->validateSchema(1)
#1 phar:///var/www/gravecmstest.net/bin/composer.phar/src/Composer/Factory.php(576): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), './composer.json', false)
#2 phar:///var/www/gravecmstest.net/bin/composer.phar/src/Composer/Console/Application.php(345): Composer\Factory::create(Object(Composer\IO\ConsoleIO), NULL, false)
#3 phar:///var/www/gravecmstest.net/bin/composer.phar/src/Composer/Console/Application.php(458): Composer\Console\Application->getComposer(false, false)
#4 phar:///var/www/gravecmstest.net/bin/composer.phar/src/Composer/Console/Application.php(156): Composer\Console\Application->getPluginCommands()
#5 phar:///var/www/gravecmstest.net/bin/composer.phar/vendor/symfony/console/Application.php(117): Composer\Console\Ap in phar:///var/www/gravecmstest.net/bin/composer.phar/src/Composer/Json/JsonFile.php on line 153
#5 phar:///var/www/gravecmstest.net/bin/composer.phar/vendor/symfony/console/Application.php(117): Composer\Console\Ap in phar:///var/www/gravecmstest.net/bin/composer.phar/src/Composer/Json/JsonFile.php on line 153

my installed php modules:

[PHP Modules]
apcu
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
Phar
readline
Reflection
session
SimpleXML
sockets
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

my php version:

PHP 7.2.11 (cli) (built: Oct  9 2018 15:09:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

what is the solution?

**Comment by 0plan** [comment]
okay i think i found now a solution, maybe only a workaround. /bin/grave clean helps me. but this is a random found for a solution. is this the normal way to install grav cms?

**Comment by rhukster** [comment]
First, I suggest trying the pre-packaged version of Grav which includes all the vendor libraries already: https://getgrav.org/downloads

If that works, then the problem is not with Grav, but more likely your installation of composer or PHP itself.
