### ISSUE TITLE
Ackee Analytics

### ISSUE THREAD

**Issue by mayailkour** [getgrav/grav#2856]
Is it easy to use [Ackee](https://ackee.electerious.com/) by @electerious on [Grav](https://getgrav.org/) websites? 🤔
I only found a Google Analytics plugin and would use that one otherwise but a more privacy-friendly solution might be better.

**Comment by rhukster** [comment]
It's easy to use any analytics tool on Grav.  You don't actually need a plugin, you can simply paste the analytics tracking code into your theme's files.  Typically this is `partials/base.html.twig`...

**Comment by mayailkour** [comment]
That's great to know. Thanks for the info. 😎
