### ISSUE TITLE
[add-resource] New Plugin markdown-details

### ISSUE THREAD

**Issue by bitstarr** [getgrav/grav#2858]
I would like to add my new plugin to the Grav Repository.
[Here are the project details](https://github.com/bitstarr/grav-plugin-markdown-details)

**Comment by rhukster** [comment]
I will add this, but you should probably know that Grav 1.7 contains the updated Parsedown 1.7 version that seems to break a few markdown specific plugins.  You might want to test with the latest RC version also.

**Comment by rhukster** [comment]
added to GPM
