### ISSUE TITLE
[task] Upgrade vulnerable system asset jquery 3.3.1

### ISSUE THREAD

**Issue by Rotzbua** [getgrav/grav#2859]
Hi,

while scanning my website there was found a vulnerability. Jquery3 library should be upgraded to new minor.

Reference:
https://snyk.io/vuln/npm:jquery?lh=3.3.1

Best wishes

**Comment by rhukster** [comment]
This was already updated in Grav 1.7, but i've also upgraded in 1.6/develop branch already.

**Comment by Rotzbua** [comment]
@rhukster Thanks and sorry I thought that `develop` is the latest branch.
