### ISSUE TITLE
navigation in RTFM breaks if dir titles are changed

### ISSUE THREAD

**Issue by notklaatu** [getgrav/grav#286]
With the RTFM theme, I have the default set of user/pages:

```
|-- 01.basics
|   |-- 01.overview
|   |   `-- docs.md
|   |-- 02.requirements
|   |   |-- 01.sub-topic
|   |   |   |-- 01.sub-sub-topic
|   |   |   |   `-- docs.md
|   |   |   `-- docs.md
|   |   `-- docs.md
|   |-- 03.installation
|   |   `-- docs.md
|   `-- chapter.md
|-- 02.intermediate
|   |-- 01.topic-1
|   |   `-- docs.md
|   |-- 02.topic-2
|   |   `-- docs.md
|   |-- 03.topic-3
|   |   `-- docs.md
|   |-- 04.topic-4
|   |   `-- docs.md
|   `-- chapter.md
|-- 03.advanced
|   |-- 01.adv-topic-1
|   |   `-- docs.md
|   |-- 02.adv-topic-2
|   |   `-- docs.md
|   `-- chapter.md
`-- index.html
```

If I changed the title of a directory, going to the site lands me on an error page.

For instance:

    $ mv 01.basics 01.foo
    $ sed -i 's/Basics/Foo/' 01.foo/chapter.md

I've removed the /cache dir I found at /grav root, but error persists.

I assume the name of the initial page is being set somewhere, but I can't determine where?

**Comment by rhukster** [comment]
You need to change the homepage in your `user/config/system.yaml`.. It's the `home: alias:` setting.
