### ISSUE TITLE
bin/gpm index - error

### ISSUE THREAD

**Issue by pizu** [getgrav/grav#2860]
Hi,

Am trying to install Grav and when doing: `bin/gpm index` am getting the bellow error:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/openssl.so' - /usr/lib64/php/modules/openssl.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  Module 'zip' already loaded in Unknown on line 0
PHP Fatal error:  Uncaught Error: Class 'Parsedown' not found in /var/www/html/tst01nettools01portal/grav/system/src/Grav/Common/GPM/Local/Package.php:26
Stack trace:
#0 /var/www/html/tst01nettools01portal/grav/system/src/Grav/Common/GPM/Local/AbstractPackageCollection.php(22): Grav\Common\GPM\Local\Package->__construct(Object(Grav\Common\Data\Data), 'plugins')
#1 /var/www/html/tst01nettools01portal/grav/system/src/Grav/Common/GPM/Local/Plugins.php(29): Grav\Common\GPM\Local\AbstractPackageCollection->__construct(Array)
#2 /var/www/html/tst01nettools01portal/grav/system/src/Grav/Common/GPM/Local/Packages.php(19): Grav\Common\GPM\Local\Plugins->__construct()
#3 /var/www/html/tst01nettools01portal/grav/system/src/Grav/Common/GPM/GPM.php(59): Grav\Common\GPM\Local\Packages->__construct()
#4 /var/www/html/tst01nettools01portal/grav/system/src/Grav/Console/Gpm/IndexCommand.php(95): Grav\Common\GPM\GPM->__construct(false)
#5 /var/www/html/tst01nettools01portal/grav/system/src/Grav/Console/ConsoleCommand.php(41): Grav\Console\Gpm\Ind in /var/www/html/tst01nettools01portal/grav/system/src/Grav/Common/GPM/Local/Package.php on line 26

Thanks.

**Comment by rhukster** [comment]
According to your error output, you need to install OpenSSL.

**Comment by pizu** [comment]
Hi,

Thanks for your quick reply.

open ssl is installed.

![image](https://user-images.githubusercontent.com/7047326/77075472-ae919500-69f2-11ea-9be7-c0fbd62d8d4d.png)

**Comment by rhukster** [comment]
I would suggest googling this, as it could be many things, all of which are related to the OS and how OpenSSL is installed:

https://www.google.com/search?q=openssl.so%3A+cannot+open+shared+object+file&oq=openssl.so%3A+cannot+open+shared+object+file&aqs=chrome..69i57.718j0j1&sourceid=chrome&ie=UTF-8
