### ISSUE TITLE
[add-resource] Plugin - Mobile Detect

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav#2861]
Hello,

i had 2 new release for https://github.com/dimitrilongo/grav-plugin-mobile-detect, 1.4.1 & 1.4.2, but the GPM show  1.4 (there is an issue in 1.4), that's why i made new release, i change also date format in changelog, because it seems there is an issue with european format date.

![screenshot 2020-03-20 à 09 02 18](https://user-images.githubusercontent.com/3842190/77145718-a0428800-6a89-11ea-886c-4371325d2ef6.png)
![screenshot 2020-03-20 à 09 01 58](https://user-images.githubusercontent.com/3842190/77145730-a7699600-6a89-11ea-9f8a-748539065d8e.png)

can you take a look please ?
Thanks

**Comment by rhukster** [comment]
The problem is you never bumped the version in blueprints:

https://github.com/dimitrilongo/grav-plugin-mobile-detect/blob/v1.4.2/blueprints.yaml

**Comment by dimitrilongo** [comment]
@rhukster thanks
but about changelog i have error 500, changelog is empty on https://getgrav.org/downloads/plugins

i thought it was date format, i change them to US date format but still same issue

**Comment by rhukster** [comment]
I’ll dig deeper.

**Comment by dimitrilongo** [comment]
@rhukster it's ok now, it seems issue with wrong date format ( i change all date to U.S format)
