### ISSUE TITLE
[add-resource] New Plugin: Edit Media Metadata from within the Admin plugin

### ISSUE THREAD

**Issue by clivebeckett** [getgrav/grav#2862]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **[clivebeckett/grav-plugin-admin-addon-media-metadata](https://github.com/clivebeckett/grav-plugin-admin-addon-media-metadata)**

It’s an addon for the Admin plugin and lets you edit metadata for media files in the Page Media Browser by creating and editing *.meta.yaml files.

**Comment by rhukster** [comment]
Added to GPM for next update.
