### ISSUE TITLE
auto_url_links does not work

### ISSUE THREAD

**Issue by Balindil** [getgrav/grav#287]
Hello,

I tried
```yaml
markdown:
  auto_url_links: true
```
and it seems it doesn't work. If I write ```<address@example.com>``` in markdown there is no link in source code or front view visible.

**Comment by flaviocopes** [comment]
I think the problem is that an email is not a link. Does it work for links?

**Comment by Balindil** [comment]
No, ```<http://example.com/>``` also does not work.

**Comment by Balindil** [comment]
I see the problem. I cannot use this:
```html
<div markdown="1">
  ...
  <http://example.com/>
  ...
</div>
```
Shouldn't it work?

**Comment by flaviocopes** [comment]
URLs in normal markdown work:

```

# Title
This is a link http://example.com
```

is correctly converted.
