### ISSUE TITLE
Grav admin add account appears to fail.

### ISSUE THREAD

**Issue by bbhack** [getgrav/grav#2872]
This is regarding a fresh install of Grav v1.7.0-rc.8 - Admin v1.10.0-rc.8:

When a new account is added in admin and it’s fields populated, trying to save it generates a 404 error. Then an attempt to log in using the new account’s username and password fails with “Login failed…”. The initial admin account works correctly. This is the case on both my local development server and on the production server.

In user/accounts a new yaml file is created with what looks like a 32 digit hex number as its name (e.g. ‘b5ec29f160ca2a63e70f08d39f6792bb.yaml’). If this file name is used as the username or if the yaml file name is changed to intended username, everything works correctly. I assume the 404 is because admin is looking for a yaml file with the correct username and but at login it expects the numeric name.

**Comment by localnetwork** [comment]
I also encounter this:

**After creating an account**
![grav-add-user-404](https://user-images.githubusercontent.com/15809239/78322564-ac5a3980-75a1-11ea-9722-b29a6cdcf8b9.jpg)

**when you access the username you entered**
![grav-user-username](https://user-images.githubusercontent.com/15809239/78322583-c1cf6380-75a1-11ea-8de1-8843dc422248.jpg)

**Comment by mahagr** [comment]
This one has actually been fixed already.

**Comment by pushpinder6805** [comment]
adding a new admin user , still give error , site is reachable when deleting the yaml file ?
