### ISSUE TITLE
[add-resource] New Plugin: grav-plugin-tabs

### ISSUE THREAD

**Issue by domsson** [getgrav/grav#2875]
I would like to add my new plugin to the Grav Repository.
Here are the project details: [grav-plugin-tabs](https://github.com/domsson/grav-plugin-tabs)

The plugin provides four components:

- `blueprints/partials/tabs.yaml`, for inclusion in a theme's blueprint
- `templates/partials/tabs.html.twig`, for inclusion in a theme's template
- `js/tabs.js`, enables the Tab functionality
- `js/tabs.css` (optional), simple built-in CSS

With these, the plugin enables easy creation of tabbed content, no matter the page type (regular or modular). It is aimed mainly at theme developers, as it requires the partial template to be included in another page template to function.

There can be multiple tab sets on any given page and all tabs can retain their state (active/hidden) via URL fragments, so sharing links to a page with tabs will re-open the tabs accordingly. The plugin differs from the Shortcode UI plugin in that it **only** provides tabs, plus it does not do so via shortcodes.

**Comment by rhukster** [comment]
Added to GPM for next update
