### ISSUE TITLE
Where should I put static files, e.g. robots.txt & .well-known/* ?

### ISSUE THREAD

**Issue by Syndesi** [getgrav/grav#2876]
Hi,

is there a place for static assets like `robots.txt` and `.well-known/*`? And if so, can themes define their own static assets?

**Comment by ricardo118** [comment]
Regarding robots you can place them as per this recipe on the documentation [https://learn.getgrav.org/16/cookbook/general-recipes#display-different-robots-txt-contents-for-different-environments](Robots txt), alternatively you could just use the root folder
