### ISSUE TITLE
Handle HTTP_X_FORWARDED_HOST variable

### ISSUE THREAD

**Issue by A----** [getgrav/grav#2877]
I wonder why `HTTP_X_FORWARDED_HOST` (from the X-Forwarded-Host header) is not handled. This (unofficial) header is sent by reverse proxies to tell the "real" address for the website.

Is this because it might be used to poison one's cache? (In case it's not vetted by the reverse proxy).

As a matter of fact, other variables of this kind are used ( `HTTP_X_FORWARDED_PORT` ).

Fixing this is pretty easy it seems. In `system\src\Grav\Common\Uri.php`, line 1172:

```php
        if (isset($env['HTTP_X_FORWARDED_HOST'])) {
            $hostname = $env['HTTP_X_FORWARDED_HOST'];
        } else if (isset($env['HTTP_HOST'])) {
 ```

I can do a PR if needed.

In the meantime, I can use the `custom_base_url` options, which works.

**Comment by rhukster** [comment]
Please provide a PR. Thanks!

**Comment by A----** [comment]
Done!
