### ISSUE TITLE
Add option to disable breaking markdown links

### ISSUE THREAD

**Issue by tg-x** [getgrav/grav#2882]
Grav breaks links by [removing certain attributes](https://github.com/getgrav/grav/blob/ef80e28d1db6a8d59581d77b26231169a7194c8b/system/src/Grav/Common/Page/Markdown/Excerpts.php#L90) if it finds them.
There should be a global configuration option to turn this off instead of adding `&noprocess` one by one to each link.

This is an unintuitive anti-feature that breaks user expectations of being able to link to pages without unintended side-effects of breaking links by silently dropping commonly used attributes.
There have been several reports before from users unwittingly stumbling upon this, e.g. #989, #1877

**Comment by rhukster** [comment]
Only a few reports in 5 years, disabling site-wide would mean huge chunks of functionality suddenly not working, leading to more issues/questions/etc. Might be better to put a good entry in the doc's so people find the solution quickly after googling.

**Comment by OleVik** [comment]
This warrants a global option to disable though, as there are many cases where you either need the pass through of query parameters, or media-processing disabled altogether. It would be advantageous to be able to get the media with query-parameters and have Grav process it afterwards.

**Comment by otahirs** [comment]
I ran into the same issue.

**Comment by rhukster** [comment]
Fixed via https://github.com/getgrav/grav/commit/bfbe4ce1b847ade2df074b1df5900b1daa3a2e7f
