### ISSUE TITLE
install time : possible misleading permission check reported

### ISSUE THREAD

**Issue by msharp1** [getgrav/grav#2883]
Grav 1.6.23.

I've been using debian 10 with nginx and php-fpm running the default user `www-data`. I've installed grav with git and `bin/grav install` as invited in the docs.

The base folder looks like this:
```
drwxr-xr-x  2 pi pi         4096 Apr 18 08:43 assets
drwxr-xr-x  2 pi pi         4096 Apr 18 08:43 backup
drwxr-xr-x  2 pi pi         4096 Apr 18 08:43 bin
drwxrwxr-x  4 pi www-data   4096 Apr 18 15:03 cache
-rw-r--r--  1 pi pi       141554 Apr 18 08:43 CHANGELOG.md
-rw-r--r--  1 pi pi          302 Apr 18 08:43 codeception.yml
-rw-r--r--  1 pi pi         3216 Apr 18 08:43 CODE_OF_CONDUCT.md
-rw-r--r--  1 pi pi         3808 Apr 18 08:43 composer.json
-rw-r--r--  1 pi pi       198558 Apr 18 08:43 composer.lock
-rw-r--r--  1 pi pi         7098 Apr 18 08:43 CONTRIBUTING.md
drwxr-xr-x  2 pi pi         4096 Apr 18 08:43 images
-rw-r--r--  1 pi pi         1710 Apr 18 08:43 index.php
-rw-r--r--  1 pi pi         1071 Apr 18 08:43 LICENSE.txt
drwxr-xr-x  2 pi pi         4096 Apr 18 08:43 logs
-rw-r--r--  1 pi pi           76 Apr 18 08:43 now.json
-rw-r--r--  1 pi pi         6701 Apr 18 08:43 README.md
-rw-r--r--  1 pi pi          227 Apr 18 08:43 robots.txt
drwxr-xr-x 10 pi pi         4096 Apr 18 08:43 system
drwxr-xr-x  8 pi pi         4096 Apr 18 08:43 tests
drwxr-xr-x  2 pi pi         4096 Apr 18 08:43 tmp
drwxr-xr-x  8 pi pi         4096 Apr 18 08:43 user
drwxr-xr-x 28 pi pi         4096 Apr 18 15:03 vendor
drwxr-xr-x  2 pi pi         4096 Apr 18 08:43 webserver-configs
```
As you see I already started tweaking the permissions for the `cache` folder.
But what I think is wrong is I got many folders being reported as **... is writable** and looks OK while they are not. See the permission above, PHP cannot write into them. Am I missing something ?

![image](https://user-images.githubusercontent.com/5676327/79641632-06115500-8199-11ea-845d-2ded2f0cf234.png)

**Comment by rhukster** [comment]
Is your web server running as pi user? If not then the files are not going to be writable by php (which runs as web server by default).  If you run php-fpm then it has its own user/group permission setting you can play with.

**Comment by msharp1** [comment]
> Is your web server running as pi user? 

Hi thanks for your answer. No it's not. In my post I'm mentioning `www-data` for both PHP-FPM and Nginx , see:

```
www-data 19385  0.0  0.7  51064  7020 ?        S    15:08   0:00 nginx: worker process
www-data 19386  0.0  0.7  51064  7008 ?        S    15:08   0:00 nginx: worker process
www-data 19387  0.0  0.7  51064  6780 ?        S    15:08   0:00 nginx: worker process
www-data 19388  0.0  0.6  51064  5764 ?        S    15:08   0:00 nginx: worer process
...
www-data 14890  0.0  2.4 212592 23392 ?        S    15:01   0:00 php-fpm: pool www
www-data 14891  0.0  2.4 212592 23628 ?        S    15:01   0:00 php-fpm: pool www

```

What I'm telling is, the green checks should be red, as `www-data` don't have write access to the `system` folder for instance.

**Comment by msharp1** [comment]
hmm the problem is maybe grav runs into a subfolder, while nginx nginx `location` points to the root. I'll do another test and report.

**Comment by msharp1** [comment]
It's not. Might it be possible that we miss a test case in https://github.com/getgrav/grav-plugin-problems/blob/621fac5249ef7e05c9fd2bb05df5b119c333157b/classes/Problems/EssentialFolders.php#L45 ?

**Comment by b7s9** [comment]
I had this same problem recently. What worked for me was running this from the root of the grav directory

```bash
sudo chown $USER:www-data -R ./
```

Notice that `cache` is already writable for you because the `www-data` group has been given write access.

**Comment by rhukster** [comment]
The check and message is valid.. to the webserver those files are not writable as it's running under a different user.  Closing...
