### ISSUE TITLE
Add operator for complex collection definition

### ISSUE THREAD

**Issue by bitstarr** [getgrav/grav#2885]
I would like to request a feature for page collections. See this example:
````
content:
    items:
        - '@page.children': '/productspace/products'
        - '@taxonomy.audience': owner
````
At the moment both querys parts of ``items`` are comulated (OR). I would like to combine them with AND, so that only pages with the specific taxonomy from that folder will be in the results.

In this case the primary request to get the pages by taxonomy. But I wanted to avoid getting pages that have, for whatever reason, this taxonomy but are not part of the products.

**Comment by rhukster** [comment]
Frankly this kind of complex behavior is best handled in a bit of custom PHP code.. see: https://learn.getgrav.org/16/content/collections#custom-collection-handling-with-oncollectionprocessed-event
