### ISSUE TITLE
Image on shared link NOt works on Twitter 

### ISSUE THREAD

**Issue by Potitus** [getgrav/grav#2887]
Good morning,
when i share on twitter or telegram one link of my items on the site , the image not appear over the link meanwhile it works on facebook and linkedin.
there is something setting to do? I have installed SEO plugin but it still not work on twitter and telegram only

**Comment by rhukster** [comment]
Which SEO plugin?

**Comment by Potitus** [comment]
this one https://github.com/clemdesign/grav-plugin-adsense

**Comment by rhukster** [comment]
Sounds like you should create the issue on their repo? Grav itself is not setting any opengraph image tags automatically.

**Comment by Potitus** [comment]
sorry for mistake, im new ....Im studying about grav
