### ISSUE TITLE
Dynamic page visibility throws a critical error

### ISSUE THREAD

**Issue by MakaryGo** [getgrav/grav#2889]
|Grav|Admin|Login|
|---|---|---|
|  v1.7.0-rc.3 | v1.10.0-rc.3|  v3.0.5|

When `dynamic_page_visibility:` is set to `true` Grav throws a critical error:

```php
grav.CRITICAL: Call to a member function header() on null
```

Full log included:
[error.last.log](https://github.com/getgrav/grav-plugin-login/files/4077472/error.last.log)

**Comment by mahagr** [comment]
@MakaryGo Could you test with latest Grav CI build if your issue is fixed? We're going to do release maybe tomorrow.

Thanks!
