### ISSUE TITLE
[add-resource] Web Monetization Plugin

### ISSUE THREAD

**Issue by arkhi** [getgrav/grav#2893]
Hello,

As a first attempt at writing a public plugin, I would like to add a [Web Monetization Plugin](https://github.com/arkhi/grav-plugin-web-monetization) to the Grav Repository.

For now, it allows to:

- add a Wallet Pointer from the plugin configuration.
- create the proper `<meta>` tag in the `<head>` of the website.

I’m all hears if you have any comments, requests or suggestions. :)

**Comment by rhukster** [comment]
Added to GPM for next release
