### ISSUE TITLE
grav/admin Error 404

### ISSUE THREAD

**Issue by King-GO** [getgrav/grav#2899]
Windows 7, XAMPP
Grav upgrade 1.6.23 to 1.6.24 is successful, 
then upgrade all plugins and get Error 404 (Woops. Looks like this page doesn't exist.)
grav/admin
grav/admin/pages
grav/admin/plugins
grav/admin/config/site

--
plugins update available!
Admin Panel  v1.9.13
Breadcrumbs  v1.5.1
Email  v3.0.7
Form  v4.0.6
Login  v3.1.0 
 Shortcode Core  v4.2.2

**Comment by rhukster** [comment]
I can't really tell what happened from this. Does upgrading a second-time work? If you get an error, please get a screenshot of it.

**Comment by King-GO** [comment]
How to rollback to previous status without plugins updated?
![image](https://user-images.githubusercontent.com/54804407/80550424-ab76c500-89f2-11ea-820a-01ad5e99f2a8.png)

**Comment by rhukster** [comment]
I don’t see how any of those plugins would cause a page not found.
