### ISSUE TITLE
Dropbox plugin

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav#29]
I would love to have a dropbox plugin to sync data. There are several key things to consider:
1. webhook to automatically trigger a sync process
2. manual method to start sync process
3. sync from dropbox to grav
4. sync from grav to dropbox

**Comment by dfrankland** [comment]
Going off of what @rhukster said, I have tried to create a Dropbox plugin for Grav :+1: 
*It is still very untested and is probably written very badly, so I would love some feedback!*
**Check it out here: https://github.com/dfrankland/grav-plugin-dropbox**

Cheers!

**Comment by Deester4x4jr** [comment]
This would be really cool.  If you guys decide to go down this path, it would be cool to add support for box.com and
