### ISSUE TITLE
Blog plugin not stored with the correct name

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav#290]
The Blog plugin https://github.com/giansi/grav-plugin-blog is installed with the folder named `grav-plugin-blog` instead of `blog`.

As a side-effect, Blog in the admin-side plugins list is not ordered alphabetically but comes under the 'g' letter.

I don't notice anything strange in its blueprint that might cause this issue, so it might be related to the plugin repository.

**Comment by rhukster** [comment]
I actually think this is actually how we entered the plugin the GPM.. it should of just been 'blog' probably, but that's a little misleading and very general.

**Comment by flaviocopes** [comment]
Yes, maybe there should be some folder-based namespacing based on the plugin vendor? like `/giansi-blog` or something similar?

**Comment by rhukster** [comment]
I've updated the GPM to use the `blog` name
