### ISSUE TITLE
 Error while trying to download (code: ): https://getgrav.org/downloads/grav.json?v=1.5.5&stable=1

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav#2900]
I have a site stuck on Grav 1.5.5
It wont recognise any update options within the admin plugin.

if I ssh in remotely I cannot run

`bin/gpm selfupgrade -f`

I get 

```
In Response.php line 314:
                                                                                                     
Error while trying to download (code: ): https://getgrav.org/downloads/grav.json?v=1.5.5&stable=1
```

if I then run

`bin/gpm index -f`

it says 

```
GPM Releases Configuration: Stable
No data was found in the GPM repository stored locally.
```

Any idea what is going on?

If I log in to the remote site via Admin panel, the admin seems very slow which I have also experienced on other sites on the same server.

(could this be something to do with Serverpilot hosting / php versions)

**Comment by ricardo118** [comment]
if i were you id locally test the site with one of grav's latest RC versions then just replace the live one entirely via zip

**Comment by rhukster** [comment]
Really sounds like you have a server issue. The site is accessible, and others are having no problem reaching it.

When dealing with a truculent server it's best to try some direct curl/wget calls on the server, and perhaps a simple PHP script run from the command line to determine what's going on.

I don't think updating Grav will solve anything as it's clearly a server issue, but if you did want to reinstall, you can simply download/install a new Grav instance, and copy over your `user/` folder, then update the plugins.

**Comment by MattAppleton** [comment]
Thanks guys for the suggestions... in the end I just replaced the site with a fresh install via remote zip install of Grav — could have been the server. Equally the upload speeds on my home-working Covid broadband a re shocking so might be connectivity...

**Comment by jorgemfm** [comment]
I'm having the same problem.

I've tested by command line with **curl** and **wget** and its works with **curl** but **wget** I have to force ipv4

Forcing IPV4

```
wget -4  https://getgrav.org/notifications.json?1588099385
--2020-04-28 20:17:59--  https://getgrav.org/notifications.json?1588099385
Resolving getgrav.org (getgrav.org)... 45.79.6.45
Connecting to getgrav.org (getgrav.org)|45.79.6.45|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘notifications.json?1588099385’
```

Without forcing IPV4
```
wget https://getgrav.org/notifications.json?1588099385
--2020-04-28 20:18:07--  https://getgrav.org/notifications.json?1588099385
Resolving getgrav.org (getgrav.org)... 2600:3c00::f03c:91ff:fe61:8b0e, 45.79.6.45
Connecting to getgrav.org (getgrav.org)|2600:3c00::f03c:91ff:fe61:8b0e|:443...
```

I don't know what GRAV uses to make the request. Could if be related?

**Comment by jorgemfm** [comment]
Sorry, the issued got closed while I was writing.
Still gone leave what I found.

I Went to **Configuration > Advanced** and changed the **Remote Fetch Method** from **Auto** to **cURL** and it started working, than I tried **fopen** and was still working, then changed back to **Auto** and kept on working.

Don't know what happened, but something must have changed on the configuration file that maybe had a "unkown" value?

I have a few Grav installations and they all had the same problem.

Anyway, problem solved.

**Comment by MattAppleton** [comment]
OMG this is a life saver! thanks!

The whole admin started behaving much better after toggling **Remote fetch method**

Now the question is — WHY?!

**Comment by MattAppleton** [comment]
tested on two different sites now, this procedure seems to work well so far.

**Comment by jorgemfm** [comment]
If I have to guess (and I might be completely wrong), I think that maybe some problem with PHP fopen?

I've noticed this problem only today, and I think I used grav last week.
I did a server update last Thursday where PHP was updated

**Comment by MattAppleton** [comment]
the two sites where I see the issue were running php 7.2 on the same Serverpilot / Linode setup. AFAIK no updates there for a while...

**Comment by jorgemfm** [comment]
My PHP is 7.2.30

**Comment by MattAppleton** [comment]
So this issue seems to be solved, still a mystery as to _why_ it is happening though :) Closing...
