### ISSUE TITLE
Process Twig First renders headers as code

### ISSUE THREAD

**Issue by andreibereczki** [getgrav/grav#2903]
Hi, i have the following page content:
`# some h1 title`

if i activate the option "Process Twig First" in the Advanced Tab of the page, the h1 tag is not rendered anymore, instead the text **"# some h1 title"** is rendered inside `<pre><code>` blocks.

Is this per design? If so, what are feasible workarounds for the issue?

**Comment by rhukster** [comment]
It's not normal but greatly depends on your page layout, can you include a copy of your entire page in this issue? either upload it, or put it in a codeblock.
