### ISSUE TITLE
Inconsistent markdown parsing before and after twig

### ISSUE THREAD

**Issue by andreibereczki** [getgrav/grav#2904]
Hi, i have the following page content

<pre>
---
title: Services
process:
    markdown: true
    twig: true
twig_first: true
services:
    -
        section: green
        name: 'Custom Web Applications: Java, PHP, Node.js'
        url: '/services.html?view=web-applications&language=en'
---

some text here
{% for service in page.header.services %}
[{{ service.name }}]({{ service.url }}&classes=service-box,box-color-{{ service.section}})
{% endfor %}
some more text here</pre>

The expected output of the twig for loop is: `<a href="/services.html?view=web-applications&amp;language=en" class="service-box box-color-green">Custom Web Applications: Java, PHP, Node.js</a>`.

With the frontmatter option twig_first **enabled** i get the expected output but i can't use it because of #2903 
With the frontmatter option twig_first **disabled** i don't get the expected output, instead the output is: `<a href="/services.html?view=web-applications&amp;language=en&amp;classes=service-box,box-color-green">Custom Web Applications: Java, PHP, Node.js</a>`

My current workarround for the issue is to disable the frontmatter option twig_first and to render html inside the for loop, instead of markdown.

**Comment by ricardo118** [comment]
its recommended to  put the twig code in a twig template

**Comment by andreibereczki** [comment]
> its recommended to put the twig code in a twig template

It might be, but how do i then have that loop of items in between the text bits?
besides ... if this were not supported, why then would there be the option to process both, twig and markdown + the option to process twig first?

**Comment by ricardo118** [comment]
the option for processing twig first is usually for frontmatter variables like

```
email: {{ site.email }}
---
```
Something like that.

Regarding the 2 text bits, you could do blueprints as 1 example and having 2 editors in the page, one for top section one for bottom section.

another option is to use html not markdown inside the twig

```

some text here
{% for service in page.header.services %}
<a href="{{ service.url }}" class="service-box,box-color-{{ service.section}}">{{ service.name }}</a>
{% endfor %}
some more text here
```

**Comment by andreibereczki** [comment]
Hi @ricardo118,
thank you for the tips. I tried the html version (it's also written in my initial post) but i just noticed something weird. This is how those links are rendering now: 
`<a href="%7B%7B%20service.url%20%7D%7D" class="plus">Consulting</a>`
So service.url doesn't get rendered properly, but service.name does. Do you know if this is a know issue?

**Comment by rhukster** [comment]
I can't replicate this.  Your first version from the initial post works fine in Grav 1.6 and 1.7rc.  Perhaps you have changed some configuration that might be impacting it?

**Comment by markwtt** [comment]
I am having same issue as above when using  <a href=  tags with twig {{variable}} inserted within the tag. 
I am upgrading existing site that is still working fine on grav v1.5.3,  I made a copy of working site to development server then upgraded to latest grav v1.6.25 and also installed gantry 5.4.34.   I had assumed gantry causing the problem, but just dropped back to a non gantry theme and seeing same issue - example:

    <li> <a href= "{{p.route}}"> {{p.title}} </a> </li>

renders to

`<li> <a href="%7B%7Bp.route%7D%7D"> Expected Page Title </a> </li>`

Perhaps someone who knows more can shed light on this.
