### ISSUE TITLE
Redirects error

### ISSUE THREAD

**Issue by petira** [getgrav/grav#2905]
**Updated: 05/07/2020**

If a redirect to a URL with the same basis is set in `site.yaml`, the redirect is repeated, if the target page does not exist.

Specifically (if the target page does not exist):
```
redirects:
  /contact: /contacts
  /x: /xyyy
```

Entering the URL `http://www.example.com/contact` results in `http://www.example.com/contactsssssssssssssssssss` and an error **ERR_TOO_MANY_REDIRECTS**.

Another example:
`http://www.example.com/x` => `http://www.example.com/xyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy`

In this case, the page repeatedly calls itself instead of displaying an error page (404).

The result is a base (source) URL augmented with repeated characters that are additionally included in the target URL.

However, the redirect problem also occurs when the linked subpage does not exist in the URL.

Specifically, the following site structure exists:
```
root
   - home
   - contacts
     - owner
     - contact-form
   - ...
```
and the following redirect settings in `site.yaml`:
```
redirects:
  /contact: /contacts
```
The expected behavior (redirection) occurs in these cases:

1. `http://www.example.com/contact` => `http://www.example.com/contacts`
2. `http://www.example.com/contact/owner` => `http://www.example.com/contacts/owner`
3. `http://www.example.com/contact/contact-form` => `http://www.example.com/contacts/contact-form`

but when inserting a non-existent subpage into the URL, there is a problem with repeated redirects:
1. `http://www.example.com/contact/non-existent-page` => `http://www.example.com/contactsssssssssssssssssss/non-existent-page`
2. `http://www.example.com/contacts/non-existent-page` => `http://www.example.com/contactssssssssssssssssssss/non-existent-page`

**Comment by rhukster** [comment]
you need to use regex, because without it you are simply matching if the key (`/contact`) is in the URL and then redirecting to the value (`/contacts`), but then the key is in the URL again, just the start of the URL, so yes, that's going to cause an infinite loop.

The regex anchor for start of line is `^` and end of line is `$`, so, you probably need to use:

```
redirects:
  ^/contact$: /contacts
  ^/x$: /xyyy
```

**Comment by petira** [comment]
Thank you, the above works fine. I thought it was possible without the regex, but this solution is also satisfactory.

**Comment by joenovell** [comment]
Wow this DOES work! Knew I would like 'Andy Miller' I am organizing a new
Andy Miller email BOX here and time traveling back a couple weeks/years;

In the words of Seymore Gray:

>I would rather have two (2) Blue Oxen plowing my father's field than 1024
programmers!
