### ISSUE TITLE
[add-resource] New Plugin: Stamp

### ISSUE THREAD

**Issue by petira** [getgrav/grav#2908]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **https://github.com/petira/grav-plugin-stamp**.

This plugin automatically adds or changes date_modified, editor and revision to frontmatter when a page is saved via the Grav Admin Plugin.

**Comment by petira** [comment]
A new and significantly improved version (1.0.1) of the plugin is available. I will upload it as soon as the initialization version (1.0.0) is approved.

**Comment by rhukster** [comment]
Added to GPM for next update

**Comment by petira** [comment]
> Added to GPM for next update

Assumption when the plugin will be published?
