### ISSUE TITLE
page.children in twig return modulars too

### ISSUE THREAD

**Issue by ricardo118** [getgrav/grav#2909]
In discord a user with this setup:

![pages](https://cdn.discordapp.com/attachments/501854266873348112/709066307982852216/Bildschirmfoto_2020-05-10_um_17.35.58.png)

when running `{% for bikes in page.parent.children %}` its also returning _intro and _bikes however running `{% for bikes in page.parent.children.visible %}` the modular children no longer get printed

**Comment by rhukster** [comment]
In twig you are using the Page methods directly, this is not referring to collection filtering, so this is expected behavior.
