### ISSUE TITLE
Block direct access to git folder

### ISSUE THREAD

**Issue by fantasticme** [getgrav/grav#291]
I have just installed GRAV CMS for the first time.
If installation was done via `git clone https://github.com/getgrav/grav.git` the .git folder(direct file access) created in the root folder is accessible for public. Maybe a temporary solution to fix it:
```php
# Block all direct access for these folders
RewriteRule ^(.git|cache|bin|logs|backup)/(.*) error [L]
```

**Comment by rhukster** [comment]
Looks good to me, why don't you create a PR for this?

**Comment by flaviocopes** [comment]
Fixed by https://github.com/getgrav/grav/pull/294
