### ISSUE TITLE
Would be great to have an official docker compose file

### ISSUE THREAD

**Issue by QuentinFAIDIDE** [getgrav/grav#2914]
To deploy inside docker swarm clusters, or to Amazon S3 more easily, it would be great to have a docker-compose.yml file in the official repository.
There is a repo with the file all ready at evnsio/grav on Github.

**Comment by rhukster** [comment]
We do have: https://github.com/getgrav/docker-grav

**Comment by QuentinFAIDIDE** [comment]
Ok, my bad, didn't see it haha
Thanks you
