### ISSUE TITLE
Setting permissions on Flex Objects

### ISSUE THREAD

**Issue by josecarvalhoSigned** [getgrav/grav#2915]
On Grav 1.7, when we are defining permissions for a group after saving is created a groups.yaml file with the following data

![image](https://user-images.githubusercontent.com/44067633/82073777-9cba2e80-96d1-11ea-9b5d-378f278b9429.png)

The problem is, in the line 14 if i dont change "flex-object:" to "flex-objects:" those using this group cannot see the "Flex Objects" module in the sidebar

**Comment by mahagr** [comment]
Fixed in https://github.com/trilbymedia/grav-plugin-flex-objects/commit/f34050fc53cf1a94ce7344d1389d4cf402fdde20
