### ISSUE TITLE
Home url does not respect any settings in multiple functions

### ISSUE THREAD

**Issue by xf-** [getgrav/grav#2916]
Tested on 1.7.rc10

## Situation
- Got an template and URL shouldn't end with '/' instead /index.html
- Page routing default is /index and systems.
- system work even stranger is /index is used compared to indexfoo
- Setting for hide home `Hide home route in URLs` is `No`

## Workaround for link
- `{{ page.find('/home').url ~ system.pages.append_url_extension }}`

## Problem with following variables
- home_url won't respect anything and falls back to '/' n SourceCode
- `page.canonical()` returns different URLs (after reload)
  - `<link rel="canonical" href="https://dev.docker/."/>`
  - `<link rel="canonical" href="https://dev.docker/.html"/>`
  - `<link rel="canonical" href="https://dev.docker/index"/>`
- `page.find('/home').url` should return the correct url with append_url_extension
- `page.permalink()` returned also without append_url_extension on home - subpages used append_url_extension

## Tested as well
- Adding different settings like append_url_extension not only in systems, also on home and no effect.
- Set  default route to `index.html` and now only `index.html.html` works and with `/index` before `/index` worked without `.html`. Looks like some special case.

**Comment by ricardo118** [comment]
is this flex pages or legacy pages?

**Comment by rhukster** [comment]
`home_url` should already take language into account:

Twig.php:
```php
'home_url'          => $pages->homeUrl($active_language),
```

Pages.php:
```
    public function homeUrl($lang = null, $absolute = null)
    {
        return $this->baseUrl($lang, $absolute) ?: '/';
    }
...
    public function baseUrl($lang = null, $absolute = null)
    {
        if ($absolute === null) {
            $type = 'base_url';
        } elseif ($absolute) {
            $type = 'base_url_absolute';
        } else {
            $type = 'base_url_relative';
        }

        return $this->grav[$type] . $this->baseRoute($lang);
    }
...
    public function baseRoute($lang = null)
    {
        $key = $lang ?: $this->active_lang ?: 'default';

        if (!isset($this->baseRoute[$key])) {
            /** @var Language $language */
            $language = $this->grav['language'];

            $path_base = rtrim($this->base(), '/');
            $path_lang = $language->enabled() ? $language->getLanguageURLPrefix($lang) : '';

            $this->baseRoute[$key] = $path_base . $path_lang;
        }

        return $this->baseRoute[$key];
    }
```

**Comment by rhukster** [comment]
It doesn't look like `home_url` takes the url extension into account.  The `append_url_extension` option seems to be only partially implemented... it's never been a problem before because it's so rarely used.

**Comment by mahagr** [comment]
I've observed this, too. Grav doesn't take extensions into account by default but tends to strip them out.

**Comment by mahagr** [comment]
If you want .html in your pages, there's already option to add that. Closing this issue as there has been a few fixes for this already.
