### ISSUE TITLE
PHP Fatal error creating directory cache/compiled/blueprints because a blueprints file already exists

### ISSUE THREAD

**Issue by matt-j-m** [getgrav/grav#2920]
Had this issue on 2 separate installations in the last 2 weeks. Entire site becomes inaccessible with error:

Fatal error: Uncaught RuntimeException: Creating directory '[grav site]/cache/compiled/blueprints' failed on error in [grav site]/vendor/rockettheme/toolbox/File/src/File.php:423

When I go to the cache/compiled directory there is an existing blueprints **file**. If I remove the file and clear the cache, the site comes back up.

The site files are being synced from a master server to multiple slave servers with rsync each hour, but rsync is configured to ignore the cache directory. When the sync finishes, the cache is cleared on the slave server and I believe this must be when the blueprints file is being created. This process has worked successfully 24 times each day for several weeks, except for the 2 times mentioned above.

Any insight into what process may be creating the rogue blueprints file, or how I can further troubleshoot the issue? I have set up monitoring so I will know if/when it happens again.

Sites are running Grav v1.5.10.

**Comment by rhukster** [comment]
1.5.10? Time to update me thinks.. so many bug fixes since then.

**Comment by matt-j-m** [comment]
Thanks @rhukster I'm locked at that version due to the version of PHP running on the servers, which is outside of my control. But this should be the push I need to get it updated. Will continue to monitor after upgrading and post again if it reoccurs. Cheers.

**Comment by matt-j-m** [comment]
Sorry to report we have had the same issue again after updating. Have been running Grav v1.6.25 successfully for about a week. Error message: Creating directory failed for [grav site]/cache/compiled/blueprints/master-[site url].php. Any help on what could be causing this / where to start troubleshooting?

**Comment by matt-j-m** [comment]
I found this similar issue https://github.com/getgrav/grav/issues/2462 and realised that the script we run to rsync and clear the cache is running as a different user to the web server. Have updated now and will continue to monitor.
