### ISSUE TITLE
The page content doesn't appear in admin plugin

### ISSUE THREAD

**Issue by Strixos** [getgrav/grav#2928]
Hi there,

I looked for some informations about that but I didn't find anything (I think).

I don't know why but my page content doesn't appear anymore when I want to edit it in the admin plugin.
I used to edit it, but not now.

This is what I have in admin plugin :
![image](https://user-images.githubusercontent.com/27220378/83385258-34fe2600-a3e9-11ea-8e48-4e05b2eece9c.png)

And this is my md file : 
![image](https://user-images.githubusercontent.com/27220378/83385347-595a0280-a3e9-11ea-90e3-19b94bf52ed3.png)

It happens on every pages. Is there a link to this issue : https://github.com/getgrav/grav/issues/2737 ?

Regards

**Comment by Strixos** [comment]
I also updated Grav to the lastest version and the plugins too.

![image](https://user-images.githubusercontent.com/27220378/83385512-ad64e700-a3e9-11ea-835e-73438695389f.png)

**Comment by mahagr** [comment]
Check if you're editing the wrong language. Also check if there's warning on the top of the edit page.

**Comment by Strixos** [comment]
Hi,
I only have one language selected by default and no warning on the top of the page : 
![image](https://user-images.githubusercontent.com/27220378/83949691-9d079e80-a825-11ea-9e0b-c3acb2f19353.png)

**Comment by ricardo118** [comment]
select francais, not default

**Comment by Strixos** [comment]
Hi ricardo,

I can't select Français, it sticks too Default.

**Comment by ricardo118** [comment]
can u test to edit the page file from game-resume.fr.md to game-result.md for example if that works, if not try to rename to game_result.md,you will need to change the twig file name to match to game_result.html.twig

**Comment by Strixos** [comment]
Seems like the french langage isn't properly set up. I remove the .fr from the name of the md file and got access to the content.

![image](https://user-images.githubusercontent.com/27220378/84070950-3c1aca80-a9cd-11ea-978b-5dcac5c18c48.png)

**Comment by hotdoy** [comment]
I had the same issue recently. It's specific to 1.7.
I didn't look further and rolled back to 1.6

**Comment by hotdoy** [comment]
Just updated a french site to 1.7.
The site only has french ```pageName.fr.md``` pages and nothing shows up making 1.7 unusable for multilang websites at the moment. Just like @Strixos said. The only way to edit pages is do change the name of all files to pageName.md.

**Comment by mahagr** [comment]
Looks like this is a valid bug.

**Comment by elusamus** [comment]
Any plans to make multilang feature work for 1.7 version?

**Comment by mahagr** [comment]
Well, the issue is kind of that the page only has French version and you're not editing in French. I need to figure out how to deal with this situation as there's possibility that you also have .md file without any language extension in it.

**Comment by hotdoy** [comment]
This is, at the moment, the main bug preventing me to use 1.7 in production. Hope you can figure out something 🙆‍♂️

**Comment by mahagr** [comment]
I'm looking into this. Found couple of other bugs as well.

**Comment by mahagr** [comment]
This one should be fixed in: https://github.com/trilbymedia/grav-plugin-flex-objects/issues/47#issuecomment-682364221

**Comment by hotdoy** [comment]
Great! Thanks.
