### ISSUE TITLE
Admin/ Gantry 5 page layout tab error in Ver 1.7/rc11

### ISSUE THREAD

**Issue by psd-uk** [getgrav/grav#2929]
Hi,

after upgrade to 1.7 rc11 using the admin panel, gantry 5 page layouts are no longer functional. Just an empty page as per image:

<img width="1756" alt="Screenshot 2020-06-01 at 15 44 40" src="https://user-images.githubusercontent.com/59086878/83420738-f4210400-a41e-11ea-83c0-fef41f5d60a8.png">

page header menu also missing.

It occurs when Admin plugin is updated.

**Comment by simmonsr** [comment]
I've put a fix in place. Please test with CI Build:

http://gantry.org/downloads#ci-builds

**Comment by simmonsr** [comment]
If satisfied, please close this issue. Thank you!

**Comment by psd-uk** [comment]
Yes, that is now sorted. Thanks
