### ISSUE TITLE
Creating New user

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav#2935]
Is it possible to create a new user with editor permissions ( not like admin ) through a url like www.example.com/createnew-user

**Comment by ricardo118** [comment]
@geogeorgejoseph yes, when enabled in the login plugin you can register new front end users with the options you want.

To easily add it, just go to login plugin configuration using the admin.

**Comment by rhukster** [comment]
In grav 1.7/admin 1.10 you can do this from the "Accounts" menu item also
