### ISSUE TITLE
Can you add galician language from Crowdin

### ISSUE THREAD

**Issue by meixome** [getgrav/grav#2941]
The translation of the grav-core for galician (gl) is ready.
I'm performing the admin-panel too and would appreciate if all of this it's include with the code for install.

Antón

**Comment by xabiercid** [comment]
That would be really great

**Comment by meixome** [comment]
Admin-panel is already translated to galician.
Please take care of integration.

I can't download the galician core for Grav translation from Crowdin. So I can't perform my localizated instalation.
Cheers
