### ISSUE TITLE
Save Failed: The MIME type "application/pdf" is not accepted

### ISSUE THREAD

**Issue by ricardo118** [getgrav/grav#2943]
Saving pdf to the pages flex media does not work

![Preview](https://i.imgur.com/tGTgRaL.png)

**Comment by rhukster** [comment]
I think a bigger issue that has been raised is that media uploads are not uploaded instantly.  Only on save.  This is not the same as existing pages behavior.

**Comment by ricardo118** [comment]
@rhukster yeah i was investigating this and its because current flex pages upload is using the task from the "type: file", which has 

```
    /** @var array */
    private $_upload_defaults = [
        'self'              => true,        // Whether path is in the media collection path itself.
        'avoid_overwriting' => false,       // Do not override existing files (adds datetime postfix if conflict).
        'random_name'       => false,       // True if name needs to be randomized.
        'accept'            => ['image/*'], // Accepted mime types or file extensions.
        'limit'             => 10,          // Maximum number of files.
        'filesize'          => null,        // Maximum filesize in MB.
        'destination'       => null         // Destination path, if empty, exception is thrown.
    ];
```

where as admin uses 2 seperate tasks for "type:pagemedia" and "type: file". Type file checks for the "accept:" in settings and defaults to images only, where are type: pagemedia doesnt look for file MIME types at all, `taskAddmedia`

**Comment by ricardo118** [comment]
also regarding the upload instantly, it does upload instant, but only to the "tmp" folder only later does it get transfered over. I guess this was done to allow media uploading prior to first page save?

Maybe can be expanded to save to tmp if page doesnt exist yet (no first save) and if it does, automatically move it

**Comment by hotdoy** [comment]
Does the same with everything that is not an image.

**Comment by rhukster** [comment]
This is fixed already in 1.7 branch.

**Comment by mahagr** [comment]
There was a case I missed. Should be fixed now.

**Comment by hotdoy** [comment]
Looking good!
