### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by matt-j-m** [getgrav/grav#2944]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: https://github.com/matt-j-m/grav-plugin-aura-authors

**Comment by rhukster** [comment]
Apologies for taking so long to get this added to GPM. We do have plans to finish up our 'new gpm' solution that would not cause these bottlenecks.  But have a few things ahead of that first.

Added now, and should hopefully show up in the next hour.
