### ISSUE TITLE
Meta name description doesn't display any content for homepage

### ISSUE THREAD

**Issue by gizmecano** [getgrav/grav#2945]
_First of all, I have to say that I'm not sure that this issue is directly related the Grav core, but as I have not been able to find if it's due to Grav, a plugin or the theme, I prefer to ask directly at the main source (and also because nobody seems able to [answer in the forum](https://discourse.getgrav.org/t/empty-content-for-meta-name-description/12674)). Nevertheless, I hope to have followed the contribution guidelines._

***

I’m currently working on a theme and I’m facing to an issue with the proper rendering of the `<meta name="description">` element within the homepage.

While everything works with `post` and `page` templates, this metadata doesn’t return _any content_ for the homepage.

When this content should be a value taken from `site.metadata.description` set in the `user\config\site.yaml` file, the generated code remains only these kind of lines : 

```html
<meta name="generator" content="GravCMS" />
<meta name="description" />
...
```

I have checked issues into this repository, but I have only found one answer related to a direct insertion of this description (#722) without using the main loop set in `metadata.html.twig` file:

https://github.com/getgrav/grav/blob/00c5dba210888604fe324313aecb503000384eb0/system/templates/partials/metadata.html.twig#L2

Of course, I have looked for solution on the forum, but I don't think that I'm facing to the [problem which is describe in this question](https://discourse.getgrav.org/t/meta-description-does-not-show-up/8473/17), because I don't use the same extensions.

To check if this dysfunction could be from the changes I've made to the [forked theme](https://github.com/gizmecano/grav-theme-hereditor/), I have obviously tested the rendering of the homepage with the [original theme](https://github.com/getgrav/grav-theme-mediator) (maintained by the Grav team) and the element remains uncompleted in the both cases.

I cannot totally exclude that the problem could also come from a plugin. Indeed, I currently use [grav-plugin-seo](https://github.com/paulmassen/grav-plugin-seo) to manage various metadata. I didn't really find out if _and_ how it could interfere, but nevertheless, I have checked its configuration and everything seems theoretically correct for the homepage in the admin panel.

To complete, I'm currently working on a local environment with PHP `7.3.12` enabled (on Windows 10), but this issue happens to remote server too.

I would be grateful if anybody could guide me about this issue, specially to know if it could be rather due to the Grav core, the theme files or the plugin behavior.

Thanks in advance.

**Comment by ricardo118** [comment]
could you please test with the seo plugin disabled

**Comment by gizmecano** [comment]
Damn! I thought I had payed attention to all steps to check each component. But you're pointing to **an essential check** that I forgot to do... 😠 

Indeed, after the plugin deactivation, `content` is properly displayed with the expected value. Therefore, it is this plugin which seems to be at the origin of the issue.

Sorry for this long issue not applicable.

Thanks @ricardo118 ! 🙇
