### ISSUE TITLE
missing +x for bin/* using composer install (no zip)

### ISSUE THREAD

**Issue by pierrejoye** [getgrav/grav#2946]
Hello,

Not a dramatic miss but could help other:

composer create-project getgrav/grav ~/webroot/grav

not using the unzip command

bin/grab or any files in bin/ are missing the +x flag, meaning they are not executable. git supports it.

Let me know if you like me to provide a PR (no code change tho' as it is only about +x) :)

**Comment by rhukster** [comment]
Works for me on my Mac + Linux.
