### ISSUE TITLE
Deploy Grav on Nginx Webserver does not show styling (no request)

### ISSUE THREAD

**Issue by edrichhans** [getgrav/grav#2950]
Hi, I’m deploying a grav site to my CentOS 7 webserver using Nginx and PHP-FPM. I configured everything following the guide [here](https://learn.getgrav.org/16/webservers-hosting/servers/nginx), but the pages are all showing skeleton html. The admin panel’s styling works fine though.

Here’s the index page.
<img width="636" alt="Screen Shot 2020-07-01 at 12 14 48 PM" src="https://user-images.githubusercontent.com/13763624/86213754-c14c6600-bbac-11ea-922d-b8a50982ba82.png">

Checking the network response of the index page, it's not sending out requests for the css and js files for the theme (default theme, learn2).
<img width="771" alt="Screen Shot 2020-07-01 at 12 16 45 PM" src="https://user-images.githubusercontent.com/13763624/86213765-c6a9b080-bbac-11ea-907a-6f1dedba14ae.png">

As I mentioned, the admin panel styling is fine as seen here:
<img width="1134" alt="Screen Shot 2020-07-01 at 12 06 25 PM" src="https://user-images.githubusercontent.com/13763624/86213787-cc9f9180-bbac-11ea-8fda-7079d62d190e.png">

To add more info: running the development server using `php -S localhost:8000 system/router.php` in my local development machine runs perfectly fine. The problem arises just when I'm deploying to my server running Nginx. There are no error messages displayed in console or grav.log.

Any help would be appreciated. Thank you!

**Comment by edrichhans** [comment]
Setting the `css_pipeline: false` and `js_pipeline: false` in the `user/config/system.yaml` solved the problem for me. Not sure if this is the correct behavior if I set the asset pipeline to `true`. Might be a bug?

**Comment by ricardo118** [comment]
i use nginx with pipeline just fine, its likely something wrong with your pipeline result, either a broken css or js result

**Comment by rhukster** [comment]
Sounds like a misconfiguration of nginx configuration. Did you base yours on the default configuration that is included in Grav?

**Comment by edrichhans** [comment]
@rhukster Yes I used the default configs from Grav
