### ISSUE TITLE
[GRAV v1.7] Pages are unaccessible when in the Admin Panel

### ISSUE THREAD

**Issue by Martinusius** [getgrav/grav#2953]
In Grav v1.7 pages are unaccessible from plugin when in the Admin Panel.

Code:
```php
public function onPagesInitialized($event) {
    dump(array_keys($event['pages']->all()->toExtendedArray()));
}
```
This will display `[]` when you are in the Admin Panel.

This alternative also does not work:
```php
public function onPagesInitialized() {
    dump(array_keys($this->grav['pages']->all()->toExtendedArray()));
}
```

More info can be found in [this forum post](https://discourse.getgrav.org/t/page-collection-is-empty-when-in-admin-panel/12791).

**Comment by ricardo118** [comment]
my guess is you are `use` the wrong class, since you mention 1.7, my guess is your frontend is using legacy pages, and your admin is using flex pages so you get different results

**Comment by Martinusius** [comment]
Yes, that would make sense. However I still don't quite understand how I can `use` the correct class. In the plugin I don't think I use the `use` keyword with anything page related. Am I missing something?

**Comment by pamtbaau** [comment]
@ricardo118 , I have copied the same plugin into two fresh installs of latest Grav 1.7 and 1.6.

When running `$page = $event['pages']->find('/typography', true);` in `function onPagesInitialized()` while running Admin plugin:
- It returns a Page object in 1.6
- It returns null in 1.7

**Comment by ricardo118** [comment]
@pamtbaau what plugin is it? and can you come to discord and ping me there? i can help you debug what's wrong

**Comment by pamtbaau** [comment]
@ricardo118 , I have created a test plugin using devtools. I rather not come to discord. Visited a view times, but really dislike the place...

Here are the steps to reproduce:

Download latest Grav 1.6 + Grav 1.7
For each installation do the following:
- $ bin/gpm install devtools
- $ bin/plugin devtools newplugin
I named it 'test'
- $ cd user/plugins/test
- $ composer update
- Changed codelines (using vscode)
  ```
  public function onPluginsInitialized()
  {
      // Don't proceed if we are in the admin plugin
      if ($this->isAdmin()) {
          $this->enable([
              // Put your main events here
              'onPagesInitialized' => ['onPagesInitialized', 0],
          ]);
          return;
      }

      // Enable the main events we are interested in
      $this->enable([
          // Put your main events here
      ]);
  }

  public function onPagesInitialized($event) {
      $page = $event['pages']->find('/typography', true);
      dump($page);
  }
  ```
- Open Admin plugin

Results:
- Grav 1.6: Dump of Page object of '/typography'
- Grav 1.7: null

**Comment by mahagr** [comment]
I recommend reading https://github.com/getgrav/grav/blob/1.7/UPGRADE-1.7.md

**Comment by pamtbaau** [comment]
Ahh... Didn't look at the migration docs.

I presume you meant the section on [breaking changes for Admin plugins](https://github.com/getgrav/grav/blob/1.7/UPGRADE-1.7.md#admin-1)?
> BC BREAK Admin will not initialize frontend pages anymore, this has been done to greatly speed up Admin plugin.
>
>Please call $grav['admin']->enablePages() or {% do admin.enablePages() %} if you need to access frontend pages. This call can be safely made multiple times.

The following works in Grav 1.7.
```
public function onPagesInitialized($event) {
    $page = $event['pages']->find('/typography', true);   // null
    $this->grav['admin']->enablePages();
    $page = $event['pages']->find('/typography', true);   // Correct Page object
}
```

Thanks @mahagr !

**Comment by mahagr** [comment]
You don't need the first line, but I suppose you added it for an example. If you also want to make the plugin compatible for Grav 1.6, you can check if the `enablePages()` method exists.

**Comment by pamtbaau** [comment]
Yes, the first line was only to show the effect of `enablePages()`.

Btw. extensive migration list... Also many breaking changes. I wonder how this will workout with plugins. I have the impression that many are very old if not abandoned. Are there any thoughts on this?

**Comment by mahagr** [comment]
Most of the breaking changes are really not common at all, or some special cases or very old approaches. Or things that were not really working and fixing them changed the behaviour.

**Comment by Martinusius** [comment]
The issue has been resolved. Thanks everyone for help.
