### ISSUE TITLE
Create a floating form accessible on all pages

### ISSUE THREAD

**Issue by josecarvalhoSigned** [getgrav/grav#2955]
I am having a lot of difficulties in creating a floating form that has the same process as a normal form, and when it is submitted pass in the onFormProcessed () function of the plugin form. I want this form to be accessible on all pages of the site and so far I got it, but when submitting I am not getting it to take any action. Any tips? Thank you.

**Comment by rhukster** [comment]
First you can create a form in a generic location such as `modules/contact/form.md`, with a `name: contact-form` defined in the `form:` definition, and then you can reference this from any page via twig:

```twig
{% include 'forms/form.html.twig' with {form: forms('contact-form')} %}
```

If you don't provide an `action:` in the form definition, the form will be submitted to the current page.  You can also give the action a simple target, like: `action: #my-form` assuming you have a div with an `id="my-form` above the form, will ensure when you submit the page to the current page, the URL will include the target and jump back to the form.
