### ISSUE TITLE
0 - is not a valid CRON expression 

### ISSUE THREAD

**Issue by eloque1** [getgrav/grav#2956]
Started seeing this Critical Error after updating.
Cant access my home page now. Any ideas on the problem.
Being fired in an in
/Grav/Common/Scheduler/IntervalTrait.php

**Comment by rhukster** [comment]
what updates? which version are you on? do you have any custom scheduled jobs? if so what is the result of:

bin/grav scheduler -j

from the terminal?

what plugins do you have installed?

**Comment by eloque1** [comment]
> scheduler-j
$ bin/grav scheduler -j


  [LogicException]
  User class was called too early!

no schedules
plugins
$ bin/grav --version
Grav CLI Application version 1.0.6
```
$ cd user
$ cd plugins
$ dir
admin
archive_plus
email
error
form
getgrav-grav-plugin-page-inject-1.0.0-0-ga47e559.zip
getgrav-grav-plugin-pagination-1.2.7-0-ga3f00b3.zip
getgrav-grav-plugin-random-1.3.0-0-g4f86af4.zip
getgrav-grav-plugin-simplesearch-1.3.0-0-g602f25c.zip
grav-plugin-admin-develop.zip
grav-plugin-archive-plus-master.zip
grav-plugin-email-develop.zip
grav-plugin-error-develop.zip
grav-plugin-form-develop.zip
grav-plugin-jscomments-develop.zip
grav-plugin-login-develop.zip
grav-plugin-problems-develop.zip
grav-plugin-social-buttons-master.zip
grav-plugin-taxonomylist-develop.zip
jscomments
login
old
pagination
problems
sft_plugins.zip
simplesearch
socialbuttons
taxonomylist
```

**Comment by mahagr** [comment]
Looks like something in the scheduler hasn't initialized Grav fully to use user objects. Hmm..

**Comment by eloque1** [comment]
Any suggestions?

**Comment by rhukster** [comment]
well i've not seen that error with our 'core' plugins.. i would recommend disabling plugins one-by-one starting with non-core plugins.  e.g. archive-plus, jscomments, socialbuttons, etc.  If those don't resolve it start with the core ones.

Also what does your `user/config/scheduler.yaml` look like?
