### ISSUE TITLE
Asset injection throwing error

### ISSUE THREAD

**Issue by mminer237** [getgrav/grav#2959]
Currently calling `addJs()` in Grav 1.7.0-rc.13 seems to always throw an error. I assume the same happens for CSS. I noticed this because it breaks multiple plugins that rely on this such [Grav Adsense](https://github.com/clemdesign/grav-plugin-adsense) and [Grav Google Analytics](https://github.com/escopecz/grav-ganalytics). Their async request is also ignored now, but that seems like a separate issue.

Calling `callJs()` with anything results in the following error:
```
InvalidArgumentException: Property 'grav\common\assets\js_pipeline_before_excludes' does not exist in the object! in file /home/public/blog/grav-admin/system/src/Grav/Framework/Object/Property/ObjectPropertyTrait.php on line 105
Stack trace:
  1. InvalidArgumentException->() /home/public/blog/grav-admin/system/src/Grav/Framework/Object/Property/ObjectPropertyTrait.php:105
  2. Grav\Framework\Object\PropertyObject->doGetProperty() /home/public/blog/grav-admin/system/src/Grav/Framework/Object/Base/ObjectTrait.php:81
  3. Grav\Framework\Object\PropertyObject->getProperty() /home/public/blog/grav-admin/system/src/Grav/Framework/Object/Access/OverloadedPropertyTrait.php:37
  4. Grav\Framework\Object\PropertyObject->__get() /home/public/blog/grav-admin/system/src/Grav/Common/Assets.php:191
  5. Grav\Common\Assets->addType() /home/public/blog/grav-admin/system/src/Grav/Common/Assets.php:247
  6. Grav\Common\Assets->addJs() /home/public/blog/grav-admin/user/plugins/adsense/adsense.php:206
```

The problem seems to be caused by commit 25461f7ca88ea5ee4936b2d0efcfb53a5e83680d. I don't really know what that's supposed to do, but I think `addJs()` is still just supposed to pass "Js" instead of "Grav\Common\Assets\Js".

**Comment by rhukster** [comment]
Should be fixed already with this commit i made earlier today: https://github.com/getgrav/grav/commit/0f6c5fe49dec31963340a79de05f19093fd13935
