### ISSUE TITLE
Template html.twig is not defined

### ISSUE THREAD

**Issue by AutentiiK** [getgrav/grav#296]
Hi,
I'm getting the same issue with diferent packages, i tried core alone, with skeletons ...
When i try to use the wysiwyg button to edit pages i get this message : Template "modular/my_file.html.twig" is not defined ().
I checked the folder templates/modular and my file is right there, i dont understand why it's not working.
If u have any sugestions ...
Thanks.

**Comment by rhukster** [comment]
can you first provide a screenshot of the error?

**Comment by rhukster** [comment]
I've put some different handling in around this error message. Next time it occurs it should be more helpful.
