### ISSUE TITLE
[add-resource] New plugin: markdown-typography

### ISSUE THREAD

**Issue by N-Parsons** [getgrav/grav#2960]
I just wrote a new plugin to make it easy to add typographic symbols via Markdown processing.

**Repo:** https://github.com/N-Parsons/grav-plugin-markdown-typography

**Comment by rhukster** [comment]
looks good. only thing i will say is markdown already has native newline support.  just put two spaces at the end of a line and hit return.

**Comment by N-Parsons** [comment]
I was aware of the space notation for a line break, but I really don't like relying on trailing whitespace for adding meaning, particularly since I have my editors configured to strip extra whitespace. I've just added a note to the Readme to mention the existing notation though.

**Comment by rhukster** [comment]
Apologies for taking so long to get this added to GPM. We do have plans to finish up our 'new gpm' solution that would not cause these bottlenecks.  But have a few things ahead of that first.

Added now, and should hopefully show up in the next hour.
