### ISSUE TITLE
Reordering Modular with Folder Numeric Prefix trough the admin (drag&drop) sometimes messes up the folder names, creating duplicate folder prefixes or duplicates entire folders 

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav#2962]
Ok so this one still need more testing.
With the latest version of 1.7 (I can confirm the issue on at least the 2 previous versions) 

When ordering modular folders trough the admin then saving tend to rename folders improperly, and sometimes creates duplicates. I have a feeling this happens more often (or only) when reordering folders I am currently in ? (Not sure if that's clear)

Anyway, the only thing I can do to fix this is then to ftp in and clean everything manually.

I'll update next week. But I had this issue on 2 or 3 sites running 1.7 now so it's starting the look like a bug.

**Comment by hotdoy** [comment]
I did not experienced the issue with regular pages, but then again, I rarely move pages around so this applying to modular might not be relevant.

**Comment by hotdoy** [comment]
When reordering causes duplication, only folders and md files are copied. Not the media. Don't know if it's relevant.

**Comment by mahagr** [comment]
The version released yesterday works a bit better but still doesn't fix the issue fully. I did find the cause of this issue today, though.

Basically the issue was caused by an optimization with cache turned off. I commented out the code for now.

**Comment by hotdoy** [comment]
That's great news. Thanks!
