### ISSUE TITLE
1.7: Query params dropped when ? is preceded with /

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#2964]
In Grav v1.7.0-rc.14, Query params which are preceded with a '/' will be dropped when Grav redirects to url without '/'.

E.g.:
`mydomain/typography/?a=b` is redirected to `mydomain/typography`

Problem seems to be caused by [Uri::toArray()](https://github.com/getgrav/grav/blob/82f11825030d07a6c635ea92fc3ed7fba02247b9/system/src/Grav/Common/Uri.php#L630) which doesn't return `query_params => $this->queries` as part of the Uri parts.

Adding `query_params => $this->queries` to the returned array fixes the issue.

**Comment by Flamenco** [comment]
I verify this is a still a bug, introduces in said version, and has still not been fixed.  My plugin generates URLs such as:
```
http://localhost:8080/admin/powertools/edit-section/?section=hello
```
and we needed to rework all the code code to:
```
http://localhost:8080/admin/powertools/edit-section?section=hello
```

**Comment by pamtbaau** [comment]
Thanks @mahagr
