### ISSUE TITLE
[add-resource] New Plugin „grav-plugin-shortcode-external-caller“

### ISSUE THREAD

**Issue by kgitthoene** [getgrav/grav#2965]
I would like to add my new plugin to the Grav Repository.
[Here](https://github.com/kgitthoene/grav-plugin-shortcode-external-caller) are the project details: **kgitthoene/grav-plugin-shortcode-external-caller**

The Shortcode External Caller plugin provides the [external-caller="..."] shortcode for Grav to call external programs.

**Comment by ricardo118** [comment]
@kgitthoene i checked, you might wanna require the shortcode core in your blueprints or people will get an error if they install it without the core

**Comment by kgitthoene** [comment]
Please be so kind to inform me, what's the next step?

**Comment by rhukster** [comment]
You need to perform a release: https://learn.getgrav.org/16/advanced/grav-development#theme-plugin-release-process

**Comment by kgitthoene** [comment]
Check. The release was created.

**Comment by w00fz** [comment]
This was added FYI, we just never closed the issue.
