### ISSUE TITLE
Buttons inverted and messed up

### ISSUE THREAD

**Issue by ptrxyz** [getgrav/grav#2968]
In the grav admin panel, some buttons are inverted (text being "enabled" on disabled buttons and "disabled" on enabled buttons) and some options show too many options (see screenshot). Any idea how to fix this or where it might come from?

I tried to purge the caches as well as changing language, however no success.

![bug](https://user-images.githubusercontent.com/209056/87961988-d125de80-cab6-11ea-810f-6a08393f021b.png)

(I am using Grav v1.6.26 - Admin v1.9.15)

**Comment by mahagr** [comment]
The issue looks like there's issue with blueprints -- duplicating the options. Does this happen with only a single pege type or with all of them?

**Comment by ptrxyz** [comment]
Hm, what do you mean with `page type`? I check for all the pages I have (all just basic markdown files based on the same template) and it was like that for all of them.

**Comment by mahagr** [comment]
I mean the blueprint file. If you just copy the default file over with a new name, you'd get something like this.

**Comment by ptrxyz** [comment]
Hm, ok, can you point me on something where I can check that? I am just trying out Grav, so I am really not an expert on it.
I am pretty sure I never touched anything beside the pages in the `user` folder.

**Comment by mahagr** [comment]
Are you using some skeleton? Which theme are you on?

**Comment by ptrxyz** [comment]
It is the Miligram theme. However I changed back to the default theme, deleted the cache and the issue was still present.
I checked the file `system/blueprints/pages/default.yaml` and judging by the name "FOLDER_NUMERIC_PREFIX" I think this is the relevant part, right? It seems as if there is only two options defined, so I really wonder where the other two come from. ... :thinking: 

![image](https://user-images.githubusercontent.com/209056/88380142-48ec5580-cda4-11ea-8270-fc489c9365f1.png)

**Comment by mahagr** [comment]
To me, it looks like that all the options have been duplicated. Can you check if the values are 0,1,2,3? I think that something makes the blueprint to read the values twice and there's `array_merge()` instead of `array_replace()` causing them to be duplicated...

Can you try to disable all the plugins except for admin, email, error, form, login and problems and check if the issue is still there after cache clear?

**Comment by ptrxyz** [comment]
Ok, I found something. The last plugin `Tools Collection` is respsonsible for this behavior. Apparently it has a feature to automatically add
```
extends@: default
```
to all my pages (see https://github.com/Memurame/grav-plugin-tools-collection#insert-blueprints-on-pages).
There is also an option in the plugins settings to disable this behavior and well, now it's all fine.

Thanks for your time, @mahagr. You certainly pointed me in the right direction.
