### ISSUE TITLE
[add-resource] New Plugin "shortcode-chart-js-plusplus"

### ISSUE THREAD

**Issue by sal0max** [getgrav/grav#2969]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **[sal0max/grav-plugin-shortcode-chart-js-plusplus](https://github.com/sal0max/grav-plugin-shortcode-chart-js-plusplus)**

It extends [shortcode-core](https://github.com/getgrav/grav-plugin-shortcode-core) with a functionality to create charts with [Chart.js](https://www.chartjs.org/)

There is already the plugin [CPPL/grav-plugin-shortcode-chartjs](https://github.com/CPPL/grav-plugin-shortcode-chartjs) with the same functionality, but it wasn't updated since January '19. Also it lacks a lot of basic functionality, like the ability to add line graphs. My plugin was written from scratch.

**Comment by rhukster** [comment]
Apologies for taking so long to get this added to GPM. We do have plans to finish up our 'new gpm' solution that would not cause these bottlenecks.  But have a few things ahead of that first.

Added now, and should hopefully show up in the next hour.
