### ISSUE TITLE
Duplicate and move pages ( coming soon )

### ISSUE THREAD

**Issue by josecarvalhoSigned** [getgrav/grav#2972]
Hi,
We are aware that we have an alternative to carry out these two actions, but what is the forecast for these two features to be working on pages list module?

![image](https://user-images.githubusercontent.com/44067633/88277779-2fcaa280-ccd9-11ea-84e9-f2ee5608e8e5.png)

**Comment by mahagr** [comment]
FYI: These buttons should also obey CRUD ACL.

**Comment by w00fz** [comment]
Please follow the progress on https://github.com/trilbymedia/grav-plugin-flex-objects/issues/81
