### ISSUE TITLE
Why Carousel (slideshow) example from Spectre Github documentation doesn't work in Grav Quark by default?

### ISSUE THREAD

**Issue by mevsme** [getgrav/grav#2973]
Hello. Is there some other version of Spectre css framework included into Grav that Carousle from the documentation doesn't work? How can I debug fully CSS carousel?

![image](https://user-images.githubusercontent.com/1394030/88356863-f5611400-cd71-11ea-911a-9dafa5887c77.png)

**Comment by rhukster** [comment]
this is not a support forum and should only be used for bugs. please ask your questions on our forum or the discord chat. thanks!
