### ISSUE TITLE
Running Scheduler with Plesk?

### ISSUE THREAD

**Issue by K232** [getgrav/grav#2974]
Hi all,
I'm trying to run the [scheduler](https://learn.getgrav.org/16/advanced/scheduler) with [Plesk](https://docs.plesk.com/en-US/obsidian/customer-guide/scheduling-tasks.65207/) but I'm not successfull. Would it work with plesk?

I've removed the "crontab"-commands from the line shown in Tools -> Scheduler, e.g. with your example on https://learn.getgrav.org/16/advanced/scheduler it would be
`echo "* * * * * cd /Users/andym/grav;/usr/local/bin/php bin/grav scheduler 1>> /dev/null 2>&1"`
but that does not seemt to work. The line is executed without errors, showing green checkmark. But in Grav Admin at Tools -> Scheduler, no jobs were started :-( 
Is there a way to run the scheduler with a scheduled task in Plesk?

**Comment by NicoHood** [comment]
I have a similar issue. I am using hosting at netcup which also uses Plesk. However I am debugging it via ssh. I am running `./bin/grav scheduler -j -vvv` but no output is shown. `-V` returns `Grav CLI Application 1.6.31`. On my local PC everything works fine, I am currently trying to find the issue. I guess it is not a problem with Plesk itself, but rather grav or the hosting settings.

**Comment by NicoHood** [comment]
In my case it turns out that firing the `onPluginsInitialized` event fails. However I do not yet know why, as I do not have any error message. It was just a try-error via grav logging output. Any ideas on how to get more information when using the cli?
https://github.com/getgrav/grav/blob/develop/system/src/Grav/Console/Cli/SchedulerCommand.php#L63

**Comment by mahagr** [comment]
@NicoHood Redirect should be fixed?

**Comment by NicoHood** [comment]
I think so. I did not test this in my production environment yet.

**Comment by mahagr** [comment]
Closing this issue, let me know if you get it again.
