### ISSUE TITLE
truncated backtraces within log entries

### ISSUE THREAD

**Issue by drzraf** [getgrav/grav#2981]
When a critical error is logged, string arguments of the backtrace are truncated:
```
[2020-08-10 10:01:49] grav.CRITICAL: Call to a member function getCurrent() on null - Trace:
#0 /srv/www/grav/vendor/twig/twig/src/ExpressionParser.php(166): Twig\Parser->getCurrentToken()
#1 /srv/www/grav/vendor/twig/twig/src/ExpressionParser.php(78): Twig\ExpressionParser->getPrimary()
#2 /srv/www/grav/vendor/twig/twig/src/TokenParser/IfTokenParser.php(38): Twig\ExpressionParser->parseExpression()
#3 /srv/www/grav/vendor/twig/twig/src/Parser.php(209): Twig\TokenParser\IfTokenParser->parse(Object(Twig\Token))
#4 /srv/www/grav/vendor/twig/twig/src/Parser.php(122): Twig\Parser->subparse(NULL, false)
#5 /srv/www/grav/vendor/twig/twig/src/Environment.php(735): Twig\Parser->parse(Object(Twig\TokenStream))
#6 /srv/www/grav/vendor/twig/twig/src/Environment.php(793): Twig\Environment->parse(Object(Twig\TokenStream))
#7 /srv/www/grav/vendor/twig/twig/src/Environment.php(482): Twig\Environment->compileSource(Object(Twig\Source))
#8 /srv/www/grav/vendor/twig/twig/src/Environment.php(445): Twig\Environment->loadClass('__TwigTemplate_...', 'partials/modals...', NULL)
#9 /srv/www/grav/vendor/twig/twig/src/Environment.php(611): Twig\Environment->loadTemplate('partials/modals...')
#10 /srv/www/grav/vendor/twig/twig/src/Extension/CoreExtension.php(1567): Twig\Environment->resolveTemplate(Array)
#11 /srv/www/grav/cache/twig/bb/bbabc21ef4ca01c03cac9f094976faa09a209b1cf9a61ceed49a12b41d75886d.php(134): twig_include(Object(Grav\Common\Twig\TwigEnvironment), Array, 'partials/modals...') 
```

I'd have appreciated to know which template is triggering that specific error, but can't because of the truncation.

**Comment by drzraf** [comment]
Because I encountered this error in production and couldn't find how to trigger it again ... because the information was too restricted.

**Comment by mahagr** [comment]
Usually, most of the trace is irrelevant, generally I just look into few last items in it.

**Comment by drzraf** [comment]
If you look at the above trace, all the deepest level are related to Grav internals and thus useless to pinpoint user code.
See the OP, up to level 11, there is nothing that would allow me to debug it.
Worse, the `Twig\Environment->loadTemplate('partials/modals...')` which could let me know **which** file is causing the error, is ellipsized.
In my case, such backtrace does not serve its intended purpose. Could you point me to the place it's being stripped?

**Comment by mahagr** [comment]
We are not doing that, it must be somewhere in Whoops library.

**Comment by mahagr** [comment]
I just checked my local and the long backtraces seem to be split into multiple log entries in grav.log file.
