### ISSUE TITLE
[add-resource] New Plugin: Foundation-for-sites

### ISSUE THREAD

**Issue by Bibi40k** [getgrav/grav#2982]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **Bibi40k/grav-plugin-foundation-for-sites
![foundation-for-sites](https://user-images.githubusercontent.com/4104609/89873878-c2b57900-dbc3-11ea-9987-6dc0163fde4e.png)
**

**Comment by rhukster** [comment]
Apologies for taking so long to get this added to GPM. We do have plans to finish up our 'new gpm' solution that would not cause these bottlenecks.  But have a few things ahead of that first.

Added now, and should hopefully show up in the next hour.

**Comment by Bibi40k** [comment]
Thank you
