### ISSUE TITLE
[add-resource] New Plugin: Yandex Turbo

### ISSUE THREAD

**Issue by dragomano** [getgrav/grav#2983]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **https://github.com/dragomano/grav-plugin-yandex-turbo**

**Comment by rhukster** [comment]
Apologies for taking so long to get this added to GPM. We do have plans to finish up our 'new gpm' solution that would not cause these bottlenecks.  But have a few things ahead of that first.

Added now, and should hopefully show up in the next hour.
