### ISSUE TITLE
Config reading issue with Grav 1.6.26 & Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by jonathankaiser** [getgrav/grav#2984]
I setup a new Ubuntu 20.04 LTS VM through Vagrant and got the issue below. I switched it out to Ubuntu 18.04 LTS and Grav ran just fine. For some reason Grav is having trouble reading any of the config files in 20.04. In the image below, $types is empty on line 1612 (20.04) but when setup on 18.04 it gets populated correctly ([html,htm,xml,txt,json,rss,atom]). Am I missing anything or does anyone have a similar with 20.04?

<img width="1395" alt="Screen Shot 2020-08-19 at 2 57 35 PM" src="https://user-images.githubusercontent.com/5582441/90693829-0ca6fa80-e267-11ea-9b10-7a543928ed04.png">

**Comment by rhukster** [comment]
It's not really an issue with Grav then,  sounds like an issue with PHP.  Grav doesn't access anything directly, everything goes through PHP.  What version of PHP is Grav running on your Ubuntu 20.04 compared to your 18.04 ?

**Comment by jonathankaiser** [comment]
On Ubuntu 20.04 I tried Grav with both PHP 7.3.21 & PHP 7.4.9 and had the same issue. However, Grav ran correctly on Ubuntu 18.04 with PHP 7.4.9. This is all on Apache by the way.
