### ISSUE TITLE
[add-resource] New Plugin (Grav Tag Manager)

### ISSUE THREAD

**Issue by OrthoCube** [getgrav/grav#2986]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **OrthoCube/grav-plugin-tag-manager**

It is a plugin that batch-deletes or renames tags from multiple pages at once.

I have tested it and it seems to work. It's my first release, so I might have made some mistakes--if that's the case, please feel free to inform me and I'll check it and see what I can do to correct it.

Thanks!

**Comment by rhukster** [comment]
Apologies for taking so long to get this added to GPM. We do have plans to finish up our 'new gpm' solution that would not cause these bottlenecks.  But have a few things ahead of that first.

Added now, and should hopefully show up in the next hour.
