### ISSUE TITLE
[add-resource] New Theme (Dark Quark)

### ISSUE THREAD

**Issue by HeavyWolfPL** [getgrav/grav#2989]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: [**HeavyWolfPL/grav-theme-darkquark**](https://github.com/HeavyWolfPL/grav-theme-darkquark)

It is just a dark, eye-friendly during the night version of Quark theme with some changes. I've noticed that people wanted a darker version of Quark so here it is, _DarkQuark_!

**Comment by w00fz** [comment]
Added in GPM - will be available soon.

Thanks! 👍
