### ISSUE TITLE
Implement  a way to setlocale via system.yml file 

### ISSUE THREAD

**Issue by simogeo** [getgrav/grav#299]
Like so : 

`pages.dateformat.locale: "fr_FR"` would produce :

```php
setlocale(LC_ALL, 'fr_FR');
```

and display `12 Mars 2013` in place of `12 March 2013`

Thanks !

**Comment by rhukster** [comment]
I think this needs to be done in a multilang friendly way.. it needs some thinking on because you may not have multi language enabled, just some non-english single language.

**Comment by simogeo** [comment]
perfect. Thanks !
