### ISSUE TITLE
[add-resource] New Plugin/Theme (cdn-asset)

### ISSUE THREAD

**Issue by tacoen** [getgrav/grav#2990]
I would like to add my new plugin/theme to the Grav Repository.

Its to make it easy to add css/js cdn resources.

Repo: https://github.com/tacoen/grav-cdnasset-plugin

**Comment by rhukster** [comment]
This one really needs a readme at least.  There's nothing explaining what it does or how to use it.

**Comment by w00fz** [comment]
@tacoen Did you ever got around adding a README? Can't really publish this in GPM without some basic instructions on how to use the plugin.

**Comment by tacoen** [comment]
> @tacoen Did you ever got around adding a README? Can't really publish this in GPM without some basic instructions on how to use the plugin.

> This one really needs a readme at least. There's nothing explaining what it does or how to use it.

Sorry, haven't notice this conversations. I take this plugin down and already remove the repo, because there is a similiar one.
