### ISSUE TITLE
External Link (external.md) throws exception 'external.html.twig does not exist'

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#2993]
When creating a page of type 'external' with header `external_url: https://getgrav.org`, Grav will throw a runtime exception when pointing the browser to the url of the page.

Steps:
- Create page '/user/pages/03.gogograv/external.md'
- Add header:
  ```
  ---
  title: Go Go Grav
  external_url: https://getgrav.org
  ---
  ```
- Point browser to 'localhost/gogograv
- Enjoy exception: "RuntimeException: Template "external.html.twig" does not exist"

Although the functionality of 'external_url' was probably intended to be used only in combination with a menu item, accessing the page url using 'localhost/gogograv' should nonetheless not throw an error.

Maybe Grav should instead use a redirect as fallback when a page contains 'external_url' in the header and the page is requested by the browser.

**Comment by rhukster** [comment]
That `external.html.twig` template needs to exist in your theme even if it does nothing.  Just copy `default.html.twig` and rename it to `external.html.twig` and it should work fine.

**Comment by pamtbaau** [comment]
@rhukster, IMHO that is a workaround for an incorrect behaviour... Although, admittedly, the chances this will occur are slim.

Admin offers an easy way to add an extra menu-item with a link to an external page by creating a new page using the template 'External' from the list of available templates.

Internally, this dummy page is treated by Grav as a valid page with a valid slug. Although the dummy page is not intended to be requested, a user might request the page anyway using 'localhost/dummy-page-for-external-link'. A forum-member did and received the Exception. 

I think an Exception should not be thrown. Instead  I would suggest the following possible solutions:
Fix:
- Admin, could provide an 'external.html.twig' template to prevent the Exception. It offers the use of the 'External' template, so it might as well provide a real template.
- Grav could redirect the request to the external link

Docs:
- The blueprint used by Admin for the 'External' page, could provide a warning if no 'external.html.twig' template is created
- The docs on the header variable [external_lurl](https://learn.getgrav.org/16/content/headers#external-url), should mention that a dummy 'external.html.twig' template needs to be created to prevent this Exception.

No fix:
- Or, lastly, since the chances that a user tries to access the dummy page and experiencing the accompanying Exception are so slim that no solution will be provided...

**Comment by mahagr** [comment]
I believe that the template(s) were already added to Grav 1.7:

https://github.com/getgrav/grav/commit/9880ce977ad079aae9975e3ea8d2eddc5c8dfc86

**Comment by pamtbaau** [comment]
Nice! I think this will reduce the chances for an unexpected Exception thrown at the user. The content of the template could be a little bit more explanatory... For example:

<p>This page is not meant to be accessed. Please click menu item "{{ page.menu }}" or click <a href="{{ page.header.external_url }}">link</a> to access the intended url.</p>

**Comment by mahagr** [comment]
It may be a good idea for example if the page is somehow getting listed inside the content of another page. If you try to access this page directly, it should always redirect. 

CC @rhukster

**Comment by pamtbaau** [comment]
> If you try to access this page directly, it should always redirect.

What do you mean by "access directly"?:
- By requesting the url 'domain/slug_of_dummy_page_used_for_external_url' in the browser?
That would be my preferred behaviour, instead of displaying the page with template `external.html.twig`.
- Or when clicking the menu item?
This already works fine.

**Comment by mahagr** [comment]
Doesn't it redirect when accessing the page directly? It should already do that -- even if it needs the twig template.

**Comment by pamtbaau** [comment]
No it doesn't. See my initial post and the steps to reproduce the exception being thrown.

When accessing the page directly, it seems that, instead of redirecting immediately, Grav will try to parse the template 'external.html.twig' and throw an Exception because the template does not exist.
