### ISSUE TITLE
onAdminSave($event) passes page as $event['object'] or $event['page'] depending on regular/flex page

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#2995]
When subscribing to onAdminSave event, a different Event object is passed when saving a 'regular' page versus a 'flex' page.

regular: $event['object']
flex: $event['page']

This will break plugins that want to intercept the saving of a page.

**Comment by mahagr** [comment]
@rhukster Looks like there are a lot of inconsistencies in how the admin deals with the page events. All the other events use page instead of object.

**Comment by mahagr** [comment]
I updated the other events to use `object` as well (`page` variable is still there for backwards compatibility).

**Comment by pamtbaau** [comment]
Thanks @mahagr 👍
