### ISSUE TITLE
Featur Request: Support duplicate query parameters

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#2999]
As mentioned in the stackoverflow post below, I want to use multiple, duplicate query parameters: `mysite.com?id=1&id=2&id=3`
https://stackoverflow.com/questions/11621477/using-duplicate-parameters-in-a-url

The usecase is to have multiple checkboxes with the same name (query parameter), so it will end up sending multiple query parameters to the backend.

This is not yet supported. Even `uri.query()` does remove the duplicate entries. The last one is always kept.

Is this by design? Could we add a function to (at least) show the PURE raw value?

**Comment by mahagr** [comment]
PHP doesn't support this. If you want to support multiple ids, you need to use an array: `id[]` inside the input field.

**Comment by NicoHood** [comment]
Thanks
