### ISSUE TITLE
Error while trying to download (code: 0)

### ISSUE THREAD

**Issue by RaSchn** [getgrav/grav#3001]
I got the same issue like in this issue-reports: #2835 and #2848 while trying to update from grav 1.5.8 to 1.6.27
I've tried all the hints, but it didn't work.
Is there a way to update grav manually? How would that work? Copy all the files from the update-package over the existing grav installation?

Thanks a lot!

**Comment by rhukster** [comment]
You can download the update package directly: https://github.com/getgrav/grav/releases/download/1.6.27/grav-update-v1.6.27.zip

Then just unzip and copy OVER the existing Grav installation.  The update package won't overwrite your user/ folder, and really just updates the core files.  Always a good idea to backup/copy the site first though, just in case.
