### ISSUE TITLE
1.7- Gantry version 5.4.35 + Grav v1.7.0-rc.16 - Admin v1.10.0-rc.16 Gantry plugin Layout edit broken

### ISSUE THREAD

**Issue by psd-uk** [getgrav/grav#3002]
1.7- Gantry version 5.4.35 + Grav v1.7.0-rc.16 - Admin v1.10.0-rc.16 Gantry plugin Layout edit broken

Just updated a site with these latest versions and the Gantry Outline Layout page is broken again.

see screenshot - works OK with dev version dev-fb39b49e0

<img width="1270" alt="Screenshot 2020-09-09 at 15 02 40" src="https://user-images.githubusercontent.com/59086878/92610072-332ce400-f2af-11ea-8b01-c0b1f3e8aaf1.png">

**Comment by mahagr** [comment]
I have no issues with Gantry admin, though I'm running all dev. I will need to test this.

**Comment by mahagr** [comment]
Is the issue browser related or does the issue appear on different browsers?

**Comment by psd-uk** [comment]
I know that Safari always has issues. This particular problem is OK in Safari but other parts of the page don't work.

I normally use Chrome and this is where this problem is.

**Comment by svatas** [comment]
This is bug in Gantry, it was already reported to Gantry project, please see :+1: 
https://github.com/gantry/gantry5/issues/2701
