### ISSUE TITLE
Grav 1.7.0-rc.16: Class 'Twig\Node\Expression\Test\DefinedTest' not found

### ISSUE THREAD

**Issue by Torsten-K** [getgrav/grav#3003]
The error message above appeared after a fresh install of 1.7.0-rc.16. I could solve this issue by uploading the directory  _vendor/twig/twig_ from version 1.6.27 and overwriting the newer files. Afterwards I was able to create the administrator account and log in, but then another error message appeared: _Class 'Grav\Framework\Flex\Pages\FlexPageCollection' not found_.

I will keep using version 1.6.27, but I thought I should report these issues.

**Comment by mahagr** [comment]
There's something badly wrong in your fresh install. Grav is not using test classes from the vendor libraries.

Also, your installation seems to be missing files.

**Comment by Torsten-K** [comment]
I downloaded it again, and now it works. I don’t know what went wrong the last time. Anyway, thanks for your hint.
