### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by zoof** [getgrav/grav#3007]
When I try to run `bin/gpm index` I get:

```
PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /home/user/www/grav/vendor/symfony/var-dumper/Resources/functions/dump.php on line 18
```
I am happy to provide further information to help debug this.

I am running `grav` on a Centos 7 box with Apache and I have been using `grav` at least as far back as 2017.

**Comment by mahagr** [comment]
Looks like your CLI uses too old version of PHP (5.6?). See instructions (ISP/Centos/CPanel, whichever you're using) on how to set CLI to use the correct one.

**Comment by zoof** [comment]
Actually I am running 7.3.

```
$ php --version
PHP 7.3.11 (cli) (built: Dec 10 2019 16:14:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11, Copyright (c) 1999-2018, by Zend Technologies
```

7.4 is not available yet but I guess that is probably not the problem.

**Comment by rhukster** [comment]
7.3.11 should be fine.  That error does look like a PHP error though. This is an error in the symfony library `var_dumper` as the error clearly shows.  A quick Google returns various results like: https://github.com/laravel/framework/issues/28807

They all are a result of the PHP being run in the CLI as < 7.1.

**Comment by zoof** [comment]
Interesting.  So even though I have a more recent install of php, I did not uninstall the old version (5.4).  I have now uninstalled it and I'm getting
```
$ sudo bin/gpm index
/usr/bin/env: php: No such file or directory
```
I would have expected Redhat to do a better job of integrating backported software into a running system.
