### ISSUE TITLE
Is there a way to get pages from collection using a range?

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav#3008]
Just like it's possible with ```dateRange```, is there a way to build a collection and ask for a certain range of pages based on their position in said collection?

Something like :
```
{% set options = { items: {'@page.children': ''}, 'range': {'start': 5, 'end': 10}, 'order': {'by': 'date', 'dir': 'desc'}} %}
```

**Comment by rhukster** [comment]
In short, yes and no.  If you don't use pagination, then yes you can easily get all the results, then use the regular Twig slice functionality to get a range.  However, with pagination, slicing is already happening on the collection returned, and then your results will probably be not as expected.

**Comment by hotdoy** [comment]
Thanks @rhukster .
That was pretty much my next step. Thank you for taking the time to answer 👋
