### ISSUE TITLE
i18n bug in v1.7.0-rc.16 ?

### ISSUE THREAD

**Issue by mrtngrsbch** [getgrav/grav#3019]
Hi,

I just made the update to v1.7.0-rc.16 and lost my content in ES

![image](https://user-images.githubusercontent.com/693328/94353029-d701e800-0042-11eb-97d1-f264b9c43bc5.png)

And if I edit I create a page in (another language?)
![image](https://user-images.githubusercontent.com/693328/94353037-e08b5000-0042-11eb-92ab-90be61e64d51.png)

I have the impression that you are not considering my ES language as default...

![image](https://user-images.githubusercontent.com/693328/94353043-f26cf300-0042-11eb-8bb7-25b54d1eba66.png)

**Comment by mahagr** [comment]
Actually this is expected. You have two defaults and Grav allows you to edit both the files, one as `default` and one as `es`.
