### ISSUE TITLE
Accessing from URL/folder containing special character ~

### ISSUE THREAD

**Issue by eminos** [getgrav/grav#302]
I just tried to run Grav from a "cPanel temporary user URL" that has this format:
`http://server1.webhost.tld/~grav/`

But I get redirected to "server1.webhost.tld", ie "the root".

I guess it's the tilde (~) that's messing things up.
I've tried adjusting the .htaccess to include `RewriteBase /~grav/` but it didn't help, same result.
I have no issues running other CMSes using these type of "cPanel temporary user URLs".

**Comment by rhukster** [comment]
I just can't replicate this. I setup my local mac with userdirname support (http://stackoverflow.com/questions/24583859/apache-localhost-username-not-working) and then installed Grav in a variety of scenarios including symlinks and straight installs, at root and in subdirs, and they all worked fine.  

I'm positive the issue you are having is not a Grav issue.  BTW no rewritebase changes were needed, I just installed the blog skeleton as a test case with the default `.htaccess`

![2015-09-05-23-2y48h](https://cloud.githubusercontent.com/assets/1084697/9702682/32cef1b4-5427-11e5-9115-5bd80f1392cd.png)
