### ISSUE TITLE
'Page media' insert image problem (?)

### ISSUE THREAD

**Issue by mrtngrsbch** [getgrav/grav#3021]
Hi,

I insert an image = OK
Image uploads and has permissions = OK

But the thumbnail shows me an 'Error' and the image does not insert correctly.
But when I add the full URL it looks OK
And 'grav.log' does not register any error

This error occurs with JPG images. With PNG it works correctly
![image](https://user-images.githubusercontent.com/693328/94637828-e2f1e200-02ae-11eb-8b52-3a3a7d650159.png)

backend:
![image](https://user-images.githubusercontent.com/693328/94632397-c484ea00-02a0-11eb-8a42-61b3df0a958a.png)

frontend:
![image](https://user-images.githubusercontent.com/693328/94632570-568cf280-02a1-11eb-9473-006d0090eb24.png)

best,
Martin

Linux 228d1db02a38 4.15.0-106-generic #107-Ubuntu SMP
PHP Version 7.4.10
Grav v1.7.0-rc.16 - Admin v1.10.0-rc.16

**Comment by mahagr** [comment]
This issue should already be fixed for upcoming version.
