### ISSUE TITLE
Back-ups not working because of set_time_limit() unavailable

### ISSUE THREAD

**Issue by nclm** [getgrav/grav#3023]
When using One.com as a host, the back-up feature does not work. It displays this error:

`An error occurred. set_time_limit(): Cannot set max execution time limit due to system policy`

However, back-ups work perfectly when commenting out this in the code:

https://github.com/getgrav/grav/blob/5ba4c8ee5beeed0283088b76d6aec9fe865c38fe/system/src/Grav/Common/Filesystem/Archiver.php#L40-L43

It appears that the check performed for the availability of `set_time_limit()` is not enough on this host.

**Comment by ricardo118** [comment]
to expand:
```
PHP Version 7.4.11
disable_functions
    disk_total_space, diskfreespace, exec, system, popen, proc_open, proc_nice, shell_exec, passthru, dl
```

Hosts php.ini also has spaces in it

**Comment by nclm** [comment]
The issue is still there in 1.7.7. 
Now, the lines to comment out to make the backup works on One.com are these:

https://github.com/getgrav/grav/blob/061a65f730ba419b91e4a2c0051274786ef7f915/system/src/Grav/Common/Filesystem/Archiver.php#L63-L65

**Comment by mahagr** [comment]
@nclm I need more information about what is going on.

Can you run this and return me the output:
```
<?php
$str = trim(ini_get('disable_functions') . ',' . ini_get('suhosin.executor.func.blacklist'), ',');
$list = $str ? array_flip(preg_split('/\s*,\s*/', $str)) : [];
var_dump($list);
```

**Comment by nclm** [comment]
Thanks for your reply, here is the result:

`array(10) { ["disk_total_space"]=> int(0) ["diskfreespace"]=> int(1) ["exec"]=> int(2) ["system"]=> int(3) ["popen"]=> int(4) ["proc_open"]=> int(5) ["proc_nice"]=> int(6) ["shell_exec"]=> int(7) ["passthru"]=> int(8) ["dl"]=> int(9) } `

**Comment by mahagr** [comment]
@nclm It looks like the method is allowed, which means that it can be called. Maybe your configuration doesn't like the argument, which sets the time limit to infinite. Try it with a value of 300 instead (5 minutes).

**Comment by nclm** [comment]
Same issue with a value of `300`, I get the same error: `An error occurred. set_time_limit(): Cannot set max execution time limit due to system policy`. 

As soon as I comment out the whole of the `if` statement, it works. And every time Grav is updated (now using 1.7.8 by the way), `Archiver.php `is overwritten and back-up becomes broken once again.

**Comment by mahagr** [comment]
@nclm OK, so the method isn't disabled, but PHP still won't allow the method to run. Try doing this instead: `@set_time_limit(0);` and report back if it works.

**Comment by nclm** [comment]
This works!! What is the `@` for?

**Comment by rhukster** [comment]
Missed this for 1.7.9 but it will be sorted in 1.7.10 release

**Comment by mahagr** [comment]
Did the same for GPM.
