### ISSUE TITLE
500 sever error after successful bin/grav install 

### ISSUE THREAD

**Issue by r2sd** [getgrav/grav#3024]
I got myself a free Ubuntu VM on Oracle Cloud Infrastructure, a free domain from freenom.com and a free SSL certificate from Let's Encrypt. 

Then, I installed grav by cloning the git repository and modified the nginx.conf file in my VM. Upon visiting the domain, I got a message asking me to run `bin/grav install`. I did that as well (had to install a few dependencies to get it to run) and got the final message `SUCCESS cloned https://github.com/getgrav/grav-theme-quark -> /home/ubuntu/grav/user/themes/quark`.

Now, visiting my site throws me an HTTP ERROR 500.

I also followed the 500 Internal Server Error guide:
* Test PHP is Working
  * This prints a ton of info starting from `PHP Version 7.4.3`
* Check permissions
  * nginx runs as `ubuntu` and the grav directory is also owned by `ubuntu`
* Register Globals Issue
  * Updated php ini file (should I restart something?)
* Options -Indexes
  * Updated .htaccess file (should I restart something?)
* RewriteBase problems
  * Updated .htaccess file (should I restart something?)

What else could be wrong here?

**Comment by rhukster** [comment]
500 is an internal server error.  You need to check the web server logs.  They should tell you exactly what the issue is.

**Comment by r2sd** [comment]
This is what I found in nginx's logs
```
2020/10/02 15:08:23 [error] 83955#83955: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Failed to save file /home/ubuntu/grav/cache/compiled/blueprints/master-anon-domain.php in /home/ubuntu/grav/vendor/rockettheme/toolbox/File/src/File.php:351
Stack trace:
#0 /home/ubuntu/grav/vendor/rockettheme/toolbox/File/src/PhpFile.php(31): RocketTheme\Toolbox\File\File->save()
#1 /home/ubuntu/grav/system/src/Grav/Common/Config/CompiledBase.php(252): RocketTheme\Toolbox\File\PhpFile->save()
#2 /home/ubuntu/grav/system/src/Grav/Common/Config/CompiledBase.php(117): Grav\Common\Config\CompiledBase->saveCompiledFile()
#3 /home/ubuntu/grav/system/src/Grav/Common/Service/ConfigServiceProvider.php(77): Grav\Common\Config\CompiledBase->load()
#4 /home/ubuntu/grav/system/src/Grav/Common/Service/ConfigServiceProvider.php(36): Grav\Common\Service\ConfigServiceProvider::blueprints()
#5 /home/ubuntu/grav/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\ConfigServiceProvider->Grav\Common\Service\{closure}()
#6 /home/ubun" while reading response header from upstream, client: 117.98.169.210, server: anon-domain, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "anon-domain"
```

**Comment by r2sd** [comment]
Looks like a permission issue, I'm trying this from root directory: https://learn.getgrav.org/16/basics/requirements#permissions
