### ISSUE TITLE
do not cache 404 about /images/*

### ISSUE THREAD

**Issue by drzraf** [getgrav/grav#3025]
When creating a pages and medias, the admin panel may requests images derivatives *before* these are actually created.

I don't know exactly why and where this behavior happens but would like the subsequent issue resolved:

These `/images/` 404 are given the default header from `src/Grav/Common/Page/Page.php::httpHeaders()` which usually contains something like `Cache-Control: max-age=1080`.

The problem is that these 404 on /images/ are transitory by nature and should neither be cached by the browser nor by intermediary caches. It's even more likely since intermediary cache base their heuristic on the file extension rather than mime-type, and as such, URL matching /images/ declaring a max-age are likely to be cached (confirmed on Cloudflare and mod-cache)

The immediate consequence is visitors getting this cached 404 (created during admin's edition) instead of the regular derivative image.

Sample patch (although may not sound pretty):
```patch
diff --git a/system/src/Grav/Common/Page/Page.php b/system/src/Grav/Common/Page/Page.php
index 176a2788..ce923a01 100644
--- a/system/src/Grav/Common/Page/Page.php
+++ b/system/src/Grav/Common/Page/Page.php
@@ -509,6 +509,13 @@ public function httpHeaders()
         // Set Content-Type header
         $headers['Content-Type'] = Utils::getMimeByExtension($format, 'text/html');
 
+        // If these headers are for an error-page and the initial request was for a generated image
+        //  don't allow caching
+        if ($this->template() === 'error' && $grav['uri']->paths()[0] ?? '' === 'images') {
+            $headers['Cache-Control'] = 'no-cache';
+            return $headers;
+        }
+
         // Calculate Expires Headers if set to > 0
         if ($expires > 0) {
             $expires_date = gmdate('D, d M Y H:i:s', time() + $expires) . ' GMT';
```

**Comment by rhukster** [comment]
I'm not sure "..the admin panel may requests images derivatives before these are actually created..." is actually possible.

1. Image derivatives and any 'processed' Grav images are generated and stored in the `/images/**` folder.  These images are direct links to the images in the filesystem and are served by the web server itself, not Grav. Any 404's for missing images are coming from the webserver, and as such Grav will have no control over their cache settings, those would have to be controlled via webserver config.
2. Grav's PHP process does not create these images in the background. or asynchronously, it only finishes processing (and sends a response) after the images have been created in the filesystem.

So I'm not quite sure how you are having this happen, but even if it is, I don't see how your fix will help as that will only address the headers of the document, not the images.

**Comment by drzraf** [comment]
About 1. I'll try to get a confirm and pinpoint. Could be the `admin` plugin or something similar doing some ajax on the file before they are actually created.

> These images are direct links to the images in the filesystem and are served by the web server itself [...]

**if** they exist, otherwise, request pointing to non-existing files (including those under /images/) are directed to the `index.php` entrypoint (Grav's catch-all) and trigger a 404 (and the corresponding `error` template markup and corresponding headers)

So I would not call these 404 _coming from the webserver_, but thank you for clarifying that there is no such thing like _lazy-generation_.

Example:
```
$ HEAD https://learn.getgrav.org/images/a/b/c/d.jpg`
# This one comes from 404 Grav generator
> Cache-Control: max-age=604800
# This one probably comes from your Nginx (like the duplicated `Vary`), but seems inadequate here anyway
> Pragma: no-cache
```

Now, let's omit that particular `Pragma` for a minute and imagine Grav instance at learn.getgrav.org just created `images/a/b/c/d.jpg`: clients won't obtain it because intermediary caches are still serving the 404 obtained in the initial request (and may do it for the next 7 days)

In the end, the dirty patch I suggested above is about avoiding Grav-generated 404 from being cached in the specific case of `/images/*` because that's were caching a 404 can be harmful.

**Comment by mahagr** [comment]
Above commit will not alone fix the issue. This issue is the same new FF caching issue as always, now with 404 pages.

**Comment by drzraf** [comment]
What do you mean by `FF caching issue as always`? (The issue is not firefox-specific but related to the use of HTTP headers).
Out of curiosity:
- Why headers must be changed both in PHP and `notfound.md` template?
- Do you think there a way to only avoid cache for `images/* ` URL?

**Comment by mahagr** [comment]
Latest FF (81.0+?) versions changed the behaviour on how the browser caches the pages. Every other browser and older FF as well are less strict on the headers and will query the server anyway.

The changes in Grav are only a small part of the fix.

* Both need to be changed as they have different purpose. Some plugins do not use the default template for 404.
* Yes, if the request goes to Grav itself.

**Comment by drzraf** [comment]
> Every other browser and older FF as well are less strict on the headers and will query the server anyway.

Not sure about this, but older browsers are still affected if Grav is behind a caching reverse-proxy (Squid, Apache2 mod-cache, Cloudflare, ...) because, other than `private` cache, these directives apply to them too.

**Comment by mahagr** [comment]
I know. We just first saw these issues starting to pop in with FF a few weeks ago.

**Comment by mahagr** [comment]
Error plugin needs to be updated, too (will be released soon).
