### ISSUE TITLE
Where is the GraphQL and MongoDB Docs?

### ISSUE THREAD

**Issue by maheraldous** [getgrav/grav#3026]
Hello

I just need those things in a CMS:

1. MongoDB.
2. GraphQL to make some simple request to the CMS.
3. Multiple Media Upload via Admin UI and GraphQL just for Images and posts.
4. Multilingual (I know Grav have this but I wonder if it work with GraphQL too).

If Grav have those of at least number 1, 2 ,3 I will use it in my project and recommend it to my team. :)

Thanks in advance

**Comment by rhukster** [comment]
If you are looking for a CMS powered by MongoDB, Grav is not for you.  Grav is a flat-file CMS. Also Grav currently doesn't have any built-in GraphQL.  Of course it could be added via a plugin, or in the core itself in time, but it's not there yet.

**Comment by maheraldous** [comment]
> If you are looking for a CMS powered by MongoDB, Grav is not for you. Grav is a flat-file CMS. Also Grav currently doesn't have any built-in GraphQL. Of course it could be added via a plugin, or in the core itself in time, but it's not there yet.

Thanks for the replay.
