### ISSUE TITLE
Question About Page Id's

### ISSUE THREAD

**Issue by AndrewNB** [getgrav/grav#3027]
Hi,

I have a Grav site on a server and has been using the page.id as a unique identifier for a user favourite system.

I'm being forced to Migrate this site, is there any way to move the host and keep the id for the pages the same? 

Thanks,

**Comment by rhukster** [comment]
id is not intended to be used as a long-life universal identifier as it is based on `time()` plus the current filepath.

```
    /**
     * Gets and sets the identifier for this Page object.
     *
     * @param  string|null $var the identifier
     * @return string      the identifier
     */
    public function id($var = null)
    {
        if (null === $this->id) {
            // We need to set unique id to avoid potential cache conflicts between pages.
            $var = time() . md5($this->filePath());
        }
        if ($var !== null) {
            // store unique per language
            $active_lang = Grav::instance()['language']->getLanguage() ?: '';
            $id = $active_lang . $var;
            $this->id = $id;
        }

        return $this->id;
    }
```

It was intended to be used for a cache ID that is meant to be unique on content changes:

```
    /**
     * @return string
     */
    public function getCacheKey(): string
    {
        return $this->id();
    }
```

So in short, it's not a good value to be unique between systems, and really not even on the same system as it will change between edits/modifications to the file.

A better ID would be to use the `route` or the `rawRoute()`, perhaps md5 of those?

**Comment by AndrewNB** [comment]
Ok, understood.  Thanks for the info!
