### ISSUE TITLE
Filepicker field folder other than @self, @theme: or @page:

### ISSUE THREAD

**Issue by funktionaer** [getgrav/grav#3032]
Hello,
is it possible to define a folder for filepicker field other than @self, @theme: or @page:?
Let's say I have a page with modular pages underneath. Is it possible to define a filepicker for the modular pages such as @self.parent to pick files available of parent page?

Cheers,
funktionaer

**Comment by mahagr** [comment]
You cannot pick parent page, but the field also accepts streams like `theme:://` or `user-data://`

**Comment by dani-ooo** [comment]
i achieved this with `user://pages/pagefolder`, but it breaks if you make any changes to the numeric prefix.

**Comment by mahagr** [comment]
@dani-ooo For that there is `@page:/pagefolder`.
