### ISSUE TITLE
Add fix-permissions script with install

### ISSUE THREAD

**Issue by b7s9** [getgrav/grav#3036]
One of the first things I do when installing a new grav instance is to copy the fix permissions script from the documentation (or from another instance I have)...

```sh
#!/bin/sh
chown -R $USER:www-data .
find . -type f -exec chmod 664 {} \;
find ./bin -type f -exec chmod 775 {} \;
find . -type d -exec chmod 775 {} \;
find . -type d -exec chmod +s {} \;
```

into a shell script `fix-permissions.sh` to run at the start, and to keep handy if any of my file permissions get screwed down the road. If this is something other users tend to do a lot, maybe it would be worth adding this to the project for convenience, to save a trip to the docs.

Thanks for all the great work, y'all 💚

**Comment by b7s9** [comment]
idea to improve this would be to first prompt users if they're running nginx or apache, then running

`ps aux | grep -v root | grep ${apache || nginx} | cut -d\  -f1 | sort | uniq` (whatever the syntax would be)

and setting the proper values for the `chown` command

**Comment by rhukster** [comment]
I have a script like this in my `bin` folder.  However, It's not something that's easily generalized to a point where a single script can be reliably used in all circumstances on all server setups, so i don't see how we can put it in core.
