### ISSUE TITLE
Grav 1.7.0-rc.17: Setting User Language Does Not Change Admin Language

### ISSUE THREAD

**Issue by OrthoCube** [getgrav/grav#3039]
Inside the Admin panel, clicking on the current user, choosing (in my case) Japanese as the 'Language' of the user does set 'language: ja' on the user/account/admin.yaml file, but does not actually change the language of the Admin panel.

Is there any way to fix this manually? Old Grav versions does change the language to Japanese when this is set.

Thanks.

**Comment by rhukster** [comment]
I think you will find that logging off and back on will see the language take effect.

You can also enable the `session_user_sync` option in the login plugin to make these kinds of changes take effect immediately: https://github.com/getgrav/grav-plugin-login/commit/8d738a3af9d469bc25578bc9112e15f31d712098

I think we might set this to true by default going forward.

**Comment by OrthoCube** [comment]
Thanks, logging out then logging back in solved it. Thanks!

I'm not too knowledgeable how stuff works in GRAV's Github so please close the issue if no longer needed. :)
