### ISSUE TITLE
[add-resource] New Geocoding Plugin

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3044]
Hi there,
I've written a very simple geocoding plugin, that I want to share with others:
https://github.com/NicoHood/grav-plugin-geocoding

It uses GPL3, not MIT but is compatible with MIT, as far as I understand. It cannot be used in a commercial website that is not open source, unless I give out a per-user license.

**Comment by w00fz** [comment]
Added in GPM - will be available soon.

Thanks! 👍
