### ISSUE TITLE
Twig variables 'pages' contains root page, but not the pages object

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3049]
I recently stumbled across the following issue while tweaking the theme navigation bar and its footer:
```
{{ pages.all|gettype }}
```
Returns NULL

It turns out, that `pages` is not the [Pages Object](https://learn.getgrav.org/16/api#class-gravcommonpagepages) but rather the root of the pages: [`$pages->root()`](https://github.com/getgrav/grav/commit/230a2b594e3f4370db22b5a7dd404a5c9eb665ba#diff-610126884cdfed4d3ac3f346aeb52eb64f1260510b41f41a6adf1d11269fc48dR209).

The [documentation](https://learn.getgrav.org/16/themes/theme-vars#pages-object) however states:

> The pages object represents a nested tree of every page object that Grav knows about.

It also links to the `pages` API, not the `page` API.

Now to solve the issue, we can go two ways:
* **Fix the documentation**
* Fix the code to point to the pages object instead of the root page

The code was added in 2014, so it's been there for quite a long time. The Quark theme for example uses `pages.children.visible` which will fail, if we use the `pages` object, as it required an additional parameter. I guess it would make most sense to fix the documentation? It could make sense to fix this in grav 1.7 as a breaking change.

**Comment by NicoHood** [comment]
Documentation suggestion: https://github.com/getgrav/grav-learn/pull/847

**Comment by mahagr** [comment]
I agree that we shouldn't make the change, but rather fix the documentation.
