### ISSUE TITLE
... exists but is not writable.

### ISSUE THREAD

**Issue by YagizKCKN** [getgrav/grav#3051]
I tried to install Grav but i got many errors. I checked permissions fixed many of them but i cant fix /backup folder error. I tried `chmod 777 /backup` and `chown www:www -R /backup` and they some how broke entire system and gave 404 Not Found. Also tried deleting it didnt work too. I edited /user/config/system.yaml didnt work. I also tried **permission shell script** didnt work either. Any ideas?

> Edit
I tried a skeleton package and backup is okay but now i have the same error with tmp.

**Comment by rhukster** [comment]
Have you gone through these steps? https://learn.getgrav.org/16/troubleshooting/permissions

**Comment by YagizKCKN** [comment]
Yes did all as i stated in text.

**Comment by rhukster** [comment]
You have really provided enough information to determine the issue.  What is the state of the filesystem, are all the files and folder owned by `www` user and `www` group? is that the user the webserver runs with?
