### ISSUE TITLE
grav scheduler creates files owned by root in /cache/compiled, instead of the webserver user  

### ISSUE THREAD

**Issue by downhiller** [getgrav/grav#3052]
My web server runs as `nginx`, and prior to the scheduler running all files in `/grav` are owned by `nginx`.

How can I prevent it from creating files owned by `root`?  The resulting files cause the website to be offline with a  500 server error.

Thank you!

**Comment by rhukster** [comment]
This is why you should have the crontab job setup and running as the 'webserver' user, and not root.

**Comment by downhiller** [comment]
Thanks.  I'll be honest, I wasn't aware that each user had its own crontab. I've now put the scheduler in nginx's crontab with `crontab -u nginx -e` - I guess that'll do it?

Thanks for the pointer.  I don't know if this should maybe be made clearer on https://learn.getgrav.org/16/advanced/scheduler, as it's certainly not a given that people will be logged in as the user that runs their webserver.

**Comment by rhukster** [comment]
I added a note in the docs.  thanks.
