### ISSUE TITLE
Grav should not distribute an user/ directory.

### ISSUE THREAD

**Issue by drzraf** [getgrav/grav#3055]
`user/` directory is for users, they modify it to their will and such changes must not be considered by Grav's git.
I use Grav from git but also gitted (with the `git-sync` plugin) my `user/` directory.
Currently, `git status` reports:
```
	modified:   .gitignore
	modified:   robots.txt
	deleted:    user/pages/01.home/default.md
	deleted:    user/pages/02.typography/default.md
```
(And it would be worst if I didn't gitignored `user/`).

But this is suboptimal, especially if I want to update Grav with a `git pull`.

I think the correct way would be:
- Do not provide `user/` within the git repository
- Create a `sample-user/` directory
- Fix https://github.com/getgrav/grav/issues/2397
- Use a `composer` post-install hook to `cp sample-user/ user/` if the later does not exist

That way git wouldn't consider local modification to `user/` and updates would be smooth.

(Admittedly something could be done for `robots.txt` too but this is less critical)

**Comment by rhukster** [comment]
This is not going to change with version 1.0, as a change of this level would definitely cause people issues.  We might reconsider how we package and bundle the packages and the source repo for version 2.0.
