### ISSUE TITLE
A Page folder starting with "." should be ignored 

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav#306]
Example of possible problems:

.idea/ 
.git/

**Comment by flaviocopes** [comment]
https://github.com/getgrav/grav-plugin-admin/pull/149 fixes the problem but just in the Admin. Maybe it's better to have a parameter in Grav itself, so it will completely ignore passed Pages, defaulting to common hidden folders?

**Comment by rhukster** [comment]
Yah I think it should be something at the Grav level rather than at the admin level.  I could of sworn I added logic to skip dot folders already though???

**Comment by flaviocopes** [comment]
Tried adding the .idea folder but it showed in the Admin Pages list.

I've closed my PR https://github.com/getgrav/grav-plugin-admin/pull/149 in the admin plugin, better move it here.

**Comment by hwmaier** [comment]
Is ignoring dot folders in the page tree going to be implemented? I think its useful, for example to keep a directory unpublished while under construction or to quickly hide something. This should be in addition to ignore_folders.

**Comment by rhukster** [comment]
Pretty sure this is already implemented.  Are you having problems?

**Comment by rhukster** [comment]
Actually just tested, we don't actually have a skip ALL dot files rule, but we do use these settings in the `system.yaml`:

```
  ignore_files: [.DS_Store]            # Files to ignore in Pages
  ignore_folders: [.git, .idea]        # Folders to ignore in Pages
```

To ignore a specific dot folder, add it to the list.

**Comment by rhukster** [comment]
I'm actually going to add a toggle for skipping all 'hidden' files/folders too will be 'true' by default.

**Comment by hwmaier** [comment]
Great. Not sure if a toggle is really needed. Like `_folders` have a modular property auto-magically,  `.folders` could have the hidden property auto-magically. This is what most would expect anyway and this avoids config feature bloat.

**Comment by rhukster** [comment]
Problem is I have to think about backwards compatibility. I can't just change the way something works with out at least having a toggle to return it to the prior state.  It could be that people are using 'dot' folders or files for some reason. 

it really doesn't cost much to add a config option for this, and I know that it would drive me crazy if something just changed and was not easy to fix.
