### ISSUE TITLE
Flex errors

### ISSUE THREAD

**Issue by acondura** [getgrav/grav#3062]
I keep seeing the following errors in PHP error logs:

[10-Nov-2020 09:13:01 America/New_York] PHP Fatal error: Uncaught TypeError: Argument 1 passed to Grav\Framework\Flex\FlexDirectory::createIndex() must be of the type array, bool given, called in /var/www/webroot/ROOT/system/src/Grav/Framework/Flex/FlexDirectory.php on line 892 and defined in /var/www/webroot/ROOT/system/src/Grav/Framework/Flex/FlexDirectory.php:500
Stack trace:
#0 /var/www/webroot/ROOT/system/src/Grav/Framework/Flex/FlexDirectory.php(892): Grav\Framework\Flex\FlexDirectory->createIndex(false, 'storage_key')
#1 /var/www/webroot/ROOT/system/src/Grav/Framework/Flex/FlexDirectory.php(338): Grav\Framework\Flex\FlexDirectory->loadIndex('')
#2 /var/www/webroot/ROOT/system/src/Grav/Common/Service/AccountsServiceProvider.php(155): Grav\Framework\Flex\FlexDirectory->getIndex()
#3 /var/www/webroot/ROOT/system/src/Grav/Common/Service/AccountsServiceProvider.php(66): Grav\Common\Service\AccountsServiceProvider->flexAccounts(Object(Grav\Common\Grav))
#4 /var/www/webroot/ROOT/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\AccountsService in /var/www/webroot/ROOT/system/src/Grav/Framework/Flex/FlexDirectory.php on line 500

[10-Nov-2020 09:36:52 America/New_York] PHP Fatal error: Uncaught Error: Call to a member function trackHit() on null in /var/www/webroot/ROOT/user/plugins/admin/admin.php:419
Stack trace:
#0 /var/www/webroot/ROOT/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\Plugin\AdminPlugin->onShutdown(Object(RocketTheme\Toolbox\Event\Event), 'onShutdown', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#1 /var/www/webroot/ROOT/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onShutdown', Object(RocketTheme\Toolbox\Event\Event))
#2 /var/www/webroot/ROOT/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'onShutdown', Object(RocketTheme\Toolbox\Event\Event))
#3 /var/www/webroot/ROOT/system/src/Grav/Common/Grav.php(491): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(RocketTheme\Toolbox\Event\Event), 'onShutdown')
#4 /var/www/webroot/ROOT/system/src/Grav/Common/Grav.php(551): Gr in /var/www/webroot/ROOT/user/plugins/admin/admin.php on line 419

I use Flex objects for accounts and pages in a Grav 1.7 rc17 installation.

**Comment by acondura** [comment]
![Uploading Screenshot 2020-11-11 at 15.23.15.png…]()

**Comment by acondura** [comment]
<img width="1827" alt="grav-flex-errors" src="https://user-images.githubusercontent.com/1694890/98816866-f6f23d00-2431-11eb-858a-aec05487b399.png">

**Comment by rhukster** [comment]
What version of Grav + Flex are you on?

**Comment by acondura** [comment]
1.7.0-rc.17

On Wednesday, November 11, 2020, Andy Miller <notifications@github.com>
wrote:
> What version of Grav + Flex are you on?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/2h48hGB7D7IMBb_Q1523HkhCdQi3BnR7tmNp3WY0fztEJRHAeYbVBBTsgzv2Lbo4vNENY9hU196EWxXLn_Fok8vBtMGzb2zm4Ordar3zNjBcPLlLMPyTejCUxI8KnffGThrmBaEDE3d05GkbWQJp-hrfir9WZrmBSY6BMlsVGLwjZCL_epwqsH7ZsVOymO2OEbqE93yUozw9iA3eQrnyibiKi56iDLaXsY48LeMv-Q=s0-d-e1-ft#https://github.com/notifications/beacon/AAM5ZKS6DTXKU4YA464RHPLSPLCTJA5CNFSM4TR7SMMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFM7RRUQ.gif>

**Comment by mahagr** [comment]
That should fix it.

**Comment by acondura** [comment]
I'm sorry, what should fix it?

>

**Comment by w00fz** [comment]
> I'm sorry, what should fix it?
> […](#)

Matias commit: https://github.com/getgrav/grav/commit/a9e6d3665f1f193692ccfaf82d07390db255e9ea

**Comment by acondura** [comment]
Right, thank you. I saw the reply in my email and nothing else.
Thank you!
