### ISSUE TITLE
[FEATURE] The location of webroot MUST be a subfolder

### ISSUE THREAD

**Issue by gesof** [getgrav/grav#3066]
Guys, having index.php on the same level with the sources and source control files is just wrong in 2020. There is another issue reported here with a couple of pages of security configuration for nginx exactly to patch this security whole. The solution is to just follow these good practices when building the framework.

**Comment by rhukster** [comment]
This is something we plan to support in Grav 2.0

**Comment by mahagr** [comment]
Actually, it is already partly supported but not enabled by default.
