### ISSUE TITLE
[bin/grav newuser] Password visible in command history

### ISSUE THREAD

**Issue by nunull** [getgrav/grav#307]
I quickly searched for this issue on GitHub, but couldn't find anything. I am new to grav development, so if I've overlooked something, just let me know.

`bin/grav` prompts for a password when used with the `newuser` parameter to add a new user as suggested in the [Administration Panel Introduction](http://learn.getgrav.org/admin-panel/introduction). This, however, results in the password being visible in the command history of your shell. I have huge security concerns regarding this.

When prompting for a password, input should not be displayed. (Like `sudo` does, for instance.)

Any thoughts on this?

**Comment by rhukster** [comment]
Is it really shown in the command history?  It's a PHP command that is running and all you would see is `bin/grav newuser` in your history.

**Comment by nunull** [comment]
@rhukster You might be right. I'm not sure if it would be possible to capture that somehow. Maybe not, but i think it already is an issue to see the password as plaintext in your current session.

**Comment by nunull** [comment]
I just requested for pulling my fix for this, as I don't see any reasons for not changing this behaviour. Maybe there are any?

**Comment by rhukster** [comment]
I'm ok with this if you add some logic to repeat your password and then check the two entries are valid and match.. nothing worse than typing a hidden password field once, with a typo, and then not being able to login because you didn't type what you thought.

Thanks.

**Comment by nunull** [comment]
Agreed, will do so.
