### ISSUE TITLE
Converted img tag from markdown missing /

### ISSUE THREAD

**Issue by replayshot** [getgrav/grav#3071]
I have noticed that when I add an image via markdown to a page 
 `![](sample-image.jpg)`
it converts it to 
`<img src="/sample-image.jpg">`

This is however problematic because it misses the closing `</img>` or '/'. (for example RSS/Atom feeds will not validate because of this)

In the media documentation, https://learn.getgrav.org/16/content/media it says that the markdown should be converted to `<img src="/sample-image.jpg" />`, but it is not so. 

This seems to be a bug or I am missing something.  I've seen this in both of the following versions:
Grav v1.7.0-rc.17 - Admin v1.10.0-rc.17 
Grav v1.6.28 - Admin v1.9.17

I am grateful for any insights/comments. Thank you.

**Comment by w00fz** [comment]
Since HTML5, it is optional for void elements to have a `/` in the tag, most IDE with linters and validators do seem to prefer avoiding adding it and markdown converters, such parsedown (the grav uses), seem to omit it too as you have noticed.

> Start tags consist of the following parts, in exactly the following order:
> [...]
> 5. Optionally, a "/" character, which may be present only if the element is a void element.

https://www.w3.org/TR/2011/WD-html-markup-20110113/syntax.html#void-element

**Comment by replayshot** [comment]
thank you for the quick reply.  The weird thing is that this missing closing slash issue only happens on individual post (blog item). For example my meta tag which is pulled from the base template and is the same everywhere, shows up fine on the home page and blog listing page, but misses the final slash on the post item page. Would you have an idea why this would happen? Even if you throw out some thought that might point me into a direction to investigate.

**Comment by replayshot** [comment]
It appears, the problem is with this plugin: https://github.com/trilbymedia/grav-plugin-image-captions  (version 2.0.1)- After disabling it, all is as it should be. Better yet, after disabled the feature of the plugin to Scan the entire page, it works fine.
