### ISSUE TITLE
1.7 Final Issues / Enhancements

### ISSUE THREAD

**Issue by w00fz** [getgrav/grav#3072]
Here to list all the known and final issues that we do need to get resolved before 1.7 release:

- [x] system:// stream is causing issues in Admin, making Media tab to disappear and possibly causing other issues. First introduced via https://github.com/getgrav/grav/commit/747055f60e3e897a76363161dd16108c4048913a
- [x] Add `user/env` as primary environmental location and fallback to `user/` (for traditional behavior backward compatibility). This will allow to keep all the environments under one place the user folder tidy.
- [x] Autoescape will be enabled by default and to guarantee BC we need postflight installer to be able to handle installations vs updates. (ed. I believe this is already done)
- [x] Support picking up changes in Flex Users (such as manual password reset) when a user yaml is updated.
- [x] `safe_email` filter should remove HTML from the email (tags, entities) and output HTML safe output [see here](https://github.com/getgrav/grav/issues/3069#issuecomment-731774440).
- [x] Fix clockwork to work with the latest client

// cc: @rhukster @mahagr

**Comment by mahagr** [comment]
`system:// stream` issue has been fixed in Toolbox update (needs a release).

**Comment by mahagr** [comment]
Clockwork client 5.0.1  has a bug on rendering user defined data. The bug has been fixed, but isn't released just yet.

**Comment by mahagr** [comment]
@rhukster For object refresh support grav, **login** and flex plugins need to be updated
