### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by iainsgillis** [getgrav/grav#3077]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **iainsgillis/grav-plugin-plausible**

Minimal implementation for using [Plausible Analytics](https://plausible.io) in Grav without manually tweaking themes.

Plausible is a lightweight, open-source, privacy-focused alternative to Google Analytics or Matomo.

**Comment by w00fz** [comment]
Added in GPM - will be available soon.

Thanks! 👍
