### ISSUE TITLE
1.7 Migration 404 Error page

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3078]
> BACKWARDS COMPATIBILITY BREAK: We fixed 404 error page when you go to non-routable page with routable child pages under it. Now you get redirected to the first routable child page instead. This is probably what you wanted in the first place.

https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#pages

Is there an option to disable this behavior? I do not want this behavior, if possible.

**Comment by mahagr** [comment]
It redirects only if
1. current page is not routable
2. there is a visible child

So if you do not have items in the menu which are visible, no redirect happens.

Is there a real use case for this?

**Comment by NicoHood** [comment]
Okay, the fact about visible pages is new to me. So this only applies to pages shown in the main navbar?

In that case it should be fine, but also added to the docs.

**Comment by w00fz** [comment]
Any help in the docs front is more than welcome. So if you feel like it, open a PR in learn and we can merge it!

**Comment by NicoHood** [comment]
https://github.com/getgrav/grav-learn/pull/862
