### ISSUE TITLE
readme.md redirected/broken link (/blob/develop)

### ISSUE THREAD

**Issue by CouldBeThis** [getgrav/grav#3085]
On the page https://github.com/getgrav/grav/#from-github (you have to go to that page I don't think it will duplicate from Issues) it says:

> 1. Clone the Grav repository from https://github.com/getgrav/grav to a folder in the webroot of your server, e.g. ~/webroot/grav. 

* the URL stated _actually_ links to https://github.com/getgrav/grav/blob/develop 
* adding **/blob/develop** breaks the link

**Comment by mahagr** [comment]
Looks like this is fixed in 1.7 but not in develop.
