### ISSUE TITLE
Collection.copy() return type

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3086]
I am looking at the documentation of page collections:
https://learn.getgrav.org/16/api#class-grav-common-page-collection

```
copy() : \Grav\Common\Page\static
Create a copy of this collection
```

https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Collection.php#L82-L91

The return type is not a Page, it is rather a Collection. However I am not sure about this static thing, so I am not sure if the correct fix would be `Collection` or `static|collection` or something else.

**Comment by mahagr** [comment]
The return type is `static` which is the `Collection` itself (or class that extends it). Thus return type is correct. It is the API docs generator which does not work properly.
