### ISSUE TITLE
Error on modular page delete 1.7.0-rc.18

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav#3088]
`Argument 1 passed to Grav\Framework\Flex\Storage\FolderStorage::deleteFile() must be an instance of RocketTheme\Toolbox\File\File, instance of Grav\Common\File\CompiledMarkdownFile given, called in /home/getwheat/public_html/system/src/Grav/Framework/Flex/Storage/FolderStorage.php on line 186`

**Comment by hotdoy** [comment]
On pages as well (not just modular)

**Comment by Flamenco** [comment]
And from the context menu `delete` from the pages.html page.

**Comment by rhukster** [comment]
Please try rc.19 which was released to include an important update to Toolbox that was missed in the rc.18 version.

**Comment by mahagr** [comment]
Fixed in rc.19
