### ISSUE TITLE
GPM not reachable

### ISSUE THREAD

**Issue by christophdoering** [getgrav/grav#3093]
In GPM.php line 497:
                                                                               
  GPM not reachable. Please check your internet connection or check the Grav   
  site is reachable

This worked for me:
Errors in Admin Page - Plugins #1044
but i had to edit: response.php as described

Any ideas?

**Comment by mahagr** [comment]
We have replaced the logic in Grav 1.7, which will be out in a short time. So I'm considering this issue as being fixed.
