### ISSUE TITLE
wrong parentheses on css--var -- grav css minify

### ISSUE THREAD

**Issue by tacoen** [getgrav/grav#3095]
grav css minify turn
    --c-b: hsl(var(--h), var(--s), calc(var(--l) + (calc(var(--df) * -5))));

into
    --c-b: hsl(var(--h),var(--s),calc(var(--l) +)calc(var(--df) * -5))));

 wrong parentheses on calc(var(--l) +)

**Comment by rhukster** [comment]
Actually, this is an upstream bug in `matthiasmullie/minify` library I commented on a while ago:

https://github.com/matthiasmullie/minify/issues/312

**Comment by rhukster** [comment]
BTW, solution at the moment is to ensure the CSS file that contains this calc is not minified by keeping it out of the pipeline: with `{position: after}` for example: https://learn.getgrav.org/16/themes/asset-manager#for-css
