### ISSUE TITLE
attempting to save user calls with null

### ISSUE THREAD

**Issue by Andy-Flack** [getgrav/grav#3101]
Select user from list
view user 
save

Argument 1 passed to Grav\Common\User\DataUser\User::filterUsername() must be of the type string, null given, called in /var/www/html/system/src/Grav/Common/User/DataUser/User.php on line 123.

I have just updated to latest on all modules

This is NOT related to the 2fa fix I have running as I have tested with and without and both fail.

**Comment by mahagr** [comment]
https://github.com/getgrav/grav/commit/d34593928da30df8996f9def3d2ee3b5033adb47
