### ISSUE TITLE
getgrav.org/blog RSS Feed not functional

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3102]
I've added the Grav RSS Feed into my thunderbird. It can read all existing entries, and it is a valid xml it seems. However I did not receive new entries for the 1.7 News. I removed the Feed and added it again. Now the post about grav premium also did not pop up. All other feeds work as expected. I think it is also in your interest to provide the users with updates, especially about grav premium ;-)

**Comment by arkhi** [comment]
I ran the feed [through the RSS Validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fgetgrav.org%2Fblog.rss) to see what’s wrong.

Seems like the language is missing:

> line 8, column 18: language must be an ISO-639 language code: [help]

```xml
       <description>Grav Development Blog</description>
       <language></language>
       <lastBuildDate>Mon, 07 Dec 2020 11:49:00 +0000</lastBuildDate>
```

**Comment by NicoHood** [comment]
It is still broken

**Comment by rhukster** [comment]
Fixed the feed plugin (in develop).  And updated getgrav.org to use it.  Passes validation with just 'recommendation' to not use relative URLs although they are fully supported.
