### ISSUE TITLE
Unable to save with PHP8

### ISSUE THREAD

**Issue by xf-** [getgrav/grav#3107]
Version Grav 1.7-rc20

Error
```
Save Failed: Array to string conversion
```

Exception
```
user/plugins/flex-objects/classes/Admin/AdminController.php
Line 735
```

**Comment by rhukster** [comment]
Does it work with PHP 7.4??

**Comment by xf-** [comment]
@rhukster yeah works with 7.4

e.g. configuration -> site or config save

**Comment by mahagr** [comment]
@xf- Is this still an issue? If so, can you please update the error for me as the file has been changed?

**Comment by xf-** [comment]
@mahagr looks like it is resolved.
