### ISSUE TITLE
Markdown headers should process markdown

### ISSUE THREAD

**Issue by johnnywon** [getgrav/grav#311]
When creating a markdown file, the header's section text should accept markdown. 

Currently only the markdown's page content renders markdown so the power of using sections is lost with markdown. 
    
For example: 
    ---
    title: Demo Example
    sections:
        - title: Hello World
          texts: 
              - ### Diam tempor dui lacinia accumsan.
              - [plugin:youtube](https://www.youtube.com/watch?v=BK8guP9ov2U)
        - title: Hello Land
          texts: 
              - ### Diam tempor dui lacinia accumsan.
              - [plugin:youtube](https://www.youtube.com/watch?v=BK8guP9ov2U)
    ---
    + Gravida dis placerat lectus ante vel nunc euismod est turpis sodales. 
    + random-02.png
    + Random thought 3

**Comment by rhukster** [comment]
You can explicitly render anything (including page header) with markdown from the Twig:

```
{{ page.header.texts|markdown }}
```
