### ISSUE TITLE
CLI selfupgrade to RC20 Claims Success But Does Not Update

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav#3116]
Used `bin/gpm selfupgrade` successfully on my local dev system (PHP 7.3.20). When I tried that on production (PHP 7.3.25), I got the success message below:

![CLI_selfupgrade-result](https://user-images.githubusercontent.com/998832/103225345-b2463680-48f7-11eb-9c95-ada3640f085d.png)

But `bin/grav -V` returns "Grav CLI Application 1.7.0-rc.17"

Ran the update in Admin and it succeeded and CLI now throws error "PHP version ">= 7.3.6". You are running 7.2.24-0ubuntu0.18.04.7". 

So my CLI version on production was the issue - a check and warning message before update/upgrade would be helpful.

**Comment by rhukster** [comment]
Can you try this again with the latest 1.7.0 final release? I think it must be a caching issue, can you try clearing cache afterward also?

**Comment by mahagr** [comment]
Grav 1.7.0-rc.17 was the last version supporting PHP 7.2. To me, it looks like the installation fails but CLI fails to report the error.

You need to upgrade your PHP.

**Comment by mahagr** [comment]
OK, this was an issue with installation error detection when using the command (it was only detecting unzip issues).

Unfortunately, this will still be an issue when upgrading from older versions, but at least it is fixed from Grav 1.7.1 onwards.

**Comment by thekenshow** [comment]
Thanks, I'll test this on my next update.

**Comment by mahagr** [comment]
I don't think you can test this as the issue is in Grav 1.6 and you need to get your CLI to use PHP 7.3/7.4 to update in the first place.

**Comment by thekenshow** [comment]
I have other sites hosted on this server, and I have updated my CLI PHP version.
