### ISSUE TITLE
Scheduler status differes between admin plugin and command line

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3119]
Using grav 1.6.31

```
$ bin/grav scheduler -j

Scheduler Jobs Listing
======================

┌─────────────────────┬────────────────────────────────────┬───────────┬────────┬──────────┬─────────┐
│ Job ID              │ Command                            │ Run At    │ Status │ Last Run │ State   │
├─────────────────────┼────────────────────────────────────┼───────────┼────────┼──────────┼─────────┤
│ cache-purge         │ Grav\Common\Cache::purgeJob        │ 0 4 * * * │ Ready  │ Never    │ Enabled │
│ cache-clear         │ Grav\Common\Cache::clearJob        │ 0 3 * * * │ Ready  │ Never    │ Enabled │
│ default-site-backup │ Grav\Common\Backup\Backups::backup │ 0 3 * * * │ Ready  │ Never    │ Enabled │
└─────────────────────┴────────────────────────────────────┴───────────┴────────┴──────────┴─────────┘

 ! [NOTE] For error details run "bin/grav scheduler -d" 
```

![image](https://user-images.githubusercontent.com/6888294/103445565-22e1b000-4c76-11eb-9dca-96b3cb278cfa.png)

The Admin Plugin says disabled, the command line enabled. I did not set any explicit setting, so I guess it is disabled? I dont know.

**Comment by w00fz** [comment]
What about 1.7? In less than a month that will be released as stable and all our focus is put towards it right now.

**Comment by NicoHood** [comment]
Grav 1.7 RC 20 is the same

**Comment by mahagr** [comment]
I fixed a similar issue to this: https://github.com/getgrav/grav/commit/cc8ec10098fb7acf370596fbbbe8fbb2ca278a1a

This allows you to define `--env=www.domain.com` to run the scheduler for that specific site.

PS. If you run the scheduler without an environment, make sure that the commands are in the global configuration, not under the environment.
