### ISSUE TITLE
Run CLI command with different config context rather than 'localhost'

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3120]
Looking at https://github.com/getgrav/grav-plugin-admin/issues/2010 it causes me some trouble to differentiate between plugin configs for localhost and cli commands.

For example I want to enable some special debug settings for localhost/development. I do not want those to run on the production server. However I have also added them to the git, which makes sense. But the cli commands also pickup those localhost settings, but they should not. They should rather pickup the domain setting (e.g. `example.org`) or a special `cli` context.

**Comment by mahagr** [comment]
CLI doesn't have a domain name available and in most servers, it's different from the sites anyway. So CLI just cannot use any environment. I think that CLI should actually not use any environment at all and just stick on the `user/config` instead.

@rhukster Should we disable the environment by default? I am already using `--env=''` in a few scripts to prevent me from having issues in multi-site setups.

**Comment by rhukster** [comment]
this is not something that can easily be removed.  It's actually used in several commands where it's needed to pick up configuration for those environments.  Pretty sure the CLI commands initialized URI with the environment, so while things like PHP constants are not going to be accurate, to Grav and it's internals such as configuration it is.

**Comment by NicoHood** [comment]
This issue is obsolete, as you can use --env now.
