### ISSUE TITLE
[Grav 1.7] Metadata template should not use escaping

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3121]
https://github.com/getgrav/grav/blob/fdf884036da0c3b613be75e815eaebb6de015722/system/templates/partials/metadata.html.twig

When having a metadata of `red & blue` this is getting escaped twice with Grav 1.7. I guess this is done somewhere in the code and also via default escaping. What I am not sure about is, if only `content` must have a `raw` filter, or `property`, `charset`, `name` and `http_equiv` as well. Or if there is even a better fix.

**Comment by NicoHood** [comment]
I found another issue: Site metadata is not escaped, while page metadata is. This causes issues in my case, as I must handle those cases differently, which is nearly impossible.
```
{{site.metadata.description}}<br>
{{page.metadata.description.content}}
```

**Comment by mahagr** [comment]
No need to change anything. I made the method to automatically take care of whether to escape or not.

**Comment by NicoHood** [comment]
Nice, that works for me!
