### ISSUE TITLE
[add-resource] JSON-LD Breadcrumbs Plugin

### ISSUE THREAD

**Issue by arkhi** [getgrav/grav#3125]
I would like to add [this new plugin](https://github.com/arkhi/grav-plugin-json-ld-breadcrumbs/tree/1.0.0) to the Grav Repository.

It adds the [breadcrumbs as a JSON-LD object](https://schema.org/BreadcrumbList) for the current page in the `<head>` of the page, root included.

This means semantic breadcrumbs should be available for any theme without modification.

**Comment by rhukster** [comment]
Added to GPM. Thanks.

**Comment by arkhi** [comment]
With pleasure. :)
