### ISSUE TITLE
Error adding user in 1.7

### ISSUE THREAD

**Issue by Japhys** [getgrav/grav#3126]
I added a user with 

Nickname
Full name
Password
emailadres

Ubuntu 20.04 / Apache 2.4 / PHP Version 7.4.11 / Grav v1.7.0-rc.19 - Admin v1.10.0-rc.19

And I get this error consistently

` TypeError
Argument 1 passed to Grav\Common\User\DataUser\User::filterUsername() must be of the type string, null given, called in /var/www/html/----/public_html/system/src/Grav/Common/User/DataUser/User.php on line 123`

My solution for know, which is not a solution: I just added the user in 1.6 (same details) and copied the user file to 1.7 environment

**Comment by mahagr** [comment]
Already fixed in Grav v1.7.0-rc.20.
