### ISSUE TITLE
Bug with accentuated character when using truncate filter 

### ISSUE THREAD

**Issue by simogeo** [getgrav/grav#313]
Accent characters are not supported when using truncate Twig filter. See below.

![truncate_bug](https://cloud.githubusercontent.com/assets/154323/9785806/553efb18-57b5-11e5-8a0c-525a3954c3fa.png)

I don't know how things are coded right now but I guess using [mbstring](http://php.net/manual/en/book.mbstring.php) would prevent the issue. See also : http://php.net/manual/en/function.mb-strcut.php

**Comment by rhukster** [comment]
I just updated this the other day to support multibyte strings!

https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Twig/TwigExtension.php#L132-L149

**Comment by simogeo** [comment]
Indeed ! Perfect

**Comment by simogeo** [comment]
Actually, it does not work with html content because it relies on truncateHtmlFilter() function so TruncatorHelper.https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Helpers/Truncator.php

**Comment by rhukster** [comment]
Yes only the regular 'text' truncate filter works with multibyte.  You can strip tags before using it:

```
{{ my_text|striptags|truncate(100) }}
```

The truncateHTML filter is a 3rd party function that currently does not support multibyte.  However I did open an issue about that too:

https://github.com/urodoz/truncateHTML/issues/1

**Comment by simogeo** [comment]
Does not seem to work

text is : "Mise œuvre de Linea21 comme plateforme d'information et d'échanges entre les villes du réseaux et les différents partenaires de l'étude. Déploiement de l'application en anglais."

en twig call is : 

```
{{ text|striptags|truncate(110) }}
```

**Comment by rhukster** [comment]
text is before or after truncation?

**Comment by simogeo** [comment]
before

**Comment by rhukster** [comment]
and after? what are you expecting, what are you seeing?

**Comment by simogeo** [comment]
always the same : 

![truncate_bug](https://cloud.githubusercontent.com/assets/154323/9785806/553efb18-57b5-11e5-8a0c-525a3954c3fa.png)

**Comment by rhukster** [comment]
Did you update your code to use the newer mbstring version i linked to above?  It is not in the current version of Grav, but will be so in the next release.

**Comment by simogeo** [comment]
Yes, I've updated /Twig/Twig.php, /Twig/TwigExtension.php and /helpers/Truncator.php files.

**Comment by rhukster** [comment]
Ok, that's odd, i will have to investigate this a little.

**Comment by siren386** [comment]
Is the file formatted with UTF8-without BOM? I use notepad++ where the default ist UTF8 and this always gives me the same results on special (Austrian) characters ...

**Comment by simogeo** [comment]
it is ut-8 encoded.

Please @rhukster, reopen the bug.
I will update on next release and let you know when tested

**Comment by flaviocopes** [comment]
@simogeo a string like this works for you?

`{{ "éééééééééééééééééééé"|striptags|truncate(4) }}`

**Comment by Sommerregen** [comment]
@rhukster Looking into this problem, I noticed that Grav has three different functions for doing the same thing

1.) https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Twig/TwigExtension.php#L132-L149
2.) https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Utils.php#L116-L213
3.) https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Twig/TwigExtension.php#L161-L164

(ok but at least two). Maybe it is worth of a refactoring?

**Comment by flaviocopes** [comment]
Good catch. Should all use the Truncator helper I think

**Comment by simogeo** [comment]
@flaviocopes : it works ... strange. I will investigate on my part

**Comment by flaviocopes** [comment]
@Sommerregen care to open a ticket with that?

**Comment by simogeo** [comment]
Got it ... I think the truncate function do not use mbstring to cut strings

`{{ "éééééééééééééééééééé"|striptags|truncate(4) }}`

display only **éé...** and should of course display **4 chars**, ie `éééé`

And 

`{{ "éééééééééééééééééééé"|striptags|truncate(5) }}`

display `éé�…`

**Comment by flaviocopes** [comment]
Both work fine for me. What's the difference in the second, it should display 5 chars (ééééé...)

**Comment by flaviocopes** [comment]
Maybe it's just the fact I'm using Grav from github's latest develop branch, maybe those 3 files you copied are not all it's needed

**Comment by simogeo** [comment]
@flaviocopes : I thought updating these files was enough. Seems to be not !

Is there a way to sync grav with github repo using gpm ?

**Comment by flaviocopes** [comment]
Not with gpm. This is the best way to be in sync with the latest develop branch: http://learn.getgrav.org/advanced/grav-development#github-setup

Anyway I think @rhukster will push an update today.

**Comment by Sommerregen** [comment]
@flaviocopes I will file an issue.

**Comment by rhukster** [comment]
Should be sorted now!
