### ISSUE TITLE
config.plugin for plugins file/folder names with -

### ISSUE THREAD

**Issue by cord** [getgrav/grav#314]
A '-' in the plugin files folder name seems to confuse twig:

Does not work:
`{{ config.plugins.my-plugin.enabled }}`

Does work:
`{{ config.plugins.my_plugin.enabled }}`

So `{{ config.plugins.advanced-pagecache.enabled  }}` does not deliver the status of the plugin.

same seems to be the case for the parameter names.

**Comment by flaviocopes** [comment]
`-` is not an acceptable char in Twig attributes, so you must use `{{ config.plugins['my-plugin'].enabled }}`

**Comment by flaviocopes** [comment]
Just read the comment on the referenced issue
