### ISSUE TITLE
1.7: Should functions in plugin with names of events be called without subscribing to events?

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#3143]
I noticed that functions with names corresponding to existing events get called, even when `getSubscribedEvents()` is not defined and no events are subscribed to.

Tested on Grav 1.7 with functions `onPluginsInitialized()` and 'onPageInitialized()'

**Comment by rhukster** [comment]
I feel you should still have to subscribe the method even if the name matches the event name. This is to ensure you meant to call it at the appropriate time, in the appropriate manner.  I've not tested this as I always manually subscribe, but seems like a bug to me.

Any thoughts @mahagr?

**Comment by mahagr** [comment]
That is part of Symfony Event Dispatcher implementation. I think that is something that will be changing, though, as Symfony now follows PSR-14.
