### ISSUE TITLE
Refactoring truncate function

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav#315]
This is a gentle reminder that there exist three `truncate` functions in Grav doing (almost) the same thing and hence should be refactored.

1.) https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Twig/TwigExtension.php#L132-L149
2.) https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Utils.php#L116-L213
3.) https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Twig/TwigExtension.php#L161-L164

Either one provides an own unique implementation (without needing any third party module) or one simple sticks to the already in use [truncateHTML](https://github.com/urodoz/truncateHTML/blob/master/src/TruncateService.php) library, which does not support UTF-8 at the moment (see issue here https://github.com/urodoz/truncateHTML/issues/1).

I don't know what's the best. Maybe provide one own?

**Comment by rhukster** [comment]
Should all be sorted! Had to refactor Truncator a little to fix some stuff that was not working properly, and also add UTF-8 support to it.

**Comment by Sommerregen** [comment]
Ok. Glad to know!
