### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS with HTTPS = 'On'

### ISSUE THREAD

**Issue by b2z** [getgrav/grav#3155]
Hello,

We have a hosting that has server `HTTPS` var set as `On` instead of `on`. These produces the loop redirect with ERR_TOO_MANY_REDIRECTS as a final error. The dirty fix is to set  `$_SERVER['HTTPS'] = 'on'` to the `index.php`, but I am sure it is too dirty :)

**Comment by b2z** [comment]
Thanks. I will test the fix and let you know.

**Comment by Sulpher** [comment]
This patch disappeared in the latest version of Grav. Please return it back ;-)
I mean the problem occur again after updating Grav, so I had to add the line ```$_SERVER['HTTPS'] = 'on'``` to index.php again.

**Comment by Sulpher** [comment]
UPD: the front-end works, the admin panel gets endless redirects.
If I add this line:
$_SERVER['HTTPS'] = 'on' 

then the admin panel is loading correctly.

**Comment by mahagr** [comment]
You cannot just manually patch the files, every update removes all your changes. Please create a new issue about the admin redirect and try to provide more information about your setup.

**Comment by Sulpher** [comment]
Sorry, but I have no idea what additional information can be provided from my side.
We use the latest version of Grav and PHP 7.4.10.
I found this issue, the patch of index.php helped. I shared this info.

**Comment by mahagr** [comment]
It looks like your server isn't using HTTPS then, or fails to report on that. Do you have some kind of proxy setup?

**Comment by mahagr** [comment]
Ok, there was another issue in admin. Thanks!
