### ISSUE TITLE
Flex Pages: No way to determine page type from blueprint?

### ISSUE THREAD

**Issue by rcheetah** [getgrav/grav#3157]
In the context of a blueprint, there seems to be now way to determine the page type of a page.

Before 1.7 you could tell the type of page by using $blueprint->getFilename(). This would return the type like `default` or `modular` or `modular/jumbotron` etc. But in 1.7 every page has the filename `blueprints://flex-objects/pages.yaml`, no matter what type of page it is. Therefore you can't extend specific blueprints, you can only extend the global pages blueprint. You can't add new fields only for pages of type 'modular'. 

```php
// Grav v1.6.*
public function onBlueprintCreated(Event $event)
{
    /** @var Data\Blueprint $blueprint */
    $blueprint = $event['blueprint'];
    $this->grav['debugger']->addMessage($blueprint->getFilename()); // ->  'default'  ||  'modular'  ||  'modular/text'
}


// Grav v1.7.0-rc
public function onBlueprintCreated(Event $event)
{
    /** @var Data\Blueprint $blueprint */
    $blueprint = $event['blueprint'];
    $this->grav['debugger']->addMessage($blueprint->getFilename()); // -> 'blueprints://flex-objects/pages.yaml'
}
```

**Comment by mahagr** [comment]
@rcheetah The event should now be backwards compatible. Also, the event will now be including `$event['type']` and it's being fired only once in admin, see https://github.com/trilbymedia/grav-plugin-flex-objects/commit/bccf43b52f54f416e82ba646be0942ca0b27fdfe
