### ISSUE TITLE
Cannot move a page to Root (/)

### ISSUE THREAD

**Issue by Ribero** [getgrav/grav#3161]
Grav v1.7.0 - Admin v1.10.0

If I try to move `01.page` from `/folder/` to `/` I get a crash: 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2266264/105156291-ea622300-5b0b-11eb-8c5c-91b505ce62c5.png">

If I try to move the same page to another subfolder, for ex : from `/folder` to `/folder2` no problem
Issue occurs when trying to move to `/`

Details:
[Crikey! There was an error.html.zip](https://github.com/getgrav/grav-plugin-admin/files/5841458/Crikey.There.was.an.error.html.zip)

**Comment by mahagr** [comment]
@Ribero Thanks for reporting the issue. It has now been fixed for the next version.
