### ISSUE TITLE
1.7 Unexpected character "&" in Page

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3162]
When using the following code (simplified) in my `default.md` using `process.twig: true` it fails:
```
[schreibe uns einfach eine Email.]({{ '/kontakt' }})
```

This worked with 1.6

**Comment by mahagr** [comment]
Content of the parsed markdown is:

```
<p><a href="{{ &#039;/kontakt&#039; }}">schreibe uns einfach eine Email.</a></p>
```

**Comment by mahagr** [comment]
This is actually the expected result in the new parsedown library. It escapes the links.

However... This is something we may want to detect and prevent from happening, content inside `{{ ... }}`, `{% ... %}` and `{# ... #}` should not be parsed if twig parsing is enabled and happens after Markdown has been converted to HTML.

**Comment by mahagr** [comment]
@NicoHood Can you try out the fix?

**Comment by NicoHood** [comment]
The fix works. It looks a bit hacky with the base64 though.

**Comment by mahagr** [comment]
Well, the purpose was to hide the content from the Markdown parser. I thought first about just replacing certain characters, but then I thought that nothing inside twig should be seen as Markdown code:

```twig
{{ 'This is *My* text.'|markdown }}
```

as it could have crazy side effects. So I thought if I just make it to look text, there shouldn't be any issues. You can still use conditional statements and loops as only twig tags are being hidden.

**Comment by NicoHood** [comment]
Alright, yeah I dont have any better idea.
