### ISSUE TITLE
Aborted  upgrade 1.7 -> 1.7.1 Unsupported option "curl" passed to "Symfony\Component\HttpClient\CurlHttpClient"

### ISSUE THREAD

**Issue by saramato** [getgrav/grav#3165]
When upgrading from 1.7 to 1.7.1 from the console (PHP 7.4.14 (cli))

In HttpClientTrait.php line 223:
Unsupported option "curl" passed to "Symfony\Component\HttpClient\CurlHttpClient", did you mean "auth_basic", "auth_bearer", "query", "headers", "body", "json", "user_data", "max_redirects", "http_ve  
  rsion", "base_uri", "buffer", "on_progress", "resolve", "proxy", "no_proxy", "timeout", "max_duration", "bindto", "verify_peer", "verify_host", "cafile", "capath", "local_cert", "local_pk", "passphra  
  se", "ciphers", "peer_fingerprint", "capture_peer_cert_chain", "extra", "auth_ntlm"?

**Comment by saramato** [comment]
Something wrong with my apache2/php configuration?

**Comment by lleddewk** [comment]
Me too with nginx / php 7.3.19 updating from the CLI using gpm selfupgrade.  The error message is exactly the same.

**Comment by acondura** [comment]
Running the update from the admin UI seems to go successfully. If that fails too, try setting Configuration > System > Advanced > Remote Fetch Method to Auto or Fopen and update again.

**Comment by lleddewk** [comment]
Thanks.  I manually patched the file system/src/Grav/Console/Gpm/SelfupgradeCommand.php and now the upgrade works flawlessly. Thanks again.

**Comment by mahagr** [comment]
Running this in Grav root should fix the issue:

```
wget https://raw.githubusercontent.com/getgrav/grav/c8af0d8a385a4dce7d5c5ef54a50c23b5946167f/system/src/Grav/Console/Gpm/SelfupgradeCommand.php -O system/src/Grav/Console/Gpm/SelfupgradeCommand.php
```

**Comment by saramato** [comment]
After replacing the 'system/src/Grav/Console/Gpm/SelfupgradeCommand.php' file, the upgrade runs without any problems. Thanks!

**Comment by jeremycherfas** [comment]
Re-opening this issue. I Just  got the same error. Currently on 1.7.0-rc.20

```
In HttpClientTrait.php line 223:
                                                                               
  Unsupported option "curl" passed to "Symfony\Component\HttpClient\CurlHttpC  
  lient", did you mean "auth_basic", "auth_bearer", "query", "headers", "body  
  ", "json", "user_data", "max_redirects", "http_version", "base_uri", "buffe  
  r", "on_progress", "resolve", "proxy", "no_proxy", "timeout", "max_duration  
  ", "bindto", "verify_peer", "verify_host", "cafile", "capath", "local_cert"  
  , "local_pk", "passphrase", "ciphers", "peer_fingerprint", "capture_peer_ce  
  rt_chain", "extra", "auth_ntlm"?   
```
I tried the fix at https://github.com/getgrav/grav/issues/3165#issuecomment-764680561  and got 

```
HTTP request sent, awaiting response... 416 Range Not Satisfiable

    The file is already fully retrieved; nothing to do.
```
What now? My site is unreachable.

**Comment by jeremycherfas** [comment]
> What now? My site is unreachable.

In the end I downloaded `system/src/Grav/Console` by hand and went from there. Error updating Problems, which seems to want grav 1.7.11 but otherwise OK.

**Comment by mahagr** [comment]
@jeremycherfas It has been fixed in later version of Grav. you need to manually update from update package.
