### ISSUE TITLE
Page order by header sorts integers different on webserver than on localhost

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3167]
I have multiple pages with headers  like `footer: 10`. I am generating an ordered list of this pages as footer.

```twig
{% set footer_pages = page.collection({'items': '@root.descendants', 'order': {'by': 'header.footer'}})|filter(x => x.header.footer == true) %}
{% if footer_pages|length %}
  <ul class="footer-list">
    {% for p in footer_pages %}
      {% set active_page = (p.active) ? 'active' : '' %}
      <li>
        <a href="{{ p.url }}" class="{{ active_page }}">
          {{p.header.footer}}{{ p.menu }}
        </a>
      </li>
    {% endfor %}
  </ul>
```

On localhost:
![grafik](https://user-images.githubusercontent.com/6888294/105337273-82c6d900-5bda-11eb-8011-fe10529277af.png)

On Server:
![grafik](https://user-images.githubusercontent.com/6888294/105337185-66c33780-5bda-11eb-9441-d18667410571.png)

It looks like the server is sorting the integers maybe via string compare rather than normal int compare. Both run php 7.4, but the server uses apache, while on localhost I am running via `php -S 0.0.0.0:8000 system/router.php`.

Do you have any hint why this could happen?

**Comment by mahagr** [comment]
Looks like the first ordering is using natural ordering and the second is using character-by-character ordering. Look at the last method in `system/src/Grav/Common/Page/Pages.php`

**Comment by NicoHood** [comment]
Localhost uses:
https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Pages.php#L1979

Server uses (Collator::SORT_STRING):
https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Pages.php#L1974

It seems `extension_loaded('intl')` is not loaded locally. Now from the admin panel this seems to be not a required dependency, however the sort seems wrong with the extension anyways.

I guess there is something wrong with the implementation: `array_shift($list_vals)` contains the following and is (of course) always not numeric:
```
/var/www/vhosts/hosting00000000000000000000000000123456.a123eee0000000000000000000000123456.netcup.net/httpdocs/test.mydomain.de/user/pages/00000000000000000000000000000001.home
```

**Comment by mahagr** [comment]
@NicoHood Try setting collator up: `$col->setAttribute(Collator::NUMERIC_COLLATION, Collator::ON);`

**Comment by NicoHood** [comment]
That works!

**Comment by mahagr** [comment]
Let me fix that.

**Comment by NicoHood** [comment]
Thanks, nice!

And the other options are not affected? To me it looks like numeric sorting is now always applied. I have no knowledge about that at all, so I might be wrong. Also I am wondering why the full path (see post above) is used for sorting, is that correct?

**Comment by mahagr** [comment]
It is what is applied to normal search, too. Basically, it just sorts numbers as 1 < 10 < 100 < 1000, otherwise it works like normal sort.

**Comment by NicoHood** [comment]
Guess this can be closed then
