### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by wernerjoss** [getgrav/grav#3168]
I would like to add my new plugin to the Grav Repository.
Here are the project details: 
[Ipcount on Github](https://github.com/wernerjoss/grav-plugin-ipcount)

**Comment by wernerjoss** [comment]
Update: V 1.3.0 can now also visualize dayly visitor counts in a Diagram.

**Comment by rhukster** [comment]
Added to GPM. Thanks.
