### ISSUE TITLE
Upgrade 1.7.1 : ERROR: flex-objects.html.twig template not found for page: 

### ISSUE THREAD

**Issue by Open-wan** [getgrav/grav#3169]
ERROR: flex-objects.html.twig template not found for page:  
- accounts
- pages
on admin panel (1.10.2) after upgrade 1.7.1 ( idem with 1.7.2)

**Comment by rhukster** [comment]
I don't see that. Are you on latest version of flex-objects?  Tried clearing cache?

**Comment by Open-wan** [comment]
Flex Objects v1.0.1
no improvement after clearing cache

**Comment by mahagr** [comment]
I cannot reproduce either. Do you have some extra plugins installed?

**Comment by Open-wan** [comment]
Admin Panel  v1.10.2
 Custom CSS  v0.2.2
 Email  v3.1.0
 Error  v1.7.1
 Flex Objects  v1.0.1
 Form  v4.3.0
 Leaflet Address v1.0.1
 Login  v3.3.8
 Map Marker Leaflet v1.1.2
 Markdown Color  v1.0.1
 Markdown Notices  v1.1.0
 matomo v1.0.3
 piwik v1.0.2
 Problems  v2.0.3
 Responsive Images v2.0.3
 SEO v2.3.5
 Shortcode Core  v5.0.3
 SimpleSearch  v2.2.1
 YouTube  v3.1.0

**Comment by Open-wan** [comment]
no improvement after forced reinstall of : 
bin/gpm install admin
bin/gpm install flex-objects

**Comment by rhukster** [comment]
Were things working fine in 1.7.1? There were only minor updates in 1.7.2.

**Comment by Open-wan** [comment]
Problem comes after 1.7.1 upgrade.

Just tryed bin/gpm selfupgrade -f, but no improvement anymore :

********
You are already running the latest version of Grav v1.7.2
which was released on Thu Jan 21 18:59:36 2021

However post-install scripts have not been run.

 Would you like to run the scripts? [Y|n]  (yes/no) [yes]:
 > y
  |- Running post-install scripts...    '- Success!
*****

still have ERROR: flex-objects.html.twig template not found for page: Flex Objects
on admin/pages and admin/accounts/users

**Comment by rhukster** [comment]
That `flex-objects.html.twig` is located in flex-objects plugin, so it's like its not installed or not able to run.  Try deleting the `user/plugins/flex-objects` folder and reinstalling it.

**Comment by Open-wan** [comment]
rm -r user/plugins/flex-objects
bin/gpm install flex-objects

still have this error...
really strange.

**Comment by Open-wan** [comment]
Where I can find post installation script of 1.7.1 ?

**Comment by Open-wan** [comment]
think post installation script was ote done after installation of 1.7.1

bin/gpm selfupgrade -f -o
GPM Releases Configuration: Stable

Grav v1.7.1 is now available [release date: Wed Jan 20 19:03:58 2021].
You are currently using v1.7.2.

**Comment by rhukster** [comment]
we have found an issue related to post-install processing, this may have caused the problem you are seeing too. I've pulled the 1.7.2 packages while we investigate.  That's why you are seeing 1.7.1

**Comment by rhukster** [comment]
1.7.3 is out, and it is loading classes differently. This 'might' resolve your issue, or you might have something else going on.

**Comment by mahagr** [comment]
FYI: post-install script has nothing to do with Flex issue. It runs only after the update is installed and changes only a few configuration options to keep it compatible with the older version. I don't think that the issue is related to the errors which were present during the update.

What happens if you make a new installation to the server, maybe into a `test/` folder? Do you get the same issue?

**Comment by Open-wan** [comment]
Similarissue with 1.7.3 upgrade.
Fresh install is OK.

**Comment by mahagr** [comment]
If the fresh install is OK, something in your site is causing the error. Try disabling 3rd party plugins and you may find the cause.

**Comment by GeoFux** [comment]
I had the same problem after 1.71 and 1.7.3 upgrade..
It solves while deactivating the Content-edit plugin:

https://github.com/finanalyst/grav-plugin-content-edit

**Comment by rhukster** [comment]
Good to know!

**Comment by rhukster** [comment]
Added to the docs: https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#error-flex-objects-html-twig-template-not-found-for-page

**Comment by drukq5** [comment]
I had the exact same problem, and I did not have Content Edit installed. It did, however, inspire me to troubleshoot all of my plugins, and I can confirm that the having the following plug-in enables causes the same problem.

https://github.com/foxfabi/grav-plugin-leaflet-address
