### ISSUE TITLE
Cannot change image format in Grav 1.7

### ISSUE THREAD

**Issue by fdruide** [getgrav/grav#3173]
I found a regression in Grav 1.7.3 from Grav 1.6.31 while doing HTML diff of our website. We have a template where we use the image _format_ method to replace several PNG to JPG. However, it remains in PNG in Grav 1.7.3. I hope this is not a repost.

Here is the minimal steps to reproduce the problem : 
1. Get a clean install of Grav core 1.7.3
2. Modify user/themes/quark/templates/default.html.twig with the following content:
```
{% extends 'partials/base.html.twig' %}

{% block content %}
    {% set img = page.media.images|first %}
    <img src="{{ img.format('jpg').url() }}" />
    {{ page.content|raw }}
{% endblock %}
```

3. Add the included PNG image inside the following folder : user/pages/01.home/
![my-image](https://user-images.githubusercontent.com/32466736/105549235-b4b96780-5cce-11eb-8967-f765383b2e4b.png)

4. Load the main page.

Actual result in Grav 1.7.3, the image is still a PNG (the transparency is still there):
<img width="600" alt="format-grav1-7-3" src="https://user-images.githubusercontent.com/32466736/105549396-e3cfd900-5cce-11eb-9f4a-a62a166fc551.png">

Expected result as in Grav 1.6.31, the image becomes JPG :
<img width="600" alt="format-grav1-6-31" src="https://user-images.githubusercontent.com/32466736/105549460-f6e2a900-5cce-11eb-99b0-01e97fdffd26.png">

The problem is in ImageMediaTrait::saveImage. The format is overridden with the following code :
```
            $extension = strtolower($this->get('extension'));
            $this->format($extension);
```

I think the fix would be to verify the format is actually set to guess before getting the file’s extension :
```
        if ($this->format == 'guess') {
            $extension = strtolower($this->get('extension'));
            $this->format($extension);
        }

```
In that case, if we set the format prior hand, our requested format would not be overridden.

Thank you for your time,
François

**Comment by NicoHood** [comment]
This can be closed now
