### ISSUE TITLE
Cannot save the content page in expert mode

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [getgrav/grav#3174]
Hi.
I'm trying to delete some content, in expert mode through admin panel. The content can't be deleted, it shows again after click in save button.

Is this a bug?

https://user-images.githubusercontent.com/60596353/105612191-c5470c00-5dba-11eb-91ad-af8bac837d6d.mp4

**Comment by mahagr** [comment]
I'm able to reproduce the issue.

**Comment by mahagr** [comment]
There's 3rd commit in: https://github.com/trilbymedia/grav-plugin-flex-objects/commit/064facb2360d59389e61cbead8d2a337ecb08664

**Comment by pmoreno-rodriguez** [comment]
Hi, 
I've trying the changes with new file in classes/Admin/AdminController.php, and the system show the following error:

**Call to undefined method Grav\Framework\Flex\FlexForm::setSubmitMethod()**

I attach a screenshot of error:
![Selection_039](https://user-images.githubusercontent.com/60596353/106378140-76910780-63a2-11eb-8a90-5f94b9912156.png)

Is there something I'm doing wrong?

**Comment by mahagr** [comment]
It also requires a change in Grav, see the commits from above (3 altogether).

**Comment by pmoreno-rodriguez** [comment]
Hi @mahagr ,

I have 3 files you have commited in their folders. The problem persists.

I've attached a short video to show the error.

https://user-images.githubusercontent.com/60596353/106491618-5a32bf00-64b7-11eb-91c9-8d6f3f89c7fe.mp4

**Comment by mahagr** [comment]
Could you check if the release fixes your issue, thanks!

**Comment by pmoreno-rodriguez** [comment]
Hi @mahagr 

I just installed another local site with Grav 1.7.5 and all work fines, at the moment. Could be something from the cache.

Thanks for your help and your good job.

**Comment by mahagr** [comment]
@pmoreno-rodriguez It has nothing to do with cache (well, if you exclude opcache). Basically it looks like Grav is an older version or at least the above class is old (cannot be updated/written?).
