### ISSUE TITLE
Update 1.7.3 - Memcached::setMulti() error in admin panel and admin addon user manager 

### ISSUE THREAD

**Issue by ChristianaHoJo** [getgrav/grav#3179]
Hi!

After Update of Grav and the admin panel  with admin addon user manager to latest versions the following error occures: 

`Memcached::setMulti(): failed to set key flex-objects-user-accountsg-ae158301[user-name][1]`

I would be very thankful for getting help!

**Comment by rhukster** [comment]
Admin addon user manger will very likely conflict with latest Admin 1.10 because it has it down flex-based user manager.  I suggest removing the “addon user manager” plugin and see if you issue persists.

**Comment by ChristianaHoJo** [comment]
Thank your for your quick response.
I deinstalled addon user manager and then I did the admin update.
The issue still exists. Do I have to delete all existing users?

**Comment by rhukster** [comment]
Ok so now a different error than the original. To be honest I’m not sure what the user manager addon did.  Simplest solution to try is move all the user accounts out of accounts folder to somewhere you can reference them, then with no accounts you should be promoted to create admin account. Make sure you can now get into users menu item.. If that works.  Recreate the accounts in the new accounts ui referencing the old accounts  files for names emails etc.

**Comment by ChristianaHoJo** [comment]
Thank your for your help! 
I tried your solution...it must be something in our site causing this error. I'll disabling 3rd party plugins and try to find our problem.

**Comment by ChristianaHoJo** [comment]
We have an own written plugin that modifies pages template. we had to change onAdminTwigTemplatePaths function to solve this issue
`   public function onAdminTwigTemplatePaths(Event $event)
    {
       // **before update to admin 1.10.**
       // $event['paths'] = [__DIR__ . '/admin/themes/grav/templates'];

       // exclude other admin plugins or menu items
       if($this->grav['uri']->basename() === 'pages') {
            $event['paths'] = [__DIR__ . '/admin/themes/grav/templates'];
       }
    }`
