### ISSUE TITLE
a small cosmetic suggestion

### ISSUE THREAD

**Issue by dawidxt** [getgrav/grav#318]
Hi, thanks for an update !!!
I have a small cosmetic suggestion about this weird focus: on button clicked (blue border). In my opinion it's just ugly

![screen](https://cloud.githubusercontent.com/assets/13783466/9830496/b41bb97e-5930-11e5-84d8-59247c9c90b4.png)

This can be easy fixed by setting in CSS: outline: none; 
Of course this is only my opinion.

**Comment by rhukster** [comment]
It's one of those things, that although it may not look as nice as it could, removing it has huge usability implications:

http://www.outlinenone.com/

**Comment by MrSchism** [comment]
While this is closed, it's worth mentioning a better option might be some sort of system to come up with a color complementary to the button color (defaulting to blue or black).

Alternatively, have an easier option to change the button click color.  This may be easier than the previous method.

**Comment by nunull** [comment]
Isn't it an option to explicitly declare a styling? Something like `button:focus { outline: solid 2px color; }`. That way, tab navigation and the like work just fine.
