### ISSUE TITLE
[SOLVED] HTML shown and not rendered since last update (1.7.3)

### ISSUE THREAD

**Issue by vitaminace33** [getgrav/grav#3181]
Hi! Since the last update from 1.6.x, I get an HTTP 500 error on [my site](https://cmcampos.xyz/resume), which is based on the [resume theme](https://github.com/getgrav/grav-theme-resume). Any suggestion on how to fix this?

UPDATE1: HTTP 500 was due to not having a plugin folder in the subsite tree, after which the subsite shows html code that is not properly parsed by Twig. Following [the upgrade guide](https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide) doesn't solve the problem.
UPDATE2: I have updated the issue's title to reflect better the problem.
UPDATE3 (solved): There's a typo in the docs and it should say `autoescape: false`.

**Comment by rhukster** [comment]
an HTTP 500 error is from the server.  You would need to look at your webserver logs to see what the actual error is. We could go from there.

**Comment by vitaminace33** [comment]
```
[28-Jan-2021 19:41:55 Europe/London] PHP Fatal error: Uncaught BadMethodCallException: Failed to open dir: plugins:// does not exist. in /home/gravuser/public_html/vendor/rockettheme/toolbox/ResourceLocator/src/UniformResourceIterator.php:102
Stack trace:
#0 /home/gravuser/public_html/vendor/rockettheme/toolbox/ResourceLocator/src/UniformResourceIterator.php(47): RocketTheme\Toolbox\ResourceLocator\UniformResourceIterator->rewind()
#1 /home/gravuser/public_html/vendor/rockettheme/toolbox/ResourceLocator/src/UniformResourceLocator.php(45): RocketTheme\Toolbox\ResourceLocator\UniformResourceIterator->__construct('plugins://', NULL, Object(RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator))
#2 /home/gravuser/public_html/system/src/Grav/Common/Plugins.php(46): RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator->getIterator('plugins://')
#3 /home/gravuser/public_html/system/src/Grav/Common/Grav.php(677): Grav\Common\Plugins->__construct(Object(Grav\Common\Grav))
#4 /home/gravuser/public_html/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Co in /home/gravuser/public_html/vendor/rockettheme/toolbox/ResourceLocator/src/UniformResourceIterator.php on line 102
```

**Comment by vitaminace33** [comment]
I have created a `plugins` folder under the subsite's tree and no HTTP 500 error is thrown but some html code is not rendered and exposed explicitly.

**Comment by rhukster** [comment]
I think you must have somehow lost your plugins folder.  it's not something that Grav does during the 'upgrade' process, so you must have perhaps done it accidentally yourself?

I don't know what plugins you had installed, but if HTML is displayed and not rendered, it's most likely because you didn't upgrade via GPM, so Grav wasn't able to automatically set the compatibility flag for Twig, as not Twig auto-escapes all HTML unless you specifically use the `|raw` filter.  You can easily fix it with a simple config option though:

https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#twig

**Comment by vitaminace33** [comment]
1. As it's a rather basic subsite, it has no plugins (it doesn't need any). I have symlinked basic ones for administration and testing. But this is not the problem, now.
2. Grav was updated from the admin plugin.
3. `system.yaml` had alredy the `twig: autoescape: true` lines.
4. I have added `strict_mode: twig_compat: true` as in the upgrade guide (directly and through the admin plugin). **The site still shows raw html code.**
Any suggestion? Perhaps that `|raw` filter you talk about? I am puzzled. It is a really simple site.

**Comment by rhukster** [comment]
Can you provide a url or something.  Perhaps a screenshot ?

**Comment by vitaminace33** [comment]
[Here.](https://cmcampos.xyz/resume)

**Comment by rhukster** [comment]
Looks fine to me (on mobile). Have you tried hard refreshing your browser or using another browser? Sounds like browser caching at this point.

**Comment by vitaminace33** [comment]
Are you sure? On Firefox Focus (mobile) it shows html code, as well as Firefox (desktop), Chrome (desktop), all with private navigation (no caching).

**Comment by rhukster** [comment]
Oh just the contact box.  Was expecting the whole page. 

did you set both options? https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#twig

**Comment by vitaminace33** [comment]
As stated earlier, yes.

**Comment by vitaminace33** [comment]
Is the `|raw` filter important? My theme is a fork of [resume](https://github.com/getgrav/grav-theme-resume) 1.3.0.

**Comment by rhukster** [comment]
The settings should make it compatible without raw.  But sure add the raw filter to the twig that outputs the contact stuff.

**Comment by vitaminace33** [comment]
That's the thing... I have more code exposed and I intend to extend the theme. I need to know who is to blame, Grav, the theme (resume) or the configuration (I obviously discard myself :D). Any idea???

**Comment by vitaminace33** [comment]
I have created [a page](http://cmcampos.xyz/resume/test) whose only content is a one line text without any html tags. Grav ignores 
```
twig:
  autoescape: true
strict_mode:
  twig_compat: true
```
and shows the html paragraph tag `<p>` added by the system.

**Comment by rhukster** [comment]
How about you send me a zip of the user folder and I'll take a look at wahts' going on, it's just to hard to guess what might be issue with trial and error.

**Comment by vitaminace33** [comment]
Pardon my ignorance. How should I send it? Or where?

**Comment by rhukster** [comment]
Put it on a cloud share somewhere of you choice and send me a link to andy at trilbymedia dot com.

**Comment by rhukster** [comment]
Ok, sorry about that.. is a typo in the docs!! Should be `autoescape: false`. 

After that you will need to clear the cache manually as twig won't know that the files need to be refreshed.  Then it works.

**Comment by vitaminace33** [comment]
LoL In fact, I was wondering because to me it was counter intuitive.

Thank you very much for the help.

**Comment by rhukster** [comment]
Glad it's sorted! closing...

**Comment by drzraf** [comment]
When `user://` points to a directory missing a `plugins/` directory, we indeed hits this strange error (`Failed to open dir: plugins:// does not exist.`) with this stack:

```
Xdebug: user triggered in /grav/vendor/rockettheme/toolbox/ResourceLocator/src/UniformResourceIterator.php on line 102
Call Stack
#	Time	Memory	Function	Location
1	0.0002	428664	{main}( )	.../index.php:0
2	0.0053	486448	Grav\Common\Grav->process( )	.../index.php:58
3	0.0086	661160	Grav\Framework\RequestHandler\RequestHandler->handle( )	.../Grav.php:304
4	0.0103	665816	Grav\Framework\RequestHandler\RequestHandler->handle( )	.../RequestHandlerTrait.php:62
5	0.0103	665912	Grav\Common\Processors\InitializeProcessor->process( )	.../RequestHandlerTrait.php:50
6	0.0103	666664	Grav\Common\Processors\InitializeProcessor->initializeConfig( )	.../InitializeProcessor.php:73
7	0.0104	667040	Grav\Common\Grav->offsetGet( )	.../InitializeProcessor.php:181
8	0.0104	667040	Grav\Common\Service\ConfigServiceProvider->Grav\Common\Service\{closure:/grav/system/src/Grav/Common/Service/ConfigServiceProvider.php:49-58}( )	.../Container.php:118
9	0.0104	667040	Grav\Common\Service\ConfigServiceProvider::load( )	.../ConfigServiceProvider.php:50
10	0.0111	676672	Grav\Common\Config\CompiledConfig->load( )	.../ConfigServiceProvider.php:135
11	0.0111	676672	Grav\Common\Config\CompiledConfig->load( )	.../CompiledConfig.php:61
12	0.0150	676928	Grav\Common\Config\CompiledConfig->loadFiles( )	.../CompiledBase.php:112
13	0.0157	683032	Grav\Common\Config\CompiledConfig->loadFile( )	.../CompiledBase.php:180
14	0.0157	683032	Grav\Common\Config\Config->join( )	.../CompiledConfig.php:111
15	0.0157	683032	Grav\Common\Config\Config->blueprints( )	.../Data.php:120
16	0.0157	683032	Grav\Common\Service\ConfigServiceProvider::Grav\Common\Service\{closure:/grav/system/src/Grav/Common/Service/ConfigServiceProvider.php:131-133}( )	.../Data.php:272
17	0.0157	683032	Grav\Common\Grav->offsetGet( )	.../ConfigServiceProvider.php:132
18	0.0157	683032	Grav\Common\Service\ConfigServiceProvider->Grav\Common\Service\{closure:/grav/system/src/Grav/Common/Service/ConfigServiceProvider.php:45-47}( )	.../Container.php:118
19	0.0157	683032	Grav\Common\Service\ConfigServiceProvider::blueprints( )	.../ConfigServiceProvider.php:46
20	0.0161	755376	Grav\Common\Config\CompiledBlueprints->load( )	.../ConfigServiceProvider.php:105
21	0.0161	755472	Grav\Common\Config\CompiledBlueprints->loadCompiledFile( )	.../CompiledBase.php:112
22	0.0230	755568	Grav\Common\Config\CompiledBlueprints->checksum( )	.../CompiledBase.php:211
23	0.0231	759664	Grav\Common\Config\CompiledBlueprints->getTypes( )	.../CompiledBlueprints.php:45
24	0.0231	759664	Grav\Common\Grav->offsetGet( )	.../CompiledBlueprints.php:68
25	0.0231	759664	Grav\Common\Grav->Grav\Common\{closure:/grav/system/src/Grav/Common/Grav.php:708-710}( )	.../Container.php:118
26	0.0234	766264	Grav\Common\Plugins->__construct( )	.../Grav.php:709
27	0.0234	766264	RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator->getIterator( )	.../Plugins.php:47
28	0.0234	783728	RocketTheme\Toolbox\ResourceLocator\UniformResourceIterator->__construct( )	.../UniformResourceLocator.php:45
29	0.0234	783728	RocketTheme\Toolbox\ResourceLocator\UniformResourceIterator->rewind( )	.../UniformResourceIterator.php:47
30	0.0234	783816	xdebug_print_function_stack ( )	.../UniformResourceIterator.php:102
```

A more explicit error about uninitialized or badly initialized streams would really help.

**Comment by mahagr** [comment]
Please open a new issue about it.
