### ISSUE TITLE
Feature: Add links to latest/next zip downloads of Grav Core and Grav+Admin 

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#3185]
To automate the download of the latest Grav core or Grav +Admin, it would be nice to have download links like:
- https://getgrav.org/download/core/grav/latest
- https://getgrav.org/download/core/grav-admin/latest

and maybe:
- https://getgrav.org/download/core/grav/next
- https://getgrav.org/download/core/grav-admin/next

Also, there seems to be no links to older versions. Would it be an idea to create a download page with a list of older versions, latest and next.

**Comment by rhukster** [comment]
You know those latest links already work right?

**Comment by pamtbaau** [comment]
You know I wouldn't create the issue if I knew already right?

Just never tried... and I would have known if there was page with a listing ;-)

**Comment by mahagr** [comment]
Older versions also work by just adding the version number.

**Comment by pamtbaau** [comment]
Yes, I know, but its kind of  hidden if you don't look at the download Url of the version listed on the download page. 

Therefor, like offered for other apps (e.g. a page by [vscode](https://code.visualstudio.com/updates/v1_52), github releases by [bootstrap](https://github.com/twbs/bootstrap/releases)), or just the ability to browse the 'https://getgrav.org/download/core' folder, would be handy.

It's not a big deal, the url to 'latest' is already fine (to me). Maybe a mentioning of the url structure on the downloads page would suffice.

**Comment by rhukster** [comment]
I've noted this for future improvements. thanks
