### ISSUE TITLE
Svg is not added to page media images namespace

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3196]
I am trying to access a footer image like that:
```
{% set footer_image = footer_page.media.images|first %}
```

SVG images are not added to "images", png and other images are.

**Comment by rhukster** [comment]
SVG is in files

**Comment by NicoHood** [comment]
That seems wrong to me.

**Comment by rhukster** [comment]
Images are tied to Gregwar Image library, so only formats that are supported by that library are in 'images'.  SVGs don't have to be images, they are a vector format.

**Comment by NicoHood** [comment]
It seems that even when I try to apply any image operation to the svg it just gets ignored (which is okay in my case). Isnt there a way to properly integrate svg into the image directory or at least create a specific `svg` entry? Otherwise you need to filter the files by file endings etc... I found no easy solution to built a template that both supports svg and png as variable input
