### ISSUE TITLE
Page keeps loading with custom video gallery yaml template with more than 9 videos in directory

### ISSUE THREAD

**Issue by eggithub** [getgrav/grav#3197]
Howdy,

I don't know where to start to resolve this issue but here's the thing. I have a video gallery that works with the following yaml template:

``` yaml
{% embed 'partials/base.html.twig' with { github_link_position: false } %}

  {% block content %}

    {% if page.title != 'Recordings' %}
      Date: {{ page.title }}<br>
    {% else %}
      some text<br>
      ... some more text ...<br><br>
    {% endif %}

    {{ page.content }}

    {% for video in page.media.videos|reverse %}
{#      {{ video.resize(472,266).html }} #}
      {{ video.resize(315,177).html|raw }}
    {% endfor %}

  {% endblock %}

  {% block footer %}{% endblock %}

{% endembed %}

```

**Problem: videos only load and give a preview image when there is less than 10 videos in a directory. When there are 10 or more videos in a directory, the page does not load and no preview images are displayed**
Browser: the problem only occurs in **Firefox** (not in any chromium related browsers or IE 20H2 version even)
System: PRi4 4GB, latest Raspbian + Apache2 +php7.3
Grav version: 1.6/1.7

You guys have any idea? What info should I provide to people can even have a clue on how to solve this?

Is there a way to circumvent this by changing the yaml?

Cheers!

**Comment by rhukster** [comment]
Well due to the fact that it only occurs in Firefox, it sounds like the issue is with Firefox itself. Probably limiting the number of video previews for performance reasons.  I don't see anything in your code that would limit it.  Either that or some Firefox plugin (ad blocker) ?

**Comment by eggithub** [comment]
> Either that or some Firefox plugin (ad blocker) ?

Yep, already tried that, still the same...

Indeed Firefox was my first guess too, but could also be something like php mods or bad server config. 

I'll post on the Firefox issue list first, see what happens. 

Thanx for your time!

**Comment by eggithub** [comment]
Bug was filed at Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1690839
