### ISSUE TITLE
Pages object missing in modules

### ISSUE THREAD

**Issue by Karmalakas** [getgrav/grav#3199]
In modular twig templates `pages` object is `null`. I found a workaround though - using `grav['pages']` seems to work fine.

I got to the part, where `Pages::index` in modules is empty, therefore `Pages::root()` returns `null`.
The solution could maybe be in _/system/src/Grav/Common/Twig/Twig.php::387_ adding a check:
```php
$twig_vars['pages'] = $pages->root() ?: $pages;
```

But I have no idea how good or bad that would be, so for now I'm sticking with `grav['pages']` in my modular templates

**Comment by Karmalakas** [comment]
OK, I got back to this after some time to change URLs in my templates, and now it seems even `grav === null`, so not sure how it was there before, but it looks like I can't use the workaround I thought I could :(

**Comment by Karmalakas** [comment]
@rhukster , I understand this workaround to use `grav['pages']` in module templates is the right one? Maybe it should be documented then? I could add some notes to the docs if this is the case. Because I spent a lot of time figuring out how to get some other page route when I had only a folder based URL. Only searching through code I stumbled on this approach.

**Comment by mahagr** [comment]
To be honest, I would always use `grav` container to fetch what I need as there's no need to pollute context with a million variables that need to be copied and merged on every template context change (that happens also inside a single twig file).
