### ISSUE TITLE
[add-resource] Update Editorial Theme

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [getgrav/grav#3202]
I would like to add the new version of Editorial theme to the Grav Repository. It's prepared for Grav 1.7, updated to latest css/js files from original HTML5Up theme.

Here are the project details: **https://github.com/pmoreno-rodriguez/grav-theme-editorial**

**Comment by rhukster** [comment]
If this is an existing theme, and you follow the standard update/release approach on github, it will just show up in GPM with next GPM update

**Comment by pmoreno-rodriguez** [comment]
> If this is an existing theme, and you follow the standard update/release approach on github, it will just show up in GPM with next GPM update

Hi. I don't know how to do this, because I've uploaded a fork of original theme, and I can't merge with the original theme.

Can you give me any advice to upload my Editorial Theme fork?

**Comment by rhukster** [comment]
You need to rename the theme to something unique.
