### ISSUE TITLE
Add brotli compression support

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3203]
As [mentioned in the forum](https://discourse.getgrav.org/t/brotli/2304) brotli support will be added when the "market saturation is worth to be supporting".

Brotli now has a coverage of 94%, so its worth to have a look at it again. It will speed up websites even more:
https://caniuse.com/brotli

**Comment by mahagr** [comment]
Be free to add the support. Likely you need to check if PHP has the extension installed as well as if the browser supports the encoding. For example, Firefox only supports it when using HTTPS protocol.

**Comment by Rotzbua** [comment]
Brotli is not available with php without special custom extensions. In my opinion it is not usable with php. Also it is more a distribution (webserver) topic than generator (grav) topic.

Better enable brotli on the webserver. On nginx just some steps:
https://docs.nginx.com/nginx/admin-guide/dynamic-modules/brotli/

I think most ppl use plesk and plesk enabled it in their latest update by default:
https://support.plesk.com/hc/en-us/articles/360018910173-Does-Plesk-support-BROTLI-compression-for-Apache-or-nginx-web-server-

> For example, Firefox only supports it when using HTTPS protocol.

Chrome too.

**Comment by w00fz** [comment]
I agree with @Rotzbua here, what would be required on the Grav side to fulfill your support suggestion @NicoHood?

We have been using brotli successfully on many grav projects by just ensuring the web server/nginx was properly setup, with brotli being such a low level caching mechanism, I fail to see what else Grav could do for it, is there anything we are missing? What type of support are you thinking about?

**Comment by mahagr** [comment]
I tend to agree that this is a web server configuration issue, not something that should be supported by Grav itself. This is kind of true with the deflate, too, it really should be handled by the server, but we support it because it may still be useful in some shared hosts. But even it causes issues because of how easy it is to misconfigure it...

**Comment by Rotzbua** [comment]
@NicoHood My provider uses the latest plesk and brotli works without any change. It seems brotli is used for static css and js. Not for (dynamic) html but I guess that is an performance decision.
https://support.plesk.com/hc/en-us/articles/360018910173-Does-Plesk-support-BROTLI-compression-for-Apache-or-Nginx-web-server-

**Comment by rhukster** [comment]
If you use cloudflare you can just enable brotli and it will compress all, including content.

**Comment by NicoHood** [comment]
My hoster (netcup) just told me, that is is activated by default.

**Comment by Rotzbua** [comment]
@NicoHood Brotli is used on both pages for css and js. Tested with FF88.

**Comment by NicoHood** [comment]
And why not html?
