### ISSUE TITLE
Blockquote not rendering when using markdown within a html code

### ISSUE THREAD

**Issue by lguariento** [getgrav/grav#3204]
With markdown extra enabled, and `markdown="1"` in the wrapping html element, the blockquote markdown instruction is passed as-is instead of being transformed into a `<blockquote>` element:

```
<div class="accordion-body" markdown="1">
> This should be a blockquote
</div>
```

**Comment by rhukster** [comment]
Do you have **markdown-extra** enabled?  It's required for `markdown="1"` functionality.

Alternatively, due to long-standing issues with markdown-extra, I suggest installing `shorcode-core` and using shortcode syntax for div:

```
[div class="accordion-body"]
> This should be a blockquote
[/div]
````

**Comment by lguariento** [comment]
Yes, as per my question: "With markdown extra enabled..." :) . The issue is only with the blockquote instruction (likely for the > special character). I'll give shortcodes a go then, thanks.

**Comment by w00fz** [comment]
This is unfortunately a long standing issue with Parsedown Extra (https://github.com/erusev/parsedown-extra/issues/94).

I have narrowed it down to https://github.com/erusev/parsedown-extra/blob/master/ParsedownExtra.php#L641 which in a variation of your example converts the text to an escaped `&gt; This should be a blockquote **bold**` which of course can no longer be converted to blockquote.

I think your best bet would be to shortcode like Andy has suggested.

Alternatively, and very hackish but might serve the job 😄:

```html
<div class="accordion-body" markdown="1">
```blockquote
This should be a blockquote **test**
</div>
```
