### ISSUE TITLE
Inserting link into twig template headline breaks whole page

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3205]
1. Download Grav 1.7.5 from the website
2. Edit `default.html.twig` template as shown below
3. Run the webserver

```twig
{% extends 'partials/base.html.twig' %}

{% block content %}
    <h3><a href="/">test<a/></h3>
    {{ page.content|raw }}
{% endblock %}
```

You can see, that Grav randomly inserts additional link tags:
![grafik](https://user-images.githubusercontent.com/6888294/107068145-85335080-67e0-11eb-9815-9ac2e77d4dbc.png)

**Comment by w00fz** [comment]
That's because the browser is trying to heal your tag by properly end the `<a>` tag, since your closing one is invalid. 

Check your syntax, you have `<a/>` instead of `</a>`. :)

**Comment by w00fz** [comment]
Also I shall suggest using an IDE or advanced Code Editor such as PhpStorm / VSCode, they would highlight broken syntaxes like the one you had and you would spot them right away. Very efficient for your workflow!

**Comment by NicoHood** [comment]
Oh how could I miss this obvious thing... what a shame!

I am using atom, but I thought about switching to vscode. Do you use any special plugin for this?

**Comment by w00fz** [comment]
I recommend **Markdown All in One**
