### ISSUE TITLE
Save Failed: Undefined index: grav-base

### ISSUE THREAD

**Issue by Umbyology** [getgrav/grav#3210]
So, this showed up this morning when I create, make changes, or save an External Page Type. The save does work though.

![Screen Shot 2021-02-07 at 10 02 31 AM](https://user-images.githubusercontent.com/22547499/107152183-0a774c00-692c-11eb-9b66-5ee14255c779.png)

Suggestions?

**Comment by mahagr** [comment]
Unfortunately I'm not able to reproduce the error. I created a new external page and saved it, it was successfully saved. 

Maybe you have a plugin that causes this issue. If you enable debugger (and install clockwork browser extension), you should be able to see the exception and where it happens.

**Comment by Umbyology** [comment]
ok, It will be a week before I can get back to this, but I'll take a look. THX!

Brian U.
