### ISSUE TITLE
Have tried to move a page, it didn't work, and the page is gone now.

### ISSUE THREAD

**Issue by adrianmrozo** [getgrav/grav#3227]
Have tried to move a page, it didn't work, and the page is gone now.
Error message:
FilesystemIterator::__construct(… some folder structure …): filled to open dir: Not a directory
I still found a file with the name of the page in my hosting service, but the file is empty (0 bytes).
Used grav version: v1.7.3.

**Comment by mahagr** [comment]
Unfortunately, I need more information in order to figure out what went wrong.

All information is welcome, here are some questions:
- What was the language for your page?
- Do you have multiple languages? Did this page have multiple translations?
- What was the slug/path for the page? Did it contain non-ascii characters?
- In the target folder, did you have a page with the same slug?
- Are you able to reproduce the issue?

**Comment by adrianmrozo** [comment]
Sure, no problem, I was worried that it might be too little information, to work on.
What was the language for your page? English.
Do you have multiple languages? No.
Did this page have multiple translations? No.
What was the slug/path for the page? The complete error message is the following: FilesystemIterator::__construct(/home/d4chdjbkuiqm/public_html/user/pages/11.test): failed to open dir: Not a directory
Did it contain non-ascii characters? No.
In the target folder, did you have a page with the same slug? Not sure what this means.
Are you able to reproduce the issue? Yes. Everytime I try to move a page.
Maybe it really has something with the path, as I do not know where the part "d4chdjbkuiqm" is coming from.

**Comment by mahagr** [comment]
I'm still not able to reproduce the issue.

The part "d4chdjbkuiqm" is your user in the server.

Can you check what's in the folder `/home/d4chdjbkuiqm/public_html/user/pages/11.test`? As it says that it is not a directory.

Also, can you enable debugger and errors from your Grav configuration to see the full stack trace to the issue?

**Comment by mahagr** [comment]
@adrianmrozo I was finally able to reproduce this issue. The bug happens when you try to move the page to itself.

**Comment by mahagr** [comment]
Related commits to the issue:

https://github.com/getgrav/grav/commit/0491bd1a762c764e4096710fd6409475b3e141a2
https://github.com/getgrav/grav/commit/eb89c00bd5d383da1b260233216f9973124f063a
https://github.com/getgrav/grav/commit/fa819064ef2145e2c5e7d72a6ca2284809266051
