### ISSUE TITLE
[Feature request] Crop image by ratio

### ISSUE THREAD

**Issue by Karmalakas** [getgrav/grav#3228]
Would be nice to have something like `cropRatio` next to all other image manipulation methods.
Eg. if image is 1800x900 (2:1) calling `cropRatio(3, 1)` should end up in 1800x600 or `(1, 1)` - 900x900

**Comment by rhukster** [comment]
Probably something we would look to add when we move away from Gregwar Image library in Grav 2.0.

**Comment by Karmalakas** [comment]
Can I follow this somehow now that issue is closed or you have some private ToDo list? :)

**Comment by rhukster** [comment]
There is no todo/roadmap for 2.0 currently. That's something we want to work on this year.  We will probably have a public facing issue to track major features/changes though.
