### ISSUE TITLE
Pipeline : minified CSS file altered on 3-values synthax shorthand properties only

### ISSUE THREAD

**Issue by lafabriqueavisuels** [getgrav/grav#3229]
Hello !

After an update from 1.6.31 to 1.7.5, I ve noticed some of my CSS rules were altered when minified.

For instance 
`.card-small .card-body .card-img-small {
      padding: calc(var(--spacer)*1.5) calc(var(--spacer)*1.5) 0;
    }`
is becoming 
` .card-small .card-body .card-img-small {
    padding: calc(var(--spacer)*1.5) 0;
}`

After a quick look, it seems this issue is happening only with the 3-values synthax on [shorthand properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties) on my CSS. One of the double value is deleted.

On https://staging.btb-consulting.com/en, working with grav 1.7.5 there is this issue but not on https://btb-consulting.com/en working with grav 1.6.31.

Thanks for your help

**Comment by rhukster** [comment]
This is really the realm of the minify plugin we use https://github.com/matthiasmullie/minify

And we are on the latest version.  It seems that calc is a bit problematic.  There was a recent fix that resolved one issue, but may have introduced another. I suggest opening a ticket on the minify repo.  Thanks!
