### ISSUE TITLE
Slower page saves with 1.7.6 — 30 secs for date md edit via Admin

### ISSUE THREAD

**Issue by MattAppleton** [getgrav/grav#3231]
I have noticed recently that a simple page edit (changing a date) is taking around 30 seconds to save?!

[This site ](https://www.thames-sidestudios.co.uk) running 

Grav v1.7.6
Admin v1.10.5
PHP Version 7.4.15 with plenty of memory allocated (1024MB)

The site does have a fair few pages — 734 at the minute... the page I was editing as an example [here](https://www.thames-sidestudios.co.uk/news/general/laurence-owen-in-john-moores-painting-prize-2020-exhibition-12-feb-27-jun-2021) — but this applies to the whole admin it seems to be going pretty slow...

*edit* — changing plugin settings seems to save quickly, page amends are taking a long time to see... **

I was wondering if this was something to do with the admin plugin and associated cache? If I edit the page directly on the server via FTP it saves pretty much instantly...

thanks for looking

**Comment by mahagr** [comment]
You could enable debugger and install clockwork into your browser to see what's taking the time. Additionally, you could also install PHP extension https://github.com/tideways/php-xhprof-extension which will provide data from the individual method calls.

Saving shouldn't take that much time, though it does clear some cache and also recreates index file, which can be pretty large with 1000+ items.

**Comment by MattAppleton** [comment]
Hi @mahagr  I had a quick look at composer and its extension but got stuck trying to install Cooper / clockwork, the docs dont seem clear for OSX installation.

Here is a debugger screenshot when simply saving a css change on a fairly untouched local Typhoon install... is that helpful? If so I can try the same thing with the offending site. Mind you even this pretty lightweight GRAV test site with 19 pages seems to be slower on admin save than the old versions of GRAV.

**Comment by MattAppleton** [comment]
So using Chrome and Clockwork now I am getting 35312ms in the log when it saves... not sure what I am looking for though that might point out what the issue is.
![Uploading SS- 2021-02-26 at 17.14.13.png…]()

**Comment by MattAppleton** [comment]
All I am doing is adding a character to the text and hitting save!

<img width="655" alt="SS- 2021-02-26 at 17 15 47" src="https://user-images.githubusercontent.com/6295710/109332677-572cb380-7856-11eb-9993-8485ac232cec.png">

**Comment by MattAppleton** [comment]
trying to figure out the sharing...

**Comment by MattAppleton** [comment]
Just the performance log: https://clockwork.underground.works/share/nbocwail

**Comment by mahagr** [comment]
Check which plugins are using the event. You can do that by going to the events tab and finding the event from there. In the right there's a small arrow icon that will show the hooked up listeners.

**Comment by mahagr** [comment]
Hmm, also.. Do you have all the pages at the same level?

**Comment by MattAppleton** [comment]
This is an example page structure — I am trying to save (for example) news/general/item one of 335
![Uploading SS- 2021-02-26 at 18.20.42.png…]()

**Comment by MattAppleton** [comment]
Thing is, this is definitely a new issue with newer versions of Grav. Site was originally built by @rhukster  :)

**Comment by mahagr** [comment]
I just saved a page in 1800 pages in a single folder test site. Saving takes 300ms.

**Comment by MattAppleton** [comment]
The thing that is clogging up 'events' is LOADS of 'onFlexObjectBefore / After Save entries...

https://clockwork.underground.works/share/ifedhqsm

**Comment by MattAppleton** [comment]
The onFlexObject events seem to have no listeners then finally

AdminPlugin->onAdminAfterSave() GitSyncPlugin->onAdminAfterSave()

and then 

GitSyncPlugin->synchronize()

(GitSync is set to NOT sync on page save tho')

**Comment by MattAppleton** [comment]
<img width="713" alt="SS- 2021-02-26 at 18 26 37" src="https://user-images.githubusercontent.com/6295710/109340062-6ca6db00-7860-11eb-97b4-fdde4181ad62.png">

**Comment by mahagr** [comment]
Looks like I can see the clockwork in the frontend. (BTW)

Can you contact me privately and send the installation to me, so I can take a look. This is clearly something I'm not able to reproduce locally.

**Comment by mahagr** [comment]
I'm able to reproduce the issue.

**Comment by mahagr** [comment]
@MattAppleton Can you try if everything looks good with above fix? Please test saving pages in the news as well as adding new pages to there.

**Comment by MattAppleton** [comment]
Will do. Swapping out this file 

> system/src/Grav/Common/Flex/Types/Pages/PageObject.php

 right?

**Comment by MattAppleton** [comment]
So far that seems much quicker, now 6-7 secs per save...

**Comment by mahagr** [comment]
Cool. I think you're also using gitsync, which also slows down saves. Let me know if you find any side effects from the fix.

**Comment by MattAppleton** [comment]
I'll check that on live site ASAP. Does Gitsync slow things down even if the 'Automatic Synchronization Settings' are toggled 'off'? If so, I guess its best to disable Gitsync between development stages then?


thanks

**Comment by mahagr** [comment]
It only slows the save when it pushes to the repository.

**Comment by w00fz** [comment]
Automatic synchronization off won’t slow things down as no push will happen on save. Of course there will be the push time when you manually sync.

**Comment by rhukster** [comment]
Released version should be improved.
