### ISSUE TITLE
Typo in src/Grav/Common/Language/Language.php — page_extesions should be page_extensions

### ISSUE THREAD

**Issue by padawan** [getgrav/grav#3233]
I think there is a typo here:

```
    public function resetFallbackPageExtensions()
    {
        $this->fallback_languages = [];
        $this->fallback_extensions = [];
        $this->page_extesions = [];
    }
```

Last line should read:

```
        $this->page_extensions = [];
```

Same problem in its declaration:

class Language
{
    /** @var Grav */
    protected $grav;
    /** @var Config */
    protected $config;
    /** @var bool */
    protected $enabled = true;
    /** @var array */
    protected $languages = [];
    /** @var array */
    protected $fallback_languages = [];
    /** @var array */
    protected $fallback_extensions = [];
    /** @var array */
    protected $page_extesions = [];
    /** @var string|false */

Last line should read:

```
    protected $page_extensions = [];
```

**Comment by mahagr** [comment]
Not really a bug, but.. Fixed.
