### ISSUE TITLE
Grav with custom_base_url stops loading CSS and JS

### ISSUE THREAD

**Issue by assimoes** [getgrav/grav#3238]
Hello everyone, 

I am experimenting with custom base urls with Grav and this is getting a bit over my head. Whenever I setup a custom base url like `/info` (using relative urls) assets are no longer loaded (404 errors) because Grav will try to load them from eg `https://mydomain/info/someasset.css`, and of course, it will error out with 404. 

Are there any settings I'm missing to make it work?

P.S.: Custom Base Url is the only setting I am changing.

**Comment by mahagr** [comment]
Custom base URL is meant for sites that are behind a proxy server. So you shouldn't use it and instead have your Grav instance under that folder in the web root.

**Comment by assimoes** [comment]
Sure, I get that. Probably I should have mentioned that I'm setting up an Application Gateway with a `/info/*` rule, which hits Grav perfectly, but with the assets not being found as grav will look for them at  `https://mydomain/info/`. This is why I have started fiddling with the `custom base url`. 

I have tried the following combinations:

- Application Gateway with `/info` rule  +  default Grav config (no custom base url) -> error 404 when loading assets
- Application Gateway with `/` rule + default Grav config (no custom base url) -> works
- Application Gateway with `/info` + Grav custom base url `/info` -> error 404 when loading assets

**Comment by mahagr** [comment]
So the custom base URL should be the address people use to access the server. So if your Grav installation can be accessed from `https://mydomain/info/`, the setting is correct. So basically the setting should point to the path where clients are connecting to (usually `/`). Basically, it changes the links in the HTML document to point into a location which the client can see.

**Comment by drzraf** [comment]
I'm sorry to say that starting with 1.7 I'm getting this problem (but this opposite way).
`https://mydomain.com/foo/  -> [reverse proxy to http://127.0.0.4:8000/] -> Grav`
With 1.6, setting `custom_base_url: /foo` was fine.
With 1.7, I'm really blocked:
- No `custom_base_url` : Assets are missing (looked for at `https://mydomain.com/` without `foo/`)
- With `custom_base_url: /foo` : Pages are not found (even /foo/admin is not found)

`custom_base_url` does affects pages retrieval (and more generally, the whole routing process), but I can't find how to make it work.
Help very welcomed!

**Comment by mahagr** [comment]
As the issue has been closed for a long time, please create a new issue from this.
