### ISSUE TITLE
Multilang support for filters like the nicetime filter?

### ISSUE THREAD

**Issue by stell** [getgrav/grav#324]
Maybe via language files?

**Comment by flaviocopes** [comment]
Added, will be available in the next grav update (or fetch the changes from GitHub). You can push a PR to include other translations, I added italian https://github.com/getgrav/grav/blob/4153dbb8e5917464755781301c7cde42b618340e/system/languages/it.yaml

**Comment by stell** [comment]
done PR

**Comment by flaviocopes** [comment]
thanks :)
