### ISSUE TITLE
[remove-resource] Delete Open Presentation Hub skeleton

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#3244]
With the pending release of the new Open Matter MultiCourse Hub skeleton, I'd like to have my (now superseded) Open Matter Presentation Hub skeleton removed from the getgrav.org site:

https://github.com/hibbitts-design/grav-skeleton-open-matter-presentation-hub

Thanks very much,
Paul

**Comment by rhukster** [comment]
removed.
