### ISSUE TITLE
No info about new plugin release

### ISSUE THREAD

**Issue by MajorKuprich** [getgrav/grav#3247]
There's no info about my new plugin release (https://github.com/greenrivers/grav-plugin-webp - 1.0.1 version) on https://getgrav.org/downloads/plugins.

![github](https://i.imgur.com/L7oUJIb.png)
![grav](https://i.imgur.com/zuXb5PU.png)

Similarly, there's no info in the admin panel regarding the possibility of updating the extension.

![admin](https://i.imgur.com/EIy0hQP.png)

**Comment by Rotzbua** [comment]
you bugged here:
https://github.com/greenrivers/grav-plugin-webp/blob/1.0.1/blueprints.yaml#L4

**Comment by rhukster** [comment]
You have not released properly.  You did the GitHub side but your blueprint still shows version 1.0.0

https://github.com/greenrivers/grav-plugin-webp/blob/master/blueprints.yaml

**Comment by MajorKuprich** [comment]
Thank You @Rotzbua & @rhukster for Your notes - it was helpful :-)

Last but not least, there is still no possibility to update plugin in admin panel (no info about new version):
![](https://i.imgur.com/avHzRrZ.png)
![](https://i.imgur.com/LI9KQFM.png)

**Comment by rhukster** [comment]
That info is cached for a day in grav. You can force a check by clicking “check for updates”. If it shows up in the site then it shows up in gpm for grav.  They both use the same system.

**Comment by MajorKuprich** [comment]
Thank You for Your explanation @rhukster 
All works fine now ;)
![](https://i.imgur.com/HN7cWdW.png)
