### ISSUE TITLE
New custom pagination query parameter, how to change?

### ISSUE THREAD

**Issue by 01Kuzma** [getgrav/grav#3252]
[Improved `Pagination` class to allow custom pagination query parameter ](https://github.com/getgrav/grav/commit/340f478bfa67662394b6d539303d921e1d7b1592)
has been added, but where it could be changed? In pagination plugin? But it's not updated

**Comment by mahagr** [comment]
The class is being used by a couple of plugins, namely Flex Objects, and the upcoming JSON:API plugin (which needed this feature). Currently, pagination plugin doesn't use this class.
