### ISSUE TITLE
blueprint in theme's blueprints/flex-objects folder not loaded

### ISSUE THREAD

**Issue by phmg701** [getgrav/grav#3255]
Hello,

here's the case:
* blueprint my_objects.yaml placed in `user/blueprints/flex-objects` is correctly loaded.
* blueprint my_objects.yaml placed in `themes/my_theme/blueprints/flex-objects` is not loaded.

Maybe it's not a bug _per se_, but if I correctly understand the path to 2.0, letting flex-objects blueprints to be loaded alongside other theme blueprints would be very useful.

Edit: Grav + Plugins are up-to-date as of today.

Thank you!

**Comment by mahagr** [comment]
Themes do not have the same folder structure for blueprints (for legacy reasons themes contain only page blueprints), which likely is the reason why it doesn't work.

**Comment by phmg701** [comment]
Thank you for the prompt reply! I suspected this couldn't be actually a bug :smile:
It would be great to have such feature in a near-future release, paving the way to 2.0 theme blueprint management.
It would also be great to have multilanguage support for Flex Objects, but that's another story :eyes:
Thank you!

**Comment by mahagr** [comment]
Should be now implemented and will be released soon.

In order to enable the support, you need to set minimum requirement in the blueprints:
```yaml
dependencies:
  - { name: grav, version: '>=1.7.8' }
```

And move all the files from `user/theme/blueprints/` folder into `user/theme/blueprints/pages/`.

**Comment by rhukster** [comment]
released

**Comment by phmg701** [comment]
Hello, thank you very much @mahagr, just updated everything to yesterday's release but I am sorry to report that blueprint `photos.yaml` doesn't load from location `user\themes\{THEME}\blueprints\pages\`.
```
title: Photos
description: Simple Photo directory with Categories and Tags.
type: flex-objects
dependencies:
  - { name: grav, version: '>=1.7.8' }
```
the same loads perfectly from `user\blueprints\flex-objects\`

Shall I do some other tests? Change something else? Delete some config files?
I am fascinated by Grav's approach to content management, and willing to understand it, but it's a steep learning curve! 

Thank you!

**Comment by mahagr** [comment]
Umm, that is not a page blueprint. I tried to say that you need to move **every existing blueprint file** in the theme from `blueprints/` to `blueprints/pages/`, otherwise it is using a wrong directory structure and it only supports page blueprints.

Also the dependencies section needs to be in the theme blueprint (`blueprints.yaml`), not in the flex object blueprint.

**Comment by phmg701** [comment]
Roger that!

I did as suggested, updated `dependencies` in theme's `blueprints.yaml` but unfortunately `flex-objects` type blueprint is not loaded.
<img width="182" alt="2021-03-18_Grav_01" src="https://user-images.githubusercontent.com/68058405/111612251-94dd8600-87dd-11eb-94d2-48ba1eb3c1c9.png">
<img width="879" alt="2021-03-18_Grav_02" src="https://user-images.githubusercontent.com/68058405/111612295-a161de80-87dd-11eb-8482-1cc88459dde3.png">


I am a beginner, so thank you for your patience.

Once I get this to work, I am willing to propose changes in Learn so others can take advantage of this.

Thank you!

**Comment by mahagr** [comment]
Now you need to move the flex blueprint out of the pages folder to where it is supposed to be :) My instruction was just for the existing stuff before adding the new blueprints :)

**Comment by phmg701** [comment]
<img width="169" alt="2021-03-18_Grav_03" src="https://user-images.githubusercontent.com/68058405/111623838-36b79f80-87eb-11eb-996e-f3057d68efdb.png">
Like this, correct? It doesn't get loaded, but I am sure I am missing something!
Thanks!!!

**Comment by mahagr** [comment]
Umm, `blueprints` should have no files, everything needs to be in specific folders under it. Check `system/blueprints` for reference.

**Comment by phmg701** [comment]
![2021-03-19_Grav_01](https://user-images.githubusercontent.com/68058405/111784844-27545700-88bc-11eb-9c35-08cb3a92af6d.PNG)

Thanks now it's even clearer! Even doing so, blueprint it's not loaded.

Thank you!

**Comment by phmg701** [comment]
I tried the following:

* Grav 1.7.9 + Admin - fresh local install (MacOS 10.15.7 - PHP 7.3.27)
* creation of the first user account
* moved Quark theme files into `pages`
* created folder `flex-objects` and copied `photos.yaml` there
* edited Quark theme `blueprints.yaml` with
> ```
> dependencies:
>   - { name: grav, version: '>=1.7.8' }
> ```

`Photos` appears in Flex Objects Plugin list, so I enabled it:
<img width="337" alt="2021-03-20_Grav_01" src="https://user-images.githubusercontent.com/68058405/111865760-347b4f80-8969-11eb-9327-6e836d303876.png">
yet it doesn't appear on the left.
[photos.yaml.txt](https://github.com/getgrav/grav/files/6175227/photos.yaml.txt)
here's the blueprint, maybe the problem is there.

Again, thank you!

**Comment by phmg701** [comment]
OK, there's definitely something going on @mahagr .
Default `contacts`, when moved to `/user/themes/quark/blueprints/flex-objects/` is listed in Flex Objects Plugin but doesn't get loaded either.
Maybe this issue still needs to be open?
Thank you!

**Comment by LiaraAlis** [comment]
From version 1.7.41 flex-object blueprints are not loaded in the frontend (admin works). See also https://github.com/trilbymedia/grav-plugin-flex-objects/issues/177. Has anyone else had such experiences?

After a long research it seems that the path to the theme blueprint directory is only added to the locator if the flex object plugin has already tried to add the directory to the flex object for the respective type. However, since it cannot find the blueprint, the listing in the frontend with custom blueprint types does not work. Asking the locator about the blueprint path after theme initialization is finished, produces a positive result - but it is to late for the flex object when using `Flex::getDirectory()`.
