### ISSUE TITLE
Page alias with redirect

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3258]
Checking the docs for [page routing](https://learn.getgrav.org/17/content/headers#routes) tells me that I can set aliases for a page or specify a redirect. But what I cannot do right now is to specify an alias that redirects to the main URL. Would that be possible?

Cause a "normal" alias, as it is right now gives bad SEO, as it is just duplicated content. Having that alias redirect function in the page header would be super handy, as you can always specify outdated/old/legacy URL in there directly.

**Comment by rhukster** [comment]
If you set `pages.redirect_default_route: true` in system.yaml it should redirect any alias to the default route.

**Comment by NicoHood** [comment]
Thanks, that works.

With Grav 1.7.8 it is also possible to set the redirect code to 301:
`redirect_default_route: 301`
