### ISSUE TITLE
PHP Zip extension is required but not installed

### ISSUE THREAD

**Issue by udaykumaruking** [getgrav/grav#3268]
I have installed Grav in my shared hosting and when I open the website it's showing this error.

![image](https://user-images.githubusercontent.com/32547287/110986049-348cb580-8393-11eb-81fe-b85bdf7fc97f.png)

**Comment by rhukster** [comment]
What is the question?

**Comment by udaykumaruking** [comment]
> What is the question?

I'm unable to install grav properly can you help me out with the problem shown in the image.

**Comment by udaykumaruking** [comment]
> What is the question?

I'm unable to install grav properly can you help me out with the problem shown in the image.

**Comment by rhukster** [comment]
Grav is telling you your server doesn't have the "ZIP" extension enabled in PHP.  You probably need to speak to your hosting company.  It's a standard extension, so they must have gone out of their way to disable it.
