### ISSUE TITLE
system.languages.session_store_active: Language never stored in, or retrieved from session

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#3269]
The following setting in `system.yaml` is supposed to store the chosen language extension in the url into the session:
```
languages:
  supported: [it, en]
  session_store_active: true
```
However, the chosen language will never be stored in, nor retrieved from, the session, because function `Language::setActiveFromUri($uri)` is called before the session has been initialized.

**InitializeProcessor.php** 
In `InitializeProcessor::process()`, the line  `$this->initializeUri($config);`, which calls `Language::setActiveFromUri($uri)` is executed before `$this->initializeSession($config);`
https://github.com/getgrav/grav/blob/a67a538dfdeda51cd4cc5e92e4340438e2d188ad/system/src/Grav/Common/Processors/InitializeProcessor.php#L104-L123

**Language.php**
Because of the above, the following if-statements, meant to store and retrieve the language value from the session, will always evaluate to `false`:
https://github.com/getgrav/grav/blob/a67a538dfdeda51cd4cc5e92e4340438e2d188ad/system/src/Grav/Common/Language/Language.php#L249-L261

**Comment by mahagr** [comment]
The language code should really be inside an event `SessionStartEvent` (class).

**Comment by mahagr** [comment]
@pamtbaau Can you test my fix? :)

**Comment by pamtbaau** [comment]
Just did and it seems to be working fine.

- Fresh install Grav 1.7.10
- system.yaml
  ```
  languages:
    supported: [de, en]
    session_store_active: true
  ```
- browse to 'localhost/**en**/typography'
- browse to 'localhost/typography'      ---redirect---> localhost/**en**/typography
- browse to 'localhost/**de**/typography'
- browse to 'localhost/typography'      ---redirect---> localhost/**de**/typography
```
