### ISSUE TITLE
Provide a canonical name for the latest version

### ISSUE THREAD

**Issue by attiks** [getgrav/grav#327]
We use the following to jump start a site and to deploy

```
wget https://github.com/getgrav/grav/releases/download/0.9.42/grav-v0.9.42.zip
unzip grav-v0.9.42.zip 
mv grav my_new_site
```

The problem is we need to update the URL each time, would be nice to be able to download from a fixed URL like ```http://getgrav.org/downloads/latest.zip```

**Comment by rhukster** [comment]
Not a bad idea.. i'll look into it.

**Comment by rhukster** [comment]
Ah, sometimes I really remember what joy it is to work with Grav.  Whipped up a plugin in 10 minutes:

http://getgrav.org/downloads/grav/latest

It will redirect a couple of times as GitHub's releases are stored in a cloud environment. So use a browser or pass the appropriate options to curl:

```
$ curl -O -J -L http://site.dev/downloads/grav/latest
```
