### ISSUE TITLE
The list of pages is not displayed after updating Admin v1.10.7 (Grav v1.7.8)

### ISSUE THREAD

**Issue by petira** [getgrav/grav#3280]
Is it possible that after updating to Grav v1.7.8 - Admin v1.10.7 the list of pages (`/admin/pages`) is not displayed? That is exactly what happened to me. Everything else works, including editing pages after entering a direct path (`/admin/pages/anypage`).

Before I look for another cause of the problem, has it happened to someone else?

**Comment by mahagr** [comment]
@petira @tonhaarmans @aricooperdavis Can you please try with the above patch?

It will fix the spinning wheel, but it will not fix the cause. In the list view, try to find pages with no visible route under the title. Please let me know what you find, I'm assuming that you will see it in some of the translated pages, but I do not know why.

**Comment by tonhaarmans** [comment]
Oops, no idea how to apply the patch. Never done that before.
Perhaps I'll wait till there is a real update?

**Comment by mahagr** [comment]
The second commit is accidental, I had the wrong comment in it.

Just replace  `system/src/Grav/Common/Flex/Types/Pages/PageIndex.php` with [this](https://raw.githubusercontent.com/getgrav/grav/9082cd5b177ea4a9cbfdf7ff6966b21d9da55568/system/src/Grav/Common/Flex/Types/Pages/PageIndex.php).

**Comment by petira** [comment]
Yes, this fix resolves the issue. The list of pages is displayed. Thank you.

**Comment by izumitelj** [comment]
Patch fixed it for me too! (Firefox and Chrome on Windows). Thanks

**Comment by Philemon23** [comment]
> 
> 
> The second commit is accidental, I had the wrong comment in it.
> 
> Just replace `system/src/Grav/Common/Flex/Types/Pages/PageIndex.php` with [this](https://raw.githubusercontent.com/getgrav/grav/9082cd5b177ea4a9cbfdf7ff6966b21d9da55568/system/src/Grav/Common/Flex/Types/Pages/PageIndex.php).

This helped me too, thanks!
I guess we can expect new realese fixing this soon?

**Comment by izumitelj** [comment]
I think we might have another problem now :(. Pages do load but if I try to edit and save any paga I get "Save Failed: Cannot reorder a page which has no parent". 

How to revert problematic plugin to previewous version until this gets fixed?

**Comment by izumitelj** [comment]
I've just tried clean install of latest release from the repo ``grav-admin-v1.7.8.zip``. Admin panel doesn't display pages and if I access page directlly (or apply previous patch) – pages can't be saved ``Save Failed: Cannot reorder a page which has no parent``. Also no pages are listed under Advanced/Ordering. 

My envoronent is localhost, Windows FF and Chrome.

I believe this is urgent, bacause the main release doesn't work out of the box.

**Comment by TheDuffman85** [comment]
I ran into this problem yesterday, on my first time ever install of Grav. This issue cost me many hours and was driving me crazy. I thought it is a problem with my environment. I agree with @izumitelj that it's urgent to make an emergency release.

**Comment by izumitelj** [comment]
Can confirm this workaround – downgrading Grav to 1.7.7. restores the functionality. Admin and Flex Objects plugin can stay at their latest versions.

**Comment by mahagr** [comment]
Can someone who's brave enough to upgrade (test site) help me on figuring out what causes this bug?

Please ping me in discord, I need either a working example or someone who I can talk with to go through what happens. Thanks!

**Comment by paulhibbitts** [comment]
@[**mahagr**](https://github.com/mahagr) If it helps, I just tried to update two Grav sites to 1.7.8 and no issues - here is my PHP info:

PHP Version 7.3.24  
PHP Version 7.3.23

Please let me know if any other config info might be useful.  
Paul

**Comment by rhukster** [comment]
it must be something specific to a setting or configuration option, a plugin, or perhaps a custom blueprint.  Could be anything at this point but it's certainly impacting 'some' people and not all.  I can't reproduce it either.  We need details about a setup that is causing it, or better yet, a ZIP file of a test instance where it occurs so we can dig in and find out what causes it.

**Comment by TheDuffman85** [comment]
I did a clean install with a skeleton. After the encounter of this problem I started over and cloned from Git and installed the dependencies with compose. But the error was the same. 

My environment:
PHP 7.4.16
IIS 10
Windows Server 2019

**Comment by izumitelj** [comment]
I did clean install from [https://github.com/getgrav/grav/releases/download/1.7.8/grav-admin-v1.7.8.zip](https://github.com/getgrav/grav/releases/download/1.7.8/grav-admin-v1.7.8.zip)

After creating Admin account, pages don't load and I can't edit any through Admin panel.

My environment is:
Laragon local development environment (Windows)
PHP 7.4.15.
Nginx 1.14.0

**Comment by tonhaarmans** [comment]
Andy, I can give you a zip through WeTransfer If you give me your email

**Comment by tonhaarmans** [comment]
[website.zip](https://github.com/getgrav/grav/files/6173269/website.zip)
I just discovered I can also upload here...
It's a site I am developing for my daughter. I have it on localhost (Laragon webserver, PHP 7.4 on Windows 10)

**Comment by paulhibbitts** [comment]
Can now see it too on my Windows 10 Surface, PHP 4.7.1 and have DM's Matias.

**Comment by rhukster** [comment]
@tonhaarmans i'm assuming you didn't apply the patch yet? I tried your site locally in Chrome and it works fine. I can list he pages no problem.  The only issue I see is that during save in the blog posts, it throws an error related to date format.  I changed from your day/year to a full date and it saves fine.

![CleanShot 2021-03-19 at 12 54 17@2x](https://user-images.githubusercontent.com/1084697/111830079-1b17cc00-88b3-11eb-8899-91d184bad184.png)

**Comment by izumitelj** [comment]
Three of us that provided details experience this on Windows machines. And if I copy the same site (that doesn't work localy) to the server – than it works.

**Comment by rhukster** [comment]
@paulhibbitts can you open up the "network" panel and click "XHR" to filter the results, then inspect any failed calls and paste the output.

**Comment by tonhaarmans** [comment]
I didn't apply the patch, because I don't even know how to do that. Maybe it's the webserver? I saw another one who uses that server...BTW, it works fine online...

**Comment by izumitelj** [comment]
> @paulhibbitts can you open up the "network" panel and click "XHR" to filter the results, then inspect any failed calls and paste the output.

not @paulhibbitts ;), but here is what I see there:

```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. pages
XHRPOSThttp://gravvv.test/admin/update.json/task:getUpdates
[HTTP/1.1 200 OK 833ms]

XHRPOSThttp://gravvv.test/admin/task:getNotifications
[HTTP/1.1 200 OK 401ms]

XHRPOSThttp://gravvv.test/admin/pages
[HTTP/1.1 500 Internal Server Error 450ms]

	
POST
	http://gravvv.test/admin/pages
Status500
Internal Server Error
VersionHTTP/1.1
Transferred685 B (199 B size)
Referrer Policystrict-origin-when-cross-origin

    	
    Cache-Control
    	no-store, no-cache, must-revalidate
    Connection
    	keep-alive
    Content-Type
    	application/json
    Date
    	Fri, 19 Mar 2021 19:13:25 GMT
    Expires
    	Thu, 19 Nov 1981 08:52:00 GMT
    Pragma
    	no-cache
    Server
    	nginx/1.14.0
    Set-Cookie
    	grav-site-9b4e02d-admin=bfptag5c41pic8a6b0cgebe02i; expires=Fri, 19-Mar-2021 19:43:25 GMT; Max-Age=1800; path=/; domain=gravvv.test; HttpOnly; SameSite=Lax
    Transfer-Encoding
    	chunked
    X-Powered-By
    	PHP/7.4.15
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Content-Length
    	36
    Content-Type
    	application/x-www-form-urlencoded; charset=UTF-8
    Cookie
    	grav-site-9b4e02d-admin=bfptag5c41pic8a6b0cgebe02i; grav-admin-flexpages=eyJmaWx0ZXJzIjp7fX0%3D
    DNT
    	1
    Host
    	gravvv.test
    Origin
    	http://gravvv.test
    Referer
    	http://gravvv.test/admin/pages
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0
    X-Requested-With
    	XMLHttpRequest
```

**Comment by paulhibbitts** [comment]
Thanks @izumitelj , I see an error with Network -> XHR but unable to get to that log. I see jquery at the front of the item.

**Comment by mahagr** [comment]
Changing those 2 lines from the above commit (click on the number in the right side) will fix the issue in Windows.

**Comment by izumitelj** [comment]
I can confirm this fixes the issue in my case! Thanks 👍
