### ISSUE TITLE
Problem with thumbnail in image folder

### ISSUE THREAD

**Issue by yuperi** [getgrav/grav#3285]
If I add mp4 and thumbnail png to page folder it's worked as expected
```
![](mal1.mp4?display=thumbnail)
![](mal1.mp4.thumb.png)
```
If I add mp4 and thumbnail png to image subfolder I've got error
```
![](image://mex1/mal1.mp4?display=thumbnail)
![](image://mex1/mal1.mp4.thumb.png)
```

**Comment by yuperi** [comment]
`![](image://mex1/mal1.mp4?display=thumbnail)
![](image://mex1/mal1.mp4.thumb.png)`
![er](https://user-images.githubusercontent.com/32847814/111869024-a6489e80-8953-11eb-8416-405279b8c3e2.png)

**Comment by yuperi** [comment]
With grav 1.7.10
![](image://mex1/mal1.mp4?display=thumbnail) give default image from system/images/media
![](image://mex1/mal1.mp4.thumb.png) give error
![exc](https://user-images.githubusercontent.com/32847814/114338581-59ef1980-9b21-11eb-9d3d-7ea34f397092.png)

**Comment by mahagr** [comment]
Fix is not released yet, see the changed files from the commit above if you wish to test the fix.
