### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by noppingen** [getgrav/grav#3291]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: https://github.com/noppingen/grav-plugin-file_exists

**Comment by pamtbaau** [comment]
@noppingen, Just curious... 

Looking at the [example](https://github.com/noppingen/grav-plugin-file_exists#example) shown in the repo of the plugin, I'm afraid I fail to see the added value. The example can easily be implemented using build-in Grav functionality as shown below.

```
{% set image = page.media['_header.jpg'] %}           {# get image from current page's folder #}
{% set image = media['theme://images/_header.jpg'] %} {# get image from folder '/user/themes/<current theme>/images' #}

{# Show image if found #}
{% if image %}
    {{ image.html('Header - ' ~ page.title) | raw }}
{% endif %}
```

**Comment by noppingen** [comment]
Oh, yes - you're right. Might be the reason for me not finding an existing plugin for this application.

closed-youreblind-wontfix

Thank you!

**Comment by noppingen** [comment]
... then use the plugin for testing dynamically generated files files outside the grav folder stucture for including them :P

**Comment by pamtbaau** [comment]
Wouldn't a simple symlink to a file outside the Grav folder be more efficient then starting/invoking a plugin?

**Comment by w00fz** [comment]
I appreciate the effort put into this but I don’t think it’s a fit for the plugins repository.  

As noted above the plugin’s logic you have can already be achieved via twig and the built in media object. Moreover, if you were really looking for ways to simplify @pamtbaau ‘s code, you could delegate your theme or a custom plugin with a Twig function.

By all means if this plugin works for you, you should keep using it as a custom one, however having it published in the repository I’m afraid would just add confusion and not really add anything to what Grav already offers.

Again thank you for the time put into it, I hope to see another plugin submission from you!
