### ISSUE TITLE
Flex Objects blueprint in theme's blueprints/flex-objects not showing in Admin sidebar

### ISSUE THREAD

**Issue by phmg701** [getgrav/grav#3292]
Hello,

as of #3255, blueprints appear in Flex Object Plugin and are confirmed to work at engine level, but are not displayed in the Admin sidebar and adding/editing objects is no more possible.

Thank you!

**Comment by mahagr** [comment]
https://github.com/trilbymedia/grav-plugin-flex-objects/commit/785eb663b642261e305e73816ca0e400b9376f94
