### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by wernerjoss** [getgrav/grav#3295]
I would like to add my new plugin to the Grav Repository.
Here are the project details: https://github.com/wernerjoss/grav-plugin-caldav2ics

**Comment by pamtbaau** [comment]
@wernerjoss, I've taken the liberty to give this plugin a spin... Unfortunately, the plugin does not seem to be production ready yet.

Steps:
- Performed manual installation
- Copied `user/plugins/caldav2ics/caldav2ics.yaml` to `user/config/plugins/caldav2ics.yaml`
- Started Admin, but even before logging in:
  > Whoops \ Exception \ ErrorException (E_WARNING)
filemtime(): stat failed for /mnt/c/Users/Lex/Documents/Development/Web/www/grav/site-dev/user/data/calendars/calendars.yaml
  - Fixed issue by creating file `/user/data/calendars/calendars.yaml`
- Started Admin, but even before logging in:
  > Whoops \ Exception \ ErrorException (E_NOTICE)
Undefined index: calendars
- I gave up...

Other impressions:
- Code style is messy:
  - Mixed use of camelCase and PascalCase for variables
  - No use of whitespace between mathematical operators
  - No use of blank lines to improve readability
  - ...
- No check if file exists (see exception above)
- No check if array key exists (see exception above)
- No error handling
- Editor throws issues on non-existing variable
- Event `onSchedulerInitialized` is always handled on every request
- Event `onAdminAfterSave` is always handled, without checking what type of data is being saved
  - When saving a page, an error is thrown

Enough said....

**Comment by wernerjoss** [comment]
@pamtbaau ,
thanks for taking the time to test, reply and comment.
and, yes, you are right: I missed to provide a sane default configuration that would enable the plugin to not crash upon first start, without any prerequisites.
I'll try to comment inline below to your statements, hope that is readable.

> @wernerjoss, I've taken the liberty to give this plugin a spin... Unfortunately, the plugin does not seem to be production ready yet.
> 
> Steps:
> 
>     * Performed manual installation
> 
>     * Copied `user/plugins/caldav2ics/caldav2ics.yaml` to `user/config/plugins/caldav2ics.yaml`

this should be done automatically if using the admin, but as said, the default was incomplete, should now be sane.

> 
>     * Started Admin, but even before logging in:
>       > Whoops \ Exception \ ErrorException (E_WARNING)
>       > filemtime(): stat failed for /path/to/user/data/calendars/calendars.yaml

this is now fixed in branch main.

>       * Fixed issue by creating file `/user/data/calendars/calendars.yaml`
> 
>     * Started Admin, but even before logging in:
>       > Whoops \ Exception \ ErrorException (E_NOTICE)
>       > Undefined index: calendars

also fixed in main.

> 
>     * I gave up...
> 
> 
> Other impressions:
> 
>     * Code style is messy:
>       
>       * Mixed use of camelCase and PascalCase for variables
>       * No use of whitespace between mathematical operators
>       * No use of blank lines to improve readability
>       * ...

have worked on that, although not finished yet.

>     * Unused imports

I think you refer to

    use Symfony\Component\DomCrawler\Crawler;

right ?
this is currently not used in caldav2ics.php, but in the helper file jobs/create_calendars.php which uses the same autoloader
(I thought it would be more comprehensive to use only one vendor directory for the entire plugin)

> 
>     * No check if file exists (see exception above)

improved in main

>     * No check if array key exists (see exception above)

improved in main
 
>     * No error prevention and no error handling
> 
>     * Editor throws issues on non-existing variable

this is unclear, I have no such issue here ?
 
>     * Event `onSchedulerInitialized` is always handled on every request
> 
>     * Event `onAdminAfterSave` is always handled, without checking what type of data is being saved

I have moved these into    onPluginsInitialized()
now, not sure if this is correct, though.

>       * When saving a page, an error is thrown

I think this is a followup from other errors before.

>     * Etc...
> As said, I'm afraid this plugin is not yet ready to be released to the community...

I hope the current state is closer to this goal now :smile: 
would you mind to give it another try ?

**Comment by wernerjoss** [comment]
> Still seems to be happening and I'm afraid I fail to see the need for this...
> - On every page request, the entire `onSchedulerInitialized` will be run.
> - On every Admin request, the entire `onSchedulerInitialized` will be run.
> - On every Admin save request, the entire `onAdminAfterSave` will be run.
> 
> Did you run the debugger to see if events are being handled?

yes, I did.
and it looked ok, at least, it behaves just the same way as the Grav TNTsearch plugin, which I took as a reference.
In fact,  the onSchedulerInitialized event is triggered also by the email plugin and by backup, my plugin just adds
an additional listener to that, thats all.

> Maybe I just don't understand and this is intended behaviour:
> - When should `onSchedulerInitialized` be handled?
> - When should  `onAdminAfterSave` be handled.

ideally, this should only be handeled once, upon save of this particular page, as it does some adjustments due to the strange
behaviour of the scheduler described [here](https://discourse.getgrav.org/t/shebang-in-php-file/16737/2)
(in addition to that, I realized that Symfony's PhpExecutableFinder returns a wrong PHP path on my live site, so I had to introduce another approach)

> Also, this repo is not the place to do a review on the plugin. You might consider closing this request and then we can discuss further at your repo.

closed with this post.
