### ISSUE TITLE
How to center align paragraph, not just a single line

### ISSUE THREAD

**Issue by lustyffh** [getgrav/grav#3300]
Hi, I think this question is specific to Grav, rather than generic to Markdown. I have a page with a poem. I'd like that poem to have center alignment on a page. However, if try to enclose the whole poem into `<center>` tags then all formatting is lost inside. For example, all line breaks and `<p>` tags. Apparently, it's not efficient to enclose each and every line into `<center>` tags. What's the proper way to achieve that with Grav?

**Comment by phmg701** [comment]
Hello, what theme are you using?
I currently use Markdown Extra, [here](https://learn.getgrav.org/content/markdown) you can find instructions.
Once activated, my advice is to set CSS class in page content with {.myclass} to match the CSS class which has centered content.
If you are building your own theme or inherithing from an existing one, you could take a look at [Modular Pages](https://learn.getgrav.org/content/modular), which are a really cool way to build pages block-by-block. Modular Pages give you total control on each block type.

**Comment by rhukster** [comment]
I recommend using shortcode-core. It has a `[center][/center]` shorcode included as well as many other useful ones like `[div]` and `[span]`

**Comment by lustyffh** [comment]
thanks a lot for the hints! I'm using "Quark Open Publishing". And shortcode-core plugin is part of it. So, `[center][/center]` worked for me!
