### ISSUE TITLE
Deleting page with language code doesn't delete the folder

### ISSUE THREAD

**Issue by Ribero** [getgrav/grav#3305]
Grav v1.7.1 - Admin v1.10.1

- add a new page in /root using Admin Panel GUI and select visible to yes in the dialog box
- save the page
- go back to Admin Panel
- Open the page 
- Change status of page from Published=Yes (default) to Published = No -> the page is then marked as non published and you can verify it on the site
- Save & go back to Admin Panel
- From Admin Panel GUI select the page and delete it:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/2266264/105385746-f89b6680-5c13-11eb-9823-2f08d7333376.png">

You first  see that even if the page has the red dot (not published)  the menu shows the contrary (green label Published)

- select delete
- The delete is confirmed by the message "Directory Entry removed successfully"
- but you will see it is not deleted:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/2266264/105386870-3947af80-5c15-11eb-8c85-834a76c9bee1.png">

- You will also see that the page as now has a green dot (published) and you can effectively see it's entry on the site menu but you will get a 404 if you click it
- from Admin Panel, You can then try a second delete and this time the page will be deleted and the web site menu updated.

**Comment by mahagr** [comment]
This will be fixed to the next release.

**Comment by mahagr** [comment]
The logic now works in this way:

1) Attempting to delete the page without language code (en.md, fi.md etc) will always delete the folder
2) If you delete a language-specific page, it will not delete the folder unless it was the last markdown file in that folder

We should probably improve the modal to allow user to choose what he wants to do.
