### ISSUE TITLE
How to download a release candidate like 1.7.0-rc.10

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#3307]
I know one can download earlier release like https://getgrav.org/download/core/grav-admin/1.6.23, but I haven't found a way to download e.g https://getgrav.org/download/core/grav-admin/1.7.0-rc.xx

I've tried all sorts of permutations, but no luck sofar...

I've also tried using `git clone` using tag names like `-b 1.7.0-rc.10`, but I cannot get these clones to work.

Any suggestions?

Why I would like to do that? 
Because Admin of 1.7.x keeps crashing Apache (using WSL + Ubuntu 20.04) when saving any page or config. 1.6.23 is working fine and I believe earlier versions of 1.7 RC worked fine too. Just want to make sure, if it's Grav or my environment.

**Comment by OleVik** [comment]
Are the packages included with the releases not working? Eg., https://github.com/getgrav/grav/releases/tag/1.7.0-rc.10.

Does Apache log any errors when crashing?

**Comment by pamtbaau** [comment]
Haven't though of the releases... Downloading right now.

The Apache logs show errors indeed, but often different ones. It often complains about the the fact that autoloader cannot vind a class. The class it cannot find differs per crash... I have no ideas how Apache works, but it seems as if one process is still processing while the other is already gone.

And sometimes saving goes ok, and when hitting save again Admin throws a 'Fetch failed' and Apache is gone. The saving works, but the refresh of Admin fails. Probably because Apache is already gone before refreshing.

**Comment by w00fz** [comment]
Don't use GitHub directly, go through Getgrav, if it's a testing version, append `?testing=true`:

```
https://getgrav.org/download/core/grav-admin/1.7.0-rc.10?testing=true
https://getgrav.org/download/core/grav-update/1.7.0-rc.10?testing=true
https://getgrav.org/download/core/grav/1.7.0-rc.10?testing=true
```

Same applies for any resource:

```
https://getgrav.org/download/plugins/flex-objects-json/0.1.0
https://getgrav.org/download/themes/quark/2.0.3
```

Easy to reconstruct a URL for download and you get the download triggered automatically.

**Comment by OleVik** [comment]
Those links should make it into docs, @w00fz.

**Comment by w00fz** [comment]
Agreed. Mind opening a ticket in learn or better yet a PR? I will for sure forget!

**Comment by OleVik** [comment]
Yep, see linked PR.

**Comment by w00fz** [comment]
Cheers, appreciate it!
