### ISSUE TITLE
Cache key prefix not being used for Redis

### ISSUE THREAD

**Issue by mabushey** [getgrav/grav#331]
In Drupal 7 if I use `$conf['cache_prefix'] = array('default' => 'www');` (prefix of www), entires look like this:

`www:cache_menu:links:user-menu:tree-data:en:2dca64bda4df082ccbecd433b90151b6de60b9878dd71b4e245f1f8a504f8e53`

Setting `driver: redis` and `prefix: www` under `cache:` in `user/config/system.yml` results in keys like `DoctrineNamespaceCacheKey[969d0ad3]` and `969d0ad3[6224505d462a962b9829398215b41bd5][1]`. The prefix does not appear to be used.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Cache.php#L100-L110

The prefix is used, it's just md5'ed with a few other settings to ensure uniqueness.  Generally this is not something that is read by humans, and we just need to ensure that the key is unique per site/environment.

**Comment by mabushey** [comment]
Can we have an option to select the size of the hash key?

**Comment by rhukster** [comment]
Do you think the size is causing your collisions? Can you confirm by manually changing the size in this file and seeing if that sorts it? What size do you find works best?

**Comment by mabushey** [comment]
Andy,

Really quick:

I didn't encounter a collision, but I've done a lot of research in the past
on collisions, Including writing a search engine with 300K indexed items.
The big thing is being able to clear all keys out of redis for just the
site.
I'll post a proper response by Monday EOD on the ticket.


Also, I am really, really liking Grav. It's fucking awesome! Thank you for
such an amazing system. There's so much to like about it.
Have a great weekend. :)

Michael

**Comment by rhukster** [comment]
No worries michael, thanks for the kind words!

**Comment by rhukster** [comment]
@mabushey any update on this michael?  cheers.

**Comment by mabushey** [comment]
Let's assume a grav site has 93 cache keys that are 32 bit (ie: 7cf68fbe). The odds of a collision are 1 in a million. If we have 100 sites with 93 cache keys each, our odds of collision are now 1 in a hundred.

source: http://preshing.com/20110504/hash-collision-probabilities/

If we have a custom key prefix on each hash, we keep the collision likely-hood at one in a million. If we use 'mir' for a prefix ( keys look like `mir7cf68fbe[a98d0023e1b9052ce565fb53e68d9a2f][1]` we can graph/monitor what Redis is doing, and clearing out keys for a site is as simple as `redis-cli KEYS "mir*" | xargs redis-cli DEL`

I looks like clicking the "Clear Cache" button in the top right of the Admin Dashboard page does not clear out Redis cache.

**Comment by mabushey** [comment]
Looking at this a bit it looks like the key (ie 7cf68fbe) may be site specific. When I looked at it before I was seeing multiple keys, possibility from other Grav sites. If that key is site specific (45767e4e = www.sendthemtomir.com) then a lot of what I've posted is incorrect. I still like the idea of using mir instead of 45767e4e as it's shorter (better performance) and easier to admin/monitor.

**Comment by rhukster** [comment]
I do think your math is off a little because each key is built from factors to guarantee uniqueness between sites.  

If you had a million grav sites using the same redis server, you would have a 1 in a million, so probably 1 collision so 2 sites colliding. So pretty unlikely!

I hear what your saying about a readable portion to the key, so you can manually clear.  So I'm going to change the way the key is built to this:

```
$this->key = ($prefix ? $prefix : 'g') . '-' . substr(md5($uri->rootUrl(true) . $this->config->key() . GRAV_VERSION), 2, 8);
```

This way the prefix is not included in the md5, it simple is prefixed to the front of the key.  So for uniqueness you can just ensure you set your prefix to something that is unique per site.

Sound good?

**Comment by mabushey** [comment]
Sounds good. :)
