### ISSUE TITLE
Maximum function nesting level of '256' reached, aborting! from page.summary()

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#3311]
Pardon the title, it's the standard error-message and most succinct hit for Google. When calling `page.summary()`, under certain circumstances, `Grav\Common\Helpers\Truncator::removeProceedingNodes()` is called 188 times. As best I can tell, this is a result of xDebug being enabled with its defalt `xdebug.max_nesting_level=256`-setting. Still, its not actually doing much since this is set:

```
xdebug.remote_autostart=0
xdebug.remote_enable=0
xdebug.profiler_enable=0
```

This happens on PHP Version 7.4.16, with a [pretty standard production-server](https://olevik.me/staging/grav-skeleton-scholar/phpinfo.php) (no sensitive information contained within). As shown in the [full error stack](https://olevik.me/staging/grav-skeleton-scholar/markdown), [Truncator::truncateLetters()](https://github.com/getgrav/grav/blob/1.7/system/src/Grav/Common/Helpers/Truncator.php#L96) is called with a limit of 300. The site runs on Core 1.7.10, and is a direct copy of [this skeleton](https://github.com/OleVik/grav-skeleton-scholar/tree/2.0.1).

The same occurs even without the [filters applied](https://github.com/OleVik/grav-skeleton-scholar/blob/2.0.1/user/themes/scholar/templates/partials/listing.html.twig#L17). `page.content()` renders just fine.

I'm not sure which end it's best to approach this from: I rarely run xDebug locally in this way, but I'm aware that many servers might. There are other truncators that could be used as less intense alternatives, but access to `page.summary()` is very useful. I'm sure I've come across this before in a similar setup and environment, but I can't recall when.

Is this an intended limit on truncation, or an unintended side-effect of `max_nesting_level`?

**Comment by mahagr** [comment]
Try disabling xdebug if that helps. I would not say it's a bug as long as it works without xdebug and even then it's just one setting that you can use to get rid of the error.

**Comment by OleVik** [comment]
Disabling xDebug is done, as noted with the settings above, though the recursion-limit appears to be enforced by xDebug just being loaded. I am concerned that other production-servers may also be loading it, making `page.summary()` more crashy.

**Comment by mahagr** [comment]
Production servers should never have xdebug enabled. NEVER. :)

**Comment by OleVik** [comment]
It's not enabled, it's loaded. The recursion-limit comes from the DLL-loading, not profiling.

**Comment by mahagr** [comment]
By enabled, I mean that the extension is loaded. I would commend out loading the library in production as it should really be used only for development.

**Comment by OleVik** [comment]
Solved by not loading xDebug. It's rather unfortunate that the max_nesting_level-setting of xDebug takes precedence even if xDebug is not configured to do anything.

**Comment by mahagr** [comment]
Well, xdebug runs normally unless you're running the latest version with PHP 8. But that is not really the issue here -- it's a debug tool and as such, it can be used to reveal information about the site which can be used to attack against the site.
