### ISSUE TITLE
Can't login with 2-Factor Authentication

### ISSUE THREAD

**Issue by steffenweb** [getgrav/grav#3312]
Hello,

i had activate 2-Factor Authentication and can't login. It worked since months until today. 
On my smartphone i use the Microsoft Authenticatior App. 
So i removed the 2-Factor Authentication in my user configuration and configure it again and its still not working. (Regenerate)

I checked my PHP and Grav time settings noticed that nothing is configured in Grav so configured like the settings in php. (see Screenshots)

![gravsettings](https://user-images.githubusercontent.com/79727274/114599054-e3722900-9c92-11eb-8556-474b00895e6b.jpg)
![phpsettings](https://user-images.githubusercontent.com/79727274/114599057-e40abf80-9c92-11eb-9325-ab5353a9dfb4.jpg)

I configured it again but its not working. The twofa_secret was saved but it does not seems to saved correct it looks like:

twofa_secret: 'XXXXXXXX XXXX XXXX XXXX XXXX XXXX XXXX '

Is this the problem?

PHP 7.4.14
Grav v1.7.10
Admin Panel v1.10.10

**Comment by mahagr** [comment]
Update admin plugin. It was released a couple of minutes ago.

**Comment by steffenweb** [comment]
The update fixed the problem, Thank you. Grav is a great CMS!
