### ISSUE TITLE
Grav Admin indicating new version (v1.7.11) available, but fails when you try

### ISSUE THREAD

**Issue by fseesink** [getgrav/grav#3313]
I happened to be going to GitHub to try and snag the latest .zip and noticed a new version (v1.7.11).  But when I copied the link and tried doing a `wget` on my server, it came back with a 404.  Reloading the GitHub release page, v1.7.11 disappeared from the releases.

Guessing you pulled it.  But just note that wherever Grav Admin is looking for updates, it still thinks the new version is out there.  And if someone tries to update, they get a message indicating to wait as it needs to download 6.3MB (but never does).

**Comment by rhukster** [comment]
We had to delete 1.7.11 and reset to 1.7.10 as there were several issues found with 1.7.11.
