### ISSUE TITLE
[add-resource] New Plugin - ExtraWatch stats

### ISSUE THREAD

**Issue by extrawatch** [getgrav/grav#3319]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **extrawatch/extrawatch-grav-stats**

https://github.com/extrawatch/extrawatch-grav-stats

Best Regards,
Matej Koval
www.extrawatch.com

**Comment by rhukster** [comment]
Added to GPM for next udpate

**Comment by extrawatch** [comment]
thanks
