### ISSUE TITLE
Textfield maxlength validation newline issue

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3324]
There is still a problem with the textarea maxlength validation. If you are using newlines, they are counted/processed differently:

* The browser inserts `\n` - 1 character (for the builtin browser check)
* Javascript reads '\n' -1 character (for length calucation)
* The browser sends '\r\n' - 2 chracters
* The grav code will receive and count '\r\n'

You can read more about that here:
https://stackoverflow.com/questions/14217101/what-character-represents-a-new-line-in-a-text-area

Now the issue is, that if you have a simple textarea with maxlength 10 and you enter:
```
a
b
c
d
e
```

The browser will count 9, but will send 13 characters. And so will the Grav validation fail.

So in order to get this working we must somehow proceed the text of the textarea field and replace all '\r\n' with '\n'. That sounds like the only working solution to me. What do you think?

**Comment by mahagr** [comment]
Text validation/filtering can be easily tweaked to add some logic to replace \r\n and \r with \n.

**Comment by NicoHood** [comment]
Thanks a lot!
