### ISSUE TITLE
Unable to edit pages since last 1.7.13 update

### ISSUE THREAD

**Issue by sebastien-favier** [getgrav/grav#3332]
Hi,

I can't edit any pages since last update :(
What i can do ? Have you need more informations?

![image](https://user-images.githubusercontent.com/16797554/116001807-c0326c80-a5f6-11eb-8a42-a6bddb6b4df7.png)

Regard

EDIT : Message
`"Argument 1 passed to Grav\Common\Flex\Types\Pages\PageIndex::getLanguageTemplates() must be of the type string, int given, called in /home/spinti/site/system/src/Grav/Common/Flex/Types/Pages/PageIndex.php on line 419 "`

**Comment by mahagr** [comment]
@sebastien-favier Fixed, look into the commit how to fix this in your local (super simple fix).

This is an issue only with numeric language codes, such as version numbers.

**Comment by mahagr** [comment]
Here is the commit https://github.com/getgrav/grav/commit/2cf7a5f281e3b5008474230c488c1e4653fc2354

Moved the issue to Grav as well.

**Comment by sebastien-favier** [comment]
Thank you very much for your speed!
I fixed the problem with your solution ✅

Regards
