### ISSUE TITLE
Video not shown anymore

### ISSUE THREAD

**Issue by yuperi** [getgrav/grav#3333]
With version 1.7.13 video not shown anymore
Picture is showing
`![](image://mex3a/mal7a.mp4)` show empty
`![](image://mex3a/mal7.png)` as expected
If I can downgrade grav, please tell me how to do it

**Comment by rhukster** [comment]
What version where you on before that worked?  I don't see anything that would of changed the video behavior between .12 and .13.

**Comment by yuperi** [comment]
1.7.10

**Comment by mahagr** [comment]
You can downgrade Grav by just installing the older version (remember to downgrade admin and flex objects plugin as well). You can do that by manually downloading the package(s) and doing a `bin/gpm directinstall` from CLI or using admin to do that.

**Comment by mahagr** [comment]
Grav 1.7.11: Fixed deleting page with language code not removing the folder if it was the last language [#3305]
