### ISSUE TITLE
[add-resource] New plugin

### ISSUE THREAD

**Issue by X-Ryl669** [getgrav/grav#3340]
I would like to add my new plugin to the Grav Repository.
Here are the project details: [grav-plugin-viewer3-d](https://github.com/X-Ryl669/grav-plugin-viewer3-d)

It's a 3D object model viewer for Grav.

**Comment by pamtbaau** [comment]
@X-Ryl669, I've taken the liberty to test-run your plugin. In short: I cannot get it to work...

I proceeded as follows:
- `$ cd user/plugins`
- `$ mkdir viewer3-d`
- `$ cd viewer3-d`
- `$ git clone https://github.com/X-Ryl669/grav-plugin-viewer3-d .`
- Created page `user/pages/03.viewer/default.md`
- Downloaded `https://blog.cyril.by/en/documentation/3d%20models/filament-detector/SupportFilDet.stl` into folder
- Added the following inside the markdown of the page:
  <pre>
  ```3dv
  SupportFilDet.stl
  ```
  </pre>
- Pointed browser to `localhost/grav/viewer`
  - No 3D is being shown
  - A `<div class="online_3d_viewer"...>` is being created, but is empty

Other remarks:
- I would suggest using a Shortcode instead of Markdown extension:
The plugin is extending the block code fences (triple back-ticks) using <code>```3dv</code> to generate the code to view the 3D model. IMHO adding a 3D viewer to the page is not really what block code fences are meant to be used for.
- I think a name like "viewer-3d" would be a more suitable name. 
- In its current state, I don't think the plugin should be released to the community. My suggestion would be to close this issue and open a new one when the plugin is ready for production.

**Comment by X-Ryl669** [comment]
>     * A `<div class="online_3d_viewer"...>` is being created, but is empty

This is strange, since the code that writes this DOM node also add some content to it:

```php
        $Block['markup'] = "<div class='online_3d_viewer' model='".$slug.'/'.$Block['src']."' camera='-1.5,-3.0,2.0,0,0,0,0,0,1' edge='#000000' color='#A0B0A0'><div class='toolbar'></div><div class='details'></div></div>";
```
Do you have some Javascript error in your console ?










>     * I would suggest using a Shortcode instead of Markdown extension:
>       The plugin is extending the block code fences (triple back-ticks) using `` ```3dv `` to generate the code to view the 3D model. IMHO adding a 3D viewer to the page is not really what block code fences are meant to be used for.

TBH, the ` ```header ` is used in many other project to include plugin. For example, in Docsify it's [how you embed a PDF viewer](https://github.com/lazypanda10117/docsify-pdf-embed) or [how you embed a live diagram](https://github.com/Leward/mermaid-docsify) or [how to embed a 3D model](https://github.com/X-Ryl669/docsify-gltfexplorer)

I've no idea what are short codes so maybe you're right it's better, but I'm used to the Docsify way of extending with plugins.



>     * I think a name like "viewer-3d" would be a more suitable name.

At first, I started `bin/plugin devtools new-plugin` as stated in the documentation and entered `3DViewer` for the name. But it breaks Grav installation, since it creates a plugin called `3-d-viewer` and a PHP class called `3DViewerPlugin` which is an invalid PHP name (it starts with a number, that's not allowed in PHP), thus breaks the admin page and the website. 

So I retried with "Viewer3D" and it created `viewer3-d` (with the ugly dash in between).  I've tried to rename it to viewer3D but the admin would not see the plugin anymore. So I'm left with viewer3-d that works. The admin page is picky about which plugin it displays (it has to follow some obscure naming rules, mixing slug and actual plugin name and PHP's class name) so when you change some name, this relation breaks silently leading to the plugin not listed anymore without any error message. 
If you can document what is the black magic rule for naming plugins that actually works, I'll be happy to follow it.

**Comment by pamtbaau** [comment]
Shall we continue the conversation on your repo? I'll create an issue with a copy of my experience.

**Comment by X-Ryl669** [comment]
Sure!

**Comment by X-Ryl669** [comment]
I've followed your suggestions and instead used a shortcode instead of markdown's code block.
The new plugin is [here](https://github.com/X-Ryl669/grav-plugin-viewer3d), if you can review it and if it's passing your expectations, please include in the grav's plugin repository. Thank you for your detailed review.

**Comment by X-Ryl669** [comment]
I think all issues mentionned here were resolved. Can you include it in grav's plugin repository ? Thanks!

**Comment by rhukster** [comment]
You will need to have a release before we can add it to GPM.

**Comment by rhukster** [comment]
@X-Ryl669 please create a release so this will show up in GPM.  Cheers.

**Comment by X-Ryl669** [comment]
Should be done now. Thanks!

**Comment by rhukster** [comment]
I still don't see a release.

**Comment by X-Ryl669** [comment]
Indeed, this issue points to the older repository. I'll close it now, since it's not used anymore. The new repository is [here](https://github.com/X-Ryl669/grav-plugin-viewer3d).

**Comment by rhukster** [comment]
Ok, this has been added for next update.  Cheers.
