### ISSUE TITLE
Add Event / Hook for Plugin Update

### ISSUE THREAD

**Issue by wernerjoss** [getgrav/grav#3344]
This is a feature request and / or enhancement proposal:
I would like to have the possibility for plugins to register to an `onPluginsUpdate` Event which would allow to perform housekeeping tasks upon plugins update, such as data format migration - see [this discussion](https://github.com/wernerjoss/grav-plugin-ipcount/pull/2) .
btw., Wordpress (which I used before switch to Grav) has such a hook - I find this very useful and would like to have this also in Grav.

**Comment by pamtbaau** [comment]
You might consider doing a search before creating a new issue.... [Feature: onPluginInstalled and onPluginUpdated events](https://github.com/getgrav/grav/issues/3342)

You should probably close this one.

**Comment by wernerjoss** [comment]
well, I did a search some time before and found nothing then...
closing this now.
