### ISSUE TITLE
daterange without start fails

### ISSUE THREAD

**Issue by tbowan** [getgrav/grav#3345]
Hi,

After reading the documentation of [daterange in collection](https://learn.getgrav.org/16/content/collections#date-range), I understood that I can only specify the end date of the range, without providing the start date.

Indeed, if I specify a collection without the start date, grav encounter an exception :

```
content:
  items: '@self.descendants'
  dateRange:
    end: now
  limit: 10
```

The exception is as follows :

```
(An exception has been thrown during the rendering of a template ("DateTime::__construct(): Failed to parse time string (0) at position 0 (0): Unexpected character").)
```

The problem occurs first in the method that build the collection (/system/src/Grav/Common/Page/Pages.php at line 546). As no start is provided, it uses the value 0. Then call `$collection->dateRange(0, 'now', false)` which will always convert the start value (0) into a timestamp with Utils::date2timestamp (which call a basic `new DateTime(0)' which fails).

**Comment by tbowan** [comment]
Here is a diff that fix my problem.

```diff
--- a/system/src/Grav/Common/Page/Collection.php
+++ b/system/src/Grav/Common/Page/Collection.php
@@ -331,7 +331,7 @@ class Collection extends Iterator implements PageCollectionInterface
      */
     public function dateRange($startDate, $endDate = false, $field = null)
     {
-        $start = Utils::date2timestamp($startDate);
+        $start = is_numeric($startDate) ? $startDate : Utils::date2timestamp($startDate);
         $end = $endDate ? Utils::date2timestamp($endDate) : false;

         $date_range = [];
```

**Comment by tbowan** [comment]
The PR has a better fix (_i.e._ fix all implementation of the dateRange method).

**Comment by mahagr** [comment]
I'm currently merging/testing the change.
