### ISSUE TITLE
Media operations not working when using image:// stream

### ISSUE THREAD

**Issue by bperry11** [getgrav/grav#3349]
After upgrading to 1.7.14 some markdown I had in 1.6 stopped working

```![Church Greeter Smiling](image://greeter-2.jpg?cropZoom=350,400)```

Pulling the image from the user/images folder the cropZoom would not work. 

Looks like the html would render as 

```src="/user/images/greeter-2.jpg?cropZoom=300,450?cropZoom=300,450"```

and the image would not be cropped.

Work around was to copy image to page folder and not use the php stream.

**Comment by mahagr** [comment]
@bperry11 Should be an easy fix, please check my commit and report back.

**Comment by mahagr** [comment]
Also, the fix should allow any other stream to be used. :)
