### ISSUE TITLE
Skeleton Grayscale abandoned

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#3353]
According the dev in response to an [issue](https://github.com/vmcosta/grav-skeleton-grayscale-site/issues/2) created by @flaviocopes at Nov 2016:

> Hi @flaviocopes Sorry about that.
Unfortunately I no longer have the time to maintaining this project/theme skeleton, could you be so kind to un-list it from the downloads section of Grav website?
>
> Thank you.

It might save some frustration when it has been removed.

**Comment by rhukster** [comment]
removed (also theme as it's the same author)

**Comment by pamtbaau** [comment]
What if a site does use the now deleted theme and needs a re-install? 

Sure, it can be cloned or downloaded as a zip, but it will lead to confusion and questions on the forum(s) I'm afraid...
