### ISSUE TITLE
https://getgrav.org/ offline: error 500

### ISSUE THREAD

**Issue by TomOne** [getgrav/grav#3356]
Not sure if this is the right place to report this, but https://getgrav.org/ is offline and returns a 500 error.

**Comment by ChetanGoti** [comment]
Yes, just came to report this. The error title says:

```
Whoops \ Exception \ ErrorException (E_WARNING)
file_put_contents(): Only 0 of 1229014 bytes written, possibly out of free disk space
```

**Comment by rhukster** [comment]
Thanks cleared the space up and we're back running again.
