### ISSUE TITLE
[add-resource] Update Existing Plugin/Theme

### ISSUE THREAD

**Issue by DanielFlaum** [getgrav/grav#3357]
I would like to update my plugin/theme to the Grav Repository.
Here are the project details: **DanielFlaum/grav-plugin-mermaid-diagrams**

**Comment by bitstarr** [comment]
I think the plugin directory automatically updates when you add a new tag. As i see it provides the current version of your plugin right now.

**Comment by DanielFlaum** [comment]
So it does. I'll see about adding relevant documentation to https://learn.getgrav.org/17/advanced/grav-development#theme-plugin-release-process, which is what I followed because it's what I vaguely remembered following last time.
