### ISSUE TITLE
Revisions - New Plugin

### ISSUE THREAD

**Issue by z3cka** [getgrav/grav#336]
I would like to add my new plugin to the Grav Repository.
Here are the project details: https://github.com/z3cka/grav-plugin-revisions

**Comment by nunull** [comment]
Haven't thought a lot about this, but  it seems that if at least one revision exists, you always read both files in completely and compare the contents. This is not very efficient. Maybe it would be better to use some hashing function like `sha1_file` to check wether the files differ.

**Comment by z3cka** [comment]
Good idea!

**Comment by rhukster** [comment]
FYI, the Grav team was talking about revisions and implementation details the other day.  Perhaps this is something we can work on together?

**Comment by z3cka** [comment]
That would be great! This was mostly a quick pass at learning how Grav plugins work and Grav's development concepts.

**Comment by rhukster** [comment]
Closing as we are going to add similar functionality.

**Comment by z3cka** [comment]
Where is this functionality going to be added?

**Comment by noahlvb** [comment]
This Issue has been silent for the past 2 years and I currently have a client who would really like to use the revision functionality. Can you give me any idea of when it is coming?

**Comment by flaviocopes** [comment]
Page revisions will be part of Admin Pro. No ETA at the moment, it's still work in progress.
