### ISSUE TITLE
Fresh grav-admin-v1.7.15 install generates error

### ISSUE THREAD

**Issue by awrog** [getgrav/grav#3366]
Is did a **fresh** install of grav-admin-v1.7.15.
It generates:
This page isn’t working right now
[domainname] can't currently handle this request.
HTTP ERROR 500

grav-admin-v1.7.14 works without errors

grav-admin-v1.7.14.zip => 20,773,764 bytes
grav-admin-v1.7.15.zip => 18,452,925 bytes (!)

**Comment by awrog** [comment]
(auto) Updating an existing (freshly installed) grav-admin-v1.7.14 site does not cause any errors

**Comment by pamtbaau** [comment]
Tried several fresh installs on Windows 10 + WSL 2 + Apache, but cannot reproduce.
- Fresh install using `$ wget https://getgrav.org/download/core/grav-admin/1.7.15 .`
- `http://localhost/grav/grav-admin` works fine
- `http://domain` works fine

**Comment by awrog** [comment]
@pamtbaau Downloaded again, extracted the zipfile and uploaded to the domain again.
Now it works :-( 
I suspect a faulty download or (in this case more likely) interference from MS Defender (extracting the first time took awfully long).
Thanks for checking
