### ISSUE TITLE
Aesthetic glitch

### ISSUE THREAD

**Issue by thistlillo** [getgrav/grav#3379]
I am using the latest grav version 1.7.13.

I added to my site some child pages with authenticated access, that require log in. 

When I log out, clicking on `log out` in the menu bar, this text, including the bracket, is shown on the screen:

````
}
Info: You have been successfully logged out...
````
![image](https://user-images.githubusercontent.com/6717655/121031534-b6ca2180-c7aa-11eb-8b11-532c415ec075.png)

**Comment by w00fz** [comment]
@thistlillo do you have a custom page template for it? That looks like `}` is leaking through the twig file, perhaps you have a custom `messages.html.twig`?

I think we are missing some informations here and I believe it has to do with a custom twig where perhaps there is a mis-closed parenthesis or a misplaced one, unfortunately without more details / screenshots / url it's hard to track down.

**Comment by thistlillo** [comment]
Sorry, you are right. I am using the hypertext theme. May be I should open an issue with them. Sorry again

**Comment by w00fz** [comment]
No problem 👍
