### ISSUE TITLE
Upgrade from 1.6x to 1.7.16 breaks import of blueprints for pages/modular folders

### ISSUE THREAD

**Issue by fatelgit** [getgrav/grav#3381]
Hello,
first of all: thank you for this great project!
I've recently upgraded a grav instance from 1.6x to 1.7.16 which works fine in general but I've noticed that my blueprints for modular pages won't work anymore. Since I couldn't find any problems with yaml syntax or configuration I dug a little deeper and found an interesting change in Pages.php:  
https://github.com/getgrav/grav/blob/ad1cf15d7c7719aa884cef7f2aad245052ebe0c7/system/src/Grav/Common/Page/Pages.php#L1222-L1227 

Whereas before upgrade there was simply this line: 
`self::$types->scanBlueprints('theme://blueprints/');` 

So in case you have a folder called "pages" **and** one called "modular" only the content of "pages" will be used. I think this isn't exactly a bug or faulty code but I wonder if this is intended. 

Edit: In case someone else is having this issue - moving my "modular" folder into "pages" folder is sufficient to make it work again.

**Comment by mahagr** [comment]
Yes, the page blueprints used to be in the wrong folder and it was fixed by adding logic to detect the new location and use it if found.

Maybe some themes worked around the same bug themselves? Which theme are you using?

**Comment by fatelgit** [comment]
Thank you for your quick response!
We are using our own custom theme. Issue can be closed. Just wanted to be sure because I couldn't find a hint in the upgrade guide.

**Comment by mahagr** [comment]
I added some documentation about this issue:

https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#page-blueprints-stop-working-in-admin
