### ISSUE TITLE
page header redirect does not work with external urls

### ISSUE THREAD

**Issue by cord** [getgrav/grav#339]
http://learn.getgrav.org/content/headers#redirect

does not work for external sites, the redirect url looks like this:

http://grav-local.de/dehttp://myexternalsite.com

**Comment by rhukster** [comment]
I will take a look at this. thanks.

**Comment by flaviocopes** [comment]
Works fine for me @cord, I tried adding that header to a blog post page. Was it a root page?

**Comment by rhukster** [comment]
Discovered it was specific to being under a language. Should be sorted now.
