### ISSUE TITLE
@self and @page taking precedence over @taxonomy when using them in the same collection.

### ISSUE THREAD

**Issue by hotdoy** [getgrav/grav#3391]
Mixing up 2 (or more) collection options does not seem to behave properly. 
In the example, It looks like `@self.children` is being processed but the taxonomy part is ignored.

**Not fine**

```
{ 
    items:
    [{'@self.children': '', '@taxonomy.category': 'myCategory'}], 
    'order': {'by': 'folder', 'dir': 'asc'}
}
```

Same if I put taxonomy first. Only `@self.children` is processed.

**This works fine**

```
{ 
    items:
    {'@taxonomy.category': 'myCategory'}, 
    'order': {'by': 'folder', 'dir': 'asc'}
}
```

**This is also fine**

```
{ 
    items:
    {'@self.children': ''}, 
    'order': {'by': 'folder', 'dir': 'asc'}
}
```

I also tried using `page.evaluate()` with no success.

_Grav 1.7.17_

**Comment by hotdoy** [comment]
Here is a bit more context. 

```
{% set audienceQuery = uri.query('audience') %}

{% set filteredOptions = { 
    items:
    [{'@self.children': '', '@taxonomy.audience': audienceQuery}], 
    'order': {'by': 'folder', 'dir': 'asc'},
    'filter': {'type': 'service'},
} %}

{% set unfilteredOptions = { 
    items:
    {'@self.children': ''}, 
    'order': {'by': 'folder', 'dir': 'asc'},
    'filter': {'type': 'service'},
} %}

{% set services = audienceQuery ? page.collection(filteredOptions) : page.collection(unfilteredOptions) %}
```

**Comment by pamtbaau** [comment]
@hotdoy, I tried to reproduce the issue, but can't... My setup:

- Folder structure from a default [Blog Site](https://getgrav.org/download/skeletons/blog-site/2.0.0-admin) skeleton with `02.test` folder added.
  ```
  user/pages
  ├── 01.blog
  │   ├── blog.md
  │   ├── classic-modern-architecture
  │   │   ├── item.md
  │   │   └── unsplash-luca-bravo.jpg
  │   └── ...etc.
  ├── 02.test
  │   ├── blog.md
  │   └── test-item
  │       └── item.md     <-- has taxonomy tag: xxx
  └── modules
  ```

- Updated Quark `/user/themes/quark/templates/blog.html.twig` with:
  ```
  {% set options = { 
      items:
      [{'@self.children': '', '@taxonomy.tag': 'xxx' }], 
      'order': {'by': 'folder', 'dir': 'asc'},
      'filter': {'type': 'item'},
  } %}
  {% set collection = page.collection(options) %}
  ```

  And
  ```
  {% set options = { 
      items:
      [{'@page.children': '/blog', '@taxonomy.tag': 'xxx' }], 
      'order': {'by': 'folder', 'dir': 'asc'},
      'filter': {'type': 'item'},
  } %}
  {% set collection = page.collection(options) %}
  ```

- Result: 
  - All blog items in folder `/01.blog` + item with `tag: xxx` from folder `/02.test` are shown.
  - Removed collection definition from '01.blog' with same result.
  - Tried more different setups, repeatedly cleared cache, but taxonomies are always shown.

**Comment by hotdoy** [comment]
Thanks. I'll get back to it in the coming days and see what happens then.

**Comment by hotdoy** [comment]
Been a while. Can't even remember the specifics. Closing...
