### ISSUE TITLE
Getting error when submitting the forms  ( Trying to access array offset on value of type null )

### ISSUE THREAD

**Issue by geogeorgejoseph** [getgrav/grav#3392]
### Getting error when submitting the forms 
Error Msg : **Trying to access array offset on value of type null**
![Crikey-There-was-an-error-](https://user-images.githubusercontent.com/25584016/124091506-8a38bb00-da73-11eb-8056-d929f7ef9229.png)

**Comment by mahagr** [comment]
It looks like you have an old version of the Form plugin. Please update it as this issue has already been fixed.

**Comment by geogeorgejoseph** [comment]
> It looks like you have an old version of the Form plugin. Please update it as this issue has already been fixed.

Ok. Thank you @mahagr
