### ISSUE TITLE
[BUG] Clockwork debugger won't output empty values

### ISSUE THREAD

**Issue by Karmalakas** [getgrav/grav#3393]
Wasted quite a bit of time until realized debugger doesn't work as expected. Some empty values are completely ignored and not displayed in log. Eg.:
```twig
    {{ dump('TRUE') }}
    {{ dump(true) }}
    {{ dump('FALSE') }}
    {{ dump(false) }}
    {{ dump(0) }}
    {{ dump('') }}
    {{ dump(null) }}
    {{ dump([]) }}
    {{ dump({}) }}
```

Debugger output:
![image](https://user-images.githubusercontent.com/3602819/124160461-f253c500-daa4-11eb-8c16-611068210553.png)

So basically these three are never displayed:
```twig
    {{ dump(false) }}
    {{ dump(0) }}
    {{ dump('') }}
```

P. S. Also was always wondering why `null` is wrapped into an array 🤔

**Comment by mahagr** [comment]
This is upstream issue.

**Comment by Karmalakas** [comment]
I have no idea what that means 😄 
Are you saying it's Clockwork related and nothing can be done on Grav side?

**Comment by mahagr** [comment]
Oh, I meant to say that the issue is in clockwork. Debugbar is fine.

**Comment by Karmalakas** [comment]
Created [an issue there](https://github.com/itsgoingd/clockwork/issues/507)

**Comment by Karmalakas** [comment]
Apparently [with `clock()` it works just fine](https://github.com/itsgoingd/clockwork/issues/507#issuecomment-872531971) (and also `null` is logged normally) 😕
