### ISSUE TITLE
Page Filter

### ISSUE THREAD

**Issue by saysora** [getgrav/grav#340]
Hate to do this, I'm super noob when it comes to Grav, but am loving what I am testing out here.

I was wondering if when using the page.find function, if there's a way to filter by a custom option set in the blueprint.yaml.

For instance, I'm making a blog and listing options as to whom is the author. I want when you go to the author page to list the blogs that the author has posted on the site, so to do so I wanted to do something like-

{% for post in page.find('/blog').children.filter(author.name, header.author.name) %}
posts
{% endfor %}

Am I just missing some tiny detail here?

**Comment by flaviocopes** [comment]
Solved in Gitter
