### ISSUE TITLE
[add-resource] New Plugin: PageLocks

### ISSUE THREAD

**Issue by skinofthesoul** [getgrav/grav#3401]
I would like to add my new plugin to the Grav Repository.
Here are the project details: [skinofthesoul/grav-plugin-pagelocks](https://github.com/skinofthesoul/grav-plugin-pagelocks/)

**Comment by rhukster** [comment]
Sorry, i've been super lax on this, will be catching up this week.

**Comment by rhukster** [comment]
Added for next GPM update.
