### ISSUE TITLE
Open BaseDir Issue

### ISSUE THREAD

**Issue by blizam** [getgrav/grav#3403]
Running into an open basedir exception recently, possibly after a recent Grav update, or PHP 7.4 upgrade, though I'm not 100% sure when it started.

Specifically on pages with contact forms I'm getting this error:

is_file(): open_basedir restriction in effect. File(/index.yaml) is not within the allowed path(s): (/home/xxxx/:/tmp/:/var/tmp/:/opt/alt/php74/usr/share/pear/:/dev/urandom:/usr/local/php74/lib/:/usr/local/php74/lib/:/usr/local/php73/lib/:/usr/local/php72/lib/:/usr/local/lib/php/)

this file:

/vendor/rockettheme/toolbox/File/src/AbstractFile.php

line 157 this function:

```
    public function exists()
    {
        return null !== $this->filename && is_file($this->filename);
    }
```

I'm pretty sure the issue is with the leading / on the is_file() for /index.yaml

It's something "related" with the cache too I guess because if I turn off the grav cache there's no issue

I suppose it's worth mentioning that I've only seen this on sites running Gantry as well, but Gantry doesn't appear in the backtrace anywhere.

 Grav\Plugin\FormPlugin onTwigVariables is the first thing after the symfony event dispatcher then

/user/plugins/form/form.php

```
        if (!isset($twig->twig_vars['form'])) {
            $twig->twig_vars['form'] = $this->form($page);
        }
```

**Comment by rhukster** [comment]
Sounds like an issue with your open_basedir settings. That specifically limits PHP to only use files you allow in that path that is defined. Probably started with an upgrade to PHP, or something that added open_basedir paths to your configuration.

It's not a Grav issue, and this functionality has not changed within Grav.  I would put your webroot in open_basedir setting, or empty it out completely.

**Comment by blizam** [comment]
Yeah, I think it's happened from upgrading to PHP 7.4 -- and I confirmed it on a non-Gantry Grav site just now, and an older version of Grav as well... I think the webroot is configured in the open_basedir settings though... which led to me think the forward slash on index.yaml was pathing as a double-forward-slash... thank you for the response and I'll bug my host to investigate a little more and ensure the webroot is configured properly

**Comment by blizam** [comment]
hrm... any reason this is only happening with the cache on though?

**Comment by rhukster** [comment]
Cache is trying write files to the file system.

**Comment by blizam** [comment]
So in this specific request it should be looking for index.yaml somewhere in the webroot...

/home/xxxx/public_html/.../index.yaml

but instead it's merely looking in the root

/index.yaml

so I think the webroot isn't being properly appended to the request

**Comment by stvnthomas** [comment]
We're running into the same problem. Just upgraded to latest Grav and PHP 7.4. We have a password protected page using Private that's throwing the same error.

```
E_WARNING - is_file(): open_basedir restriction in effect. File(/index.yaml) is not within the allowed path(s): (/var/www/vhosts/example.com/:/tmp/)
```

It looks like it's not resolving the path correctly.

**Comment by blizam** [comment]
Any ideas @rhukster ? I had the same Open BaseDir config under PHP 7.2 (which you can actually see in the error response that provides the config) so I really think this is a PHP 7.4 specific issue... something with how this particular path is fed to AbstractFile.php -- in PHP 7.2 it was either the proper full webroot or (conjecture on my part) perhaps it didn't have the leading slash making it a relative(?) path inside the webroot... in PHP 7.4 it's looking at the server root, not the webroot for index.yaml

**Comment by rhukster** [comment]
@mahagr can you think of anything that would cause this in PHP 7.4?

**Comment by mahagr** [comment]
I don't think it has anything to do with PHP but our locator call, which seems to fail (false) on a missing file or folder.

`index.yaml` is used by flex objects to have a quick way to get a full list of the objects without needing to go through the filesystem. It is used for caching, which is why the issue appears when the cache is being used.

Can you check out the backtrace where it is being called?

**Comment by blizam** [comment]
it's the form plugin near as I can tell. Here' the full Whoops backtrace:

Whoops\Exception\ErrorException 
…/vendor/rockettheme/toolbox/File/src/AbstractFile.php159
55
 is_file
…/vendor/rockettheme/toolbox/File/src/AbstractFile.php159
54
RocketTheme\Toolbox\File\AbstractFile exists
…/system/src/Grav/Framework/Form/FormFlash.php123
53
Grav\Framework\Form\FormFlash loadStoredForm
…/system/src/Grav/Framework/Form/FormFlash.php88
52
Grav\Framework\Form\FormFlash __construct
…/system/src/Grav/Framework/Form/Traits/FormTrait.php433
51
Grav\Plugin\Form\Form getFlash
…/system/src/Grav/Framework/Form/Traits/FormTrait.php376
50
Grav\Plugin\Form\Form traitReset
…/user/plugins/form/classes/Form.php260
49
Grav\Plugin\Form\Form reset
…/user/plugins/form/form.php926
48
Grav\Plugin\FormPlugin getFormByName
…/user/plugins/form/form.php1025
47
Grav\Plugin\FormPlugin form
…/user/plugins/form/form.php390
46
Grav\Plugin\FormPlugin onTwigVariables
…/vendor/symfony/event-dispatcher/EventDispatcher.php264
45
Symfony\Component\EventDispatcher\EventDispatcher doDispatch
…/vendor/symfony/event-dispatcher/EventDispatcher.php239
44
Symfony\Component\EventDispatcher\EventDispatcher callListeners
…/vendor/symfony/event-dispatcher/EventDispatcher.php73
43
Symfony\Component\EventDispatcher\EventDispatcher dispatch
…/system/src/Grav/Common/Grav.php556
42
Grav\Common\Grav fireEvent
…/system/src/Grav/Common/Twig/Twig.php408
41
Grav\Common\Twig\Twig processSite
…/system/src/Grav/Common/Service/OutputServiceProvider.php36
40
Grav\Common\Service\OutputServiceProvider Grav\Common\Service\{closure}
…/vendor/pimple/pimple/src/Pimple/Container.php118
39
Pimple\Container offsetGet
…/system/src/Grav/Common/Processors/RenderProcessor.php40
38
Grav\Common\Processors\RenderProcessor process
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php50
37
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php62
36
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php38
35
Grav\Common\Processors\DebuggerAssetsProcessor process
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php50
34
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php62
33
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Common/Processors/PagesProcessor.php81
32
Grav\Common\Processors\PagesProcessor process
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php50
31
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php62
30
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Common/Processors/TwigProcessor.php38
29
Grav\Common\Processors\TwigProcessor process
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php50
28
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php62
27
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Common/Processors/AssetsProcessor.php39
26
Grav\Common\Processors\AssetsProcessor process
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php50
25
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php62
24
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Common/Processors/SchedulerProcessor.php40
23
Grav\Common\Processors\SchedulerProcessor process
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php50
22
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php62
21
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Common/Processors/BackupsProcessor.php39
20
Grav\Common\Processors\BackupsProcessor process
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php50
19
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php62
18
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Common/Processors/TasksProcessor.php69
17
Grav\Common\Processors\TasksProcessor process
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php50
16
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php62
15
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Common/Processors/RequestProcessor.php63
14
Grav\Common\Processors\RequestProcessor process
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php50
13
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php62
12
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Common/Processors/ThemesProcessor.php38
11
Grav\Common\Processors\ThemesProcessor process
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php50
10
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php62
9
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Common/Processors/PluginsProcessor.php39
8
Grav\Common\Processors\PluginsProcessor process
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php50
7
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php62
6
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Common/Processors/InitializeProcessor.php130
5
Grav\Common\Processors\InitializeProcessor Grav\Common\Processors\{closure}
…/system/src/Grav/Common/Debugger.php546
4
Grav\Common\Debugger profile
…/system/src/Grav/Common/Processors/InitializeProcessor.php131
3
Grav\Common\Processors\InitializeProcessor process
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php50
2
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php62
1
Grav\Framework\RequestHandler\RequestHandler handle
…/system/src/Grav/Common/Grav.php295
0
Grav\Common\Grav process
…/index.php58

**Comment by blizam** [comment]
Upgrading from Grav 1.7.17 to 1.7.18 appears to have fixed it... I did some plugin updates at the same time so it might've been related to a Flex or Email plugin update.

I can no longer reproduce the issue after upgrading Grav and plugins

**Comment by mahagr** [comment]
I see, this is the form bug I fixed two weeks ago. :)
