### ISSUE TITLE
chat.getgrav.org just takes you to the main Grav webpage; how to get to Grav Discord?

### ISSUE THREAD

**Issue by fseesink** [getgrav/grav#3407]
I hope I am posting this to the right place.  If not, please let me know.

How does one get to the Grav Discord server?  When I click the Discord icon in the upper right of https://getgrav.org/, it takes me to https://chat.getgrav.org/.  But that just loads the same page all over again.  And further down on the page where there is another Discord icon, that again just points to https://chat.getgrav.org.

I was kind of expecting the usual invite link somewhere to join the Discord server.  Am I wrong?

**Comment by w00fz** [comment]
Sorry about that, looks like we do have an issue. You can reach the details via https://getgrav.org/discord which is where you are supposed to be redirected from chat.getgrav.org

**Comment by fseesink** [comment]
@w00fz cool!  Thanks!  That worked.

**Comment by rhukster** [comment]
Fixed this.
