### ISSUE TITLE
Warning:  Undefined array key "SERVER_SOFTWARE" in index.php

### ISSUE THREAD

**Issue by lufog** [getgrav/grav#3408]
![image](https://user-images.githubusercontent.com/10379487/126261868-b6254ddd-fb42-468c-8881-3f2060645598.png)

OS: Windows 11
PHP: 8.0.8 ts x64
Server:  `php -S 0.0.0.0:80 system\router.php`

**Comment by rhukster** [comment]
Replace line 20 in index.php with: 

```
    $symfony_server = stripos(getenv('_'), 'symfony') !== false || stripos($_SERVER['SERVER_SOFTWARE'] ?? '', 'symfony') !== false || stripos($_ENV['SERVER_SOFTWARE'] ?? '', 'symfony') !== false;
```
