### ISSUE TITLE
error with missing Type of | null for the `loadDirectoryConfig`

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav#3409]
Using latest release of Grav and Admin

while inside the pages GUI

<img width="1176" alt="Screenshot 2021-07-20 at 12 22 54" src="https://user-images.githubusercontent.com/7076631/126316036-1bfc29a2-a90b-4a32-8361-e6f8d5189d50.png">

clickin on the Configuration - Top Right Corner

<img width="1162" alt="Screenshot 2021-07-20 at 12 22 46" src="https://user-images.githubusercontent.com/7076631/126316049-92c35e9b-07ae-4770-84d1-64f2f86b58c4.png">

errors out due to the loadDirectory expecting an Array but getting a null 

i could provide more details if needed but i think this is a bug ?

**Comment by k8n** [comment]
This this appears to be fixed in the upcoming 1.7.19 according to the changelog - close ticket?

**Comment by JohnMica** [comment]
I haven't checked this. I'll comeback later on today/tomorrow with an answer.

**Comment by JohnMica** [comment]
sorry for the delayed response

it works as expected now
