### ISSUE TITLE
Hard wired cache path in GPM.php causes issues with non-standard grav installation

### ISSUE THREAD

**Issue by makuhama** [getgrav/grav#3410]
Follow-up to https://github.com/getgrav/grav/issues/3297

I'm the maintainer of [Arch Linux' Grav package](https://aur.archlinux.org/packages/grav/). I tried to package the recently published v1.7.18 but ran into issues when doing tests with `gpm install`. gpm was not able to create `/usr/share/webapps/grav/cache/gpm` - which is understandable from my point of view as the Grav installation via my package makes everything in and below `/usr/share/webapps/grav` owned by root and not writeable by the dedicated grav user `grav`.

IMHO the culprit is line 63 in `GPM.php`. The `Folder::create` statement there assumes the cache folder is located within `GRAV_ROOT` - this is not necessarily true, especially not with the installation created by my package. The statement should be

```php
Folder::create(GRAV_CACHE_PATH . '/gpm');
```

I'm terribly sorry I cannot provide a PR for this. I currently have no access to my packaging and testing environment.

**Comment by mahagr** [comment]
@makuhama Should be fixed in above patch. :)

**Comment by mahagr** [comment]
Can you apply patch to it in the package to test if it works (and get the updated package out)?

**Comment by makuhama** [comment]
@mahagr I've already extended the packaging instructions (see [grav.patch](https://aur.archlinux.org/cgit/aur.git/tree/grav.patch?h=grav)) to apply the suggested patch. My tests showed that the issue was solved this way. The package is out since Wednesday evening. Thanks for fixing this (so I can follow upstream more closely again with v1.7.19).

**Comment by mahagr** [comment]
Just make sure you're not using GRAV_CACHE_PATH as you suggested, it'll not really work. :) Well.. it does.. in your case, but breaks the others.
