### ISSUE TITLE
@data-options on plugin's blueprints caused error on gpm

### ISSUE THREAD

**Issue by akhyarrh** [getgrav/grav#342]
Steps:
- install smileys plugin version 1.2.0 (`bin/gpm install smileys`) or [download](https://github.com/Sommerregen/grav-plugin-smileys/archive/v1.2.0.zip) and extract to `user/plugins`
- go to Grav's root, open terminal, run `bin/gpm index`
- Enjoy the error message

This error caused by `@data-options` on Smileys's blueprints.yaml (line 67).

**Comment by flaviocopes** [comment]
The error is caused by the `\Grav\Plugin\SmileysPlugin::getSmileyPacks` execution, triggered by `@data-options`.

I think it's too early to call the debugger, which might not be initialized yet at that point when running `bin/gpm index`, and it gives an error. Filing a PR on the Smileys Plugin.
