### ISSUE TITLE
Tags or Category separator, who generate taxonomy list?

### ISSUE THREAD

**Issue by Deight8** [getgrav/grav#3420]
I cant find the file whare is generate the taxonomy list if i show page tags for example with this: 

```
{% if page.taxonomy.tag %}
    {% for tag in page.taxonomy.tag %}
    {{ tag }}
    {% endfor %}
{% endif %}
```

And i have tag like this:

`Alfa Beta Gama`

I want put the separator for this:

`Alfa, Beta, Gama`

Knows this someone?

Thank you guys!

**Comment by pamtbaau** [comment]
@Deight8, To ease the workload on  the core development team and allow them to concentrate on"real" issues, there is a dedicated forum where Grav users can post the "how to"/"beginner" questions: [Grav Community Forum](https://discourse.getgrav.org/)

You might consider closing your recent questions and re-post them on the forum.

**Comment by Deight8** [comment]
Mnohokrát děkuji za pomoc. Mám dotazy smazat?

**Comment by pamtbaau** [comment]
Please have the courtesy to use the lingua franca of the internet: English.
