### ISSUE TITLE
Error loading form page when cache is turned on

### ISSUE THREAD

**Issue by bugz313** [getgrav/grav#3421]
I have a form on a page. When the cache is turned on I get this error when loading the page from cache:
![Crikey-There-was-an-error-](https://user-images.githubusercontent.com/5494116/129037369-b828e6d4-b1f3-4b83-b145-49d44e9ee369.png)
If I turn cache off it works fine.
The cache_enable is set to false on this page but it makes no difference.

PHP Version 7.4.22
Grav version 1.7.17
From plugin v. 5.0.3

After some debugging I found that the problem is here:

```
public function getTmpDir(): string
{
    return $this->folder && $this->uniqueId ? "{$this->folder}/{$this->uniqueId}" : '';
}
```

In FormFlash.php because the uniqueId property is null.

**Comment by mahagr** [comment]
This has already been fixed for upcoming version, here: https://github.com/getgrav/grav/commit/c9159695aa0390bcc8d4970bdfde29337e98aec7
