### ISSUE TITLE
MIME Type Checking Inconsistencies from v1.7.14+

### ISSUE THREAD

**Issue by Verequies** [getgrav/grav#3422]
From Grav 1.7.14, I am unable to upload Zip files from Windows. This is very strange because uploading the same file works on Linux and macOS. I have narrowed it down to this [commit](https://github.com/getgrav/grav/commit/f8106a48ae442f75573c43c3ee5425f818164b13#diff-44e2dd232cd70c31a9b206d442c01aa528efa78df457a4e83a1fdb5372dcaba3R187). Specifically the mimeTest code.

These checks seem inconsistent as the same file on Linux and macOS present as 'application/zip' while on Windows present as 'application/x-zip-compressed'. I have had no choice but to comment these lines out on my server so that my users can upload Zip files from Windows.

**Comment by mahagr** [comment]
Hmm. It looks like we may want to add support for multiple mime-types per file extension.

https://www.php.net/manual/en/function.mime-content-type.php has some ideas on how to do this.

**Comment by mahagr** [comment]
It's not trusting the browser, instead, there is double check that both the extension and mime match.

Anyway, both the reported issues have been fixed by the change.
