### ISSUE TITLE
Twig function `http_response_code` doesn't do anything

### ISSUE THREAD

**Issue by Sailoriae** [getgrav/grav#3437]
Hello ! ^^
First of all, thank you very much for Grav, it's a really great CMS ! 😀
I don't know if it's a real problem, but the Twig function `http_response_code` doens't seems to work. HTTP status code 200 is always sent.
I use it this way :
```
{% do http_response_code(404) %}
```
I'm using Grav v1.7.20, and I tested with most of my plugins disabled.
Thank you in advance and have a nice day !

PS : The following instruction works :
```
{% do page.modifyHeader('http_response_code', 404) %}
```

**Comment by rhukster** [comment]
I just tested and it works fine.. However you need to put it in primary twig template or something like `templates/partials/base.html.twig`.  To make it work in a Grav page, you would need to enable twig processing, and set `never_cache_twig:  true` or the contents will be cached and the twig will not run after the first time:

```markdown
---
title: Twig Testing
never_cache_twig: true
process:
    twig: true
---

{% do page.modifyHeader('http_response_code', 404) %}
```

**Comment by Sailoriae** [comment]
Hello, 
Thank you very much for your explanation. ^^
Have a nice day !
