### ISSUE TITLE
HHVM-Error in "Notepad"-Skeleton's Template File "partials/blog_item.html.twig"

### ISSUE THREAD

**Issue by mewcrazy** [getgrav/grav#344]
I get a wierd error and google gives me only the hhvm source code as a result :grinning:

Okay it works now, just the template "blog_item.html.twig" throwed the error somehow, after emptying the template my page was running fine again. Now I'm going to see what line/function exactly is causing it. Btw: It was a skeleton of the Grav Site (Notepad Skeleton), so maybe this should get fixed.
found:

**blog_item.html.twig**
```html
        {% elseif truncate and page.summary != page.content %}
            <p>{{ page.summary }}</p>
            <p><a href="{{ page.url }}">Continue Reading...</a></p>
        {% elseif truncate %}
            {% if page.summary != page.content %}
                <p>{{ page.content|truncate(550) }}</p>
            {% else %}
                <p>{{ page.content }}</p>
            {% endif %}
            <p><a href="{{ page.url }}">Continue Reading...</a></p>
```

Those 2 else if's throw the following error:
```
An exception has been thrown during the rendering of a template ("Setting DOMNode derived property 'preserveWhitespace' with the incorrect casing") in "partials/blog_item.html.twig" at line 49.
```

**Comment by flaviocopes** [comment]
Most probably a `truncate`-related issue

**Comment by rhukster** [comment]
Should be sorted in next release.
