### ISSUE TITLE
Since upgrading to Grav 1.7.21, can no longer save new or existing pages. Get crash with 'Call to a member function header() on array' error

### ISSUE THREAD

**Issue by fseesink** [getgrav/grav#3442]
I thought everything was cleared up regarding issue #3432 .  And at least that bug DOES appear fixed after I upgraded from Grav 1.7.20 to Grav 1.7.21.

But then this morning I tried to save a change to a page and suddenly got slammed with an
> Error
Call to a member function header() on array

Thought it was just a goof so reloaded the page in the browser, then tried again.  Nope.
Tried creating a new page.  Same thing.  Doesn't matter what directory I put it in.  ANY attempt to save a page, new or existing, results in the same error.

This is not a particularly fancy setup, so I'm scratching my head as to what's going on.  The error is a bit generic, but not sure what information to provide here.

So please specify what I can provide and will do so.

**Comment by rhukster** [comment]
Is this on a custom page type? if so what does your blueprint look like.

**Comment by mahagr** [comment]
Can you try this fix: https://github.com/getgrav/grav/commit/ba19ce4919922b98d3aab0d115f0fd770786c7ab

**Comment by fseesink** [comment]
@rhukster Not a custom page type.  Basic `blog item` page.

@mahagr How exactly would I go about doing this?  I'm not pulling Grav via Git.  This is stock install doing updates via Admin Panel.

Currently we're talking Grav 1.7.21, Admin Panel 1.10.21, and all other plugins up-to-date.

**Comment by fseesink** [comment]
If I simply open an existing blog item page (I have a separate folder for draft posts) and then try to save it, same error.

Wish there was a simpler way to show this here with copy/paste from the error page.  But it seems to lack line numbers/etc.  Hopefully this screenshot will do it some justice:
![image](https://user-images.githubusercontent.com/48991/133472409-aadd0f4a-9102-4855-8861-3c1241657523.png)

Looks like error is occurring on line 134 in `./grav/user/plugins/aura/aura.php` if that helps at all.

**Comment by fseesink** [comment]
To be clear, I'm using rather simple pages at this point.  Not even using a modular template or anything.  This is pretty much open editor in Admin Panel to type some words, click [Save].

The only thing that is even slightly unique is that I'm not using the default Quark theme but rather the Gantry5 Helium theme.  But honestly, beyond that, not exactly pushing any boundaries here.

**Comment by Karmalakas** [comment]
> Looks like error is occurring on line 134 in `./grav/user/plugins/aura/aura.php` if that helps at all.

But Aura uses `getOriginal()`, which should be fixed in @mahagr's referenced [commit](https://github.com/getgrav/grav/commit/ba19ce4919922b98d3aab0d115f0fd770786c7ab). If you could just apply the changes directly, you'd be able to check if they help

**Comment by fseesink** [comment]
Ok, @mahagr and @Karmalakas , edited the 2 .php files in that commit (didn't bother with CHANGELOG.md), basically changing the variable `_original` to `_originalObject`.  And voila!  Yep, now working.  Didn't dig through the source code, but what the?

But yes, I now appear to be able to save pages again.

**Comment by outofcontrol** [comment]
Same error today after upgrading to 1.7.21. Confirming this (https://github.com/getgrav/grav/commit/ba19ce4919922b98d3aab0d115f0fd770786c7ab) fixed the problem.

**Comment by requiem958** [comment]
I got the same error after the upgrade to 1.7.21 and the commit ([ba19ce4](https://github.com/getgrav/grav/commit/ba19ce4919922b98d3aab0d115f0fd770786c7ab)) also fixed the problem. Hope it will soon get into a release.

**Comment by rhukster** [comment]
Plan to get a release out soon...
