### ISSUE TITLE
Admin plugin can't list local installed plugins and themes when it's offline.

### ISSUE THREAD

**Issue by noahmelto** [getgrav/grav#345]
A few days ago I've started testing grav, and when I've manually installed the admin plugin throw exceptions on plugins section or instead the admin plugin can't list local installed plugins and themes. I've started testing below a proxy configuration and later I went offline to test if that is the issue.
@rhukster suggest me to open an issue here to let the team know about it.. I hope that we will achieve an answer!!
The details of the issue are more detailed at the forum on:
http://getgrav.org/forum#!/getgrav/plugin-development:admin-plugin-dashboard-its
I am available for testing everything what you want!!

**Comment by flaviocopes** [comment]
Are you having this problem on Apache or Nginx?

**Comment by noahmelto** [comment]
Apache... Xampp actually...

**Comment by noahmelto** [comment]
Apache... Xampp actually...

**Comment by flaviocopes** [comment]
I think I need you to test something on your environment, because I cannot recreate the issue. Try opening `plugins/admin/classes/admin.php` and in the plugins() method, line 426, try adding some dumps, like

```
public function plugins($local = true)
    {
        $gpm = $this->gpm();
dump($gpm);
        if (!$gpm) {
            return;
        }
dump( $gpm->getInstalledPlugins());exit();
        return $local ? $gpm->getInstalledPlugins() : $gpm->getRepositoryPlugins()->filter(function (
            $package,
            $slug
        ) use ($gpm) {
            return !$gpm->isPluginInstalled($slug);
        });
    }
```

You should see something like

![screen shot 2015-10-05 at 17 35 41](https://cloud.githubusercontent.com/assets/11783388/10285093/95f92eae-6b87-11e5-8a6c-7c8345053bd5.png)

**Comment by noahmelto** [comment]
I already tested that and this is the answer:
![testing-gpm](https://cloud.githubusercontent.com/assets/7748211/10285485/0cd08e68-6b57-11e5-8123-74bdb1353145.png)
any thoughts??

**Comment by flaviocopes** [comment]
In the same file, function gpm(), try

```
    public function gpm()
    {
        if (!$this->gpm) {
            try {
                $this->gpm = new GPM();
            } catch (\Exception $e) {
                dump($e);
                exit();
            }
        }

        return $this->gpm;
    }
```

**Comment by noahmelto** [comment]
![dumping-exception](https://cloud.githubusercontent.com/assets/7748211/10285988/5d74841c-6b59-11e5-92e0-648fcae459de.png)
maybe it's an offline issue after all...

**Comment by flaviocopes** [comment]
Commenting line 216 of `system/src/Grav/Common/GPM/Response.php`, `//throw new \RuntimeException("Error while trying to download '$uri'");`, makes it work?

**Comment by noahmelto** [comment]
![blank-again](https://cloud.githubusercontent.com/assets/7748211/10286498/ff67f3ec-6b5b-11e5-9ecc-3d61c1d18ee7.png)
It is blank again.. and even the logout option doesn't appear!!

**Comment by flaviocopes** [comment]
Did you remove the other exit() calls?

**Comment by noahmelto** [comment]
yes I've removed the ones placed on plugins/admin/classes/admin.php and system/src/Grav/Common/GPM/Response.php.. I forgot anyone??

**Comment by flaviocopes** [comment]
It might crash for other reasons if the Exception is not triggered. Strange thing btw. Happens also if the site is completely offline? Or just through the proxy?

**Comment by noahmelto** [comment]
oops!! without conection has the same error as earlier:
![without-connection](https://cloud.githubusercontent.com/assets/7748211/10287206/c7862fb2-6b5f-11e5-980d-03767a3c9aa0.png)

**Comment by flaviocopes** [comment]
One last try: in `system/src/Grav/Common/GPM/GPM.php, like 40, change the __construct method to

```php
    public function __construct($refresh = false, $callback = null)
    {
        $this->installed  = new Local\Packages();
        try {
            $this->repository = new Remote\Packages($refresh, $callback);
            $this->grav       = new Remote\Grav($refresh, $callback);
        } catch (\Exception $e) {
        }
    }
```

same error?

**Comment by noahmelto** [comment]
sorry for the delay...I had some internet issues... with the try-catch routine the problem was completely solved!!! I even added a new plugin manually and it reconognized as well. Thanks for the attetion, I'm very excited about you creation!! A lot of good thoughts for your team!! If you need to test something about grav please let me help you back, I will please of do it!!!


![it works](https://cloud.githubusercontent.com/assets/7748211/10314451/d3096c5a-6c22-11e5-9886-73f4f8ffea13.png)

**Comment by flaviocopes** [comment]
Ah great we solved this problem! Will push this fix for the next release
