### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by andreaZHrustichelli** [getgrav/grav#3450]
I would like to add my theme to the Grav Repository. It's a theme based on Afterblog2 but more blog oriented (i came from Wordpress)
GitHub page (version 0.9.0):https://github.com/andreaZHrustichelli/theme4grav-afterblog
Demo page: http://www.andrea.rustichelli.name/demo-grav-theme-afterblog/

Thank you
Andrea

**Comment by lisandi** [comment]
looks nice :-)

**Comment by rhukster** [comment]
funny thing about this is that Afterburner is a theme I created for Joomla back in 2013!

https://rockettheme.com/blog/joomla/31-afterburner2-joomla-template

This WordPress theme is just a port of the original from Joomla or perhaps the one I already ported to Grav 7 years ago: 
https://github.com/getgrav/grav-theme-afterburner2

**Comment by rhukster** [comment]
So what does it have that Afterburner2 doesn't?

**Comment by andreaZHrustichelli** [comment]
> looks nice :-)

thank you

**Comment by rhukster** [comment]
Sorry, i've been super lax on this, will be catching up this week.

**Comment by rhukster** [comment]
Added for next GPM update.
