### ISSUE TITLE
Nested lists break content with enabled markdown extra

### ISSUE THREAD

**Issue by wolkyura** [getgrav/grav#3452]
Hello!

I'm using the latest version of Grav and have the next settings in `system.yaml`:

```
absolute_urls: false

home:
  alias: '/home'

pages:
  theme: custom
  markdown:
    extra: true
  process:
    markdown: true
    twig: false

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  releases: stable
  verify_peer: true
```

I noticed the next problem with markdown parsing of nested lists (if `markdown: extra: true`) e.g.:

```
* item 1
* item 2
  * item 2.1
* item 3

... other content here ...
```

The content after such lists disappears.

**Comment by rhukster** [comment]
Just an issue with Parsedown Extra.  It has quite a few 'quirks'.  We don't recommend using it unless you have to.

**Comment by rhukster** [comment]
Actually i tried to recreate this and it works fine for this page:

```md
---
title: Markdown Extra Testing
markdown:
    extra: true
---

* item 1
* item 2
  * item 2.1
* item 3

... other content here ...
```
<img width="1230" alt="CleanShot 2021-09-29 at 10 39 02@2x" src="https://user-images.githubusercontent.com/1084697/135312067-c87aa48d-8dbf-42f2-a89f-e7670126189e.png">
