### ISSUE TITLE
Feature Request: Move index to public folder

### ISSUE THREAD

**Issue by toitzi** [getgrav/grav#3456]
I am new to grav, so sorry if this feature request may seem off.
I noticed, that the index.php is in the root of all files, which seems to be no problem, since most files get rewritten to index.php.

However, if i read the .htaccess correctly, if the file exists, direct access is allowed.
Repository specific files seem to be exclded from it with a deny list.
However, if it happens that a developer forgets to add some custom files to the deny list or it is forgotten at some point, files which are not meant to be viewed can possibly be accessed directly / public.

This could be preventent (and potentially also remove the need of a htacces deny/allow list) by moving the index.php to a "public" folder (kinda like laravel does for example) and set that to the Web-Root.

Altough it was quite easy to archive this by changing just some config variables...the site only runs and i hadn't time to find where this might cause errors.

I thought i might just open a Feature Request issue, since i think this would be an improvement, or would it?

**Comment by rhukster** [comment]
This is actually a big change to how Grav works and would not be a seamless upgrade.  

Moving everything into a relocatable public folder is something we want to do for Grav 2.0.
