### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by numito** [getgrav/grav#3462]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: https://github.com/dfacto-lab/grav-plugin-videoembed
This was an existing plugin that was not working with new version of grav (1.5 and higher) and that I have updated and that is now correctly working.  Might be interesting to add it back to the plugin list.

**Comment by rhukster** [comment]
Sorry, i've been super lax on this, will be catching up this week.

**Comment by rhukster** [comment]
Added for next GPM update.
