### ISSUE TITLE
grav['page']->translatedLanguages() returns wrong data

### ISSUE THREAD

**Issue by saxinte** [getgrav/grav#3465]
### Context:
`$this->grav['page']->translatedLanguages(true);` seems to be wrong in a specific scenario which I'm explaining below. I'd expect to see an Array with the other available translated languages.

### Problem:
`$this->grav['page']->translatedLanguages(true);`is supposed to return an Array with the other available languages for the current page. It seems that when the language does not exist, this Array is wrong and doesn't return the rest of the available pages.

### Scenario:
- Tested with Grav `v1.7.23` and Grav Admin `v1.10.23`.
- Brand new Grav using multi languages setup with `EN`, `ES` and `FR` as languages. Default language is `EN`. 
- Created a `/typography` page where only `ES` and `FR` are available as translated pages. 
- When trying to access `/en/typography`, I would expect Grav to return the following Array when using `$this->grav['page']->translatedLanguages(true);` since those two languages are available:
```
array:2 [
  "es" => "/typography"
  "fr" => "/typography"
]
```
- Although, this is what is returned:
```
array:1 [
  "en" => null
]
```

### What's expected?
I would expect to see the following output even for a language that is not translated. This behaviour was working as expected in the previous version of Grav.
```
array:2 [
  "es" => "/typography"
  "fr" => "/typography"
]
```

#### Language Config
![Screenshot 2021-10-12 at 17 01 13](https://user-images.githubusercontent.com/1248623/136990561-7aab82e6-b40e-4485-b8d2-d207be7a8c7a.png)

#### File and folder structure
![Screenshot 2021-10-12 at 17 01 30](https://user-images.githubusercontent.com/1248623/136990573-2cc751ad-5eb2-4e83-8830-f2e56ce92759.png)

#### Seems right
![Screenshot 2021-10-12 at 16 58 21](https://user-images.githubusercontent.com/1248623/136990060-8de07de5-b954-4f9d-9f92-a0dfe558931c.png)

#### Seems wrong
![Screenshot 2021-10-12 at 16 57 38](https://user-images.githubusercontent.com/1248623/136990075-4cce10d4-fea5-4935-a47a-494058bda66b.png)

Any questions please let me know, thanks!

**Comment by mahagr** [comment]
It is expected behavior. The current page is 404 page (coming from errors plugin), and it doesn't have translations.

Grav 1.6 had really bad behavior for missing translations where it ended up showing the page in "random" language. In Grav 1.7 translations were improved so that it shows 404 by default.

You can still mimic the behavior by setting fallbacks for all your languages. It allows you to better control the fallback languages to better match the most common secondary language skills people may have.

**Comment by saxinte** [comment]
Hello, @mahagr thanks for your response, really appreciated. 

> You can still mimic the behavior by setting fallbacks for all your languages. It allows you to better control the fallback languages to better match the most common secondary language skills people may have.

This is what I'm trying to do, I am relying on `grav['page']->translatedLanguages();` today, which now doesn't seem to be returning the other available languages, because the current page is a 404, like you just explained.

How can I find out what are the other available languages for a current page given that the current language might not be available? Should I use another method?

Thanks for the help! :slightly_smiling_face:

**Comment by mahagr** [comment]
Check the language configuration `Content Language Fallback` and include all the other languages as a fallback to every other language.

**Comment by saxinte** [comment]
Thanks for the quick response 👍 

I'll check it out. I would still need to rely on such a method to fix a broken plugin (we use the `translatedLanguages()` from a PHP Plugin for a different need). 

Do you have in mind another method or way to mimic what `translatedLanguages()` used to do in Grav 1.6 ?

Thanks

**Comment by saxinte** [comment]
Thanks @mahagr but apart from the language configuration in the `Content Language Fallback`, is I need to find out the other translated pages from a given route, in PHP, in a Plugin, how would I achieve that? Can I still rely on `translatedLanguages()`  ?

**Comment by mahagr** [comment]
Fallback should make it work as then the page would exist, although with a different language.

**Comment by saxinte** [comment]
Ok thank you! I think we can close this conversation - I will reach out if we face any additional issues. Thank you @mahagr
