### ISSUE TITLE
Double translations

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#347]
When some strings translated in the language file in `/user/languages` folder and in the `languages.yaml` file inside theme folder then both translations are stored.
For example inside `/use/languages` folder I have the `en.yaml` file with the following content:
```
SITE:
  TITLE: 'Title from user/languages translations'
```
And in theme folder I have `languages.yaml` file containing:
```
en:
  SITE:
    TITLE: 'Title frome theme translations'
```
Then `en.SITE` will contain both translations:
```
array:2 [
  "TITLE" => array:2 [
    0 => "Title from user/languages translations"
    1 => "Title frome theme translations"
  ]
]
```
Is this intended behavior to store both translations and not to overwrite them?

**Comment by rhukster** [comment]
it's semi intentional :)  I didn't want to blindly overwrite an existing translation as there may be a legitimate reason for it.  However, the language code will see the entry is an array, and simply pull the first entry from that array when asked for this string.
