### ISSUE TITLE
Grav v1.7.24 - Admin panel : Big troubles ...

### ISSUE THREAD

**Issue by ValordProd** [getgrav/grav#3477]
Hey all,

I just updated my Grav version from the v1.7.23 to the v1.7.24 and since I did it, I am not able to log into my website administration anymore ...

When I go to www.mywebsite.com/admin there is no field to fill.

Here's what I get :
<img width="637" alt="Capture d’écran 2021-11-02 à 19 58 33" src="https://user-images.githubusercontent.com/70521183/139928629-61719c05-e65d-4241-9422-072a1237447e.png">

What am I supposed to do ? How will I be able to update to the next version if I can't access the admin panel ?
I'm afraid to be stuck here ...

Thanks in advance for your help.

Valord.

**Comment by rhukster** [comment]
Can you try clearing cache from the CLI? 

```
bin/grav clear
```

**Comment by ValordProd** [comment]
Hey @rhukster,

Thanks for your help, I just deleted all the files and folders into the "Cache" folder of my website and it seems to work !

I still don't understand why this happened with that specific version but now I'll know what to do if it happens agains.

Thanks again.
