### ISSUE TITLE
Default language from config is overridden by alphabetical sorting

### ISSUE THREAD

**Issue by mikkosalo** [getgrav/grav#348]
Upgrading to version  0.9.44 breaks getting the default language.

https://github.com/getgrav/grav/commit/b7da95bc361acfa44247e781648ced2863d56730#diff-d77f09a6fba57db4165ea82afa02d571

The sorting made here affects `$this->languages` for the entire class. When no language is set in the URI, chosen language is not the first in config file, but the first language sorted in alphabetical order.

**Comment by flaviocopes** [comment]
Thanks for reporting!
