### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK for "https://getgrav.org/blog.atom".

### ISSUE THREAD

**Issue by christophdoering** [getgrav/grav#3482]
I have no idea
This error happened on OS X and I'm using mamp

**Comment by jenspepie** [comment]
same here

**Comment by paulhibbitts** [comment]
I had this same problem, and after doing a fresh install of MAMP the error no longer occurred.

**Comment by mahagr** [comment]
Please update your certs. :)

**Comment by jenspepie** [comment]
> I had this same problem, and after doing a fresh install of MAMP the error no longer occurred.

Thanks, solved.

**Comment by mahagr** [comment]
@christophdoering As everyone else said, you should update your MAMP which includes updated root SSL certificates.

**Comment by christophdoering** [comment]
Thank you all for your feedback. I found other solutions with the help of a friend. Just in case anyone is interested. 
first by altering my system.yaml
`gpm:
  verify_peer: false`

or by altering the certificate lifespan in MAMP/…/openssl.cnf
`default_days	= 3650			# how long to certify for`

both worked for me.

**Comment by jeffsilverm** [comment]
I did the same thing but to a different key.  I found verify_peer under http.
