### ISSUE TITLE
Built in server to mirror MAMP setup

### ISSUE THREAD

**Issue by jeremycherfas** [getgrav/grav#3484]
Is there any way to get Grav's built in server to use the same settings as when I use MAMP? I ask because I recently upgraded to a new computer and the built-in server no longer works for me. It says PHP zip is not installed, and suggests I download Symfony, but I'm not sure where Symfony should go in this case.

Thanks.

**Comment by rhukster** [comment]
MAMP comes with it's own PHP version.  If you use the path to that MAMP version of PHP as the default, it should match.

**Comment by jeremycherfas** [comment]
In the end I upgraded the OSX version of PHP and included PHPzip, so I am closing the issue.
