### ISSUE TITLE
Flex Objects

### ISSUE THREAD

**Issue by RalfKerkhoff** [getgrav/grav#3487]
Hi,
after updating FlexObjects the scheduler throws errors as follows:

PHP Fatal error:  Uncaught Error: Call to a member function getRoute() on null in /home/example.com/gravsite/user/plugins/flex-objects/flex-objects.php:293
Stack trace:
#0 /home/example.com/gravsite/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\Plugin\FlexObjectsPlugin->onPagesInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#1 /home/example.com/gravsite/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event))
#2 /home/example.com/gravsite/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event))

Cheers
Ralf

**Comment by mahagr** [comment]
See https://github.com/trilbymedia/grav-plugin-flex-objects/issues/151
