### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by matthiez** [getgrav/grav#3489]
Hi,
I would like to add my new plugin to the Grav Repository.
[grav-plugin-sms77](https://github.com/sms77io/grav) allows making text-to-speech calls or sending SMS whenever a form gets submitted.

Thanks for evaluating.

**Comment by pamtbaau** [comment]
I've taken the liberty to do a quick review of your plugin.

Please have a look at the Grav 1.7 guidelines about plugins:
- [Use composer autoloader](https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#use-composer-autoloader)
- [Plugin/Theme Blueprints (blueprints.yaml)](https://learn.getgrav.org/17/advanced/grav-development/grav-17-upgrade-guide#plugin-theme-blueprints-blueprints-yaml)

An easy way to create a compliant plugin skeleton is to install plugin Devtools and create a new plugin using command:
```
$ bin/plugin devtools new-plugin
```

**Comment by rhukster** [comment]
Added for next GPM update.
