### ISSUE TITLE
Remove security and privacy issue `Gravatar`

### ISSUE THREAD

**Issue by Rotzbua** [getgrav/grav#3491]
## Reason

Gravatar is not a reliable service. There was a data leak where more than 100 million(!!) emails were leaked.

References:
* https://monitor.firefox.com/breach-details/Gravatar
* https://haveibeenpwned.com/

Gravatar is a security risk and privacy issue.

It also causes problems when users want to use new security features such as CSP.

It should be removed in my opinion.

## Current usage

It is used as default for avatar images.

At core it is just **one** line of code to change:
https://github.com/getgrav/grav/blob/42084ea0cb5f3aebcb385a1a797af72000b6d1e1/system/src/Grav/Common/User/Traits/UserTrait.php#L180

## Solution

Use an self hosted default fallback avatar image or return empty string.

**Comment by froschdesign** [comment]
Regardless of security issues, the use of external services should always be optional.

**Comment by rhukster** [comment]
We've added Multiavatar... right now Gravatar is still default.  We'll switch to Multiavatar as default in Grav 1.8 when we can warn people about the change and how it impacts them.
