### ISSUE TITLE
Blueprint Fieldset Add ID fields to make it targetable [Feature Request]

### ISSUE THREAD

**Issue by spamhater-grav** [getgrav/grav#3492]
With backend blueprints I wonder if the Fieldset code could be updated to include the ID parameter to help with targeting 
<div class="form-fieldset "  
in the user/plugins/admin/themes/grav/templates/forms/fields/fieldset/fieldset.html.twig (line 4) 

I my workaround is to use the `classes: hidden xyz`  and use the xyz class to be able to able to use js queryselector to target  

<div class="form-fieldset hidden xyz" >

to be able to remove **hidden xyz** and make the item visible and then also hide and reclaim screen space if there is no need for the toggle / option and also reduce inline code on pages (more on demand).

There is assignment of **ID** to the sub checkbox code but not above so hard to target. 

This would be useful on larger blueprints to toggle/hide elements based on with a toggle button.
ie . Toggle Button = Slider Enable / Disabled
then based on the option can then show/hide the fieldset with options for js / slider / etc

thus making the ability to control the output and show fields which can help people with customisable field and  reduced the visual size blueprints and only display relevant options when enabled.

I understand the admin blueprints are not currently dynamic and this could be open a can of worms, but the ability to have this in the core of grav including javascript to toggle (show/hide) items easily which can be passed from the blueprint brings a lot of potential.

Seems a really good use of reusable code especially in to imported blueprints 

With assistance from Ricardo, he has helped me manually, create a blueprint, which then adds an event which then triggers the hide and show of a toggle, was quite a long and hard process (not a developer) which there probably many ways where the form fields can be expanded with a simple show / hide ... 

but compared to other fields which able to be given id / name / target as standard but not the fieldset 

Open to discussion about it ...  Sorry I am a bit dyslexic so might not be as clear as it is my head !

**Comment by mahagr** [comment]
You can already do that for many of the fields by adding `id: xxx` to the field.

**Comment by spamhater-grav** [comment]
Hi Mahagr, thanks for your response 
Yep when I read the documentation I saw the id: xxx was a value, but seem strange whilst it was omitted by fieldset , especially due to being a parent container item.

but now as support from Ricardo on Discord, he has shown by the 

I am not that familiar with dom objects and javascript as I still on learning curve and  having to create a blueprint hook and a bit of .js .  The concept of parentElement was not know, so I was thinking how can I access something which is inner has an id and not the container element, in this case (fieldset)

const fieldset = document.querySelector('[id="fieldset_collapsible_header.myfieldset"]').parentElement;

where I would be trying to find something in the parent item to hook to.

Then the second part of this, is probably all of what I was trying to achieve probably already exists within grav admin itself.

So fighting off a massive learning curve / over thinking that probably all ready exists and could be done from the core / admin plugin.

Thanks for replying and confirming my original way of trying to tackle it with your info.
:)
