### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by rblinde** [getgrav/grav#3499]
Hi all,

I would like to add my plugin to the Grav Repository. You can find the plugin here: [grav-plugin-html-minifier](https://github.com/rblinde/grav-plugin-html-minifier). The plugin minifies the HTML output and can store it in cache for future use.

Thanks for evaluating.

**Comment by pamtbaau** [comment]
Had a quick look at the plugin.

- Checking if plugin is enabled in `onPluginsInitialized` isn't needed. Plugin will be ignored anyway when not enabled.

**Comment by rblinde** [comment]
Thanks for evaluating the plugin. I have removed the unnecessary check in `onPluginsInitialized`.

Enjoy the holidays!

**Comment by rhukster** [comment]
just back from holidays, will add this soon.

**Comment by rhukster** [comment]
This needs a release or it will not be picked up by GPM. See here: https://learn.getgrav.org/17/advanced/grav-development#theme-plugin-release-process

**Comment by rblinde** [comment]
I have published a release.

**Comment by rblinde** [comment]
@rhukster, issue closed as I have seen it on GPM
