### ISSUE TITLE
Grav URL with variable not passing as expected within Twig template

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#350]
I've been using Grav's super-handy ability to pass variables via URL to selectively display content using if statements within a Twig template. For example http://cmpt-363-153.hibbittsdesign.com/home/week-01 vs. http://cmpt-363-153.hibbittsdesign.com/home/week-01/displaypagecontentonly:true

This has been working fine except in one case. If I include a URL such as href = "../ux-techniques-guide/displaypagecontentonly:true" within a Twig template I seem to get a 404 error. Please let me know if further details are required.

Thanks for looking into this,
Paul

**Comment by rhukster** [comment]
Can you please provide a sample of the exact Twig you used?

**Comment by paulhibbitts** [comment]
Sure thing, here is the Twig I've got:

```
{% if not grav.uri.param('displaypagecontentonly') %}
 <p>Still wanting more? Explore the <a href="../ux-techniques-guide">UX Techniques Guide</a> or the course <a href="../resources">Resources</a>.</p>
{% else %}
 <p>Still wanting more? Explore the <a href="../ux-techniques-guide/displaypagecontentonly:true">UX Techniques Guide</a> or the course <a href="../resources/displaypagecontentonly:true">Resources</a>.</p>
{% endif %}
```

Here is the odd thing: when displaypagecontentonly is false the resulting URL works, and is http://localhost:8888/cmpt-363-153-website/ux-techniques-guide but when I add the variable to it the base URL changes to http://localhost:8888/cmpt-363-153-website/home/ux-techniques-guide/displaypagecontentonly:true (for some reason /home seems to be added.

**Comment by rhukster** [comment]
Ok, after looking into this I think the problem is just in your relative paths.  When you create a relative path like this your not actually in that folder, its relative from the root. 

Better to get the actual page location with `page->find()`:

```
{% if not grav.uri.param('displaypagecontentonly') %}
 <p>Still wanting more? Explore the <a href="../ux-techniques-guide">UX Techniques Guide</a> or the course <a href="../resources">Resources</a>.</p>
{% else %}
 <p>Still wanting more? Explore the <a href="{{ page.find(/ux-techniques-guide)/displaypagecontentonly:true">UX Techniques Guide</a> or the course <a href="{{ page.find('/resources')/displaypagecontentonly:true">Resources</a>.</p>
{% endif %}
```

**Comment by paulhibbitts** [comment]
As discussed on Gitter, quotes and a .url needs to be added to find statements. So, revised fix is:

```
{% if not grav.uri.param('displaypagecontentonly') %}
<p>Still wanting more? Explore the <a href="{{ page.find("/ux-techniques-guide").url }}">UX Techniques Guide</a> or the course <a href="{{ page.find("/resources").url }}">Resources</a>.</p>
{% else %}
<p>Still wanting more? Explore the <a href="{{ page.find("/ux-techniques-guide").url }}/displaypagecontentonly:true">UX Techniques Guide</a> or the course <a href="{{ page.find("/resources").url }}/displaypagecontentonly:true">Resources</a>.</p>
{% endif %}
```

		{% if not grav.uri.param('onlydisplaypagecontent') %}
		 		<p>Still wanting more? Explore the <a href="{{ page.find("/ux-techniques-guide").url }}">UX Techniques Guide</a> or the course <a href="{{ page.find("/resources").url }}">Resources</a>.</p>
			{% else %}
				<p>Still wanting more? Explore the <a href="{{ page.find("/ux-techniques-guide").url }}/onlydisplaypagecontent:true">UX Techniques Guide</a> or the course <a href="{{ page.find("/resources").url }}/onlydisplaypagecontent:true">Resources</a>.</p>
			{% endif %}
