### ISSUE TITLE
[add-resource] New Theme Telephasic by HTML5Up

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [getgrav/grav#3506]
Hello.

Here is the link to the github repository ([https://github.com/pmoreno-rodriguez/grav-theme-telephasic](https://github.com/pmoreno-rodriguez/grav-theme-telephasic)) for the HTML5Up Telephasic Theme, ported to Grav.
It is a very fast theme, with a very good performance and to which I have included the full functionality of Blog.

See demo here: [http://telephasic.juanvillen.es/](http://telephasic.juanvillen.es/)

Hope you enjoy it and can add it to Grav's theme repository.
Thank you.

**Comment by rhukster** [comment]
just back from holidays, will add this soon.

**Comment by rhukster** [comment]
This needs a release before it will show up in GPM: https://learn.getgrav.org/17/advanced/grav-development#theme-plugin-release-process

**Comment by pmoreno-rodriguez** [comment]
Hi @rhukster, I've just added the first release of Telephasic theme.

**Comment by pmoreno-rodriguez** [comment]
Hi.

Is there any problem with theme to be published into Grav repository. I'd like to have any feedback to solve possible issues.

Thanks so

**Comment by w00fz** [comment]
I added this back in the repository, keep an eye on it within the next hour and it should appear if everything is setup correctly.

I can tell your other theme https://github.com/getgrav/grav/issues/3481 is still missing a release, that one has not been added. Please fix that and let us know in the #3481 issue
