### ISSUE TITLE
Grav 1.7.26 crashes on Windows with basedir in place

### ISSUE THREAD

**Issue by EPinci** [getgrav/grav#3508]
Hello,

I have a Windows Server with PHP 7.4.27 and the basedir configuration in place as follows:
`open_basedir = "C:\Inetpub\temp;D:\Inetpub"`

Copied the grav+admin release 1.7.26 in a "grav" folder and used the provided web.config file.
Trying to call grav from the webserver results in:

`UnexpectedValueException
GlobIterator::__construct(): open_basedir restriction in effect. File(D:/Inetpub/WWWRoot/grav/cache/problem-check-*) is not within the allowed path(s): (C:\Inetpub\temp;D:\Inetpub)`

Note that the reported file path is, indeed, within the scope of the basedir configuration.

Could this be a bug?

**Comment by rhukster** [comment]
Is this something that just started happening with Grav 1.7.26 but worked before? I don't recall that anything changed with Grav that would effect this.  

The simplest solution is to set open_basedir empty:

```
open_basedir = ""
```

or add the `D:/Inetpub/WWWRoot/grav` folder to the list.

**Comment by mahagr** [comment]
To me, it looks like there shouldn't be any issues with the path. Could the issue be related to GlobIterator?

**Comment by EPinci** [comment]
@rhukster, this is a fresh installation trying grav for the first time.
I cannot clear the open_basedir setting as a security measure.
Explicitly adding the path to the open_basedir or fiddling with the direction of the slash, however, still results in the same error.

Based on the stack trace I get, looks like the issue is in the "Problems" plugin where the GlobIterator returns the UnexpectedValueExecption in \grav\user\plugins\problems\problems.php:95
It appears to me that the plugin tries to look for... problems... before the PHP does and traps the error before it occurs to show the stack trace?

Interestingly enough, entirely removing the plugin results in a "successful installation"... (!).

**Comment by rhukster** [comment]
I'm not sure what to suggest other than trying another version of PHP? Seems to be a specific PHP issue on your machine. Not really a Grav issue.

**Comment by EPinci** [comment]
Without the "problems" pluging I can get Grav to run.
The only other place where GlobIterator is used is in the backup (…\system\src\Grav\Common\Backup\Backups.php:161)  so hitting the admin/tools page still triggers the error but I can give it a test spin.

I just upgraded my PHP from 7.4.27 to 8.1.1 - same behavior.
With a little digging, according to https://bugs.php.net/bug.php?id=65069, this appears to be an unfixed Windows-specific issue (?) - bummer.

**Comment by rhukster** [comment]
GlobIterator is a core PHP function so yah, it's not going to be just Problems plugin (which is not required to function).  As this is localhost and for development, i think it's pretty safe to remove the `open_basedir` setting.  I always clear that out.. for local development it's a pain.
