### ISSUE TITLE
http client

### ISSUE THREAD

**Issue by ranjit-git** [getgrav/grav#3509]
Does grav has built in api/method to fetch remote url response ?
Ex: i want to fetch http://example.com response with grav built in http client . is it possible?

**Comment by mahagr** [comment]
We are using this library: https://symfony.com/doc/current/http_client.html

So it should be easy enough...

**Comment by w00fz** [comment]
To a little bit more context to the answer above, you can use Grav's API that wraps the library mentioned above.

An example would be:

```php
$client = Client::getClient();
$response = $client->request('GET', 'https://example.com');
```

You can also use callbacks and set headers. More details can be found in the Client class [Common/HTTP/Client](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/HTTP/Client.php).

Hope this helps a bit more :)
