### ISSUE TITLE
Support for relative path

### ISSUE THREAD

**Issue by rolfjoseph** [getgrav/grav#351]
To integrated a url to other programm of the same server, i need the support for relative path. The internal path works, an external path works, but a path as follow dosn´t works:

./myotherprogramm
../myotherprogramm

It´s for linking to the other programm on the same server.

 I hope for support for this enhancement.

**Comment by rhukster** [comment]
This might be related to #350. 

Are you trying this in a markdown link or via Twig?

**Comment by rolfjoseph** [comment]
Sorry, a have forgotten, it´s the linking path at the admincenter. Not the same as issue 350.

**Comment by rhukster** [comment]
I'm not really following then, it really depends on where your linking from. Can you show me an example I can see in my browser?

**Comment by rolfjoseph** [comment]
It´s to set at the admincenter a link as follow path:

root/openwebsoccer/
root/grav/

At this time i have to integrade the hole struktur auf grav into the openwebsoccer linke this:

openwebsoccer/system
openwebsoccer/user

The index.php is from the openwebsoccer and the grav index.php ist renamend to portal.php.

**Comment by rhukster** [comment]
Sorry i'm still struggling to understand :)

1) admincenter is Grav admin plugin?
2) where/how did set the link, not sure what you mean here
3) openwebsoccer is what? That Grav or something else?
4) are you trying to link between the two sites?

A URL would **really** help

**Comment by rolfjoseph** [comment]
1) yes
2) page edit -> advanced -> Folder Name
3) openwebsocccer is https://github.com/rolfjoseph/OpenWebsoccer
4) yes from the grav page home with a link to the openwebsoccer

I know i can set the real URL to the openwebsoccerpath ( mywebspace.com/openwebsoccer/ ) , but it seems to be a preset for all openwebsoccer installations.

Have a make this issue better at getgrav/grav-plugin-admin ?

**Comment by rolfjoseph** [comment]
It works now properly. http://openwebsoccer.mygoodpage.org/grav/
