### ISSUE TITLE
Collection "order: manual". What is use-case?

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#3513]
In the docs, it is mentioned that a collection can be ordered by `manual`, which refers to a field `order_manual` in the frontmatter of the page at hand.

I'm having difficulty seeing the added value over `content.order.custom`.

Would you mind providing a use-case and examples (frontmatter, php and Twig) for using `manual` instead of `content.order.custom`?

I've also found some "unexpected behaviours", but these might be solved when I get more understanding of the use-case and samples.

**Comment by mahagr** [comment]
It's just an alias for ordering by `default` with `content.order.custom`. Basically what happens is that collection gets first default ordering and custom list gets moved to the top.

**Comment by mahagr** [comment]
Yup, your code says that it should ignore `order_manual` and use the ordering you specify instead. You need to pass the manual ordering into the options as `page.header.content` is only used if you do not set the options. To options, you can either pass the property name from the page header (such as `content`) or use a custom configuration ignoring the defaults.

**Comment by mahagr** [comment]
You are right, after some investigation, it looks like the `order_manual` is leftover from backward compatibility and should never be used. It just messes up collections, especially if you want to use multiple collections.

The proper way to write the code is this:

```yaml
---
content:
  items: '@self.children'
  order:
    dir: asc
    custom:
      - child2
      - child3
---
```

And when using it in Twig:

```twig
{% set mycollection = page.collection('content') %}
```

or

```twig
% set options = page.header.content|merge({
  order: page.header.content.order|merge({ dir: 'desc' })
  })
%}

{% set mycollection = page.collection('content') %}
```

**Comment by pamtbaau** [comment]
I've just updating my post to make it a bit more clearer and ease the discussion by providing numbers to different uses-cases...

In my Twig examples (4,5,6), there is no local collection definition in frontmatter, only `order_manual`. Twig defines a fresh collection.

- Your first frontmatter example just works fine as expected.
- > BTW: order.by: manual is alias to default.
    - Yes, I've seen in `Page` that `manual` and `default` use the same switch path.
- Your first Twig example is using an existing definition in frontmatter and, I believe, parameter `'content'` isn't needed, unless more collections are being defined in frontmatter. Right?
- Your second Twig example again extends an existing collection definition in frontmatter. All my Twig examples are fresh collection definition.
  Interesting override/extension of definition in frontmatter BTW

Going forward...

- Should all references to `manual` be removed from the section [Ordering Options](https://learn.getgrav.org/17/content/collections#ordering-options) in the docs?
- By the way, section 'Ordering Options' is now part of section 'Taxonomy' which, I think, is incorrect. Same holds for 'Date Range', 'Multiple Collections' and 'Collection Object Methods' which should all be separate section because they are not specific to 'Taxonomy'.

**Comment by mahagr** [comment]
Yeah, I think we need to start removing those `order_manual` from the docs as well as from the page blueprints (mark deprecated there, too, and make sure the new way is offered instead).

My second example just showed a way to define the collection to be used, using the default value. So it's not needed, but shows an example of why `order_manual` should not be used -- it just doesn't work if you use multiple collections.

PS: I slightly modified the docs to fix the title level and adding deprecated to the manual ordering.
