### ISSUE TITLE
Pipeline support for modern JS ES modules and modulepreload

### ISSUE THREAD

**Issue by w00fz** [getgrav/grav#3516]
Currently pipeline is not compatible with the `<link rel="modulepreload" href="file.js">` and the `<script type="module" src="file.js>`.

Grav should perhaps introduce an `assets.addLink()` method that allows to pipeline the scenario of `modulepreload`, by pipelining together all the assets in one head entry. Alternative, and perhaps better, would be if `assets.addJs` supported the `rel: 'modulepreload'` accoringly, just like `addCss` takes care of the css files.

The other issue comes from the wrong concatenation of `<script src="">` and `<script type="module" src="">` assets under the same pipeline roof, however these should be distinct header entries if the `type` is specified. The issue comes from the fact that `type="module"` is treated by the browser differently than the default script javascript type.

Open for discussions and further investigations.

References:
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-type
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#applying_the_module_to_your_html

**Comment by mahagr** [comment]
@rhukster It would have been nice if you had included the issue into the commits you made.

c962201baead34427a274d0d64b2188869376ada
756b088adae796645dd04dd7374fcc1b9cc4a8a5
8767bfb9b0ba9c2c467093e3a604be639f6b795a
99ceb40c5ff516044d7668014581fd8f552c1a13
3febaaa80239f283717cc74c65e37df6295e4c0b
f9fcdd6c5187fe46a38788d84b7747a52fa8d504
7bb8d10b2240fd589502dc6d76d27b7dc2fd5db4
2ac38d39ea33d5eaef0f67db99a1f93df83544dd
