### ISSUE TITLE
[Markdown Extra] Error when adding class attribute into a markdown file

### ISSUE THREAD

**Issue by Ideneal** [getgrav/grav#352]
Hi everyone,
I'm using grav v0.9.45, I added a css class into a nested image in a link but this feature not work very well... the css class is showed near the image as a link insted of be setted as a class attribute. When I worked on previous version (I don't remember which) it worked.

this is my code:
```markdown
[![image](image-path.jpg) {.img-class}](link)
```

Some idea about the problem?
Thank you

**Comment by flaviocopes** [comment]
Just tried, it works. You need to enable Markdown Extra in `system.yaml` (or through the Admin Plugin), by default it's disabled.

**Comment by Ideneal** [comment]
The markdown extra was enabled.

This is the configuration within the system.yaml file
```markdown
pages:
    theme: stylish
    markdown_extra: true
    process:
        markdown: true
        twig: false
```

**Comment by flaviocopes** [comment]
If `pages.markdown.extra` is set, it overrides `pages.markdown_extra`, which is deprecated.

So also check that:

![screen shot 2015-10-12 at 20 27 00](https://cloud.githubusercontent.com/assets/11783388/10435335/a08044f0-711f-11e5-8588-519351b1c219.png)

**Comment by Ideneal** [comment]
Yes it's this...I had the previous configuration which is deprecated.
Thank you so much Flavio ;)

**Comment by eightyfive** [comment]
Thanks! This should be changed in the default scaffold where config is (`system.yaml`):

```
pages:
   markdown_extra: true
```

Instead of:


```
pages:
   markdown:
      extra: true
```

**Comment by flaviocopes** [comment]
Why do you think so? `pages.markdown_extra` is deprecated, use `pages.markdown.extra` instead.

**Comment by eightyfive** [comment]
I don't understand I am just saying this should be changed in the official antimatter theme, cause... It is deprecated. So why leaving a deprecated setting in the very own getgrav most popular scaffold/theme?

**Comment by flaviocopes** [comment]
Ok I was thinking you were referring to the default system.yaml, as you didn't mention Antimatter I didn't "link" to it.

Yes, that most probably needs to change as well.
