### ISSUE TITLE
Future2021 theme in Grav Repository is wrong linked

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [getgrav/grav#3524]
Hello.

The Future2021 theme recently uploaded to the Grav repository is mislinked. It is now linked to a fork of grav-theme-future in my repository, however it should be linked to this repository:

[https://github.com/pmoreno-rodriguez/future2021](https://github.com/pmoreno-rodriguez/future2021)

I just uploaded all the files to regenerate the repository as it was. And I've numbered the version number one, not to confuse it with the old Future theme.

Thank you.

**Comment by w00fz** [comment]
I updated this but for the future please follow Grav's nomenclature standard `grav-theme-<your_theme_name>`.

Thanks!

**Comment by pmoreno-rodriguez** [comment]
Updated Future2021 to grav-theme-future2021
