### ISSUE TITLE
Incorrect values returned to the form in the Page Security tab

### ISSUE THREAD

**Issue by petira** [getgrav/grav#3525]
If you enter Page Authors in the Security tab, it will be saved correctly in the frontmatter:

```
permissions:
    authors:
        - author1
        - author2
        - author3
```

but incorrect values will be returned in Normal mode:

```
Page Authors:
        - 'author1,author2,author3'
        - 'author1,author2,author3'
        - 'author1,author2,author3'
```

These values will be saved the next time you send form:

```
permissions:
    authors:
        - 'author1,author2,author3'
        - 'author1,author2,author3'
        - 'author1,author2,author3'
```

etc.

**Comment by w00fz** [comment]
Good catch, thanks. I also transferred the issue here in getgrav/grav since the fix was here.
