### ISSUE TITLE
New themes added to the repository are not displayed in the admin

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [getgrav/grav#3526]
Hello.

The latest themes, Telephasic and Future2021, added to the Grav repository are displayed in [https://getgrav.org/downloads/themes](https://getgrav.org/downloads/themes), but not in the Themes admin section.

Why?. Do I have to do something else?

**Comment by w00fz** [comment]
You need to `bin/gpm index -f` to refresh your repository, or go in Admin -> Themes -> Check for updates, to refresh the cache, or wait 24hrs and it will clear itself.

This is documented under the GPM section: https://learn.getgrav.org/17/cli-console/grav-cli-gpm#how-does-it-work
