### ISSUE TITLE
Grav 1.7 Installation fails because of undefined method in Grav-61f81d0d41083

### ISSUE THREAD

**Issue by eurokrl** [getgrav/grav#3532]
Almost the same issue as in #3523 , this time it's not the `Grav-61f6b713f0bb9` folder, but `Grav-61f81d0d41083`.
Tried w/ old & fresh install of `Grav 1.6.31` and `selfupgrade` & `direct-install <LatestVersionURL>`.

I am trying to update to the latest Grav release 1.7.29 from (originally 1.6.24, while troubleshooting today updated to) 1.6.31 (using direct-install.
But, while trying to install, it gives me the following error:

> Installing package... [31-Jan-2022 18:31:57 Europe/city] PHP Fatal error: Uncaught Error: Call to undefined method Grav\Common\Utils::basename() in /var/www/virtual/name/html/tmp/Grav-61f81d0d41083/grav-update/system/src/Grav/Installer/VersionUpdate.php:29
> Stack trace:
> #0 /var/www/virtual/name/html/tmp/Grav-61f81d0d41083/grav-update/system/src/Grav/Installer/VersionUpdater.php(126): Grav\Installer\VersionUpdate->__construct('/var/www/virtua...', Object(Grav\Installer\VersionUpdater))
> https://github.com/getgrav/grav/pull/1 /var/www/virtual/name/html/tmp/Grav-61f81d0d41083/grav-update/system/src/Grav/Installer/VersionUpdater.php(38): Grav\Installer\VersionUpdater->loadUpdates()
> https://github.com/getgrav/grav/pull/2 /var/www/virtual/name/html/tmp/Grav-61f81d0d41083/grav-update/system/src/Grav/Installer/Install.php(239): Grav\Installer\VersionUpdater->__construct('core/grav', '/var/www/virtua...', '1.7.29', Object(Grav\Installer\Versions))
> https://github.com/getgrav/grav/pull/3 /var/www/virtual/name/html/tmp/Grav-61f81d0d41083/grav-update/system/src/Grav/Installer/Install.php(184): Grav\Installer\Install->prepare()
> https://github.com/getgrav/grav/issues/4 /var/www/virtual/name/html/system/src/Grav/Console/Gpm/Direct in /var/www/virtual/name/html/tmp/Grav-61f81d0d41083/grav-update/system/src/Grav/Installer/VersionUpdate.php on line 29

Since #3523 was fixed, I am assuming a similar issue will reappear again in a different folder after this issue is fixed. Just a heads up for anyone looking into this.

**Tried with:**
**PHP:** 7.3 & 7.4
**Grav:** 1.6.31
**Admin:** 1.9.10
**Host:** Uberspace

**Comment by mahagr** [comment]
This has already been fixed for 1.7.30: https://github.com/getgrav/grav/blob/1.7.30/system/src/Grav/Installer/VersionUpdate.php#L29
