### ISSUE TITLE
Discourse slow all day and not able to create posts.

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#3534]
Through the day Discourse has been slow. Because there were no posts all day, I tried to create one. It failed...

**Comment by w00fz** [comment]
How did it fail? I was able to create a topic https://discourse.getgrav.org/t/testing-if-discourse-works/19888

**Comment by pamtbaau** [comment]
- On saving, the "Saving" spinner doesn't finish.
- When trying to discard the saving (using X on blue bar), I'm asked to discard but it doesn't abort the saving process. Keeps spinning.
- When editing a post and clicking discard, I'm asked if I want to discard, but it does't close the editor.

**Comment by rhukster** [comment]
This is 100% hosted by discourse, so even if there's a problem, we have no way of fixing it.. has to be done on discourse side.  They might just be having a partial outage?

**Comment by w00fz** [comment]
@pamtbaau Have you tried with a different browser? By the way I made you moderator

**Comment by pamtbaau** [comment]
Discourse is endless trying to access anything. Though I already was moderator. Not sure what the title is, but I do have elevated permissions to remove/split/edit posts of others.
