### ISSUE TITLE
What happens if DirectoryIndex and Option-indexes are omitted?

### ISSUE THREAD

**Issue by GndZ3r0** [getgrav/grav#3536]
One of the webhost I use disables .htaccess DirectoryIndex and Option-indexes by default.  This will cause grav to show error 500.  Omitting it will make grav works.  

My question is how important are these? should I go somewhere else that offers and allow these htaccess functions?

![awardspace_grav_500error](https://user-images.githubusercontent.com/19254282/154023275-5b2aeeba-bca3-4b05-9d6e-66e3518e2fd0.png)

**Comment by mahagr** [comment]
The rules just prevent directory information from leaking to the user, but they have likely been set up like that anyway.

**Comment by GndZ3r0** [comment]
Correct!

The webhost awardspace.com have their own set of rules when it comes to handling DirectoryIndex.  They provide their own error pages to websites hosted on them. For example: grav1.atwebpages.com/images

I manage to isolate the problem and recreate the same issue using a different subdomain with its own .htaccess (DirectoryIndex, Option-indexes enabled) and one index.html file, the result? Error 500.

![awardspace_htaccess_directoryindex](https://user-images.githubusercontent.com/19254282/154405990-f178cc46-82f2-421f-ad7b-3c43c0c76042.png)

Just like before, omitting (adding #) to DirectoryIndex/Option-indexes will make the website working again.
Conclusion, this has more to do with webhost than Grav.
