### ISSUE TITLE
Images don't get recognised as such

### ISSUE THREAD

**Issue by jcpwdev** [getgrav/grav#3544]
Hi there,

maybe you can help me out on this one:

I copy (via terminal or php, tried both) a chunk of folders and md-files (representing some blog posts) into my user/pages/blog/ directory in Grav.

As expected the pages are available just fine afterwards. Except the images. every blog post has its own images in his folder - but they don't get recognised as images, it seems.

In the Admin panel they just have the "JPG" text as thumbnail. when using them in markdown no image gets output, but just the (alt)-Text as a \<p\> tag. opening the images via browser shows them normally.

if I upload a new image via admin panel this new image works just fine and be used as expected.

I suspect that the "externally added" pictures are missing something that helps Grav to determine their type and how to use them - sadly I am at a loss here what this could be. my tries of debugging so far have been fruitless, pretty new to Grav.

cheers and many thanks!

**Comment by jcpwdev** [comment]
Hi Andy,

thanks for reaching out!

I have added a working example (uploaded normally via Grav admin).

[blogpost.zip](https://github.com/getgrav/grav/files/8153048/blogpost.zip)

For further clarification (if needed):
how a working and not working image get displayed in Grav admin:
<img width="576" alt="media view in grav admin" src="https://user-images.githubusercontent.com/24292853/155978526-33103874-43d3-46d4-b7dc-2e44efa2a3b8.png">


and how they render as html:
<img width="597" alt="generated html" src="https://user-images.githubusercontent.com/24292853/155978347-f055adaa-12e5-4bd7-8848-d96064a8cc92.png">

**Comment by rhukster** [comment]
Are you talking about being broken only the thumbnail in the Page media field?

They actually all show up fine for me:
<img width="982" alt="CleanShot 2022-02-28 at 11 41 32@2x" src="https://user-images.githubusercontent.com/1084697/156039817-5a36b5b9-f84e-48b4-8331-269f20bd9808.png">

And they all render fine on frontend and in preview.  I'm not seeing anything broken.

**Comment by rhukster** [comment]
Even deleting the image and re-uploading it looks fine:
<img width="328" alt="CleanShot 2022-02-28 at 11 43 35@2x" src="https://user-images.githubusercontent.com/1084697/156040257-e4bbec29-b738-4a11-b15f-942a9b691062.png">

**Comment by jcpwdev** [comment]
ooff, that's a bummer. sounds to me like I have a problem with the deployment environment. good for you, nothing to do here. bad for me. yikes.

thanks for your time and fast response, I think we can close this here :/
