### ISSUE TITLE
json.twig is not working

### ISSUE THREAD

**Issue by Gobikannan** [getgrav/grav#3547]
I m trying to load the page as json content type and it always loads as html.

I have installed Grav CMS in my local IIS and everything works fine except json. I have followed the below link with JSON example.
https://learn.getgrav.org/17/content/content-types#example-with-json-files

Grav Version - Grav CLI Application 1.7.30
OS - Windows
PHP 7.4.27 (cli) (built: Dec 14 2021 19:52:04) ( NTS Visual C++ 2017 x64 )

Really appreciate any help.

**Comment by pamtbaau** [comment]
I cannot test using your environment, but tested it on Windows 10 using WSL with Ubuntu-2-.04.

I've followed the same tutorial, although slightly altered, as follows:
- Using fresh installation of latest Grav
- Created file */user/themes/quark/templates/default.json.twig* with the following content:
  ```
  {% set payload = {frontmatter: page.header, content: page.content}  %}
  {{ payload|json_encode(constant('JSON_PRETTY_PRINT'))|raw }}
  ```
- Accessed page with *http://dev-dev/typography.json* and got the following result:
  ```
  {
    "frontmatter": {
        "title": "Typography"
    },
    "content": "<div class=\"notices yellow\">\n<p>Details on the full capabilities of Spectre.css can be found in the <a ...
    [stuff deleted]
    ... This is a error notification\n\n!!! This is a default notification\n\n!!!! This is a success notification<\/code><\/pre>"
  }
  ```

**Comment by Gobikannan** [comment]
Thanks, it worked. I named the file as page name instead of default.json.twig which works fine. 

I really appreciate for quick response @pamtbaau
