### ISSUE TITLE
[change-resource] Take over grav-plugin-google-analytics

### ISSUE THREAD

**Issue by mminer237** [getgrav/grav#3556]
I would like to take over the existing plugin of grav-plugin-google-analytics

Here are the project details: https://github.com/cworreschk/grav-plugin-google-analytics

Two major bugs, with pull requests provided, have gone unaswered:
 * https://github.com/cworreschk/grav-plugin-google-analytics/pull/6
 * https://github.com/cworreschk/grav-plugin-google-analytics/pull/8

The later completely breaks the plugin for most uses, and [has gone unaddressed since 2019](https://github.com/cworreschk/grav-plugin-google-analytics/issues/4).

Seeing as how I've already fixed the issues myself, I would like to just take over the plugin to share the fixes with others.

**Comment by rhukster** [comment]
What is the github URL of the new project?

**Comment by mminer237** [comment]
https://github.com/mminer237/grav-plugin-google-analytics/

**Comment by aricooperdavis** [comment]
I would love to see this actioned - with UA being discontinued this will be the only published plugin allowing Google Analytics to be used in Grav, and it's been abandoned by its owner so the pull requests that will fix it can't be merged. The workaround of manually installing from the github branch is inconvenient across multiple sites.

**Comment by rhukster** [comment]
I've transferred the google-analytics plugin to: mminer237/grav-plugin-google-analytics
