### ISSUE TITLE
Twig: attribute function broken/changed after Grav 1.7.25

### ISSUE THREAD

**Issue by hfp** [getgrav/grav#3559]
The Twig [attribute](https://twig.symfony.com/doc/2.x/functions/attribute.html) function changed after Grav 1.7.25 (and remained different or somehow broken since then). For example, the following code snippet:

```
{% if attribute(header_image_media, image_action) is defined %}
  {% set header_image_media = attribute(header_image_media, image_action,
                                       [header_image_width, header_image_height]) %}
{% endif %}
```

had to be changed to:

```
{% if '' != image_action and attribute(header_image_media, image_action) is defined %}
  {% set header_image_media = attribute(header_image_media, image_action,
                                       [header_image_width, header_image_height]) %}
{% endif %}
```

Please note, the issue is about `image_action` eventually an empty string which previously did not enter the original condition. After Grav v1.7.25, the condition required to test for an empty string or caused to call an incorrect method of the given `header_image_media`. The `image_action` is supposed to be a valid method-name (defined) and it seems to be invalid behavior if an empty string is now considered a valid method-name.

**Comment by rhukster** [comment]
That's a built-in Twig function and I doubt it changed.  More likely this is related to your `image_action` variable.  What does your YAML look like?

**Comment by mahagr** [comment]
I agree, it doesn't seem to be broken, but just an empty string as the value (which is defined). Likely there's a bad value in YAML.

**Comment by hfp** [comment]
I do not understand the reference to a YAML file. The code is a Twig template (blog_item.html.twig),  `image_action` may or may not be an empty string, and `header_image_media` is, e.g., `page.media.images|first` (or any other item from that list). For me this is fixed as shown above, but I wanted to share this issue with you (to double-check). No problem otherwise. So, feel free to close this report.

**Comment by mahagr** [comment]
Can you paste the whole twig related to this?

**Comment by hfp** [comment]
Perhaps the whole theme is needed to make sense of [blog_item.html.twig](https://github.com/getgrav/grav/files/8284383/blog_item.html.twig.txt). Unfortunately, the theme is pretty customized and related to the content.

**Comment by rhukster** [comment]
I assumed it was a YAML variable as you have another variable called `header_image_media` which sounds like its coming from a page header/frontmatter, and that is going to be in YAML format.  Anyway, it's going to be because that value is set to an empty string. That logic has not changed, so sounds like your variable has changed.. Either way its seems like its not core-related so closing.

**Comment by hfp** [comment]
Thank you for taking a look!
