### ISSUE TITLE
[add-resource] New Plugin -- Server-side syntax highlighing with highlight.php

### ISSUE THREAD

**Issue by iainsgillis** [getgrav/grav#3565]
Hi, Folks --

I would like to add my new plugin, which adds server-side syntax highlighting courtesy of the [highlight.php library](https://github.com/scrivo/highlight.php) and the [ShortCode Core plugin](https://github.com/getgrav/grav-plugin-shortcode-core), to the Grav Repository.

The project lives here: [iainsgillis/grav-plugin-highlight-php](https://github.com/iainsgillis/grav-plugin-highlight-php)

FWIW, I wrote a series of blog posts about conceiving, designing, and releasing this plugin on my own site, starting with https://www.iainsgillis.com/essays/build-a-grav-plugin-1

**Comment by iainsgillis** [comment]
Many thanks for this review -- I appreciate the suggestions, and the rationale.

I'll make some revisions in the coming days.



On Mon, Mar 21, 2022, at 07:54, pamtbaau wrote:
> 
> 
> @iainsgillis <https://github.com/iainsgillis>, I've taken the liberty to create a review of your plugin.
> 
> Suggestions:
> 
>  * HiglightPhpShortcode.php 
>    * Use shortcode with parameters 
> `[phphighlight=js]
> class Rectangle {
>   constructor(height, width) {
>     this.height = height;
>     this.width = width;
>   }
> }
> [/phphighlight]
> 
> [phphighlight=js code="console.log('hello')"]
`

**Comment by pamtbaau** [comment]
@iainsgillis,  Forgot to mention that the following condition will never be true, because the plugin will not be called when not enabled. It can be removed.
```
if (!$this->config->get('plugins.highlight-php.enabled')) {
    return;
}
```

**Comment by iainsgillis** [comment]
@pamtbaau Many thanks for the review and the suggestions! Really appreciate your time.

**Comment by rhukster** [comment]
Sorry missed this one, added.
