### ISSUE TITLE
Default Setting Modular Page

### ISSUE THREAD

**Issue by marexx** [getgrav/grav#3569]
Hi There,
I have a Projects Page, and every Child-Page is a Modular Page.
At the moment i've to add 
`content:
    items: '@self.modular'
    order:
        by: default
        dir: asc`

to every Child-Page per hand, so the content is displayed. Can I set that by default, so you don't have to do it every time?

**Comment by Miimosh** [comment]
@marexx did you find a solution to this problem?

**Comment by marexx** [comment]
No Sorry.
