### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by xf-** [getgrav/grav#3571]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **[catch-IT/grav-image-server](https://github.com/catch-IT/grav-image-server/)**

**Comment by xf-** [comment]
@mahagr any information missing

PS: Footer link on plugins page points to gitter

**Comment by mahagr** [comment]
I recommend you to use Twig 2 compatible name-spaced methods as Twig 1 is no longer supported forcing us to update it to v2.

Otherwise it looks good to me, with the note that there may be incompatible changes in Grav 1.8 due to image rework.

**Comment by mahagr** [comment]
@xf- I've been working on my `feature/media` branch of Grav (1.8), which allows us to have far better image manipulation, retina scaling, webp... It basically moves any image manipulation into the image request itself, but does that using obfuscated requests to prevent any misuse.

I haven't yet started the part your plugin is trying to fix, as I'm still finalizing the underlying code. But soon I will start looking into adding full media support for most of the things you have already solved. Do you want to work with me to get things done? :)

**Comment by rhukster** [comment]
Added.

**Comment by xf-** [comment]
sry, really busy the last months @mahagr
