### ISSUE TITLE
Bug Report/ Feature Request: Allow CLI commands to specify an env to load configurations

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav#3575]
Problem:
Using site-specific env overrides/ configuration files aren't reachable via CLI commands.  This breaks plugin configurations placed into the env folders.

To replicate:
* Install email plugin
* Customize the plugin via a user/env/sitename/config/plugins/email.yaml file
* View changes in admin were applied properly
* Run a `bin/plugin email test-email`
* CLI command will fail due to settings not properly set.

Feature request:
Allow all CLI commands in general to be "sitename aware" somehow, maybe via parameter.  If parameter is empty, then fallback to defaults, which is current behavior.

**Comment by rhukster** [comment]
This already exists (and has for quite some time).  It’s the `—env sitemame` option on the base level cli class.

**Comment by jgonyea** [comment]
I'm sorry. I don't know how, but I missed that.

appending `--env "sitename"` worked in the expected manner.
