### ISSUE TITLE
Update to php 8.1

### ISSUE THREAD

**Issue by ChristianaHoJo** [getgrav/grav#3576]
Hi,

we are running grav v1.7.32. Can we update to the latest php 8.1 version?

I'm looking forward to an answer!

Greetings,
Christiana

**Comment by mahagr** [comment]
We've been using PHP 8.1 for a while and it works as long as you update all the plugins and the theme. PHP 8.1 is more strict than the older versions, which is why the updates may be needed to theme.

**Comment by ChristianaHoJo** [comment]
Hi @mahagr ,

thank you for your answer. Then we will give it try!
