### ISSUE TITLE
[add-resource] New Plugin Better Typography

### ISSUE THREAD

**Issue by bricebou** [getgrav/grav#3577]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **[bricebou/grav-plugin-better-typography](https://github.com/bricebou/grav-plugin-better-typography)**

The purpose is to propose a multilingual typographic enhancements plugin ; you can see it live on the monolingual website [grav.reclic.dev](https://grav.reclic.dev).

I'm not a developer so the code might be dirty... I'm open to suggestions, advice, comments...

I've just realized that I create a release package (https://github.com/bricebou/grav-plugin-better-typography/releases/tag/v0.1.0) but it doesn't contain the vendor/ folder, so the plugin will miss the PHP Typography library. 
What's the best practice ?

Thanks in advance !

**Comment by rhukster** [comment]
Added.
