### ISSUE TITLE
[add-resource] New Plugin GIS

### ISSUE THREAD

**Issue by bricebou** [getgrav/grav#3578]
I would like to add my new plugin GIS to the Grav Repository.
Here are the project details: **[bricebou/grav-plugin-gis](https://github.com/bricebou/grav-plugin-gis)**

You can see the public live on [grav.reclic.dev](https://grav.reclic.dev/).

Like I said in my previous request, I'm not a developer... I've tried to do my best ;)

Thanks !

**Comment by rhukster** [comment]
Added.
