### ISSUE TITLE
[add-resource] New Hereditor theme

### ISSUE THREAD

**Issue by gizmecano** [getgrav/grav#3583]
Greetings,

I would like to submit my theme (_Hereditor_) to the Grav repository (it's a detached fork of the [getgrav/grav-theme-mediator](https://github.com/getgrav/grav-theme-mediator) theme initially developed by Grav team and contributors).

The project details and source code is available at [gizmecano/grav-theme-hereditor](https://github.com/gizmecano/grav-theme-hereditor).

The related skeleton package is available at [gizmecano/grav-skeleton-hereditor-site](https://github.com/gizmecano/grav-skeleton-hereditor-site/).

In addition, a [demonstration implementation](https://htg.gizmecano.net/) of this theme based on the skeleton has been published online.

**Comment by gizmecano** [comment]
Just a quick note to inform that I have just improved a bit the [theme pre-release](https://github.com/gizmecano/grav-theme-hereditor/releases/tag/2.0.0-beta.2) for submission to the Grav repository.

**Comment by rhukster** [comment]
Added.
