### ISSUE TITLE
[add-resource] New Plugin "Whistleblower"

### ISSUE THREAD

**Issue by LuanHimmlisch** [getgrav/grav#3588]
I would like to add my new plugin to the Grav Repository.
Here are the project details: [**Himmlisch-Studios/grav-plugin-whistleblower**](https://github.com/Himmlisch-Studios/grav-plugin-whistleblower)

![image](https://user-images.githubusercontent.com/46875694/169686236-c121f9a6-9a37-406c-a893-d05bb8a987fe.png)

It lets you receive notifications on your phone or PC every time an event hook happens via [ntfy](https://github.com/binwiederhier/ntfy/).

![image](https://user-images.githubusercontent.com/46875694/169686489-8053cc47-8b85-4b4a-ac0b-82e8e0c0685d.png)

**Comment by rhukster** [comment]
Added
