### ISSUE TITLE
Proxy support in cli

### ISSUE THREAD

**Issue by spacemonkey** [getgrav/grav#359]
Running `bin/gpm index` behind a corporate proxy results in a foreach error.

Haven't done PHP this decade, but someone pointing me in the right direction will likely in a pull request :-)

**Comment by rhukster** [comment]
Yah I don't think we have run into this before.. Couple of things would need to be done:

1) Have some proxy configuration settings in system.yaml, so they can be overridden by the user's config: https://github.com/getgrav/grav/blob/develop/system/config/system.yaml

2) Utilize these in Response.php: https://github.com/getgrav/grav/blob/develop/system%2Fsrc%2FGrav%2FCommon%2FGPM%2FResponse.php

**Comment by spacemonkey** [comment]
Would prefer to use environment variables, to avoid hardcoding auth credentials in yet another file :)

Just got things installed and running, will look around and issue a pull request if I can get to it.

**Comment by flaviocopes** [comment]
curl allows you to set the proxy as an environment variable (`http_proxy` & `https_proxy`), without changes needed in Grav, see http://stackoverflow.com/questions/7559103/how-to-setup-curl-to-permanently-use-a-proxy. You might need to disable `allow_url_fopen` to avoid Grav using fopen instead of curl

**Comment by spacemonkey** [comment]
@flaviocopes we have a winner! Didn't know allow_url_fopen could unintentionally bypass all env variables set for curl to work. Looks like that is the easy fix, however it might be good to check in that foreach and spit out "unable to connect, could you be behind a proxy?" type of message instead of the php fatal.

**Comment by flaviocopes** [comment]
That's because in Grav fopen is given priority over curl, if available.

The error message is annoying, you're right!

**Comment by c33s** [comment]
vote for reopen or new ticket for enhanced proxy support:

currently i have to add this in my `system.yaml` if i don't want to use curl
```
gpm:
  proxy_url: 'tcp://proxy.example.com:8080'
```
but i would prefer to let the grav read it from my env variables. 

i configured my php to set the defaults for stream contexts in a php file which always gets included:
`php.ini`
```
auto_prepend_file = "proxy.php"
```
`proxy.php`
```
<?php

$stream_default_opts = array(
  'http'=>array(
    'proxy'=>"tcp://proxy.example.com:8080",
    'request_fulluri' => true,
  )
);

stream_context_set_default($stream_default_opts);
```

but it looks like grav overwrites this somewhere. i needed the proxy setting in the yaml file to make it work. other php apps on my system work out of the box with the proxy
