### ISSUE TITLE
Registration does not work. OSX - Monterey

### ISSUE THREAD

**Issue by DoktorVonMixer** [getgrav/grav#3602]
I've tried using MAMP, and now have another PHP/Apache combo going on that displays the basic grav-admin. So, php-side is covered.
When trying to enter a password, prompts/error says the password does not meet minimum requirements.

Tried editing system.yaml with other regex but no luck.

I was imagining permission issues, and tried applying recursing fixes on the files and folders (same user for apache, folders, files, etc). Again, no luck.

It's impossible for me to get Grav running.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/25445182/177615310-f272ef4f-eb11-478a-8f89-3c8b78bd538e.png">

**Comment by rhukster** [comment]
hmm.. can you try just lowercase `dokmixer` ?
