### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by AizkibelRojo** [getgrav/grav#3608]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **[AizkibelRojo/grav-bettercomments](https://github.com/AizkibelRojo/grav-bettercomments)**

Comment plugin for Grav cms enhanced from "comments" plugin.

- Admin panel (delete, approve, reject)
- Admin can answers from panel (1 nexting level)
- Ajax for user comments and admin panel actions 
- Error and succes messages

**Comment by rhukster** [comment]
Added!
