### ISSUE TITLE
[change-resource] Take over Plugin grav-plugin-autoseo

### ISSUE THREAD

**Issue by francodacosta** [getgrav/grav#3609]
I would like to take over an existing plugin.
Here are the project details: **gameamea/grav-plugin-autoseo**

I use it in a bunch of my sites and the plugin owner states on the readme file that has no time to maintain it and his happy for someone else to do it

I've emailed him but got no answer back (although not enough time has passed yet)

**Comment by francodacosta** [comment]
Update: the email bounced back!

**Comment by rhukster** [comment]
Do you have a fork and a released version?

**Comment by francodacosta** [comment]
No, I understood from the instructions to contact you first

Let me do that then

**Comment by francodacosta** [comment]
here it is https://github.com/francodacosta/grav-plugin-autoseo release 1.4.0

**Comment by rhukster** [comment]
You should probably also update the changelog and explain the takeover + any fixes you have made since 1.3.5

**Comment by francodacosta** [comment]
@rhukster done!

Not sure of how much detail to give regarding the takeover

**Comment by rhukster** [comment]
will get this updated.. cheers.
