### ISSUE TITLE
Multiple Collections Using the Same Keys

### ISSUE THREAD

**Issue by jeffaudio** [getgrav/grav#361]
When defining multiple collections within a page, only the first of each item type is added to the collection if the keys are the same.

```
content:
    items:
        @taxonomy.category: blog
        @taxonomy.category: featured
```

This will only match items with the first category, `blog`, but ignore those with `featured` (unless they also have `blog`), which is not the intended collection.

Per discussion over on the [forums](https://muut.com/getgrav#!/getgrav/general:multiple-collections-and-ta) this is due to the way YAML defines the key.

```
content:
    items:
        @taxonomy: {category: blog}
        @taxonomy.category: featured
```

This is one workaround for two items, although it's not extensible. Perhaps `items` could be an array of distinct items or a `filter_combinator` mechanism could be used like in the simplesearch plugin.

**Comment by rhukster** [comment]
I have an idea for this that would allow unlimited numbers of the same taxonomy, just need to test it.

**Comment by rhukster** [comment]
Ok this last fix will allow you to do:

```
content:
    items:
        - @taxonomy.category: blog
        - @taxonomy.category: featured
        - @taxonomy.category: foo
        - @taxonomy.category: bar
```

These will all be **or**-ed together
