### ISSUE TITLE
[bug] Wrong ordering in Clockwork

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav#3611]
Code:
```

{{ dump(1) }}
{{ dump(2) }}
{{ dump(3) }}
{{ dump(4) }}
{{ dump(5) }}
{{ dump(6) }}
{{ dump(7) }}
{{ dump(8) }}
{{ dump(9) }}
```

Output:
![image](https://user-images.githubusercontent.com/7556290/181905604-c8425ac0-9e72-4744-8803-8d2cca27efa1.png)

it changes multiple times on every page refresh.

PHP Debug Bar works fine:
![image](https://user-images.githubusercontent.com/7556290/181905675-21d6013e-7669-4753-bbd0-f4f3b859815f.png)

**Comment by rhukster** [comment]
Clockwork uses ajax so it's quite possible that things get received out of order... its not a bug its a feature of clockwork :)
