### ISSUE TITLE
Cache-Control: max-age should contain delta-seconds

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#362]
At the moment the `Cache-Control` header contains the date as argument for the `max-age` directive, for example `Cache-Control: "max-age=Fri, 16 Oct 2015 08:14:43 GMT"`.
But according to the [standard](http://tools.ietf.org/rfcmarkup?doc=7234#section-5.2.2.8) the `max-age` directive should contain delta-seconds as argument, for example `Cache-Control: "max-age=604800"`.

**Comment by flaviocopes** [comment]
You're right, thanks for reporting
