### ISSUE TITLE
Duplicated website problem

### ISSUE THREAD

**Issue by maofree** [getgrav/grav#3621]
Hi
I put my first grav site online and saw a problem that it is possible to see it in 4 modes
http://www.autotrasportimorellisbrana.it
http://autotrasportimorellisbrana.it
https://www.autotrasportimorellisbrana.it
https://autotrasportimorellisbrana.it

with force ssl I remove the option http://www.autotrasportimorellisbrana.it but the other two present
I want only https://www.autotrasportimorellisbrana.it

is it possible to set a redirect from the admin's panel? the better solution should be add some option in the configuration page to remove this seo problem, in fact Google search console alert me about these duplications

at this moment I'll resolve this problem by htaccess, but the best solution is add some settings in the configuration page

thanks

**Comment by rhukster** [comment]
this is not something you can do from the admin panel.  You need to configure this in your webserver config or .htaccess if you run apache.
