### ISSUE TITLE
Option to disable Shopping Cart icon (Gumroad)

### ISSUE THREAD

**Issue by slalabs** [getgrav/grav#3631]
Please add an option to disable this cart icon in the top right. After an update it appears there, overlap the update button. I already have active premium licenses. 

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/84683304/194695673-d99bf942-2dce-4cab-b28d-a92a57a50a0e.png">

**Comment by rhukster** [comment]
yes this is very annoying. it seems something that gumroad just enabled. i had to block it with css in the vet grav.org site.  will release a quick update that does the same in admin.

**Comment by rhukster** [comment]
Fixed in 1.10.37.1 of admin plugin
