### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by svnwa** [getgrav/grav#3632]
I would like to add my new theme to the Grav Repository.
It is a TailwindCSS 3 based theme for a single page landing page.

Here are the project details: **svnwa/grav-theme-tail-land**

See [https://github.com/svnwa/grav-theme-tail-land](https://github.com/svnwa/grav-theme-tail-land).

**Comment by rhukster** [comment]
Sorry for the delay, this has been added to GPM
