### ISSUE TITLE
www to non-www problem when Grav is in subfolder

### ISSUE THREAD

**Issue by Sulpher** [getgrav/grav#3637]
Hello,
Grav based site is located in subfolder:
domain.com/docs/

The problem occurs with a redirect. 
I have tried different options, here is the example:

```
RewriteEngine On
RewriteBase /
RewriteCond %{HTTP_HOST} ^www\.(.*)$ [NC]
RewriteRule ^(.*)$ https://%1/$1 [R=301,L]
```

When I add these lines to .htaccess which is located in the root of Grav CMS (in my case, it is domain.com/docs/), the logic works so:
A user enters the following address:
www.domain.com/docs and is being redirected to the https://domain.com instead of https://domain.com/docs/

I also tried these lines:

```
RewriteEngine On
RewriteBase /
RewriteCond %{HTTP_HOST} ^www\.domain\.com\docs\(.*)$ [NC]
RewriteRule ^(.*)$ https://domain.com/docs%1/$1 [R=301,L]
```

or these:
```
RewriteEngine On
RewriteCond %{HTTP_HOST} ^www.domain.com\/docs$ [NC]
RewriteRule (.*) https://domain.com\/docs$1 [R=301,L]  
```

But it also redirects to domain.com instead of domain.com/docs

There should be right .htaccess commands.
Can you help, please?

Thanks in advance.

**Comment by rhukster** [comment]
As this is a webserver question, and not really Grav-specific, it should be asked in the Grav discord channel: https://chat.getgrav.org.

Thanks!

**Comment by Sulpher** [comment]
Hi Andy,
Thanks for the reply.
I found the solution.

For history and other users:
If you need to redirect all Grav pages from subfolder https://domain.com/docs/ to the subdomain https://docs.norrnext.com, use the following lines in .htaccess:

```
RewriteEngine On
RedirectMatch 301 ^/docs/(.*)$ http://docs.domain.com/$1
```

It will redirect all pages to the new URL.
