### ISSUE TITLE
Add SVG format support for favicon

### ISSUE THREAD

**Issue by Sulpher** [getgrav/grav#3639]
Hi,
I'd like to suggest adding SVG format support for favicons.
It is more universal than PNG and can be scalable on any modern device.
Would be just great to put favicon.svg to theme and get magic :-)

Thanks.

**Comment by bitstarr** [comment]
When creating a theme, you are free to use the formats you prefer. There is no default or magic. It depends on the theme and how it integrates favicons.

See:
https://learn.getgrav.org/16/themes/asset-manager#examples
https://learn.getgrav.org/16/themes/twig-tags-filters-functions/tags#link

**Comment by Sulpher** [comment]
@bitstarr thank you.

**Comment by pmoreno-rodriguez** [comment]
Has this problem been solved? If so, I think the Grav team will appreciate you closing this issue.
