### ISSUE TITLE
Upgrading from PHP version 7.x to version 8.x BE CAREFUL OF YOUR PLUGINS

### ISSUE THREAD

**Issue by symgryph** [getgrav/grav#3642]
All:

This is more of an fyi for those of you who are upgrading from version 7.x to version 8.x. The old 'shortcode' plugin is NOT compatiable with php8.1. I removed it and it fixed everything. You get the horrible error message:

```ini
Server Error
Sorry, something went terribly wrong!

E_NOTICE - spl_autoload_register(): Argument #2 ($do_throw) has been ignored, spl_autoload_register() will always throw
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
```

**Comment by rhukster** [comment]
I assume you meant PHP version 7 to 8 as Grav is at 1.7 currently.

Actually shortcode plugin is fully PHP 8.1 compatible, but if you were on a very old version, it's possible that it was a version that was not compatible.  All the core Team Grav and TrilbyMedia plugins are 8.1 compatible as is Grav itself of course. 

It's always tricky changing PHP versions if you are running code that was released prior to the version and perhaps is not 100% compatible.  The best approach is always be running the latest versions of everything (Grav, Plugins, Themes, etc), and then upgrade your PHP version.  This way you ensure you are running any PHP-specific fixes before you upgrade the underlying PHP that runs everything.
