### ISSUE TITLE
[add-resource] New Plugin: zmarkdown-engine

### ISSUE THREAD

**Issue by AmauryCarrade** [getgrav/grav#3647]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **AmauryCarrade/grav-plugin-zmarkdown-engine**

It's a kinda niche one: it replaces the native Markdown engine with [zmarkdown](https://github.com/zestedesavoir/zmarkdown), another engine developed for a French knowledge-sharing website and non-profit, Zeste de Savoir (Zest of Knowledge), and published under MIT licence. As I'm publishing in there and on my own personal site running Grav, it's comfortable to have the same engine on both sides. Also, zmarkdown have some other possibilities Grav do not have (or implement differently, mainly through shortcodes).

It's compatible with Twig processing, shortcodes, and Grav's links & images post-processing.

**Comment by rhukster** [comment]
Sorry for the delay, added to GPM.
