### ISSUE TITLE
[add-resource] New Plugin: Sender

### ISSUE THREAD

**Issue by aricooperdavis** [getgrav/grav#3648]
I would like to add my new plugin to the Grav Repository.

Here are the project details: [aricooperdavis/grav-plugin-sender](https://github.com/aricooperdavis/grav-plugin-sender)

It's a plugin that adds a form action that uses the Sender.net API to add subscribers to a Sender.net account, so it's useful for a "sign-up to my newsletter" type thing.

**Comment by rhukster** [comment]
Sorry for the delay, this has been added to GPM.
