### ISSUE TITLE
Change folder generation

### ISSUE THREAD

**Issue by leon1995** [getgrav/grav#3650]
I would like the blog posts to have a slug structure like year/month/day/post-title. However, I dont want to set it manually for each blog item I am going to write. Is there a way to chqnge the default slug generation?

**Comment by pamtbaau** [comment]
@leon1995, To relieve the dev team, "how to" questions are generally posted on the community forums. That can either be [Discourse](https://discourse.getgrav.org/) (threaded discussions), or [Discord](https://getgrav.org/discord) (chat like).

The dev team itself is mostly available on Discord.

**Comment by leon1995** [comment]
Yeah I asked my question there. Thanks for the advice!
