### ISSUE TITLE
[add-resource] New Plugin: nyk-authors

### ISSUE THREAD

**Issue by Nykold** [getgrav/grav#3656]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **[Nykold/nyk-authors](https://github.com/Nykold/nyk-authors)**

It intends to make it easier to automatically add a string with a specific page's authors in blogs (via page header and Twig) and it is especially made for people that are using the Admin plugin.

**Comment by rhukster** [comment]
Sorry for the delay, this has been added to GPM.
