### ISSUE TITLE
Question about loading of SVG images

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#366]
I have a question about loading of SVG images.
For example I have the following folder structure:
```
/user
└─/pages
  ├─/01.home
  │ ├─/_header
  │ └─/_body
  ├─/02.blog
  │ ├─/blog-item-1
  │ ├─/blog-item-2
  │ ├─/blog-item-3
  │ └─/docs
  │   └─/images
  │     ├─image.png
  │     ├─image.jpg
  │     └─image.svg
  └─/error
```
So I have three images in the `/user/pages/02.blog/docs/images` folder.

Next, if I open the following URLs
```
http://site.local/blog/docs/images/image.png
http://site.local/blog/docs/images/image.jpg
```
PNG and JPEG image files will open in browser.

But if I try URL for SVG image file
```
http://site.local/blog/docs/images/image.svg
```
Browser starts to download the file because it loads SVG image with `Content-Type: "application/octet-stream"`.

What can be done to load SVG file as an image?

**Comment by flaviocopes** [comment]
Fixed in develop, thanks for reporting!

**Comment by sphkress** [comment]
I just found out, SVG is working when using it inside an <IMG>, but when using it as <OBJECT>, it's still trying to download the file instead of displaying it. Is this really intended?
