### ISSUE TITLE
HR tag breaks markdown

### ISSUE THREAD

**Issue by u07** [getgrav/grav#3664]
Hi! 

Seems like GRAV expects the [`<HR>` tag](https://www.w3docs.com/learn-html/html-hr-tag.html) to have a matched closing one `</HR>`. Without it the following markdown will be rendered as a plain text:

```
---
title: Hi there
---
<HR>
This won't look like [markdown](https://mark.down/).
```

**Comment by rhukster** [comment]
first xhtml tags should be lowercase. second there's no need for an <hr> tag at all as Markdown already supports it natively:

https://markdown-guide.readthedocs.io/en/latest/basics.html#horizontal-rules
