### ISSUE TITLE
Devtools: Tailwind theme is broken 

### ISSUE THREAD

**Issue by tauchvogel** [getgrav/grav#3665]
Hi there,

I play around with Grav CMS and its plugin dev tools. With this plugin I had successfully created a theme with tailwind.

I am a bit confused about a thing with this theme. In the “head” of the page I can see this code:
`<link rel="icon" type="image/png" href="/user/themes/taily/images/logo.png" />`

I can click on the link and I see the Grav-logo in a new browser window.

But I can not see this image on the page itself. Why?

The code in base.html.twig of the image is this:
`<link rel="icon" type="image/png" href="{{ url('theme://images/logo.png')|e }}" />`

Also the whole page output seems not working right now. It seems that the stylesheet is not loading exactly!

Is the theme broken? Please fix it, I wanna use it for Grav CMS!

I also made an issue for the developer of the tailwind theme for devtools plugin. But it was not fixed yet.

**Comment by pamtbaau** [comment]
Cross-post from this original issue: [Tailwind theme created by devtools plugin is broken? #78](https://github.com/getgrav/grav-plugin-devtools/issues/78)
