### ISSUE TITLE
[change-resource] Take over Plugin/Theme

### ISSUE THREAD

**Issue by aricooperdavis** [getgrav/grav#3670]
I would like to take over an existing plugin/theme.

Here are the project details: [**skinofthesoul/grav-plugin-antispam**](https://github.com/skinofthesoul/grav-plugin-antispam/)

[Here is the pull request](https://github.com/skinofthesoul/grav-plugin-antispam/pull/25) that has remained unnoticed since 23rd Nov 2022.

I appreciate that this has been over the holiday period, but the maintainer has no github activity since 2nd Sep 2022.

Thanks,
Ari

**Comment by rhukster** [comment]
I've created an issue on the author's repo.  Let's give them some time to respond.
