### ISSUE TITLE
Transfer theme project: grav-theme-editorial

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav#3673]
Hi,

I'd like to transfer the link in the GPM for grav-theme-editorial from:
https://github.com/jgonyea/grav-theme-editorial
to:
https://github.com/pmoreno-rodriguez/grav-theme-editorial

The other developer has agreed to take ownership of this theme (https://github.com/jgonyea/grav-theme-editorial/pull/17#issuecomment-1368008662)

Please let me know if there is anything else you need.

**Comment by rhukster** [comment]
I've trasnferred the theme.  thanks.

**Comment by jgonyea** [comment]
Many thanks, @rhukster.
