### ISSUE TITLE
Wrong data in new Editorial repository

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [getgrav/grav#3674]
Hi @rhukster.

Recently @jgonyea transferred the Editorial theme repository  to me to continue its development from my repository on GitHub.
My repository is a fork of the original, but GPM is correctly pointing to it. However, when the Grav themes repository shows wrong data such as author, thumbnail image and CHANGELOG.

How can I fix this?. Should I recreate the repository in my GitHub profile as the main repository and not a fork?

**Comment by jgonyea** [comment]
I would be fine with that.  @pmoreno-rodriguez, if you'd like, I can delete my repo and then I think yours becomes a "real" one, as in, a non-forked repo.

**Comment by jgonyea** [comment]
I just don't want to do it until I know you have a copy of your work locally.

**Comment by pmoreno-rodriguez** [comment]
Hi there.
I've finally re-created the Editorial Theme repository on my GitHub profile, and confirmed that Grav Themes displays it fine. Everything seems to be fine, except that the Changelog button does not correctly display the Changelog.md file for version 1.0.3 (the latest available version of the theme).

What can I do so that all changes are displayed correctly when the user clicks on the "Changelog" button?

**Comment by pmoreno-rodriguez** [comment]
This is what is now displayed on the Grav Themes website when you click the Changelog button:

![changelog_editorial](https://user-images.githubusercontent.com/60596353/212608742-93f2f17d-87cd-4395-82df-620e7a7980cd.png)

If you take a look at the changelog.md file you can see that there are more lines of text than what appears when you click the "Changelog" button in the theme (only Bugfixes).

How can i fix this?

**Comment by pmoreno-rodriguez** [comment]
Fixed in version 1.0.5.

**Comment by pmoreno-rodriguez** [comment]
> I just don't want to do it until I know you have a copy of your work locally.

@jgonyea I think the new editorial repository is working fine. So I think it may be a good time to archive your repository instead of deleting it, if you want.
