### ISSUE TITLE
[add-resource] New Plugin: IP Blacklist

### ISSUE THREAD

**Issue by aricooperdavis** [getgrav/grav#3675]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: [**aricooperdavis/grav-plugin-ip-blacklist**](https://github.com/aricooperdavis/grav-plugin-ip-blacklist)

This plugin allows you to block IPs from accessing your site, instead returning an http status code (e.g. 403 Forbidden). This can either use a local blacklist or the [AbuseIPDB](https://www.abuseipdb.com/) blacklist or both.

It also filters the URIs of requests to your site against a number of regex patterns for known abuse requests (probing for vulnerabilities), such as `./env`. Matching requests can have their IP added to your local blacklist, and can be reported to AbuseIPDB.

It's no replacement for a server firewall, but it is likely to put off a a few common automated hacking attempts, will save you some server resources and bandwidth in responding to these abusive requests, and helps AbuseIPDB build up an understanding of which IPs are abusive.

**Comment by rhukster** [comment]
Added to GPM for next update
