### ISSUE TITLE
[add-resource] New Plugin: Timestamp

### ISSUE THREAD

**Issue by petira** [getgrav/grav#3678]
I would like to add my new plugin to the Grav Repository.
Here are the project details: https://github.com/petira/grav-plugin-timestamp.

The **Timestamp** Plugin is an extension for [Grav CMS](https://github.com/getgrav/grav). The Timestamp Plugin overrides the values of all listed `date` type variables from a recognizable `string` format to a value in `timestamp` format. Valid values are any string date values that `strtotime()` supports. Optionally, if a variable is not specified on a page, it can be created and the selected value returned to it.

Among other things, it can solve the following issues: https://github.com/getgrav/grav/issues/3543, https://github.com/getgrav/grav/issues/1641, https://github.com/getgrav/grav/issues/1368, https://github.com/getgrav/grav/issues/1199, and/or possibly others.

**Comment by rhukster** [comment]
Added to GPM for next update
