### ISSUE TITLE
Invalid Security Token - Azure Hosted Grav

### ISSUE THREAD

**Issue by kirbyAlasdairAnswer** [getgrav/grav#3686]
I have an instance of Grav 1.7.38 with grav-admin installed as a web-app on azure. 
Volume is mounted to an Azure storage container. 
Login to Admin page fails 90% of the time with invalid token error.

In response to this we have tried repeated fixes including installing grav through [linux-server-get-grav](https://github.com/linuxserver/docker-grav) and [docker grav ](https://github.com/getgrav/docker-grav) all of which work fine locally but have this token issue on azure.

I have seen the troubleshooting guides and applied all the fixes there to no affect.

**Comment by saberking** [comment]
I am having the same problem using nginx reverse proxy. I have spent many hours searching for a solution.

**Comment by saberking** [comment]
I gave up on using nginx and switched to traefik, now it works. I combined the configs here https://www.digitalocean.com/community/tutorials/how-to-use-traefik-as-a-reverse-proxy-for-docker-containers-on-ubuntu-18-04 
and here
https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/

**Comment by kirbyAlasdairAnswer** [comment]
did you manage to get this working from a single container?

**Comment by kirbyAlasdairAnswer** [comment]
I have resolved the Issue, the session.save_path must be set (was commented out) in /etc/php81/php.ini. I did this by adding the following line to my docker file
`session.save_path=\"/tmp\"" >> /etc/php81/php.ini`
