### ISSUE TITLE
RSS Feeds Broken with commit ea010f19

### ISSUE THREAD

**Issue by 9p4** [getgrav/grav#3689]
With commit https://github.com/getgrav/grav/commit/ea010f19f0194540aefc9b06a1e1e3fbbb2b2781, the RSS feeds have been broken. Going to the RSS feed URL redirects the user to the site's page and does not yield feed data.

**Comment by rhukster** [comment]
Confirmed, i'll look a thist first thing tomorrow.

**Comment by rhukster** [comment]
fixed with https://github.com/getgrav/grav/commit/72b769aa63e42758891b055da13e6a7e05658ccf

**Comment by 9p4** [comment]
Confirmed that the fix works. Thanks for quick fix!

**Comment by rhukster** [comment]
pushed a cleaner fix.. and released as 1.7.39.3
