### ISSUE TITLE
Issue with exporting data to CSV in Grav's Data Manager plugin

### ISSUE THREAD

**Issue by kevin19100** [getgrav/grav#3691]
Hello,

I am currently experiencing an issue with exporting data to CSV in Grav's Data Manager plugin. Whenever I try to export the data, I receive the following error message:

"Server Error
Sorry, something went terribly wrong!

0 - Failed to save file /var/www/grav/tmp/data-manager/63f732fe7c6fc.csv/
For further details please review your logs/ folder, or enable displaying of errors in your system configuration."

I am running Grav on a web browser and I previously had no issues exporting data to CSV.

Can someone please help me troubleshoot this issue?

Thank you in advance for your assistance.

**Comment by rhukster** [comment]
Most likely your folder is not writable by the webserver.

Check this out: https://learn.getgrav.org/17/troubleshooting/permissions

**Comment by jovaniedelacruz** [comment]
Do you think it has to do with trying to save the file with an appended "/" to the end of it? Look at this other issue discussed:
https://github.com/getgrav/grav-plugin-data-manager/issues/43#issuecomment-1147121498

**Comment by kevin19100** [comment]
Thanks everyone
