### ISSUE TITLE
[add-resource] New Plugin: CNB Exchange Rates

### ISSUE THREAD

**Issue by petira** [getgrav/grav#3693]
I would like to add my new plugin to the Grav Repository.
Here are the project details: https://github.com/petira/grav-plugin-cnb-exchange-rates.

The **CNB Exchange Rates** Plugin is an extension for [Grav CMS](https://github.com/getgrav/grav). The CNB Exchange Rates plugin obtains information about current exchange rates from source files published by the Czech National Bank (CNB) and subsequently provides their outputs.

**Comment by rhukster** [comment]
Added to GPM for next update
