### ISSUE TITLE
Help to delete all saved data in my database

### ISSUE THREAD

**Issue by kevin19100** [getgrav/grav#3694]
Hello everyone,

I'm currently facing an issue that I can't seem to solve. I have a database that contains too much data and I would like to permanently delete it.

I'm using the Grav database and I would like to know if there is a method to delete all the data that has been saved in the Grav database.

Thank you in advance for your help.

![Capture](https://user-images.githubusercontent.com/93037207/221643863-5dd07b13-237a-4342-972e-4fd57328db64.PNG)

**Comment by spamhater-grav** [comment]
Grav actually doesn't use a database , it will be the grav-database-plugin (found here https://github.com/getgrav/grav-plugin-database)  which allows you to create a connection to the an external database.
  
check the following locations 
`user/plugins/database/database.yaml` 
or
`user/config/plugins/database.yaml`

This should tell you  the name and location of the filename on your system and you can simply delete that file or at least find where it is stored and what system (mysql, sqllite) etc it is .. and just rename the file or go in to your database admin program and delete the database records within cli / gui - and delete all the records, but leave the schema (database field layouts) - you can google the command for a specific database software for a single command you can apply 

I would personally make a copy of the file or at least export all the data, just in case you need something out of it, maybe something like .csv format so you can open it up in spreadsheet.

**Comment by spamhater-grav** [comment]
You have duplicated and recreated your question , where there has been answers  placed here

https://github.com/getgrav/grav/issues/3691

**Comment by kevin19100** [comment]
Thanks everyone
