### ISSUE TITLE
Admin dashboard broken after upgrade

### ISSUE THREAD

**Issue by zoof** [getgrav/grav#3715]
I upgraded `grav` this morning and now the admin panel is broken.  The web page still renders.  Happy to provide any data to figure out the problem.  My installation is running on Centos 7 with an Apache backend and a fairly modern php (8.x? can't check at the moment as I don't have ssh access).

The error page has a lot of information and I can post anything that would be useful.  The "headline" message is:

`Twig \ Error \ RuntimeError
An exception has been thrown during the rendering of a template ("Undefined array key "time"").`

**Comment by zoof** [comment]
My php is 8.0.28.  I did the upgrade from #3718 and unfortunately, it is still broken.  But unlike others from #3718, my page renders without error.  Please let me know what kind of useful information I can supply.

**Comment by rhukster** [comment]
i need more info, can you turn on full errors and give me a screenshot of the page? Need to know what file this is happening in.

**Comment by zoof** [comment]
I turned on debugging and here is a screenshot.

![grav-admin-error](https://github.com/getgrav/grav/assets/1737483/fdcc050b-3d39-44a2-86d4-ffd114c245dc)

**Comment by rhukster** [comment]
I'm unable to replicate this.  Are you fully up to date with all plugins + latest grav? from CLI do a `bin/gpm update -f` if possible.

**Comment by rhukster** [comment]
If you can access the filesystem, could you try replacing the existing `Admin::lastBackup()` method starting on line 1439 in `user/plugins/admin/classes/plugin/Admin.php` with this:

```php
    public function lastBackup()
    {
        $backup_file = $this->grav['locator']->findResource('log://backup.log');

        $file    = JsonFile::instance($backup_file);
        $content = $file->content() ?? null;

        if (!file_exists($backup_file) || is_null($content) || !isset($content['time'])) {
            return [
                'days'        => '&infin;',
                'chart_fill'  => 100,
                'chart_empty' => 0
            ];
        }

        $backup = new \DateTime();
        $backup->setTimestamp($content['time']);
        $diff = $backup->diff(new \DateTime());
        $days = $diff->days;
        $chart_fill = $days > 30 ? 100 : round($days / 30 * 100);
        return [
            'days'        => $days,
            'chart_fill'  => $chart_fill,
            'chart_empty' => 100 - $chart_fill
        ];
    }
```

**Comment by rhukster** [comment]
I could replicate it if i created an empty `user/logs/backup.log` with no data in it.  Removing the backup.log file or having a legit log file was fine.

**Comment by zoof** [comment]
> I'm unable to replicate this. Are you fully up to date with all plugins + latest grav? from CLI do a `bin/gpm update -f` if possible.

It was fully up-to-date.

> If you can access the filesystem, could you try replacing the existing Admin::lastBackup() method starting on line 1439 in user/plugins/admin/classes/plugin/Admin.php with this:

This did the trick.

> I could replicate it if i created an empty user/logs/backup.log with no data in it. Removing the backup.log file or having a legit log file was fine.

After reverting the prior change, this also worked.

Many thanks!  Upgrades have always worked without problem in the past so this was puzzling.

**Comment by rhukster** [comment]
Admin 1.10.41.2 has been released with this fix.
