### ISSUE TITLE
Homepage broke after update

### ISSUE THREAD

**Issue by JohnJonnyJohn** [getgrav/grav#3718]
After I updated (incl. plugins) yesterday (11.05.23 ~14:15), my homepage was broken. 

I am not sure how exactly this happened, but this is what I noticed:

- LangSwitcher and 1-2 other of the plugins were stopped with a red message.
- Grav wanted to update LangSwitcher v3.1.0 -> v3.1.1
- I could find out that grav wanted to download the langswitcher from this URL: `https://getgrav.org/download/plugins/langswitcher/3.1.1`, there I got a 404 until yesterday evening. Today I could download the langswitcher again under this URL.

My suspicion is that a new version has been registered, but nothing has been uploaded under the url. As a result, my homepage broke.

### My plugins:

Admin Panel v1.10.40 -> 10.41.1
Email v3.2.0 -> v4.0.0
Flex Objects v1.3.4 -> v1.3.5
Form v7.1.2 -> v7.1.3
LangSwitcher v3.1.0 -> v3.1.1
Login v3.7.3 -> v3.7.4
Page Toc v3.2.0 -> v3.2.2
Pagination v1.4.3 -> v1.4.4

Admin Power Tools v0.1.17
Auto Author v0.1.0
Auto Date v1.0.2
Breadcrumbs v1.6.2
Core Service Manager v1.1.4 
Error v1.8.0
Feed v1.9.0
JSON-LD Breadcrumbs v1.0.2
Login LDAP v1.0.2
Markdown Notices v1.1.0
Prism Highlight v3.0.0
Problems v2.1.1
Quick Tray Links v1.1.1
Simple Responsive Tables v1.1.1
SimpleSearch v2.3.0
Sitemap v3.0.2
SVG Extension v1.0.2
Translate Date v0.3.0
Webp v1.4.3

**Comment by rhukster** [comment]
There were a couple more released yesterday to fix some issues that were reported with truncation and page-tic and also lanfswircher.  All should be good now. If you force an check with bin/gpm update -f they should show up. 

If you still have an issue after updating. I will need to know the exact error message. Set errors to true (full trace) in the system.yaml to get those.

**Comment by alexfare** [comment]
Updated to 1.7.41.1 and it completely broke my website.

**Comment by dumiller** [comment]
Also broke my website.

**Comment by rhukster** [comment]
> Updated to 1.7.41.1 and it completely broke my website.

More details place, "broke my website" is not enough to go on.

**Comment by rhukster** [comment]
> I just updated today at 10:45AM UTC-6 and it also broke my grav installation. No website or admin panel.

Also, more information needed or I can't help you.

**Comment by alexfare** [comment]
> > Updated to 1.7.41.1 and it completely broke my website.
> 
> More details place, "broke my website" is not enough to go on.

I updated and I couldn't access my website. No error messages or anything. I backed up before updated so I was able to quickly recover. But I did back up the corrupted folder before hand as well. I went through the logs and didn't really seen anything. I can attempt to recreate it if you'd like, Let me know If I can do anything to log whats happening.

**Comment by rhukster** [comment]
I found one scenario where there was a blank empty `logs/backup.log` file, this fix should address that: https://github.com/getgrav/grav/issues/3715#issuecomment-1544411481

Other than that I'm not seeing any issues.

**Comment by alexfare** [comment]
> I found one scenario where there was a blank empty `logs/backup.log` file, this fix should address that: [#3715 (comment)](https://github.com/getgrav/grav/issues/3715#issuecomment-1544411481)
> 
> Other than that I'm not seeing any issues.

I attempted to recreate my issue by doing everything the same as before and I was able to successfully update to 1.7.41.1.

**Comment by dumiller** [comment]
> > I just updated today at 10:45AM UTC-6 and it also broke my grav installation. No website or admin panel.
> 
> Also, more information needed or I can't help you.

There are no errors show in my log for the last 24 hours. I have done an 

bin/gpm self-upgrade
bin/gpm update

to make all pugins are up to date. Some of them were not up to date. After a reboot my website is still in the same state. Broken. Can you recommend next steps?

**Comment by rhukster** [comment]
I've updated admin to 1.10.41.2 with a fix that was breaking for another user.

@dumiller when you say "broken" do you mean you get an error? If so what error? If you mean a blank screen then there's some PHP error, and you need to enable PHP error logging to display it, or talk to your host about where PHP error log files are stored.

**Comment by dumiller** [comment]
Fixed it with 

sudo chown -R www-data:"myuser" /var/www/html/grav

Not sure how the permissions got messed up.
