### ISSUE TITLE
 grav-admin-v1.7.41.2 is vulnerable to host header injection in forget password.

### ISSUE THREAD

**Issue by r4vanan** [getgrav/grav#3725]
# Describing problem
I found the host header injection on the host header injection vulnerability on admin forget password.

# steps to reproduce the problem.

- navigate to the forget password link http://127.0.0.1:8000/admin/forgot.
- capture the request in the burpsuite.
- change the host header value into a attackers domain.
- here you can see this domain is redirecting to the attackers domain.
![host_header_injection](https://github.com/getgrav/grav/assets/35825039/8138d8fc-3f04-4e71-beb8-94f8199fd7cd)

# PHP version
PHP 8.2.6 (cli) (built: May 9 2023 16:47:59) (NTS)

**Comment by rhukster** [comment]
Please submit security vulnerabilities in the proper place: https://github.com/getgrav/grav/security
