### ISSUE TITLE
Grav 1.7.42 crashes in Grav\Common\Utils isDangerousFunction - strtolower

### ISSUE THREAD

**Issue by softyde** [getgrav/grav#3727]
The following Twig expression leads to a crash in Utils.isDangerousFunction
```        
 {% set first_image = p.media.images|filter(i => not(i.filename starts with '___'))|first %}
```

<img width="1357" alt="Bildschirmfoto 2023-06-15 um 16 35 55" src="https://github.com/getgrav/grav/assets/24863879/e31332f5-20f6-4ce7-bbba-208c706fbddd">

Grav 1.7.42

As a workaround I was able to install 1.7.41.2 via direct installation.

**Comment by rhukster** [comment]
quick fix would be to wrap that higlighted line in a check:

```php
if (is_string($name)) {
    $name = strtolower($name);
}
```
