### ISSUE TITLE
JS pipeline generates minified version multiple times with unwanted content

### ISSUE THREAD

**Issue by kunago** [getgrav/grav#373]
I have run into an issue with JS pipeline. I currently have 2 javascript regions:
1) at the top (in head)
```
{% if browser.getBrowser == 'msie' and browser.getVersion <= 9 %}
  {% do assets.addJs('theme://js/IE/html5shiv.min.js', {'group':'header'}) %}
{% endif %}
{{ assets.js('header') }}
```
2) at the bottom (before closing body)
```
{% do assets.addJs('theme://js/jquery.smartresize.js') %}
{% do assets.addJs('theme://js/jquery.slidebars.min.js') %}
{% do assets.addJs('theme://js/jquery.owlcarousel.min.js') %}
{% do assets.addJs('theme://js/jquery.spritespin.min.js') %}
{% if browser.getBrowser == 'msie' and browser.getVersion <= 8 %}
  {% do assets.addJs('theme://js/IE/respond.min.js') %}
{% endif %}
{% do assets.addJs('theme://js/main.js', {'priority':5}) %}
{{ assets.js() }}
```

The jquery library is added in the admin plugin as a separate asset in order to overwrite the necessity to have the "jquery" defined, yet I need to use jQuery 1 for my site so I could support IE 8.

Even thought the first section should not display any output (and it does not when not using pipelining), once the pipelining is turned on, both regions receive the concantenated JS files. The first JS file contains jQuery (in the admin plugin) and featherlight (as a plugin), the second one jQuery, featherlight and the rest of JS files defined. The first appearance of jQuery and featherlight is not wanted in the head; both of the files should be only in the second file as it is the "head" JS region.

**Comment by rhukster** [comment]
At the bottom you need to be putting things into a 'footer' group.  The default group if you don't provide one is 'header'.  That is why you are seeing the same things twice. 

Better off to not use anything at the top, but use 'bottom' for the group name for all assets at the bottom.

**Comment by rhukster** [comment]
Fixed yesterday.
