### ISSUE TITLE
Group assets outputs all assets

### ISSUE THREAD

**Issue by cord** [getgrav/grav#374]
http://learn.getgrav.org/themes/asset-manager#grouped-assets

when adding a grouped asset e.g.

`{% do assets.addCss('theme://css/nucleus-ie10.css', {'priority':102,'group':'msie_10'}) %}`

the tag

`{{ assets.css({'group':'msie_10'}) }}`

returns **all** assets - also those without having specified a group.

I would expect that only the assets of the same group would be returned.

**Comment by rhukster** [comment]
This has been fixed in develop branch.  Can you try that?

**Comment by rhukster** [comment]
BTW you are doing it wrong.. you add the group with the `{'group': 'msie_10'}`, but you render by passing the group as a string: `{{ assets.css('msie_10') }}`.

The way you have it, it will not see a string, and just render the default group, hence all the other assets.

**Comment by cord** [comment]
just updated to 1.0.0RC1:

using `{{ assets.css('msie_10') }}` still gives following error
`"array_merge(): Argument #2 is not an array"`

**Comment by rhukster** [comment]
Oh I see. CSS doesn't support groups only JS. CSS is only valid in head so no point having multiple group support for it.

**Comment by cord** [comment]
would be useful to group CSS assets for e.g. MSIE compatibility

**Comment by rhukster** [comment]
Hmm. I guess I can see how having multiple groups in the head could be useful.. I can add it.. not a big deal.

**Comment by cord** [comment]
great :)

**Comment by rhukster** [comment]
Ugg. committed to master accidentally.. should be in develop now though.
