### ISSUE TITLE
Resize image in multiple sizes and get URLs

### ISSUE THREAD

**Issue by heyarne** [getgrav/grav#3742]
I'm trying to do this for a responsive background in a twig template:

``` twig
{% set img = page.media['some_image.jpg'] %}
{{ img.url(false) }}
{% set img_mobile = img.cropResize(768, 10000).quality(95) %}
{{ img.url(false) }}
{{ img_mobile.url(false) }}
{% set img_tablet = img.cropResize(1023, 10000).quality(95) %}
{{ img.url(false) }}
{{ img_tablet.url(false)
```

What I would expect is to see this output (with actual URLs instead of letters):

```
A
A
B
A
C
```

Instead what I'm seeing is:

```
A
B
B
B
B
```

What's going on? How can I get the actual URLs, how do I treat all of these as separate images instead of messing with each other?

**Comment by heyarne** [comment]
I was able to get what I wanted by using `.url` instead of `.url(false)`; my bad, maybe I didn't read the documentation correctly? I got this from here: https://learn.getgrav.org/17/content/media#resetting-multiple-calls-to-the-same-image

**Comment by heyarne** [comment]
I'm not sure if I interpret this correctly, but it seems as if the output is non-deterministic as soon as caching is involved? Is that possible? Is there a recommended way to reliably get the desired order?

**Comment by rhukster** [comment]
Rather than doing these manually for each size, maybe use derivatives?  https://learn.getgrav.org/17/content/media#sizes-with-media-queries-using-derivatives

**Comment by heyarne** [comment]
@rhukster sounds like an option! how would i get the urls of the different derivatives to use them in `background: url(...)`?

**Comment by fighterii** [comment]
Any progress on this @heyarne ?

I want to achieve a [image-set ](https://dev.to/ingosteinke/responsive-background-images-with-image-set-the-srcset-for-background-image-259a) for background-image css property.
I think the only way would be to manually set the image-set via single urls getting from the derivatives.
So basically i want to get e.g. 3 different urls for 3 different resized images.

**Comment by heyarne** [comment]
Yes, I solved this in the end, but I have to say my solution didn't give me a lot of confidence in the code quality of this particular piece of grav. As described above, the outcome is a bit unpredictable, and something happens somewhere when in these resize  calls that affects the other ones. That shouldn't be the case. There are also some issues when activating caching, so I avoid it.

What workes for me is this:

```twig
{# responsive image resizing #}
{% if page.header.hero.background_image %}
{% set img = page.media[page.header.hero.background_image] %}
{% set img_mobile = img.cropResize(768, 10000).quality(95) %}
{% set img_tablet = img.cropResize(1023, 10000).quality(95) %}

<style scoped>
#hero_{{page.id}} {
  background-image: url({{img_mobile.url|e}})
}

@media screen and (min-width: 1024px) {
  #hero_{{page.id}} {
    background-image: url({{img_tablet.url|e}})
  }
}

@media screen and (min-width: 769px) and (max-width: 1023px) {
  #hero_{{page.id}} {
    background-image: url({{img.url|e}})
  }
}
</style>
{% endif %}

```
