### ISSUE TITLE
Using clipboard with Javascript

### ISSUE THREAD

**Issue by AutomationMan808** [getgrav/grav#3751]
I have a js file that works with HTMLy. It copies the title description and URL into the clipboard so the guest can share it on social media email or whatever. I can't get it to work. Is there some security thing I need to turn off in grav to access the clipboard?

Rick

**Comment by rhukster** [comment]
No special security if you add it in a twig template. If you are trying to add it in content then yes there are some security checks to stop js injection. Also check your theme. The js might not be compatible with the theme you are using. Look in the js console for errors.
