### ISSUE TITLE
system.languages.debug: true creates faulty element when translation happens inside element

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#3752]
When using {{ "STRING.TO.TRANSLATE"|t }} outside an element, all goes well. 

However, when using a translation inside an element, it will create a faulty element. 

For example, plugin SimpleSearch uses the following input element:

```
<input
            name="searchfield"
            class="search-input"
            aria-label="search"
            type="text"
            {% if min_chars > 0 %} data-min="{{- min_chars -}}" {% endif %}
            required
            placeholder="{{"PLUGIN_SIMPLESEARCH.SEARCH_PLACEHOLDER"|t}}"
            value="{{ query|e }}"
            data-search-invalid="{{ "PLUGIN_SIMPLESEARCH.SEARCH_FIELD_MINIMUM_CHARACTERS"|t(min_chars)|raw }}"
            data-search-separator="{{ config.system.param_sep }}"
            data-search-input="{{ base_url }}{{ config.plugins.simplesearch.route == '@self' ? '' : (config.plugins.simplesearch.route == '/' ? '' : config.plugins.simplesearch.route) }}/query"
        />
```

**Comment by rhukster** [comment]
Yes. I can see that being an issue. I can’t think of any solution tho as it adds html to make it visible.  It’s only for quick debugging tho. Not intended for long term use.

**Comment by pamtbaau** [comment]
True, but a less seasoned users might get confused and consider the site to be broken, while not being to relate the issue to `system.languages.debug` as shown in this topic on [Discourse](https://discourse.getgrav.org/t/simplesearch-plugin-input-field-broken/24038).

The behaviour of `system.languages.debug` is also quite different from `system:debugger:enable: true`. Would it be possible to dump the translation debug into Clockwork too?
