### ISSUE TITLE
Inline JS is stripped of HTML tags when defined in Twig and such HTML tags are used frequently with jQuery

### ISSUE THREAD

**Issue by hwmaier** [getgrav/grav#376]
When adding inline JS using `asset.addInlineJs()` then any HTML tags contained are stripped. It is fine to strip any optionally enclosing `<script>` tags but it also strips HTML in jQuery strings like the following `img` tag:

```
{% set script %}
    $("span.heading").replaceWith('<img src="/images/corporate/heading.png">');
{% endset %}
{% do assets.addInlineJs(script) %}
```
Above currently renders ` $("span.heading").replaceWith('');`

One could just limit the stripping to optionally enclosing `<script>` tags using str_replace rather strip_tags which allows the use of the enclosing tags which is nice with code editors as they recognize the code as javascript and render it syntax highlighted.

**Comment by rhukster** [comment]
I'm not seeing it stripped, however I am seeing it converted to HTML entities by Twig.  Please try this commit: https://github.com/getgrav/grav/commit/3e3b4548e9fc960d53ef47f44c74566d87d0fde3

**Comment by rhukster** [comment]
Actually it's different from on-page and in twig.  on-page it is entities, in twig it's not.. Hence the real tags that are getting stripped in that case.  I'll dig a bit deeper and see if there is a workaround.

**Comment by hwmaier** [comment]
Re, your first comment with HTML encoding. On my system they are definitely not encoded and just stripped empty. I have 

```twig: 
#  autoescape: false
```
which I think is the default.

**Comment by rhukster** [comment]
Ok, this takes into account the html encodings that happens in a .md page, and also should remove **Only** the surrounding HTML. I think we should be good now!

**Comment by hwmaier** [comment]
Almost. The regex needs the s modifier so it works if there is a line break after the tag.
```
preg_match('#(<([A-Z][A-Z0-9]*)>)+(.*)(<\/\2>)#is', $asset, $matches);
```

Test example:
```
{% set script %}
<script>
    $("span.heading").replaceWith('<img src="/images/corporate/heading.png">');
    $("span.heading2").replaceWith('<img src="/images/corporate/heading2.png">');
</script>
{% endset %}
{% do assets.addInlineJs(script) %}
```

**Comment by rhukster** [comment]
Good call, fixed and updated.
