### ISSUE TITLE
Could the standard Grav variables like grav,config,assets etc be Twig globals?

### ISSUE THREAD

**Issue by hwmaier** [getgrav/grav#377]
More a discussion point at this stage rather a feature request.

If the site twig_vars (grav, config, site, assets, ...) would be added as globals to Twig rather as template variables this would have the benefit that they would be accessible from twig macros.

This can of course also easily be achieved using a user-specific plugin rather adding it to the core.

**Comment by rhukster** [comment]
I always have had an aversion to 'global' variables of any kind, so that's why I tend to not consider them.  However for macros you do have a valid point and i've run into this a few times.  I would need to experiment with this as it could have other implications related to variable scope with existing themes/plugins.  Worth investigating though.

**Comment by hwmaier** [comment]
I would also not make everything global per se. But The grav objects like grav, config, assets et al are more an API than global variables.

Having to pass them all to a macro, is cumbersome.

I currently add them through a plugin so I can use them in macros:

```
    public function getGlobals()
    {
        return [
            'assets' => $this->grav['assets'], // Otherwise we can't use this in macros
            'config' => $this->grav['config'], // Otherwise we can't use this in macros
            'taxonomy' => $this->grav['taxonomy'], // Otherwise we can't use this in macros
        ];
    }

```

**Comment by rhukster** [comment]
I think adding the grav object itself is a good option.  Most everything can be obtained from that.

**Comment by hwmaier** [comment]
I think too that's the best way forward. It would allow creation and publishing of self contained macros which do not depend on a global set by a plugin nor on passing down API variables.

**Comment by rhukster** [comment]
Ok will make this happen.

**Comment by rhukster** [comment]
The Grav object is now available as a global and has been removed as a template variable.
