### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by skynetindia** [getgrav/grav#3776]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: 
**Repository:** https://github.com/skynettechnologies/grav-allinoneaccessibility/

**Description:** All in One Accessibility widget improves getgrav website ADA compliance and browser experience for ADA, WCAG 2.1, Section 508, Australian DDA, European EAA EN 301 549, UK Equality Act (EA), Israeli Standard 5568, California Unruh, Ontario AODA, Canada ACA, German BITV, and France RGAA Standards.

By default it is free with limited features and users can upgrade to pro version which provide 52 plus features.

**Comment by skynetindia** [comment]
@rhukster is there any update for the plugin ?

**Comment by rhukster** [comment]
Sorry, missed this one.. It's been added to GPM

**Comment by rhukster** [comment]
Actually had to unpublish because your blueprint.yaml is malformed: 

```
Malformed inline YAML string: "All in One Accessibility widget improves #PLATFORM NAME# website ADA compliance and
  browser experience for ADA, at line 3 (near "description: "All in One Accessibility widget improves #PLATFORM NAME#
   website ADA compliance and browser experience for ADA, ").
```

**Comment by rhukster** [comment]
Please make sure its passes here: https://www.yamllint.com/

**Comment by skynetindia** [comment]
@rhukster thanks for informing
we have fixed that issues, please let us know your feedback if anything else required

**Comment by rhukster** [comment]
Do you release?

**Comment by skynetindia** [comment]
yeah we have release 1.0.1 version

**Comment by rhukster** [comment]
thanks, running now.

**Comment by skynetindia** [comment]
@rhukster we have release new version can you please check and let us know your feedback

**Comment by rhukster** [comment]
If you are checking in Grav itself, the GPM results are cached for a day, so you have to click “Check Updates”.  A good way to check is to visit https://getgrav.org/downloads/plugins (updates every hour), if it shows up there, then you are good.

![Unknown](https://github.com/getgrav/grav/assets/1084697/45aef307-cfb5-4776-bd02-190e3aaa2685)
