### ISSUE TITLE
Menu new to Grav

### ISSUE THREAD

**Issue by AutomationMan808** [getgrav/grav#3777]
Aloha,
New to Grav former HTMLy user. I created a second page but cannot seem to get it to list on the menu. I'm using Quark theme Grav v1.7.43

thank you,
Rick

**Comment by rhukster** [comment]
page should have a numeric prefix for folder name (e.g. `02.second-page/default.md`) or alternatively you can set `visible: true` in the frontmatter/header of the page.  e.g.:

```md
title: My Page
visible: true
---

# My Title

my page content
```
