### ISSUE TITLE
[add-resource] New Theme Mundana ported to Grav from Jekyll

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [getgrav/grav#3781]
Hello.

Here is the link to the github repository (https://github.com/pmoreno-rodriguez/grav-theme-mundana) for the Mundana Theme, ported to Grav from Jekyll.
It is a very fast theme, with a very good performance and to which I have included the full functionality of Blog.

See demo here: https://mundana.pmdesign.dev/

Hope you enjoy it and can add it to Grav's theme repository.
Thank you.

**Comment by rhukster** [comment]
This has been added to GPM. Merry Christmas
