### ISSUE TITLE
[Request] - add decoding="async" support like for loading="lazy"

### ISSUE THREAD

**Issue by maofree** [getgrav/grav#3794]
Hi
is it possible to add decoding="async" like loading="lazy"?
it's a new option that is added to photos, as happens with lazy loading, and grav should handle this solution too

https://fantinel.dev/web-images-modern-formats#lazy-loading-and-async-decoding

thanks

**Comment by pmoreno-rodriguez** [comment]
@maofree, I've just to send a pull request to Grav repo. You can to test with this [update](https://github.com/getgrav/grav/pull/3796).
