### ISSUE TITLE
Fatal error if opcache_compile_file is included in PHP disable_functions

### ISSUE THREAD

**Issue by reswild** [getgrav/grav#3797]
I'm getting fatal errors when I try to run Grav sites on servers where the opcache_compile_file function is restricted using disable_functions in the PHP configuration. The error I'm getting is `Call to undefined function Grav\Common\File\opcache_compile_file()`

As a workaround, I patched `system/src/Grav/Common/File/CompiledFile.php` to check for the existence of 'opcache_compile_file' instead of 'opcache_invalidate' in lines 91 and 161.

**Comment by rhukster** [comment]
i think this is a good and important error.  Haveing `opcache_comile_file()` disabled is a very rare and rather obscure situation.  I would want to know if such a function was being disabled and therefore limiting the peformance of my site. I've never run across any web hosting provider that limited this function though as it's an important one for opcache to function as it should. I suggest finding another host, or if you manage this yourself, removing that restriction.

**Comment by reswild** [comment]
The thing is, though, that you already have added an exception for this, it's just that this exception doesn't work with my particular server settings. It seems a bit inconsistent that if I restrict `opcache_invalidate()`, everything continues to work without any notification, but if I just restrict `opcache_compile_file()`, my whole site dies (and again with no notification unless I dig through my server error logs).

There is even a comment in your code that says
`// Silence error if function exists, but is restricted.`
and an `@` is added before the `opcache_compile_file` function call, but this doesn't actually do anything on my system.

My hosting solution is admittedly quite obscure, but I have seen other hosts restrict opcache functions for security reasons. I suspect the reason why more people haven't experienced this issue is that servers that restrict `opcache_compile_file()`, normally also restrict `opcache_invalidate()`, so are then covered by your existing exception.

**Comment by omega8cc** [comment]
BOA (hosting stack for Drupal) restricts two opcache functions and it also affects Grav sites hosted on BOA: `opcache_compile_file` and `opcache_reset`, however, since it's problematic for Grav, we can reduce this to just `opcache_reset` I guess.

**Comment by rhukster** [comment]
That's awesome, thanks so much @omega8cc .. i think with just `opcache_reset` being disabled, Grav should function fine. 

Just to note, having quickly looked at the relevant Grav code, setting `opache.enable=0` in `php.ini` should also skip the calls to both `opacache_invalidate` and `opcache_compile_file`.
