### ISSUE TITLE
Markdown Is Rendered Inside of Span Tags

### ISSUE THREAD

**Issue by 9p4** [getgrav/grav#3799]
`<span>**test**</span>` renders as bold, but `<div>**test**</div>` renders as plain text. I expect the `span` tag to function as a div when used in Markdown: the contents of the tags are not parsed.

**Comment by pmoreno-rodriguez** [comment]
Hi @9p4 , Have you tried ```**<div>test</div>**``` ??

**Comment by rhukster** [comment]
This is 100% expected.  markdown is not parsed inside HTML. This is a part of the markdown spec.  You can test here:

https://parsedown.org/demo (what we use)
https://spec.commonmark.org/dingus/ (another even more compliant parser)

**Comment by rhukster** [comment]
btw if you want to wrap markdown inside div's to provide some classes or styling, you can use `shortcode-core` plugin which provides simple div's and spans via `[div][/div]` and `[span][/span]` and markdown is then parsed as you expected.

**Comment by 9p4** [comment]
I think that I may not have been clear: I reported the issue that the Markdown *is* being rendered inside of an HTML tag. Furthermore, it seems as if the demos also have the same behaviour.

I expected `<span>*text*</span>` to render without italics, but it appears to be within spec.

Is there an inline container that Markdowk will not be parsed in?
