### ISSUE TITLE
Changes made to markdown file isn't showing up in the browser.

### ISSUE THREAD

**Issue by ofisia** [getgrav/grav#38]
I know the [official documentation](http://learn.getgrav.org/basics/requirements) recommended [LightPaper](http://clockworkengine.com/lightpaper-mac/) for editing markdown files, but since I'm not accustomed to it, I tried editing the markdown files using other code editors.

Surprisingly, changes made using those code editor aren't showing up in the browser (Chrome/Firefox), I even tried clearing the browser everytime I'm previewing but the problem persist. The only way to have the browser reflect the changes is by opening and re-saving the markdown files using LightPaper.

Those code editors are:
- Atom
- Brackets
- Dreamweaver
- Komodo Edit
- SeaMonkey
- TextWrangler

Encoding-related issue?

**Comment by mahagr** [comment]
Commit was supposed to be for https://github.com/getgrav/grav-plugin-admin/issues/38
