### ISSUE TITLE
@page collection does include modular pages

### ISSUE THREAD

**Issue by hwmaier** [getgrav/grav#380]
Playing around with more advance collections today revealed that when iterating over `@page` collections that they do include _modular pages as well which they shouldn't.

Using Xdebug I saw that the init method of the _modular page is called and the modular_twig flag set correctly to true at the beginning when the page tree is built.

However when later the collection is generated in the evaluate() method the $pages variable derived from $pages = self::getGrav()['pages']
contains the very same _modular page as instance but with modular_twig flag set to null which results that page included in the collection.

**Comment by rhukster** [comment]
Ok i've investigated this a bit, and i'm not seeing what you are seeing.  After this is processed:

```
$results = $pages->all($page)->nonModular()->published();
```

The results do not contain any modular pages.  Now by that i mean pages that the results don't any of the modular sub-pages that constitute a single `'modular.md` page.  They do contain the top level `modular.md` page. 

Confusing naming I know! But hope that makes sense.  Here's a screenshot of my debugger:

![2015-10-26-16-ckpef](https://cloud.githubusercontent.com/assets/1084697/10744560/6f7b909e-7c00-11e5-9b16-ccb58f27dc39.png)

Notice the `/modular` page is there as is a regular `/modular/random` page.  but none of the `_showcase`, `_features` modular subpages are in the results.

This is as expected.

**Comment by hwmaier** [comment]
If I wouldn't have kept log files from yesterday I would not believe it did happen myself. Today the issue vanished mysteriously after I tried to replicate this with a standard Grav install and now my dev site is OK as well. Maybe there was something still lurking in the cache which triggered this,

Sorry for the stir-up. I will be a bit more cautious with future reports and make always sure to replicate it with cleared cache.

**Comment by rhukster** [comment]
No problem, I actually like potential issues to be raised, it gives me the chance to double check things :)
