### ISSUE TITLE
[add-resource] New Theme: Oxygen

### ISSUE THREAD

**Issue by kittyfishfrommars** [getgrav/grav#3800]
Please add my new theme "Oxygen" to the Grav repository.

Project details: [kittyfishfrommars/grav-theme-oxygen](https://github.com/kittyfishfrommars/grav-theme-oxygen)

Changelog/Feature List: [CHANGELOG.md](https://github.com/kittyfishfrommars/grav-theme-oxygen/blob/main/CHANGELOG.md)

**Comment by rhukster** [comment]
Theme aded to GPM for next release
