### ISSUE TITLE
[add-resource] New Skeleton: Oxygen

### ISSUE THREAD

**Issue by kittyfishfrommars** [getgrav/grav#3801]
Please add my new skeleton "Oxygen" to the Grav repository.

Project details: [kittyfishfrommars/grav-skeleton-oxygen](https://github.com/kittyfishfrommars/grav-skeleton-oxygen)

Changelog: [CHANGELOG.md](https://github.com/kittyfishfrommars/grav-skeleton-oxygen/blob/main/CHANGELOG.md)

**Comment by rhukster** [comment]
skeleton added to GPM for next release
