### ISSUE TITLE
[feat] add Arbitrary Propertys to image tags

### ISSUE THREAD

**Issue by veni-vidi-code** [getgrav/grav#3802]
When using an image like `{{ some_image.html('Title', 'Alt' , 'some-class') | raw }}` there is currently no option to add specific properties such as  fetchPriority etc. As there exist quite a lot of such properties (https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement) and one might also want to override one of the properties created by html i think it is not feasible to have all of them as arguments to the html call, but rather to offer an option to add arbitrary propertys using a map. I could imagine this to look something like
 `{{ some_image.html('Title', 'Alt' , 'some-class', {fetchPriority: 'high'}) | raw }}`

**Comment by pmoreno-rodriguez** [comment]
Hi @veni-vidi-code 

Have you tried with [`attribute`](https://learn.getgrav.org/17/content/media#attribute) option?.
Example: 
```{{ page.media['sample-image.jpg'].attribute('fetchPriority', 'high').html('Sample Image')|raw }}```

**Comment by pmoreno-rodriguez** [comment]
Hi @veni-vidi-code, if my suggestion helped you, you could close this issue. Thanks
