### ISSUE TITLE
[add-resource] New Plugin String Replacer

### ISSUE THREAD

**Issue by robertotravagliante** [getgrav/grav#3804]
I would like to add my new plugin/theme named "String Replacer" to the Grav Repository.

String Replacer is a Grav plugin that allows the automatic substitution of a string contained into a post or a page. This is a useful plugin that you can use to add pure HTML, CSS, JS, and any raw content into a post, using a shortcode directly defined by user, or a previously defined string, based on his preferences.

Here are the project details: **robertotravagliante/string-replacer**

Thank you, in advance

**Comment by pmoreno-rodriguez** [comment]
hello.
What is the GitHub repository with the plugin code?
You do not provide any valid link to view this plugin

**Comment by rhukster** [comment]
link is: https://github.com/robertotravagliante/string-replacer. will add to gpm soon.

**Comment by rhukster** [comment]
Added to GPM for next release
