### ISSUE TITLE
[add-resource] New Plugin Amazon Affiliate Search Link

### ISSUE THREAD

**Issue by robertotravagliante** [getgrav/grav#3805]
I would like to add my new plugin Amazon Affiliate Search Link to the Grav Repository.

Amazon Affiliate Search Link is a plugin that adds Amazon affiliate search links in the top, middle and bottom of your pages, automatically, based on the content of your pages specified by user.

Here are the project details: **robertotravagliante/amazon-affiliate-search-link**

Thank you, in advance

**Comment by pmoreno-rodriguez** [comment]
hello.
What is the GitHub repository with the plugin code?
You do not provide any valid link to view this plugin

**Comment by rhukster** [comment]
link is:  https://github.com/robertotravagliante/amazon-affiliate-search-link

will add it shortly

**Comment by rhukster** [comment]
Added to GPM for next release
