### ISSUE TITLE
Request for attention to an already reported security issue on Grav CMS

### ISSUE THREAD

**Issue by akabe1** [getgrav/grav#3806]
Hi @rhukster, 
I am aware that this is not the channel where to report vulnerabilities of Grav CMS, but I hope so that I can finally get a response. Unfortunately, I have been trying to report a major vulnerability on this product since November 2023 (via email and github security issues section at: https://github.com/getgrav/grav/security) without receiving any response from the developers.
If possible I would publish it following responsible disclosure procedure, could you read the Github security section (or my emails) and give me a response?

**Comment by rhukster** [comment]
I’m aware of it.  I have yet to find an adequate solution that does not break compatibility. I’ll reply on the security issue when I have an update.  Thanks.
