### ISSUE TITLE
`twig-first: true` in Module makes Markdown fail

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav#3808]
When using `process: twig: true` with `twig_first: true` in a Module, the template of the module is being applied, instead of only executing Twig statements in the content string.

After applying the module's template, the still unprocessed Markdown is being surrounded with block-level elements which prohibits Markdown from being processed.

**Example using skeleton One-Page site:**
Module *01.home/03._callout/text.en.md*
```
---
process:
  twig: true
twig_first: true
---

## **Your Content** Unchained!

No longer are you a _help captive by your CMS_. Grav **empowers** you to create anything from a [simple one-page site](https://demo.getgrav.org/onepage-skeleton?target=_blank), to a [beautiful blog](https://demo.getgrav.org/blog-skeleton?target=_blank), to a powerful and feature-rich [shop site](https://demo.getgrav.org/shop-skeleton?target=_blank), to pretty much anything you can dream up!

[Find out more...](https://getgrav.org?classes=btn,btn-primary,btn-lg)

```

**Using `twig_first: false`**
![image](https://github.com/getgrav/grav/assets/5120011/eec15ec1-f608-4735-a714-304c7a63d1d2)

**Using `twig_first: true`**
![image](https://github.com/getgrav/grav/assets/5120011/e47214c0-eb07-4598-a29c-02e7cd0e8b8a)

**Comment by rhukster** [comment]
This is expected behavior for `twig_first: true`

This is an option to be used only when requiered. There are times when you need the Twig to be processed before Markdown. This can prevent markdown from processing as markdown is never processed inside HTML elements.  This is why the default procedure is to process Markdown first, and then Twig second.

**Comment by pamtbaau** [comment]
Processing Twig scripts inside a page's content works fine in Regular pages.

For example `[My Link](/{{ 'THEME_QUARK.MYLINK' | t }} )` works fine with `process: twig: true` in combination with `twig_first: true`.

It only fails in a module, which uses the template assigned to it when rendering Twig first. Wouldn't it be possible to:
1. process Twig only inside the module's content string
1. then process Markdown 
1. and after that the Twig template of the module?

**Comment by rhukster** [comment]
this probably would work if the page was not modular, but a modular page is different from a normal page where twig is processed during the content() method. You are getting in the weeds here.. frankly i would just not use the markdown link syntax at all, just use HTML or create a shortcode in this scenario and you would have no problems.

**Comment by pamtbaau** [comment]
OK, I'll feed this back into the forum. Thanks.
