### ISSUE TITLE
[add-resource] New Theme: grama

### ISSUE THREAD

**Issue by eauchat** [getgrav/grav#3815]
[Here](https://framagit.org/squeak/grama) is a newly developed theme, if you are interested in adding it to the Grav Repository, let me know.

**Comment by pmoreno-rodriguez** [comment]
Hello. Why don't you upload your code to GitHub? I think most of the Grav community uses GitHub to host their developments.
It would be interesting to see a demo of the theme online.

**Comment by eauchat** [comment]
I'm currently happy with hosting the theme out of github. Please note still that it's a public repository, freely accessible, just decentralized.
I don't know if grav supports having themes and plugins from gitlab and other forges. If not it'd be cool if it did. But I imagine that if it's hasn't already been built in, it may be complicated to implement, so if necessary I can at make some researches at how to sync the gitlab directory with one in github.

About the demo, I'll work at creating a skeleton, and having it available as a demo somewhere.

**Comment by rhukster** [comment]
As mentioned we use GitHub api so that repos must be hosted there to work with GPM.

**Comment by eauchat** [comment]
You may now test grama theme with the following [demo website](https://skelgrama.eauchat.org/). It is based on [this skeleton](https://framagit.org/squeak/skelgrama). The skeleton should already work fine, the only thing I wasn't so sure was how to properly format the `.dependencies` file, so if someone want to have a quick check at it to make sure it's fine and functional that's cool.

I haven't had time yet to look into setting up the mirroring of the repositories to github, but it should be pretty easy to do so I'll do it as soon as I can.

Are there any other issues that made you flag this issue as invalid?

I can make further corrections if needed.

**Comment by rhukster** [comment]
Just needs to be on GitHub. Cheers.

**Comment by eauchat** [comment]
Ok, here we go, both the [theme](https://github.com/eauchat/grama) and [skeleton](https://github.com/eauchat/skelgrama) are now synced with github.
If you want, you can add both to grav catalog.

**Comment by rhukster** [comment]
Added to GPM, should show up soon.

**Comment by eauchat** [comment]
Cool.
Do you plan on adding the skeleton as well?
