### ISSUE TITLE
XMPP: Post to PubSub

### ISSUE THREAD

**Issue by sjehuda** [getgrav/grav#3817]
Greetings!

In XMPP, using PubSub(1) (XEP-0060), it is possible to store posts as Atom Syndication(2) entries into XMPP(3).

There are several XMPP extensions that apply it, namely XEP-0227 (4) and XEP-0472 (5) which make node `urn:xmpp:microblog:0` as a common choice to manage news for client accounts (e.g. `blog@getgrav.org`), yet a component account (e.g. `pubsub.getgrav.org`) may use all of its nodes for this purpose.

```
pubsub.getgrav.org/
|
|-- updates/
    |-- Sombre
     `-- Varied
|-- releases/
 `-- events/
```
```
pubsub service/
|
|-- node/
    |-- item
     `-- item
|-- node/
 `-- node/
```

A PHP library that can be utilized would be Moxl of Movim.

I have made a script that realizes viewing PubSub node items as Atom XML feeds over HTTP.

1. [XEP-0060: Publish-Subscribe](https://xmpp.org/extensions/xep-0060.html)
2. [RFC 4287: The Atom Syndication Format](https://www.rfc-editor.org/rfc/rfc4287)
3. [Atom Over XMPP](https://datatracker.ietf.org/meeting/66/materials/slides-66-atompub-1.pdf)
4. [XEP-0277: Microblogging over XMPP](https://xmpp.org/extensions/xep-0277.html)
5. [XEP-0472: Pubsub Social Feed](https://xmpp.org/extensions/xep-0472.html)
6. [Moxl](https://github.com/movim/movim/tree/master/src/Moxl)
7. [PubSub Over HTTP](https://codeberg.org/poezio/slixmpp/issues/3526)

**Comment by rhukster** [comment]
Can you be more specific about exactly what you are asking about? I'm not going to read all these pubsub URLs.

**Comment by sjehuda** [comment]
Alright, shortly.

In XMPP there is an ability - which is provided in almost 100% of servers -  to upload textual content to own account. This is calld "PubSub" protocol.

The current prominent platform that extensively utilizes the PubSub system is Movim.

In the example script I have made (clause 7), I realize a simple way to fetch content from PubSub to an XML file (it can be a decorated HTML file too).

**Comment by rhukster** [comment]
There's nothing stopping you from putting your own files in any format you want into the Grav content structure.  However, you will probably want a custom plugin that intercepts the request and does the converstion of the pubsub formatted files and process them.  

Only caveat is that the Admin plugin expects 'content' to be in stored in .md files and that means it's not going to understand anything non-standard.  As long as you don't need the admin to edit/create your content, there should be no issues.

**Comment by sjehuda** [comment]
Is there a dedicated repository for plugins?

Is there a procedure to publish plugins?

**Comment by rhukster** [comment]
There’s docs on learn.getgrav.org.   Just search for “release plugin”

**Comment by sjehuda** [comment]
Thank you, Andy!
