### ISSUE TITLE
[change-resource] Take over Plugin/Theme

### ISSUE THREAD

**Issue by jwrobb** [getgrav/grav#3820]
I would like to take over an existing plugin/theme. The project is marked as abandoned and I have emailed the maintainer who has stated the same.

Here are the project details: 

* Original project **https://github.com/Perlkonig/grav-plugin-table-importer**
* My new project: **https://github.com/jwrobb/grav-plugin-table-importer**

**Comment by rhukster** [comment]
hi @jwrobb please make sure you have a 'release' first.  Nothing will show up in GPM without a current release in your repository: https://learn.getgrav.org/17/advanced/grav-development#theme-plugin-release-process

cheers,

**Comment by jwrobb** [comment]
Apologies on the churn, I should have had the release together when I submitted the take over request. I've made the updates and put out a new release.

https://github.com/jwrobb/grav-plugin-table-importer/releases/tag/v2.3.0
