### ISSUE TITLE
[change-resource] Take over Plugin/Theme

### ISSUE THREAD

**Issue by jwrobb** [getgrav/grav#3826]
I would like to take over an existing plugin/theme. The project is marked as abandoned and I have emailed the maintainer who has stated the same.

Here are the project details:

* Original project https://github.com/Perlkonig/grav-plugin-table-importer
* My new project: https://github.com/jwrobb/grav-plugin-table-importer

Current release

https://github.com/jwrobb/grav-plugin-table-importer/releases/tag/v2.3.0

**Comment by rhukster** [comment]
thanks will get on this shortly

**Comment by rhukster** [comment]
Added to GPM for next release
