### ISSUE TITLE
content not rendering UTF-8 special characters

### ISSUE THREAD

**Issue by jonata** [getgrav/grav#3833]
As shown in the image, the contents of `content|raw` are not rendering special characters. But other template elements are rendered correctly (the yellow box in this example).

![image](https://github.com/getgrav/grav/assets/908065/29931ee0-a5d2-4e7e-9b5a-f93b26e0c884)

I tried to downgrade grav and grav-admin with no success.

As a workaround, I had to add this to my templates:

`{{ utf8_decode(page.content)|raw }}`

**Comment by rhukster** [comment]
Are you using `page-toc` plugin? I found an issue there that is fixed in 3.2.4 (should be available soon).

**Comment by jonata** [comment]
Yes, I am! Great, I see there is an update, and applying it solves the problem. Thank you so much!!
