### ISSUE TITLE
[add-resource] New Plugin: Umami Analytics

### ISSUE THREAD

**Issue by chraebsli** [getgrav/grav#3836]
I would like to add my new plugin to the Grav Repository.
Here are the project details: [**Crabston/grav-plugin-umami-analytics**](https://github.com/Crabston/grav-plugin-umami-analytics)

**Comment by pamtbaau** [comment]
Just a quick note: 
Assets should be added using the [Asset Manager ](https://learn.getgrav.org/17/themes/asset-manager)instead of injecting it in the generated HTML using `preg_replace`. 

Assets can ben added when, or after, the `onAssetsInitialized` event is/has been fired.

**Comment by chraebsli** [comment]
Thanks for the feedback! I'll update it soon.

**Comment by rhukster** [comment]
Added to GPM
