### ISSUE TITLE
@collection ideas

### ISSUE THREAD

**Issue by hwmaier** [getgrav/grav#384]
This is just a note of some ideas how to add to the existing collection concept. This could be developed further into a roadmap.

This is based on a comment I submitted here: https://github.com/getgrav/grav/commit/077ba28706f38ea00804f4c39644e34e40ff0b71

```
content:
  items:
    - @page: /fruit
    - @page.descendants: /fruit  # recurse, alternative syntax to recurse flag...
    - @root   # Alternative syntax to using  @page: @root
    - @root.descendants  # Same as above but recurse
    - @self.parent    # Just the parent page
    - @self.siblings   # A collection of all other pages on this level
    - @self.modular
    - @self.children
    - @self.descendants # recurse
    - /fruit/pear     # Add just a single named page to the collection
    - /fruit/apple    # Add just a single named page to the collection
```

**Comment by rhukster** [comment]
I'll take a look at these in more detail after we get Grav 1.0 final sorted.  Thanks!

**Comment by hwmaier** [comment]
Just one point, as the recursive flag is now already in the current branch it will be hard to change later should you opt want to adopt the `.descendant` variant proposed here instead. So I think its better to make a decision now while you still can change things. Once v1.0 is out and people are using the other syntax  from https://github.com/getgrav/grav/commit/077ba28706f38ea00804f4c39644e34e40ff0b71 you can't change it any more.

You don't have to implement the full sibling set know, just make a decision whether to bring in line the @root/recurse syntax with above proposal or keep it as commited.

**Comment by rhukster** [comment]
I have modified this a little:

```
    - '@root'                                       # Get the root children
    - '@root.children'                              # Get the root children (alternative)
    - '@root.recurse'                               # Get the root and recurse through ALL children
    
    - '@self.parent'                                # Get the parent of the current page
    - '@self.siblings'                              # A collection of all other pages on this level
    - '@self.modular'                               # Get only the modular children
    - '@self.children'                              # Get the non-modular children
    - '@self.recurse'                               # Recurse through all the children
    
    - '@page': '/fruit'                             # Get all the children of page `/fruit'
    - '@page.children': '/fruit'                    # Alternative to above
    - '@page.self': '/fruit'                        # Get a collecton with only the page `/fruit'
    - '@page.recurse': '/fruit'                     # Get and recurse through all the children of page '/fruit'
    
    - '@taxonomy.tag': photography                  # taxonomy with tag='photography'
    - '@taxonomy': {tag: birds, category: blog}     # taxonomy with tag='photography' && category='blog'
```

**Comment by rhukster** [comment]
Please test when you get a chance!  Cheers.

**Comment by hwmaier** [comment]
Ah, nice.

`.recurse` is shorter to type than `.descendants`. But with `.recurse` its not clear if it will include the page itself or not. Given that recurse scenarios are used not that often I wouldn't be too concerned about the length of the keyword.
If `recurse` however does include the top page itself, then there should be an option to get just the children, grandchildren, grandgrandchidren and so forth without the page itself.
From the example above it appears that `@self.recurse` behaves different in that respect than `@page.recurse`.

The @ as I understand indicates a command which transforms a following parameter into a list of pages. As such specifying a page directly would not necessarily require a command as no transformation is performed, its just an item added directly to the list. So maybe the `@page.self` command would not really be necessary if pages can be added straight. Or maybe allow both syntaxes.

With all these additions the collections feature becomes even more powerful and this is a unique feature of Grav where other CMS require database queries to retrieve collections (sql, active records et al), your collection concept make this obsolete and easy to understand and use.

**Comment by rhukster** [comment]
I thought that recurse was clearer than descendants, but the more I think of it maybe its better to stick with the family metaphor (children/parents/siblings/decendents/etc).. I'll make the change.

@page.self is probably not necessary, but I thought for consistency it was nice, and there maybe a need to get a single page from a collection, so better to have it than to not.

**Comment by hwmaier** [comment]
Yes, @page.self complements nicely the list and make it look orthogonal.

And I could use the feature of adding single pages into a collection. So either by just @page.self or just adding the page path without command or both syntaxes.

**Comment by rhukster** [comment]
I think we are good the way things are.  It feels more consistent now. If you find any issues with any of them, please let me know.
