### ISSUE TITLE
Twig sort() not working with spaceship operator (<=>)

### ISSUE THREAD

**Issue by mjmaax** [getgrav/grav#3842]
I am using Grav 1.7.46 with PHP 8.1.
Whenever I try to use the twig Sort() function, I get an error on the spaceship operator (<=>):
```
Twig \ Error \ SyntaxError
Unexpected token "operator" of value ">".
```
I think this issue is discussed here:
https://github.com/symfony/symfony/issues/33895

**Comment by rhukster** [comment]
Grav 1.7 currently uses Twig 1.x.  Upcoming Grav 1.8 will use Grav 2.x. I think this is needed for support of <=>
