### ISSUE TITLE
Name vs Property in meta tags in page headers

### ISSUE THREAD

**Issue by diziara** [getgrav/grav#3843]
Context: Mastodon is introducing a new feature where if you include a meta tag with your fediverse handle, they'll put it into the link preview card as the author, making it easier for people to find you and read more of your content. This seems like a useful thing for a blog to make use of, so I decided to try to add the tag to my Grav sites. You can read more about it here: https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/

TL;DR: I want to include `<meta name="fediverse:creator" content="@my@fediverse.instance" />` to my Grav site.

When I attempt to do this using either the admin panel site settings, or by directly editing `site.yaml`, it instead returns `<meta property="fediverse:creator" content="@my@fediverse.instance" />` which is not what one needs for this particular meta tag. On the Grav Community forums, the closest we could get it is `<meta name="fediverse:creator" property="fediverse:creator" content="@me@fediverse.instance" />` which isn't correct because you're not supposed to have both a name and a property attribute in the same meta tag. And if I edit anything else that gets saved to `site.yaml` via the admin panel (which, let's be honest, with ADHD, I'll likely forget and do so) it'll overwrite the work around we hacked together. https://discourse.getgrav.org/t/fediverse-creator-meta-tag/25652

I can't find anything that allows me to specify which to use, or how it determines which is correct, but in this case it is not resulting in the correct thing. We need to be able to override the automagic detection when it gets it wrong like this... maybe default to whatever process the template uses, but if it's specified then instead use what's specified.

**Comment by pmoreno-rodriguez** [comment]
Hi @diziara , Have you tried with metadata.html.twig file in your theme, including this?:
```
{% for meta in page.metadata %}
<meta {% if meta.name %}name="{{ meta.name }}" {% endif %}{% if meta.http_equiv %}http-equiv="{{ meta.http_equiv }}" {% endif %}{% if meta.charset %}charset="{{ meta.charset }}" {% endif %}{% if meta.property %}property="{{ meta.property }}" {% endif %}{% if meta.content %}content="{{ meta.content }}" {% endif %}/>
{% endfor %}
```
You could take a look to [this example](https://github.com/pmoreno-rodriguez/grav-theme-editorial/blob/develop/templates/partials/page-bits/metadata.html.twig) of Editorial theme.

Then, in admin panel you could add your custom metadata. I hope this help you

**Comment by pmoreno-rodriguez** [comment]
Well, it seems that Grav tries to distinguish between social metadata and other types of metadata by using the presence of a colon separator : and the Utils::startsWith() method for specific exceptions. However, the current logic applies property to any key that contains a : separator and does not start with 'twitter' or 'flattr'.
You can see this in the file [Page.php](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Page.php), on line 1777. Yes changing that line to 
```
if ($hasSeparator && !Utils::startsWith($key, ['twitter', 'flattr','fediverse'])) {
``` 
solves the problem. Now with:
```
metadata:
 'fediverse:creator': '@my@fediverse.instance'
```
the html output is:
```
<meta name="fediverse:creator" content="@my@fediverse.instance" >
```

**Comment by diziara** [comment]
Okay. So is this something I need to override on my local installs, or is this something that's going to be pushed to the main Grav code base and I can wait for it to get folded in and push with an update? (Since Masto's feature is still in beta anyway, I'm not in a rush.)

**Comment by pmoreno-rodriguez** [comment]
Well, since it's a small change, I already made a [pull request](https://github.com/getgrav/grav/pull/3844) to the Grav development team

**Comment by diziara** [comment]
Awesome! Thank you! Hopefully they'll pick it up and include it in the next release. I'll try to keep an eye on it.

**Comment by pmoreno-rodriguez** [comment]
@diziara. This change has been [merged](https://github.com/getgrav/grav/commit/f73813103d12e25632097ded4487b6b139c9b979) into develop branch of Grav.

You could close this issue if you are ok with solution.
