### ISSUE TITLE
Nginx 404 in /admin site

### ISSUE THREAD

**Issue by jurek1337** [getgrav/grav#3847]
hi
i downloaded newest version 1.7.46 of grav + grav admin plugin
installed on turnkey debian 12

and when i am going to /index.php site i was redirected to /admin and i see 404 not found error
**while i try other subfolders like /logs, /images, i see 403 forbidden**
so imo nginx is configured **properly**
i also changed of course in nginx.conf the root of grav to **/var/www**, changed permissions, owner, and group-owner, updating the admin plugin

I will be grateful for your help

**Comment by rhukster** [comment]
Sounds like an Nginx configuration error.  Please review the sample webserver-configs/nginx.conf in the Grav installation, and also this in the docs: https://learn.getgrav.org/17/webservers-hosting/servers/nginx

if you have further questions, please ask on Discord https://getgrav.org/discord
