### ISSUE TITLE
In  Admin panel, template of module set via front-matter not picked up

### ISSUE THREAD

**Issue by mpjanus** [getgrav/grav#3852]
I had a module where I used the front-matter to set the template. In the admin page, it kept on displaying another template. In the end, I noticed that it selects the template that matches the page name and if you change it via the admin panel, it changes the file name.  On the front-end however, it will still use the template as specified in the front-matter.  This is highly confusing (took me hours to figure out), especially because the documentation of Grav states you can override the template via the front-matter. So please, do respect this setting in the Admin page.

**Comment by rhukster** [comment]
Sounds like an admin issue, please report the bug there.

**Comment by mpjanus** [comment]
so why dont you move this issue there instead of closing it?
