### ISSUE TITLE
[add-resource] New Plugin - Shortcode Swiffy Slider for Grav CMS

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [getgrav/grav#3853]
Hi. 

I'd like to add the Shortcode Swiffy Slider plugin to Grav repository.

The project and documentation are here: [https://github.com/pmoreno-rodriguez/grav-plugin-shortcode-swiffy-slider](https://github.com/pmoreno-rodriguez/grav-plugin-shortcode-swiffy-slider)

Best regards,

**Comment by rhukster** [comment]
Added to GPM for next update
