### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by mo-nonym** [getgrav/grav#3869]
I would like to add my new theme to the Grav Repository.
Here are the project details: https://codeberg.org/mononym/grav-theme-doric
Demo: https://doric.julienrippinger.eu
Releases: https://codeberg.org/mononym/grav-theme-doric/releases

**Comment by rhukster** [comment]
You need to host on GitHub to be included in GPM as our script uses the GitHub API to handle releases.

**Comment by mo-nonym** [comment]
OK, I understand. But I'm sorry, I won't do that.
c.f. https://sfconservancy.org/GiveUpGitHub/

**Comment by mo-nonym** [comment]
OK, I understand. But I'm sorry, I won't do that.
c.f. https://sfconservancy.org/GiveUpGitHub/
