### ISSUE TITLE
Unused plugin:// stream

### ISSUE THREAD

**Issue by hwmaier** [getgrav/grav#394]
Class `Grav\Common\Config\Config` contains a `plugin` stream definition which is a double up of `plugins` and it appears a redundant entry which probably should be removed to avoid any confusion which of the two is the correct one to use. I did a quick search in the core and only `plugins` appears to be used.

**Comment by Sommerregen** [comment]
@hwmaier Good point! As far as I know the `plugin://` stream was used in earlier versions of Grav (really old btw). For me the `plugins://` stream superseded this one and thus `plugin://` stream can be safely considered to be deprecated or be removed.

**Comment by rhukster** [comment]
`plugin://` and `plugins://` are used interchangeably in many plugins.  It's not save to remove it.  They equate to the same thing though.
