### ISSUE TITLE
Problem with default language and slugs that is starting with language name

### ISSUE THREAD

**Issue by mikkosalo** [getgrav/grav#395]
I have multilingual site that have many languages (en, fi, et, de ...). Let's play that english is a default language of site so English version of site is running in url http://domain.com and other languages get language slug after it (http://domain.com/fi etc.). 

Something strange happens if I create a page whose slug is for example "english" (http://domain.com/english) or something else that starts with string "en". Site gives me a 404 error and it seems that Grav is try to get pages named "glish". I debug this little and Grav debugger is telling me like this:

Grav\Common\Uri {#50
  +url: "http://localhostglish"
  #basename: "glish"
  #base: "http://localhost"
  #root: "http://localhost"
  #bits: null
  #extension: null
  #host: "localhost"
  #content_path: "glish"
  #path: "glish"
  #paths: array:1 [
    0 => "glish"
  ]
  #query: []
  #params: []
}

Is this a bug or am I missing something?

**Comment by Sommerregen** [comment]
@mikkosalo This seems like a bug. Try changing https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Language/Language.php#L165 to

```php
$regex = '/(^\/(' . $this->getAvailable() . '))(?:\/.*|$)/i';
```

**Comment by mikkosalo** [comment]
Yeah! This helped. Thank you for the quick reply!

**Comment by Sommerregen** [comment]
:smile: Ok, just wait for @rhukster to merge or to comment on this issue.
