### ISSUE TITLE
wordpress import ?

### ISSUE THREAD

**Issue by tmos** [getgrav/grav#40]
Hi,
Is there a way to import wordpress content on Grav ?

I am very interested to switch from WP to this very nice CMS :)
Thanks for your time,
Regards
Tom

**Comment by cord** [comment]
hey guys, am working on a wp plugin to export into a grav file structure. The export will support multilingual sites using qtranslate and qtranslate-slug

**Comment by cord** [comment]
Just released the wordpress plugin wp2grav to export pages, posts, authors, categories, tags into the grav format:

https://github.com/SiteBeez/wordpress-wp2grav-markdown-exporter

**Comment by simogeo** [comment]
I'll test it soon ! Thanks for sharing !
Does it handle images ?

**Comment by cord** [comment]
@simogeo just updated the documentation regarding images and link.

Also submitted to
https://wordpress.org/plugins/wp2grav/

(lets see if it gets approved...)

**Comment by simogeo** [comment]
I tested your plugin. It works well ! great job

**Comment by cord** [comment]
great! feel free to improve the code if you see any need

**Comment by mahagr** [comment]
I believe this one can now be closed. :)

**Comment by jeffmcneill** [comment]
The plugin was removed from the wordpress.org plugin site.

**Comment by Kuzmanov** [comment]
@jeffmcneill You can find the plugin here: https://github.com/SiteBeez/wordpress-wp2grav-markdown-exporter, but from the reviews on WP.org it seems it's not working.

**Comment by jeffmcneill** [comment]
Hi @Kuzmanov thanks for that. Are there any other options for doing migration from Wordpress? I see this plugin, but it looks like it only fetches, but does not store Wordpress posts. Also, I've got both posts and pages that need migration from a few different sites. https://github.com/cpannwitz/grav-plugin-fetchwp

**Comment by Kuzmanov** [comment]
@jeffmcneill No idea if there is a working plugin for migration, but I will definitely look into that and develop one :) FetchWP is not doing any migration.

Just an idea: You can export `wp_posts` in csv and create folder and `post.md` with the content using a shell script.

**Comment by jeffmcneill** [comment]
@Kuzmanov the tables are very messy. Export out to xml and then modify from there is the only sane approach I can see (which is what the previous plugin did). I'll take a look at the errors it is throwing.
