### ISSUE TITLE
selfupgrade from v1.0.0-rc.1 fails with Exception

### ISSUE THREAD

**Issue by derhasi** [getgrav/grav#400]
When trying to selfupgrade grav from `v1.0.0-rc.1`with using `bin/gpm selfupgrade` it throws an Exception:

>  [Whoops\Exception\ErrorException]
>  Undefined index: grav-update
>
>
>
> self-upgrade [-f|--force] [-y|--all-yes]

When hitting "Update Grav Now" in the admin dashboard an _Internal Server Error_ is displayed.

**Comment by rhukster** [comment]
I'm not seeing this on my test setups.  Are you able to install plugins/themes via GPM?

**Comment by fourroses666** [comment]
in admin the check for updates isn't working either.. just loading...

**Comment by rhukster** [comment]
What about installations of plugins/themes?

**Comment by fourroses666** [comment]
Plugins works

**Comment by fourroses666** [comment]
Themes get stuck also. 

I do see a blank red popupbox. 
But still have some issues with that message. 
It pops up every time when going to an other page.

**Comment by derhasi** [comment]
Meanwhile update the update to rc4 worked for me. I could start it via the admin plugin. Did not test it with the command line again. Maybe that was really a network issue, like @rhukster said in gitter.

**Comment by rhukster** [comment]
I really think it is a network or server config issue as I'm unable to replicate this even after testing on a wide variety of hosting providers. Closing for now, please reopen if you can recreate reliably.

**Comment by fourroses666** [comment]
i tried manual updating with ftp.
no luck. never had the problem with updating in admin. really doubt its the server thow. shall i try downgrading to see if its an issue with the newer version?

**Comment by khanduras** [comment]
I had a similar issue but it happen while upgrading to 1.0.-rc1. Not too sure what's causing it but I'm getting ```include_once(/usr/share/nginx/chiefqualakon-grav): failed to open stream: No such file or directory``` on web site and admin panel. Can be seen here: [chiefqualakon.net](http://chiefqualakon.net).
