### ISSUE TITLE
system/absolute_urls and lightbox

### ISSUE THREAD

**Issue by npanau** [getgrav/grav#401]
Hi,

It seeems that `absolute_url` in system.yaml disables lightbox generation if set to `true`.
When set to `false`, img are correctly turned to `<a rel="lightbox" />`
When set to `true`, img stays as img. 
Sadly I need this setting set to true for image generation in PDF...

Regards

**Comment by rhukster** [comment]
Phew! was a pain in the arse to track that down, but turned out to be a relatively simple fix.  Wasn't just lightbox, it was all media methods. They just appeared to be working due to the fallback functionality within Grav executing commands on images dynamically.  Fixed properly now.
