### ISSUE TITLE
[add-resource] New Plugin - jsonapi

### ISSUE THREAD

**Issue by npfedwards** [getgrav/grav#403]
I would like to add my new JSON api plugin to the Grav Repository.
Here are the project details: https://github.com/npfedwards/jsonapi

It's rather rough, we were trying out Grav for work and building this was part of it. Unfortunately, I wasn't able to make the case well enough for my boss to agree, so I'll only be able to develop this in personal projects. However, it's a start if someone else wants to pick it up, and I think it's useful as it stands.

**Comment by rhukster** [comment]
We actually already have an API plugin in development.  Looking at your plugin, it seems to be focused on the page content only. The one we are developing is a much more full API with many methods available. 

I appreciate your plugin, but it would conflict and cause confusion with the one we will be releasing soon, especially as your naming `jsonapi` sounds like it's a full api.  If you wish to rename this to something that better represents the scope of the plugin, i'de be glad to add it.

Cheers!

**Comment by rhukster** [comment]
https://github.com/flaviocopes/grav-plugin-api

You can see @flaviocopes 's progress here...

**Comment by npfedwards** [comment]
Hey, I totally understand. @flaviocopes plugin looks pretty awesome. I thought I might as well commit my progress.

**Comment by flaviocopes** [comment]
I think this can be named `grav-plugin-pages-json` or something similar, i can see this handy in some situations where a full API is not needed

**Comment by npfedwards** [comment]
I changed the name of the plugin/repo to what Flavio suggested, so if you want to add it to the repository, feel free to do so. I hope someone finds it useful either way.

**Comment by rhukster** [comment]
You will need to update your php and yaml filenames, as well as the classname to match.  Currently your repo is called `grav-plugin-pages-json` so grav will expect the PHP classname to be `pagesJsonPlugin`, currently it's called `JsonapiPlugin`.  You'll need to fix this or the plugin will not work.  Thanks!

**Comment by npfedwards** [comment]
Updated now.

**Comment by rhukster** [comment]
and added!
