### ISSUE TITLE
Default routes with trailing slash end up in infinite redirect loop

### ISSUE THREAD

**Issue by hwmaier** [getgrav/grav#404]
This occurs when `redirect_default_route` is set to `true`. The setting of `redirect_trailing_slash` does not matter for this to occur.

When a page's route is defined with a trailing slash and its URL is requested, Grav ends up in a redirect loop.

```
---
routes:
  default: /support/
---
```

In class Grav in the page function line 117, the trailing slash is removed.

Later in same function line 134 the path is tested against the default route and if no match, it redirects.
Because the default route has a slash but the path not, we end up in an infinite redirect loop.

**Comment by rhukster** [comment]
I can see this.  routes should not have  a trailing slash and we probably should trim them anyway.

Also wouldn't hurt to have logic to take trim that trailing slash in the redirect also.

**Comment by hwmaier** [comment]
I personally do not like routes with a trailing slash, but sometimes you want to be able migrate existing sites to Grav and keep existing and long established URLs and bring all the page SEO juice across as well.

So unless Grav can support trailing slash URLs I would not be able to use it for some sites.

**Comment by hwmaier** [comment]
I was proactive and submitted a PR. See https://github.com/getgrav/grav/pull/405

**Comment by rhukster** [comment]
This has been merged.  Thanks!
