### ISSUE TITLE
Easier access to theme configuration settings

### ISSUE THREAD

**Issue by hwmaier** [getgrav/grav#406]
If a theme has configurable entries (like for exampleantimatter does), the theme configuration values have to be accessed using code like this:
```
{% set theme_config = attribute(config.themes, config.system.pages.theme) %}
{% if theme_config.dropdown.enabled %} 
```
 or
```
{% set width = config.themes[config.system.pages.theme].width %}
```

Just an idea, Grav could automatically copy the current theme's settings into a global namespace like `config.theme` or `config.themes.current` or `page.theme`. Above code could would then simplify to this:

```
{% if page.theme.dropdown.enabled %} 
```
```
{% set width = page.theme.width %}
```
Another usage example:
```
![]my-image.jpg?resize={{page.theme.width}},0)
```

**Comment by rhukster** [comment]
It's a good idea! but i think that `theme` should even be a top level twig variable.

**Comment by rhukster** [comment]
Ok this is in there.. syntax will be:

```
{{ config.theme.dropdown_enabled }}
```
