### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by lab-dev-code** [getgrav/grav#409]
I would like to add my new theme to the Grav Repository.
Here are the project details: **https://github.com/lab-dev-code/grav-theme-identity**

**Comment by rhukster** [comment]
Can you ensure your `screenshot.jpg` is 1:1 aspect ratio, and preferably 800x800px or larger. 

Also you need a `thumbnail.jpg` also 1:1 aspect ratio, 300px x 300px

Also it would be nice if you include a screenshot in the README.md so it shows up nicely in Github. Like this:

https://github.com/getgrav/grav-theme-antimatter

**Comment by lab-dev-code** [comment]
Everything is done.
I forgot to precise that a demo is available [there](http://lab.dev-code.fr/demos/grav-themes/identity), using an out of the box Grav installation.

**Comment by rhukster** [comment]
ok thanks, will add this soon.

**Comment by lab-dev-code** [comment]
Thank you !

**Comment by rhukster** [comment]
Just keep it open until it's added :)
