### ISSUE TITLE
Admin Panel Relogin 

### ISSUE THREAD

**Issue by mkennon** [getgrav/grav#413]
When I hit the dashboard button in the Admin Panel it makes me log back in.

**Comment by rhukster** [comment]
Hi, can you please provide as much information as possible on how to replicate this.  Cleary i'm not seeing this myself, so anything would be helpful.  Perhaps you can provide a zip of your grav site in case there is something specific to your setup?

**Comment by mkennon** [comment]
It won't allow me to add a ZIP file to this post as it is not a supported file type. All I did was add a brand new install of grav with the admin panel. I can't seem to get anything to work actually. I can't add any themes or change themes even when I add a skeleton.

**Comment by mkennon** [comment]
Well now its also doing it when I try to edit a page. I'm not sure what I've done wrong

**Comment by rhukster** [comment]
First things first. Try closing your browser entirely and restarting it.  if that has no effect, try another browser (for example firefox) and see if you get the same behavior.

**Comment by rhukster** [comment]
BTW this issue really should be in the admin plugin issues, not the grav core.  I'll let it slide though :)

**Comment by rhukster** [comment]
I'll close this as there has been no more comments. Please reopen if the issue persists.
