### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by lab-dev-code** [getgrav/grav#414]
Hello !

I would like to add another theme to the Grav Repository.
Here are the project details: **https://github.com/lab-dev-code/grav-theme-lens**.

I have followed the same instructions that I did for the [Identity](https://github.com/lab-dev-code/grav-theme-identity/) theme.
A demo is available [here](http://lab.dev-code.fr/demos/grav-themes/lens), still using an out of the box Grav Installation.

I hope I didn't forget anything.

**Comment by rhukster** [comment]
your demo page is reporting an issue: http://lab.dev-code.fr/demos/grav-themes/lens

**Comment by lab-dev-code** [comment]
This is strange ... It worked and the only thing I did after that is updating Grav to RC4.
I'll investigate.

**Comment by lab-dev-code** [comment]
Fixed. A simple permissions mistake.

**Comment by rhukster** [comment]
btw i'm traveling at the moment, and will add this as soon as i can.  thanks for your patience :)

**Comment by lab-dev-code** [comment]
Okay ! Thanks :)

**Comment by rhukster** [comment]
ok should be out there! thanks!
