### ISSUE TITLE
Duplicated page entries using multi-language slugs

### ISSUE THREAD

**Issue by PeterSiegl** [getgrav/grav#415]
I have a page in english with the default slug `/en/features` and a german translation with the slug `/de/funktionen` (custom slug configured in the page header). both template markdown files include the language tags, but oddly there is a duplicated german page reachable via `/de/features`. I reproduced this issue with the multi-language skeleton using custom slugs.

**Comment by flaviocopes** [comment]
`de` is the site default language?

**Comment by PeterSiegl** [comment]
english is the default language and it makes is no difference if I explicitly define the slug `features` in the english md file or not.

**Comment by rhukster** [comment]
there is always going to be a route for every page and every language that exists irrespective of your custom route (set by slugs).  This is called the **Raw Route** and is there so you can switch between languages for a particular page.

Basically when your in English pages, Grav does not load any of the German page information.  This is a speed and memory optimization.  The only way Grav knows how to get to the German version of the page, is to use the raw route, and then, if configured, it will redirect to the **Default Route**, ie the custom one you created.  

For the most part, the raw route is not every displayed, and should not show up in links/sitemaps/etc.. it's just an internal page alias.

**Comment by PeterSiegl** [comment]
Thanks for the explanation! I activated the redirect to the default route and the language switcher plug-in works now.

It makes sense to prevent Grav from loading the additional languages, but in order to create dynamic `hreflang` tags for SEO the custom slug should be accessible somehow. Is there a way to get the links with the custom slugs after all?
