### ISSUE TITLE
Media with title (sample-image.jpg "äöå"), special character problem

### ISSUE THREAD

**Issue by markosu** [getgrav/grav#417]
Something goes wrong when setting title to image with special character 
```![Some ALT text](sample-image.jpg "Ötökät saa kyytiä. ö ä å ö ä å ")```

Screenshot from browser (Chrome ver. 46.0...)
![grav_cms_images_title_text_problem_special_characters_oaa_leikattu](https://cloud.githubusercontent.com/assets/6770959/10920304/109c1afc-8278-11e5-8f37-186820f5499f.png)

In blog item special characters works.
Skeleton: TwentyFifteen site

**Comment by lab-dev-code** [comment]
I just tried to recreate the issue but everything's fine, even if the tooltip box doesn't look the same at all :

![screenshot_1](https://cloud.githubusercontent.com/assets/15379265/10933482/0b876bfa-82d9-11e5-8a28-950eaa11719d.jpg)

TwentyFifteen site Skeleton, Chrome 46, Windows 10.

**Comment by flaviocopes** [comment]
Are you editing it through the admin panel, or via your own code editor?

**Comment by markosu** [comment]
I tested again in both way, through admin panel and nano (code editor in shell).
Same problem still exist if I add special characters through admin panel and nano.
in shell locales:
LANG=en_GB.UTF-8
LANGUAGE=en_US:en

From admin panel: Configuration - PHP Info
PHP Version 5.4.45-0+deb7u2
default_charset, no value, no value

**Comment by flaviocopes** [comment]
Try making sure that `default_charset` is set to 'UTF-8`

**Comment by markosu** [comment]
I set ```AddDefaultCharset UTF-8``` in .htaccess file on root.
Now there is in admin panel PHP Info ```default_charset UTF-8 UTF-8```

I checked what happened after change. 
Now everything works on item page file, but on blog page file (list of blog pages) special characters doesn't works when cursor is on image.

**Comment by rhukster** [comment]
I think if one works and the other doesn't, then it's just down to you having to recreate/resave the one file so the encoding is correct.  I don't think this is a Grav bug at this point.  Please reopen if you feel this statement is invalid :)
