### ISSUE TITLE
Alternative Templating engines

### ISSUE THREAD

**Issue by andrewminton** [getgrav/grav#42]
Loving what I'm reading so far with Grav and think I'd like to use it on a few projects in the near future.

One thing has cropped up that i'd like to know what peoples opinions are on alternative templating engines? Is there scope to swap out Twig for something else if we wished to used a different flavour of constructing our sites maybe?

We use XSLT and XML a lot and it would be great to think some sort of XSLT bridge similar to this: https://github.com/iwyg/xsltbridge which is for Laravel, but could possibly be ported to work with Grav?

Just putting it out there.

**Comment by matthew-dean** [comment]
Twig is kind of terrible, syntax-wise. I prefer something like Foil. http://www.foilphp.it/

But the point is that there's no reason to not make it a developer preference. I mean, why can't Grav allow a theme to use whatever template flavor they like? I don't understand why Grav would even have a horse in this race. As long as a template adapter can expose X method that can receive Y data from Grav, it shouldn't matter. (Same logic applies to YAML and Markdown, but that's a different issue.)

**Comment by rhukster** [comment]
Something we're planning for Grav 2.0.

**Comment by onedal88** [comment]
Support for [Latte](https://github.com/nette/latte) can be nice. Personally i love it.
