### ISSUE TITLE
Is there fieldset support in grav?

### ISSUE THREAD

**Issue by rovillesarate** [getgrav/grav#422]
Hi! Just wondering if grav can make fieldsets that can be edited from the admin page?

**Comment by rhukster** [comment]
Do you mean like this?

![2015-11-06 at 10 09 am](https://cloud.githubusercontent.com/assets/1084697/10989556/b85527fa-846e-11e5-99e9-36c8895cc4a5.png)

This is called the **list** field type, and it basically allows multiple iterations of other fields.

**Comment by rovillesarate** [comment]
it gets a bit confusing since it not within the content editor. plus is it limited to just modular pages? cant the field set be set from the content editor itself? or will this work with any type of page.

**Comment by mikegcox** [comment]
In Grav, you customize the admin pages using the blueprints YAML files within your theme. There are a lot of different field types available to use and you can move them around, add tabs, remove tabs etc. Look at the blueprints files, you will see the naming convention follows the same logic as template and pages files.

**Comment by rovillesarate** [comment]
I was able to put in the features fields in the content field. Just wondering how to remove the content field though. what if i just need the title and the feature field?

**Comment by rovillesarate** [comment]
I was able to put in the fields in the content tab but it wont save the fields on save.

**Comment by rhukster** [comment]
The important things is the prefix/name of the field.. Take this example:

**Comment by rhukster** [comment]
Please reopen if you continue to have problems.
