### ISSUE TITLE
Is there a members functionality in grav?

### ISSUE THREAD

**Issue by rovillesarate** [getgrav/grav#423]
Hi! How do you create members / users in grav. Cant seem to find a create user from the admin page. Is this function not yet available right now?

**Comment by wsanter** [comment]
Creating a User

With Grav , you can now create a user account with the CLI:

$ bin/grav newuser


See: http://learn.getgrav.org/admin-panel/introduction

**Comment by rovillesarate** [comment]
yes. i have seen the documentation but what if i am creating a web app and i want to create a user from the frontend? like a registration form of some sort.

**Comment by flaviocopes** [comment]
That kind of functionality is the realm of a plugin. As far as I know there's no such plugin yet. I'll add to my queue to write one core plugin soon.

P.s. for the next time, the best place for questions is the forum http://getgrav.org/forum, issues are best to be used for bug reports.
