### ISSUE TITLE
Locale twig helpers are not documented enough

### ISSUE THREAD

**Issue by mariosant** [getgrav/grav#424]
It would be nice to have multilingual twig helpers documented.

**Comment by flaviocopes** [comment]
http://learn.getgrav.org/themes/twig-filters-functions has documentation for `t` and `ta`. (just committed a fix to their visualization).

**Comment by flaviocopes** [comment]
Would you like to see more?

**Comment by mariosant** [comment]
@flaviocopes, here aresome helpers that I would like to see documented:

* Get available languages
* Get current language

I will think more about it and will post here. Thanks!

**Comment by rhukster** [comment]
http://learn.getgrav.org/content/multi-language#language-logic-in-twig-templates

**Comment by mariosant** [comment]
Awesome!
