### ISSUE TITLE
New Theme Grayscale for Grav

### ISSUE THREAD

**Issue by vmcosta** [getgrav/grav#425]
Hi guys, just wanted to contribute in some way to Grav, I've ported a Theme called Grayscale and... I would like to add my new theme to the Grav Repository.

Here are the project details:
[Grav Grayscale Skeleton](https://github.com/vmcosta/grav-skeleton-grayscale-site)
[Grav Grayscale Theme](https://github.com/vmcosta/grav-theme-grayscale)
[Grav Grayscale Demo](http://demo.vmcosta.net/grayscale-skeleton/)

This is my first one, so please let me know if somethings not right :)

Best

**Comment by rhukster** [comment]
ok should be out there! thanks!
