### ISSUE TITLE
[add-resource] New Twitch.tv Plugin

### ISSUE THREAD

**Issue by lab-dev-code** [getgrav/grav#436]
Hello !

I would like to add my new [Twitch](http://twitch.tv/) plugin to the Grav Repository.
Here are the project details: **https://github.com/lab-dev-code/grav-plugin-twitch**.

It's based on the [Youtube plugin](https://github.com/getgrav/grav-plugin-youtube) and I already got some possible improvements in mind.
~~I'll probably release a [Hitbox.tv](http://hitbox.tv) equivalent pretty soon.~~ [Done](https://github.com/getgrav/grav/issues/437). 

I hope everything's fine !

**Comment by rhukster** [comment]
added!
