### ISSUE TITLE
[add-resource] New Hitbox.tv Plugin

### ISSUE THREAD

**Issue by lab-dev-code** [getgrav/grav#437]
Hello !

I would like to add my new [Hitbox](http://hitbox.tv/) plugin to the Grav Repository.
Here are the project details: **https://github.com/lab-dev-code/grav-plugin-hitbox**.

It's the [Twitch plugin](https://github.com/getgrav/grav/issues/436) brother, sharing most of its logic.

And again, I hope everything's fine !

**Comment by rhukster** [comment]
added!
