### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by magikcypress** [getgrav/grav#442]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **magikcypress/grav-plugin-leaflet**

**Comment by rhukster** [comment]
link in the README for leaflet.com is broken.  What is leaflet?

**Comment by flaviocopes** [comment]
http://leafletjs.com

**Comment by magikcypress** [comment]
Fix it, thanks !
Leaflet an open-source JavaScript library interactive maps.

**Comment by rhukster** [comment]
added!

**Comment by magikcypress** [comment]
On grav-plugin website, the descriptive is not correct.

http://www.getgrav.org/downloads/plugins

"This plugin add [Leaflet](http://leafletjs.com) into your Grav site."

Thanks

**Comment by rhukster** [comment]
You need to do a new release with your updated text, and it will get picked up in GPM.
