### ISSUE TITLE
Utils::hash() causing error in PHP 7

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav#445]
https://github.com/tpunt/PHP7-Reference#deprecation-of-salt-option-for-password_hash

Currently passwords are hashed with custom salt, this is no longer supported in PHP 7.  Unfortunately this means that providing a non-error throwing hash method for PHP7 would result in incompatible passwords when switching to PHP 7.  Some approach needs to be discussed here.

**Comment by rhukster** [comment]
@flaviocopes this seems to be used by the new nonce functionality.  We should be safe to change right? Just remove our custom salt?

**Comment by flaviocopes** [comment]
Right, I need to rework that part
