### ISSUE TITLE
Blog child order in grav admin

### ISSUE THREAD

**Issue by fredericmohr** [getgrav/grav#446]
Hi, 

first of all thanks for GRAV, it's awesome! I'm using it for our website and blog and there is one thing that's a bit annoying when it comes to blogging. The child pages under my blog parent page are sorted by alphabet instead of publish date. (I added the numbers to represent the publishing order, 1=first, 10=newest)

![grav-blog-children](https://cloud.githubusercontent.com/assets/5955966/11207623/8fc154b6-8d16-11e5-9010-33ec7805dc23.png)

Any chance this could be changed? I had to force the order of modular pages by naming the modular pages 

_01_something
_02_something-else

But I would like to avoid that with real pages (e.g. blog posts) as it would be visible in the url later and also I would have to lookup the number of the last blog post each time I write a new one.

Thanks!

**Comment by rhukster** [comment]
This is a legit question, but can you please repost this under the admin plugin issues:

https://github.com/getgrav/grav-plugin-admin/issues

This is the wrong repo :)
