### ISSUE TITLE
Suggestion / Question Why don't we have cli hooks for pages

### ISSUE THREAD

**Issue by CoolGoose** [getgrav/grav#447]
Hi guys, I'm trying to use getgrav as a static site generator, I'm mostly there (just needed to hack the page generation to take a page id), but it would be great to have a proper hook into the cli that plugins can connect to

**Comment by rhukster** [comment]
I'm not sure what you mean by hook into the CLI? Can you provide more details of what you need?

**Comment by CoolGoose** [comment]
I'm trying to basically do a full site export as a static site. Like you would use a static site generator.

**Comment by rhukster** [comment]
You would like to create/add a CLI command from a plugin?

**Comment by rhukster** [comment]
We're working on something :)

**Comment by CoolGoose** [comment]
Let me know on how I can help ;) a plugin will come after for sure with the export part. Thanks for the quick reply.

**Comment by rhukster** [comment]
You can check in the develop branch. @w00fz has added functionality to allow a plugin to provide CLI commands.  The documentation for this is coming, but in the meantime you can look at the Error plugin which has a new command added to view logs:

https://github.com/getgrav/grav-plugin-error/blob/develop/cli/LogCommand.php

**Comment by serphacker** [comment]
@CoolGoose did you have some plugin or peace of code to share ?

I exactly want to do the same thing, I wasn't happy with static website generator like jekyll and sculpin because of their poor i18n support.

I discovered grav which is cool and have good i18n support, now i'm thinking about generating the website in html because I have really no need of php server side for the kind of website I do. (more perf, better security,  zero maintenance).

**Comment by CoolGoose** [comment]
@serphacker this week ;) i'll let you know.

**Comment by dcutting** [comment]
Hi @CoolGoose, how far did you get with this idea?

**Comment by CoolGoose** [comment]
@dcutting i pretty much had to add a processSitePage function in Twig.php that's identical with processSite only that it takes a page as a parameter.

https://gist.github.com/CoolGoose/2138f796a881f47b54f4 is the plugin code. I think i've initialized most of the things, it's just manual-ish on the current "template" that it copies over. It seems to be fine so far.

**Comment by Fil** [comment]
This tool ought to be turned into an official plugin, so grav could be used as a static site generator too.

**Comment by rhukster** [comment]
I think there will be too many compromises having a static version of Grav.  It may work in general but won't work with everything, meaning a lot of caveats. Grav was never intended to be a static site generator, and many of it's greatest features and capabilities would be unusable.

 As such it doesn't make sense for this to be an officially supported thing, better to leave it as a 3rd party plugin if someone wants to develop it.

**Comment by rhukster** [comment]
BTW @CoolGoose you could make a plugin that actually provided it's own CLI command to do this.. That way it could actually be releaesd via GPM and not just a Gist.   Look at the `scss`, `login`, or `error` plugins which all have a CLI command.. to use them they are just:

```
bin/plugin <plugin_name> <cli_command> <command_options>
```

**Comment by CoolGoose** [comment]
@rhukster my only problem is the extra ```processSitePage``` method that I need in order to generate the page themselves.
