### ISSUE TITLE
nextChild Bug

### ISSUE THREAD

**Issue by supaweb** [getgrav/grav#456]
I have set up a small portfolio website and have a next link on the gallery page. I have to gallery files with same size, same encoding. All the differences are the first file have content and the second don't. I have three gallery in portfolio. When i open gallery with working file i can cycle through all three galleries. When i replace file with non-working version i can cycle only through two items. I can find the differences, and why is it working like this. 

Attach two files and two user-folders without plugins for saving some space. Standart Grav install with admin plugin.
working file - https://yadi.sk/d/O1WzjHJqkaetH
non working file - https://yadi.sk/d/Nn8N3Ia2kaeuL
user folders - https://yadi.sk/d/WcFHqkwakafUd

**Comment by rhukster** [comment]
Those 2 files appear to be identical to me.  i thought perhaps it was an encoding thing, but seems both are UTF-8.  I can't see any differences even when diffed, so really I have no idea where to even start. 

I suggest turning off your cache, and see if that makes a difference.  Sometimes removing/adding files doesn't trigger the cache so Grav might think you only have 2 pages.  Best to disable cache in development phase.

**Comment by supaweb** [comment]
i think in such a way but when i copy non-working file back to pages directory this thing appear again. Can give you any access to server you want, any logs. Seems like amazing mystery but it couldn't be it.
Did you open attached archive and test two versions on your server?

**Comment by flaviocopes** [comment]
I tried the user/ folder but I don't know what should I look at because the site does not seem to work. Please attach a fully working user folder (with plugins) and a non-working user folder with the explanation (screenshots) of what is not working

**Comment by supaweb** [comment]
while preparing user-folder for showcase broke somehow nextChild at all.
What i did? Just delete bigger part of images, left only four images per gallery. I didn't touch template files of other pages, or parent page where pagination option is On.
Will be glad if you can reproduce my state and save how to fix this. How to add nextChild link

https://yadi.sk/d/rs98QPN5kc6Un

**Comment by rhukster** [comment]
I can't replicate this and i'm having trouble even getting the last zip file as it's on some russian yandex based site i can't understand. Please reopen if this issue is persisting.
