### ISSUE TITLE
Question: Joomla conversion

### ISSUE THREAD

**Issue by sural98** [getgrav/grav#459]
Can we expect of the Grav community a Joomla to Grav plug-in?

**Comment by flaviocopes** [comment]
If you mean something like https://it.wordpress.org/plugins/wp2grav, I hope it will happen :)

**Comment by flaviocopes** [comment]
I'm closing this since it's not an issue, more a question for the forum

**Comment by ocean123** [comment]
Its not perfect. But works for me.
https://github.com/Syndes/Joomla2Grav

**Comment by rhukster** [comment]
Hmm.. wish had not seen that before.. Wish there was some more info in the `README.md`

**Comment by ocean123** [comment]
First project ever in Github. Just uploaded 2 min ago

**Comment by ocean123** [comment]
`README.md` is now uploaded

**Comment by flaviocopes** [comment]
Added some feedback :)

**Comment by ocean123** [comment]
Thanks 👍
