### ISSUE TITLE
Undefined variable: _SESSION after upgrade 1.0.0 rc4-rc5

### ISSUE THREAD

**Issue by pbwebdev** [getgrav/grav#461]
Whoops \ Exception \ ErrorException (E_NOTICE)

Undefined variable: _SESSION
Open: /vendor/rockettheme/toolbox/Session/src/Session.php
     *
     * @param string $name
     *
     * @return mixed The removed value or null when it does not exist
     */
    public function __unset($name)
    {
        unset($_SESSION[$name]);
    }

**Comment by rhukster** [comment]
How did you upgrade Peter?  Are you running a GitHub version?  I have tested upgrading and not received this.

**Comment by pbwebdev** [comment]
Upgraded via command line.

eg bin/gpm selfupgrade -f

**Comment by rhukster** [comment]
Can you try doing a `bin/grav composer` see if that fixes it?

**Comment by pbwebdev** [comment]
worked it out

session:
  enabled: true
  timeout: 1800
  name: grav-site

Session was set to false set to true and the variable exists.

**Comment by rhukster** [comment]
Ok cool.  Yah sessions were not started.  Might need a check in there though to ensure this doesn't happen.

Thanks!

**Comment by pbwebdev** [comment]
no probs! back to bed 5am
