### ISSUE TITLE
Unauthorized in Page Deletion

### ISSUE THREAD

**Issue by umbergerba** [getgrav/grav#462]
When I click the "X" to delete a page from the page list the page simply refreshes and I get an "Unathorized" remark at the top of the page (see attachment).

"Delete" from the actual page works fine though.

![screen shot 2015-11-21 at 11 56 12 am](https://cloud.githubusercontent.com/assets/5008228/11319767/f7a2ec50-9047-11e5-869e-0d75900908f5.png)

**Comment by rhukster** [comment]
This is a missing nonce security thing I think.  We got most of them, but clearly a couple slipped through

**Comment by rhukster** [comment]
BTW this is an admin bug.. can you create the same issue there????

**Comment by umbergerba** [comment]
No sure what you mean, I am using the Admin plugin for all my GRAV sites.

**Comment by rhukster** [comment]
I'm saying you created this issue in the "Grav" repo. 

https://github.com/getgrav/grav/issues

The issue should be in the "Grav Admin Plugin" repo:

https://github.com/getgrav/grav-plugin-admin/issues

**Comment by umbergerba** [comment]
DOH! ...  yes.

**Comment by flaviocopes** [comment]
Anyway thanks for reporting, fixed in https://github.com/getgrav/grav-plugin-admin/commit/05bfe20c330e3f3a1edf6138dd79ec64488ae4b1, will get in the next update!
