### ISSUE TITLE
mkdir(): Permission denied

### ISSUE THREAD

**Issue by lid3rs** [getgrav/grav#467]
Issue appears on El Capitan OS when twig is parsing the line:
```
{{ image.resize(600, 600).url }}
```
It appears randomly and i can not find how to fix it. i did http://learn.getgrav.org/troubleshooting/permissions - no luck. My personal guess is that OS 'csrutil' makes something on background and removes permissions.

**Comment by rhukster** [comment]
What is the error???

**Comment by w00fz** [comment]
I tried replicating this but I don't get any error, I just get the URL output of the resized image as expected.
I am running El Capitan and Grav's setup for AMP (http://getgrav.org/blog/mac-os-x-apache-setup-multiple-php-versions)

**Comment by lid3rs** [comment]
Sorry. Error: An exception has been thrown during the rendering of a template ("mkdir(): Permission denied") in "portfolio.html.twig" at line 15.

As i said, error appears randomly.

**Comment by rhukster** [comment]
How do you have your El Capitan setup with Apache? Are you using the method as described in the blog post @w00fz mentioned? Are you running MAMP? Where is your webroot? What do your permissions look like (owner/group) of your files? What owner/group is your web server running under?

You said you 'did' the things recommended in the permissions guide, what exactly did you do?

**Comment by flaviocopes** [comment]
Check the owner of the assets images/ folder. Is that the same of the other folders?

**Comment by lid3rs** [comment]
Today i put a whole new grav system and copied my user folder. Now i can be sure that everything is clear. I will keep monitoring, and if it appears again i will post here.

@rhukster I am running MAMP. localhost targeted to Sites folder in MAMP config. All other settings including permissions were default.

**Comment by rhukster** [comment]
ok, closing this for now.
