### ISSUE TITLE
Installing blog breaks admin page after the latest update grav-RC5 release

### ISSUE THREAD

**Issue by danreb** [getgrav/grav#468]
Whoops \ Exception \ ErrorException (E_ERROR)

Call to a member function url() on a non-object 

 Open: /home/gravdemo/public_html/gallery/user/plugins/blog/blog.php

            $this->grav['assets']->add(sprintf('plugin://blog/css/%s_blog.css', $framework));
            if ($this->config->get('plugins.blog.add_framework_assets')) {
                $method = 'add' . ucfirst($framework);
                $this->$method();
            }
            
            $twig = $this->grav['twig'];
            $feedUrl = $baseUrl = $this->grav['page']->parent()->url();
            if ($baseUrl == '/') {
                $baseUrl = '';

**Comment by danreb** [comment]
Hi, just want to report this maybe this could be on blog plugin issues page

**Comment by flaviocopes** [comment]
Yes please report it on the blog plugin
