### ISSUE TITLE
appending a class attribute to a video.

### ISSUE THREAD

**Issue by bovisp** [getgrav/grav#469]
HI @rhukster . I've been using this code for quite a while, which appends a class attribute to an image using twig:
```
page.media.images|first.cropResize(800,800).quality(60).html('','','img--responsive')
```
It seems that I cannot do the same for videos using the code:
```
page.media['figure_19.mp4'].html('','','vid--responsive')
```
Is this a bug or is there an alternate way to append a class to a video?

Thanks!

Paul B.

**Comment by rhukster** [comment]
I'll look into it.

**Comment by bovisp** [comment]
Thanks!

**Comment by rhukster** [comment]
Ok i've added a more flexible solution.  You can still do it the way you were doing it, or you can use a new `classes` and `id` methods on medium objects.  

For example:

```
![](myimage.jpg?classes=float-left)
```

or more than one:

```
![](myimage.jpg?classes=float-left,shadow)
```

or equiv in Twig:

```
{{ page.media['myimage.jpg'].classes('float-left,shadow').html }}
```

Same goes for `id` but that only takes one argument
