### ISSUE TITLE
documentation on twig debugging

### ISSUE THREAD

**Issue by woutgg** [getgrav/grav#470]
Trying to enable twig debugging (i.e. to get text into the debug bar from statements like `{% do dump('test') %}`), I noticed some information is missing from the documentation.
Following http://learn.getgrav.org/advanced/debugging#php-debug-bar does not work; I also have to add the following:
```
twig:
  debug: true
```
In fact, disabling the `debugger: twig: true` field does not seem to have influence on debug output.

**Comment by rhukster** [comment]
Oh yes I need to remove that.  Twig actually removed the functionality needed for that to work.

**Comment by woutgg** [comment]
Just to make sure: with the yaml I mentioned, dumping variables to the debug bar works just fine.

**Comment by rhukster** [comment]
Items removed from docs.  Thanks.
