### ISSUE TITLE
translating issue - my language is trickier

### ISSUE THREAD

**Issue by diomed** [getgrav/grav#471]
So, let me explain: 

My language is trickier than just singular-plural
https://github.com/getgrav/grav/blob/develop/system/languages/hr.yaml

and when comes to this line, for example:
`WEEK_PLURAL: tjedana`

it's okay for most of it, but when numbers are 2,3,4 that line should look like this:
`WEEK_PLURAL: tjedna`

is there any way to include this also?

**Comment by flaviocopes** [comment]
This happens when using the `nicetime` twig filter, right?

**Comment by flaviocopes** [comment]
The PR linked allows to overcome this problem

**Comment by flaviocopes** [comment]
Merged, starting with the next release you can add 

_PLURAL_MORE_THAN_TWO

in addition to 

_PLURAL

**Comment by flaviocopes** [comment]
you can already post a PR for your language file so that will be included

**Comment by diomed** [comment]
ok, can you please give me example for these two, mentioned, how my code should look, and then I'll add rest of them? like - when numbers 2,3,4 = tjedna / for all the rest = tjedana

**Comment by flaviocopes** [comment]
For example after this line: https://github.com/getgrav/grav/blob/develop/system/languages/en.yaml#L84

 MONTH_PLURAL: months

add 

 MONTH_PLURAL_MORE_THAN_TWO: whatever

to your language file.

**Comment by diomed** [comment]
okay, i understand, but how will grav know when to use second one, in case of those three numbers?
shouldn't they be assigned somehow?

**Comment by flaviocopes** [comment]
You can read how here: https://github.com/getgrav/grav/pull/473/files if there's the _MORE_THAN_TWO string, it uses that when > 2

**Comment by diomed** [comment]
i think that line should be somehow limited like >2 & <5 [more than two, but less than 5] because from 5 on,,, regular plural is applied

**Comment by flaviocopes** [comment]
to what strings?

**Comment by diomed** [comment]
>2<5

SECOND_PLURAL_MORE_THAN_TWO:
MINUTE_PLURAL_MORE_THAN_TWO:
HOUR_PLURAL_MORE_THAN_TWO:
WEEK_PLURAL_MORE_THAN_TWO:
MONTH_PLURAL_MORE_THAN_TWO:
YEAR_PLURAL_MORE_THAN_TWO:


[not days!] they are the same

**Comment by flaviocopes** [comment]
I just checked, it works fine. Did you apply the fix to your code?

**Comment by Sommerregen** [comment]
@flaviocopes I think this issue is far more complicated than doing a simple check, whether there is a singular or a plural form. See for example here http://stackoverflow.com/questions/12121515/multiple-plural-forms-in-gettext.

We need something like a check here, which plural form should be used. For example for `SECOND` all forms can then go into

```
SECOND:
  - ...
  - ...
```

where `SECOND_PLURAL` can be a string (for singular word only) or an array (to include plural forms). The plural choice should happen in the `Language` class and can be hard-coded using e.g. http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html. No need to restrict some general only to the nicetime filter ;-)

**Comment by flaviocopes** [comment]
Yes this just works for the `nicetime` filter, which already had logic to determine singular/plural. Supporting languages with various forms of plurals like https://stackoverflow.com/questions/12121515/multiple-plural-forms-in-gettext is out of the scope of this PR for sure :) although would be nice to have in the future for sure

**Comment by diomed** [comment]
I updated grav today and it says 2 tjedana [incorrect] instead of 2 tjedna [correct]

in english you have a phrase like 7 days ago - and in croatian this usually isn't like that - we put word ago=prije on first place [prije 7 dana] can this be fixed somehow?

**Comment by drnasin** [comment]
@diomed sorry for reviving this thread but how did you solve this issue? I have the same problem.
