### ISSUE TITLE
Extended instructions for multisite (themes and plugins) 

### ISSUE THREAD

**Issue by HomaEEE** [getgrav/grav#472]
HELLO. Who can write more detailed instructions for setting up a multisite. For example different themes and plug-ins

**Comment by flaviocopes** [comment]
Did you already check http://learn.getgrav.org/advanced/multisite-setup?

**Comment by HomaEEE** [comment]
Yes. But I need settings for domain.:
Site1.com - theme1
Site2.com - theme2

**Comment by flaviocopes** [comment]
It's all explained here: http://learn.getgrav.org/advanced/multisite-setup#quickstart-for-beginners as you specify a user/ folder different for each site

**Comment by seandowney** [comment]
@flaviocopes The instructions were great but it seems that the Admin plugin doesn't install/update plugins or themes into the relevant directories for the site but just into the top level /user/plugins/ and /user/themes/

**Comment by flaviocopes** [comment]
Ah! That's a different issue. 
I think Admin plugin on multisite is still an untested field. Can you open an issue on the Admin Plugin with those details, just not to lose track of it?

**Comment by seandowney** [comment]
Will do, thanks.

**Comment by Legend23** [comment]
I followed the tutorial https://learn.getgrav.org/advanced/multisite-setup
but it doesn't work ... 

someone can explain me ? ><'

**Comment by flaviocopes** [comment]
Please do not crosspost between here, forum, and chat, we read them all. Choose one place to go on, here or on the forum, and explain in details what doesn't work, and what did you do.
