### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by philippspinnler** [getgrav/grav#474]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: [https://github.com/philippspinnler/grav-theme-minimalist](https://github.com/philippspinnler/grav-theme-minimalist)

I hope it meets the requirements.

**Comment by rhukster** [comment]
You need to do a release for it to show up in the the repo.

**Comment by philippspinnler** [comment]
done :)
