### ISSUE TITLE
Markdown parsing error for `www.grav.dev` literal

### ISSUE THREAD

**Issue by bobrocke** [getgrav/grav#490]
I have this Markdown:
```
At the base of my development stack is my local server run by MAMP PRO. For each project website I have a separate local folder that MAMP PRO see as a site and serves from it. So, for example, I have www.br.dev (for Grav), www.brp.dev (for Statamic) and www.materialize.dev (for Grav), plus a bunch more.
```
and it generates this output from Grav with Parsedown Extra:

![bob rockefeller - my web workflow and tools](https://cloud.githubusercontent.com/assets/2962426/11472514/252b6964-973b-11e5-8096-e5f853a7ada3.jpg)

but this from the Parsedown tester:

![better markdown parser in php - demo](https://cloud.githubusercontent.com/assets/2962426/11472533/4a389c90-973b-11e5-8dd8-3b8b460d00d7.jpg)

Do I have something set up wrong, or is there a problem within Grav?

**Comment by flaviocopes** [comment]
Is the site running on `www.br.dev`?

**Comment by bobrocke** [comment]
Yes and no.

The URL that generated the example is `http://localhost:5757/blog/my-web-workflow-and-tools?ckcachecontrol=1448887144`.

But that is being served via CodeKit's internal server that uses MAMP PRO for PHP and MAMP PRO is serving www.br.dev.

However, if I use the URL, `http://www.br.dev/blog/my-web-workflow-and-tools`, I get this output:

![bob rockefeller - my web workflow and tools](https://cloud.githubusercontent.com/assets/2962426/11473004/01b4a57e-973e-11e5-9cd0-60137d438dbf.jpg)


which looks fine.

Very strange. Something with CodeKit's server in the chain?

**Comment by flaviocopes** [comment]
Really strange. I don't get why it changes that string, which has nothing to do with the server it's running on, even the domain name is not involved.
What about running the site on MAMP without going through CodeKit? I am running MAMP, tried the same string, nothing happens.

**Comment by bobrocke** [comment]
It looks fine for me, too, straight from MAMP PRO. That's the screenshot that looks fine, above.

**Comment by flaviocopes** [comment]
So definitely something in the CodeKit changing the output for some way
