### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by absalomedia** [getgrav/grav#492]
Here's a 1.0.0 release of the Future Imperfect theme from HTML5UP ported across to Grav.

https://github.com/absalomedia/grav-theme-future/releases/tag/1.0.0

**Comment by muuvmuuv** [comment]
Looks awesome!

**Comment by absalomedia** [comment]
It's stable enough for a first release. I've noticed a few annoying typos in the documentation & if you port in any blog skeletons (e.g. https://github.com/getgrav/grav-skeleton-striped-site) it will play nice with it.  So basic blog layout is done as well as the sidebar.

The next release should be aimed at more plugin coverage & layout fixes (including Snipcart)

**Comment by rhukster** [comment]
If you find typos in the documentation, please fix them! 

All the docs are on GitHub, and there's even a link on every page that takes you right to the page in question.  There is really no reason why we can't all contribute to make the docs more accurate and better.

**Comment by absalomedia** [comment]
Andy, all documentation fixes are done. I'm already done a 1.0.1 release with the layout tweaks are done.

**Comment by rhukster** [comment]
Thanks, will add your theme today.. was busy yesterday with releases.

**Comment by rhukster** [comment]
Was added yesterday.. see issue about your thumbnails though.
