### ISSUE TITLE
Mini issue on update

### ISSUE THREAD

**Issue by CoolGoose** [getgrav/grav#497]
Hi Guys,

Just as a note (maybe for reference, and documentation updates).
I've updated grav, from rc4 to rc7, but i didn't update the plugins initially.

Doing that took me in the following funny situation 
```
-bash-4.1$ php bin/grav newuser

DEPRECATED COMMAND
  `bin/grav new-user` has been deprecated in favor of the new `bin/plugin login new-user`
-bash-4.1$ php bin/plugin login new-user
No Console Commands for 'login' where found in 'plugins://login/cli'
```

Updating the plugins obviously fixed the issue, since the user management is in the admin plugin.

**Comment by rhukster** [comment]
Where did you see this reference to `bin/grav newuser` ? I thought I had updated all the references?

**Comment by CoolGoose** [comment]
@rhukster https://github.com/getgrav/grav-plugin-admin . Want me to do a pull request ? Or just a quick fix away ?

**Comment by rhukster** [comment]
This is not something for Grav, this is something you should do in your plugin's CLI command.

**Comment by CoolGoose** [comment]
@rhukster what do you mean ? Was this related to the other issue ? At the moment it's just a documentation line change on the grav-plugin-admin .

**Comment by rhukster** [comment]
Ugg sorry, i was replying to another issue and got my tabs confused!  Please submit a PR yes.

**Comment by CoolGoose** [comment]
No problem. https://github.com/getgrav/grav-plugin-admin/pull/324
