### ISSUE TITLE
Forgot Password feature of Admin Plugin throws an error

### ISSUE THREAD

**Issue by mikegcox** [getgrav/grav#498]
From admin plugin login screen, press Forgot Password and type in a username that exists and the following error is thrown:
`Address in mailbox given [] does not comply with RFC 2822, 3.6.2.`

**Comment by flaviocopes** [comment]
Is the Email plugin correctly configured to send emails? The Admin plugin uses that for this functionality. The error most likely comes from there.

**Comment by mikegcox** [comment]
That is all it was.

**Comment by flaviocopes** [comment]
Maybe we can have a more meaningful error there.

**Comment by flaviocopes** [comment]
Handled in https://github.com/getgrav/grav-plugin-admin/commit/48f6da2bc3d748bd35c22bf3ff89eff199df0f3e
