### ISSUE TITLE
Confusing Documentation - Manually creating new user account.

### ISSUE THREAD

**Issue by danreb** [getgrav/grav#501]
I can't use CLI to create new user account as shell_exec() function was disabled on the server so manually needs to create new user. 

Reading the documentation located here -> http://learn.getgrav.org/admin-panel/faq under "Grav Admin FAQ" pointed me to manually create a file name "admin.md" instead of "admin.yaml" because of this confusing information that I think needs an update.

> User data is stored in SITE_ROOT/user/accounts/ and each user is given a YAML file containing that users login information and other details. Here is an example of the data contained within a user account file. For example this could be the content of **SITE_ROOT/user/accounts/tester.md**

> **The filename tester.md dictates the username is tester**

The documentation gives an example file with .md instead of .yaml which confuse somebody reading the documentation. Please updates it cause I started pulling my hair why it is not working just to realized i am creating a wrong file extension.

**Comment by rhukster** [comment]
I'll fix this as it's clearly a typo.  In the future, rather than opening an issue here, you can just edit the docs directly by clicking on the edit link in the top right corner.  Make your edits and then click the green "Pull Request" button.

**Comment by danreb** [comment]
Thanks... missed that "edit this page" link at the top :)
