### ISSUE TITLE
Using an invalid email address in forms, will result in Swift_RfcComplianceException

### ISSUE THREAD

**Issue by acki-m** [getgrav/grav#503]
When I input an invalid email address (e.g. 'm') in an email field, I get a php exception:
```
Swift_RfcComplianceException
Address in mailbox given [m] does not comply with RFC 2822, 3.6.2. 
```
Someone in the forum mentioned, that it is possible to enable HTML5 client side check:
http://getgrav.org/forum#!/?Swift_RfcComplianceException
However, this option does nothing, because I have it enabled, please check if this is true?

PS: In the docs I found nothing mentioned about validation rules

**Comment by rhukster** [comment]
Can you please put this in the forms plugin issues tracker:

https://github.com/getgrav/grav-plugin-form/issues
