### ISSUE TITLE
Error in AddJs/AddCss functions in Assets.php

### ISSUE THREAD

**Issue by antony-o** [getgrav/grav#513]
I was trying to add a js file using the AddJs method of the Assets class. There is an issue with the parameter $pipeline, specifically line 320 in Assets.php:

`'pipeline' => $pipeline ?: true`

This always evaluates to true, even if $pipeline is set to false. I had to change this line to:

`'pipeline' => is_null($pipeline) ? true : $pipeline`

The same error is present in the method AddCss, line 266.

**Comment by rhukster** [comment]
Thanks for reporting, will be fixed for next release.

**Comment by antony-o** [comment]
Thanks for sorting. In hindsight I should have logged this issue here, I'll make sure to do that in future.

Best,
Antony
