### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by artifex404** [getgrav/grav#514]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: https://github.com/artifex404/grav-plugin-instagram

**Comment by w00fz** [comment]
Hi! nice plugin, thank you.
There are 2 things before we can add it. 

1. There is a dependency to it self in the plugin which is not needed, you can remove the whole `dependencies` block (https://github.com/artifex404/grav-plugin-instagram/blob/master/blueprints.yaml#L14-L15)
2. You do need to a GitHub release in order for the GPM repository to pick it up

**Comment by artifex404** [comment]
Removed the dependency to itself, released the initial version 1.0.0 and refactored to use the Response class.

**Comment by w00fz** [comment]
Added to GPM, it should be picking up pretty soon on the site.

Thanks! :+1:
