### ISSUE TITLE
locale in url with base_url variable,even if include_default_lang is set to false

### ISSUE THREAD

**Issue by marsien** [getgrav/grav#523]
Hi,

There is a problem in urls when you specify to GRAV one or more languages. In my case, I specified french language (fr) only and choose FALSE for `include_default_lang` variable in admin plugin.

All urls are displayed without locale (as espected), excepted url using `base_url`, `base_url_relative` or `base_url_absolute` variables. With these variables, the locale is added in urls!

Thx

**Comment by rhukster** [comment]
Thanks will take a look at this.

**Comment by flaviocopes** [comment]
Cannot recreate this on the Multilang skeleton.

So putting this in a twig file of your theme appends the lang code in the default language pages?

{{ base_url }}
{{ base_url_relative }}
{{ base_url_absolute}}

Doesn't happen to me. While it's appended to non-default languages. Can you paste your whole language settings section in system.yaml?

**Comment by marsien** [comment]
Here the values of base_url variables when they are included in a
    twig file of the antimatter template:
    base_url = /scribavita/fr
    base_url_relative = /scribavita/fr
    base_url_absolute = http://localhost/scribavita/fr 
    
    
    The settings in my system.yaml file for languages:
    languages:
      supported:
        - fr
      include_default_lang: false
      translations: true
      translations_fallback: true
      session_store_active: false
      http_accept_language: true
      override_locale: true
      home_redirect:
        include_lang: true
        include_route: false
    
    
    Le 15/12/2015 11:09, Flavio Copes a
      écrit :
    
    
      Cannot recreate this on the Multilang skeleton.
      So putting this in a twig file of your theme appends the lang
        code in the default language pages?
      {{ base_url }}
        {{ base_url_relative }}
        {{ base_url_absolute}}
      Doesn't happen to me. While it's appended to non-default
        languages. Can you paste your whole language settings section in
        system.yaml?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by flaviocopes** [comment]
Replicated, thanks. In Twig it was always appending it when `http_accept_language` was true. I didn't have that setting on, I thought it was unrelated, but changed the result.
