### ISSUE TITLE
False positive on Issues Found page

### ISSUE THREAD

**Issue by rogerpence** [getgrav/grav#525]
After updating 'getgrav/grav-theme-bootstrap' (via the command line) Grav's Issues Page says bin/gpm, /bin/grav, /bin/composer.phar, and /bin/plugin are not executable--but they are. All show as -rwxrwxr-x and from the root, bin/grav (for example) successly launches the grav console and the admin panel displays successfully. The CLI app shows Grav CLI as 0.1.0 and the admin panel shows Grav version 1.0.4.

**Comment by rhukster** [comment]
Can you provide some information about your setup?  I can't replicate this on my local Mac.  It just works for 775 permission as you have set, and also when i change it to something else, such as 644, it gives me the error as expected.

**Comment by rogerpence** [comment]
I'm using a VirtualBox VM, Ubuntu 14.04. I abandoned my changes (which except for a small post was updating the theme) and then did a git pull of my previous version and then it ran fine. Tonight I'll work a little harder to recreate the error. I'll post more tonight.

**Comment by rhukster** [comment]
This is an issue in the problems plugin, you can always just remove the plugin or set it to `enabled: false`

**Comment by rogerpence** [comment]
Andy--it was the [Bootstrap theme](https://github.com/getgrav/grav-theme-bootstrap). I'm sorry to have caused you any time. Thank you!

**Comment by rhukster** [comment]
no worries :)

**Comment by owlas** [comment]
@rogerpence do you remember what it was about the theme that caused the problems page to fail. I'm also getting a false positive with the HPSTR skeleton.
