### ISSUE TITLE
New Plugin

### ISSUE THREAD

**Issue by muuvmuuv** [getgrav/grav#526]
I would like to add my new plugin to the Grav Repository.
Here are the project details: **muuvmuuv/grav-plugin-adsense**

**Comment by flaviocopes** [comment]
Just for consistency across plugins, do you mind changing the language strings to `PLUGIN_ADSENSE.*` instead of `PLUGINS.ADSENSE.*` ?

E.g. like
https://github.com/getgrav/grav-plugin-login/blob/develop/languages.yaml
https://github.com/getgrav/grav-plugin-form/blob/develop/languages.yaml

**Comment by rhukster** [comment]
This plugin needs a release before it will be available in GPM.

**Comment by muuvmuuv** [comment]
@flaviocopes okey I did that and updated the repo

@rhukster Its my first time using Github so how can I do that ? It was a long way until here :dancers:

**Comment by rhukster** [comment]
Ok, it's showing up in the repo now. You should be good to go!
