### ISSUE TITLE
The "(required)" contact form text in the Nucleare theme is "(obligatoire)" and I tried changing it, but it breaks the entire contact form?

### ISSUE THREAD

**Issue by Magew** [getgrav/grav#532]
I changed "obligatoire" to "required" in templates/forms/field.html.twig and it broke the entire contact form. I reverted the word change and it fixed it. What am I doing wrong?

 {{ field.validate.required in ['on', 'true', 1] ? '<span class="required">(obligatoire)</span>' }}

**Comment by rhukster** [comment]
Hi, could you please post this in the forms plugin? https://github.com/getgrav/grav-plugin-form/issues
