### ISSUE TITLE
Page blueprints and theme inheritance

### ISSUE THREAD

**Issue by hugoaf** [getgrav/grav#534]
Hi again,

I'm taking advantage of theme inheritance, and it works perfect until I get to add my own page blueprints, in that moment the original theme blueprints (blog, item, etc) quit working.

I am using bootstrap as my base theme with inheritance to my theme (called `colcif`).

Without touching blueprints, I have all working normal, like blog fields, etc:

![blog-blueprint-ok](https://cloud.githubusercontent.com/assets/8611472/11912196/5c90b64c-a5e7-11e5-95d8-f95c83568cbe.jpg)

Then I added my own blueprints for a diferente kind of page (personaje):

![mytheme-blueprints](https://cloud.githubusercontent.com/assets/8611472/11912182/952f50a4-a5e6-11e5-9422-8ada2dc7c7f4.jpg)

This new blueprints works as expected:

![personaje-blueprint](https://cloud.githubusercontent.com/assets/8611472/11912183/b78be4dc-a5e6-11e5-98cb-047e3cb8be17.jpg)

But blueprints from base theme (bootstrap) quit working:

![blog-blueprint-ng](https://cloud.githubusercontent.com/assets/8611472/11912198/639d7542-a5e7-11e5-933e-85ae8ebed2fc.jpg)

As soon I remove `my-theme/blueprints` folder the base theme blueprints fields are back in blog lista and item, etc.

If I copy all blueprints files from base theme to my theme everthing works as expected, but will be great to have page blueprints inheritance as well.

**Comment by rhukster** [comment]
We will investigate this.  Thanks!

**Comment by mahagr** [comment]
@rhukster Issue is in here:

https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Types.php#L106-L108

**Comment by rlynjb** [comment]
hello @hugoaf I was wondering if you can tell me how to go about setting up Page Blueprint? I maybe missing some configuration in .yaml file. I was able to create a Page Blueprint under my /modular directory, the fields would display on the admin page but when Save the form, the values I entered doesn't seem to save. I am not inheriting a theme though.

**Comment by flaviocopes** [comment]
@rlynjb make sure your fields are named `header.something`, check how your blueprint differs from the Antimatter theme ones for example.
