### ISSUE TITLE
Image resize bug

### ISSUE THREAD

**Issue by katrynvonfelsen** [getgrav/grav#538]
There is a problem with the resize module. Ii create a weird background image that I can't get rid off 😅

![image](https://cloud.githubusercontent.com/assets/416462/11916674/1ada929a-a6af-11e5-9843-2cef53918057.png)

The GRAV version is  version 1.0.5 and is running locally on MAMP for Mac!

Cheers
Catherine

**Comment by rhukster** [comment]
What is the resize command you are using?  There are many different variations.  [resize](http://learn.getgrav.org/content/media#resizewidth-height-background) itself will put a background behind the image if the new size is not the exact aspect ratio as the original. You can change the color of course, but it's more likely you are actually looking for another method.

I suggest you try using [cropZoom](http://learn.getgrav.org/content/media#cropzoomwidth-height):

> With cropZoom, the image is resized so that there is no background visible, and the extra image area of the image outside of the new image size is cropped.

**Comment by katrynvonfelsen** [comment]
I use the _?resize=400,200_ command.
The fact is that with the _resize_ command name, I do not expect the creation of a background image in the post content wrapper. Here are the things that I have done without success to remove the _background image_ :

- Removing all the images from the text box
- Deleting the media from the post

What is weird is that is I delete the post and create another one with the same name, the same background keep coming back Ô_o

**Comment by rhukster** [comment]
These names are coming directly from the Image package we are using: https://github.com/Gregwar/Image

We really don't have any control over them.  I've tried to make the documentation as human-readable as possible.

if you change the type of resize to `cropZoom` a new image should be generated.  If you are having trouble with images being deleted, try clearing the cache.

**Comment by katrynvonfelsen** [comment]
But yes your proposed function is working and the syntax is logic to my eyes  so that is perfect :)

cheers,
C

**Comment by rhukster** [comment]
Great :) closing...
