### ISSUE TITLE
[add-resource] Theme Library

### ISSUE THREAD

**Issue by khanduras** [getgrav/grav#547]
A theme that makes use of the UIKitifier plugin. Based on YooTheme's UI Kit and is a reimagining of the Agency theme one-pager and a news section.

https://github.com/khanduras/grav-theme-library

**Comment by rhukster** [comment]
really could do with a better quality screenshot here. It's very blocky?

**Comment by khanduras** [comment]
How's that?

**Comment by rhukster** [comment]
https://raw.githubusercontent.com/khanduras/grav-theme-library/master/thumbnail.jpg

it's not 'smooth'. it should resample when resized.  This doesn't look bad to you??

**Comment by khanduras** [comment]
OH I thought you were looking at screenshot.jpg

That was using monosnap. Going from 2736x2736 resolution to 300x300 is tough.

I tried it again and it doesn't look any better. How can I resample with monosnap?

**Comment by rhukster** [comment]
I actually don't use monosnap for resizing.. just taking snapshots. I just use the built-in `preview` that comes with OS X, or I use Affinity Designer if I have it open.  Dont' really know the options on a PC.

**Comment by khanduras** [comment]
I'm trying GIMP. How's that?

**Comment by khanduras** [comment]
Looks a little blurry now.

Can you try taking screenshot.jpg and sizing it down to 300x300?

**Comment by rhukster** [comment]
Looks way better though :)

**Comment by rhukster** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1084697/11937701/33fe9c92-a7d3-11e5-8f33-7513ba2fe257.jpg)

Here's my version.  Probably shoudln't keep that HUGE image in the repo.. 1.5mb just for a screenshot is crazy.

**Comment by rhukster** [comment]
![thumbnail](https://cloud.githubusercontent.com/assets/1084697/11937745/87424804-a7d3-11e5-839f-c794253c22ea.jpg)

BTW this was your original to compare

**Comment by khanduras** [comment]
Ahh yikes, much better.

I think my ducks are in a row now.

**Comment by rhukster** [comment]
Oh i guess you deleted your screenshot file.. The release failed because it was not there. I just suggest making it smaller in size pixels and kb.  As soon as you add it your theme should get picked up in the next GPM refresh.

**Comment by khanduras** [comment]
I want some of what this guy is smoking ^^

In all seriousness:
 ![](https://github.com/khanduras/grav-theme-library/blob/master/screenshot.jpg?raw=true)

Never deleted it

**Comment by khanduras** [comment]
1024x1024 @ 356 KB is [too large](https://github.com/khanduras/grav-theme-library/blob/master/screenshot.jpg)?

**Comment by khanduras** [comment]
I downloaded the latest release and it had a large screenshot rather than the one we were seeing in Github. I recreated the release and it has the smaller version. Hopefully that gets picked up. :)

**Comment by rhukster** [comment]
Worked on my local.  Should get picked up in the next GPM update in a few minutes.
