### ISSUE TITLE
Can't install with mutualise webhoster OVH

### ISSUE THREAD

**Issue by fbardel** [getgrav/grav#551]
Hi,

Thanks for this great job :)
I have an issue when I want to see the website :
![issue_grav_admin](https://cloud.githubusercontent.com/assets/5451956/11942795/3eacfba0-a839-11e5-811f-ed3f039244b0.png)
All the folder bin is not executable.
Version 1.0.5.

Thanks

**Comment by rhukster** [comment]
Can you please change these files so they are executable?  That is what the error is telling you.  You can do this from SSH via `chmod +x bin/*` from the root of your Grav install.

**Comment by fbardel** [comment]
Oh sorry, I'm tired ^^
The SSH don't work with personal OVH plan, but it works with Filezilla (0704) ;)
Thanks...
