### ISSUE TITLE
When I click on the category(s) of a post it brings me to the front page.

### ISSUE THREAD

**Issue by Magew** [getgrav/grav#552]
Each blog post has a link to its category and takes you to /en/category:photography (obviously depends on category name). However, that only brings me to the front page (home).

**Comment by rhukster** [comment]
really this is dependent on your theme, page, and category setup. 

In the blog skeleton for example, the main 'blog/list' view is the homepage, so anything that filters the list (ie taxonomy filtering) should take you to the homepage.

What exactly are you expecting? and what are you getting?  What is your question?

**Comment by Magew** [comment]
I see. I was not sure if this was an issue or not. I know that at least with Wordpress and other systems, clicking on the category would normally take you to a list of posts in that category.

My homepage is static and not a blog list view, so when it takes me to the homepage that seems odd or unexpected, because why would someone click that to get there? You know? If thats dependent on the theme, then I should be modifying that? Where can I find out the variable that will input the link to the category it is referencing to? (if thats something that is already set that is)

**Comment by rhukster** [comment]
You really have to provide the link you want to go to via the Twig.  Grav doesn't necessarily know where that listing page is.  If you started with a blog skeleton that had the listing at the root, the twig is probably written to still point there.  Grav is a bit more manual in things like this. 

In Grav a theme is not something you just drop in and your site is magically transformed.  There is a direct relationship between the theme and the content.  I tried to explain things here: http://getgrav.org/blog/traditional-cms-platforms-and-grav

It sounds like a negative, but actually it means the theme can be much more customized and lets Grav easily do things like documentation sites, blogs, landing-pages etc.  This is why we have skeleton packages as these really are able to showcase the relationship between a theme and the content.

**Comment by Magew** [comment]
Completely understood. I highly enjoy the versatility of Grav and the simplicity it has right now. I am actually finding it to be much more easier to understand/learn than most systems. I'm new to it, but I love it. I am starting to really grasp how great it is and I enjoy the fact that its not just click and play with everything, because the problem I had with Wordpress was feeling like the website wasn't what I wanted and would be displeased with it.

With Grav, I am patiently adjusting everything manually and tweaking it to what I want, including adding configuration options and toggles and what not for my own ease.

I'll see if the theme I've been altering has what I need already, and if not I'll see if I can't figure it out on my own and then report back to here with the solution for others to see.

**Comment by rhukster** [comment]
Awesome, closing for now.  Hop on our Gitter.im chat if you have more questions.
