### ISSUE TITLE
Httponly and secure cookie flags

### ISSUE THREAD

**Issue by ArnCo** [getgrav/grav#553]
Hi,

Httponly and secure cookie flags do not seem to be set in ./system/src/Grav/Common/Session.php. 

Is there any plan to let users choose to set these flags in the configuration panel ?

Keep up the good work !

ArnCo

**Comment by flaviocopes** [comment]
@ArnCo added a PR to support this, good idea. Would you mind testing it too?

**Comment by ArnCo** [comment]
Hi @flaviocopes ,
Glad to read that. No problem to test it.
