### ISSUE TITLE
Adding to assets from a plugin for a modular page fails

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav#562]
The mechanism described below works for a simple page, but not if the page is modular. Is it expected behaviour? Would it be addressed or left as is?

### Description:

One 'module' of the modular page causes a plugin to call 
```php
$assets = $this->grav['assets'];
$assets->addJs('plugin://blabla.js', null, true, null, 'bottom');
```
That's because I think assets must only be loaded if used in the page.

### Current workaround

This works for both normal pages and modular pages. Add the asset from inside the ```onTwigSiteVariables()``` event handler. *But that causes unnecessary file traffic for java script and CSS from plugins that are unused for most pages.*

### Side note
A website typically has different types of pages (intro, contact, blog, photos, etc) making use of a different set of plugins. Grav's plugin (even those official provided by the Grav team) inject CSS and/or javascript for _each_ page of the site. Even if the plugin's functionality is unused. Can you propose a workaround that functions correctly for modular pages?

thanks

**Comment by rhukster** [comment]
This is actually a known issue, it' not a trivial one to solve because a modular page is actually just part of other pages that are processed together and cached as the content of the parent page.  Once cached, there's no more processing of anything so things like assets are lost.

**Comment by aptly-io** [comment]
Hi Andy,

Thanks for the explanation. 
I tried to follow your workaround; disabling caching, is that adding the following line in the header?
```cache_enable: false```
I tried to both the module and containing page but the plugin's assets don't show up ... I found this header line in the form's tutorial on the learn site (6. Advanced/Forms)? BTW Is this also why the headers of the form are inside the main modular page?

As another workaround, I added a specific header option ```force_assets_on_modules``` for the plugin so that it is forced to include its assets in the main modular page (even if the plugin is not used in the main modular page itself, only in one of its sub module page).

That works partly; when loading the page the first time, the plugin contents show up. But if the page is refreshed (or reloaded), the plugin's assets are included only in _the very first refresh_, subsequent refreshes don't add the assets anymore :-( Even with ```cache_enable: false```. Very odd, why just the 1st refresh cause the ```onPageContentProcessed``` called, and not next refreshes/reloads.

Merry Christmas 

PS I also tried this to no result:
```yaml
cache:
  enabled: false                             # Set to true to enable caching
twig:
  cache: false                               # Set to true to enable twig caching
```

**Comment by aptly-io** [comment]
Oke, I found ```cache_enable``` in ```Page.php```'s ```content()``` by step-debugging.

As I understand the flow-control, the main modular's page ```Assets.js("head")``` is called before its sub-modules are processed? So even if a sub-module adds assets for the ```head```, this never makes it inside the HTTP response. Only assets for the ```body``` still make it in the response.

Couldn't the generation of the response data be postpone untill all main, and sub modular pages are processed? This gives sub modular pages the opportunity to add assets for the head (of the main modular).

**Comment by rhukster** [comment]
Actually this should now be fixed also.  Now `cache_enable: false` will cause the page to be reprocessed properly.

https://github.com/getgrav/grav/commit/52544a8b25c1e5e61f6a1627db8598bc302817a0

let me know if that fixes your issue.

**Comment by rhukster** [comment]
Also i've updated the **Assets** plugin to work with cached pages.  It basically does what you mentioned above by storing the assets in Grav's cache for future use when the page is cached, and the inline assets tags have been processed and striped put.
