### ISSUE TITLE
Plugins are redownloaded for plugins with same dependencies

### ISSUE THREAD

**Issue by mosid** [getgrav/grav#563]
Consider the following plugins are installed
- Admin
- Login  
When updating,the admin plugin checks for its dependencies - which in this case it includes the login plugin - and update them. 
After that the update process checks the login and its dependencies - which is already updated -  and update it again.  
I think there should be a plugin dependency version check before every single plugin update.  
![grav](https://cloud.githubusercontent.com/assets/5040354/11999847/f8e5c55a-aad8-11e5-91ee-f81d71052ea9.png)

**Comment by rhukster** [comment]
Yah, this is a known issue. Definitely something we want to improve going forward.

**Comment by rhukster** [comment]
Closing this as we are developing this currently and any issues regarding that (when ready) should be opened as a new issue.
