### ISSUE TITLE
cache_enable: false does not trigger onPageContentProcessed

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav#564]
Found after investigating solutions for defect #562 . Andy describes setting ```cache_enable``` to ```false``` in that defect.

When setting ```cache_enable: false``` in a header does not cache the twig output indeed. However the *markdown-to-html* is cached in ```cachePageContent()```. This function broadcasts the ```onPageContentProcessed```. This gives plugins an opportunity to post-process the *markdown-to-html* just before it's cached on disk.

When the page is requested a second time, the markdown is fetched from the cache. A plugin's ```onPageContentProcessed``` is never triggered in this case.

I would assume ```cache_enabled: false``` does not do any caching. This would cause plugin's to be called (as suggested in #562).

Maybe these lines (508..510) in Page.php (tagged 1.0.6)
```php
                    if (!$cache_twig) {
                        $this->cachePageContent();
                    }
``` 
should become something like 
```php
                    if (!$cache_twig) {
                        self::getGrav()->fireEvent('onPageContentProcessed', 
                                  new Event(['page' => $this]));
                    }
```

However since this is already long in the code base, might it break existing web sites since we are now 1.0.x ... (likely it only affects a slowdown due to no markdown caching?)

There's also a semantic issue. Depending on the ```cache_enable``` plugins work on *markdown-to-html* or *twig-to-html*; what is a stage further. It's my (personal) feeling that plugins should always get the same content, independent of the value of  ```cache_enable``` (that should just be about caching as it name suggests).

**Comment by rhukster** [comment]
Should be fixed by: https://github.com/getgrav/grav/commit/dc9b9509d7bc0815a212aeb7a3f56477c8029c13
