### ISSUE TITLE
Assets object only has data inside its inline-js data member

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav#565]
Can it happen that ```Assets``` has data inside its ```inline_js``` but not its ```js```? In this case might it be skipped in ```Assets.js()```? Because the first conditional makes it return on ```js``` only. Unless I misunderstand something, perhaps change this
```php
        if (!$this->js) {
            return null;
        }
```
as follows:
```php
        if (!$this->js && !$this->inline_js) {
            return null;
        }
```

PS I have the same observation for handling the data members ```css``` and ```inline_css```.

**Comment by flaviocopes** [comment]
While unlikely, you're right, that could happen. The above commit fixes the issue :+1:
