### ISSUE TITLE
Question on caching css, js

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav#567]
I was wondering if theres' a reason (like e.g. HTTP-specification wise or technical) for not caching the css and js? I noticed it's sometimes a considerable amount of data.

I saw how ```Page.php``` is caching markdown or twigged content with a cache id based on a ```$this->id```.

As a small trial I replaced in ```base.html.twig``` the ```{{assets.js(['bottom'])}}``` and ```{{assets.css()}}``` with ```{{page.js(['bottom'])}}``` and ```{{page.css()}}```.

In Page.php I added this function (leveraging the $this->id):
```php
    public function js($group = 'head', $attributes = [])
    {
        $cache_enabled = isset($this->header->cache_enable) ? $this->header->cache_enable : true;
        $cache_id = md5('page-js'.$group.$this->id());
        if ($cache_enabled) {
            $cache = self::getGrav()['cache'];
            $js = $cache->fetch($cache_id);
        }
        if ($js === false) {
            $assets = self::getGrav()['assets'];
            $js = $assets->js($group, $attributes);
            if ($cache_enabled) {
                $cache->save($cache_id, $js);
            }
        }
        return $js;
    }
```

So instead of going straight to ```Assets```, I go through ```Page```, just for reasons that `Page` contains already a lot of cache code and its id. This seems to work. Of course more work might be required for handling the css/js pipelining (I did not understand this completely yet).

An advantage of using cached css/js is that the plugins no longer need to inject mindlessly css and jss for every type of page.

**Comment by rhukster** [comment]
Assets are generally not page specific.  

There is a use-case for page-specific assets though, although I think you should add CSS/JS to cache with a plugin that basically does what you coded into the Page object.
