### ISSUE TITLE
JavaScript assets are not initialized if there are only inline scripts

### ISSUE THREAD

**Issue by stianlik** [getgrav/grav#572]
I'm using the [grav-ganalytics](https://github.com/escopecz/grav-ganalytics/blob/master/ganalytics.php) plugin to handle GoogleAnalytics for a site without any JavaScript code. This plugin use the `onAssetsInitialized ` event to add inline javascript so I expected that the following code in my site header would be sufficient to make the plugin work:

```Twig
{{ assets.js() }}
```

However, this did not render any JavaScript at all. From further investigation I found that it did not render any JavaScript registered using `assets.addInlineJS()` unless I included a call to `assets.addJs()` somewhere in the theme. As a workaround I'm currently registering a dummy script:

```Twig
{% do assets.addJs('dummy', { group: 'dummy' }) %}
{{ assets.js() }}
```

Adding a dummy script works for now, but I assume this is a bug?

**Comment by flaviocopes** [comment]
Yes it's a known issue, already fixed in develop by https://github.com/getgrav/grav/commit/492b290845551c7800fa43979622ece26c813293, will be in the next release :+1:
