### ISSUE TITLE
Renaming site causes breakage

### ISSUE THREAD

**Issue by Corwin7** [getgrav/grav#573]
If you have a running grav site, `/var/www/html/www1.example.com`, and move it to `/var/www/html/www2.example.com`, it breaks because the site is hardcoded:

```
vendor/composer/autoload_classmap.php:$baseDir = dirname(dirname(dirname($vendorDir))).'/html/www1.example.com';
vendor/composer/autoload_psr4.php:$baseDir = dirname(dirname(dirname($vendorDir))).'/html/www1.example.com';
vendor/composer/autoload_namespaces.php:$baseDir = dirname(dirname(dirname($vendorDir))).'/html/www1.example.com';
vendor/composer/autoload_files.php:$baseDir = dirname(dirname(dirname($vendorDir))).'/html/www1.example.com';
```

The site works as soon as the site name is changed in those four files. My config is a little different as Grav and the modules are installed with symlinks, and I also previously ran `bin/composer.phar install` to fix things due to this config.

Renaming the site directory used to work. Grav rocks! Thanks. :)

**Comment by flaviocopes** [comment]
Run into this before. This is not an issue in Grav, but rather it's an issue in Composer.

What happens is that if the `vendor` folder is symlinked, Composer adds a path in a relative way until if finds the folder where `composer update` was run.

In my example: `$baseDir = dirname(dirname(dirname(dirname($vendorDir)))).'/www/grav';` is hardcoded in the vendor/composer/autoload_*.php` files.

The solution then is to regenerate the vendor folder if you move the site to another path.

I'm not aware of a solution to this, googled a bit but I couldn't find anything, if you find a way to avoid this, ping :)
