### ISSUE TITLE
Missing installation step in readme and docs

### ISSUE THREAD

**Issue by yurimorini** [getgrav/grav#576]
Maybe is implicit but following instructions in http://learn.getgrav.org/basics/installation using **Option 2: Install from GitHub** after cloning repo and before using the `bin/grav` command you must launch composer to install deps. 

This step is missing from the docs and it's not straightforward for someone.

**Comment by yurimorini** [comment]
Here I've found
> (v0.9.2+) If you installed Grav from GitHub, the vendor folder won't be included with it. You will have to run bin/grav install **or** composer install from the root of your Grav instance in order to get the vendors installed. More details can be found under the installation section.

but for my installation `bin/grav` produces error for missing autoload files solved running composer before grav.

I'm on a win10 platform

**Comment by rhukster** [comment]
yah this is a bug in the docs.. you would  need to have composer on your system.

Updated.
