### ISSUE TITLE
Extending site.yaml blueprint in Grav Admin does not work

### ISSUE THREAD

**Issue by mikewink** [getgrav/grav#578]
I'm trying to extend the "Site" tab (based on site.yaml) in Grav Admin with my own blueprint file. I've created a .yaml file in the blueprints folder in my theme called mysite.yaml. The content can be seen here:

https://gist.github.com/mikewink/174c8652d41065e911c1

The problem I have is that the new form fields don't show up anywhere on the site form in Grav Admin. 

Thank you for any help or advice how to help fixing that in Grav itself.

**Comment by mahagr** [comment]
@rhukster @flaviocopes I don't think we ever implemented anything like this into admin.

**Comment by rhukster** [comment]
Currently you can't extend or override the `site.yaml` via the theme.  However you can override via the `user/blueprints/config/site.yaml`.

We do have plans to rework the blueprints locations a bit in the next major version of Grav to allow blueprints to be defined in plugins and be more flexible in how you can extend them.  So I'll close this for now and we'll revisit it later.  Thanks!

**Comment by OleVik** [comment]
@mahagr and @rhukster was this ever implemented for themes?

**Comment by mahagr** [comment]
Not really, though it may work now as there have been some improvements on blueprint inheritance. The main configuration is still loaded very early (before anything else is set up), so you need to tweak streams configuration to allow overrides to be detected by the system.
