### ISSUE TITLE
Images deleted from images folder using gpm to install plugin

### ISSUE THREAD

**Issue by locii** [getgrav/grav#580]
Not sure if I've done something wrong but have just installed the sitemap plugin using terminal on my local installation and that process has resulted in the removal of images in my images folder.

1. Latest version of grav
2. Add an image to the images folder
3. use bin/gpm install sitemap to install the site map
4. Images are gone.

Not sure if this is specific to the plugin but I recall this happening another time that I installed a plugin (sorry cant recall which one) - so have posted this here just in case.

Thanks

**Comment by rhukster** [comment]
The cache is cleared after doing a `bin/gpm` install. This includes the auto-generated images stored in the `images/` folder.  

However, they should be regenerated the next time you hit the page.

**Comment by locii** [comment]
Yes that happened but my manually placed image files were also removed. Is it best not to use the images folder for manually added images?

Thanks!

**Comment by rhukster** [comment]
Oh yah, definitely do not put your own images in that folder.  I would suggest putting them in a `user/pages/images` folder that way you can reach them via `page->find('/images')` and also you can find them easily via markdown and perform operations on them: `![](/images/my-image.jpg?cropResize=300,300)`.

Alternatively you can put them in your theme, as that is easily accessible via CSS references.
