### ISSUE TITLE
External images meta files filters are not applied

### ISSUE THREAD

**Issue by giansi** [getgrav/grav#581]
I try to add a metafile to apply some filters to an image as explained here http://learn.getgrav.org/content/media#metafiles but they are not applied.
My image is named image1.jpg, so I added an image1.jpg.media.yaml under the same folder with this code inside:

    image:
        filters:
              default:
                  - [brightness, -30]

but filter is not applied.

**Comment by rhukster** [comment]
Thanks for the reminder.  I'll look into this.

**Comment by rhukster** [comment]
Should work fine, but you need to name the file correctly.  You have `media.yaml` and it should be `meta.yaml`

Image filename: `sample-image.jpg`
Meta filename: `sample-image.jpg.meta.yaml`
