### ISSUE TITLE
Invalid security token

### ISSUE THREAD

**Issue by adi8i** [getgrav/grav#589]
I get this error often when save, change theme, logout and when i want to login.

**Comment by rhukster** [comment]
Can you provide a ZIP of your site?

**Comment by adi8i** [comment]
@rhukster would be better if you can log in on C9, i can share the workspace

**Comment by rhukster** [comment]
No I really need a zip so i can try to replicate locally.  I trust you are getting the message, i need to find out why, and I can't debug the code on your end.

**Comment by rhukster** [comment]
BTW, I see you mentioned in Gitter.im you have Gantry5 installed.  That is VERY EARLY beta.  Try removing that and see if your issues go away.

**Comment by adi8i** [comment]
Yeah, i got `Oops there was a problem, please check your input and submit the form again.` when i try to create the username on a clean installation. 

I manually created the username, i have to hit login lot of times to work.

Looks like i am the only one having this issues, i use c9, but is not the best option as i see... Is useful because i can share the website and others can see what i work on, otherwise is not really what i need.

I am closing it for now, because it's a clean installation, nothing added.
