### ISSUE TITLE
.htaccess Dependency Issue on IIS

### ISSUE THREAD

**Issue by sekjun9878** [getgrav/grav#59]
On systems such as IIS and nginx, the .htaccess is not used at all.

However, Grav seems to require a .htaccess file during requirement checking. This can be worked around by adding a dummy .htaccess but really this should be supported natively with IIS semi-officially supported on the documentation.

**Comment by rhukster** [comment]
Ive just removed this check from the problems plugin.  it's really should not have been required

**Comment by sekjun9878** [comment]
Thanks!
