### ISSUE TITLE
[add-resource] New Theme Prickly Pear

### ISSUE THREAD

**Issue by MATsxm** [getgrav/grav#590]
I would like to add my new theme to the Grav Repository.
Here are the project details: https://github.com/CaribThemes/grav-theme-pricklypear

Bonjour everyone,

If you are interested and want to add it, I have just finished the first release of a theme named Prickly Pear. This is a very first try to understand how Twig and Grav are working, then thank you for your feedbacks & remarks you think would be useful or required.
If you think this may interest the Grav Community, I can also build a Skeleton.

![prickly-pear](https://cloud.githubusercontent.com/assets/1972717/12119728/a6fdbc42-b3a3-11e5-960f-5a6d465ec3fa.jpg)

Thank you
Best regards,

**Comment by MATsxm** [comment]
**v1.0.1** with Demo Simple Data added (I hope the right way :wink:  )

**Comment by rhukster** [comment]
FYI, only pages work with _demo content.  And even then it wont install via admin, only via GPM.  If you wish to provide a full config, you should look at developing a skeleton package - http://diblas.net/blog/how-to-build-a-grav-skeleton

**Comment by rhukster** [comment]
done
