### ISSUE TITLE
[add-resource] New Theme - Bones Vanilla

### ISSUE THREAD

**Issue by benblee** [getgrav/grav#591]
I would like to add my new theme to the Grav Repository.
Here are the project details: **https://github.com/smartgravity/grav-theme-bones-vanilla**

I think the theme needs to be added first before the skeleton, so I can require the theme in the dependencies of the skeleton.

**Comment by benblee** [comment]
Here is a zip of a sample "/pages" directory to test the theme with sample content.
[pages.zip](https://github.com/getgrav/grav/files/79275/pages.zip)

**Plugins that can be included in a test install are:**
- Archives
- Breadcrumbs
- Featherlight
- Random
- RelaatedPages
- TaxonomyList
- SimpleSearch

**Comment by rhukster** [comment]
You know you can have pages in an `_demo` folder, and grav will prompt you to install the sample data when you install the theme.

Check this example out:  https://github.com/nunopress/grav-theme-developer

**Comment by rhukster** [comment]
done
