### ISSUE TITLE
canonical // page.url

### ISSUE THREAD

**Issue by B-iggy** [getgrav/grav#593]
Hey grav devs,

in my current setup I get always http in my canonical though I'm running https in admin and front-end. Do you know how to customize the canonical?

Additionally page.url(true) gives me at the end of my url a port. (e.g. example.com:12345) But this URL doesn't work. Is this the failure of my hoster / setup?

My setup:
nginx running under a certain port behind apache. So only this port gives me access to my nginx webserver.

**Comment by rhukster** [comment]
So.. you have a reverse proxy setup?  Where externally it's port 80 or 443 and internally it's some other port?

1) I'll double check the canonical code to see if `http://` is hardcoded in there.

2) That is probably why when you ask for `page.url(true)` you get that internal port as that is what the client (proxy) is accessing with. There's not a whole lot we can do other than let you override the port somehow. This is a pretty uncommon setup however, in fact i've never seen it before.  You will probably be ok by not passing (true) and just going based on the protocol.

**Comment by B-iggy** [comment]
Thank you rhukster for your answer!

Yeah, you are right. Basically it's a hoster where you can do a lot by yourself in the terminal but without root and it's shared hosting. It's because they don't support nginx and I build it on my own but with this port / proxy setup.

1) thanks

2) yes, makes sense. I'm asking the support in the mean time about my configuration.
Sure I could use relative paths but Google wouldn't be happy with it ;)
https://support.google.com/webmasters/answer/139066 (in the middle of the page:
Avoid errors: use absolute paths rather than relative paths with the rel="canonical" link element.

Use this structure:  https://www.example.com/dresses/green/greendresss.html
Not this structure: /dresses/green/greendress.html).
")

**Comment by rhukster** [comment]
Ok, so quick test and things look fine on Grav site.  `page.url(true)` works properly.  If you access the page with https:// it will insert that back into the full URL. See my screenshot:

![route testing grav 2016-01-07 10-30-09](https://cloud.githubusercontent.com/assets/1084697/12177491/aa04add8-b529-11e5-9205-52d927ac7b8a.png)

I think your reverse proxy is proxying https to http internally.  This is why the URLs are showing up with http://.  You should ensure your actual webserver is running https://

BTW, You are not really gaining anything by reverse proxying from apache to nginx.  Your basically going to bottleneck at apache, and slow things down even more than just a plain apache setup.  Now, if you were reverse proxying from nginx to apache, that's a different story.  You get the benefits of nginx for performance, and the convenience of apache for configuration via .htaccess.  ServerPilot does this to great effect.  We are doing this for getgrav.org too.

Regarding your Google reference.  That stuff is way overrated :)  I've been doing this web development stuff **for a long time**, and while those are valid recommendations, they are really not required at all, in fact most of the time they cause more trouble than they solve. Same goes for the `.html` suffix.  Grav supports all these things, but really they are not worth even bothering with.

I personally never use canonical URLs, and I always use relative paths, and never ever use extensions unless i want something non-html.  It makes things more readable, portable and outputs less code, less complicated to process, many reasons.  It's never hurt me in anyway, in fact getgrav.org for example (which doesn't do these things) is very highly ranked for SEO. 

I can give you a great example. if you search for "mac os x apache", something that is quite generic and not even very grav-specific, getgrav.org comes up #3 in google (at least for me) :)

https://www.google.com/?#q=mac+os+x+apache

The secret to good SEO is good content.  Everything else makes up such a small part of the equation that it becomes irrelevant.

**Comment by B-iggy** [comment]
Hey rhukster,

sorry for the delay. Figured some things out with my Hoster and my nginx setup. So basically it's this thing https://en.wikipedia.org/wiki/Pound_(networking)
And I figured out why it wasn't https (wrong nginx fastcgi_params conf).

But the port problem is still there. I looked around and found in this file following lines:
https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Uri.php#L57

If I comment this out the port disappears and my problems are solved ;)
Well... why is it there? I mean why you asking hardcoded if port 80 or 443?
What if - like me - someone has a reverse proxy setup with xxx port?

@canonical topic: I trust you in. For me it isn't on #3 in google (maybe 'cause you are logged in google? [you get different search results when you are logged in - but you know this for sure]) but yeah, content is the king. Unfortunately my port problem isn't solved if I use relative paths for this.
The backup tool using absolute paths too when I try to download my backup (error).

**Comment by rhukster** [comment]
Regarding line #57.. if you are running a normal scenario but are running your site on say port 8080, then the full URL needs to have this port in the URLs or subsequent requests will be on the wrong port.  Your running a reverse proxy where the SSL port on your internal machine is not the standard port, say 1443, but externally it's standard port 443, so this 1443 port gets added to your URL because Grav thinks your running non-standard and therefore needs it.

I guess i'll need to add some config option to toggle on/off a reverse proxy setup, because Grav simply cannot determine this automatically.

**Comment by B-iggy** [comment]
Yes, that is the case for me.
That would be awesome! :) (already loving the configuration page in Grav)

**Comment by rhukster** [comment]
For now leave it commented out...

**Comment by B-iggy** [comment]
Alright. Thanks so far!

**Comment by rhukster** [comment]
https://github.com/getgrav/grav/commit/9a3005e3c57d703e16ba265d6dd548944752b7ba is the commit that adds this functionality.

**Comment by B-iggy** [comment]
Hey, it's me again ;)
Great commit, I'm just wondering why it's not in the release but says it is.
After normal update -> reverse proxy option not in there
After download from here: http://getgrav.org/downloads -> not there
After removing everything from webspace and put it there again -> not there
Challenge accepted -> downloading only the develop zip -> it's there but look at the screenshot.
If you look at the packages https://github.com/getgrav/grav/releases the commit isn't there but here it says it should be there? https://github.com/getgrav/grav/compare/1.0.8...develop
I'm confused ;)
Just to let you know. Maybe my mistake.
![unbenannt](https://cloud.githubusercontent.com/assets/7815434/12217446/20334784-b701-11e5-92ff-6c31bad17451.PNG)

**Comment by flaviocopes** [comment]
As you can see in https://github.com/getgrav/grav/commits/develop the 1.0.8 release was made before the commit that Andy referenced, so it's not in the latest release.

**Comment by B-iggy** [comment]
yeah, just checked the changelog too. Sorry. All good.
