### ISSUE TITLE
Post schedule

### ISSUE THREAD

**Issue by akhyarrh** [getgrav/grav#599]
Sometime I write my post at night and forgot to publish it. Have a post schedule plugin would be great.

AFAIK only [wardrobe](https://github.com/wardrobecms/wardrobe) have this feature. But wardrobe are outdated (latest commit Apr 2014).

**Comment by rhukster** [comment]
Actually Grav already supports this.  Simply set a `publish_date' in the future and your post will get published appropriately. http://learn.getgrav.org/content/headers#publish-date
