### ISSUE TITLE
feature request: page update time for modular pages

### ISSUE THREAD

**Issue by simonhaenisch** [getgrav/grav#600]
The date for the last update of a page that is modular is the update time of the page markdown file, but I think it should be the update time of the module that was last modified, because thats the real update time of that page. The sitemap plugin uses this date for the sitemap and thus it seems a homepage wasn't updated even though the modules changed.

**Comment by flaviocopes** [comment]
Seems a good improvement to me

**Comment by flaviocopes** [comment]
Can you test the linked PR?

**Comment by rhukster** [comment]
I looked at this PR and while this should resolve the issue in most cases, tecnically a modular page can be defined by a variety of options that are set in the page header, not just children.  So to to do this properly it would have to use the modular page's collection, not just the children.

**Comment by rhukster** [comment]
@simonhaenisch Please test the latest updates to the PR so I can close this.  Cheers.
