### ISSUE TITLE
meta generator

### ISSUE THREAD

**Issue by B-iggy** [getgrav/grav#603]
Hey,
I understand why you do it but can you add an option to optional let the meta tag generator for GravCMS be set though?
Speaking of this line: https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Page.php#L1156

**Comment by flaviocopes** [comment]
Just set in site.yaml (or in Admin, in Site configuration)

```
metadata:
  generator: "Your Custom Generator"
```

**Comment by B-iggy** [comment]
I know this. But if I don't want a generator at all. What should I do? An empty generator is not valid HTML code.

**Comment by flaviocopes** [comment]
Ah I misunderstood then. My PR #604 should fix this. Can you give it a try?

**Comment by B-iggy** [comment]
If it's empty it's fixed and nothing shows up. But if I delete the meta setting this comes up:
```
<meta property="generator:name" content="generator" />
<meta property="generator:content" content="GravCMS" />
```

**Comment by flaviocopes** [comment]
Right, fixed in https://github.com/getgrav/grav/commit/3da70797771a485547532a70892a27a54805b985

**Comment by fstelzner** [comment]
This worked for me (i removed the author as well):

**Change metadata.html.twig to:**

`{% for meta in page.metadata %}

{% if meta.name == "generator" or meta.name == "author"%}
   {# skip #}
{% else %}
	<meta {% if meta.name %}name="{{ meta.name }}" {% endif %}{% if meta.http_equiv %}http-equiv="{{ meta.http_equiv }}" {% endif %}{% if meta.charset %}charset="{{ meta.charset }}" 
	{% endif %}{% if meta.property %}property="{{ meta.property }}" {% endif %}{% if meta.content %}content="{{ meta.content }}" {% endif %}/>
{% endif %}

{% endfor %}`
