### ISSUE TITLE
How can I realize that my items appear in the Blog

### ISSUE THREAD

**Issue by AlexL777** [getgrav/grav#607]
Hello Developers,
I discovered your Grav CMS and would like to run it for testing.

Now I have installed it and am just trying to publish an item in the blog. Unfortunately, the items do not appear in the blog and I do not understand why.

The blog is in my under **/blog** and a new item is then **/blog/myItem** and I can view from the backend out me this Item.

But when I'm in the blog at /blog I do not see the items.

How can I help myself. I work a lot with WordPress and I have to get used. Therefore, the first steps are a bit difficult.

Can you help me maybe?

Thank you in advance.

**Comment by rhukster** [comment]
The **easiest** way is to download a skeleton with a blog, for example, the "Blog Site"   - https://github.com/getgrav/grav-skeleton-blog-site/releases/download/1.1.1/grav-skeleton-blog-site-v1.1.1.zip

This is a full blow Grav + Theme + Content + Plugins example, simply extract.

The bit that you want to look at specifically is the `01.blog/blog.md` file that basically defines the blog. 

https://github.com/getgrav/grav-skeleton-blog-site/blob/develop/pages/01.blog/blog.md

This sets up the page collection (`items: @self.children`), and then Grav gathers up the child pages and this is collection by the associated `blog.html.twig` file:

https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/blog.html.twig#L22-L24

Hope that helps explain it!

**Comment by AlexL777** [comment]
Thank you, that helped me a lot! And a question I have for the time being still.

How to add the content to "Some text widget" at Theme Afterburner? This can be seen with me in the right sidebar under http://wpzweinull.ch/cms/gravweblog/grav/de/blog

**Comment by Endogen** [comment]
@AlexL777 Do you want to remove "Some text widget" form the sidebar? If so, then edit this files (or the correspondent file for your theme) `antimatter/template/partials/sidebar.html.twig`. Search there for the text.

**Comment by AlexL777** [comment]
OK thanks! Now I use a different theme and can in the Sidebar also place a "AboutMe" info. That's even better.
