### ISSUE TITLE
Routes rewritten if no custom redirects set up

### ISSUE THREAD

**Issue by skunca** [getgrav/grav#610]
If you remove the default custom redirects and routes, the URL gets rewritten:

> /some/url/20501

turns into

> /some/url/251

This was in IIS (Azure Web App).

**Comment by flaviocopes** [comment]
Can you please provide a step-by-step on how to reproduce this? Which settings did you change? What is the page exact URL? If you can, check if it also happens under Apache or Nginx, to check if it's an environment issue or not.

**Comment by rhukster** [comment]
Will close soon unless you comment with more information....

**Comment by skunca** [comment]
Sorry about dropping out. So, step by step:
* download grav + admin 1.0.8
* unpack, copy the web.config into root and deploy to web server (Azure Web App, PHP 5.6, default settings)
* go to /admin, create a user, log in, create a page called "agency101"
* add media to the page (in my case a zip file named agency-10203.txt.zip)
* create a link on the page by drag-dropping the uploaded media item
* test the link on the page, all good at this point
* go back to /admin and remove all redirects in Configuration -> Redirects & Routes

After doing this, looking at the created page when I hover over the link I can see it pointing to the correct location but after I click on it I get redirected to:

    blahblah.azurewebsites.net/agency11/agency-123.txt.zip

The zeroes in both the page stub and the filename are gone. Same behavior on Apache 2.4.16 on OSX.

**Comment by rhukster** [comment]
Thanks I can definitely replicate this now.. will see what's going on.

**Comment by rhukster** [comment]
Ok so tracked this down.. Here's the thing.  When you delete all the redirects and save the empty list in the admin, it actually saves as:

```
redirects:
  - ''
```

This is actually required to override the default redirects coming from `system/config/site.yaml` which are the examples.  However, this was being treated as a valid Regex pair of `0` the index, and `` the replacement.. so was replacing all `0`'s with `''`.  Anyway, I just added an extra check in redirects and routes to ensure this case is skipped.
