### ISSUE TITLE
IIS showing warnings about colons in URL

### ISSUE THREAD

**Issue by skunca** [getgrav/grav#612]
IIS shows a warning about colons in the URL:

> A potentially dangerous Request.Path value was detected from the client (:).

This could be solved by adding a less restrictive "httpRuntime requestPathInvalidCharacters" key in web.config.

**Comment by flaviocopes** [comment]
On Windows for Apache you need to change param_sep in user/config/system.yaml (or by using Admin) to `;` instead of `:`. You might want to do the same to avoid this situation.

See the fourth param listed in the first example in http://learn.getgrav.org/basics/grav-configuration#system-configuration

`param_sep: ':'                              # Parameter separator, use ';' for Apache on windows`

**Comment by rhukster** [comment]
Does it work ok if you change the param separator to `;` ?  I think perhaps we just need to update the docs / info to mention IIS.

**Comment by Vivalldi** [comment]
Where are you seeing this warning? I have 5 separate IIS servers running right now and none of them show these warnings you are referring to.

**Comment by rhukster** [comment]
Will close soon unless you comment with more information....

**Comment by skunca** [comment]
This is from eventlog on Azure Web Apps (PHP 5.6, default settings). Here's an output file -> [grav_event.txt](https://github.com/getgrav/grav/files/105986/grav_event.txt).

Changing the param separator to a semicolon should work but it might be a good idea to fix this in the web.config settings:

```xml
<system.web>
    <httpRuntime requestPathInvalidCharacters="&lt;,&gt;,*,%,&amp;,\,?" />
</system.web>
```

The default string is ```"&lt;,&gt;,*,%,&amp;,:,\,?"```. 

Is a semicolon param separator to safe on Linux or do I need to change ```system.yaml``` on every deployment depending on the target OS?

**Comment by rhukster** [comment]
Any ideas on this @Vivalldi ???

**Comment by Vivalldi** [comment]
Local versions of IIS tend not to validate URL's so no problems there (for the most part)
Azure IIS does validate and the changes in my pull request should work with default Azure settings.

@skunca can you test by replacing the web.config in your root (grav) folder with this [web.confg](https://github.com/Vivalldi/grav/blob/af2e416ea1dcf2461cd699c7f946745b7ae92655/webserver-configs/web.config)?

**Comment by rhukster** [comment]
If no updates made on this soon, i will assume @Vivalldi's fix sorted it.

**Comment by skunca** [comment]
I can confirm that with the new web.config the warnings no longer appear.
