### ISSUE TITLE
Can't use the page.find.media method to get png images. Only works with jpg extension.

### ISSUE THREAD

**Issue by adrianocr** [getgrav/grav#614]
So if you use the following method to reference image files `{{ page.find('/images').media['logo.png'].sizes('25vw').html }}` (images directory inside pages directory) twig returns nothing. However, if you rename that same file (without recreating the image, simply renaming it) to have a .jpg extension, twig returns the correct img tag and src attribute. Like this: `{{ page.find('/images').media['logo.jpg'].sizes('25vw').html }}` it works. Once again, to clarify, simply right click on the image and select "rename" and then change the .png to .jpg. So it's still a png but grav returns it because it has a .jpg extension. Even though it isn't a jpg.

**Comment by rhukster** [comment]
I don't think it's the `page.find()` method or the `.media()` bit.. I just tested and worked fine:

![home grav 2016-01-18 20-47-54](https://cloud.githubusercontent.com/assets/1084697/12409168/d399b626-be24-11e5-86b2-8b53b5cbf3ff.png)

**Comment by adrianocr** [comment]
Hmmm I think it was a cache thing. About an hour ago I had to clear the cache and then I just tried the image thing again and it worked with the png. So I guess we can close this issue. False alarm on my part.
