### ISSUE TITLE
Theme development mytheme.yaml inheritance settings

### ISSUE THREAD

**Issue by DimitriSteyaert** [getgrav/grav#615]
Hi, I have created a new theme with inheritance based on the Deliver theme.
This Deliver theme has the following parameter in its user/themes/deliver/deliver.yaml:
```
dropdown:
  enabled: true
``` 
After creating my own theme all my css and twig tweaks work but my custom dropdown menu isn't visible anymore. I tried to paste these 2 lines in my user/themes/mytheme/mytheme.yaml but also no luck (even after flushing caches).

Is this a bug or is there another workaround?

**Comment by flaviocopes** [comment]
Do you have a `user/config/themes/mytheme.yaml` overriding this config? or `user/config/themes/deliver.yaml`

**Comment by DimitriSteyaert** [comment]
Nope I haven't, not even a themes folder in user/config. Should I have this?

**Comment by flaviocopes** [comment]
No. But having those files would override your  user/themes/mytheme/mytheme.yaml. Was to exclude one possible cause of the problem.
Need to recreate, can you PM me your theme zipped via Gitter?

**Comment by DimitriSteyaert** [comment]
Ok, sent via Gitter.

**Comment by flaviocopes** [comment]
Solved, was depending on another configuration option to be set in the page (`onpage_menu`)

**Comment by DimitriSteyaert** [comment]
Tbh, that wasn't the solution. I have fiddled around for a while and I was able to pinpoint the cause of this behaviour.

1. This has no dependency on **onpage_menu**
2. I had to copy 2 files from the **Deliver** theme into my own theme folders:
  * ```cp user/themes/deliver/templates/modular_alt.html.twig user/themes/mytheme/templates/modular_alt.html.twig``` 
  * ```cp user/themes/deliver/templates/partials/navigation.html.twig user/themes/mytheme/templates/partials/navigation.html.twig``` 
3. Within these files I had to replace the word **deliver** with the word **mytheme**
4. Then in my user/themes/mytheme/mytheme.yaml I placed the following code on top
```yaml
dropdown:
  enabled: true
```
Then cleared all my caches to be sure aaaaand my dropdown menu was now working in my theme.

**Comment by flaviocopes** [comment]
:+1: looks like an issue on the theme then. Please report it on https://github.com/getgrav/grav-theme-deliver/issues as it should use the config without the theme name to prevent this happening in the future, just like Antimatter does:

https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/base.html.twig#L1

https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/navigation.html.twig#L19


I guess I got this right on my testing because I had set 

```
dropdown:
  enabled: true
```

on the Deliver config too.
