### ISSUE TITLE
[add-resource] New Theme - Course Companion Bones Vanilla 

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#617]
I would like to add this new inherited theme to the Grav Repository. **Course Companion** is a [Grav](http://getgrav.org) inherited theme based on [Bones Vanilla](https://github.com/smartgravity/grav-theme-bones-vanilla), intended to accompany a face-to-face, blended or fully online university course.

Here are the project details: https://github.com/hibbitts-design/grav-theme-course-companion-bones-vanilla

I next plan to create a Skeleton, but from what I understand I need to first release a theme.

**Comment by rhukster** [comment]
should show up in an hour or so...

**Comment by paulhibbitts** [comment]
Thanks very much Andy.
