### ISSUE TITLE
Setting custom class for all images parsed from markdown

### ISSUE THREAD

**Issue by solusipse** [getgrav/grav#618]
I would like to wrap all images on my website in custom blocks, but as far as I know, there is no option to add such wrappers for images which by default look in such way:
```
<p><img src="..." /></p>
```
I'd like to have something like this:
```
<p class="post-image-container"><a class="post-image-link" href="..."><img class="post-image" src="..."></a></p>
```
I don't want to use `post.media.images`, because I want to keep original images positions in text. I've written plugin for doing that. There's a draft:
```
public function onPageProcessed(Event $event)
{
    $page = $event['page'];
    $buffer = $page->content();
    $url = $page->url();
    $buffer = preg_replace("/<p><img src=\"(.*?)\" \/><\/p>/", "<p class='post-image-container'><a class='post-image-link' href='$1'><img class='post-image-main' src='$1'></a></p>", $buffer);
    $page->setRawContent($buffer);
}
```
but then I realised it could be probably done with a smart twig template. Unfortunately, it seems that twig's version used by Grav does not support `replace` with regular expressions:
```
{{ post.content|replace("/<p><img src=\"(.*?)\" \/><\/p>/", "<p class='post-image-container'><a class='post-image-link' href='$utest'><img class='post-image-main' src='test'></a></p>") }}
```
Is this a bug? Could you consider adding such functionality?

**Comment by rhukster** [comment]
I think the preferred solution would be to create a plugin that extends the markdown syntax.  We have examples of these types of plugins:

* https://github.com/getgrav/grav-plugin-markdown-color
* https://github.com/getgrav/grav-plugin-markdown-notices

Alternatively you could use twig and just create a Twig extension that adds a replace filter that uses regex like this: https://github.com/low/low_regex

**Comment by solusipse** [comment]
Thank you for these links. I'm afraid I'm stuck. If I understood correctly, according to [this documentation page](https://fossies.org/dox/grav-v1.0.6/ParsedownGravTrait_8php_source.html), `onMarkdownInitialized` event is fired after parsing default block types (including images). I guess that's why I cant catch images with this:
```
$markdown->addInlineType('!', 'Image');
        // Add function to handle this
        $markdown->inlineColoredTexta = function($excerpt) {
            ....
         };
}
```
On [event hierarchy page](http://learn.getgrav.org/plugins/event-hooks#onPageContentProcessed) there is no information about markdown events. Could you, please, provide an information whats just before `onMarkdownInitialized` so I could do the parsing job there?

**Comment by solusipse** [comment]
Btw, I actually solved that problem with such code:
```
<?php
namespace Grav\Plugin;

use Grav\Common\Plugin;
use RocketTheme\Toolbox\Event\Event;

class ImgClassPlugin extends Plugin
{

    public static function getSubscribedEvents() {
        return [
            'onPageContentProcessed' => ['onPageContentProcessed', 0]
        ];
    }

    public function onPageContentProcessed(Event $event)
    {
        $page = $event['page'];
        $buffer = $page->content();
        $url = $page->url();
        $buffer = preg_replace("/<p><img src=\"(.*?)\" \/><\/p>/",
        	"<p class='post-image-container'><a class='post-image-link' href='$1'><img class='post-image-main' src='$1'></a></p>",
        	$buffer);
        $buffer = preg_replace("/<p><img alt=\"(.*?)\" src=\"(.*?)\" \/><\/p>/",
        	"<p class='post-image-container'><a class='post-image-link' href='$2'><img class='post-image-main' src='$2'></a></p>",
        	$buffer);
        $page->setRawContent($buffer);
    }

}
```
But, as you see, that's a bit dirty.

**Comment by rhukster** [comment]
Actually i think its quite elegant as you can still use all the ParsedownTrait logic that is happening on the image tag already, then you just manipulate the resulting tag to your needs.  And look your code is tiny!

**Comment by solusipse** [comment]
Maybe you're right, I guess I'll stay with it. Thanks!
