### ISSUE TITLE
Home menu link not working when Append URL extension .html

### ISSUE THREAD

**Issue by buitermark** [getgrav/grav#621]
If **Append URL extension** in settings is set as **.html** (for example)
the home link is rendered only as **domain.tld/.html** in stead of **domain.tld>/home.html**

All the other pages are rendered correct

**Comment by flaviocopes** [comment]
The home link should not contain any slug, so the home should just point to `/`

**Comment by buitermark** [comment]
Great, Thanks very much.
This works now.
