### ISSUE TITLE
Themes - Multisite configuration (via subdomain)

### ISSUE THREAD

**Issue by hotovec** [getgrav/grav#627]
Hey just testing multisite - subdomain config. 
I Found issue with locators and themes. (other folders not tested yet)

My multisite config is using your subdomain example from grav docs.
![screenshot 2016-01-24 00 04 26](https://cloud.githubusercontent.com/assets/388276/12533359/2255453e-c22e-11e5-837c-dfe6994225d9.png)

My actual structure:
![screenshot 2016-01-23 23 59 34](https://cloud.githubusercontent.com/assets/388276/12533349/9c197440-c22d-11e5-8560-c9970e305b0b.png)

a)
As you can see all user data are under subdomain (user/sites/thx.engine.dev/)
Including themes and antimatter theme. But this config is throwing "theme antimatter does not exist"

b) 
When I move theme to the default place (user/themes/antimatter) 
I'm getting same error. Theme does not exsit.

c) 
When I keep theme under my site (user/sites/thx.engine.dev/themes/antimatter) and have also copy
at default place (/user/themes/antimatter) everything goes well.

This behavior is strange. It is something in locators and detecting paths under user://

When I extend setup.php by this:
![screenshot 2016-01-24 00 11 41](https://cloud.githubusercontent.com/assets/388276/12533397/2ccf7e48-c22f-11e5-8d60-65ddb16d757d.png)

theme start working but this kind of config does not make sense if you need different theme for other sites. Otherwise theme locator is empty. I'm not sure where trouble is. If Themes.php is parsing something wrong, or locators do not contain right path.

Important note:
If you will try this setup. You need disable Problem plugin. It is throwing errors and it is ignoring subdomain and it still checking default folders.

**Comment by hotovec** [comment]
After a couple of XDebug sessions I found problem in antimatter.yaml file.
![screenshot 2016-01-24 02 10 29](https://cloud.githubusercontent.com/assets/388276/12533834/d9bf104a-c23f-11e5-9b47-133767d68560.png)

This is causing that bug. It is overriding stream setting from template.
This is pretty dangerous behavior.

**Comment by flaviocopes** [comment]
Was most probably a leftover. Solved in https://github.com/getgrav/grav-theme-antimatter/commit/cbcedbb7b74664687eea1b8918902a829603d400
