### ISSUE TITLE
Issues installing ssl certs from letsencrypt due to htaccess rules

### ISSUE THREAD

**Issue by robwent** [getgrav/grav#631]
Installing the new free ssl certs from https://letsencrypt.org/ requires the remote server to access a file in the .well-known/acme-challange folder of the site to verify the domain.

This line blocks access to that folder by blocking any requests to files and folders starting with a dot https://github.com/getgrav/grav/blob/develop/.htaccess#L55

There is a related discussion with the core Drupal htaccess file supporting RFC 5785 /.well-known/ directories here: https://www.drupal.org/node/2408321

I will submit a pull request with the drupal patch which I just tested and the certs were installed correctly.

**Comment by rhukster** [comment]
Please submit the PR from your fork.  Thanks!

**Comment by robwent** [comment]
Hoping that was right. Just had a quick lesson in updating forks.

**Comment by rhukster** [comment]
There should be a git green "Create Pull Request" on your fork.  You will need to do that, and ensure your PR only has your fixes in it.

**Comment by robwent** [comment]
ok, giving it another go. Couldn't work out how to separate changes so just removed other files I added

**Comment by robwent** [comment]
hmm, that also sent my additions and deletions. Might be easier for you to change.
