### ISSUE TITLE
[add-resource] New Theme - Bones

### ISSUE THREAD

**Issue by benblee** [getgrav/grav#633]
I would like to add my new theme to the Grav site. You can find the theme info here:
https://github.com/smartgravity/grav-theme-bones

*(This is different from "[Bones Vanilla](https://github.com/smartgravity/grav-theme-bones-vanilla) in that it includes all Foundation JS and SCSS files to be compiled)*

**Comment by rhukster** [comment]
should show up in an hour or so...
