### ISSUE TITLE
[add-resource] New Skeleton - Bones Site

### ISSUE THREAD

**Issue by benblee** [getgrav/grav#634]
I would like to add my new skeleton install for the Bones Theme to the Grav site. You can find the skeleton info here:
https://github.com/smartgravity/grav-skeleton-bones-site

*(This is different from [Bones Vanilla](https://github.com/smartgravity/grav-theme-bones-vanilla) in that it includes all Foundation JS and SCSS files to be compiled)*

**Comment by rhukster** [comment]
should show up in an hour or so...
