### ISSUE TITLE
[add-resource] New Skeleton - Course Companion

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#638]
Thanks for accepting my course companion inherited theme. I would now like to add this new skeleton package to the Grav Repository, which uses the Course Companion Bones Vanilla inherited theme.

Here are the project details: https://github.com/hibbitts-design/grav-skeleton-course-companion (updated URL)

Thanks very much,
Paul

**Comment by rhukster** [comment]
Missing a release for the skeleton, but the theme is fine.  

You need to make sure you have a release 'package' built.  Not just a release done via github.  the package should be the installable grav+theme+plugins+content etc: http://diblas.net/blog/how-to-build-a-grav-skeleton

**Comment by paulhibbitts** [comment]
Thanks Andy, I've reviewed that article (very helpful!) and after a process of experimenting with dependencies and blueprints I think I've got a release ready. Zip file is also attached.

**Comment by rhukster** [comment]
Still failing on getRelease

**Comment by paulhibbitts** [comment]
Hi Andy, I think I've tracked down several issues with my skeleton which was preventing it getting through - hoping this one works, thanks. https://github.com/hibbitts-design/grav-skeleton-course-companion

**Comment by rhukster** [comment]
Think this is all working.. closing

**Comment by paulhibbitts** [comment]
Thanks Andy, I always appreciate your help.
