### ISSUE TITLE
Cannot connect to the GPM when using proxy

### ISSUE THREAD

**Issue by Birssan** [getgrav/grav#639]
Hi there,

I tried to use Grav on a server behind a proxy.
At first I tried to update packages and install plugins from the admin plugin. I had `Cannot connect to the GPM`.
Then I tried using the GPM CLI and got
```
[RuntimeException]           
  cURL error (7):              
   Couldn't connect to server
```

I decided to go and check the doc to see if there was any information I could use (I already had `http_proxy` and `https_proxy` env vars set).

I disabled `allow_url_fopen` in my php.ini, It worked well for the GPM CLI but I still had `Cannot connect to the GPM` in the admin interface when looking for updates or trying to install a plugin.

I also tried this code http://stackoverflow.com/questions/9922562/how-to-resolve-curl-error-7-couldnt-connect-to-host/9923212#9923212 (suggested by @flaviocopes), it worked.

@flaviocopes Suggested that I force curl to use my proxy settings in https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/GPM/Response.php

So I added `CURLOPT_PROXY` in the curl options like this

```
'curl'  => [
            CURLOPT_REFERER        => 'Grav GPM',
            CURLOPT_USERAGENT      => 'Grav GPM',
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_TIMEOUT        => 15,
            CURLOPT_HEADER         => false,
            CURLOPT_PROXY          => '192.168.100.241:8080'
            /**
             * Example of callback parameters from within your own class
             */
            //CURLOPT_NOPROGRESS     => false,
            //CURLOPT_PROGRESSFUNCTION => [$this, 'progress']
        ],
        'fopen' => [
            'method'          => 'GET',
            'user_agent'      => 'Grav GPM',
            'max_redirects'   => 5,
            'follow_location' => 1,
            'timeout'         => 15,
            /**
             * Example of callback parameters from within your own class
             */
            //'notification' => [$this, 'progress']
        ]
```

And now it works.

**Comment by rhukster** [comment]
I've added proxy support in the latest develop branch.  Should work fine with regular HTTP type proxies (squid etc) for both Curl and Fopen approaches.
