### ISSUE TITLE
Sorting of Pages in Templates

### ISSUE THREAD

**Issue by ChristianAuth** [getgrav/grav#643]
Hey,

when you sort collections right now the result does not properly handle upper / lowercase stuff.

Form a query like this:
```
{% set projects = taxonomy.findTaxonomy({'tag':'featured-project'}).order('header.owner') %}
```

You get this:
```
A
B
a
b
```

I would have expected this:
```
A
a
B
b
```

Problem is the sorting within the Pages Collection that uses asort without any options.
Since PHP 5.4 you can use Flags to state that you want a proper case honoring sorting:

```
asort($list, SORT_NATURAL | SORT_FLAG_CASE);
```

Can we add this as a default or will this implode anything?

cheers
Chris

**Comment by flaviocopes** [comment]
I think that should be fixed as currently it's not an expected behavior. @rhukster agree?

**Comment by rhukster** [comment]
Should be fixed in repo.
