### ISSUE TITLE
Image watermarking

### ISSUE THREAD

**Issue by buitermark** [getgrav/grav#647]
I'd like to see a possibility for 'watermarking' foto's/images with text/images on different positions.

If i'm correct, the Gregwar library can support this, will this be a feature we can expect in Grav?

**Comment by rhukster** [comment]
Thanks for the reminder, i'll see if this is possible to add.

**Comment by rhukster** [comment]
This is kinda complicated.. it requires merging two images.  I think this is beyond the scope of standard Grav functionality. I think you could achieve this with a plugin if you needed this, but it would require a rather sizeable refactor of our media functionality to support it natively.  Not something we want to tackle at this stage. Maybe in a Grav 2.0 release we can revisit.
