### ISSUE TITLE
[add-resource] New Theme - Course Companion Bootstrap

### ISSUE THREAD

**Issue by paulhibbitts** [getgrav/grav#654]
I would like to add this new inherited theme to the Grav Repository. Course Companion B3 is a Grav inherited theme based on Bootstrap, intended to accompany a face-to-face, blended or fully online university course. This is the 2nd of two course companion compatible themes (1st was for the Foundation framework using the Bones Vanilla theme).

Here are the project details: https://github.com/hibbitts-design/grav-theme-course-companion-b3

I only plan to release one skeleton, which will support either of the two course companion themes.

**Comment by rhukster** [comment]
Done
