### ISSUE TITLE
Installing from github results in errors at each plugin install command

### ISSUE THREAD

**Issue by D3m1urg0** [getgrav/grav#656]
if i install Grav from github (and only in this case) i get this error:

`[InvalidArgumentException] Identifier "base_url" is not defined.`

each time i run
`bin/gpm install "SOMETHING"`

**Comment by codev0** [comment]
I have same issue
![ScreenShot](https://i.imgur.com/dXVhh2D.png)

**Comment by flaviocopes** [comment]
Cannot recreate this, strange! With a fresh GitHub install.

There was a recent change regarding `base_url`, not sure if it's related: https://github.com/getgrav/grav/commit/5abb4060f39cd0b221a5cf86873f9d8b8cc7d570

**Comment by rhukster** [comment]
That's probably it.  I did this refactor to better support the unit testing we're implmenting, but clearly breaks GPM.  I will fix this today.

BTW, in the meantime, you can install the stable version via composer. http://learn.getgrav.org/basics/installation#option-2-install-with-composer

**Comment by rhukster** [comment]
Ok should be fixed now: https://github.com/getgrav/grav/commit/e4cda6383f27d881a3a12e178d0d72ed9d9be804
