### ISSUE TITLE
Would Grav support the multi-language interface about admin page ?

### ISSUE THREAD

**Issue by it4u** [getgrav/grav#657]
Hi Dear Develop Team:

I want to ask would Grav support the multi-language interface ? 
If hasn't, I could translate the Traditional Chinese and Simp Chinese language.

Thanks for response.

Aaron Wang

**Comment by rhukster** [comment]
Here’s the info on multi language support:

http://learn.getgrav.org/content/multi-language <http://learn.getgrav.org/content/multi-language>

For translations we use Crowdin:

https://getgrav.org/blog/crowdin-translation <https://getgrav.org/blog/crowdin-translation>

Thanks!
