### ISSUE TITLE
CSS media queries on file load with assets.addCss

### ISSUE THREAD

**Issue by adamjansch** [getgrav/grav#661]
I like to separate my CSS files by media query, with each handling the rules I'm designing for, using the media query on file load, like so:

    <link rel="stylesheet" href="css/style-min-640.css" media="only screen and (min-width: 640px)" />
    <link rel="stylesheet" href="css/style-min-960.css" media="only screen and (min-width: 960px)" />
    ...

However, it looks like Asset Manager's `assets.addCss()` function can't handle this scenario: would it be a feature worth adding?

(The workaround for the moment would be to load all the separate CSS files and wrap the rules within the relevant media query in the file.)

**Comment by rhukster** [comment]
Actually just tested and this functionality exists already:

```
{% do assets.add('theme://css/style-min-640.css', {'media':'only screen and (min-width: 640px)'}) %}
```

**Comment by adamjansch** [comment]
Seems to work at this end, thanks!
