### ISSUE TITLE
We would love

### ISSUE THREAD

**Issue by vtmx** [getgrav/grav#663]
I think one of the best features that CMS's had been in the custom fields and live preview and media manager. I would love to see something similar to below:

http://www.advancedcustomfields.com/pro/
+
https://craftcms.com/features/live-preview
+
https://octobercms.com/blog/post/introducing-media-manager

**Comment by rhukster** [comment]
We're definitely planning on building a **forms pro plugin** that would have form building functionality.  This is probably scheduled for the second half of the year depending on how other stuff goes.

Regarding page-building, we do have some plans to improve the way modular pages are built.  This will cover some of what you are mentioning.

Lastly we are brining Gantry5 framework to Grav, and that will also cover some of the bases.
