### ISSUE TITLE
Is Grav compatible with Gulp and Bower?

### ISSUE THREAD

**Issue by paper9oll** [getgrav/grav#664]
Hi All,

Is Gulp compatible with Grav as I use Gulp a lot, and is it possible to include things like bootstrap via Bower instead direct downloading as stated in the documentation?

Asking this as i'm interested in moving some projects to Grav.

Thanks you

**Comment by flaviocopes** [comment]
Grav is tooling-agnostic, so you can use any tool you want. 
Also, themes can use any kind of CSS/JS framework and install however they like, there is no fixed rule. If you install it via Bower, just point the theme to use its folder as location.

P.S. If not a possible bug, please post questions on the Forum / Gitter.
