### ISSUE TITLE
[add-resource] Please check New Plugin

### ISSUE THREAD

**Issue by gracix** [getgrav/grav#666]
I would like to add my new plugin to the Grav Repository.
Here are the project details gracix/grav-plugin-snippet

**Comment by rhukster** [comment]
You need to have a more unique name.  There is already a plugin called "snippet"

**Comment by gracix** [comment]
OK, Can I use 'Snippet**s**' ?
The similar name is not good ?

**Comment by rhukster** [comment]
I think this is going to just make it confusing for users.. how about `gracix-snippets`

this means the plugin will be installed under `user/plugins/gracix-snippets/` and expect to find a `gracix-snippets.php` with classname `GracixSnippets` and a `gracix-snippets.yaml`

**Comment by gracix** [comment]
Thanks I understand.
I want to more universally name.
changing to "minicode"

**Comment by gracix** [comment]
I changed plugin name.
Please check this. gracix/grav-plugin-minicode

**Comment by rhukster** [comment]
will be in next GPM update
