### ISSUE TITLE
Dependency Version Detection

### ISSUE THREAD

**Issue by Vivalldi** [getgrav/grav#667]
Currently when installing plugins via the GPM dependencies are installed with the most up to date version, or if already installed does not check for a minimum version. For example the OAuth plugin will require that the login plugin is updated to v2.x.x

**Comment by rhukster** [comment]
Yes, this is a known issue and something we intend to add.

it's actually already mentioned in the Grav 1.X section of the 2016 plans: https://getgrav.org/blog/plans-for-2016

**Comment by rhukster** [comment]
also related to #563 so closing as we know about this already :)
