### ISSUE TITLE
'grav-plugin-markdown-rubytext'

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav#668]
**I would like to publish a new plugin 'grav-plugin-markdown-rubytext'.**

- It is my first plugin:
it has been made possible with support of @rhukster and @sommerregen.

- It create a _markdown shortcut_ to make _ruby tagged text_ simply:
it is helpful especially for _far east languages_ like:
    1. japanese,
    2. korean,
    3. chinese
    ...

- I am very proud to have the honor to contribute modestly to GravCMS:
I have tested it as much as I could: to me it's OK.

- Here is the link:
[grav-plugin-markdown-rubytext](https://github.com/tidiview/grav-plugin-markdown-rubytext)

*_Thank you._*

**Comment by rhukster** [comment]
You need to fix the name of your bluerpints.. should be `blueprints.yaml`, not `blueprint.yaml`.  After that you will need to rerelease.

Thanks~

**Comment by tidiview** [comment]
- I changed to blueprints.yaml

- I rereleased

Thanks ～

**Comment by rhukster** [comment]
Should get picked up next hour if all is good.. i'll watch to see what happens.

**Comment by rhukster** [comment]
Ok added!
