### ISSUE TITLE
Video thumbnails not working

### ISSUE THREAD

**Issue by lzwaan** [getgrav/grav#673]
I like to add an thumbnail / poster to my mp4 video, but i only see the actual video.
This is the code in the page:    ![](test.mp4)
And these are the files located in the page directory:
- test.mp4
- test.mp4.thumb.jpg

As i said, it only returns the actual mp4 file

**Comment by flaviocopes** [comment]
The video is played inline in the page unless you explicitly want to link to it. To do so, use

```
![](video.mp4?link)
```

and the page will show the thumbnail with a link to the video.

**Comment by lzwaan** [comment]
i like to use embedded video and a poster for preview:

<video  poster="image.jpg" controls>

**Comment by tsopanid** [comment]
> i like to use embedded video and a poster for preview:
> 
> ```
> <video  poster="image.jpg" controls>
> ```

same for me
