### ISSUE TITLE
Feature Request: Forums

### ISSUE THREAD

**Issue by vpontin** [getgrav/grav#678]
Hi all!

Just discovered this CMS and has found it extremely versatile!

But after some search in the issues i dont find this liitle thing would be ultimate for migrating my website to grav platform: What about a Forum plugin?

Instead of bbcode, it would use Markdown and integrate nicefully with existent themes.

Maybe a register form, and social login integrated.

I dont know how data would be stored (not a hardcore dev boy), so if this request are impossible with current architeture, sorry. And just ignore these requests if already exists.

**Comment by flaviocopes** [comment]
It's certainly possible to write a Forum plugin. It's not easy given the range of features that must be added to a fully-featured forum, so maybe a Grav plugin that provides http://flarum.org/ integration would be very nice to start with.

**Comment by flaviocopes** [comment]
Will close as it's not a Grav issue, maybe you can post on the Grav Forum to see if someone can pick up this idea.

**Comment by DamirPecnik** [comment]
Flarum integration would be really nice with Grav ...

**Comment by flaviocopes** [comment]
Flarum is not really something that can be integrated, but rather you install Grav, and alongsite you install Flarum, which is a separate system on its own. And you'll need to integrate the theme used on the 2 systems. 
You could then have an account integration, if you use user accounts within Grav.

**Comment by DamirPecnik** [comment]
Yeah that was my thinking Account integration one single sing on ....
