### ISSUE TITLE
When plugin name has "-"

### ISSUE THREAD

**Issue by Ricoom** [getgrav/grav#680]
refrenciing it like {{  dump(config.plugins.login-oauth.enabled)  }} crashes grav as Unsupported operand types

**Comment by flaviocopes** [comment]
Not an issue in Grav, it's how Twig works. Use `{{ config.plugins['login-oauth'] }}`

**Comment by rhukster** [comment]
or attributes: http://twig.sensiolabs.org/doc/functions/attribute.html
