### ISSUE TITLE
Custom url variable for snipcart_product-item and snipcart_detail_item buttons

### ISSUE THREAD

**Issue by paulvanderschee** [getgrav/grav#683]
Dear grav developers, Is it possible to tweak the snipcart module to reference a external product item as well. Like this example:
![howtoroutecorrectly](https://cloud.githubusercontent.com/assets/11161836/13090897/bb3765ca-d4f8-11e5-9601-f7445c8f5a76.jpg)

The specific file which need to be edited in this case is: https://github.com/getgrav/grav-plugin-snipcart/blob/develop/templates/partials/snipcart_detail_item.html.twig  the following code:

`<a href="#"
                class="button snipcart-add-item"
                data-item-id="{{ page.header.product_id }}"
                data-item-name="{{ page.header.title }}"
                data-item-price="{{ page.header.price }}"
                data-item-url="{{ page.url }}"
            >
                <i class="fa fa-shopping-cart"></i> Add to Cart
            </a>
`
the variable: page.url variable should be an external custom url variable which should get customized in the frontmatter with any custom link from the product item page.

and the same for: https://github.com/getgrav/grav-plugin-snipcart/blob/develop/templates/partials/snipcart_product_item.html.twig

`<a href="{{ page.url }}">{{ page.header.title }}</a></h3>
    <div class="snipcart-thumb">
        {% if snipcart_image %}
            <a href="{{ page.url }}">{{ snipcart_image.cropResize(200,200).html('page.header.title','snipcart-thumb-image') }}</a>
        {% endif %}
        <span class="snipcart-price">
        ${{ page.header.price }}
        </span>
    </div>
    <div class="snipcart-details">
    <p>
        <a href="{{ page.url }}"
            class="button button-small">
            <i class="fa fa-info-circle"></i> Details
        </a>
        <a href="#"
            class="button button-small snipcart-add-item"
            data-item-id="{{ page.header.product_id }}"
            data-item-name="{{ page.header.title }}"
            data-item-price="{{ page.header.price }}"
            data-item-url="{{ page.url }}"
        >
            <i class="fa fa-shopping-cart"></i> Add
        </a>
`

the variable: page.url and # variable should be an external custom url variable which should be able to get customized with any custom link in the frontmatter from the grav product item page.

For now it is not possible for me to tweak this to any custom url from the frontmatter. I worked on a mac computer, and used the http://demo.getgrav.org/shop-skeleton/shop/geek-toys/ia449-brick-mug + Grav core + Admin plugin.

Greetings Paul

**Comment by flaviocopes** [comment]
This is something that should go in https://github.com/getgrav/grav-plugin-snipcart/issues.

You can create a PR for the plugin if you like this to be included, but as I read Andy answer, this then will not need Snipcart at all, you could just copy its styling into your site if you want to refer to external pages.

**Comment by rhukster** [comment]
You can simply copy the `partials/snipcart_product_item.html.twig` to your theme (in the correct path) and make the modifications yourself.

**Comment by paulvanderschee** [comment]
Thanks, its pretty much to do with external redirecting from the product_item.html.twig, but not as perfect as it should be, i will create  a PR for the plugin, because shop owners who do have internal products will stick with snipcart but what if shop owners also want to display external products from others then this option should definitly be available (custom url implementation instead of addtocart). anyway thanks for helping guys! :)
