### ISSUE TITLE
502 on homepage after first page load

### ISSUE THREAD

**Issue by mabushey** [getgrav/grav#685]
If I do either a `bin/grav clearcache` or `rm -rf /var/www/html/www.sendthemtomir.com/cache/twig/*` I can load www.sendthemtomir.com once. Any additional page loads of the home page give a 502. All pages under /admin work perfect.

I have several sites on this server with a shared grav install in /var/www/grav.  The rest of the sites work properly.

```
╭─root@sendthemtomir.com /var/www/html/www.sendthemtomir.com  
╰─➤  bin/composer.phar selfupdate
You are already using composer version e3fabf58445d351735297e018b12b5d94c582add.
```

Please let me know what additional information is helpful in figuring this out. I love grav, thank you. :)

**Comment by rhukster** [comment]
Seems like a server issue: http://jvdc.me/fix-502-bad-gateway-error-on-nginx-server-after-upgrading-php/

**Comment by mabushey** [comment]
It's not Nginx, all the /admin pages work and the other grav sites work fine.

If I `FLUSHALL` in Redis, I can load the homepage once.

```
127.0.0.1:6379> keys *
 1) "wwwmir-f5f63d59[dc8093f76ecd8f07954a4c8d23ed47f4][1]"
 2) "wwwmir-f5f63d59[6e721acce063ce47cdec81e00bf1360f][1]"
 3) "wwwmir-f5f63d59[4ec02cfd68f74521ef7d815207dfac2e][1]"
 4) "wwwmir-f5f63d59[5a12f9cff74caaf28c5fb06cb6023a9e][1]"
 5) "wwwmir-f5f63d59[d234695177c135851a74540384452a2f][1]"
 6) "wwwmir-f5f63d59[45040874615c5573dc72da2c35855256][1]"
 7) "wwwmir-f5f63d59[0d7c3c20fe1924056848bfe924736f01][1]"
 8) "wwwmir-f5f63d59[6e3d18bbe66c2822e60f74c07880e8bf][1]"
 9) "wwwmir-f5f63d59[9f60d3853690a77445a8e9b93e79a0be][1]"
10) "wwwmir-f5f63d59[20b2e054964511ddb0952e843dac29d0][1]"
11) "wwwmir-f5f63d59[8d020ed88145f962ca810b197cc4f65e][1]"
12) "wwwmir-f5f63d59[3f74e62bcfbda1ca2f60ff5477ae2ffa][1]"
```

As soon as those keys are back I get a  502.

**Comment by mabushey** [comment]
The error in the php error log:
```
2016/02/18 00:15:31 [error] 14287#14287: *892 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 216.253.238.138, server: www.sendthemtomir.com, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "www.sendthemtomir.com"
```
I'm using php 7.0.3-3 on Debian using the dotdeb packages.

**Comment by mabushey** [comment]
Changing line 65 of `user/config/system.yaml` from `driver: redis` to `driver: auto` brings the site back to life, so it looks like a bug in redis caching.

I see predis in `vendor/composer/installed.json`. Is it possible to uninstall that? The predis driver is written in php and slow compared to the real php redis extension.

**Comment by rhukster** [comment]
can you try doing this:

```
composer update --no-dev -o
```

**Comment by mabushey** [comment]
I think I already tried that.

```
╭─root@sendthemtomir.com /var/www/html/www.sendthemtomir.com  
╰─➤  bin/composer.phar update --no-dev -o                                                                                                                                                                                              127 ↵
Loading composer repositories with package information
Updating dependencies
Nothing to install or update
Writing lock file
Generating optimized autoload files
```

Putting `driver: redis` back once again results in only the first page load giving a 200.

**Comment by rhukster** [comment]
I don't think redis is installed unless you install the *development* composer packages.  It is part of codeception installation.

Doctrine cache is what your configuring Redis for and it has it's own `PredisCache.php` library.  If there's an issue with Redis, then it's probably upstream with Doctrine Cache.  Grav doesn't use Redis at all directly.

**Comment by mabushey** [comment]
You're most likely right about it being an upstream problem. While it would be nice to have redis caching, the reality is Grav is so damn fast that I doubt it even matters. Thanks for your help with this. :)

**Comment by rhukster** [comment]
Frankly in my testing Redis was one of the slowest cache options for Doctrine. APCu is the fastest by a long shot (except with PHP7 where file caching is surprisingly the fastest)
