### ISSUE TITLE
Is there a way to override Parsedown methods without touching the Grav source code?

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#687]
Is there a way to override Parsedown methods (like it is done in `ParsedownGravTrait`) without touching the Grav source code?
The approach used in the `markdown-color` and `markdown-notices` plugins don't work for existing methods.
For example, how one could override `blockQuote` method without touching the Grav core?

**Comment by rhukster** [comment]
Currently there is no way to override the default behavior of Parsedown from a plugin. We are doing this in the `ParsedownGravTrait.php` but this is not something that is easy to do at runtime.

**Comment by maxlysenko** [comment]
Hello,
I found that it's possible to call a new function (closure) for processing a standard block/inline type if we have possibility to insert the new tag for that type into the `BlockTypes`/`InlineType` array in a particular position (higher than the tag we want to override).
Here is a possible workaround that is working for me:
If you change the `addBlockType` function to something like this:
```php
public function addBlockType($type, $tag, $continuable = false, $completable = false, $index = null)
{
    if (!isset($index)) {
        $this->BlockTypes[$type] [] = $tag;
    } else {
        array_splice($this->BlockTypes[$type], $index, 0, $tag);
    }

    if ($continuable) {
        $this->continuable_blocks[] = $tag;
    }

    if ($completable) {
        $this->completable_blocks[] = $tag;
    }
}
```
and then in the `onMarkdownInitialized` event call `addBlockType` like this:
```php
 $markdown->addBlockType('>', 'QuoteExtended', true, false, 0);
```
the tag is inserted into the `BlockTypes` array higher than the existing tag
```
 #BlockTypes: array:24 [
...
    ">" => array:2 [
      0 => "QuoteExtended"
      1 => "Quote"
    ]
...
]
```
and then the closures are called so it's possible to extend/override standard processing.

The same is true for the `addInlineType`:
```php
public function addInlineType($type, $tag, $index = null)
{
    if (!isset($index)) {
        $this->InlineTypes[$type] [] = $tag;
    } else {
        array_splice($this->InlineTypes[$type], $index, 0, $tag);
    }

    $this->inlineMarkerList .= $type;
}
```
