### ISSUE TITLE
site.yaml routes not working

### ISSUE THREAD

**Issue by embieone** [getgrav/grav#688]
The routes defined in site.yaml seems to be ignored or not working.

e.g.
**//localhost/grav/en-US/something/en-US/else**
should be routed to
**//localhost/grav/en-US/something/else**

through the following block in **/user/config/site.yaml**

```
routes:
  /something/en-US/(.*): '/something/$1'
```

Configuration via admin plugin and without regex didn't worked either.
Defining the default route in the page front matter works perfectly.

**Comment by flaviocopes** [comment]
As explained in http://learn.getgrav.org/content/routing#route-aliases routes do not actually redirect the user to the provided page, it simply displays the page when you request the alias. 

Before trying to replicate, is this something that you know already?

**Comment by embieone** [comment]
Yes I know, but when I request the defined alias I get an Error 404. 
This is not the case when defining the default route in the page front matter.

Furthermore links to the page created by grav should use the alias instead of the real url, right? This is not the case.

**Comment by rhukster** [comment]
This could be related the multi-language nature of your site.  Rather than me spending ages trying to replicate it, can you simply zip up your site (or a smaller test site) that exhibits this problem and give the URL so I can download it and see the problem in action?

**Comment by embieone** [comment]
As requested, here is a lite version of my project.

[grav-test.zip](https://github.com/getgrav/grav/files/137819/grav-test.zip)

I left only a few pages in the project. Within the remaining pages the events page is the interessting one.

**Comment by rhukster** [comment]
After disabling the **countryswitcher** plugin, i get the test site running.  

Then i setup a **redirect** in the `site.yaml` as you described:

```
redirects:
  '/something/en-US/(.*)': '/something/$1'
```

And then I pointed my browser to: `http://localhost/grav/en-US/something/en-US/else`

and it was correctly redirected to: `http://localhost/grav/en-US/something/else`

However, there is no page here, so that resulted in an **Error 404**. 

Also, you were putting these in the **routes** section and as such was also resulting in a 404 error for the same reason.  

I then created a folder at `/02.something/else` and put a simple page `static.html.twig` with the following content:

```
---
title: Something else
---

# Something Else
```

Then the redirect work.  Now i could see the redirect working, I removed the redirect, and put it back into the routes:

```
routes:
    '/something/en-US/(.*)': '/something/$1'
```

And it worked still.  The `/something/else` pages was found even when requesting `/en-US/something/en-US/else`


So, I think it's more likely it's just a bug in your content more than anything else.

**Comment by embieone** [comment]
First thank you for your time and tests. But I think you tested the wrong page. 
Sure, in my initial comment I wrote something about  `//localhost/grav/en-US/something/en-US/else` but this was just an abstract example to show the problem, this path and never exists in my site.

Let me translate this example to the package I provided:

As I pointet out my last comment, the '/events/' page is the interesting one. 

There are pages for each language and some language folders `de`, `de-AT` and `de-CH'.

Each page is a blog with content from the corresponding language folder, e.g. in `/events/de-CH/` are two sub folders `cats` and `dogs` resulting in two blog posts cats and dogs. 

So the cats page url is `http://localhost/grav/de-CH/events/de-CH/cats`.

Now the Problem:

To get rid of the language folder I created the following route in sites.yaml:

`'/events/de-CH/(.*)': /events/$1`

Now the page should be requestable through `http://localhost/grav/de-CH/events/cats`, but this request results in an **Error 404**.

**Comment by flaviocopes** [comment]
If you're using `routes` you're doing it backwards:

```
  /events/(.*): '/events/de-CH/$1'
```

NOT

```
'/events/de-CH/(.*)': /events/$1
```

Here's an example: http://learn.getgrav.org/basics/grav-configuration#site-configuration

Redirects on the other hand work backwards, first the old url, then the new one. Like @rhukster suggested.

Anyway there is an easier way to get this blog multilanguage thing, and is

```
03.events
  -> blog.de.md
  -> blog.de-CH.md
  -> blog.de-AT.md
  -> 01.cats
     ....
```

And provide a translation for each blog post in its own md file. If a language has no translation, creata a page file for it and add `visible: false`

**Comment by embieone** [comment]
Thank you, the routes are working now. 
But I have one more question: Routes defined in site.yaml won't affect the `page.url`, unlike the default route defined in the page front matter, right?

I know that there is an easier way to get this blog working, but with 15+ languages with different content this way is a bit confusing in the backend.

And again, thank you very much for your help and patience.

**Comment by embieone** [comment]
OK, I've tested a bit and it seems I've misunderstood the whole routes thing. 

I thought I could define routes in `site.yaml` and achieve the same behavior as defining the default route in the page front matter without definging the default route for each page. But this seems not to be the case. 

Defining the routes in site.yaml like 
```
routes:
    /events/(.*): '/events/de-CH/$1'
```
results in: each page requested by `[language]/events/[event]` will show the content of the folder defined by the first route, e.g.  `/de-AT/events/cats` would show the content of the folder `/events/de-CH/cats/` instead of `/events/de-AT/cats/`.

So, is there a way to achieve the same behavior as defining the default route for each page without defining the default route for each page? Hopefully it's somewhat understandable...

Thanks, again.

**Comment by rhukster** [comment]
There really isn't.  Like I said before, the routes defined in `site.yaml` are used when a page is not found.  This is sort of a last-resort type scenario that Grav tries before giving up and throwing a page-not-found exception.  

I think you should look into doing this with webserver rewrites if you don't want to go through the trouble of adding alternative routes per-page.

**Comment by embieone** [comment]
It's a pity, however many thanks for your time and advice.
