### ISSUE TITLE
Active page style?

### ISSUE THREAD

**Issue by HomanBas** [getgrav/grav#689]
Hey! Working whit Grav for 2 month's now and i Got a problem whit the menu. I got my own menu on it. But i want to give the page thats active at the moment an other background color in the menu list item. :active in CSS and stuff does not give any result. Does anybody have a solutions for my problem?

~Bas.

**Comment by flaviocopes** [comment]
It all depends on the theme, as the theme defines all the markup. Usually themes add a class to the active menu, Antimatter for example adds `class="active"`. `:active` in CSS is a completely unrelated thing, see https://developer.mozilla.org/en/docs/Web/CSS/:active
