### ISSUE TITLE
RuntimeException - unlink failed installing new theme

### ISSUE THREAD

**Issue by kehugter** [getgrav/grav#691]
Fresh Grav installed with git worked fine in a remote server, the default site was displayed correctly. The problem occurred when I tried to install a new theme:

> $ bin/gpm install solid-state

> Preparing to install Solid State [v1.0.1]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok                             
  '- Success!  

> Attention: Solid State contains demo content
> n
>   '- Skipped!  

> Clearing cache

>   [RuntimeException]
unlink(/var/www/site/cache/twig/85/8507b05c764868eb4075755961a9e6caaf42925a9b72546c7684a103ab1326e9.php): Permission denied  

> install [-f|--force] [-y|--all-yes] [-d|--destination [DESTINATION]] [--] <package> (<package>)...

I removed everything and installed Grav again, this time using composer, but the result was the same.

I double-checked the permissions before and after the install. `chmod` ing again resulted in

> find . -type f | xargs chmod 664
chmod: changing permissions of ‘./user/config/security.yaml’: Operation not permitted
chmod: changing permissions of ‘./cache/twig/85/8507b05c764868eb4075755961a9e6caaf42925a9b72546c7684a103ab1326e9.php’: Operation not permitted
chmod: changing permissions of ‘./cache/twig/bf/bff2c3dc8eb4cf23052a227cc022c632473470d2fe0a59339d3750cfeab49ba4.php’: Operation not permitted
chmod: changing permissions of ‘./cache/twig/e8/e8039e89da6e62bd4fd3e739b0e076bbe815c11ba96c2198de943aac5cf2fb3e.php’: Operation not permitted
chmod: changing permissions of ‘./cache/twig/d6/d6fc3a6a50ebdf361fe32e27a0052c3c54e3ab6e6f2dc1ea17adbeae2c8f3614.php’: Operation not permitted
chmod: changing permissions of ‘./cache/compiled/files/c56b870485078b3429edf69d4ab36de6.yaml.php’: Operation not permitted
(lots of ./cache/compiled/files/) ...
chmod: changing permissions of ‘./cache/compiled/languages/master-blog.winkler.link.php’: Operation not permitted
chmod: changing permissions of ‘./cache/compiled/blueprints/master-blog.winkler.link.php’: Operation not permitted
chmod: changing permissions of ‘./cache/compiled/config/master-blog.winkler.link.php’: Operation not permitted
chmod: changing permissions of ‘./cache/problem-check-g-9d27ea40’: Operation not permitted
chmod: changing permissions of ‘./cache/doctrine/d1/672d39643237656134305b64336161346531316132643437386638666265373261366137666663643431315d5b315d.doctrinecache.data’: Operation not permitted
chmod: changing permissions of ‘./cache/doctrine/38/672d39643237656134305b33323430346233363331633339383433343861383062653966393765373463665d5b315d.doctrinecache.data’: Operation not permitted
chmod: changing permissions of ‘./cache/doctrine/c0/672d39643237656134305b37316439333961646339386365396265373365656130623764303436393637615d5b315d.doctrinecache.data’: Operation not permitted

Not even `sudo chmod`ing would let me modify the files in `./cache`.

An unzipped skeleton worked as expected out of the box.

---

Debian 8 x64
Minimum requirements met
Required PHP modules enabled

**Comment by rhukster** [comment]
This is a permissions issue.  Once the folder is created by the user (installation), the webserver doesn't have access to modify it.

Depending on your hosting setup, this can be a bit of a pain in the arse, but we have a basic troubleshooting guide that should help: http://learn.getgrav.org/troubleshooting/permissions

Really the best solution is to have the same user for your webserver and for logging in and manipulating files.  That way you will never have any permission issues.

Other than that, sharing a group is the next best option.  Then you might need to tweak the settings in Grav to ensure that Twig and Images are created with the proper permissions:

* https://github.com/getgrav/grav/blob/develop/system/config/system.yaml#L79
* https://github.com/getgrav/grav/blob/develop/system/config/system.yaml#L104

**Comment by kehugter** [comment]
I'm in a dedi with full root access, editing something won't be a problem.

> tweak the settings in Grav to ensure that Twig and Images are created with the proper permissions

Yep, that did it, thanks for your help! And I found that `umask`ing to `0002` _before_ the installation (I was doing it after) solves the problem too.

---

On a different matter: with composer I noticed that on prompts, if I type something and then hit backspace until I reach the start of the string, the prompt question gets deleted too. Is that upstream?

**Comment by jeremyjumeau** [comment]
What about using ACL rights?

**Comment by kehugter** [comment]
That's what I finally did. Files created after the installation were causing problems. Is the only good solution to keep the read/write rights tidy in an environment where www-data is not the owner.

**Comment by jeremyjumeau** [comment]
:+1: 

I did the same, I was inspired by Symfony installation process:
http://symfony.com/doc/current/book/installation.html#book-installation-permissions

**Comment by kehugter** [comment]
If you use Apache, [this](http://stackoverflow.com/questions/11584021/nginx-php-fpm-umask-setting) could help too ([others say](http://stackoverflow.com/questions/21248904/how-to-trace-where-php5-fpm-umask-settings-are-coming-from-on-ubuntu) it doesn't work). I didn't test it, I use nginx.

**Comment by jeremyjumeau** [comment]
I use Nginx too! Thanks for your feedback!
