### ISSUE TITLE
Image .url() is not working as expected

### ISSUE THREAD

**Issue by moreplavec** [getgrav/grav#692]
Today i tried to put some images as _div_ background while using url() method. I tried it this way:
**{{page.media.images|first.resize(500, 500).url()}}**

I cant get URL working, while HTML works fine:
**{{page.media.images|first.resize(500, 500).html('', '', 'img-responsive featurette-image center-block')}}**

**Comment by rhukster** [comment]
Please attach your image for testing.

**Comment by rhukster** [comment]
Still need that image to ensure it's not related to that :)

**Comment by rhukster** [comment]
I cannot replicate this.. works fine for me.
