### ISSUE TITLE
Opengraph Metadata / flat arrays not overridden by YFM in pages markdown files

### ISSUE THREAD

**Issue by 5TFN** [getgrav/grav#694]
I tried to adjust the opengraph metadata as described in the changelog of the 1.0.9 release.

> [BC] Metadata now supports only flat arrays. To use open graph metas and the likes (ie, ‘og:title’), simply specify it in the key.

These flat arrays do work for me in the site.yaml and site-wide.
If I use the same notation in the markdown headers, the site.yaml metadata is not overridden.
I tried a few variations, also mixing flat and non-flat arrays across both files but nothing seems to work.
It looks like the section in the docs [(Opengraph-Metatag-Examples)](http://learn.getgrav.org/content/headers#opengraph-metatag-examples) has already been updated. So I tried that example too…without any luck.
```
metadata:
    'og:title': The Rock
    'og:type': video.movie
    'og:url': http://www.imdb.com/title/tt0117500/
    'og:image': http://ia.media-imdb.com/images/rock.jpg
```

**Comment by flaviocopes** [comment]
Just tested, work fine. 

Make sure you disable or clear the cache.
