### ISSUE TITLE
Invalid Security Token

### ISSUE THREAD

**Issue by Anthonytr** [getgrav/grav#696]
I'm getting a similar problem as https://github.com/getgrav/grav/issues/589

When I'm editing a page for too long and try to save, it sends me to the login page displaying the "Invalid Security Token" error message. I'm running a lightly modified version of the meteorite theme (primarily styling changes)

**Comment by rhukster** [comment]
What version of Grav, Admin plugin, Login plugin, and Form plugin are you running?

```
bin/gpm version
```

For the Grav version, and...

```
bin/gpm index -I
```

For the plugin versions...

**Comment by flaviocopes** [comment]
@Anthonytr define "too long", how much time passed since you opened the page and when you save?

**Comment by Anthonytr** [comment]
I've only experienced it within a few minutes of working on the page. No more than 5 or so minutes






On Mon, Feb 22, 2016 at 2:04 AM -0800, "Flavio Copes" <notifications@github.com> wrote:












@Anthonytr define "too long", how much time passed since you opened the page and when you save?

**Comment by w00fz** [comment]
We are working on a [JS Revamp](https://github.com/getgrav/grav-plugin-admin/tree/feature/es6_revamp) which features a `keep-alive` implementation where this should not be happening anymore.

**Comment by rhukster** [comment]
In the meantime you might want to increase the `session: timeout` value in your system.yaml

**Comment by Anthonytr** [comment]
As for the version numbers

Grav: 1.0.10

`05. Login                [       login        ]  [v1.3.0 ➜ v1.3.1]   (installed)
06. Email                [       email        ]  [v2.1.1 ➜ v2.2.0]   (installed)
07. Admin Panel          [       admin        ]  [v1.0.7 ➜ v1.0.9]   (installed)
08. Form                 [        form        ]  [v1.2.0 ➜ v1.2.2]   (installed)`

And thanks for the recommendations, I'll make the adjustments and see if that helps!

**Comment by rhukster** [comment]
Yup, try a `bin/gpm update` to update your plugins

**Comment by rhukster** [comment]
I think this should be sorted, we've really not seen any invalid token reports in quite some time. Reopen if the issue persists.

**Comment by fourroses666** [comment]
* I have this message now too, after changing CHMOD 755 644 to 775 664.

**Comment by flaviocopes** [comment]
You got the problem after doing the chmod? Before, no issue?

**Comment by fourroses666** [comment]
got it before the chmod.
i just installed it on a subdomain, fresh install. first grav then admin.

**Comment by flaviocopes** [comment]
Not sure why you mentioned "after changing CHMOD 755 644 to 775 664" then, I thought you didn't have it before.

I could find this https://learn.getgrav.org/troubleshooting/common-problems#invalid-security-token-popup-in-admin in our learn site

**Comment by fourroses666** [comment]
Ah I now see, its missing some text I typed, sorry for that.

It makes me a bit sad when I do a clean install and get all kind of issues.
Everything works but these 2 messages; 'insecure token' and the 'fetch error' keep comming. 
Even after changing CHMOD and clear cookies etc, OpenSSL and cURL are enabled etc.

**Comment by flaviocopes** [comment]
Which kind of setup are you on? Windows/Mac/Linux?

**Comment by flaviocopes** [comment]
Looks like a case that could be solved by this new addition to Grav https://github.com/getgrav/grav/pull/1053

**Comment by fourroses666** [comment]
iMac latest IOS, browser FF 49.0.1 and Chrome. Site isn't https. Host uses Linux shared.
Will try when ready.

**Comment by flaviocopes** [comment]
It's merged in the `develop`, if you want to test and report it's working, the more eyeballs on it, the better :)

**Comment by fourroses666** [comment]
Hmm, don't know what happened. Did a "develop" update by overwriting with FTP.
Don't see the Invalid Security Token message anymore.
But some others came along. Could be I didn't update it the correct way.
I'm a front-end developer..

Anyway here's a screeny:
![some-error](https://cloud.githubusercontent.com/assets/523389/19172820/3c27e3de-8c24-11e6-9e60-0057609aa998.jpg)

---

The "funny"  thing is I do get some "can't find page" messages, also with an other CMS in its manager. Don't know if its related to Grav but Grav seems to have it too.
As if its Grav causing the issues. Long time ago when I installed Grav for the first time I experienced it for the first time. Issues went away and are now back after testing / installing Grav again. Could be it has nothing to do with Grav at all.. Just saying what I'm experiencing.

**Comment by w00fz** [comment]
Did you turn off the new ssl verify peer?

**Comment by fourroses666** [comment]
Cleared cache folder. Newsfeed came back up. Looks a lot better now but going to dashboard I still have an error;
"Fetch Failed: NetworkError when attempting to fetch resource."

Also these weird "page not found" issues are there allot. After saving a page for example. Then reload the page a couple of times and then it works again. Really weird.
