### ISSUE TITLE
[add-resource] New Events Plugin

### ISSUE THREAD

**Issue by kalebheitzman** [getgrav/grav#697]
I would like to add the Events plugin to the Grav Repository.

It supports creating basic calendar events with support for repeating daily, weekly, monthly, and yearly events.

https://github.com/kalebheitzman/grav-plugin-events

**Comment by kalebheitzman** [comment]
I've tagged the plugin at 1.0.1

Everything is in working order as far as I can tell including repeating dates.

**Comment by rhukster** [comment]
should be available in GPM in 10mins or so.
