### ISSUE TITLE
Pure Fragment-URL unnecessarily prepended by the page itself

### ISSUE THREAD

**Issue by Ambitionierter** [getgrav/grav#701]
If you provide a link to a fragment within the same page, e.g. [link text](#xyz), the translated html-code looks like /abc/def/#xyz instead of simply #xyz. This alone is not a problem, but combined with the page-scroll-functionality in themes like Grayscale, it becomes a problem, as the smooth page-scroll and the non-altering of the URL don't work as intended. So (?classes=page-scroll#xyz) becomes <a href="/abc/def#xyz" class="page-scroll">link text</a> instead of <a href="#xyz" class="page-scroll">link text</a>.

One might argue, this should be solved within the template, but I think, that the link (#xyz) should correctly translate to href="#xyz", so it's an issue of the core code.

In /grav/system/src/Grav/Common/Uri.php in line 754-761, URLs starting with an # are prepended by $base_url, which i.m.o. should not happen. So, I suggest something along:

        if (isset($url['scheme']) && Utils::startsWith($url['scheme'], 'http')) {
            $external = true;
        } elseif (Utils::startsWith($url_path, '#') || $url_path == '' && $url['fragment']) {
        } elseif (($base_url != '' && Utils::startsWith($url_path, $base_url)) ||
                   $url_path == '/') {
                       $url_path = $base_url . $url_path;
        } else {
            [...]

**Comment by rhukster** [comment]
This was also brought up by @810 so should resolve his issues also.
