### ISSUE TITLE
Derivatives for responsive images producing incorrect results

### ISSUE THREAD

**Issue by rjdusk** [getgrav/grav#704]
When inserting an image with the following code:
`{{ page.media['tromsdalstinden-valley.jpg'].derivatives(320, 2560, 256).sizes('100vw').html() }}
`
it produces the following HTML:
`<img src="/images/5/7/2/4/5/5724582bd8fb3d88b86d69c828a66e1d7b81e008-1b3039f3a86ee6062d97409cb9e8ddff6f98928a-tromsdalstinden-valley2x.jpeg" srcset="/images/0/6/b/3/b/06b3b00a107c878644beace11d9e852513bdfe3b-1b3039f3a86ee6062d97409cb9e8ddff6f98928a-tromsdalstinden-valley2x.jpeg 320w, /images/c/1/0/5/4/c10549d1a00a0ee0f57c6af6064b841258f7b420-1b3039f3a86ee6062d97409cb9e8ddff6f98928a-tromsdalstinden-valley2x.jpeg 576w, /images/c/7/0/2/4/c7024ef7711a20e74288aa4274d8b1ac80e1d6e4-1b3039f3a86ee6062d97409cb9e8ddff6f98928a-tromsdalstinden-valley2x.jpeg 832w, /images/8/e/5/4/4/8e544c51e8bd207818875d89ce88aab2b0d28f69-1b3039f3a86ee6062d97409cb9e8ddff6f98928a-tromsdalstinden-valley2x.jpeg 1088w, /images/5/7/2/4/5/5724582bd8fb3d88b86d69c828a66e1d7b81e008-1b3039f3a86ee6062d97409cb9e8ddff6f98928a-tromsdalstinden-valley2x.jpeg 1280w" sizes="(min-width:80rem) 80rem, 100vw" />`

The srcset should go up to 2560w but it stops at 1280w. The source image here is 2560px in width (see attached
![tromsdalstinden-valley 2x](https://cloud.githubusercontent.com/assets/11424870/13334411/12381bca-dc0c-11e5-891a-00643368c230.jpg)
).

**Comment by fredrikekelund** [comment]
Seeing as the resulting maximum width here is half of the maximum width you're aiming for, is it possible that you put an `@2x` in your image filename? I tried to address some issues around this logic in #1107, so if you want to test again with the latest version of Grav, the problem might have been helped.

**Comment by rhukster** [comment]
Pretty sure we sorted this.. Closing, but create a new issue if this is ongoing.
