### ISSUE TITLE
Responsive images loaded via Markdown behave differently than Twig

### ISSUE THREAD

**Issue by rjdusk** [getgrav/grav#705]
When loading an image into my page via Markdown:
`![Tromsdalstinden valley, Tromsø](tromsdalstinden-valley.jpg?sizes=65vw "Skiing up Tromsdalstinden valley in Tromsø") {.colwrap--100}`
results in the correct behavior. A @2x image is loaded for retina screens where as the @1x (Grav generated) image is loaded on standard screens. 

Why is it then when I load the exact same image via twig:
`{{ page.media['tromsdalstinden-valley.jpg'].sizes('65vw').html('Skiing up Tromsdalstinden valley in Tromsø','Tromsdalstinden valley, Tromsø','colwrap--100') }}`
with the exact same parameters do I NOT get the @2x image loaded for retina screens? The result is @1x image across all screens.

This is further exploration from my previous bug filing here: https://github.com/getgrav/grav/issues/704 

Why do I want to load the images via Twig instead of Markdown? It's mainly the pesky `<p>` tag that wraps around the images. But I find this very strange behavior considering the methods described above are doing the same thing just via different means.

Image attached for further testing: 
![tromsdalstinden-valley 2x](https://cloud.githubusercontent.com/assets/11424870/13347324/4cc49712-dc6d-11e5-8f35-a72b1160896b.jpg)

**Comment by rhukster** [comment]
I did find a bug in Retina images that was not clearing the alternatives properly. This might be related:

https://github.com/getgrav/grav/commit/91222cb32b276b06442656607c0c57ed6a9684f1

Might be worth trying?

**Comment by rjdusk** [comment]
Gave it a whirl @rhukster but no dice, still the same behavior as before.

**Comment by rjdusk** [comment]
Bah! You know what, scratch that last comment @rhukster , you got it right! This fixes the twig loading of retina images issue. When can one expect this fix to go into release (though I'm using locally :+1: )

**Comment by flaviocopes** [comment]
:+1:  will be in the next release, as already in the develop branch.
