### ISSUE TITLE
Softaculous install not setting admin username/password correctly

### ISSUE THREAD

**Issue by 4evermaat** [getgrav/grav#706]
[softaculous](https://www.softaculous.com/apps/cms/GRAV) seems like it does not setup the admin username / password properly.  It does not alert the user of a username or password that is formatted incorrectly.

https://www.softaculous.com/support/open.php .  You can refer to ticket # 865206.  but they do a good job of trying to reach out to the developer.

**Comment by rhukster** [comment]
I've reached out to my contact at softaculous and I'll wait to see what he says.  It's their own custom form, so they will have to mimic the rules we have on our end.

**Comment by rhukster** [comment]
Ok they replied back to me reporting the validation is fixed on their end.
