### ISSUE TITLE
Plugin: plugin_name & camelCase

### ISSUE THREAD

**Issue by absalomedia** [getgrav/grav#707]
This might be a refactoring nuance, but is there any reason why plugin architecture uses `plugin_name` instead of a camelCased variable like: `pluginName` ?

Just seeing it as an issue in CI plugin testing shown [here] (https://codeclimate.com/github/absalomedia/grav-plugin-shoppingcart-pin/issues)

**Comment by rhukster** [comment]
It's really just a coding standard we use. We follow PSR-1 and PSR-2 coding standards but variable names are not really covered.  

We use camel case for methods and classes, but lower+underscored for variables.  This is really to more clearly differentiate them.

Andy
