### ISSUE TITLE
Theme Inheritance Setup

### ISSUE THREAD

**Issue by mttmccb** [getgrav/grav#708]
Could this be handled by using the Grav CLI? (sorry if this isn't the right place)

It seems like the steps are fairly straightforward but it's a bit easy to miss one.

**Comment by rhukster** [comment]
Actually this is something that could be added to a 'developer' plugin I have been thinking about. This developer plugin would have the ability to create a skeleton/base plugin and theme and any other Grav development type tasks.  It would be a set of CLI commands that just help you shortcut some manual steps. 

Stay tuned!

**Comment by rhukster** [comment]
This is done!  Check out https://github.com/getgrav/grav-plugin-devtools
