### ISSUE TITLE
Modular page blueprint is not possible translate

### ISSUE THREAD

**Issue by moreplavec** [getgrav/grav#712]
While creating modular page blueprint i can use _label_ for each field, but not blueprint name itself.

What about add _label_ or use _title_ as page title listed in dropdown list as a name? It can be translated if used like in twig templates.

Example:

**blueprint of modular page without translation:**

>
title: gallery
@extends: default
label: Photogallery

**and with translation:**

>
title: gallery
@extends: default
label: MODULAR.GALLERY.LABEL

with in langauges.yaml file included:

>
cs: 
   MODULAR.GALLERY.LABEL: Fotogalerie

**Comment by flaviocopes** [comment]
I think this is just a Admin plugin issue, the label should be translated.

**Comment by flaviocopes** [comment]
The problem lies in the translation file format. Use:

```
cs:
  MODULAR:
    GALLERY:
      LABEL: Fotogalerie
```
