### ISSUE TITLE
Windows 10 CLI new-project symlink halts project creation

### ISSUE THREAD

**Issue by namekia** [getgrav/grav#713]
Have Grav CLI running on Windows 10 — for the most part. One issue seemingly remains.
The issue involves an incomplete build when running

```
 bin/grav new-project C:/MAMP/htdocs/zzMyNewProject
```

GitBash reports that the directories and files  load. However, the process ends with:

```
...
Pages Initializing
    C:\MAMP\htdocs\gravBlog/user/pages -> Created
    mappings: /.editorconfig does not exist!
    mappings: /codeception.yml does not exist!

install should be run with --symlink|--s to symlink first
```

The following has no effect:
`bin/grav --s new-project C:/MAMP/htdocs/zzMyNewProject`

Perhaps the reported directory structure C:\MAMP\htdocs\gravBlog/user/pages (mix of forward and back slashes) is causing the problem? Note that "gravBlog" is the initiating folder that contains `bin/grav` -- not the newly created project.

I then open gitBash in the newly created folder and run `bin/grav install' to install the dependencies, an error results:

```
$ bin/grav install
'eval' is not recognized as an internal or external command,
operable program or batch file.
ERROR Missing .dependencies file in user/ folder
ERROR invalid YAML in .dependencies
```

I'm sure that this has something to do with the symlink reference. However, a stackoverflow search on this returns a rabbit-hole of regex fixes. I'd rather not go down that path.

**Comment by Vivalldi** [comment]
Hello @namekia 
I'm unable to produce these problems. I'm aware of the `eval` is not recognized (normal for windows) but the missing .dependencies file in user/ is a new one. Did you clone this from github or download a zip?

**Comment by namekia** [comment]
Hi Vavaldi,
Neither of the cases you list above.

I ran into this issue while attempting to begin a new project within the Grav CLI.

After opening GitBash in the root of an existing project (Blog Skeleton), I ran ` bin/grav new-project C:/MAMP/htdocs/zzMyNewProject' with the intent of TESTING the creation of a new project from within the CLI. Yes, I could have easily downloaded another skeleton but that was not what I was testing.

If you have a Windows 10 computer please run the command above in CLI to see if you can replicate my issue.

As I said above, the new project creation process appears to proceed as expected until the end.

This issue either needs to be identified (for Windows) or the learning docs need to be modified to warn of the possible outcome.

This is the docs section I was using as reference:
http://learn.getgrav.org/cli-console/grav-cli#creating-a-new-project

**Comment by Vivalldi** [comment]
I am still unable to replicate this. The only thing I've noticed issues with is when the command attempts to install the dependencies it says 'folder already exists' and the quick fix for that is to cd into that directory and run `bin/grav install` 
Other than that I have no issues.

**Comment by Vivalldi** [comment]
I stand corrected. I am able to replicate it using the Blog skeleton. I'll take a look now and see what I can do to fix it.

**Comment by bgambier** [comment]
Hello, 
same problem for me (Windows 8.1).

Any issue ?

Thx

**Comment by Vivalldi** [comment]
@bgambier what install of grav is giving you issues? Is it the blog skeleton also? or is it just grav a standard grav install?

**Comment by bgambier** [comment]
A standard one, "php bin/grav install". Don't know if it could help, but I tried to "manually" get all dependencies in sub folders with composer, and the app runs perfectly so far...

**Comment by FDiskas** [comment]
I just tryed that. All seems to be working on windows 10
```
php bin/grav new-project D:\xampp2\htdocs\demonas
```

**Comment by namekia** [comment]
This is my experience from a few minutes ago. Please see the  "Page
Initializing" section. Perhaps this is normal?


​

**Comment by rhukster** [comment]
Be curious if anyone has tried the new Bash stuff with Windows 10? I think it's available in the beta/testing releases?

**Comment by namekia** [comment]
Sorry. Please see below. All other aspects of the install seem fine. Perhaps I shouldn't be concerned?

```
Pages Initializing
    mappings: /.editorconfig does not exist!
    mappings: /codeception.yml does not exist!

install should be run with --symlink|--s to symlink first
```

**Comment by rhukster** [comment]
can you provide the full output including the initial command???

**Comment by namekia** [comment]
Sure. Here is the output... Hope it helps.
BTW, using Blog skeleton with Grav version 1.0.10

```

Gregory Chambers@trout MINGW64 /c/MAMP/htdocs/_gChambersBlog (master)
$ bin/grav new-project C:/MAMP/htdocs/zzTestNewestProject

Creating Directories
    Directories already exist

Copying Files
    /.editorconfig -> C:/MAMP/htdocs/zzTestNewestProject/.editorconfig
    /.gitignore -> C:/MAMP/htdocs/zzTestNewestProject/.gitignore
    /CHANGELOG.md -> C:/MAMP/htdocs/zzTestNewestProject/CHANGELOG.md
    /LICENSE.txt -> C:/MAMP/htdocs/zzTestNewestProject/LICENSE.txt
    /README.md -> C:/MAMP/htdocs/zzTestNewestProject/README.md
    /CONTRIBUTING.md -> C:/MAMP/htdocs/zzTestNewestProject/CONTRIBUTING.md
    /index.php -> C:/MAMP/htdocs/zzTestNewestProject/index.php
    /composer.json -> C:/MAMP/htdocs/zzTestNewestProject/composer.json
    /bin -> C:/MAMP/htdocs/zzTestNewestProject/bin
    /system -> C:/MAMP/htdocs/zzTestNewestProject/system
    /vendor -> C:/MAMP/htdocs/zzTestNewestProject/vendor
    /webserver-configs ->
C:/MAMP/htdocs/zzTestNewestProject/webserver-configs
    /codeception.yml -> C:/MAMP/htdocs/zzTestNewestProject/codeception.yml

Pages Initializing
    mappings: /.editorconfig does not exist!
    mappings: /codeception.yml does not exist!

install should be run with --symlink|--s to symlink first

Gregory Chambers@trout MINGW64 /c/MAMP/htdocs/_gChambersBlog (master)
$
```

**Comment by webdev-kiwi** [comment]
To confirm, I'm receiving the same error (win10 pro). v1.1.8 core+admin downloaded from website. I have tried Git Bash, Ubuntu bash, command prompt, and powershell. Each with and without being run as administrator, the issue seems persistent regardless of method. Any ideas?

**Comment by webdev-kiwi** [comment]
I just tried the same on a Ubuntu 16.04 Server, exact same issue.

**Comment by rhukster** [comment]
I think `new-project` looks for files that are only available in the github repo version. The 'packages' probably have `.editorconfig` file and `codeception` folder stripped out.

**Comment by webdev-kiwi** [comment]
Thanks for that, appears to be the case. Works fine using Bash on Ubuntu on Windows on master branch.

**Comment by flaviocopes** [comment]
I think we can safely delete those files, as they are just used for development
