### ISSUE TITLE
Gantry Support

### ISSUE THREAD

**Issue by topwebs** [getgrav/grav#717]
What is the status of Gantry support in Grav?

**Comment by rhukster** [comment]
It's coming :)  I really can't give a timeline.  We needed some improved blueprint functionality and a JS rewrite of the admin to make it a better integration.  This is what we have been focusing on the past month. We'll get his Grav 1.1 release out soon, then G5 for Grav will follow...

**Comment by barryanders** [comment]
Update for current readers: Grav 1.1 is out which indicates, according to the previous post, that G5 is coming soon.

**Comment by w00fz** [comment]
Yes, it will be coming soon. We are in the process of implementing the few last bits required to make Gantry consistently working in Grav like it does with Joomla and WordPress.

Also, keeping in mind it is still all well under development, we started building [CI Builds](http://gantry.org/blog/gantry5-ci-builds) for Grav a while back and you can already play around with the packages (http://gantry.org/downloads#ci-builds). As we get closer to a proper stable state, we will be writing about it to let the community know. Any testing at that point and before the release, will be very appreciated.
