### ISSUE TITLE
Update googlemaps plugin version 0.3.4

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav#718]
Hi,
I release a new googlemaps plugin and gave it tag (and version) 0.3.4.
Can the update be taken into the plugin catalogue?

Thanks,
francis

**Comment by flaviocopes** [comment]
You need to wait up to one hour, it's picked up automatically.
I see the update available now in the plugins list.

**Comment by aptly-io** [comment]
Thank you Flavio!

On 2016-03-05 04:43 PM, Flavio Copes wrote:
> You need to wait up to one hour, it's picked up automatically.
> I see the update available now in the plugins list.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/getgrav/grav/issues/718#issuecomment-192675040

-- 
Kind regards,
francis                   [home page](https://aptly.io)

"Empty cans make the most noise" - Farah Ann Abdul Hadi
