### ISSUE TITLE
Expose the active theme metadata through the grav.theme object

### ISSUE THREAD

**Issue by martinec** [getgrav/grav#720]
Currently, get the version number of the active theme using Twig is possible using e.g.:

```
{% set themeobj  = grav['themes'] %}
{% set themeinfo = themeobj.get(config.system.pages.theme).blueprints %}
<p id="theme-about">{{ themeinfo.name }} {{ themeinfo.version }}</p>
```
But, it doesn't feel very idiomatic. It would be better to have a shortcut through the grav.theme object, e.g.:

```
<p id="theme-about">{{ grav.theme.name }} {{ grav.theme.version }}</p>
```

Or even better, to expose all Blueprint *metadata* information using something similar to: 

```
<p id="theme-about">{{ grav.theme.info.name }} {{ grav.theme.info.version }}</p>
```

**Comment by mahagr** [comment]
Great idea, though in that case we should also expose current settings from the theme object. In that case we need to solve how to access both of those without having name clashes.

**Comment by mahagr** [comment]
Implemented both.

You can access all the blueprint metadata as @martinec proposed, with the exception on `theme.name`, which was already reserved in the object. Use `theme.title` instead.

Configuration can be fetched by `theme.config.value`.
