### ISSUE TITLE
Page::modular() not doing what's advertised to do

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav#724]
I think the docs for the method are wrong or the method implementation is wrong. It returns true if the page is a modular child, while the docs say 

> Gets and sets the modular var that helps identify this parent page contains modular pages

Is the implementation wrong, or the docblock?

Issue raised on the Forum https://getgrav.org/forum#!/getgrav/general:pagemodular-not-returnin

**Comment by rhukster** [comment]
The implementation is wrong, but the docs are probably not.
