### ISSUE TITLE
cannot use page.find() when redirect statement in header

### ISSUE THREAD

**Issue by gigago** [getgrav/grav#727]
Using redirect: statement in the header of page X prevents using page.find(X) in twig. Instead of making page X accessible to twig, the browser is always redirected to the redirect address of page X.

**Comment by flaviocopes** [comment]
I checked. The code explicitly calls the redirect if a redirect is set.

Set the second parameter of find() to true to avoid this behavior, and just store the page instance in a variable.

```twig
	{% set page = page.find('/something', true) %}
	{{ dump(page) }}
```

**Comment by gigago** [comment]
Fair enough, thank you!
