### ISSUE TITLE
Making all extensions and extensionless files available

### ISSUE THREAD

**Issue by anza** [getgrav/grav#728]
Hi,

it seems that file types that can be downloaded from post directory are defined in ```media.yaml```. I have several files with variable extensions and even extensionless files that I'd like to make available with a post.

I was wondering if it was possible in any way to make all files in the post directory available so that I wouldn't need to add the extensions and mime types to ```media.yaml``` - just linking from post to a specific file would suffice.

Also, I'm not sure how extensionless files are currently treated. Would it be possible to make also the extensionless files available? Now I can get only a 404 error when I try to acces such files.

Thank you.

**Comment by rhukster** [comment]
The way Grav works is that it verifies the file type against this `media.yaml` to ensure that it's a file you intend to support.  This is a matter of security as well as control.  You can easily add your own file types by copying the `media.yaml` into your `user/pages/config/` folder and adding any file types you might need.

There is a problem with extensionless files though as Grav will just assume these are routes to pages. Currently it blindly assumes you mistyped the route if it can't fe found as a page in Grav, hence the 404. And combined with the fact it has no extension, and therefore can't be defined in the media.yaml, means it's not going to be found as a media file either.

I'm not sure there's any other solution than zipping it up or something.

**Comment by smz** [comment]
sorry for dropping in and maybe telling something stupid, but... shouldn't access to _physical _files be granted by the `RewriteCond %{REQUEST_FILENAME} !-f` directive found in standard .htaccess?

Also, if the disposition of all those different files with and w/o extension is to be downloaded, couldn't they be the target of `ftp://` links instead of `http://`?

**Comment by rhukster** [comment]
These are not actually physical files, they are files accessed via the page route.. so:

```
/my/page/my_file.jpg
```

as opposed to:

```
/01.my/02.page/my_file.jpg
```

For example.

**Comment by anza** [comment]
Thanks for your answers and sorry for answering late! So I guess there's no practical way to achieve this functionality. I really admit it's surely not what every user needs and not on the list of typical use cases.

@smz Maybe it could work with ```ftp``` but with this implementation it's more about convenience. I selected Grav for convenience, as it is really usable in most situations. Setting up an ftp server in my case would be an overkill.

Anyway, thanks again for your time with my question.

**Comment by rhukster** [comment]
BTW, we're going to add an admin configuration tab to allow editing of the media types.  Should make it easier to add your own if required.

**Comment by smz** [comment]
@rhukster got it, tnxs!

@anza When I was talking about using the FTP protocol I wasn't thinking about using it _instead of_ Grav, but to put into your Grav pages links to the relevant files to be downloaded via FTP. Actually I see there is some issue with that too (_see_ https://github.com/getgrav/grav/issues/738), but I'm sure that will be solved soon. Beware that I based my advice on the basis of my experience that all hosting providers I used so far do offer an anonymous FTP layer, but, as they say, _your mileage may vary..._

Thanks all and keep on going: Grav is really fantastic!
