### ISSUE TITLE
links should point to the modular page that contains it

### ISSUE THREAD

**Issue by calimou** [getgrav/grav#729]
Hi,
Plese see https://github.com/getgrav/grav-skeleton-onepage-site/issues/8
As answered by someone on the chat "looks like a bug, a link in the modular child points to the modular child, but should point to the modular page that contains it. "

Cheers,

**Comment by rhukster** [comment]
https://github.com/getgrav/grav/commit/f74562987dacd46290a7db6c6c4bc66b06c6cd8a

Fixed in develop

**Comment by calimou** [comment]
hi rhukster and thanks. I've cloned grav's develop branch and the skeleton and it seems to solve the issue, but still, if you don't specify an anchor like `[simple one-page site](#)` aren't we expected to see a link to # or #top (for example ?) instead of a link to the child (ie to `home/_callout`) ?
