### ISSUE TITLE
Template "default.html.twig" is not defined when deployed to heroku

### ISSUE THREAD

**Issue by loganfreeman** [getgrav/grav#730]
[evening-meadow-98674.herokuapp.com](https://evening-meadow-98674.herokuapp.com/)

I deployed to a local nginx server. it works fine. when I push to heroku. It throws the following exception.

```shell
git init
git remote add heroku https://git.heroku.com/evening-meadow-98674.git
git add -A .
git commit -m "Add Grav"
git push heroku master
heroku ps:scale web=1
```

This is the Procfile:

```
web: vendor/bin/heroku-php-apache2 ./
```

/app/system/src/Grav/Common/Twig/Twig.php
            $error_msg = $e->getMessage();
            // Try html version of this template if initial template was NOT html
            if ($ext != '.html' . TWIG_EXT) {
                try {
                    $output = $this->twig->render($page->template() . '.html' . TWIG_EXT, $twig_vars);
                } catch (\Twig_Error_Loader $e) {
                    throw new \RuntimeException($error_msg, 400, $e);
                }
            } else {
                throw new \RuntimeException($error_msg, 400, $e);
            }
        }
 
        return $output;
    }
 
    /**
     * Simple helper method to get the twig template if it has already been set, else return
     * the one being passed in
     *

GET Data empty
POST Data empty
Files empty
Cookies
grav-site-8c069df	
"7uaf86jf71m09j94qit62u4iu3"
grav-site-8c069df-admin	
"30fr377olmmsgcos9dlu4qupr6"
Session
user	
User {▼
  #gettersVariable: "items"
  #items: []
  #blueprints: null
  #storage: null
  #nestedSeparator: "."
}
Server/Request Data
COMPOSER_BIN_DIR	
"vendor/bin"
DOCUMENT_ROOT	
"/app/"
HEROKU_PHP_HTTPD_CONFIG_INCLUDE	
"/app/vendor/heroku/heroku-buildpack-php/conf/apache2/default_include.conf"
DYNO	
"web.1"
PATH	
"/app/.heroku/php/bin:/app/.heroku/php/sbin:/app/.heroku/php/bin:/app/.heroku/php/sbin:/app/.heroku/php/bin:/app/.heroku/php/sbin:/app/.heroku/php/bin:/usr/local/bin:/usr/bin:/bin:/app/vendor/bin"
WEB_CONCURRENCY	
"4"
PWD	
"/app"
COMPOSER_VENDOR_DIR	
"vendor"
HOME	
"/app"
SHLVL	
"2"
PORT	
"43113"
HEROKU_APP_DIR	
"/app"
_	
"/app/.heroku/php/sbin/php-fpm"
USER	
"u56975"
SCRIPT_NAME	
"/index.php"
REQUEST_URI	
"/"
QUERY_STRING	
""
REQUEST_METHOD	
"GET"
SERVER_PROTOCOL	
"HTTP/1.1"
GATEWAY_INTERFACE	
"CGI/1.1"
REMOTE_PORT	
"34249"
SCRIPT_FILENAME	
"/app/index.php"
SERVER_ADMIN	
"you@example.com"
CONTEXT_DOCUMENT_ROOT	
"/app/"
CONTEXT_PREFIX	
""
REQUEST_SCHEME	
"http"
REMOTE_ADDR	
"10.234.209.123"
SERVER_PORT	
"80"
SERVER_ADDR	
"172.19.75.122"
SERVER_NAME	
"evening-meadow-98674.herokuapp.com"
SERVER_SOFTWARE	
"Apache"
SERVER_SIGNATURE	
""
HTTP_TOTAL_ROUTE_TIME	
"0"
HTTP_X_REQUEST_START	
"1458077465715"
HTTP_CONNECT_TIME	
"5"
HTTP_VIA	
"1.1 vegur"
HTTP_X_FORWARDED_PORT	
"443"
HTTP_X_FORWARDED_PROTO	
"https"
HTTP_X_FORWARDED_FOR	
"155.101.209.174"
HTTP_X_REQUEST_ID	
"b632799a-5000-4849-b96b-35a4db586752"
HTTP_COOKIE	
"grav-site-8c069df=7uaf86jf71m09j94qit62u4iu3; grav-site-8c069df=7uaf86jf71m09j94qit62u4iu3; grav-site-8c069df-admin=30fr377olmmsgcos9dlu4qupr6; grav-site-8c069df-admin=30fr377olmmsgcos9dlu4qupr6"
HTTP_ACCEPT_LANGUAGE	
"en-US,en;q=0.8"
HTTP_ACCEPT_ENCODING	
"gzip, deflate, sdch"
HTTP_REFERER	
"https://evening-meadow-98674.herokuapp.com/admin"
HTTP_USER_AGENT	
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
HTTP_UPGRADE_INSECURE_REQUESTS	
"1"
HTTP_ACCEPT	
"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
HTTP_CONNECTION	
"close"
HTTP_HOST	
"evening-meadow-98674.herokuapp.com"
FCGI_ROLE	
"RESPONDER"
PHP_SELF	
"/index.php"
REQUEST_TIME_FLOAT	
1458077465.7082
REQUEST_TIME	
1458077465
Environment Variables
COMPOSER_BIN_DIR	
"vendor/bin"
DOCUMENT_ROOT	
"/app/"
HEROKU_PHP_HTTPD_CONFIG_INCLUDE	
"/app/vendor/heroku/heroku-buildpack-php/conf/apache2/default_include.conf"
DYNO	
"web.1"
PATH	
"/app/.heroku/php/bin:/app/.heroku/php/sbin:/app/.heroku/php/bin:/app/.heroku/php/sbin:/app/.heroku/php/bin:/app/.heroku/php/sbin:/app/.heroku/php/bin:/usr/local/bin:/usr/bin:/bin:/app/vendor/bin"
WEB_CONCURRENCY	
"4"
PWD	
"/app"
COMPOSER_VENDOR_DIR	
"vendor"
HOME	
"/app"
SHLVL	
"2"
PORT	
"43113"
HEROKU_APP_DIR	
"/app"
_	
"/app/.heroku/php/sbin/php-fpm"
USER	
"u56975"
SCRIPT_NAME	
"/index.php"
REQUEST_URI	
"/"
QUERY_STRING	
""
REQUEST_METHOD	
"GET"
SERVER_PROTOCOL	
"HTTP/1.1"
GATEWAY_INTERFACE	
"CGI/1.1"
REMOTE_PORT	
"34249"
SCRIPT_FILENAME	
"/app/index.php"
SERVER_ADMIN	
"you@example.com"
CONTEXT_DOCUMENT_ROOT	
"/app/"
CONTEXT_PREFIX	
""
REQUEST_SCHEME	
"http"
REMOTE_ADDR	
"10.234.209.123"
SERVER_PORT	
"80"
SERVER_ADDR	
"172.19.75.122"
SERVER_NAME	
"evening-meadow-98674.herokuapp.com"
SERVER_SOFTWARE	
"Apache"
SERVER_SIGNATURE	
""
HTTP_TOTAL_ROUTE_TIME	
"0"
HTTP_X_REQUEST_START	
"1458077465715"
HTTP_CONNECT_TIME	
"5"
HTTP_VIA	
"1.1 vegur"
HTTP_X_FORWARDED_PORT	
"443"
HTTP_X_FORWARDED_PROTO	
"https"
HTTP_X_FORWARDED_FOR	
"155.101.209.174"
HTTP_X_REQUEST_ID	
"b632799a-5000-4849-b96b-35a4db586752"
HTTP_COOKIE	
"grav-site-8c069df=7uaf86jf71m09j94qit62u4iu3; grav-site-8c069df=7uaf86jf71m09j94qit62u4iu3; grav-site-8c069df-admin=30fr377olmmsgcos9dlu4qupr6; grav-site-8c069df-admin=30fr377olmmsgcos9dlu4qupr6"
HTTP_ACCEPT_LANGUAGE	
"en-US,en;q=0.8"
HTTP_ACCEPT_ENCODING	
"gzip, deflate, sdch"
HTTP_REFERER	
"https://evening-meadow-98674.herokuapp.com/admin"
HTTP_USER_AGENT	
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36"
HTTP_UPGRADE_INSECURE_REQUESTS	
"1"
HTTP_ACCEPT	
"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
HTTP_CONNECTION	
"close"
HTTP_HOST	
"evening-meadow-98674.herokuapp.com"
FCGI_ROLE	
"RESPONDER"
PHP_SELF	
"/index.php"
REQUEST_TIME_FLOAT	
1458077465.7082
REQUEST_TIME	
1458077465
Registered Handlers
0. Whoops\Handler\PrettyPageHandler
1. Whoops\Handler\CallbackHandler

**Comment by loganfreeman** [comment]
```
.
|-- app.json
|-- assets
|-- backup
|-- bin
|-- cache
|-- CHANGELOG.md
|-- codeception.yml
|-- composer.json
|-- composer.lock
|-- CONTRIBUTING.md
|-- images
|-- index.php
|-- LICENSE.txt
|-- logs
|-- Procfile
|-- README.md
|-- robots.txt
|-- system
|-- tests
|-- user
|-- vendor
`-- webserver-configs
```

**Comment by loganfreeman** [comment]
```shell
git clone https://github.com/getgrav/grav.git
cd grav && bin/grav install
bin/gpm install admin
```


The admin works fine on heroku.

**Comment by loganfreeman** [comment]
```shell
find . -type f -name 'default.html.twig'
```

`./user/themes/antimatter/templates/default.html.twig`

the default.html.twig is found inside the antimatter themes folder

**Comment by flaviocopes** [comment]
The template is probably not committed to Git, so not pushed to Heroku. Otherwise no idea, personally had Grav run successfully on Heroku without trouble (http://learn.getgrav.org/hosting/paas/heroku)

**Comment by loganfreeman** [comment]
I found this in .gitignore:

```
user/themes/*
```

**Comment by diazwatson** [comment]
Same issue here and although I removed this line in .gitignore I still have issues accessing the admin panel.
