### ISSUE TITLE
Certain twig functions are deleting accented characters

### ISSUE THREAD

**Issue by bovisp** [getgrav/grav#732]
I have been translating UI-related items in my blog and noticed that when I apply the `titleize` twig function, all accented characters are stripped out. Once I took this function out, the characters came back. A quick check showed that `camelize` behaved the same way. 

Strangely, `humanize` will not strip the characters out, but if an accented character is the first word of a phrase or sentence, Grav will not strip out the character, but will also not capitalize it either. As an example:

`échelle synoptique`

should be changed to

`Échelle synoptique`

but in fact remains

`échelle synoptique`

All other accented characters in `humanize` remain, just as they should.

`@Sommerregen` suggested that I try `underscorize` to test if the accented characters are stripped out, which they are.

**Comment by rhukster** [comment]
will look into this.

**Comment by bovisp** [comment]
Thanks @rhukster !

**Comment by KrakenEXE** [comment]
I can look into this tonight if you haven't done this yet. What do you say @rhukster?

**Comment by rhukster** [comment]
That would be appreciated

**Comment by Sylk** [comment]
This is beyond my technical level. I apologize.

**Comment by pmoreno-rodriguez** [comment]
Hi.
I have also had this problem recently. It seems that the problem is in the following lines of the Inflector.php file in the system/src/Grav/Common folder:
```
public static function titleize($word, $uppercase = '')
     {
         $uppercase = $uppercase === 'first' ? 'ucfirst' : 'ucwords';

         return $uppercase(static::humanize(static::underscorize($word)));
     }
```

If you delete the reference to the `underscorize` function, it works perfectly, but I don't know if that change will affect anything else.

**Comment by pmoreno-rodriguez** [comment]
Hi again.
I think this code is a possible solution. Replace line 201 of Inflector.php to:

`$regex3 = preg_replace('/[^\p{L}^0-9]+/u', '_', $regex2);`

**Comment by pmoreno-rodriguez** [comment]
This code seems to fix the problem:
`$regex3 = preg_replace('/[^\p{L}^0-9]+/u', '_', $regex2);`
