### ISSUE TITLE
Better Document Blueprint Type Options

### ISSUE THREAD

**Issue by LiquidHelium** [getgrav/grav#734]
I've been using grav in production and it's been completley smooth and a lovely experience, so great job guys.

However the place where I have experienced most friction is when trying to figure out how to define the form on my custom pages. There is good documentation explaining how blueprints work and a list of types, but it would really benefit from a full list of what every type can take as an option. For example from the docs right now I can tell there is a checkboxes type, but I'm not sure how to define the checkbox names. I could find out there is a List type, but I had to check through github to find out how to define the types of the list objects. It would also be really helpful to show examples including how to hide fields from the thing your extending (it's not that hard to figure out, but would still be nice).

**Comment by flaviocopes** [comment]
Yes I agree, it's something we need to add to the docs.

**Comment by rhukster** [comment]
We've put some effort into updating our forms documentation types lately.  Today we released a new 'advanced' page for new stuff in the Grav 1.1.0-beta.1 - https://learn.getgrav.org/forms/blueprints/example-config-blueprints
