### ISSUE TITLE
Link with different protocol

### ISSUE THREAD

**Issue by primeinc** [getgrav/grav#738]
If I add a link like this on a non root page
```
**TS:** [ts.example.com](rdp://ts.example.com)
```
generates a link for rdp://ts.example.com/whatever/sub_folder/

I'd expect it to generate a link to: rdp://ts.example.com

Is this an issue with parsedown?

**Comment by flaviocopes** [comment]
Confirmed, looks like an issue in Grav. Using protocols other than `http` or `https` get the page path appended.

**Comment by flaviocopes** [comment]
For the time being, use a plain html URL: 

`**TS:** <a href="rdp://ts.example.com">ts.example.com </a>`

**Comment by flaviocopes** [comment]
@rhukster was able to fix this by adding the protocol to ParsedownGravTrait::$special_protocols, is this the right way?

**Comment by flaviocopes** [comment]
Or should it actually do the opposite? Whitelist `http/https` and leave the others unchanged?

**Comment by rhukster** [comment]
It probably makes more sense to whitelist known correct protocols and attempt to retrieve the correct grav-related path, and leave all others as-is.

**Comment by rhukster** [comment]
Fixed in develop branch

**Comment by smz** [comment]
:+1:  :smile:
