### ISSUE TITLE
Excited about grav

### ISSUE THREAD

**Issue by Ahmed-Badawy** [getgrav/grav#740]
just used grav today for the first time. 
& i am very excited about Grav & i want to translate it into Arabic if you allow me to.
can i ?

**Comment by rhukster** [comment]
The core can be translated here: https://crowdin.com/project/grav-core

The admin plugin can be translated here: https://crowdin.com/project/grav-admin

Just join crowdin and start translating!

Thanks!


On March 23, 2016 at 5:15:53 AM, Ahmed Badawy (notifications@github.com) wrote:

just used grav today for the first time.
& i am very excited about Grav & i want to translate it into Arabic if you allow me to.
can i ?
