### ISSUE TITLE
path to current pages folder....

### ISSUE THREAD

**Issue by 4evermaat** [getgrav/grav#744]
theme-vars link was very helpful.  I see the section that says [`filepath()`](http://learn.getgrav.org/themes/theme-vars#filepath), `filepathclean()`, and `path()`.  

Is there a "`pathClean()`" function?  It would give me relative access to folder path, but from grav root folder. e.g. user/pages/[current page folder]

edit:  This can be more than a question.  it can be a feature request if this function does not yet exist.

**Comment by rhukster** [comment]
Sorry missed this one.  I think what you are looking for is:

```
{{ page.relativePagePath() }}
```

Eg:

```
user/pages/08.test/01.page-headers
```
