### ISSUE TITLE
The Twig `date` filter stopped working correctly after changing to own filter

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#748]
Hello
As the title says the `date` filter not working correctly.
All of the following variants do not work:
```twig
{{ 'now'|date('F jS \\a\\t H:i') }}
{{ 'now'|date('F jS, Y') }}
{{ 'now'|date(config.system.pages.dateformat.short) }}
{{ 'now'|date(config.system.pages.dateformat.long) }}
```
but they work with the standard Twig `date` filter.

Also, maybe you'll consider changing own filter name to something different (maybe `tdate` if it's related to translation) from the predefined standard Twig filter name to avoid confusion.
I guess when someone uses standard Twig filter, the results are expected as they described in Twig documentation.

Besides, Twig has some [extensions](http://twig.sensiolabs.org/doc/extensions/index.html) ([`Intl`](http://twig.sensiolabs.org/doc/extensions/intl.html) and [`Date`](http://twig.sensiolabs.org/doc/extensions/date.html) in particular) which are working fine. For example:
```twig
{{ page.date|localizeddate('long', 'short', grav.language.getLanguage) }}
{{ '01.01.2017'|time_diff }}
```
I personally use these extensions as a plugin:
```php
<?php
namespace Grav\Plugin;

use Grav\Common\Plugin;
use Symfony\Component\Translation\Translator;
use Symfony\Component\Translation\Loader\YamlFileLoader;

class TwigExtensionsPlugin extends Plugin
{
    /**
     * @return array
     */
    public static function getSubscribedEvents()
    {
        return [
            'onPluginsInitialized' => ['onPluginsInitialized', 0],
        ];
    }

    /**
     * Initialize configuration
     */
    public function onPluginsInitialized()
    {
        if ($this->isAdmin()) {
            $this->active = false;
            return;
        }

        $autoload = __DIR__ . '/vendor/autoload.php';

        if (file_exists($autoload)) {
            require_once $autoload;

            $this->enable([
                'onTwigExtensions' => ['onTwigExtensions', 0]
            ]);
        }
    }

    public function onTwigExtensions()
    {
        $extensions = (array) $this->config->get('plugins.twigextensions.extensions');

        if (in_array('date', array_map('strtolower', $extensions))) {
            $language = $this->grav['language']->getLanguage();

            $translation = __DIR__ . '/translations/date.' . $language . '.yaml';

            if (file_exists($translation)) {
                $translator = new Translator($language);
                $translator->addLoader('yaml', new YamlFileLoader());
                $translator->addResource('yaml', $translation, $language, 'date');
            }
        }

        foreach($extensions as $extension) {
            $extension_class = '\Twig_Extensions_Extension_' . ucfirst($extension);
            if (class_exists($extension_class)) {
                if (stripos($extension, 'date') !== false && isset($translator)) {
                    $this->grav['twig']->twig->addExtension(new $extension_class($translator));
                } else {
                    $this->grav['twig']->twig->addExtension(new $extension_class());
                }
            }
        }
    }
}
```

**Comment by flaviocopes** [comment]
Are you using the latest stable Grav, or `develop`?

**Comment by flaviocopes** [comment]
From the title I assume develop, where I merged https://github.com/getgrav/grav/pull/731/files recently.

Can you define "do not work"? What's the expected output, what you get instead?

**Comment by maxlysenko** [comment]
Hello,
I am testing `develop`.

The expected output:
```
{{ 'now'|date('F jS \\a\\t H:i') }}  —> March 24th at 12:56
{{ 'now'|date('F jS, Y') }} —> March 24th, 2016
{{ 'now'|date(config.system.pages.dateformat.short) }} —> 24th Mar 2016
{{ 'now'|date(config.system.pages.dateformat.long) }} —> March 24th at 12:56pm

```
Instead I get empty string.
It returns `false` in debug bar when trying like this `{{ dump('now'|date('F jS \\a\\t H:i')) }}`

**Comment by flaviocopes** [comment]
I added this change to allow Grav to automatically translate the dates, according to the locale.

Might depend on the locale used. 

Using english (or no languages setup) I get

```
March 24S \P\t 11:10 
March 24S, 2016 
24S Mar 2016 
March 24S \P\t 11:10P 
```

Using italian I get

```
Marzo 24S \P\t 10:50 
Marzo 24S, 2016 
24S Mar 2016 
Marzo 24S \P\t 10:50P 
```

There's a problem with the date format however, `S` `P` and `t` are unsupported by that "translation" function I added. 

Will look into that, but definitely should not be an empty object. What's your languages setup?

**Comment by maxlysenko** [comment]
I am testing the default [develop](https://github.com/getgrav/grav/archive/develop.zip) download without changing anything in configuration except enabling the debugging.
If it matters I am testing on Windows the locale and regional settings of the OS is Russian.

**Comment by rhukster** [comment]
I noticed the same weird \P\t in my test setup, wasn't sure where that was coming from. So does seem to be a  problem with formatting at least.

**Comment by rhukster** [comment]
Sorry, sticky button!

**Comment by flaviocopes** [comment]
Reverted the date change in https://github.com/getgrav/grav/commit/7158dd9beb8b80065558669557d10ae20fda4356, now it's back to the original Twig date filter.

- `DateTime` does not handle the locale, it needs the `Intl` extension and a date format using `IntlDateFormatter` to do it, but that does not allow all the Date format identifiers accepted by DateTime, so there was a bit of adjustment to do.
- Using `strftime`, my original try, is not a working way as the date format is too different and not everything handled by `DateTime` does work with `strftime`.
- Some plugins, including "Archives", rely on the date being in english to build the archives links, so that would break this functionality.

I think loading the Intl twig extension http://twig.sensiolabs.org/doc/extensions/intl.html as you suggested is the way to go.

**Comment by flaviocopes** [comment]
Added a PR to load the Intl Twig extension if needed https://github.com/getgrav/grav/pull/758
