### ISSUE TITLE
using underscore vs dashes in page filename

### ISSUE THREAD

**Issue by 4evermaat** [getgrav/grav#749]
how do I get grav to use underscore `_` instead of dashes `-` in the pages filename?  I noticed that grav uses dashes in the page name when there are spaces or on default. I prefer underline.  Is there an admin panel option for this?

I see the option to put `.html` at the end of the page.  But it seems spaces in filename default to `-` instead of `_` .  Any ideas?

**Comment by flaviocopes** [comment]
@4evermaat no there's no such option at the moment. Add it to the Admin Plugin issues to be considered https://github.com/getgrav/grav-plugin-admin/issues/new
