### ISSUE TITLE
Random 404 page errors

### ISSUE THREAD

**Issue by igor-gp** [getgrav/grav#750]
@flaviocopes Hey mate, as requested via https://github.com/gantry/gantry5/issues/1137 here is what happens for me on Grav which causes a 404 page. 

I log into the back end via domain.com/admin, navigate to themes, then go into learn2. I then change the github tree URL and save. It works around 2 times (i.e. 2 saves) but then it keeps throwing 404 pages on save.

Same thing happens in Gantry in WordPress (haven't seen this in Joomla)

I just did some more tests in Grav and this is the strange thing!

Every time i copy and paste in a link it throws the 404 page but then when i copy from within Grav and paste in, it doesn't. So something happens on paste, have a look at the attached video.
[grav save 404.zip](https://github.com/getgrav/grav/files/189165/grav.save.404.zip)

**Comment by rhukster** [comment]
This 'could' be something related to Gantry5 (this is not anywhere near production ready on Grav yet), the other option is that it could well be a server issue.

It's certainly not a Grav-specific thing.

**Comment by flaviocopes** [comment]
Seeing your comments on https://github.com/gantry/gantry5/issues/1137#issuecomment-202322740 looks a environment-specific issue (`mod_security` related)

**Comment by igor-gp** [comment]
I haven't fully tested Grav but i assume it's the same cause. I'll test later today and confirm just in case. The strange thing is, this never used to be an issue. I'm guessing it's possible tweaks to mod security that triggered it.
