### ISSUE TITLE
blog does not display correctly

### ISSUE THREAD

**Issue by georgesuba** [getgrav/grav#751]
hi there.. I am just trying grav, basically just installed and I am unable to create blog.. there is nothing mentioned how to create blog with grav in current documentation however if I follow simple logic to create blog and then post I get always displayed this:
![screenshot from 2016-03-26 05 28 02](https://cloud.githubusercontent.com/assets/13392310/14058312/0165585c-f314-11e5-953c-a4566319f979.png) 

Nothing like its on demo.. can you tell me how to make blog working like on demo page or navigate me to proper documentation where it is described how to get this working? I would like to have few pages and then blog with it. I am trying to replace my documentation site with this however blog is need it. 

Thanks

**Comment by BugHunter2k** [comment]
Have you read the documentation yet? 
http://learn.getgrav.org/cookbook/tutorials/create-a-blog

**Comment by georgesuba** [comment]
@BugHunter2k Hi, yeah sure, the screenshot is showing the result. I did followed exactly what is said on that manual page.

**Comment by rhukster** [comment]
I suggest installing the "Blog Skeleton" package.  This will give you a working installation with a blog just like the demo: http://demo.getgrav.org/blog-skeleton/

It includes Grav + Content + Plugins + Theme: https://github.com/getgrav/grav-skeleton-blog-site/releases/download/1.1.1/grav-skeleton-blog-site-v1.1.1.zip

Probably you missed a step in the process or have your content items configured incorrectly.  If you use the blog skeleton as your base, you can more easily see what you missed.

**Comment by flaviocopes** [comment]
http://learn.getgrav.org/cookbook/tutorials/create-a-blog can help too

**Comment by georgesuba** [comment]
this works out of the box.. the problem was between chair and keyboard.. I did not realized that I should use item instead of blog.. it works now.. thank you all.

**Comment by rhukster** [comment]
hah, "problem was between chair and keyboard", i like hat one!
