### ISSUE TITLE
HTML5 Videos do not loop in Chrome

### ISSUE THREAD

**Issue by ArjanJ** [getgrav/grav#752]
Problem: HTML5 Videos do not loop in Chrome.

Expected Result: HTML5 Videos loop in Chrome.

**Why do I think the issue is with Grav?**
After reading this [stackoverflow issue](http://stackoverflow.com/questions/24904912/html5-video-loop-doesnt-work-on-chrome-sitefinity-cms) I think this problem might be happening in Grav too.

> Chrome/Opera can't loop the video if the video itself is not served with HTTP 206 Partial Content response but 200 OK instead.

When I open up the Network tab in dev-tools the video is served with a 200 OK response status not a 206.

**Comment by rhukster** [comment]
I will look into this, but you could well be on to something.

**Comment by rhukster** [comment]
So i was starting to look into this issue, but I need to know if Grav is streaming your file, or the webserver itself is serving.  For that I need to know what your code/content is you are using to render the HTML5 video?

**Comment by rhukster** [comment]
Actually the more I look into this I think it's a problem with your weberver configuration. I just tested and it is being served by the webserver if you use the markdown sytnax, and I'm receiving the correct `206 Partial Content` status code:

![media grav 2016-04-06 16-24-40](https://cloud.githubusercontent.com/assets/1084697/14334821/37d1086a-fc14-11e5-8cf0-7c5f1a66d1ce.png)

I'm not sure how to fix that exactly, as i've never had to do it.  It will depend on your server and OS however, so you might need to Google it for more details.  Anyway, it doesn't seem to be a Grav issue at this point. 

Please reopen if you feel this was closed in error.  cheers!

**Comment by ArjanJ** [comment]
Ok thanks for looking into this. I'll have to look into my setup deeper. I wasn't loading the video in markdown though, it was in a twig template file, so just raw html, I don't think that would make a difference though would it?

**Comment by rhukster** [comment]
Nope shouldn't make a difference.

**Comment by rhukster** [comment]
BTW, you can test but just putting in some plain old HTML video tag, and seeing if there's anything different.  That would remove the Grav component.

**Comment by rhukster** [comment]
Another report: #793
