### ISSUE TITLE
plugin inheritence....

### ISSUE THREAD

**Issue by 4evermaat** [getgrav/grav#755]
I was thinking about [theme inheritance improvement](https://github.com/getgrav/grav-plugin-admin/issues/434) and then I realized I might have another problem.
I noticed that my theme (gravstrap) called plugin (gravstrap plugin) to render some stuff in the footer that I didn't like.  so I edited some twig files in the plugin to alter the contents of the footer.  The problem with this is that when the plugin gets updated, all those twig files will get overwritten.  so I'd have to remember the exact edits I made so that I can re-edit the files.

The admin panel does not allow users to pick/choose what to update; it's an all or nothing approach.

I'm wondering if there is any way to tell a page or the entire theme to redirect all requests for `pluginA` to `pluginA_mod`  then `pluginA_mod` can inherit most of the qualities of `pluginA` keeping the modifications.

Or at least I can manually update the `pluginA_mod` (copy the newer files) when i have time.

**Comment by flaviocopes** [comment]
Currently this is not possible. You can however put the Twig files in the theme, and those will take precedence over the plugin-provided Twig files.

This is done for example with the Form plugin, with some themes customizing the form.html.twig file markup.

**Comment by rhukster** [comment]
You can extend another plugin by putting logic into a class in one plugin, then extending that class in another.  We use this technique in the Admin Pro plugin as it extends the base Admin plugin.  Also you can modify the Twig paths to control which plugin is providing the templates.
