### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by MATsxm** [getgrav/grav#756]
Bonjour,
I would like to add my new theme to the Grav Repository.
Here are the project details: https://github.com/CaribThemes/grav-theme-tintamarre
I will add the Skeleton later.
Thank you  and do not hesitate if you need any further information.
Regards,
MATsxm

**Comment by rhukster** [comment]
Sorry missed this, will add soon!

**Comment by MATsxm** [comment]
No hurry - thanks

**Comment by rhukster** [comment]
will be in next GPM update.  Thanks!
