### ISSUE TITLE
Pre/Post install/update/remove events for GPM

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav#760]
GPM is currently able to install/update/remove plugins and themes, but there is no ability to run special logic before and after these events.  We want to add this functionality.

**Comment by mahagr** [comment]
PRE:
* check requirements, license etc and prevent installation if not met
* preparations before install/update (offline mode, backups, trigger install for dependency etc)

POST:
* clear cache, generate, re-compile, cleanup, back to online
* post install message, preferably nice section with full control on output
* possibility to run AJAX for time consuming post-installation task

**Comment by rhukster** [comment]
So after discussions, we have come up with the concept of supporting an optional `install.php` in the theme/plugin.

In this class would be methods that would be run at the appropriate stage in the installation process:

- `preInstall()`
- `postInstall()`
- `preUpdate()`
- `postUpdate()`
- `preUninstall()`
- `postUninstall()`

The ability to abort the installation should be possible from any `pre*()` method.

On top of regular work, the ability to add a message to the output should be possible from any `post*()` method.

**Comment by rhukster** [comment]
Closing as PR merge is imminent.
