### ISSUE TITLE
Add possibility to store translations of themes in separate files inside the `languages` folder.

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#761]
```
..
|-languages
|  |-en.yaml
|  |-fr.yaml
|  |-etc.
..
```
like It's already done for plugins.

**Comment by rhukster** [comment]
Please check the commit i made for this issue and let me know if it works.. I didn't check every combination.

**Comment by maxlysenko** [comment]
Hello,
for my test cases it works well.
Thanks.
