### ISSUE TITLE
[add-resource] New Skeleton Tintamarre

### ISSUE THREAD

**Issue by MATsxm** [getgrav/grav#762]
Bonjour,
following the #756 
I would like to add the Skeleton in relation with the Tintamarre theme to the Grav Repository.
Here are the project details: https://github.com/CaribThemes/grav-skeleton-tintamarre
Thank you and do not hesitate if you need any further information.
Regards,
MATsxm

**Comment by rhukster** [comment]
will be in next GPM update. Thanks!
