### ISSUE TITLE
Having a plugin/theme in a folder with the same name of a GPM package one, triggers an update

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav#765]
Issue coming from users following the [Theme Tutorial](http://learn.getgrav.org/themes/theme-tutorial) being prompted by Grav to update the theme as there was a newer version available, because the theme is built in a `bootstrap` folder, and we have a "Bootstrap" theme in GPM that installs there.

After adding the `bootstrap.yaml` file, Grav thinks the theme is from the GPM and needs an update, saying

```
You are running Bootstrap v1.4.1 [updatable: v1.4.1]
```

We should at least:

- [x] ~~First, change the tutorial theme folder, to avoid confusion for new users~~ https://github.com/getgrav/grav-learn/commit/8884963d54562658828e68ab675b556131c902fb
- [x] Avoid Grav prompting for an update if there's no blueprints.yaml file in the theme, which indicates the version installed [PR Ready](https://github.com/getgrav/grav/pull/767)
- [x] Should we also add a special field to a theme/blueprint to indicate it's not from the GPM? Like `private: true` or `gpm: false` or `<suggest better name here>` [PR Ready](https://github.com/getgrav/grav/pull/767)

**Comment by flaviocopes** [comment]
PR https://github.com/getgrav/grav/pull/767 addresses this problem, introducing a check on `gpm: false` in the theme/plugin blueprint, and also avoid trying to update if no version is specified in the blueprint, which means it's not a package published on the GPM.

**Comment by rhukster** [comment]
- [ ] Also want to rewrite the tutorial in question to use the new 'prime-blank' theme i put together for the CLI dev tools.

**Comment by flaviocopes** [comment]
Closing as the issue in code is solved
