### ISSUE TITLE
Assets with the option `pipeline` set to `false` are removed from the output when pipelining assets.

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#770]
Here is example with the latest [`develop`](https://github.com/getgrav/grav/archive/develop.zip) and default Antimatter theme.
For example, the `partials/base.html.twig` template contains the following :
```twig
...
{% block stylesheets %}
    {% do assets.addCss('https://fonts.googleapis.com/css?family=Open+Sans', {'priority':110, 'pipeline':false}) %}
    {% do assets.addCss('theme://css/pure-0.5.0/grids-min.css', 103) %}
    {% do assets.addCss('theme://css-compiled/nucleus.css', 102) %}
    {% do assets.addCss('theme://css-compiled/template.css', {'priority':101, 'pipeline':false}) %}
    {% do assets.addCss('theme://css/custom.css', 100) %}
    {% do assets.addCss('theme://css/font-awesome.min.css', {'priority':100, 'pipeline':false}) %}
    {% do assets.addCss('theme://css/slidebars.min.css') %}

    {% if browser.getBrowser == 'msie' and browser.getVersion == 10 %}
        {% do assets.addCss('theme://css/nucleus-ie10.css') %}
    {% endif %}
    {% if browser.getBrowser == 'msie' and browser.getVersion >= 8 and browser.getVersion <= 9 %}
        {% do assets.addCss('theme://css/nucleus-ie9.css') %}
        {% do assets.addJs('theme://js/html5shiv-printshiv.min.js') %}
    {% endif %}
{% endblock %}
{{ assets.css() }}
...
```
After page refresh with enabled option `assets:css_pipeline` all styles except the pipelined one are removed from the output.
And even if they wouldn't be removed, I suppose assets should be added respecting priority, e.g. if Google Fonts link has the highest priority it should be output first (before the pipelined css file) otherwise the fonts won't be rendered.

The same is true for JS assets. JS assets with  `pipeline: false` are also removed from the output when pipelining is enabled.
```twig
...
{% block javascripts %}
    {% do assets.addJs('jquery', {'priority':101, 'pipeline':false}) %}
    {% do assets.addJs('theme://js/modernizr.custom.71422.js',100) %}
    {% do assets.addJs('theme://js/antimatter.js') %}
    {% do assets.addJs('theme://js/slidebars.min.js') %}
{% endblock %}
{{ assets.js() }}
...
```

**Comment by maxlysenko** [comment]
@rhukster what about suggestion to output assets (js and css) respecting priority and ordering, because assets could depend on each other and loading order could be important?
For example:
```twig
...
{% do assets.addJs('https://some-js-cdn/jquery-2.2.2.js', {'priority':110, 'pipeline':false}) %}
{% do assets.addJs('theme://js/plugin1.js', {'priority':99}) %} -> depends on jquery
{% do assets.addJs('theme://js/plugin2.js', {'priority':98}) %} -> depends on jquery
{% do assets.addJs('theme://js/lib1.js', {'priority':97}) %} -> depends on jquery
{% do assets.addJs('theme://js/lib2.js', {'priority':96}) %} -> depends on jquery
{% do assets.addJs('theme://js/theme.js', {'priority':10, 'pipeline':false}) %} 
...
```
After pipelining we will have something like this:
```html
...
<script src="/assets/<long-pipeline-md5-uid>.js" type="text/javascript" ></script>
<script src="https://some-js-cdn/jquery-2.2.2.js" type="text/javascript" ></script>
<script src="/user/themes/mytheme/js/theme.js" type="text/javascript" ></script>
...
```
But all pipelined js plugins and libraries are depend on jquery and require jquery to be loaded first. So for correct work we should have something like this:
```html
...
<script src="https://some-js-cdn/jquery-2.2.2.js" type="text/javascript" ></script>
<script src="/assets/<long-pipeline-md5-uid>.js" type="text/javascript" ></script>
<script src="/user/themes/mytheme/js/theme.js" type="text/javascript" ></script>
...
```

The same is true for css assets when styles must be loaded in particular order.

**Comment by rhukster** [comment]
Well, the problem is you have picked a simplistic case.  But what about this:

```
{% do assets.addJs('https://some-js-cdn/jquery-2.2.2.js', {'priority':110, 'pipeline':false}) %}
{% do assets.addJs('theme://js/plugin1.js', {'priority':99}) %} -> depends on jquery
{% do assets.addJs('theme://js/plugin2.js', {'priority':98}) %} -> depends on jquery
{% do assets.addJs('theme://js/lib1.js', {'priority':96}) %} -> depends on theme
{% do assets.addJs('theme://js/lib2.js', {'priority':96}) %} -> depends on theme
{% do assets.addJs('theme://js/theme.js', {'priority':97, 'pipeline':false}) %} 
```

This would mean you would need:

...
<script src="https://some-js-cdn/jquery-2.2.2.js" type="text/javascript" ></script>
<script src="/assets/<long-pipeline-1-md5-uid>.js" type="text/javascript" ></script>
<script src="/user/themes/mytheme/js/theme.js" type="text/javascript" ></script>
<script src="/assets/<long-pipeline-2-md5-uid>.js" type="text/javascript" ></script>
...

You would have to split up the pipeline into 2 parts, with the 2 lib.js files pipelined under the un-pipelined theme.js.  This gets very complex very quickly!  If you start running into these situations the whole pipelining process becomes useless as you end up having nearly as many files as you started with.  I think the better/simpler option is to have the pipelined file come **above or below** the non-pipeline stuff.  If that option doesn't solve your issues, then turning off pipeline completely is the best option.

**Comment by maxlysenko** [comment]
But for these simplistic cases, like this:
```twig
...
{% do assets.addCss('theme://css/main.css', {'priority':110, 'pipeline':false}) %}
{% do assets.addCss('theme://css/component1.css') %}
{% do assets.addCss('theme://css/component2.css') %}
{% do assets.addCss('theme://css/component3.css') %}
...
```
and this:
```twig
...
{% do assets.addJs('https://some-js-cdn/jquery-2.2.2.js', {'priority':110, 'pipeline':false}) %}
{% do assets.addJs('theme://js/plugin1.js') %}
{% do assets.addJs('theme://js/plugin2.js') %}
{% do assets.addJs('theme://js/plugin3.js') %}
...
```
what should I do to have the non-pipelined asset **above** the pipelined one, because now the non-pipelined is always inserted **below** pipelined.

**Comment by rhukster** [comment]
Like i said in my comment above, i could add a simple option to "put pipeline first/last".

**Comment by maxlysenko** [comment]
It will be good, if you add such option.
Thank you!

**Comment by rhukster** [comment]
That should do it.
