### ISSUE TITLE
new field type from plugin

### ISSUE THREAD

**Issue by balintgaspar** [getgrav/grav#771]
is there any way to create a new filed type for forms (backend) plugin through a plugin?

Where I need to start?

Thanks! 

Looking forward, Balint.

**Comment by rhukster** [comment]
Yup, basically form fields are just Twig templates.  All you need to do is create a plugin of your own that provides your custom fields as Twig template files, and use the Twig template paths event to register the location of these.  

For example the **Form** plugin does exactly this, you can see the fields defined here: https://github.com/getgrav/grav-plugin-form/tree/develop/templates/forms/fields

And then this path is registered by the plugin via the `onTwigTemplatePaths()` event:  https://github.com/getgrav/grav-plugin-form/blob/develop/form.php#L76-L79

Now the paths under the `templates/` folder is important.. it needs to be `forms/fields/yourfield.html.twig`

Also your plugin will need to to subscribe to this `onTwigTemplatePaths()` event, like the form plugin does: https://github.com/getgrav/grav-plugin-form/blob/develop/form.php#L32-L40

**Comment by tranduyhung** [comment]
Thank you @rhukster , your explanation should be put in the documentation: https://learn.getgrav.org/forms/blueprints/advanced-features. I spent hours to follow the the docs and checked the core code, finally I found this issue. It was so easy!

**Comment by rhukster** [comment]
Feel free to add it to the docs as a PR :) I just don't have time to do it all...

**Comment by tranduyhung** [comment]
I will try. It is just that English is not my mother language :).
