### ISSUE TITLE
We need a way to sell Grav over other well known CMS's.

### ISSUE THREAD

**Issue by mariosant** [getgrav/grav#774]
I suppose this is not your average issue, but it still needs to be addressed.

I get contacted by potential customers, who would like a brand new website to demonstrate their business. 9 out of 10 times, they ask me to use Wordpress which is currently the most popular way to go.

Don't get me wrong, I am not a sales person and as such, I seek tools that will help sell our favorite CMS, over other not so favorite ones. Making Grav a well known, popular choice is very important and should help it to grow into this over-populated ecosystem.

**Comment by smz** [comment]
... give it time, it will grow! :muscle: The guys at Grav are doing really well!!

An idea I'm fancying is to build "_exporters_" for extracting content from the major "_legacy_" CMSs to Grav pages. Not easy, though...

**Comment by flaviocopes** [comment]
Surely a good point. It's our job, a job of the community as a whole, developers, integrators, to spread the word. Probably the most important issue, but one that cannot be fixed with a PR :wink: 

@smz https://wordpress.org/plugins/wp2grav/ (https://github.com/SiteBeez/wordpress-wp2grav-markdown-exporter) is a WP plugin already going in that direction.

**Comment by smz** [comment]
@flaviocopes Wow!!! Interesting!

**Comment by mariosant** [comment]
@flaviocopes I agree with what you are saying. Maybe not the best place to discuss this, but I would really like to know how to deal with this.

**Comment by rhukster** [comment]
The problem we face is Grav is relatively new, it's relatively untested, and the community is in much smaller than WordPress's.  The only way for that ever to change is for it to be more widely used.  This is a classic chicken and the egg situation, so the only way this can change is for developers to convince their clients that it's the better option.

My thoughts on how this can be achieved are:

* Explain to your clients the many benefits of Grav.  Familiarize yourself with the features: https://getgrav.org/features.  

* Also mention that Grav is the #2 most popular PHP CMS on GitHub: https://github.com/search?l=PHP&o=desc&q=cms&s=stars&type=Repositories&utf8=%E2%9C%93 (probably will be number 1 within a few weeks/months)

* Point to good blog posts/articles about Grav such as:
  * https://davidwalsh.name/grav-building-fast-flexible-websites
  * http://www.sitepoint.com/building-faster-websites-with-grav-a-modern-flat-file-cms/

* Be very vocal about Grav in social media - this means tweeting about it as much as possible, getting the name out there, explain the benefits, etc.  Retweeting positive Grav related news, etc.

* Writing about Grav in blogs, news sites, reviews, roundups, etc.  We need to be considered along side other platforms such as WordPress.  People need to be aware that Grav is a viable option!

* Proof is in the pudding!  Show your clients Grav sites you have done (even if it's your own), explain how it was faster to develop a site with, easier to use etc.  Show them it will save them money :)

* Build themes, plugins for Grav to make more options available.  Currently Grav has over 100 plugins and over 50 themes.  This is a lot for most open source CMS platforms, but nothing compared to WordPress or Joomla.  The only way for this increase, is for people to build stuff.  This is happening now, but ever one counts!

Feel free to add other ideas!

**Comment by rhukster** [comment]
Hopefully this info is useful, perhaps at some point we can migrate this information to the docs. Closing this though because I like to keep the issues tracker focused on things we need to get sorted, it's not a wiki :)
