### ISSUE TITLE
Update Googlemaps plugin version 0.3.5

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav#776]
Hi,
I release a new googlemaps plugin and gave it tag (and version) 0.3.5.
Can this update be taken into the plugin catalogue?
Thanks a lot,
francis

**Comment by flaviocopes** [comment]
It's in (https://getgrav.org/downloads/plugins)

That's automatic. When you create a release on GitHub, it's picked up by the GPM in ~1 hour

**Comment by aptly-io** [comment]
OMG! Great I thought I had to ask for it; very nice!


On 2016-04-07 08:38 AM, Flavio Copes wrote:
> It's in (https://getgrav.org/downloads/plugins)
> 
> That's automatic. When you create a release on GitHub, it's picked up
> by the GPM in ~1 hour
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/getgrav/grav/issues/776#issuecomment-206716339

-- 
Kind regards,
francis                   [home page](https://aptly.io)

"Empty cans make the most noise" - Farah Ann Abdul Hadi
