### ISSUE TITLE
Generate a list of main features

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav#777]
As developer of a Grav plug-in, since a specific version I received complaints from a few people that it did not work for them. I failed to detect a common pattern. 

I wonder if it were possible to have a functionality (e.g. a button in the admin page) that returns a description of people's Grav setup: what Grav version, php-version, os-type+version, plug-ins and their version, what settings are overwritten from their defaults, changed sources, used themes and version etc.). This would make it easier for a developer/maintainer to replicate a certain set-up and dig for issues. 

Think of something like a descriptive script (e.g. it could be partly a bash script filled with statements like `bin/gpm install <blable>` and `# grav v1.0.8`) that's generated and is easy to "play back" in order to replicate a certain set-up ...

**Comment by rhukster** [comment]
I have something similar as an issue in the admin plugin issues list.  Let's move any topic there as it makes more sense to be primarily in the admin.
