### ISSUE TITLE
Unable to remove asset collection (jquery) without modifying system

### ISSUE THREAD

**Issue by awhitehouse104** [getgrav/grav#782]
With a fresh install, I can remove the jquery collection from the assets under user/config/system.yaml yet it still loads with `assets.js()`. Only editing the system/config/system.yaml will allow me to remove it.

**Comment by rhukster** [comment]
You should simply remove the:

```
{% do assets.addJs('jquery',101) %}
```

From the theme (probably `templates/partials/base.html.twig`)

However, if you turn on the debugger, it will probably fail because this is auto-loading jquery because it needs it to funciton.

**Comment by awhitehouse104** [comment]
Sorry I failed to mention it, but I did remove the `{% do assets.addJs('jquery',101) %}`.

You're right about the debugger, though. I'm managing jquery on my own and was surprised to see it show up multiple times despite having removed it, so it's strange in this case but it makes sense at least.

**Comment by rhukster** [comment]
Yah you shouldn't really remove it from the collection in the config, if you want to use your own jquery version, you can modify the location to point to yours.  Can we close this?

**Comment by awhitehouse104** [comment]
Yep thanks for the quick response
