### ISSUE TITLE
Redirecting to it's own folder

### ISSUE THREAD

**Issue by mpetricek** [getgrav/grav#783]
Hello everybody! 

I have moved my website from localhost to my shared webhosting. Now from some reason Grav is redirecting from "domain.com" to "domain.com/domain.com/". When I write actual folder where the website is "domain.com/domains/domain.com/" everything is ok. The domain is http://petriczech.com I would appreciate your help a lot! Thank you!

**Comment by flaviocopes** [comment]
The Grav cache was cleared after the move / is disabled?

**Comment by rhukster** [comment]
Sound more like an `.htaccess` or vhost config than Grav itself. Try clearing the cache as @flaviocopes suggests, and let us know if the issue persists.

**Comment by mpetricek** [comment]
Yes, I cleared the cache. I do believe that the problem is in .htaccess file. I think I had similar problem with Joomla! and I solved it with Base URL parameter or something like that. I found on google this https://github.com/getgrav/grav/issues/625 and I believe that I have the same problem. I have the same Hosting provider that's for sure.

**Comment by rhukster** [comment]
Ah we never found a solution for that because we've never seen this setup except on that one provider.  It's very non-standard.  Maybe the provider can help???

**Comment by mpetricek** [comment]
I spent some time with theirs online support and we couldn't find the solution. It's very weird that the page is repeating the domains name in URL.

**Comment by mpetricek** [comment]
I tried now to make clean installation on the server. Again the same problem. Homepage is from some reason redirecting to the domain.com/domain.com

Is there any way how to set up Base URL in Grav?

**Comment by mpetricek** [comment]
So, I tried solution from #625 and it's working for me for now. I don't know in which way it was breaking the Grav for @flaviocopes and @jardicc but in my case everything seems to work good. So for anybody with similar problem - change uri.php (system/src/Grav/common/):

From:
$root_path = str_replace(' ', '%20', rtrim(substr($_SERVER['PHP_SELF'], 0, strpos($_SERVER['PHP_SELF'], 'index.php')), '/'));

To:
$root_path = str_replace(' ', '%20', rtrim(substr($_SERVER['REQUEST_URI'], 0, strpos($_SERVER['REQUEST_URI'], 'index.php')), '/'));

Thank you guys for awesome work! I almost thought that I would have to switch to another platform, but there is simply no other product like Grav!

Cheers!

**Comment by jardicc** [comment]
@mpetricek  I didn't clear cache. I am not sure if cache could cause error.

**Comment by jardicc** [comment]
@mpetricek hostuješ to taky na wedosu?

**Comment by mpetricek** [comment]
Jo, hostuju. Pokud jsi to měl přímo ve složce /www tak tam musíš nechat původní .htaccess od WEDOSu . Ten co má Grav ti přepíše ten původní, takže myslím, že ti to zlobilo kvůli tomu. Já to mám ve složce /domains/mujweb.com

**Comment by flaviocopes** [comment]
Closing as you solved it. 
This looks like an issue related to the Wedos hosting provider only, as it's the same of issue #625?

**Comment by mpetricek** [comment]
It probably is related only to czech Wedos hosting provider and it is same issue as #625 indeed. 
Maybe useful in the future for users with specific FTP folder structure though.
