### ISSUE TITLE
Ordering accentuated characters in page collections

### ISSUE THREAD

**Issue by lprndn** [getgrav/grav#784]
Hi everybody.

When ordering pages collections alphabetically, accentuated characters (like _éàùçì_) are at the end of the list while it could be expected to find them with there non-accentuated equivalent (*e* for *é* and *è*, *a* for *à* and *â* for exemple).

Have a nice day,
Bye

**Comment by rhukster** [comment]
Thanks, will look into this.

**Comment by flaviocopes** [comment]
Fix in develop, will be in the next beta
