### ISSUE TITLE
[add-resource] New plugin cclinker

### ISSUE THREAD

**Issue by BugHunter2k** [getgrav/grav#785]
Just wanted to add a new plugin **creative-common-linker**

Project-Details: https://github.com/BugHunter2k/grav-plugin-cclinker

**Comment by rhukster** [comment]
Noticed a couple of leftover mentions of recapcha contact plugin in the readme.

**Comment by BugHunter2k** [comment]
oh, you're right, fixing this

**Comment by BugHunter2k** [comment]
done.

**Comment by rhukster** [comment]
Cool, will add this soon.

**Comment by rhukster** [comment]
Added to GPM and should be in next update.  Thanks!
