### ISSUE TITLE
getgrav HTML5 Video loop not working

### ISSUE THREAD

**Issue by lid3rs** [getgrav/grav#793]
In Chrome browser HTML5 videos will not loop. I read on SO that it might be because the video response status is 200 OK when it should be 206 Partial Content or something.

Detailed thread: https://getgrav.org/forum#!/general:getgrav-html5-video-loop-no

**Comment by flaviocopes** [comment]
To make a video loop you need to add the `loop` attribute to the `video` tag. Just tested, it works.

**Comment by rhukster** [comment]
This was already reported, but I was unable to replicate.  Videos were sending back the 206 partial content just fine in my testing: 

https://github.com/getgrav/grav/issues/752

I chalked this up to server configuration error, but 2 people having the same problem, probably means there is more to it.   Can you perhaps zip up at 'test' site where this issue happens, so we can try to recreate it?

**Comment by lid3rs** [comment]
@rhukster I've sent you an email with the site link. This is a full dump, just unpack it and you are ready to go. The video is on the front page.

**Comment by rhukster** [comment]
Ok, i recreated this, and found the problem.. in short it's more than just 206 header, you have to handle the HTTP_RANGE information and send back portions of the file.  So was quite a bit more work than I thought but i think i have it fixed.

The `Utils::download()` method has been changed, and the new version is here: https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Utils.php#L227-L298

The quickest solution for you however, is to not use the media URL and simply point your URLs to actual file paths.  For example, your code looks like this:

```
<video autoplay loop preload poster="{{ random_bg_image.resize(1280).url }}" class="frontpage-video__video">
    <source src="bg.mp4" type="video/mp4">
    <source src="bg.webm" type="video/webm">
    <source src="bg.ogg" type="video/ogg">
</video>
```

Change it to:

```
<video autoplay loop preload poster="{{ random_bg_image.resize(1280).url }}" class="frontpage-video__video">
    <source src="/user/pages/01.home/bg.mp4" type="video/mp4">
    <source src="/user/pages/01.home/bg.webm" type="video/webm">
    <source src="/user/pages/01.home/bg.ogg" type="video/ogg">
</video>
```

Tweak those paths as required.

**Comment by MattAppleton** [comment]
Not having any luck with this — video not looping on chrome...

<video autoplay loop preload class="FPvideo green">
    <source src="/UrbanMind/user/pages/01.home/train2_1.mp4" type="video/mp4">
</video>
