### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by RomainFallet** [getgrav/grav#795]
I would like to add my new plugin to the Grav Repository. Here are the project details : https://github.com/numee/grav-plugin-customadmin

**Comment by rhukster** [comment]
Have you tested this with the **develop** versions of Grav + Admin plugin?  I've refactored the CSS considerably.  Probably won't impact your plugin too much other than some CSS class names.  But thought I would mention it as it touches on stuff i've worked on recently.

**Comment by RomainFallet** [comment]
The plugin is very basic, it simply adds links to a blank CSS and JS file to let people customize the admin panel if needed, without having to update the core files of the Admin Panel.
No class name is mentionned.
In fact, the plugin stands in three lines :
        $assets = $this->grav['assets'];
        $assets->addCss('user/plugins/customadmin/customadmin.css', 1);
        $assets->addJs('user/plugins/customadmin/customadmin.js', 1);

**Comment by rhukster** [comment]
ok, should be fine.. i'll get this added in the next day or two.  Cheers.

**Comment by rhukster** [comment]
Should be in GPM soon.  Cheers.
