### ISSUE TITLE
CSS/JS pipelines with absolute urls

### ISSUE THREAD

**Issue by jemmasta** [getgrav/grav#799]
I wish to use absolute urls and I'm using pipelining for css and js.

I noticed that when you turn absolute urls on the compiled css and js tags disappear from the head section of html source breaking the site.

**Comment by rhukster** [comment]
Which version of Grav are you running?

**Comment by jemmasta** [comment]
Tested on production version 1.0.10 and also testing version of 1.1.0-beta.1

Occurs on both.

**Comment by rhukster** [comment]
I'm not really able to repeat this. I'm seeing the generation of the combined `.css` files being generated in assets.  This is correct and functioning correctly.  You might need to try a `bin/grav clear` to clear out any stored assets as these are not automatically regenerated on changes.

I am seeing an issue with relative paths within css files (such as in fontawesome) are not working after pipelineing. This only happens with absolute URLs are on.  I think this is a minor issue that i'll dig into now.  However I don't htink this is the issue you are experiencing?

Also can you try turning **off** CSS Minify? Again you will have to clear the cache to pick up any changes.

**Comment by rhukster** [comment]
BTW fixed that path issue here: https://github.com/getgrav/grav/commit/385c0769644f62ec7404584af1dfe1ed7845ff6b

Don't think that's related to what you are seeing though.

**Comment by jemmasta** [comment]
No it doesn't seem to be the same issue.

I retested this and it seems to be very straight forward. If I have either CSS or JS pipeline on with absolute urls, the head section asset links disappear on css or on js. They reappear as assets if I remove absolute urls setting and pipelines are on. If I have absolute urls on and set pipeline off the linking reappears correctly as separate files.

**Comment by jemmasta** [comment]
Changing minify setting did pretty much nothing on this issue. It is just the pipeline/absolute urls that doesn't work together.

**Comment by rhukster** [comment]
Well, i'm not really able to replicate your problems.  Pipeline is working fine for me both with absolute URLs or not.  I think at this stage i'll need a copy of your `user/` folder zipped up so I can download and test your setup.  There must be something going on here to cause the problems you are experiencing.

**Comment by rhukster** [comment]
Oh hold on a minute.  I re-read your comments.  Let me clarify something regarding pipelining.

What CSS and JS pipelining does is gather up the individual files, and joins them into a single file in the assets folder. This single file is then used.  The purpose of this is improve performance with HTTP 1.1 so you browser doesn't make lots of calls to individual files.  So you should definitely see the individual links being removed and replaced by the single pipelined file.  This is the whole point of pipelining.  Adding minify (on my default) minifies the CSS/JS during this pipeline process so the resulting file is as small as possible.  

So it sounds like what you are seeing is actually what it's supposed to be doing.  Or am i misunderstanding what you are saying?

**Comment by jemmasta** [comment]
Yes, I do know what pipelining does. :)

Maybe I'm not that clear about this issue. Let me clarify to my best ability.

So when configuration has pipeline on without absolute urls the head section shows:

        <link href="assets/myasset.css?g-1a1ac4f9" type="text/css" rel="stylesheet">

and similar with js of course.

But when I set absolute urls on these lines disappear from source and thus no css nor js is loaded in head at all. So when the source should show:

          <link href="http://www.mydomain.com/assets/myasset.css?g-1a1ac4f9" type="text/css" rel="stylesheet">

This line does NOT generate into source. Instead even linebreak is removed and the line disappears.

I hope this clears out the issue. :)

**Comment by flaviocopes** [comment]
I cannot replicate this in both Grav 1.0.10 and in 1.1-beta. Tested with Antimatter. Can you paste your system.yaml?

**Comment by rhukster** [comment]
Ok, so i'm assuming when you say `source` you mean the generated assets file.  To me `source` means what you see when you *view source* in the browser.  This is leading to my confusion.

I think at this point, we need a copy of your `user/` folder zipped up so we can test with your code.  If it works for us, then it's a server issue.  If it doesn't then that will allow us to debug the exact issue.

**Comment by jemmasta** [comment]
No, I do mean view-source in the browser. Those lines I mentioned just disappear and reappear if I toggle absolute urls. anything under assets folder is showing only without domain.

I've attached my user folder. I have set up basis for my own theme that expands Antimatter, but i tested with Antimatter only, clean install on both 1.0.10 and 1.1-beta. Always the same issue. It is weird, since everything else gets the absolute urls just right in view-source, but the two asset lines disappear.

[user.zip](https://github.com/getgrav/grav/files/235241/user.zip)

**Comment by rhukster** [comment]
I just tested with your user.zip and it appears to work as expected.

With `absolute_urls: true` and `assets: css_pipeline: true` i get:

![2016-04-25 13-40-43](https://cloud.githubusercontent.com/assets/1084697/14796595/6c556820-0aeb-11e6-9e86-8450b200ae15.png)

This is the expected result as it has pipelined the individual CSS assets into one file.  Page renders fine, i see the Antimatter styling as expected.

When i turn off CSS pipelining with `assets: css_pipeline: true` , i get:

![2016-04-25 13-42-58](https://cloud.githubusercontent.com/assets/1084697/14796641/a3ecd278-0aeb-11e6-8260-7bf4c86ad823.png)

Again, as expected, this time with no pipelining, just individual files. Again rendering is fine.

This is running the latest Grav 1.1 beta.  I'm just not seeing what your issue is???

**Comment by rhukster** [comment]
Let me try with a vhost, as that can sometimes cause differences.

**Comment by rhukster** [comment]
Nope, works fine with vhost also:

![view-source jemmasta dev 2016-04-25 13-47-27](https://cloud.githubusercontent.com/assets/1084697/14796772/47a1d7ec-0aec-11e6-90c3-cdf1650882d3.png)

**Comment by jemmasta** [comment]
I have nginx as my webserver behind varnish, so there is reverse proxy setup in place. Might that cause this?

**Comment by rhukster** [comment]
it's possible i suppose, i don't have a way to quickly set it up.  

Can you post screenshots like i have of what you are seeing with CSS pipeline on and off.

**Comment by rhukster** [comment]
BTW, rather than varnish have you looked at Nginx microcaching? Better performance i think.

**Comment by jemmasta** [comment]
Here you, go absolute urls off:
![kuvakaappaus 2016-04-25 22 54 40](https://cloud.githubusercontent.com/assets/18602696/14796972/edde0332-0b38-11e6-9ea2-6e4a6566d048.png)

And absolute urls on:
![kuvakaappaus 2016-04-25 22 55 36](https://cloud.githubusercontent.com/assets/18602696/14796978/ff4fccfe-0b38-11e6-814c-6b012ae91622.png)

**Comment by jemmasta** [comment]
Haven't yet tested microcaching. Got good performance with current setup already, so I left it like that. :) Maybe microcaching would be worth taking a closer look.

**Comment by rhukster** [comment]
BTW, have you tried setting `reverse_proxy_setup: true` in the system configuration???

**Comment by jemmasta** [comment]
Yes, I have that setting on, otherwise it would show nginx port in url

2016-04-28 20:52 GMT+03:00 Andy Miller <notifications@github.com>:

**Comment by rhukster** [comment]
FYI i'll need to get some kind of reverse proxy setup in place to debug this further... might not be super quick...

**Comment by jemmasta** [comment]
Can you point me where the absolute urls are handled in the src? I could see if I can find a solution as well.

**Comment by jemmasta** [comment]
Never mind, found it. Will report if I'm able to provide something more.

**Comment by jemmasta** [comment]
Ok, I've noticed so far the following:

in pipelinecss and pipelinejs functions this line: 
        $buffer = $this->gatherLinks($temp_css, CSS_ASSET);

leaves buffer empty when absolute urls are on, it works as it should when they're off.

Digging into gatherLinks function next. :)

**Comment by jemmasta** [comment]
Oh geez, I fixed it. Was not a case of reverse proxy or code... feeling stupid right about now.

When I saw that file_get_contents() function was used, I realized to check php.ini for allow_url_fopen

It was set to off and that caused this. Set that on and everything works. I'm closing this one. :)

**Comment by rhukster** [comment]
Well glad you got that sorted because it would of taken me ages to guess that :)

**Comment by jemmasta** [comment]
Yeah, thought that I'll post this here. the absolute urls function to work always requires allow_url_fopen to be On with any server when using absolute urls.
