### ISSUE TITLE
Installation Exceptions

### ISSUE THREAD

**Issue by jacoblw** [getgrav/grav#800]
Hello,

Running into problems when trying to install - Advice appreciated.
![Error](http://i.imgur.com/k8KjzOm.png)

Directory Permissions are 775
```
drwxrwxr-x. 12 deploy deploy 4096 Apr 21 20:47 grav-admin
```

NGINX Configuration
```
server {
    listen 80;
    index index.html index.php;

    root /var/www/grav-admin;
    server_name grav.domain.com;

    location / {
        try_files $uri $uri/ /index.html;
        if (!-e $request_filename){ rewrite ^(.*)$ /index.php last; }
    }

    location ~ \.php$ {
    try_files $uri =404;
    fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
}
}
```
Env
```
CentOS Linux release 7.2.1511 (Core)
PHP 5.6.20 (cli) (built: Mar 31 2016 07:17:10)
```

**Comment by rhukster** [comment]
It looks like you have a problem with your PHP/Apache setup.  PHP is not able to store session data:

https://www.google.com/?ion=1&espv=2#q=open(%2Fvar%2Flib%2Fphp%2Fsession%2F%20failed%20permission%20denied%20(13)

Google has lots of answers for you, try this one? http://stackoverflow.com/a/6628575

**Comment by jacoblw** [comment]
Just incase anyone experiences this, I ran the following and grav is now working
`chown -R nginx: /var/lib/php/session`
