### ISSUE TITLE
In expert mode: Frontmatter isn't displayed as a 'textarea' anymore in beta 1.1.0

### ISSUE THREAD

**Issue by nepomuk13** [getgrav/grav#802]
Title says it all, frontmatter is no more displayed in a 'textarea' style, no matter how long the text is in beta 1.1.0
Admin panel is: v1.0.9

Edit: I realize maybe this issue is related to admin plugin, sorry if it isn't the correct place.
![capture](https://cloud.githubusercontent.com/assets/12809352/14762055/bcca104c-0971-11e6-8743-c6447d510723.PNG)

**Comment by rhukster** [comment]
You need to be running the latest Admin 1.1.0-beta.1 as well as the Core Grav 1.1.0-beta.1.  

It should show up as a CodeMirror editor.  Does for me.
