### ISSUE TITLE
Grav-v1.0.10 : Blank Screen on apache and 500 Internal Server Error on caddy server

### ISSUE THREAD

**Issue by othpiik** [getgrav/grav#803]
![screenshot from 2016-04-23 23-04-21](https://cloud.githubusercontent.com/assets/11581180/14762574/e8daa7c4-09a7-11e6-8cb0-b437eb1b73aa.png)
![screenshot from 2016-04-23 23-04-21](https://cloud.githubusercontent.com/assets/11581180/14762575/f46a3f14-09a7-11e6-8502-20bbed4062f2.png)

my localhost on Arch linux with Grav-v1.0.10 

```
Apache/2.4.20 (Unix)
PHP 7.0.5 
mode_rewrite enable

Result : Blank screen
```

```
Caddy 0.8.2
PHP-FPM 7.0.5
with rewrite

Result : 500 Internal Server Error 
```

Caddyfile
```
localhost:8080
gzip
errors error.log
fastcgi / /var/run/php-fpm/php-fpm.sock php

# Begin - Security
# deny all direct access for these folders
rewrite {
    r       /(.git|cache|bin|logs|backups|tests)/.*$
    status  403
}
# deny running scripts inside core system folders
rewrite {
    r       /(system|vendor)/.*\.(txt|xml|md|html|yaml|php|pl|py|cgi|twig|sh|bat)$
    status  403
}
# deny running scripts inside user folder
rewrite {
    r       /user/.*\.(txt|md|yaml|php|pl|py|cgi|twig|sh|bat)$
    status  403
}
# deny access to specific files in the root folder
rewrite {
    r       /(LICENSE.txt|composer.lock|composer.json|nginx.conf|web.config|htaccess.txt|\.htaccess)
    status  403
}
## End - Security

# global rewrite should come last.
rewrite {
    to  {path} {path}/ /index.php?_url={uri}
}
![screenshot from 2016-04-23 23-04-21](https://cloud.githubusercontent.com/assets/11581180/14762571/d3c0cd3c-09a7-11e6-93a9-b5351c6f444c.png)

```
any help, please?

**Comment by rhukster** [comment]
does your caddy sever error log give you any detail?

**Comment by rhukster** [comment]
These errors can be caused by missing PHP libraries.  not familiar with ArchLinux, but on Ubuntu/Debian they break out the PHP packages, so you need to ensure you have the critical ones that are usually part of the standard PHP build.

https://learn.getgrav.org/basics/requirements#php-requirements

**Comment by othpiik** [comment]
Re-check my php-modules
```
PHP 7.0.5 , PHP-FPM 7.0.5
GD 2.1.1  enabled 
curl 7.48.0 enabled
OpenSSL/1.0.2g 
Zip 1.13.2 
mbstring enabled / libmbfl version 1.3.2 / oniguruma version 5.9.6 
xml 2.9.3 active
```

Caddy Error logs
```
24/Apr/2016:21:54:28 +0700 [ERROR 500 /] PHP message: PHP Fatal error:  Uncaught RuntimeException: Opening file for writing failed on error fopen(/srv/http/user/config/security.yaml): failed to open stream: Permission denied in /srv/http/vendor/rockettheme/toolbox/File/src/File.php:202
Stack trace:
#0 /srv/http/vendor/rockettheme/toolbox/File/src/File.php(316): RocketTheme\Toolbox\File\File->lock()
#1 /srv/http/system/src/Grav/Common/Config/Setup.php(250): RocketTheme\Toolbox\File\File->save(Array)
#2 /srv/http/system/src/Grav/Common/Config/Setup.php(175): Grav\Common\Config\Setup->check(Object(RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator))
#3 /srv/http/system/src/Grav/Common/Grav.php(213): Grav\Common\Config\Setup->init()
#4 /srv/http/index.php(38): Grav\Common\Grav->process()
#5 {main}
  thrown in /srv/http/vendor/rockettheme/toolbox/File/src/File.php on li...
```

Permission denied ??? how to fixed, please?

This command  not work!
```
chgrp -R http .
find . -type f | xargs chmod 664
find . -type d | xargs chmod 775
find . -type d | xargs chmod +s
umask 0002
```

**Comment by rhukster** [comment]
Well it seems like you might of already read this: https://learn.getgrav.org/troubleshooting/permissions

But the problem lies in your files have permissions such that the webserver is unable to write to them.  When I run php-fpm i like to setup the pool so that it runs with the same user/group that own the files.  You can see how I do this in this DigitalOcean writeup that uses Nginx and PHP-FPM: https://learn.getgrav.org/hosting/vps/digitalocean#configure-nginx-connection-pool

Most hosting providers use SuPHP to achieve the same result, but if you do this, you will never have any permissions issues ever again :)

**Comment by rhukster** [comment]
BTW, you don't have to use your own user, you can create another unprivileged user that you use for both PHP and files access.  However, most setups have webserver/php running with a user that has no shell, so you can't login or su to it.

**Comment by othpiik** [comment]
fixed with 
```
chown http:http .
chown -R http:http *
find . -type f | xargs chmod 664
find . -type d | xargs chmod 775
find . -type d | xargs chmod +s
umask 0002
```

I am use Arch Linux, another distro maybe different..

**Comment by rhukster** [comment]
You'll just need to make sure than you always chown the files to `http:http` if you edit/create from the terminal/ftp.  That's why i prefer to use a user that can login.
