### ISSUE TITLE
[add-resource] New Plugin - Markdown Font Awesome

### ISSUE THREAD

**Issue by yoshikin** [getgrav/grav#804]
I would like to add my new plugin to the Grav Repository.
Here are the project details:

https://github.com/yoshikin/grav-plugin-markdown-fontawesome

It's a simple parsedown extension for Font Awesome (alternative to shortcode)

**Comment by rhukster** [comment]
Thanks will get this added to GPM soon.

**Comment by rhukster** [comment]
Ok added. Should show up in next GPM regeneration.  Thanks!
