### ISSUE TITLE
In-line edit pages

### ISSUE THREAD

**Issue by phsc** [getgrav/grav#805]
As we all know, Grav is very versatile and can even be used as a wiki due to the Learn2 theme.

But to make Grav a real wiki replacement, it has to offer in-line edit of pages as you know it from all the common wiki engines.

I also think, that this feature would be very useful for a lot of basic users.

**Comment by flaviocopes** [comment]
A wiki engine is certainly not trivial to build, but can surely be built as a Grav Plugin. Maybe post on the forum, I remember other posts asking for this, could trigger the interest of other developers too. Grav is Open Source and as such the effort of everyone is very much welcome, especially for plugins and themes that extend the platform. 

Closing this as it's not a Grav issue but a request for a non-core feature.

**Comment by phsc** [comment]
I've just searched the forum and found the following post:
https://getgrav.org/forum#!/general:subj-lets-talk-about-con

Just for information purposes, if anyone is interested in it.
