### ISSUE TITLE
[add-resource] New Plugins - ShoppingCart Email Notifications, Manual Checkout, Product Variations

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav#807]
All pre-releases for the testing channel.

Projects details:

https://github.com/flaviocopes/grav-plugin-shoppingcart-email
https://github.com/flaviocopes/grav-plugin-shoppingcart-manual-checkout
https://github.com/flaviocopes/grav-plugin-shoppingcart-product-variations

**Comment by rhukster** [comment]
You've been busy :)

**Comment by rhukster** [comment]
Added
