### ISSUE TITLE
Apache 403 page instead of custom error page

### ISSUE THREAD

**Issue by liebig** [getgrav/grav#808]
First I want to say thank you for Grav, because it is an amazing CMS! But I am getting the ugly default Apache 403 page if I try to access a forbidden directory (for example /backup, /vendor, ...):

![image](https://cloud.githubusercontent.com/assets/3033740/14887466/48de3508-0d56-11e6-8b46-8bc1f673d832.png)

My Apache 000-default.conf file looks like:
```
<VirtualHost *:80>
	<Directory /var/www/html>
        	Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
	</Directory>
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

I tried several config changes (e.g. ErrorDocument), but only the default Apache error page occures for the 403 error. If I remove the `[F]` flag from the `RewriteRule` at the `.htaccess` file (e.g. line 47 and 57) it works for files (LICENSE.txt, composer.lock, composer.json) but not for folders (cache, bin, logs, backup, webserver-configs) because of an `ERR_TOO_MANY_REDIRECTS` error. I would like to return the 403 Forbidden header and show the content of the root homepage or error page.

Thanks!

**Comment by rhukster** [comment]
Well, this is because the .htaccess is specifically blocking this, hence the Apache style error message. Maybe this will help?

http://stackoverflow.com/questions/30983968/simple-way-to-redirect-403-and-404-errors-to-the-main-page-htaccess

**Comment by liebig** [comment]
If I add `ErrorDocument 403 /` to the `.htaccess` file I got a `ERR_TOO_MANY_REDIRECTS` error. The best way would be a redirect to a custom error page (e.g. /error/forbidden). Any ideas how can I achieve this? Thank you.

**Comment by flaviocopes** [comment]
`ErrorDocument 403 http://yoursite.com/error/forbidden` 

should work

**Comment by liebig** [comment]
Yeah it does, thanks. But is there a way to do this via relative path?

**Comment by rhukster** [comment]
This maybe possible, but i'm afraid I don't know off hand.  At this point, it's purely an Apache thing, and not a Grav thing. So closing.
