### ISSUE TITLE
Remove a particular page from the cache by code

### ISSUE THREAD

**Issue by ikabod** [getgrav/grav#810]
For dynamic generated content I would need a function to remove a particular page from the cache by code in my plugin, something like this:

`$this->grav['cache']->clearPage('03.Temp')`

**Comment by rhukster** [comment]
Rather than clearing cache, how about the ability to just recache the content?  We already have a private method to do this, i could just expose this as a public method:

```
    public function cachePageContent()
    {
        $cache = Grav::instance()['cache'];
        $cache_id = md5('page' . $this->id());
        $cache->save($cache_id, ['content' => $this->content, 'content_meta' => $this->content_meta]);
    }
```

It would take whatever has been currently set for `Page::$content` and recache it with the same ID.
