### ISSUE TITLE
Filtering different categories for a blog archive

### ISSUE THREAD

**Issue by minimalex** [getgrav/grav#811]
Hi

I have a question about the filtering synthax in the find() function. Is it somehow possible to feed it with different tags or categories so that I can build an archive from items in different folders? The documentation is just covering items on one ('/blog') page.

My initial plan was to do this:

{% for post in page.find(['/category1', '/categoriy2', '/category3']).children.order('date', 'desc') %}

Thank you

**Comment by rhukster** [comment]
This is possible, you just need to use Taxonomy object:  https://learn.getgrav.org/content/taxonomy#taxonomy-example
