### ISSUE TITLE
Date problem

### ISSUE THREAD

**Issue by ikabod** [getgrav/grav#812]
I'm used to show visitors of my website both, the creation date and the modified date. So they can see how old a post is and when it was last modified.

So I thougt "page.date" in a twig template gives back the creation date of a markdown file and "page.modified" the last modified date. But the docs says:

> The date variable allows you to specifically set a date associated with this page. This is often used to indicate when a post was created and can be used for display or sort-order purposes. If not set, this defaults to the last modified time of the page.

Is it possible to change this behaviour as I thought it is? Normally there should be no need to set creation and/or modified date manually. 

Currently I have to do this if I want to show both dates. So it would be better practice not to set theese dates manually for each markdown file but only for that I want to override it.

**Comment by rhukster** [comment]
Being a flat-file system, there is no database.  What this means is that we only have the file to work with. There is a dynamic modification date available, so you can use `page->modified()` for that, and you can then manually set the date the file was originally published via the `date:` Page header, and that's accessible via `page->date()`

**Comment by ikabod** [comment]
Ah, ok, I did not knew that there is no creation date on most file systems except Windows.

**Comment by ganar** [comment]
@rhukster 

I'm sorry to bother again with this issue.

But.

Shouldn't the creation date be set automatically when creating content within GRAVCMS? It seems counter-intuitive not to register the date automatically when creating the content. 

Am I missing a configuration option?

**Comment by rhukster** [comment]
The admin tries to where to the principals of the core (without admin) as much as possible. This means that it only adds things to the frontmatter only if you explicitly tell it to do so. Automatically adding dates is one such example.

**Comment by flaviocopes** [comment]
This plugin https://github.com/getgrav/grav-plugin-auto-date will add the current date when the page is created. Your theme can then render that header field.
