### ISSUE TITLE
Escaped html entity in admin panel options tooltip

### ISSUE THREAD

**Issue by tfeldmann** [getgrav/grav#813]
As you can see in the screenshot escaped HTML entities are shown in the tooltip of the "Show GitHub Link" in admin panel plugin options.

![bildschirmfoto 2016-05-02 um 15 34 23](https://cloud.githubusercontent.com/assets/385566/14955633/9141f104-107b-11e6-907a-9c0944b991e1.png)

I'm using the admin panel v1.1.0-beta.2.

**Comment by rhukster** [comment]
Pretty sure this is fixed already in develop branch, but i'll double check.

Also, FYI please put admin issues here: https://github.com/getgrav/grav-plugin-admin/issues
