### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by koca** [getgrav/grav#815]
Hello ^^
I would like to add my new theme to the Grav Repository. 
Here are the project details: https://github.com/koca/grav-theme-masonry
Thanks.

**Comment by rhukster** [comment]
You will need to create a release within GitHub before it shows up in GPM.

https://help.github.com/articles/creating-releases/

The version number you tag the release with should match the version number in the `blueprints.yaml`

**Comment by koca** [comment]
Alright, done :)

**Comment by rhukster** [comment]
And now showing up in GPM.
