### ISSUE TITLE
White page after installation

### ISSUE THREAD

**Issue by kultz** [getgrav/grav#816]
I've installed grav on my own VPS but a white page shows up when i open home page.
I can't figure out what's wrong because everything is fine, and dependencies installed both composer and server.

**Comment by flaviocopes** [comment]
A white page is generally an error page, it should show a message but your PHP error reporting is probably too low. So try turning error reporting to the maximum level in your `php.ini` file first.

Also, which PHP version are you running?

**Comment by kultz** [comment]
It was a permission issue, I was almost sure about permissions but after a double check i realized that's not set in appropriate way.
Thank you @flaviocopes
