### ISSUE TITLE
Lock system plugins so they can't be deleted via admin panel

### ISSUE THREAD

**Issue by rsip22** [getgrav/grav#817]
I found out the hard way that some plugins cannot be uninstalled or Grav just might stop working. I was uninstalling a few plugins and did this by accident. I can not find a way to fix this other than re-installing Grav, so...

I want to suggest that such plugins (admin, login, forms and email, I believe) to be locked from deleting via admin panel, to prevent this from happening to someone else.

**Comment by flaviocopes** [comment]
Yes, Admin depends on Form, Login, Email. 
Version 1.1 Beta 3 already denies disabling Form and Email (and Admin itself) through the Admin interface. Beta 4 will also apply this to Login (just committed a fix). You can still disable them from the command line or file system.

But removing one of these plugins was still possible, so I just committed a fix to avoid removing the required plugins in https://github.com/getgrav/grav-plugin-admin/commit/c9e9588ccc61ccd4e011dfb275153306718b78f8
