### ISSUE TITLE
Not found on home page

### ISSUE THREAD

**Issue by kultz** [getgrav/grav#818]
I've downloaded grav-admin-v1.0.10.zip from the website after unzip, When i open up my home page: a "404 Not Found" shows up. What's wrong with it?
php -v
PHP 5.5.9-1ubuntu4.16 (cli) (built: Apr 20 2016 14:31:27)

**Comment by flaviocopes** [comment]
Most likely one of these problems: learn.getgrav.org/troubleshooting/page-not-found

**Comment by kultz** [comment]
The 404 error is a grav style 404 not a web server style.
This is the default .htaccess on my server and i don't believe there's a problem with it:  http://pastebin.com/8qyN71QP

> Maybe helps:

 I'm using nginx and apache(for handling php and of course .htaccess)

**Comment by rhukster** [comment]
To get past the 'forcing' of user creation, can you create a user manually.  Then we can see if it works by default on the 'homepage'. https://learn.getgrav.org/admin-panel/faq#adding-and-managing-users

**Comment by kultz** [comment]
@rhukster Thank you Andy, But I believe that's not the point because i've already created a user by `bin/plugin login newuser`

**Comment by rhukster** [comment]
so you get this on the 'homepage', does your `user/config/system.yaml` have `home: alias: /home` and is there a `user/pages/01.home/` directory ?

**Comment by kultz** [comment]
`home: alias: '/home' ` is exists, `user/pages/01.home/`directory is available too.

**Comment by kultz** [comment]
I don't know what's wrong, I tried to set it up same way on MAMP(on Mac) then here you go: Grav is Running!

**Comment by rhukster** [comment]
So is it working?

**Comment by rhukster** [comment]
does it work going to `/admin` too?

**Comment by kultz** [comment]
On MAMP yes everything is fine, But my server as i said!

**Comment by kultz** [comment]
Update:
As i mentioned i'm running both Apache and Nginx, But I realized that Grav is running perfect on Apache alone after requesting to 8080(I've set port 8080 for Apache-only).
server:80 (apache + nginx) : 404 Not Found
server:8080 (apache): working fine

I'm pretty sure i need to reconfigure Nginx!
Thank you @rhukster @flaviocopes
