### ISSUE TITLE
Theme infos error

### ISSUE THREAD

**Issue by qmarlats** [getgrav/grav#823]
When clicking on a theme, an error is shown:
`An exception has been thrown during the rendering of a template ("Array to string conversion") in "partials/themes-details.html.twig" at line 72. `
As error say, it's because Grav try to show an array of keywords as a string. You should replace:
`{{ theme.keywords }}`
By something like:
`{% for keyword in theme.keywords %}{{ keyword }}{% if not loop.last %}, {% endif %}{% endfor %}`

Edit: I think this issue should be moved to the admin plugin. Excuse me I discovered Grav few minutes ago. ^^

**Comment by rhukster** [comment]
Keywords are generally a string, which theme did you find this in?

**Comment by qmarlats** [comment]
I think it was [this theme](https://github.com/sommerregen/grav-theme-machine) but not sure, I just tested Grav so I don't have access to it anymore.

**Comment by rhukster** [comment]
Thanks i'll put a check in to handle both strings and array.

**Comment by rhukster** [comment]
Fixed in repo.
