### ISSUE TITLE
site.login: true, But page still accessible

### ISSUE THREAD

**Issue by adamgajzlerowicz** [getgrav/grav#824]
In the page's configuration  I set `site.login: true` in the header.

When I try to visit the page I am asked for a password. If I login with incorrect credentials or no credentials the content of the restricted page is showing. Page is malformed but visible. Information about incorrect login does show, but below the content of the shown page.

I am running latest grav, on a fresh project (I am learning at the moment)

Thank you

**Comment by rhukster** [comment]
Thanks for the report, this is actually a problem with the **login** plugin.  I'll leave it here though as you've already created it.

**Comment by flaviocopes** [comment]
Should already be fixed in version 2.0, which is currently in beta using Grav 1.1.

Going to fix this on the stable (1.3) version of the Login plugin too, with a minor release.

**Comment by adamgajzlerowicz** [comment]
Thank you for your reply. 
How can I upgrade plugin to 1.3, or tell which one is currently installed? I can't find it in my composer.json file.

**Comment by flaviocopes** [comment]
You can check it via Admin, or in the user/plugins/login/blueprints.yaml file

**Comment by adamgajzlerowicz** [comment]
I have updated the plugin to 1.3 and the issue is gone. Thank you.
