### ISSUE TITLE
Special character > is translated differently

### ISSUE THREAD

**Issue by jimmysjolund** [getgrav/grav#825]
When using the character > in text, such as text arrow ->, it translates correctly in the actual blog post. But in the blog roll (so to speak) it will get translated to `&gt;` . Further if I use a workaround such as `<i class="fa fa-long-arrow-right"></i>` it doesn't show anything in the blog roll but show the arrow when reading the actual blog post.

 .

**Comment by jimmysjolund** [comment]
Should probably mention I was using the theme "antimatter".

**Comment by flaviocopes** [comment]
Quick fix: add `===` in a line to add a manual summary, it's not affected by this problem.

The automatic summary calculation strips HTML tags (fine) but also encodes html entities. @rhukster should we decode them before returning the summary? 

`return html_entity_decode(Utils::truncateHTML($content, $size));` in https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Page.php#L503 ?

**Comment by rhukster** [comment]
Yes, i think that is what's needed.  I'll add it.

**Comment by rhukster** [comment]
Fixed for next release
