### ISSUE TITLE
Plugin name and meta data not populating from yaml file on admin page

### ISSUE THREAD

**Issue by adamgajzlerowicz** [getgrav/grav#827]
I have created a test plugin and in the admin all I can see is `v`.

Please see on the screenshot. Am I missing something?
Here is my importer.yaml file:
```
name: importer
version: 0.1
enabled: true
route: /foo
filename: feed
```

![image](https://cloud.githubusercontent.com/assets/675615/15115255/fdd607ea-15f5-11e6-9375-ab909a59425a.png)

**Comment by rhukster** [comment]
you need a `blueprint.yaml` to define the information that tell's Grav about your plugin.  

The best way to create a new plugin, is to use the devotools plugin from the CLI: https://github.com/getgrav/grav-plugin-devtools

This will create all the required files and give you a working plugin base to start from.

NOTE: I will be updating the docs soon to reflect this.
