### ISSUE TITLE
Admin Area Title Needs Fixed

### ISSUE THREAD

**Issue by umbergerba** [getgrav/grav#829]
FYI ... under new beta4 ... see attachment. The custom name over-runs the given area for title. THX!

![capture](https://cloud.githubusercontent.com/assets/5008228/15146325/51c48e0a-1680-11e6-8ade-6b61c7aee576.PNG)

**Comment by flaviocopes** [comment]
How did you add the custom name?

**Comment by Quy** [comment]
I can reproduce it under Plugins>Admin Panel, `Logo text`.

**Comment by rhukster** [comment]
Ok as there's no way to guarantee custom strings will fit, i've styled this so the first letter is displayed:

![plugin admin panel grav 2016-05-10 10-46-50](https://cloud.githubusercontent.com/assets/1084697/15154776/94ddf3b8-169c-11e6-916e-98fff977d3c4.png)

FWIW, this was an admin issue and should be opened in admin plugin in the future.

**Comment by umbergerba** [comment]
That should do the job then ... Thx!
