### ISSUE TITLE
Exceeded filesize limit

### ISSUE THREAD

**Issue by rickysullivan** [getgrav/grav#830]
I'm trying to upload a 2.9Mb image file to a page's media section.

I've increased my ``client_max_body_size`` in nging.conf to ``200M``

And checked my PHP config.

What else would be causing this error?

**Comment by rickysullivan** [comment]
Found another php.ini in 'fpm' folder. Fixed.

**Comment by btn0s** [comment]
Where are these files located? I need to up that limit as well.

**Comment by flaviocopes** [comment]
Varies depending on your setup. Ask you hosting provider first.
