### ISSUE TITLE
`gpm` throws unhelpful exception

### ISSUE THREAD

**Issue by victormoukhortov** [getgrav/grav#831]
Using Grav Package Manager version 0.9.37. Paths truncated for clarity.

```
bin/gpm index -vvv
                                          
  [Whoops\Exception\ErrorException]        
  Invalid argument supplied for foreach()  
                                           
Exception trace:
 () at /Users/.../system/src/Grav/Common/GPM/Remote/Grav.php:30
 Whoops\Run->handleError() at /Users/.../system/src/Grav/Common/GPM/Remote/Grav.php:30
 Grav\Common\GPM\Remote\Grav->__construct() at /Users/.../system/src/Grav/Common/GPM/GPM.php:44
 Grav\Common\GPM\GPM->__construct() at /Users/.../system/src/Grav/Console/Gpm/IndexCommand.php:55
 Grav\Console\Gpm\IndexCommand->execute() at /Users/.../vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /Users/.../vendor/symfony/console/Application.php:878
 Symfony\Component\Console\Application->doRunCommand() at /Users/.../vendor/symfony/console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Users/.../vendor/symfony/console/Application.php:126
 Symfony\Component\Console\Application->run() at /Users/victorm/src/amayasoftware.com/bin/gpm:56
```

Any `gpm` command will result in this exception. The fix seems to be to run `gpm index -f` (what is being forced I have no idea), after which `gpm` starts to work normally. A more helpful error message might be useful here.

**Comment by flaviocopes** [comment]
0.9.37 is 10 months old. 
Can you check if you get the same issue on a 1.0.10 / 1.1 beta release, on the same server? You can install it in a subfolder, just to try.

**Comment by rhukster** [comment]
I didn't catch that it was such an old version.  maybe we fixed something since then that forces GPM to grab newer content before failing.  If you could try a newer version that would help a lot!

**Comment by victormoukhortov** [comment]
Newer version seems to work fine. Thanks for looking into it.

**Comment by rhukster** [comment]
Great closing...
