### ISSUE TITLE
Regex_replace filter does not conform to PCRE syntax

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#833]
Running Beta4, the `regex_replace`-filter does not appear to work. For example, running a pure installation of Beta4 with the only change being to `default.html.twig` in the Antimatter-theme:

	{% extends 'partials/base.html.twig' %}

	{% block content %}
		{{ page.content|regex_replace("/<p>(.*?)<\/p>/", '<p class="col-md-8 offset-md-2">$1</p>') }}
	{% endblock %}

A pattern which essentially captures the content of the paragraph, and rewraps it with a `class="col-md-8 offset-md-2"`-attribute, [like this](https://regex101.com/r/hF6wK9/1). When wrapped as a simple plugin the pattern works:

	class WrapPlugin extends Plugin
	{
		public static function getSubscribedEvents() {
			return [
				'onPageContentProcessed' => ['onPageContentProcessed', 0]
			];
		}

		public function onPageContentProcessed(Event $event)
		{
			$page = $event['page'];
			$pluginsobject = (array) $this->config->get('plugins');
			$pageobject = $this->grav['page'];
			if (isset($pluginsobject['wrap'])) {
				if ($pluginsobject['wrap']['enabled'])  {
					$buffer = $page->content();
					$url = $page->url();
					$buffer = preg_replace("/<p>(.*?)<\/p>/",
						'<p class="col-md-8 offset-md-2">$1</p>',
						$buffer);
					$page->setRawContent($buffer);
				}
			}
		}
	}

Which returns:

	<p class="col-md-8 offset-md-2">Congratulations! You have installed the <strong>Base Grav Package</strong> that provides a <strong>simple page</strong> and the default <strong>antimatter</strong> theme to get you started.</p>

Whereas the `regex_replace`-filter applied [returns this error](http://olevik.net/staging/grav-1.1.0-beta.4/):

	Twig_Error_Runtime
	An exception has been thrown during the rendering of a template ("preg_replace(): Unknown modifier 'p'") in "default.html.twig" at line 4.

Per the [Usage-example](https://github.com/kesslernetworks/grav-plugin-twigpcre#usage) on the `twigpcre`-plugin, a virtual predecessor to this filter, the pattern should be set using tilde-characters rather than forward slashes: `client.website|preg_replace('~^https?://~')`, or in this case: `|regex_replace("~<p>(.*?)<\/p>~", '<p class="col-md-8 offset-md-2">$1</p>')`. Which does return the expected:

	<p class="col-md-8 offset-md-2">Congratulations! You have installed the <strong>Base Grav Package</strong> that provides a <strong>simple page</strong> and the default <strong>antimatter</strong> theme to get you started.</p>

The result is unexpected, as per the Regex101 example linked above which uses PCRE.

For reference, `system.yaml` is set as:

	absolute_urls: false

	home:
	  alias: '/home'

	pages:
	  theme: antimatter
	  markdown_extra: false
	  process:
		markdown: true
		twig: true

	cache:
	  enabled: false
	  check:
		method: file
	  driver: auto
	  prefix: 'g'

	twig:
	  cache: false
	  debug: true
	  auto_reload: true
	  autoescape: false

	assets:
	  css_pipeline: false
	  css_minify: true
	  css_rewrite: true
	  js_pipeline: false
	  js_minify: true

	errors:
	  display: true
	  log: true

	debugger:
	  enabled: true
	  twig: true
	  shutdown:
		close_connection: true

**Comment by Sommerregen** [comment]
Hi  @OleVik ,

I experienced the same issue in the past. As far as I have found out it is due to how Twig parses and processes params. I don't know actually, which one, but I think it was the backslash Twig strips out. That's why

```twig
{{ page.content|regex_replace("/<p>(.*?)<\/p>/", '<p class="col-md-8 offset-md-2">$1</p>') }}
```

doesn't work, whereas

```twig
{{ page.content|regex_replace("/<p>(.*?)<\\/p>/", '<p class="col-md-8 offset-md-2">$1</p>') }}
```

does work. Note the escaped backslash. You can write your own Twig function and test yourself, how Twig passes the arguments to your function. That's why `regex_replace("~<p>(.*?)<\/p>~", ...)` does work, because Twig strips out the backslash and the argument becomes `"~<p>(.*?)</p>~"`, which PCRE understands. Thus, you can even use `regex_replace("~<p>(.*?)</p>~", ...)`. In comparison with `regex_replace("/<p>(.*?)<\/p>~/", ...)`, the argument becomes `"/<p>(.*?)</p>~/"`, which is malformed for the PCRE compiler.

Thus, every time you use a backslash you have to escape it, too. However, in most of the cases you can avoid using backslashes, when sticking to the `~` boundary.

Hope it helps,
Sommerregen

**Comment by OleVik** [comment]
Indeed, the double-escaped forward slash (`\\/p`) does work. From a bit more reading, coffee in hand, the tilde key is seemingly one of several possible delimiters for the PCRE-syntax. The difference in how Twig handles params led to some very varied results on local testing yesterday, and it might be advantageous to make a note of the syntactic peculiarities alongside the `regex_replace`-filter's documentation.
