### ISSUE TITLE
[add-resource] New Plugin: ImgCaptions

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav#834]
Suggestion for adding a new plugin to the Grav Repository. Here are the project details: **[OleVik/grav-plugin-imgcaptions](https://github.com/OleVik/grav-plugin-imgcaptions)**

It wraps images in `<figure>` and captions in `<figcaption>` based on the `title`-attribute of the `img`-element. From this:

	<p><img title="Street view from the east" alt="Street view" src="street.jpg"></p>

To this:

	<figure><img title="Street view from the east" alt="Street view" src="street.jpg"><figcaption>Street view from the east</figcaption></figure>

Requires PHP's PCRE extension as it uses `preg_replace` on processed Markdown content.

**Comment by rhukster** [comment]
Thanks will get this added soon.

**Comment by rhukster** [comment]
has been added to GPM, should show up < 1 hr.
