### ISSUE TITLE
Unclear error message when rendering image

### ISSUE THREAD

**Issue by Mausy5043** [getgrav/grav#835]
Sometimes I get this error:
```
Twig_Error_Runtime thrown with message "An exception has been thrown during the rendering of a template ("getimagesize(): Read error!") in "modular.html.twig" at line 54."
```

The cause of the error (at least in my cases) is that an image has a null-size. This is because the (`gnuplot`) images on my website are dynamically created by a number of servers on the LAN and sometimes `gnuplot` errors out and doesn't produce a usable image. The problem is that the error message is not very specific and there are a lot of images being created. So, it's kind of hard to troubleshoot this, trying to find out which server/image is the culprit. 

Could you perhaps improve the error message? For example including the path/filename of the image that caused the error somewhere in the stacktrace would be great.

Thanks!

**Comment by flaviocopes** [comment]
Thanks for reporting, fixed
