### ISSUE TITLE
Smooth filter is not working

### ISSUE THREAD

**Issue by MBThaumatec** [getgrav/grav#847]
Hi,
I found an issue with smooth filter not working. I've tried from markdown and twig template and didn't manage it to work. 

I've GD installed
```
{ ["GD Version"]=> string(9) "2.1.1-dev" ["FreeType Support"]=> bool(true) ["FreeType Linkage"]=> string(13) "with freetype" ["T1Lib Support"]=> bool(false) ["GIF Read Support"]=> bool(true) ["GIF Create Support"]=> bool(true) ["JPEG Support"]=> bool(true) ["PNG Support"]=> bool(true) ["WBMP Support"]=> bool(true) ["XPM Support"]=> bool(true) ["XBM Support"]=> bool(true) ["JIS-mapped Japanese Font Support"]=> bool(false) }
```

PHP Version 5.5.9

Other filters like grayscale, colorize, edge are working fine.

**Comment by flaviocopes** [comment]
I have no issues with it, can you upload the image you used?

**Comment by MBThaumatec** [comment]
I was playing with it, and noticed that with cropZoom it is working. It turned out that the smooth is applied to full resolution picture, and I was not able to notice any effect when Image was posted on a page (downscaled). So smoothing is working. Sorry for trouble.
