### ISSUE TITLE
[add-resource] New Plugin: Image Collage

### ISSUE THREAD

**Issue by petrgrishin** [getgrav/grav#853]
Suggestion for adding a new plugin to the Grav Repository. Here are the project details: [grav-plugin-image-collage](https://github.com/petrgrishin/grav-plugin-image-collage)

![image](https://github.com/petrgrishin/grav-plugin-image-collage/raw/master/assets/example.png)
Usage
```php
{{ images_collage(page.media.images).html }}

{{ images_collage(page.media.images|slice(1, 5)).html }} //or slice

{{ images_collage(page.media.images, 3, 5, 900).html }} //or with params
//image_collage(images: ImageMedium[], column: int, borderSize: int, width: int): ImageMedium
```

**Comment by rhukster** [comment]
very nice, will get it added soon.

**Comment by rhukster** [comment]
Added
