### ISSUE TITLE
No support for xx-xx style locale codes (en-US, zh-TW etc.)

### ISSUE THREAD

**Issue by 01010000101001100** [getgrav/grav#854]
I discovered this issue when I was playing around with langswitcher plugin. I noticed that `xx-xx` style locales doesn't show up on front-end and after further investigation in this [topic](https://github.com/getgrav/grav-plugin-langswitcher/issues/6) @rhukster pointed me to this:

`Grav\Common\Languages\LanguageCodes::getNames()` only knows how to lookup `xx` style language codes. This would have to be improved to support `xx-xx` styles too.

https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Language/LanguageCodes.php

**Comment by 01010000101001100** [comment]
There is lot's of locales but the most common that are widely supported by systems and platforms out there are:

- English (American)       `en-US`
- English (British)	        `en-GB`
- English (Australian)	`en-AU`
- English (Canadian)	`en-CA`
- French (Canadian)	`fr-CA`
- Chinese (Simplified, PRC)      `zh-CN`
- Chinese (Simplified, Singapore) `zh-SG`
- Chinese (Traditional, Taiwan)  	 `zh-TW`
- Chinese (Traditional, Hong Kong S.A.R.) `zh-HK`
- Chinese (Traditional, Macao S.A.R.) `zh-MO`

**Comment by 01010000101001100** [comment]
Here are the most common locales, widely supported by systems and platforms out there:

Description | Locale code
------------ | -------------
English (American) | en-US
English (British) | en-GB
English (Australian) | en-AU
English (Canadian) | en-CA
French (Canadian) | fr-CA
Chinese (Simplified, PRC) | zh-CN
Chinese (Simplified, Singapore) | zh-SG
Chinese (Traditional, Taiwan) | zh-TW
Chinese (Traditional, Hong Kong S.A.R.) | zh-HK
Chinese (Traditional, Macao S.A.R.) | zh-MO

**Comment by rhukster** [comment]
I need to find a list of all ISO 639-1 (xx) and 639-2 (xxx) but with an appropriate **native language** name. 

Then I also need to cross correlate this with a list of locale-based names (en-GB, en-US, zh-CN, zh-TW, etc) but these need to have appropriate **native names** too.  

This is not easy to find!

Links to info I've found far:

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
https://www.loc.gov/standards/iso639-2/php/code_list.php
http://www.lingoes.net/en/translator/langcode.htm

So far i've been able to find resources to ISO 639-1 and 639-2, but nothing to locale-based names with native languages.

**Comment by rhukster** [comment]
Ok this is closest so far:

https://github.com/jlongster/php-product-details/blob/master/localeDetails.class.php

**Comment by rhukster** [comment]
and another:

https://chronoplexsoftware.com/myfamilytree/localisation/languagecodes.htm

**Comment by rhukster** [comment]
I've released an update for this plugin that causes the languages to be displayed with suffix in parens:

```
English (gb) English (us) English 
```

This is not the final solution.  A proper update to the array with more local languages is the ideal solution, but this will at least work for the time being.

**Comment by rhukster** [comment]
Fixed for next Grav release: https://github.com/getgrav/grav/commit/d7f286f601229bb0e485c8d1713b5b235f66f10c

**Comment by 01010000101001100** [comment]
@rhukster could you also add `zh-TW` & `zh-CN` for next release?

**Comment by rhukster** [comment]
Already there:

https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Language/LanguageCodes.php#L137-L138

**Comment by manuel-84** [comment]
Hi @rhukster , is it possible to add custom languages not defined into LanguageCodes.php without editing the core?
