### ISSUE TITLE
UX suggestion: Markdown editor with preview side-by-side (split-view)

### ISSUE THREAD

**Issue by 01010000101001100** [getgrav/grav#855]
As in the title - it will be great to have Markdown editor where you type together with preview available side-by-side in split-view, perhaps working in fullscreen mode, similar to one markdown editor for Mac [Mou](http://25.io/mou/). This will look less or more like this (excuse me using text, not proper icons, its just a quick mock-up:

![split-view](https://cloud.githubusercontent.com/assets/4720153/15631228/3fe20086-2590-11e6-98f8-73ddc416d960.png)

**Comment by rhukster** [comment]
I've already answered this in the admin plugin (where this should of been raised :)

https://github.com/getgrav/grav-plugin-admin/issues/533
