### ISSUE TITLE
how to get img url of page

### ISSUE THREAD

**Issue by alihaddadkar** [getgrav/grav#856]
Hi.
I've used this code on the index page. Now, I want display one image of gallery like thumbnail in wordPress.
How should I do it?
```
{% for post in taxonomy.findTaxonomy({'category':'ali'}) %}
                    <div class="pull-right col-md-3 col-sm-3 col-xs-12">
                        <div class="forms-item">
                            <a href="{{post.url}}">
                                <img class="img-responsive" src="{{ page.media[item.img].url }}">
                                <h5>{{ post.title }}</h5>
                            </a>
                        </div>
                    </div>
{% endfor %}
```

**Comment by rhukster** [comment]
If you mean have a thumbnail that then displays an image in a 'lightbox' you might want to look at the featherlight plugin: https://github.com/getgrav/grav-plugin-featherlight

Alternatively you just pick some other lightbox plugin that you want to use and output the respective HTML as the plugin dictates.  You can resize images on the fly like this:

```
{{ page.media[item.img]cropZoom(200,200).url }}
```

More information on various image manipulations including a wide variety of resize methods in the docs: https://learn.getgrav.org/content/media

**Comment by alihaddadkar** [comment]
my photo in the gallery folder. The above code is placed in default page but is not working.

<img width="490" alt="screen shot 2016-05-30 at 12 22 22 am" src="https://cloud.githubusercontent.com/assets/6142279/15635755/b9d95936-25fc-11e6-9fa2-70246971d265.png">

**Comment by rhukster** [comment]
Sorry misunderstood the question. 

I don't see where item.img is set. That's probably your problem. Check this out.  

https://learn.getgrav.org/cookbook/general-recipes#creating-a-simple-gallery

**Comment by alihaddadkar** [comment]
Unfortunately, the problem is still not resolved :(
How can I choose a cover photo for Posts and displays it on my site?
