### ISSUE TITLE
Documentation about adding Plugins to the repository is broken

### ISSUE THREAD

**Issue by MaZderMind** [getgrav/grav#860]
Both, the _Theme/Plugin Release Process section_ and the _open a Grav Issue on GitHub. You can also use this precompiled link._ link in the [_Add your resource to the repository_ Section](https://learn.getgrav.org/cli-console/grav-cli-gpm#add-your-resource-to-the-repository) of the _cli-console/grav-cli-gpm_ document point nowhere useful.

The first (https://learn.getgrav.org/cli-console/grav-development#theme/plugin-release-process) points to a 404 Page while the second (https://github.com/getgrav/grav/issues/new?title=%5Badd-resource%5D%2520New%2520Plugin%2FTheme&body=I%2520would%2520like%2520to%2520add%2520my%2520new%2520plugin%2Ftheme%2520to%2520the%2520Grav%2520Repository.%250AHere%2520are%2520the%2520project%2520details%3A%2520%2A%2Auser%2Frepository%2A%2A) seems to be double-escaped.

**Comment by rhukster** [comment]
You can edit it directly here: https://github.com/getgrav/grav-learn/blob/develop/pages/08.advanced/09.grav-development/docs.md
