### ISSUE TITLE
[add-resource] New Plugin "urlparamfilter"

### ISSUE THREAD

**Issue by MaZderMind** [getgrav/grav#862]
Hi

I wrote a plugin that adds twig-filters for accessing and manipulating URL-Parameters, Query-Strings and URL-Fragments in Templates:

https://github.com/MaZderMind/grav-plugin-urlparamfilter

The Readme and the Source-Code documents the possible usages.
Logterm I'd suggest to make the `Grav\Common\Uri`-Class initializable with partitial URls (which it currently isn't) and add `assembleUrl`-style functionality to it. Also the filter might be something one wants to have in the Core, but these are obviously your decisions.

I'd be happy to receive feedback and apply changes, if required.

**Comment by rhukster** [comment]
For this to show up in the GPM repo, it will need a tag+release.

If you are interested in seeing this in the Grav core, simply create a pull request and i'll gladly review it!

**Comment by MaZderMind** [comment]
I tagged a `v1.0` release. I'll see if I can assemble a PR for moving this into the core.

**Comment by rhukster** [comment]
Should show up in GPM soon.
