### ISSUE TITLE
Grav Displaying Strange Characters on Chrome for Android

### ISSUE THREAD

**Issue by Friscopolice** [getgrav/grav#863]
When accessing a Grav website using a Chrome browser on Android, the website displays random characters instead of website content.
![screenshot_2016-05-30-13-51-36](https://cloud.githubusercontent.com/assets/6260521/15659571/423993dc-2692-11e6-8a98-be7f0d06bed0.png)

**Comment by rhukster** [comment]
This is related to gzipping the site.   I spent this weekend sorting out a few of these problems, but those are only in the develop branch currently.

- What version of Grav are you running? 
- What kind of gzipping setup do you have?  `mod_deflate` in .htaccess? `zlib.output_compression` in php.ini, or simply `gzip` enabled in Grav system.yaml?

**Comment by Friscopolice** [comment]
Our Grav version is 1.0.10. I will look into the gzipping setup this afternoon.

**Comment by briankb** [comment]
that happened on an iOS devices, 4S I believe, as well. we thought it was just a temp glitch in the matrix.

**Comment by flaviocopes** [comment]
Can you post the site url?

**Comment by Friscopolice** [comment]
We use Nginx for our web server, so we do not have a .htaccess file. zlib.output_compression in .php.ini is off. Gzip is not enabled in system.yaml. Site URL is impartialitynet.gq

**Comment by flaviocopes** [comment]
Looks like a misconfiguration, because the browser dev tools tell me the page is gzipped.

**Comment by OleVik** [comment]
@rhukster, @flaviocopes there was 2-3 instances of the same issue today. Gibberish-characters stemming from Gzip-configurations with v1.1.13, apparently because the server has Gzip-enabled but it was not explicitly set in Grav's configuration with `cache: gzip: true`. Not quite sure why this occurs, as servers can generally deliver Gzipped content fine on their own.

See [Gitter-archives](https://gitter.im/getgrav/grav/archives/2017/01/18) from January 18th, starting with question by @kreativmind, for reference. Note that this occurred in any browser, not Android Chrome.

**Comment by kreativmind** [comment]
Just to add to this information, I had 1.1.12 running for a while successfully. Yesterday, when the admin notified of 1.1.13 update, I updated Grav and then my site became as such. Maybe we should have gzip set to true in the config file as default as a backup precaution in all future releases of Grav updates. is this a possible option?

**Comment by mahagr** [comment]
Its already fixed in Grav 1.1.14.

**Comment by OleVik** [comment]
@mahagr Great, just wanted to add in details for what was a bit of a rush-fix for some people. `cache: allow_webserver_gzip` looks like a good solution, though like several others I could not successfully replicate the issue.

I think this can be closed now, as there are multiple solutions outlined and the issue clearly delineated as a conflict between server-config and Grav-config, which needs resolution on both ends (if you Gzip through server, don't also do it with Grav).

**Comment by Eggeriley** [comment]
I am running the latest version of Grav 1.2.3 I am using the helium theme with Gantry 5. I am getting weird characters only on IOS devices.. Gzip compression is not aloud. any help?

**Comment by Eggeriley** [comment]
check out this url on ios kegge.accessipd.com

**Comment by OleVik** [comment]
@Eggeriley Where is GZip disabled, through Grav or the server?

**Comment by flaviocopes** [comment]
I cannot replicate the problem on any of my iOS devices

**Comment by flaviocopes** [comment]
Ok looks like solved already https://github.com/getgrav/grav/issues/1443
