### ISSUE TITLE
Allow `memcache` and `redis` to be automatically selected as cache method when present

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav#867]
1. Although somewhat implemented, the auto select logic of the cache method doesn't select **Memcache** or **Redis** if present (see https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Cache.php#L139-L148). Obviously, some `extension_loaded(...)` checks are missing.

2. Further, both **Memcache** or **Redis** can only be configured manually (https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Cache.php#L172-187), but not via **Admin plugin**. I actually don't know, whether this issue should be addressed here; if required I'll open an issue on the Admin plugin tracker instead.

3.  **APCu** can not be selected as a cache method option.

**Comment by rhukster** [comment]
it's the very need of these two cache providers to require options to be configured, which is why they are not included in the auto selection process.  With invalid settings, this would just cause your site to fail, and you wouldn't really know why.  

Better to manually change these settings, and then set the cache to use this provider explicitly.

**Comment by Sommerregen** [comment]
@rhukster Ok, this addresses point 1.)

My point 2. addresses the configuration options for these two cache providers. In the admin panel they can not be adjusted and not even be selected manually. What I mean is, there are no special cache specific options for both two cache providers:

![cache_options](https://cloud.githubusercontent.com/assets/9073307/15702461/65382b7e-27e0-11e6-94e1-f8ce0a61a34e.png)

From the cache driver options there is no possibility to set Redis (my point 2) or APCu (my point 3) manually:

![cache_driver](https://cloud.githubusercontent.com/assets/9073307/15702463/6822b692-27e0-11e6-9050-bc03c9f143e8.png)

**Comment by flaviocopes** [comment]
PR #887 addresses this issue. Adds Redis (and memcached) to the list, allows to configure them.

![screen shot 2016-06-09 at 12 34 18](https://cloud.githubusercontent.com/assets/11783388/15926869/8415a9cc-2e3e-11e6-86fb-41bbbee8fc65.png)

**Comment by Sommerregen** [comment]
Thanks! :-) Was about to implement it by myself

**Comment by flaviocopes** [comment]
Give it a try with memcache(d) if you want you use them, will test too

**Comment by Sommerregen** [comment]
I have Grav running with Redis and one with Memcached under PHP7. It's working like a charm :-)

**Comment by flaviocopes** [comment]
👍

**Comment by flaviocopes** [comment]
merged
