### ISSUE TITLE
With system.absolute_urls:false {{ base_url }} in a subpage returns the current url 

### ISSUE THREAD

**Issue by ardkevin84** [getgrav/grav#868]
Unless is set `system.absolute_urls: true`, calling `{{ base_url }}` in twig returns the current page url. 
I can workaround by using `{{ base_url_absolute }}`, as illustrated here: 

    {# returns proper home page link #}
    <a class="navbar-brand" href="{{ base_url_absolute }}"></a>
    {# returns current page #}
    <a class="navbar-brand" href="{{ base_url }}"></a>                

Also, as mentioned above, setting `system.absolute_urls: true` will return the proper uri.

**Comment by rhukster** [comment]
Flavio can you take a look at this and perhaps investigate the idea of providing an _optional_` base_url` system  override?

**Comment by ardkevin84** [comment]
would it be counterdesign for relative url configs to fall back to phps internals for this? 

eg:
- parse_url() http://php.net/manual/en/function.parse-url.php
- $_SERVER['HTTP_HOST'] http://php.net/manual/en/reserved.variables.server.php

**Comment by ardkevin84** [comment]
I started to prepare a PR, but the fix is so small that it doesn't really warrant a full git flow setup (something I should do one day, but not tonight).... So, here's a patch, if you're interested: 

in `system/src/Grav/Common/Twig/Twig.php` at line 159 (approx), `$this->twig_vars` is being assigned. 

beforehand, this logic will account for `base_url` (I tested on cli, but not in live browser) 

    // if $this->grav['base_url'] fails a (maybe) regex test
    // assigned for cli testing
    $this->grav['base_url'] = "http://foo.com/remodels/baths";
    $parsed = parse_url($this->grav['base_url']);
    echo var_export($parsed);
    // the parsed array can be recompiled, ignoring its 'path' element
    $compiled = $parsed['scheme'] . "://" . $parsed['host'];
    $this->twig_vars['base_url'] = $compiled;

**Comment by flaviocopes** [comment]
Looking into it

**Comment by flaviocopes** [comment]
`{{ base_url }}` should return the base url, not the current page url, same as `{{ base_url_relative }}`. This is what I got from my tests, on both Grav 1.0 or 1.1.

What environment are you on? Which web server?

**Comment by ardkevin84** [comment]
It's a vagrant box spun from https://github.com/ardkevin84/vagrant-lamp (ubuntu 14.04) Same behavior on its VPS, though. I'm concerned about placing a phpinfo there, for the obvious reasons, so the output from one on my vagrant is attached here. 

also, I fired up xdebug and place a breakpoint at `local.dev/system/src/Grav/Common/Twig/Twig.php:166`; this is immediately after $this->twig_vars is set. I captured var_export of twig_vars at that point. (see attached var_export.php). 

[phpinfo.html.txt](https://github.com/getgrav/grav/files/294225/phpinfo.html.txt)
[var_export.php.txt](https://github.com/getgrav/grav/files/294224/var_export.php.txt)

**Comment by flaviocopes** [comment]
I just saw another issue mentioning base_url points to the current page url. 
It should not, and I'm not seeing this in my test installs, but I'm trying to replicate.

**Comment by ardkevin84** [comment]
Sorry, I was out of town for a few days or I would have chimed in sooner. Since I am running on a vagrant box that *happens* to throw the error, would replication be easier if you pulled the repos for my vagrant and site code? (the box pre-configures XDebug as well, so it's well-suited for test\debug)

**Comment by flaviocopes** [comment]
I have some troubles running vagrant on my machine. 

Since you know your stuff, you can check what's happening here: https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Uri.php#L338

`Uri::rootUrl()` should return the root url, not the page relative path.

**Comment by ardkevin84** [comment]
I have it resolved in my (problematic) install. It's locked in a private repo for my project, though. I don't know of a way to submit a PR with that kind of repo relationship, so here's a patchfile. 

[issue868.patch.txt](https://github.com/getgrav/grav/files/300612/issue868.patch.txt)

It's a dead-simple fix: 
in `public function rootUrl($include_host = false)`: 

original: 

	} else {
	$root = str_replace($this->base, '', $this->root);

In the trouble environments, `$this->base == $this->root`, so str_replace returns `''`

patched: 

	}else {
	$root = $this->root==$this->base ? $this->base : str_replace($this->base, '', $this->root);

The `$root` assignment is handled by a ternary that addresses edge cases without affecting normal operation

**Comment by flaviocopes** [comment]
Ok so correct me if I'm wrong: `base_url` is actually empty, so your links point to the current page as your code is building a `<a href="">` instead of `<a href="/">`, is this the problem?

Most theme/plugins links use this style 

`<h3><a href="{{ base_url == '' ? '/' : base_url }}">{{ config.site.title }}</a></h3>`

Does the above snippet work in your case, without your edit?

**Comment by ardkevin84** [comment]
Problem solved. It's a template issue, not grav. Thanks!

**Comment by ardkevin84** [comment]
closed because we found that the issue can be easily handled at the template layer without adding to grav core. yes, it could be handled internally by grav, but that creates overhead that would affect the lightness of the platform as a whole, which is counter to grav.

**Comment by kehugter** [comment]
@flaviocopes 

> Most theme/plugins links use this style
> `<h3><a href="{{ base_url == '' ? '/' : base_url }}">{{ config.site.title }}</a></h3>`

But they shouldn't, right? As you said

> I just saw another issue mentioning base_url points to the current page url.
> It should not

`base_url` should be reliable and therefore never empty.

(I just came across this issue myself)
