### ISSUE TITLE
markdown extra lang feature implementation

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav#869]
This is a proposition of enhancement

in .md file,
```
# TITLE 1 # {lang=ja}
```
would give 
````
<h1 lang="ja">TITLE 1</h1>
````

**Comment by rhukster** [comment]
I don't really want to start adding arbitrary enhancements to the markdown support in the core.  If you wish to create a plugin to do this, you can do so.  You can look at markdown-notices plugin to give you an idea of how to accomplish this.
