### ISSUE TITLE
Feature request. Add ability to prioritize "assets.addInlineJs"

### ISSUE THREAD

**Issue by lid3rs** [getgrav/grav#870]
Something like ->  {% do assets.addInlineJs('alert(\'This is inline!\'),100') %}

Not sure if this is already done, but if yes, then it is not working.

**Comment by flaviocopes** [comment]
Should working, the order is applied within inline js, not mixed with the js file includes.

**Comment by flaviocopes** [comment]
You need to add a second parameter, like ` {% do assets.addInlineJs("alert('This is inline!')", 100) %}`

**Comment by rhukster** [comment]
Can we close this @flaviocopes ?

**Comment by flaviocopes** [comment]
I believe so. @lid3rs confirm it's working with the syntax I wrote above?
