### ISSUE TITLE
pagemediaselect Issue

### ISSUE THREAD

**Issue by ChrisRiddell** [getgrav/grav#872]
Hello,

When you delete an image from a page that is using said image in a pagemediaselect field it delete's all the inputed data.

Grav 1.1RC1

eg:

edit \user\themes\antimatter\blueprints\modular\features.yml adding the following to the last fields:

```markdown
.img:
    type: pagemediaselect
    label: file
```

edit user\themes\antimatter\templates\modular\features.html.twig adding the following under feature.text if statement

```html
{% if feature.img %}
  <img src="{{ page.media[feature.img].url }}">
{% endif %}
```

clear caches then in the admin edit the features page and add an image click Features tab and for the first item in the file drop down select that image you just uploaded then save, go back to the content tab and delete the image, the image is still on the file system but all the Features items will be gone.

**Comment by rhukster** [comment]
@ChrisRiddell sounds like an issue  for admin plugin? https://github.com/getgrav/grav-plugin-admin/issues

**Comment by ChrisRiddell** [comment]
Can this issue be moved to that repo or should i repost it there?

**Comment by rhukster** [comment]
It needs to be recreated over there should be able to "edit" your original post and copy the markdown into a new issue there.

**Comment by ChrisRiddell** [comment]
Done

https://github.com/getgrav/grav-plugin-admin/issues/636
