### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by Edelan** [getgrav/grav#873]
Hello,

I would like to add my new theme to the Grav Repository.
Here are the project details: [theme-gravi-k](https://github.com/Edelan/grav-theme-gravi-k)
I will add the blog template later.
Thank you.
Regards,

**Comment by rhukster** [comment]
Looks really nice!  Wil get this added soon.

**Comment by rhukster** [comment]
Should be in next GPM update.

**Comment by Edelan** [comment]
Thank you very much for your reply.
