### ISSUE TITLE
[add-resource] New Plugin - Diagrams

### ISSUE THREAD

**Issue by Seao** [getgrav/grav#875]
Hello,

I would add my new plugin to the Grav Repository. You will find the plugin on the following page : https://github.com/Seao/grav-plugin-diagrams

I will regularly improve the plugin by adding support of new diagrams. Don't hesitate to ask me if you have any questions :)

Thank you.
Regards,

**Comment by rhukster** [comment]
Ok that looks like it will be super useful!

**Comment by rhukster** [comment]
Should be in next GPM update.
