### ISSUE TITLE
Unknown: open(/var/lib/php/session/sess_jc330rvt9kuon5uakrl8v239u1, O_RDWR

### ISSUE THREAD

**Issue by PwnArt1st** [getgrav/grav#878]
Whoops\Exception\ErrorException thrown with message "Unknown: open(/var/lib/php/session/sess_jc330rvt9kuon5uakrl8v239u1, O_RDWR) failed: No such file or directory (2)"

Stacktrace:
#1 Whoops\Exception\ErrorException in Unknown:0
#0 Whoops\Run:handleError in [internal]:0

**Comment by flaviocopes** [comment]
I replied in the chat. Looks like PHP cannot write to the session folder (/var/lib/php/session).

If you setup the server, check that that directory exists, and that it's writeable.

**Comment by PwnArt1st** [comment]
turns out my php version was like .01 off the required, updating to 5.6 fixed it, can be closed

**Comment by rhukster** [comment]
Cool!
