### ISSUE TITLE
Server path fragment with value zero "0" breaks rendering

### ISSUE THREAD

**Issue by haralduna** [getgrav/grav#883]
`Whoops \ Exception \ ErrorException (EWARNING)
fileexists(): open_basedir restriction in effect. File(/customers/f/6/haraluna.no/httpd.www/user/pages/images/web-hoved- bilde.png) is not within the allowed path(s): (/customers/f/6/0/haraluna.no/httpd.www:/customers/f/6/0/haraluna.no/h ttpd.private:/customers/f/6/0/haraluna.no/tmp:/customers`/haraluna.no/haraluna.no:/var/www/diagnostics:/usr/share/php)`
The ‘0’ has been removed from the path so the path is not valid. Seems to be a problem with the URL conversion.

The cause has been identified to the line:
https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Utils.php#L333
`if (($segment == '.') || empty($segment)) {`
If $segment equals "0" the segment is skipped.
The solution may be to change the above line to:
`if (($segment == '.') || strlen($segment) == 0) {`

Thanks to @Sommerregen for pointing out a possible solution.
I have tried the fix both locally and on a production server and it seems to work.

**Comment by flaviocopes** [comment]
Fixed by https://github.com/getgrav/grav/pull/882 thanks to @Sommerregen  👍
