### ISSUE TITLE
[add-resource] New Theme

### ISSUE THREAD

**Issue by tnware** [getgrav/grav#884]
I have been writing a theme for Grav based on  the [Cascade CSS Framework ](http://www.cascade-framework.com/).

I have just released [v0.1.1](https://github.com/tnware/grav-theme-cascade/releases/tag/0.1.1) today as it is stable for use, but lacking many page styles still such as a blog page. I hope to have this added to the repository for themes.

GitHub - [Cascade Theme](https://github.com/tnware/grav-theme-cascade)

[edit 6/8 v0.1.1 links]

**Comment by tnware** [comment]
I'm making some minor adjustments and I'll release 0.1.1 soon with blog support, adjusted nav, footer, and a few other tweaks.

Thanks.

**Comment by rhukster** [comment]
Added thanks.
