### ISSUE TITLE
wrong path on glyphincons font file when CSS pipeline is active

### ISSUE THREAD

**Issue by beijersb** [getgrav/grav#888]
I'am using Bootstrap for my theme and when i turn on CSS pipeline the paths for the glyphicons font files are referring to a non existing location.
`http://www.nepalichildren.com/fonts/glyphicons-halflings-regular.woff2`
`http://www.nepalichildren.com/fonts/glyphicons-halflings-regular.woff`
`http://www.nepalichildren.com/fonts/glyphicons-halflings-regular.ttf`
BTW in my theme i'am not loading these assets at all, they come from bootstrap which is a asset i do load.

I am not sure if this is an actual issue with Grav, or i should actually create the location on my server and drop in the font files.
My bootstrap file are located on MaxCDN: `http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css`

There seems to be some overlap with [this forum post](https://getgrav.org/forum#!/theme-development:css-pipeline-breaks-image-p) but i can't figure it out (yet)

Does anybody have an idea?

Grtx,
Ben

**Comment by flaviocopes** [comment]
This should be fixed in Grav 1.1 rc . Are you using that, or Grav 1.0.10?

**Comment by beijersb** [comment]
I'am still running 1.0.10, so i will wait for the release of 1.1 and then try again!

Thnx!

**Comment by rhukster** [comment]
I'm 'pretty sure' this is already fixed in 1.1 as @flaviocopes says, so marking as fixed in repo.  Please reopen if you find it's not so in 1.1
