### ISSUE TITLE
Feature Present? Twig Template with Custom JSON

### ISSUE THREAD

**Issue by barryanders** [getgrav/grav#891]
Is there a built-in way to create twig templates with custom JSON data?

Say I have JSON `{ "key": "value" }`. There has to be a way to import it. My thinking is to include it with PHP, but maybe that's wrong. Then I should be able to write something like `<div>{{key}}</div>` to return `value` within the div. I know this can be done, I just wasn't sure if there was a so called intended way to do this with Grav or if this is not part of it.

I know I can generate my files and then load it with [this plugin](https://github.com/getgrav/grav-plugin-file-content). I was just trying to see if there was a more direct way within Grav.

**Comment by MaZderMind** [comment]
If my Data would be per-Page or per-Page-Tree I'd add it to the Frontmatter of the Page or the Head of the Pagetree, where it's applicable to.

I'd then use `page.headers` or `page.parent.headers` or a combination of `page.find(…).headers` to access it.


If the data is system-wide, you might put it into `user/config/site.yaml` and access it via `site.my_variable`.


You can also set theme-wide variables in `user/config/themes/<theme>.yaml`.

**Comment by rhukster** [comment]
yes the 'built-in' way is to use YAML frontmatter to set your data, then simply `json_encode` it in Twig when you send it back via your `.json.twig` template.  However, if your json needs to be maintained in json itself, the you would need a plugin to read it and set the json data as a Twig variable.

**Comment by barryanders** [comment]
Awesome, thanks for taking the time to help answer my question. I'll look into it some more and if I decide to go the plugin route, then I may create one which seems beneficial to other Grav users, however, from just reading, I don't see why I can't use the Frontmatter. Thanks again.

**Comment by flaviocopes** [comment]
@barryanders you can put the json in the frontmatter directly, like

```
---
title: 'Test'
json: {"glossary":{"title":"example glossary","GlossDiv":{"title":"S","GlossList":{"GlossEntry":{"ID":"SGML","SortAs":"SGML","GlossTerm":"Standard Generalized Markup Language","Acronym":"SGML","Abbrev":"ISO 8879:1986","GlossDef":{"para":"A meta-markup language, used to create markup languages such as DocBook.","GlossSeeAlso":["GML","XML"]},"GlossSee":"markup"}}}}}
---

# test
```

and then create a yourpagetype.json.twig in the theme, and just have `{{page.header.json|json_encode}}` into it.

This will print the field content as JSON.

You need to `|json_encode` that field because JSON is interpreted by YAML, which means you can also write a YAML data structure in the header, and print it using `|json_encode` to build a JSON output.


---

Another way is to have the JSON in the page content directly. In that case, simply output `{{ page.content }}` in the json.twig file.

**Comment by barryanders** [comment]
I finally got around to actually using this for a work project and I didn't realize that you could process twig directly in the page. Seems pretty obvious now, but wow, that's such an incredible idea. Very useful. I can also see how it may be beneficial to have a plugin that reads json files separately rather than including them in frontmatter. I say this, because if I were to make, say, a mobile app that needs to access that same json data, I'm not sure how it would be accessible if it's tucked away in the frontmatter of a Grav page. I'm going to guess there's a way but I haven't looked too much into it yet.

**Comment by rhukster** [comment]
You can actually store data a number of ways.. you can put it in the frontmatter of a page, then 'find' that page, and then the header variable containing the data from wherever you want.

Or you can simply have a json file in say your `user/data` folder and use the `onTwigPageVariables` hook via your theme class or a simple plugin, to load that data (or load + cache) and store as a Twig variable for use by any twig logic in a page or template.

**Comment by barryanders** [comment]
Sorry to keep this alive, but I was just curious if anyone could help me with this. Trying to implement the general idea that rhukster presented, but I'm not sure how to put the PHP together. This is what I've come up with, which I put in my child theme php file inside `class myChildTheme extends Bootstrap`

```
  public function onTwigPageVariables() {
    $twig = $this->grav['twig'];
    $data = file_get_contents('/user/data/'.$this->grav['title'].'.json');
    $twig->twig_vars['data'] = json_decode($data);
  }
```

In theory, this should grab the contents of a json file with a name of the Grav page title and then pass it in the form of a twig variable, `data`. So I should be able to do `{% for person in data %}` and then do like `{{person.name}}`, `{{person.emailAddress}}`, right? I hope I'm close and not totally off base.

**Comment by barryanders** [comment]
Ok, problem solved. My code was fine, but my link to the file was not. Swapped for an absolute url and all is well.

**Comment by barryanders** [comment]
Still one issue though. I was also wrong on how I was calling the grav page title. `$this->grav['title']` says the title doesn't exist. `0 - Identifier "title" is not defined.` I know this is simple but anyone's input would save me the time of trying to figure it out. I've looked in the docs but just having trouble. Maybe I'm out of scope or something.

**Comment by barryanders** [comment]
Bingo: `$event['page']->title()`

**Comment by barryanders** [comment]
I do have one issue here, and maybe this can't be resolved, since Grav wasn't create with this use case in mind. Using the method I showed above, it loads the page the first time, but post cache, it loads a blank page. I'm assuming this is because onTwigPageVariables doesn't fire once a page is cached. And since nothing actually exists in the grav page (not even frontmatter), nothing is actually cached other than a blank page.

Confirmed, because when I shut off cache on the page, then it reloads every time. Any idea if this can be made to work so that caching is possible too? My first thought was to try and pass the twig variable in a different function but it seems like this may be the only spot in the scope to actually pull this off. Yea, nay? Thanks for your help.

**Comment by barryanders** [comment]
@rhukster: here's what you said in action.

```
{
  public static function getSubscribedEvents() {
    return [
        'onTwigPageVariables' => ['onTwigPageVariables', 0],
    ];
  }
  public function onTwigPageVariables($event) {
    $json = $event['page']->header()->json;
    foreach ($json as $value) {
      $fileName = str_replace(' ', '-', strtolower($value));
      $data = file_get_contents('/user/data/' . $fileName . '.json');
      $this->grav['twig']->twig_vars[${value}] = json_decode($data);
    }
  }
}
```

This allows you to grab multiple JSON files in the same Grav page. The twig variable is defined by the value in frontmatter which also calls the name of the file. So for example...

```
title: my page
json:
  - jsonfile
```
Frontmatter

```
{% for person in jsonfile %}
  {{person.name}}
  {{person.emailAddress}}
{% endfor %}
```
Twig template
