### ISSUE TITLE
Feature Request: Add more options to `bin/gpm update` command

### ISSUE THREAD

**Issue by Sommerregen** [getgrav/grav#892]
Currently, `bin/gpm update` updates all packages, which have changed during the last update. Updating certain package classes like "only update all plugins" or "only update all themes" is not possible. What I'd like to see is to have options `--plugins` and `--themes` for the update command to do something like this

```
bin/gpm update --plugins
bin/gpm update --themes
```

A `--quiet` command may also be useful, which installs the plugin/theme without the need of any user interaction.

**Comment by rhukster** [comment]
Good options 👍 

PR would be lovely! :)
