### ISSUE TITLE
fixOrientation fails with .png's

### ISSUE THREAD

**Issue by MaZderMind** [getgrav/grav#893]
When processing a PNG (see example attached) through `.fixOrientation()` it get's replaced with a `fallback.jpg`, also attached. Instead, `fixOrientation` should return the Image unchanged.

**Example-File:**
![a-big](https://cloud.githubusercontent.com/assets/142237/15991891/e82a6866-30bf-11e6-9e6d-9dba1e17929f.png)

**fallback.jpg:**
![fallback](https://cloud.githubusercontent.com/assets/142237/15991892/f429c166-30bf-11e6-86c6-bc9e2c30832d.jpg)

**Comment by rhukster** [comment]
Probably relates to this **upstream issue** - https://github.com/getgrav/grav/pull/555

In the meantime you can either fix the orientation 'offline' or you can use the manual rotate command: https://learn.getgrav.org/content/media#rotateangle

**Comment by MaZderMind** [comment]
Just fyi: it seems this is now fixed upstream.

**Comment by flaviocopes** [comment]
@MaZderMind thanks for commenting on that! Seems to have triggered the merge 👯
