### ISSUE TITLE
404 error for uploaded file to subpage..

### ISSUE THREAD

**Issue by danielpetre** [getgrav/grav#895]
Hello, so using grav 1.1rc1 and having a SITE.TLD/page1/subpage1 and uploading a file in subpage1 admin editor and inserting it to the page makes the actual clicking on it throw a 404 error..

The nginx webserver is set according to the official grav specifications and everything else works fine. Both page1 and subpage1 have folder numeric prefix enabled. The 404 error page looks like SITE.TLD/page1/subpage1/file.zip !

**Comment by rhukster** [comment]
What do you mean by 'actual clicking on it..' ?

**Comment by danielpetre** [comment]
Here is the page where i uploaded the file and inserted it via the admin plugin editor:

https://tmp.ro/firmware/openwrt

And clicking on the linked file in the browser takes me here:

https://tmp.ro/firmware/openwrt/superwrt-dir505.zip

P.S. not even a open in new tab option..?

**Comment by flaviocopes** [comment]
Is "zip" listed in your `user/config/media.yaml`?

**Comment by danielpetre** [comment]
zip is listed in my system/config/media.yaml 

zip:
  type: file
  thumb: media/thumb-zip.png
  mime: application/zip

isnt this enough?

**Comment by flaviocopes** [comment]
It is, in fact it works in my tests. You can post me your user/ folder via Gitter PM, I'll check if there's some other setting getting in the way.

**Comment by flaviocopes** [comment]
Tried tehe `user/` folder, works fine to me. Most probably a web server configuration issue?

**Comment by danielpetre** [comment]
Then probably the grav team is recommending wrong nginx settings.

**Comment by flaviocopes** [comment]
We never had reports of this issue. Did you try the nginx settings I use, that I posted you in Gitter?

**Comment by danielpetre** [comment]
Weird stuff: uploading images and linking them into pages works as intended but not for zips.. Probably something on my end.

**Comment by rhukster** [comment]
Closing to due to inactivity
