### ISSUE TITLE
home page is defined, but won't load, redirects to 404 page with index.php in URL

### ISSUE THREAD

**Issue by milholen** [getgrav/grav#901]
When I navigate to my domain with a brand new Grav installation, let's call it http://example.com (with or without the trailing slash), the URL changes to http://example.com/index.php and I see the Grav-style "Page not found" error.

I've been through the troubleshooting documentation at https://learn.getgrav.org/troubleshooting/page-not-found and didn't see anything that would help. I also see some other issues, for example #818 but none of those threads seem to apply.

I've tried deleting Home and recreating it, and setting new pages other than "Home" to be the "Home page" in the Grav configuration (via the admin panel). It doesn't seem to matter what page I use, typing in the domain by itself always defaults to the index.php and the 404 page.

I can enter specific URLs including /home and the pages will load as expected. They just won't show up as the default page when the site is accessed, the index.php URL is always loaded instead. And FWIW that index.php is there in the right place, I haven't changed its location or renamed it.

**Comment by rhukster** [comment]
Sounds like something related to your web server setup.  If it's apache, then it's probably an `.htaccess` file rewrite rule that is causing the redirect to index.php.  it's not something that Grav itself is capable of.

**Comment by milholen** [comment]
Thanks, I am using the stock .htaccess file from the latest version of Grav with no edits, so there aren't any additional rewrite rules.

**Comment by rhukster** [comment]
Definitely something is going on. Maybe something at the hosting level?  Perhaps you can give a full set of details of how you are 'serving' Grav? PHP version, webserver version, configuration etc.  Also if you attach your grav folder as a zip i can double check on my local.

**Comment by milholen** [comment]
@rhukster this was indeed a server config issue on Site5, it's been resolved and Grav seems to work OK now. Thanks for the quick responses nonetheless.
