### ISSUE TITLE
Assets accessed via routes are not cached by browser.

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#904]
Hi, recently I've discovered that assets used in pages (js, css, image files) loaded via routes aren't cached by browser and reloaded each time.
Testing done on the latest commit f8964ab of `develop`.
Test image put into the `user/pages/01.home` folder and two lines added into the `01.home/default.md` file:
```html
<p><img src="user/pages/01.home/test_image.png" alt="Image test 1 (path)"></p>
<p><img src="home/test_image.png" alt="Image test 2 (route)"></p>
```
the firt line can be changed to:
```markdown
![Image test (markdown)](test_image.png)
```
as they are acting just the same.
Next I have the following results:
The same image (or script, or stylesheet) loaded via path is cached by browser, but loaded via route is not cached.
![img_20160615_152209](https://cloud.githubusercontent.com/assets/12494082/16079664/714df14a-330d-11e6-88d9-31f169360ced.png)
Also they have different headers.
![img_20160615_152242](https://cloud.githubusercontent.com/assets/12494082/16079703/9a305f62-330d-11e6-9219-3b344c72334f.png)
![img_20160615_152310](https://cloud.githubusercontent.com/assets/12494082/16079717/ad15ff74-330d-11e6-8c41-7ea67a469feb.png)

Is there a way to leverage browser caching for assets loaded via routes?

**Comment by flaviocopes** [comment]
Replicated. Trying to see where this problem comes from

**Comment by flaviocopes** [comment]
Posted PR https://github.com/getgrav/grav/issues/905 to solve this, when the system cache is enabled. Can you try it?

**Comment by maxlysenko** [comment]
I've tested PR #905 and generally browser caching is working now for images accessed via routes.
But the problem is that the same issue occurs not only for images but for any assets (scripts, stylesheets).
With PR #905 I am facing the following things for assets accessed via routes:
- in my .httaccess i have the following lines:
```
# Begin - EXPIRES CACHING
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType application/javascript "access 1 month"
    ExpiresByType application/pdf "access 1 month"
    ExpiresByType application/x-javascript "access 1 month"
    ExpiresByType application/x-shockwave-flash "access 1 month"
    ExpiresByType image/gif "access 1 year"
    ExpiresByType image/jpeg "access 1 year"
    ExpiresByType image/jpg "access 1 year"
    ExpiresByType image/png "access 1 year"
    ExpiresByType image/svg+xml "access 1 year"
    ExpiresByType image/x-icon "access 1 year"
    ExpiresByType text/css "access 1 month"
    ExpiresByType text/javascript "access 1 month"
    ExpiresDefault "access 7 days"
</IfModule>
# End - EXPIRES CACHING
```
but for assets loaded via routes it's not taken into account, and `Cache-control: max-age` header always has the value of `604800` (from config)
- `Last-Modified` header has the `+0000` time zone instead of `GMT`
- svg, css and js files have `application/octet-stream` in `Content-Type` header so svg images are not rendered on page

**Comment by flaviocopes** [comment]
Yes the htaccess rules are not applied because the media is accessed and generated through Grav, not by the web server directly. I choose to use the cache value from the config for page images too.

Svg - checking now. As for scripts or stylesheets, you access them through a page route?

**Comment by maxlysenko** [comment]
I've sorted out the case with the `Content-Type: application/octet-stream` header, this was because of the old `media.yaml` config file without the `types:` key.

Yes, on some pages I am using some scripts and/or stylesheets through a page routes.
For example like this:
```twig
{% do assets.addCss(page.find('/features/vendor').route ~ '/codemirror/codemirror.css', 70) %}
{% do assets.addCss(page.find('/features/vendor').route ~ '/codemirror/show-hint.css', 70) %}
...
{% do assets.addJs(page.find('/features/vendor').route ~ '/holder.js', {'priority':90}) %}
{% do assets.addJs(page.find('/features/vendor').route ~ '/codemirror/codemirror.js', {'priority':70}) %}
```

**Comment by flaviocopes** [comment]
Now also svg work for you?

I didn't consider the option of loading css/js from a page route. Works correctly now too?

**Comment by maxlysenko** [comment]
Yes, except for two mentioned minor points (not applied `.htaccess` rules and `+0000` time zone in the `Last-Modified` header) svg, css and js files are loading correctly now, at least for my use cases.

**Comment by flaviocopes** [comment]
You're right. Synced a fix for GMT.

.htaccess rules _should_ be applied as we set the Content-Type accordingly.

**Comment by rhukster** [comment]
Should be fixed in repo with flavio's fixes.
