### ISSUE TITLE
remove /blog/blog in url

### ISSUE THREAD

**Issue by marioloncarek** [getgrav/grav#909]
Hello, first I want to say thanks for creating Grav, this is the best flat file CMS i have ever used. 

Im using Grav as a blog on my static web site and its installed in `marioloncarek.com/blog` folder. Everything is great but when you click on any post my url looks like this:
`http://marioloncarek.com/blog/blog/POST_URL`
So there is /blog/blog in my URL. I cant find anything in my dashboard for this problem, and i want it to look like 
`http://marioloncarek.com/blog/POST_URL`

Thanks in advance!

**Comment by rhukster** [comment]
It's not configurable in the admin, but you can configure it manually in your `user/config/system.yaml`:

```
home:
  hide_in_urls: true
```

This should do the trick for you..

**Comment by flaviocopes** [comment]
Should be configurable in Admin too, by enabling "**Hide home route in URLs**"  in the system configuration.

**Comment by itxdevs** [comment]
This works like charm for the URL in a browser but in the sitemap there is still /blog/
Any way to do the something similar for sitemap.xml?

**Comment by flaviocopes** [comment]
This is a sitemap issue. There is a PR to fix this, https://github.com/getgrav/grav-plugin-sitemap/pull/28, please test it and comment on the PR.
