### ISSUE TITLE
[add-resource] New Plugin

### ISSUE THREAD

**Issue by NeonTigerWeb** [getgrav/grav#911]
I would like to add my new plugin to the Grav Repository.
Here are the project details:

https://github.com/NeonTigerWeb/onWebChat/releases/tag/1.0

**Comment by NeonTigerWeb** [comment]
permission has been sought already from onWebChat, and they will happily put the GRAV logo on the homepage of their website with a link to the plugins page of www.getgrav.org once it is available (assuming it passes)

**Comment by rhukster** [comment]
Added!
