### ISSUE TITLE
/admin is a 404

### ISSUE THREAD

**Issue by endquote** [getgrav/grav#915]
I'm trying to try out Grav under the Apache server on OS X, managed by Server.app.

If I download the version without admin, I can get to the home page ok.

If I download the version with admin, I get redirected to /admin, but it's a 404. (However nothing about it shows up in the Apache error log.)

I see the same behavior if I download without admin and use gpm to install it, and if I use either the RC or stable versions.

I'm guessing this is some issue with the default Apache config on OS X?

**Comment by endquote** [comment]
PHP 5.6.22 btw...

**Comment by flaviocopes** [comment]
Solved?

**Comment by nobol** [comment]
Same problem here on Arch Linux.

**Comment by rhukster** [comment]
@nobol did you try these tips: https://learn.getgrav.org/troubleshooting/page-not-found ???

**Comment by nobol** [comment]
Jup, and I actually had to undo the nginx rip (the last one) and simply moved the installation NOT in a subfolder. Then it worked quite fine.

**Comment by mlopezcoria** [comment]
I had the same issue with CentOS 7 and PHP 7.0.20 and I solved it by modifying to apache config (`/etc/httpd/conf/httpd.conf`) the following setting:

`    <Directory "/var/www">`
`    AllowOverride `**All**


I hope it can help others.

**Comment by flaviocopes** [comment]
Detailed in https://learn.getgrav.org/troubleshooting/page-not-found#allowoverride-all

**Comment by f3bruary** [comment]
Sorry to bring up an old issue, but I have this problem with Lighttpd, after I installed the admin module. I got "mod_rewrite" enabled and server.follow-symlink = "enable" in my config. Not sure what the equivelant of "AllowOverride = All" is in Lighttpd.

**Comment by chansdad** [comment]
While the main site was being rendered , admin site was not , a bit of research and this worked for me 
<Directory "/var/www">
AllowOverrideAll

Thanks to -> mlopezcoria
