### ISSUE TITLE
Error On Softaculous Install: err_alphanumpass

### ISSUE THREAD

**Issue by Xarcell** [getgrav/grav#916]
I don't know really who I should report this to, but in softaculous, it throws this error when I try to install. Using PHP version 5.6.x.

![screenshot from 2016-06-25 12-58-17](https://cloud.githubusercontent.com/assets/6114450/16358003/938805c4-3ad4-11e6-983a-d15cce4011a1.png)

**Comment by ardkevin84** [comment]
password strength issue. 

see this: http://www.gigarank.net/forum/Thread-Ghost-instalation-fails-via-Softaculous

i can't seem to deep-link that thread, but focus on the post with timestamp 04-16-2016, 11:46 PM

**Comment by Xarcell** [comment]
Deep-link what thread?

**Comment by ardkevin84** [comment]
the link i posted explains the issue you're having and how to fix it. i couldn't link directly to the specific comment, though

**Comment by flaviocopes** [comment]
Yes, this is an issue in how Softaculous sets the password format. We're in touch with them to fix this, @rhukster confirm?

**Comment by rhukster** [comment]
I've sent another email to my Softaculous contact.

**Comment by Xarcell** [comment]
This issue seems to have been resolved. Closing....
