### ISSUE TITLE
[add-resource] New Plugin: flickr

### ISSUE THREAD

**Issue by GuLinux** [getgrav/grav#919]
Hi,
I just developed this plugin to create a rich gallery on my website/blog using Grav and Flickr as a backend image provider.

I hope the Readme is clear enough for usage, I soon will provide also a live demo, when I'll finish migrating my website to Grav.
Here's a link to the plugin: https://github.com/GuLinux/grav-plugin-flickr
Cheers,
Marco

**Comment by flaviocopes** [comment]
👍

**Comment by w00fz** [comment]
Nice!

**Comment by OleVik** [comment]
This is most excellent. Remind me, can shortcodes be instantiated through Twig? In the case that you want to designate a Flickr-photoset from the template, rather than the content.

**Comment by GuLinux** [comment]
Hi,
no, I don't think shortcodes can be used in Twig, I did a little test with negative results, though I'm no expert at it, so maybe there could be a way

**Comment by Sommerregen** [comment]
@OleVik @GuLinux The usual way is to add Twig functions and filters via e.g. a Twig Extension for that. You can see it as an improvement for your Flickr plugin.

**Comment by rhukster** [comment]
Sorry guys, been on vaca.  Will add this to repo tomorrow!

**Comment by rhukster** [comment]
Added for next repo regen.

**Comment by GuLinux** [comment]
Thanks :)
Sorry I've been away a bit... lots of changes these days!
Anyway in the meantime I also had released version 1.0.2, could you update the plugin in the repo? or do I have to file a different issue?

**Comment by OleVik** [comment]
The repo auto-updates when you (correctly) create a new release on GitHub.
