### ISSUE TITLE
url() behavior ignores SSL and lack of www

### ISSUE THREAD

**Issue by vemacs** [getgrav/grav#920]
For example:

     <link rel="icon" type="image/png" href="{{ url('theme://images/favicon.png', true) }}" />

when visiting https://mydomain.us will always return http://www.mydomain.us/images/favicon.png. I can't seem to figure out how to force Grav to use SSL, as there seems to be no way to force the root path. The www. being added is annoying as well.

**Comment by flaviocopes** [comment]
Are you using Grav 1.1 or 1.0? If the latter, can you try if you got the same issue with Grav 1.1?

**Comment by vemacs** [comment]
I am using Grav 1.1.

**Comment by flaviocopes** [comment]
I've tested this on a site I have running on HTTPS. It's running with relative urls, but by turning `system.absolute_urls` to `true`, I have the URL generated correctly as `https://mydomain.com/whatever`. 

I guess it's a web server configuration issue but I'm not sure what to suggest, I checked the issues history but cannot find a similar case.

An easy fix is to disable **Absolute URLs** in the system configuration.

**Comment by vemacs** [comment]
I had the option disabled originally, but I when I turned it on, the www. being appended was resolved. Unfortunately, it converted all the paths (even the relative paths) to http, breaking https entirely.

**Comment by LeePorte** [comment]
Is there any reason not to force all traffic to https?

It's a simple mod to your nginx config

`server {
  server_name myservername.com;
  listen 80;
  return 301 https://$host$request_uri;

}

server {

  listen 443 ssl;
  root /usr/share/nginx/grav;
  index index.php;
  include cloudflare.conf;
  ssl_certificate /etc/nginx/ssl/nginx.crt;
  ssl_certificate_key /etc/nginx/ssl/nginx.key;

  location / {
      try_files $uri $uri/ /index.php?$args;
  }

  location ~ /\. {
      return 403;
  }

  ## Begin - Security
  # deny all direct access for these folders
  location ~* /(.git|cache|bin|logs|backups|tests|webserver-configs)/.*$ { return 403; }
  # deny running scripts inside core system folders
  location ~* /(system|vendor)/.*\.(txt|xml|md|html|yaml|php|pl|py|cgi|twig|sh|bat)$ { return 403; }
  # deny running scripts inside user folder
  location ~* /user/.*\.(txt|md|yaml|php|pl|py|cgi|twig|sh|bat|json|scss)$ { return 403; }
  # deny access to specific files in the root folder
  location ~ /(LICENSE.txt|composer.lock|composer.json|nginx.conf|web.config|htaccess.txt|\.htaccess|fixperms.sh|CONTRIBUTING.md|README.md|CHANGELOG.md) { return 403; }
  ## End - Security

  location ~ \.php$ {
      try_files $uri =404;
      fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      include fastcgi_params;
      fastcgi_param  HTTP_MOD_REWRITE  On;
  }
}`

**Comment by vemacs** [comment]
I did that and grav still generates HTTP links.

**Comment by LeePorte** [comment]
Can you still visit http://myservername.com?

**Comment by vemacs** [comment]
No, as it's 301ed to https

**Comment by LeePorte** [comment]
What happens if you disable absolute URLs?

**Comment by w00fz** [comment]
Meaning, make sure you have:

```
fastcgi_param	HTTPS			$https if_not_empty;
```

**Comment by vemacs** [comment]
I actually fixed this another way (I have no idea why), it does seem like it was an issue with my nginx config, not grav.

Changing

    listen 443 ssl;

to

    listen 443;
    ssl on;

Resolved the issue.
