### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by sebelk** [getgrav/grav#924]
Hi,

I've made the quick installation as is in https://getgrav.org/downloads but it didn't work, it outputs:
```
Not Found

The requested URL /cms/admin was not found on this server.
```

I've tried uncommenting `RewriteBase /` on .htaccess

and even changing by:

`RewriteBase /cms`

But it didn't work either...

My info:

```
/var/www/cms# bin/grav  -V
Grav CLI Application version 0.1.0

/var/www/cms# apache2 -v
Server version: Apache/2.4.10 (Raspbian)
Server built:   Jan 23 2016 22:26:49

```

Any ideas?

**Comment by flaviocopes** [comment]
There is a list of common 404 causes on learn.getgrav.org/troubleshooting/page-not-found - did you check it?

**Comment by sebelk** [comment]
Shame on me!

Indeed it was missing `AllowOverride All`
Fixed
