### ISSUE TITLE
HTTP Headers for individual pages

### ISSUE THREAD

**Issue by dimayakovlev** [getgrav/grav#926]
Can be useful to overwrite system and add custom http headers for individual pages.

**Comment by rhukster** [comment]
What sort of headers?

**Comment by dimayakovlev** [comment]
These standard headers:
https://learn.getgrav.org/admin-panel/configuration-system#http-headers
For example, I would like to set individual expires values for some pages.

**Comment by flaviocopes** [comment]
You can set them in the page header: `expires`, `etag`, `last_modified`.

In Admin, they can be added in Expert Mode.

**Comment by dimayakovlev** [comment]
@flaviocopes, thank you!
How I can implement this for page: ```<?php header("Cache-Control: no-cache, must-revalidate"); ?>``` Only with plugin?

**Comment by flaviocopes** [comment]
Yes that can be set using a plugin. 

In the page header you can set a custom expires / etag / last_modified values only.
