### ISSUE TITLE
A non well formed numeric value encountered" in "partials/base.html.twig"

### ISSUE THREAD

**Issue by stelgenhof** [getgrav/grav#928]
Accessing my website (index file), I now suddenly receive the following message: 

`("A non well formed numeric value encountered") in "partials/base.html.twig" at line 27`

Snippet of the template where this takes place:

```
24 {% block stylesheets %}
25     {% do assets.addCss('theme://css/style.css', 100) %}
26 {% endblock %}
27 {{ assets.css() }}
```

The stylesheet is properly formatted. I have tried many things:
- Cleared Cache
- Used empty stylesheet
- Checked Grav pages headers for proper use of date format

If I remove line 27, the page gets rendered but of course without styling. Anybody else experienced this also?

I am using PHP 5.6.23 and Grav 1.0.10

**Comment by flaviocopes** [comment]
There's anything that looks strange in that snippet. Maybe caused by some plugin?

You can PM me the user/ folder via gitter.im/flaviocopes and I can give a look.

**Comment by rhukster** [comment]
Are you sure you are not running PHP 7.1 alpha??? That is a known problem with this early alpha version of PHP.

**Comment by stelgenhof** [comment]
Let me check the plugins if they cause anything strange... I tried different versions of PHP (7.0, 5.6 and 5.5); however all gave the same result.

**Comment by stelgenhof** [comment]
After verifying many things (removed plugins, installed default theme, switched PHP versions, etc.), it caused by my HTTP server. I am using Laravel's Valet which is based on Dnsmasq and CaddyServer.

Restarting Valet solved the issue (ie. error no longer showing), however assets are not found. I will further look into how to solve this. So it's not a Grav issue :)

**Comment by flaviocopes** [comment]
I know it works perfect on Caddy as I use it too, but I never tried Valet

**Comment by stelgenhof** [comment]
Yeah, the strange thing is that it was working before. Perhaps because I did some composer updates, causing this error. Once I restarted Valet it kind of worked. Still don't know the real reason, but hey... :)
