### ISSUE TITLE
Formatting error with two code blocks

### ISSUE THREAD

**Issue by dmenne** [getgrav/grav#929]
**Grav 1.1.0 rc3**

Sample code, simplified from Rcmd (R + knitr) comes in separate zip file because is shows problems with code blocks.
There seems to be a problem when there are 2 code blocks. Grav generates the following wrong output (if we accept that Catalina should be Catilina):

![Wrong output produces be grav](https://cloud.githubusercontent.com/assets/506275/16743825/75c667e2-47ae-11e6-9061-5b9e3b43f4f6.png)

MarkdownPad and knitr produce correct output:

![Correct output produced by Markdownpad](https://cloud.githubusercontent.com/assets/506275/16743848/99921d10-47ae-11e6-93a0-b2bf4cf1ad1f.png)

Looks like some greedy regexps involved trying to catch the last backticks.....

[item.zip](https://github.com/getgrav/grav/files/357886/item.zip)

**Comment by w00fz** [comment]
Seems to be rendering fine in antimatter for me:

![test grav 2016-07-11 12-36-51](https://cloud.githubusercontent.com/assets/11734/16744087/453508b2-4764-11e6-977d-bc2ade784bcd.png)

**Comment by rhukster** [comment]
What plugins are you using? Perhaps something is interfering with the markdown processing because I don't think it's the parsedown library itself as @w00fz points out, it is working with straight up markdown.

**Comment by dmenne** [comment]
Will check plugins tomorrow, it's late. This was Bootstrap. Antimatter see below, same.
![antimatter](https://cloud.githubusercontent.com/assets/506275/16744224/687fa1b4-47b0-11e6-85e6-70808758dc26.png)

**Comment by dmenne** [comment]
Plugins confirmed, Mathjax 1.4.0 causes the trouble. Too bad, I had switched to Grav because I wanted Mathjax...

**Comment by rhukster** [comment]
Maybe add a ticket on the mathjax plugin? It might be something that can be fixed related to the order of processing within the plugin: https://github.com/Sommerregen/grav-plugin-mathjax/issues
