### ISSUE TITLE
Markdown extra tables with long content cause rendered page to time out

### ISSUE THREAD

**Issue by a1studmuffin** [getgrav/grav#930]
Issue context: Grav v1.1.0-rc.3 fresh install (but also occurs in v1.0.10), 100% repro rate

With markdown extra enabled, the following table markdown on a page will result in the page timing out when you save and try to view the rendered page:

---

|aaaaaaa|
|-|
|aaaa aaaaaaaaa aaa aaaaa aaaaa aaaa aaaaaa aaaaaa aaaaa. aaaaa aaa aaaa aaaaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaa aaaaa aaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaaaa aaaaaa aaaaaaaaa aaaaaaaaa.|

---

If you remove a single 'a' character it will start working again - I'm guessing there's a fixed limit somewhere in the markdown extra processing code that's breaking?

**Comment by rhukster** [comment]
I 'think' this is a problem with the regex used by the markdown-extra library we use.  Can you test here: http://parsedown.org/extra/

**Comment by a1studmuffin** [comment]
Appears to work fine in that sandbox, even with longer strings, for example:

|aaaaaaa aaaa aaaaaaaaa aaa aaaaa aaaaa aaaa aaaaaa aaaaaa aaaaa. aaaaa aaa aaaa aaaaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaa aaaaa aaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaaaa aaaaaa aaaaaaaaa aaaaaaaaaaaa aaa aaaaa aaaaaaa aaaaaaa aaaa aaaaaaaaa aaa aaaaa aaaaa aaaa aaaaaa aaaaaa aaaaa. aaaaa aaa aaaa aaaaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaa aaaaa aaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaaaa aaaaaa aaaaaaaaa aaaaaaaaaaaa aaa aaaaa aaaaaaa aaaaaaa aaaa aaaaaaaaa aaa aaaaa aaaaa aaaa aaaaaa aaaaaa aaaaa. aaaaa aaa aaaa aaaaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaa aaaaa aaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaaaa aaaaaa aaaaaaaaa aaaaaaaaaaaa aaa aaaaa aaaaaaa aaaaaaa aaaa aaaaaaaaa aaa aaaaa aaaaa aaaa aaaaaa aaaaaa aaaaa. aaaaa aaa aaaa aaaaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaa aaaaa aaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaaaa aaaaaa aaaaaaaaa aaaaaaaaaaaa aaa aaaaa aaaaaaa aaaaaaa |
|-|
|aaaa aaaaaaaaa aaa aaaaa aaaaa aaaa aaaaaa aaaaaa aaaaa. aaaaa aaa aaaa aaaaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaa aaaaa aaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaaaa aaaaaa aaaaaaaaa aaaaaaaaaaaa aaa aaaaa aaaaaaa aaaaaaa aaaa aaaaaaaaa aaa aaaaa aaaaa aaaa aaaaaa aaaaaa aaaaa. aaaaa aaa aaaa aaaaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaa aaaaa aaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaaaa aaaaaa aaaaaaaaa aaaaaaaaaaaa aaa aaaaa aaaaaaa aaaaaaa aaaa aaaaaaaaa aaa aaaaa aaaaa aaaa aaaaaa aaaaaa aaaaa. aaaaa aaa aaaa aaaaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaa aaaaa aaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaaaa aaaaaa aaaaaaaaa aaaaaaaaaaaa aaa aaaaa aaaaaaa aaaaaaa aaaa aaaaaaaaa aaa aaaaa aaaaa aaaa aaaaaa aaaaaa aaaaa. aaaaa aaa aaaa aaaaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaa aaaaa aaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaaaa aaaaaa aaaaaaaaa aaaaaaaaaaaa aaa aaaaa aaaaaaa aaaaaaa aaaa aaaaaaaaa aaa aaaaa aaaaa aaaa aaaaaa aaaaaa aaaaa. aaaaa aaa aaaa aaaaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaa aaaaa aaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaaaa aaaaaa aaaaaaaaa aaaaaaaaaaaa aaa aaaaa aaaaaaa aaaaaaa aaaa aaaaaaaaa aaa aaaaa aaaaa aaaa aaaaaa aaaaaa aaaaa. aaaaa aaa aaaa aaaaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaa aaaaa aaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaaaa aaaaaa aaaaaaaaa aaaaaaaaaaaa aaa aaaaa aaaaaaa aaaaaaa aaaa aaaaaaaaa aaa aaaaa aaaaa aaaa aaaaaa aaaaaa aaaaa. aaaaa aaa aaaa aaaaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaa aaaaa aaaa aaaa aaaaa aaaaa aaaaa aaaaaaa aaaaaa aaaaaa aaaaaaaaa aaaaaaaaaaaa aaa aaaaa aaaaaaa aaaaaaa .|

**Comment by rhukster** [comment]
Even your long example works for me.

![markdown extra tables grav 2016-08-16 17-52-58](https://cloud.githubusercontent.com/assets/1084697/17719773/5129f24e-63da-11e6-8a0d-062a25e42469.png)

I have a tonne of pages and plugins in this instance too.  Could be related to RAM or something though? What is your PHP memory size?

**Comment by rhukster** [comment]
Closing to due to inactivity
