### ISSUE TITLE
Installation Error Fetch Failed  undefined is not an object evaluating t.isUpdatable

### ISSUE THREAD

**Issue by qasimk2** [getgrav/grav#932]
Hi All,

Just installed grab 1.1 rc3 on a clean ubuntu 16.04 with php7.

I am getting the attached message in the admin panel, though it does not seem to be affecting the website pages.

<img width="333" alt="grav_error" src="https://cloud.githubusercontent.com/assets/20448849/16826593/33bb6924-49b1-11e6-972d-613c765e59b4.png">

**Comment by rhukster** [comment]
Do you have all the requirements for PHP installed?

https://learn.getgrav.org/basics/requirements#php-requirements
