### ISSUE TITLE
Latest Updates, Core, Admin & Gravstrap

### ISSUE THREAD

**Issue by 2braincells2go** [getgrav/grav#934]
Was working on new site using Gravstrap. Got notice of updates and updated all.

Gravstrap theme was not one updated but, now the header / footers menus are gone, totally missing from entire site.

Looks like the shortcode core plugin is the cause.

Also just noticed can no longer add new pages after updating code + admin plugin. Time to restore last good backup and start over...

Not for faint of the heart for sure, lol. One lesson I learned, do not update a site you want and certainly make sure you backup before doing anything:)

**Comment by w00fz** [comment]
When you updated Grav and then Admin, did you also do clear all and updated everything else that popped up?

**Comment by 2braincells2go** [comment]
Yes sir, that is what I did.

**Comment by 2braincells2go** [comment]
The shortcode core plugin seems to break bootstrap based theme header/footer menus. For sure on Gravstrap.

When trying to add a new page, fill out fields in popup and when clicking "continue" nothing happens. No errors in chrome dev console either.

**Comment by 2braincells2go** [comment]
Restored admin, email, form and login plugins. All fine and can now add a page...

**Comment by rhukster** [comment]
Still having problems?

**Comment by MindlessPursuits** [comment]
Just to add, rather than create a new report - I have encountered the issue as well, both in upgrading, and in doing a completely fresh install of the Grav+Admin package. It does not appear to be browser-specific, as I can't add a page through the admin plugin using chrome, firefox or MS Edge.

**Comment by w00fz** [comment]
I was able to reproduce. Looking into it now.

**Comment by w00fz** [comment]
This is an admin issue. Workaround for the moment is to create an empty page manually so that the Pages list in admin picks it up, you will be able to then edit it as normal.

**Comment by w00fz** [comment]
Issue was introduced with https://github.com/getgrav/grav-plugin-admin/issues/694

**Comment by w00fz** [comment]
Fix is in place, Admin is getting re-released and it will be available in few mins. 

MS Edge is still known to cause problems when saving a Page, we will address this soon, you can subscribe to https://github.com/getgrav/grav-plugin-admin/issues/694 to follow the progress, if needed.

Sorry for the inconvenience!

**Comment by 2braincells2go** [comment]
Thanks much guys!

**Comment by flaviocopes** [comment]
@2braincells2go your original issue with footer and header is solved now?

**Comment by 2braincells2go** [comment]
@flaviocopes no it is not buy issue closed so figure no hope.

When updating shortcode core plugin, the Gravstrap (and a bootstrap based theme I am creating) header/footer menus disappear.

**Comment by flaviocopes** [comment]
Ok this is not an issue of Grav itself, but the shortcode plugin. Can you report it here? https://github.com/getgrav/grav-plugin-shortcode-core/issues just to keep things organized

**Comment by 2braincells2go** [comment]
@flaviocopes, no problem, will do. I used my mobile yesterday to work on GitHub and some crazy things happened. Think be last time to choose that route to work on GitHub:)
