### ISSUE TITLE
0 - An exception has been thrown during the rendering of a template

### ISSUE THREAD

**Issue by AlexL777** [getgrav/grav#935]
Hello Developers,

I have problems with the latest GRAV Version, especially with the Admin Plugin. The Pages in the admin sector are unreachable. I have just installed the admin plugin from an older version, but the result is the same. The Pages I can not create.

In the Backend under **/admin/pages** this error message:

```
Server Error
Sorry, something went terribly wrong!

0 - An exception has been thrown during the rendering of a template ("First parameter must be URI") in "pages.html.twig" at line 124.
```

Can you help me somehow?

Thanks in advance.

I have PHP 5.6, latest MySQL version and the latest GRAV version. But apparently it does not quite work.

**Comment by rhukster** [comment]
You really need to run Admin v1.1 with Grav 1.1.  it will be very unreliable running with an older version.  That said it should just work fine.  How did you update Grav and the plugins? were there any errors reported during that?

**Comment by AlexL777** [comment]
Hello @rhukster ,

I now have the very last version of the Admin plugins and have just reinstalled the admin at the command line.

Unfortunately, the error is still present.

Yesterday I installed the CMS GRAV again under Centos 7 and since I have no problems with the admin plugin.

Very strange, I find the.

I All plugins updated and the CMS itself is uptodate.

What else can I do??

**Comment by AlexL777** [comment]
I still have that and with this SSH command I can not install.

I was asked today when updating to execute this SSH command.

    php56 bin/grav install
    ERROR Missing .dependencies file in user/ folder
    ERROR invalid YAML in .dependencies

**Comment by w00fz** [comment]
What are the outputs for `bin/gpm version` and `bin/gpm index --installed-only`?

Also where did it say you had to run `bin/grav install`?

**Comment by AlexL777** [comment]
php56 bin/gpm version
    You are running Grav v1.1.1

    php56 bin/gpm index --installed-only

    GPM Releases Configuration: Stable

    Plugins [ 36 ]
    01. Archive Plus         [    archive_plus    ]  [v1.3.2]            (installed)
    02. Smileys              [      smileys       ]  [v1.2.1]            (installed)
    03. Shortcodes           [     shortcodes     ]  [v1.2.0]            (installed)
    04. reCAPTCHA Contact    [  recaptchacontact  ]  [v1.0.8]            (installed)
    05. Toc                  [        toc         ]  [v1.3.1]            (installed)
    06. SocialButtons        [   socialbuttons    ]  [v1.0.3]            (installed)
    07. DropCaps             [      dropcaps      ]  [v1.3.4]            (installed)
    08. Markdown Sections    [ markdown-sections  ]  [v0.9.1]            (installed)
    09. AdSense              [      adsense       ]  [v1.0.1]            (installed)
    10. Markdown Notices     [  markdown-notices  ]  [v1.0.0]            (installed)
    11. Markdown Color       [   markdown-color   ]  [v1.0.1]            (installed)
    12. Taxonomy List        [    taxonomylist    ]  [v1.2.7]            (installed)
    13. Random               [       random       ]  [v1.5.0]            (installed)
    14. Materializer         [    materializer    ]  [v1.7.0]            (installed)
    15. View                 [        view        ]  [v1.3.2]            (installed)
    16. Bootstrapper         [    bootstrapper    ]  [v1.3.2]            (installed)
    17. BlogInjector         [   blog-injector    ]  [v1.2.2]            (installed)
    18. CookiesPolicy        [   cookiespolicy    ]  [v1.0.9]            (installed)
    19. JSComments           [     jscomments     ]  [v1.2.10]           (installed)
    20. Pagination           [     pagination     ]  [v1.3.2]            (installed)
    21. Problems             [      problems      ]  [v1.4.3]            (installed)
    22. AboutMe              [      aboutme       ]  [v1.1.3]            (installed)
    23. Shortcode Core       [   shortcode-core   ]  [v2.3.1]            (installed)
    24. Feed                 [        feed        ]  [v1.5.0]            (installed)
    25. Editor Buttons       [   editor-buttons   ]  [v1.1.1]            (installed)
    26. Email                [       email        ]  [v2.4.1]            (installed)
    27. SimpleSearch         [    simplesearch    ]  [v1.8.0]            (installed)
    28. Related Pages        [    relatedpages    ]  [v1.1.3]            (installed)
    29. Form                 [        form        ]  [v1.3.0]            (installed)
    30. Login                [       login        ]  [v2.0.0]            (installed)
    31. Breadcrumbs          [    breadcrumbs     ]  [v1.5.0]            (installed)
    32. Archives             [      archives      ]  [v1.5.0]            (installed)
    33. Error                [       error        ]  [v1.5.0]            (installed)
    34. Sitemap              [      sitemap       ]  [v1.6.2]            (installed)
    35. Comments             [      comments      ]  [v1.2.0]            (installed)
    36. Admin Panel          [       admin        ]  [v1.1.2]            (installed)

    Themes [ 16 ]
    01. Materialize          [    materialize     ]  [v1.3.8]            (installed)
    02. Bones Vanilla        [   bones-vanilla    ]  [v0.5.2]            (installed)
    03. Alpha                [       alpha        ]  [v2.0.2]            (installed)
    04. Developer            [     developer      ]  [v2.0.4]            (installed)
    05. Future               [       future       ]  [v1.0.7]            (installed)
    06. Cardstack            [     cardstack      ]  [v1.1.3]            (installed)
    07. Purity               [       purity       ]  [v0.5.5]            (installed)
    08. Pinpress             [      pinpress      ]  [v1.2.0]            (installed)
    09. Bootstrap            [     bootstrap      ]  [v1.5.0]            (installed)
    10. TwentyFifteen        [   twentyfifteen    ]  [v1.1.0]            (installed)
    11. Afterburner2         [    afterburner2    ]  [v1.6.0]            (installed)
    12. Woo                  [        woo         ]  [v1.2.0]            (installed)
    13. Striped              [      striped       ]  [v2.2.0]            (installed)
    14. SoraArticle          [    soraarticle     ]  [v1.4.0]            (installed)
    15. Deliver              [      deliver       ]  [v1.5.0]            (installed)
    16. Antimatter           [     antimatter     ]  [v2.0.0]            (installed)


My GRAV installation is under http://internetblogger.org. In the frontend works everything, but just under **/admin/pages** is nothing.
`

**Comment by flaviocopes** [comment]
@AlexL777 I cannot reproduce this problem. Easiest and fastest way is PM me you user/ folder to gitter.im/flaviocopes, you can remove the user/accounts and user/data folders

**Comment by craigward** [comment]
Im currently having the same issue, updated via the admin panel, everything works fine front and back until I try to get to the Pages section in the admin. I then get the following error

`An exception has been thrown during the rendering of a template ("First parameter must be URI") in "pages.html.twig" at line 124.`

**Comment by flaviocopes** [comment]
@craigward not having heard from @AlexL777, I send the question to you - I can't replicate myself. PM me you user/ folder to gitter.im/flaviocopes, you can remove the user/accounts and user/data folders, so I can recreate the issue

**Comment by craigward** [comment]
sent you message on Gitter with a link to the file

**Comment by flaviocopes** [comment]
@AlexL777 @craigward  looks like the View plugin is the problem. I'm going to open an issue on its repo https://github.com/ellioseven/grav-plugin-view

**Comment by flaviocopes** [comment]
Ok I already stumbled on this in https://github.com/getgrav/grav-plugin-admin/issues/664 and made a PR on it, but it's missing a release - pinging the dev

**Comment by matthew-dean** [comment]
I had this message show up after switching from one theme to another. Ideally, Grav would issue a more recoverable warning.

**Comment by Perlkonig** [comment]
Make sure errors:show is set to true to get the full error. You're probably missing a plugin or something.
