### ISSUE TITLE
Feature request: command line agruments for demo content

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav#936]
I have a bash script to check and update many of my Grav sites to latest release. With "-y" argument for `bin/gpm selfupgrade` and `bin/gpm update` everything is almost automatic. I need to manually answer the questions for demo content:

> Attention: Cacti contains demo content
> Do you wish to install this demo content? [y|N]
> This will backup your current `user/pages` folder to `user/pages.07-15-2016-11-54-21`, continue? [y|N]

I think it really helps if there are 2 argument to assume yes or no for installing demo content and backing up current content.

**Comment by w00fz** [comment]
I think with just `-y` it should quietly answer `no` to demo content and `no` to backup. We could then have a `-y-demo` and `-n-demo` to change this default behavior and force it to whether update demo content or not.

**Comment by rhukster** [comment]
This will default to `Yes` for both of these questions with the next Grav release.
