### ISSUE TITLE
Minor CSS Problem - Maintenance text off center on toggling sidebar

### ISSUE THREAD

**Issue by barryanders** [getgrav/grav#937]
![screen shot 2016-07-15 at 3 54 39 pm](https://cloud.githubusercontent.com/assets/5648875/16888283/a9e657c8-4aa4-11e6-8493-93d48a53d429.png)

Browser: Safari Version 9.1.1

On large screen view, after collapsing the sidebar and then opening it back up, this happens.

**Comment by rhukster** [comment]
This is the wrong repo. Please reopen in the admin plugin issue tracker as we can't move it.

**Comment by w00fz** [comment]
I fixed this in admin anyway.
