### ISSUE TITLE
Blueprint toggle type's value is not available in configuration variable if yes/true is selected

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav#939]
In my theme I have a field for configuring to show site logo or not:

```
show_logo:
	type: toggle
	toggleable: false
	label: Show Logo
	help: Show site's logo.
	options:
		1: PLUGIN_ADMIN.YES
		0: PLUGIN_ADMIN.NO
	validate:
		type: bool
```

If I select Yes, the field is not included in theme's configuration in Twig.
If I select No, the field is available in Twig with value "false".

So to know if logo should be shown, I need to do like this:

```
{% if themeCfg.show_logo is null %}
```

Am I doing something wrong? Should Grav always include the field's value in configuration variable as "true" or "false"?

**Comment by rhukster** [comment]
try removing that `toggleable: false`
