### ISSUE TITLE
user/config/media.yaml

### ISSUE THREAD

**Issue by ritchiedalto** [getgrav/grav#943]
After the upgrade to 1.1.1, a custom plugin that I wrote stopped working. It pulls in an attached `.csv` file and does some stuff with the data. When I set this up I had to put...

```
csv:
  type: file
  thumb: media/thumb-xml.png
  mime: text/css
```

...in the `user/config/media.yaml` file for it to allow dropping of a `.csv` file onto a page in the media section. After this upgrade my plugin stopped working, I checked the `user/config/media.yaml` file and the above settings were in there. But in the admin ui, on the **media tab**, there was no entry for `.csv`  So I entered one there in the UI, saved, and my plugin worked again. The entry still exists in `user/config/media.yaml` just the same as before.

Forgive the insanity of attaching this image, but I didnt know how to give you the diff as text. This shows the `media.yaml` file after upgrade to 1.1.1 compared with after I added the `.csv` settings via the Admin UI.

![media-yaml-grav-git-diff](https://cloud.githubusercontent.com/assets/3119016/16901660/f857bcd4-4c17-11e6-9090-47a4201251c2.jpg)

Thought I'd mention this, I'm thinking it's a bug to break stuff like this, and someone else might need to know this info.

**Comment by rhukster** [comment]
We did change the media array to be nested under `types:` due to other issues that needed this fix to resolve. Your saved file looks strange though, so there may be a bug with how new media types are saved.  I will look at this soon.

**Comment by flaviocopes** [comment]
The media.yaml file was saved correctly as the `types` yaml object was added, and the old media objects are still there, but now unused, as Andy says, the structure changed and this is a backwards incompatible change which was introduced to solve another issue.

Maybe we could have some logic to overcome this BI change, and merge the existing media information but this would probably cause more issues than the ones it's solving

**Comment by rhukster** [comment]
Not sure if it's possible, i will investigate when i get a chance.
