### ISSUE TITLE
Failed to update from 1.1 to 1.1.1

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav#944]
Hello!

Tried to update in admin panel and got an error:
```
Warning: require(C:\OpenServer\domains\dissolution\vendor\composer/../../system/defines.php): 
failed to open stream: Permission denied in
C:\OpenServer\domains\dissolution\vendor\composer\autoload_real.php on line 66
```

Site and admin panel not working now.

**Comment by rhukster** [comment]
Says permission denied for `system/defines.php`.  Is this file not readable by the webserver?

**Comment by rhukster** [comment]
BTW have you ever upgraded Grav before?  From say 1.0.9 to 1.0.10?

**Comment by Sogl** [comment]
I'm on Windows 7 and have full admin rights.

>BTW have you ever upgraded Grav before? From say 1.0.9 to 1.0.10?
Yes, all updates I did in Admin panel.

Problem is solved with moving to previous commit and update again.

**Comment by rhukster** [comment]
which commit works and which commit doesn't?

**Comment by rhukster** [comment]
If we can isolate a commit specifically we can certainly determine what is causing this. I suspect it's related to Windows and the direction of the slashes as those seem to be different in that string you posted.

**Comment by rhukster** [comment]
Also when does this error occur? During the Grav upgrade process itself? can you take a screenshot of the error?

**Comment by Sogl** [comment]
It's my own repo commit with previous 1.1 version. I'm just moving to it without saving 1.1.1 breaking changes.

>I suspect it's related to Windows and the direction of the slashes as those seem to be different in that string you posted.

I don't think so... just because in Windows right slash works in the same way as left.
For example, `C:/Windows\system32` moves you to `C:\Windows\system32` correctly.

>Also when does this error occur? During the Grav upgrade process itself? 

Something happend during the update and after page refresh I saw this error.

>can you take a screenshot of the error?

No. I can't reproduce because second update works fine. 
But I can try to revert and update again some times.

**Comment by rhukster** [comment]
There was very minor changes between 1.1.0 and 1.1.1.  Nothing that would cause this.  Please try the update again and see if the issue persists.

**Comment by Sogl** [comment]
Tried 5 times without any error...

My console still open and I can share full update command output:
```
mezin.a@MEZIN MINGW64 /c/OpenServer/domains/dissolution (master)
$ bin/grav update -f

Warning: require(C:\OpenServer\domains\dissolution\vendor\composer/../../system/defines.php): failed to open stream: Permission denied in C:\OpenServer\domains\dissolution\vendor\composer\autoload_real.php on line 66

Call Stack:
    0.0000     247792   1. {main}() C:\OpenServer\domains\dissolution\bin\grav:0
    0.0000     249744   2. require_once('C:\OpenServer\domains\dissolution\vendor\autoload.php') C:\OpenServer\domains\dissolution\bin\grav:21
    0.0010     268424   3. ComposerAutoloaderInit6c2d5a8ec8024ca4dc88746518918b5a::getLoader() C:\OpenServer\domains\dissolution\vendor\autoload.php:7
    0.0050     707560   4. composerRequire6c2d5a8ec8024ca4dc88746518918b5a() C:\OpenServer\domains\dissolution\vendor\composer\autoload_real.php:56

Dump $_SERVER
   $_SERVER['REMOTE_ADDR'] is undefined
   $_SERVER['REQUEST_METHOD'] is undefined
Dump $_SESSION
   $_SESSION['*'] is undefined
Dump $_REQUEST

Fatal error: require(): Failed opening required 'C:\OpenServer\domains\dissolution\vendor\composer/../../system/defines.php' (include_path='.;c:/openserver/modules/php/PHP-5.6-x64;c:/openserver/modules/php/PHP-5.6-x64/PEAR/pear') in C:\OpenServer\domains\dissolution\vendor\composer\autoload_real.php on line 66

Call Stack:
    0.0000     247792   1. {main}() C:\OpenServer\domains\dissolution\bin\grav:0
    0.0000     249744   2. require_once('C:\OpenServer\domains\dissolution\vendor\autoload.php') C:\OpenServer\domains\dissolution\bin\grav:21
    0.0010     268424   3. ComposerAutoloaderInit6c2d5a8ec8024ca4dc88746518918b5a::getLoader() C:\OpenServer\domains\dissolution\vendor\autoload.php:7
    0.0050     707560   4. composerRequire6c2d5a8ec8024ca4dc88746518918b5a() C:\OpenServer\domains\dissolution\vendor\composer\autoload_real.php:56


````

**Comment by flaviocopes** [comment]
Looks like the path is generated wrongly by Composer, is this possible? Did you move the site from linux to windows? Can you try renaming the vendor/ folder (don't delete, in case you can revert) and then run `composer install`?

**Comment by rhukster** [comment]
Well the composer stuff is generated on linux during the building of the packages, so that 'could' be linux centric, but never been a problem before.  Closing for now, if it happens on next update, please open a new issue.

**Comment by Sogl** [comment]
@rhukster Same problem with update from 1.1.1 to 1.1.3 on Mac OS X. Strange JSON error and now site shows `Please run: bin/grav install`, but I can't because `-bash: bin/grav: Permission denied`.
Revert to previous commit didn't help.

My Apache runs as current user so I can't understand what's going wrong.

**Comment by Sogl** [comment]
These lines not helped:
```
chown Artyom:staff .
chown -R Artyom:staff *
find . -type f | xargs chmod 664
find . -type d | xargs chmod 775
find . -type d | xargs chmod +s
umask 0002
```
But `composer install` helps.

Now site works and `bin/grav install` show this:
```
Warning: require_once(/Users/Artyom/domains/dissolution/bin/../vendor/autoload.php): 
failed to open stream: No such file or directory in 
/Users/Artyom/domains/dissolution/bin/grav on line 21

Fatal error: require_once(): Failed opening required 
'/Users/Artyom/domains/dissolution/bin/../vendor/autoload.php' (include_path='.:') 
in /Users/Artyom/domains/dissolution/bin/grav on line 21
```

Second attempt to update failed:
```
rmdir(/Users/Artyom/domains/dissolution/vendor/bin): Directory not empty
```
and third:
```
unlink(): No such file or directory
```

Screen:
![image](https://cloud.githubusercontent.com/assets/7556290/17732181/49471664-64bc-11e6-8374-0910a033e7fc.png)

**Comment by rhukster** [comment]
I suggest downloading the core Grav package from getgrav.org, extracting it then copying over your user folder from you current install. 

That should fix everything.

**Comment by Sogl** [comment]
Found new file in `cachetmp/Grav-57b42bef1f34b/grav-update-v1.1.3.zip`. Can it work with extracting it?

**Comment by w00fz** [comment]
I'd just delete cache and grab the latest update package from https://github.com/getgrav/grav/releases

**Comment by Sogl** [comment]
Solved with manual update...
