### ISSUE TITLE
Correct usage of arbitrary yaml files in the config folder

### ISSUE THREAD

**Issue by locii** [getgrav/grav#949]
In the documentation on this page:
 it mentions that you can use an arbitrary yaml file to load config values:

"You are also not limited to the user/config/system.yaml or the user/config/site.yaml files as described above. You can create any arbitrary .yaml configuration file in the user/config folder you wish and it will get picked up by Grav automatically."

I've understood that to mean that if I add a file called hello.yaml in the config folder I should be able to access the yaml data using something like this in a twig template:

{{hello.mysetting}}

However it's not getting picked up.

If I put an error in the yaml I get a whoops page so it seems that the hello.yaml is loaded so I guess it's a matter of finding the right syntax.

Any pointers on what that syntax should be?

Thanks

**Comment by flaviocopes** [comment]
`config.hello.mysetting` should work, can you check?

**Comment by rhukster** [comment]
I will update the docs with this information.

**Comment by locii** [comment]
Hi yes thanks that's perfect:

{{config.hello.mysetting}}

I didn't think that was needed because the plugin syntax didn't require it but it makes sense now.
Thanks!

**Comment by locii** [comment]
Just added the edit to that page.

**Comment by flaviocopes** [comment]
@locii make a PR from your branch, I'l merge it

**Comment by locii** [comment]
@flaviocopes done :)

https://github.com/getgrav/grav-learn/pull/297
