### ISSUE TITLE
Reordering Metadata, Redirects, and Routes

### ISSUE THREAD

**Issue by barryanders** [getgrav/grav#950]
Noticed in Site>Config that it's seemingly impossible to move metadata, redirect, or routes up and down. It might be nice to be able to drag and drop them. Over time, someone may want to reorganize them and if they can't, then they only solution is to remove them all and start over (kind of like writing on a chalk board).

**Comment by rhukster** [comment]
Really this would require the ability to reorder our 'array' type.  Adding it as an enhancement.

**Comment by w00fz** [comment]
The only reason there is no reordering capabilities at the moment is because in array field the order doesn't really matter.
However I can see this being useful for organizational purposes.

**Comment by w00fz** [comment]
This is implemented now. Please note that this issue should have been opened in the [grav-plugin-admin](https://github.com/getgrav/grav-plugin-admin) repository.
