### ISSUE TITLE
Please add way to get image height/width in twig

### ISSUE THREAD

**Issue by jmaronson** [getgrav/grav#953]
I originally brought this up on the grav forum (https://getgrav.org/forum#!/general:is-there-a-simple-way-to-ge).

Currently, the width() and height() actions available on images only allow you to _set_ the width/height.  This is defined in the file '/system/src/Grav/Common/Page/Medium/ImageMedium.php'.  I am requesting either adding getWidth() and getHeight() functions, or having the width() and height() functions return the values when passed nothing (currently passing nothing causes width/height to be set to 'auto').  This would be useful for flow control in the template, when different markup is desired depending on the image's dimensions, or its aspect ratio.

In my current project I have added the get* functions, like this:
```
    public function getWidth()
    {
        if (!$this->image) {
            $this->image();
        }
        return $this->image->getAdapter()->width();
    }
```
But I'm not sure if this is the best way to implement.  Thank you.

**Comment by w00fz** [comment]
I think `page.media['file.jpg'].height` works just fine?

**Comment by jmaronson** [comment]
Oh wow, you're right!  I didn't see that in the documentation anywhere.  Ok, thanks.

**Comment by krispy1298** [comment]
Has anyone tried this with gifs or movies? I'm having issues with that. I think its just outputting the html tag.

**Comment by rhukster** [comment]
Only works on images.  There's no way in PHP to get video dimensions. Also animated GIFs are not supported by GD library.

**Comment by daspete** [comment]
Hi there,

i'm trying to get the dimension if images that are not in the page.medias, for default images (for sharing) is there a way to get image dimensions from absolute pathes?
