### ISSUE TITLE
[add-resource] New Plugin: Cookies Notice

### ISSUE THREAD

**Issue by kwachu96** [getgrav/grav#954]
Hello, 
I created plugin for their own needs with my project where as backend I use Grav. 
Plugin displays banner at the top or bottom of the page. It can be freely modified, because it has the ability to import your own css, of course supports multi language on the page. 

This is a project page on GitHub:  [kwachu96/grav-plugin-cookies-notice](https://github.com/kwachu96/grav-plugin-cookies-notice)
Regards, 
kwachu

**Comment by flaviocopes** [comment]
Out of curiosity, does this differ from https://github.com/giansi/grav-plugin-cookies-policy or the end result is more or less the same?

**Comment by kwachu96** [comment]
The difference is that: my plugin only display banner (but on top or bottom) and 
it has the possibility of changing the appearance easier by load own css in field by admin panel e.g.

**Comment by rhukster** [comment]
Added for next repo update
