### ISSUE TITLE
Parent page listing in Admin UI

### ISSUE THREAD

**Issue by ritchiedalto** [getgrav/grav#955]
The screen shot should say it all... One of my users found this right after last upgrade - The **parent** page field in the admin ui shows all these `&nbsp;` codes. So weird, and it's on literally every modular child page in the entire site!

![nbsp](https://cloud.githubusercontent.com/assets/3119016/17075872/d3eb17c2-506f-11e6-9f24-9126fcbc8814.jpg)

**Comment by rhukster** [comment]
Please open this in the admin plugin repo.
