### ISSUE TITLE
addInlineJs, when set from modular page, disappears when force-reloading the page.

### ISSUE THREAD

**Issue by ulilu** [getgrav/grav#959]
I edited the [lightslider.twig-template](https://github.com/getgrav/grav-plugin-lightslider/blob/master/templates/modular/lightslider.html.twig) on my page like so:
```
{% set script %}
$(document).ready(function() {
...
});
{% endset %}
{% do assets.addInlineJs(script) %}
```
in order to get the Lightslider inline `<script>`-block to appear with the rest of my JS assets just before the closing`</body>` on my base.twig-file.

When I empty the cache, everything is fine on the first page load - the inline script gets placed with the other inline-scripts (google analytics, featherlight), right before the `</body>`. However, as soon as i force a browser reload, the Lightslider inline JS is no longer there (nor anywhere else on the page). 

After playing around with this bug for quite a while ([i already posted some of my findings in the forum - see the last comment](https://getgrav.org/forum#!/plugin-development:relocate-lighslider-plugin)) , I think it might have to do with the fact, that inlineJS coming from modular pages only gets added to the page if the cache is empty / the content is new / the page gets called for the first time.

It would be great if you could have a look, thank you!

**Comment by rhukster** [comment]
This is expected behavior actually when using Twig.  Twig in the page is only processed once, then the resultant HTML is cached.  After that, only the cached HTML is retrieved.  Twig is not processed.  If you need Twig to run every time, you must set this in the page headers:

```
cache_enable: false
```

**Comment by Gog0** [comment]
Hmm having the same problem. Disabling the cache sounds more like a workaround than an acutal solution. Choosing between having cache or having few lines of JS working isn't really cool. Isn't ther any way to cache the inline JS from the module as well?
