### ISSUE TITLE
Markdown list parse error

### ISSUE THREAD

**Issue by tsipos** [getgrav/grav#960]
Hello, i found problems when using (un)ordered lists in grav. Markdown parser is rendering weird characters when using special characters like ``` č ž ť ```. When i remove list, text is rendered correctly.
Here is screenshot, input from admin plugin is on the left half of picture and result is on the right. Any help with this? Thanks
![markdown_problem](https://cloud.githubusercontent.com/assets/17762107/17137736/0ba487f0-533d-11e6-8e56-8fc8ff50f8ee.png)

**Comment by rhukster** [comment]
Can you please test here also: http://parsedown.org/demo

This will identify if it's a parsedown error (the markdown library we have) or a Grav issue. If you can include a 'paste' of your test strings, it will let me test with your exact same use case.  Cheers.

**Comment by rhukster** [comment]
I'm not getting any issues with this:

```
* test
* hocičo
* aaaaasssaaaa
```

What other plugins do you have installed?

**Comment by tsipos** [comment]
I tried parsedown demo and text is correct. I am having installed following plugins:
``` Admin Panel  v1.1.2
 Email  v2.4.1
 Error  v1.5.1
 Form  v1.3.0
 Login  v2.0.0
 Markdown Notices  v1.0.0
 Pagination  v1.3.2
 Problems  v1.4.3
 Related Pages  v1.1.4
 SimpleSearch  v1.8.0
 Taxonomy List  v1.2.7```

I also found that this problem is happening only on my hosting, which is running on linux. I tried locally using xampp on windows and there is no problem. I have no idea what to do

**Comment by tsipos** [comment]
## Problem found!
I found that problem is ```substr_replace```. I changed code in ```vendor/erusev/parsedown/Parsedown.php``` on line 1461 to ```$markup = substr($markup, 0, $position - strlen($markup));``` and now, everything is working. @rhukster can you please take a look at it? Thanks

**Comment by rhukster** [comment]
Well I can't replicate the problem you are having, so I can't really test your fix.  

However, that fix is in the Parsedown library we use so you need to raise the issue with the author of that library and potentially submit a PR.

https://github.com/erusev/parsedown/issues

He's going to know better if it's a legit bug or something you would need to tweak/configure on your end.

**Comment by tsipos** [comment]
thanks. I further found that this issue is related with server setting and happens only when ```mbstring.func_overload = 7```

**Comment by rhukster** [comment]
sounds like it definitely is something on your server end then, but should definitely raise that with ersuev.

**Comment by tsipos** [comment]
thanks, i raised issue with erusev.
