### ISSUE TITLE
system/config/system.yaml has twig debug enabled

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav#963]
Not sure if it can be abused in some way but as general practise, it feels better not to enable debug settings in a release. In 1.1.1 I noticed that this setting is true. 

Just notice in the doc it says disabled by default (This feature is disabled by default, but can be turned on ...)

For instance a plug-in might accidently have a dump() in it's twig ...

**Comment by rhukster** [comment]
It's not full debug (debug bar etc), it's only Twig's debug statement, and it caused more problems when it was off by default because people didn't know how to enable it.
