### ISSUE TITLE
Content Editor missing content and logout on save

### ISSUE THREAD

**Issue by 88kbbq** [getgrav/grav#965]
Installed the latest Woo skeleton, working in the Admin. Setup is all good. I tried to edit a page Modular in the editor's expert mode Frontmatter but get logged out of Grav upon save. Data is saved but have to log back in with an "Invalid Security Token" error. I'm not able to edit content in normal mode because content isn't even visible in Editor mode. In Preview, mode the content appears but is not editable.

**Comment by flaviocopes** [comment]
Tested, not having issues with editing in expert mode, with a fresh Woo skeleton.

Do you have a specific page that gives this problem, or happens with any modular child page? Also, is this limited to modular pages, or happens with editing the "Style Guide" page too, which is a page of type "default"?

**Comment by 88kbbq** [comment]
Thanks for the reply Flaviocopes. Was just getting ready to move back to Craft but really, really want Grav to work. To show you what's going on, I made a quick SC mov. If you can figure out what's going on, please do share. I can give you access to the instance if there's an RT forum we can meet on, even let you inside the box if you're curious enough. Cheers! 
https://cloud.88k.com.tw/index.php/s/7k7txNgyVnlwgEz

**Comment by w00fz** [comment]
This issue should be opened in the [grav-plugin-admin](https://github.com/getgrav/grav-plugin-admin) repo.

That said, can you try running the current [`develop`](https://github.com/getgrav/grav-plugin-admin/archive/develop.zip) instance of the admin?
