### ISSUE TITLE
Multisite - streams from setup.php ignored

### ISSUE THREAD

**Issue by wardr** [getgrav/grav#967]
Grav version: 1.1.1

Following [the instructions on multisite setup](https://learn.getgrav.org/advanced/multisite-setup), Grav does not use the stream returned from setup.php.
## Steps to reproduce:
1.  Create a working single Grav site normally.
2. Under "user", create a directory named "www"
3. Copy contents of "user" to "user/www"
4. Create setup.php as per directions, with contents:

Note: paths hard-coded in this example, for simplicity. 

```
<?php

use Grav\Common\Utils;

$environment = isset($_SERVER['HTTP_HOST'])
    ? $_SERVER['HTTP_HOST']
    : (isset($_SERVER['SERVER_NAME']) ? $_SERVER['SERVER_NAME'] : 'localhost');

$environment = strtolower(Utils::substrToString($environment, ':'));

return [
    'environment' => $environment,
    'streams' => [
        'schemes' => [
            'user' => [
                'type' => 'ReadOnlyStream',
                'prefixes' => [
                    '' => ['user/www'],
                ]
            ]
        ]
    ]
];
```
1. Clear cache and run. Result: Grav displays the "Issues Found" page, with the issues being that it cannot find the following directories:
- user/data
- user/pages
- user/config
- user/plugins/error
- user/plugins
- ser/themes
## Workarounds attempted:
1.  Try defining all the streams, e.g. 

```
return [
    'user' => [
        'type' => 'ReadOnlyStream',
        'paths' => [
            '' => ['user/www'],
        ]
    ],
    'config' => [
        'type' => 'ReadOnlyStream',
        'prefixes' => [
            '' => ['user://config'],
        ]
    ],
// snipped for brevity
```

Result: Grav displays "Theme 'antimatter' does not exist, unable to display page." and Grav generates a file: user/config/security.yaml. 
1. Explicitly defining the paths in streams return from setup.php, i.e. 

```
return [
    'environment' => $environment,
    'streams' => [
        'schemes' => [
            'user' => [
                'type' => 'ReadOnlyStream',
                'paths' => [
                    'user/www',
                ]
            ],
            'config' => [
                'type' => 'ReadOnlyStream',
                'paths' => [
                    'user/www/config',
                ]
            ],
// snipped for brevity
```

Result: Grav throws an exception, stack trace:

```
8 Whoops\Exception\ErrorException 
…\system\src\Grav\Common\Uri.php330
7 implode
…\system\src\Grav\Common\Uri.php330
6 Grav\Common\Uri init
…\system\src\Grav\Common\Processors\InitializeProcessor.php35
5 Grav\Common\Processors\InitializeProcessor process
…\system\src\Grav\Common\Grav.php121
4 Grav\Common\Grav Grav\Common\{closure}
…\system\src\Grav\Common\Grav.php383
3 Grav\Common\Grav Grav\Common\{closure}
…\system\src\Grav\Common\Grav.php359
2 call_user_func_array
…\system\src\Grav\Common\Grav.php359
1 Grav\Common\Grav __call
…\system\src\Grav\Common\Grav.php122
0 Grav\Common\Grav process
…\index.php45
```

Doing some debugging, it appears that when Grav/Common/Uri, init() function is called, the second line`$config = $grav['config']` does not return anything (I say 'appears' because my expertise is not with PHP, so maybe I'm missing something).

**Comment by biocarl** [comment]
**I have almost the same scenario now:**

- ( I'm using a shared hosting service (namecheap) where I can have several websites from one hosting account (called Addon-Domains). At the same time they also have to be assigned to a subdomain )
- I´ve read the tutorial for multiside-setup for subdomains. But what I need is just is to parse the complete website name and based on that a different /user folder will be used by grav
- so what I want for the users-folder
-- www.website1.com ->[...]/users/sites/website1
-- www.website2.com ->[...]/users/sites/website2

## My setup.php file
```

<?php
/**
 * Multisite setup for subsites accessible via sub-domains.
 */

use Grav\Common\Utils;

// Get domain name
$environment = str_replace("www.", "", $_SERVER['HTTP_HOST']);

#for com-domains
$environment = str_replace(".com", "", $environment );

// Remove port from HTTP_HOST generated $environment
$environment = strtolower(Utils::substrToString($environment, ':'));
$folder = "sites/{$environment}";

# (this is already working!) when browsing e.g. www.website1.com this prints: user/sites/website1/plugins
echo "user/{$folder}/plugins";

return [
        'environment' => $environment,
        'streams' => [
                'schemes' => [
                        'user' => [
                                'type' => 'ReadOnlyStream',
                                'prefixes' => [
                                        '' => ["user/{$folder}"],
                                ]
                        ]
                ]
        ]
];
```
## My file system
```
ROOT
	TEST
		grav-admin
			index.php
			system
			user
				sites
					website1
						accounts
						config
						data
						pages
						plugins
						themes
					website2
						accounts
						config
						data
						pages
						plugins
						themes
						
			setup.php
			[...]

```
## The error messaging I'm getting in the browser when browing www.website1.com
```

Issues Found
Please Review and Resolve before continuing...

Reload Page

    /ROOT/TEST/grav-admin/user/data does not exist

    /ROOT/TEST/grav-admin/user/pages does not exist

    /ROOT/TEST/grav-admin/user/plugins/error does not exist

    /ROOT/TEST/grav-admin/user/plugins does not exist

    /ROOT/TEST/grav-admin/user/themes does not exist

```

## Notes
- when I'm browsing the website an empty config folder is created in user/sites/
- **question**: so what I really do not understand is why the präfix for user-stream is not changed

**Comment by flaviocopes** [comment]
Hi @biocarl, the "base site" must still exist in the `user/` folder. From your filesystem structure, it seems you moved everything under `user/sites`. Keep all those folders also in `user/`.  That should do it.

**Comment by illycz** [comment]
@flaviocopes This is important information which must be in documentation page, I spend one hour checking what's wrong.

Thanks

**Comment by rhukster** [comment]
Closing to due to inactivity
