### ISSUE TITLE
GRAV - Plugins for Menu and Jumbotron

### ISSUE THREAD

**Issue by AlexL777** [getgrav/grav#970]
Hello developers

one of my blog readers use GRAV CMS and asks with which plugin can create a menu. He also wants to incorporate a Jumbotron and only once do not know how he can realize.

In the menu he would like to display one language as "de" or "en".

Would that be at all possible with the GRAV CMS?

Thanks in advance.

**Comment by rhukster** [comment]
The menu is built from the page/folder structure.  The output of the menu is controlled by the theme.  No plugin is required.

Jumbotron is just a bootstrap CSS class, so yes, if you use the bootstrap CSS framework, you can simply add the class where required.

Grav supports multi language.  Full details here: https://learn.getgrav.org/content/multi-language

-- 
Andy Miller
Sent with Airmail

On August 9, 2016 at 8:57:46 AM, Alexander Liebrecht (notifications@github.com) wrote:

Hello developers

one of my blog readers use GRAV CMS and asks with which plugin can create a menu. He also wants to incorporate a Jumbotron and only once do not know how he can realize.

In the menu he would like to display one language as "de" or "en".

Would that be at all possible with the GRAV CMS?

Thanks in advance.

**Comment by flaviocopes** [comment]
Closing as it's not really an issue, feel free to reply.
