### ISSUE TITLE
Content in codeblock with data-ca-target-id triggers twig exception

### ISSUE THREAD

**Issue by dhaupin** [getgrav/grav#973]
I just started up a little dev blog about tips and whatnot for various platforms. Second article in, i was writing up how to make a wrapper for CS-Cart `cm-dialog` so that images could use them. Upon saving and visiting front end, an exception was thrown:

> An exception has been thrown during the rendering of a template ("DOMDocumentFragment::appendXML(): Entity: line 1: parser error : Specification mandate value for attribute data-ca-targ") in "partials/blog_item.html.twig" at line 53.

The piece of content that triggers it is wrapped in a code block so it shouldnt even be triggering stuff. I tried both tabbing it in and wrapping it with backtick fences:

```
<span class="cm-dialog-opener cm-dialog-auto-size" data-ca-target-id="my_dialog_container">Click me to open</span>
<div id="my_dialog_container" class="cm-dialog hidden">I am the contents of this dialog</div>
```

Specifically, its the `data-ca-target-id` part. Is there something in twig that uses this data asset, or is it just hanging up somewhere or somehow else? Is there a way to escape data style attribs with markup/html?

Appreciate your time into this awesome platform. Thanks

**Comment by dhaupin** [comment]
Oh, this error is thrown in a blog list. The normal page itself renders fine. Thanks.

**Comment by rhukster** [comment]
Can you please provide me a full example of the page's .md file so I try to replicate.

**Comment by dhaupin** [comment]
Sure man. I tried a test with a few things too trying to nail down what triggers it. In the process discovered that apparently partials/blog.html.twig is rendering the html inside code block in a list item summary. So something like this in a code block:

```
<span style="color: green">I should not be green</span>
```

Would render the span literally "i should not be green" as green text, but inside a code block. That seems like a bug for sure, but i dunno about this one: the char limiter can cut off code blocks partially. I think maybe that is what is causing exceptions. I went through all sorts of variations of the md, tried to narrow it as much as i could to a specific attrib, but it eluded me.  Typing out some instructions for a new example, it happened...exception thrown. Tried some more examples, some would work some wouldnt, then tried just an extra long list of data/class/etc attribs to allow summary to get cut off. Bascially any code block attrib that gets cut off in the char limit will cause it. Here is a sample code block to try as a blog post, then visit the block list page:

```
<span data-anything="Blue bottle food truck truffaut echo park poutine keytar pop-up try-hard chillwave squid trust fund mumblecore Selvage lumbersexual keytar polaroid schlitz affogato williamsburg kale chips flexitarian hella cronut paleo synth ramps vice Irony kombucha green juice master cleanse chillwave Art party portland meh brunch farm-to-table hoodie. Green juice kombucha banjo art party post-ironic tattooed pour-over brunch ramps Meggings pitchfork beard bespoke disrupt flexitarian humblebrag lomo vinyl leggings banh mi Before they sold out artisan narwhal hashtag ennui distillery chia lo-fi mlkshk man braid">test</span>
```

Makes sense. What do you think? Could it be because blog list is rendering code blocks, or would that exception occur anytime a codeblock is cut off between some quotes? Im thinking maybe its due to rendering somehow, could be wrong though.

Thanks man!

**Comment by flaviocopes** [comment]
I don't get any issue with that snippet in the text. Is that the whole markdown page content?

**Comment by rhukster** [comment]
Closing to due to inactivity
