### ISSUE TITLE
GPM crashes Windows Subsystem for Linux

### ISSUE THREAD

**Issue by Diegoisawesome** [getgrav/grav#974]
I was trying to get Grav to run on my Windows box through WSL but GPM somehow manages to crash the entire subsystem, forcing me to reboot my computer. It works great up until I try to update anything, whether it be through the CLI or the interface.

**Comment by flaviocopes** [comment]
As far as I know WSL is still beta and it might definitely be a bug in that, as GPM  really is not doing anything strange other than firing a fetch from the server. 

Grav uses 2 separate ways to fetch the data. First, Grav defaults to using `fopen` if `open_basedir` is not set in your PHP settings, and if `allow_url_fopen` is enabled. 
Otherwise, it uses PHP's `curl` (if installed).

So, you might want to try setting `allow_url_fopen` to false and see if it still crashes, to start with.

**Comment by flaviocopes** [comment]
Basically all is happening in here https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/GPM/Response.php

This might or might not be the cause of the issue, just a starting point

**Comment by Diegoisawesome** [comment]
It's not hanging at download, it's hanging at installing. It shows "Installing package..." and then proceeds to take down the entire WSL. I have a symlink pointing html elsewhere, could that be messing with it?

**Comment by rhukster** [comment]
Quite possibly could be the sympathy no causing the problem the Linux subsystem. Can you try without ?

**Comment by rhukster** [comment]
Don't suppose your symlink ends in a '/` slash?  Seems its  a known bug that throws the system into an infinite loop.  Sounds like this is what could take your system down:

https://social.technet.microsoft.com/Forums/en-US/a9d844c7-8907-4e0c-b368-1e7f06da550e/solved-windows-subsystem-for-linux-dropbox-symlink-issue?forum=win10itprogeneral

**Comment by Diegoisawesome** [comment]
Nope, it doesn't end in a slash, I deleted and remade the symlink to make sure. Now running grav without a symlink at all goes past the downloaded issue but causes this:

```
[RuntimeException]
  rename(/var/www/html/cache/tmp/Grav-57acb73ec8cd9/getgrav-grav-plugin-error-0517d09/,/var/www/html/user/plugins/err
  or): No such file or directory
```

Might have to do with the trailing slash on the source directory? Or maybe I just don't understand Linux permissions completely yet.

**Comment by flaviocopes** [comment]
Make sure you follow https://learn.getgrav.org/troubleshooting/permissions

**Comment by jonas-wilhelm** [comment]
Funny, having the same issue here. GPM just kills the entire sub system. But I would assume it is related to WSL, symlinks, php7 or whatnot and not the grav GPM. Let me know if you solved it.

**Comment by Diegoisawesome** [comment]
I wasn't able to solve it, I switched to development on Raspberry Pi which works flawlessly.

**Comment by rhukster** [comment]
I've added a Hacktoberfest tag to see if we can get some help with this as I'm a bit stretched with other things at the moment.
