### ISSUE TITLE
adding changelog link to plugin summary.

### ISSUE THREAD

**Issue by josefstr** [getgrav/grav#977]
It would be great if we could add a link to Changelog in the plugin summary.

> Author: Team Grav - devs@getgrav.org
> Homepage: https://github.com/getgrav/grav-plugin-admin
> Bug Tracker: https://github.com/getgrav/grav-plugin-admin/issues
> Keywords: admin, plugin, manager, panel
> License: MIT
> Description: Adds an advanced administration panel to manage your site
> Readme:   https://github.com/getgrav/grav-plugin-admin/blob/develop/README.md
> ### Changelog: https://github.com/getgrav/grav-plugin-admin/blob/develop/CHANGELOG.md

**Comment by flaviocopes** [comment]
What's the reason why you want to specify it? Grav picks the CHANGELOG.md file by convention.

**Comment by josefstr** [comment]
Before updating a plugin it's mandatory to read the changelog to be aware of the upcoming changes. So right now you have to navigate to the correct changelog file, but it would help probably those out who read it before updating a plugin. This is just a suggestion to improve usability :).

**Comment by rhukster** [comment]
I think this would be useful to see a changelog in the summary.

**Comment by rhukster** [comment]
Something we're working in the near future...
