### ISSUE TITLE
Update Google Analytics Plugin

### ISSUE THREAD

**Issue by escopecz** [getgrav/grav#978]
I would like to add new release of https://github.com/escopecz/grav-ganalytics to the Grav Repository.
Will it be done automatically somehow or do I have to create a new issue for each release? I couldn't find any info about it in the docs.

**Comment by cworreschk** [comment]
It was updated to 1.2.0 ([Grav Plugins](https://getgrav.org/downloads/plugins)). Maybe it's an automatism. :grey_question:

**Comment by flaviocopes** [comment]
It's automated. Every time you make a GitHub release (https://github.com/escopecz/grav-ganalytics/releases), it is picked up by Grav. You just fill the new version in blueprints.yaml and fill the changelog. 

👍

**Comment by escopecz** [comment]
Oh, yeah. It appeared now in my administration finally. Thanks, guys!
