### ISSUE TITLE
Twig process not working on modular pages

### ISSUE THREAD

**Issue by namaless** [getgrav/grav#98]

**Comment by rhukster** [comment]
Can you provide some information and perhaps an example of how to recreate?

**Comment by namaless** [comment]
Simple, you put this in your module page:
---
title: blabla
---
Content **example** {{ page.title }}

inthe config enable twig process ofc.

**Comment by namaless** [comment]
I can confirm the process not working because if i use a plugin function (in the page working fine) in the page module not working.

**Comment by rhukster** [comment]
Twig is not enabled by default in any markdown, so did you enable Twig with:

```
---
process:
  twig: true
---
```

???

**Comment by rhukster** [comment]
This was fixed in Grav 0.9.12
