### ISSUE TITLE
Table Display

### ISSUE THREAD

**Issue by ghostinhershell** [getgrav/grav#980]
Please advise:
Is there any way for me to adjust tables so I can have headers that extend the span of the table? When I try removing vertical bars to extend the space it throws off the whole table. 

Here's an example:
![gravtable](https://cloud.githubusercontent.com/assets/14021469/17624040/f2a49af6-6070-11e6-9c9e-5c4a264d1b91.png)

The blue text is what I want to extend the width of the table. Everything else is fine.
BTW, I love Grav. It's awesome and very easy to use. Thanks for your hard work guys!

-Sarto

**Comment by rhukster** [comment]
Our markdown library 'parsedown' has support for GFM (GitHub flavored markdown), which in turn has basic table support: https://help.github.com/articles/organizing-information-with-tables/

That said, table support is pretty minimal.  Your best option for advanced table layout is to simply use HTML in your .md file to output your table.  If you are having trouble creating that HTML, there are many table generators out there: e.g.:  http://www.tablesgenerator.com/html_tables

**Comment by rhukster** [comment]
Hopefully that resolves your question :)  Please reopen if you need further help.

**Comment by ghostinhershell** [comment]
Thank you so much! I'm going to try that now.
