### ISSUE TITLE
Exception raised by images with lightbox query string

### ISSUE THREAD

**Issue by tdulieu** [getgrav/grav#981]
I think you forgot to add the `$id` parameter to the `html()` methode of the `Grav\Common\Page\Medium\ThumbnailImageMedium.php` file, which raises an exception for images with the `?lightbox` parameter. For example, `[](blue_sky.jpg?lightbox)` produces the error:

Declaration of Grav\Common\Page\Medium\ThumbnailImageMedium::html() should be compatible with Grav\Common\Page\Medium\Medium::html($title = NULL, $alt = NULL, $class = NULL, $id = NULL, $reset = true)

I manually added the $id parameter (lines 58-61 of ThumbnailImageMedium.php), and I don't have the error anymore.
```php
public function html($title = null, $alt = null, $class = null, $id = null, $reset = true)
{
  return $this->bubble('html', [$title, $alt, $class, $id, $reset]);
}
```

**Comment by rhukster** [comment]
I think your are right!  Will get this sorted.

**Comment by rhukster** [comment]
Will get this released asap.

**Comment by rhukster** [comment]
well i'll release this fix as soon as TravisCI sorts out their issues.. Seems it wont build our packages right now :(
