### ISSUE TITLE
Not compiling 

### ISSUE THREAD

**Issue by jonathandion** [getgrav/grav#982]
Hi,

Every time I update the content in the admin platform in a blog item the changes appear on the blog page (/blog/my-title-here) but it doesn't update the blog post preview on my homepage.
When I manually update any code in my theme the new content appears on the homepage.

I put the ```twig_first: true process: twig: true```

code :
```
<ul>
{% for post in page.find('/blog').children.order('date', 'desc').slice(0, 2) %}
    <li class="recent-posts">
        <strong><a href="{{ post.url }}">{{ post.title }}</a></strong>
    </li>
{% endfor %}
</ul>
```
https://learn.getgrav.org/cookbook/twig-recipes#list-the-last-5-recent-blog-posts

**Comment by rhukster** [comment]
Where is this logic contained? Is it in a modular page? If so the content of that modular page is cached by default and will not reprocess the twig until you clear the cache.  The alternative is to disable the cache in the modular page with `cache_enable: false` so it's reprocessed every time.

**Comment by jonathandion** [comment]
@rhukster Wow thanks it's working with ```cache_enable: false``` . 

Thank you so much for the help.
