### ISSUE TITLE
Feature: Allow to use --all-yes (-y) for plugins mass-update

### ISSUE THREAD

**Issue by memtkmcc** [getgrav/grav#985]
It could be very useful for unattended upgrades we would like to include as an option in [BOA support for Grav](https://github.com/omega8cc/boa/issues/790).

Currently it will still ask for confirmation per package, even if you will attempt to run `bin/gpm update -f -y`, like in the example below:

```
The package admin is already installed, overwrite? [y|N] y
Preparing to install Admin Panel [v1.1.4]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!

The package login is already installed, overwrite? [y|N] y
Preparing to install Login [v2.0.1]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!

The package email is already installed, overwrite? [y|N] y
Preparing to install Email [v2.4.3]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!

The package form is already installed, overwrite? [y|N] y
Preparing to install Form [v1.3.2]
  |- Downloading package...   100%
  |- Checking destination...  ok
  |- Installing package...    ok
  '- Success!
```

It is also not immediately clear from [the docs](https://learn.getgrav.org/cli-console/grav-cli-gpm#update), that `--all-yes (-y)` is not expected to work for plugins updates, while it is supported for `install`, `self-upgrade` and even `uninstall`.

**Comment by rhukster** [comment]
Yes, some consistency in options is needed I think.  Thanks for the reminder! 👍

**Comment by rhukster** [comment]
This is fixed for `install` but I know it's also broken in `uninstall` and i'll double check selfupgrade

**Comment by omega8cc** [comment]
Thank you! Would it be possible to do the same for `update` ? I think that it already works for `selfupgrade`, at least it worked for us, while trying to run packages `update` still asked question-per-package.

**Comment by rhukster** [comment]
Yup, will check `update` also.

**Comment by rhukster** [comment]
ok update also works now.

**Comment by omega8cc** [comment]
Amazing! Thank you :)

**Comment by memtkmcc** [comment]
Works like a charm! Thanks :)
