### ISSUE TITLE
Taxonomy diacritics

### ISSUE THREAD

**Issue by krisak** [getgrav/grav#986]
Taxonomies in nonenglish languages without being able to use accented characters are not realy useful. 

For example czech:
exhibition - výstava
food - jídlo
important - důležitý

Its seems that the admin now does not allow use of these accented characters for taxonomy field.

Also how woul one translate those in multilang environment?

**Comment by rhukster** [comment]
I think this is admin specific?  i.e., editing the files directly does not cause problems?

If so, please open this issue on the admin plugin: https://github.com/getgrav/grav-plugin-admin/issues

**Comment by krisak** [comment]
You are right. Seems that it is more problem of admin validation. I have some issues when using it for page collections. I will investigate further, in mean time i will file bug on the grav-admin.

Sorry for all the miss reports. Ive made handful lately.

**Comment by rhukster** [comment]
Closing to due to inactivity
