### ISSUE TITLE
Uncaught exception in Monolog

### ISSUE THREAD

**Issue by jacoblw** [getgrav/grav#987]
Hi,

Having some issues getting a site running.

Scenario: 
Grav originally cloned from GitHub public
Backing up site on production server with `bin/grav`
Loaded backup into a development branch of private git
Deploying with Jenkins to development server

Receiving the following in `/var/log/nginx/error.log`
```
2016/08/17 21:15:31 [error] 27805#27805: *2 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'A stream must either be a resource or a string.' in /opt/www/paw/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:50
Stack trace:
#0 /opt/www/paw/system/src/Grav/Common/Service/LoggerServiceProvider.php(29): Monolog\Handler\StreamHandler->__construct(false, 100)
#1 /opt/www/paw/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Service\LoggerServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav))
#2 /opt/www/paw/system/src/Grav/Common/Errors/Errors.php(51): Pimple\Container->offsetGet('log')
#3 /opt/www/paw/system/src/Grav/Common/Processors/ErrorsProcessor.php(17): Grav\Common\Errors\Errors->resetHandlers()
#4 /opt/www/paw/system/src/Grav/Common/Grav.php(121): Grav\Common\Processors\ErrorsProcessor->process()
#5 /opt/www/paw/system/src/Grav/Common/Grav.php(396): Grav\Common\Grav->Grav\Common\{closure}()
#6 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('_errors" while reading response header from upstream, client: 151.224.1.181, server: servername, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "URL"
```

I've repaired the permission as per your guide
I've removed Pimple and Monolog and reinstalled with composer
I've tried clearing the cache.

Any advice appreciated.

**Comment by rhukster** [comment]
try deleting the entire `vendor/` folder and typing:

```
$ composer install
```

This should get the latest versions of all the vendor libraries

**Comment by jacoblw** [comment]
Unfortunately that didn't fix it.

I can workaround this by doing a fresh clone, `composer install --no-dev -o` (as per the install docs), and copying in the users folder from my backup

Unfortunately this does not help me long term as I'm trying to keep Grav in VCS.

**Comment by rhukster** [comment]
I don't really know what is happening.  The error looks like some out of date libraries, and you fixing it by doing a `composer install` seems to prove that hypothesis. 

However, maybe your `composer.lock` file is out of date because that should install the versions stated in it, and that should work fine.  

Really the best approach is to **only** store the `user/` folder in source control, and keep Grav updated via it's built in updater (either CLI or admin).  That will automatically install the latest vendor folders etc as part of that update procedure.  I've not really heard of anyone having issues like this with that approach.

**Comment by jacoblw** [comment]
Hmm, OK then.

I will continue my testing and take note of just putting `user/` in VCS.

Thanks for getting back to me anyway!

**Comment by isthisthat** [comment]
I fixed this issue by adding back the `logs` folder to the root dir. I had removed it from my repo for obvious reasons and when I did a `git pull` it was gone from the server as well. Adding it back on fixed this issue.

**Comment by nickanderson** [comment]
I had to add the logs folder under the root dir as well in order to fix a site that was rendering blank recently.

**Comment by flaviocopes** [comment]
The default Grav `.gitignore` commits the folder, empty, but avoid including the folder content. So you either used a custom .gitignore, or no .gitignore at all?
