### ISSUE TITLE
URL problem

### ISSUE THREAD

**Issue by Studioartcz** [getgrav/grav#990]
Hi,

i am looking for solution to set base_url for grav. I have same problem as in #783, #625.
Solution can be simple - plugin where i can overload function buildRootPath(). 

Is any option to do this?

**Comment by rhukster** [comment]
You mean like this? https://github.com/getgrav/grav/pull/896

**Comment by Studioartcz** [comment]
Yea! It´s great! Who can confirm this PR?

**Comment by rhukster** [comment]
You can test it out, but there's some issues with the admin plugin that still need to be resolved.

**Comment by Studioartcz** [comment]
Yea i see. Author maybe don't know how fix it..

**Comment by w00fz** [comment]
The feature has been merged, I believe this issue can be now closed?

**Comment by flaviocopes** [comment]
Yep this can be closed
