### ISSUE TITLE
Academic Biblatex support in grav

### ISSUE THREAD

**Issue by reyman** [getgrav/grav#993]
I'm an academic user of Grav. 

Like many scientific i use **[bibtex](https://en.wikipedia.org/wiki/BibTeX)** standard open source format to store scientific references. Like many others i suppose, i'm interested by some plugin for Grav capable to parse this bibtex file and inject the corresponding bibliography at the bottom of page.

You  can find an exemple of working plugin for jekyll here with [jekyll-scholar ](https://github.com/inukshuk/jekyll-scholar)

**Comment by rhukster** [comment]
I'm afraid I don't know anything about bibtex, but it does appear there is a PHP library so a Grav plugin should be possible: https://github.com/audiolabs/bibtexparser

**Comment by OleVik** [comment]
A fairly quick draft, which probably needs case testing, but check out [biblatex-plugin](https://github.com/OleVik/grav-plugin-biblatex).

**Comment by rhukster** [comment]
nice work @OleVik ! Let me know when you are ready to add it to GPM.

**Comment by OleVik** [comment]
@rhukster Updated to [v1.0.0](https://github.com/OleVik/grav-plugin-biblatex/releases/tag/1.0.0), and ready for adding to GPM.

**Comment by reyman** [comment]
Wow :+1: !! This is great! 
Is it also possible to create a link between citation into text `[AUTHORDATE]` to the correct reference `Author, Date, Name of document` at bottom page?

**Comment by rhukster** [comment]
Added to GPM btw @OleVik, should be visible there in about an hour.  Thanks!

**Comment by rhukster** [comment]
Closing this issue.. Thanks again Ole.

**Comment by OleVik** [comment]
@reyman I am working on a [draft](https://github.com/OleVik/grav-plugin-biblatex/issues/2) which integrates with Markdown Extra footnotes rather than an arbitrary bibliography, where used footnotes refer to the specific citations. Yet to find a suitable parser though, as the current back-ends for this are insufficient.
