### ISSUE TITLE
Admin Section Plugin Toggle Not Changing In IE Touch After Clicking It

### ISSUE THREAD

**Issue by Xarcell** [getgrav/grav#994]
In the admin section under plugins, the toggle(blue switch) is not toggling in IE Touch on the windows surface. The settings change, but the toggle does not. In order to see the changes, you click the toggle and the page reloads without the toggle changed, you then have to refresh the page to see the toggle change.

I tested this in Chromium/Ubuntu desktop and it worked fine.

**Comment by rhukster** [comment]
This sounds like an admin issue? Please open here: https://github.com/getgrav/grav-plugin-admin/issues
