### ISSUE TITLE
Naming conflicts .md !

### ISSUE THREAD

**Issue by ash0080** [getgrav/grav#995]
![2016-08-21 10 56 48](https://cloud.githubusercontent.com/assets/2803210/17835094/fb251542-678d-11e6-8fac-27757bb6b066.png)
As the attached img displayed, 
In this case， system mistakenly believes 13.md  is the page file， so require 13.html.twig as a template file, But does not actually exist!

Grav v1.1.3 - Admin v1.1.4

**Comment by rhukster** [comment]
Yes I an see in the code how this could happen. It's never come up before that someone would name a folder 'something.md', but i'll look at sorting it.

**Comment by ash0080** [comment]
Yes, It's not common. The folder names are abbreviation of US states. I use them to generate a sorted list of locations for a custom plugin of mine.

But I think strict distinguishing between folders and files suffixes makes the system robuster.

**Comment by rhukster** [comment]
Should be sorted with the above commit.

**Comment by ash0080** [comment]
I got a error message

"LogicException
The parent constructor was not called: the object is in an invalid state"

**Comment by rhukster** [comment]
i'm not able to replicate this.  What version of PHP? Are you sure you updated the `pages.php` file correctly?

**Comment by ash0080** [comment]
I found the problem，
$pages_found->count() not exsit
PHP7

**Comment by rhukster** [comment]
Oh I fixed that straight away, in the next commit. https://github.com/getgrav/grav/commit/de1d824439b25147f9bf4bc32b6cdb644c29dac2

**Comment by ash0080** [comment]
It works now, thank you
