### ISSUE TITLE
Exclude folder from backup

### ISSUE THREAD

**Issue by julienchazal** [getgrav/grav#996]
Hello
I want to setup my frontend workflow inside Grav (gulp, webpack etc...) so there will be a node_modules folder created by npm.
How can i exclude this folder from backup please ?
Thx

**Comment by rhukster** [comment]
Currently there is no exclude from backup option.  However if you are scripting this, you can simply zip up the Grav folder yourself and exclude anything you wish.  

There is nothing special happening in the backup, other than zipping up the files.

**Comment by nithinkolekar** [comment]
at-least backup folder should be excluded by default as it will increases subsequent backup zip file, by including old backup files in backup folder which is not necessary IMO.
