### ISSUE TITLE
Stronger safe_email filter

### ISSUE THREAD

**Issue by fredrikekelund** [getgrav/grav#998]
I really like the inclusion of the `safe_email` Twig filter! I realize that it's no bullet proof method for protecting from email harvesters, but strengthening it somewhat would still *feel* good.

Maybe taking a cue from WordPress is a good idea here, the [antispambot](https://codex.wordpress.org/Function_Reference/antispambot) function encodes random parts of the address as HTML entities (both decimal encoding and hex encoding) and other parts as their default character representation.

**Comment by rhukster** [comment]
done!
